### PR TITLE
[stable/weave-scope] Add ingress to weave-scope-frontend

### LINKED ISSUE #14049: [stable/weave-scope] support Ingress in weave-scope (weave-scope-frontend)
**Is your feature request related to a problem? Please describe.**
It is sometimes useful to expose `weave-scope` via Ingress, especially in dev/test and non-internet-facing clusters.  Understanding that this is a security risk, this should be disabled by default and include a prominent warning in `NOTES.txt`. 

**Describe the solution you'd like**
Optional (disabled by default) Ingress objects in the `weave-scope-frontend` subchart of `stable/weave-scope`.

**Describe alternatives you've considered**
Current alternative when this is needed is to install an Ingress object outside of helm.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by abhijit838**
#### What this PR does / why we need it:
- This PR adds `Ingress` to `weave-scope-frontend`
- Add ingress.yaml, update values.yaml, README.md and Chart.yaml

#### Which issue this PR fixes
  - fixes #14049

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by fbarl** [comment]
Thanks for your PR @abhijit838!

Taking a quick look at the code, it looks good to me, but I'd like @bboreham or @dholbach to make a final call on `ingress.yaml` as I don't feel sufficiently qualified.

/assign @bboreham
/assign @dholbach

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @abhijit838

**Pull request merged**
