### PR TITLE
[stable/prometheus-operator] move per-component rules to separate files and disable them if scrapes are off

### LINKED ISSUE #8749: [stable/prometheus-operator] Alert rules are created for components even if scrapes are disabled
*Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
*Helm*: 2.10.0
*Kubernetes*: 1.10.6

**Which chart**:
stable/prometheus

**What happened**:
If scraping of a particular Kubernetes components (e.g. API server) is disabled via Helm values, corresponding alert rules are still configured in Prometheus leading to alerts that are constantly firing.

**What you expected to happen**:
If scraping configurations are disabled then alert rules that would rely on those metrics should also be disabled.

**How to reproduce it** (as minimally and precisely as possible):
- Deploy the prometheus operator chart with the below values set:
  ```
  kubeControllerManager:
    enabled: false
  ```
- The below alert rule is still configured in the  `PrometheusRule` resource and will immediately enter an alerting state:
  ```
    - alert: KubeControllerManagerDown
      annotations:
        message: KubeControllerManager has disappeared from Prometheus target discovery.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
      expr: |
        absent(up{job="kube-controller-manager"} == 1)
      for: 15m
      labels:
        severity: critical
  ```

### PR DESCRIPTION
**Pull request by paskal**
#### What this PR does / why we need it:
It moves per-component prometheus rules to separate files and disable them if their scrapes are disabled.
Also it adds .recording.rules to name of all prometheus recording rules blocks for consistency.

#### Which issue this PR fixes:
  - fixes #8749 

#### Special notes for your reviewer:
@vsliouniaev, could you please look into it?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by paskal** [comment]
By the way, https://circleci.com/gh/helm/charts/35456 says what new files tests fail, but I can't figure out what is wrong with them, local tests shows that everything is OK and there are no new variables introduced in these files.

**Comment by gianrubio** [comment]
@paskal I don't think it's a good ideia to split the alert rules in multiple files because It'll make harder to maintain this rules. We're following the rules from [upstream](https://github.com/coreos/prometheus-operator/blob/e703065626a3ee5ee74ef334e63e27afcf9c5ac0/contrib/kube-prometheus/manifests/prometheus-rules.yaml).  We should have a way to automatically sync the rules  from upstream to this chart.

**Comment by paskal** [comment]
Can I propose separation of upstream rules into multiply files, or introduce if statements in existing file without changing anything else?
Also there is an issue with some non-etcd resources located in it's group, I might propose a PR to fix it in upstream, if there is a chance of it's merge.

**Comment by paskal** [comment]
@gianrubio, what do you think?

**Pull request closed without merging**
