### PR TITLE
make sure init.sh works with sh in addition to bash

### PR DESCRIPTION
**Pull request by burnettk**
#### What this PR does / why we need it:

init.sh had been using some syntax that does not work in sh, yet it was being invoked with sh. this makes it more posix compatible, and it works for me now.

#### Special notes for your reviewer:

I didn't know if I should bump the chart version, @ssalaues . UPDATE: ci failed, so i bumped it.

### CODE REVIEW

**Comment by cpanato** [comment]
@burnettk please bump the chart version and sign the DCO

**Comment by ssalaues** [comment]
@burnettk @cpanato I would consider this a duplicate of the open PR I have here:
https://github.com/helm/charts/pull/9428

I also added a helm test to run shell check agains the init script for any future changes.

**Comment by burnettk** [comment]
thanks a ton, @ssalaues . that's super-awesome that you got shellcheck in there. that's what i was using.

let's get that other PR merged so no one else wastes time fixing the same thing. :)

also, in case anyone here knows, why hasn't the redis-ha chart been released to the chart repo since it hit 3.x? i know it's a little scary, but can shipping chart updates to the repo please happen automatically? i love the helm/charts github repo, but it's quite confusing when you try to run the commands in the README.md of each chart (like redis-ha), and then later find out that you were installing a crazy old version.

**Comment by burnettk** [comment]
i'm closing this in light of the other existing PR. feel free to re-open if it's helpful.

**Comment by ssalaues** [comment]
@burnettk Thanks! I appreciate you putting in this PR regardless.

Also I think the chart repo gets updated shortly after merging. Have you tried to do a `helm repo update` ? It's possible that your local index of the charts is referencing the old versions.

**Pull request closed without merging**
