### PR TITLE
Fix k8 1.16 breaking changes for Prometheus chart

### LINKED ISSUE #17735: [stable/prometheus] Chart incompatible with Tiller canary+unreleased
Kubernetes version: 1.16
helm: Canary

`helm install --name prom stable/prometheus --set alertmanager.persistentVolume.storageClass=nfs-client --set=pushgateway.persistentVolume.storageClass=nfs-client --set server.persistentVolume.storageClass=nfs-client --set server.service.type=NodePort --set server.service.nodePort=30005`

Results into:
`Chart incompatible with Tiller canary+unreleased`

It is not possible to downgrade the helm because of https://github.com/helm/helm/issues/6374

### PR DESCRIPTION
**Pull request by HassanHashemi**
This PR is trying to fix #17735 and #17762 
According to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

### CODE REVIEW

**Comment by zanhsieh** [comment]
@HassanHashemi 
Please sign DCO and bump the chart version to the latest one. Thank you.

**Comment by HassanHashemi** [comment]
@zanhsieh Done.

**Comment by HassanHashemi** [comment]
/assign @gianrubio though it seems that the latest tiller version (2.15rc) is not happy with it.
older versions are OK.

**Comment by zanhsieh** [comment]
/retest
@HassanHashemi 
Just a reminder, you might seek @mgoodness or some helm member to force LGTM this PR. @gianrubio , this chart OWNER, seems lost his interest on maintaining helm chart.
If this PR pass, it would be great if you volunteer to become one of this chart OWNERs.

**Comment by HassanHashemi** [comment]
Closing in favor of https://github.com/helm/charts/pull/17268

**Pull request closed without merging**
