### PR TITLE
[stable/coredns] add one missing use of coredns.name

### PR DESCRIPTION
**Pull request by minrk**
Missed in PR #6093, caught by @mrueg after merge

cc @unguiculus

**What this PR does / why we need it**:

makes use of `coredns.name` consistent in `app` label. Some cases used `coredns.fullname` for this label.

**Special notes for your reviewer**:

Same as #6093, just fixing one more case.

### CODE REVIEW

**Review by mrueg — APPROVED** [review]

**Comment by crandles** [comment]
This has a merge conflict now, FYI.

**Comment by huseyinyilmaz** [comment]
Hey, I am trying to install coredns but because of this bug stable branch is not installable right now:

```
ip-192-168-0-102:kubernetes huseyin$ helm install stable/coredns
Error: release wobbly-clownfish failed: Deployment.apps "wobbly-clownfish-coredns" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"wobbly-clownfish-coredns", "k8s-app":"coredns", "release":"wobbly-clownfish"}: `selector` does not match template `labels`
ip-192-168-0-102:kubernetes huseyin$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
ip-192-168-0-102:kubernetes huseyin$
```

Current master is also does not work because selectors and labels do not match:

https://github.com/minrk/charts/blob/79b04b87c86c262a8f79db0a886ad2ddfaa80f25/stable/coredns/templates/deployment.yaml#L23

**Comment by minrk** [comment]
merge conflict resolved

**Comment by minrk** [comment]
cc @seanknox for approval, as recommended by the bot

**Comment by ccatlett2000** [comment]
Bump: this bug currently breaks "stable"/coredns chart install completely

**Comment by asad26** [comment]
Hi,
Can you tell me whether the issue regarding 'selector does not match template labels' has been resolved or not? As I was trying to run coredns on Kubernetes v1.9.7 and getting the similar error:
"**Error:** release coredns failed: Deployment.apps "coredns-coredns" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"coredns-coredns", "release":"coredns"}: `selector` does not match template `labels`"
Thanks

**Comment by ccatlett2000** [comment]
@asad26 it has not

**Comment by targs08** [comment]
Hi
What about this PR? I wish to note, without this change deployment is invalid

**Comment by varun-da** [comment]
Hi! Can this or https://github.com/helm/charts/pull/9303 please be merged in? This is blocking my development. I now have to create a copy of this chart and make the change to install it. The main reason for installing CoreDNS this way is because it is not supported in GKE as of now.

Thanks!!

**Pull request merged**
