### PR TITLE
[stable/datadog] remove useConfigMap, use customAgentConfig for datadog-yaml-configmap

### PR DESCRIPTION
**Pull request by johnpekcan**
#### What this PR does / why we need it:

If you are adding customAgentConfig, it seems counter intuitive to need an additional boolean:
`useConfigMap: true`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by johnpekcan — COMMENTED** [review]
Signed-off-by: John Pekcan johnpekcan@gmail.com

**Review by johnpekcan — COMMENTED** [review]
Signed-off-by: John Pekcan johnpekcan@gmail.com

**Comment by zanhsieh** [comment]
@johnpekcan 
For signing DCO, you need to force push a commit as showing in https://github.com/helm/charts/pull/18053/checks?check_run_id=262878474

**Comment by johnpekcan** [comment]
Hey @zanhsieh, I've updated my PR to remove the `useConfigMap` boolean entirely.
I've had a chance to revisit this, and I don't think it serves a real purpose. 
If you are providing `customAgentConfig` -- you are going to be using a config map.

If you were to set `useConfigMap` to `True` .. you don't really gain anything outside of some generic values that are provided for you. What's the benefit of using a configmap without providing any custom agent params?

Let me know what you think!

**Comment by johnpekcan** [comment]
Also, I've noticed that https://github.com/helm/charts/pull/17702 and this PR are very very similar. Should we group up and try to combine our PR's?  @grumpymatt

**Comment by xlucas** [comment]
@johnpekcan what you are trying to achieve is indeed being discussed in the other PR, so I think we can close this one. Please comment on #17702 if you feel like something is not being addressed.

**Pull request closed without merging**
