### PR TITLE
[stable/nginx-ingress] add instruction to make it work with nlb

### PR DESCRIPTION
**Pull request by KongZ**
#### Is this a new chart
No

#### What this PR does / why we need it:
Add documentation how to make ssl-redirect works with AWS NLB. 

#### Special notes for your reviewer:
There are a lot of unresolved questions on internet asking how to resolve this problem. I did a solution at my work so I would like to make it publicly share with everyone.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
/lgtm
Thanks!

**Comment by roeera** [comment]
Dear @KongZ I must say that I'm really wish to a solution as you described above. the problem is that the Provided Readme is really unclear.
Can you please advise to which section should I need to add the provided yaml you attached, is it ingress deployment / service / configmap etc... it's really unclear and I must say that it's a bit confusing :
```
controller:
  config:
    ssl-redirect: "false" # we use `special` port to control ssl redirection 
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
         return 308 https://$host$request_uri;
      }
  containerPort:
    http: 80
    https: 443
    special: 8000
  service:
    targetPorts:
      http: http
      https: special
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "your-arn"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```
Meanwhile I would appreciate if you could maybe paste a full deployment yaml like can be found in case if tls termination for elb  https://kubernetes.github.io/ingress-nginx/deploy/#tls-termination-in-aws-load-balancer-elb

Thanks and much appreciated

**Comment by KongZ** [comment]
@roeera the content above is a complete value.yaml file with very minimum settings for deploying nginx ingress controller with `http -> https` resolution on AWS NLB.

You can just copy above content into file `value.yaml` and run `helm install -n nginx-ingress stable/nginx-ingress -f value.yaml`

**Comment by roeera** [comment]
@KongZ thanks dear, i'll check that

**Comment by roeera** [comment]
Hi @KongZ unfortunately this is not working for me.
For example, I've jenkins installed on my cluster, and i'm using ingress for it.
When deploying the ingress using the above values, external dns update the route53 record to cluster ip (don't really understand why ?!) instead of nlb cname, and from that moment I can't reach jenkins anymore.
Any idea ?

**Comment by KongZ** [comment]
@roeera helm chart won't update DNS records on route53. I think you have some other tools which causing the trouble. The Cluster IP is private IP, thus your Jenkins is definitely can reach from Internet. You need to update route53 to NLB CNAME.

**Comment by roeera** [comment]
@KongZ  you are right, I've "external dns" component which update route 53 records. the only thing that is problematic, is when i'm checking an ingress that created, I see that the load balancer IP is wrong 

status:
  loadBalancer:
    ingress:
    - ip: 172.21.43.121

this is not the right ip of the load balancer but the pod source ip.
Did you ever see that ?

**Comment by roeera** [comment]
find it ! you need to add the following arg to controller deployment :

            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/nginx-ingress-default-backend
            - --publish-service=$(POD_NAMESPACE)/nginx-ingress-controller
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --configmap=$(POD_NAMESPACE)/nginx-ingress-controller
            - --annotations-prefix=nginx.ingress.kubernetes.io

**Pull request merged**
