### PR TITLE
replace beta workloads/RBAC APIs with GA'd APIs

### PR DESCRIPTION
**Pull request by bacongobbler**
**What this PR does / why we need it**:

RBAC was [GA'd in 1.8](https://kubernetes.io/blog/2017/10/using-rbac-generally-available-18/) and the core workloads API was [GA'd in 1.9](https://kubernetes.io/blog/2018/01/core-workloads-api-ga/)

As per the k8s version support matrix, all Kubernetes releases supported by the community charts now support both `apps/v1` and `rbac.authorization.k8s.io/v1`.

**Special notes for your reviewer**:

I have not individually tested each and every chart if they work with this change; just did a search-and-replace. From initial findings upgrading production charts should not be affected since `helm upgrade` will continue to use the old API version, so this only kicks in on a fresh `helm install`.

TODO:

- [x] bump chart versions

### CODE REVIEW

**Comment by bacongobbler** [comment]
I fixed up the one linting error related to this change, but it looks like the rest of them are unrelated to this PR. Missing fields, maintainer names not linked to github accounts, etc. Please let me know if I should make any extra changes (reverting work against deprecated charts, for example)

**Comment by prydonius** [comment]
@bacongobbler as great as this is, we prefer to prefer have changes in each chart submitted as separate PRs (this way we avoid issues where some charts failing CI prevent other chart updates from going through). Do you think you could separate this out?

**Comment by bacongobbler** [comment]
There are probably > 100 charts changed in this PR. I would be happy to, but that means opening an equally large amount of PRs which is a LOT of noise for the project. Would it be better if I just split it out into separate commits, and if there are charts blocked on this one we can split those out separately?

If y'all want to go forward with the > 100 PR parade, I will likely be unable to keep up with the volume of conversation going through, likely causing large delays on this work. Up to you :)

**Comment by unguiculus** [comment]
@bacongobbler I agree with @prydonius. You'll have a hard time getting a huge PR past CI and will have to merge in upstream changes all the time while trying to fix CI issues. I question if we should really make such a global change anyways. You'd also have to update readme files which usually specify the minimum K8s version. Also, while we officially support the current and previous minor versions, a chart maintainer may decide to support older versions. We do have such charts. In any case, we should be nice and get LGTMs by the chart maintainers and not just force this upon all charts across the board.

**Comment by bacongobbler** [comment]
sounds good. I'm off on vacation until next week but when I'm back, I'll start shipping individual PRs for the charts.

> I question if we should really make such a global change anyways.

I would argue that if someone's willing to put in the work then yes. k8s isn't going to support extensions/v1beta1 forever. ;)

> In any case, we should be nice and get LGTMs by the chart maintainers and not just force this upon all charts across the board.

that sounds more than fair to me.

**Pull request closed without merging**
