### PR TITLE
fixed description: global.postgresql.postgresqlPassword

### PR DESCRIPTION
**Pull request by mmariani**
probably a copy-paste mistake

### CODE REVIEW

**Comment by alemorcuq** [comment]
Thank you very much for fixing this, @mmariani. Can you please bump the Chart version?

Regards,
Alejandro

**Comment by juan131** [comment]
Hi @mmariani just a quick reminder to bump the "patch" version of the chart so we can continue with the merging process

**Comment by mmariani** [comment]
done, thanks

**Comment by juan131** [comment]
Hi @mmariani 

Sorry but we missed this PR. Could you please rebase from master your branch and fix the conflicts? Thanks in advance.

**Comment by mmariani** [comment]
done

**Pull request merged**
