### PR TITLE
[stable/reloader] Bump Version to v0.0.29

### LINKED ISSUE #14573: [stable/reloader] Bump app version to v0.0.29
I would like to see the version of Reloader updated in the charts/stable version to match the tags in https://github.com/stakater/Reloader 

v0.0.25 -> v0.0.29

**Is your feature request related to a problem? Please describe.**
I tried to using the existing stable/reloader chart and can into an issue reloaded a deployment based on specific configmaps
```yaml
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: 'foo-bar'
``` 
**Describe the solution you'd like**
After updating the image to v0.0.29 it worked exactly as I expected

**Describe alternatives you've considered**
I considered using the chart describe in https://github.com/stakater/Reloader

**Additional context**
N/A

**Additional Comments**
Is support for the stable/reloader chart going to be dropped for the chart in https://github.com/stakater/Reloader?

### PR DESCRIPTION
**Pull request by GreenKnight15**
Update app version in README.md, Chart.yaml and in the values.yaml

Signed-off-by: James Ritter <jamesritter15@gmail.com>

#### What this PR does / why we need it:
Update the default tag to use the latest Reloader image

#### Which issue this PR fixes
  - fixes #14573

#### Special notes for your reviewer:
Is support for the stable/reloader chart going to be dropped for the chart in https://github.com/stakater/Reloader?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @GreenKnight15, Thank you for the pull request. The stable/reloader is not actively maintained at the moment and most of the new features are pushed to stakater/reloader but we will try to maintain it as much as possible from now on.

**Comment by faizanahmad055** [comment]
Regarding your PR, it is missing this custom_annotation feature, in which you can override default reloader annotations with your own annotations. 
https://github.com/stakater/Reloader/blob/master/README.md#notes
Here are the changes required that you can add in this PR.
https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml#L43
https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/templates/deployment.yaml#L73

**Comment by GreenKnight15** [comment]
@faizanahmad055 I updated the PR to include the custom_annotations template. Also I up-reved the chart to 1.1.0 with the addition of the custom_annotations template.

**Comment by GreenKnight15** [comment]
@faizanahmad055 I updated the PR to include the changes. I up-reved the minor version with the additions.

**Comment by faizanahmad055** [comment]
Everything looks good now. Just a test case failed. Please check the [ci/circleci: lint-charts](https://circleci.com/gh/helm/charts/79420?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) result, it is related to no new line at the end of values.yaml. Add this line and we are good to go :)
Required

> stable/reloader/values.yaml
>   37:25     error    no new line character at the end of file  (new-line-at-end-of-file)

**Comment by GreenKnight15** [comment]
@faizanahmad055 Worked through the obscure white space issue should be good to go now, thanks for the review

**Pull request merged**
