### PR TITLE
[stable/mcrouter] remove unused values, make domain suffix confgurable

### PR DESCRIPTION
**Pull request by davidkarlsen**
* drop unused values from values.yaml
* make domain suffix configurable - not all clusters use '.cluster.local'

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

---
This change is [Reviewable](https://reviewable.io/reviews/helm/charts/18431)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@jphalip WDYT? I don't see how svc can work as headless if using statefulset?

**Comment by davidkarlsen** [comment]
unstale

**Comment by jphalip** [comment]
@davidkarlsen I'm not sure I follow your question. Statefulsets require a headless service. Also, how does that relate to this PR?

**Comment by davidkarlsen** [comment]
@jphalip disregard that comment - this PR is just cleaning up some unused values and making cluster suffix configurable.

**Comment by jphalip** [comment]
Ok thanks. The PR looks good to me. What do you think about adding the ".svc" part to the suffix variable as well?

**Pull request closed without merging**
