### PR TITLE
stable/datadog Add configMap for datadog.yaml config file

### PR DESCRIPTION
**Pull request by grumpymatt**
#### What this PR does / why we need it:
Added a configMap to provide the datadog.yaml file. This allows the configmap to configure the agent beyond what is available via environment variables.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #
N/A
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by CharlyF** [comment]
Thanks for the contribution @grumpymatt - We are just about to get this one https://github.com/helm/charts/pull/13088 merged, I think it could be interesting to offer a configmap to configure each of the agents. 
I'll discuss with the team tomorrow.

I see that that the linter is failing though, [master is already](https://github.com/helm/charts/blob/master/stable/datadog/Chart.yaml#L3) at `1.30.9`, could you rebase and bump it ?

**Comment by grumpymatt** [comment]
@CharlyF Ok, I rebased and bumped the version. I am using these changes in one of our k8s clusters. We needed to be able to configure the agent to use haproxy as described here:
https://docs.datadoghq.com/agent/proxy/?tab=agentv6#using-haproxy-as-a-proxy

I could not find all the environment variables need to to make it work. So I think this configmap is needed, or more environment variables need to be added to allow equivalent configuration that way.

**Comment by CharlyF** [comment]
@grumpymatt Thanks for your patience, we got the change I was referring to merged so we are going to move forward with your contribution now.
Just so it is not a breaking change however, the default CM we ship should match https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/datadog-kubernetes.yaml but more importantly, it should be behind a config flag.

Any way you can make these changes ? 

Best,
.C

**Comment by grumpymatt** [comment]
What do you want the flag to be?
Put it under the daemonset values?
Maybe like .Values.daemonset.useConfigMap

Then add to values:
```
  ## @param useConfigMap - boolean - optional
  #  Configures a configmap to provide the agent configuration
  #
  # useConfigMap: false
```

**Comment by CharlyF** [comment]
Yes, that's good! Could you just rebase and sign the DCO ? I'll approve thereafter (The lint check should pass when you bump the chart)

**Comment by grumpymatt** [comment]
@CharlyF Ok, I made a couple mistakes while rebasing, hence the multiple pushes, but I think it looks good now?

**Comment by CharlyF** [comment]
Tested on my end, it looks good.
- [x] Without the option (standard case), upgrading the chart is a no-op so it's not breaking.
- [x] With the option, I can see the CM being created and used by the agent.

Mounting:
```
    Mounts:
      /etc/datadog-agent/datadog.yaml from datadog-monitoring-datadog-yaml (rw)
[...]
  datadog-monitoring-datadog-yaml:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      datadog-monitoring-datadog-yaml
    Optional:  false
```
Usage in the lifecycle of the agent:
```
$ kubectl exec -ti datadog-monitoring-j7h4k bash
root@datadog-monitoring-j7h4k:/# agent status
Getting the status from the agent.

[...]

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d
```
And
```
root@datadog-monitoring-j7h4k:/# cat /etc/datadog-agent/datadog.yaml
## Provides autodetected defaults, for kubernetes environments,
## please see datadog.yaml.example for all supported options

# Autodiscovery for Kubernetes
listeners:
  - name: kubelet
config_providers:
  - name: kubelet
    polling: true

# Enable APM by setting the DD_APM_ENABLED envvar to true, or override this configuration
apm_config:
  enabled: false
  apm_non_local_traffic: true

# Use java cgroup memory awareness
jmx_use_cgroup_memory_limit: true
```

**Pull request merged**
