### PR TITLE
[stable/cluster-autoscaler]add extraEnv in default values.yaml

### PR DESCRIPTION
**Pull request by ediezh**
This is for the cluster-autoscaler chart.
#### What this PR does / why we need it:
The extraEnv attribute is missing from the default values.yaml file, this causes issues that user cannot specify extraEnv to the container. This PR add the missing extraEnv to the default values.yaml.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
Hmm, I've not had this issue before, but have no problem with merging this PR. Will you please rebase once #17569 is merged? Thanks!

**Comment by ediezh** [comment]
> Hmm, I've not had this issue before, but have no problem with merging this PR. Will you please rebase once #17569 is merged? Thanks!

Hi @yurrriq rebased the code.

**Comment by yurrriq** [comment]
Thanks!
/ok-to-test
/approve
/lgtm

**Pull request merged**
