### PR TITLE
[incubator/redis-cache] Add ha-proxy to forward traffic to master-onl…

### PR DESCRIPTION
**Pull request by blaw2422**
…y for redis clients that cannot handle read-only slaves

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by blaw2422** [comment]
> @blaw2422 Do you want to update the chart with new image ?

Yes, I've been using the code in the PR from your repo while testing these changes.  If we can push an image to dockerhub, and version bump that in `values.yaml` here, it'd be great.

**Comment by dhilipkumars** [comment]
@blaw2422 Sorry for my poor choice of words, what i meant is feel free to update this chart with the new docker image you had build (and published) with the changes.

**Comment by blaw2422** [comment]
I don't have privileges to push to your repo. Did you want to move it to a
new repo? Seems like we'd push to your docker hub account.

**Comment by dhilipkumars** [comment]
@blaw2422 Yes we could move to a new repo, also feel free to add yourself as one of the maintainer to this chart if you are interested.  (by adding your name and email).   We could always change the image.name in the configuration file later, I would love to do this but unfortunately i cant push anything to open internet for now as i have been re-assigned to secure internal project.  :-(

**Comment by blaw2422** [comment]
@dhilipkumars I have pushed images to a different public repo.  how do we move forward?

**Comment by blaw2422** [comment]
@sameersbn @unguiculus @prydonius , anything I can do to move this forward?

**Comment by dhilipkumars** [comment]
LGTM from myside
cc: @prydonius @unguiculus @sameersbn

**Comment by dhilipkumars** [comment]
@blaw2422 Thanks for the help, yes we need ok-to-test from the reviewer and see if it did not break anything in the CI, If yes it can be merged in my opinion.

**Comment by Globegitter** [comment]
@blaw2422 I just tried out the docker images you published and it seems `invivolink/redis-sentinel-k8s:0.2.1` is not working, it does not contain the `redis_sentinel_k8s` binary but also `mk_redis_slave`. Maybe something just got mixed up during publishing?

**Comment by andromedarabbit** [comment]
This issue is very helpful for many users and should be opened again.

**Pull request closed without merging**
