### PR TITLE
Drone: Update README.md

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Remove duplicate line

### CODE REVIEW

**Comment by christian-roggia** [comment]
Please update the chart version to **0.3.2** in the file *Chart.yaml* and this will be ready to be merged.

**Comment by julianxhokaxhiu** [comment]
Done :)

**Comment by christian-roggia** [comment]
Already merged in https://github.com/kubernetes/charts/pull/3594, this PR can be closed.
Thank you anyway for pointing out that typo in the documentation!

**Comment by julianxhokaxhiu** [comment]
Allright, thank you for merging it!

**Pull request closed without merging**
