### PR TITLE
[stable/spark] Fixes compatibility with 1.16

### PR DESCRIPTION
**Pull request by daixiang0**
To support 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@zanhsieh test pass!

**Comment by zanhsieh** [comment]
@daixiang0 
This chart does not have owner.
@juan131 
Could you help to merge it please? Thank you.
/assign @juan131

**Comment by juan131** [comment]
Hi @daixiang0 @zanhsieh 

I'm not in the OWNERS list of this chart nor in the OWNERS of the whole repository (check https://github.com/helm/charts/blob/master/OWNERS)

I'm just maintainer of the charts maintained by Bitnami.

/unassign @juan131 
/assign @unguiculus @scottrigby

**Comment by daixiang0** [comment]
@unguiculus @scottrigby any input?

**Comment by daixiang0** [comment]
@zanhsieh is there any maintainer for this?

**Comment by zanhsieh** [comment]
@daixiang0 
No owner for this chart so far. Most previous contributors are helm members (@unguiculus @cpanato @prydonius @lachie83 ).

**Comment by daixiang0** [comment]
Happy to be maintainer if possible :)

**Comment by zanhsieh** [comment]
@daixiang0 
You might consider to make another PR to add yourself to OWNERS file. If you do, please let me know. Thanks.

**Comment by daixiang0** [comment]
@scottrigby mind have a look?

**Comment by daixiang0** [comment]
ping @scottrigby

**Pull request merged**
