### PR TITLE
Include namespace in port-forward suggestion

### PR DESCRIPTION
**Pull request by nicorikken**
The commands suggested in the NOTES.txt did not include the namespace.

### CODE REVIEW

**Comment by nicorikken** [comment]
I signed the CLA.

**Comment by nicorikken** [comment]
My CLA should be in now.

**Comment by nicorikken** [comment]
Now my email should definitely be in the commit.

**Comment by sameersbn** [comment]
@nicorikken  good find. thanks for the contribution.

**Comment by thelinuxfoundation** [comment]
bump for CLA check

**Pull request merged**
