### PR TITLE
[stable/fluent-bit] Added support of Decode_Field_As to Regexp parser

### PR DESCRIPTION
**Pull request by baznikin**
#### What this PR does / why we need it:
Regexp parser acceps decoders as well as JSON parser, so I added same support to regexp parser section

@kfox1111 @edsiper @hectorj2f

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@baznikin 
Would you mind DCO and bump chart to latest please? Thank you.

**Comment by baznikin** [comment]
@zanhsieh zanhsieh
I bump chart version, but failed to add DCO. How can I do it? sorry for my ignorance

**Comment by zanhsieh** [comment]
@baznikin 
What error occur when you follow the instruction?
https://github.com/helm/charts/pull/17148/checks?check_run_id=263573770

**Comment by baznikin** [comment]
Aaaaaargh! I suppose I shoud drop this PR do do it again RIGHT was. I shoud change very first commit, so --amend won't work. I tried rebase technique but make it even worse.

**Comment by baznikin** [comment]
New PR:
https://github.com/helm/charts/pull/18128

**Pull request closed without merging**
