### PR TITLE
[stable/graylog] add namespace in NOTES.txt when get secret

### PR DESCRIPTION
**Pull request by imaemo**
Signed-off-by: Peng Tian <tcpln2009@gmail.com>

#### What this PR does / why we need it:
- add --namespace when get secret
- use --decode for base64, because at linux there is not -D option, and it is also working on mac

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by KongZ** [comment]
@scottrigby please increase Chart version

**Comment by imaemo** [comment]
> @scottrigby please increase Chart version

Hi, @KongZ 

I'm sorry this is the first time I create pr for this repo, may I know if it is need to increase chart version when I make some update ?

Thanks.

**Comment by KongZ** [comment]
@imaemo yes, you need to increase chart version every time when you make any changes. You can check the requirement in `checks` detail below in PR.

**Pull request merged**
