### PR TITLE
[traefik] Add a README header for basic auth

### PR DESCRIPTION
**Pull request by reidab**
**What this PR does / why we need it**:

Traefik's basic auth instructions seemed to be incorrectly part of the Clustering section. This adds a new header to the README to differentiate them.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lachie83** [comment]
please bump chart version

**Comment by reidab** [comment]
It doesn't seem like a version bump is appropriate, since this doesn't touch the installed chart at all…?

**Comment by dtomcej** [comment]
@reidab Could you please bump the chart version? Even if the chart files are not touched, the merge will not go through without a chart bump.

Its not ideal, but 🤷‍♂️

**Pull request closed without merging**
