### PR TITLE
stable/jenkins: fix the default value for nodeUsageMode.

### PR DESCRIPTION
**Pull request by RoelVanNyen**
Fix jenkins default nodeUsageMode in the config.xml

If you don`t set this mode you have to first save the global config in order for the slaves to start working.

### CODE REVIEW

**Comment by unguiculus** [comment]
Please fix your CLA.

**Comment by viglesiasce** [comment]
hey @RoelVanNyen! Can you check out the CLA issue. Thanks for this fix!!

**Comment by RoelVanNyen** [comment]
I'm getting my company to get to sign this. I`ll let you know when its fixed.

**Comment by RoelVanNyen** [comment]
CLA should be fixed

**Comment by RoelVanNyen** [comment]
@viglesiasce : Is there something you need me to do on this pr ?

**Comment by lachie83** [comment]
@RoelVanNyen nope. I think that's it.

**Pull request merged**
