### PR TITLE
[stable/bookstack] Add png logo to be displayed in https://hub.helm.sh

### PR DESCRIPTION
**Pull request by carrodher**
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>

#### What this PR does / why we need it:
Add `png` logo to be displayed in https://hub.helm.sh

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lachie83** [comment]
@carrodher can you please bump the chart version

**Comment by cpanato** [comment]
@carrodher ping

**Pull request merged**
