### PR TITLE
[stable/memcached] Remove replicaCount configuration

### PR DESCRIPTION
**Pull request by adoy**
**What this PR does / why we need it**:

The distribution of memcache keys on multi-server configurations
is implemented on the memcache client side. Having more than one memcached
pod will randomly distribute keys on the different instances, without any
guarantee that the same pod will be reused later for the same key. 

This may lead to serious problems like fetching an old cached value because the one cached was done on an other instance behind the svc.

**Which issue this PR fixes** 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by adoy** [comment]
CLA signed

**Comment by olemarkus** [comment]
Thanks for your PR. Instead of rewriting all those resources, could you make it configurable instead? There are several other examples where you can specify `Kind` and the other aspects of your PR.

**Comment by adoy** [comment]
@olemarkus Thanks for the answer. The point in this PR is that you should never use a replicaCount greater than one. If you do, you introduce several issues like inconsistant cache and so on. I don't see any use case where you want to do it. Unless you have one that I will be happy to ear about.

We could make it configurable, but if we do, we allow any user that do not know how memcache work to do a bad configuration that will introduce bugs in their applications.

**Comment by olemarkus** [comment]
It is a pure timed cache where any version of an object is fine as long as it has not reached its TTL. That may in some extreme cases mean reverting to an old version of the object, but that is fine. It is however better to lose 1/3 of the cache rather than 1/1 on a pod restarting.

Another usecase is that you just specify the headless service directly as your memcache server, which means you round robin between cache servers and you get x number of copies of the same object if you regenerate and store on cache miss. But you keep most of your cache on a single pod failure.

**Comment by cdemers** [comment]
@olemarkus Hi! I'm trying really hard to find an example where setting a cache value and then getting a different (older) value when subsequently reading from the cache might be ok, but I can't.  Could you help me with a concrete example?

**Comment by olemarkus** [comment]
If you use memcache for caching rendered pages for example, and you say that as long as the object is active, it is okay to use. I think your use case is only valid if you do not use TTL and you perhaps have some invalidation logic that you rely on.

You can avoid your use case by using consistent hashing though. At least it would be an edge case where you delete a pod, create a new object, add a pod, create a new object and then delete the pod again. All within the TTL of the object.

**Comment by cdemers** [comment]
While I still think that multiple memcached servers behind round robin'ish a proxy is going to create more confusion than actual value, I see your point.
What about having two Helm charts, one for multiple memcached behind a proxy (like the current one), and one for only one or multiple _addressable_ memcached (each one with it's own service)?  It's two pretty different, and incompatible, use cases. Maybe it needs two different charts will help users understand which one is appropriate for their situation?

**Comment by olemarkus** [comment]
Isn't it enough to make ClusterIP and Kind templated?

**Pull request closed without merging**
