### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by justlaputa**
Signed-off-by: Xiao Han <xhan@cogent.co.jp>

#### Which issue this PR fixes
a simple typo fix in the prometheus-operator chart's readme file

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by paskal** [comment]
@justlaputa, could you please bump the chart version by one? Even smallest changes require that.

**Review by paskal — APPROVED** [review]

**Comment by justlaputa** [comment]
sure, will do!

**Comment by paskal** [comment]
Now only thing missing is what you need to signoff your commits, see failed test details for instruction.

**Comment by justlaputa** [comment]
sorry for late, rebased and signed off

**Comment by justlaputa** [comment]
rebased

**Comment by justlaputa** [comment]
hi @paskal can you check and approve this again. Thanks!

**Comment by paskal** [comment]
@vsliouniaev could approve this one.

**Comment by vsliouniaev** [comment]
/lgtm
thanks!

**Comment by justlaputa** [comment]
solved conflit, need lgtm again @vsliouniaev, sorry 😿

**Comment by vsliouniaev** [comment]
thanks @justlaputa !

**Pull request merged**
