### PR TITLE
[stable/graylog] support graylog server logging in JSON

### PR DESCRIPTION
**Pull request by tmeneau**
@KongZ

#### What this PR does / why we need it:
This PR adds support for configuring the graylog pods to log in JSON, specifically one event per line, using the [log4j2 JSONLayout](https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout). This is useful for log aggregation with tools like fluent-bit and fluentd.

#### Special notes for your reviewer:
I know there are some other open PRs for stable/graylog, I'll re-bump the chart version if any of those get merged first. Thanks!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by tmeneau** [comment]
Sorry for the excessive retests! I'm trying to figure out why the `pull-charts-e2e` job is failing. At first glance it looks like a timeout waiting for the `mongodb` and `elasticsearch` clusters to provision, but it's not clear to me why that would be. I noticed some other recent CI checks for unrelated PRs have possibly related errors, but this is my first time looking over the helm charts CI setup so I don't yet have a good sense of that.

**Comment by scottrigby** [comment]
Testing infra was fixed, so last failure shouldn't happen again

**Comment by tmeneau** [comment]
Thank you @scottrigby!

**Pull request merged**
