### PR TITLE
[incubator/kafka] Bump zookeeper helm chart version so all the objects the kafka chart produces adhere to the k8s JSON schema strictly

### PR DESCRIPTION
**Pull request by cademarkegard**
No

#### What this PR does / why we need it:
Bumps the Zookeeper helm chart version so all the objects the Kafka chart produces adhere to the k8s JSON schema strictly. See this PR for details for what was not following the JSON schema strictly: https://github.com/helm/charts/pull/17679

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by Chili-Man — APPROVED** [review]

**Review by jlegrone — APPROVED** [review]
/lgtm

**Pull request merged**
