### PR TITLE
[stable/external-dns] Update README

### PR DESCRIPTION
**Pull request by timurkhafizov**
### Changes
- [x] Update README to list proper arguments
- [x] Remove duplicated arguments from README
- [x] Fix `--aws-zone-type` command line arg

### CODE REVIEW

**Comment by unguiculus** [comment]
FYI: Part of this is already in #2841.

**Comment by timurkhafizov** [comment]
@unguiculus okay, now it is just a README fix then :D

**Comment by unguiculus** [comment]
Thanks, excellent.

**Pull request merged**
