### PR TITLE
[stable/minio] Update README.md - Fix Default Resource Limit Documentation

### PR DESCRIPTION
**Pull request by jabdoa2**
#### Is this a new chart
No
#### What this PR does / why we need it:
CPU limit defaults do not match values.yaml for minio

#### Which issue this PR fixes
Just a doc issue

#### Special notes for your reviewer:
See value here: https://github.com/helm/charts/blob/master/stable/minio/values.yaml#L209

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by nitisht** [comment]
Can you fix the lint and DCO errors @jabdoa2

**Comment by jabdoa2** [comment]
I can fix the DCO. However, I'm not sure about the lint. Do I have to increase the version to change a README?

**Comment by jabdoa2** [comment]
Is there anything I should fix/change?

**Comment by harshavardhana** [comment]
PTAL at the conflicts

**Comment by davidkarlsen** [comment]
This chart has been deprecated: https://github.com/helm/charts/pull/23414 - please submit any PRs to https://github.com/minio/charts

**Pull request closed without merging**
