### PR TITLE
Adding dwardu89 to the owners and maintainers of the spinnaker chart

### LINKED ISSUE #7669: [stable/spinnaker] Add dwardu89 to OWNERS
**Is this a request for help?**:

I'd like to be added as an Owner. I am currently working at ClearScore and we decided to use spinnaker as our cicd solution and believe in building repeatable solutions.
In order to automate spinnaker, its already hard on its own because of every command, and I want to push towards making it as customisable as possible and contribute it back instead of having our own fork.

@linki and @viglesiasce are currently the owners of this.

### PR DESCRIPTION
**Pull request by dwardu89**
**What this PR does / why we need it**: This adds dwardu89 (myself) to the OWNERS chart as I am currently pushing to add improvements to the chart. Also I will contribute to giving more feedback to the chart's pull requests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #7669

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@viglesiasce @lachie83 are you ok with that?

**Comment by lwander** [comment]
LGTM

**Pull request merged**
