### PR TITLE
[stable/nginx-ingress] Configurable default-backend port

### PR DESCRIPTION
**Pull request by LoicMahieu**
**What this PR does / why we need it**:

It add a new value `defaultBackend.port` for being able to configure the port of the default-backend pod.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
What's the reason for this? It would be kind of inconsistent to only make the port of the default backend configurable.

**Comment by LoicMahieu** [comment]
Hi @unguiculus 
Previous to this PR, the default backend port should always be `8080` and so, we can't use an image which expose a arbitrary port.

> It would be kind of inconsistent to only make the port of the default backend configurable.

What do you see that could be configurable?

**Comment by unguiculus** [comment]
You will have to bump the chart version.

**Comment by LoicMahieu** [comment]
@unguiculus Version bumped and README updated. Thanks

**Pull request merged**
