### PR TITLE
[incubator/buzzfeed-sso] Add support for GCP BackendConfig

### PR DESCRIPTION
**Pull request by anas-aso**
#### Is this a new chart
No

#### What this PR does / why we need it:
To be able to configure GCP LB backend service (e.g timeouts) for applications behind buzzfeed-sso Proxy.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by anas-aso** [comment]
@darioblanco @komljen can I have your reviews for this PR please ?

**Comment by anas-aso** [comment]
@darioblanco @komljen any chance in reviewing this PR ?

**Review by darioblanco — APPROVED** [review]
👍   Sorry for the delay

**Comment by darioblanco** [comment]
@anas-aso sorry this one took so long. I am available in the #charts channel in the Kubernetes Slack space if I am not reacting to an assignment. I totally overlooked it.

**Pull request merged**
