### PR TITLE
[incubator/buzzfeed-sso] Allow an initial setup without upstreams

### PR DESCRIPTION
**Pull request by anas-aso**
#### What this PR does / why we need it:
For new setup you might need to deploy the chart without defining any upstreams to give other team the auth infrastructure and the freedom to add their services when needed.

#### Special notes for your reviewer:
If you try to deploy the chart without upstreams, the proxy application will fail with the following error : 
```
{"error":"Invalid configuration:\n  error reading upstream configs file: open /sso/upstream_configs.yml: no such file or directory","level":"error","msg":"error validing options","service":"sso-proxy","time":"2019-06-07 13:36:52.671"}
```
this is expected since the configuration file wasn't created by the config map in that case.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by anas-aso** [comment]
@darioblanco this PR needs `/ok-to-test` from you please :)

**Comment by darioblanco** [comment]
Actually, I think I am not allowed to do an `/ok-to-test` command, I already tried.
For instance:

**Comment by darioblanco** [comment]
I will ask to be added as a trusted collaborator. In the meantime, we will need the help of one in order to merge this.

**Comment by anas-aso** [comment]
@lachie83 maybe you can help here ?

**Comment by komljen** [comment]
@anas-aso Please rebase.

**Comment by anas-aso** [comment]
@komljen I messed up the git history. I will close this PR and open a clean one.

**Pull request closed without merging**
