### PR TITLE
[stable/percona-xtradb-cluster] percona headless service

### PR DESCRIPTION
**Pull request by hoffoo**
#### What this PR does / why we need it:

This is useful when using a proxy such as maxscale because it exposes the pod dns record as such `mysql-pxc-0.mysql-pxc.namespace.svc.cluster.local`. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
/hold
I think you should add second headless service instead of changing existing.

**Comment by hoffoo** [comment]
@maver1ck sounds good, what is a good name? `{{ template "percona-xtradb-cluster.fullname" . }}-headless`

**Comment by maver1ck** [comment]
Yep. I see similar naming in different charts.

**Comment by maver1ck** [comment]
I need to check sth about this change. Will return tomorrow.

**Comment by hoffoo** [comment]
@maver1ck please hold on this, i just realized locally that this version of the chart does not work

after changing the metadata.name I am not able to resolve the `mysql-pxc-0.mysql-pxc` dns record anymore. I will debug

**Comment by hoffoo** [comment]
@maver1ck my bad, so this is happening because we need to upgrade the serviceName in the statefulset here https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/templates/statefulset.yaml#L16 when the service is headless.

Is this what you want? It does not look right to me, can you show me an example of how other charts do this?

**Comment by paulczar** [comment]
There's already a headless service https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/templates/service-repl.yaml   why do we need another ?

**Comment by hoffoo** [comment]
The mysql-pxc-repl service cannot be used to refer to nodes directly via dns (for example `mysql-pxc-0.mysql-pxc-repl.default.svc.cluster.local`)

This is important when configuring proxies like maxscale which require each node to be configured explicitly.

Can you suggest a workaround?

**Comment by hoffoo** [comment]
Hi @paulczar have you had a chance to look into my question?

**Comment by paulczar** [comment]
Yeah i get what you're trying to do now!

/lgtm

**Comment by hoffoo** [comment]
Great! 

@maver1ck can you check out my question here https://github.com/helm/charts/pull/11291#issuecomment-463319466 - I am not totally sure how to do what you are asking (two services pointing at the same ReplicaSet)

**Comment by hoffoo** [comment]
@paulczar could you review again? The current version works as expected and uses a single service (default non-headless). I don't really know how to do what @maver1ck asked for in a clean way

**Pull request merged**
