### PR TITLE
https://github.com/kubernetes-sigs/metrics-server/issues/277

### PR DESCRIPTION
**Pull request by gswallow**
metrics-server pods were in CrashLoopBackoff because they needed to be
able to read configmaps and create subjectaccessreviews.

Signed-off-by: Greg Swallow <gswallow@developertown.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by olemarkus** [comment]
It is unclear to me why metrics-server need any of this. What configuration makes this necessary?

**Comment by gswallow** [comment]
The bug report I found is the title of the pull request.   Also, see https://github.com/kubernetes-sigs/metrics-server/blob/master/deploy/kubernetes/resource-reader.yaml

**Comment by olemarkus** [comment]
The bug report mentiones 
```
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```
Which solves the authentication part of this.

The configmap seems to be needed just because of the e2e test.

We run metrics-server using this chart on kops without metrics-server having any issues.

**Comment by gswallow** [comment]
🤷‍♂ I ran into problems where metrics-server crashlooped on EKS because it couldn't read configmaps and create subjectaccessreviews.  I think it's odd that metrics-server needed to be able to read configmaps, myself.

**Comment by olemarkus** [comment]
We have EKS in the mix too. I'll double check if we are doing something special there.

**Comment by olemarkus** [comment]
metrics-server on EKS is also working without crashloops

**Comment by gswallow** [comment]
Not to be argumentative but why are configmaps in the metrics-server kubernetes SIG's own kubernetes manifests?

https://github.com/kubernetes-sigs/metrics-server/blob/master/deploy/kubernetes/resource-reader.yaml

**Comment by olemarkus** [comment]
No problem :)
The only reference I could find was that it was used by the service account in the e2e test.

**Pull request closed without merging**
