### PR TITLE
[stable/stolon] Fix initialisation of cluster when SSL is disabled

### PR DESCRIPTION
**Pull request by zbikmarc**
This is more hotfix than proper fix but this allows new clusters to be initialised even without SSL enabled.

More details about issue in #18884 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by raqqun** [comment]
@zbikmarc I think that a better solution to express the same think would be to use that :

```
{{- range $key, $value := .Values.clusterSpec }} {{ $key | quote }}: {{ if typeIs "string" $value }} {{ $value | quote }} {{ else }} {{ $value }} {{ end }}, {{- end }} {{ if .Values.tls.enabled }} "pgParameters": {{- $pgParameters := .Values.pgParameters -}} {{ $all := set $pgParameters "ssl" "on" }} {{ $all := set $all "ssl_cert_file" "/certs/serverCrt.crt" }} {{ $all := set $all "ssl_key_file" "/certs/serverKey.key" }} {{ $all := set $all "ssl_ca_file" "/certs/rootCa.crt" }} {{ toJson $all }} {{ else }} "pgParameters": {{ toJson .Values.pgParameters }} {{ end}}
```

It prints the `ssl*` pgparams only if `tls.enabled==true` or it doesn't print anything at all. I used the same on the `create-cluster-job` also. 

With `tls.enabled==false` it prints `{  "pgParameters": {}  }` with `tls.enabled==true` it prints `"pgParameters":    {"max_connections":"1000","ssl":"on","ssl_ca_file":"/certs/rootCa.crt","ssl_cert_file":"/certs/serverCrt.crt","ssl_key_file":"/certs/serverKey.key"}` and it takes also everything in the `pgParameters` list.

**Comment by obeyler** [comment]
@davidkarlsen could you put the /lgtm tag please ?

**Comment by aligthart** [comment]
@lwolf (since you are an owner now....) without this merged the latest helm charts (1.4 and 1.5) are broken. Default install (without tls simply will not come up).

@zbikmarc your pr should indeed fix it but that can no longer be merged due to conflicts. (as a result of my 1.5 change).

**Comment by lwolf** [comment]
thanks for adding me to the thread @aligthart. I'm happy to approve as soon as conflict is resolved.

**Pull request merged**
