### PR TITLE
update nginx-ingress readme with podLabels

### PR DESCRIPTION
**Pull request by r0fls**
updated nginx-ingress readme to include the undocumented `.Values.podLabels`

### CODE REVIEW

**Comment by rjkernick** [comment]
Please increment the version in Chart.yaml

**Comment by rjkernick** [comment]
Please rebase master and resolve merge conflicts

**Comment by rjkernick** [comment]
Please increment the chart version to be greater than the existing version of 0.16.0

**Comment by unguiculus** [comment]
Closing in favor of #6924.

**Pull request closed without merging**
