### PR TITLE
Don't run Zookeeper as a shell subprocess

### PR DESCRIPTION
**Pull request by redbaron**
It improves signal handling, as with this change it is
java process which receives container signals such as SIGTERM

### CODE REVIEW

**Comment by redbaron** [comment]
I signed it

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
LGTM

**Comment by kow3ns** [comment]
/lgtm

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/charts/620#-:-Kctyvq41p0yUy5HG5XC:b-8ks5qa)*

**Comment by kow3ns** [comment]
@k8s-bot e2e test this

**Comment by kow3ns** [comment]
I added the change to a build and ran it against master. It works.

**Comment by mgoodness** [comment]
@redbaron FWIW, I really like this change. Obviously not huge, but shows thoughtfulness about how containerized applications should be run. Kudos and thanks for the contribution!

**Pull request merged**
