### PR TITLE
[stable/ark] add prometheus monitoring

### PR DESCRIPTION
**Pull request by JoschaLaubach**
#### What this PR does / why we need it:

The Heptio Ark pod in the current stable/ark chart offers some Prometheus metrics by default, but they are not exposed so they cannot be used at the moment. This PR exposes the metrics with a Service on a configurable port and also adds a ServiceMonitor CR for Prometheus operator.

#### Special notes for your reviewer:

Monitoring needs to be enabled by setting monitoring.enabled to true.

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by JoschaLaubach** [comment]
@sebastien-prudhomme Thank you for your input. I added your suggestions to the pull request. Please have another look and let me know if there is still something that should be changed.

**Comment by sebastien-prudhomme** [comment]
@JoschaLaubach seems ok for me. Will try to test that on a real Kubernetes cluster.

**Comment by sebastien-prudhomme** [comment]
@JoschaLaubach just finished the test. Ok for me, see no problem on my testing cluster.

You just need now to update the conflicting file and hope someone will officially approve it soon.

**Comment by PabloCastellano** [comment]
Similar PR: https://github.com/helm/charts/pull/9408

**Comment by agolomoodysaada** [comment]
Can we remove the stale flag?

**Comment by JoschaLaubach** [comment]
@agolomoodysaada Your comment should have removed it. At least that would have made sense to me.

**Comment by CarpathianUA** [comment]
Great work, really wait for this to be approved!

**Comment by gianrubio** [comment]
@JoschaLaubach please assign this PR to a helm maintainer

**Comment by PabloCastellano** [comment]
These changes has been merged in 
https://github.com/helm/charts/pull/11068

**Pull request closed without merging**
