### PR TITLE
 [stable/prometheus] Allow extraLabels on Pushgateway Ingress

### PR DESCRIPTION
**Pull request by atze234**
#### What this PR does / why we need it:

Allow extraLabels on Pushgateway Ingress

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by atze234** [comment]
How about a new /lgtm since those Chart Version changes? Want to see this merged ;)

**Pull request closed without merging**
