### PR TITLE
[stable/elasticsearch] replaced bootstrapCommandShell with hooks

### PR DESCRIPTION
**Pull request by fabriziofortino**
The goal of this PR is to rework the post init job (#9067) with a more generic support for [lifecycle hooks](https://github.com/helm/helm/blob/master/docs/charts_hooks.md).

This allows to:

* configure more than one lifecycle job
* run a separate job in different phases of the release lifecycle (specifying different annotations)
* support for different hooks annotations (eg: [argocd hooks](https://github.com/argoproj/argo-cd/blob/master/docs/resource_hooks.md))

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by fabriziofortino** [comment]
@maver1ck what do you think?

**Comment by maver1ck** [comment]
> @maver1ck what do you think?

Looks better than my solution. Great work.

**Comment by fabriziofortino** [comment]
@icereval @rendhalver any thought on this?

**Comment by maorfr** [comment]
/assign @Towmeykaw

can you please take a look at this?

**Comment by Towmeykaw** [comment]
This looks like a nice change. But it's a breaking change for people using the bootstrapShellCommand right? So a major version bump might be necessary. @fabriziofortino

**Comment by fabriziofortino** [comment]
@Towmeykaw you are right. This would be a breaking change. Since this chart has been deprecated in favour of the [Elastic Helm Chart](https://github.com/helm/charts/tree/master/stable/elasticsearch#pre-deprecation-notice) I think it makes more sense to create a separate PR there and close this one.

**Comment by Towmeykaw** [comment]
Sounds good

**Pull request closed without merging**
