### PR TITLE
Gitlab-ce version update & SMTP values

### PR DESCRIPTION
**Pull request by crackmac**
- Updated Gitlab-ce version to v9.2.1
- Added values and updated configmap to pass smtp configuration.

### CODE REVIEW

**Comment by unguiculus** [comment]
@k8s-bot ok to test

**Comment by gtaylor** [comment]
I'm not able to test this right now, but it _looks_ right.

**Comment by crackmac** [comment]
Just seeing that gitlab.com has a slightly different chart and solution for smtp (as well as https). 
https://docs.gitlab.com/ce/install/kubernetes/gitlab_chart.html

Not sure if my updates are relevant anymore.

**Comment by unguiculus** [comment]
@crackmac How would you want to proceed then?

**Comment by unguiculus** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
