### PR TITLE
[stable/velero] add option flag for crd installs for #11637 workaround

### LINKED ISSUE #11637: [stable/ark] Timing problem (CRDs not available immediately)
**Is this a request for help?**:
No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
```
❯ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/ark`

**What happened**:
Deploying `stable/ark` fails with:
```
Error: validation failed: unable to recognize "": no matches for kind "BackupStorageLocation" in version "ark.heptio.com/v1"
```

**What you expected to happen**:
For the deployment to work.

**How to reproduce it** (as minimally and precisely as possible):
Deploy it.

**Anything else we need to know**:
From: https://github.com/heptio/velero/issues/1195
> I think there is sort of a timing problem with the helm chart, where the CRD `backupstoragelocations.ark.heptio.com` is not "ready" before helm tries to create an "instance" of it. Trying to run it usually errors out with:
> 
> `Error: validation failed: unable to recognize "": no matches for kind "BackupStorageLocation" in version "ark.heptio.com/v1"`
> 
> It only works very rarely and randomly. Why we think this is a timing issue is because we get the same behaviour, if we try to deploy ark without helm by simply running the following from a script:
> 
> ```
> kubectl apply -f config/common/00-prereqs.yaml
> kubectl apply -f config/aws/05-ark-backupstoragelocation.yaml
> kubectl apply -f config/aws/06-ark-volumesnapshotlocation.yaml
> kubectl apply -f config/aws/10-deployment.yaml
> kubectl apply -f config/aws/20-restic-daemonset.yaml
> ```
> But if we run the prereqs first/separately and the other stuff with a couple of seconds of delay, it works. Running the prereqs manually and then using the helm charts doesn't work because of the behaviour @Sam123ben describes.
> 
> At least this is our observation and theory. If this can be reproduced, I can also open a separate issue here or in the helm chart's repository. Please advise.

### PR DESCRIPTION
**Pull request by wskulley**
Signed-off-by: Bill Skulley <wskulley@rh.com>

#### What this PR does / why we need it:
Workaround for #11637; creates a flag createCustomResources which defaults to true.  Can be set to false to skip the creation of CRDs, useful for when the CRDs already exist (from a previous helm run, manual prestep, etc).  Marking this as a "fix" though that may be overly generous.

#### Which issue this PR fixes
  - fixes #11637 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@wskulley You might need to have to tweak the CI values to avoid the CRDs.

**Comment by wskulley** [comment]
Looks like these tests are failing due to the CRDs already being present in the test environment `I0430 18:43:20.867] Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "backups.velero.io" already exists`.  This is how the chart behaves as currently released; this PR is to add an optional flag to skip the CRD installs in such a case.

**Comment by davidkarlsen** [comment]
@wskulley See https://github.com/helm/charts/tree/master/test _"Providing Custom Test Values"_

**Comment by wskulley** [comment]
Hm.  Wondering if there are an incomplete set of valero CRDs in the test environment - enough to conflict with a blank default install, but not enough for a createCustomResources=false install to succeed.  
 
https://github.com/helm/charts/pull/12031#issuecomment-484426536

Will continue to ponder but I may be stuck.

**Comment by unguiculus** [comment]
Cleaned up CRDs.

/retest

**Comment by unguiculus** [comment]
CI will always fail. One job creates CRD and a subsequent one fails because they are already there. Manual cleanup doesn't help here.

You should remove `blank-values.yaml`. It's unnecessary and doesn't add any value. We don't need three different tests. All tests should be configured such that either no CRDs are created or that they are cleaned up at the end.

**Comment by unguiculus** [comment]
I didn't want you to remove all ci values. You should have kept all but `blank-values.yaml`. Now I have to clean up manually again.

**Comment by wskulley** [comment]
Apologies. The new value I had added was intended for specifically the case where the CRDs were already present (in my particular case where a previous helm run tries to take actions but the CRDs aren't fully populated and thus it fails... but leaves the CRDs).  So running with the new createCustomResources=false in a clean environment will actually fail.  I am not aware of any method to validate the presence of a CRD before attempting its creation, which would be a much better solution than this rudimentary flag.

I had not intended to tackle the removal of CRDs, but solving that problem will not actually solve the issue this PR was intended to fix.

**Comment by jlegrone** [comment]
cc @nrb

**Comment by wskulley** [comment]
Ok, I think I see that a PR merged after this one was submitted solved the ci crd cleanup, sorry I missed that.  I have re-added the ci values (that @mattfaina had added before) for that.

**Comment by nrb** [comment]
Thanks for tackling this, @wskulley. I'm unsure if this is the correct fix, as upstream we're removing the `00-prereqs.yaml` file that had the CRD definitions. The Velero chart _should_ be waiting for the CRDs to be ready via the `crd-install` hook as of the rename, but I know you mentioned that wasn't working for you.

I'll try with a kops cluster to replicate the the timing problem, but I wasn't able to with KinD or GKE.

**Pull request closed without merging**
