### PR TITLE
[stable/metallb] Add defining priorityClassName to pods

### LINKED ISSUE #20840: [stable/metallb] Add defining priorityClassName to pods
**Is your feature request related to a problem? Please describe.**
Please add ability to define priorityClassName in pods of deployment metallb-controller and daemonset metallb-speaker in values.yaml.
I want it, because if there is insufficient hardware resources at node and if where is not priorityClassName in metallb pod higher whan other services like my apps,  kubernetes can evict metallb pods before evict another non system pods.

**Describe the solution you'd like**
For example, this lines in templates can be added
in controller.yaml
```
{{- if .Values.controller.priorityClassName }}
      priorityClassName: "{{ .Values.controller.priorityClassName }}"
```
in speaker.yaml
```
{{- if .Values.speaker.priorityClassName }}
      priorityClassName: "{{ .Values.controller.priorityClassName }}"
```
and  in values.yaml:
```
controller:
  priorityClassName: "customCriticalClass"
speaker:
  priorityClassName: "customCriticalClass"
```

### PR DESCRIPTION
**Pull request by acceptMyPR**
#### What this PR does / why we need it:
It's adding ability to define priorityClassName in pods of deployment metallb-controller and daemonset metallb-speaker in values.yaml.
Its is needs for  prioritize pods of metallb in relation to other non pods and avoid of evicting metallb pods

#### Which issue this PR fixes
  - fixes #20840 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
I'm not sure why I was assigned to review, but I am not qualified, as I've never used nor heard of this chart.

**Comment by yurrriq** [comment]
My blind feedback would be that the minor version needs a bump, instead of patch, as this adds a feature.

**Comment by evilrussian** [comment]
@davidkarlsen 
@jlegrone 
any updates?

**Comment by evilrussian** [comment]
=(

**Comment by yarelm** [comment]
any chance to re-open this? We need this feature

**Pull request closed without merging**
