### PR TITLE
[stable/kong] Fix broken admin_gui_auth_conf value because of missing quotes

### PR DESCRIPTION
**Pull request by Mattzr**
#### What this PR does / why we need it:
Fix broken admin_gui_auth_conf value because of missing quotes (when enterprise enabled)
#### Which issue this PR fixes
Haven't raised any issue but decided to fix it as I stumbled upon it

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Mattzr** [comment]
@hbagdi @shashiranjan84 the test is failing for reasons not to be related to my changes from the logs. Can you please take a look ?

**Comment by Mattzr** [comment]
Ok found the error, it was hidden from the logs which was showing another error ! fixing it...

**Comment by Mattzr** [comment]
closing to use rebase instead of merge

**Comment by hbagdi** [comment]
Replaced by https://github.com/helm/charts/pull/16408

**Pull request closed without merging**
