### PR TITLE
[stable/kube-state-metrics] add member

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Victor Login <batazor111@gmail.com>

#### Which issue this PR fixes
solve #13867

My PR:
- https://github.com/helm/charts/pull/13995

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks for the PR and offering to support us :).

As per #13867, Could you paste links to previous contributions to `kube-state-metrics` in your PR description?

**Comment by batazor** [comment]
> As per #13867, Could you paste links to previous contributions to `stable/kube-state-metrics` in your PR description?

I have not had time to make a contribution to `stable / kube-state-metrics`

**Pull request closed without merging**
