### PR TITLE
[incubator/haproxytech-haproxy-ingress] add haproxytech haproxy ingress controller

### PR DESCRIPTION
**Pull request by AlecTroemel**
Signed-off-by: alec troemel <alec@mirusresearch.com>

#### What this PR does / why we need it:
This PR adds a chart for the new(ish) official haproxytech ingress controller.
https://github.com/haproxytech/kubernetes-ingress

this chart is heavily based off the current community haproxy ingress controller 
https://github.com/helm/charts/tree/master/incubator/haproxy-ingress

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @AlecTroemel,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by AlecTroemel** [comment]
@maorfr I've created a helm repo/PR at helm hub as recommended. Is that the preferred way to get helm charts out to the community?

**Comment by maorfr** [comment]
it is indeed :)

https://helm.sh/blog/intro-helm-hub/

**Pull request closed without merging**
