### PR TITLE
Bump Pachyderm chart to 0.1.2

### PR DESCRIPTION
**Pull request by jonandernovella**
This includes fixes in the pachd secret.

### CODE REVIEW

**Comment by kminehart** [comment]
Should I close https://github.com/kubernetes/charts/pull/3279?

And are there any extra instructions for a GCP / GKE setup? Where should I mount my service account's key? :)

**Comment by jonandernovella** [comment]
@kminehart Sure. Regarding the GKE/GCP instructions, it's outside the scope of this chart, but I suggest that you take a look at [this](http://docs.pachyderm.io/en/latest/deployment/google_cloud_platform.html)

**Pull request merged**
