### PR TITLE
[stable/traefik] Create toggle for Testframework

### LINKED ISSUE #18782: [stable/traefik] Toggle for Testframework
Currently as it stands the tests/testframework is always deployed with the main traefik chart. This can cause issues when wanting to deploy just Traefik itself.

Proposal to create a value that enables turning the test framework on and off.

### PR DESCRIPTION
**Pull request by kylegoch**
## What this PR does / why we need it:
Add ability to turn the testframework off and on.

Based on: https://github.com/helm/charts/pull/17478

#### Which issue this PR fixes
  - fixes #18782 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by kylegoch** [comment]
@zanhsieh any thoughts on pushing this forward? the chart is not really usable in production environments with the test framework hanging around

**Comment by dtomcej** [comment]
@kylegoch excellent catch with this PR.

**Comment by kylegoch** [comment]
thanks @dtomcej 
Although, hindsight should have made the default to be `false`, sigh.

**Comment by dtomcej** [comment]
@kylegoch You can make a follow up PR if you want, but you need to make sure to update the https://github.com/helm/charts/commit/f655ba842013c64b88998a7ec0bc0e5198b4f61c#diff-ad8e3c0f2661dd3f69758ad06464a150 file to include this to be true, to ensure the tests run on the CI.

**Pull request merged**
