### PR TITLE
[stable/jenkins] Adding sub-path option for scraping

### PR DESCRIPTION
**Pull request by tomerleib**
Signed-off-by: Tomer Leibovich <tomer.leibovich@gmail.com>

#### What this PR does / why we need it:
In cases where Jenkins is available under sub-path, any attempts to scrape `/prometheus` failed with 404. I added a condition, if the ingress is created with sub-path, the scrape path will match it.
In addition, the current configuration creates the ServiceMonitor under the same namespace as the rest of the resources, if Prometheus isn't set to scan additional namespaces, it won't pick up the new ServiceMonitor. 
My PR also address it by adding `serviceMonitorNameSpace` which allows the user to change it according to his setup.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @tomerleib,

thanks for this PR! nice to see you get further involved :)

i must say, i am not a big fan of a chart creating resources in more then a single namespace. especially moving forward to helm 3 where each namespace will contain information about releases in that namespace.

imagine a chart deploying resources to a few namespaces, and then the original namespace is deleted. we will remain with "orphan" resources.

what do you think?

i would love to get @torstenwalter in on this as well.

**Comment by tomerleib** [comment]
I've tested it further.
Closing this PR and submitting a new one.

**Comment by torstenwalter** [comment]
@tomerleib You can always update a PR no need to close and reopen. That would keep the discussion history.

**Pull request closed without merging**
