### PR TITLE
[stable/opa] Add olemarkus and yurrriq as {review,approv}ers

### PR DESCRIPTION
**Pull request by yurrriq**
#### What this PR does / why we need it:
This chart is missing some key features, and we'd (@olemarkus and @yurrriq) like to help maintain it.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
/unassign
ping @tsandall @timothyhinrichs

**Comment by zanhsieh** [comment]
@yurrriq 
Do you mind to resolve conflicting files first please?
stable/opa/Chart.yaml

**Comment by tsandall** [comment]
@yurrriq thanks for your interest in helping maintain the chart. We'd be happy to add you as an approver once you have submitted and reviewed a couple PRs.

**Comment by yurrriq** [comment]
@zanhsieh Thanks for the reminder. I've resolved and forced pushed.

@tsandall To this chart you mean? We've contributed to a few others already.
As is, we can't really use this chart. I'll try to separate out some updates and start sending PRs then.

**Comment by tsandall** [comment]
@yurrriq yeah, if you can submit a couple PRs for this chart (and/or review other PRs against this chart) that would be great.

**Comment by yurrriq** [comment]
@tsandall Sounds good. I've made an attempt to isolate some of the changes we've been using:
- https://github.com/helm/charts/pull/18220
- https://github.com/helm/charts/pull/18221
- https://github.com/helm/charts/pull/18222

**Comment by zanhsieh** [comment]
@yurrriq 
Well, things move fast. Another conflict detected:
stable/opa/Chart.yaml

**Comment by yurrriq** [comment]
rebased on #18220

**Comment by yurrriq** [comment]
resolved the Chart.yaml conflict

**Comment by zanhsieh** [comment]
@tsandall
@timothyhinrichs
Would you guys LGTM to this PR please? Thank you.

**Comment by tsandall** [comment]
@zanhsieh per my comment above we'd like to wait until @yurrriq and others have submitted a few PRs against the chart and hopefully reviewed a couple as well.

**Comment by yurrriq** [comment]
The next time we circle back to OPA, I'll open some more MRs. Closing this for now.

**Pull request closed without merging**
