### PR TITLE
Adding existing secret

### PR DESCRIPTION
**Pull request by cliedeman**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ x] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Can you resolve the existing conflicts before continue?

**Comment by yeahphil** [comment]
Aside from the conflicts, this PR is incomplete. It doesn't change the `secretKeyRef`s in the chart, so rather than allow specifying a secret name, `existingSecret` is effectively just a flag that prevents creating a secret for the password.

That will work, but only if there's a secret with the name the chart would have used if existingSecret wasn't set (i.e. the output of `template "postgresql.fullname" .`).

I put together a PR that respects the value of `existingSecret` here: #9729

**Comment by cliedeman** [comment]
@yeahphil Thanks, I did that when I added this feature originally to the chart forgot to do it here.

**Comment by yeahphil** [comment]
@cliedeman thank you for the original work!

**Pull request closed without merging**
