### PR TITLE
[stable/cockroachdb] Allow TLS secrets for certificates

### PR DESCRIPTION
**Pull request by joachimmathes**
#### What this PR does / why we need it:

This PR allows the usage of k8s TLS secrets as certificate store, which are generated by [cert-manager](https://github.com/jetstack/cert-manager), for example.

It is an extension of the currently unmerged [PR 19755](https://github.com/helm/charts/pull/19755).
Thank you @arturrez for your preparatory work.

If [PR 19755](https://github.com/helm/charts/pull/19755) gets merged first, I will rebase my commit onto current master then.

#### Special notes for your reviewer:

@DuskEagle I decided not to make `tls.crt` and `tls.key` configurable values in `values.yaml`, since the TLS certificate, which cert-manager uses, does not allow to set them anyway. Instead the TLS secrets filenames will be converted to valid cockroachdb filenames by a projected volume mount.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped (but will be raised after PR 19755 has been merged)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DuskEagle** [comment]
Hi @joachimmathes,

Thank you for your contribution. I've tested it out and everything appears good to me. If you're ever interested in contributing additional documentation on using `cert-manager` with CockroachDB, or updating this Helm chart to include a CRDB-compatible certificate manifest, that would also be great :).

**Comment by joachimmathes** [comment]
Hi @DuskEagle,

thanks for merging. I'm sure I will find some time to provide further documentation and manifests concerning a cert-manager setup.

**Pull request merged**
