### PR TITLE
feat(chart): Add baseline Kylo chart

### PR DESCRIPTION
**Pull request by sylus**
**What this PR does / why we need it**: Adds Kylo chart (http://kylo.io)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: N/A

**Special notes for your reviewer**: This is a rather large P.R. I'll admit but Kylo is a rather large application with a lot of moving pieces. ^_^ I now have Kylo (Services / UI) working properly with a default example that runs NiFi, Hive and leverages Spark for Profiling / Validations. I will shortly post a video showcasing this work. Right now values.yaml is optimized to run on a single node which was my testing via docker for mac. I can post subsequent runs / performance benchmarks as needed. Right now my docker containers are owned by me but super happy to help the Kylo folks take ownership or assist them in any way. Several of my containers needed to leverage multi stage builds in order to keep sizes low. I also realize this might be a bit of back and forth but wanted to get this started!

**Youtube Video**: https://www.youtube.com/watch?v=mo_-IxPxTb8

P.S. Kylo itself ships with NiFi which is included in this chart but I pushed a different P.R. here that just contains NiFi itself. https://github.com/kubernetes/charts/pull/5772

## Steps to install (docker for mac)

1. You will need the Hadoop w/Hive modified chart which is available in this P.R. @ https://github.com/kubernetes/charts/pull/6688 :

In the patched stable/hadoop folder:

```sh
helm install --name hadoop --namespace hadoop -f values.yaml .
```

2. Using the Kylo chart included in this P.R.:

```sh
helm install --name kylo \
             --namespace hadoop \
             --set serviceType=NodePort \
             --set ingress.enabled=false \
             -f values.yaml .
```

3. Wait 2-5 mins or until the Kylo UI loads without connection to NiFi issues (use port for kylo-ui)

4. Profit!

## Tasks

- [ ] Use different images instead of different tags
- [ ] Rely on MariaDB Helm chart

## Platform Experts

Just including some platform experts to get their take also:

@fabiannecci
@scottreisdorf
@markap14

## Relevant Links

https://github.com/govcloud/docker-kylo (v0.9.1 branch)
https://github.com/govcloud/docker-hadoop
https://hub.docker.com/r/govcloud/docker-kylo/builds/
https://hub.docker.com/r/govcloud/docker-hadoop/builds/

### CODE REVIEW

**Comment by maver1ck** [comment]
Comment from my side?
Do you think about split this chart and use dependencies ?

**Comment by maorfr** [comment]
you do have many charts!

**Pull request closed without merging**
