### PR TITLE
[stable/postgresql] Add terminationGracePeriodSeconds parameter

### PR DESCRIPTION
**Pull request by desaintmartin**
30 seconds by default might not be enough in some cases.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@desaintmartin Can you fix the mergeconflict? TIA

**Comment by desaintmartin** [comment]
Done!

**Pull request merged**
