### PR TITLE
[stable/gocd] Introduce server and agent pre stop hooks

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#### What this PR does / why we need it:

Introduce server and agent pre stop hooks for users to optionally provide pre stop scripts.
Update agent image to gocd-agent-alpine-3.9

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

I have to still test a failure cases, I think. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
/cc @sheroy 

More info:  https://github.com/gocd/gocd-helm-chart/issues/23

**Comment by sheroy** [comment]
@varshavaradarajan I'm sorry I got to this just now. I tested the prestop hook for the server and agent. It works as expected. The only comment I'd have is that maybe we should mention in the documentation that this will not work for elastic agents and that you have to add a similar hook to an elastic agent pod yaml for it to work. Other than that this looks good. 

\cc: @arvindsv

**Comment by arvindsv** [comment]
Cool. Can merge after the doc change and conflicts are resolved.

**Comment by varshavaradarajan** [comment]
@arvindsv , @sheroy - done with the changes. Please review when you are free. Thank you!

**Pull request merged**
