### PR TITLE
Allow servicename and serviceport to be specified in an ingress host rule

### LINKED ISSUE #12261: Need to be able to provide serviceName and servicePort for Ingress Host Rules
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
Helm Client + Server: v2.12.0-rc.2
Kubernetes Client: v1.10.3
Kubernetes Server: v1.11.8-eks-7c34c0

**Which chart**:
chartmuseum

**What happened**:
Ingress rules use a hard-coded `serviceName` and `servicePort` for all rules. This is fine as a default behavior, but should be overridable by the user.

I am using the aws-alb-ingress-controller which allows you to configure ingress annotations for custom actions to be created on the ALB. One very common use case for these custom actions is to create an SSL redirect. This is currently not possible to achieve with the chartmuseum chart because it requires defining an Ingress Host Rule like so:

```yaml
- host: example.com
  http:
    paths:
    - path: /*
      backend:
        serviceName: ssl-redirect
        servicePort: use-annotation
```

The name serviceName `ssl-redirect` is used to match an alb annotation like this:

```yaml
alb.ingress.kubernetes.io/actions.ssl-redirect: {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
```

**What you expected to happen**:
The user should be able to define host rules like this:
```yaml
hosts:
  - name: example.com
    path: /*
    serviceName: ssl-redirect
    servicePort: use-annotation
  - name: example.com
    path: /*
```
The first rule should use `.serviceName` and `.servicePort` supplied in the rule. The second rule should use the default values, as in the current behavior.

**How to reproduce it** (as minimally and precisely as possible):
Try to define a rule with serviceName and servicePort properties. It doesn't work (yet :))

**Anything else we need to know**:
Here is a full sample of using the AWS ALB Ingress Controller to do SSL redirection.
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/

TIA

### PR DESCRIPTION
**Pull request by mikesigs**
#### What this PR does / why we need it:
Chartmuseum doesn't allow the user to specify their own serviceName and servicePort values when defining an ingress host rule. This PR enables the user to do so.

This is required to support setting up custom actions using the AWS ALB Ingress Controller. One such frequent use-case is [Setting Up an SSL Redirect](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #12261

#### Special notes for your reviewer:
I have tested this chart against my own EKS cluster and it creates the required ingress host rules, and the AWS ALB Ingress Controller creates the custom actions as expected. 

Use the following yaml for testing, if you wish:

```yaml
ingress:
  enabled: true
  labels:
    dns: "route53"

  annotations:
    # If you wish to test the entire ssl-redirect scenario using the AWS ALB Ingress Controller,  set these annotations
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: 'YOUR_CERTIFICATE_ARN'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

  # At a minimum, you can provide two rules to see they both work as expected.
  hosts:
    - name: example.com
      path: /*
      serviceName: ssl-redirect
      servicePort: use-annotation
    - name: example.com
      path: /*
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jdolitsky** [comment]
@mikesigs thank you! can you also update chart version to 2.1.0?

**Comment by jdolitsky** [comment]
@mikesigs one last request - can we update default image tag to `0.8.2` in value.yaml/README as well?

**Comment by mikesigs** [comment]
@jdolitsky I'm not sure what happened with the TOC in the README. Is that going to be an issue? Looks like whitespace to me. But then the comment says not to modify any of those lines. I am pretty sure I did not change that stuff. Nor do I know how to run `doctoc` to update it.

**Comment by jdolitsky** [comment]
@mikesigs hm im not sure.. can we just copy over from github UI the old content for that section?

**Comment by jdolitsky** [comment]
the TOC looks good to me :)
/lgtm

**Comment by mikesigs** [comment]
@jdolitsky It turns out the TOC was auto-updated by a VS Code extension called Markdown All In One.
The only thing it added were links to the main header and the TOC header itself. It's just a bit weird because the TOC comes after those headings. I have a fix for it. You can end a heading with `<!-- omit in toc -->` to have it omitted from the TOC.

This PR is already merged though. Do you want a new PR to fix this? Or should I just forget about it?

**Comment by jdolitsky** [comment]
@mikesigs I think it looks fine. We can forget about it unless its bugging you :) Would rather a PR with some major readme changes if anything

**Pull request merged**
