### PR TITLE
Support use of predefined configmap, upgrade locust and python versions

### LINKED ISSUE #2560: [stable/locust] Chart not useful in current form - should there be a usefulness requirement for stable charts?
I'll prefix this by saying that I might have missed something really obvious about Helm, but I've been reading docs and searching extensively for the past few hours and I've come up empty.

I guess this is part of a broader discussion around the purpose of this repo; namely, should charts be useful?

**Is this a request for help?**: No, unless I'm missing something...

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request? Open discussion?

**Which chart**: Specifically `stable/locust` but I've seen a similar issue with other charts.

The chart installs and runs with the default, bundled configuration but is absolutely useless because the behaviour of the packaged application is defined by files that are built into a ConfigMap and installed as part of the chart, when the whole point of the application is for the user to define their own behaviour via Python.

The only options that I can find for making the chart useful are:

- Maintain my own copy of the chart in a fork of this repo, which seems to defeat the purpose of Helm as a package manager,
- Create a subchart which removes and replaces the configMap with my own version, which seems hacky and could mess with upgrades, or
- Remove and replace the configMap on the cluster after installation which will **definitely** break after upgrades.

In my opinion, charts that make it to "stable" status should not just run, but also be able to support useful baseline functionality of the applications they install - otherwise what's the point?

Again, if I've missed something obvious, I apologise and would welcome a pointer in the right direction. :)

### PR DESCRIPTION
**Pull request by haugene**
Signed-off-by: Kristian Haugene <kristian.haugene@greenbird.com>

#### What this PR does / why we need it:
Adds support for referring to an existing configmap containing Locust scripts. This makes it possible to add your own scripts without forking the Chart - but simply setting a configmap name in values.yaml.

In addition to this it's upgrading Locust from v. 0.7.5 (June 2016) to v. 0.9.0 (September 2018) and the underlying python-alpine image from 2.7 to 3.7.

#### Which issue this PR fixes

  - fixes #2560

#### Special notes for your reviewer:
The new Docker image is built from the previous honestbee fork of the original GCP example. The honestbee image repo does not seem to be maintained anymore. We're using Locust actively in our organization and will keep up with version updates, issues, improvements and pull-requests to the new image.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @so0k

@haugene Since you added yourself as a maintainer: You'd be expected to actively maintain the chart, review PRs, triage issues etc. It this what you are up for? @so0k: Are you ok with this?

**Comment by haugene** [comment]
Hi @unguiculus. Yes, that was what I was thinking. At least help out as far as I can. I can't promise "daily commitment" for years to come, but I did get approval within my organisation for spending time contributing to open-source projects before adding myself. So I'm prepared to follow up.

That being said I'll of course just rebase myself out of it if @so0k prefers.

**Comment by so0k** [comment]
I think I haven't had the time to maintain this so if you want to take over, @haugene - please feel free to do so

**Comment by haugene** [comment]
@so0k Great. I know how it is with these tasks. Not easy to find the time. Hopefully I can help out. Is this good to go then @unguiculus?

**Comment by haugene** [comment]
@unguiculus or @prydonius up for merging?

**Pull request merged**
