### PR TITLE
[stable/redis] Fix ServiceMonitor to not leak.

### PR DESCRIPTION
**Pull request by desaintmartin**
Previous definition allowed Prometheus to scrape all redis in all namespaces.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @carrodher @juan131 @prydonius @sameersbn @tompizmor

**Comment by davidkarlsen** [comment]
@desaintmartin can you fix the mergeconflict?

**Pull request merged**
