### PR TITLE
[incubator/elasticsearch] Optionally expose http

### PR DESCRIPTION
**Pull request by jslusher**
Declares a value for exposing port 9200 for master and data pods and
sets it to `false`. This allows for downstream users to open
elasticsearch http port for monitoring or other purposes. We use datadog for our
monitoring and the agent pod expects port 9200 to be open so that it can
get and send metrics at the container level.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by sameersbn** [comment]
@jslusher I think `master.expose_http` is too vague. I think something clearer like `master.expose_metrics` would be more appropriate. If we could make the metrics completely configurable then I would suggest something like `master.metrics.enabled`, `master.metrics.exposed` and so on.

**Comment by jslusher** [comment]
@sameersbn In my mind `master.exposeHttp` is more accurate since all that's happening by setting it to `true` is that the http port is exposed. Our metrics-collecting solution requires that port 9200 be opened, but others might need port 9200 to be exposed for other reasons. This PR exposes the full API port, which could have several different use-cases, so my thinking is that the value should be specific to the port that is being opened and not to our specific use case. Perhaps something to do with exposing the API might be a good compromise? I'm open to suggestions!

**Comment by sameersbn** [comment]
Oh yes, you're right. I thought port 9200 was only for the metrics endpoint. 
Could you rebase the PR?

**Pull request merged**
