### PR TITLE
allowing passing multiple annotations through helm cli

### PR DESCRIPTION
**Pull request by sermilrod**
#### What this PR does / why we need it:
Allow passing several annotations through helm cli.
Previously when trying to pass more than 1 the template did not render properly the arguments throwing an error like this:
```
Error: release nginx-ingress-controller failed: Service in version "v1" cannot be handled as a Service: v1.Service.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|nternal":true},"labe|..., bigger context ...|e.beta.kubernetes.io/aws-load-balancer-internal":true},"labels":{"app":"nginx-ingress","chart":"ngin|...
```

#### Special notes for your reviewer:

I have changed the way to render the annotations based on stable/traefik helm chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@sermilrod can you please rebase and fix the conflict?

**Comment by sermilrod** [comment]
@cpanato sorry for the late response. Done!

**Comment by cpanato** [comment]
thanks @sermilrod

**Pull request merged**
