### PR TITLE
incubator/kube-downscaler - fix a regression about namespaces

### PR DESCRIPTION
**Pull request by patrungel**
#### Is this a new chart
No

#### What this PR does / why we need it:
The present fixes a regression where invalid option value 'namespaces' is passed to the tool
and overly generous permissions are granted over namespaces.

#### Special notes for your reviewer:
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Rowern** [comment]
@discreet was the one to introduce `namespaces` to the clusterrole, maybe he can justify its use (if I understand this is to support this: https://github.com/hjacobs/kube-downscaler/tree/14720bd5bf62fbc425e11f34bb7c3ed438c579fa#namespace-defaults (I might be wrong).
Either way, it does look like the perms allocated to this role are too wide, see https://github.com/hjacobs/kube-downscaler/blob/14720bd5bf62fbc425e11f34bb7c3ed438c579fa/deploy/rbac.yaml for the list of necessary verbs (get, watch, list) on namespaces.
If you change your PR to have a clusterrole closer to the one above I'm ok for approval.

**Comment by patrungel** [comment]
Read-only access to namespaces is needed for the tool to operate cluster-wide (the default mode), https://github.com/hjacobs/kube-downscaler/blob/14720bd5bf62fbc425e11f34bb7c3ed438c579fa/deploy/rbac.yaml#L13 

In 0.4.0 of the chart namespaces were made managed resources and thus the chart granted full access (or none whatsoever) over namespaces, which is indeed to wide. 
My change effectively restores the read-only access to namespaces.

**Comment by discreet** [comment]
IIRC I didn't modify the clusterrole resources from what was there before, I just removed them from being hardcoded and into the values. This might have opened up the scope beyond what I intended however and if that is the case I am 100% for rectifying this.

From what I can see this PR leaves my changes in tact while addresses the RBAC permissions. I do see that I did have an oversight with my configuration that would pass `namespaces` to the cli; thank you for catching my oversight @patrungel.

I am 100% for this PR provided tests pass.

**Comment by patrungel** [comment]
Thanks @discreet,
Alas, we're looking at a legitimate failure.
I could see a false positive test post-merge yesterday:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/22929/pull-charts-e2e/1277972756259934210/
Container exited non-zero  but the overall test passed.

I added another commit to correct this; it's about quotes around the arguments which are okay when in a shell but broke the command when passed via yaml.

**Review by Pluies — APPROVED** [review]
Thank you for this @patrungel, and thanks for the comments @discreet !

/lgtm

**Pull request merged**
