### PR TITLE
Fix kubernetes.io link

### PR DESCRIPTION
**Pull request by wclr**

### CODE REVIEW

**Comment by enisoc** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@whitecolor can you sign the CLA?

**Comment by wclr** [comment]
I think I did. Should I take some actions after?

**Comment by prydonius** [comment]
@whitecolor looks like it's not being picked up. Make sure you followed the instructions in https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ and that you're commit author email matches. There's a link at the bottom of that FAQ if you're having issues.

**Comment by mgoodness** [comment]
@whitecolor are you able to resolve this? Please let us know by 4 March, or we'll close the PR.

**Comment by wclr** [comment]
No, not able.

**Pull request closed without merging**
