### PR TITLE
[stable/consul] Fixes compatibility with 1.16

### PR DESCRIPTION
**Pull request by null93**
Signed-off-by: Rafael Grigorian <me@raffi.io>

#### What this PR does / why we need it:

Makes stable/consul compatible with 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by null93** [comment]
@davidkarlsen anyway we can merge this :)

**Comment by zanhsieh** [comment]
@null93 @sameersbn @lachie83 
It's hard to merge. This chart does not have OWNERS file.

**Pull request closed without merging**
