### PR TITLE
Chomp whitespaces in secrets.yaml

### PR DESCRIPTION
**Pull request by gorozcoh**
Chomp whitespaces.

### CODE REVIEW

**Comment by gorozcoh** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
Would like to understand a little more about what this is breaking. Can you please add some context?

**Comment by gorozcoh** [comment]
This PR do not require testing. It's only small typos.

**Comment by lachie83** [comment]
Understood. Is the current configuration breaking something because this same formatting is in a number of charts.

**Comment by gorozcoh** [comment]
Chart is installed without issues. It is only about improving the quality of the code.
Command helm install --dry-run --debug before PR:
```
  ---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lolling-kudu-postgresql
  labels:
    app: lolling-kudu-postgresql
    chart: "postgresql-0.2.0"
    release: "lolling-kudu"
    heritage: "Tiller"
type: Opaque
data:
  
  postgres-password: "T0tnUkxPb00zRA=="
  
---
```

same command after PR:
```
---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wandering-liger-postgres
  labels:
    app: wandering-liger-postgres
    chart: "postgresql-0.2.0"
    release: "wandering-liger"
    heritage: "Tiller"
type: Opaque
data:
  postgres-password: "NGRjYzJER25iSA=="
---
```

**Comment by lachie83** [comment]
Perfect @gorozcoh Thank you very much for the clarification.  I agree.

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by gorozcoh** [comment]
Added commits to correct error in template deployment.yaml chart stable/wordpress: Referenced secrets with name {{ template "mariadb.fullname" . }} for environment variable MARIADB_PASSWORD do no exists.

**Comment by viglesiasce** [comment]
@gorozcoh those are provided when the helm dep up command is run. It brings in the mariadb chart. Also please keep PRs to fixing a single thing. Previously we could have merged this but now it all has to be redone.

**Comment by viglesiasce** [comment]
Closing this as changes need to be resubmitted.

**Pull request closed without merging**
