### PR TITLE
typo

### PR DESCRIPTION
**Pull request by bartvanhoey**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by thomasliddledba — APPROVED** [review]
/lgtm

**Comment by winromulus** [comment]
@bartvanhoey - please bump the chart version and sign your commits so we can retest this.
Thanks.

**Review by thomasliddledba — APPROVED** [review]
/lgtm

**Pull request merged**
