### PR TITLE
[stable/grafana] Bump sidecar version

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
Bumps kiwigrid k8s-sidecar to 0.0.11, please see https://github.com/kiwigrid/k8s-sidecar/releases/tag/0.0.11 for more rdetails.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
@naseemkullah, you would need to bump the chart version. Thanks!

**Comment by naseemkullah** [comment]
@maorfr Done! Thanks.

**Pull request merged**
