### PR TITLE
[incubator/vault] Use single consul token for vault and consul agent

### PR DESCRIPTION
**Pull request by cyrilledec**
Signed-off-by: Cyrille <cyrille@omise.co>

#### What this PR does / why we need it:
Allow consul agent to use the same token than vault if defined (`Values.vault.config.storage.consul.token`).
When ACLs are enabled in Consul, Consul agents need a token for agent's internal operations (https://www.consul.io/docs/acl/acl-system.html). Without specifying a token the anonymous token will be used (anonymous doesn't have any right by default) and internal operations will failed like : 
```
[WARN] agent: Coordinate update blocked by ACLs
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by dmyerscough** [comment]
@unguiculus would you be able to review the above changes?

**Comment by maorfr** [comment]
hey @cyrilledec,

i have a question:
why did you choose to implement this different from the [gossip-key](https://github.com/helm/charts/blob/3fff2f25f634e3945d977551edd67cc0901d870e/incubator/vault/templates/deployment.yaml#L123) implementation?

is the consul token not sensitive information that should be mounted from a secret?

**Comment by cyrilledec** [comment]
@maorfr gossip-key is used for encryption between consul-agent and consul-server. Token is used as an authentication key when ACLs are enabled on server side.

**Comment by maorfr** [comment]
Right. My question was really more technical.
Isn't `.Values.vault.config.storage.consul.token` sensitive? And maybe should be mounted from a secret instead of through values.yaml? Similarly to gossip-key.

**Comment by cyrilledec** [comment]
The idea is to re-use the same token already used by vault container (is defined) and which should be in value file under `vault.config.storage.consul`

**Comment by cyrilledec** [comment]
If we want to use a secret for this token then we will have to change the way to configure vault (not using configmap anymore)

**Pull request merged**
