### PR TITLE
[stable/datadog] Support node selector for daemon set

### PR DESCRIPTION
**Pull request by cknowles**
Several other charts support this in a similar way.

### CODE REVIEW

**Comment by cknowles** [comment]
Just rebased this one after conflict on master.

**Comment by timstoop** [comment]
@hkaj @irabinovitch @xvello What do you think?
It looks fine to me.

**Review by hkaj — CHANGES_REQUESTED** [review]
hey, sorry for the delay @c-knowles 
this looks good to me, could you update the version to 0.13.0 before we merge please? (I set it to 0.12.3 by mistake yesterday)

**Comment by cknowles** [comment]
@hkaj done

**Review by hkaj — APPROVED** [review]

**Pull request merged**
