### PR TITLE
[stable/wordpress] Typo fix in README

### PR DESCRIPTION
**Pull request by chrisatomix**
**What this PR does / why we need it**:
Change ```persitence``` to ```persistence``` in WordPress chart README.md

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
N/A

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by chrisatomix** [comment]
CLA signed

/assign @carrodher

**Comment by juan131** [comment]
Hi @chrisatomix 

Could you please bump the patch version of the chart? It's mandatory even for minor bug fixes like this one.

**Comment by chrisatomix** [comment]
@juan131 Thanks for letting me know, I've just updated my PR

**Pull request merged**
