### PR TITLE
[stable/grafana] Add adminUser and adminPassword to README config

### PR DESCRIPTION
**Pull request by jwilander**
**What this PR does / why we need it**: I had to look at values.yaml and templates/secret.yaml to discover how to set these. It'd be nice to just see them in the README.

@rtluckie

### CODE REVIEW

**Comment by jwilander** [comment]
~~I signed the CLA but it's not updating the build check~~ and the build is failing because I didn't bump the version number which does not make sense for a simple README update.

**Comment by chainlink** [comment]
Can we get this merged in? Chart currently broken when not specifying an `adminPassword`

**Comment by davidkarlsen** [comment]
@jwilander can you merge in master to fix the conflict?

**Comment by chainlink** [comment]
Still waiting on this to get merged.

**Comment by jwilander** [comment]
Apologies, I'll merge master when I get a chance.

**Comment by davidkarlsen** [comment]
@jwilander version in Chart.yaml needs a bump to be mergable

**Comment by chainlink** [comment]
This still needs to be merged

**Pull request closed without merging**
