### PR TITLE
grammar edits to datadog helm docs!

### PR DESCRIPTION
**Pull request by cswatt**
#### Is this a new chart
No.
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Grammar edits to the Datadog Helm chart docs.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by ruthnaebeck — APPROVED** [review]
👍 for docs

**Review by cohenyair — APPROVED** [review]

**Comment by vboulineau** [comment]
@cswatt LGTM. But you'll need to sign DCO and bump chart version.

**Pull request closed without merging**
