### PR TITLE
[incubator/patroni] Bump etcd chart version

### PR DESCRIPTION
**Pull request by miles-**
The new version of the etcd chart allows `storageClass` to be explicitly set.

### CODE REVIEW

**Comment by unguiculus** [comment]
Needs a chart version bump as well.

**Comment by miles-** [comment]
@unguiculus Chart version bumped.

**Comment by miles-** [comment]
@unguiculus Not sure why that test failed. Do we need to retest?

**Comment by miles-** [comment]
@unguiculus thanks!

**Pull request merged**
