### PR TITLE
[stable/traefik]: fix domainsList variable name in readme

### PR DESCRIPTION
**Pull request by Art3mK**
#### What this PR does / why we need it:

There is typo for `domainsList` variable in README.md. This PR fixes it.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by Art3mK** [comment]
this PR doesn't change anything other than README.md, not sure if chart version bump is required, or what's wrong with `pull-charts-e2e` test

**Comment by dtomcej** [comment]
The helm repo will not allow PRs without a chart bump, even if it is a readme file change.

the version bump is mandatory.

**Comment by Art3mK** [comment]
I've bumped chart version

**Pull request merged**
