### PR TITLE
[incubator/kube-downscaler] Add support for SecurityContext

### PR DESCRIPTION
**Pull request by Pluies**
#### Is this a new chart

No

#### What this PR does / why we need it:

Add support for SecurityContext in the kube-downscaler.

We have a fairly strict PodSecurityPolicy in place, so this will help us comply and run the downscaler!

Also fixes README as values were missing and/or outdated.

#### Which issue this PR fixes

n/a

#### Special notes for your reviewer:

none

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
/ok-to-test


@Pluies 
If this PR pass, would you mind to become one of this chart owners ?
https://github.com/helm/charts/issues/13869

**Comment by Pluies** [comment]
@zanhsieh sure thing, I'm ok becoming one of the chart's owners :)

**Comment by zanhsieh** [comment]
> @zanhsieh sure thing, I'm ok becoming one of the chart's owners :)

@Pluies
Open another PR for OWNERS file modification, add yourself as one of the chart owners, bump the chart version, and let's go from there. 👍

**Pull request merged**
