### PR TITLE
[stable/prometheus-operator] Remove unused role/rolebinding from prometheus templates

### PR DESCRIPTION
**Pull request by mwieczorek**
Signed-off-by: mwieczorek <wieczorek-michal@wp.pl>

#### What this PR does / why we need it:
In https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/role-config.yaml there a role with `-prometheus-config` suffix created but then in https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rolebinding-config.yaml#L12 role with `-prometheus` suffix is added.

If I understand it correctly it should be like in this PR. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
This chart was imported from a different repository - so there are likely some artifacts left. If this configuration hasn't been working since the beginning, maybe it's better to simply remove it?
What do you think?

**Comment by mwieczorek** [comment]
@vsliouniaev True, I updated the PR (removed templates for role and rolebinding)

**Comment by mwieczorek** [comment]
@gianrubio @anothertobi Could you take a look? Thanks.

**Pull request merged**
