### PR TITLE
[stable/cluster-autoscaler ]Added DaemonSet and UpdateStrategy

### PR DESCRIPTION
**Pull request by hingstarne**
/cc @mgoodness
/cc @yurrriq

#### Is this a new chart
no

#### What this PR does / why we need it:
For having the cluster-autoscaler properly running on all master nodes we needed DaemonSets.
A DaemonSet needs the UpdateStrategy for being easily upgraded.
Our use case is that the only autoscaling group is allowed to be zero-sized. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ibelikov** [comment]
@hingstarne you can schedule cluster-autoscaler on all master nodes (with 1 replica per node) with a combination of affinity and tolerations, something like this:
`affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: "app.kubernetes.io/name"
          operator: In
          values:
          - cluster-autoscaler
      topologyKey: "kubernetes.io/hostname"

tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Exists
`

Daemonset becomes necessary when the number of your master nodes is dynamically changing, which I assume is not really the case.

Having the option to specify the update strategy is a welcome addition though, I was just about to make the same PR.

**Comment by yurrriq** [comment]
:+1: to `updateStrategy`. I'm not sure I understand the use case for DaemonSet, and even less so for Both. Could you please clarify? Also, why is it that you need CAS running on _all_ masters?

**Comment by ibelikov** [comment]
Went ahead with a separate PR for updateStrategy only: https://github.com/helm/charts/pull/20801

**Pull request closed without merging**
