### PR TITLE
[stable/minio] Add test chart

### PR DESCRIPTION
**Pull request by gabibbo97**
**What this PR does / why we need it**:
This adds a test phase

### CODE REVIEW

**Comment by cpanato** [comment]
@gabibbo97 you need to bump the chart version. can you please do that? thanks

**Comment by gabibbo97** [comment]
@cpanato bumped chart version to 1.6.2

**Comment by cpanato** [comment]
hey @gabibbo97, you need to rebase and fix the conflicts

**Comment by gabibbo97** [comment]
@cpanato Rebased
Now tests pass :1st_place_medal:

**Comment by cpanato** [comment]
Ping @davidkarlsen

**Comment by cpanato** [comment]
@gabibbo97 need to rebase and bump the chart again

**Pull request closed without merging**
