### PR TITLE
[stable/metrics-server] Bugfix / Add Missing Permissions

### PR DESCRIPTION
**Pull request by bryantbiggs**
#### What this PR does / why we need it:
- Add namespace resource to cluster role resource permission and nodes resource to aggregated reader cluster role permissions. These are required for scraping metrics per 
	- https://github.com/kubernetes-incubator/metrics-server/blob/2614b8aa74e12eefb3e9aeb2d9c15c1748f7e95b/deploy/1.8%2B/resource-reader.yaml#L13
	- https://github.com/kubernetes-incubator/metrics-server/blob/2614b8aa74e12eefb3e9aeb2d9c15c1748f7e95b/deploy/1.8%2B/aggregated-metrics-reader.yaml#L11
- Correct typo mis-spelling
- Whitespace formatting, remove trailing blank lines 
- Bump image version to latest at 0.3.3

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by PierluigiLenociAkelius** [comment]
This PR is partially duplicated here: https://github.com/helm/charts/pull/16606 (without the metrics server version bump), partially here: https://github.com/helm/charts/pull/16060 (with metrics server version bump and half of the permissions) and partially here: https://github.com/helm/charts/pull/15919 (only with metrics server version bump).

**Comment by PierluigiLenociAkelius** [comment]
If this PR build properly we can close all other PR related to metrics-server.

**Comment by PierluigiLenociAkelius** [comment]
@bryantbiggs could you please include in your PR this typo fix?
https://github.com/helm/charts/blob/4d456a565594f7fb072a220aece0b358e80403ec/stable/metrics-server/values.yaml#L26 "netwok" -> "network"

**Comment by PierluigiLenociAkelius** [comment]
@bryantbiggs thank you too. I hope the test build is successful because the bump from 0.3.2 to 0.3.3 created some problems in my PR: https://github.com/helm/charts/pull/16060
For that reason I splitted the PR: https://github.com/helm/charts/pull/16606

**Comment by PierluigiLenociAkelius** [comment]
@bryantbiggs as expected... the metrics-server bump break the build. :(

**Comment by olemarkus** [comment]
I am curious if this is related to the bump or if this is due to a change in the test platform. It looks like it struggles to remove the deployment, but I don't see a diff locally. Would be good if https://github.com/helm/charts/pull/16514 was in a good state.

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus and what to fix this https://github.com/helm/charts/pull/16606?

**Comment by PierluigiLenociAkelius** [comment]
Finally the permissions are fixed. https://github.com/helm/charts/pull/16654
@bryantbiggs now this is outdated. I'll create a new PR in order to have a PR to update the metrics-server version.

**Comment by PierluigiLenociAkelius** [comment]
Created https://github.com/helm/charts/pull/16656

**Comment by PierluigiLenociAkelius** [comment]
I'm ready also to create a PR for whitespace formatting and to remove trailing blank lines as suggested by @bryantbiggs 
https://github.com/PierluigiLenociAkelius/charts/commit/a8bbdcbf2d9b29ba049dd11a369453669429dd66

**Pull request closed without merging**
