### PR TITLE
Add condition for service clusterIP

### PR DESCRIPTION
**Pull request by hariharan16s**
Signed-off-by: Hariharan Subramanian <harsubra@adobe.com>

#### What this PR does / why we need it:

Add condition on the service clusterIP so it didn't set the clusterIP if one wasn't defined.

#### Why we need it:
First time when the service is created without clusterIP defined a clusterIP is set. The next time we run the yaml file it will fail as the clusterIP is empty and it tries to set a clusterIP

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by hariharan16s** [comment]
@davidkarlsen @prydonius Can you please review when you get a chance? Thanks!

**Review by lachie83 — APPROVED** [review]

**Comment by lachie83** [comment]
Thanks for the contrib @hariharan16s

**Comment by hariharan16s** [comment]
> Thanks for the contrib @hariharan16s

Thanks for the review @lachie83

**Comment by mbelang** [comment]
I didn't change anything to my values and after update I got: `Error: UPGRADE FAILED: Service "cluster-autoscaler-aws-cluster-autoscaler" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

@hariharan16s 
The patch doesn't seem backward compatible.

**Comment by hariharan16s** [comment]
@mbelang : This was the same error I got before making the change. 

Are you defining a ClusterIP in values? Not sure in your case how in the previous versions the clusterIP is being tracked as we had to define the clusterIP in values to get rid of the error.

Basically first time when the service is created without clusterIP defined, a clusterIP was set. The next time we run the yaml file it will fail as the clusterIP is empty and it tries to set a clusterIP which it should not.

**Comment by mbelang** [comment]
@hariharan16s 
> Are you defining a ClusterIP in values? Not sure in your case how in the previous versions the clusterIP is being tracked as we had to define the clusterIP in values to get rid of the error.
No

I do understand the purpose of the fix but it is odd that I do not have the problem on 0.12.0 and I have it on 0.12.1.

here is my value file:
```
autoDiscovery:
  clusterName: my-cluster-name

cloudProvider: aws
awsRegion: us-east-1

extraArgs:
  v: 1

podAnnotations:
  iam.amazonaws.com/role: cluster-autoscaler
  scheduler.alpha.kubernetes.io/critical-pod: ''

rbac:
  create: true

sslCertPath: "/etc/ssl/certs/bundle.crt"
sslCertHostPath: "/etc/ssl/certs/bundle.crt"
```

**Comment by hariharan16s** [comment]
@mbelang : Looks like this just appears to be issue with an upgrade with clusterIP not defined and not a fresh install. Let me try to replicate this and get back to you.

**Comment by echoboomer** [comment]
Seeing a similar issue:
`Service "cluster-autoscaler-aws-cluster-autoscaler" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

I did alter my values file to contain a service section to try and get around this based on the requirements that were added to the chart for the service manifest in the last update:
```yaml
service:
  clusterIP: ""
```

This doesn't really change anything. If I `helm get` the release, I see this for the `service` yaml:
```yaml
# Source: cluster-autoscaler/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.12.1
    heritage: Tiller
    release: cluster-autoscaler
  name: cluster-autoscaler-aws-cluster-autoscaler
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      name: http
  selector:
    app: aws-cluster-autoscaler
    release: cluster-autoscaler
  type: "ClusterIP"
```
You can see in this case there's just no `spec.clusterIP` entry at all even though the default values file seems to include `clusterIP: ""` and my local values file explicitly adds it anyway.

**Comment by echoboomer** [comment]
@hariharan16s is the solution for now just to delete the release and redeploy?

**Comment by echoboomer** [comment]
Was there ever any movement on this? I'd like to get this working properly.

**Comment by hariharan16s** [comment]
@echoboomer : For now try to delete the service and the next time you apply the yaml with clusterIP: "" it should work as expected.

**Comment by hobti01** [comment]
This is a long standing issue in other charts and still has no resolution https://github.com/helm/charts/issues/9227

It was reverted from nginx-ingress because the conditional creates a deployment that cannot be upgraded: https://github.com/helm/charts/pull/10993

This change should be reverted because it prevents upgrades.

**Pull request merged**
