### PR TITLE
upgrade alertmanager, prometheus, configmap-reload and node-exporter

### PR DESCRIPTION
**Pull request by davidkarlsen**
**Special notes for your reviewer**:

What are the guidelines for chart versioning, maybe the node-exporter upgrade should mean bumping the minor version?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/charts/6276)

### CODE REVIEW

**Review by gianrubio — CHANGES_REQUESTED** [review]
please review the Readme.md replacing the image tag

**Comment by davidkarlsen** [comment]
@gianrubio ok now?

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Pull request merged**
