### PR TITLE
[stable/grafana] Add quotes to the value of the labels

### PR DESCRIPTION
**Pull request by wgaldino**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - Kubernetes doesn't auto convert integer to string, this means that the label values must be quoted.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

Signed-off-by: Wesley Galdino <wesleygaldino@gmail.com>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@wgaldino
Could you sign as above please?

**Comment by wgaldino** [comment]
@zanhsieh 
Is it required to bump the chart version for a change in the README?

**Comment by zanhsieh** [comment]
> @zanhsieh
> Is it required to bump the chart version for a change in the README?

No.

**Pull request closed without merging**
