### PR TITLE
Bumped kube-slack version and added annotations

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by PierluigiLenociAkelius** [comment]
@mattfarina @jstriebel @monotek @viglesiasce @maorfr @rimusz

**Comment by maorfr** [comment]
/assign
/ok-to-test

Lets bump the chart version to 1.0.0 please

**Pull request merged**
