### PR TITLE
Fix default container image

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by unguiculus** [comment]
Please rebase.

**Comment by yanns** [comment]
@unguiculus done.

**Comment by unguiculus** [comment]
I'm not sure if we should do this change. In any case, the Markdown for the link is not correct.

**Comment by yanns** [comment]
I will fix the format.
Why are you not sure we should fix the link?
The base image was changed by https://github.com/kubernetes/charts/pull/1794, but the README not.

**Comment by unguiculus** [comment]
The image is mentioned in the configuration table. I think that's sufficient. It wasn't mentioned separately before, either.

**Comment by yanns** [comment]
Then we should at least delete the wrong link, shouldn't we?

**Comment by unguiculus** [comment]
Yes, of course. Silly me. I guess I was blind and didn't realize the link was wrong.

**Comment by mattfarina** [comment]
@yanns Can you please increase the chart version. Any change causes it to increment.

**Comment by unguiculus** [comment]
I think we had a little misunderstanding. I put the text back in and adapted it a little bit and fixed the link. I guess this is what you wanted, right?

**Comment by yanns** [comment]
@unguiculus yep, that was my initial intention.
I must admit I have been surprised by the reactions of such a little change ;)

**Pull request merged**
