### PR TITLE
[stable/sentry] Support loadBalancerSourceRanges on Service template

### PR DESCRIPTION
**Pull request by wvidana**
#### What this PR does / why we need it:
Support loadBalancerSourceRanges on Service template.

Needed for people that want to restrict network access to their on-prem Sentry.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by wvidana** [comment]
On a second thought maybe we don't want the variable default in here https://github.com/helm/charts/pull/13665/files#diff-14be7de4a18363a90b2ca1ecb9dfe3f4R108

That way we can avoid the whole block if not provided (backwards compatible)

**Comment by wvidana** [comment]
@sameersbn can you please review?

**Comment by wvidana** [comment]
@davidkarlsen Looks like I need approval again. Seems that 2 other sentry PRs where merged today and I had to bump the chart version twice

**Comment by wvidana** [comment]
ping @davidkarlsen

**Comment by okgolove** [comment]
@wvidana hello! Thank you for the PR.
First of all, I don't see a modified documentation (as and default values for `loadBalancerSourceRanges`).

Could you fix it?

**Comment by wvidana** [comment]
sorry about that @okgolove , completely forgot about it, good catch!

**Pull request merged**
