### PR TITLE
fix installation instruction for stable/efs-provisioner

### PR DESCRIPTION
**Pull request by darshanime**
**What this PR does / why we need it**:
Fixes installation instruction for stable/efs-provisioner

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@darshanime See the checks section - can you:
1) bump the chart version
2) sign-off your commits?

TIA

**Comment by darshanime** [comment]
@davidkarlsen can this be merged?

**Comment by davidkarlsen** [comment]
@darshanime See failing test: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/helm_charts/7603/pull-charts-e2e/15180/ - can you do something about that?
I know the documentation change is not related to that - but OTOS we need running OK tests.

**Pull request closed without merging**
