### PR TITLE
[stable/graylog] Add sidecar support, privileged access and load balance across various inputs

### PR DESCRIPTION
**Pull request by cbarton**
#### What this PR does / why we need it:
* In order to reduce the cost of hosting with extra IP's for load balancers, open up the `service.inputPorts` value to open those ports and put them behind the web load balancer
* In order to run sidecars alongside the graylog-server container, add `sidecarContainers` to host that definition. This is useful for mounting a different backend for archives (like GCS via FUSE).
* In order to support privileged actions (like mounting a FUSE volume), allow `graylog.privileged` to control if the server is running as privileged.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by KongZ** [comment]
@cbarton we already have `.Values.graylog.input.tcp` for input ports. What is purpose of introducing a new one?

**Comment by cbarton** [comment]
The current setting will create two new services (if using tcp and udp). This means that if you expose those services as a loss balancer (internal or external), they will require their own dns entry and get assigned an external ip, which costs more but does not really provide much benefit. The services load balance to the same sts, so this allows the option to expose those inputs under the same dns/ip address.

**Comment by KongZ** [comment]
@cbarton i think this is not gonna work in most cases cause the Graylog service usually is HTTP load balancer since you need to access the Graylog web interface. But Inputs usually need layer 4 load balancer since it is syslog except you are using GELF which is also HTTP.

I don't want to make chart too complicate (having two input ports locations)

May be you can just use `.Values.graylog.service.ports` and set single default port to `9000`
```
ports:
  {{- range .Values.graylog.service.ports }}
    - containerPort: {{ .port }}
       name: {{ .name}}
       protocol: {{ .protocol }}
   {{- end }}
```

And let's your use case for advanced users who understand the Graylog architecture and Kubernetes to add ports on single Load Balancer by themselves.

**Comment by cbarton** [comment]
@KongZ sure, I've renamed `inputPorts` to `ports` if that reads better to you. I left the 9000 port as default on the sts, as arrays aren't merged if you chose to override the ports and we had a default value.

**Pull request merged**
