### PR TITLE
[incubator/vault] Remove liveness probe

### PR DESCRIPTION
**Pull request by lawliet89**
#### What this PR does / why we need it:

The readiness probe already runs throughout the lifetime of the pod and
will also signal the health of the pod.

Also, using a "bare" TCP probe results in many error messages from Vault
in the form of `2019-02-11T08:51:56.900Z [INFO] http: TLS handshake
error from 172.19.9.1:49392: EOF`

There is probably no point in duplicating the same `httpGet` check in
the liveness probe too.

This is an alternative to https://github.com/helm/charts/pull/9462. I don't see a point in doing the exact same check.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by jbialy — APPROVED** [review]

**Comment by lawliet89** [comment]
Can I get someone to review this please? I've fixed the conflicts.

**Comment by cpanato** [comment]
the readiness probe run just one to let k8s know it is ready to accept traffic and liveness run during the lifetime of the pod to let the scheduler it is alive otherwise kill the pod.
i did not get why do you want to remove the liveness check

**Comment by lawliet89** [comment]
Doesn't the readiness probe run for the entire lifetime of the pod? At least that's what the docs says. 

In any case I could always add it back but it shouldn't be a bare tcp connection because it causes a lot of noise in the logs wrt bad tcp handshakes.

**Comment by cpanato** [comment]
@lawliet89 my understanding
liveness: `"Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations"` from https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command

readiness `"Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don’t want to kill the application, but you don’t want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services."` from https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes

**Comment by jbialy** [comment]
@lawliet89 I just got my PR merged (https://github.com/helm/charts/pull/9462) that should address the tcp handshake errors by hitting the the vault health endpoint using http/https.

**Comment by lawliet89** [comment]
Great. Then I guess there's no need for this PR.

**Comment by mkozjak** [comment]
@jbialy please check my review here: https://github.com/helm/charts/pull/9462#pullrequestreview-212561183
With 0.15.0 the pod gets in a CrashLoopBackOff, since k8s is killing it based on 503 and it shouldn't be, because that error means that Vault is in a sealed state.

**Pull request closed without merging**
