### PR TITLE
[incubator/rundeck] add pvc, sa, common labels, upgrade app and chart version

### LINKED ISSUE #22881: incubator/rundeck unable to install, invalid type field in configmaps.
Unable to install rundeck from 'incubator/rundeck' chart.

**Version of Helm and Kubernetes**:
helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
incubator/rundeck

**What happened**:
```
helm install rdh incubator/rundeck -n rd-helm
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap): unknown field "type" in io.k8s.api.core.v1.ConfigMap
```

Unable to install helm chart due to the field "type" in a config map. I think this field type only applies to secrets not configmaps.

**How to reproduce it** (as minimally and precisely as possible):
Just try to install the rundeck chart, or just run kubectl apply on the generated config map...which should produce the error.

### PR DESCRIPTION
**Pull request by jonathan-mothership**
FYI, PR template has broken link:
https://github.com/helm/helm/tree/master/docs/chart_best_practices
------------

#### What this PR does / why we need it:
* Upgrades the default app version set in `Chart.yaml` and default values file from 3.0.16 to 3.2.7
* Adds more flexibility around launching persistent storage for Rundeck by optionally adding a PVC or by specifying an existing claim. The existing AWS EBS volume configuration option remains but is moved under the `persistence` key in configuration values. Minor version bump of the `Chart.yaml` as a result.
* Adds support for using a k8s service account for the Rundeck pod. This opens up support for AWS IRSA as well as better supporting granting Rundeck k8s API access. Chart users may now optionally specify an externally-managed service account.
* Support for specifying annotations to add to the deployment and the rollout strategy used, which allows for specifying `Recreate` when using a PVC so the old deployment can first spin down and detach from the volume before the new one comes up. The `replicaCount` key is thus under this new parent `deployment` key.
* Adds a healthcheck handler to the default nginx config (with disabled logging) so that the readiness and liveness probes for that container don't depend on Rundeck's availability, since it's got its own probes.
* Replaced the many label set copies with a label helper template to dry things up a bit.
* Adds a configmap checksum annotation to restart the Rundeck pod in the event helm pushes new environment configuration.
* Fixes an issue in the `deployment.yaml` template where the `nginx` pod's probes are mistakenly nested under the container port keys: https://github.com/helm/charts/blob/master/incubator/rundeck/templates/deployment.yaml#L38-L51
* Removes copy-pasta references to "Riemann" in the readme.

#### Which issue this PR fixes
Overall QoL fixes for operating Rundeck in K8s using this chart.

Fixes: https://github.com/helm/charts/issues/22881

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by tkorrapati1 — APPROVED** [review]
LGTM!

**Comment by jonathan-mothership** [comment]
gtg @dwardu89?

**Pull request merged**
