### PR TITLE
[stable/grafana] Update to grafana 6.5.0

### PR DESCRIPTION
**Pull request by jperlope**
#### Which issue this PR fixes
see: https://grafana.com/docs/guides/whats-new-in-v6-5/ 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@vsliouniaev 
Could you help me to debug the e2e test please? It seems to required me to kubectl logs to get the detail.

**Comment by vsliouniaev** [comment]
CI prints the pod logs you'd get from `kubectl logs`. The test pod is on line 780: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/19123/pull-charts-e2e/1199983257391730688/#1:build-log.txt%3A780

```
I1128 09:29:55.982] ------------------------------------------------------------------------------------------------------------------------
I1128 09:29:55.983] ==> Logs of container grafana-zepjpkevdg-test
I1128 09:29:55.983] ------------------------------------------------------------------------------------------------------------------------
I1128 09:29:56.338] 1..1
I1128 09:29:56.339] not ok 1 Test Health
I1128 09:29:56.339] # (in test file /tests/run.sh, line 4)
I1128 09:29:56.339] #   `code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)' failed with status 7
```

The test appears to load a configmap and run test scripts:
```
run.sh: |-
    @test "Test Health" {
      url="http://tst-grafana/api/health"

      code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)
      [ "$code" == "200" ]
    }
```

However, that's the same endpoint that the grafana pod has configured for its own liveness probe and that pod is alerady runnning according to line 235: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/19123/pull-charts-e2e/1199983257391730688/#1:build-log.txt%3A235
```
I1128 09:29:44.744] ==> v1/Pod(related)
I1128 09:29:44.745] NAME                                 READY  STATUS   RESTARTS  AGE
I1128 09:29:44.745] grafana-zepjpkevdg-649b77cd4f-dz28j  1/1    Running  0         8s
```

Feels like a flaky test and I'm a bit puzzled why it's necessary at all, since it doesn't accomplish anything that  one of these two commands don't do:
```
helm upgrade <release> stable/grafana --install --atomic
helm upgrade <release> stable/grafana --install --wait
```

**Pull request merged**
