### PR TITLE
[stable/prometheus-mysql-exporter] Collector flags config

### PR DESCRIPTION
**Pull request by estahn**
#### What this PR does / why we need it:

This is adding the configuration of collector flags to the chart.

#### Which issue this PR fixes

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by estahn** [comment]
This was sort of implemented in #8900 but never finished.

**Comment by estahn** [comment]
@sameersbn @paulczar @davidkarlsen What's the turn-around on the reviews?

**Comment by estahn** [comment]
@sameersbn @paulczar @davidkarlsen ping.

**Comment by estahn** [comment]
@sameersbn @paulczar @davidkarlsen I can take over maintainership if that is the issue.

**Comment by paulczar** [comment]
haha typo in maintainers key.  fixed that this should pass now.

/lgtm

**Pull request merged**
