### PR TITLE
[stable/mongodb] Enable MongoDB exporter for prometheus.io

### PR DESCRIPTION
**Pull request by grebois**
https://github.com/dcu/mongodb_exporter

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @grebois 

As you may check on other charts, the usual approach when using exporter is to create a different deployment for the exporter. 

For instance, take a look to https://github.com/kubernetes/charts/tree/master/stable/redis/templates . You can find there a **metrics-deployment.yaml** and a **metrics-svc.yaml**. We used them to define the Prometheus exporter and, this way, we can don't need to scale it when scaling the MongoDB pods. As you may find, there are specific parameters on the **values.yaml** for the metrics exporter too.

Could you please adapt your PR to that approach? Using a ***postInstall** action doesn't look to me like the appropriate solution.

**Comment by grebois** [comment]
Hi @juan131 

I definitely though about that, of course it was my first approach, but right now there isn't any official docker image for this exporter, even the fork https://github.com/percona/mongodb_exporter which is much more up-to-date does not offer an official image, I really didn't want to create a fork of a fork and create an image cause then wont maintaining it will be very hard, also there are no compiled releases except for the one I'm using in this PR.

I totally agree with you that this solution is far from ideal, another option would be to use HELM post-hooks to run the exporter, I'm very open to hear other (more elegant) solutions that you might have in mind.

**Comment by juan131** [comment]
@tompizmor you had been looking for MongoDB exporters in the past, hadn't you? Do you have any clue if there's any maintained image we can use?

We could also create the image and keep updated from CVEs and so on.. As long as the Golang MongoDB exporter is maintained. What do you think? @carrodher @javsalgar

**Comment by grebois** [comment]
@juan131 @carrodher @javsalgar @sekka1 :bump:

**Comment by grebois** [comment]
@juan131 I took you advice and followed the rabbitmq-ha approach, so I'm closing this one in favor to https://github.com/kubernetes/charts/pull/6601

**Pull request closed without merging**
