### PR TITLE
Fixing SecurityContext for Kubernetes 1.4 update

### PR DESCRIPTION
**Pull request by shraykay**

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@shraykay I can't seem to find any documentation on this change in the spec. The user guide still documents the `securityContext` property: http://kubernetes.io/docs/user-guide/security-context/

**Comment by shraykay** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/proposals/pod-security-context.md @prydonius 

When I try to apply the chart without the modification, running a describe RS on the deployment shows that "securityContext" spec no longer is valid in a deployment.

**Comment by viglesiasce** [comment]
Note the examples there though:
https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/proposals/pod-security-context.md#examples

Looks like its just saying that there is a multi tiered way to control it now. Either way at each tier it is called `securityContext` and not `PodSecurityContext`.

**Comment by shraykay** [comment]
I was able to run it locally with PodSecurityContext -- it's also mentioned in the struct in the link I pasted above. Are you using 1.4 to test? @viglesiasce

**Comment by viglesiasce** [comment]
I believe its working because that field is being ignored. What is the error you are seeing? What platform are you on?

Here is my result:

``` shell
$  kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
$  helm install stable/jenkins
Fetched stable/jenkins to jenkins-0.1.1.tgz
fashionable-te
Last Deployed: Wed Oct 19 14:03:22 2016
Namespace: default
Status: DEPLOYED

Resources:
==> v1/ConfigMap
NAME                     DATA      AGE
fashionable-te-jenkins   1         0s

==> v1/PersistentVolumeClaim
NAME                     STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
fashionable-te-jenkins   Pending                                      0s

==> extensions/Deployment
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
fashionable-te-jenkins   1         1         1            0           0s

==> v1/Service
NAME                     CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
fashionable-te-jenkins   10.143.252.45   <pending>     8080/TCP,50000/TCP   0s

==> v1/Secret
NAME                     TYPE      DATA      AGE
fashionable-te-jenkins   Opaque    2         0s


Notes:
Getting Started:

1. Get your 'admin' user password by running:
  printf $(printf '\%o' `kubectl get secret --namespace default fashionable-te-jenkins -o jsonpath="{.data.jenkins-admin-password[*]}"`);echo

2. Get the Jenkins URL to visit by running these commands in the same shell:
**** NOTE: It may take a few minutes for the LoadBalancer IP to be available.                      ****
****       You can watch the status of by running 'kubectl get svc -w fashionable-te-jenkins' ****
  export SERVICE_IP=$(kubectl get svc --namespace default fashionable-te-jenkins -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo http://$SERVICE_IP:8080/login

3. Login with the password from step 1 and the username: admin

For more information on running Jenkins on Kubernetes, visit:
https://cloud.google.com/solutions/jenkins-on-container-engine


 ~  $  helm list
NAME            REVISION    UPDATED                     STATUS      CHART
fashionable-te  1           Wed Oct 19 14:03:22 2016    DEPLOYED    jenkins-0.1.1
 ~  $  kubectl get pods
NAME                                     READY     STATUS     RESTARTS   AGE
fashionable-te-jenkins-701602904-zsc7k   0/1       Init:0/1   0          41s
 ~  $  kubectl get pods -w
NAME                                     READY     STATUS     RESTARTS   AGE
fashionable-te-jenkins-701602904-zsc7k   0/1       Init:0/1   0          48s
NAME                                     READY     STATUS            RESTARTS   AGE
fashionable-te-jenkins-701602904-zsc7k   0/1       PodInitializing   0          1m
fashionable-te-jenkins-701602904-zsc7k   1/1       Running   0         1m
```

**Comment by prydonius** [comment]
@shraykay any more info on this?

**Pull request closed without merging**
