### PR TITLE
[stable/sumologic-fluentd] Fix daemonset template

### PR DESCRIPTION
**Pull request by EppO**
#### What this PR does / why we need it:
Fix YAML indentations for sumologic-fluentd daemonset template of tolerations, nodeSelector and affinity options

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by frankreno — APPROVED** [review]
LGTM

**Comment by frankreno** [comment]
@unguiculus - can we get a review/ok-to-test on this?

**Review by DandyDeveloper — APPROVED** [review]

**Pull request closed without merging**
