### PR TITLE
[incubator/kafka] adding an explicit selector to the kafka statefulset

### PR DESCRIPTION
**Pull request by KealanM**
Signed-off-by: Kealan Murphy <kealan.murphy@aspect.com>

#### What this PR does / why we need it:
Rather than using the default selector behaviour of using all labels, this pull request sets a staic set of match labels based on app and release. If the podLabels value is used in conjunction with the default selector behaviour this can lead to issues when upgrading a release if a label is being changed. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by benjigoldberg** [comment]
/ok-to-test

Thanks for the PR @KealanM

**Comment by benjigoldberg** [comment]
@KealanM if you pull upstream I can get this merged 👍

**Comment by KealanM** [comment]
@benjigoldberg Done.

**Comment by KealanM** [comment]
@benjigoldberg Another conflict came in after I rebased, doing so again.

**Comment by benjigoldberg** [comment]
.lgtm

**Pull request merged**
