### PR TITLE
Add SSL certificate support and AMPQS support

### PR DESCRIPTION
**Pull request by laghoule**
Chart stable/rabbitmq-ha:
- I have added support for using SSL certificate and use AMPQS.
- I have changed the config of rabbitmqWebMQTTPlugin to be able to use the added certificate
- I have added the possibility to add RabbitMQ authentification in the configuration file

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @etiennetremel

**Review by etiennetremel — APPROVED** [review]

**Comment by laghoule** [comment]
Hi @unguiculus,
@etiennetremel seem ok with the patch, can you approve the PR?

Thanks

**Pull request merged**
