### PR TITLE
[stable/dex] Make web.allowedOrigins configurable using values file

### PR DESCRIPTION
**Pull request by jasmdk**
Signed-off-by: Jacob Stampe Mikkelsen <jmn@systematic.com>

No
#### What this PR does / why we need it:
Allows origins to be configured for dex to allow CORS configuration. The property is supported by dex, but was not exposed through values.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks!
/assign
/ok-to-test
In order to be generic, do you think it would be a good idea to have an extraConfig that would be appended to the Secret, instead of trying to control every Dex parameter?

**Comment by jasmdk** [comment]
> Thanks!
> /assign
> /ok-to-test
> In order to be generic, do you think it would be a good idea to have an extraConfig that would be appended to the Secret, instead of trying to control every Dex parameter?

Would be a good idea, but if I add web.allowedOrigins separately, then dex no longer recognized web.http which was declared earlier in the config file.

**Comment by desaintmartin** [comment]
Indeed, let's get this merged.
Thanks for the contribution!
/lgtm

**Pull request merged**
