### PR TITLE
[stable/redis] fix typos on README/comments for service.type

### PR DESCRIPTION
**Pull request by thomas-riccardi**
#### What this PR does / why we need it:
- Fix typos on README/comments for service.type
- Also fixed default value in README for {slave,metrics}.service.type (completes #5524).

#### Special notes for your reviewer:
I did not bump the chart version as it doesn't change anything when this chart is used from the repository: only the README and comments in `values.yaml` have changed.
Should I still bump the chart version?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

In this case you should increment `patch` version

**Comment by thomas-riccardi** [comment]
/retest

@carrodher chart patch version bumped , to be merged *after* #8930

**Comment by carrodher** [comment]
I just saw that #8930 is merged, so once you rebase those changes here, I will add the LGTM label

**Comment by thomas-riccardi** [comment]
@carrodher done !

**Pull request merged**
