### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by max8899**
typo:
funtion -> fucntion

Signed-off-by: Lei Gong <lgong@alauda.io>

### CODE REVIEW

**Comment by mattfarina** [comment]
/ok-to-test

@max8899 The chart version needs to be incremented even for doc changes.

**Comment by max8899** [comment]
@davidkarlsen @mattfarina updated and sorry for the late response, almost forgot this pr

**Comment by cpanato** [comment]
@max8899 please sign the DCO

**Comment by max8899** [comment]
@cpanato  why this keeps failing? I already signed off the commit

**Comment by cpanato** [comment]
@max8899 maybe you can rebase and squash the commit and then sign-off all commits should be signed

**Pull request closed without merging**
