### PR TITLE
[incubator/couchdb] fix env vars for db container

### PR DESCRIPTION
**Pull request by willholley**
#### What this PR does / why we need it:

Fixes environment variables not being set correctly for the
couchdb container when `.Values.enableSearch` is `false` (the
default).

The feature toggle for search excluded the search container from the
statefulset but did not exclude the associated environment variables.
The result of this was a duplicate `env` field for the `couchdb`
container which would override the correct `env` field; for example,
`ERL_FLAGS` would not be passed to the container.

This comment fixes the scoping of the `.Values.enableSearch` feature
toggle to include the `env` fields for the `clouseau` container.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by willholley** [comment]
fyi @kocolosk

**Comment by kocolosk** [comment]
Oops! That's definitely a bug on my part.

I think the fix needs to be a little different, though. The `COUCHDB_USER` and `COUCHDB_PASSWORD` environment should be associated with the `couchdb-statefulset-assembler` image, not the `clouseau` image. If you agree, can you update the PR?

**Comment by willholley** [comment]
thanks @kocolosk - now fixed.

**Review by kocolosk — APPROVED** [review]
LGTM, this is a necessary bug fix, thanks @willholley

**Pull request merged**
