### PR TITLE
[stable/jenkins] JCasC auto reload works without ssh keys

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:
We make use of the fact that the Jenkins Configuration as Code Plugin can be triggered via http `POST` to `JENKINS_URL/configuration-as-code/reload`and a pre-shared key.

This way we do not rely on any users which need to exist in Jenkins and there is no need to configure ssh keys which by the way have more permissions than just reloading the configuration.

It also allows us to us `kiwigrid/k8s-sidecar:0.1.20` as sidecar for configuration reloads instead of it's fork `shadwell/k8s-sidecar`. That's 1M+ vs 10k pulls on dockerhub.

References:
- [Triggering Configuration Reload](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configurationReload.md)
- [kiwigrid/k8s-sidecar](https://hub.docker.com/r/kiwigrid/k8s-sidecar)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
The Jenkins update site seems to have some issues at the moment. The init container which is trying to download the plugins fails and restarts...

**Comment by torstenwalter** [comment]
Part-of: #16931

**Comment by maorfr** [comment]
/lgtm

amazing, as always.

**Comment by torstenwalter** [comment]
@maorfr Thanks for the kind words. It's a pleasure to contribute.

**Pull request merged**
