### PR TITLE
[stable/redis-ha] Correcting the number of arguments to toYaml

### LINKED ISSUE #16869: [stable/redis-ha] Render error in HAProxy Deployment Template
**Describe the bug**

I'm receiving the following error when enabling `haproxy.enable` and providing `haproxy.annotations` values at the same time.

```
Error: render error in "redis-ha/templates/redis-haproxy-deployment.yaml": template: redis-ha/templates/redis-haproxy-deployment.yaml:29:3: executing "redis-ha/templates/redis-haproxy-deployment.yaml" at <toYaml>: wrong number of args for toYaml: want 1 got 2
```

**Version of Helm and Kubernetes**:

Client: v2.14.3

**Which chart**: [stable/redis-ha v3.7.4](https://github.com/helm/charts/tree/master/stable/redis-ha)

**What happened**:

When running `helm install` or `helm template` with the configuration mentioned in the description, I'm receiving a Helm `render error`.

**What you expected to happen**:

The ability to apply annotations to the `haproxy` Deployment.

**How to reproduce it** (as minimally and precisely as possible):

In the `stable/redis-ha` directory

Adjust the `values.yaml` file to contain an `haproxy` section which has `haproxy.enabled=true` and at least one entry in `haproxy.annotations`.

***Example:***

```yaml
haproxy:
  enabled: true  # <--- Change from default
  replicas: 1
  image:
    repository: haproxy
    tag: 2.0.4
    pullPolicy: IfNotPresent
  annotations:
    sidecar.istio.io/inject: "false"  # <-- Change from default
  resources: {}
  ## Service type for HAProxy
  ##
  service:
    type: ClusterIP
    annotations: {}
  serviceAccount:
    create: true
  ## Prometheus metric exporter for HAProxy.
  ##
  exporter:
    image:
      repository: quay.io/prometheus/haproxy-exporter
      tag: v0.9.0
    enabled: false
    port: 9101
  init:
    resources: {}
```

In the `stable/redis-ha` directory, try to render the template locally to observe the render error:

` helm template -f values.yaml .`

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by frayer**
Correcting the number of arguments to `toYaml` from 2 to 1 in the HAProxy Deployment template.

Signed-off-by: Michael Frayer <frayerm@gmail.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

Addresses a Helm template rendering issue due to an incorrect number of arguments being passed to a `toYaml` function.

#### Which issue this PR fixes

  - fixes #16869 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by DandyDeveloper — APPROVED** [review]
/lgtm

**Comment by DandyDeveloper** [comment]
Oh actually,  @frayer Can you add a test for this? Seems like a good candidate.

**Comment by frayer** [comment]
> Oh actually, @frayer Can you add a test for this? Seems like a good candidate.

Absolutely.  Looking at how other Helm tests are written, it seems like this would be the test flow:

1. `helm get values` against the given Helm release.
2. Get the K8s config of the respective haproxy Pods for the release.
3. Check the Helm Release values if `haproxy.enable` was set and `haproxy.annotations` assigned.
4. Ensure the desired annotations are applied to the `haproxy` Pods.

Does that sound right?

**Comment by DandyDeveloper** [comment]
> Does that sound right?

Actually through the CI it should be as easy as updating the `ci/` values and the ci will test with those values enabled. Your mechanism will work, just might be overkill for this situation.

In this case, just add the annotations to what already exists and it should do a fairly straightforward sanity check. 

If we had it there previously, we would have seen these problems, so that's my bad for not including it!

**Comment by DandyDeveloper** [comment]
@frayer Can you try merging with master and forcing the retest? I've merged something elsewhere recently.

**Comment by frayer** [comment]
Sure thing.  Looks like that cleaned up the CircleCI jobs.

**Comment by frayer** [comment]
Anything else I can do to help get this one merged?

**Pull request merged**
