### PR TITLE
More features and fixes (Secrets/ENVs/ServicePort)

### PR DESCRIPTION
**Pull request by stevie-**
**What this PR does / why we need it**:
* Support ACLs for topics
* Use service port for external distinct service
* be able to control competing dns annotations
* be able to provide extra non KAFKA_ prefixed ENV variables
* be able to mount k8s secrets without subpath / keys

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This includes ACLs from pull request [https://github.com/helm/charts/pull/7505]() which will be closed.

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@stevie - awesome pr -- these features are great and sorely needed by the chart.

/ok-to-test

**Comment by benjigoldberg** [comment]
I think you just need a version bump

**Comment by stevie-** [comment]
@benjigoldberg versioned bumped and fixed a bug if multiple operations should be applied

**Comment by stevie-** [comment]
@unguiculus solved merge issues and bumped version again

**Comment by stevie-** [comment]
/assign benjigoldberg

@unguiculus assigning back to owner, since git history is fixed

**Pull request merged**
