### PR TITLE
[stable/mariadb] Bump MariaDB version 

### PR DESCRIPTION
**Pull request by juan131**
- Update Phabricator image version to "10.1.21-r0".
- Update chart to "0.5.7".

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by sebgoa** [comment]
+1

except that the comment talks about Phabricator, when we are actually talking about mariadb.

**Comment by bacongobbler** [comment]
LGTM

**Comment by sebgoa** [comment]
Can we merge this ? @viglesiasce @prydonius

**Pull request merged**
