### PR TITLE
[incubator/elasticsearch] Add loadBalancerIP/loadBalancerSourceRanges

### PR DESCRIPTION
**Pull request by Lord-Y**
It can be very useful to be able to set these 2 variables if necessary. I'm doing it every times with new charts downloaded for my private cloud

### CODE REVIEW

**Comment by Lord-Y** [comment]
@mattfarina @icereval Can you please check the patch? :)

**Comment by mattfarina** [comment]
@simonswine @icereval @rendhalver Can you please review this?

**Comment by rendhalver** [comment]
Please put the chart name IE: [incubator/elasticsearch] in the PR title so it's easier to know what the PR is for.

**Comment by rendhalver** [comment]
@Lord-Y Looks good.
What does setting these variables help us with?

**Comment by rendhalver** [comment]
/ok-to-test
(I looked up the docs)
Oh I see. Good addition. Thanks!

**Comment by Lord-Y** [comment]
@rendhalver The resources of my enterprise are on both Gcloud and 2 datacanceters. When I need to access to my Elasticsearch cluster from the datacenters I specified a loadBalancerIP so the service is available from an IP address like 10.X.X.X.
For the loadBalancerSourceRanges, it's when the service is available from a public IP address and you need to firewall this access

**Comment by rendhalver** [comment]
Weird. The last test is complaining about the version but you definitely incremented it.
@mattfarina Any ideas?

**Comment by Lord-Y** [comment]
@rendhalver @mattfarina @davidkarlsen I understood the issue. When I forked the repo, it was with version 1.4.0. I then bumped up the charts version but there was already a 1.4.1 version on master branch. So now I bumped it to version 1.4.2

**Comment by rendhalver** [comment]
Ahh that would do it.
You will need to merge upstream/master into your branch.

**Comment by Lord-Y** [comment]
Yeah @rendhalver  now I need some `/approve` from you guys @mattfarina @icereval to complete the process.

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
/lgtm

after incrementing the version

**Pull request merged**
