### PR TITLE
Kubernetes Operational View -> STABLE

### PR DESCRIPTION
**Pull request by hjacobs**
Move `kube-ops-view` to stable and add icon.

### CODE REVIEW

**Comment by hjacobs** [comment]
Any news on this PR? This PR also fixes the missing logo on https://kubeapps.com/charts/incubator/kube-ops-view :smirk:

**Comment by hjacobs** [comment]
@prydonius @viglesiasce sorry to ping you again, but any ETA on processing PRs? If we want to promote helm charts as the next kind of "app store" for Kubernetes, we clearly need faster response times for PRs (especially if it's simple changes).

I'm also happy to help if you want to onboard more maintainers :smile:

**Comment by prydonius** [comment]
@hjacobs thanks for the change, really sorry it's been slow. We're currently focusing on sets of PRs in milestones: https://github.com/kubernetes/charts/milestone/3, but we're continuously trying to improve the process to get through PRs much faster.

Adding more maintainers is certainly something we need, I'd be happy to discuss that with you on Slack.

**Comment by hjacobs** [comment]
Thanks for the answer.

**Comment by hjacobs** [comment]
@k8s-bot tell me a joke.

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@hjacobs LGTM. Sorry for the delay. We are working to get the time to merge down.

**Pull request merged**
