### PR TITLE
[stable/postgresql] Support different affinities, nodeSelectors and tolerations for master & slaves

### LINKED ISSUE #9349: [stable/postgresql] Different affinities for master & slaves
FEATURE REQUEST:

Can we have the option to set different affinities for the master vs slaves?

similiar to how redis does it https://github.com/helm/charts/tree/master/stable/redis

```
master.affinity []  
slave.affinity []
```

### PR DESCRIPTION
**Pull request by tompizmor**
Signed-off-by: tompizmor <tompizmor@gmail.com>

#### What this PR does / why we need it:
This PRs allows to specify different affinities, nodeSelectors and tolerations for master and slaves nodes
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/helm/charts/issues/9349

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @tompizmor it seems there are a couple of conflicts. Could you fix them?
It'd be great if you could add some upgrade instructions in the **README.md** since this PR breaks backwards compatibility.

**Comment by carrodher** [comment]
After apply @juan131 suggestions, it should be ready to be merged

**Pull request merged**
