### PR TITLE
fix formatting in fluentd-elasticsearch

### PR DESCRIPTION
**Pull request by cch0**
**What this PR does / why we need it**:

@monotek 

fix formatting 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

N/A

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by monotek** [comment]
Thanks! I think you have to raise the chart version to 0.6.2 too.

**Comment by monotek** [comment]
And you need to sign the CLA, see the message of the bot above...

Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by cch0** [comment]
I have signed the CLA and fixed the author email/name.

**Pull request merged**
