### PR TITLE
[stable/prometheus-operator] proper sync of rules and dashboard with upstream

### PR DESCRIPTION
**Pull request by den-is**
#### What this PR does / why we need it:
That PR syncs with the latest upstream updates.
PR tested on k8s 1.18.0 and helm2.

Upstream (kube-prometheus, kubernetes-mixin, ...) quite often not only adds new definitions and files, but also deletes old definitions/groups/files.
People forget to remove previous rules and dashboards definitions in this chart prior to syncing with upstream.
That leaves us with outdated and untracked resources. (Though of course, fresh syncs bring breaking changes too)

Actions usually required before syncing:
```sh
# in the chart root
rm -f templates/prometheus/rules-1.14/* templates/prometheus/rules/*
rm -f templates/grafana/dashboards-1.14/* templates/grafana/dashboards/*

hack/sync_prometheus_rules.py
hack/sync_grafana_dashboards.py

# don't forget to restore CoreDNS dashboard :)
# IMHO such local dashboard should stay in some different folder,
# otherwise one day someone will forget to include it in PR.
```

Post-upgrade (or pre-upgrade) users should remove outdated rules and dashboards if they wish.

**Question:** If resource definitions `removal` should be included and automated by the same python scripts?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by billimek** [comment]
I know this was merged, but I'm seeing a ton more CPU used after upgrading.  Is anyone else experiencing the same?
image

Furthermore, I'm now seeing alerts firing for `PrometheusRuleFailures`
image

... and the following errors from the `prometheus-prometheus-operator-prometheus-0` pod:

```
level=warn ts=2020-04-20T18:17:38.237Z caller=manager.go:534 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: code_verb:apiserver_request_total:increase30d\nexpr: sum by(code, verb) (increase(apiserver_request_total{job=\"apiserver\"}[30d]))\n" err="query processing would load too many samples into memory in query execution"
```

@den-is do you know where I can go digging?  I'll try downgrading the chart to see if the behavior returns to normal to validate the observations.

**Comment by billimek** [comment]
FWIW, rolling back the chart to 8.12.13 makes these issues go away.

**Comment by bismarck** [comment]
@billimek Have you tried using the latest Prometheus release (2.17.2)?  There was a performance [regression](https://github.com/prometheus/prometheus/issues/6968) in Prometheus 2.16.0.

**Comment by billimek** [comment]
@bismarck I see what you're referring to.  It looks like the version of prometheus with the regression was introduced in #21829 ([ref](https://github.com/helm/charts/pull/21829/files#diff-372fb33b457ba90ea51eb088dd8a4681R1263)) for chart version 8.12.15

**Comment by vsliouniaev** [comment]
Prometheus 2.17.2 is now out, so that's probably a better version to go to. Particularly if you use remote write

**Comment by smoke** [comment]
@billimek I have the same error
> ... and the following errors from the `prometheus-prometheus-operator-prometheus-0` pod:
> 
> ```
> level=warn ts=2020-04-20T18:17:38.237Z caller=manager.go:534 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: code_verb:apiserver_request_total:increase30d\nexpr: sum by(code, verb) (increase(apiserver_request_total{job=\"apiserver\"}[30d]))\n" err="query processing would load too many samples into memory in query execution"
> ```

I have tracked it down to https://github.com/coreos/kube-prometheus/commit/926337feacef28c43a079ba4045ed385e7243532 
Basically this metric calculation is really loading records for 30d now (prev 7d), this may also be the cause of the increased CPU utilization ...

I am still trying to figure out the best course of action - changing the rule to use less data / for less days somehow or increasing the `--query.max-samples` (default is 50'000'000) through https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#queryspec

**Comment by smoke** [comment]
So I have tried increasing the `--query.max-samples`, however this didn't quite work as I started getting `Prometheus is missing rule evaluations due to slow rule group evaluation.` alert because it took a lot of time to evaluate the rule ~30-40s

I have decided to go back to `v8.12.15` with pinned prometheus image version to `v2.17.2` as suggested:
```
helm upgrade --install prometheus stable/prometheus-operator --namespace monitoring --version 8.12.15 \
--set prometheus.prometheusSpec.image.tag=v2.17.2
```

I hope https://github.com/coreos/kube-prometheus/issues/503 gets fixed soon enough.

**Comment by smoke** [comment]
At the end - unfortunately I had to revert to too old version of the chart as the `apiserver_request_total:increase30d` aggregations were introduced with prometheus-operator helm chart `8.12.14` and later.
So I ended up with a workaround and an issue to track that problem here https://github.com/helm/charts/issues/22081

**Pull request merged**
