### PR TITLE
feat add consul

### PR DESCRIPTION
**Pull request by lachie83**
Todo
- [x] Add Readme
- [x] Add Gossip Encryption
- [x] Testing

### CODE REVIEW

**Comment by bprashanth** [comment]
@foxish @erictune fyi, if you have review cycles before i do

**Comment by foxish** [comment]
I took a look at this. Appears to run fine and perform leader election and all that. I'm not sufficiently familiar with consul to look through the intricacies. The README would help, and maybe a test.sh script that lets us confirm whatever else we expect to be working. @lachie83

**Comment by lachie83** [comment]
@foxish Sure thing. I'll get this PR updated today with README and a test script.

**Comment by lachie83** [comment]
Add README and test script

**Comment by viglesiasce** [comment]
@lachie83 would you mind pulling in the last changes from master (reorg) then putting this chart in the incubator directory?

**Comment by lachie83** [comment]
@viglesiasce Moved chart directory over to incubator. LMK if this looks okay

**Comment by viglesiasce** [comment]
ok to test

**Comment by sebgoa** [comment]
needs license header on shell script.

also could show example of how to run the `test.sh` on a pod, using `kubectl exec`.

otherwise +1

**Comment by lachie83** [comment]
@runseb - Updated license and test.sh.

**Comment by sebgoa** [comment]
+1 

don't know how gets the final call to merge charts now cc/ @viglesiasce

**Pull request merged**
