### PR TITLE
Typo fix in webpagetest-agent/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
Line 53: delete duplicated "the the"

### CODE REVIEW

**Comment by AdamDang** [comment]
@timstoop This Chart.yaml does not has appVersion key. I checked the values.yaml and found the tag is "2018-01-08", mostly this tag should be used as the appVersion, so I used it as the appVersion. But still not OK. Do you have any other suggestion?
Thanks!

**Comment by timstoop** [comment]
```
Error validating data /home/circleci/project/incubator/webpagetest-agent/Chart.yaml with schema test/circle/yaml-schemas/Chart.yaml
	appVersion: '2018-01-08' is not a str.
	appVersion: '2018-01-08' is not a num.
```

Let's wait until someone with more experience with the CI responds. I hope either @mattfarina or @unguiculus know who to ping for this.

**Comment by timstoop** [comment]
Can you try quoting the value for appVersion? So: `appVersion: "2018-01-08"`

**Comment by ljnelson** [comment]
Hello; I had a question on this (now merged) PR.

I am not a YAML expert, but I'm not sure that the YAML specification interprets quoting a scalar as type coercion (to string).  My read is that [quoting a scalar is a presentation detail](http://yaml.org/spec/1.2/spec.html#id2786942).  I'm sure many parsers _do_ use this as a helpful indication about the data type in question, but I don't think they _have_ to.

The reason I care is because in particular SnakeYAML, the _de facto_ Java YAML parser, seems to interpret `2018-01-08` and `"2018-01-08"` when used as YAML values as denoting YAML timestamp scalars.  It then helpfully turns the value of `appVersion` (in this case) into a `java.util.Date` and https://github.com/microbean/microbean-helm/issues/131 blows up.  :-)

I'm not sure what to do about all this but I didn't want it to get lost.  I've also [started a discussion on StackOverflow](https://stackoverflow.com/questions/49889416/in-yaml-must-a-quoted-scalar-be-interpreted-by-a-parser-as-a-string).

One possibility for correctness might be to tag the value instead:

    appVersion: !!str 2018-01-08

**Pull request merged**
