### PR TITLE
[stable/grafana] Fail when curl is not able to download templates.

### PR DESCRIPTION
**Pull request by kpucynski**
#### Is this a new chart
no.

#### What this PR does / why we need it:
Curl is not failing on http errors and, for example, downloads 404 error pages as json templates generating errors during grafana deployment.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by kpucynski** [comment]
```failed to try resolving symlinks in path "/var/log/pods/test-pods_ceda3a73-067e-11ea-962d-7e68fef98b17_e047f5e0-067e-11ea-94a6-42010a800010/test/0.log": lstat /var/log/pods/test-pods_ceda3a73-067e-11ea-962d-7e68fef98b17_e047f5e0-067e-11ea-94a6-42010a800010/test/0.log: no such file or directory```
Whoa, e2e chart tests are broken again (still?)?

**Pull request merged**
