### PR TITLE
[stable/grafana] Make deployment consistent with configmaps

### PR DESCRIPTION
**Pull request by swarkentin**
#### Is this a new chart
No

#### What this PR does / why we need it:
A change introduced in e9bcd1a results in configmaps not being created if a `dashboards` value entry is empty. Another change recently moved the `---` control block outside of the `range`, which loops through each dashboard. This means that only at most one configmap will ever be created - resulting in inconsistencies with the deployment configuration. This PR moves `---` back into the `range` block.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by swarkentin** [comment]
Not clear to me why the e2e tests are failing... I'll try once more.

**Comment by swarkentin** [comment]
I'm not sure what I need to do to resolve this:

```
I1030 15:15:23.157] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I1030 15:15:23.157] <== Description of pod grafana-w4xyx39juj-test
I1030 15:15:23.157] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I1030 15:15:23.620] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:23.621] ==> Logs of init container grafana-w4xyx39juj-test
I1030 15:15:23.622] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:24.119] + cp -R /usr/local/libexec/ /tools/bats/
I1030 15:15:24.124] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:24.125] <== Logs of init container grafana-w4xyx39juj-test
I1030 15:15:24.125] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:25.138] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:25.138] ==> Logs of container grafana-w4xyx39juj-test
I1030 15:15:25.139] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:26.087] 1..1
I1030 15:15:26.088] not ok 1 Test Health
I1030 15:15:26.089] # (in test file /tests/run.sh, line 4)
I1030 15:15:26.089] #   `code=$(curl -s -o /dev/null -I -w "%{http_code}" $url)' failed with status 7
I1030 15:15:26.107] ------------------------------------------------------------------------------------------------------------------------
I1030 15:15:26.108] <== Logs of container grafana-w4xyx39juj-test
I1030 15:15:26.109] ------------------------------------------------------------------------------------------------------------------------
```

**Pull request merged**
