### PR TITLE
Fixes #1341 -- update Jenkins chart documentation

### LINKED ISSUE #1341: [stable/jenkins] JNLP port should not be exposed via type=LoadBalancer
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: Makes no difference

**Which chart**: stable/jenkins

**What happened**: Port 50000 (the jenkins JNLP master port) is exposed to the open internet via an ELB when the helm chart is installed on a cluster with an AWS cloud provider

**What you expected to happen**: The jenkins master port should *not* be exposed the same way the HTTP port is... since it's configured to launch slaves in the same kubernetes cluster, that service can just be ClusterIP.  There should be an option to only expose the HTTP port via type=LoadBalancer while keeping the master port private to the cluster.

**How to reproduce it** (as minimally and precisely as possible): `helm install stable/jenkins` on an AWS cluster (I'm sure it's the same for any other cloud provider)

**Anything else we need to know**: There's enough configuration options to tune this behavior, but the defaults should not be this insecure.

### PR DESCRIPTION
**Pull request by dalvizu**
@lachie83 
@viglesiasce 

#### What this PR does / why we need it:
Update `values.yml` documentation on using `LoadBalancer` type of
Service in a secure way by adding required annotations. This creates
an internal LoadBalancer with locked down rules on allowed CIDR ranges
via annotations.

The default setting - `ClusterIp` - only works inside the same cluster.

#### Which issue this PR fixes
  - fixes #1341 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by dalvizu** [comment]
Linting is failing because I did not bump version -- is that required for documentation update?

**Comment by maorfr** [comment]
Hey @dalvizu,

Thanks for contributing!
Yes, you must bump the chart version.

**Comment by maorfr** [comment]
ping @dalvizu

**Comment by dalvizu** [comment]
Okay it was a bit of an ordeal but I think I sorted out the version bump. I also fixed some lint-script failures from trailing whitespaces, not sure if that was new or always there.

**Comment by maorfr** [comment]
/lgtm
Thanks for this contribution, this is very important.

**Pull request merged**
