### PR TITLE
[stable/prometheus-node-exporter] use standard labels and allow to override

### PR DESCRIPTION
**Pull request by bmailhe**
Signed-off-by: bmailhe <bmailhe@leadformance.com>

#### What this PR does / why we need it:
 * Use helm standard labels as recommended here https://helm.sh/docs/chart_best_practices/labels/ 
 * Allow override these labels for retro-compatibility

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bmailhe** [comment]
Hi @vsliouniaev @gianrubio anything I can do to help merging this PR ?

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to `stable` prometheus charts for a short time until prometheus-community/community#28 (comment) is resolved. If you want to help with that effort, to test etc, that would be great!

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts).

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
