### PR TITLE
[stable/fluent-bit] Fix ElasticSearch Output config templatate

### PR DESCRIPTION
**Pull request by ThorstenKunz**
The most important part of this PR is the fix for the ES config which was broken because it was cut off by the Splunk config.
It also adds the tls options to the http and fluentd output plugin as well as a shared_secret option to the fluentd forwarder output plugin. Also http_user/password options are added to the http backend. All options have backwards compatible defauts.

Signed-off-by: Thorsten Kunz <thorsten.kunz@flexarc.com>

### CODE REVIEW

**Comment by dbayendor-cb** [comment]
I originally was using #7632 for support of Elasticsearch, but since I now have to support both ES and Splunk, this current PR #8166 has passed tests in on both my EKS clusters sending to both platforms.  Giving the thumbs up on this and removing support for #7632 since it doesn't work for Splunk and is currently stale.

**Comment by edsiper** [comment]
cc: @kfox1111

**Comment by kfox1111** [comment]
@edsiper we now how 3 separate pr's trying to fix this issue due to lack of reviews :/ I'm not an approver so I can't do much to fix it. I'll try and ping the cores again.

**Comment by mwl** [comment]
@kfox1111 @edsiper Any luck finding anyone who can approve the PR?

**Comment by kfox1111** [comment]
crickets. :(

Someone suggested trying to get a hold of someone at the next call.

Either way, doesn't seem like a good sign as to the health of the charts community. :(

**Comment by dbayendor-cb** [comment]
@davidkarlsen Any chance you could take a look at this PR to get it moving forward?

**Comment by mwl** [comment]
@ThorstenKunz Do you have a chance to resolve the conflicts or give me access to do it? Other PRs went in a lot faster than this one it seems.

**Comment by ThorstenKunz** [comment]
@mwl I fixed the conflict. Hope the PR will get in before the Chart version gets updated by somebody else and cause the next conflict ;)

**Comment by mwl** [comment]
@ThorstenKunz Appreciated! I'm working on getting this merged.

**Pull request merged**
