### PR TITLE
[stable/minecraft] configurable upgrade strategy type

### PR DESCRIPTION
**Pull request by billimek**
#20375 ## What this PR does / why we need it:

The default is 'Recreate' in order to avoid issues with multi-attach
volume errors

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by itzg — APPROVED** [review]
/approve

**Comment by TJM** [comment]
You probably could have just changed it to Recreate, with rolling update, there are other parameters like how many nodes to keep online, etc.

**Pull request merged**
