### PR TITLE
[stable/prometheus] Add the ability to add sidecar containers to AM.

### PR DESCRIPTION
**Pull request by OGKevin**
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>

#### What this PR does / why we need it:
Add function to add side car containers to alertmanager.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by OGKevin** [comment]
@zanhsieh it looks like node exporter can not be scheduled which is making this job fail correct ? How can we resolve this ?

**Comment by zanhsieh** [comment]
@OGKevin 
I addressed your concern on helm members in k8s slack #charts channel.
https://kubernetes.slack.com/archives/C6E3XH1ED/p1581069316050600

**Comment by zanhsieh** [comment]
@OGKevin 
Could you resolve the conflict so we could retest e2e again please? Thank you and sorry for waiting.

**Pull request closed without merging**
