### PR TITLE
[stable/envoy] Fix template for config files

### PR DESCRIPTION
**Pull request by terashi58**
#### What this PR does / why we need it:
Fix an argument mis-match on applying template for envoy.yaml file.

When we comment out the templates value to use templated envoy.yaml, the `tpl` function raises an  error due to type mis-match. It looks like the arguments are not passed as expected.

#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by terashi58** [comment]
Hi @mumoshu,

The templated envoy.yaml is the feature I'm waiting for. I tried to switch my manifest and found a bug on `tpl` function. I made a fix and it looks working on my environment.

Could you take a look and pick it up to the stable release?

Thanks.

**Comment by terashi58** [comment]
Thanks a lot!

**Comment by mumoshu** [comment]
@terashi58 Thanks for the fix ☺️

**Pull request merged**
