### PR TITLE
[stable/incubator] remove failing icon/logo links

### PR DESCRIPTION
**Pull request by paulczar**
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

These remove icons/logos that 404/503 error.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
/lgtm

**Comment by mattfarina** [comment]
@paulczar @scottrigby The issue is that the cluster is a newer version of Kubernetes that's missing some of the resource versions these older charts have installed.

**Comment by scottrigby** [comment]
Yep 😛 may end up being a good reason to split this into separate PRs per chart, so issues can be addressed separately. But either way

**Comment by paulczar** [comment]
yeah I was afraid that would be the case.   @scottrigby what do you think we should do here ?  The only one that's not deprecated is `stable/elastic-stack/Chart.yaml `   the rest ...  it doesn't really matter if they fail tests because they're deprecated.

If we need to do individual PRs, or go fix all this ... then I'm in favor of closing the PR and ignoring the issues :)

**Comment by mattfarina** [comment]
@scottrigby the only way to address the issues is to upgrade things like Deployments to apps/v1. These are deprecated charts. :(

**Comment by scottrigby** [comment]
OK, merging this to fix the annoying issue. I checked open PRs and issues for `stable/elastic-stack` and this won't hurt anything. Thanks @paulczar 💯

**Pull request merged**
