### PR TITLE
change 'tables'->table"

### PR DESCRIPTION
**Pull request by youhonglian**
line37 change 'tables'->table"

### CODE REVIEW

**Comment by carrodher** [comment]
LGTM

**Comment by timstoop** [comment]
This is failing on something unrelated, the fact that the Chart tries to modify a mounted ConfigMap, which is no longer allowed since the latest K8s. I'll go write a patch to fix that, but you'll have to rebase and modify the version after that has been merged, though.

Actually, the error looks to me like a node error... retest started and checking if that helps. If not, I'm going to leave it to people more knowledgeable about the test system than me.

**Pull request closed without merging**
