### PR TITLE
Index mapping deprecation

### PR DESCRIPTION
**Pull request by djsd123**
#### Compatibility with Elasticsearch 6.x

Please see breaking changes [doc](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html)

Multiple mapping types are not supported in Elasticsearch 6.x.  By
default [fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) creates two mapping types per index `[foo,fluentd]`.
See [issue](https://github.com/uken/fluent-plugin-elasticsearch/issues/442)

From observation in our production cluster, explicitly declaring the mapping type name in the output config allows indexes to be created with the desired properties in Elasticsearch 6.x
and Elasticsearch 5.2.x while using this helm chart.

I have not experienced the issues with property mappings that the reporter of the [issue](https://github.com/uken/fluent-plugin-elasticsearch/issues/442) has experienced.  As you can see from below the `@timestamp: type` is correctly set to `date` using this chart. However, may not be the case if the image is updated.

```
"properties": {
  "@timestamp": {
    "type": "date"
},
```
Fluent-Plugin-Elasticsearch: `2.4.1`

### CODE REVIEW

**Comment by monotek** [comment]
Please resolve merge conflicts

**Comment by djsd123** [comment]
@monotek, @seanknox, thanks, done.

**Comment by monotek** [comment]
its already fixed in: https://github.com/helm/charts/pull/6925

**Pull request closed without merging**
