### PR TITLE
New chart submission [stable/codedx]

### PR DESCRIPTION
**Pull request by tylercamp**
Signed-off-by: Tyler Camp <tylermatthewcamp@gmail.com>

#### Special notes for your reviewer:
Some things of note:

- We use a template for resource labels, since there are many resource that have many of the same labels. I haven't seen this used in other charts but also haven't seen anything explicitly discouraging this. (Template [here](https://github.com/helm/charts/pull/11961/files#diff-bf63c2e239dfc3ea5894808fd6f74b9aR24) and sample usage [here](https://github.com/helm/charts/pull/11961/files#diff-a7d3e3a2b79971683bdc659b81f5434fR7))
- We've got many separate secrets that could probably be combined into a single secret in some cases. I'll take a second look at this if it's brought up as a concern.
- There is a [PNG diagram](https://github.com/helm/charts/blob/297d13fbfe3dcac093eb3a38e400e0211dfc1601/stable/codedx/CodeDxK8s.png) of the deployed resources in the repository. This can be removed and hosted elsewhere if necessary.
- Many of the "lines added" are from documentation files, sample files, and application-specific template files ("codedx.props")

This chart originally developed in: https://github.com/codedx/codedx-kubernetes (which has the full commit history)

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by tylercamp** [comment]
@viglesiasce @prydonius Can we get myself and @ssalas added as collaborators on this repo and get an estimate on when we can expect review/feedback for this chart? We understand there are a lot of pull requests and this is a relatively large one. Thanks for your time.

**Comment by maorfr** [comment]
hey @tylercamp 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by tylercamp** [comment]
@maorfr Thanks for your reply, we've considered it but would be more convenient for end-users if it was available in the official Stable repo. We'd also appreciate the review in general, if possible. We understand if it's unlikely for this to get a review or possible acceptance.

**Comment by maorfr** [comment]
hey @tylercamp, thanks for your reply!

i completely understand your view. having said that, the way forward is helm hub, and not this charts repository. see [this](https://helm.sh/blog/intro-helm-hub) for more information.

you are welcome to keep this PR open and hopefully get a review!
at the same time, i would further explore the helm hub option, as these are getting merged in faster and you will get some community traction :)

**Pull request closed without merging**
