### PR TITLE
[stable/kiam] Upgrade Kiam API versions

### PR DESCRIPTION
**Pull request by velothump**
Needed to deploy to k8s 1.16

Signed-off-by: Adam Graves <adam.graves85@gmail.com>

#### What this PR does / why we need it:

Upgrades api versions so it can be deployed to k8s 1.16.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by velothump** [comment]
@prydonius @unguiculus any chance of a review please? :)

**Comment by ewbankkit** [comment]
@velothump  The kiam chart is now hosted by uSwitch.
Please open the PR in their repo and close here.
Thanks.

**Comment by velothump** [comment]
Thanks @ewbankkit . PR created in uSwitch repo: https://github.com/uswitch/kiam/pull/307

**Pull request closed without merging**
