### PR TITLE
Update readme for node-red

### PR DESCRIPTION
**Pull request by niklasravnsborg**
#### What this PR does / why we need it:

This fixes a typo in the node-red README.md

### CODE REVIEW

**Comment by billimek** [comment]
@nikkasravnsborg Can you please bump the Chart version too?  The tests will fail unless the version is incremented.

**Comment by niklasravnsborg** [comment]
@billimek Did it! Actually found the same mistake on luigi chart too and fixed it. 😎

**Comment by billimek** [comment]
Thanks @niklasravnsborg!  Can you please 'sign the DCO' (instructions should be included [here](https://github.com/helm/charts/pull/13332/checks?check_run_id=113113833)).

Also, you may need to 'split' the changes for the node-red chart and the luigi chart as separate PRs.  Or rather, I won't be able to approve for the luigi chart as I'm not in the OWNERS file for that one.

**Pull request merged**
