### PR TITLE
Allow resource-specific opt-in for Istio auto-inject

### PR DESCRIPTION
**Pull request by frankbu**
This PR allows configuring Istio initializer for resource-specific opt-in.
```
helm install --set initializer.enabled=true --set initializer.policy=disabled incubator/istio
```

### CODE REVIEW

**Comment by frankbu** [comment]
@lachie83 PTAL

**Comment by lachie83** [comment]
@frankbu LGTM. Thanks! Can you bump the chart version and get your CLA sorted and we'll get this merged.

**Comment by frankbu** [comment]
@lachie83 Done and done.

**Pull request merged**
