### PR TITLE
Issue 5622: Kubeless optional Ingress for UI

### LINKED ISSUE #5622: Update Kubeless to enable an Ingress for the UI
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm: v2.9.0
Kubernetes: v1.9.6

**Which chart**:

Kubeless

**What happened**:

I want the UI component to feature a possible Ingress.

**Anything else we need to know**:

I'm implementing it.

### PR DESCRIPTION
**Pull request by alexvicegrab**
**What this PR does / why we need it**:

Added an optional Ingress for the UI component.
Updated "template" to "include" according to Helm Chart best practices in documentation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #5622 

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by unguiculus** [comment]
Any reason why you changed from `template` to `include` thoughout the chart? Both work. That's an unrelated and unnecessary change.

**Comment by alexvicegrab** [comment]
@unguiculus the reason I changed template to include is because it's the preferred way according to the official documentation (e.g.: last few paragraphs of https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md)

> It is considered preferable to use include over template in Helm templates simply so that the output formatting can be handled better for YAML documents.

**Comment by alexvicegrab** [comment]
CI and e2e passing, any other improvements needed prior to a /lgtm?

**Comment by unguiculus** [comment]
@alexvicegrab I don't know why this paragraph is in the docs. Normally, `template` is used (also in the default chart you get with `helm create`). `include` is necessary if you need the result so you can pipe it into another function or store it in a variable. So, in this case, it doesn't really matter, and, since it's a change that is not related to your PR, I'd suggest you revert it.

**Comment by alexvicegrab** [comment]
@unguiculus, thanks for the swift reply, I reverted the conversion of "template" to "include" as you requested.

I will not press the issue here, since you correctly remarked it's not the main reason of the PR, but instead will open a separate Issue to so this separate problem can be discussed and improved.

**Comment by carrodher** [comment]
At this moment it LGTM, what do you think @unguiculus?

**Comment by alexvicegrab** [comment]
Remerged with latest update of master, as there was a merge conflict caused by last update to Kubeless.

**Pull request merged**
