### PR TITLE
[stable/postgres-operator] add postgres-operator helm chart

### PR DESCRIPTION
**Pull request by FxKu**
Signed-off-by: Felix Kunde <Felix.Kunde@zalando.de>

### CODE REVIEW

**Comment by maorfr** [comment]
hey @FxKu 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by FxKu** [comment]
Somebody already pointed me to this option, but so far we are not planning to host the chart ourselve.

**Comment by maorfr** [comment]
You can do it easily with github pages:
https://github.com/helm/hub/blob/master/docs/github.md

**Comment by r3kzi** [comment]
@FxKu Confluent does it with https://confluentinc.github.io/cp-helm-charts/. The charts are located here https://github.com/confluentinc/cp-helm-charts/tree/master/docs. 

Anyway...the stable repos are fine with me as well :-) I'm currently migrating our helm installations from shell scripts to terraform so i'm desperately waiting for a solution :-)

**Comment by maorfr** [comment]
please take a look at helm/helm#6095 (comment)

we strongly encourage people to self host chart repos:
https://github.com/helm/hub/blob/master/Repositories.md

you can even do that using GitHub pages:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

**Comment by FxKu** [comment]
Thanks @maorfr for the hints (I'm just back from vacation). I'll have a look at the GitHub pages alternative.

**Comment by FxKu** [comment]
Hosting now via GitHub Pages:
```
helm install https://opensource.zalando.com/postgres-operator/charts/postgres-operator/postgres-operator-1.2.0.tgz
```

Can this PR be closed then?

**Comment by maorfr** [comment]
yup! thanks!

**Pull request closed without merging**
