### PR TITLE
[stable/sentry] Allow alternate schedulers

### PR DESCRIPTION
**Pull request by knorby**
**What this PR does / why we need it**: Allows configuration on alternate schedules, e.g. Stork. It is setup to be used on all pod specs, but it is most useful for the web pod.

### CODE REVIEW

**Comment by knorby** [comment]
/assign @scottrigby

@rothgar

**Comment by rothgar** [comment]
Can you help me understand why someone would want to use an alternate k8s scheduler for the web pod?

**Comment by knorby** [comment]
@rothgar we need it due to the persistent volume on the web pod. Stork schedules based on volume location, which we need for our volume management. I don't think there is any reason that the scheduler is so limited (hence why I allowed the option on other pods), but PVs are the reason for now.

**Comment by rothgar** [comment]
Thanks for showing me about stork. I'll try to test it this week.

**Comment by rothgar** [comment]
This LGTM and worked with a dummy scheduler I tested. I started trying to learn stork but it was too much for me to set up and didn't want to hold this up. We may need to rebase to bump the version number if one of the other sentry PRs gets merged first.

**Pull request merged**
