### PR TITLE
[stable/grafana] Typo: missing a backtick in README.md

### PR DESCRIPTION
**Pull request by lescactus**
Signed-off-by: Alexandre Maldémé <alma@moodagent.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Nothing big, it is just to fix a minor typo in the README.md (missing backtick)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lescactus** [comment]
Hi @maorfr, this patch is nothing big, just a minor typo fix. The chart version has been bumped as well. 

/assign @maorfr

**Review by maorfr — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
