### PR TITLE
[stable/sonarqube] Update startup command when plugins are enabled

### PR DESCRIPTION
**Pull request by rjkernick**
Signed-off-by: Rob Kernick <rjkernick@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by melissapalmer** [comment]
@rjkernick you are the only person in the OWNERS file for this chart ... are you able to add the lgtm tag? Or do you have someone else who can also add for you?

**Comment by rjkernick** [comment]
@melissapalmer I cannot approve my own request. @unguiculus Can you take a look at this pr for me?

**Comment by HerrmannHinz** [comment]
could need that fix as well.

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
