### PR TITLE
[stable/fluent-bit] Determine correct PodSecurityPolicy ApiGroup

### PR DESCRIPTION
**Pull request by hobti01**
PodSecurityPolicy API Group is detected based on Kubernetes version.

version <1.14 uses `extensions` while version >=1.14 uses `policy`

#### What this PR does / why we need it:

Sets the correct PodSecurityPolicy ApiGroup based on the version of Kubernetes in use.  PodSecurityPolicy is not in the 'policy' ApiGroup until Kubernetes version 1.14

#### Special notes for your reviewer:

Current chart does not work on Kubernetes <=1.13 with `rbac.pspEnabled: true`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ X ] Chart Version bumped
- [ X ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

@kfox1111 @edsiper

### CODE REVIEW

**Comment by kfox1111** [comment]
This looks good to me, but another merge is going to take that version number. please bump it up and we can merge this.

**Comment by hobti01** [comment]
@kfox1111 version bump as requested and rebased

**Comment by hobti01** [comment]
Hi @kfox1111 , any room for movement on this?

**Pull request merged**
