### PR TITLE
Added descheduler chart

### PR DESCRIPTION
**Pull request by jpdasma**
#### What this PR does / why we need it: 
This adds chart for https://github.com/kubernetes-incubator/descheduler

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by jpdasma** [comment]
Dockerfile for the image being used is located here: https://github.com/jpdasma/descheduler-docker

**Comment by sebastien-prudhomme** [comment]
Your chart seems similar to this "unofficial" chart: https://github.com/komljen/helm-charts/tree/master/descheduler

For me:
- You should enable everything by default (this is the default behaviour in descheduler and in the "unofficial" helm chart)
- You should use the yet existing "komljen/descheduler" image instead of creating a new image

**Comment by sebastien-prudhomme** [comment]
Another missing thing is the ability to setup extra arguments for the "descheduler" command. It can be used for instance to modify the log level.

Something like this in values.yaml:

```yaml
# Additional command line arguments to pass to descheduler
extraArgs: {}
#  alsologtostderr: true
#  v: 4
```

**Comment by jpdasma** [comment]
>     * You should enable everything by default (this is the default behaviour in descheduler and in the "unofficial" helm chart)

* I'll update this

>     * You should use the yet existing "komljen/descheduler" image instead of creating a new image
I don't know. I usually avoid Docker images in Docker hub that is not linked to Github/Bitbucket. (Can't see that Dockerfile they used)

>     Another missing thing is the ability to setup extra arguments for the "descheduler" command. It can be used for instance to modify the log level.

I'll add this.

**Comment by jpdasma** [comment]
hi, yes, it's working now

**Comment by sebastien-prudhomme** [comment]
Found time to test the Chart. Everything is working fine.

The little annoying thing is that i got no logs from the jobs, so i used the extraArgs parameter to configure "v: 1".

Perhaps it should be done by default in the chart? What do you thing about that?

**Comment by jpdasma** [comment]
> Found time to test the Chart. Everything is working fine.
> 
> The little annoying thing is that i got no logs from the jobs, so i used the extraArgs parameter to configure "v: 1".
> 
> Perhaps it should be done by default in the chart? What do you thing about that?

That sounds reasonable, I myself use `--v=2` in my environment. Although, I think I should just uncomment the extraArgs by default, so that they could edit the verbosity level.

**Comment by linki** [comment]
@jpdasma Would you mind adding yourself as a maintainer in the `Chart.yaml` to make the linter happy?

**Comment by jpdasma** [comment]
Added myself as maintainer.

**Comment by dgamo** [comment]
@davidkarlsen @foxish @mgoodness

I know this is closed but from the comments everything seems fine. I can take it if there is something left to but otherwise..could be added to the repo?

**Comment by alanpearce** [comment]
This would be nice to have. The comments suggest it's all fine, but just needs a review.

**Comment by austinorth** [comment]
@davidkarlsen @foxish @mgoodness Looks like this might have been missed. I can open a new PR unless @jpdasma wants to update and reopen this one. This would be a super useful tool to be able to deploy with Helm.

**Pull request closed without merging**
