### PR TITLE
[stable/prometheus-operator] Introduce crds directory for compatibility with Helm v3

### PR DESCRIPTION
**Pull request by bhavin192**
#### What this PR does / why we need it:
- This adds `crds` directory which has all 5 CRDs
- As files from crds directory needs to be plain YAMLs, keeps app: prometheus-operator label and removes all the templating
- With this change `.Values.prometheusOperator.createCustomResource` will be ignored by Helm v3 as it handles the CRDs differently. Which means, if the CRDs already present in the cluster then it won't touch them at all
- ~Helm v3 ignores the CustomResourceDefinition objects which are present in `templates` directory. (*At least I wasn't able to find any CRD YAML when I ran `helm install ... --debug`*)~ Helm v3 ignores the objects from `templates` directory which have `crd-install` hook. 
  - https://github.com/helm/helm/blob/865c46c014cdb7622f97ae287ee92fb8a280f3a9/pkg/releaseutil/manifest_sorter.go#L106-L108 
  - https://github.com/helm/helm/blob/865c46c014cdb7622f97ae287ee92fb8a280f3a9/pkg/releaseutil/manifest_sorter.go#L174-L177
- Update the README.md
- Update the chart version

#### Special notes for your reviewer:
- This PR does not do the complete migration of this chart to v2 apiVersion of Chart.yaml. This adds changes which ensure that the current chart is installable with Helm v3 as well.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
I wonder if we can just load the files from the directory and apply them using a list. 

Not sure if that would break the CRD install hooks checking for CRDs being established in Helm 2 or break upgrading the chart. Would you be interested in checking this out?

**Comment by bhavin192** [comment]
Yeah, that's an interesting idea. Thanks, let me try that out.

**Comment by bhavin192** [comment]
I deleted the `crd-*.yaml` files from `templates/prometheus-operator` and created a `crds.yaml` in same directory. Also added `crd-install` hook to files from `crds` directory. Helm v3 does not take any special action on the YAML if we have the crd-install annotation.
- With List approach: (creating the List object out of files from `crds` directory at top level)
  ```yaml
  # templates/prometheus-operator/crds.yaml
  apiVersion: v1
  kind: List
  items:
  {{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
  - {{ $.Files.Get $path | nindent 2 }}
  {{- end }}    
  ```
  - Helm v2: fails to install as well upgrade existing chart. Basically it does not consider the `crd-install` hook from `items:` section of `List` object.
  - Helm v3: fails with the error that the CRDs already exist. Reason is same as above. Does not consider the hook which prevents it from ignoring those objects.
- With separate document approach: (creating one file with all the CRD objects separated by `---`)
  ```yaml
  # templates/prometheus-operator/crds.yaml
  {{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
  {{ $.Files.Get $path }}
  ---
  {{- end }}
  ```
  - Helm v2: new installation works, CRDs are installed first. Upgrade from previous installation works as well.
  - Helm v3: install as well as upgrade works just fine. Objects from `crds.yaml` are ingored as they have `crd-install` hook in them.


@vsliouniaev what do you think, should we go with the second approach?

**Comment by vsliouniaev** [comment]
@bhavin192 thanks for checking this one out. I think that option #2 sounds like it should be the best option.

**Comment by bhavin192** [comment]
@vsliouniaev I made the changes according to the second option, please take a look whenever you are around :)

**Comment by vsliouniaev** [comment]
/lgtm
Looks like it's working!

**Pull request merged**
