### PR TITLE
[stable/nginx-ingress] Set terminationGracePeriodSeconds in DaemonSet mode

### PR DESCRIPTION
**Pull request by shurshun**
**Is your feature request related to a problem? Please describe.**
A template for a DaemonSet mode at this chart uses hardcoded value for the terminationGracePeriodSeconds param instead of in Deployment mode where this param takes from values. I just add ability to set it in DaemonSet mode as well as in other.

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
Thanks for the PR. You will need to sign the DCO before we are able to merge this in.
/ok-to-test

**Comment by shurshun** [comment]
Done!

**Pull request closed without merging**
