### PR TITLE
[incubator/kube-downscaler] Add OWNERS file

### PR DESCRIPTION
**Pull request by Pluies**
#### Is this a new chart

No

#### What this PR does / why we need it:

Create OWNERS file in `incubator/kube-downscaler`

#### Special notes for your reviewer:

Created after discussion on #18276 

I'm also adding @Rowern as he's named as the maintainer in Chart.yaml 👍 

I'm not sure I'm doing this right @zanhsieh , so please let me know if that's all good!

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Pluies 
Sorry. I am not the [helm member](https://github.com/helm/charts/blob/master/OWNERS) so have no control to add @Rowern and @Pluies as owners of this chart.

**Comment by Pluies** [comment]
Oh sorry @zanhsieh , I thought you were from the previous PR 👍 

/assign @davidkarlsen

**Comment by scottrigby** [comment]
@Pluies I have invited you and @Rowern as read-only collaborators per https://github.com/helm/charts#owning-and-maintaining-a-chart. You must each accept the invite: https://github.com/helm/charts/invitations before this PR can pass as-is. Does @Rowern want to be an owner? Can you contact them to ask?

**Comment by scottrigby** [comment]
Rather, being listed in the maintainers section is probably good enough to be added to OWNERS. It would be good to get a confirmation though.

**Comment by Pluies** [comment]
Thanks @scottrigby ! I've accepted the invite, and contacted @Rowern to ask. If it's a no / no answer, I'll edit this PR accordingly 👍

**Comment by Rowern** [comment]
Sorry for the delay, I just noticed I silenced all notifications from Github...
I accepted your invitation! Thank you for adding me as an Owner of this chart.

**Comment by Rowern** [comment]
LGTM

**Comment by Pluies** [comment]
Ping @scottrigby , I think this is all good to go now?

**Pull request merged**
