### PR TITLE
Chart for kube-consul-register

### PR DESCRIPTION
**Pull request by arunvelsriram**
**What this PR does / why we need it**:

This PR adds chart for [kube-consul-register](https://github.com/tczekajlo/kube-consul-register).

kube-consul-register is a tool to register Kubernetes Pods to Consul.

### CODE REVIEW

**Comment by arunvelsriram** [comment]
gentle ping.

**Comment by arunvelsriram** [comment]
A gentle reminder to check this

**Comment by tasdikrahman** [comment]
Can this be reopened? @mattfarina

**Comment by arunvelsriram** [comment]
I would be happy to rebase with master make a few improvements like changing `Replicaset` to `Deployment`.

**Pull request closed without merging**
