### PR TITLE
[stable/sealed-secrets] Update to v0.9.7

### PR DESCRIPTION
**Pull request by jtnz**
Updates to v0.9.7

@mkmik 
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by mkmik** [comment]
You also need to add:

```
      securityContext:
        fsGroup: 65534
```

to the podspec (not container spec)

**Comment by mkmik** [comment]
oh my, I was too slow

**Comment by mkmik** [comment]
@jtnz could you please make a new PR with manifest change only?

(sorry I'm AFAIK and cannot make the PR from mobile)

**Comment by jtnz** [comment]
> @jtnz could you please make a new PR with manifest change only?
> 
> (sorry I'm AFAIK and cannot make the PR from mobile)

On it.

**Comment by stefanprodan** [comment]
We need a helm test that uses kubeseal to create a SealedSecret, apply that and check that the Kubernetes secret has been created.

**Comment by jtnz** [comment]
> We need a helm test that uses kubeseal to create a SealedSecret, apply that and check that the Kubernetes secret has been created.

For the PR that fixes the missing `fsGroup`?

**Comment by stefanprodan** [comment]
@jtnz let's fix the chart first, please open a PR with the `fsGroup`. The test can come latter but we really need to make sure we don't break the installation by just bumping the image tag.

**Pull request merged**
