### PR TITLE
Fix key names in example.

### PR DESCRIPTION
**Pull request by jmeickle**
#### What this PR does / why we need it
The example in the docs is wrong: https://github.com/helm/charts/blob/master/stable/concourse/templates/secrets.yaml#L38

#### Which issue this PR fixes
 n/a

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by Eronarn** [comment]
@william-tran mind taking a look at this?

**Comment by cpanato** [comment]
@Eronarn can you rebase?

**Comment by cpanato** [comment]
@Eronarn can you rebase?

**Comment by william-tran** [comment]
Helm root owners please feel free to bump patch and rebase to get this merged in.

**Comment by cirocosta** [comment]
Hey, with https://github.com/helm/charts/pull/10766 I'd say we can get rid of it - I incorporated the changes there.

Thanks, @Eronarn!

**Pull request closed without merging**
