### PR TITLE
Add replicas for redis master.

### PR DESCRIPTION
**Pull request by OGKevin**
This introduces a way to have more redis masters in a cluster. This also
opens the possibility to have a different setup then master slave.
Instead of deploying x helm deployments, one could deploy one with more
replicas.

#### What this PR does / why we need it:
 As explained above, it allows one to set the number af replicas for the redis master if they just one more separate redis instances rather than making 3 redis releases.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by juan131** [comment]
Using your branch, I've being testing you changes.

- Install chart:

```bash
$ helm install stable/redis --name redis --set master.replicas=2
$ kubectl get pods -l app=redis,role=master -o json | jq -r '.items[].status.podIP'
172.17.0.9
172.17.0.10
```

- Create a Redis Client port:

```bash
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)
$ kubectl run --namespace default redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:4.0.14 -- bash
```

- Connect to both Redis pods and check REDIS INFO:

```bash
I have no name!@redis-client:/$ redis-cli -h 172.17.0.9 -a $REDIS_PASSWORD
...
Warning: Using a password with '-a' option on the command line interface may not be safe.
172.17.0.9:6379> INFO
# Replication
role:master
connected_slaves:1
slave0:ip=172.17.0.8,port=6379,state=online,offset=476,lag=0
master_replid:7c735c51ea6b5f6ad6d487bda7401fa62673e4d5
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:476
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:476
...
172.17.0.9:6379> exit
I have no name!@redis-client:/$ redis-cli -h 172.17.0.10 -a $REDIS_PASSWORD
Warning: Using a password with '-a' option on the command line interface may not be safe.
172.17.0.10:6379> INFO
...
# Replication
role:master
connected_slaves:0
master_replid:27447f740cde6f48070498c5360b2fd156ef2366
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
...
172.17.0.10:6379> exit
```

As you can see the master nodes are not talking to each other since and they're not creating any cluster. One says it has one replica while the other doesn't show any replicas.

That's why this configuration is not going to work. The master nodes haven't been configured to work as a cluster and they act as totally separate master nodes.

**Review by juan131 — CHANGES_REQUESTED** [review]
Using your branch, I've being testing you changes.

- Install chart:

```bash
$ helm install stable/redis --name redis --set master.replicas=2
$ kubectl get pods -l app=redis,role=master -o json | jq -r '.items[].status.podIP'
172.17.0.9
172.17.0.10
```

- Create a Redis Client port:

```bash
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)
$ kubectl run --namespace default redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:4.0.14 -- bash
```

- Connect to both Redis pods and check REDIS INFO:

```bash
I have no name!@redis-client:/$ redis-cli -h 172.17.0.9 -a $REDIS_PASSWORD
...
Warning: Using a password with '-a' option on the command line interface may not be safe.
172.17.0.9:6379> INFO
# Replication
role:master
connected_slaves:1
slave0:ip=172.17.0.8,port=6379,state=online,offset=476,lag=0
master_replid:7c735c51ea6b5f6ad6d487bda7401fa62673e4d5
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:476
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:476
...
172.17.0.9:6379> exit
I have no name!@redis-client:/$ redis-cli -h 172.17.0.10 -a $REDIS_PASSWORD
Warning: Using a password with '-a' option on the command line interface may not be safe.
172.17.0.10:6379> INFO
...
# Replication
role:master
connected_slaves:0
master_replid:27447f740cde6f48070498c5360b2fd156ef2366
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
...
172.17.0.10:6379> exit
```

As you can see the master nodes are not talking to each other since and they're not creating any cluster. One says it has one replica while the other doesn't show any replicas.

That's why this configuration is not going to work. The master nodes haven't been configured to work as a cluster and they act as totally separate master nodes.

**Comment by OGKevin** [comment]
@juan131 this is the setup that i was trying to get indeed, i could either deploy x helm releases or just increase the replica count. 

Maybe what we can do is add another flag to enable clustering for master-master or not.  Or any other suggestions?

**Comment by juan131** [comment]
I think you're looking for Redis HA (https://github.com/helm/charts/tree/master/stable/redis-ha). This is a different chart that uses a different topology for Redis.

**Comment by OGKevin** [comment]
@juan131 ah thanks. Then this PR can be closed. My apologies.

**Pull request closed without merging**
