### PR TITLE
[stable/nginx-ingress] update to use the correct argument name, fixes #730

### LINKED ISSUE #730: [stable/nginx-ingress] Upcoming 0.9.0 renames --nginx-configmap to --configmap
Jumping the gun a little, here, but I'm attempting to install the `0.9.0-beta.2` tag of the nginx ingress controller using the `stable/nginx-ingress` chart. Unfortunately, upstream has renamed the `--nginx-configmap` flag to `--configmap` in that version, a name which the chart currently hard-codes.

Should I add a `controller.configMapArg` value to the chart? Is there a more elegant approach?

### PR DESCRIPTION
**Pull request by egeland**
Note that this is for the beta version of the nginx-ingress controller

### CODE REVIEW

**Comment by chancez** [comment]
Do you think this could be done in a more backwards compatible way? Perhaps you can not update the image tag since it's still beta, and instead add a condition in the template like:

```
{{- if (contains "0.9." .Values.controller.image.tag) }}
            - --configmap={{ .Release.Namespace }}/{{ template "controller.fullname" . }}
{{- else }}
            - --nginx-configmap={{ .Release.Namespace }}/{{ template "controller.fullname" . }}
{{- end }}
```

I think it might be worth it since nginx-ingress is so heavily used, and some users might be running an older version but want the latest version of the chart. Not sure if its worth it, but just a potential option to break less people, and still allow them to upgrade their nginx-ingress chart.

**Comment by egeland** [comment]
I was thinking almost exactly the same thing, just after submitting the PR.
I'll tweak it early next week.

**Comment by mgoodness** [comment]
@chancez That's an interesting solution. There's an [open issue](https://github.com/kubernetes/helm/issues/2035) for Helm 2.3 that would add an `app_version` field to `Chart.yaml`. The assumption until now has been that a chart version is (loosely) tied to an application version. I think it's worth considering how an approach like this might impact that relationship.

**Comment by chancez** [comment]
@mgoodness Yeah, I think `app_version` will be nice, but likely not enough to handle all cases. As intentionally proposed. I chimed in on that issue making my point.

Sometimes an app may be composed of multiple containers, and they each have different versions and thus different compatibility needs. If the chart author wants to maintain compatibility, you would need a version per chart, which I think at this point is fairly introspectable via `app.image.tag` or something of the sort.

**Comment by egeland** [comment]
Maybe I'll hold off on this change until we have `app_version` (or some other semver implementation) in the charts..?

**Comment by chancez** [comment]
Well, I don't think we necessarily should wait for that (I think it'll be a while). The chart is still pre 1.0, so I think we could either go with what you have, or take a best effort approach to handle 0.8.x and 0.9.x. I don't think its a huge deal either way, but I just wanted to make the suggestion.

**Comment by egeland** [comment]
I'll make the change you suggested, then - and we can always fine-tune it later, as SemVer becomes available in the templating..

**Comment by mgoodness** [comment]
@egeland

I took the liberty of adding the conditional that @chancez suggested. Also added conditionals around the tcp & udp arguments to (hopefully - I haven't tested it yet) address https://github.com/kubernetes/ingress/issues/443. Finally, I'd like to keep the default image tag `0.8.3`.

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Comment by mgoodness** [comment]
Can finally confirm this works as expected with 0.8.3 and 0.9.0-beta.3.

**Comment by egeland** [comment]
Thanks for jumping in - I didn't get around to looking at this (obviously).. 😄

**Pull request merged**
