### PR TITLE
[stable/grafana] Update to Grafana 7.1.5

### PR DESCRIPTION
**Pull request by smcavallo**
#### What this PR does / why we need it:
Upgrade to the latest grafana

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X ] Chart Version bumped
- [X ] Variables are documented in the README.md
- [X ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by davidkarlsen** [comment]
This chart is deprecated: https://github.com/helm/charts/pull/23662
Please submit PRs against: https://github.com/grafana/helm2-grafana

**Pull request closed without merging**
