### PR TITLE
[stable/prometheus-blackbox-exporter] remove replicas and strategy keys from daemonset template

### LINKED ISSUE #21811: [stable/prometheus-blackbox-exporter] DaemonSet template is wrong
**Describe the bug**
DaemonSet template for Blackbox is wrong: contains "replicas" and "strategy" fields, which are not part of DaemonSet spec (guessing c/p error) and should be removed.

**Version of Helm and Kubernetes**:
K8S   v1.15.3
Helm v3.1.2

**Which chart**:
stable/prometheus-blackbox-exporter v.3.4.0 (latest as of writing)

**What happened**:
Error templating Chart

**What you expected to happen**:
Clean install

**How to reproduce it** (as minimally and precisely as possible):
Deploy Blackbox chart as DaemonSet

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by maxpain**
#### Is this a new chart
No.

#### What this PR does / why we need it:
Fixes DaemonSet template.

#### Which issue this PR fixes
  - fixes #21811

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks!
/assign
/ok-to-test

**Comment by Maxpain177** [comment]
Thanks :)

**Pull request merged**
