### PR TITLE
[stable/verdaccio] Fixes #9014 - Adds customConfigMap option into the verdaccio charts

### LINKED ISSUE #9014: stable/verdaccio chart does not honor customConfigMap option
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.11.0
K8S: 2.10.2

**Which chart**:
stable/verdaccio

**What happened**:
The docs for verdaccio describe overriding the default config using a configmap and specify a chart option of `customConfigMap` for that purpose. However, the chart code does not actually use `customConfigMap` and always uses the default config map.

ie. the following command, according to the docs, should use a custom config map:
```helm install --name my-release --set customConfigMap=verdaccio-config stable/verdaccio```

However, when inspecting the output, verdaccio is built with the default config map.

**What you expected to happen**:
When installing using a custom config map, the deployed assets reference that config at runtime.

**How to reproduce it** (as minimally and precisely as possible):
```helm install --name my-release --set customConfigMap=verdaccio-config stable/verdaccio```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by jeckhart**
#### What this PR does / why we need it:
Fixes #9014 by adding customConfigMap option into the verdaccio charts

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #9014 

#### Special notes for your reviewer:
@etiennetremel - I tested this locally on a new deploy of verdaccio using a custom config map.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jeckhart** [comment]
@viglesiasce @mgoodness can I get an /ok-to-test on this? It's a simple change that tests well on my machine and resolves a feature that is documented but not actually implemented.

**Comment by jeckhart** [comment]
@viglesiasce @mgoodness @foxish this PR has been sitting for 8 weeks now. If there is a step we should take to get this reviewed that I've missed, please let me know. Otherwise, can you take a look?

**Comment by jeckhart** [comment]
@davidkarlsen it looks like you approved the last Verdaccio update. Can you take a look here and, if all is well, apply a /lgtm label please?

**Comment by jeckhart** [comment]
@davidkarlsen it looks like you approved the last Verdaccio update. Can you take a look here and, if all is well, apply a /lgtm label please?

**Comment by jeckhart** [comment]
bump

**Review by etiennetremel — APPROVED** [review]

**Comment by davidkarlsen** [comment]
Why bother with an alternative configmap? Can't the values simply be put into the valuesfile under the key `configMap`?

**Comment by davidkarlsen** [comment]
No feedback and seems obsolete - closing
/close

**Pull request closed without merging**
