### PR TITLE
[stable/postgresql] evaluate the service's annotations as a template

### PR DESCRIPTION
**Pull request by vbehar**
#### What this PR does / why we need it:

update the service template to evaluate the annotations as a template, to allow people to use dynamic values in annotations key or values.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thank you very much, @vbehar. Could you please add the same comment you added to the `values.yaml` to the `values-production.yaml` too?

**Comment by vbehar** [comment]
@alemorcuq ok done, I also rebased on master

**Comment by carrodher** [comment]
Thanks for the contribution @vbehar and @alemorcuq for the review.

**Pull request merged**
