### PR TITLE
[stable/neo4j] Add License agreement in replica pod too

### PR DESCRIPTION
**Pull request by tomahawk28**
**What this PR does / why we need it**:
Fixing issue in #6577, 
When Neo4j has been set up with Replica pods in helm, it crushed since it does not contain a license agreement inside of it. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixing issue in #6577

**Special notes for your reviewer**:
To perform regression test, 
1. Type below cmd then you will get a timeout,  
`helm install stable/neo4j --debug --wait --name neo-helm  --set authEnabled=true --set acceptLicenseAgreement=yes --set readReplica.numberOfServers=1`

When you check `kubectl get po -w `, you will see that Replica pod had crushed already. 
```
NAME                                      READY     STATUS             RESTARTS   AGE
neo-helm-neo4j-core-0                     1/1       Running            0          3h
neo-helm-neo4j-core-1                     1/1       Terminating        0          3h
neo-helm-neo4j-replica-7b548b5f68-5jfcn   0/1       CrashLoopBackOff   5          3h
source-ip-app-8687dbf9f-p6wz6             1/1       Running            0          13d
```

2. Get this PR changes, and type as below. 
`helm install ./charts/stable/neo4j --debug --wait --name neo-helm  --set authEnabled=true --set acceptLicenseAgreement=yes --set readReplica.numberOfServers=1 # or type upgrade instead of install`
Do again, `kubectl get po - w` then Replica pod is running at this moment. 
```NAME                                      READY     STATUS    RESTARTS   AGE
neo-helm-neo4j-core-0                     1/1       Running   0          3h
neo-helm-neo4j-core-1                     1/1       Running   0          3h
neo-helm-neo4j-core-2                     1/1       Running   0          3h
neo-helm-neo4j-replica-6f97b6b8d8-mj9gb   1/1       Running   0          3h```

### CODE REVIEW

**Comment by tomahawk28** [comment]
cc>  @moxious @mneedham

**Comment by moxious** [comment]
While I'm not a maintainer, I have worked with this chart quite a bit and LGTM

**Comment by tomahawk28** [comment]
@mattfarina @foxish Can you review this?

**Comment by tomahawk28** [comment]
@mneedham would you mind to review it please? :)

**Comment by tomahawk28** [comment]
@unguiculus @rjaxin would you mind to review it please?

**Comment by tomahawk28** [comment]
I'm not sure why bot not merge this

**Pull request merged**
