### PR TITLE
[incubator/vault]: allow adding service type as nodeport with predefi…

### PR DESCRIPTION
**Pull request by sssd-dev**
…ned nodeport value

Signed-off-by: Mukesh Sharma <mukeshsh@outlook.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mattfarina** [comment]
@sssd-dev Thanks for the pull request. Can you please rebase from master and increment the chart version in the `Chart.yaml` file.

**Comment by sssd-dev** [comment]
@mattfarina I have rebased as per Master and also added the variable in Readme

**Comment by mattfarina** [comment]
@sssd-dev Can you please sign the commits. Please see the checks tab on the pull request for details on how to do this.

**Pull request closed without merging**
