### PR TITLE
[stable/home-assistant] added token support for servicemonitor

### PR DESCRIPTION
**Pull request by runningman84**
#### What this PR does / why we need it:
* added token support for servicemonitor
* bumped version
* changeed maintainer email

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [] Chart Version bumped
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by runningman84** [comment]
@billimek do you have an idea why the e2e test failed?

**Comment by runningman84** [comment]
/retest

this seems to be an e2e bug:
```
I0401 03:09:32.564] Installing chart 'home-assistant => (version: "0.12.5", path: "stable/home-assistant")'...
I0401 03:09:35.545] Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0401 03:09:35.545] ========================================================================================================================
I0401 03:09:35.545] ........................................................................................................................
I0401 03:09:35.545] ==> Events of namespace home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1
I0401 03:09:35.546] ........................................................................................................................
I0401 03:09:35.941] No resources found in home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1 namespace.
I0401 03:09:35.942] ........................................................................................................................
I0401 03:09:35.942] <== Events of namespace home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1
I0401 03:09:35.942] ........................................................................................................................
I0401 03:09:36.317] ========================================================================================================================
I0401 03:09:36.318] Deleting release 'home-assistant-dles9fe8z1'...
I0401 03:09:37.209] Error: release: "home-assistant-dles9fe8z1" not found
I0401 03:09:37.209] Error deleting Helm release: Error waiting for process: exit status 1
I0401 03:09:37.210] Deleting namespace 'home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1'...
I0401 03:09:37.749] Error from server (NotFound): namespaces "home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1" not found
I0401 03:09:37.753] Namespace 'home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1' did not terminate after 180s.
I0401 03:09:38.298] Namespace 'home-assistant-presubmit-21706-1245186001035333632-dles9fe8z1' terminated.
```

**Comment by billimek** [comment]
@runningman84 indeed yes, the e2e testing infrastructure appears to be having trouble right now after looking at other recent PRs with the same error.  I reached out on slack to one of the charts repo maintainers for help.

I think all we can do at this moment is wait for things to get fixed.

**Pull request merged**
