### PR TITLE
[stable/redis] exporter to 1.0.3

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
There are some changes, mostly in metrics name, should we advertise this? 
/assign 
/ok-to-test

**Comment by naseemkullah** [comment]
Good idea. I've added some notes. Feel free to edit them to your liking!

**Comment by javsalgar** [comment]
Thanks for the PR

/lgtm

**Comment by naseemkullah** [comment]
My pleasure.

**Pull request merged**
