### PR TITLE
[stable/concourse] set keepNamespaces to false when testing on ci

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
I was doing some maintenance in the CI for Helm and notice the concourse created a bunch of namespaces and those are not used.

I saw in the values there is an option to delete those namespaces when deleting the chart.
Adding a ci test to use that to test and remove the namespace after since we don't need those hanging around in the CI cluster.

@cirocosta if you think we can set that to false in the values I can change as well

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by cirocosta** [comment]
Hi @cpanato,

That's true, as it was, it'd indeed leave a bunch of namespaces behind :grimacing: Sorry!

Regarding setting the default value of `concourse.web.kubernetes.keepNamespaces` to `false`, I'd not do it just in order to not break possible expectations without a separate issue for it so we can gather some feedback from those using it beforehand.

I've personally never received feedback regarding setting that as a default value though. Feel free to open an issue!

Thanks!

**Comment by cpanato** [comment]
@cirocosta thanks, I think we can keep the values.yaml as is, dont see any issues.

thanks again for reviewing!

**Pull request merged**
