### PR TITLE
[stable/mongodb] feature: explicit service name

### PR DESCRIPTION
**Pull request by cspengl**
#### What this PR does / why we need it:

This PR adds the option to define a hard coded service name. This isn't a good practice in general but can be quite useful for special scenarios. (Referring to [Helm Chart Best Practices](https://github.com/helm/helm/blob/master/docs/chart_best_practices/templates.md#resource-naming-in-templates)).
In this case it could be useful to have a "release-independent" service name to tell other applications where to connect with the database. The option is disabled per default and everything works like before - just an additional option.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cspengl** [comment]
Hi, could anybody help me with the failing checks?

- **DCO check:**
  When I go to the one commit which is missing the signoff it seems to me that is signed off. What is wrong with the signature?
- **Linting:**
  Linting fails because of trailing spaces in the values.yaml file. But what I did there was just disabling the option. What do you recommend?

**Comment by cspengl** [comment]
Ok, well I forgot to sign off one of the commits. I rebased and amended it, tried a --force-with-lease push but the commit is still not updated on the remote. Could anybody give me a hint how to do this? Is it maybe easier to create a new PR ?

**Comment by juan131** [comment]
To be honest, it's much easier to create a new PR. I'd do that and close this PR

**Comment by cspengl** [comment]
Ok, great. I will close it and create a new one soon. Thank you very much!

**Pull request closed without merging**
