### PR TITLE
[stable/home-assistant] Small fix and enhancements

### PR DESCRIPTION
**Pull request by bjw-s**
#### What this PR does / why we need it:
This PR fixes / enhances a few aspects of the _stable/home-assistant_ chart:
- It is now possible to define the `externalTrafficPolicy` field for services with type `LoadBalancer`. This is required to let Home Assistant know the "real" IP address when using something like [MetalLB](https://metallb.universe.tf/usage/).
- The `git-secret` Secret was only mounted for the `configurator` and `appdaemon` containers, but not for `vscode`. This has been added to allow git commits from that container as well.
- It is now possible to set the author and email used for Git commits through the `git.user` variables.
- In the previous version it was only possible to specify a list of single secret keys to be used as environment variables. It is now possible to specify an entire secret through the `extraSecretForEnvFrom` variable.

#### Special notes for your reviewer:
@billimek @runningman84

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

Signed-off-by: Bernd Schorgers <bernd@bjws.nl>

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by billimek** [comment]
/lgtm

Thanks for these chart improvements!

**Comment by billimek** [comment]
FYI, I believe that this change introduced a problem.  I just tried upgrading and helm threw the following error,

`upgrade failed: template: home-assistant/templates/deployment.yaml:270:53: executing \"home-assistant/templates/deployment.yaml\" at <.Values.git.user.name>: nil pointer evaluating interface {}.name`.

Digging into this now and will try to submit a patch if necessary.

**Comment by Juggels** [comment]
That's odd, I thought that would be covered by the `{{- if and (.Values.git.enabled) (.Values.git.user.name) }}`. Or could it be because the `user:` section is commented by default, and therefore Helm cannot resolve the check on the subfield?

**Pull request merged**
