### PR TITLE
[incubator/mysqlha] Add imagePullPolicy for every container in the pod

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

#### What this PR does / why we need it:

All containers' pull policy in the pod can be managed by `imagePullpolicy`field.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jpoon** [comment]
/approve

Obviously the versioning will conflict with the other PRs we have open against this chart:
https://github.com/helm/charts/pull/15354
https://github.com/helm/charts/pull/15348

Not sure if you want to just combine your two PRs to avoid this or wait until the other versions are merged first.

**Comment by Aisuko** [comment]
Thanks for your review. I would like to wait for other version merged first.

**Comment by Aisuko** [comment]
The feature was included in PR #15354. So, Close this one.

**Pull request closed without merging**
