### PR TITLE
[stable/cluster-autoscaler] Allow user to define aws cred using envir…

### PR DESCRIPTION
**Pull request by hsingh6764**
…onment variables

### CODE REVIEW

**Comment by hsingh6764** [comment]
Can anyone help me figure out why build is failing. 

Error: 
```
stable/cluster-autoscaler/values.yaml
  2:3       error    comment not indented like content  (comments-indentation)
  22:3      error    comment not indented like content  (comments-indentation)
  46:3      error    comment not indented like content  (comments-indentation)

Exited with code 1
```
I did not touch those lines part of this pull request, so should I fix them or is there bug with the build script.

**Comment by hsingh6764** [comment]
@mgoodness please let me know if i can help any way
I also have the same issue with https://github.com/kubernetes/charts/pull/2466

**Comment by mumoshu** [comment]
@hsingh6764 Hi!
Would you mind if I ask about your motivation for this improvement?

This way, it seems like anyone who is able to run `kubectl get po` can obtain an AWS credential which is pretty permissive - at least one can terminate any EC2 instance managed by ASGs managed by CA with the cred.

If I were you I would run CA more safely by utilizing `kube2iam`, or instance profiles attached to EC2 instances.
WDYT?

**Comment by hsingh6764** [comment]
@mumoshu i agree the secret can been seen when running kubectl and I agree i can use kube2iam as well. But Instance profile is not good idea since profile will be provided to all instances in cluster. 

But this provides quick and easy way to start off. 

I can update the pull request to move secret into secret and use ref.

**Review by mgoodness — CHANGES_REQUESTED** [review]
I think a Secret is a much better way to approach this.

**Comment by mumoshu** [comment]
@hsingh6764 Thanks for the explanation. I agree with every point 👍 

> I can update the pull request to move secret into secret and use ref.

That would be nice.

**Comment by mgoodness** [comment]
Any update? We can use the same pattern for creating/using a Secret as in https://github.com/kubernetes/charts/tree/master/stable/kube2iam and https://github.com/kubernetes/charts/tree/master/stable/external-dns.

Marking as stale for now.

**Comment by viglesiasce** [comment]
Closing as stale.

**Pull request closed without merging**
