### PR TITLE
[incubator/aws-alb-ingress-controller] Add volumes/volumeMounts option to aws-alb-ingress-controller

### PR DESCRIPTION
**Pull request by cw-sakamoto**
Signed-off-by: cw-sakamoto <sakamoto@chatwork.com>

#### What this PR does / why we need it:
- I use [kube-aws-iam-controller](https://github.com/mikkeloscar/kube-aws-iam-controller) for attach iam role to application
- This tools needs `volumes` and `volumeMounts`, so I add `volumes/volumeMounts` option

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by cw-sakamoto** [comment]
@M00nF1sh Thanks for maintenance of this charts! Please review this PR.

**Comment by M00nF1sh** [comment]
@cw-sakamoto Hi, thanks for making this change.
But I wonder is the 'meta/aws-iam' ever going to work?  since the controller will looks for credentials from ec2MetaData / environment variables.
If you want to assign roles to controller, you should be able to use kube2iam or kiam.  And we are working on a IAM solution based on serviceAccount.

**Comment by cw-sakamoto** [comment]
@M00nF1sh Thanks for your comment!
It is possible to use a credential file by using environment variables(`AWS_SHARED_CREDENTIALS_FILE`) as well. I confirmed with this PR that it works with this settings.yaml.

```
extraEnv:
  AWS_SHARED_CREDENTIALS_FILE: /meta/aws-iam/credentials

volumeMounts:
  - name: aws-iam-credentials
     mountPath: /meta/aws-iam
     readOnly: true

volumes: 
  - name: aws-iam-credentials
     secret:
       secretName: alb-ingress-controller-role
```

>  you should be able to use kube2iam or kiam. And we are working on a IAM solution based on serviceAccount.

Sure, kiam/kube2iam is useful tool, and we used to use kiam. but we troubled [this problem](https://github.com/mikkeloscar/kube-aws-iam-controller#ec2-metadata-service-solution-kube2iam) with kiam/kube2iam some times, now we use kube-aws-iam-controller.

This tools is secrets controller for aws iam role credential with `sts:assumerole`,so the issued credential has an expiration time, it is the same as kiam/kube2iam.

**Comment by cw-sakamoto** [comment]
@M00nF1sh 
I think that `volumeMounts/volumes` itself is a common option, so can I delete the comments for `kube-aws-iam-controller` from values.yaml?

**Comment by mumoshu** [comment]
@M00nF1sh Hey! Thanks as always for providing the world's greatest cloud ☺️ 

Just wanted to chime-in to express that I wish PRs like this to get merged to any charts related to AWS IAM.

I have some experience maintaining multiple K8s clusters on AWS myself, and heard from various experiences from [kube-aws](https://github.com/kubernetes-incubator/kube-aws) users while maintaining the project.

That being said, practically, EC2 Metadata Service or it's proxy(kube2iam, kiam) turned out to add more latencies and give us less availability compared to "local files" containing AWS credentials. And that's exactly [kube-aws-iam-controller](https://github.com/mikkeloscar/kube-aws-iam-controller) provides :)

Not saying kube2iam or kiam, or even your serviceaccount-based solution, is bad. They are/would be actually great tools. I've used both kube2iam and kiam in production for years.

It is just that focusing on latencies and availability, kube-aws-iam-controller seems superior to me(and maybe @cw-sakamoto). In other words, a PR like this allows us to use AWS IAM better in some regards.

**Comment by M00nF1sh** [comment]
@mumoshu @cw-sakamoto 
This seems the only usecase for volume mounts, and for such use case,  I would suggest use the following instead(which uses k8s's downwards API):
```
- name: AWS_ACCESS_KEY_ID
   valueFrom:
   secretKeyRef:
         name: aws-secret
         key: key_id
         optional: true
- name: AWS_SECRET_ACCESS_KEY
   valueFrom:
   secretKeyRef:
          name: aws-secret
          key: access_key
          optional: true
```
BTW, I don't recommend to use fixed credentials like that:
        1. it's not secure to store aws credentials as secret(wrong RBAC configuration will leak it)
        2. it's generally a best practice to use IAM role instead of IAM user(static credentials without rotation is bad)

**Comment by mumoshu** [comment]
@M00nF1sh Hey! Thanks for your response.

>  I don't recommend to use static credentials like that

Definitely! That's why we might want to use kube-aws-iam-controller 😄 

The controller periodically fetch temporary AWS creds, writes it to K8s secret, and ROTATEs it. K8s "periodically" syncs the secret to the volume so that you can have the good latency and reliability of the creds on local disk, while rotating creds for security.

**Comment by mumoshu** [comment]
So with kube-aws-iam-controller,

> 1. it's not secure to store aws credentials as secret(wrong RBAC configuration will leak it)

That's true, but kube2iam and kiam suffers from other type of misconfigurations like wrong "namespace" annotation(they use it to limit to role access per k8s ns), or even wrong pod annotation(you can't restrict annotation by RBAC) leaks creds! So kube-aws-iam-controller can be better in regard to your point on RBAC misconfigs.

> 2. it's a best practice to use IAM role instead of IAM user(static credentials without rotation is bad)

kube-aws-iam-controller uses IAM role :) It assumes IAM role to obtain temporary creds, and that's the same as kube2iam and kiam.

**Comment by cw-sakamoto** [comment]
@M00nF1sh
Could you confirm this PR...?

**Comment by M00nF1sh** [comment]
> @M00nF1sh
> Could you confirm this PR...?

Hi, I'm good to approve this CR.  As I can see the prow is using similar mechanism to mount AWS Secrets: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-aws/sig-aws-credentials.yaml#L20

But I'm not sure if the secretKeyRef can handle this case as well, mainly whether it can handle credentials rotation. haven't got time to test it out yet.
 like the way i commented above:
```
- name: AWS_ACCESS_KEY_ID
   valueFrom:
   secretKeyRef:
         name: aws-secret
         key: key_id
         optional: true
- name: AWS_SECRET_ACCESS_KEY
   valueFrom:
   secretKeyRef:
          name: aws-secret
          key: access_key
          optional: true
```

**Comment by cw-sakamoto** [comment]
@M00nF1sh Thanks for your reply!

> if the secretKeyRef can also handle credentials rotation,

I have tested this method but environment value not change for credentials rotation...

**Comment by mumoshu** [comment]
@M00nF1sh Sorry for being intrusive! But thanks again for maintaining the chart :bow:

**Pull request merged**
