### PR TITLE
[stable/metrics-server] Upgrade app version to 0.3.7

### PR DESCRIPTION
**Pull request by Constantin07**
#### Is this a new chart
No

#### What this PR does / why we need it:
Upgrades metrics-server to the latest version 0.3.7

#### Which issue this PR fixes
Run image as non-root user.
More details on changes https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.3.7

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Constantin07** [comment]
I can see metrics with the new version on test cluster:
```
# kubectl top node
NAME                    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
master-node1.internal   183m         11%    892Mi           59%
master-node2.internal   190m         11%    776Mi           52%
worker-node1.internal   138m         8%     804Mi           52%
worker-node2.internal   118m         7%     695Mi           45%

```

**Comment by olemarkus** [comment]
Arm support. Cool.
/lgtm

**Comment by Constantin07** [comment]
looks like it fails here:
```
I0813 05:15:00.778] Error linting and installing charts: Error processing charts
I0813 05:15:00.778] ------------------------------------------------------------------------------------------------------------------------
I0813 05:15:00.778]  âœ–ï¸Ž metrics-server => (version: "2.11.2", path: "stable/metrics-server") > Error waiting for process: exit status 1
I0813 05:15:00.779] ------------------------------------------------------------------------------------------------------------------------
I0813 05:15:01.437] 2cf09bd28b0912ba1cfa2a160dff04321ff9307a1c974c33cfc8f097c740926d
W0813 05:15:01.467] Traceback (most recent call last):
W0813 05:15:01.467]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0813 05:15:01.467]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0813 05:15:01.467]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0813 05:15:01.467]     check(*cmd)
W0813 05:15:01.467]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0813 05:15:01.468]     subprocess.check_call(cmd)
W0813 05:15:01.468]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0813 05:15:01.468]     raise CalledProcessError(retcode, cmd)
W0813 05:15:01.468] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0813 05:15:01.468] Command failed
I0813 05:15:01.468] process 638 exited with code 1 after 1.4m
E0813 05:15:01.469] FAIL: pull-charts-e2e
```

**Comment by Constantin07** [comment]
Any idea why the `pull-charts-e2e` fails ? I cannot understand why it fails.

**Comment by olemarkus** [comment]
Usually it is the test that fails. See `templates/tests/test-version.yaml` what it tries to do.

**Comment by Constantin07** [comment]
> Usually it is the test that fails. See `templates/tests/test-version.yaml` what it tries to do.

Thanks, looks like the reason for fail is https://github.com/kubernetes-sigs/metrics-server/issues/574

**Pull request closed without merging**
