### PR TITLE
[stable/oauth2-proxy] Upgrade to v5.1.0.

### PR DESCRIPTION
**Pull request by desaintmartin**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by Miouge1 — CHANGES_REQUESTED** [review]
Looks good, but you would also need to update the default value in README.md

**Comment by desaintmartin** [comment]
My bad, fixed.

**Comment by desaintmartin** [comment]
Dear bot, could you:
/retest
to see if test cluster is now available?

**Comment by cpanato** [comment]
we had an issue in the cluster, that is fixed now, sorry for the trouble

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
