### PR TITLE
refactor chart version in order to stay with appVersion

### LINKED ISSUE #1501: istio chart version should ideally not get ahead of istio version
**Which chart**:
https://github.com/kubernetes/charts/blob/master/incubator/istio/Chart.yaml

**What happened**:
it says 0.3.0

**What you expected to happen**:
it's confusing to istio users as the istio latest release is 0.1.6, work is on the way for 0.2.x and planned for 0.3.x this makes it seem 0.3.0 is already out

can we have the chart version be 4 digits, the first 3 would be the istio version and a fourth digit for revisions of the chart itself ?

### PR DESCRIPTION
**Pull request by lachie83**
Fixes #1501

### CODE REVIEW

**Review by ldemailly — APPROVED** [review]
❤️ing it !

**Comment by viglesiasce** [comment]
I'm assuming since this is in incubator we don't care that it cant be upgraded to?

**Comment by lachie83** [comment]
Currently yes. I would like to get it "right" then we can move forward. Thoughts?

**Pull request merged**
