### PR TITLE
[stable/postgresql] explicitly use ipv4 for probes

### LINKED ISSUE #13072: [stable/postgresql] probes use ipv6 which creates istio<1.1 incompatibility
Refs https://github.com/istio/istio/issues/10733

### PR DESCRIPTION
**Pull request by tmc**
Fixes #13072

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign your existing commits](https://github.com/apps/dco), you can find custom instructions in the “Details” link from the below DCO check, also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by tmc** [comment]
@carrodher Why is DCO enforced on this repo? Can the contribution guidelines just state that via policy?

**Comment by carrodher** [comment]
> @carrodher Why is DCO enforced on this repo? Can the contribution guidelines just state that via policy?
This is explained in the _CONTRIBUTING.md_ file, specifically in [this section](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work). In the same way, you can find more information about DCO bot in this link https://probot.github.io/apps/dco/

**Pull request merged**
