### PR TITLE
adding component label on pod

### PR DESCRIPTION
**Pull request by ruehowl**
Signed-off-by: Rahul Varghese <rahul.varghese@qlik.com>

#### What this PR does / why we need it:

Adding `component` label as `server` in the deployments.yaml. Having a component label is fairly common practice is helm charts.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@ruehowl please rebase your branch and fix the conflict.

**Comment by ruehowl** [comment]
> @ruehowl please rebase your branch and fix the conflict.
Good to go now. 👍 
> the component is useful when you have other deployments or stateful set together in the same chart, like a front-end database ... looks like here is not the case

That is correct. The use case here is when it comes to metrics discovery and especially Prometheus setup.  Optional labels like `component` are commonly used for Job labeling and discovering metrics for `services` by Prometheus. Since chaoskube does not need/have a service object, having the `component` label will help set up Prometheus metrics for pods and treat it similar as a service.
i.e, we can rewrite the value label __meta_kubernetes_service_name with <release>-<app><componet>.
The fact that chaoskube does not have a service endpoint make it difficult to accommodate it with a service metrics monitoring system. It seems having a `component` label can avoid this gap by making some mapping in Prometheus configuration and effectively treat the metrics coming out of chaoskube similar to the metrics form any service endpoints.

**Comment by linki** [comment]
@ruehowl Would it make sense to rather have a `Service` object? I remember that Services sometimes were used solely for the purpose of discovering metrics endpoints (e.g. https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/external-dns/external-dns-svc.yaml)

**Comment by ruehowl** [comment]
@linki Yes, creating a `service` object even just for discovering metrics endpoints is a better solution. This sounds perfect to me. 👍

**Pull request merged**
