### PR TITLE
Knative Helm Chart

### PR DESCRIPTION
**Pull request by tomleah**
#### What this PR does / why we need it:
This PR adds a community Knative Helm Chart.

#### Special notes for your reviewer:
We notice there is an existing Knative chart (https://github.com/helm/charts/pull/7268), however it has been marked stale. We have attempted to address the reviews/comments in this PR.

We have used subcharts to separate out different components that can be enabled/disabled in the various `values.yaml`.

```
knative                         (default)
├── build                       (default)
├── eventing
|   ├── gcpPubSubProvisioner
│   ├── inMemoryProvisioner
|   ├── kafkaProvisioner
│   └── natssProvisioner
├── serving                     (default)
│   └── monitoring              (default)
│       ├── elasticsearch       (default)
│       ├── prometheus          (default)
|       ├── zipkin
│       └── zipkinInMem         (default)
└── eventingSources
    ├── camel
    ├── eventDisplay
    └── gcpPubSub
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by sbezverk** [comment]
I do not think deploying CRD is a good idea, other projects example Istio encountered lots of issues when CRD deployment is controlled by Tiller. CRD deployment should be a prerequisite step deployed by something else, kubectl for example, before chart are used to deploy knative.

**Comment by obeyler** [comment]
@tomleah  Does it also contain Istio as dependency ?

**Comment by mhamwala** [comment]
@obeyler If I understand your question correctly, yes and no, Istio is mentioned in the readme's (except build) as a prerequisite, its not part of the chart itself

**Comment by tomleah** [comment]
@helm/charts-maintainers could you help with `lint-charts` failing?

**Comment by unguiculus** [comment]
@tomleah You need to fix the Git history. The PR has changes to 200 files across the whole charts repo.

**Comment by tomleah** [comment]
@unguiculus I believe all changes are in the `stable/knative` directory. The large amount of files is due to it being a new chart

**Comment by gyliu513** [comment]
@tomleah for such chart, I think the community encourage to put it into incubator folder, as knative is not mature yet.

@unguiculus please show your comments if any.

**Comment by tomleah** [comment]
Yes, I agree @gyliu513. Moving to incubator now

**Comment by tomleah** [comment]
Hi, I just wanted to check if anyone was reviewing this PR before making further changes.
We have an updated version of this chart (appVersion 0.5.0) that is simpler and more consistent that might be easier to review. 
Let me know if this is in-progress, otherwise we will push the update at the end of this week

**Comment by tomleah** [comment]
I have now updated this chart to the latest appVersion (0.5.2) and is ready for review

**Comment by maorfr** [comment]
hey @tomleah 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by zxDiscovery** [comment]
@tomleah The 0.6.0 knative has already released. Do we need to update the chart to 0.6.0 version?

**Comment by gyliu513** [comment]
@tomleah can you please add a OWNERS file as well like this: https://github.com/helm/charts/blob/master/stable/burrow/OWNERS , you can add @zxdiscovery as a maintainer as well and he can help on the future maintain of this chart.

**Comment by tomleah** [comment]
Thanks for pointing us to this @maorfr! We haven't considered this yet but looks like its something we should look into 🙂

**Comment by tomleah** [comment]
@zxDiscovery it would be good if the chart could be updated to the latest release. I would, however, like to work with the helm maintainers so that the review process can be made as easy as possible without that chart changing too frequently

**Pull request closed without merging**
