### PR TITLE
[stable/opa] Fixed the NOTES.txt to include the namespace in the port-forward command

### PR DESCRIPTION
**Pull request by tharakadesilva**
Signed-off-by: Tharaka De Silva <tharaka.uo@gmail.com>

#### What this PR does / why we need it:
Minor fix in the NOTES.txt file to add the namespace to the port-forward command. When OPA is installed to a namespace other than the default namespace, the information displayed for the port-porfward to view the default policies is inaccurate.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by tharakadesilva** [comment]
@tsandall I am unable to assign this PR to you, please take a look.

**Comment by zanhsieh** [comment]
@tharakadesilva 
I could only help to here. Only owners could merge.

cc @tsandall @timothyhinrichs

**Comment by tharakadesilva** [comment]
Thanks @zanhsieh!

**Pull request merged**
