### PR TITLE
[stable/postgresql] Fullname to be same as the chart name when chart and release name are same

### PR DESCRIPTION
**Pull request by ghost**
#### What this PR does / why we need it:
Now the fullname is the same as the chart name when chart and release name are the same.
This change is not backward-compatible but it's consistent with the rest of the charts.
Also fullnameOverride is possible now.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi. Thanks for the PR. Will this break any helm upgrade operation? If so, how should the user upgrade the chart?

**Comment by k1-hedayati** [comment]
Hi, It will not break the upgrade operation if their release name is different than the chart name. But if it's the same it might get a little complex and I need to add docs for migration plan.

**Comment by javsalgar** [comment]
Great, let us know when you add the documentation to the PR

**Comment by javsalgar** [comment]
Also, could you fix the merge issue?

**Comment by k1-hedayati** [comment]
Sure

**Comment by k1-hedayati** [comment]
I tested this PR in a cluster that there is already a Postgresql deployment with the same release name as chart name and it seems the `helm upgrade` will not work in this case because the name of the resources should be changed during the upgrade and there should be a manual intervention or deleting and reinstalling chart to make this work. 
It's possible to add warnings about this case in the documents or just close the PR because of the challenges this rare case will cause.

**Comment by carrodher** [comment]
Maybe we can include this change in other major changes in order to avoid several major changes.

**Comment by juan131** [comment]
I'm not very sure about this change... I agree it's consistent with the rest of the charts but I don't think it's worth enough to break backward compatibilities to introduce it.

**Pull request closed without merging**
