### PR TITLE
[stable/spinnaker] Clean spinnaker deployment only if halyard is available.

### LINKED ISSUE #22554: [stable/spinnaker] delete hangs if there was issue in creating halyard
**Describe the bug**
If the helm chart fails to create the halyard pod, the delete of the helm release hangs. 

**Version of Helm and Kubernetes**:
Helm version: 3.0.2
Kubernetes version: 1.15.11

**Which chart**:
stable/spinnaker

**What happened**:
Create a chart where halyard deployment does not succeed. In my case, the persistent storage had an issue. So, the chart install failed. Now, when I tried to delete the release of the chart, it hangs. 

**What you expected to happen**:
The failed installation of the chart to be deleted.

**How to reproduce it** (as minimally and precisely as possible):
If you have a case where halyard pod does not come up, it is easy to reproduce. One way to simulate halyard failing to come up may be to delete the halyard statefulset. 

**Anything else we need to know**:
What seems to be happening is that ```hal deploy clean -q``` fails and so the job also fails and keeps on trying!

### PR DESCRIPTION
**Pull request by Nirmalyasen**
Fixes #22554

Signed-off-by: Nirmalya Sen <nirmalya@opsmx.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #22554

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Nirmalyasen** [comment]
@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
@Nirmalyasen The conflicts need to be corrected so the tide test can pass

**Comment by Nirmalyasen** [comment]
Got messed up in new merge. 

Closing this and will raise a new one.

**Pull request closed without merging**
