### PR TITLE
[stable/fluent-bit] Enable tls for fluent-bit forward plugin

### PR DESCRIPTION
**Pull request by alexnguyen91**
#### What this PR does / why we need it:
- TLS support for `forward` plugin doesn't get configured

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@alexnguyen91 
Would you bump the chart version to latest please?

**Comment by alexnguyen91** [comment]
@zanhsieh sure, I'll just increase the patch number since this is not a big change.

**Comment by alexnguyen91** [comment]
Hello, could someone take a look ?

**Comment by zanhsieh** [comment]
@alexnguyen91 
Could you sign DCO please?
Instruction below on "Details" next to "Action required after 1s — DCO".

**Comment by alexnguyen91** [comment]
@zanhsieh done

**Pull request merged**
