### PR TITLE
[incubator/kafka] Fix schema registry dependency collision

### LINKED ISSUE #3729: [incubator/kafka] Install fails when `service-registry.enabled` is set to `true`
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.8.1, kubernetes 1.9.1

**Which chart**: incubator/kafka

**What happened**: Setting `service-registry.enabled` to `true` causes `helm install` to fail, appears to be due to two service definitions with the same name (see below)

**What you expected to happen**: Kafka to start with a schema registry instance

**How to reproduce it** (as minimally and precisely as possible):

```bash
$ helm install --name my-kafka --namespace kafka --set global.namespace=kafka -f my-kafka.yml incubator/kafka
Error: release my-kafka failed: services "my-kafka-zookeeper" already exists
```

`my-values.yml`:

```yaml
---
replicas: 1
schema-registry:
  enabled: true
```

Changing the enabled from true to false results in a successful run.

**Anything else we need to know**:

This appears to be because there are two service named "my-kafka-zookeeper" being defined (see below).

Debugging w/ `--dry-run --debug` you can see that there are two `Service` definitions named `my-kafka-zookeeper` in the generated YAML.

```bash
helm install --dry-run --debug --name my-kafka --namespace kafka --set global.namespace=kafka -f my-kafka.yml incubator/kafka
```
First service definition:

```yaml
---
# Source: kafka/charts/schema-registry/charts/kafka/charts/zookeeper/templates/service-clients.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kafka-zookeeper
  labels:
    app: "zookeeper"
    chart: "zookeeper-0.3.1"
    release: "my-kafka"
    heritage: "Tiller"
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: "zookeeper"
    release: "my-kafka"
```

Duplicate service definition:

```yaml
---
# Source: kafka/charts/zookeeper/templates/service-clients.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kafka-zookeeper
  labels:
    app: "zookeeper"
    chart: "zookeeper-0.4.4"
    release: "my-kafka"
    heritage: "Tiller"
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: "zookeeper"
    release: "my-kafka"

```

### PR DESCRIPTION
**Pull request by JMLizano**
Simple solution to fix #3729.
Just set the kafka dependency disabled by default to avoid schema-registry to pull Kafka dependency and cause a collision of services.

### CODE REVIEW

**Comment by eicnix** [comment]
Should the version of the schema-registry dependency in the kafka chart be bumped to this version in order to apply the fix to the kafka chart?

**Comment by unguiculus** [comment]
This seems a little hacky to me. It looks like Kafka would disable a dependency to itself. Is there no other way around this? There's obviously a circular dependency. Can't we fix that in the first place?

cc @benjigoldberg @faraazkhan @h0tbird

**Comment by benjigoldberg** [comment]
@unguiculus the difficulty is that if we remove the Kafka dependency in schema registry (if I recall correctly) we can’t get the tests to pass since it requires Kafka. Perhaps we just remove schema registry as an option in this chart altogether and point people to that chart as something they can install separately.

**Comment by JMLizano** [comment]
Yep @benjigoldberg is right. With the current helm dependency management (or at least what I know about it) I only see two solutions:

1. Remove Kafka dependency from schema-registry. This leads to schema-registry not to be able to be deployed by itself, relying on a previous existing Kafka deployment on the cluster.

2. Remove schema-registry dependency from Kafka chart, and as @benjigoldberg says point people to that chart in the documentation.

I prefer option 2, seems more consistent and complies with the technical requirements. Maybe if Helm dependency management changes in the future we can put the dependency back.

**Comment by eicnix** [comment]
@JMLizano I agree with your option 2. The schema registry requires Kafka and thus should depend on it while the schema-registry is only a third party tool for Kafka.

**Comment by JMLizano** [comment]
Just pushed new commit for the remove schema-registry as dependency solution. Also updated some outdated values on the README.md

**Comment by benjigoldberg** [comment]
LGTM @JMLizano @unguiculus 

Thanks for putting the PR together 👏

**Pull request merged**
