### PR TITLE
[stable/karma] Upgrade to 0.55

### PR DESCRIPTION
**Pull request by prymitive**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by prymitive** [comment]
updated to v0.53

**Comment by prymitive** [comment]
updated to v0.54

**Comment by prymitive** [comment]
updated to v0.55

**Comment by davidkarlsen** [comment]
Sorry for the delay!
/lgtm

**Pull request merged**
