### PR TITLE
[stable/datadog] add configuration for datadog intake server (#9715)

### PR DESCRIPTION
**Pull request by PaulCharlton**
[stable/datadog]

Signed-off-by: Paul Charlton <techguru@byiq.com>

This fixes Issue #9715 

============================================

The latest datadog agent allows configuration of the datadog intake server.

Summary of PR
Add chart values to configure the datadog intake server.
Add environment variable to templates to configure the datadog intake server.

### CODE REVIEW

**Review by CharlyF — APPROVED** [review]
We are waiting on https://github.com/helm/charts/issues/8787 to be reviewed for me to be able to approve. This looks good to me though. In the interim @xvello can you take a look ?

**Comment by PaulCharlton** [comment]
@xvello @hkaj any thoughts?

**Pull request merged**
