### PR TITLE
Add KubeDB chart

### PR DESCRIPTION
**Pull request by tamalsaha**
https://kubedb.com/

### CODE REVIEW

**Comment by unguiculus** [comment]
Please apply our RBAC best practices.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

**Comment by tamalsaha** [comment]
@unguiculus , can you please point to me which specific rules are you talking about? KubDB uses Kubernetes Extended API Server. This needs special permissions. I am following the pattern used by service catalog  chart https://github.com/kubernetes-incubator/service-catalog/tree/master/charts/catalog/templates

and https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/kube-install/apiserver-list.yaml.template

**Comment by tamalsaha** [comment]
If you are referring to user roles, there should be only one copy of those in a cluster. These are used to aggregate user roles in a cluster https://kubernetes.io/docs/admin/authorization/rbac/#user-facing-roles

**Comment by unguiculus** [comment]
I'm not talking about specific roles. Just the way we configure RBAC. Simply follow the guidelines.

**Comment by tamalsaha** [comment]
@unguiculus, I have updated the RBAC stuff to the best of my understanding. PTAL

**Pull request merged**
