### PR TITLE
[stable/mongodb-replica-set] Fix metrics livenessProbe and regression in securityContext

### PR DESCRIPTION
**Pull request by josqu4red**
#### What this PR does / why we need it:

* Fix indentation in metrics container's livenessProbe settings, preventing the manifests to be applied with metrics enabled
* Re-enable securityContext which was enabled by default before #10682 

@unguiculus @steven-sheehy 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by steven-sheehy** [comment]
Thanks, I wish we wouldn't have merged that last PR. Besides accidentally disabling securityContext, it also limits people from customizing other keys within securityContext like capabilities, etc.
/assign
/assign @unguiculus 
/ok-to-test

**Comment by unguiculus** [comment]
Good points @steven-sheehy. I agree we shouldn't have merged it. Should we revert it?

**Comment by steven-sheehy** [comment]
@unguiculus Yes, we should probably revert it.

**Pull request merged**
