### PR TITLE
[stable/node-red]: add annotations in service.yaml

### PR DESCRIPTION
**Pull request by mscbpi**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

Already documented but not effective in the code.  

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by billimek** [comment]
Hi @mscbpi,

Can you please do the following to move this PR along?

1. sign the DCO via [these instructions](https://github.com/helm/charts/pull/13674/checks?check_run_id=123973858)
1. bump the chart [version in Chart.yaml](https://github.com/helm/charts/blob/master/stable/node-red/Chart.yaml#L5) - I recommend using 1.2.2

**Comment by mscbpi** [comment]
> Hi @mscbpi,
> 
> Can you please do the following to move this PR along?
> 
> 1. sign the DCO via [these instructions](https://github.com/helm/charts/pull/13674/checks?check_run_id=123973858)
> 2. bump the chart [version in Chart.yaml](https://github.com/helm/charts/blob/master/stable/node-red/Chart.yaml#L5) - I recommend using 1.2.2

Hi, DCO is still complaining about past commit sign-off, tried to get the things ok but it seems it's still not ok... Thanks.

**Comment by billimek** [comment]
It looks good now!

/lgtm

**Pull request merged**
