### PR TITLE
Fix Fluentd hanging https://github.com/fluent/fluentd/issues/1630

### LINKED ISSUE #5510: [incubator/fluentd-cloudwatch] Fluentd stop processing logs after ~ 10 minutes
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Kubernetes 1.8, Helm 2.6.2

**Which chart**: incubator/fluentd-cloudwatch

**What happened**:
Fluentd stops processing logs, but it keeps running. This happens on at least three clusters, including an old one on 1.6, all installed with kops on AWS.

**What you expected to happen**:
Fluentd should not hang.

**How to reproduce it** (as minimally and precisely as possible):
Approx 10 minutes after installation of the daemonset on a kops-created Kubernetes cluster, no logs are sent to cloudwatch.

**Anything else we need to know**:
This is a known issue: https://github.com/fluent/fluentd/issues/1630.
I don't know if this is specific to kops or not, but this basically makes this chart unusable. The fix, according to the ticket, is setting `enable_stat_watcher false` on the `tail` inputs.

### PR DESCRIPTION
**Pull request by mfornasa**
**What this PR does / why we need it**:  Fix fluentd-cloudwatch hanging as described in https://github.com/fluent/fluentd/issues/1630.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5510

### CODE REVIEW

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by mfornasa** [comment]
@unguiculus done

**Comment by unguiculus** [comment]
Please check CircleCI which is still failing.

**Comment by mfornasa** [comment]
Fixed and rebased to master.

**Comment by unguiculus** [comment]
cc @jmcarp @icereval @kenden

**Pull request merged**
