### PR TITLE
Adding Helm Chart for RBAC Manager

### PR DESCRIPTION
**Pull request by robscott**
This PR adds a Helm chart for [RBAC Manager](https://github.com/reactiveops/rbac-manager). Once merged, we will remove the Helm chart currently in place in that repository in favor of this one.

### CODE REVIEW

**Comment by robscott** [comment]
Hey @unguiculus and @seanknox would love to get this merged in if you have time to take a look. Happy to answer any questions.

**Comment by sudermanjr** [comment]
I would love to see this merged as well if that's possible.  Thanks!

**Comment by ejether** [comment]
I'm also looking forward to this.

**Comment by faheem-cliqz** [comment]
Would be nice to integrate the recent status field change in CRD, in to chart as well, to avoid breakages in 1.11 k8s https://github.com/reactiveops/rbac-manager/pull/33

**Comment by robscott** [comment]
@faheem-cliqz The chart here already included a couple improvements, including that getting removed. I had no idea this PR would take so long to get merged in. If there's no progress here soon, I'll move these chart changes into the rbac-manager repo as well.

**Comment by robscott** [comment]
Working on moving this chart to Helm Hub.

**Pull request closed without merging**
