### PR TITLE
[stable/coredns] Add ReadinessProbe

### PR DESCRIPTION
**Pull request by mrueg**
#### What this PR does / why we need it:
Adds a readinessProbe
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)
- [x] Tested and applied the change to a live cluster

### CODE REVIEW

**Comment by mrueg** [comment]
@shashidharatd tested it, ptal :)

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

also added @andor44 as a trusted collaborater

**Pull request merged**
