### PR TITLE
[stable/grafana]update the grafana to 7.0.5

### PR DESCRIPTION
**Pull request by gowrisankar22**
#### What this PR does / why we need it:

This PR is required to fix the alerts issue with granfana 7.0.3. More details : https://github.com/grafana/grafana/issues/25709

#### Which issue this PR fixes

  - https://github.com/grafana/grafana/issues/25709

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by gowrisankar22** [comment]
@zanhsieh Can you check and merge?

**Pull request merged**
