### PR TITLE
[stable/airflow] Fix unknown field scheduler

### PR DESCRIPTION
**Pull request by BernhardRode**
#### What this PR does / why we need it:

Installing airflow/stable currently fails with:

```
➜  airflow git:(master) ✗ helm upgrade --debug --install --namespace "default" airflow stable/airflow --values ./helm/values.yaml
[debug] Created tunnel using local port: '51833'

[debug] SERVER: "127.0.0.1:51833"

UPGRADE FAILED
Error: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "scheduler" in io.k8s.api.core.v1.ResourceRequirements
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "scheduler" in io.k8s.api.core.v1.ResourceRequirements
```

#### Which issue this PR fixes
* no open issue

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] stable/airflow

### CODE REVIEW

**Comment by dignajar** [comment]
Hi @BernhardRode 
I have the same issue, thank for your PR.
Have you some workaround meanwhile ? I'm trying to install Airflow in K8s.
Thanks

**Comment by BernhardRode** [comment]
Hey @dignajar 

we just switched to an older version (2.2.0 afaik).
That's not what we want, but all other fixes would be worse ;)

**Comment by JonnyIncognito** [comment]
Agreed this is a bug. The current values file includes a `scheduler.resources.scheduler` dictionary that's included into a container `resources` section in `deployments-scheduler.yaml`, even though the K8s spec doesn't have such a key.

**Comment by JonnyIncognito** [comment]
#14045 duplicates this, both fix issue #13352. @gsemet would you be happy merging this in? Multiple people have hit the issue. If so, @BernhardRode needs to update the version in Chart.yaml.

**Comment by gsemet** [comment]
No probl. Just rebase and update the version

**Comment by BernhardRode** [comment]
I will do this tomorrow when I‘m back from the weekend

**Comment by BernhardRode** [comment]
I've rebased the branch. Hope it is ok now.

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
/lgtm

Looks great !

**Pull request merged**
