### PR TITLE
[stable/prometheus-operator] k8s-coredns.yaml fixed time duration unit

### PR DESCRIPTION
**Pull request by b8rq**
No.

#### What this PR does / why we need it:
PR fixes difference between metric's unit and panel's yaxis unit:
  - expression uses coredns_dns_request_duration_seconds_bucket — so it means unit is seconds;
  - panel config uses "format": "ms" — i.e. milliseconds.

#### Which issue this PR fixes

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
/ok-to-test
/lgtm

**Review by vsliouniaev — APPROVED** [review]

**Comment by scottrigby** [comment]
Merge master to fix conflicts and retest. CI infra should now be fixed

**Pull request closed without merging**
