### PR TITLE
[stable/traefik] Disable acme volume if kvprovider is configured

### PR DESCRIPTION
**Pull request by fank**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
If you configure traefik with a kvprovider then a `emptryDir` for "acme" will be created which causes the cluster autoscaler to not remove the node where the pod is running on.
The option `storeAcme` will store the acme stuff in the kvprovider instead of disk, so if this option is enabled i don't need the `/acme` volume.

#### Which issue this PR fixes
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@Fank please sign the DCO

**Comment by Fank** [comment]
@cpanato sorry fixed

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
