### PR TITLE
[stable/node-red] add member

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Victor Login <batazor111@gmail.com>

#### Which issue this PR fixes

solve #13867

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by billimek** [comment]
@batazor I think you need to bump the chart version again - it's failing linting.

**Comment by billimek** [comment]
@batazor the DCO needs to be signed for the PR to pass all the checks.  Can you please [follow these instruction](https://github.com/helm/charts/pull/13928/checks?check_run_id=130134300) for doing so?

**Comment by batazor** [comment]
@billimek done

**Pull request merged**
