### PR TITLE
[stable/prometheus-operator]: do not allow '--manage-crds' flag in operator version >= v0.39.0

### PR DESCRIPTION
**Pull request by iwilltry42**
#### What this PR does / why we need it:

Options for managing CRDs were removed in this PR which is included in the latest v0.39.0 release:
https://github.com/coreos/prometheus-operator/pull/3155

This PR introduces a semVer check to definitely not set this flag if one deploys the operator with a version lower than v0.39.0

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@iwilltry42 Could you please bump the chart version here?

**Comment by vsliouniaev** [comment]
@iwilltry42 looks like this needs a version bump

**Comment by iwilltry42** [comment]
@vsliouniaev done :+1:

**Pull request merged**
