### PR TITLE
[stable/datadog] fix syntax error in templates/datadog-yaml-configmap.yaml

### LINKED ISSUE #19673: [stable/datadog] syntax error in template/datadog-yaml-configmap
**Describe the bug**
Syntax error in datadog-yaml-configmap template

**Version of Helm and Kubernetes**:
helm 2.16
kubernetes 2.

**Which chart**:
stable/datadog

**What happened**:
PR #19559 introduced a syntax error on line 43, this causes installations to fail

**What you expected to happen**:
chart should not have a syntax error

**How to reproduce it** (as minimally and precisely as possible):
    `{{- $version = "6.15" }}` should be `:=` not just `=`

### PR DESCRIPTION
**Pull request by AlexMichaelJonesNC**
Signed-off-by: Alex Jones <ajones@agari.com>

#### What this PR does / why we need it:
Fixes #19673 which blocks deploy of the datadog chart with our specific configuration. 

#### Which issue this PR fixes
  - fixes #19673 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by clamoriniere** [comment]
Hi @AlexMichaelJonesNC 
Could you bump the chart version? another pr was merge since your created this PR.
then I will be happy to merge your PR.

**Comment by AlexMichaelJonesNC** [comment]
@clamoriniere  - I've rebased this on the latest version and reupped the version as requested.

**Comment by clamoriniere** [comment]
/lgtm
Thanks @AlexMichaelJonesNC for your contribution!

**Pull request merged**
