### PR TITLE
Update requirements for stable charts

### PR DESCRIPTION
**Pull request by viglesiasce**

### CODE REVIEW

**Comment by prydonius** [comment]
LGTM, but should we just point to https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements from the README instead of listing requirements in multiple places?

**Comment by viglesiasce** [comment]
Good point. But at this point most of the charts in the incubator do not meet those requirements and in the README we say `Incubator Charts are those that do not meet these criteria, but still meet the technical and documentation requirements described in CONTRIBUTING.md.`

So should I patch up both ends of this with:
1. README: explicit about what can go into stable, with ref to tech requirements
2. CONTRIBUTING: lighten up the wording around incubator charts.

**Comment by viglesiasce** [comment]
Oops. 2 above needs to also be patched in the README

**Comment by prydonius** [comment]
I think we should put all the requirements in one place, otherwise people will be confused about where to look for what. The README is the first place people will look, but CONTRUBUTING.md is probably the best place for listing requirements, and we should probably aim to keep the README succinct. To this end, what about we move the Stable Chart requirements to a section above the 'Technical requirements' section? Then in the README we can just describe the structure and link to CONTRIBUTING.md for the detailed Stable Chart requirements.

Regarding charts that don't meet tech/docs requirements, that means we either need to relax some of those requirements and move them to the Stable Chart requirements section, or work on getting those charts up to scratch.

**Comment by viglesiasce** [comment]
RE: CONTRIBUTING/README: will update

I think we need to relax the requirements for incubator at least for now until we have a "good enough" template in `helm create` that provides scaffolding for all the things we are asking for.

**Review by prydonius — APPROVED** [review]
lgtm! thanks

**Pull request merged**
