### PR TITLE
[stable/chaoskube] Fix wrong label in docs

### LINKED ISSUE #161: Follow Logs doesnt work on new install using Helm Chart
Hi there,

If you install chaoskube by helm using `helm install stable/chaoskube` the displayed command to follow the pods log doesn't work:

```
You can follow the logs to see what chaoskube does:

    POD=$(kubectl -n default get pods -l='app.kubernetes.io/instance=khaki-pika-chaoskube' --output=jsonpath='{.items[0].metadata.name}')
    kubectl -n default logs -f $POD 

You are running in dry-run mode. No pod is actually terminated.
```

If you execute it, following error happens:
```
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

Problem is the label 
`-l='app.kubernetes.io/instance=khaki-pika-chaoskube'` 
which should be just
`-l='app.kubernetes.io/instance=khaki-pika`

Origin in [Notes.txt](https://github.com/helm/charts/blob/master/stable/chaoskube/templates/NOTES.txt) where 
`-l='app.kubernetes.io/instance={{ template "chaoskube.fullname" . }}'` 
should be probably replaced with
`-l='app.kubernetes.io/instance={{ .Release.Name }}`

I can make a PR if you want :D

### PR DESCRIPTION
**Pull request by WtfJoke**
No

#### What this PR does / why we need it:
Hi there

This PR fixes a small docs issue when installing the chart stable/chaoskube.

The label for searching the pod should have been the release name instead of the fullname.

#### Which issue this PR fixes
Fixes linki/chaoskube/issues/161

#### Special notes for your reviewer:

Not sure if I should have bumped the chart version for that issue. I did in order to complete the checklist and its probably not that bad. :sweat-smile:

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by WtfJoke** [comment]
/assign @syedimam0012

cc @linki

**Comment by linki** [comment]
@WtfJoke Thanks!

**Pull request merged**
