### PR TITLE
Updated role to accommodate using a Helm release name other than "kured"

### PR DESCRIPTION
**Pull request by patrickmslatteryvt**
#### What this PR does / why we need it:
* Updated role to accommodate using a Helm release name other than "kured"
* Added chart icon

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

@plumdog
@Flask

### CODE REVIEW

**Comment by plumdog** [comment]
LGTM :+1:

**Comment by patrickmslatteryvt** [comment]
Any chance that someone can take a look at this and either approve or reject?

**Pull request merged**
