### PR TITLE
[CI] Use latest chart-testing image

### PR DESCRIPTION
**Pull request by unguiculus**

### CODE REVIEW

**Comment by unguiculus** [comment]
Image pushed and tested.

**Comment by unguiculus** [comment]
@davidkarlsen This won't help. It's a CircleCI issue.

**Comment by davidkarlsen** [comment]
@unguiculus I was hoping it was just temporarily

**Comment by unguiculus** [comment]
https://github.com/helm/chart-testing/pull/13 causes problem with CircleCI. I already had to add workarounds due to this. We should revert the changes to the Dockerfile. If someone needs this, they should extend the image.

**Pull request merged**
