### PR TITLE
quote boolean S3 environment variables

### LINKED ISSUE #5065: [stable/docker-registry] s3.encrypt or s3.secure needs to be quoted
**Is this a request for help?**:

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** 

Bug report

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:14:31Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:

docker-registry

**What happened**:

If you specify `s3.encrypt` or `s3.secure` as a standard YAML boolean (e.g. true/false) Kubernetes throws this error:

```
Error: release docker-registry failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Env: []v1.EnvVar: v1.EnvVar: Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false},{"na|..., bigger context ...|"},{"name":"REGISTRY_STORAGE_S3_ENCRYPT","value":false},{"name":"REGISTRY_STORAGE_S3_SECURE","value"|...
```

**What you expected to happen**:

Deploy with the environment variables set to `true` or `false`.

**How to reproduce it** (as minimally and precisely as possible):

Set `s3.encrypt` and/or `s3.secure` to a boolean value, and install chart. E.g.:

```
helm install stable/docker-registry -n docker-registry -f docker-registry.yaml --set s3.encrypt=true
```

**Anything else we need to know**:

Have fix, will issue a PR.

### PR DESCRIPTION
**Pull request by emsixteeen**
**What this PR does / why we need it**:
Fixes #5065

**Which issue this PR fixes**
Fixes #5065

**Special notes for your reviewer**:
Maintainers: @jpds @rendhalver

### CODE REVIEW

**Comment by rendhalver** [comment]
Ahh that makes sense because it's being put into an environment variable.

**Comment by rendhalver** [comment]
I would approve it if I could. (I should really apply for membership.)

**Comment by mattfarina** [comment]
@rendhalver If you want to apply feel free to use me as a sponsor. Then we can set you up with an OWNERS file for this chart.

**Comment by rendhalver** [comment]
Awesome. Thanks @mattfarina

**Pull request merged**
