### PR TITLE
[stable/uchiwa] add repo archive notice and deprecate chart

### PR DESCRIPTION
**Pull request by scottrigby**
See #24030

### CODE REVIEW

**Review by unguiculus — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
```
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by mattfarina** [comment]
Manually merging as this is a required action. The tests are failing because the chart includes a resource version that is no longer supported in Kubernetes.

**Pull request merged**
