### PR TITLE
[stable/traefik] Use new-style dashboard and metrics configuration 

### LINKED ISSUE #5731: [stable/traefik] web provider configuration is deprecated
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/traefik`

**What happened**:
When starting Træfik following warning gets logged
```
level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
```

**What you expected to happen**:
Træfik chart should use the api provider instead.

**How to reproduce it** (as minimally and precisely as possible):
Enable the dashboard.

**Anything else we need to know**:
Deprecation notes: https://docs.traefik.io/configuration/backends/web/
API provider: https://docs.traefik.io/configuration/api/

### PR DESCRIPTION
**Pull request by briancharous**
**What this PR does / why we need it**: The way the Traefik chart configured Traefik's dashboard and metrics exporters under the `[web]` section is now deprecated. 

**Which issue this PR fixes** : fixes #5731

### CODE REVIEW

**Comment by dtomcej** [comment]
Very nice PR. Much needed update.

@briancharous Can you please bump the chart version?

**Comment by briancharous** [comment]
Thanks for the review @dtomcej, the version has been bumped

**Comment by briancharous** [comment]
@dtomcej Any change we can get this merged in?

**Pull request merged**
