### PR TITLE
[stable/ipfs] add configmap to ipfs

### PR DESCRIPTION
**Pull request by VladimirKobets**
**What this PR does / why we need it:**
Allow the user to provide custom config

**Special notes for your reviewer:**
Some users might use custom config

### CODE REVIEW

**Comment by mattfarina** [comment]
/ok-to-test

@YuviPanda Can you review this change?

**Comment by VladimirKobets** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.

The pull request is still actual

**Comment by VladimirKobets** [comment]
@mattfarina @foxish 
Could you please say what is next with my PR

**Pull request closed without merging**
