### PR TITLE
[incubator/jaeger] Fixed jaeger chart config options

### PR DESCRIPTION
**Pull request by aleerizw-zz**
**What this PR does / why we need it**:
Fixes the Configuration options for the Jaeger chart.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @dvonthenen @mikelorant @pavelnikolov

**Comment by aleerizw-zz** [comment]
Can someone please review this :smile:

**Comment by aleerizw-zz** [comment]
Just updated the chart version, @unguiculus can you please review again.

**Comment by aleerizw** [comment]
| /test pull-charts-e2e
-- | --

**Review by pavelnikolov — APPROVED** [review]

**Pull request merged**
