### PR TITLE
Add appVersion key for sapho

### PR DESCRIPTION
**Pull request by AdamDang**
The key "appVersion" is needed for ci testing, it's missing in this yaml. That sometimes will cause testing failure.

### CODE REVIEW

**Comment by timstoop** [comment]
Seems like there's a bug in the test code for this Chart: 
```
I0404 14:56:49.490] 2018-04-04T14:53:53.976338Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
I0404 14:56:49.490] 2018-04-04T14:53:53.976377Z 0 [ERROR] Aborting
```

**Comment by AdamDang** [comment]
pull-charts-e2e — Job failed.

**Pull request closed without merging**
