### PR TITLE
 [stable/external-dns] Revert "Allow upgrade with empty clusterIP (#4711)"

### PR DESCRIPTION
**Pull request by coreypobrien**
Reverts #4711 

If `clusterIP` is `""` in the `values.yaml` by default, you will never be able to upgrade. having `clusterIP: ""` in your spec means "Have Kubernetes assign a cluster IP". Applying the first time results in `clusterIP: x.x.x.x` in the spec. The second apply then fails when it tries to apply `clusterIP: ""` again because `clusterIP` is immutable.

Example:
```
$ cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  clusterIP: ""
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default
  type: ClusterIP

$ kubectl apply -f svc.yaml
service "test" created

$ kubectl apply -f svc.yaml
The Service "test" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

If `clusterIP` is `""` in the values for the chart, we shouldn't be including it in the service definition.

### CODE REVIEW

**Comment by linki** [comment]
@unguiculus There's some back and forth with this issue in general. Seems like no solution works in all cases, see https://github.com/kubernetes/charts/pull/4711#issuecomment-382795692. Is there a recommended way?

**Comment by unguiculus** [comment]
@linki There's no recommended way. I think we should merge this.

**Pull request merged**
