### PR TITLE
[incubator/airflow] Airflow Helm Chart with KubernetesExecutor

### PR DESCRIPTION
**Pull request by tekn0ir**
#### What this PR does / why we need it:
There is no official curated chart for Airflow in helm repositories. Earlier attempts on adding charts has been based on the CeleryExecutor. This version is based on the native KubernetesExecutor and will hopefully have higher probability to get merged.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
Please note that Airflow is in Apache incubator and the KubernetesExecutor is just in early stages, but still, as I see; the only good solution when running on top of k8s. That said, at the time of this PR the code has a bug or two. Due to that, the docker image used is built from a PR on Airflow. Thus it is set to latest and not a release of Airflow. But I will update it as soon as it is merged and new release of Airflow is available.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
@tekn0ir 
Before creating this PR have you watched at https://github.com/helm/charts/pull/3959 ?

**Comment by maver1ck** [comment]
@tekn0ir 
So let's add support for KubernetesExecutor to Airflow Chart.
There is no sense to have to charts for the same app.

**Comment by tekn0ir** [comment]
I also used over the Astronomer Airflow helm chart as inspiration, it is quite similar to #3959: https://github.com/astronomer/helm.astronomer.io/tree/master/charts/airflow but is built into an ecosystem of charts that is impressive. I think they have gathered most experience of what works and what does not.

**Pull request closed without merging**
