### PR TITLE
[stable/concourse] Update Concourse to 3.10

### PR DESCRIPTION
**Pull request by arbourd**
**What this PR does / why we need it**:

Updates Concourse to 3.10, and amends the chart to support these changes.

Specifically, `--tsa-port` and env `CONCOURSE_TSA_PORT` has been removed for the worker. Now, the `--tsa-host` and/or `CONCOURSE_TSA_HOST` require the host and port.

**Special notes for your reviewer**:

Bumped the minor because this change is not interoperable with < 3.10.

### CODE REVIEW

**Comment by william-tran** [comment]
What's the definition of a breaking change wrt. the chart version? Upgrading concourse to 3.10 contains quite a few breaking changes to concourse itself: https://concourse-ci.org/download.html#v3100 But these changes to concourse, and this particular change to the chart, isn't a breaking change in terms of chart values; you won't have to refactor your values to make this work. 

If this isn't a breaking change to the chart values, and this isn't merely a bugfix, the bumping minor is appropriate, unless we must also take into account the breaking changes of the underlying application. Can any Helm pros weigh in? @unguiculus @mattfarina @viglesiasce ?

**Comment by arbourd** [comment]
A note for flapping workers might be a nice addition too in the `NOTES`. Workers must be pruned and have their pods deleted.

Another quick question: regarding the default change from `naive` to `btrfs` with 3.10, should we consider this in the chart as well?

**Comment by timstoop** [comment]
Not a Helm pro here, but I think that bumping the major is the only real way to signal to end users that there are going to be breaking changes in this update. So I would recommend to bump the major and make sure to explain somewhere what's going on.

**Comment by viglesiasce** [comment]
I agree. We should operate on principle of least surprise. If upgrading to this chart version would leave you with a broken Concourse setup I think we should bump the major. OTOH if an upgrade will "just work" for most users running previous versions, then I think we are good.

@arbourd the reason we are using naive is because it is the only default that will be guaranteed to work on any K8s install regardless of node image.

How will upgrade work for people running the previous version of the chart?

**Comment by william-tran** [comment]
@viglesiasce  It will break if the user has specified a pre 3.10 version of concourse in their values. We could use the `semverCompare` function to deal with this though, e.g. https://github.com/kubernetes/charts/pull/4597/files#diff-33a16a0789cde854c77e65e7774aa2beR156. If we deal with that, I don't think anything else will break. There is a suggestion in the [release notes](https://concourse-ci.org/download.html#v3100):

>We recommend spinning up a new pool of worker nodes, upgrading your web nodes, and then removing the old workers. Otherwise your workers may get swarmed with containers, if only one 2.0 worker is added at a time with the web nodes already upgraded.

Helm will do everything all at once, and it's likely the web pods will be upgraded and ready before the workers roll over. The swarming situation could happen, resulting in a worker that hits a fatal error when it exceeds container capacity and restarts, but it will recover and containers will re-balance on their own.

**Comment by arbourd** [comment]
Oh nice, didn't know about `semverCompare`. I can definitely switch up the chart to use that instead with `.Chart.AppVersion` and then bump the patch.

**Comment by william-tran** [comment]
@arbourd would it be possible to use `imageTag` instead, as that's the value that actually gets used.

**Review by william-tran — CHANGES_REQUESTED** [review]
Let's do a bump minor to 1.2.0 instead. Given semver rules, new chart features or Concourse version updates that contain new features will be a minor bump, breaking changes or definite downtime is a major bump, and docs updates and bugfixes is a patch bump.

**Comment by william-tran** [comment]
@timstoop do you disagree that changes are needed to bump minor vs patch? Though your lgtm doesn't have affect on the PR process because you are not an owner of this chart or on any parent folder, I'd like to know your reasoning for this.

**Comment by arbourd** [comment]
@william-tran I had updated the chart back to `1.2.0` by the time @timstoop /lgtm and force pushed. Sorry for the confusion.

**Comment by william-tran** [comment]
My bad I didn't see that subsequent commit that addressed the bump to 1.2.0. LGTM!

**Pull request merged**
