### PR TITLE
[stable/jenkins] extracted "jenkins.url" into template

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

This way we can re-use the logic when configuring the URL via JCasC or when we need the URL somewhere else.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
/lgtm

I love it.

**Comment by torstenwalter** [comment]
@maorfr adjusted Chart.yaml to fix merge issues

**Pull request merged**
