### PR TITLE
[stable/spinnaker] Correct kubeConfig value casing typo

### LINKED ISSUE #17591: [stable/spinnaker] typo issue
**Describe the bug**
PR introduced a small typo https://github.com/helm/charts/pull/16473 at stable/spinnaker/templates/_helpers.tpl

and breaks helm deployment

**Version of Helm and Kubernetes**:
Helm 2, k8s 1.13

**Which chart**:
stable/spinnaker

**What happened**:
kubeConfig  in values.yaml has been referred as kubeconfig (mind capital C) in stable/spinnaker/templates/_helpers.tpl

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart version 1.16.0 or 1.19.0

**Anything else we need to know**:
As workaround, I had to add new set of values:
`kubeconfig:
  encryptedKubeconfig:
`

### PR DESCRIPTION
**Pull request by EricLemieux**
Signed-off-by: Eric Lemieux <eric@lemieuxdev.com>

#### Is this a new chart
No, bug fix existing chart

#### What this PR does / why we need it:
Fixes bug causing issues with deployment as documented in the related issue

#### Which issue this PR fixes
fixes #17591

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@EricLemieux 
Could you resolve conflict on stable/spinnaker/Chart.yaml please? Thank you.

**Comment by EricLemieux** [comment]
@zanhsieh conflict resolved

**Pull request merged**
