### PR TITLE
jenkinsuriprefix in NOTES and ingress in addition of healthprobes (cf…

### LINKED ISSUE #5283: [stable/jenkins] when I change JenkinsUriPrefix on values.yaml, pod fails on initializing because of wrong readiness and liveness probe
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/jenkins

**What happened**:

when I added either of these lines into a custom values.yaml file to override some values.

```
JenkinsUriPrefix: /jenkins
  JenkinsOpts: '--prefix=/jenkins'
```

jenkins pod never comes to ready state, when I check kubelet logs, it says 

```
Readiness probe for "jenkins-7bcf95b8b7-g6894_jenkins-ci(75ec018b-47e8-11e8-9ad7-022c97c65004):jenkins" failed
```

when I checked jenkins deployment, it was showing

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
```
```
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
```

when I changed these paths according to my prefix, it is fixed

**What you expected to happen**:

When I added a prefix, I expect livenessProbe and readinessProbe  paths would be changed accordingly. 

**How to reproduce it** (as minimally and precisely as possible):

1 - install with default values
```
helm install --name jenkins  stable/jenkins
```
after that, create a values.yaml file 

add below lines

```
Master:
  JenkinsUriPrefix: /jenkins
  JenkinsOpts: '--prefix=/jenkins'
```
and run 
```
helm upgrade -f values.yaml jenkins stable/jenkins
```

**Anything else we need to know**:

when you changed deployment jenkins with the correct probe values, it is fixed

in this file 

https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml

```
{{- if .Values.Master.HealthProbes }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout }}
            timeoutSeconds: 5
            failureThreshold: {{ .Values.Master.HealthProbeLivenessFailureThreshold }}
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout }}
{{- end }}
```
should be something like this 
```
{{- if .Values.Master.HealthProbes }}
          livenessProbe:
            httpGet:
              path: {{.Values.Master.JenkinsUriPrefix}}/login
              port: http
            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout }}
            timeoutSeconds: 5
            failureThreshold: {{ .Values.Master.HealthProbeLivenessFailureThreshold }}
          readinessProbe:
            httpGet:
              path: {{.Values.Master.JenkinsUriPrefix}}/login
              port: http
            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout }}
{{- end }}
```

### PR DESCRIPTION
**Pull request by kstevena**
**What this PR does / why we need it**: 

- It correctly sets the healthprobes when `Master.JenkinsUriPrefix` is specified as it was proposed in #5737 , then not causing always failing health checks
- It also indicate the proper url users need to use to reach the jenkins instance
- It also set appropriately the path on the ingress controller, so that multiple jenkins instances could be hosted under a single virtual host

**Which issue this PR fixes**:
fixes #5283 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kstevena** [comment]
CLA signature done

**Comment by Hokwang** [comment]
any updates?

**Comment by kstevena** [comment]
Hi I'm out with just my mobile phone for a couple of days...

**Comment by viglesiasce** [comment]
The prefix issue has already been merged but not the NOTES fix. Can you submit just that part:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L136

**Pull request closed without merging**
