### PR TITLE
[incubator/drone] Move drone from incubator to stable

### PR DESCRIPTION
**Pull request by christian-roggia**
The Drone CI chart has been in the incubator repository for around 7 months, after over 20 PRs I believe that the chart is stable and ready for use in production.

In this PR the following changes have been applied:

- [x] Removed incubator/drone chart.
- [x] Added stable/drone chart.
- [x] Updated the README file with the stable chart.
- [x] Added the OWNERS file.
- [x] Updated the .helmignore file with the OWNERS file.
- [x] Bumped the chart version to 1.1.0

### CODE REVIEW

**Comment by unguiculus** [comment]
You need to copy it and deprecate the incubator one.

See https://github.com/kubernetes/charts/blob/master/PROCESSES.md

**Comment by christian-roggia** [comment]
You are completely right, I totally missed that point. I will update the PR as soon as I arrive home.

**Comment by unguiculus** [comment]
You need to add deprecation notes to the readme and to NOTES.txt. Direct users to the stable chart.

https://github.com/kubernetes/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by christian-roggia** [comment]
Everything is done!

**Comment by unguiculus** [comment]
You changed permissions of two scripts in `test`. Please revert that.

**Comment by christian-roggia** [comment]
Yep, I noticed Windows screwing up with file permissions, reverted the change on the scripts.

**Pull request merged**
