### PR TITLE
[stable/reloader] Fix nodeSelector indenting

### PR DESCRIPTION
**Pull request by winromulus**
#### What this PR does / why we need it:
Fixes indenting in nodeSelector

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by winromulus** [comment]
@maorfr available for a quick review on this?

**Comment by maorfr** [comment]
i've added all approvers in the owners file as trusted collaborators, so this may start moving more quickly. @winromulus I have also added you as a trusted collaborator, feel free to `/ok-to-test`!

**Pull request merged**
