### PR TITLE
[stable/pomerium] Handle NodePort and LoadBalancer service types correctly

### PR DESCRIPTION
**Pull request by travisgroth**
#### What this PR does / why we need it:
Ensures that the Authorize service: 

- works correctly by default even when the user specifies a `NodePort` or `LoadBalancer` service
- allows exposure of the Authorize service via non-headless `service`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by desimone — COMMENTED** [review]
One small issue experienced when running the `gke_script`. 

```
error while evaluating the ingress spec: service "default/dandy-cheetah-pomerium-authorize" is type "ClusterIP", expected "NodePort" or "LoadBalancer
```
Ingress creation failed because authorize is of type ClusterIP now (which totally makes sense). 


Once I did that, everything worked perfectly.

**Comment by victornoel** [comment]
@travisgroth upgrading from 1.3.2 worked ok (except for the force thing with the service, I'm using helmfile and couldn't pass the force flag so I simply deleted the service just before applying the new chart :)

/lgtm

**Comment by victornoel** [comment]
@travisgroth too late, sorry about that :/

**Comment by travisgroth** [comment]
Just saw - no problem.  BTW this branch was a bug fix not the TLS refactor.  Wanted to make sure it is fixed in the 2.x series.

It seems the fix isn't complete so I'll have another PR.  GKE ingress will still have issues with this but it isn't any worse.

**Pull request merged**
