### PR TITLE
[stable/newrelic-infrastructure] Set the apiVersions to newest version to support recent k8s clusters

### PR DESCRIPTION
**Pull request by jeffdesc**
#### What this PR does / why we need it:
Updates all [stable/newrelic-infrastructure] apiVersions for recent K8S cluster versions. Otherwise a deploy on new versions (e.g. v1.16.3) is impossible.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by douglascamata** [comment]
Hey @jeffdesc! Sorry for the delay. We're keen to accept your contribution. Do you mind solving the conflicts, please?

**Comment by douglascamata** [comment]
@jeffdesc can you also update the title according to the guidelines? It's one of the checklist items in the PR's description.

**Comment by jeffdesc** [comment]
Hey @douglascamata, I've adjusted everything as requested. 
Please let me know if I need to do anything else.

**Pull request merged**
