### PR TITLE
[stable/mongodb] Added authenticationDatabase parameter to connection string

### PR DESCRIPTION
**Pull request by esanchezm**
#### What this PR does / why we need it:

Added `--authenticationDatabase admin` parameters to the `NOTES.txt` as I was having issues connecting to mongo. Probably it was a client configuration and most of the users will have it properly setup, but I spent too much time with this and I think it's a good practice.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by esanchezm** [comment]
@carrodher sorry i forgot :) Done now.

**Comment by carrodher** [comment]
🤦‍♂️ It seems a new mongodb version appears in the meantime. Anyway, changes LGTM, please, can you rebase the changes? After that it should be ready to be merged

**Pull request merged**
