### PR TITLE
[stable/collabora-code] Add livenessProbe and readinessProbe scheme value option

### LINKED ISSUE #14980: [stable/collabora-code] Allow to customise livenessProbe and readinessProbe scheme
**Is your feature request related to a problem? Please describe.**
Collabora-code can be configured to use TLS. We need to adapt the livenessProbe and readinessProbe to use HTTPS scheme if so.

**Describe the solution you'd like**
Customise livenessProbe and readinessProbe scheme

**Describe alternatives you've considered**
Disabeling TLS will not fit our needs.

### PR DESCRIPTION
**Pull request by BertrandGouny**
#### What this PR does / why we need it:
Add livenessProbe and readinessProbe scheme value option

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #14980

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
@chrisingenhaag, after you accept the invite you can `/assign`
Will appreciate your review!

**Comment by chrisingenhaag** [comment]
Hi @BertrandGouny ,
can you please bump the chart version to 1.0.4 as the current is already 1.0.3. No idea why the diff says current master is 1.0.2.

best

**Comment by BertrandGouny** [comment]
Just bumped the version to 1.0.4, thanks for the review

**Comment by BertrandGouny** [comment]
Who just tried to sign one all commit an mess it up :/ sorry for the noise

**Review by chrisingenhaag — APPROVED** [review]

**Comment by BertrandGouny** [comment]
ok this too hard for me to sign the comit ommited just leaving this...

**Comment by chrisingenhaag** [comment]
Ok nevermind. Thx for the PR anyway. I'll get this done

**Comment by BertrandGouny** [comment]
Finaly managed to rebase and sign the commit :) sorry for the delay

**Comment by chrisingenhaag** [comment]
Thx
/lgtm

**Pull request merged**
