### PR TITLE
[incubator/zookeeper] Add Prometheus ServiceMonitor for each exporter

### PR DESCRIPTION
**Pull request by mhaunolder**
#### What this PR does / why we need it:
Installs a Prometheus ServiceMonitor for each enabled exporter and exposes the exporter ports if there are enabled.

#### Which issue this PR fixes
--

#### Special notes for your reviewer:
@lachie83
@kow3ns

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mhaunolder** [comment]
@lachie83 @johnny Please have a look at my PR

**Comment by AlexisSellier** [comment]
Hello, what it missing for this PR to be merged ?

**Review by lachie83 — APPROVED** [review]

**Comment by lachie83** [comment]
Sorry for the delay in review.

**Pull request merged**
