### PR TITLE
[stable/bookstack] Fix default value in values.yaml based on README.md:

### PR DESCRIPTION
**Pull request by thiagolsfortunato**
#### Is this a new chart
no

#### Which issue this PR fixes

Fix default value in `values.yaml` based on `README.md`:

|            Parameter              |              Description                 |                          Default                        | 
| --------------------------------- | ---------------------------------------- | ------------------------------------------------------- 
| -- | -- | -- |
| `mariadb.master.persistence.enabled` | Enable MariaDB persistence using PVC     | `false`       
| -- | -- | -- |
| `persistence.uploads.accessMode` | PVC Access Mode | `ReadWriteOnce`
| `persistence.storage.accessMode` | PVC Access Mode | `ReadWriteOnce`
-- | -- | --

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by maorfr** [comment]
i'm fine with this change. changing the README to match the values would be an easy lgtm. since this is in fact a breaking change, i suggest we bump the major version. wdyt?

**Comment by thiagolsfortunato** [comment]
Why bump de major version? It's only an update in README.md.

**Comment by maorfr** [comment]
You are updating values, not README.

**Comment by verwilst** [comment]
Since you're indeed changing default values ( and not only the readme ), i would at least go to version 1.3.0 instead of 1.2.1.

**Comment by thiagolsfortunato** [comment]
Ok, You suggest to modify only README, then should not bump version, ok?

**Comment by thiagolsfortunato** [comment]
I have a commit to fix README. I will push to remote.

**Comment by maorfr** [comment]
Now that the change is only to the README, it is enough to bump the patch only

**Comment by verwilst** [comment]
Please set version to 1.2.1, not 2.2.0.

**Comment by thiagolsfortunato** [comment]
updated :heavy_check_mark:

**Comment by theAkito** [comment]
Shouldn't `mariadb.master.persistence.enabled` actually default to `true`? I think it is crazy to keep it set to `false`, as there is almost no use-case for this. It is highly irritating. Also, whose deployment would it break, if this was actually fixed in `values.yaml`? It does not make any sense for it to be turned off, in almost all cases. Especially, since the `README.md` was apparently wrong all along, so people had to set it explicitly, anyway, to fix the mistake. So there is no breaking change. The only breaking change that might've been introduced was after this pull request was merged. Still, extremely unlikely.
I had to check 5 times, if I was reading correctly. As everything pretty much depends on this being enabled, so it was really confusing to see it being `false` as the default.

**Pull request merged**
