### PR TITLE
[spinnaker] Make Jenkins optional

### PR DESCRIPTION
**Pull request by benjaminws**
Some organizations may not use jenkins with Spinnaker. This PR proposes to make jenkins usage optional.

- Update jenkins dep
- Adds jenkins.enabled value
- Load requirements, hooks, and config maps if jenkins
enabled

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by benjaminws** [comment]
sorry i missed all this :|

**Comment by viglesiasce** [comment]
No worries @benjaminws! Much needed feature of the chart. Then there were just things that I figured we'd update at the same time. Also note that I just submitted #3883 which bumps up Spinnaker to v1.6.0.

**Comment by musabmasood** [comment]
@benjaminws  @viglesiasce 

I was working on this helm chart and was able to disable jenkins (thank you). However, I could not find a way to connect my own jenkins master. I see that this can be done in the igor-local file, but that would mean I need to download/unpack the spinnaker the chart locally. Any other way?

**Pull request merged**
