### PR TITLE
[stable/drone] #13867 Update owners

### PR DESCRIPTION
**Pull request by zakkg3**
Because of https://github.com/helm/charts/issues/13867

Here is a previous [PR](https://github.com/helm/charts/pull/11619).

There are a few things to improve in this chart that I would like to discuss with @christian-roggia and @cpanato  @max-rocket-internet

1- For K8s enabled, the DRONE_RPC_HOST env var is not specified so by default it's = to DRONE_HOST,  which means the interaction job <-> server is going through the public endpoint instead to the service, not ideal in some cases. It would be nice to have the option to set it to the local service. 

2- Update to drone 1.1.0 instead of the release candidate `1.0.0-rc.5`

3- Add the option to install the secret plugin, to be able to read secrets from K8s backend

4- Fix Grpc (not in drone1.0) there is an [open pr](https://github.com/helm/charts/pull/13866/commits/5f8cfe20742e482f8c4d17ca01f36f56520b47b3#diff-aef3ca8b1055a09ded2f4ca6b47e3d6c) for this 

One more thing: @paulczar  is in `chart.yaml` but not in `OWNERS`, let me know if I should include him.?

### CODE REVIEW

**Comment by maorfr** [comment]
/assign @paulczar 

can you ptal? :)

**Comment by max-rocket-internet** [comment]
Hey @zakkg3 

> 1- For K8s enabled, the DRONE_RPC_HOST env var is not sp..

Nice 💯

> 2- Update to drone 1.1.0 instead of the release candidate 1.0.0-rc.5

Nice 💯

> 3- Add the option to install the secret plugin, to be able to read secrets from K8s backend

What do you mean here? `helm-secrets` Helm plugin?

> 4- Fix Grpc (not in drone1.0) there is an open pr for this

Nice 💯

**Comment by zakkg3** [comment]
> > 3- Add the option to install the secret plugin, to be able to read secrets from K8s backend
> 
> What do you mean here? `helm-secrets` Helm plugin?

External secrets are stored in a third party system, such as Vault or the AWS Secrets Manager, and are requested at runtime. In order to use external secrets you must install and configure a [secret plugin
](https://docs.drone.io/user-guide/secrets/external/)

**Comment by zakkg3** [comment]
/assign @maorfr
:)

**Comment by christian-roggia** [comment]
/approve

I fully approve of this and I really would love to get some help in maintaining this chart.

I am sorry for the late answer but I'm currently extremely busy with the KubeCon.

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

thanks! welcome @zakkg3 !

**Pull request merged**
