### PR TITLE
[stable/jenkins] Add support for service account annotations in jenkins

### PR DESCRIPTION
**Pull request by hamza3202**
**Problem:**
We need to deploy jenkins on openshift using helm.

**Solution**
We need to add annotation to service Account so that openshift can correctly route to service.
A sample annotation looks like this 
```
serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name": "route-name" }}
```

**What this PR does?**
Add option to specify annotations for service account.

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Comment by hamza3202** [comment]
@maorfr The image is still not available. Can you guide as to what is the issue?

**Comment by maorfr** [comment]
you mean the chart version? i guess we should give it some time...

**Pull request merged**
