### PR TITLE
[stable/ambassador] Create metrics service if prometheus exporter enabled

### PR DESCRIPTION
**Pull request by ysaakpr**
#### What this PR does / why we need it:
Expose the Prometheus exporter metrics as a service, so service monitors can start scraping.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Flydiverny** [comment]
Why do we need this / what does it solve?

**Comment by ysaakpr** [comment]
This will enable the Prometheus service monitor to scrape the service. Currently, the ports are exposed, but there is no service which exposes the container port to external

**Comment by n1koo** [comment]
This has the downside of using `ServiceIP`, eg a single IP that is loadbalanced to backends. Correct me if i'm wrong, but doesn't that mean we will have random backends (each having their own stats) rather than collecting *all* of the stats from all instances?

Not sure if headless service would be better, i've been just using using:

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9102"
``` 

myself

**Comment by steven-sheehy** [comment]
+1 to using pod scraping, the metrics service is not necessary. Perhaps this PR can be turned into a documentation PR that mentions how to enable Prometheus scraping via podAnnotations in the README?

**Comment by djsly** [comment]
how do you perform scraping when using ServiceMonitor with Prom-Operator if you don't have a service?

FYI: Prometheus when scraping Services, will, in fact, scrape the endpoints associated with the Service, so you still get all of the backend instances metrics.

https://www.datawire.io/faster/ambassador-prometheus/#configure-prometheus

The DOC talks about deploying a Service to front the metric port as well as a ServiceMonitor. I understand that the ServiceMonitor needs to be configurable, not all Prometheus CRDs are using the same ServiceMonitorSelector.

The Spec for theService Monitors talks about Endpoints: 
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec

**Comment by Flydiverny** [comment]
@djsly yes I think it would be worth revisiting. There's quite a few examples in the helm charts repository with similar implementations for optionally adding a service monitor. 
I think @jamessthompson was considering giving a PR a go as well.

**Comment by n1koo** [comment]
> how do you perform scraping when using ServiceMonitor with Prom-Operator if you don't have a service?

Prometheus will be monitoring the annotions on the pods and automatically creating endpoints.

eg. 

```
Annotations: 
                    prometheus.io/port: 9102
                    prometheus.io/scrape: true
```

see https://medium.com/faun/production-grade-kubernetes-monitoring-using-prometheus-78144b835b60 for more information about how that works.

> FYI: Prometheus when scraping Services, will, in fact, scrape the endpoints associated with the Service, so you still get all of the backend instances metrics.

The documentation Ambassador (now) has is correct, but is also crucially different from what was suggested in this PR. The documentation has a headless service ( `clusterIP: None` ) which will create just create a DNS record with 3 A records corresponding to the backend endpoints (=pods). Not a a single service IP that is routed via `kube-proxy`.

Creating a headless service is alternative to the pod annotations. Both work pretty much the same underneath (prometheus talks straight to the pods). 

`ServiceMonitor` however is superior if you need to do revamping for labels. So refactoring to use a (headless) service 👍

**Comment by djsly** [comment]
@n1koo thanks for your reply, FYI, I was mainly referring to the fact the `ServiceMonitor` won't list PODs. It expects a Service (headless or not) with a certain label. So it seems to make sense that a service would a nice to have to allow easy integration with the `ServiceMonitor`  :)

I will add a US for my next to look at creating a PR to support both `Service (headless)` + `ServiceMonitor`

**Pull request closed without merging**
