### PR TITLE
[stable/postgresql] Use tpl so release name can be used in config maps

### PR DESCRIPTION
**Pull request by nuwang**
#### What this PR does / why we need it:

This runs the config map name through tpl so that templating can be
used with config map and secret names in postgres. Otherwise, it limits
postgres to a single release when using a custom config map name.

#### Which issue this PR fixes
This is a workaround for issue: https://github.com/helm/helm/issues/2492
and follows similar solutions used elsewhere:
https://github.com/helm/charts/issues/10342

#### Notes to reviewer
Please squash

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @nuwang 

Could you update the **README.md** so it reflects that **initdbScriptsConfigMap** will be evaluated as a template?

For instance, check how `persistence.existingClaim` is documented:

| Parameter                                     | Description                                                                                                            | Default                                                     |
| --------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| `persistence.existingClaim`                   | Provide an existing `PersistentVolumeClaim`, the value is evaluated as a template.                                     | `nil`           |

**Comment by nuwang** [comment]
@juan131 Thanks for the catch! Pushed in an update.

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by juan131** [comment]
Thanks @nuwang for implementing the changes! Approving your PR

**Pull request merged**
