### PR TITLE
[incubator/gogs] Bumped version from 0.11.86 to 0.11.91

### PR DESCRIPTION
**Pull request by ribeiromiranda**
#### What this PR does / why we need it:
Bumped version from 0.11.86 to 0.11.91

@obeyler @poblin-orange

### CODE REVIEW

**Review by obeyler — APPROVED** [review]

**Comment by ribeiromiranda** [comment]
> @ribeiromiranda: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-charts-e2e	[99500eb](https://github.com/helm/charts/commit/99500eb604622ed1c24be3dd00a384ffefd20bf8)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/21945/pull-charts-e2e/1251223088398340096/)	`/test pull-charts-e2e`
> [Full PR test history](https://prow.k8s.io/pr-history?org=helm&repo=charts&pr=21945). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3ribeiromiranda). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/helm/charts/issues?q=is:issue+is:open) when you hit one in your PR.

W0417 18:59:34.657]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0417 18:59:34.658]     subprocess.check_call(cmd)
W0417 18:59:34.658]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0417 18:59:34.658]     raise CalledProcessError(retcode, cmd)
W0417 18:59:34.658] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0417 18:59:34.658] Command failed
I0417 18:59:34.658] process 625 exited with code 1 after 1.8m
E0417 18:59:34.658] FAIL: pull-charts-e2e

The test error is not related to the change.
@obeyler

**Pull request closed without merging**
