### PR TITLE
[stable/newrelic-infrastructure] Update image, limits and add kubernetes host and port option

### PR DESCRIPTION
**Pull request by jfjoly**
- Updated image to 1.2.0 (latest) 
- Changed limits to match the ones in [newrelic-infrastructure-k8s-latest.yaml](https://download.newrelic.com/infrastructure_agent/integrations/kubernetes/newrelic-infrastructure-k8s-latest.yaml)
- Added options to configure the Kubernetes service host and port

#### What this PR does / why we need it: 
The new version introduces improvements, in particular in environments where the Kubernetes service host and port have been changed from the default. This is useful to match a certificate for instance. 
The limits are updated to match the same one provided by default on the New Relic daemonset, the memory request is lower , the memory limit is higher and there is no CPU limit.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by jfjoly** [comment]
@rk295 You're marked as the maintainer of this chart, would you mind take a look at this PR?

**Comment by rk295** [comment]
@jfjoly sure thing.

**Comment by rk295** [comment]
LGTM. Somebody else will have to merge though.

**Comment by smoya** [comment]
It would be nice to see this PR merged asap. The chart was using a very old integration version. A lot of improvements were added to the latest versions.

**Comment by jfjoly** [comment]
Thanks @rk295 ! It’s outdated, i just created a new one with version 1.3.1 and will do smaller ones for the new configuration options. I hope the smaller PR will get approved faster.

**Comment by jfjoly** [comment]
https://github.com/helm/charts/pull/9283

**Comment by rk295** [comment]
👍 :)

**Pull request closed without merging**
