### PR TITLE
Allow to run filebeat pods as privileged

### PR DESCRIPTION
**Pull request by mcanevet**
This is required to run filebeat on OpenShift

### CODE REVIEW

**Comment by rendhalver** [comment]
Chart version needs to be incremented on every change.

**Comment by mcanevet** [comment]
@rendhalver done!

**Comment by AntonioMeireles** [comment]
guys... rebase and merge please ... handy !

**Comment by mcanevet** [comment]
@rendhalver could you please merge this?

**Comment by mcanevet** [comment]
@rendhalver is there something I can do to have this PR merged?

**Comment by bquartier** [comment]
Hi. Can someone please merge this PR if there is no further issue?
It is very small and is necessary to use this chart on Openshift!
@rendhalver ?

**Comment by mcanevet** [comment]
Rebased. Again...

**Pull request merged**
