### PR TITLE
[stable/docker-registry] Improve full name definition

### PR DESCRIPTION
**Pull request by v0ctor**
**What this PR does / why we need it**:
It makes possible to create deployments named like the chart. Currently, if the same name is set, all resources are named like this: `docker-registry-docker-registry`. I have copied the definition that is used in the [Jenkins chart](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl) (among others).

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@victordzmr can you bump the Chart.yaml version?

**Comment by victordzmr** [comment]
@davidkarlsen Done! :)

**Comment by davidkarlsen** [comment]
@victordzmr still a conflict

**Comment by victordzmr** [comment]
@davidkarlsen Sorry, I didn't realize. Now it is ready to be merged.

**Pull request merged**
