### PR TITLE
[stable/prometheus] add hostAliases

### PR DESCRIPTION
**Pull request by wopincm**
What this PR does / why we need it:
Enables use of [HostAliases](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#hostalias-v1-core)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by wopincm** [comment]
Can it be merged, can't we play happily together?

**Comment by zanhsieh** [comment]
@wopincm 
Could you rebase again to latest chart version please?

**Comment by miono** [comment]
@wopincm This change is needed also in the file `server-statefulset.yaml` for people running a statefulset instead of a deployment.

**Pull request closed without merging**
