### PR TITLE
[incubator/jaeger] Add basePath option for Jaeger.

### LINKED ISSUE #7489: [incubator/jaeger] Add option for specifying basePath
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Jaeger has added a new option to set the base path of the query UI, which makes it usable behind reverse proxies. This option should also be exposed in the chart as well.

PR which added this support: https://github.com/jaegertracing/jaeger/pull/748

### PR DESCRIPTION
**Pull request by hypnoce**
Based on #7490

#### What this PR does / why we need it:
This PR allows jaeger to be configured behind a load balancer using [base-path](https://www.jaegertracing.io/docs/1.8/deployment/#ui-base-path)
#### Which issue this PR fixes
  - fixes #7489

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lachie83** [comment]
cc @dvonthenen @mikelorant @pavelnikolov

**Comment by pavelnikolov** [comment]
lgtm

**Pull request merged**
