### PR TITLE
Update elasticsearch chart to work with Kube 1.5

### PR DESCRIPTION
**Pull request by mkrakowitzer**
* Add environment variable KUBERNETES_MASTER, resolves issue documented
here:
https://github.com/fabric8io/fabric8/issues/6229#issuecomment-247373967
* Rename PetSet to StatefulSet, rename template file
* Add initialDelay and increase timesouts to all liveness and readiness
checks. This was the only way I could get it to deploy reliably in my
environment.
* Update to a newer image version

### CODE REVIEW

**Comment by seanknox** [comment]
@mkrakowitzer looks great. Now that this chart no longer uses Kubernetes Alpha APIs, can you move it to `stable/`?

**Comment by mkrakowitzer** [comment]
@seanknox done. Thanks.

**Comment by viglesiasce** [comment]
One more thing needed for the stable repo is to have a NOTES.txt file that tells people how they can connect to the cluster. For an example, look at the Jenkins chart:
https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/NOTES.txt

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by lostintangent** [comment]
Should the `DataStorageClassVersion` default in `values.yaml` be changed `beta` as well? Since this chart is being moved to `stable`?

**Comment by hekike** [comment]
@mkrakowitzer today I tested your branch and seems to be that`elasticsearch-client-deployment.yaml` and `elasticsearch-master-deployment.yaml` readiness and liveness probes are broken.

You try to probe for `9200` but the master has only `9300` for example.
Other than that it seems to work for me on GCP with:

```
DataStorageClass: "standard"
DataStorageClassVersion: "beta"
```

**Review by viglesiasce — CHANGES_REQUESTED** [review]
1) Make PVCs configurable
2) Fix health checks as reported by @hekike 
3) Add NOTES.txt (example in prometheus chart)

@mkrakowitzer for an example of how to configure the PVCs look at the prometheus chart:
https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L51
https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/alertmanager-deployment.yaml#L73
https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/alertmanager-pvc.yaml

**Comment by hekike** [comment]
@viglesiasce as @lostintangent recommended I think we should also change `storage-class` to `default` like at MySQL and PostgreSQL to improve portability: https://github.com/kubernetes/charts/blob/master/stable/postgresql/templates/pvc.yaml#L15

@maciaszczykm I'm happy to do these changes if you don't have time, just say a word.

**Comment by maciaszczykm** [comment]
@hekike Did you mean to @ me? I seem to be a little out of topic :-)

**Comment by hekike** [comment]
Sry, I missed it. :/ cc @mkrakowitzer

**Comment by unguiculus** [comment]
I'd suggest to rather not move the chart to stable yet. As I mentioned at https://github.com/kubernetes/charts/pull/1062#discussion_r116161560, I'd rather align it to best practices first and then move it in a separate PR.

**Comment by prydonius** [comment]
@unguiculus I agree that #1062 should be pushed through first. @mkrakowitzer want to close this out in the meantime? Perhaps you can migrate some of the other changes into #1062 or another PR.

**Comment by prydonius** [comment]
I see that #1062 is based on this one so already includes those changes. What do we want to do here? Close this in favour of #1062 and work on 1.5 changes in incubator there, and then follow up in a future PR to move it to stable?

**Comment by icereval** [comment]
I can rebase #1062 back on master and reapply my changes to the incubator files.

**Comment by prydonius** [comment]
@icereval that would be great, @mkrakowitzer I'll close this out in favour of #1062

**Comment by icereval** [comment]
Just an update for all watching, I was moving last week so did not get around to making the updates I promised. I plan on having time this week to make the changes, and unblock any further work.

**Pull request closed without merging**
