### PR TITLE
[stable/logstash] Add loadBalancerSourceRanges

### PR DESCRIPTION
**Pull request by thirstydeveloper**
#### What this PR does / why we need it:

Adds the ability to specify which CIDRs can access the logstash LoadBalancer service, if enabled, to help maintain a least privilege security posture.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by thirstydeveloper** [comment]
Ping @rendhalver @christian-roggia 

(Hopefully this will make the PR not be stale)

**Comment by thirstydeveloper** [comment]
*tap* *tap*. Is there anybody out there?

**Comment by christian-roggia** [comment]
/ok-to-test

Conflicts should be solved with the upstream branch.

**Pull request merged**
