### PR TITLE
[stable/redis-ha]  Fixed unused env section.

### PR DESCRIPTION
**Pull request by yutachaos**
#### Which issue this PR fixes
* Fixed the problem that empty env section remains when env of value.yaml is false.

* Procedure
```
## Master branch 
pwd
/Users/src/github.com/helm/charts/stable/redis-ha
 helm template ./ -f values.yaml --name redis  > orig.yaml
## Fixed branch
helm template ./ -f values.yaml --name redis  > fix.yaml

## diff 
diff fix.yaml orig.yaml
503a504
>         env:
```
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@yutachaos https://github.com/DandyDeveloper/charts

Can you also PR this here? This chart is being deprecated. Want to make sure they are in sync as best I can.

**Comment by yutachaos** [comment]
> @yutachaos https://github.com/DandyDeveloper/charts
> 
> Can you also PR this here? This chart is being deprecated. Want to make sure they are in sync as best I can.

@DandyDeveloper 
Thanks.
I sent a pull request this repository.
https://github.com/DandyDeveloper/charts/pull/10

**Pull request merged**
