### PR TITLE
[stable/redis-ha] Use sh instead of bash to support alpine image

### PR DESCRIPTION
**Pull request by ceshihao**
#### What this PR does / why we need it:
Bash is not supported when I use image `4.0.11-alpine`.

Therefore I change `bash` to `sh`, it can be compatible with alpine image.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
/cc @ssalaues 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by unguiculus** [comment]
ping @ssalaues

**Review by ssalaues — APPROVED** [review]
Upgraded so far without any issues running the script as sh. 

lgtm

**Comment by 007** [comment]
@ssalaues @ceshihao did you test this with the default `redis` non-alpine image? I'm getting failures for `init` and it seems to be the difference between Alpine/busybox `sh` and Debian `sh`.

**Comment by ceshihao** [comment]
I tried both `4.0.11-alpine` and `4.0.11-stretch` before.

@007 
Could you please clarify which image is used and what is the failure in details?

**Comment by 007** [comment]
It was showing syntax errors on the `function` definitions on the init script running against `5.0`.

I switched the interpreter to `bash` and it worked fine again, but it's odd that it wouldn't work as-is with `sh` since `5.0` is nearly identical to `4.0.11-stretch` - just `ca-certificates` and source version change.

**Comment by ssalaues** [comment]
@007 I looked into it and seems to be some bash-isms in the script that aren't quite POSIX portable. I'll make a PR to make the init script more portable.

**Pull request merged**
