### PR TITLE
stable/jenkins: Update kubernetes plugin URL

### PR DESCRIPTION
**Pull request by timja**
#### What this PR does / why we need it:
The previous WIKI URL is deprecated and all content removed, replaced with the new one

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [na] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@timja you need to increase the chart version. A little bit useless for this changes, but required CI checks.

**Comment by timja** [comment]
> @timja you need to increase the chart version. A little bit useless for this changes, but required CI checks.

yeah :( done

**Comment by torstenwalter** [comment]
@timja Thanks for the PR!

**Pull request merged**
