### PR TITLE
[prometheus-operator] Sync prometheus operator dashboard and rules

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Signed-off-by: Matteo Gazzetta <matteo_gazzetta@hotmail.it>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ElfoLiNk** [comment]
@gianrubio i rebased and synced again

**Comment by ElfoLiNk** [comment]
Any news ? i also update to point to the new repository https://github.com/coreos/kube-prometheus

**Comment by paskal** [comment]
@ElfoLiNk, thanks a lot! I'm very happy my work was used and improved by someone else.

**Pull request merged**
