### PR TITLE
[stable/cockroachdb] Add cert-manager example setup to documentation

### PR DESCRIPTION
**Pull request by joachimmathes**
Signed-off-by: Joachim Mathes <joachim_mathes@web.de>

#### What this PR does / why we need it:

@DuskEagle Referring to https://github.com/helm/charts/pull/20425#issuecomment-582573659: I've found the time to extend the documentation on how to use cert-manager certificates with the cockroachdb helm chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by kylos101** [comment]
@joachimmathes hi there, are you aware of instructions that I might be able to follow to get [cockroachdb-client-secure](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/client-secure.yaml) to work with a client root certificate provisioned by cert-manager? 

I've been trying to reuse the root certificate provisioned when I setup my cluster, but am getting this error:

```
W200621 17:48:29.761730 1 security/certificate_loader.go:312  bad filename /cockroach-certs/tls.crt: unknown prefix "tls"
Error: connections with user root must use a client certificate
```

Here is what my cert lists look like on my client and one of my DB nodes.

client
```
kubectl exec -it cockroachdb-client-secure \
> -- ./cockroach cert list \
> --certs-dir=/cockroach-certs
W200621 17:50:13.019224 1 security/certificate_loader.go:312  bad filename /cockroach-certs/tls.crt: unknown prefix "tls"
Certificate directory: /cockroach-certs
  Usage | Certificate File | Key File |  Expires   |    Notes     | Error  
+-------+------------------+----------+------------+--------------+-------+
  CA    | ca.crt           |          | 2021/06/21 | num certs: 1 |   
```

node-0
```
kubectl exec -it cockroachdb-0 -- ./cockroach cert list --certs-dir=/cockroach/cockroach-certs
Certificate directory: /cockroach/cockroach-certs
  Usage | Certificate File | Key File |  Expires   |                                                                            Notes                                                                             | Error  
+-------+------------------+----------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
  CA    | ca.crt           |          | 2021/06/21 | num certs: 1                                                                                                                                                 |        
  Node  | node.crt         | node.key | 2020/09/19 | addresses: localhost,node,*.cockroachdb.default.svc.cluster.local,*.cockroachdb,cockroachdb-public,cockroachdb-public.default.svc.cluster.local,127.0.0.1,:: |  
```

**Comment by kylos101** [comment]
> @joachimmathes hi there, are you aware of instructions that I might be able to follow to get [cockroachdb-client-secure](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/client-secure.yaml) to work with a client root certificate provisioned by cert-manager?
> 
> I've been trying to reuse the root certificate provisioned when I setup my cluster, but am getting this error:
> 
> ```
> W200621 17:48:29.761730 1 security/certificate_loader.go:312  bad filename /cockroach-certs/tls.crt: unknown prefix "tls"
> Error: connections with user root must use a client certificate
> ```
> 
> Here is what my cert lists look like on my client and one of my DB nodes.
> 
> client
> 
> ```
> kubectl exec -it cockroachdb-client-secure \
> > -- ./cockroach cert list \
> > --certs-dir=/cockroach-certs
> W200621 17:50:13.019224 1 security/certificate_loader.go:312  bad filename /cockroach-certs/tls.crt: unknown prefix "tls"
> Certificate directory: /cockroach-certs
>   Usage | Certificate File | Key File |  Expires   |    Notes     | Error  
> +-------+------------------+----------+------------+--------------+-------+
>   CA    | ca.crt           |          | 2021/06/21 | num certs: 1 |   
> ```
> 
> node-0
> 
> ```
> kubectl exec -it cockroachdb-0 -- ./cockroach cert list --certs-dir=/cockroach/cockroach-certs
> Certificate directory: /cockroach/cockroach-certs
>   Usage | Certificate File | Key File |  Expires   |                                                                            Notes                                                                             | Error  
> +-------+------------------+----------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
>   CA    | ca.crt           |          | 2021/06/21 | num certs: 1                                                                                                                                                 |        
>   Node  | node.crt         | node.key | 2020/09/19 | addresses: localhost,node,*.cockroachdb.default.svc.cluster.local,*.cockroachdb,cockroachdb-public,cockroachdb-public.default.svc.cluster.local,127.0.0.1,:: |  
> ```

Hi there, I was able to connect as root this:

```
kubectl exec -it cockroachdb-client-secure -- ./cockroach sql --url="postgres://root@cockroachdb-public:26257/?sslmode=verify-full&sslcert=/ca-certs/tls.crt&sslkey=/ca-certs/tls.key&sslrootcert=/ca-certs/ca.crt"
```

I'm not sure if there's a better way (like via mounting secrets to cockroachdb-client-secure, but this will do for now.

**Comment by joachimmathes** [comment]
@kylos101 You could apply
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  namespace: my-app
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v19.2.5
    env:
    - name: COCKROACH_CERTS_DIR
      value: /cockroach/cockroach-certs
    - name: COCKROACH_HOST
      value: cockroachdb
    command:
    - sleep
    - "2147483648" # 2^31
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb-root
      defaultMode: 0400
      items:
      - key: ca.crt
        path: ca.crt
      - key: tls.crt
        path: client.root.crt
      - key: tls.key
        path: client.root.key
```
With that pod running a connection can be established with:
```
$ kubectl exec -it cockroachdb-client-secure -- ./cockroach sql
```

Does this answer your question? If yes, I will extend the documentation in this PR.

**Comment by kylos101** [comment]
@joachimmathes I had no idea that secret keys could be rewritten using path like that ... thank you so much! Also, nice usage of ENV VARs. 

This was perfect, thank you very much for taking the time to help with this. Ultimately I hope it helps more people adopt cockroachdb. 👍

**Pull request closed without merging**
