### PR TITLE
Upgrade Kong README

### PR DESCRIPTION
**Pull request by ademspr**
Adding KONG_PG_SSL on environment variable options documentations.

### CODE REVIEW

**Comment by zanhsieh** [comment]
@ademspr 
Would you mind to sign DCO and bump the chart version to latest please?

Sign DCO instruction should be below ('DCO Action required after 1s — DCO' > click Details).

**Comment by ademspr** [comment]
@zanhsieh 
I Sign the DCO :D
What did you mean by bump the chart version to the latest ? change 0.26.0 -> 0.26.1?

**Comment by zanhsieh** [comment]
/check-dco

@ademspr 
That's correct.

**Comment by zanhsieh** [comment]
@ademspr 
Commit https://github.com/helm/charts/pull/18640/commits/a7766fa7e216ea47e3fc56386b7f8edd671b92d9
also need to get signed off.

**Comment by ademspr** [comment]
/check-dco
@zanhsieh 

Changed 💃

**Comment by zanhsieh** [comment]
@ademspr 
Commit https://github.com/helm/charts/pull/18640/commits/36c8a57f7b37f5fa29fa0dc1d786a7d1d7fa00c6 not signed.

**Comment by ademspr** [comment]
For me it appears signed LOL

image

**Comment by hbagdi** [comment]
Your first commit is missing DCO, the line at the end of the commit message:
`Signed-off-by: Ademir Pereira <ademirspr@live.com>`.

**Comment by zanhsieh** [comment]
@ademspr 
Also, the chart version needs to bump to latest please.
```
Old chart version: 0.27.0
New chart version: 0.26.1
Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ kong => (version: "0.26.1", path: "stable/kong") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Exited with code 1
```

**Pull request closed without merging**
