### PR TITLE
[stable/prometheus] add kubernetes_node label

### PR DESCRIPTION
**Pull request by spiarh**
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>

#### What this PR does / why we need it:
When using the cluster internal IP to scrape the metrics from node-exporterthere is no way to know which node Prometheus is scraping the metrics from because there is no label, for example:

> node_exporter_build_info{app="prometheus",branch="HEAD",chart="prometheus-7.3.4",component="node-exporter",goversion="go1.9.6",heritage="Tiller",instance="172.16.0.44:9100",job="kubernetes-service-endpoints",kubernetes_name="prometheus-node-exporter",kubernetes_namespace="monitoring",release="prometheus",revision="d42bd70f4363dced6b77d8fc311ea57b63387e4f",version="0.16.0"}

Adding the kubernetes_node allows us to know which node is scraped. It is also easier even when the host IP is used because we work with hostnames in Kubernetes, for example:

>  node_exporter_build_info{app="prometheus",branch="HEAD",chart="prometheus-7.3.4",component="node-exporter",goversion="go1.9.6",heritage="Tiller",instance="172.16.0.44:9100",job="kubernetes-service-endpoints",kubernetes_name="prometheus-node-exporter",kubernetes_namespace="monitoring",**kubernetes_node="vm153071"**,release="prometheus",revision="d42bd70f4363dced6b77d8fc311ea57b63387e4f",version="0.16.0"}

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by lcavajani** [comment]
I have updated the chart version and fix the conflicts ;)

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Pull request merged**
