### PR TITLE
[stable/minio] Add affinity and toleration to bucket creation job

### PR DESCRIPTION
**Pull request by alexrashed**
#### What this PR does / why we need it:
Currently minio allows defining nodeSelectors, affinities and tolerations which are applied to the deployment. For the bucket-creation job only the nodeSelectors are set. If a nodeSelector restricts the deployment to nodes with taints (which are tolerated for the deployment but not for the bucket-creation) the deployment fails.

#### Which issue this PR fixes
None submitted.

#### Special notes for your reviewer:
Applied the same affinity and toleration definition as found in the deployment template.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by alexrashed** [comment]
Is there any interest in the PR? I tested it in my setup and I guess the review would only take a minute ;)

**Comment by nitisht** [comment]
can you please resolve the conflict @alexrashed

**Pull request merged**
