### PR TITLE
[stable/gocd] Quote ingress host

### PR DESCRIPTION
**Pull request by austinorth**
When using a wildcard DNS name for host, such as *.example.com, Helm
fails with a yaml parsing error. 

Signed-off-by: Austin Orth <aorth@niche.com>

#### What this PR does / why we need it:
Added quote function to allow use of wildcard DNS names in the ingress template. Without this PR, Helm will error when trying to set up the ingress when users try a wildcard DNS name.

#### Which issue this PR fixes
When setting `hosts` in values file to `["*.example.com"]`
```bash
$ helm install gocd ./ -f ~/gocd/values.aws.yaml
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
Error: YAML parse error on gocd/templates/ingress.yaml: error converting YAML to JSON: yaml: line 16: did not find expected alphabetic or numeric character
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

**cc:** @arvindsv @ganeshspatil @varshavaradarajan

### CODE REVIEW

**Review by varshavaradarajan — APPROVED** [review]
Thanks for the PR @austinorth! Do you mind changing the api version of ingress to `networking.k8s.io/v1beta1`? Just want to avoid an additional release just for that. I had tried doing it before - https://github.com/helm/charts/pull/15377#issuecomment-509897523

**Comment by varshavaradarajan** [comment]
@austinorth - Can you please update the changelog?

**Comment by austinorth** [comment]
@varshavaradarajan sure! should I include the chart bump commit, or just https://github.com/helm/charts/pull/20477/commits/b85600766063ea78ece92e9a7ffefc3092b7be77 and https://github.com/helm/charts/pull/20477/commits/e2f27a9d14ff60432f18f95c70d1458a85ef8000 ?

**Comment by varshavaradarajan** [comment]
just b856007 and e2f27a9 should be fine

**Pull request merged**
