### PR TITLE
Typo fix in cert-manager/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
line 52: 
"The following tables lists"->"The following table lists"

### CODE REVIEW

**Comment by kragniz** [comment]
For cert-manager, we generally prefer changes to the chart be merged upstream ([here](https://github.com/jetstack/cert-manager/tree/master/contrib/charts/cert-manager)), but since this case is a trivial typo, I'll merge here and manually sync upstream.

/ok-to-test

**Review by kragniz — APPROVED** [review]
/lgtm

**Comment by AdamDang** [comment]
@kragniz Thanks a lot!

**Pull request merged**
