### PR TITLE
[stable/prometheus] Add a New Maintainer and Owner

### PR DESCRIPTION
**Pull request by Xtigyro**
#### Is this a new chart

No.

#### What this PR does / why we need it:

- Adds a new maintainer and owner.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@Xtigyro 
Merged. Welcome aboard.

**Comment by Xtigyro** [comment]
@zanhsieh Thank you! I feel honoured. I wish we all have a good time together. 

Do I need to talk to any other Helm members about my permissions in the repo? Will I bee able to review and merge PRs of other people now?

**Pull request merged**
