### PR TITLE
Fix README documentation

### PR DESCRIPTION
**Pull request by moorara**
**What this PR does / why we need it**:
Documentation regarding `updateStrategy` is not quite right. This value is nested under `statefulset` and represents the update strategy for statefulsets.

The default value for `antiAffinity` is `soft`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@moorara Can you please sign the CLA and bump the Chart.yaml version?

**Comment by moorara** [comment]
@davidkarlsen DONE

**Pull request merged**
