### PR TITLE
[stable/kube-state-metrics] Solve #13961

### LINKED ISSUE #13961: [stable/kube-state-metrics] The values description show follow proper grammar and be consistent
See [here](https://github.com/helm/charts/tree/master/stable/kube-state-metrics). Some of the sentences in the Description column do not follow the required grammatical convention (the first letter of the first word should be capitalized).

FYI @batazor

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Login Victor <batazor111@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #13961

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by batazor** [comment]
@tariq1890 Fix description on README.md and formatted table

/assign @tariq1890

**Review by tariq1890 — APPROVED** [review]
/ok-to-test

**Comment by tariq1890** [comment]
@batazor Can you squash your commit history?

**Comment by batazor** [comment]
@tariq1890 done

**Review by tariq1890 — APPROVED** [review]

**Pull request merged**
