### PR TITLE
[stable/cockroachdb]: Update version to v19.2.6

### PR DESCRIPTION
**Pull request by nathanstilwell**
Signed-off-by: Nathan Stilwell <nathanstilwell@cockroachlabs.com>

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by otan** [comment]
obsoleted by v20.1.0

**Comment by joshimhoff** [comment]
@nathanstilwell, close?

**Comment by nathanstilwell** [comment]
obsolete

**Pull request closed without merging**
