### PR TITLE
[stable/cockroachdb]: Update version to v19.2.4

### PR DESCRIPTION
**Pull request by danhhz**
Signed-off-by: Dan Harrison <dan@cockroachlabs.com>

#### What this PR does / why we need it:

Updates the cockroachdb version to the latest stable version v19.2.3 -> 19.2.4

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DuskEagle** [comment]
Hey @danhhz , 

It appears the name and email in your `Signed-off-by` line doesn't match the name and email you used to author this commit. This is causing [the DCO step to fail](https://github.com/helm/charts/pull/20698/checks?check_run_id=439757335). Can you update this commit with a corrected signoff?

**Comment by danhhz** [comment]
@DuskEagle Sorry about that, done!

**Review by joshimhoff — APPROVED** [review]
LGTM.

**Pull request merged**
