### PR TITLE
[stable/wordpress] Add pod tolerations and affinity.

### PR DESCRIPTION
**Pull request by jeff-french**
**What this PR does / why we need it**:
Allows installers of the Wordpress chart to specify tolerations and affinity to better control how the pods are distributed in their cluster.

### CODE REVIEW

**Comment by juan131** [comment]
Hi @jeff-french 

Thanks for the contribution! Please bump the chart minor version on the **Chart.yml** file.

Please also note that we document every single parameter available on the values.yml on the **README.md** file. Could you please ensure these new parameters are included on that README?

**Comment by juan131** [comment]
Hi @jeff-french 

It seems you bumped the version to **2.1.0**. Please just bump the minor version, so you move it from **2.0.1** to **2.0.2**.

**Comment by jeff-french** [comment]
Hi @juan131 

I had originally bumped the version to *2.0.2* but then I noticed that you had asked me to bump the _minor_ version. According to [Semver](https://semver.org/) the numbers are `<major>.<minor>.<patch>` so I changed it to *2.1.0*. I'll push up another commit bumping the _patch_ version to *2.0.2*.

**Comment by juan131** [comment]
Hi @jeff-french 

You're right! Sorry for the noise

**Review by prydonius — APPROVED** [review]
I agree that 2.1.0 is correct here since this is adding a feature in a backwards compatible way.

/lgtm

**Comment by jeff-french** [comment]
@prydonius I pushed a commit to remove the blank line that caused the build failure.

**Pull request merged**
