### PR TITLE
[stable/reflector] Add Reflector

### PR DESCRIPTION
**Pull request by winromulus**
#### What this PR does / why we need it:

Add Reflector (https://github.com/EmberStack/ES.Kubernetes.Reflector)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by scottrigby** [comment]
Update: @winromulus and I are working to add the EmberStack/ES.Kubernetes.Reflector chart to the new https://hub.helm.sh instead, since it's a perfect chart for it (already hosted). They will need to:

1. Set up that helm chart as a Helm per [this doc](https://github.com/helm/hub/blob/master/docs/github.md)
1. Open a PR at github.com/helm/hub per [this doc](https://github.com/helm/hub#how-to-add-your-helm-charts)

Let's leave this PR open until that is done.

**Comment by winromulus** [comment]
Added PR https://github.com/helm/hub/pull/71 for the Hub

**Comment by scottrigby** [comment]
Merged to hub repo 👍

**Pull request closed without merging**
