### PR TITLE
[stable/redis-ha] Enable sticky connections balancing via HAProxy.

### PR DESCRIPTION
**Pull request by Antiarchitect**
I just found that python Redis client (Sentry, Weblate) is having trouble with HAProxy + Redis HA scheme.
It seems like HAProxy `balance source` + `hash-type consistent` does the trick.
More info: https://www.haproxy.com/blog/client-ip-persistence-or-source-ip-hash-load-balancing/#source-ip-hash-load-balancing-algorithm

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
The changes look good. You will just need a rebase and re-bump of the version.

**Comment by Antiarchitect** [comment]
@ssalaues Done

**Comment by Antiarchitect** [comment]
```
Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
``` 
in tests. Seems this is related to metrics-server on the test environment is down and the process hangs

**Pull request merged**
