### PR TITLE
[incubator/vault] Allow additional arguments for vault server command

### PR DESCRIPTION
**Pull request by orirawlings**
Signed-off-by: Ori Rawlings <orawlings@egencia.com>

#### What this PR does / why we need it:
This PR allows the user to set the args array on the vault server containers. 

My specific use case is to allow additional `-config` options which refer to dynamically generated files (based on data from the [Kubernetes Downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/)). I needed to set up telemetry configuration for a DataDog Agent that runs as a daemonset on the host IP address. Basically something like the following:
```
vault:
  extraArgs:
  - -config
  - /telemetry-config/telemetry.hcl
  extraVolumeMounts:
  - mountPath: /telemetry-config
    name: telemetry-config
  extraInitContainers:
  - name: telemetry-config
    image: busybox:1.31.0
    env:
    - name: DOGSTATSD_ADDR
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    command: ["/bin/sh", "-c"]
    args:
    - |
      cat > /telemetry-config/telemetry.hcl <<EOF
      telemetry {
        dogstatsd_addr = "${DOGSTATSD_ADDR}:8125"
      }
      EOF
    volumeMounts:
    - mountPath: /telemetry-config
      name: telemetry-config
  extraVolumes:
  - name: telemetry-config
    emptyDir: {}
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jbialy** [comment]
@orirawlings This is an interesting use-case! 

Adding the `args` option to the container spec reminds me of this issue: https://github.com/helm/charts/issues/12470

I think that switching away from using the `command` option in the Chart and falling back on the container's entrypoint would a good idea. What's your take on that? Of course, the option for adding extra args can definitely remain!

**Comment by orirawlings** [comment]
@jbialy I think switching to the official entry point in the image might be a good idea. Maybe for this PR, I can call the new variable `extraArgs` instead of `args`? It might be easier to switch the template to use the set the PodSpec Container `args` rather than `command` as it does today, without bumping in to potential confusion or incompatibilities for the chart users that have adopted the `args` chart variable.

**Comment by orirawlings** [comment]
@jbialy I updated this PR to use `vault.extraArgs` instead of `vault.args`.

**Comment by jbialy** [comment]
> @jbialy I updated this PR to use `vault.extraArgs` instead of `vault.args`.

Great, I think that using `extrArgs` will be more clear!

**Review by jbialy — APPROVED** [review]

**Comment by orirawlings** [comment]
@jbialy do you need anything else from me for this to be merged? Looks like it is still missing the `approved` and `lgtm` labels.

**Comment by jbialy** [comment]
> @jbialy do you need anything else from me for this to be merged? Looks like it is still missing the `approved` and `lgtm` labels.

Looks good!

**Comment by jbialy** [comment]
Thanks for making the changes so fast!

**Pull request merged**
