### PR TITLE
[stable/spinnaker] Fix environment variable name for proxy in Java

### PR DESCRIPTION
**Pull request by Wykiki**
The previous environment variable DEFAULT_JVM_OPTS was not giving to Halyard the correct proxy settings.
Renaming it to JAVA_OPTS fixed that.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by aegershman** [comment]
Just to be clear, [does this mean the doc about using halyard behind a proxy is incorrect?](https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-run-halyard-behind-a-proxy)

I literally just ran into this issue a few hours ago, and I found even with setting `halyard.env. DEFAULT_JVM_OPTS="-Dhttp.proxyHost=10.xxx.yyy.zzz -Dhttp.proxyPort=3128"`, hal config didn't appear to be respecting the proxy. But that certainly could've been (and probably was) user error on my part.

**Comment by Wykiki** [comment]
For my use case, running Spinnaker on a Kubernetes behind a corporate proxy, I needed to change what is mentionned in the documentation [about proxy](https://github.com/helm/charts/pull/15061/files#diff-91f0ff1f45e99083851f8f4f1b909dbbL172).
Renaming the env var `DEFAULT_JVM_OPTS` to `JAVA_OPTS` did the trick.

**BELOW IS NOT DIRECTLY RELATED TO THIS PR**

After that, Spinnaker deployed successfully, but the pod `spin-clouddriver` encountered some proxy errors, due to `JAVA_OPTS` being overriden in this container.

The hack I did was to manually update the env var of this pod (`spin-clouddriver`), and it worked.

I may work on a correct fix about that if I get some time.

**Pull request merged**
