### PR TITLE
[stable/sentry] Refactor charts for reduced boilerplate on env variables and add existingSecrets

### PR DESCRIPTION
**Pull request by stephenmoloney**
#### What this PR does / why we need it:

- Reduce boilerplate code
- Enhance readability
- Adds possibility to use an existing secret

#### Which issue this PR fixes

- Refactor charts for reduced boilerplate on env variables
- Refactor the template "redis.fullname" and "redis.fullname" to
take account of a potential nameOverride or fullNameOverride as is
possible in the redis and postgresql parent charts respectively
- Add a reference to existingSecret to allow to use a user added secret instead of 
the standard secret for parent chart and subcharts

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by stephenmoloney** [comment]
@davidkarlsen Any chance of a review?

**Comment by unguiculus** [comment]
cc @rothgar

This is an excellent change. Sorry for the delay. Could you fix conflicts, please, and I'll try and get it merged.

**Comment by stephenmoloney** [comment]
@unguiculus 

There have been a few substantial changes to the sentry chart and the rebase will be involved - I read through all previous merges since then.
The most recent merge requests add the ability to use external postgresql and external redis hosts which is a great feature and helpful PRs. 
I would like to make some patches onto those ones though because my approach here with a single existingSecret is incompatible with those PRs.

Also, I have some additional PRs (sitting on my laptop) that take a different approach.

Given that PR reviews take a long time, 

1. should I just do one big massive PR with all my suggested changes 
or 
2. incremental PRs ?

Normally, I'd always pick 2 but I think 1 is better given the time to review and all the changes that occur in the interim.

**Comment by unguiculus** [comment]
Pick whatever makes the most sense in your case, but, in general, smaller PRs are easier to review.

**Comment by mattfarina** [comment]
@stephenmoloney I'm sorry about the delay. I was hoping @rothgar would have reviewed by now. Can you please rebase from master? Due to the conflicts we cannot merge it right now.

**Comment by rothgar** [comment]
Sorry about the delay. I didn't realize this was waiting on me. I looked over the changes (they looked good from what I could tell) but I didn't deploy it to test.

**Comment by stephenmoloney** [comment]
Hi @rothgar, @unguiculus, @mattfarina 

Thanks for getting back to me even if it's later than I hoped. Opensource takes time and everyone is on a different schedule so I understand.

I did the bulk of this work a few months ago and I really just can't get time to continue this PR having just started a new job.

Ultimately, I had hoped to introduce a createProject job based off of work I completed some time ago that is visible [here](https://github.com/stephenmoloney/saleor-helm/tree/fork/sentry-charts/deployment/helm/forked-charts/sentry) but I won't have time now to clean it up and get a new PR written. 

I'll close this PR for now, If somehow I get the time to finish this work off, I'll try to reopen.

Thanks for this chart.

**Pull request closed without merging**
