### PR TITLE
[stable/minio] Set service name to HTTP/HTTPS rather than Service

### PR DESCRIPTION
**Pull request by carpenike**
#### What this PR does / why we need it:
Tools like Istio configure their backend paths based on the name of the service (http/https/etc). This dynamically sets the service name based on whether TLS is enabled or not.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by harshavardhana** [comment]
@carpenike PTAL tests are failing

**Comment by harshavardhana** [comment]
@carpenike looks like the change breaks helm install

```
I0213 16:35:16.994] Error: release minio-h21msh2sla failed: timed out waiting for the condition
I0213 16:35:16.996] ========================================================================================================================
I0213 16:35:16.997] ........................................................................................................................
I0213 16:35:16.997] ==> Events of namespace minio-presubmit-20649-1227991889290989568-h21msh2sla
I0213 16:35:16.997] ........................................................................................................................
I0213 16:35:17.939] LAST SEEN   TYPE      REASON                   OBJECT                                            SUBOBJECT                SOURCE                                            MESSAGE                                                                                                                                   FIRST SEEN   COUNT   NAME
skipped 538 lines unfold_more
W0213 16:35:48.384]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0213 16:35:48.384]     subprocess.check_call(cmd)
W0213 16:35:48.384]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0213 16:35:48.384]     raise CalledProcessError(retcode, cmd)
W0213 16:35:48.385] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0213 16:35:48.385] Command failed
I0213 16:35:48.385] process 667 exited with code 1 after 11.0m
E0213 16:35:48.385] FAIL: pull-charts-e2e
```

**Comment by carpenike** [comment]
@harshavardhana, I had missed one of the service ports when using a statefulset. I don't use statefulsets so it never showed up in my environment. :(

Sorry!

**Pull request merged**
