### PR TITLE
[stable/prometheus-operator] Integrate PSP Clusterroles into regular ones

### PR DESCRIPTION
**Pull request by mrueg**
#### What this PR does / why we need it:
- integrate PSP Clusterroles into regular Clusterroles

#### Special notes for your reviewer:
This would get rid off making clusterroles more complex than they should be.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Tested

### CODE REVIEW

**Comment by gianrubio** [comment]
Have you tested this changes?

**Comment by mrueg** [comment]
Sorry, not tested yet lacking access to a k8s cluster right now. I'll rebase on master in the upcoming days.

**Comment by paskal** [comment]
@mrueg, have you tested these changes?

**Comment by mrueg** [comment]
Rebased onto master. Hopefully get some time to test this.

**Comment by paskal** [comment]
Was it ever tested? Do you need help with this one?

**Pull request closed without merging**
