### PR TITLE
[stable/concourse] Fixing parsing error in _helper file

### PR DESCRIPTION
**Pull request by spaghettifunk**
#### What this PR does / why we need it:

This PR solves a problem when installing the chart. There was a parsing error - precisely `Error: parse error in "concourse/templates/_helpers.tpl": template: concourse/templates/_helpers.tpl:63: unexpected "=" in operand`

#### Which issue this PR fixes
None

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cirocosta** [comment]
Hi @spaghettifunk ,

Thanks for your contribution!

Would you mind checking if you're getting into the same problem as https://github.com/helm/charts/pull/15220#issuecomment-508219465? If so, which version of Helm are you using?

Thank you!

**Comment by spaghettifunk** [comment]
Hi @cirocosta,

Thanks for pointing that out. My current version of `Helm` is `2.11.0` while `go` is `1.12.4`. From the comments above, I couldn't really understand if that is a problem with my current version or not. Should we ignore this PR for compatibility or do we need to wait for something else? :)

Let me know how to proceed :)

Thank you!

**Comment by cirocosta** [comment]
Hi @spaghettifunk,

I was searching around [helm/helm](https://github.com/helm/helm), and it seems like ﻿﻿this is indeed a known issue for versions `<=` 2.11: https://github.com/helm/helm/issues/4987#issuecomment-460654819

> Helm 2.11.0 was compiled against Go 1.10 which is why this feature won't work. You need to use something compiled against issue 4637 (such as Helm 2.12.0-rc.1) if you want to use a version of Helm compiled against Go 1.11.

Later, in the same issue, a workaround:

> nuxlli As tested and proved, this works with v2.12.x. If you can't use this version then maybe compile against Go 1.11.

---

Regarding the PR itself, it seems to me that switching from assignment  (`=`) to definition (`:=`) is not right - the effect that we want isn't really achieved 🤔  

E.g., consider the following `sample.yaml` values file:

```yaml
web:
  service:
    type: NodePort
    tsaNodePort: 30001
```

Applying the patch from this PR (i.e., using `:=`):

```console
$  helm template --values=./sample.yaml --name=abc  . -x ./templates/worker-statefulset.yaml | ag -A 1 'TSA_HOST'
            - name: CONCOURSE_TSA_HOST
              value: "abc-web:2222"
```

Now, moving back to what's currently in `master` (i.e., using `=`):

```console
$ helm template --values=./sample.yaml --name=abc  . -x ./templates/worker-statefulset.yaml | ag -A 1 'TSA_HOST'
            - name: CONCOURSE_TSA_HOST
              value: "abc-web:30001"
```

IMO the way to move forward would be to clearly state in the `README.md` for this Chart that it needs Helm `>` 2.11.

Wdyt?

Thank you!

**Comment by spaghettifunk** [comment]
@cirocosta I think you are absolutely right! I appreciate the time you spent in writing the examples and made me understand much better how it would behave.
I agree with you that we can ignore this PR and state in the README the version of Helm that is required 😃 

Thanks once again!

**Pull request closed without merging**
