### PR TITLE
Template does not use storageClass

### PR DESCRIPTION
**Pull request by mzehrer**
The template does not make use of a configured cluster.persistentVolume.storageClass value for the Stateful Set. The property is documented but not applied.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
You also need to bump the version in Chart.yaml.

**Comment by mzehrer** [comment]
Version is now 0.1.2

**Comment by timstoop** [comment]
Merging from master made the version no longer bumped :) You'll need to bump it again.

**Comment by mzehrer** [comment]
Oh my... this pull request thing makes me confused.... now it should be OK?

**Comment by timstoop** [comment]
It seems there are still some problems: `[ERROR] templates/: render error in "rethinkdb/templates/rethinkdb-cluster-stateful-set.yaml": template: rethinkdb/templates/rethinkdb-cluster-stateful-set.yaml:105:8: executing "rethinkdb/templates/rethinkdb-cluster-stateful-set.yaml" at <eq "-" .Values.clust...>: error calling eq: invalid type for comparison`

**Comment by unguiculus** [comment]
There's another PR for storage class which is kind of stuck: #2030

**Pull request closed without merging**
