### PR TITLE
[stable/aerospike] upgraded statefulset to apps/v1, needed for kubernetes 1.16

### PR DESCRIPTION
**Pull request by raducrisan1**
Signed-off-by: Radu Crisan <radu.crisan@gmail.com>

#### What this PR does / why we need it:
Minikube 1.4.0 deploys kubernetes version is 1.16.  The developers that use it (or other ways of using kubernetes 1.16)  will not be able to have the aerospike chart working anymore without this change. Reason: the deprecation of statefulsets versioned apps/v1beta1. Older versions of kubernetes are not affected, since the statefulsets v1 have been introduced in kubernetes 1.9.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by okgolove** [comment]
Hi @raducrisan1. Thank you for the PR.
Could you bump the chart's version?
Also, it will be great if you change the documentation [here](https://github.com/helm/charts/blob/master/stable/aerospike/README.md#pre-requisites).

**Comment by raducrisan1** [comment]
Hi,

I have fixed the chart version and adjusted the kubernetes version in the Readme.md file.

**Review by okgolove — APPROVED** [review]

**Pull request merged**
