### PR TITLE
[stable/jasperreports] Use storageClassName for jasperreports.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed jasperreports for #1869

/cc @prydonius

### CODE REVIEW

**Comment by prydonius** [comment]
@gyliu513 it would make sense to get the same fix in mariadb merged and update the dependency here before merging this

**Review by prydonius — CHANGES_REQUESTED** [review]
wait for mariadb update

**Comment by gyliu513** [comment]
@prydonius The Mariadb patch was now merged https://github.com/kubernetes/charts/pull/2004

**Pull request merged**
