### PR TITLE
[stable/nginx-ingress] If clusterIPs are set, they will automatically be quoted

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:

So that if by chance clusterIP values are actually provided (this PR aside, these are values that should not even exist imho), they are automatically quoted.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

Along the path to the current fix for the infamous clusterIP conflicts of having them commented out in the default values file, I proposed a fix that included removing the `| quote` in the templates. This proved to be useless, so I am adding that back for those (if anyone) that set their clusterIPs.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

cc @ChiefAlexander @taharah

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
/lgtm
Thanks!

**Comment by ChiefAlexander** [comment]
Other changes have been merged in before yours. You will have to fix the conflicts and then bump the version of the chart.

**Comment by naseemkullah** [comment]
np @ChiefAlexander, done.

**Comment by ChiefAlexander** [comment]
Sorry about this, but yet another change went in before yours. You will have to update your pr again.

**Comment by naseemkullah** [comment]
np @ChiefAlexander I think I screwed up anyways, should be good now

**Comment by ChiefAlexander** [comment]
/lgtm
Thanks!

**Comment by cgroschupp** [comment]
@naseemkullah How is it possible to set ClusterIP to an empty string after this PR?

values.yaml:
```
defaultBackend:
  service:
    omitClusterIP: false
    clusterIP: '""'
```
With chart version 0.28.1, i get this:
```
clusterIP: ""
```
With chart version 0.28.2, i get this:
```
clusterIP: "\"\""
```

**Comment by naseemkullah** [comment]
> @naseemkullah How is it possible to set ClusterIP to an empty string after this PR?
> 
> values.yaml:
> 
> ```
> defaultBackend:
>   service:
>     omitClusterIP: false
>     clusterIP: '""'
> ```
> 
> With chart version 0.28.1, i get this:
> 
> ```
> clusterIP: ""
> ```
> 
> With chart version 0.28.2, i get this:
> 
> ```
> clusterIP: "\"\""
> ```

Hi @cgroschupp  try `clusterIP: ""` or `clusterIP:`` or `clusterIP: null` one of those should  work.
I'm curious as to why though, is it beneficial to have `clusterIP: ""` in the resulting template?

**Comment by cgroschupp** [comment]
Hi @naseemkullah None of the variants produces an empty string.  older kubernetes version requires an empty string in ClusterIP. Now is it possible to omit the ClusterIP. But you have to destroy the old service. Therefore the parameter omitClusterIP was introduced.

**Comment by naseemkullah** [comment]
My mistake @cgroschupp and I did not know older k8s versions required an empty string as ClusterIP. 

By default the chart now does not template this, even without the omitClusterIP because in the default values file `clusterIP:` values are commented out altogether. If this does not play well with older versions of k8s we should maybe update the minimum k8s version required to run this chart as is.

**Pull request merged**
