### PR TITLE
[stable/kibana] updated kibana to 6.5.0

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it:
* updated kibana to 6.5.0

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by compleatang** [comment]
@monotek do you want to join me as an owner of this chart as you've made quite a few improvements to it and it's probably not ideal for the community to have only one owner considering the traffic this chart is starting to get. 

Also, would be grateful for your thoughts on us bumping the chart to 1.0 considering my view is that it is pretty stable now.

**Review by compleatang — APPROVED** [review]

**Comment by monotek** [comment]
Hey Casey,

shure. I'm glad if i can help :-)

Regards
André

**Pull request merged**
