### PR TITLE
[stable/redis-ha] Change to statefulset and add pdbs and extra options (from #4038 + extra)

### PR DESCRIPTION
**Pull request by timstoop**
**What this PR does / why we need it**:
This is a continuation of the PR #4038, as the original requester seems to be busy. Aside from fixing all the requested changes from that ticket, I've also added the following
- affinity per server and per sentinel
- the option to add extra Labels
- persistent volumes, as supplied by @thuandt 
- the Dockerfile and scripts used for the images as created by @bzumhagen and @smileisak, I merged their respected changes

**Special notes for your reviewer**:
@unguiculus @scottrigby you both already reviewed this in #4038, so although this is a very large PR, it shouldn't contain lots of surprises.

### CODE REVIEW

**Comment by bzumhagen** [comment]
Hi Tim,

Thanks for doing this. However the main reason I went radio silent was because we identified some gaps in the chart which actually meant it wasn't as stable as we thought. I've updated my PR with the new stabilizations and hopefully this will make for a good basis.

**Comment by timstoop** [comment]
Thanks for letting me know! I'll put this one on hold until your changes are applied so my small changes can get incorporated as well :)

**Comment by timstoop** [comment]
/hold
Wait until #4038 is merged.

**Comment by bzumhagen** [comment]
I would also recommend we add PSV in a new PR. In order to limit the number of big changes we are making (and also because I haven't tested using the PSV)

**Comment by bzumhagen** [comment]
I appreciate the effort though, I know how much it sucks when someone disappears before something you need gets merged.

**Comment by timstoop** [comment]
/ok-to-test cancel
Let's wait until it's actually working locally and the other patches are applied.

**Comment by timstoop** [comment]
Can't be cancelled :(

**Pull request closed without merging**
