### PR TITLE
[stable/postgresql] Support adding labels and annotations to pods.

### PR DESCRIPTION
**Pull request by bradenwright**
#### What this PR does / why we need it:

It allows the ability to add labels and annotations to the pods.  This is need so I can disable Istio's sidecar proxy via an annotation.

#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by tompizmor — CHANGES_REQUESTED** [review]
Can you also apply the changes from `values.yaml` to `values-production.yaml`?

**Comment by tompizmor** [comment]
It seems there are also conflicts in the `Chart.yaml` file. Can you resolve them?

**Comment by bradenwright** [comment]
@tompizmor sorry missed the notification somehow, but should be all good now

**Comment by tompizmor** [comment]
No worries! 
/ok-to-test
/lgtm

**Pull request merged**
