### PR TITLE
[stable/kibana] Add support for user-defined init containers

### PR DESCRIPTION
**Pull request by pavdmyt**
#### What this PR does / why we need it:

Allows to define custom init containers. This is useful for e.g. checking if elasticsearch is already up and running (before starting kibana container), creating custom ES indexes for kibana upfront, etc. More generic example use-cases can be found here: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#examples

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by onorua — APPROVED** [review]

**Comment by compleatang** [comment]
@pavdmyt can you please add a test case in the ci directory? this is seemingly a reasonable perspective to take and the PR looks fine from my POV, but it would be helpful for others to have a test case in the ci so this feature of the chart doesn't break going forward.

**Comment by pavdmyt** [comment]
@compleatang sure, I'll prepare commit.

**Comment by pavdmyt** [comment]
@compleatang  I've changed `initContainers` type from `[]` to `{}`. This is useful because it makes possible to override specific fields of any init container from a parent chart (very helpful for my specific use-case).

Regarding tests in `ci` directory. I'm not sure how it is exactly working. [README](https://github.com/helm/charts/blob/master/test/README.md) is not very clear to me. As I understood, it is possible to provide custom `*-values.yaml` file which will be used at CI side to pass additional values to default chart's `values.yaml`. I've created `ci/initcontainers-values.yaml` for this purpose. Please advice whether it is appropriate.

**Comment by compleatang** [comment]
Yup. That's how that dir works. Thanks!

/ok-to-test

**Pull request merged**
