### PR TITLE
[incubator/vault] allow extra init containers to be added

### PR DESCRIPTION
**Pull request by mikeraimondi**
#### What this PR does / why we need it:
Allows adding init containers. One use case is to manage plugins.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by apenney** [comment]
Anything we can do to get this unstale @paulczar?

**Comment by mikeraimondi** [comment]
@paulczar merge conflicts are addressed. Let me know if I can do anything to move this forward.

**Comment by sdickhoven** [comment]
is there a way to get this pr merged? we're using vault with google 2fa and need init containers to add the google auth plugin to vault.

**Comment by mikeraimondi** [comment]
@paulczar merge conflicts addressed again! Still hopeful we can get this merged.

**Comment by mattfarina** [comment]
cc @jpds

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
