### PR TITLE
[stable/weave-scope] update weave-scope to 1.11.0

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

#### What this PR does / why we need it:

Updates Weave Scope to the latest stable release.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

thanks!

**Comment by dholbach** [comment]
ccing @fbarl and @bboreham re: https://github.com/helm/charts/pull/13949/commits/d5ba531762f5dc049c765fbbcb0ee6d44190cf9e

**Comment by maorfr** [comment]
Would you mind also adding yourselves to Chart.yaml?

**Comment by maorfr** [comment]
i have already added you all as collaborators :)

**Comment by dholbach** [comment]
Thanks @maorfr - done!

**Comment by dholbach** [comment]
@maorfr Not sure if you can help with the failing test. I have no idea why this is happening.

**Comment by maorfr** [comment]
/test pull-charts-e2e

i see no reason as well.

**Comment by dholbach** [comment]
Third time lucky? :crossed_fingers:

**Comment by maorfr** [comment]
/retest

is it possible that this is failing?

https://github.com/helm/charts/blob/2ccc033ab7d2e2b7bda219e9da94e0d49b43fc09/stable/weave-scope/templates/test-config.yaml#L12

**Comment by maorfr** [comment]
/lgtm

passed passed! :)

**Pull request merged**
