### PR TITLE
[stable/redis-ha] Updating OWNERS list.

### PR DESCRIPTION
**Pull request by DandyDeveloper**
#### What this PR does / why we need it:
Helping out ssalaues with the chart. Adding myself to OWNERS. 

#### Special notes for your reviewer:
@ssalaues They mentioned they'd add me to approved list so I'm just throwing this PR out there to start that process.

@maorfr Per [comment](https://github.com/helm/charts/issues/13867#issuecomment-526899687) adding this PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@maorfr Invalid OWNERS right now, let me know if I can do anything to help get this process going.

**Comment by ssalaues** [comment]
@DandyDeveloper I approved this PR https://github.com/helm/charts/pull/16256 first so you will have to rebase once it merges.

@maorfr I'm okay with these changes and adding @DandyDeveloper as a maintainer to the chart.

**Comment by maorfr** [comment]
/ok-to-test
/approve

@DandyDeveloper once you accept the invitation, comment `/verify-owners`

**Pull request merged**
