### PR TITLE
Kong, Cassandra, and PostgreSQL version bump

### PR DESCRIPTION
**Pull request by shashiranjan84**
- Kong version bumped to 0.13.1
- Cassandra chart version bumped to 0.2.6
- PostgreSQL chart bumped to 0.10.0

### CODE REVIEW

**Comment by shashiranjan84** [comment]
@unguiculus I am not sure why test complaining about chart version, I rightly updated the chart version to `0.2.6`.

**Comment by timstoop** [comment]
It's not complaining about the Chart version: `Error: requirements.lock is out of sync with requirements.yaml` That seems to be the cause of the fail.

**Comment by shashiranjan84** [comment]
@timstoop sorry, I missed that error message, I dropped `requirements.lock`.

**Comment by shashiranjan84** [comment]
@timstoop waiting for your approval.

**Comment by shashiranjan84** [comment]
@unguiculus it needs your approval.

**Comment by unguiculus** [comment]
Why did you drop `requirements.yaml`? Instead of dropping it you should have regenerated it.

**Comment by shashiranjan84** [comment]
@unguiculus I dropped `requirements.lock` not `requirements.yaml`, is it a requirement to ship that file?

**Comment by shashiranjan84** [comment]
@unguiculus I have added back.

**Comment by shashiranjan84** [comment]
@mattfarina any specific reason for hold?

**Comment by unguiculus** [comment]
@shashiranjan84 The merge queue was stuck.

/hold cancel

**Pull request merged**
