### PR TITLE
[stable/mongodb] Fix #14187, adding quotes around annotation values while rendering StatefulSet PVC templates

### LINKED ISSUE #14187: [stable/mongodb] Chart does not render PVC annotations correctly. Strips quotes away from numbers.
Similar to https://github.com/helm/charts/issues/14139, this chart also renders PVC annotations without proper quotes. This causes problems with annotations containing numbers and other non-string values.

### PR DESCRIPTION
**Pull request by juliohm1978**
Proposed fix for https://github.com/helm/charts/issues/14187; a similar issue to https://github.com/helm/charts/issues/14139.

### CODE REVIEW

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by juliohm1978** [comment]
Branch rebased to sync with remote master.

/retest

**Review by tompizmor — APPROVED** [review]
/lgtm

**Pull request merged**
