### PR TITLE
Filebeat k8s fix

### PR DESCRIPTION
**Pull request by sstarcher**
Fixes - https://github.com/elastic/beats/pull/6353
And fixes logs from `/var/log`
Drops filebeat logs to prevent excess pressure from filebeat erroring when the output is backed up

### CODE REVIEW

**Comment by ghost** [comment]
Related: https://github.com/kubernetes/charts/pull/4372

**Comment by rifelpet** [comment]
@sstarcher between this and #4372 which PR do you think would make more sense to merge first and have the other rebase?

**Comment by sstarcher** [comment]
@rifelpet you took a different tact than I did.  I removed the prospector directory and moved it into the primary configuration.  

I think the main thing of importance is it useful to separate the prospector configuration or to just merge it into the primary configuration?

If we should keep the prospector we should merge yours first and I should redo mine.
If we should merge the prospector into the main config we should merge mine and redo yours.

Opinions?

**Comment by rifelpet** [comment]
@sstarcher I am by no means a Filebeat expert but I think consolidating the configurations into one kubernetes resource probably makes the most sense 👍

**Comment by sstarcher** [comment]
@rifelpet sounds good if that's the case sounds like we should get this one merged in first.

**Pull request merged**
