### PR TITLE
[stable/traefik] TLS key/value out of scope

### PR DESCRIPTION
**Pull request by amalucelli**
#### What this PR does / why we need it:

This PR will fix the key/value range of TLS parameters that are out of order over the template for the `kvprovider`: `etcd`, `consul`, `boltdb` and `zookeeper`.

When `kvprovider` is enabled and there are no `TLS` parameters configured, the `ConfigMap` generated for `traefik` is an invalid template:

```yaml 
apiVersion: v1
data:
  traefik.toml: "# traefik.toml\nlogLevel = \"INFO\"\ndefaultEntryPoints = [\"http\",\"https\"]\n[entryPoints]\n
    \ [entryPoints.http]\n  address = \":80\"\n  compress = true\n  [entryPoints.https]\n
    \ address = \":443\"\n  compress = true\n    [entryPoints.https.tls]\n      [[entryPoints.https.tls.certificates]]\n
    \     CertFile = \"/ssl/tls.crt\"\n      KeyFile = \"/ssl/tls.key\"\n[kubernetes]\n
    \ [kubernetes.ingressEndpoint]\n  publishedService = \"traefik/traefik\"\n[traefikLog]\n...
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gzamboni — APPROVED** [review]

**Comment by dtomcej** [comment]
Good catch!

**Pull request merged**
