### PR TITLE
[stable/envoy] Add prometheus-operator ServiceMonitor support

### PR DESCRIPTION
**Pull request by mumoshu**
Also bumps the chart minor version number because this results in a feature release

Signed-off-by: Yusuke Kuoka <ykuoka@gmail.com>

### CODE REVIEW

**Comment by mumoshu** [comment]
Great to know we can't self-approve PRs :)

**Comment by mumoshu** [comment]
@josdotso Hey! Would you mind reviewing/approving this?

**Comment by josdotso** [comment]
Cool stuff!

/lgtm

**Comment by josdotso** [comment]
@lachie83 Please approve this. It looks good to me.  ref: https://github.com/helm/charts/blob/master/stable/envoy/OWNERS

**Pull request merged**
