### PR TITLE
[stable/rabbitmq] Add priorityClassName

### PR DESCRIPTION
**Pull request by viktor42b**
#### What this PR does / why we need it:
This PR allows user to specify PriorityClass for rabbitmq pods

#### Checklist
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by javsalgar** [comment]
LGTM

**Comment by tompizmor** [comment]
Hi @victorboissiere!

The pull-charts-e2e automated test is failing because wrong chart version:

```
I0214 10:25:17.639] Error linting and installing charts
I0214 10:25:17.639] ------------------------------------------------------------------------------------------------------------------------
I0214 10:25:17.639]  ✖︎ stable/rabbitmq > Chart version not ok. Needs a version bump!
I0214 10:25:17.639] ------------------------------------------------------------------------------------------------------------------------
```

Can you check the version in master and increase it in the PR?

**Comment by victorboissiere** [comment]
Done!

**Comment by tompizmor** [comment]
@victorboissiere I still see the warning about conflicts in the `Chart.yaml` file. can you take a look?

**Comment by victorboissiere** [comment]
@tompizmor done! Merged

**Pull request merged**
