### PR TITLE
Update service.yaml

### PR DESCRIPTION
**Pull request by kti-rob**
**What this PR does / why we need it**: Fix a typo in service.yaml

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:  n/a

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rjkernick** [comment]
Thanks for the pull request. Please sign the CLA and increment the version in Chart.yaml.

**Review by rjkernick — CHANGES_REQUESTED** [review]
Please increment the version in chart.yaml

**Comment by davidkarlsen** [comment]
@kti-rob bump

**Comment by davidkarlsen** [comment]
@kti-rob Can you also bump the Chart.yaml version please?

**Comment by rjkernick** [comment]
Opened new request: #7198 
/close

**Pull request closed without merging**
