### PR TITLE
add exist volume and sub path to persistent volume option

### PR DESCRIPTION
**Pull request by tomqwu**
```release-note
NONE
```

### CODE REVIEW

**Comment by tomqwu** [comment]
Done signing the CLA

**Comment by lachie83** [comment]
cc @zanhsieh

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by zanhsieh** [comment]
good to go.

**Comment by sameersbn** [comment]
@tomqwu can you rebase the pr please?

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Pull request merged**
