### PR TITLE
[stable/traefik] Fix for helm 2.15 Ingress status check

### LINKED ISSUE #18206: [stable/traefik]  Helm 2.15 checks for ingress status, traefik publishedService not enabled default
**Describe the bug**
Helm as of version 2.15, when you use the `--wait` argument, will now wait for the Ingress object to be ready. src: https://github.com/helm/helm/releases/tag/v2.15.0

> Notable Changes
> ...
> `--wait` now waits for ingress hosts to become ready

Traefik previous to version 1.7 apparently didn't support updating the ingress status, resulting in an empty ingress status, thus, failing your helm upgrade if it contained an ingress object. Tiller just complains that the ingress is not ready (as this is now checked by helm: https://github.com/helm/helm/commit/1d95d8396bd57d26ce98a001526b495c0bb413a5#diff-d18c4d83690679deed0c84f55bf476bdR283)

In traefik 1.7, you should add the publishedService to your traefik configuration so it may be able to update the ingress object and effectively set it's status to ready, so helm doesn't fail. This should be enabled by default now to support the behaviour in helm 2.15

```
[kubernetes]
  [kubernetes.ingressEndpoint]
    publishedService = "traefik/traefik"
```
`traefik/traefik` in publishedService is `<namespace>/<traefik service name>`

This would be in your configMap in kubernetes or values.yaml file:

```
kubernetes:
  ingressEndpoint:
    publishedService: "traefik/traefik"
```

**Version of Helm and Kubernetes**:
Helm 2.15
Kubernetes 1.14.x

**Which chart**:
stable/traefik

**What happened**:
Upgrades started failing since helm 2.15. Install should probably fail as well. Unless publishedService is enabled.

**What you expected to happen**:
publishedService should be enabled default. Logic should be in place to support this.

**How to reproduce it** (as minimally and precisely as possible):
Use helm 2.15, values.yaml should not have publishedService set (as it would appear as a default setting)

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Exodus**
#### What this PR does / why we need it:
Addresses Issue #18206 
#### Which issue this PR fixes
  - fixes #18206 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

cc: @krancour @emilevauge @dtomcej @ldez

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Exodus 
Please sign DCO for commits you made. See: https://github.com/helm/charts/pull/18209/checks?check_run_id=270600428

**Comment by dtomcej** [comment]
I am not sure this is the right move for a few reasons:

1. This change is not a required change for helm 2.15 compatibility
2. The issue that was raised in this issue is due to a non-required feature addition in helm (the --wait flag)
3. By making this mandatory, it means that user objects will be modified without choice, and changes default chart behavior, and is not backwards compatible

I feel that this is not the correct way to go about this.

If you want to use helm with --wait, you should ensure the ingressStatus is set, otherwise, no changes are required.

I think that this should be a documentation update, not a code update.

**Comment by Exodus** [comment]
I understand @dtomcej, though today it's `helm --wait` complaining about the unsatisfied status in the Ingress object, tomorrow it could be any other service/application that does the same check. The fact that Traefik isn't completing the status of the ingress object on it's creation is the underlying issue that `helm --wait` is just uncovering. That issue nonetheless needs to be addressed somehow.

At the least, this is better than nothing at the moment :-) if there's another route, I'd appreciate a comment into what that would be and when it could happen.

Regarding backwards compatibility, I'm not following, can you elaborate? I tested from the standpoint of someone that does not have this enabled. Upon upgrading to this chart, it would be enabled and all ingresses would return the proper status.

**Comment by dtomcej** [comment]
> The fact that Traefik isn't completing the status of the ingress object on it's creation is the underlying issue that helm --wait is just uncovering

Is this an _issue_ or an _observance_?

The `--wait` flag is not a default. It does not apply unless a user chooses to enable it. If a user enables that flag without understanding how it applies is not an issue with the chart, it is an issue with the user.

This is why I recommended that this be a documentation/Readme update, to inform users that if they use the `--wait` flag, that they should set those values accordingly.

The Traefik team is very careful about not modifying user's objects without their permission. To update the status on an ingress, we have to modify objects that we did not create. This can cause issues if there are other tools and systems also managing objects.

>Regarding backwards compatibility, I'm not following, can you elaborate?

If a user has used this chart for the last 25 versions, and has not wanted Traefik to touch the ingress status, this change will:

1. Require changes to the values.yaml file
2. Change the default behavior of the chart
3. Potentially cause ingress issues or conflicts for systems that do not want the status populated

This is because the changes in this PR do not affect users that enable `--wait`, they affect _all_ users of the chart.

Being that this chart is used by a huge number of people, we have to be cogent about changing default behavior.

**Comment by dtomcej** [comment]
Just a follow up comment to my previous:

I am not trying to be contrarian or argumentative. I really do appreciate the situation that this helm fiasco has put us in.

However, we have to be aware that there are large groups of production users that use this chart, and stability and predictability are important.

If we implement features, it should be because we _want_ them, not just because they make other tools work the way they should.

😄

**Comment by timja** [comment]
> > The fact that Traefik isn't completing the status of the ingress object on it's creation is the underlying issue that helm --wait is just uncovering
> 
> Is this an _issue_ or an _observance_?
> 
> The `--wait` flag is not a default. It does not apply unless a user chooses to enable it. If a user enables that flag without understanding how it applies is not an issue with the chart, it is an issue with the user.

It is very non obvious in helm that this is the issue though, I would not expect to have to change the traefik chart for this to work out of the box.

Don't the other ingress controllers update this by default?

**Pull request closed without merging**
