### PR TITLE
[stable/sonatype-nexus] create proxy service only if nexus-proxy is enabled

### PR DESCRIPTION
**Pull request by diwakar-s-maurya**
#### What this PR does / why we need it:
sonatype-nexus helm chart bundles an authentication proxy service along the standard nexus repository manager installation. It is possible to disable authentication proxy installation using `--set nexusProxy.enabled={true|false}`.  If it is set to false then all resources required for authentication proxy are not installed except one kubernetes service resource. This PR makes the creation of that service also dependent on whether the authentication proxy is enabled or not.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] ~~Variables are documented in the README.md~~

### CODE REVIEW

**Comment by diwakar-s-maurya** [comment]
@rjkernick

**Comment by rjkernick** [comment]
Please merge latest master and resolve merge conflicts

**Comment by diwakar-s-maurya** [comment]
@rjkernick Done

**Pull request merged**
