### PR TITLE
[stable/consul] WIP: Allow configurable fullnameOverride

### PR DESCRIPTION
**Pull request by siwyd**
As per current recommendations, add fullnameOverride options to the helpers file.

### CODE REVIEW

**Comment by siwyd** [comment]
@unguiculus I think my tests are failing because of the default anti affinity settings. The chart wants more nodes to spin up the Consul cluster. Any suggestions?

**Comment by unguiculus** [comment]
Would you like to create a separate PR to fix affinity? I don't like the way it is set now. I'd rather go with what `helm create` with Helm 2.8+ gives you. This is what's commonly used now.

**Comment by siwyd** [comment]
@unguiculus Alright, I'll have a look!

**Comment by siwyd** [comment]
@unguiculus New PR for affinity settings: https://github.com/kubernetes/charts/pull/5532. I'll set a new Chart version and rebase if when that PR gets approved.

**Pull request closed without merging**
