### PR TITLE
[stable/jenkins] Changes to import job XML and Groovy init scripts as external files, instead of having to type them inside the YAML values

### PR DESCRIPTION
**Pull request by michelzanini**
**What this PR does / why we need it**:
Changes to import job XML as external files, instead of having to type them inside the YAML values.
Job files are normally big, and having then outside the YAML file looks better.
I also updated to have Groovy init scripts as external files as well, to keep consistency.

**Special notes for your reviewer**:

This is a PR to open a discussion, maybe you wish to keep the way it is now.
Maybe we can provide the two options, either inline or external files.
Let me know what you think and I can either improve the PR or close it.

### CODE REVIEW

**Comment by Nodraak** [comment]
I think you should also rework `InitScripts` the same way. Do you think you could do it ?

(Also, please update the Chart version)

/assign @viglesiasce

**Comment by michelzanini** [comment]
Hi @Nodraak ,
Yes I can update InitScripts as well.
Will do this soon, Thanks.

**Comment by michelzanini** [comment]
Regarding the version, I am thinking this feature breaks the values.yml, so maybe I will update to 0.17 instead of 0.16.x?

**Comment by Nodraak** [comment]
Yes, you should update to 0.17

**Comment by michelzanini** [comment]
Hi @Nodraak ,
I have updated InitScripts to also be external files as was suggested.

**Comment by viglesiasce** [comment]
Hey @michelzanini!!!

This would be a breaking change so would need to go into the v1.0.0 of the Jenkins chart. I've started a branch over here:
https://github.com/viglesiasce/charts/tree/jenkins-v1.0.0

Would love to have this contribution there so we can include it when the v1.0.0 chart is ready.

**Comment by Nodraak** [comment]
Hi @viglesiasce. When is this v1.0.0 branch expected to be merged ? More like 2 weeks to 2 months?

**Comment by viglesiasce** [comment]
Hey @Nodraak my goal is in about a month or so.

**Pull request closed without merging**
