### PR TITLE
[stable/prometheus-operator]: Add specific condition for each alerts

### PR DESCRIPTION
**Pull request by mathieuherbert**
#### What this PR does / why we need it:
This PR add specific condition for each alerts.
We would like to be able to specified which alerts we want to integrate in  AlertManager

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by jmlrt — APPROVED** [review]
LGTM

**Review by victorsalaun — APPROVED** [review]
LGTM 👍

**Review by paskal — CHANGES_REQUESTED** [review]
Alerts are generated by scripts in hack folder and thus you need to change this script, and then regenerate alerts to see your change applied - otherwise changes there will be removed by next script run.

**Comment by mathieuherbert** [comment]
@paskal thanks ! 
I update the script but I could not tested it, I will do it on monday.

**Review by paskal — CHANGES_REQUESTED** [review]
I've checked, you did the good job with the conditions: no changes applied for them. Please run scripts from hack folder once, commit the changes (new rules will be delivered from coreos/prometheus-operator) and it will be good to go.

**Comment by mathieuherbert** [comment]
@paskal : thanks, I did some fixes on the condition and I run the script.

**Review by paskal — APPROVED** [review]
LGTM. @gianrubio, could you please review and approve that?
@mathieuherbert, it would be nice if you will sync grafana dashboards too (there are small changes from coreos there as well).

**Comment by mathieuherbert** [comment]
@paskal yes sure :) done in the last commit

**Comment by vsliouniaev** [comment]
Seems like folks are interested in this and it looks like a neat way to do it. 👍

**Comment by paskal** [comment]
@mathieuherbert please rebase by upstream/master and bump the version once more.

**Comment by mathieuherbert** [comment]
@paskal it's done. I put the version in 2.1.0

**Comment by paskal** [comment]
I'm just making sure things go smoothly, I can't approve anything to be merged - I have absolutely no rights in this repository. However now I see that things are done the right way and whoever will approve it unlikely will ask you to change anything.

**Comment by mathieuherbert** [comment]
thanks @paskal  !

**Comment by vsliouniaev** [comment]
@mathieuherbert
You should make the changes to `ci/test-values.yaml` as well. The only difference between that and values.yaml should be `prometheusOperator.cleanupCustomResource=true` in the ci version.

**Comment by mathieuherbert** [comment]
@vsliouniaev ok I added it :)

```diff ci/test-values.yaml values.yaml                                                                                                                                                   ✔  10783  14:58:04
557c557
<   cleanupCustomResource: true
---
>   cleanupCustomResource: false```

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Pull request merged**
