### PR TITLE
[stable/gcloud-endpoints] Deprecating Chart.

### PR DESCRIPTION
**Pull request by timstoop**
**What this PR does / why we need it**:

As discussed in #2149, this Chart is not working for a very long time now and nobody seems to be picking up the slack. Therefore, I think it's warranted to deprecate this chart. I followed the steps outlined in PROCESSES.md at the root of the charts repository.

### CODE REVIEW

**Comment by timstoop** [comment]
Of course, the CI fails...

**Comment by unguiculus** [comment]
Was trying to push it directly but couldn't since master is now protected.

**Pull request merged**
