### PR TITLE
Add an ingress template to the seq chart

### PR DESCRIPTION
**Pull request by msschl**
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by gertjvr** [comment]
@msschl can you bump the version number to 0.1.3 so the ci tests can run.

**Comment by msschl** [comment]
@gertjvr done

**Pull request merged**
