### PR TITLE
[stable/metallb]: Add support for nodeSelector/affinity/tolerations

### PR DESCRIPTION
**Pull request by kiall**
Adds support for nodeSelector/affinity/tolerations for both the speaker
and controller pods.

Additionally, a second commit includes some minor README fixes.

### CODE REVIEW

**Comment by kiall** [comment]
/assign @linki

bump :)

**Comment by kiall** [comment]
Pinging a few others from the OWNERS file - @unguiculus / @mattfarina - thanks :)

**Review by mattfarina — COMMENTED** [review]
Can you bump the chart version in the chart.yaml file and can you fix the merge issue?

**Pull request closed without merging**
