### PR TITLE
[stable/opa] Parameterize deployment strategy

### PR DESCRIPTION
**Pull request by yurrriq**
#### What this PR does / why we need it:
Template deployment strategy.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by timothyhinrichs** [comment]
This looks good.  Except it has the same version as the other 2 PRs.

**Comment by yurrriq** [comment]
I figured I'd rebase and bump as the others get merged. This way they're independent.

**Comment by yurrriq** [comment]
rebased

**Pull request merged**
