### PR TITLE
[stable/prometheus-operator] Remove duplicate namespace values

### PR DESCRIPTION
**Pull request by mercul3s**
There were additional namespace keys in some service templates, which
caused a duplicate namespace error.

#### Is this a new chart
No

#### What this PR does / why we need it:
Fixes an issue with duplicate namespace values in the prometheus-operator chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
The tests will keep failing until one of these can be done:
- https://github.com/helm/charts/pull/18271
- https://github.com/helm/charts/issues/18310

**Comment by vsliouniaev** [comment]
The changes look backwards to me - the resources should be in the kube-system namespace, rather than the release namespace

**Comment by mercul3s** [comment]
@vsliouniaev is the kube-system namespace a requirement, or just recommended? It looks like the release namepsace was added for all resources in PR #17689, which creates an additional namespace key/value. I'm using ship to generate a rendered.yaml artifact for deployment containing all resources, and it fails on the duplicate namespace. Removing the release namespace would also solve this issue, but since that's been updated in a previous PR, it might break things for other folks using these charts.

**Comment by vsliouniaev** [comment]
Yes, the kube-system namespace is required in the services and endpoints resources and the chart won't work if it is swapped out for the release namespace. The current behaviour I'm getting is that the kube-system namespace overrides the {{ .Release.Namespace }} since it comes after it and so it's still working.

**Comment by mercul3s** [comment]
@vsliouniaev ok, it makes sense to me why the services and endpoints need to be in kube-system. Regarding the second namespace overriding the first - that behavior might be something that just works in helm, but does not work for my use case, and appears to differ from yaml spec, which will ignore the second value: https://yaml.org/spec/1.1/#id932806
Since the namespace should always be kube-system, I've gone ahead and added that back and removed the release namespace reference.

**Comment by vsliouniaev** [comment]
Please update wrt the changes
/lgtm

**Comment by vsliouniaev** [comment]
/test all
Looks like this needs another version bump on account of another PR getting merged in

**Comment by mercul3s** [comment]
@vsliouniaev chart version bumped - anything else I need to do for this one?

**Pull request merged**
