### PR TITLE
[stable/redis-ha] Make namespaces of resources configurable.

### LINKED ISSUE #19263: [stable/redis-ha] Allow namespace of resources to be configurable
**Is your feature request related to a problem? Please describe.**
It is common to want the redis-ha to be deployed in a namespace other than the default. There is also a discussion about this being a best practice ([Look Here](https://github.com/helm/helm/issues/5465))

**Describe the solution you'd like**
All templates should allow you to configure the namespace using the --namespace flag

**Describe alternatives you've considered**
Other alternatives would include hardcoding the namespace in the templates which I believe should be avoided or setting as a value which is pretty much the same thing but slightly less flexibility.

Note: Issues copied from Issue #17936

### PR DESCRIPTION
**Pull request by atulagrwl**
Fixes #19263 

#### Is this a new chart
No

#### What this PR does / why we need it:
Adding namespace in chart in order for spinnaker to install it in desired namespace

#### Which issue this PR fixes
  - fixes #19263

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
@atulagrwl Another PR just merged, could you rebase and bump the version once more?

**Comment by atulagrwl** [comment]
@ssalaues - Done

**Pull request merged**
