### PR TITLE
[incubator/docker-registry] Add extra configuration options for docker-registry

### PR DESCRIPTION
**Pull request by rendhalver**
This is a redo of #2801 
#2612 was merged before this was completed.

I am mostly adding this so we can use it in the Portus chart I am submitting in #2766.
It will also allow people to configure their registry how they need it setup.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by rendhalver** [comment]
@unguiculus Should we use this PR to promote docker-registry to stable?

**Comment by unguiculus** [comment]
Please create a separate PR for the promotion.

**Comment by rendhalver** [comment]
Ok I will do that after this gets merged.

**Pull request merged**
