### PR TITLE
[stable/consul] Pass HttpPort to consul

### LINKED ISSUE #1614: HttpPort parameter doesn't works
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Using Kubernetes 1.6.6 and Helm 2.5.0

**Which chart**: Consul (https://github.com/kubernetes/charts/tree/master/stable/consul)

**What happened**: After assign the HttpPort parameter to 80, the Consul UI can't be reached (I'm using LoadBalancer as Service Type)

**What you expected to happen**: See the Consul UI (as it's shown when you use the default port 8500)

**How to reproduce it** (as minimally and precisely as possible): Just set the HttpPort to a value different from 8500. For example:

```
   helm install \
     --name consul \
     --namespace default \
     --set "uiService.enabled=true,uiService.type=LoadBalancer,HttpPort=80" \
     stable/consul
```

**Anything else we need to know**: By the way, the "ui.enabled" parameter described on the documentation it's not used at all on the Helm Chart, but that's a different issue.

I have received the help of @netflash to investigate this issue. He discovered that, when "uiService.enabled" is set to true, only the "-ui" argument is passed to the Consul server (https://github.com/kubernetes/charts/blob/master/stable/consul/templates/consul.yaml#L179). This is ok, but is not enough if "HttpPort" was also used to indicate a different port. According to https://www.consul.io/docs/agent/options.html, the "ports/http" setting should be changed also:
ports-http

Thank you very much in advance!

### PR DESCRIPTION
**Pull request by jonstacks**
Fixes #1614.

We were not passing the HTTP port through to consul. This fixes it so that consul serves is HTTP interface on the user supplied port.

### CODE REVIEW

**Comment by jonstacks** [comment]
@lachie83,

From what I can tell, only 2/3 pods in the stateful set were up when the tests ran. I'm wondering if maybe we shouldn't update the `helm install` command with a `--wait` flag? Do you think re-running the test might fix it?

Relevant lines from the test:

```
W0118 23:40:37.065] ++ kubectl get pods --namespace pr-3375-4762 -o 'jsonpath={.items[*].status.containerStatuses[?(@.ready!=true)].name}'
I0118 23:40:37.166] INFO: All pods entered the Running state
I0118 23:40:37.413] INFO: All containers are ready
W0118 23:40:37.513] + UNREADY_CONTAINERS=
W0118 23:40:37.514] + '[' -n '' ']'
W0118 23:40:37.514] + echo 'INFO: All containers are ready'
W0118 23:40:37.514] + exit 0
W0118 23:40:37.514] + kubectl get pods --namespace pr-3375-4762
I0118 23:40:37.722] NAME                   READY     STATUS    RESTARTS   AGE
I0118 23:40:37.723] consul-4762-consul-0   1/1       Running   0          28s
I0118 23:40:37.723] consul-4762-consul-1   0/1       Pending   0          0s
W0118 23:40:37.823] + kubectl get svc --namespace pr-3375-4762
I0118 23:40:38.011] NAME                    CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                            AGE
I0118 23:40:38.011] consul-4762-consul      None           <none>        8500/TCP,8400/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   29s
I0118 23:40:38.011] consul-4762-consul-ui   10.3.253.253   <nodes>       8500:32432/TCP                                                                     29s
W0118 23:40:38.112] + kubectl get deployments --namespace pr-3375-4762
W0118 23:40:38.304] No resources found.
W0118 23:40:38.307] + kubectl get endpoints --namespace pr-3375-4762
I0118 23:40:38.604] NAME                    ENDPOINTS                                                  AGE
I0118 23:40:38.604] consul-4762-consul      10.0.7.99:8600,10.0.7.99:8400,10.0.7.99:8302 + 6 more...   29s
I0118 23:40:38.604] consul-4762-consul-ui   10.0.7.99:8500                                             29s
W0118 23:40:38.705] + helm test consul-4762
```

**Comment by jonstacks** [comment]
Had to update part of the tests to get this to pass. Not sure if this is the best place to do it or if we should make modifications to the `/test/verify-release.sh` which checks for all pods being available.

**Comment by lachie83** [comment]
@jonstacks --wait has had issue between releases in the past. How about we make the helm test script handle the cluster coming up for some predetermined time -- https://github.com/kubernetes/charts/blob/master/stable/consul/templates/test-config.yaml

**Comment by jonstacks** [comment]
@lachie83, Sounds good. I'll Remove the wait and update the consul test.

**Comment by jonstacks** [comment]
@lachie83,

I think this should be good to go now.

**Comment by lachie83** [comment]
Thanks!

**Comment by jonstacks** [comment]
@lachie83, I'm thinking your /lgtm from earlier didn't register.

**Pull request merged**
