### PR TITLE
[stable/prometheus-mysql-exporter] updated gce-proxy to 1.14 & added myself to maintainers & owners

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* updated gce-proxy to 1.14 
* added myself to maintainers 
* added owners file

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes # 

#### Special notes for your reviewer:
https://github.com/helm/charts/issues/13869

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by tklovett** [comment]
Thanks for getting these changes in @monotek – I'm happy to be an OWNER too if that is useful

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

thanks a good luck!

**Pull request merged**
