### PR TITLE
bump version to v0.3.6

### PR DESCRIPTION
**Pull request by rohannayakwadi**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@rohannayakwadi 
Would you mind to sign DCO and bump the chart to latest version please? Thank you.

**Comment by zanhsieh** [comment]
@rohannayakwadi 
Would you mind to sign DCO and bump the chart to the latest version please? Thank you.

**Comment by jordie23** [comment]
Anything holding this PR back?

**Comment by olemarkus** [comment]
Seems like there is no attempts to fix the failing tests

**Comment by davidkarlsen** [comment]
@rohannayakwadi can you sign-off your commit please?

**Pull request closed without merging**
