### PR TITLE
[stable/kong] 0.35 update all standard labels

### PR DESCRIPTION
**Pull request by hbagdi**
#### What this PR does / why we need it:

Update all standard labels to match https://v2.helm.sh/docs/chart_best_practices/#standard-labels

#### Special notes for your reviewer:

Please review the last commit only. The others are part of #19854 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hbagdi** [comment]
@shashiranjan84 @rainest Please review this after #19854 is good to merge.
Also, please review the last commit only. Others are part of #19854.

**Review by rainest — APPROVED** [review]
Tested against an existing complex-ish non-controller release and neither Helm nor the resulting resources appeared to have any issues with the change (Helm 3 has gotten a lot stricter about spec violations and should catch most bad indents).

Spot check of indentation via the following looks sane:
```
$ helm template example -f example.yaml /tmp/charts-stable-kong-label-revamp/stable/kong | grep -A6 -B1 labels: | less 
$ helm template example -f example.yaml /tmp/charts-stable-kong-label-revamp/stable/kong | grep -A6 -B1 selector: | less
```

**Review by shashiranjan84 — APPROVED** [review]
/lgtm

**Comment by rifelpet** [comment]
I think this will cause problems because the Deployment's label selector field is immutable. 

At the very least, `app.kubernetes.io/version` needs to not be included in the deployment's `selector. matchLabels`, but it's also worth noting that chart users prior to this version will not be able to upgrade to this version in place, they'll need to `helm del --purge` and redeploy from scratch, which means downtime for the kong proxy.

**Comment by hbagdi** [comment]
@rifelpet 
Dropping the `app.kubernetes.io/version` makes sense to me as well.
Could you send out a PR to note the upgrade in place and the above change in the changelog?

**Comment by rifelpet** [comment]
@hbagdi done: https://github.com/helm/charts/pull/19916

**Pull request merged**
