### PR TITLE
Consul release name check

### PR DESCRIPTION
**Pull request by timm088**
What this PR does / why we need it:

When releasing these charts, service name will be prefixed with the release name, resulting in name-name. This also impacts DNS resolutions.

Special notes for your reviewer:

From my research, looks like the default chart template was changed (i.e., when running helm create locally), this function was just not added here

### CODE REVIEW

**Comment by timm088** [comment]
@mattfarina ok to move forward with testing?

**Review by unguiculus — CHANGES_REQUESTED** [review]
Thanks for this. You also added the `chart` partial, but didn't update resources. Care to do that as well?

**Comment by timm088** [comment]
Can do @unguiculus

**Comment by timm088** [comment]
@unguiculus to confirm, your request is for updating the resource (ingress etc,) to their latest versions?

**Comment by unguiculus** [comment]
No, you added the chart partial (https://github.com/kubernetes/charts/pull/5769/files#diff-a36b57d5b978075541e1493fbbcd535aR30), but don't use it in any resource. You should update `chart` labels.

**Comment by timm088** [comment]
Apologies, now I understand. Have added their usage @unguiculus , thanks.

**Review by unguiculus — APPROVED** [review]

**Comment by timm088** [comment]
I'll sort this out, looks like the changing of the name of the chart has broken the cluster join, should be an easy fix.

**Comment by timm088** [comment]
Ready to go with this one now @unguiculus , only the test was broken, not the actual cluster join

**Pull request merged**
