### PR TITLE
[/stable/kube-state-metrics] Add ImagePullSecret to serviceAccount

### PR DESCRIPTION
**Pull request by pmontanari**
Ability to specify ImagePullSecrets to serviceAccount

### CODE REVIEW

**Comment by pmontanari** [comment]
Hello, is there something wrong with this PR ?

**Review by fiunchinho — APPROVED** [review]
LGTM

**Comment by pmontanari** [comment]
Added a new fix to prometheus-node-exporter no setting promerly the serviceaccount with imagepullsecret

**Pull request closed without merging**
