### PR TITLE
[incubator/vault] Update readme for missed nodeSelector and tolerations

### PR DESCRIPTION
**Pull request by alantang888**
Signed-off-by: Alan Tang <alantang888@users.noreply.github.com>

#### Is this a new chart
Update readme for missed nodeSelector and tolerations

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@alantang888 
Could you bump chart version to the latest one please? Thank you.

**Comment by alantang888** [comment]
@zanhsieh Sure, I though already pumped 😉

**Pull request merged**
