### PR TITLE
[stable/mercure] Add pborreli as an approver

### PR DESCRIPTION
**Pull request by dunglas**
Signed-off-by: Kévin Dunglas <dunglas@gmail.com>

#### What this PR does / why we need it:

Adds @pborreli as maintainer for this chart.
See https://github.com/helm/charts/pull/13606#issuecomment-490406420

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
need a version bump here :)

**Comment by dunglas** [comment]
@maorfr done

**Comment by maorfr** [comment]
/lgtm

thanks and good luck!

**Pull request merged**
