### PR TITLE
[stable/concourse] bump to concourse 5.4.1

### PR DESCRIPTION
**Pull request by aegershman**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cirocosta** [comment]
Hey @aegershman , thanks for the PR!

It seems like you missed signing the commit 😁  

thanks!

**Comment by cirocosta** [comment]
(whops, wrong command)

**Comment by cirocosta** [comment]
For anyone in `5.4.0`, here's why you should upgrade:

Screen Shot 2019-08-07 at 7 26 08 PM

**Comment by aegershman** [comment]
👍 signature should be resolved, apologies about that. got lazy.

**Review by YoussB — APPROVED** [review]
Thanks @aegershman

**Pull request merged**
