### PR TITLE
[stable/concourse] Quote all environmental vars

### PR DESCRIPTION
**Pull request by arbourd**
#### What this PR does / why we need it:

There are a few variables for both the web and worker that will break
(bools, ints) if not quoted. This PR ensures all environmental variables are quoted.

#### Special notes for your reviewer:

There may be some values (multiline) that might be negatively affected by this.

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ahume** [comment]
Work around for this is to put .e.g `insecureSkipVerify: '"true"'` (note double quoted value).

**Comment by william-tran** [comment]
@arbourd I'm trying to understand the risk of 
> There may be some values (multiline) that might be negatively affected by this.

Can you provide any examples? How would a multiline string get mangled by passing it to `quote`?

**Comment by william-tran** [comment]
@xtremerui FYI I think `| quote` will need to be added to your values generator, if you're using such a thing

**Comment by xtremerui** [comment]
> @xtremerui FYI I think `| quote` will need to be added to your values generator, if you're using such a thing

We don't have such thing yet but will add it when we do.

**Comment by arbourd** [comment]
@william-tran there may not be. I was just thinking that this may not work:

```yaml
key: "valuevaluevaluevaluevaluevaluevaluevalue
valuevaluevaluevaluevaluevaluevaluevalue
valuevaluevaluevaluevaluevaluevaluevalue
valuevaluevaluevaluevaluevaluevaluevalue"
```

**Pull request merged**
