### PR TITLE
[stable/kube2iam]: add rbac support

### PR DESCRIPTION
**Pull request by SamClinckspoor**
Adds support in kube2iam for RBAC.

setting `rbac.enabled` to true will create a role, rolebinding and service account.

### CODE REVIEW

**Comment by SamClinckspoor** [comment]
Can I get a review on this?

**Comment by icereval** [comment]
Reviewed discussion from @c-knowles' merged `traefik` PR and this looks good, thanks!

LGTM

**Comment by cknowles** [comment]
If you'd like to account for users switching RBAC enabled from `true` to `false` then currently you'll need to explicitly set `serviceAccountName` to `default`. The reason is that there's a deprecated `serviceAccount ` attribute in k8s 1.6 so if you only unset `serviceAccountName` it will be restored from the deprecated attribute.

You can see the fault by installing a chart that does not do this and then trying to turn RBAC off, you will notice the deployment still has the RBAC service account and not the default service account:
```
helm install stable/etcd-operator --name tester --wait --set rbac.install=true
helm upgrade tester stable/etcd-operator --install --wait --set rbac.install=false
```

**Comment by cknowles** [comment]
I think it's definitely an edge case though so the rest of this PR looks great.

**Comment by SamClinckspoor** [comment]
@c-knowles you mean I should set the following?
```yaml
{{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "fullname" . }}
{{- else }}
      serviceAccountName: default
{{- end }}
```

**Comment by cknowles** [comment]
@SamClinckspoor yes exactly that. As above it's an edge case but may be worth including. It will go away whenever k8s gets rid of the deprecated attribute.

**Comment by icereval** [comment]
@c-knowles, thanks for pointing out the SA default.

**Comment by icereval** [comment]
LGTM, cc @lachie83 @viglesiasce @prydonius

**Pull request merged**
