### PR TITLE
[stable/gocd] Bump k8s plugin to latest

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#### What this PR does / why we need it:

Bumps k8s EA plugin to the latest version.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
@GaneshSPatil - please don't merge this until https://github.com/gocd/docker-registry-artifact-plugin/pull/27#issuecomment-465390567 is resolved this week. I think we can bump both the EA and the artifact plugin as part of the same helm charts release.

**Comment by arvindsv** [comment]
@varshavaradarajan wants to check something. Will approve after.

**Pull request merged**
