### PR TITLE
[stable/traefik] quote boltdb prefix

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:

otherwise the toml file would be invalid.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by SantoDE** [comment]
Hey @carlossg,

thanks a lot. We have another PR open which will bump the minor version: #14585 

Maybe its a good idea to wait for that, so the fix is in the then new 1.70.X version of the chart?

**Comment by caarlos0** [comment]
> Maybe its a good idea to wait for that, so the fix is in the then new 1.70.X version of the chart?

hey, your call.. either way is fine by me :)

**Comment by caarlos0** [comment]
not sure why tests fail... the test case does not even uses boltdb..

**Pull request merged**
