### PR TITLE
[stable/prometheus] Prometheus server globals parameterization

### PR DESCRIPTION
**Pull request by marksto**
Externalize global timing-related parameters to allow their easier modification, i.e. without the need to pass the whole configuration file. See #1550 for details. P.S. Sorry for being stupid for the first two unsuccessful attempts — this is my first personal contribution to the open-source project — being confused by an issue with invalid "user.email" which (for whatever reason) differs for GUI and command line tools, even if I set it up manually from the second one.

### CODE REVIEW

**Comment by marksto** [comment]
Yay! It passed the Foundation check. =)

**Comment by mattfarina** [comment]
/ok-to-test

@marksto Thanks for the PR and welcome to contributing to charts.

**Comment by marksto** [comment]
@mattfarina Ok, what's next? Am I supposed to bump the chart version myself?

**Comment by mattfarina** [comment]
@marksto Can you rebase this from master to account for the changes?

**Pull request closed without merging**
