### PR TITLE
[stable/kubernetes-dashboard] add configurable replicaCount

### LINKED ISSUE #4282: [stable/kubernetes-dashboard] support multiple replicas
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

The chart has no configurable value for the amount of replicas to create for the dashboard deployment. For better availability, I'ld like to be able to scale the dashboard.

### PR DESCRIPTION
**Pull request by mxey**
**What this PR does / why we need it**:

Add a replicaCount value to the chart so one can run more than one dashboard instance for high availability 

closes #4282

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @kfox1111

**Comment by kfox1111** [comment]
I'm good with it if it works, but it is unclear to me how the dashboard works in this regard. It wasn't entirely clear to me that some of the recent changes (such as the authentication stuff) works properly with multiple instances? Do you need to specify a common hash key or something to get it to work? (Some systems require that kind of thing)

**Comment by mxey** [comment]
@kfox1111 I previously used multiple Dashboard replicas before I used the Helm chart and had no issues, but I don't know about any particular details.

**Comment by unguiculus** [comment]
I think we should find out first if this is supported before we merge it.

**Comment by mxey** [comment]
I asked on #sig-ui about this: https://kubernetes.slack.com/archives/C09R1JVU6/p1527774171000415
> Generated encryption key is used to encrypt the cookie that holds the "credentials" in your browser. It is then used by the backend to decrypt it and those credentials are used to create api client to talk with apiserver. It is done on every call. As the key is stored in the secret and synced with every replica, it is safe to scale Dashboard. It is still stateless.

**Comment by kfox1111** [comment]
Awesome. Thanks for tracking that down and the patch. :)

**Pull request merged**
