### PR TITLE
[stable/datadog] container-trace-agent - fix useSocketVolume

### PR DESCRIPTION
**Pull request by karolinepauls**
#### Checklist

- [ x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@karolinepauls please rebase your PR and fix the conflict, thanks!

**Comment by karolinepauls** [comment]
@cpanato It's rebased.

**Comment by karolinepauls** [comment]
I had to update the version number again.

**Comment by karolinepauls** [comment]
Bumped the version again.

**Comment by L3n41c** [comment]
Hello Karoline,
Unfortunately, another PR has been merged before yours.
Could you please fix the confilct in `Chart.yaml` and add an entry in `CHANGELOG.md` ?

**Comment by karolinepauls** [comment]
This is the worst git flow I've ever seen.

**Comment by karolinepauls** [comment]
Not really, it took so unreasonably long to merge a single-line fix, that someone more lucky got the same fix meanwhile.

Which means that someone had to spend time debugging the same problem (which would not exist if Helm didn't repeat the same mistake of rendering data with text templating, but did its research and got inspired by Lisp, but Go is about cobbling things together after all).

This is the single most hostile-to-contribution-for-no-reason repository I've ever tried contributing to.

What about just merging pull requests and fixing version numbers later? Even if the chart repository is a mirror of the master branch, make it a mirror if the "prod" branch and merge master to prod.

This is going to be less work than the busywork of saying "no" to people because someone was more lucky with their PR, and the other person got the shit end of the stick.

The current "flow" basically requires contributors to slave away checking every day or more often if their PR needs rebasing for the most trivial reason - the version in Chart.yaml.

**Pull request closed without merging**
