### PR TITLE
Add note to Spinnaker doc about destination path for additionalConfigMaps

### PR DESCRIPTION
**Pull request by milesmatthias**
#### What this PR does / why we need it:

A suggestion for improving docs. I spent a while trying to figure out where additional configMaps are uploaded to the halyard pod on a k8s spinnaker deployment so they could be used in config scripts, and this one line would've helped.

#### Special notes for your reviewer:

I realize Spinnaker is deployed on multiple kinds of infra, not just k8s, which is why I didn't mention a halyard pod, but maybe there's a better way to make this note generic.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by milesmatthias** [comment]
The linter is complaining because I didn't bump the chart version, but I don't think this change needs a version bump since it's just documentation.

**Comment by viglesiasce** [comment]
All changes require a version bump since the contents of the chart will
change.

**Comment by milesmatthias** [comment]
Bumped chart version.

**Pull request merged**
