### PR TITLE
[stable/sonarqube] Ingress path configuration for SonarQube

### LINKED ISSUE #13257: [stable/sonarqube] Support ingress path configuration
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Which chart**:
stable/sonarqube

The current ingress configuration supported by stable/sonarqube provides limited functionality because it does not support ingress path configuration.  Currently, the only way to configure ingress with SonarQube is at the root level (e.g., sonarqube.domain.com), where many use-cases may require an ingress path (e.g., domain.com/sonarqube).

I recommend that the ingress template be modified to allow for custom paths to be defined following the patterns used in other Helm charts such as WordPress, Jenkins, and ChartMuseum.

### PR DESCRIPTION
**Pull request by out-of-band**
#### What this PR does / why we need it:

This PR adds support for ingress paths in SonarQube

#### Which issue this PR fixes
  - fixes #13257 

#### Special notes for your reviewer:
I thought it might be useful to also automatically configure a few other properties in `values.yaml`, namely the `sonarWebContext` in the liveness/readiness probes and `extraEnv: sonar.web.context`, if an ingress path (other than the root /) is configured.  However, I didn't want to overcomplicate the PR or make superfluous changes without asking seeing as this PR was created to address an issue I created.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by out-of-band** [comment]
@davidkarlsen I had to resolve a merge conflict in `Chart.yaml` since the chart version has changed in the interim.

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
