### PR TITLE
[stable/sentry] Add support for external postgres DB (continued)

### PR DESCRIPTION
**Pull request by wgiddens**
**What this PR does / why we need it**:  Use external postgres db with sentry

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes PR #3376 

**Special notes for your reviewer**:  This is a continutation of PR #3376. Its been open since Januray and appears to be abandoned.

@unguiculus

### CODE REVIEW

**Comment by cpanato** [comment]
@wgiddens 
missing to sign the [DCO](https://github.com/helm/charts/pull/7449/checks?check_run_id=14900167) - https://www.helm.sh/blog/helm-dco/index.html

**Comment by wgiddens** [comment]
@cpanato DCO is signed.

**Comment by wgiddens** [comment]
@cpanato I've merged in master. Can you take another look?

**Comment by wgiddens** [comment]
@scottrigby @foxish 
It seems as if I've gotten @k8s-ci-robot confused. When I've /assigned it to different owners it's not showing up on their PR dashboard. Right now it is stuck to foxish's dashboard so I'm leaving it alone. If someone would take a look I'd appreciate it.

**Comment by wgiddens** [comment]
@MattLaw0 It looks like the DCO check didn't like your email address.

**Comment by MattLaw0** [comment]
@wgiddens Ugh sorry this is turning into such a mess - if I rebase the last 2 commits to get back to the broken signature I then can't force push directly to your repo. And if we wanted to get my commit back as is with my commit history, you'd have to revert and I'd make the PR again etc which seems like a lot more faff.

I think actually what might be easiest is if you just want to rebase to at least before my commit (maybe to your first one in this branch (069d3dff7e086cae980287923b6f633c8f60d08e)), and then just use that as the single summarising commit for this PR. I don't mind if my little contribution gets lost as it was just a simple extension of what you'd already done.

**Comment by wgiddens** [comment]
/cc @scottrigby 
The PR dashboard doesn't seem to be working for this PR. Can you take a look?

**Comment by wgiddens** [comment]
@scottrigby @seanknox @unguiculus 
Can someone take a look?

**Comment by silvez-dh** [comment]
Hello, there an prevision when this chart will be merged? Or can i do something to help with it? Tks! :)

**Comment by cpanato** [comment]
@wgiddens can you please rebase then I can do the final review and get this merged

**Comment by wgiddens** [comment]
@cpanato It has been rebased. Please have a look.

**Review by cpanato — APPROVED** [review]

**Pull request merged**
