### PR TITLE
[stable/prometheus-operator] fix runbookUrl consistency

### LINKED ISSUE #20148: [stable/prometheus-operator] Inconsistent variable name in runbook_url config
**Describe the bug**
In pull request #19811 I applied an inconsistent naming convention (mix of camelCase and snake_case) to the runbook url variable.

**Which chart**:
stable/prometheus-operator

**What happened**:
Some runbook urls are truncated if defaultRules.runbookUrl is specified.

**How to reproduce it** (as minimally and precisely as possible):
Set `defaultRules.runbookUrl` to any value.

### PR DESCRIPTION
**Pull request by seanson**
#### What this PR does / why we need it:
Resolves an issue with variable consistency.

#### Which issue this PR fixes
  - fixes #20148

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@seanson Could you bump the chart version?

**Comment by seanson** [comment]
> @seanson Could you bump the chart version?

Bumped!

**Comment by bismarck** [comment]
@seanson I think you need to update your PR one more time?

**Pull request merged**
