### PR TITLE
[stable/traefik] Quote all values in ConfigMap under 'etcd.tls'

### LINKED ISSUE #8952: traefik chart fails in setup
BUG REPORT

**Version of Helm and Kubernetes**:
v2.11.0 and kubernetes 1.11.0

**Which chart**:
traefik

**What happened**:
trying to setup traefik with below yaml - results in storeconfig-job failing with:
Error reading TOML config file /config/traefik.toml : Near line 26 (last key parsed 'etcd.tls.ca'): floats must start with a digit, not '.'

**What you expected to happen**:
that it created a working traefik or atleast told me my yaml was invalid :)

in readme for traefik chart it says for RootCA f.ex.: NOTE: You can use file path or cert content directly
it says nothing in kvprovider etcd - so perhaps it does not accept file paths? (and if not - how do I add the certs to the yaml ?) base64 encoded string of file?

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/traefik --name traefik-public --namespace kube-system --values traefik-publicsites.yaml

**traefik-publicsites.yaml**:
```
## Default values for Traefik
serviceType: LoadBalancer
whiteListSourceRange: []
externalTrafficPolicy: Cluster
replicas: 1
cpuRequest: 100m
memoryRequest: 20Mi
cpuLimit: 100m
memoryLimit: 30Mi
debug:
  enabled: false
kubernetes:
  labelSelector: 'realm=public'
ssl:
  enabled: true
kvprovider:
  storeAcme: true
  importAcme: false
  etcd:
    endpoint: traefik-etcd-wtzrrwbb6s.traefik-etcd.default.svc.k8cb.example.org:2379
    useAPIV3: true
    watch: true
    prefix: traefik
    tls: 
      ca: ./etcd-client-ca.crt
      cert: ./etcd-client.crt
      key: ./etcd-client.key
acme:
  enabled: true
  email: myemail@example.org
  onHostRule: true
  logging: false
  challengeType: tls-alpn-01
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: false
  domain: traefik.k8cb.example.org
  service: {}
  ingress: {}
  auth: 
     basic:
       traefik: Traef1k
  statistics: {}
gzip:
  enabled: true
traefikLogFormat: json
accessLogs:
  enabled: false
metrics:
  prometheus:
    enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
    dashboardEnabled: true
```

### PR DESCRIPTION
**Pull request by gaui**
#### What this PR does / why we need it:

Quote all `[etcd.tls]` values in ConfigMap template

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #8952

#### Special notes for your reviewer:

@krancour 
@emilevauge
@dtomcej 
@ldez

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by dtomcej** [comment]
@gaui Needs DCO signoff :)

**Comment by dtomcej** [comment]
And needs a chart version bump :)

**Comment by gaui** [comment]
> And needs a chart version bump :)

@dtomcej  Rebased against upstream + chart version bump :)

**Pull request merged**
