### PR TITLE
[stable/coredns] allow user selection of label names

### PR DESCRIPTION
**Pull request by mmiller1**
#### What this PR does / why we need it:
This allows a user of the chart to change the label names being used to work around upgrade incompatibility issues that can come with altering label selectors.

#### Special notes for your reviewer:
There is no change to the generated templates in this PR. the default values are set to what was previously hard coded.
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mrueg** [comment]
Thanks for your contribution. Unfortunately I think this is not an ideal solution. 
The labels are pretty well standardized in https://helm.sh/docs/chart_best_practices/#standard-labels
If we need additional labels, we could define an "additionallabels" key.

**Comment by mmiller1** [comment]
The problem that I'm trying to address is that when the chart's labels changed, existing coredns deployments can't be upgraded without resource recreation (labelSelectors is immutable on deployments). So a CoreDNS deployment using the labels provided prior to https://github.com/helm/charts/pull/13310 can no longer be upgraded without incurring downtime, as critical as cluster DNS is, this doesn't seem reasonable in for a production environment.

**Comment by mrueg** [comment]
I understand the issue. Unfortunately, the taken approach manifests, that folks with old deployments of the chart will keep carrying on their old labels forever while adding more complexity to the chart. Let's wait for the other chart maintainers on this and let me consult the charts slack channel to see if there's another approach we could take.

**Comment by mrueg** [comment]
Would this approach solve your issue as well? https://github.com/helm/charts/pull/17966
You could define your old labels as custom labels and this would allow you to upgrade with no downtime, while the old labels become meaningless in the future and are still kept.

**Comment by mmiller1** [comment]
@mrueg yes, this will work nicely, and I agree it is much cleaner. Thanks.

**Comment by mrueg** [comment]
Great! Do you mind closing this PR and we'll proceed with https://github.com/helm/charts/pull/17966 ?

**Pull request closed without merging**
