### PR TITLE
Add loadbalancer IP to kibana

### PR DESCRIPTION
**Pull request by todoesverso**
**What this PR does / why we need it**:
Kibana expose service type and service annotations to be modified. In that case _loadBalancerIP_ should be able to be configured.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
In my particular case I needed it because I had:
```yaml
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @compleatang

**Comment by compleatang** [comment]
@todoesverso Can you add the `service.loadBalancerIP` value to table of values in the README.md? Other than that LGTM @unguiculus

**Comment by todoesverso** [comment]
@compleatang done

**Pull request merged**
