### PR TITLE
[stable/chartmuseum] support 'hostPath' persistent storage

### PR DESCRIPTION
**Pull request by enrique-fernandez-polo**
support 'hostPath' persistent storage

Signed-off-by: Enrique Fernández-Polo Puertas <kike.fdez.polo@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Quaiks** [comment]
Hello!! Am I missing something in the PR?

Regards!

**Comment by zanhsieh** [comment]
@Quaiks 
Could you bump the chart version to latest please? Thank you.

@jdolitsky
@goruha
@olemarkus
@yurrriq
Would you mind to take a look this PR?

**Comment by olemarkus** [comment]
Thanks for this PR.

I had a look at other charts with hostPath and there are very few of them that allow this without being charts for log exporters and similar. So I am not sure if it is a good idea to allow this in the first place.

Secondly, I think the readme need to be very clear about how to set hostPath. See for example the drupal or redis-ha chart.

**Review by yurrriq — APPROVED** [review]
Thanks!

**Pull request closed without merging**
