### PR TITLE
[incubator/rundeck] add support for init containers and custom volumes

### PR DESCRIPTION
**Pull request by georgekaz**
#### What this PR does / why we need it:
Add support for initContainers, custom volumes and volume mounts, in my case to install rundeck plugins, but I'm sure there are other uses.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dwardu89** [comment]
@georgekaz can you fix the conflicts please?

**Comment by georgekaz** [comment]
@dwardu89 I've sorted the conflicts

**Comment by georgekaz** [comment]
hi @dwardu89 @davidkarlsen This had a lgtm label but didn't automatically merge. Then a conflicts arose so I've resolved those again, could you re-review please, it's been waiting a while and I've already fixed merge conflicts twice. Thanks

**Comment by georgekaz** [comment]
thanks

**Pull request merged**
