### PR TITLE
[stable/nginx-ingress] Adding clusterIP condition for remaining services

### PR DESCRIPTION
**Pull request by harshal-shah**
Signed-off-by: Harshal Shah <harshal2623@gmail.com>

#### What this PR does / why we need it:
This PR adds conditions to the clusterIP value in the service spec for additional services of this chart. An initial fix was done in #7933 but only for the main service.

#### Which issue this PR fixes
  - fixes #7933

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by harshal-shah** [comment]
@robermorales @ivanmp91 @mtparet @unguiculus @cpanato

**Comment by harshal-shah** [comment]
no it does not break existing releases

**Comment by monotek** [comment]
@harshal-shah 
> no it does not break existing releases

Yes it does.

` Error: UPGRADE FAILED: Service "nginx-ingress-controller-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Service "nginx-ingress-controller-stats" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Service "nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

**Comment by mtparet** [comment]
Perhaps, we could add a new key like `useClusterIP: true/false` if we want to move forward without breaking things.

**Pull request merged**
