### PR TITLE
[stable/redis] add 'namespace: {{ .Release.Namespace }}' to stable/redis

### PR DESCRIPTION
**Pull request by laverya**
#### What this PR does / why we need it:

```
helm template --name myname --namespace mynamespace stable/redis > apply.yaml
kubectl apply -f apply.yaml
```
`apply.yaml` will not contain `namespace: mynamespace`, and so the resources will be created within `default`.

#### Special notes for your reviewer:

If this has been requested and rejected before, I'm sorry for duplicating that request!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by juan131** [comment]
Hi @laverya 

Thanks for your PR!

Did you try to add the "namespace" in the `kubectl apply` command?

```
$ helm template --name myname stable/redis > apply.yaml
$ kubectl apply -f apply.yaml --namespace mynamespace
```

I don't see any advantage on adding the namespace field in the templates since it can be easily overwritten.

**Comment by laverya** [comment]
@juan131, while `kubectl apply -f apply.yaml --namespace mycustomnamespace` would work in some situations, it doesn't work with flux or other gitops-oriented workflows. There's a lot of situations where someone won't be able to run arbitrary `kubectl` commands to deploy to a cluster,  and at least in my opinion it makes sense to support them.

**Comment by mruoss** [comment]
I would like to see this merged too. See more discussions about the issue on helm/helm#3553

**Comment by juan131** [comment]
Hi @laverya @mruoss 

I find this very controversial even though I understand its limitations in some Gitops environments. 

With Helm 3 being just around the corner (which removes Tiller) this kind of `helm template | kubectl apply` workarounds disappear. I don't think we should support this, which is just a way to support a way to install charts in a different way they were thought to be installed.

**Pull request closed without merging**
