### PR TITLE
Allowing override for all fluentd config files

### PR DESCRIPTION
**Pull request by brosander**
**What this PR does / why we need it**: There were hardcoded config files that we needed to override :)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
/ok-to-test
ping @monotek, as maintainer of the Chart.

The change makes sense to me, kind of wondering why nobody ran into this before!

**Comment by monotek** [comment]
We can do this change but there are some points i'd like to address:

* If we put the whole config into the values.yaml naming the chart fluentd-elasticsearch makes not a lot of sense anymore as it would be completely generic. We could even think about to merge it with the fluentd-cloudwatch chart (https://github.com/kubernetes/charts/tree/master/incubator/fluentd-cloudwatch) and also the fluentd chart (https://github.com/kubernetes/charts/tree/master/incubator/fluentd)

* Also the custom config parts in the values file should be deleted then

* the elasticsearch host, port & buffer... values could be removed as one could just change the configmap

* If this will affect users on update we need to put it in the readme somehow

* i also had in mind to add an option to choose between daemon set & deployment as deployments make updates more easy but we can save this for later (if we merge with the fluentd chart to this would be more or less solved out of the box anyway)

**Comment by timstoop** [comment]
It still uses a different upstream image, right? As it requires the elasticsearch plugin.

That said, I still think having the default config available makes sense, as it also allows us to educate the user to more advanced options. For instance, we tend to generate the hash ids from fluentd as well, as this solves a thundering herd-like problem we had on a fairly loaded ES cluster. Would be worthwhile to add it here as well. For those kind of small changes, it's convenient to have the configmaps in values.yaml, so they're easy to modify.

**Comment by monotek** [comment]
The used image is this one: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch which is build from: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

So yes, for a merge of the charts we would likely need to create a new image which has all the needed plugins installed. So i guess lets forget about the merge :D

Nevertheless i'd like to see this stuff replaced when adding this pr:
* the custom config parts in the values file should be deleted then
* the elasticsearch host, port & buffer... values could be removed as one could just change the configmap

**Comment by brosander** [comment]
@monotek good points :) should I revise with those changes or would you like to see a bigger combination pr?

**Comment by monotek** [comment]
for me its ok if the last 2 points are resolved :-)

**Comment by brosander** [comment]
@monotek rebased on master and removed fluentdcustomconfig

I still think the elasticsearch params provide value.  (I'm not overriding that particular file but it's nice to just be able to set the host for example.)

Please advise :)

**Comment by monotek** [comment]
Ok, leave them in...

**Comment by brosander** [comment]
@unguiculus @timstoop thoughts?

**Comment by timstoop** [comment]
I follow the maintainer in this, trusting he knows best :)

**Comment by brosander** [comment]
@monotek any further action on my part?

**Comment by monotek** [comment]
@brosander 
no :-)

**Pull request merged**
