### PR TITLE
fluent-bit: Add 'fullConfigMap' option to allow entire config external

### PR DESCRIPTION
**Pull request by donbowman**
By default this template provies different 'files' for config
(fluent-bit.conf, custom_parsers.conf) under a common configMap. This
defeats changing the configmap (since it uses subPath).  If this variable
is set, the user is assumed to have provided, in 'existingConfigMap'
the entire config (etc/*) of fluent-bit, parsers and system config. In
this case, no subPath is used.  ConfigMaps using 'subPath' do not
[update automatically](https://github.com/kubernetes/kubernetes/issues/50345)

With this option, if the user sets 'fullConfigMap: true' it is
expected that the 'externalConfigMap' provided is a valid fluent-bit
config (with both fluent-bit.conf and parsers.conf).

Signed-off-by: Don Bowman <db@donbowman.ca>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by donbowman** [comment]
hello? what more is needed from me here?

**Comment by kfox1111** [comment]
lgtm

**Comment by naseemkullah** [comment]
Merged into #9008 @donbowman @kfox1111

**Comment by donbowman** [comment]
I believe https://github.com/helm/charts/pull/9008 incorporates this, closing.

**Pull request closed without merging**
