### PR TITLE
[stable/cluster-autoscaler] Fixing bug with extra args boolean convert

### LINKED ISSUE #9280: [stable/cluster-autoscaler] Extra argument valuess don't get added when the value is set to false, resulting in the flag being set to true
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
any

**Which chart**:
cluster-autoscaler

**What happened**:
When passing in flags as extraArgs with the value set to `false`, they are not added.

**What you expected to happen**:
If I do this in the value files:
```yaml
extraArgs:
  skip-nodes-with-local-storage: false
```
It results in this in the deployment manifest which is the opposite of what the desired state is:
```
--skip-nodes-with-local-storage
```
I expect:
It results in this in the deployment manifest:
```
--skip-nodes-with-local-storage=false
```

**How to reproduce it** (as minimally and precisely as possible):
start a deployment with 
```yaml
extraArgs:
  skip-nodes-with-local-storage: false
```

### PR DESCRIPTION
**Pull request by softstuff**
Fixing bug with extra args boolean convert.
Use less verbose default values.
Signed-off-by: Stefan Lundgren <ztefan.lundgren@gmail.com>

#### What this PR does / why we need it:
ExtraArgs can not handle values 'false' or '0' correct

#### Which issue this PR fixes
  - fixes #9280 (closed but PR never mearged)

#### Special notes for your reviewer:
Verify by running: 
```
helm install  --dry-run --debug \
    --set extraArgs.skip-nodes-with-local-storage=false \
    --set extraArgs.max-nodes-total=0 \
    --set autoDiscovery.clusterName=testing .
```
Output before PR:
...
kind: Deployment
...
           command:
            - ./cluster-autoscaler
            - --max-nodes-total
            - --skip-nodes-with-local-storage

Output after PR:
...
kind: Deployment
...
           command:
            - ./cluster-autoscaler
            - --max-nodes-total<b>=0</b>
            - --skip-nodes-with-local-storage<b>=false</b>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by rajakshay** [comment]
I am running chart version 0.11.1 and I believe that this PR can fix the issue that I am facing with extraArgs not taking the false value. Any estimate on when this could be merged?

**Comment by paulczar** [comment]
PR seems fine, but we need tests passing and conflicts merged.

**Pull request merged**
