### PR TITLE
[stable/redis] Updating redis img to 5.0.4

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### What this PR does / why we need it:
https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by carrodher** [comment]
Hi, thanks for the contribution, this chart is contributed by Bitnami and we have automated the release process using some bots, in this way we are checking upstream in order to detect new versions in the branch (in this case Redis 4.0). As you suggested, we can move Redis chart to the latest branch (Redis 5.0), but it is something we need to do in our internal logic; if I merge this PR, next time a new version appears in the branch 4.0 the changes will be overwritten.
For that reason, I will maintain this PR open and I will do the necessary changes in our side in order to release Redis 5.0 in the future.

**Comment by naseemkullah** [comment]
Thanks @carrodher

**Comment by carrodher** [comment]
Hi @naseemkullah, I just implemented the needed changes in our release pipeline in order to track and release Redis 5.0. 
Can you rebase the changes and increase the Chart version in a major? I mean, to `8.0.0`.

**Comment by naseemkullah** [comment]
Thanks @carrodher ... that's been done. Anything worth mentioning in the `Upgrading` section of `README`?

**Comment by carrodher** [comment]
Yes, it's a good point. We can add a line explaining the change from `7.X.X` to `8.X.X`, apart from the application version, we should add a note if there is something different or something that doesn't work upgrading the chart. Did you test upgrading from the current chart version to `8.0.0` via `helm upgrade`?

**Comment by carrodher** [comment]
ping @naseemkullah

**Comment by naseemkullah** [comment]
Sorry for dropping the ball on this. Will have a look at upgrading soon

**Comment by naseemkullah** [comment]
Hi @carrodher , I performed an upgrade from 4.0.14 to 5.0.4 and it went smoothly, no need for anything in `Upgrading` section finally. Please merge this! Thanks.

**Comment by carrodher** [comment]
Thanks, @naseemkullah! So we are ready to merge it, only one thing: can you revert this commit 48aba1a1309d3a22c8dfb6877d80c0281a45b59a? We are bumping the chart from `version: 7.1.1` to a new major version `version: 8.0.0`, it is not needed to bump it to `version: 8.1.0`

**Comment by naseemkullah** [comment]
Sorry, not sure why I put `8.1.0` ...fixed now!

**Pull request merged**
