### PR TITLE
[stable/home-assistant] add esphome option

### PR DESCRIPTION
**Pull request by hall**
#### Is this a new chart
No.

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR adds an ESPHome deployment to Home Assistant.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

I haven't tested these changes with any of the `configurator`, `vscode`, or `appdaemon` containers or all possible storage options.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

cc: @billimek @runningman84

### CODE REVIEW

**Comment by billimek** [comment]
Hi @hall,

I wonder if this should be an independent helm chart instead of adding it in with the home-assistant chart.  Does ESPHome require access to the home-assistant config files in order to run?

**Comment by hall** [comment]
That makes sense. I've always deployed ESPhome alongside HA but it's not a requirement. I'll create a separate chart and then open a PR to add it as a dependency to `stable/home-assistant`.

**Comment by carpenike** [comment]
@hall -- did you ever get to creating a helm chart for ESPHome?

**Comment by hall** [comment]
Hi @carpenike, I haven't gotten around to creating a dedicated chart. If you'd like to take a stab at it, the work is still available on the source branch of this PR.

**Comment by hall** [comment]
An `esphome` chart has been created here: https://github.com/billimek/billimek-charts/tree/master/charts/esphome

**Pull request closed without merging**
