### PR TITLE
[stable/influxdb]: Add the existing pvc and the release label back to the chart.

### LINKED ISSUE #18479: [stable/influxdb] Statefulset?
@Aisuko What are your thoughts converting to a statefulset? Or at least adding the option to use a statefulset instead of a deployment.

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

#### What this PR does / why we need it:

* Add back pre-existing volume.
* Add the label name `release`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #18479

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by naseemkullah** [comment]
bump

**Comment by scottrigby** [comment]
Will try to look more closely at this soon, but may not be able today. Quick notes for now: the pv dynamic provisioning logic changes - I remember that is something that was applied to a lot of charts (see the comments in values.yaml). Let’s please explain this change, and make sure it doesn’t cause another regression. Also does the data loss is the previous version mean it was an accidental breaking change (if upgrading from a previous version, requiring manual steps to preserve data)? If so we should note that in the readme and version bump accordingly.

**Comment by naseemkullah** [comment]
I don't think a major bump/upgrading note is needed, this is to fix a regression from the move to statefulset.

upgrading note definitely needed for move to 3.X.X which was bi of a disaster (aside from removal of pre existing PVC, statefulset  should have been an option (type: Deployment|StatefulSet) instead instead of complete shift, with a deprecation notice about deployment), but is already there https://github.com/helm/charts/tree/master/stable/influxdb#from--300-to--300

Backup and restore steps should be elaborated on though. not only for that breaking change but as general guidelines for users of this chart.

**Comment by Aisuko** [comment]
> I don't think a major bump/upgrading note is needed, this is to fix a regression from the infamous move to statefulset.
> 
> upgrading note definitely needed for move to 3.X.X which was bit of a disaster (aside from removal of pre existing PVC, statefulset should have been an option (type: Deployment|StatefulSet) instead instead of complete shift, with a deprecation notice about deployment), but is already there https://github.com/helm/charts/tree/master/stable/influxdb#from--300-to--300
> 
> Backup and restore steps should be elaborated on though. not only for that breaking change but as general guidelines for users of this chart.

Hello, sir.  I agree with you. Add `Deployment` as another choice would be good.  But, for this PR, I 'd like to fix the `release.label` and complete the storage policy for `Statefulset` first.  This PR status has been so long time to open.

**Comment by Aisuko** [comment]
To be honest, I do not know why the CI can not work very well, for this PR. Please help 
 to look at this log. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/helm_charts/19295/pull-charts-e2e/1209648306368548864/build-log.txt

**Comment by naseemkullah** [comment]
> > I don't think a major bump/upgrading note is needed, this is to fix a regression from the infamous move to statefulset.
> > upgrading note definitely needed for move to 3.X.X which was bit of a disaster (aside from removal of pre existing PVC, statefulset should have been an option (type: Deployment|StatefulSet) instead instead of complete shift, with a deprecation notice about deployment), but is already there https://github.com/helm/charts/tree/master/stable/influxdb#from--300-to--300
> > Backup and restore steps should be elaborated on though. not only for that breaking change but as general guidelines for users of this chart.
> 
> Hello, sir. I agree with you. Add `Deployment` as another choice would be good. But, for this PR, I 'd like to fix the `release.label` and complete the storage policy for `Statefulset` first. This PR status has been so long time to open.

But we are fixing a regression introduced in v3.X.X so I don't think a major bump is necessary. Elaboration on how to migrate from 2.X.X to 3.X.X should be added along with the regression fixes.

**Comment by Aisuko** [comment]
I know what you mean and I checked the PV logic. There is true that we add back the PV logic to the chart and did not cause a broken change, there just more than one option for how to use the PV.

**Pull request closed without merging**
