### PR TITLE
[stable/redis] Support defining PriorityClass

### PR DESCRIPTION
**Pull request by galiev**
Signed-off-by: Renat Galiev <renat@galiev.net>

#### What this PR does / why we need it:
Enables users to specify a priorityClassName for Redis pods

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by tompizmor — CHANGES_REQUESTED** [review]
Can you make the same changes you did in `values.yaml` file to `values-production.yaml`?
Other than that, the changes looks good to me

**Comment by galiev** [comment]
@tompizmor of course I will do it

**Comment by tompizmor** [comment]
@galiev Thanks! Let me know when it is done!

**Comment by galiev** [comment]
@tompizmor I made changes in file values-production.yaml and fix the conflicts in Chart.yaml and README.md

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by tompizmor** [comment]
Thanks for the contribution @galiev!!

**Pull request merged**
