### PR TITLE
Add GKE CloudSQL support for anchore-engine

### PR DESCRIPTION
**Pull request by pbalogh-sa**
#### What this PR does / why we need it:
Add GKE CloudSQL support for anchore-engine using gce-proxy.
If anchore-engine is deployed in GKE, with this change it will be able to use a CloudSQL instance as backend.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by zhill** [comment]
Looking at this. Will update with my review. The idea is reasonable, so if it works and fits in the broader chart/deploy flow then it should be ok.

**Comment by zhill** [comment]
Transferring the review to help expedite it as i've been very cycle constrained.

**Comment by Btodhunter** [comment]
@pbalogh-sa @zhill This looks good to me and all worked great in testing! 

One thing I wanted to bring up for discussion was if we want to allow the utilization of a credential file secret for authenticating to CloudSQL. I imagine most people using CloudSQL are on Google Cloud and would utilize an attached service account for auth, however I'm sure there are cases where using a credentials file would be preferred.

Currently this PR does not include a way to utilize a credentials file secret. Is this functionality that should be included?

**Comment by zhill** [comment]
@Btodhunter , service account will be the the method used for GKE, anything else can be added later in another PR if someone else needs it, so I'm fine with a merge that only uses that way of providing creds.

**Pull request merged**
