### PR TITLE
[incubator/spark-cluster-operator] Add initial chart for spark-operator

### PR DESCRIPTION
**Pull request by jkremser**
**What this PR does / why we need it**:

Adds new chart for Apache Spark operator - https://github.com/Jiri-Kremser/spark-operator

**Special notes for your reviewer**:
:cookie:

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
@scottrigby @foxish Could you please look?

**Comment by foxish** [comment]
Is this the same as https://github.com/helm/charts/pull/6239?

**Comment by Jiri-Kremser** [comment]
@scottrigby @foxish Can we merge this PR?

**Comment by Jiri-Kremser** [comment]
:man_facepalming:

**Comment by Jiri-Kremser** [comment]
.

**Comment by Jiri-Kremser** [comment]
.

**Pull request closed without merging**
