### PR TITLE
[stable/prometheus] add support for running without cluster-admin privileges

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
#### Which issue this PR fixes
adds support for running on kubernetes setups (such as openshift) where you only have access to your own namespaces.

Signed-off-by: Klavs Klavsen <klavs@EnableIT.dk>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mrueg** [comment]
Thanks for your contribution. Can you split this up into one PR per chart please?

**Comment by KlavsKlavsen** [comment]
Updated to only be about prometheus chart - and added seperate PR for kube-state-metrics

**Comment by zanhsieh** [comment]
@KlavsKlavsen 
Could you sign DCO please as listed on the bottom of this PR please?

/assign

**Comment by KlavsKlavsen** [comment]
git commit -s -m "signing" - has been done

**Comment by zanhsieh** [comment]
@KlavsKlavsen 
Could you also fix what ci/circleci lint-charts reported errors and sign all commit you made please?
```
stable/prometheus/values.yaml
  549:5     error    trailing spaces  (trailing-spaces)
  554:5     error    trailing spaces  (trailing-spaces)
  558:4     error    missing starting space in comment  (comments)
  560:1     error    trailing spaces  (trailing-spaces)

Error linting charts: Error processing charts
```

**Comment by KlavsKlavsen** [comment]
For some reason when I click "details" on lint check - circleci will only let me see the details, if I grant it write access too ALL my repos (public and private).. WTF ?

**Comment by KlavsKlavsen** [comment]
dco signing fixed for all commits. I thought I fixed linting - but appearently not and cannot see the details as I explained above :(

**Comment by KlavsKlavsen** [comment]
I tried running ct lint locally but it fails with:
```
~/charts/stable/prometheus$ ct lint --config ~/charts/test/ct.yaml
Linting charts...
Using config file:  /home/klavs/charts/test/ct.yaml
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: k8s
TargetBranch: master
BuildId:
LintConf: /home/klavs/.ct/lintconf.yaml
ChartYamlSchema: /home/klavs/.ct/chart_schema.yaml
ValidateMaintainers: true
ValidateChartSchema: true
ValidateYaml: true
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: [incubator=https://kubernetes-charts-incubator.storage.googleapis.com/]
ChartDirs: [stable incubator]
ExcludedCharts: [common]
HelmExtraArgs: --timeout 600
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace:
ReleaseLabel:
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Error identifying charts to process: Error running process: exit status 128
Error linting charts: Error identifying charts to process: Error running process: exit status 128
```

**Comment by zanhsieh** [comment]
```
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 prometheus => (version: "11.6.2", path: "stable/prometheus")
------------------------------------------------------------------------------------------------------------------------

Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
"incubator" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading kube-state-metrics from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
Linting chart 'prometheus => (version: "11.6.2", path: "stable/prometheus")'
Checking chart 'prometheus => (version: "11.6.2", path: "stable/prometheus")' for a version bump...
Old chart version: 11.6.1
New chart version: 11.6.2
Chart version ok.
Validating /root/project/stable/prometheus/Chart.yaml...
Validation success! 👍
stable/prometheus/values.yaml
  549:5     error    trailing spaces  (trailing-spaces)

Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ prometheus => (version: "11.6.2", path: "stable/prometheus") > Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------

Exited with code exit status 1
CircleCI received exit code 1
```

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
