### PR TITLE
[stable/goldpinger] add repo archive notice

### PR DESCRIPTION
**Pull request by scottrigby**
See #24030

### CODE REVIEW

**Review by unguiculus — APPROVED** [review]
/lgtm

**Comment by okgolove** [comment]
@scottrigby could you add a link to my repo? Goldpinger helm chart now lives there https://github.com/okgolove/helm-charts/tree/master/stable/goldpinger

**Comment by cpanato** [comment]
@okgolove please open a PR for this chart to deprecate and add the documentation to the new repo in the readme. then assign Scott and myself, thanks!

**Pull request merged**
