### PR TITLE
[stable/kibana] Exit dashboard import script with error if import fails

### PR DESCRIPTION
**Pull request by branden**
No.

#### What this PR does / why we need it:

This causes the dashboard import to fail if a request to `/api/kibana/dashboards/import` returns an error status. Without this PR, if an import response status is e.g. 404 or 503 then the import will succeed, and falsely log that all dashboards were imported.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

N/A

#### Special notes for your reviewer:

In case the diffs for the curl lines are difficult to read, I'm adding `--fail` to get curl to exit nonzero when the HTTP response status is an error.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]

**Comment by branden** [comment]
CI is failing because the import script times out waiting for Kibana to come up and attempts the import before it's ready: 
```
I0916 18:11:49.541] Importing 1_create_index dashboard...
I0916 18:11:49.541] Valid JSON found in 1_create_index, importing...
I0916 18:11:49.542] * About to connect() to localhost port 5601 (#0)
I0916 18:11:49.542] *   Trying 127.0.0.1...
I0916 18:11:49.543] * Connected to localhost (127.0.0.1) port 5601 (#0)
I0916 18:11:49.543] > POST //api/kibana/dashboards/import?force=true HTTP/1.1
I0916 18:11:49.543] > User-Agent: curl/7.29.0
I0916 18:11:49.544] > Host: localhost:5601
I0916 18:11:49.544] > Accept: */*
I0916 18:11:49.544] > kbn-xsrf:true
I0916 18:11:49.545] > Content-type:application/json
I0916 18:11:49.545] > Content-Length: 381
I0916 18:11:49.546] > 
I0916 18:11:49.546] } [data not shown]
I0916 18:11:49.546] * upload completely sent off: 381 out of 381 bytes
I0916 18:11:49.547] * The requested URL returned error: 503 Service Unavailable
I0916 18:11:49.547] * Closing connection 0
I0916 18:11:49.547] 
I0916 18:11:49.548] Import of 1_create_index dashboard failed... Exiting...
```
I'll try bumping the timeout for this test to see if it helps. I suspect the default of 60 seconds may be too short.

**Comment by branden** [comment]
It finally occurred to me that the e2e test is deploying Kibana without Elasticsearch, which I think is why the Kibana API is serving 503s. If that's the case then the dashboard import initContainer won't ever succeed regardless of how high the timeout is. @monotek Do you have a suggestion for a path forward with this test?

**Comment by monotek** [comment]
We could add an disabled elasticsearch dependency and enable it in the ci.

**Pull request closed without merging**
