### PR TITLE
Introduce incubator jenkins

### PR DESCRIPTION
**Pull request by maorfr**
#### What this PR does / why we need it:
As chart maintainers, we have been working towards making the stable/jenkins chart follow chart best practices, while attempting to simplify it.
Over time, some breaking changes have been introduced to the chart. As this chart is in major version 0, the major version was not bumped, which is confusing as the chart is in the stable repository.
This has led to some discussions [[1](https://github.com/helm/charts/pull/11960)] around these changes, and we have decided to move active development to the incubator repository.

cc @viglesiasce @lachie83 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by torstenwalter** [comment]
@maorfr How is this intended to work? Is the goal to move active development to incubator for a limited timeframe (sax e.g. 2-3 months) make all necessary breaking changes there to comply with helm [best practices]( https://helm.sh/docs/chart_best_practices/) and then move it back to stable as 1.0.0?

How to ensure that changes made in `stable` in the meantime become part of `1.0.0`

**Comment by maorfr** [comment]
@torstenwalter, you got it exactly right.

and regarding your question, i have added these notes[[1](https://github.com/helm/charts/pull/12935/files#diff-59173791422882bfe5e70b7318025ffcR9)][[2](https://github.com/helm/charts/pull/12935/files#diff-ad134b2d1323fa2fab7c507137295984R9)] to the README of both charts.

**Pull request closed without merging**
