### PR TITLE
[stable/grafana] Corrected error in README.md dashboard/datasource examples

### PR DESCRIPTION
**Pull request by erlendr**
No

#### What this PR does / why we need it:

The README.md dashboard/datasource ConfigMap examples contains invalid label metadata syntax, as labels cannot have numeric values (`grafana_dashboard: 1`). See https://github.com/kubernetes/kubernetes/issues/57509

Corrected the examples to use string values for the `grafana_dashboard` label instead. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@erlendr 
Could you bump to the latest chart version and sign DCO please?

**Comment by erlendr** [comment]
@zanhsieh
DCO signed and chart version bumped (patch).

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@erlendr 
Build failed. Please check.

**Comment by erlendr** [comment]
@zanhsieh
The "pull-charts-e2e" job seems to have timed out: 
`I0928 10:10:32.066] error: timed out waiting for the condition on namespaces/grafana-presubmit-17388-1177886548067094528-k74n59e9yn`

I can't see how this is related to any of my changes?

**Pull request merged**
