### PR TITLE
[stable/nfs-client-provisioner] Fix compatibility issue with 1.16

### PR DESCRIPTION
**Pull request by msschl**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by verwilst** [comment]
Since the charts repository only supports the 2 latest versions of kubernetes, I'm not sure we should bother with conditionals for old versions. What do you think?

**Comment by msschl** [comment]
I have seen this approche in the chart stable/redis. They use this approche for networkpolicies.
```
{{- if semverCompare ">=1.4-0, <1.7-0" .Capabilities.KubeVersion.GitVersion -}}
```

**Comment by verwilst** [comment]
As seen in the repo's main readme:

"
Supported Kubernetes Versions

This chart repository supports the latest and previous minor versions of Kubernetes. For example, if the latest minor release of Kubernetes is 1.8 then 1.7 and 1.8 are supported. Charts may still work on previous versions of Kubernertes even though they are outside the target supported window.
"

Unless there are major objections, i would like to see the chart as clean and simple as possible..

**Comment by verwilst** [comment]
But it's only a small thing so i'll go ahead and merge this.

/lgtm
/approve

**Comment by msschl** [comment]
Ok I will clean this up and create a new pull request without an compatibility switch. :-)

**Comment by verwilst** [comment]
Well, it's ok, no worries. :-) Maybe it will make some pre-1.11-using people happy.

**Pull request merged**
