### PR TITLE
[stable/kuberhealthy] fix security context indenting and errant space.  Removed bad fsGroup…

### LINKED ISSUE #180: Error during helm install
Trying to install kuberhealthy using helm. Cluster is running k8s 1.14

Getting the following error,

helm install stable/kuberhealthy
> Error: validation failed: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "imagePullPolicy" in io.k8s.api.core.v1.SecurityContext]

### PR DESCRIPTION
**Pull request by integrii**
Fixes https://github.com/Comcast/kuberhealthy/issues/180 and fixes a typo.

### CODE REVIEW

**Comment by integrii** [comment]
force push was to satisfy DCO signing.

**Comment by saokar** [comment]
can someone merge this PR? thanks!

**Comment by integrii** [comment]
@davidkarlsen can you `/ok-to-test` us pretty please?

**Comment by saokar** [comment]
any updates please ?

**Comment by saokar** [comment]
Can someone merge this please?

**Comment by integrii** [comment]
@lolimjake and @ihoegen can probably /lgtm this...

**Comment by bcg62** [comment]
this is blocking use of the chart. please merge.

**Comment by integrii** [comment]
```
I0702 18:50:03.416] Installing chart 'kuberhealthy => (version: "1.2.6", path: "stable/kuberhealthy")'...
I0702 18:50:04.522] Error: release kuberhealthy-6eh3a9qzle failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.SecurityContext: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|Context":"allowPrivi|..., bigger context ...|"cpu":"100m","memory":"80Mi"}},"securityContext":"allowPrivilegeEscalation:false runAsNonRoot:true r|...
```

Looks like the error above is blocking builds... Taking a look.

**Review by ihoegen — APPROVED** [review]

**Pull request merged**
