### PR TITLE
[stable/jenkins]: add cache section under persistence to define volumes

### PR DESCRIPTION
**Pull request by krishnakvall**
#### What this PR does / why we need it:

Allows the chart to defined a set of volumes that can be mounted by agents for caching libraries and other build artifacts.
Volumes of type `PVC` are created by the chart and a corresponding `CronJob` is created to clear the cache on a periodic basis.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

Additional paramters added under persistence.cache section
Values and README files have been updated with the details of how to use these values and snippets.

| Parameter                                 | Description                     | Default         |
| ----------------------------------------- | ------------------------------- | --------------- |
| `persistence.cache.volumes`               | List of volumes, created if PVCs| `[]`            |
| `persistence.cache.clearJob.cronSchedule` | Cron string for schedule        | `0 0 * * SUN`   |
| `persistence.cache.clearJob.image`        | Image to run cache clear job    | `alpine`        |
| `persistence.cache.clearJob.tag`          | Image ta to run cache clear job | `3.7`           |

Persistence Cache Values

Its possible to define a set of volumes that will be mounted by agent pods for caching 
libraries and other artifacts for build. Each volume of type `PVC` in this list will be created
by the chart along with a `CronJob` to clear the cache (delete all files) on a periodic basis.

A volume is defined in the format below:

```
  volumes:
  - type: PVC
    claimName: "{{ .Release.Name }}-maven-cache"
    size: "4Gi"
    storageClassName:
```

These volumes can be mounted in agents under `additionalAgents` and `podTemplates` sections as
per the code snippets below:

```  
  podTemplates: 
    maven: |
      - name: maven
...
        volumes:
          - persistentVolumeClaim: 
              claimName: "{{ .Release.Name }}-maven-cache"
              mountPath: /home/jenkins/agent/.m2/repository
              readOnly: false
```

```
additionalAgents: {}
  maven:
    podName: maven
...
    volumes:
    - type: PVC
      claimName: "{{ .Release.Name }}-maven-cache"
      mountPath: /home/jenkins/agent/.m2/repository
      readOnly: false
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by wmcdona89** [comment]
@krishnakvall thanks for the PR. this is really neat!

it seems like some or all of the new values could be at the top-level. here are a couple options.

@torstenwalter let us know what you think

**option 1**: 
- add `persistence.cache` to configure the cache PVCs and consider `persistence` to be the home for all of the chart's PVC configuration.
- add top-level `clearCache` to mirror top-level `backup` which is also a CronJob. it wouldn't necessarily need all the same fields initially.
```
persistence:
  # can create a single PVC to share across all agents or build-tool specific PVCs
  cache: {}
    # maven:
    #   enabled: true
    #   claimName: "{{ .Release.Name }}-maven-cache"
    #   size: "4Gi"
    #   storageClass:
    #   accessMode: "ReadWriteMany"
    #   annotations: {}
```
```
clearCache:
  enabled: false
  componentName: "clear-cache"
  schedule: "0 0 * * SUN"
  labels: {}
  annotations: {}
  image:
    repository: "alpine"
    tag: "latest"
  extraArgs: []
  existingSecret: {}
  env: []
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
```
**option 2**: 
- add top-level `cache` to configure the cache PVCs as well as the `clear` CronJob which mirrors `backup` in terms of the configurable values.
- `persistence` is not modified and is considered to be for the Jenkins Master PVC only
```
cache:
  # can create a single PVC to share across all agents or build-tool specific PVCs
  pvcs: {}
    # maven:
    #   enabled: true
    #   claimName: "{{ .Release.Name }}-maven-cache"
    #   size: "4Gi"
    #   storageClass:
    #   accessMode: "ReadWriteMany"
    #   annotations: {}
  clear:
    enabled: false
    componentName: "clear-cache"
    schedule: "0 0 * * SUN"
    labels: {}
    annotations: {}
    image:
        repository: "alpine"
        tag: "latest"
    extraArgs: []
    existingSecret: {}
    env: []
    resources:
        requests:
        memory: 1Gi
        cpu: 1
        limits:
        memory: 1Gi
        cpu: 1
```

**Comment by torstenwalter** [comment]
@wmcdona89 For me both options look fine. I am just wondering if we should rename it from `cache` to `cacheVolumes` as we are just creating volumes and the user needs to actively make use of them within buildpods otherwise nothing is cache.

@krishnakvall Do you use it in your setup? Can you confirm that everything works?

I think that we need at least a warning that volume type needs to be ReadWriteMany as otherwise only a single agent can use the volume could use the cache at any given time.

I can imagine issues with cache cleanup: If that runs while a build job is using it you might get strange results. e.g. Maven populating the cache and we are removing files before they are used...

**Comment by krishnakvall** [comment]
@torstenwalter I can confirm we are using this pattern and it works. Of course, the actual speedup depends on the type of build, the time spent in build step v/s others etc.

@wmcdona89 Happy with either option 1 or 2, I can rework accordingly. Let me know.

And yes, will make sure that the naming and the README makes it clear that this just creates the volumes, we would need additional code to mount and use in the agents.

**Comment by torstenwalter** [comment]
@wmcdona89 Do you prefer option 1 or 2 from your suggestions? I tend to option 2, having a top-level cache and keep persistence for master only.

**Comment by wmcdona89** [comment]
@krishnakvall @torstenwalter 
I'm leaning towards a 3rd option which adds the cache to agent configuration thus allowing all values to be inherited or overridden to be agent specific.
```
agent:
  # create cache. override in `additionalAgents` for an agent-specific cache.
  cache:
    enabled: true
    componentName: "{{ .Release.Name }}-cache"
    size: "4Gi"
    # storageClass:
    accessMode: "ReadWriteMany"
    # enable CronJob to periodically clear the cache
    clear:
      enabled: true
      componentName: "{{ .Release.Name }}-clear-cache"
      schedule: "0 0 * * SUN"
      image: "maorfr/kube-tasks"
      tag: "0.2.0"
      command: "kube-tasks execute --command 'rm -rf'"
   # mount cache to agent pod
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-cache"
        mountPath: /home/jenkins/agent
additionalAgents:
  maven:
    cache:
      componentName: "{{ .Release.Name }}-maven-cache"
      clear:
        componentName: "{{ .Release.Name }}-clear-maven-cache"
        schedule: "0 2 * * WED"
        image: "maven"
        tag: "3.6.3-openjdk-11"
        command: "mvn dependency:purge-local-repository -DsnapshotOnly=true"
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-maven-cache"
        mountPath: /home/jenkins/agent/.m2/repository
```

**Comment by krishnakvall** [comment]
@wmcdona89 @torstenwalter the third option localizes the caches with the agents, so would be better to understand and work with. A couple of questions/ assumptions below.

If all good, will rework to bring this in sync with option #3 above.

1. if there is a cache defined at the root level but an underlying agent does not require a cache, it can just be overridden by setting cache.enabled = false
2. Access mode would need to be enforced as ReadWriteMany. This is from earlier, I will also add the comments around the cache clear jobs
3. Do we add support for direct NFS mounts too?
4. This would move persistence definitions to multiple places within the chart, but bring it closer to the point(s) of use

**Comment by torstenwalter** [comment]
@krishnakvall sounds good. Having it close to where it's used makes sense for me.

What types of volumes you would support would be up to you. As long as it can be extended later it would also be fine to just start with PVCs.

**Comment by krishnakvall** [comment]
Hi @torstenwalter @wmcdona89 

Have moved the caches under agent. Had to take a couple of calls - happy to change if required after a review.
1. Have specified the mount path also under cache so that the cache PVC is created and mounted automatically on the agents instead of having this specified separately under "volumes"
2. Have added a de-duplication logic under the PVC and CronJob creation logic as there is a risk that there may be duplication otherwise (for example, if the same cache is mounted under multiple agents)
3. Do we want to add a cache section under one of the ci values files to be tested? 
4. The default values file has a sample cache but with "enabled = false", is this OK or could we comment it out similar to the "volumes" section? 
5. Have increased the minor version number. This is designed to be non-breaking but is a functionality change.

Thanks much.

**Comment by wmcdona89** [comment]
@krishnakvall your updates caused me to realize I should have provided clarification on sharing a `cache` among agents. for example, given `maven` and `maven-xlarge` agents which share a maven cache, one of the agents would create and mount the cache while the other agent would only mount the cache. I see now that it would be confusing for only one of the agents to have `cache.enabled=true` so perhaps we use a `cache.persistence.enabled` key instead so it's more obvious that only one of the agents should be creating the PVC. this approach avoids `cache` duplication and thus allows the `PersistentVolumeClaim` and `CronJob` templates to avoid de-duplication logic. what do you think?

```
additionalAgents:
  maven:
    cache:
      # create cache
      persistence:
        enabled: true
        componentName: "{{ .Release.Name }}-maven-cache"
        ...
      clear:
        ...
    # mount cache to agent pod
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-maven-cache"
        mountPath: /home/jenkins/agent/.m2/repository
  maven-xlarge:
    # mount cache to agent pod
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-maven-cache"
        mountPath: /home/jenkins/agent/.m2/repository
```

**Comment by wmcdona89** [comment]
Added `cache.clear.path` and a python agent example which uses NFS. 

```
additionalAgents:
  maven:
    cache:
      # create PVC
      persistence:
        enabled: true
        componentName: "{{ .Release.Name }}-maven-cache"
        ...
      # create CronJob (which mounts all agent volumes)
      clear:
        enabled: true
        componentName: "{{ .Release.Name }}-clear-maven-cache"
        path: /home/jenkins/agent/.m2/repository
        ...
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-maven-cache"
        mountPath: /home/jenkins/agent/.m2/repository
  maven-xlarge:
    volumes:
      - type: PVC
        claimName: "{{ .Release.Name }}-maven-cache"
        mountPath: /home/jenkins/agent/.m2/repository
  python:
    cache:
      # create CronJob (which mounts all agent volumes)
      clear:
        enabled: true
        componentName: "{{ .Release.Name }}-clear-pip-cache"
        path: /var/myapp/mynfs/pip
        ...
    volumes:
      - type: Nfs
        mountPath: /var/myapp/mynfs/pip
        readOnly: false
        serverAddress: "192.0.2.0"
        serverPath: /var/lib/containers
```

**Comment by torstenwalter** [comment]
@krishnakvall can you sign the last commits?

**Comment by krishnakvall** [comment]
Hi @torstenwalter @wmcdona89 

1. Pushed the PVC creation and CronJob as separate sections under "cache"
2. There is some redundancy in the tags (e.g. clear.mountPoint) but have kept it at minimum
3. Have modified values.yaml to have these values set with enabled = false. This is so that the "IF" conditions under the PVC and CronJob rendering are not checking each part of the tree, by default expecting tags like cache.persistence to be there.
4. There is a "Tip" cautioning users that one componentName should be defined only once

Note: had to rewrite latest history as I was facing signing and merge issues, Let me know if any issues, happy to open a new (clean) pull, if required.

Thanks,
Krishna

**Comment by torstenwalter** [comment]
/hold This chart will be moved to https://github.com/jenkinsci/helm-charts see for details #23562

@krishnakvall I know that you out a lot of work into that and it would be great to get this in. Could you create a PR in in the new location for it? Let me know if I can assist you.

**Comment by krishnakvall** [comment]
> /hold This chart will be moved to https://github.com/jenkinsci/helm-charts see for details #23562
> 
> @krishnakvall I know that you out a lot of work into that and it would be great to get this in. Could you create a PR in in the new location for it? Let me know if I can assist you.

Hi @torstenwalter , sure, will create a fresh PR against the new repo this week with some final tweaks. Thanks!

**Comment by scottrigby** [comment]
👍

**Pull request closed without merging**
