### PR TITLE
[stable/keel] Added missing Slack Approval Channel

### PR DESCRIPTION
**Pull request by RiceBowlJr**

### CODE REVIEW

**Comment by unguiculus** [comment]
@ricebowljr Since you added yourself as maintainer: You will be expected to keep contributing and to review future PRs and triage issues. Is this your intention?

@ArchiFleKs Are you ok with this?

**Comment by ArchiFleKs** [comment]
@unguiculus I'm okay with that

**Comment by RiceBowlJr** [comment]
@unguiculus yes I am willing to contribute for further PR and triage issues, that's why I added myself as maintainer, if you're all OK with that.

**Pull request merged**
