### PR TITLE
[stable/ipfs] Bump version of IPFS as it fix few majors bugs

### PR DESCRIPTION
**Pull request by bclermont**
https://github.com/ipfs/go-ipfs/releases/tag/v0.4.22

Signed-off-by: Bruno Clermont <bruno@robotinfra.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@bclermont 
Please sign DCO. Thank you.

**Comment by bclermont** [comment]
@zanhsieh 

[signed already](https://github.com/helm/charts/pull/16721/commits/15194f03b74cb319f496e034f16a925efabeb096)

**Comment by zanhsieh** [comment]
@bclermont @mattfarina @maorfr 
This chart will be hard to merge since no OWNERS (OWNERS file do not exist).

**Comment by bclermont** [comment]
> @bclermont @mattfarina @maorfr
> This chart will be hard to merge since no OWNERS (OWNERS file do not exist).

here you go #17635

**Comment by zanhsieh** [comment]
@bclermont 
Could you fix the conflicting file please?
stable/ipfs/Chart.yaml

BTW, you cannot LGTM yourself (sadly). You need another owner.
/verify-owner

**Comment by bclermont** [comment]
well, I deleted the fork where this is coming from, and as there is no other owner, I will ask someone else to redo this PR

**Pull request closed without merging**
