### PR TITLE
[stable/traefik] Use http endpoint /ping for liveness and readiness probes

### PR DESCRIPTION
**Pull request by minhdanh**
#### What this PR does / why we need it:

Traefik has a http endpoint for healthcheck `/ping` but it needs to be enable with `--ping` or `[ping]` in the config file.
Using this http endpoint for the readiness and liveness is more accurate then just use plain tcp port 80.
See:
- https://docs.traefik.io/configuration/ping/
- https://docs.traefik.io/basics/#command-healthcheck

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@minhdanh please sign the DCO

**Comment by minhdanh** [comment]
`pull-charts-e2e — Pod pending timeout. `
@cpanato What can I do with this?

**Comment by cpanato** [comment]
I will check the ci

**Comment by minhdanh** [comment]
@cpanato I tried `/assign @timoreimann` as suggested and the bot said `GitHub didn't allow me to assign the following users: timoreimann.`

What should I do?

**Review by SantoDE — APPROVED** [review]
/lgtm - Thanks :) 👼

**Comment by minhdanh** [comment]
@SantoDE Sorry, but maybe `/lgtm - Thanks :) 👼` didn't work. The `lgtm` label still missing.
😸

**Pull request merged**
