### PR TITLE
Add support for pre-created secrets and AWS STS session tokens

### PR DESCRIPTION
**Pull request by robbie-demuth**
#### What this PR does / why we need it:

Not all consumers want to provide AWS secrets such as `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` via values. For consumers, it may be preferable to create the Kubernetes secret containing the credentials out-of-band and pass the name of the secret to the chart instead.

The AWS Java SDK supports AWS STS session tokens via the `AWS_SESSION_TOKEN` environment variables. This PR also updates the chart to optionally retrieve session tokens from the pre-created Kubernetes secret described above. Since session tokens are short lived, it doesn't make sense to provide them via values to `helm install` or `helm upgrade`

This PR also removes the unused `aws.region` value. The region is instead meant to be specified as part of the `config` value

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by robbie-demuth** [comment]
Quick ping on this @viglesiasce @gianrubio

**Comment by robbie-demuth** [comment]
Any thoughts on this @viglesiasce @gianrubio?

**Comment by viglesiasce** [comment]
Will defer to @gianrubio as the maintainer of the chart.

/ok-to-test

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Pull request merged**
