### PR TITLE
[prometheus-node-exporter] Use latest API versions

### PR DESCRIPTION
**Pull request by velothump**
Needed for 1.16 support

Signed-off-by: Adam Graves <adam.graves85@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mnaser** [comment]
I'm not an owner, but this looks good and solves my issue.

**Comment by zanhsieh** [comment]
/assign @gianrubio
@gianrubio
Could you take a look at this PR please? Thank you.

**Comment by zanhsieh** [comment]
@lachie83 
Could you approve this please? Thank you.

**Pull request merged**
