### PR TITLE
[stable/prometheus-operator] bump prometheus-node-exporter version

### PR DESCRIPTION
**Pull request by sergeimonakhov**
Signed-off-by: Sergey Monakhov <monakhov@puzl.ee>

#### What this PR does / why we need it:
bump prometheus-node-exporter version

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by D1abloRUS** [comment]
@bismarck @gianrubio approve pls

**Comment by D1abloRUS** [comment]
@vsliouniaev approve pls

**Comment by vsliouniaev** [comment]
I believe this is no longer required

**Comment by D1abloRUS** [comment]
@vsliouniaev need bump prometheus-node-exporter in requirements.yaml

**Comment by vsliouniaev** [comment]
Could you please resolve the merge conflicts? I am not an admin on this repo - I can only merge PRs once the tests pass

**Comment by D1abloRUS** [comment]
@vsliouniaev why i get `Error: requirements.lock is out of sync with requirements.yaml` i recreate lock file using `helm dependency build`

**Comment by vsliouniaev** [comment]
Try delete the lock file and then you will know for sure

**Comment by D1abloRUS** [comment]
@vsliouniaev approve pls i fixed error on ci, using helm2 for generate lockfile

**Comment by D1abloRUS** [comment]
@unguiculus Again problem with running tests on the prometheus-operator chart

**Pull request merged**
