### PR TITLE
Add kube-iptables-tailer chart to incubator

### PR DESCRIPTION
**Pull request by mtparet**
Signed-off-by: --replace-all <matthieu.paret@lifen.fr>

#### What this PR does / why we need it:
Add an incubator chart for [kube-iptables-tailer](https://github.com/box/kube-iptables-tailer/) which will ease the usage of this tool.

#### Special notes for your reviewer:
I would like to get this into the official Helm repo. Thank you for the review in advance!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
hey @mtparet,

Have you considered self-hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by mtparet** [comment]
cc @dilyar85 if you wish to review or be added as approvers or reviewers, let me know.

**Comment by mtparet** [comment]
Hey @maorfr,

As it is our first chart and I already taken some time to work on this chart, if it possible, I wish to use this common repository to avoid setting up the hosting. Also It enables the original contributor to be part of this chart as it is under my enterprise organization.

But thanks for the proposition, indeed it could be nice to host it our-self, we will think about it in the future.

**Comment by maorfr** [comment]
thanks @mtparet.

looking at your OWNERS file, i see that you are the only one there. this means that if you want to add new changes, you are blocked by [us](https://github.com/helm/charts/blob/master/OWNERS#L1). in this case, it would make much more sense to self host.

if you wish to add your chart, that is totally fine, but i would request an additional approver. also note that review for new charts may take a long while, so this is another thing to consider.

thanks for contributing!

**Comment by mtparet** [comment]
I added an additional approver who accepted to handle this task (and already reviewed this work) :)

**Comment by mtparet** [comment]
@prydonius @maorfr I know you are busy on others tasks so if we can help the review by providing more input/information, let me know.

**Comment by dilyar85** [comment]
Hi @mtparet,

This is really awesome, and I would love to be added as an approver. Feel free to let me know if you need any help from my side. 

Thanks again for adding this kube-iptables-tailer chart!

**Comment by maorfr** [comment]
hey @mtparet 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Pull request closed without merging**
