### PR TITLE
Update GitLab-CE image to release 8.16.1

### PR DESCRIPTION
**Pull request by twk3**
Update from previous chart won't work because:
PersistentStorage was changed to default to WriteMany in order to support replicas

And postgres database version was updated to 9.6 in order to be a version
that matches an avaiable shipped binary in the GitLab image. (Enabling backup support, etc)

We can update to 8.16 without these other changes, but it seems like we should get the breaking changes/good defaults in sooner rather than later.

### CODE REVIEW

**Comment by markpundsack** [comment]
@twk3 This also switches to using `ReadWriteMany`, which iirc isn't supported by GKE. Will that make this chart unusable on GKE?

**Comment by twk3** [comment]
@markpundsack I was testing the chart on GKE and it seemed to work fine. Doesn't the GitLab demo use ReadWriteMany on GKE?

**Comment by markpundsack** [comment]
@twk3 Yeah, I just noticed that it does use ReadWriteMany and seems to work. I was just looking at https://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes which claims `GCEPersistentDisk` doesn't support ReadWriteMany.

Well, sorry for the false alarm.

**Comment by viglesiasce** [comment]
ReadWriteMany does not work on PD in GCE. The fact that the GitLab demo works is likely because they only use 1 replica.

**Comment by twk3** [comment]
Thanks @viglesiasce 

I will drop the replica and storage changes then

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Pull request merged**
