### PR TITLE
Fix the Nginx service name shown in NOTES.txt

### PR DESCRIPTION
**Pull request by eldada**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Review by paulczar — APPROVED** [review]
LGTM

**Comment by eldada** [comment]
Any reason why this is still waiting?

**Comment by eldada** [comment]
@mattfarina - I'm asking you since you were involved in previous PRs on Artifactory - any reason why this is not merged? I see @paulczar approved it. Thx!

**Comment by eldada** [comment]
I removed my fork eldada/charts, which is now showing this pull request: `... kubernetes:master from unknown repository`. I'll close this and create a new one. Sorry for the mess...

**Pull request closed without merging**
