### PR TITLE
[stable/elasticsearch-exporter] add repo archive notice

### PR DESCRIPTION
**Pull request by scottrigby**
See #24030

### CODE REVIEW

**Review by unguiculus — APPROVED** [review]
/lgtm

**Comment by desaintmartin** [comment]
/hold
This one has been moved to prometheus helm charts. Should we still merge this PR?

**Comment by desaintmartin** [comment]
See https://github.com/helm/charts/pull/24221 instead.

**Comment by cpanato** [comment]
thanks @desaintmartin 

/close in favor of #24221

**Pull request closed without merging**
