### PR TITLE
Grafana fix extraSecretMounts

### PR DESCRIPTION
**Pull request by j18e**
This completes the changes made by @anuraaga in #5630 

The previous PR already configures the secret as a volume and mounts into the initContainer, but it doesn't mount it into the main container. Example use case is mounting aws credentials into the container at runtime at /root/.aws

### CODE REVIEW

**Comment by anuraaga** [comment]
Thanks! Sorry for missing the fact that it was not the right container

**Comment by j18e** [comment]
@anuraaga who can approve the merge?

**Comment by anuraaga** [comment]
I'm not an OWNER but this comment has the command to get a review. I don't think it'll work if I enter it myself.

https://github.com/kubernetes/charts/pull/5964#issuecomment-395058768

**Pull request merged**
