### PR TITLE
[stable/memcached] Add maxItemSize config to memcached chart

### PR DESCRIPTION
**Pull request by etandel**
Signed-off-by: Elias Tandel Barrionovo <elias.tandel@gmail.com>

#### What this PR does / why we need it:

Later versions of memcached allow for the user to specify the maximum size of each cache entry when starting the server. This PR adds this option to the memcached chart so we can overload it if needed.

#### Special notes for your reviewer:

@gtaylor @olemarkus @kennethaasan 
memcached's default value for this config is 1mb, so that's what I put as the default to the variable.
BTW, this is my first contribution to helm/charts, so please let me know if I did anything wrong and how to improve the PR. Thanks!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by olemarkus** [comment]
Same as mentioned [here](https://github.com/helm/charts/pull/6760#issuecomment-412254948) I don't think adding an config value for every argument is the way to go, but rather have a generic extraArgs value for the container.

**Comment by etandel** [comment]
Do you mean removing all the cli args, their values, and adding instead a `commandArgs` variable? Or do you mean only removing the maxItemSize value and adding a new extraCommandArgs variable?

**Comment by olemarkus** [comment]
Just leave the existing ones and add `extraArgs` as parameter. This value is what most charts use for this purpose.

**Comment by codearm-docker** [comment]
I think having this optional value would be quite useful. Or at least an option to add custom args. Can this PR be reopened?

**Comment by olemarkus** [comment]
If you'll do a PR to add extraArgs, it can be merged fairly quickly

**Pull request closed without merging**
