### PR TITLE
[stable/locust] Adding nodeselector and tolerance options

### PR DESCRIPTION
**Pull request by sekka1**
Signed-off-by: garland <garlandk@gmail.com>

#### What this PR does / why we need it:

When running a Locust load test on a shared cluster, we almost always want to put the worker nodes on a separate node group so that it has full access to the nodes.

#### Which issue this PR fixes
none

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by sekka1** [comment]
@so0k @haugene Can you take a look at this PR?  THanks.

**Comment by sekka1** [comment]
@so0k @haugene ping =)

**Comment by haugene** [comment]
Hey @sekka1. Sorry about the delay. The changes looks good to me and it's a good addition as one would usually want to run locust on separate nodes as you say.
I wanted to test the changes as well, and haven't come around to that yet - hence the delay. But I should have some time over the next couple of days.

Could you also update the version in Chart.yaml again to resolve the conflict? Needs to be 1.0.1 after #13803

**Comment by sekka1** [comment]
@haugene Thanks for checking it out.  I have updated the chart's version.  Let me know if there is anything else.

**Comment by haugene** [comment]
Options are parsed correctly and everything looks good to me. I'm new in the maintainer procedure here on the repo and not sure exactly what my role is. I can't merge it, but I can at least approve. Let's see where it goes from there :)

/lgtm

**Comment by haugene** [comment]
Yeah, that was not it. Trying to assign it then, as the bot suggests.
/assign @cpanato

**Comment by sekka1** [comment]
@cpanato Can we approve this and merge?

**Pull request merged**
