### PR TITLE
HTTPS is required for unifi gui

### LINKED ISSUE #19611: [stable/unifi] Unifi GUI does not work with HTTP so is not reachable after installation
**Describe the bug**
The unifi GUI does not work with HTTP, only HTTPS. After deploying this chart with ingress enabled, accessing the service returns a response of
```
Bad Request
This combination of host and port requires TLS.
```

See https://community.ui.com/questions/Controller-how-to-deactivate-http-to-https/c5e247d8-b5b9-4c84-a3bb-28a90fd65668

**Version of Helm and Kubernetes**:
Helm 3.0.1
Kubernetes 1.16.1

**Which chart**:
stable/unifi

**What happened**:
GUI was not reachabe in browser

**What you expected to happen**:
GUI to be accessible in browser

**How to reproduce it** (as minimally and precisely as possible):
Enable ingress in `values.yaml` and install the chart

**Anything else we need to know**:
This is fixed by adding an annotation in `values.yaml` to force transport to https
```
ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

### PR DESCRIPTION
**Pull request by WTPascoe**
#### What this PR does / why we need it:
This PR adds an annotation to the ingress values to ensure that HTTPS is used as a backend transport. The Unifi gui does not work with HTTP, so this is required to function.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #19611 19611

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by billimek** [comment]
This change assumes that nginx is being used as the ingress controller?  That may be too opinionated for situations where someone chooses to use an ingress controller other than nginx.

Instead, perhaps we should add verbiage to the README indicating that whatever ingress controller is used should be configured to support a backend of https?

**Comment by WTPascoe** [comment]
> Instead, perhaps we should add verbiage to the README indicating that whatever ingress controller is used should be configured to support a backend of https?

That's fair. Pushed a change that implements that.

**Pull request merged**
