### PR TITLE
[stable/rabbitmq-ha] Fix the statefulset when persistent volume is disabled

### PR DESCRIPTION
**Pull request by francois-travais**
#### What this PR does / why we need it:
Right now the statefulset cannot work if the persistent volume is disabled for the following reasons:
- `priorityClassName`, if enabled, would be placed between the beginning of the volumes definitions and the data volume definition
- The data volume name property is not used when persistent volume is disabled 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by francois-travais** [comment]
@steven-sheehy Version bumped. You can assign it to someone now. I can bump the version again later if necessary.

**Comment by steven-sheehy** [comment]
Thanks @francois-travais, looks good to me
/assign @davidkarlsen

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
