### PR TITLE
[stable/rabbitmq-ha] fix typo: customConfigMap -> existingConfigMap

### PR DESCRIPTION
**Pull request by xornet-sl**
**What this PR does / why we need it**:
This PR fixes value existingConfigMap missdocumentation. There was a typo error

@etiennetremel

### CODE REVIEW

**Comment by xornet-sl** [comment]
cncf signed

**Review by etiennetremel — APPROVED** [review]
Good catch, thanks!

**Comment by steven-sheehy** [comment]
This PR and PR #6234 accomplish the same thing. Probably only one should be merged and I personally prefer this one since it has less unnecessary formatting changes that contribute to merge conflicts.

**Comment by mattfarina** [comment]
Closing this one as #6234 is being merged. Thanks you for catching the issue.

**Pull request closed without merging**
