### PR TITLE
fix the semver compare issue in nginx-ingress chart

### PR DESCRIPTION
**Pull request by chenzhiwei**
The version compare in **nginx-ingress** chart is using string compare, but when upgrading to Kubernetes v1.10.0, the string compare of `7` is greater than `10`, but it actually less than `10` in semver.

The issue is logged in: https://github.com/kubernetes/charts/issues/3002

### CODE REVIEW

**Comment by sameersbn** [comment]
Please bump the chart version in Chart.yaml

**Comment by chenzhiwei** [comment]
@sameersbn @mattfarina Do you know this error message?

```
[ERROR] templates/: render error in "nginx-ingress/templates/controller-service.yaml": template: nginx-ingress/templates/controller-service.yaml:28:12: executing "nginx-ingress/templates/controller-service.yaml" at <semverCompare ">= 1....>: error calling semverCompare: Invalid Semantic Version
```

I can use the semverCompare in my chart as following:

```
{{- if semverCompare ">= 1.10" .Capabilities.KubeVersion.GitVersion }}
  key: value
{{- end }}
```

**Comment by mattfarina** [comment]
Figured it out. See kubernetes/helm#3349. I've got a fix in mind that I'll try to get today. Doesn't look like we can use the GitVersion property in helm template or lint for the moment.

**Comment by mattfarina** [comment]
Note, helm 2.8 was just released with k8s 1.9 support and a fix for `GitVersion`. Once we switch to that release (more testing first) we can revisit this PR.

**Comment by mattfarina** [comment]
@sameersbn we've not upgraded to 2.8 here just yet. I'll circle back around to this one when we do.

**Comment by thomas-riccardi** [comment]
In GKE `GitVersion` has a suffix interpreted by semver as a pre-release, breaking such tests (in semver pre-releases are incompatible with ~normal releases). 
Example: ` v1.7.12-gke.1`.

I didn't find a way to remove the pre-release part off the `GitVersion` string , so the only other way I can see is to parse using `semver` then re-create a new dict without the `Prerelease` part, then `semverCompare` (not tested).

**Comment by ReSearchITEng** [comment]
Just migrated to k8s 1.10 and this si critical...
I am using latest helm 2.8.2

**Comment by ReSearchITEng** [comment]
I confirm the newly/fixed nginx-ingress 0.12.2 works fine.
Thanks!

**Comment by chenzhiwei** [comment]
I will test this on Monday. Thank you guys.

**Comment by thomas-riccardi** [comment]
What about GKE with `GitVersion:"v1.8.5-gke.0"` ?

**Comment by mattfarina** [comment]
@thomas-riccardi Thanks. I didn't know that GKE was using pre-releases as part of their naming. We'll need to chase that down.

**Comment by mattfarina** [comment]
I created #4629 to address this issue.

**Pull request merged**
