### PR TITLE
[stable/jenkins] add namespace flag for port-forwarding in jenkins notes

### PR DESCRIPTION
**Pull request by bksteiny**
Signed-off-by: Chris Stein <bksteiny@gmail.com>

#### What this PR does / why we need it:
Adds `--namespace {{ .Release.Namespace }}` to `kubectl port-forward` in NOTES.txt for Jenkins. This allows easy copy/paste after installing the chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by lachie83** [comment]
@bksteiny please go ahead and squash my commits because the GH UI doesn't add my email as an author and hence my commit signing doesn't match (apologies for the mess) Please squash my commits, bump the chart version and we can proceed with getting this merged. Thanks

**Comment by bksteiny** [comment]
@lachie83 - I think I got this taken care of. Let me know if not. Thanks!

**Pull request merged**
