### PR TITLE
Fix data.persistence.storageClass in example

### PR DESCRIPTION
**Pull request by patsevanton**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rendhalver** [comment]
Please increment the Chart version and sign off on your commits.

**Comment by patsevanton** [comment]
Place an
DCO signed
Chart Version bumped
?

**Comment by patsevanton** [comment]
If i Increment the Chart version, then have Conflicting files incubator/elasticsearch/Chart.yaml

**Comment by patsevanton** [comment]
Somebody helm please.
how to do pull request correctly?

**Comment by rendhalver** [comment]
Please rebase or redo this. elasticsearch has been promoted to stable.

**Comment by patsevanton** [comment]
Create new PR

**Pull request closed without merging**
