### PR TITLE
[stable/consul] Fix statefulset selector

### PR DESCRIPTION
**Pull request by coreypobrien**
Selectors need to be explicit and immutable so they can't contain the chart version. Currently attempting to upgrade between two versions will fail because the `chart` label on the `selector` cannot be changed from `chart: consul-1.x.x` to `consul-1.y.y`. 

```StatefulSet.apps "consul-consul" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.```

This removes the version from the `chart` label.

### CODE REVIEW

**Comment by unguiculus** [comment]
Actually, `chart` and `heritage` labels should not be part of the selectors at all.

**Comment by coreypobrien** [comment]
👍 In that case, maybe leave the version in the `chart` labels?

**Comment by coreypobrien** [comment]
@unguiculus Circling back on this today. 👍 with the reduced selectors?

**Comment by unguiculus** [comment]
I'll accept it like this. Maybe you'd like to open another PR to align labels with our standard.

**Pull request merged**
