### PR TITLE
update aerospike README.md to read yaml config from stable directory

### PR DESCRIPTION
**Pull request by mllu**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by mllu** [comment]
CLA signed

**Comment by foxish** [comment]
/hold

@mllu, please fix the lint failure in circle-ci
```
Checking the Chart version has increased for the chart at stable/aerospike
Error please increment the new chart version to be greater than the existing version of 0.1.5
```

**Comment by foxish** [comment]
@unguiculus - do we need to bump the chart version here for a readme update?

**Comment by mattfarina** [comment]
@foxish charts are immutable so every change needs to bump the version.

**Pull request merged**
