### PR TITLE
[stable/hazelcast] bump to hazelcast 3.12 and adds YAML configuration support

### PR DESCRIPTION
**Pull request by mesutcelik**
Signed-off-by: Mesut Celik <mesut@hazelcast.com>

#### What this PR does / why we need it:
- bump hazelcast version to 3.12
- add YAML support

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by mesutcelik** [comment]
cc: @davidkarlsen @leszko

**Comment by davidkarlsen** [comment]
@leszko Should this chart rather be deprecated and eventually removed *) - and the efforts put into https://github.com/hazelcast/charts/?

*) _Deprecating charts_ at https://github.com/helm/helm/blob/master/docs/charts.md

**Comment by leszko** [comment]
@davidkarlsen technically yes, but there is also the marketing side of this. Meaning that we're still in the official repo, so that a user could install hazelcast without needing to add hazelcast helm repo.

What are the plans for other similar cases, I checked e.g. redis, they're also in both their own repo and in the official one. Any comments on that?

**Comment by mesutcelik** [comment]
closing this one... will send another one...

**Pull request closed without merging**
