### PR TITLE
[stable/neo4j] Add Bolt protocol to the Service

### LINKED ISSUE #6737: Neo4j does not expose bolt port
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 2.9.0
Kubernetes 1.10  

**Which chart**:
stable/neo4j

**What happened**:
The service exposes only port 7474 (http). It is not really right way to connect to a neo4j cluster since http driver (at least for java) does not support routing, so writes quite often go to follower.

**What you expected to happen**:
Service defined in core-dns.yaml should export port 7678 as well to allow using bolt+routing:// protocol

### PR DESCRIPTION
**Pull request by RothAndrew**
#### What this PR does / why we need it:

This PR adds the ability to communicate with Neo4j over the Bolt protocol on port 7687. Transmission over Bolt is significantly faster than over HTTP. See [this blog post](https://neo4j.com/blog/neo4j-3-0-language-drivers/) for a deeper dive on Bolt vs HTTP.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #6737

#### Special notes for your reviewer:

The ports should really be configurable, but this is the first step, which matches the existing setup for the HTTP port 7474.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

☝️ maintainer: @mneedham

### CODE REVIEW

**Comment by RothAndrew** [comment]
bump. Any update on this?

**Comment by RothAndrew** [comment]
@cpanato @lachie83 @mneedham?

**Comment by cpanato** [comment]
@RothAndrew please update your pr with latest master

**Comment by JasonCarter80** [comment]
Was this not merged, this is quite needed.

**Pull request closed without merging**
