### PR TITLE
[stable/influxdb] Add delete-policy for set-auth

### PR DESCRIPTION
**Pull request by Ferenc-**
Withouth any hook delete policy,
the hook resource remains in the namespace
even after a 'helm delete --purge', and
consequent installations of the chart fail with:
Error: jobs.batch "[...]influxdb-set-auth" already exists

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Ferenc-** [comment]
Can somebody please advise what to do with this:
`ERROR: 'Jack Zampolin' is not a valid GitHub account.`
It appears that this name is listed as maintainer at least 6 times in this repo.

**Comment by unguiculus** [comment]
Please merge in the current master.

**Comment by Ferenc-** [comment]
I think I managed to complete the merge, please review.

**Pull request merged**
