### PR TITLE
Fix typo in mongodb-replicaset README.

### PR DESCRIPTION
**Pull request by bweston92**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by foxish** [comment]
I think this would also need a chart version bump

**Comment by bweston92** [comment]
@foxish really?

**Comment by foxish** [comment]
All changes need it IIRC. @unguiculus, can you confirm?

**Comment by steven-sheehy** [comment]
> @foxish really?

Yes, really: https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#immutability

**Pull request closed without merging**
