### PR TITLE
[stable/kured] Update kured to 1.4.0

### PR DESCRIPTION
**Pull request by ckotzbauer**
Signed-off-by: Christian Kotzbauer <christian.kotzbauer@gmail.com>

#### What this PR does / why we need it:
Update the kured-chart to the newest version 1.4.0
https://github.com/weaveworks/kured/releases/tag/1.4.0

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dholbach** [comment]
/ok-to-test

Do you know what hte `autolock.image` keys are for?

**Comment by code-chris** [comment]
@dholbach These are two cronjobs to apply the lock-annotation to prevent kured from running at any time. This was introduced with #17246.
But this could also be achieved with the `--start-time` and `--end-time` time cli-flags.

**Comment by dholbach** [comment]
Not sure how to feel about `autolock` generally.

In general this PR makes sense though. Did a quick test too.

/approve
/lgtm

**Comment by code-chris** [comment]
> Not sure how to feel about `autolock` generally.

I think we can remove this feature, when we move the chart, cause there's a built-in-solution for that use-case...

What do you think?

**Comment by dholbach** [comment]
I personally don't have a strong opinion - maybe let's discuss it in the [next kured meeting](https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit#).

**Comment by ckotzbauer** [comment]
@unguiculus @cpanato @paulczar Is there anything missing to get this merged?

**Pull request merged**
