### PR TITLE
[stable/kube2iam] adds Prometheus ServiceMonitor resource to kube2iam

### PR DESCRIPTION
**Pull request by willfrew**
#### What this PR does / why we need it:
Adds the ability to create a prometheus operator ServiceMonitor resource that configures prometheus to scrape kube2iam's [`/metrics` endpoint](https://github.com/jtblin/kube2iam#metrics).

#### Special notes for your reviewer:
Since kube2iam itself handles defaulting the `--metrics-port` parameter to the value of `--app-port`, I wasn't sure how best to handle the config of it. I didn't want to specify `8181` in the included `values.yaml` so I documented the parameter but left it commented out. Let me know if you'd prefer a different approach here.

CC @jmcarp / @icereval / @mgoodness 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by willfrew** [comment]
@paulczar @scottrigby @lachie83 bump? This is quite a small change to add some optional monitoring config that would be greatly helpful :D

Also please let me know if you guys were incorrectly assigned and this would be better with someone else?

**Comment by willfrew** [comment]
/unassign @paulczar 
/assign @davidkarlsen 

@davidkarlsen I spotted you reviewed some other `ServiceMonitor`-related PRs recently - hope you can help but apologies if you're not the right person. I'm a little confused as to how the auto-suggested assignee was generated.

**Comment by jeyglk** [comment]
bump

**Comment by willfrew** [comment]
/assign mgoodness
:pray:

**Pull request merged**
