### PR TITLE
A couple of typos in chart configuration examples

### PR DESCRIPTION
**Pull request by dylburger**
@gsemet @maver1ck 

#### What this PR does / why we need it:

There were a couple of typos in the Airflow chart configuration examples in the `README`, which caused me a bit of trouble until I hunted down the correct values in `values.yaml`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Review by gsemet — APPROVED** [review]
/lgtm

**Comment by gsemet** [comment]
You need to update the version

**Comment by dylburger** [comment]
@gsemet just to confirm, I need to update the version of the chart, correct?

**Comment by gsemet** [comment]
Yes

**Comment by dylburger** [comment]
Great thanks, first Helm commit :) . Let me know if it looks good now.

**Review by gsemet — APPROVED** [review]
/lgtm

**Comment by gsemet** [comment]
hello. Can you rebase this pull request ?

**Comment by zanhsieh** [comment]
@dylburger 
Would you mind to resolve conflicting files below please?
stable/airflow/Chart.yaml

**Comment by gsemet** [comment]
Hi. Can you rebase your PR?

**Comment by davidkarlsen** [comment]
This PR has been obsoleted as the changes have already been applied in another PR.

**Pull request closed without merging**
