### PR TITLE
[stable/prometheus] add path element to ingress definitions

### PR DESCRIPTION
**Pull request by hoesler**
This PR adds a feature to the prometheus chart which allows to define the path component in ingress definitions.

### CODE REVIEW

**Comment by yuvipanda** [comment]
What should the value of hosts param be after this PR?

I had:

```
    ingress:
        hosts:
          - prometheus.mybinder.org
```

which worked fine, but now fails with
```
Error: UPGRADE FAILED: render error in "mybinder/charts/prometheus/templates/server-ingress.yaml": template: mybinder/charts/prometheus/templates/server-ingress.yaml:23:21: executing "mybinder/charts/prometheus/templates/server-ingress.yaml" at <$url>: wrong type for value; expected []interface {}; got []string
```

**Comment by hoesler** [comment]
@yuvipanda  I cannot reproduce your error. If I run `helm install stable/prometheus --version 5.3.1 --debug --dry-run --set "server.ingress.enabled=true,server.ingress.hosts={prometheus.mybinder.org}"`, I get the following output, which looks good to me:

```
...
# Source: prometheus/templates/server-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.3.1
    component: "server"
    heritage: Tiller
    release: punk-sabertooth
  name: punk-sabertooth-prometheus-server
spec:
  rules:
    - host: prometheus.mybinder.org
      http:
        paths:
          - path: /
            backend:
              serviceName: punk-sabertooth-prometheus-server
              servicePort: 80
```

I am also able to install this resource definition without errors.

**Comment by benmathews** [comment]
I ran into the same issue @yuvipanda describes and got here via Google. Existing and working yaml files will not work with this change. 

I think based on the above comment that the config should look like this. (Note, the docs were NOT modified and should be before this could be considered finished.)

```
server:
  ingress:
    enabled: true
    hosts: 
      - { prometheus.foo.com }
```

**Comment by yuvipanda** [comment]
Yeah, what does the - { prometheus.foo.com } syntax do? I haven't seen that before elsewhere...

**Comment by benmathews** [comment]
It makes it an interface which is what the error was complaining about. I don't know enough to say if this is the only way to do it. I'd hope not because now everyone's configuration is broken.

**Comment by hoesler** [comment]
No. From [the docs](https://github.com/kubernetes/helm/blob/master/docs/using_helm.md):

The Format and Limitations of --set:
"Lists can be expressed by enclosing values in { and }"

So on the cli `server.ingress.hosts={prometheus.mybinder.org}` means

```
server:
  ingress:
     hosts:
        - prometheus.mybinder.org
```

**Comment by hoesler** [comment]
I am really sorry, if I broke something. This was definitely not my intention. But so far, I don't see how this happened.

**Comment by benmathews** [comment]
Doing a helm install with the default values works as expected because ingress isn't even enabled. 

Using this values document

```
server:
  ingress:
    enabled: true
    hosts: 
      - prometheus.foo.com
```

Gives me 

```
helm install stable/prometheus -f valuesold.yaml 
Error: render error in "prometheus/templates/server-ingress.yaml": template: prometheus/templates/server-ingress.yaml:23:21: executing "prometheus/templates/server-ingress.yaml" at <$url>: wrong type for value; expected []interface {}; got []string
```
Using the same valuesold.yaml against an older version of the prometheus chart works as expected. 

```
$ helm install stable/prometheus -f valuesold.yaml --version 5.1.7
NAME:   anxious-tarsier
LAST DEPLOYED: Fri Feb 23 08:32:08 2018
NAMESPACE: default
STATUS: DEPLOYED
```

Now, changing the yaml to 

``` 
server:
  ingress:
    enabled: true
    hosts: 
      - { prometheus.foo.com }
```

Still doesn't work

```
$ helm install stable/prometheus -f valuesnew.yaml
Error: render error in "prometheus/templates/server-ingress.yaml": template: prometheus/templates/server-ingress.yaml:22:30: executing "prometheus/templates/server-ingress.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
```

If I run the exact command that @hoesler referenced yesterday, I also get a failure. 
```
$ helm install stable/prometheus --version 5.3.1 --debug --dry-run --set "server.ingress.enabled=true,server.ingress.hosts={prometheus.mybinder.org}"
[debug] Created tunnel using local port: '41977'

[debug] SERVER: "127.0.0.1:41977"

[debug] Original chart version: "5.3.1"
[debug] Fetched stable/prometheus to /home/ben/.helm/cache/archive/prometheus-5.3.1.tgz

[debug] CHART PATH: /home/ben/.helm/cache/archive/prometheus-5.3.1.tgz

Error: render error in "prometheus/templates/server-ingress.yaml": template: prometheus/templates/server-ingress.yaml:23:21: executing "prometheus/templates/server-ingress.yaml" at <$url>: wrong type for value; expected []interface {}; got []string
```

I did my tests against a minikube install.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by hoesler** [comment]
I am using 2.8.1 on the server. For me the above commands work for client versions 2.8.1 and 2.7.2.

Maybe it's the tiller version then?
There was a minor update to the sprig library in helm 2.8.0.

**Comment by benmathews** [comment]
That appears to be the issue. I upgraded helm so I have 
```
$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

Now, the scenarios I worked through above all work.

**Pull request merged**
