### PR TITLE
[stable/minio] Add Bucket Pod Label Capability for network policy communication when…

### PR DESCRIPTION
**Pull request by sshahinco**
… creating bucket job

Signed-off-by: Sherief Shahin <smshahin1611@gmail.com>

#### What this PR does / why we need it:
Facilitates pod communication with a given network policy

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by sshahinco** [comment]
Anu updates on this pull request? @nitisht It's quite similar to the previous one. I also wanted to know if there is something I have to do or not, relating to the released versions. When I do a `helm search -l stable/minio` I see the older versions. On average, how long does it take for a new version to be released on the helm repo? Thank you!

**Comment by nitisht** [comment]
@sshahinco have you tried `helm repo update` command? It should populate new chart versions

**Comment by sshahinco** [comment]
I tried it yesterday, but it did not retrieve it. But I guess it was too early because when I tried it now it worked. Thank you! @nitisht

**Pull request merged**
