### PR TITLE
[incubator/cloudwatch-agent] Add the helm chart for installing AWS CloudWatch Agent to Kubernetes cluster

### PR DESCRIPTION
**Pull request by s2504s**
Signed-off-by: Sergey Vasilyev <s2504s@gmail.com>

#### What this PR does / why we need it:
Setting Up Container Insights on Amazon EKS and Kubernetes
[Description](https://docs.aws.amazon.com/en_us/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html)
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by s2504s** [comment]
Hello @viglesiasce @unguiculus
Could you please review my PR?

**Comment by zanhsieh** [comment]
@s2504s 
Pinged in kubernetes slack channel #charts .

**Comment by gsf** [comment]
Thanks for creating this chart! I just pulled this in and started using it in our cluster. Only issue I'm seeing is that configurable parameters aren't injected into the cwagent-configmap.yaml as they should be.

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

**Comment by scottrigby** [comment]
PS this chart looks nice 😄 Hope to see it on the Hub. Let us know in Slack if you need any help

**Pull request closed without merging**
