### PR TITLE
fix: new line is removed from useSocketVolume section

### PR DESCRIPTION
**Pull request by rgaskill**
Template produces invalid yaml when useSocketVolume is enabled.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by L3n41c** [comment]
Hello @rgaskill,
Thanks you for spotting this !
Could you please bump the version inside `Chart.yaml`, add an entry in `CHANGELOG.md` and add a sign-off inside your commit message (`git commit --amend --signoff`) ?

**Comment by rgaskill** [comment]
yup... one sec

**Pull request merged**
