### PR TITLE
Metrics are incorrectly prefixed with ingress path

### PR DESCRIPTION
**Pull request by martinhoefling**
#### What this PR does / why we need it:

Grafana always exposes metrics at /metrics and thus are not scraped if an ingress path is provided.

http://docs.grafana.org/installation/configuration/#metrics

@gianrubio

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
Could you please fix the conflicts here and I think it's good to go!

**Comment by martinhoefling** [comment]
@vsliouniaev [x]done

**Pull request merged**
