### PR TITLE
[stable/prometheus-operator]Generate a complete Kubernetes Service

### PR DESCRIPTION
**Pull request by enflo**
Signed-off-by: Antoni Florit Homar <toniflorithomar@gmail.com>

#### What this PR does / why we need it:
I have detected that the Service does not contain many options allowed by Kubernetes, a Service is generated with these options

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

Currently if in the values file you change the service.type for loadbalancer or clusterIP it assigns random values. In my case, using loadbalancer assigns me a random public ip, and I can't adjust the ip to my private network or use a static public ip. In other Charts like stable/prometheus this configuration is used

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by paskal** [comment]
I'm sorry, but which problem does it solve? Could you please describe some real life scenarios which is impossible or harder without this change?

**Comment by enflo** [comment]
> I'm sorry, but which problem does it solve? Could you please describe some real life scenarios which is impossible or harder without this change?

Currently if in the values file you change the service.type for loadbalancer or clusterIP it assigns random values. In my case, using loadbalancer assigns me a random public ip, and I can't adjust the ip to my private network or use a static public ip. In other Charts like stable/prometheus this configuration is used.

**Review by paskal — APPROVED** [review]

**Review by gianrubio — CHANGES_REQUESTED** [review]
please add all variables and the defaults on Readme.md

**Comment by enflo** [comment]
I think all the variables are in the readme

**Pull request merged**
