### PR TITLE
[stable/airflow] added resources limit to git-clone initcontainer

### PR DESCRIPTION
**Pull request by yehlo**
Signed-off-by: Joshua Leuenberger <joshua.leuenberger@bedag.ch>

#### What this PR does / why we need it:
Git-Clone InitContainers were missing a ressources limitation. 
Defaulted it to the main container (eg. scheduler, web...)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by gsemet** [comment]
I have just approved another pr, you might need to rebase this one :)

**Comment by yehlo** [comment]
I am to stupid to make the rebase look good, going to create new pull request.

**Comment by gsemet** [comment]
“git pull --rebase” is your friend :)

**Pull request closed without merging**
