### PR TITLE
 [stable/airflow] Support affinity, nodeSelector and toleration for a…

### PR DESCRIPTION
**Pull request by MahaGamal**
#### What this PR does / why we need it:

This PRs allows to set affinity, nodeSelector and toleration for ariflow and worker 
for the k8s executor

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by gsemet** [comment]
Hi. Can you rebase ?

**Review by gsemet — CHANGES_REQUESTED** [review]
Hum i wonder if we don’t want these affinity per type (workers, web, scheduler).
Later we also may want different affinity on different types of workers.

**Comment by MahaGamal** [comment]
Sure I will update it

**Comment by gsemet** [comment]
Hi. Sorry for the delay, can you rebase again and update the version?

**Comment by gsemet** [comment]
/ldtm
/ok-to-test

You stiil need to click on the checklist on you PR and sign the DCO.

**Comment by gsemet** [comment]
/ok-to-test

@maver1ck can you approve as well?

**Comment by gsemet** [comment]
ah cool, merged without test :)

**Comment by MahaGamal** [comment]
> ah cool, merged without test :)

How has it happened?

**Comment by gsemet** [comment]
I think this is the normal behavior for "minor" version update

**Pull request merged**
