### PR TITLE
[stable/mysql] Add ability to modify timezone (#7121)

### PR DESCRIPTION
**Pull request by tristanveness**
* Add a 'timezone' to allow timezone to be configured via TZ env

### CODE REVIEW

**Comment by tristanveness** [comment]
I think I've signed the CLA now. Had to interrogate spam folder >_<

**Comment by davidkarlsen** [comment]
@tristanveness Are you by any chance using two different users in the commits?

**Comment by mattfarina** [comment]
If you go tot the commits there is one commit that is not tied to a GitHub account. That is the one causing the issue.

**Comment by tristanveness** [comment]
Thanks. Didn't realise I'd committed with 2 different emails, I've now added the other email to my github account.

**Comment by lanyangkj** [comment]
This issue also exists under stable/percona, redis-ha etc. What do we do?

**Pull request merged**
