### PR TITLE
Fix typo on hostname variable

### PR DESCRIPTION
**Pull request by admoriarty**
Signed-off-by: Aidan Moriarty <aidan.moriarty@gmail.com>

#### What this PR does / why we need it:
@kashook noted a mistake in my previous changes with mismatched variable names. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
/assign
/ok-to-test

This PR should close #12107 as well

**Comment by admoriarty** [comment]
@maorfr Its unrelated but just got caught again by not seeing JenkinsUriPrefix mentioned in the readme....is there any reason not to add it, I can throw it into this PR?

**Comment by maorfr** [comment]
go ahead, this is not merged yet anyway for some reason

**Comment by admoriarty** [comment]
@maorfr this still isn't auto-merging it seems?

**Pull request merged**
