### PR TITLE
[stable/elastalert] Fix verbose/confusing index names on Elasticsearch 6.x

### PR DESCRIPTION
**Pull request by mumoshu**
I had to set the writeback index to just `elastalert` in order to prevent elastalert to create verbose or confusing indices/types named like `elastalert_status_status/elastalert_status`, `elastalert_status_silence/elastalert_silence`, `elaststatus_status/elastalert`. The `_status` suffixes are redundant.

For more context, see the elastalert issue Yelp/elastalert#1488 which was fixed via Yelp/elastalert@c250100

### CODE REVIEW

**Comment by mumoshu** [comment]
@viglesiasce Would you mind reviewing this? Thanks!

**Comment by mumoshu** [comment]
@jertel Hi! Thanks for maintaining this chart and the companion docker image.

This is a change that I believe necessary in order to support ES 6.x. Would you mind taking a look?

**Comment by jertel** [comment]
@mumoshu Hi, and thanks for the PR. I think you might have missed a required change in templates/config.yaml. 

This line is hardcoded to `elastalert_status`:
```
 writeback_index: elastalert_status
```
and I would expect it needs to be changed to:
```
 writeback_index: {{ .Values.writebackIndex }}
```

**Comment by mumoshu** [comment]
@jertel Thanks for the review! I updated the commit, manually verified what it actually fixes, and updated the PR/commit description accordingly.

**Comment by mumoshu** [comment]
@jertel Thanks for the review! Probably we also need someone from the k8s org to approve this?

Are you aware of any reviewer who belongs to the k8s org., and has access to AWS/capable of reviewing AWS-related charts like this?

I have difficulty receiving reviews for such charts also in #5766 and #5820 recently.

**Comment by jertel** [comment]
@mumoshu You're welcome. The "charts" maintainers will take care of them. It could take several days due to the high PR volume.

**Comment by mumoshu** [comment]
@jertel Good to hear. I appreciate your support!

**Comment by mumoshu** [comment]
@unguiculus Would you mind confirming this?

**Comment by mumoshu** [comment]
Could anyone review this?

**Comment by jertel** [comment]
@mumoshu my PR that was merged a couple weeks ago also bumped the chart version to the same version you bumped to, so that's causing the lint test to fail. Can you bump yours again?

**Pull request merged**
