### PR TITLE
[stable/atlantis] Allow creation of config.yaml

### PR DESCRIPTION
**Pull request by crainte**
#### What this PR does / why we need it:
This allows the creation of a `config.yaml` for users to fill with whatever arguments they feel necessary

#### Special notes for your reviewer:
I only bumped the patch value but I did rename the ConfigMap so I'm not certain if that would require a minor version bump instead.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by crainte** [comment]
Rebased

**Review by lkysow — CHANGES_REQUESTED** [review]
Thanks for the PR but I think this will be too confusing. It will be confusing because we already have values.yaml for defining your config in YAML and now we'll have a second layer of YAML that can define the same values.

I understand that you might like this better for your use case, but I would encourage you to instead fork the helm chart.

**Comment by lkysow** [comment]
Hmm okay now I see (after reading this PR https://github.com/helm/charts/pull/14503) that this is required for Slack. Is that why you need this too?

**Comment by crainte** [comment]
Yes, this PR was started so we could configure Slack.

**Pull request closed without merging**
