### PR TITLE
[stable/neo4j] Change the image of the initContainer examples

### PR DESCRIPTION
**Pull request by olemarkus**
**What this PR does / why we need it**:
The initContainer examples use a container with an old curl version. This version of curl has failed since GitHub disabled TLSv1.  This PR updates the examples to use an image with a working curl.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by olemarkus** [comment]
The CLA should already be signed ...

**Comment by unguiculus** [comment]
cc @mneedham

**Comment by mneedham** [comment]
LGTM

**Pull request merged**
