### PR TITLE
[WIP] feat add Jenkins chart

### PR DESCRIPTION
**Pull request by lachie83**
Provides scalable Jenkins cluster based on Jenkins swarm plugin.

Outstanding
- [ ] Remove HPA
- [ ] Persistant storage
- [ ] Provide source images
- [ ] ConfigMap of Jenkins.xml
- [ ] Install Kubernetes plugin and a way to add more plugins

### CODE REVIEW

**Comment by lachie83** [comment]
Add @erictune

**Comment by viglesiasce** [comment]
Hey @lachie83!

I have some strong opinions on this one 😄 

There are a few things that we need for a Jenkins chart to be generally useful:
1.  Needs to allow you to provide a list of plugins/versions to install
2. Should use the Kubernetes plugin for build agents
3. Use persistence by one of:
     1.  Backing up and restoring from object storage using a side car
     2. Leveraging PDs
     3. Use a git volume with prebaked home directory files and a job to commit those to a repository when they are changed.

The use of the HPA in this case is not ideal because it will have no idea whether a job is currently running on the agent or not. Some jobs will not consume much CPU but will still need to persist through the life of a longer pipeline. The Kubernetes plugin only creates pods when necessary thus provides a better scaling methodology.

**Comment by viglesiasce** [comment]
Oops forgot to link to the following which gives more details for Jenkins on Kubernetes:
https://cloud.google.com/solutions/jenkins-on-container-engine

**Comment by lachie83** [comment]
Perfect - Thanks @viglesiasce. I can absolutely take a crack at most of these things and have solutions for almost all of them. My theory here was to get something into the repo then iterate. I absolutely want there to be PROD ready trusted charts but would like to know how we should iterate on these charts.

**Comment by viglesiasce** [comment]
Jenkins is not exposed publicly yet

```
./linux-amd64/helm lint jenkins
2016-08-17 23:51:14.623691 I | Preparing template jenkins/templates/jenkins-master-deployment.yaml
2016-08-17 23:51:14.624008 I | Preparing template jenkins/templates/jenkins-master-svc.yaml
2016-08-17 23:51:14.624128 I | Preparing template jenkins/templates/jenkins-slave-deployment.yaml
2016-08-17 23:51:14.624433 I | Preparing template jenkins/templates/jenkins-slave-hpa.yaml
==> Linting jenkins
[WARNING] templates/jenkins-master-deployment.yaml: wrap substitution functions in quotes or use the sprig "quote" function: : {{.Values.Master.ContainerPort}} -> : {{.Values.Master.ContainerPort | quote }}
[WARNING] templates/jenkins-master-svc.yaml: wrap substitution functions in quotes or use the sprig "quote" function: : {{.Values.Master.ServicePort}} -> : {{.Values.Master.ServicePort | quote }}
[WARNING] templates/jenkins-slave-deployment.yaml: wrap substitution functions in quotes or use the sprig "quote" function: : {{.Values.Slave.ContainerPort}} -> : {{.Values.Slave.ContainerPort | quote }}
```

**Comment by viglesiasce** [comment]
The failure here was actually a duplicate release name. I tried to delete those resources then rerun and saw this:
- ./linux-amd64/helm install jenkins
  Error: release falling-ragdoll failed: [HorizontalPodAutoscaler.autoscaling "falling-ragdoll-jenkins-" is invalid: metadata.name: Invalid value: "falling-ragdoll-jenkins-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)\* (e.g. 'example.com'), Deployment.extensions "falling-ragdoll-jenkins-" is invalid: [metadata.name: Invalid value: "falling-ragdoll-jenkins-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)\* (e.g. 'example.com'), spec.template.spec.containers[0].name: Invalid value: "falling-ragdoll-jenkins-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')], services "jenkins" already exists, Deployment.extensions "falling-ragdoll-jenkins-" is invalid: [metadata.name: Invalid value: "falling-ragdoll-jenkins-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)\* (e.g. 'example.com'), spec.template.spec.containers[0].name: Invalid value: "falling-ragdoll-jenkins-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')]]

**Comment by viglesiasce** [comment]
I believe that the truncation of 24 characters is making this provide invalid values for the named resources when the release name is long. Additionally the service name is not templated out.

**Comment by prydonius** [comment]
@viglesiasce I actually just ran into the same issue with the truncation, I filed an issue in the Helm tracker to see if there was a better way when using the release name: https://github.com/kubernetes/helm/issues/1071

**Comment by lachie83** [comment]
@viglesiasce - Added comments to related issue to relax linter in helm -- https://github.com/kubernetes/helm/issues/1037

**Comment by lachie83** [comment]
@viglesiasce @prydonius Appreciate all the feedback.

Thanks for raising a case against the 24 character name constraint. Do you know of another way to do string manipulation to drop the dash using sprig?

@viglesiasce - The service name is a constraint mentioned in the limitations in the README. I can dig a little further to see if I can variablize. Interested in your thoughts on nuking the HPA or changing the contraints.

**Comment by prydonius** [comment]
@lachie83 update on the 24 char name issue, the head of Helm now limits release names to 14 characters, so a chart can add 10 characters onto that for a deterministic name.

**Comment by viglesiasce** [comment]
@lachie83 wrt HPA, we should build a Jenkins master image that has the Kubernetes Plugin installed and use that, I think checking that into this repo would make sense. I have already poked around what it would take to get that done so I could send a PR to your branch with those changes. 

We should also use a config map of the main Jenkins config.xml so that we can parameterize the default pod config to use for the agents that the Kubernetes plugin will launch. I would also add a PVC to store jobs configs and build results. 

WDYT?

**Comment by viglesiasce** [comment]
@k8s-bot test this

**Comment by lachie83** [comment]
Hi @viglesiasce. I'm completely onboard with your suggestions. I'm about a week off looking at this again.

**Comment by lachie83** [comment]
Parking for a week or two. Updated PR title and outstanding items listed at top of PR

**Comment by viglesiasce** [comment]
Sounds good  @lachie83, if i get a chance before then I'll send a PR to your branch

**Comment by wombat** [comment]
Hi folks,
I already worked on Jenkins on K8s, Jenkins K8s cloud and Jenkins dind slave images and would be happy to merge anything that is of help with this chart :)
Feel free to look at https://github.com/WombatSoftware/Jenknetes and lets discuss if this can be of any help.

**Comment by viglesiasce** [comment]
Hey @w0mbat !! 

I have an updated chart that I'll push a PR for on Tuesday that includes the fixes to the the items mentioned in the description of this PR. The one thing I didn't yet dive into was DinD so would love to add your stuff there. I'll ping you on that PR so you can check it out. I already have the image configurable via an item in the values.yaml so hopefully its easy to integrate.

**Comment by wombat** [comment]
@viglesiasce cool - sounds good. We are using it at a customer and so far are pretty happy with the setup - mainly using it to avoid trashing the host system - downside is that there is no docker image caching so it has to repull base images all the time

**Comment by viglesiasce** [comment]
Closing in favor of #61

**Pull request closed without merging**
