### PR TITLE
Upgrade to 3.8.1

### PR DESCRIPTION
**Pull request by diemol**
Upgrading tag to newest released version: 3.8.1
I also changed the maintainer and added myself since there was not so much activity before I started sending PRs. I am also the one who is usually releasing docker-selenium in the official repo, so it just made sense to me.

### CODE REVIEW

**Comment by unguiculus** [comment]
We should still ask the old maintainer before removing them.

@flah00 Are you still interested in maintaining the chart?

**Comment by diemol** [comment]
Sure, if @flah00 wants to keep maintaining it, I am also ok with it :)

**Comment by flah00** [comment]
Adding yourself is one thing, but kicking off the original author is quite another. I'm still interested in being a maintainer. Thanks for checking in.

**Comment by diemol** [comment]
Sorry @flah00, you are 100% right, I didn't mean to be rude or disrespectful.  
I just opened #3059 to correct my impoliteness.

**Comment by unguiculus** [comment]
Sorry, I merged too early. I was gonna wait for @flah00's response.

**Pull request merged**
