### PR TITLE
[stable/drone] add logs, database and private repo pull-secret configs

### PR DESCRIPTION
**Pull request by hacktron95**
No
#### What this PR does / why we need it:
- add the ability to pull server image from private repo by passing k8s-secret name.
- add the logs configuration [DRONE_LOGS_COLOR](https://docs.drone.io/installation/reference/drone-logs-color/)
[DRONE_LOGS_DEBUG](https://docs.drone.io/installation/reference/drone-logs-debug/)
[DRONE_LOGS_PRETTY](https://docs.drone.io/installation/reference/drone-logs-pretty/)
[DRONE_LOGS_TRACE](https://docs.drone.io/installation/reference/drone-logs-trace/)
DRONE_LOGS_TEXT

- add [DRONE_DATABASE_DRIVER](https://docs.drone.io/installation/reference/drone-database-driver/), and [DRONE_DATABASE_DATASOURCE](https://docs.drone.io/installation/reference/drone-database-datasource/) configurations
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hacktron95** [comment]
@zakkg3 hello,
is there anything that I should update to help this get merged faster?
thanks

**Comment by zakkg3** [comment]
> @zakkg3 hello,
> is there anything that I should update to help this get merged faster?
> thanks

Well, I need some ppl to do my daily job, that would help :)
thanks for your PR, sorry for the delay!

**Pull request merged**
