### PR TITLE
[stable/minio] style: replace if-else statement with $variable

### PR DESCRIPTION
**Pull request by TreeKat71**
To reduce redundancy, I replace the if else statement with $scheme declared earlier.

Signed-off-by: Muller Hsu <muller79924@gmail.com>

#### What this PR does / why we need it:
No functionality change, just revise the go template syntax and make it easy to read.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by TreeKat71** [comment]
Hi @zanhsieh ,
Could you help me to merge this? It doesn't change the functionality, just reduce the redundancy.
Thanks!

**Comment by zanhsieh** [comment]
@krisis
@harshavardhana
@nitisht
@wlan0
@dvaldivia
Could you guys lgtm this ticket?

@TreeKat71 
Sorry I am not on the list of OWNER so I cannot merge it.

**Review by harshavardhana — COMMENTED** [review]
What happens to existing deployments? This looks a like breaking change.

**Comment by harshavardhana** [comment]
Ah I see it's not breaking. 

/lgtm

**Comment by harshavardhana** [comment]
Can you fix conflicts in your commit?

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL at the conflicts

**Comment by davidkarlsen** [comment]
This chart has been deprecated: https://github.com/helm/charts/pull/23414 - please submit any PRs to https://github.com/minio/charts

**Pull request closed without merging**
