### PR TITLE
[stable/chaoskube] Update docker image to v0.14.0

### PR DESCRIPTION
**Pull request by linki**
Updates to `chaoskube` to the latest version and allows using the new flags.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @linki 

think there may be anyone interested in being a maintainer of this chart with you? :)

**Comment by linki** [comment]
> think there may be anyone interested in being a maintainer of this chart with you? :)

Maybe 😃 @j0sh3rs @shaikatz @syedimam0012 @marc-sensenich @alexvicegrab Would anyone of you be interested in helping out maintaining the `chaoskube` chart?

**Comment by alexvicegrab** [comment]
I could occasionally review PRs, although I don't have as much time and focus on K8S as I did before. It might be worth adding some very basic integration tests, as I did for my own K8S project to make things easier: https://github.com/hyperledger-labs/nephos

**Comment by syedimam0012** [comment]
I'll be happy to @linki 
Cheers

**Comment by maorfr** [comment]
for each person that agrees (yay!), feel free to submit a PR that adds you to the Chart.yaml and OWNERS files. @linki can approve and merge that. just ping me on the PR so I will add you as a collaborator to the repo.

thanks!

**Comment by alexvicegrab** [comment]
Submitted #14054

**Pull request merged**
