### PR TITLE
[stable/prometheus-yace-exporter] New helm chart - prometheus-yace-exporter

### PR DESCRIPTION
**Pull request by mogaal**
#### What this PR does / why we need it:

Unfortunately, [cloudwatch-exporter](https://github.com/prometheus/cloudwatch_exporter) doesn't [support filtering by tags](https://github.com/prometheus/cloudwatch_exporter/issues/20) and it is something very handy when you want to implement auto-discovery of resources via tags. [YACE](https://github.com/ivx/yet-another-cloudwatch-exporter) is just another Cloudwatch exporter which solve this problem. There wasn't any helm chart for it so I decided to create one and share it with the community.

#### Special notes for your reviewer:

I took most of the ideas of prometheus-cloudwatch-exporter chart, so it is very similar.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Aisuko** [comment]
please take a look at helm/helm#6095 (comment)

we strongly encourage people to self host chart repos:
https://github.com/helm/hub/blob/master/Repositories.md

you can even do that using GitHub pages:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

**Comment by mogaal** [comment]
This is not self-hosted. So we can close this issue https://hub.helm.sh/charts/mogaal/prometheus-yace-exporter

**Pull request closed without merging**
