### PR TITLE
[stable/kafka-connect] Create a Kafka Connect Chart

### PR DESCRIPTION
**Pull request by benjigoldberg**
#### What this PR does / why we need it:
This chart introduces Kafka Connect to the Charts repository. Kafka Connect is a system which provides convenient integration into and out of Kafka for many common data sources, such as SQL, filesystem, Cloud K/V stores, HDFS, and more.

The chart includes optional JMX metrics export, prometheus metrics, and alertmanager alerts. 

#### Which issue this PR fixes
* N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by benjigoldberg** [comment]
For reference, this is [my second attempt to have the Kafka Connect chart added to the helm repository](https://github.com/helm/charts/pull/7045). 

CC: @davidkarlsen who was the original reviewer

**Comment by maorfr** [comment]
hey @benjigoldberg 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by benjigoldberg** [comment]
Hi @maorfr -- Happy to do that as well. Is the goal to _not_ merge new charts into stable and incubator anymore?

**Comment by benjigoldberg** [comment]
Not stale

**Comment by maorfr** [comment]
please take a look at https://github.com/helm/helm/pull/6095#issue-301608768

we strongly encourage people to self host chart repos:
https://github.com/helm/hub/blob/master/Repositories.md

you can even do that using GitHub pages:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

**Comment by benjigoldberg** [comment]
@maorfr Thank you for the links and the context, much appreciated.

**Pull request closed without merging**
