### PR TITLE
[stable/nfs-server-provisioner] deprecating chart

### PR DESCRIPTION
**Pull request by mattfarina**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by scottrigby** [comment]
See #24310

**Comment by nagasitaramthigulla** [comment]
since stable/nfs-server-provisioner is depricated 
do we have any alternative to start with

**Comment by kvaps** [comment]
Hey, there was another PR https://github.com/helm/charts/pull/23891

With the link to the new repository
https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

**Comment by kvaps** [comment]
Hey, there was another PR https://github.com/helm/charts/pull/23891

With the link to the new repository
https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

**Comment by scottrigby** [comment]
(deleted duplicate comment)

@kvaps sorry we missed your earlier PR. By the time we needed to turn down the stable and incubator repos, we had to do this programmatically for several hundred charts. We'll want to update https://github.com/helm/charts/issues/21103 to reflect the new home (see this comment https://github.com/helm/charts/issues/21103#issuecomment-732992002 a format for updating that issue after the repo became read-only still has to be set up)

**Pull request merged**
