### PR TITLE
[stable/goldpinger] add ServiceMonitor

### PR DESCRIPTION
**Pull request by azman0101**
#### What this PR does / why we need it:

Add Prometheus-operator's ServiceMonitor optionally

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by okgolove** [comment]
Hi @azman0101. Thank you for the PR.
This is a really necessary feature.

But, can you rework this one using the next template.
It is more configurable and used by more another helm charts.
Thank you!

**servicemonitor.yaml:**
```
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "service.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    path: /metrics
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end -}}
```

**values.yaml:**
```values.yaml
serviceMonitor:
  enabled: false
  namespace: monitoring
  interval: 10s
  selector:
    prometheus: kube-prometheus
```

**Comment by azman0101** [comment]
Hi @okgolove,

I've just rework as you asked.

Regards

**Review by s-vkropotko — APPROVED** [review]

**Pull request merged**
