### PR TITLE
[stable/chronograf] update to support k8s v1.16

### PR DESCRIPTION
**Pull request by billimek**
#### What this PR does / why we need it:
Handle [API deprecations](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) in kubernetes v1.16

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@billimek 
Could you fix this e2e error please?
```
I1023 14:39:11.595] ==> Linting stable/chronograf
I1023 14:39:11.597] [INFO] Chart.yaml: icon is recommended
I1023 14:39:11.597] 
I1023 14:39:11.598] 1 chart(s) linted, no failures
I1023 14:39:11.599] Installing chart 'chronograf => (version: "1.1.1", path: "stable/chronograf")'...
I1023 14:39:17.455] Error: release chronograf-opylaqfueb failed: Deployment.apps "chronograf-opylaqfueb-chronograf" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"chronograf-opylaqfueb-chronograf"}: `selector` does not match template `labels`]
```

**Comment by billimek** [comment]
> @billimek
> Could you fix this e2e error please?
> 
> ```
> I1023 14:39:11.595] ==> Linting stable/chronograf
> I1023 14:39:11.597] [INFO] Chart.yaml: icon is recommended
> I1023 14:39:11.597] 
> I1023 14:39:11.598] 1 chart(s) linted, no failures
> I1023 14:39:11.599] Installing chart 'chronograf => (version: "1.1.1", path: "stable/chronograf")'...
> I1023 14:39:17.455] Error: release chronograf-opylaqfueb failed: Deployment.apps "chronograf-opylaqfueb-chronograf" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"chronograf-opylaqfueb-chronograf"}: `selector` does not match template `labels`]
> ```

@zanhsieh Nice catch and fixed.

Additionally, it appears that the switch to apps/v1 (which is required in order for the chart to be able to deploy to kubernetes v1.16) may be a breaking change.  See [this issue](https://github.com/helm/helm/issues/6583) for some context.

Therefore, it may be necessary to bump the chart version to 1.2.0 or even 2.0.0 to denote the change.  What do you think?

**Comment by zanhsieh** [comment]
@billimek 
Agreed.

**Comment by zanhsieh** [comment]
@jackzampolin
Would yo uLGTM this chart please? Thank you.

**Review by michelgokan — APPROVED** [review]

**Pull request closed without merging**
