### PR TITLE
[stable/k8s-spot-termination-handler] Add maintainers

### PR DESCRIPTION
**Pull request by egeland**
Add maintainers as per #13867

Chart had no OWNERS file, adding myself and @KierranM 

Signed-off-by: Frode Egeland <egeland@gmail.com>

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by egeland** [comment]
@maorfr , any chance of approving this one?

**Comment by maorfr** [comment]
@egeland hey!
thanks for volunteering ;)

i'd like to get @KierranM 's lgtm on this

**Review by KierranM — APPROVED** [review]
LGTM :)

**Comment by KierranM** [comment]
Thanks for doing this @egeland

**Pull request merged**
