### PR TITLE
[stable/k8s-spot-termination-handler] add securityContext and podSecurityContext

### PR DESCRIPTION
**Pull request by skarj**
#### What this PR does / why we need it:
Add securityContext and podSecurityContext variables to enable privilege and access control settings for a Pod or Container.
For details please refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@axozoid
@egeland
@kierranm

Would you guys take a look this PR please? Thank you.

**Review by egeland — APPROVED** [review]

**Comment by zanhsieh** [comment]
@skarj 
Would you mind to bump the chart version to latest please? Thank you.

**Pull request closed without merging**
