### PR TITLE
[stable/elasticsearch] better chown in init containers

### PR DESCRIPTION
**Pull request by anapsix**
#### What this PR does / why we need it:
In some environment PVs may contain special directories, such as `.snapshot`, that are read-only.
Having these unexpected read-only directories makes `chown` initContainer to fail.

#### Which issue this PR fixes
~Introducing new attributes `master.allow_chown_failure` and `data.allow_chown_failure`, which allows `chown` container to fail..~
Implemented more targeted chown

#### Special notes for your reviewer:
~Alternatively, using more targeted chown command might be more desired.~
```
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data/nodes
chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/logs/*log*
```
More targeted chown was implemented
#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rendhalver** [comment]
Just ignoring the a failure doesn't sound like a good plan to me.
There could be other reasons the command fails.
Can you change this to use the more targeted command.

**Comment by anapsix** [comment]
@rendhalver rebased off `master`, and changed to more targeted "chown"

**Comment by anapsix** [comment]
@rendhalver could you please take a look at this again?

**Comment by anapsix** [comment]
Updated title to better reflect what code does after implementing changes suggested by @rendhalver

**Comment by anapsix** [comment]
bumped the version and merged master/origin..

**Comment by anapsix** [comment]
@rendhalver "pull-charts-e2e" is now passing

**Comment by anapsix** [comment]
merged master and bumped version `1.15.1`

**Comment by anapsix** [comment]
merged master, bumped version to `1.15.2`

**Comment by anapsix** [comment]
merged master, bumped version to `1.15.3`

**Comment by anapsix** [comment]
.. and bumped to `1.15.4`

**Comment by desaintmartin** [comment]
/assign
Instead of doing an inclusion, could we search for files based on exclusion (.snapshot) in order to be future-proof? And comment why?

**Comment by anapsix** [comment]
@desaintmartin I've targeted known Elasticsearch directories, since they seems to be stable and known..
going the other way, explicitly ignoring `.snapshot` is future proofing it, I suppose..
suggested change have been implemented

**Comment by desaintmartin** [comment]
Thanks!
/lgtm

**Review by desaintmartin — APPROVED** [review]

**Pull request merged**
