### PR TITLE
[stable/falco] Upgrade Falco to 0.18.0 and revamp auditLog feature

### PR DESCRIPTION
**Pull request by nestorsalceda**
#### What this PR does / why we need it:

This PR updates Falco Chart to its latest release. It also syncs with https://github.com/falcosecurity/falco/blob/0.18.0/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml and revamps the auditLog feature to be more similar to stable/sysdig one.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
/hold for another review

**Comment by cpanato** [comment]
@nestorsalceda I need to talk with you :), are you in the k8s slack?

**Comment by nestorsalceda** [comment]
> @nestorsalceda I need to talk with you :), are you in the k8s slack?

Yes! I will reach you!

**Comment by cpanato** [comment]
@nestorsalceda im in the sysdig slack now, made a post in falco :)

**Review by bencer — APPROVED** [review]

**Pull request merged**
