### PR TITLE
[stable/gcloud-sqlproxy] improve README.md

### PR DESCRIPTION
**Pull request by AkihiroSuda**
- Description for Cloud SQL Administration API
- Fix wrong release name
 -Fix wrong DNS name
- Tip for GNU implementation of `base64`
- Tip for MySQL

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @rimusz

**Comment by rimusz** [comment]
LGTM

**Pull request merged**
