### PR TITLE
[stable/kong] add hbagdi and shashiranjan84 as OWNERS

### PR DESCRIPTION
**Pull request by hbagdi**
#### What this PR does / why we need it:

Adding http://github.com/hbagdi and https://github.com/shashiranjan84 as OWNERS of Kong chart.

### CODE REVIEW

**Comment by hbagdi** [comment]
cc @shashiranjan84

**Comment by scottrigby** [comment]
@hbagdi and @shashiranjan84 OK great (I see you on https://github.com/Kong and your activity there, this should definitely happen. Thanks!)

I'll merge this PR now. Just added as read only collaborators to this repo per # 2 in [Owning and Maintaining A Chart](https://github.com/helm/charts#owning-and-maintaining-a-chart). Once this PR is merged, and you accept the invite, you should be able to perform bot commands on this chart 👍

**Comment by scottrigby** [comment]
Actually sorry, this is why we have CI 😄 You need to bump the chart version in this PR (it can be PATCH).

**Pull request merged**
