### PR TITLE
[stable/datadog] Remove duplicate env in initContainer

### PR DESCRIPTION
**Pull request by deiga**
#### What this PR does / why we need it:
Remove `env` duplication on init container

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by deiga** [comment]
@xlucas Could you please take a look at this? It's a really annoying bug in the Chart

**Comment by deiga** [comment]
@ahmed-mez @celenechang @charlyf @clamoriniere @hkaj @irabinovitch @L3n41c @mfpierre @vboulineau @xornivore
Sorry to ping all of you, could someone review my PR? It's been hanging around for 2 months now.

**Comment by vboulineau** [comment]
Hi @deiga,

I believe I've fixed that as part of a PR merged in the meantime, as you can see here:
https://github.com/helm/charts/blob/master/stable/datadog/templates/containers-init-linux.yaml

Do you still experience this issue?

**Comment by deiga** [comment]
Hi @vboulineau,

Yeah, it seems it's fixed already. I didn' notice that.
Thank you!

**Pull request closed without merging**
