### PR TITLE
[stable/efs-provisioner] add support for mounting with DNS

### LINKED ISSUE #12585: [stable/efs-provisioner] add support for mounting with IP
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.12.1
K8S v1.12.5-gke.5

**Which chart**: 
efs-provisioner

**What happened**:
I'd like to mount my EFS from outside my AWS VPC, but it's only possible with the IP address [see this](https://docs.aws.amazon.com/efs/latest/ug/efs-onpremises.html#wt5-step3-connect)

The chart currently supports efsFileSystemId so I can't use for the above scenario.

### PR DESCRIPTION
**Pull request by kszalontai**
#### What this PR does / why we need it:
This PR allows to use DNS for mounting an EFS

#### Which issue this PR fixes
  - fixes #12585

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by weitzj** [comment]
Hi. I am also very interested in this feature, as we don't use AWS DNS.

**Comment by hareku** [comment]
@kszalontai Thank you for your PR.
Could you fix conflicting files?

**Comment by kszalontai** [comment]
@hareku i've resolved the conflict

**Comment by weitzj** [comment]
Thank you so much

**Comment by sstarcher** [comment]
@kszalontai why was dnsName set to be required?  Anyone who upgrades will have the efs-provisioner deployment disappear.  What was the reason for this?

**Pull request merged**
