### PR TITLE
[stable/cluster-autoscaler] Add me as owner

### PR DESCRIPTION
**Pull request by yurrriq**
#### What this PR does / why we need it:
Add me as owner.

#### Which issue this PR fixes
- https://github.com/helm/charts/issues/13869

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
I've asked in Slack how to get added to the GitHub org.

**Comment by maorfr** [comment]
Hello and thanks for stepping up!
Any past contributions to this chart or others?

**Comment by yurrriq** [comment]
Yeah, I've made a few contributions to a few different charts: https://github.com/helm/charts/pulls?q=is%3Apr+author%3Ayurrriq

**Comment by yurrriq** [comment]
And a few open PRs for this chart: https://github.com/helm/charts/pulls?q=is%3Apr+author%3Ayurrriq+[stable%2Fcluster-autoscaler]

**Comment by maorfr** [comment]
works for me :)

/assign
/ok-to-test

**Comment by yurrriq** [comment]
Thanks, @maorfr! I've joined the org. What's the next step?

**Comment by maorfr** [comment]
You need to resolve the conflict that will arrive soon :)

**Comment by yurrriq** [comment]
heh on it!

**Comment by yurrriq** [comment]
I think all my :duck:s are in a row now.

**Comment by maorfr** [comment]
/lgtm

welcome to the party :)

**Comment by yurrriq** [comment]
Thanks!

**Pull request merged**
