### PR TITLE
[stable/jenkins] fix blueocean dependency issue

### LINKED ISSUE #23043: [stable/jenkins] blueocean plugin dependency issue
**Describe the bug**
Jenkins has plugin dependency issues when installing blueocean plugin. The problem is the end of the dependency chain:

```
2020-07-02 08:32:28.833+0000 [id=26]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Docker Commons Plugin v1.17 (docker-commons)
java.io.IOException: Failed to load: Docker Commons Plugin (1.17)
 - Update required: Credentials Binding Plugin (1.22) to be updated to 1.23 or higher
```
Docker Commons Plugin v1.17 (docker-commons) was released 20h ago.

**Fix:**
The fixed credentials-binding plugin version in https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml should be updated from 1.22 to 1.23.

**Version of Helm and Kubernetes**:
Helm: v3.1.3, Kubernetes v1.18.3

**Which chart**:
stable/jenkins latest (2.1.0)

**What happened**:
Jenkins can't start

**What you expected to happen**:
Jenkins can start

**How to reproduce it** (as minimally and precisely as possible):
Install latest blueocean plugin via "additionalPlugins" configuration

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by mscholze**
#### Is this a new chart
no

#### What this PR does / why we need it:
Fix blueocean plugin dependency issues with credentials-binding plugin 1.22

#### Which issue this PR fixes
  - fixes #23043

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mscholze** [comment]
Force-pushed to fix commit message (use real name to meet contribution guidlines)

**Comment by torstenwalter** [comment]
@mscholze Thank you for the PR

**Comment by torstenwalter** [comment]
@mscholze `java.lang.AssertionError: class hudson.security.csrf.DefaultCrumbIssuer is missing its descriptor` could it be that JCasC config differs with the new plugin version?

**Comment by mscholze** [comment]
@torstenwalter No it shouldn't. I got this warning already some days ago. Looks like another issue: https://issues.jenkins-ci.org/browse/JENKINS-56812

**Pull request merged**
