### PR TITLE
[stable/etcd-operator] removed lachie83 as a reviewer and approver

### PR DESCRIPTION
**Pull request by alejandroEsc**
#### What this PR does / why we need it:
lachie83 is no longer a reviewer/approver and made mention of this in the past. Let's stop spamming him or confusing contributors. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by paulczar** [comment]
/ok-to-test

I would imagine this will still need a chart version bump, and I'd like to see @lachie83 respond his okay here too.

**Comment by alejandroEsc** [comment]
> /ok-to-test
> 
> I would imagine this will still need a chart version bump, and I'd like to see @lachie83 respond his okay here too.

Sure to both. I am awaiting for https://github.com/helm/charts/pull/16714 to merge first, can you @paulczar push allow the the tests to run on that PR and rerun those tests? I have memory being able to allow these but it seems i do not any longer?

**Comment by paulczar** [comment]
looks like the other one is merged!

**Comment by zanhsieh** [comment]
@alejandroEsc 
Mind you sign DCO and bump the chart to latest please? Thank you.

**Pull request closed without merging**
