### PR TITLE
[incubator/jaeger]  FIX - Set elasticsearch password only if used

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### What this PR does / why we need it:

Please see https://github.com/helm/charts/issues/15122#issuecomment-509728009

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mentalblock** [comment]
I just realized this is broken because the `eq` function is not given a second argument.

**Comment by pavelnikolov** [comment]
Could you, please, push a PR with a fix?

**Comment by naseemkullah** [comment]
AFK now but will do in a bit

**Comment by naseemkullah** [comment]
Sorry about that guys, here is the fix: https://github.com/helm/charts/pull/15413

**Pull request merged**
