### PR TITLE
Add Replace_Dots option to fluent-bit elasticsearch output

### PR DESCRIPTION
**Pull request by donbowman**
This addresses https://github.com/fluent/fluent-bit/issues/854.
Make 'Replace_Dots' settable for fluent-bit elasticsearch
output, and default to 'On'.

Signed-off-by: Don Bowman <db@donbowman.ca>

#### What this PR does / why we need it:

Elasticsearch does not allow a leaf to be both 'text' and 'object'. In Kubernetes, labels + annotations can be of the format 'app' or 'app.kubernetes.io/foo', which confuses it. Fluent-bit has an option 'Replace_Dots' which should be settable (and default on).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

https://github.com/fluent/fluent-bit/issues/854

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ x] Chart Version bumped
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by rimusz** [comment]
please bump chart version to 0.13.2

**Comment by donbowman** [comment]
is there anything more I need to do here? This is the 2nd time now i'll have to update the version to avoid conflict on merge

**Comment by donbowman** [comment]
is there anything more I need to do here?

**Comment by donbowman** [comment]
@rimusz i need the /lgtm etc again since after bumping the chart version to match master it shows as a change.

**Comment by donbowman** [comment]
coming back to this, @rimusz @davidkarlsen @foxish I'm not sure what more is needed from me.
The workflow removed the /lgtm when I rebased to get the Chart version bump.

**Comment by donbowman** [comment]
ping? hello?
What more is needed from me?

**Comment by kfox1111** [comment]
lgtm

**Comment by donbowman** [comment]
I believe https://github.com/helm/charts/pull/9008 incorporates this, closing.

**Pull request closed without merging**
