### PR TITLE
[stable/sysdig] Allow the DaemonSet to schedule using affinity rules

### PR DESCRIPTION
**Pull request by thiagocaiubi**
#### What this PR does / why we need it:

Allow the DaemonSet to schedule ussing affinity rules

Heavily inspired by
https://github.com/helm/charts/blob/master/stable/signalsciences.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

@lachie83 @bencer @nestorsalceda

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/ok-to-test
/approve

**Review by nestorsalceda — APPROVED** [review]

**Comment by cpanato** [comment]
hey @nestorsalceda when you have some time can you review this pr?

**Comment by cpanato** [comment]
we are in sync @nestorsalceda 😂

**Comment by nestorsalceda** [comment]
> we are in sync @nestorsalceda joy

Hahahaha! The Helm connection, bro! :D

**Pull request merged**
