### PR TITLE
[stable/traefik] Improve kubernetes section in values.yaml.

### PR DESCRIPTION
**Pull request by timstoop**
The values.yaml had the kubernetes section under the ingress section, which is not correct. This would've saved me a few minutes of searching and reading the source.

### CODE REVIEW

**Comment by timstoop** [comment]
CLA procedure fulfilled.

**Comment by timstoop** [comment]
Not sure if and how I should restart CircleCI testing, sorry.

**Comment by krancour** [comment]
I agree that the indentation is wrong and should be corrected, however, I would discourage the change wherein you've assigned `kubernetes` a default value of `{}` instead of just commenting it out. That _is_ a nice thing to do in that it alleviates the need for extra `nil` checks in the chart's templates, _but_ it's harder to explain to users that to configure any of the subordinate settings in that section, they must _also_ delete the `{}`. It's easier and more intuitive for people to just uncomment stuff.

**Comment by timstoop** [comment]
I'm happy to change that, didn't know what the default was and noticed some charts that do it that way (particularly stable/prometheus and stable/redis) and it's also used for the nodeSelector within this values.yaml. But I'll change it.

**Comment by krancour** [comment]
Yep. That change wasn't wrong, per se, but as it stands this chart is fine and easy to work with without that change. Of course the indentation issue is still a grrat catch. Thank you so much for noticing it and taking the initiative to fix it.

**Comment by unguiculus** [comment]
What is the status with this?

**Pull request merged**
