### PR TITLE
[stable/prometheus-mysql-exporter] feat: add optional ServiceMonitor

### LINKED ISSUE #14563: [stable/prometheus-mysql-exporter] Add support for Prometheus Operator's ServiceMonitor
I would like to add a ServiceMonitor to `stable/prometheus-mysql-exporter`. The current discovery mechanism ([`prometheus.io/scrape`](https://github.com/helm/charts/blob/master/stable/prometheus-mysql-exporter/values.yaml#L39-L41)), doesn't work for the common Prometheus Operator setup. From what I can tell, [`coreos/kube-prometheus` hasn't supported this annotation-driven mechanism since ~2017](https://github.com/coreos/kube-prometheus/pull/16#issuecomment-305933103).

**Is your feature request related to a problem? Please describe.**
Yes, this chart is not compatible out-of-the-box with Prometheus Operator. I would need to write an additional chart to add a `ServiceMonitor` for this `Deployment`.

**Describe the solution you'd like**
I would like to add a `monitoring.coreos.com` `ServiceMonitor`. It will `selector.matchLabels` on `app: {{ template "prometheus-mysql-exporter.name" . }}`.

Optionally, I could _remove_ the `prometheus.io/*` default annotations. This would be a breaking change, but there may not be many users affected. Perhaps it would make sense to do that in a separate PR.

**Describe alternatives you've considered**
#### Roll My Own
I could roll my own chart which creates a `ServiceMonitor`. It could be installed alongside `stable/prometheus-mysql-exporter` or wrap it with a dependency. However, this makes our configuration slightly more complicated, and doesn't allow the community to benefit from my work.

/cc past contributors @monotek @Tarick @estahn  @Juanchimienti

### PR DESCRIPTION
**Pull request by tklovett**
#### What this PR does / why we need it:

See Issue #14563

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #14563

#### Special notes for your reviewer:

/cc @Juanchimienti 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by monotek — APPROVED** [review]
/lgtm

**Comment by tklovett** [comment]
/assign @paulczar 

@monotek Looks like the bot won't let you approve since there is no OWNERS files in this chart :(

**Comment by tklovett** [comment]
I resolved the merge conflict 👍

**Comment by tklovett** [comment]
Is this OK to test?

**Review by Zempashi — COMMENTED** [review]
Tested this successfully few days ago.

**Review by monotek — APPROVED** [review]
/lgtm

**Review by monotek — CHANGES_REQUESTED** [review]
please merge master & bump version

**Review by monotek — APPROVED** [review]
/lgtm

**Pull request merged**
