### PR TITLE
[stable/rabbitmq-ha] Allow specify custom rules for role

### PR DESCRIPTION
**Pull request by matejhasul**
Signed-off-by: Matej Hasul <matej.hasul@gooddata.com>

#### What this PR does / why we need it:
Allow to specify custom rules for rabbitmq role. Our use case is to get amqp port of rabbitmq service  via k8s api from custom sidecar container (introduced in https://github.com/helm/charts/pull/16660).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
> Allow to specify custom rules for rabbitmq role. Our use case is to get amqp port of rabbitmq service via k8s api from custom sidecar container (introduced in #16660).

Why does this need to be part of the chart? You can just create a separate role and rolebinding to the same rabbitmq serviceaccount for your purposes, right?

**Comment by matejhasul** [comment]
You are right, it does not have to be part of the chart. I did not realize it, sorry. Your suggested solution works as expected.

However it would be nicer and more compact if it is part of the chart. On the other hand, I understand your concern about unnecessary bloating of the chart. Feel free to close the PR if you are not willing to merge it.

**Comment by steven-sheehy** [comment]
I think it should be separate from the chart as it's a bit specific to your use case and there is a more appropriate solution. Unfortunately I don't have permission to close the PR.

**Comment by matejhasul** [comment]
OK, closing.

**Pull request closed without merging**
