### PR TITLE
[stable/prometheus-blackbox-exporter] Fix upstream URL

### PR DESCRIPTION
**Pull request by anuraaga**
**What this PR does / why we need it**:

Fixes broken URL in README and install command

### CODE REVIEW

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by anuraaga** [comment]
Sure, though I'm surprised to do that for a README-only change.

**Comment by bhack** [comment]
Is this a duplicate of https://github.com/kubernetes/charts/pull/6399?

**Comment by anuraaga** [comment]
Yeah looks like the README changes are already part of that one. Feel free to close this if that one will get merged.

**Comment by unguiculus** [comment]
Closed in favor of #6399.

**Pull request closed without merging**
