### PR TITLE
[stable/rabbitmq-ha] Fix health checks

### LINKED ISSUE #7752: [stable/rabbitmq-ha] new HTTP healthcheck probe never fail
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm v2.9.0
k8s v1.9.7

**Which chart**:
rabbitmq-ha 1.9.0

**What happened**:
Probes never fail.

**What you expected to happen**:
Probes should fail if rabbitmq nodes fail.

**How to reproduce it** (as minimally and precisely as possible):
no repro: it's a code review found issue, see next point.

**Anything else we need to know**:

Since #7378 from @steven-sheehy a new (and way faster!) healthcheck is used for probes:
`httpGet` on `/api/healthchecks/node`

This api always returns 200 according to the doc:
https://rawcdn.githack.com/rabbitmq/rabbitmq-management/v3.7.7/priv/www/api/index.html
> Runs basic healthchecks in the current node. Checks that the rabbit application is running, channels and queues can be listed successfully, and that no alarms are in effect. If everything is working correctly, will return HTTP status 200 with body:
> {"status":"ok"}
> **If something fails, will return HTTP status 200** with the body of
> {"status":"failed","reason":"string"}

As for the k8s `httpGet` probe:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

=> the probe will *not* fail when the rabbitmq healthcheck api returns an error.

I suggest using something like `test "$(wget ...)" = '{"status":"ok"}'` as probe command (`bash` and `wget` are available in the used rabbitmq alpine docker image).

As a side-note, maybe we could ask upstream rabbitmq to support an alternative status code schema using a special header (to avoid breaking change): return 5xx when healthcheck fails?

### PR DESCRIPTION
**Pull request by steven-sheehy**
#### What this PR does / why we need it:
Fixes regression in rabbitmq health checks introduced in my previous PR. See ticket for details.
Also bumps the initial readiness probe to avoid failing initially before rabbitmq is fully up.

#### Which issue this PR fixes
  - fixes #7752

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by bjornryden** [comment]
I'm not sure this is the right place to bring this up, but please bear with me:
We had a provoked cluster outage, to test things coming back up and we got bitten a bit by well-known situations around rabbit.
First thing was to do the `.spec.podManagementPolicy: Parallel` which I believe is discussed in a different PR.
Second thing is regarding the Probes. For the cluster to report OK to the probes, it needs to be up and in quorum. The service will not get any active endpoints while the probes are failing and the services endpoints are being used for the cluster to establish. So this is a bit of a catch 22, if I understand this correctly.
We recovered by deleting the statefulset, setting the parallel podManagementPolicy and disabling/removing the probes.
Sorry if there's something I'm missing.

**Comment by steven-sheehy** [comment]
@bjornryden This is really not the place to discuss. But I don't see why anyone would use Parallel with rabbitmq, use OrderedReady and let it RollingUpdate so only one is down at a time. Make sure you use odd number of replicas so that there's a quorum. Ensure your queues are mirrored across more nodes than will be down. The probe doesn't check across nodes only that the current node is up and able to list queues. See [/api/healthchecks/node](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.8/priv/www/api/index.html)

**Comment by steven-sheehy** [comment]
A similar change was merged in PR #8146 for the other rabbitmq chart.

**Comment by steven-sheehy** [comment]
@davidkarlsen Any changes I need to make for this to be approved?

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
