### PR TITLE
[stable/apm-server] Add optional TLS configuration to the chart

### PR DESCRIPTION
**Pull request by amit-o**
#### What this PR does / why we need it:
Add optional TLS configurations to the recently added ingress object

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mumoshu** [comment]
@amit-o Would you mind signing commits according to the instruction explained in https://github.com/helm/charts/pull/14305/checks?check_run_id=140590481 ?

**Comment by amit-o** [comment]
> @amit-o Would you mind signing commits according to the instruction https://github.com/helm/charts/pull/14305/checks?check_run_id=140590481 ?

Yep, sorry about that.

**Pull request merged**
