### PR TITLE
[stable/k8s-spot-termination-handler] Merge [incubator/kube-spot-termination-notice-handler] into this chart

### PR DESCRIPTION
**Pull request by legal90**
#### What this PR does / why we need it:

Apparently, there are 2 charts for the same products in `stable` and `incubator`:
- `incubator/kube-spot-termination-notice-handler` added by https://github.com/helm/charts/pull/1908
- `stable/k8s-spot-termination-handler` added by https://github.com/helm/charts/pull/8187

This PR merges useful changes from `[incubator/kube-spot-termination-notice-handler]` to `[stable/k8s-spot-termination-handler]`:

- Switches to the image `kubeaws/kube-spot-termination-notice-handler` which has better support and versioning.
- Adds the support of Slack integration
- Allows to customize EC2 metadata poll interval
- Improves the RBAC policies, so there should be no issues for the `k8s-spot-termination-handler` to drain the node (the fix https://github.com/helm/charts/pull/4730 ported)
- Updates k8s labels according to the latest guidelines of Helm (https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels)
- Deletes `incubator/kube-spot-termination-notice-handler` chart. Considered it as promoted to stable by this PR.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

cc: @egeland , @kierranm

Closes #10270 as superseded

### CODE REVIEW

**Comment by legal90** [comment]
Could anyone please review this PR?
cc @foxish, @lachie83, @mattfarina

**Review by egeland — APPROVED** [review]
While I'm sad that my chart was gazumped ( 😉 ), this stable chart looks good, too! 👍

**Comment by egeland** [comment]
Can we add in #10093 functionality, too?

**Comment by egeland** [comment]
Would be good to get this done, so we have one canonical chart going forward.

Given this PR has lingered since 29Dec, I don't feel (too) guilty to mass-mention the approvers:
@lachie83 
@prydonius
@sameersbn
@viglesiasce
@foxish
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato

**Comment by legal90** [comment]
@egeland Thanks! I've appended changes from your PR #10093 to this one. 👍

**Pull request merged**
