### PR TITLE
[incubator/linkerd2] New chart for Linkerd2

### PR DESCRIPTION
**Pull request by alpeb**
#### What this PR does / why we need it:

This is a chart for Linkerd2, that didn't exist in this repo.

#### Special notes for your reviewer:

This is the official chart from the Linkerd2's maintainers. Looking forward for your comments :)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by alpeb** [comment]
Hi @scottrigby, any feedback on this PR? Is there something else pending we need to do on our side before this can get reviewed? Thanks.

**Comment by Aisuko** [comment]
I'm sorry for replying to this too late.

Please take a look at helm/helm#6095 (comment)

We strongly encourage people to self-host chart repos:
https://github.com/helm/hub/blob/master/Repositories.md

You can even do that using GitHub pages:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

**Comment by alpeb** [comment]
Thanks @Aisuko . We ended up publishing our own repos and submitting to the Helm Hub, so I'm closing this issue.

**Pull request closed without merging**
