### PR TITLE
[datadog][dogstatsd] Add datadog's dogstastd standalone chart

### PR DESCRIPTION
**Pull request by tuannvm**
## Why?
- Datadog has rewritten their [agent](https://github.com/DataDog/datadog-agent) in golang.
- Dogstatsd is a standalone part of the new agent.
- This helm chart provide support for that.

### CODE REVIEW

**Comment by pierreozoux** [comment]
There is already a datadog chart https://github.com/kubernetes/charts/tree/master/stable/datadog with dogstasd:
https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/service.yaml#L16-L18

**Comment by tuannvm** [comment]
@pierreozoux this is part of the new agent rewritten in golang :) Perhaps I need to update description to clarify this, thanks!

**Comment by unguiculus** [comment]
Please read our review guidelines and follow best practices, especially regarding labels.
https://github.com/unguiculus/charts/blob/master/REVIEW_GUIDELINES.md

@tuannvm @pierreozoux Does this chart supersede the existing one? Would it make sense to update the existing chart instead of creating a new one?

**Comment by xvello** [comment]
@tuannvm thanks for your interest in dogstatsd6!

We currently distribute three images:

- `datadog/docker-dd-agent`: the current agent5 / dogstatsd5, deployed by the `datadog` chart
- `datadog/agent`: the open beta of the future agent6. This will be the final image name for agent6 when it reaches GA
- `datadog/dogstatsd`: the [standalone light dogstatsd image](https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/dogstatsd/alpine) from agent6 (open beta too)

The main use case for this light image is to run it as a sidecar container inside pods, as it has a very small memory footprint and supports running alongside an existing agent, by setting `DD_ENABLE_METADATA_COLLECTION=false`. 

We are currently working on updating the chart to support agent6 deployments, but that's not trivial. What we could do is offer an option in the agent6 chart to override the default `datadog/agent` image name with `datadog/dogstatsd` to only deploy dsd6. Would that work for you?

**Comment by tuannvm** [comment]
Hi @xvello , thanks for the feedback!

> We are currently working on updating the chart to support agent6 deployments, but that's not trivial. What we could do is offer an option in the agent6 chart to override the default datadog/agent image name with datadog/dogstatsd to only deploy dsd6. Would that work for you?

At first, I would like to create a helm chart for agent6, but then I see the documentation is unfinished, so I write this to work with my specific use case, i.e some lightweight service to send custom metrics to.

So just to confirm, `agent6 chart` would be a separated chart from the current `datadog chart`, right?

**Comment by xvello** [comment]
hi @tuananh 

As agent6 is as compatible with agent5 as possible (although we're deprecating several legacy features), modifying the chart to support agent6 is pretty simple: https://github.com/kubernetes/charts/pull/3368

Do you see a use case to prefer a different chart?

**Comment by xvello** [comment]
hi @tuananh,

Did you manage to deploy the updated `datadog` chart? I'd love to have your feedback on it.

**Comment by tuananh** [comment]
@xvello you probably mean @tuannvm ?

**Comment by xvello** [comment]
Yes, my bad 🙇

**Pull request closed without merging**
