### PR TITLE
Spleling

### PR DESCRIPTION
**Pull request by mrwacky42**

### CODE REVIEW

**Comment by Miouge1** [comment]
@mrwacky42 you need a version bump even for a documentation change.

**Comment by mrwacky42** [comment]
Spelling sure is a lot of work. Are you sure we need all the DCO/e2e tests just to change docs?

**Comment by davidkarlsen** [comment]
@mrwacky42 yes, they are needed, see the failing "checks" section in this PR

**Comment by mrwacky42** [comment]
@davidkarlsen - I realize the repository is configured to require these checks. However, the checks are timing out not because good spelling and grammar is breaking the test, but because the tests are bad.
I was just wondering out loud if there is a better way to short-circuit changes that are purely cosmetic.

**Comment by mrwacky42** [comment]
Ok, good luck fixing your test suite, I'm unsubscribing from this PR.

**Comment by mrwacky42** [comment]
Stale bot, spelling and grammar *is* important.

**Comment by cpanato** [comment]
@mrwacky42 please rebase the PR

**Comment by cpanato** [comment]
ping @davidkarlsen

**Pull request merged**
