### PR TITLE
[stable/elasticsearch-curator] Fixed values for helm hooks and added CI test for it

### PR DESCRIPTION
**Pull request by lebenitza**
#### What this PR does / why we need it:

Fixes a previous release which tried to fix the helm hooks in the chart :( 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name

@desaintmartin @gianrubio

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks!
I realize there is no default values.yaml for CI, could you add it (see redis chart for example)?

/assign

**Comment by MihaiAnei** [comment]
@desaintmartin good catch. Done. 

More generally speaking, would not this be nice to be the default CI behavior for all chart? Meaning, testing it's deployable with default values.yaml

**Comment by desaintmartin** [comment]
Thank you very much ;)
/lgtm

I believe it has been done like this to be explicit!
But, if no ci directory exists, it will test with default values.

**Pull request merged**
