### PR TITLE
[stable/kibana] Make serviceAccountName configurable

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**:
This PR makes serviceeAccountName configurable. 
This can be useful in Kubernetes and is mandatory to use this chart in Openshift.

### CODE REVIEW

**Comment by ghost** [comment]
cla signed

**Comment by compleatang** [comment]
Can you add an entry in the table in the README and also a commented entry in the values.yaml? This will help new folks understand that such a configuration option exists.

**Comment by ghost** [comment]
ok, done.

**Comment by compleatang** [comment]
LGTM 👍

**Pull request merged**
