### PR TITLE
[stable/postgresql] Fix typo

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
Should I bump the chart version for a change like this?

**Comment by rafariossaa** [comment]
Hi, 
  You need to bump the patch version of the chart.

**Comment by saraedum** [comment]
@rafariossaa, ok fixed.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, helm charts are being restructured.

  Could you make the PR to this other repository https://github.com/bitnami/charts .

Thanks forehand.

**Comment by carrodher** [comment]
Yes, sorry, this PR appeared in the middle of the transition to distributed repositories.
Since https://github.com/helm/charts/pull/21408 was merged the chart in this repository is deprecated, in this PR you can find a linked issue with all the information related to the transition process.

Sorry again for the inconveniences, as @rafariossaa said, now the code is hosted [here](https://github.com/bitnami/charts) and contributions are welcome in this new place.

**Comment by davidkarlsen** [comment]
Chart is deprecated.

**Pull request closed without merging**
