### PR TITLE
[stable/kong] mark the chart as deprecated

### PR DESCRIPTION
**Pull request by hbagdi**
Signed-off-by: Harry Bagdi <harrybagdi@gmail.com>

No

#### What this PR does / why we need it:

Marking the chart as deprecated.
New repository is at https://charts.konghq.com

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hbagdi** [comment]
cc @rainest

**Review by shashiranjan84 — APPROVED** [review]

**Comment by hbagdi** [comment]
@cpanato SEems like CI has an issue with custom resource. How can we fix that problem?

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Comment by cpanato** [comment]
/approve cancel
/lgtm cancel

sorry, just realize you need to edit the readme as well and add a note that this is deprecate and where people can find the new helm repo

**Review by cpanato — CHANGES_REQUESTED** [review]
see my comment

**Comment by cpanato** [comment]
now it is timoe out
```
I0423 07:25:49.389] nc: kong-3y8qjlv6dy-postgresql (10.3.246.240:5432): Connection timed out
I0423 07:25:49.389] waiting for db
```

**Comment by hbagdi** [comment]
@cpanato We already had deprecated the chart before but didn't mark the chart as such: https://github.com/helm/charts/blob/master/stable/kong/README.md

**Review by cpanato — COMMENTED** [review]
/lgtm
/approve

**Comment by hbagdi** [comment]
The last test failure was due to:
> I0423 16:01:46.238] Error: could not find a ready tiller pod

/test pull-charts-e2e

**Comment by hbagdi** [comment]
And now we are back at the CRD already exists problem.

**Comment by hbagdi** [comment]
ping @cpanato

**Comment by cpanato** [comment]
@hbagdi since this chart is deprecated maybe you can remove the test values that uses the db since that is failing

**Comment by hbagdi** [comment]
@shashiranjan84 @cpanato Please take another look.

**Pull request merged**
