### PR TITLE
[stable/envoy] Fix typo for envoy

### PR DESCRIPTION
**Pull request by renjikari**
#### Is this a new chart
No

#### What this PR does / why we need it:
Fix my #18878 typo
from `lifecyle` to `lifecycle`

#### Which issue this PR fixes
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by renjikari** [comment]
@mumoshu 
I fix my old typo. It's pointed out in #18878
Would you mind reviewing?

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
