### PR TITLE
[stable/prometheus-operator] Add kube-proxy exporter to prometheus-operator charts.

### PR DESCRIPTION
**Pull request by whypro**
#### What this PR does / why we need it:

Add kube-proxy exporter to prometheus-operator charts.

To collecting kube-proxy metrics, we should edit kube-proxy config and enable metrics port:
https://github.com/helm/charts/pull/14234#issuecomment-497561647

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by whypro** [comment]
cc @gianrubio @anothertobi

**Comment by vsliouniaev** [comment]
/ok-to-test

Thanks @whypro ! Will try to get some time to test it soon as I can

**Comment by vsliouniaev** [comment]
@whypro Could you add instructions about what needs to be changed with the kube-proxy deployment to make this work properly? By default it's missing a port and it seems to bind to 127.0.0.1 too, but I'm not sure about the scope of necessary changes to make this work in all clusters.

**Comment by whypro** [comment]
> @whypro Could you add instructions about what needs to be changed with the kube-proxy deployment to make this work properly? By default it's missing a port and it seems to bind to 127.0.0.1 too, but I'm not sure about the scope of necessary changes to make this work in all clusters.

We could just set `metricsBindAddress` in kube-proxy ConfigMap to `0.0.0.0:10249` to expose metrics.

For examples: 

``` yaml
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    # other configs ...
    metricsBindAddress: 0.0.0.0:10249
    # other configs ...
  kubeconfig.conf: |-
    # ...
kind: ConfigMap
metadata:
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
```

**Comment by whypro** [comment]
hi @vsliouniaev,  I've add some introdutions, could you ptal?

**Comment by vsliouniaev** [comment]
@whypro Sorry about the wait - got this working locally in `kind` so I think it would be good to go if you re-open or re-create the PR. It would be good to add the instructions about how to expose the ports to the README.md

**Comment by whypro** [comment]
@vsliouniaev Thanks! I will create another PR.

**Comment by pgporada** [comment]
Does this section have to be added to the configmap or should it just be edited in place? 
```
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    # other configs ...
    metricsBindAddress: 0.0.0.0:10249
    # other configs ...
```

Should it already exist when I run this command?
```
$ kubectl -n kube-system get configmap/kube-proxy -o yaml
```

**Pull request closed without merging**
