### PR TITLE
Sync prometheus operator dashboard and rules

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Signed-off-by: Matteo Gazzetta <matteo_gazzetta@hotmail.it>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@ElfoLiNk Could you please bump the chart version?

**Comment by ElfoLiNk** [comment]
Done

**Comment by vsliouniaev** [comment]
Thanks!
/lgtm

**Pull request merged**
