### PR TITLE
Adding support Tensorflow Serving REST API

### PR DESCRIPTION
**Pull request by cpena**
#### What this PR does / why we need it:
 Adding support to Tensorflow Serving REST API and use by default official docker image.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cheyang** [comment]
@cpena could you fix the automatic testing issue?
```
I0113 04:23:33.704] 2019-01-13 04:13:43.733313: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path gs://model-base-path/model-nam for servable model-name
```

**Review by cheyang — COMMENTED** [review]
I think this default value fails the automatic testing.

**Comment by igaskin** [comment]
@cpena this PR would be useful to get merged.  The failure in the automatic testing is due to the version bumped image, which now is validating that the base model path exists.  Do you want to correct this in this PR, or in a separate one? From what I can tell there is no way to ignore loading the model at startup.  We could potentially set the default image to one that has a model loaded it, so that the pod will come up cleanly?

**Comment by ckdarby** [comment]
This would actually be very useful. Today I am stuck doing pretty much what this PR is suggesting to be able to get REST & default image.

**Pull request closed without merging**
