### PR TITLE
Added ingress support for the stable/ipfs chart

### PR DESCRIPTION
**Pull request by jonaskint**
#### What this PR does / why we need it:
The PR implements 2 ingress rules for the ipfs gateway and api. This way, the chart now supports Kubernetes ingress rules and possible Letsencrypt certificates.

#### Which issue this PR fixes
- Implements: https://github.com/helm/charts/issues/18100

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jonaskint** [comment]
Anything that needs to be done to move this pr forward?

**Comment by maorfr** [comment]
/lgtm

thanks and congrats on your first contribution!

**Comment by zanhsieh** [comment]
@jonaskint 
Would you mind to get another version bump to latest? e2e failed due to version problem.

**Comment by jonaskint** [comment]
Hi @maorfr i need another /lgtm as the version needed an extra bump.

**Pull request merged**
