### PR TITLE
incubator/webpagetest-server add all paths to wptest server ingress

### PR DESCRIPTION
**Pull request by shmargum**
@timothyclarke these charts work pretty well, but the i have been manually making this small edit to the ingress portion (I am using this with aws-alb-ingress-controller + external-dns)

#### Is this a new chart
NO

#### What this PR does / why we need it:
Fixes ingress for routes other than homepage (fixes assets, and other urls)

#### Which issue this PR fixes
none

#### Special notes for your reviewer:
I have been using the official docker images `webpagetest/server` and `webpagetest/agent` (they work fine)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by timothyclarke** [comment]
I've never needed the `*` on the ingress. Are you sure that is not specific to your setup.
I'd be happier if you pulled that change to `values.yaml` and defaulted to the current `/`

**Comment by shmargum** [comment]
@timothyclarke I have only used the AWS alb ingress controller, and it does need the *, otherwise all routes except / 404.  An example ingress looks like this https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/2048/2048-ingress.yaml

Anyways, I have made the change to parameterize the path with / being the default.

**Pull request closed without merging**
