### PR TITLE
[stable/airflow] git sync sidecar container

### PR DESCRIPTION
**Pull request by hmike96**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR enables a gitSync feature that will spawn on sidecar container in the all the pods that syncs dags with a git repository(only in pods that need dags). It syncs after a desired amount of time. This feature by now way inhibits any old implementation it simply will spawn the side car only if you go in and enable it. I noticed I needed this because if I updated my dags in my git repo the I had to kill all my pods to resync them when just using the initContainer feature. I have test this feature and it works as expected.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hmike96** [comment]
@gsemet

**Comment by gsemet** [comment]
Looks amazing ! But don’t you still have to kill and restart all the pods to have them see the latest version of your DAGs

**Comment by hmike96** [comment]
You actually don't have to because the git-sync container and the other container in each of the  pods (the one running the airflow service whether it be worker, web or scheduler) have the same volume mounted. This volume for the airflow container is mounted as dags directory and the volume for the git sync container is the location where the git repository is. The git sync just runs a git pull in that volume every so often (you choose with the git.gitSync.refreshRate value). The name of this volume mounted in both container is the dags-data if you want to look. You can also alter how often the UI of dags is updated internally to airflow (The time it takes for airflow scheduler to register new dags with db and have the web server update the UI) https://stackoverflow.com/questions/51558313/what-is-the-difference-between-min-file-process-interval-and-dag-dir-list-interv

**Comment by hmike96** [comment]
@gsemet any updates on this one?

**Comment by gsemet** [comment]
/lgtm

ok for me, thanks a lot for the README update :)

**Comment by javamonkey79** [comment]
@hmike96 I can't seem to get this feature to work. I wonder if the docs are missing something? I added the new fields, I can see the git sync container pull, but, it never updates in airflow. 

```
airflow:
  config:
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: False
  fernetKey: "xxx"
  variables: '{ "environment": "dev" }'
  connections:
  - id: databricks
    type: databricks
    login: something
    password: else
    host: foo.com
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: myhost.domain.com
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
dags:
  initContainer:
    enabled: true
  git:
    url: https://oauth2:123@gitlab/something.git
    ref: refs/remotes/origin/wip
    gitSync:
      enabled: true
      refreshTime: 60
persistence:
  enabled: true
  storageClass: gp2
```

**Comment by hmike96** [comment]
@javamonkey79 If you shell into the git sync and the airflow-web (or scheduler just using one as example) do the contents in the dags folders match? Also if you shell into airflow web, after a new git pull of some content in the git sync container, do the contents in the dags directory change? If the contents are changing correctly, it is the schedulers job to update the database which the web server then reads to update the UI. This can sometimes take up to 5 minutes though.

**Comment by javamonkey79** [comment]
hey @hmike96 thanks for your response :)

That's the funny thing, I did try shelling in and checking the dags and it didn't match what was in git, even though when I follow the log for the git sync container, I can clearly see it pulling. 

It seems to be either an issue with the persistent volume or perhaps an issue with the fact that I have my git repo pointed at a branch. 

For now, I've fallen back to using a cronpod, but, I'd love to use this new built in functionality.

**Comment by hmike96** [comment]
Of course @javamonkey79 !

Interesting yeah I have it working currently but I am just using the master branch. For `ref: refs/remotes/origin/wip` have you tried just setting ref to `ref: wip` ? Not sure if this will help  but maybe

**Comment by javamonkey79** [comment]
@hmike96 yes, when I set it to `ref: wip` it actually failed. I will try changing it to master and see if the issue is specific to it.

**Comment by javamonkey79** [comment]
@hmike96 I've confirmed it works with master; so, it appears to be an issue related to using a branch\ref. I can open an issue for this?

**Comment by hmike96** [comment]
@javamonkey79 Yeah I will put up the fix up hopefully by this weekend. tag me in issue just to remind. thanks :) and sorry for trouble

**Pull request merged**
