### PR TITLE
WIP feat(commons): add commons chart

### PR DESCRIPTION
**Pull request by technosophos**
This chart contains lots of common stuff, including template
partials for frequently used kinds, and template macros for frequently
used pieces of calculated information.

### CODE REVIEW

**Comment by sebgoa** [comment]
@technosophos do you still want this in ?

**Comment by chrislovecnm** [comment]
@technosophos tests are failing, and do you want this merged or do you want to close this?  @viglesiasce this is tied to an internal link for the build, so I cannot see why it has failed.

**Comment by chrislovecnm** [comment]
Bump

**Comment by prydonius** [comment]
@technosophos I'd like to keep this somewhere as it's a great example of using templates, but it doesn't fit in this repository. Do you think this would be a better fit in the Helm repo's docs folder?

**Comment by technosophos** [comment]
I am going to pull this into its own repo and close the PR

**Comment by technosophos** [comment]
This is now in its own repo here: https://github.com/technosophos/common-chart

**Pull request closed without merging**
