### PR TITLE
[stable/prometheus] Added configmapReload.enabled parameter (#20578)

### PR DESCRIPTION
**Pull request by Adri2000**
Signed-off-by: Adrien Cunin <adrien.cunin@springernature.com>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Adri2000 
Please bump the chart to latest version. Thank you.

**Comment by Adri2000** [comment]
Pull-request updated, HEAD is now b1b8f8c229b62180d377db16c790f187e48f681b

**Comment by Adri2000** [comment]
Pull-request updated, HEAD is now cef38124352d1d8fe22d671324bd2036730be917

**Comment by Adri2000** [comment]
@zanhsieh done.

I also added another - related - change to allow to independently configure the configmapReload containers for Prometheus and Alertmanager.

(As an example, I need this while using Prometheus and Thanos, where the Thanos sidecar container handles the config reload for Prometheus, so I want to disable only the configmapReload container for Prometheus.)

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Adri2000 
Would you mind to rebase 10.5.2 as well as adding '[stable/prometheus]' in front of this PR title please?

I admit I accidentally click 'Done' button due to not seeing this PR title. Sorry about that.

**Comment by Adri2000** [comment]
Pull-request updated, HEAD is now f714c4311af14331eb989e37cc4e3aaca7bf3378

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@Adri2000 
Sorry. There's still some file conflicting (see the bottom of this PR). Once updated, I will lgtm ASAP.

**Comment by Adri2000** [comment]
Pull-request updated, HEAD is now 13541e54401ec3a277f8334150cfb6926e67bdc5

**Pull request merged**
