### PR TITLE
Add default function from chart template to check release name match

### PR DESCRIPTION
**Pull request by timm088**
**What this PR does / why we need it**:

When releasing these charts, service name will be prefixed with the release name, resulting in `name-name`. This also impacts DNS resolutions. 

**Special notes for your reviewer**:

From my research, looks like the default chart template was changed (i.e., when running helm create locally), this function was just not added here.

### CODE REVIEW

**Comment by timm088** [comment]
I have signed the CLA

**Comment by unguiculus** [comment]
Please create separate PRs per chart. Thanks.

**Comment by timm088** [comment]
Will do. Looks like the chart has been updated in the last < 1w for the consul chart also.
Will close this PR and then open again as seperate PRs

**Pull request closed without merging**
