### PR TITLE
update minio fullname with releaseName to prevent collision in naming

### PR DESCRIPTION
**Pull request by merlindorin**
Signed-off-by: merlin <romain.dary@renault.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@wlan0 can you take a look in this PR? thanks!

**Comment by wlan0** [comment]
Thanks for the PR @iam-merlin! 

While this PR is needed, it unfortunately has an issue when the release name does not contain the chart name. I'm sorry, but I'm cancelling this PR as it introduces the issue described here: https://github.com/helm/charts/pull/8349#issuecomment-442595444

I've created a new PR coupled with your changes, with a version bump of minio that includes critical security fixes.

**Comment by iam-merlin** [comment]
no pb, I close this one so

**Pull request closed without merging**
