### PR TITLE
[stable/jaeger-operator] Align resources with the latest jaeger-operator 1.14.0

### PR DESCRIPTION
**Pull request by qlikcoe**
This is a follow-up PR for the previous version bump. 

- Align resources with the latest jaeger-operator 1.14.0
- Fix a known issue described here: https://github.com/jaegertracing/jaeger-operator/issues/721

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
LGTM

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by qlikcoe** [comment]
@cpanato @batazor  Not sure why the test is failing. Seems like helm's issue when trying to delete the CRD.

**Pull request merged**
