### PR TITLE
[stable/traefik] Use unprivileged ports

### PR DESCRIPTION
**Pull request by pho-enix**
Don't use low ports because some k8s environments might not allow it.

Move:
http    80 -> 8080
https  443 -> 8443
dash  8080 -> 8000

Signed-off-by: Sebastian Poehn <sebastian.poehn@gmail.com>

#### What this PR does / why we need it:
Use high ports for `containerPort`. On some Kubernetes environments usage of low ports is not allowed due to security policies.

#### Which issue this PR fixes
* Use `containerPort` > 1024

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by dtomcej** [comment]
Hi @pho-enix, I am OK with the premise of this PR, however I have some suggestions:

1. To maintain backwards compatability, could we add a `useNonPriviledgedPorts` flag in the values that is false by default, to enable this change?
2. Modifying the default http entrypoint to 8080, then using a different port for the dashboard could be confusing configuration wise. Could I suggest using 6080 for http, 6443 for https, and then 8880 for httpn, and 8080 for the dashboard? This would keep things clearer as to what has been changed, and what remains the same?

Let me know what you think!

**Comment by pho-enix** [comment]
@dtomcej are you okay with the changes now? To prevent bloating the templates I put the port number logic to the _helper

**Comment by dtomcej** [comment]
@pho-enix, Good job!

Looks good!

Can you bump the version, and we can 🚢 this?

**Pull request merged**
