### PR TITLE
[incubator/solr] Fix language typos in the README

### PR DESCRIPTION
**Pull request by makuk66**
@ian-thebridge-lucidworks

#### Is this a new chart

This is only a README update, not a new chart

#### What this PR does / why we need it:

Makes it easier to read.

#### Which issue this PR fixes

No github issues.

#### Special notes for your reviewer:

As this is only a README update, I have not tested this PR, or bumped the version.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@makuk66 
Could you do a version bump please? Thank you.

**Comment by makuk66** [comment]
@zanhsieh Done. Also added some further fixes. Pardon the force push. Thanks.

**Comment by maorfr** [comment]
/lgtm

thanks!

**Pull request merged**
