### PR TITLE
[stable/kubernetes-dashboard] Upgrade to 1.10.1

### PR DESCRIPTION
**Pull request by desaintmartin**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
/do-not-merge
Docker image is not yet available.

**Comment by desaintmartin** [comment]
Strange that you can't lgtm, being a global owner...

**Comment by cpanato** [comment]
@desaintmartin not anymore

**Pull request merged**
