### PR TITLE
[stable/kubernetes-dashboard] add tests

### PR DESCRIPTION
**Pull request by s12chung**
#### What this PR does / why we need it:

adds tests to stable/kubernetes-dashboard

#### Which issue this PR fixes
No issue, adds new test and ci test cases.

#### Special notes for your reviewer:
Only works for `rbac.clusterAdminRole: true` because `k8s.gcr.io/kubernetes-dashboard-amd64` attempts to create resources in `kube-system` and I didn't want to create RBAC roles just to test things.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
thanks!
/ok-to-test

**Comment by desaintmartin** [comment]
You know what to do. ;)

**Comment by s12chung** [comment]
wierd. worked locally on my kind cluster. i'll take another look...

**Pull request closed without merging**
