### PR TITLE
[stable/airflow] depreciate chart

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR puts up a notice for the new chart repo

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@gsemet can you please review?

**Comment by gsemet** [comment]
do you have tested if we still publish to the same google repository ? won't we need to describe what change for users?

**Comment by thesuperzapper** [comment]
@gsemet that Google repository is being deleted?

What do you mean?

**Comment by gsemet** [comment]
when we move the chart source to our group, what do the users need to do to continue to use the new chart versions?

**Comment by thesuperzapper** [comment]
@gsemet because all helm does is generate YAML, all that users need to do is start using the new chart.

**Comment by gsemet** [comment]
I didn't tried, but you can have a running instance (pointing to https://kubernetes-charts.storage.googleapis.com) and move to the new location? Or is still building to https://kubernetes-charts.storage.googleapis.com for the moment?

**Comment by thesuperzapper** [comment]
@gsemet a few points:
* `https://kubernetes-charts.storage.googleapis.com` it is being replaced with `https://charts.helm.sh/stable`, but only for the ARCHIVE of versions from THIS repo, nothing new will be added to `https://charts.helm.sh/stable` after November 13, 2020
* Our new repo is `https://airflow-helm.github.io/charts`, see our new docs: https://github.com/airflow-helm/charts/tree/main/charts/airflow

Any migration guide should live in the new repo anyway, so I think its safe to merge this PR ASAP, so people don't continue using the soon-to-be-archived chart.

**Comment by gsemet** [comment]
that's good to me

/lgtm

**Pull request merged**
