### PR TITLE
[stable/fluent-bit] Add support for `Exclude_Path`

### PR DESCRIPTION
**Pull request by lsowen**
#### What this PR does / why we need it:

In some situations files which match the `Path` configuration for
the "Tail" input plugin should _not_ be parsed.  `fluent-bit`
supports this via the `Exclude_Path` configuration variable, so
this commit allows setting this variable in the chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lsowen** [comment]
@kfox1111 or @edsiper, when you get a chance...

**Comment by kfox1111** [comment]
in your values file, you can add whatever extra config you want already like:

```yaml
extraEntries:
  input: |
    Exclude_Path    <whatever>
```

No need for the patch.

**Comment by lsowen** [comment]
ha, nice, not sure how I missed that.  Thanks!

**Comment by kfox1111** [comment]
Any time. 

Its pretty new.

Have a good one. :)

**Pull request closed without merging**
