### PR TITLE
[stable/prometheus] Add myself to OWNERS

### PR DESCRIPTION
**Pull request by zanhsieh**
Signed-off-by: Mingchin Hsieh <zanhsieh@gmail.com>

Base on https://github.com/helm/charts/issues/13867

#### Special notes for your reviewer:
@mgoodness would like to step down as in kubernetes slack private chat and #chart channel. See:
https://kubernetes.slack.com/archives/C6E3XH1ED/p1573240846209800

(Truly sorry for bothering him so many times)

cc: @gianrubio 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Hm... can anything be done to get this in? I assume a repo owner will have to approve and merge this.

**Comment by zanhsieh** [comment]
@Vlaaaaaaad 
You might buzz @maorfr or any helm member to override it.

**Pull request merged**
