### PR TITLE
[stable/prometheus-operator]: fix disabling of default prometheus rule in rules-1.14

### PR DESCRIPTION
**Pull request by bzon**
…t created if disabled

#### What this PR does / why we need it:

Ensure rules-1.14 Prometheus rule is not created `defaultRules.rules.prometheus` is `false`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by bismarck — CHANGES_REQUESTED** [review]
@bzon unfortunately the file you edited is generated.  I believe the bug in the script that generates this file is [here](https://github.com/helm/charts/blob/master/stable/prometheus-operator/hack/sync_prometheus_rules.py#L72).  If you update that key to `prometheus` instead of `prometheus.rules`, that should add the missing condition.  Do you mind updating this PR?

**Comment by bzon** [comment]
@bismarck hmm I'm not sure how to update it but I don't mind if someone can update it. :)

**Comment by bismarck** [comment]
@bzon Looks like the underlying issue was fixed in #19335

**Pull request closed without merging**
