### PR TITLE
[ark] create service

### PR DESCRIPTION
**Pull request by gianrubio**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ X] Chart Version bumped
- [X ] Variables are documented in the README.md

### CODE REVIEW

**Comment by sebastien-prudhomme** [comment]
@gianrubio perharps using "metrics.enabled: true" is a better option? I see a lot of chart that are using that kind of convention.

**Comment by gianrubio** [comment]
@davidkarlsen please review it

**Comment by gianrubio** [comment]
closing as duplicate of #9496

**Pull request closed without merging**
