### PR TITLE
Use ConfigMap for mongo configuration

### PR DESCRIPTION
**Pull request by zonorti**
* For more fine-grained control on MongoDB configuration moving mongod.conf to ConfigMap from the container.
* To have the container more lightweight - switching to alpine. Should be enough for running bash scripts.
* ReplicaSet and ClusterRole added as values for easier multi-shard cluster creation. Also added as labels for discovery purpose.

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@foxish can you take a look at this one? The image is not currently pushed either so once if it looks good can you go ahead and push it?

Also keep in mind currently:
https://github.com/kubernetes/charts/issues/242

**Comment by foxish** [comment]
@viglesiasce I'll take a look at it today and push the image as well. Thanks!

**Comment by foxish** [comment]
Merge conflicts need to be fixed? @iMelnik

**Comment by viglesiasce** [comment]
Thanks @foxish! 

@iMelnik the chart changed to the mongodb-replicaset folder so the files will need to be moved.

**Comment by zonorti** [comment]
@foxish @viglesiasce sure, I would update this PR

**Comment by zonorti** [comment]
@k8s-bot e2e test this

**Comment by zonorti** [comment]
@foxish this e2e fail looks like a Jenkins problem
or is there something to fix?

**Comment by foxish** [comment]
@k8s-bot e2e test this

**Comment by foxish** [comment]
The change LGTM. I'm trying to deploy it once but helm seems to have issues when I have a cluster spun up using Kubernetes release-1.5.

**Comment by foxish** [comment]
> W1124 01:47:10.109] Error: release mongodb-246 failed: Namespace "pr-master:14bee1e456c1789d1ebdfc2dc7e3ae2b9ea930ce,223:a5e1b12e9605de227f330a40a3dedcd5f1e5c6c2-246" is invalid: [metadata.name: Invalid value: "pr-master:14bee1e456c1789d1ebdfc2dc7e3ae2b9ea930ce,223:a5e1b12e9605de227f330a40a3dedcd5f1e5c6c2-246": must be no more than 63 characters, metadata.name: Invalid value: "pr-master:14bee1e456c1789d1ebdfc2dc7e3ae2b9ea930ce,223:a5e1b12e9605de227f330a40a3dedcd5f1e5c6c2-246": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')]


@viglesiasce This looks like an e2e testing framework issue. Any ideas why it's picking a large garbled namespace to deploy?

**Comment by viglesiasce** [comment]
@foxish looks like something has changed on the Jenkins side. The ghprbPullId is now showing as that rather than the PR Id. Will look today.

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
Opened https://github.com/kubernetes/test-infra/issues/1202

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
Opened https://github.com/kubernetes/test-infra/issues/1253, sorry for the churn folks.

**Comment by spxtr** [comment]
@k8s-bot e2e test this

**Comment by zonorti** [comment]
@viglesiasce thanks for checking tests!

**Comment by viglesiasce** [comment]
@foxish can you push the image when you get a chance?

**Comment by foxish** [comment]
@viglesiasce On it

**Comment by foxish** [comment]
> gcr.io/google_containers/mongodb-install:0.3
> 0.3: digest: sha256:46d232cd66435c4ed0565818a45c326b00fa95fe65af171400fc0501b1cd578f size: 1157
> 

Done.

**Comment by foxish** [comment]
I still can't test this. 
Is there an issue with running helm on the latest master/HEAD?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.986+a2d5df40af698a", GitCommit:"a2d5df40af698a801556f4524a2642e37001e0bb", GitTreeState:"clean", BuildDate:"2016-12-01T21:11:03Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.986+a2d5df40af698a", GitCommit:"a2d5df40af698a801556f4524a2642e37001e0bb", GitTreeState:"clean", BuildDate:"2016-12-01T21:08:51Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm init
$HELM_HOME has been configured at $HOME/.helm.
Warning: Tiller is already installed in the cluster. (Use --client-only to suppress this message.)
Happy Helming!

$ helm version
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}

$ helm install mongodb-replicaset/
Error: transport is closing

$ helm install mongodb-replicaset/
Error: could not find a ready tiller pod

$ helm version
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Error: cannot connect to Tiller

```

**Comment by viglesiasce** [comment]
I am able to install on a 1.4.x cluster but seeing the following in the `bootstrap` init container:
```
2016/12/02 06:48:16 lookup smelly-indri-mongodb-rep on 10.19.240.10:53: server misbehaving
2016/12/02 06:48:17 lookup smelly-indri-mongodb-rep on 10.19.240.10:53: server misbehaving
```

**Comment by zonorti** [comment]
I guess it makes sense to wait till 1.5 release and have it updated at that time

**Comment by foxish** [comment]
@iMelnik I made a couple of changes to your PR, to work with StatefulSets in k8s1.5. I see the same issue as @viglesiasce did with the bootstrap container. PTAL.

**Comment by foxish** [comment]
@iMelnik @viglesiasce Pushed commit to fix the issue with bootstrap. It works well on my local setup.
The only update needed is to test.sh, to change the name of the pod from `mongodb-` to `mongodb-rs-`.

This is ready for merge once that change is made.

**Comment by viglesiasce** [comment]
Awesome stuff. Thanks @iMelnik and @foxish!!!

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by foxish** [comment]
@viglesiasce We're not testing on a 1.5 cluster yet? I updated the reference to StatefulSet and that seems to be why it's failing.

**Comment by viglesiasce** [comment]
Correct. We will move to 1.5 once GKE has it ready. Until then we wont block this (or other SS prs). Once CI is pointing to 1.5 I will send a PR to move this to the stable folder.

**Comment by zonorti** [comment]
@viglesiasce @foxish thanks for updating and megring this one!
I've managed to build one with auto restoring mongo from snapshot, ping me if you think that is worth being public

**Pull request merged**
