### PR TITLE
[stable/kubernetes-dashboard] Upgrade to 1.10.0

### PR DESCRIPTION
**Pull request by desaintmartin**
**What this PR does / why we need it**:

Upgrade kubernetes-dashboard to 1.10.0.

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @kfox1111

**Comment by kfox1111** [comment]
lgtm

**Comment by lachie83** [comment]
Please add the DCO to the commit message - https://www.helm.sh/blog/helm-dco/index.html

**Comment by desaintmartin** [comment]
Done.

**Pull request merged**
