### PR TITLE
[stable/kibana] Fix for issue with resources not working when specifying extra container

### PR DESCRIPTION
**Pull request by Towmeykaw**
Signed-off-by: towmeykaw <tkindmark@gmail.com>

Fixes issue raised in PR #7298 where resources and volumemounts will dissapear when using extracontainers

### CODE REVIEW

**Comment by johnmarcou** [comment]
Hi,

The line 151 needs to close the if plugin section before the extraContainer section.
Otherwise, we need to enable a plugin to be able to inject extra-Containers.

Thx

**Comment by Towmeykaw** [comment]
@johnmarcou  You are right. Made fixed it in a new PR

**Pull request merged**
