### PR TITLE
Added nodeSelector to Concourse worker

### PR DESCRIPTION
**Pull request by pontusarfwedson**
Pull request that adds an attribute `additionalSpec` to the `values.yaml`. Under that attribute, a developer can add whatever custom specs he/she wants which will get added into the statefulset template. This can be used to achieve node selection for the workers, otherwise impossible.

### CODE REVIEW

**Comment by pontusarfwedson** [comment]
cncf-cla: yes

**Comment by unguiculus** [comment]
Thanks for the PR. Thus is too coarse-grained. Please have a look what `helm create` does using Helm 2.8+ and follow that example.

**Comment by pontusarfwedson** [comment]
Alright, thanks for comment! I sort of like idea of having a completely customizable variable (to add anything you want to your pod spec) but for the case of nodeselector I know replaced it as helm create does.

**Comment by william-tran** [comment]
@pontusarfwedson In the [k8s 1.7 docs](https://v1-7.docs.kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity):

>`nodeSelector` continues to work as usual, but will eventually be deprecated, as node affinity can express everything that `nodeSelector` can express.

I'm citing the 1.7 docs because this is the oldest version that helm charts need to support. The chart already supports affinities through `.Values.worker.additionalAffinities` so I would not be in favour of accepting this PR; I don't want to add another feature to control this behaviour, which could complicate things and will eventually be deprecated.

**Review by william-tran — CHANGES_REQUESTED** [review]
See my previous comment. Is there another feature other than nodeSelector / affinity that you need to add?

**Comment by unguiculus** [comment]
@william-tran Affinity and node selectors are different things. It is very common to have both. This is also what `helm create` does.

**Comment by pontusarfwedson** [comment]
@william-tran @unguiculus So I guess we/you need to chose if we should "adhere" to Helm or to Kubernetes. I agree that we can achieve node selection through affinity,  but if the newest version of Helm believes both are useful, than perhaps thats motivation enough?

**Comment by william-tran** [comment]
It doesn't make sense to add support for something that will be deprecated, but if `nodeSelector` satisfies the majority of use cases, and is simpler, then maybe the usability of that today outweighs the loss of that usability in the future when k8s drops support for `nodeSelector`. I think this is something the helm folks should provide some clarity on, given an existing issue for adding nodeSelctor to charts: #1899

**Comment by unguiculus** [comment]
I wasn't aware that node selectors will be deprecated. Anyways, they have been added to many charts, so people seem to want them. If you don't want them, that's fine for me.

**Comment by viglesiasce** [comment]
I say lets add whats easy for users today via a nodeSelector value in the values.yaml. When it gets deprecated in K8s we can translate the nodeSelector into whatever is required to achieve the same thing with node affinity.

**Review by william-tran — APPROVED** [review]

**Comment by william-tran** [comment]
Seems I can't `/ok-to-test` but I'm ok with adding `nodeSelector`, and its default value won't break anyone current using affinities.

**Pull request merged**
