### PR TITLE
[stable/postgresql] Added ability to set the NodePort for the postgresql chart.

### PR DESCRIPTION
**Pull request by cravall**
What it says on the tin basically.

CC @swordbeta @databus23

### CODE REVIEW

**Comment by cravall** [comment]
@foxish - did you have a chance to review this?

**Comment by foxish** [comment]
@swordbeta @databus23 can you do a review?
My concern here is that it needs some additional documentation as well. The nodeport usually needs to be in a particular range for this to work, and that's a cluster level parameter.

**Comment by unguiculus** [comment]
@foxish This is a common pattern in many charts. The config table in the readme lists it. I'd say that's all we need. We don't have to repeat Kubernetes docs here.

**Pull request merged**
