### PR TITLE
Add OWNERS file to doc reqs

### PR DESCRIPTION
**Pull request by lachie83**
Adding OWNERS to doc requirements.

### CODE REVIEW

**Comment by unguiculus** [comment]
So far we haven't required OWNERS files. They only make sense for members of the org. Should we still require them for new charts?

**Comment by lachie83** [comment]
@unguiculus I think we should make it a requirement. They can approve the PR without being in the k8s org right?

**Comment by mattfarina** [comment]
OWNERS files only work if you're a member of the k8s org.

**Pull request closed without merging**
