### PR TITLE
Fix fluentd-elasticsearch doc

### PR DESCRIPTION
**Pull request by jorge07**
**What this PR does / why we need it**:
Impossible to read the config table

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: None

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
Thanks for your pr! I believe the `circleci` build is failing, because you need to bump the `version` to 0.6.1 in `Chart.yaml`. Its a bit confusing, but even documentation fixes require bumping the version number.

**Comment by jorge07** [comment]
Done @mattjmcnaughton 👍

**Review by mattjmcnaughton — APPROVED** [review]
LGTM!

**Comment by monotek** [comment]
Already fixed with: https://github.com/kubernetes/charts/pull/6067/

**Pull request closed without merging**
