### PR TITLE
Added new aws-xray chart

### PR DESCRIPTION
**Pull request by okgolove**
Signed-off-by: Mikhail Naletov <okgolove@markeloff.net>

#### What this PR does / why we need it:
* It makes easier to use AWS X-Ray tracing system in Kubernetes

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by okgolove** [comment]
I'd like to get a review, please
@scottrigby

**Comment by excavador** [comment]
What the status of the issue?

**Comment by okgolove** [comment]
@excavador I hope somebody somewhen will take a look to the PR :)

**Comment by maorfr** [comment]
/unassign @scottrigby 
/unassign @paulczar 
/unassign @cpanato 

Hey @okgolove,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by okgolove** [comment]
@maorfr hello! No, I haven't. Should we do it? What should I do to do it?

**Comment by maorfr** [comment]
So many questions :)

I think that you totally should host your own charts!
This will give you more freedom around management, and you will not be blocked by us (maintainers).

This means that when users want to install your chart, instead of installing them from `stable`, they will install it from (for example) `mycompany-charts`:
```
$ helm install --name my-release mycompany-charts/mychart
```

Here are some instructions about how to host your own charts repo:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

In order for people to find out about your charts repo, you should add it to helm hub:
https://hub.helm.sh/

Here are some instructions about how to add your charts repo to helm hub:
https://github.com/helm/hub#how-to-add-your-helm-charts

Hope that answered all your questions! :)

**Comment by okgolove** [comment]
@maorfr thank you! This is because I create a lot of PRs? :)
Should I close this one?

**Comment by maorfr** [comment]
This is because this is the path forward. As in, this is why helm hub was created :)
And if you intend to host your own charts, then yes, you can close this PR :)

**Comment by okgolove** [comment]
@maorfr got it. Thank you for the feedback.
May be this is not a best place to ask it but: how to become a read-only member in helm/charts?

**Comment by maorfr** [comment]
are you maintaining any charts?

**Comment by okgolove** [comment]
At least two:
https://github.com/helm/charts/tree/master/stable/prometheus-nats-exporter
https://github.com/helm/charts/tree/master/stable/goldpinger

**Comment by maorfr** [comment]
so as i see it, we have 2 options:

1. you can host these charts along with aws-xray and [deprecate](https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart) them from `stable`.
2. i can add you as read only user.

i would go with 1. what do you think?

**Comment by okgolove** [comment]
As far as I see somebody has already used goldpinger chart (there was the PR you merged before). So, if it's possible, I'd like to become a read only user and proceed maintaining those two charts. And I'm going to close this PR and move it to my own repo.

**Comment by maorfr** [comment]
Done.

**Comment by okgolove** [comment]
@excavador you can find the chard here https://hub.helm.sh/charts/okgolove/aws-xray

**Pull request closed without merging**
