### PR TITLE
[stable/spinnaker] Template Annotations for Spinnaker HAL Cleanup Job

### LINKED ISSUE #20046: [stable/spinnaker] Template Annotations for Spinnaker HAL Cleanup Job
This feature request is related to #12354. It's about adding support for custom annotations for the Spinnaker HAL cleanup job. Our use-case is not directly related to the usage of [jtblin/kube2iam](https://github.com/jtblin/kube2iam) but rather the usage of a service-mesh (e.g. [istio/istio](https://github.com/istio/istio)) to add annotations to skip the automatic injection of the service mesh sidecar as Kubernetes jobs might not terminate correctly without it (https://github.com/istio/istio/issues/11045#issuecomment-455780604), i.e.

```yaml
halyard:
  annotations:
    sidecar.istio.io/inject: "false"
```

I believe adding the functionality to the cleanup job was perhaps missed in #12354 as there is no use for a kube2iam annotation for this job as the cleanup job is mostly concerned with terminating the Spinnaker deployments. Anyways I hope the actual use for it is clear with this service mesh example.

**Is your feature request related to a problem? Please describe.**
Right now the Spinnaker HAL Cleanup job is not terminating correctly after a successful run due to the automatically attached Service Mesh sidecar ([Istio - Automatic Sidecar Injection](https://istio.io/docs/ops/configuration/mesh/injection-concepts/)). This causes any Helm Chart changes to hang/timeout and ultimately fail.

**Describe the solution you'd like**
I would like to add an annotation to the pod template of the job to prevent the automatic Istio sidecar injection process, e.g.

```yaml
halyard:
  annotations:
    sidecar.istio.io/inject: "false"
```

Future versions of Kubernetes might handle the issue of sidecar container termination for Kubernetes Jobs better: https://twitter.com/stefanprodan/status/1193937986121084928 but I believe annotation capabilities are still relevant.

**Describe alternatives you've considered**
I did not consider alternatives as this exact approach was already implemented for the other Halyard components in #12354 and I believe it should also be implemented for the HAL cleanup job.

**Additional context**
Related ticket: #12354

### PR DESCRIPTION
**Pull request by nagelflorian**
#### What this PR does / why we need it:

Fixes an issue related to the correct termination of the Spinnaker HAL cleanup job like described in #20046. I believe adding the annotation templating capability for this job was missed in #12355.

#### Which issue this PR fixes

- fixes #20046

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by nagelflorian** [comment]
@viglesiasce @ezimanyi @dwardu89 any chance we can merge this soon (the related ticket #20046 is already marked as stale)? Is there any way I can help? I am sure you're all busy, so even a small update is greatly appreciated.

**Review by dwardu89 — APPROVED** [review]

**Pull request merged**
