### PR TITLE
added me to prometheus-nats-exporter/OWNERS

### PR DESCRIPTION
**Pull request by caarlos0**
(template not applicable it seems)

refs https://github.com/helm/charts/issues/13867#issuecomment-499084668

cc/ @okgolove

### CODE REVIEW

**Comment by okgolove** [comment]
Bump chart version :)

**Comment by caarlos0** [comment]
@okgolove btw, just noticed we are not using the official docker images https://github.com/nats-io/prometheus-nats-exporter/releases

**Comment by okgolove** [comment]
@caarlos0 I didn't know about the official image.
We definitely should switch to it.

**Comment by caarlos0** [comment]
> @caarlos0 I didn't know about the official image.
> We definitely should switch to it.

cool, will do a PR :)

**Pull request merged**
