### PR TITLE
[stable/home-assistant] Fixes typo in README

### PR DESCRIPTION
**Pull request by MathildeLeroi**
Signed-off-by: Mathilde Leroi <mathilde.leroi@gmail.com>

#### What this PR does / why we need it:
It fixes a typo in the README

### CODE REVIEW

**Comment by billimek** [comment]
Hi @MathildeLeroi can you please bump the chart version (probably to `0.12.4`) in the `Charts.yaml` file, in order for linting to pass?

**Comment by MathildeLeroi** [comment]
Hi @billimek, I just updated the PR accordingly

**Review by billimek — APPROVED** [review]

**Pull request merged**
