### PR TITLE
Fix typo and whitespace

### PR DESCRIPTION
**Pull request by ketan**

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@ketan can you sign off you commits and bump the chart version please? TIA
https://www.helm.sh/blog/helm-dco/index.html

**Comment by ketan** [comment]
@davidkarlsen — ammended that original commit to add DCO. Added a second commit to bump version. Let me know if anything else is needed.

**Review by GaneshSPatil — APPROVED** [review]

**Pull request merged**
