### PR TITLE
[stable/prometheus] allow for relabeling in the apiserver ServiceMonitor

### PR DESCRIPTION
**Pull request by acondrat**
#### What this PR does / why we need it:
This allows fixing the ServiceMonitor for API Server in case endpoint address is not reachable (as in AKS)

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by acondrat** [comment]
@gianrubio I bumped the version as tests failed. Can you please have a look and `lgtm` again if it is fine.

**Comment by acondrat** [comment]
@gianrubio any updates on this, please?

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by acondrat** [comment]
@gianrubio I had to bump the version again, so a new lgtm required.

Thanks!

**Comment by vsliouniaev** [comment]
@acondrat Since there are many PRs open it will probably take a bit of time to make sure they all get the chart version bumps appropriately. I will check back in regularly and if the PR is mergeable according to the chart version requirement I'll merge it.

**Comment by acondrat** [comment]
@vsliouniaev I agree, the process is not very straightforward. I've been trying to get this merged for two weeks!
I think it would be better if we don't bump version in the PR. Chart maintainers could handle the release process in master branch.

**Comment by vsliouniaev** [comment]
@acondrat that is not possible to do - I don't have rights to do the changes you suggest.

**Pull request merged**
