### PR TITLE
[stable/datadog] Change to use specified port instead of default

### PR DESCRIPTION
**Pull request by deiga**
#### What this PR does / why we need it:

The Chart default port for metrics-api Service was changed, but this Resource uses k8s default port of 443

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vboulineau** [comment]
Hello @deiga. Thanks for this fix, you need to sign your commits `git commit -s`, lgtm otherwise

**Comment by deiga** [comment]
@vboulineau Ah, yes. Done :)

**Pull request merged**
