### PR TITLE
[stable/keycloak] Update to Keycloak 4.2.1.Final

### PR DESCRIPTION
**Pull request by thomasdarimont**
cc @unguiculus @nexeck 

**What this PR does / why we need it**:
Updates the Keycloak chart to the latest final version.

**Special notes for your reviewer**:
Manually tested the chart with the postgresql database option.

### CODE REVIEW

**Comment by thomasdarimont** [comment]
Just singed the CLA

**Comment by styk-tv** [comment]
This should not be merged until "unable to login" is solved. This needs to be merged in to solve. I confirmed after 6444 is applied login works fine.

https://github.com/helm/charts/pull/6444

https://github.com/helm/charts/issues/6851

**Pull request merged**
