### PR TITLE
[stable/contour] fix replica count conflict

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### What this PR does / why we need it:
cc @scottrigby 
affects helm3 managed releases.
Please see #19008 for more info

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pickledrick** [comment]
Hi, @naseemkullah Thanks for the PR!

Are you able to create an issue and provide a little context into the problem and make a reference as a comment here?

**Comment by naseemkullah** [comment]
Hi @pickledrick, no problem, sure:

> Helm 3's 3-way strategic merge strategy is a huge improvement, and is the correct way to go. However it uncovered that one use case for the incorrect behavior in Helm 2 actually had a nice outcome: HPA-scaled replicas were untouched on helm upgrade, whereas Helm 3 now sets the replicas back to the values/template-defined number of replicas.

**Review by poidag-zz — APPROVED** [review]
/approve

**Pull request merged**
