### PR TITLE
Add source for docker image

### LINKED ISSUE #11046: [stable/fluentd] Source for docker image not included
**Is this a request for help?**:
Yes
---

The contribution guidelines technical requirements include the following:
> Must include source GitHub repositories for images used in the Chart

stable/fluentd chart has links to sources in Chart.yaml, but these are not the source of the image that is used in the chart. I would like to contribute to extending this image to include other plugins but the sources listed don't seem to produce an image that works with the chart.

Where can I find the source of the image used for stable/fluentd so that I can contribute to extending it, or fork for a different plugin config?

### PR DESCRIPTION
**Pull request by dshackith**
The existing sources do not produce an image that works with this chart. From what I can tell, the image was built from the fluentd-es image maintained in the Kubernetes repo.

#### What this PR does / why we need it:
@rendhalver This adds the source for the docker image in the source section of the Chart. Existing list does not point to repos that can be used to produce an image that works with this chart. This is the image also used for stable/fluentd-elasticsearch
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #11046

#### Special notes for your reviewer:
If this is not the source, please update with correct source.
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

### CODE REVIEW

**Comment by cpanato** [comment]
@dshackith please sign the DCO and bump the chart version

**Comment by dshackith** [comment]
Signed and bumped chart version. I have another PR waiting in the wings once this one is approved.

**Pull request merged**
