### PR TITLE
typo fixed in REVIEW_GUIDELINES.md

### PR DESCRIPTION
**Pull request by iamrajiv**
#### What this PR does / why we need it:
Fixes small typo and grammatical mistakes in `REVIEW_GUIDELINES.md`. This PR improves the quality of Documentation.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@iamrajiv thanks for the PR, please sign the DCO

**Comment by iamrajiv** [comment]
@cpanato how to sign DCO since I have made this PR and commit directly not by git bash shell

**Comment by iamrajiv** [comment]
@cpanato how to sign DCO since I have made this PR and commit directly not by git bash shell so how to amend the commit

**Comment by cpanato** [comment]
@iamrajiv you can do this `git commit --amend --signoff` and the push again

**Pull request merged**
