### PR TITLE
[incubator/kafka]: add reassignPartitions to topic configuration

### PR DESCRIPTION
**Pull request by giacope**
**What this PR does / why we need it**:

The only way to increase the replication factor of an existing topic, is by reassigning partitions. This PR adds a new field to the topic configuration values: `reassignPartitions`. When this value is set to `true`, the `kafka-config-job` will reassign partitions and increase the replication factor of an existing topic. Both `partitions` and `replicationFactor` need to be specified as well.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@benjigoldberg is this ok to merge?

**Comment by giacomoguiulfo** [comment]
@benjigoldberg (cc @davidkarlsen) 
The PR needed a bump in the chart version in order to pass CI. So, I just did that and also decided to do a minor version bump (from 0.9.6 to 0.10.0) since this is a feature rather than a patch. But let me know if you guys prefer just a "patch" to `0.9.7`.

**Comment by benjigoldberg** [comment]
Thanks @giacomoguiulfo -- apologies for the delay on merging this.
/lgtm

**Comment by vanto** [comment]
Wouldn't it be better to move the if statement from the template to runtime? Currently, if the reassignPartitions flag is set, non-existing topics are not created anymore. What about changing the script to the following behaviour:

1. check if topic exists. If no, create and return. If yes:
2. check if reassignPartitions flag is set. If no, return, if yes, do the assignment.

WDYT?

**Comment by giacomoguiulfo** [comment]
@vanto If it works, it sounds good to me. I agree this is not the best way to do things.

**Pull request merged**
