### PR TITLE
Add linting for charts

### PR DESCRIPTION
**Pull request by viglesiasce**
Adding back linting for changed charts in PRs. Updates to follow for adding back the functional tests.

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot test this

**Comment by sebgoa** [comment]
technically all scripts should have the ASL license header in them....

**Comment by viglesiasce** [comment]
@runseb added headers to the shell scripts. Does Dockerfile need it too?

**Comment by sebgoa** [comment]
the copyright is actually with:

Copyright 2016 The Kubernetes Authors All rights reserved.

Personally, I think it is good practice to put it everywhere (and that's what the license says)

Also technically I don't think you need to put maintainers in Dockerfile and Charts as the maintainers are the folks with write access to repo. History is in git....but again that's my take.

**Comment by sebgoa** [comment]
+1

**Comment by sebgoa** [comment]
the Dockerfile could be optimized a bit...

so can you merge yourself ? let me know in not, happy to do it for you.

**Comment by viglesiasce** [comment]
Merged. Would love to see the optimizations. I'm out for tonight but will check back tomorrow morning.

**Pull request merged**
