### PR TITLE
[stable/jenkins] Add OWNERS file in .helmignore

### PR DESCRIPTION
**Pull request by yanc0**
`OWNERS` file is only useful for development and contributing workflows but it is added in the chart anyway. Fix that.

**What this PR does / why we need it**:
Ignore `OWNERS` file in packaged chart

Referenced in https://github.com/weaveworks/multienv-example/pull/3

### CODE REVIEW

**Comment by Nodraak** [comment]
Hi

Please rebase your PR and bump the chart version (in Chart.yaml)

**Comment by unguiculus** [comment]
Something must have gone wrong here. This adds lots of unrelated changes. Also, in general, we want to have separate PRs per chart.

**Comment by yanc0** [comment]
Yes, it seems that something went wrong. I completely broke my PR. What should I do? Restart a new PR and cherrypick my commit?

I think we can close this one. I will recreate a new one.

**Comment by Nodraak** [comment]
Maybe if you `git rebase origin/master` it will clean up things. Otherwise, creating a new PR + cherry picking will indeed solve it

**Pull request closed without merging**
