### PR TITLE
concourse: Add annotations for web deployment

### PR DESCRIPTION
**Pull request by brianmartin**
**What this PR does / why we need it**:

This PR allows the annotations on concourse-web pods to be customized.

Our particular use case involves using Datadog for scraping Prometheus endpoints. This is configured via annotations the Datadog agent is watching for (see: [datadog docs](https://docs.datadoghq.com/agent/prometheus/#auto-discovery)).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by brianmartin** [comment]
(trigger CLA verification)

**Review by william-tran — CHANGES_REQUESTED** [review]
We have annotations support for the worker pods, is the intent to add the same support for the web pods? If so, the annotations need to be nested under `spec.template.metadata.spec.annotations`

**Comment by brianmartin** [comment]
@william-tran Yes! That's exactly the intent. I realize now, I may have overeagerly opened this PR. I need to look a little deeper at the worker pod annotations (thanks for the note!).

For example, I've done more basic templating following the `tolerations` example, but the worker `annotations` are likely a better example:

```
      annotations:
        {{- range $key, $value := .Values.worker.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
```
https://github.com/kubernetes/charts/blob/master/stable/concourse/templates/worker-statefulset.yaml#L18-L21

I'll post again here in the next day or so, once this is fully tested and in use in production on our side.

**Comment by unguiculus** [comment]
@brianmartin I fixed a few things for you.

**Comment by william-tran** [comment]
Thanks @unguiculus

**Comment by brianmartin** [comment]
Awesome, thanks @unguiculus!

**Pull request merged**
