### PR TITLE
[stable/weave-scope] Fix error messages by using new architecture

### LINKED ISSUE #3669: Weave scope running in eks throws error messages
## What you expected to happen?
I have installed scope using helm into an eks cluster. Everything seems to work fine but my logs get spammed with error messages from weave scope agent.

## What happened?
```
weave/weave-scope-agent-weave-scope-xkxx4[weave-scope-agent]: <probe> WARN: 2019/08/30 12:20:16.948717 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
```

## How to reproduce it?
Install weave scope using the helm chart with default values.

## Anything else we need to know?
aws eks cluster

## Versions:
weave-scope helm version: 1.1.2
weave-scope image version: tag: master-c99a5e6d
kubectl version 1.13

### PR DESCRIPTION
**Pull request by runningman84**
#### Is this a new chart
no

#### What this PR does / why we need it:
The old chart produces a lot of error messages. According to the weave scope devs this is caused by an old configuration. I have modified the Chart based on their recommendations.

#### Which issue this PR fixes
  - fixes https://github.com/weaveworks/scope/issues/3669

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by runningman84** [comment]
@fbarl @dholbach @bboreham is anybode able to review and merge this?

**Comment by bboreham** [comment]
(a) I’m not a maintainer in this repo. 
(b) I’ve never used helm. 

Taking that into account, this change looked good to me.

**Comment by runningman84** [comment]
@bboreham that's funny because your are listed as a maintainer in this repo.

Mabye you can just add a /approve here.

**Comment by dholbach** [comment]
@qiell tested this too.

/approve

**Pull request merged**
