### PR TITLE
[incubator/sparkoperator] Add webhookNamespaceSelector

### LINKED ISSUE #22433: [incubator/sparkoperator] Allow configuring webhook namespace selectors
**Is your feature request related to a problem? Please describe.**
In the current deployment template, there isn't a way to pass a `namespaceSelector` to the webhook although the flag is available in the source code [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/webhook/webhook.go#L117). 

**Describe the solution you'd like**
Add a variable to the `values` file and to the `deployment` template the will allow setting this flag

**Additional context**
See discussion here GoogleCloudPlatform/spark-on-k8s-operator#873

### PR DESCRIPTION
**Pull request by hagaibarel**
Signed-off-by: Hagai Barel <hagaibarel@gmail.com>

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file.
@yuchaoran2011 

#### What this PR does / why we need it:
Add webhook namespace selector option to allow the webhook to only operate on specific namespaces 

#### Which issue this PR fixes
  - fixes #22433 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by yuchaoran2011 — COMMENTED** [review]
Looks good. But let's change the version to `0.7.0` as this is not a bug fix.

**Comment by HagaiBarel** [comment]
Changed the version

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
