### PR TITLE
[stable/traefik] support /ping healthcheck with optional entrypoint

### PR DESCRIPTION
**Pull request by bazbremner**
It's possible to enable the /ping healthcheck before this change by
passing `--ping` as an additional command line flag, however that will
always be on the `traefik` entryPoint (port 8080 by default).

Update: as is the way, I discovered that it's possible to do `--ping.entrypoint=http` _after_ I opened this PR! Still, I think it'd be useful to parameterise this behaviour rather than having to split configuration between the config file and command line where avoidable.

If one wants to run the healthcheck on the same port as inbound
services, configuration file entries are required.

This commit adds that ability.

Set ping.enabled to get /ping on the traefik entryPoint (equivalent to
specifying `--ping` on the command line) or additionally set
ping.entrypoint to define which entryPoint /ping should appear on.

For example: to have /ping on port 80, ping.enabled should true _and_
ping.entrypoint should be 'http'.

Signed-off-by: Barrie Bremner <baz@barriebremner.com>

#### Which issue this PR fixes

Fixes (already closed with an alternate solution) #11125

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mazzy89** [comment]
+1 to this. Could we add also the configuration to configure the ping to a dedicated port like in here ? https://docs.traefik.io/configuration/ping/#enable-ping-health-check-on-dedicated-port

**Comment by bazbremner** [comment]
@mazzy89 The interaction between `[ping]` and the entryPoints feels like a more involved change - I'd be inclined to get this merged first, then consider extra logic around entryPoints later, I suspect it has a bigger impact than just ping as well.

Certainly my use case (and hence this PR) is just about using one of the currently available entryPoints.

**Comment by bazbremner** [comment]
Closing: probably redundant (at least for my use case) now that ping is enabled on the http entryPoint following https://github.com/helm/charts/pull/14845

**Pull request closed without merging**
