### PR TITLE
Fix a few typeos in stable/prometheus-operator/README.md

### PR DESCRIPTION
**Pull request by mpursley**
@gianrubio @vsliouniaev @gianrubio @vsliouniaev FYI

Signed-off-by: Matt Pursley <mpursley@gmail.com>

#### What this PR does / why we need it:

Just fixes a few typeos in the readme.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mpursley** [comment]
/assign @vsliouniaev 

btw, circleci failed because the version was not bumped.. but I'm not sure if it's worth bumping the version for this small update to stable/prometheus-operator/README.md

**Comment by vsliouniaev** [comment]
Thanks @mpursley!
Could you please fix the CI by bumping tye chart version?

**Comment by mpursley** [comment]
> Thanks @mpursley!
> Could you please fix the CI by bumping tye chart version?



> Thanks @mpursley!
> Could you please fix the CI by bumping tye chart version?

Ok, I bumped to "version: 4.3.4" in "stable/prometheus-operator/Chart.yaml" in a new commit.

**Pull request merged**
