### PR TITLE
[stable/mssql-linux] Added support for SQL Agent and loadBalancerIP

### PR DESCRIPTION
**Pull request by winromulus**
## What this PR does / why we need it:
Added support for SQL Agent and loadBalancerIP

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by winromulus** [comment]
Mentioning @thomasliddledba for review

**Comment by winromulus** [comment]
@maorfr Hi, can you have a quick look over this small PR, please?

**Comment by maorfr** [comment]
i just added @thomasliddledba as a trusted collaborator, lets give him a chance to accept and review

**Review by thomasliddledba — APPROVED** [review]
/lgtm

**Pull request merged**
