### PR TITLE
[stable/redis] Add option to supply extra arguments for metrics

### PR DESCRIPTION
**Pull request by mikeraimondi**
**What this PR does / why we need it**:
Adds option to pass extra arguments to the metrics binary. This is particularly useful for monitoring specific keys with `--check-keys`.

### CODE REVIEW

**Comment by carrodher** [comment]
@mikeraimondi as #6684 was merged some minutes ago, you need to update Chart.yaml in order to resolve the conflicts generated by the other PR.

**Comment by mikeraimondi** [comment]
@carrodher Chart.yaml is updated.

**Pull request merged**
