### PR TITLE
[incubator/zookeeper] v1.0: Revamp, add exporters, add chroots job

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it / Which issue this PR fixes** 

Related:
- https://github.com/kubernetes/charts/issues/3020#issuecomment-351753281  cc: @mattfarina 

**Special notes for your reviewers**:

- Please note that this PR drops the readme defaults table in favor of the hierarchal data structure that is values.yaml.

- Let me know what you want to see and I'll try to bring the PR in line with it.

Notable changes (not an exhaustive list):

- Breaks with current chart syntax, so bumps chart version to `1.0.0`.
- Adds job to create Zookeeper chroots.
- Adds (disabled by default) JMX Exporter and Zookeeper Exporter as sidecar containers
- Adopts present day Helm patterns WRT chart metadata.
- Avoids trying to flatten values.yaml into a lossy markdown table.
- Adds pod disruption budget.
- Take a more flexible stance on anti-affinity (to support use case of anti-affinity across both availability zone AND node).
- Upgrade to Zookeeper 3.4.10. (bumps to v3 of container image)
- Parameterize all ports in a lookup-friendly way (maps not slices).
- Standardize on environment variables for config (maps not slices) as that is what the container uses.
- **Parameterize most everything!** (even resources on exporters).
- Exporter ports use a regular suffix of `xp` to facilitate Prometheus "[scrape by port name](https://github.com/prometheus/prometheus/issues/3756#issuecomment-362266296)" jobs. 
- Add activeDeadlineSeconds setting.
- No longer set default `resources` per `helm create` guidance.
- Builds on the pattern established by: https://github.com/kubernetes/charts/pull/3844

Pinging maintainers/owners:
- @lachie83 
- @kow3ns

### CODE REVIEW

**Comment by ghost** [comment]
/assign @lachie83 

cc: @unguiculus

**Comment by tedmiston** [comment]
@josdotso This seems useful but the size makes it quite hard to tell what specific changes are made in the diff, especially with the deleted docs (seems like a complete rewrite?).  Have you given consideration to breaking up the atomic changes into several smaller PRs instead?

**Comment by ghost** [comment]
@tedmiston . I'm sorry about that. Much of this indeed was a complete rewrite.  I squashed some of the incremental changes because there was no frame of reference where the chart was usable in the interim commits.  Please do note that the base code for the rewrite came from #3844 so it's not entirely new.  I considered doing a far more incremental approach, but i wasn't confident I could go top to bottom of values.yaml without further breaking from the #3844 pattern.  

I'll definitely keep this in mind for next time, although I have a Kafka PR coming after this one which gives a similar treatment to Kafka.  The break from current Zookeeper pattern is why I opted for 1.0.0 version on this PR.

**Comment by tedmiston** [comment]
Totally makes sense.  I've got some local modifications beyond the stock Kafka and ZooKeeper charts, so trying to figure out how to reconcile those differences with this.

**Comment by unguiculus** [comment]
Thanks for this @josdotso. This looks great.

**Comment by unguiculus** [comment]
Let's give maintainers some more time to review.

**Comment by ghost** [comment]
@lachie83 @kow3ns .. Please let me know if you'd like any changes to this PR.  Thanks!

**Comment by ghost** [comment]
@unguiculus Please advise on next steps. Thanks!

**Comment by alexvicegrab** [comment]
This is a solid improvement on the current state of Zookeeper, would be great if this could be merged in the near future, so the community could make use of it.

**Pull request merged**
