### PR TITLE
[stable/tomcat] Added failureThreshold on livenessProbe and timeoutSeconds

### PR DESCRIPTION
**Pull request by mrestivill**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by glarfs** [comment]
I didn't change any code on pgadmin, I don't know why the system detect a failure there.

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
