### PR TITLE
[stable/jenkins] fix chart errors

### PR DESCRIPTION
**Pull request by kimxogus**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by torstenwalter** [comment]
@kimxogus could you rebase you branch and fix the version conflict, please?

**Comment by kimxogus** [comment]
@torstenwalter just rebased and fixed version conflict :)

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Comment by torstenwalter** [comment]
@kimxogus Thank you for the PR!

**Pull request merged**
