### PR TITLE
[stable/traefik] externalTrafficPolicy support

### PR DESCRIPTION
**Pull request by santinoncs**
externalTrafficPolicy denotes if this Service desires to route external
traffic to node-local or cluster-wide endpoints. "Local" preserves the
client source IP and avoids a second hop for LoadBalancer and Nodeport
type services, but risks potentially imbalanced traffic spreading.
"Cluster" obscures the client source IP and may cause a second hop to
another node, but should have good overall load-spreading.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by caarlos0** [comment]
dupe of #4353?

**Comment by carrodher** [comment]
You should increment chart version (`version`) in `Chart.yaml`

**Comment by krancour** [comment]
@santinoncs, thanks for the PR, however, I'm going to close this in favor of #4353. Although this PR was submitted first (by a very narrow margin), #4353 is closer to a complete / mergeable state.

/close

**Comment by santinoncs** [comment]
thanks!

**Pull request closed without merging**
