### PR TITLE
Allow kiam-write to send events to pods

### PR DESCRIPTION
**Pull request by jeckhart**
This is from https://github.com/uswitch/kiam/pull/174

Allow kiam-write to send events to pods so that kiam can send events to pods about authentication failures, expiry and others.

Without this permission the following will be seen in the kiam-server logs;

```'events "pod.156488d50955a61a" is forbidden: User "system:serviceaccount:kube-system:kiam-server" cannot patch events in the namespace "default"' (will not retry!)```

Signed-off-by: John Eckhart <johne@nearpod.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by jeckhart** [comment]
@pingles @uswitch/cloud Who is able to help push this through? Any chance you could take a look and put a /lgtm if all is well?

**Comment by lachie83** [comment]
Hey @jeckhart. I would be happy to get this merged but I forgot the Github UI don't sign-off commits. Yey! I can either force push the branch and squash the commits or you can then we can get this merged. How would you like to proceed?

**Comment by jeckhart** [comment]
No problem, I just rebased, updated the version in Chart.yaml, and force pushed!

**Comment by jeckhart** [comment]
Bump.

I think this needs a /lgtm from a committer/maintainer .

- John

**Pull request closed without merging**
