### PR TITLE
[stable/rabbitmq] enhance readiness-probe to handle pod restart

### PR DESCRIPTION
**Pull request by aggiefly**
#### What this PR does / why we need it:
When install rabbitmq chart with replica > 1, say 3, if delete the rabbitmq pods with sequence of 0,1,2.
When pods restart, pod 0 is up, and try to sync data from pod 3 (last terminated pod). But due to readiness-probe fails on pod 0, pod 1&pod 2 can't up. 
So it caused some kind of dead lock:
   pod 0 wait for pod 3 up to sync data (during this period 127.0.0.01:15672 is not accessible)
   pod 1 & pod 2 wait for pod 0 pass readiness-probe and up successfully.
As a result, rabbitmq pods can never be re-started.

To solve this issue, add some special handling for readiness-probe after pod restart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
This is not an appropriate solution. If you stop all Rabbitmq nodes simultaneously, Rabbitmq is explicitly not allowing it to start up in a different order to avoid data loss. If you don't care about data loss and prefer availability over data integrity, then you can choose to either set `forceBoot.enabled` to true or you can set `podManagementPolicy` to `Parallel` to start them all simultaneously.

**Comment by aggiefly** [comment]
It's kind of compromisation, to avoid race condiftion when podManagementPolicy is Parallel, and let rabbitmq sync data as possible.

**Comment by tompizmor** [comment]
Hi @aggiefly,

Thanks for the PR and sorry for the late response. Can you please resolve again the conflicts so this can be merged?

**Comment by aggiefly** [comment]
@tompizmor 
conflict resolved.

**Pull request merged**
