### PR TITLE
[stable/redis-ha] add custom init containers for redis server

### PR DESCRIPTION
**Pull request by cryptobioz**
### What this PR does / why we need it:

This PR adds support of extra initContainers for the Redis server.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@cryptobioz Can you give me a little context behind this change? I am not against it, but I really want to avoid making the chart anymore complicated then it really needs to be. 

I do wonder, is this a common chart practice? It seems sensible, I am just worried about the cascading effects this may have down the line.

@ssalaues What do you think?

**Comment by cryptobioz** [comment]
@DandyDeveloper In our use case, we must start Redis from a dump so we download it with an initContainer and then, configure the instance to use it.
I don't know if it's a common practice, the Prometheus Helm chart allows that for example and it can be very useful. What cascading effects do you have in mind that could be a problem?

**Comment by DandyDeveloper** [comment]
@cryptobioz Can you bump the chart version? Seems reasonable. 

My concern is more the effect of adding too many "niche" requirements and bloating the chart to the point where individuals wanting to use it find it too complicated to use. 

I think this is fine though.

**Comment by cryptobioz** [comment]
@DandyDeveloper Just rebased and updated the chart version.

**Pull request closed without merging**
