### PR TITLE
Set DISCOVERY_SERVICE to use local DNS instead of fully qualified DNS

### LINKED ISSUE #6741: [incubator/elasticsearch] not enough masters
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[incubator/elasticsearch] - https://github.com/helm/charts/tree/master/incubator/elasticsearch

**What happened**:
Master nodes can't discover themselves. All pods start but it seems that the discovery service isn't allowing masters to see each other. Even after a hour of them sitting they just report the following:

```
[2018-07-20T14:33:51,481][WARN ][o.e.d.z.ZenDiscovery     ] [nd-infra-elasticsearch-master-1] not enough master nodes discovered during pinging (found [[Candidate{node={nd-infra-elasticsearch-master-1}{UPiTP94YTTiWz6R0COZmKw}{LYO7sVKSRvu4hNDSD7E0zg}{10.244.2.109}{10.244.2.109:9300}, clusterStateVersion=-1}]], but needed [2]), pinging again
```

Service looks like:

```
awilhelm@MBP ~/work/k8s-config (SRE-796)*$ kubectl describe svc nd-infra-elasticsearch-discovery
Name:              nd-infra-elasticsearch-discovery
Namespace:         nd-infra
Labels:            app=elasticsearch
                   chart=elasticsearch-1.3.0
                   component=master
                   heritage=Tiller
                   release=nd-infra
Annotations:       <none>
Selector:          app=elasticsearch,component=master,release=nd-infra
Type:              ClusterIP
IP:                None
Port:              <unset>  9300/TCP
TargetPort:        %!d(string=transport)/TCP
Endpoints:         10.244.2.109:9300,10.244.7.73:9300,10.244.2.145:9300
Session Affinity:  None
Events:            <none>
```

The service responds as expected to a dig call:

```
[root@nd-infra-elasticsearch-master-0 elasticsearch]# dig nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42802
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. IN	A

;; ANSWER SECTION:
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.2.109
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.7.73
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.7.145

;; Query time: 2 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jul 20 14:35:28 UTC 2018
;; MSG SIZE  rcvd: 109
```

I am able to telnet to the remote pod using the IP address which proves the other master is online and listening:

```
[root@nd-infra-elasticsearch-master-0 elasticsearch]# telnet 10.244.7.73 9300
Trying 10.244.7.73...
Connected to 10.244.7.73.
Escape character is '^]'.
```

**What you expected to happen**:

The "nd-infra-elasticsearch-discovery" service should allow all masters to detect each other and resolve quorum. 

**How to reproduce it** (as minimally and precisely as possible):

helm install --name elasticsearch --namespace infra incubator/elasticsearch

kubectl log -n infra elasticsearch-master-0

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by aba182**
What this PR does / why we need it:

Changes from global to local DNS for the elasticsearch discovery service. The fully qualified DNS entry doesn't work.

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #
fixes #6741

Special notes for your reviewer:
@rendhalver offered to review from the issue.

### CODE REVIEW

**Comment by aba182** [comment]
This is a duplicate of https://github.com/helm/charts/pull/7085 which I appear to have made a larger mess than I can clean up. I hope that we are ok to work from this pull request and I can just close the other?

**Comment by aba182** [comment]
@davidkarlsen So I broke https://github.com/helm/charts/pull/7085 can you give LGTM here?

**Comment by rendhalver** [comment]
@davidkarlsen You can close the other one.
Let's get this one working and go from there.

**Comment by davidkarlsen** [comment]
Sorry for the delay!
/retest pull-charts-e2e

**Pull request merged**
