### PR TITLE
[stable/prometheus-operator] Added more options for AlertManager ServiceMonitoring

### PR DESCRIPTION
**Pull request by pburgisser**
Signed-off-by: Philippe Bürgisser (Camptocamp) philippe.burgisser@camptocamp.com

Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pburgisser-c2c** [comment]
cc: @vsliouniaev @bismarck

**Comment by pburgisser-c2c** [comment]
Hi @scottrigby,

You helped on my PR #22725 to merge the conflict to the test could run.
I see there is still an issue with testing with this current PR. Can you help please?$

Is there a way to avoid such issue in the future?

Thanks!
cc: @bismarck

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to prometheus-operator for a short time until https://github.com/prometheus-community/community/issues/28#issuecomment-672933972 is resolved. If you want to help with that effort, to test etc, that would be great!

Regarding CI failures here, it’s an ongoing issue with potentially different causes. The new Helm GitHub Actions CI will go a long way to help because each chart change is tested in complete isolation, unlike the current CI which shares a test cluster (where various conflicts can happen, depending which tests are currently running).

For this chart, let’s try to focus on getting the new repo in prometheus-community set up? It seems we are close now.

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
