### PR TITLE
Add RBAC support to the kubernetes-dashboard chart

### PR DESCRIPTION
**Pull request by iuriaranda**
Based on the official Kubernetes dashboard deployment file: https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml#L21

### CODE REVIEW

**Comment by iuriaranda** [comment]
I've signed the CLA as an employee of `CNCF - Skyscrapers`

**Comment by unguiculus** [comment]
There is another PR for this: #1415

**Comment by kfox1111** [comment]
Looks good to me.

**Comment by unguiculus** [comment]
Closing this since it duplicates #1415.

**Pull request closed without merging**
