### PR TITLE
[stable/sonarqube] Fix mount of configMap

### PR DESCRIPTION
**Pull request by guillomep**
#### What this PR does / why we need it:
We do not override anymore the startup command, so we have to mount the
sonar.properties directly instead of copying from /tmp/

#### Special notes for your reviewer:
I don't know the reason why we mounted the confi into /tmp/ and then copying in the right place, instead of directly mounting it the right way. Maybe there is a problem somewhere that I'm not aware of.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by rjkernick** [comment]
In a previous version of kubernetes, config maps were mounted read-only which can cause problems when you need to edit the file after it is mounted. I am not sure if that was changed back or not.

**Comment by guillomep** [comment]
The `sonar.properties` file seems to be mounted as read/write for the `sonarqube` user

**Comment by guillomep** [comment]
> @guillomep even after directly mounting the config after your changes, sonarqube is not applying the properties. Did you verify this issue? Can you confirm the image version of sonarqube? and are you installing any extra plugin with it?

Yes I have verified that the configuration is not updated since it does not copy file from `/tmp/` where the new version was mounted, that's how I discovered there was a problem with the chart

**Comment by guillomep** [comment]
> Please merge the latest master branch and increment the version in Chart.yaml

Done

**Pull request merged**
