### PR TITLE
[stable/airflow] remove secret subpath

### PR DESCRIPTION
**Pull request by ms32035**
Signed-off-by: Marcin Szymanski <ms32035@gmail.com>

#### What this PR does / why we need it:

I'm not exactly sure if it's not some bug in Kubernetes 1.12, but with `subPath` set the secret volumes are not mounted correctly on the workers. If anyone experienced similar issues, any input is appreciated.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by gsemet** [comment]
This might be conflict with a previous dev. Need to investigate more why this happens only on worker

**Comment by ms32035** [comment]
> This might be conflict with a previous dev. Need to investigate more why this happens only on worker

Those secrets are mounted only on workers

**Comment by ms32035** [comment]
@gsemet, did you have a chance to look into this?

**Comment by gsemet** [comment]
seem ok. You need to rebase

**Comment by ms32035** [comment]
Should be good for squash merge.

**Comment by ms32035** [comment]
@gsemet please approve

**Pull request merged**
