### PR TITLE
[stable/wordpress] Add JSON Schema to WordPress chart

### PR DESCRIPTION
**Pull request by andresmgot**
#### What this PR does / why we need it:

With Helm v3, it's now possible to include a [JSON Schema](https://json-schema.org/) in the chart package that validates that the given values satisfy the expected schema. This PR includes a basic JSON schema for the WordPress chart. It doesn't cover all the possible values of the chart but just the ones that, in my opinion, are more likely to be modified.

Apart from validating that the values complies with the schema, the next version of Kubeapps will use these schemas to render a simple form so the chart containing it is easier to configure and deploy. See https://github.com/kubeapps/kubeapps/blob/master/docs/developer/basic-form-support.md for more information.

Please let me know if you think any parameter should be included/removed from this list. This is an example of the file rendered by Kubeapps:

Screenshot from 2019-10-17 13-29-11

#### Which issue this PR fixes

  - ref https://github.com/kubeapps/kubeapps/issues/1182

#### Special notes for your reviewer:

cc/ @juan131 @javsalgar @carrodher @sameersbn @tompizmor 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by carrodher — APPROVED** [review]
As there is a separate file that doesn't affect when deploying the chart using Helm 2, we can merge those changes right now without issues.
Anyway I will wait until more members review the PR before setting the proper tags to merge it

**Comment by juan131** [comment]
I think users would find very useful to modify the PV size of the MariaDB database too.

Probably the number of replicas it's sth to be considered too, but for WP it's mandatory to use NFS for PVC(s) when using more than 1 replica...

**Comment by andresmgot** [comment]
Thanks @juan131 for your suggestions:

> I think users would find very useful to modify the PV size of the MariaDB database too.

That's a good point but there is an issue with that. The value `mariadb.enabled` is used to enable/disable the `externalDatabase` section and we cannot reuse the same value for two different sections. That means that we have two options: 1. Leave it as it is and if users need to modify the PV size, they need to go to the `Advanced` tab and modify it manually. 2. Add the PV size as a parameter and remove the `externalDatabase` details. In that case, if users disable mariadb, they need to go and fill the external database values manually. Having those two options, what do you think is best?

In any case, ideally we should have some mechanism for supporting both. I will create an issue to provide that functionality.

> Probably the number of replicas it's sth to be considered too, but for WP it's mandatory to use NFS for PVC(s) when using more than 1 replica...

If changing the number of replicas implies more changes in the rest of values it's probably better to leave it in the "Advanced" tab only.

**Review by juan131 — APPROVED** [review]
Approving your PR

**Pull request merged**
