### PR TITLE
[stable/redis] Add service for redis exporter

### LINKED ISSUE #5237: [stable/redis] redis-exporter connection refused
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
- BUG REPORT

**Version of Helm and Kubernetes**:
- Kubernetes v1.8.11
- Helm: v2.8.2

**Which chart**:
- stable/redis

**What happened**:
When I deploy redis with `metrics` value enabled, error occurs in prometheus.
```
Get http://172.30.22.136:9121/metrics: dial tcp 172.30.22.136:9121: getsockopt: connection refused
```

**What you expected to happen**:
I expected redis metrics to be collected in prometheus.

**How to reproduce it** (as minimally and precisely as possible):
```bash
$ git clone https://github.com/kubernetes/charts.git
$ cd charts/stable/redis
$ vi values.yaml
$ helm install . -n redis01 --namespace redis --values values.yaml
```
(values.yaml)
```bash
metrics:
  enabled: true
  resources: {}
  podAnnotations: {}
  targetServiceAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  image:
    registry: docker.io
    repository: oliver006/redis_exporter
    tag: v0.11
    pullPolicy: IfNotPresent
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by 7CHANHO**
(I have a mistake in my last pull request #5263, and I pull request again. I will close my last pull request.)

**What this PR does / why we need it**:
I add service for redis-exporter.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5237 

**Special notes for your reviewer**:
@unguiculus Please review this PR.

### CODE REVIEW

**Comment by rjkernick** [comment]
Please merge the latest master and resolve merge conflicts

**Comment by timstoop** [comment]
Why do you actually need a Service for the exporter? Can't that be handled by annotations on the Pod itself?

**Comment by unguiculus** [comment]
@timstoop Both is possible. I think you need a service if you use a service monitor for prometheus-operator.

**Comment by unguiculus** [comment]
@7CHANHO Are you going to close #5495 as mentioned? It's still open and discussions are still happening there. I don't even understand why you created a second PR for the same thing. Please close one of the two.

**Comment by 7CHANHO** [comment]
@unguiculus First, thank you for your review.
The last PR #5263 worked on the master branch. I closed it now.
Sorry for the confusion.

**Pull request merged**
