### PR TITLE
[stable/elasticsearch] Add the option to configure logging.yml or log4j2.properties

### PR DESCRIPTION
**Pull request by melifaro**
#### What this PR does / why we need it:
This PR moves logging configuration from configmap to values.yaml and so allows to customize it.
Our particular case was to enable slow logs within the cluster.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by monotek** [comment]
Could you also raise the image version to 6.6.1 please?

**Comment by melifaro** [comment]
@monotek I guess it's already done here: https://github.com/helm/charts/pull/11669

**Comment by melifaro** [comment]
@icereval @rendhalver what do you think about the change?

**Comment by melifaro** [comment]
@desaintmartin can I ask you to have a look here?

**Comment by svenmueller** [comment]
@simonswine maybe you have some spare time to review this PR?

**Pull request closed without merging**
