### PR TITLE
[all charts] Charts compatible with kubernetes 1.16

### PR DESCRIPTION
**Pull request by uniuuu**
Replaces extensions/v1beta1 to policy/v1beta1 for PodSecurityPolicy.
```
sed -i 's@apiVersion: extensions/v1beta1@apiVersion: policy/v1beta1@' `find . -iregex ".*yaml\|.*yml" -exec awk '/kind:\s+PodSecurityPolicy/ {print FILENAME}' {} +`
````
Replaces extensions/v1beta1 to apps/v1 for Deployment, StatefulSet, ReplicaSet, DaemonSet
```
sed -i 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' `find . -iregex ".*yaml\|.*yml" -exec awk '/kind:\s+(Deployment|StatefulSet|ReplicaSet|DaemonSet)/ {print FILENAME}' {} +`
sed -i 's@apiVersion: apps/v1beta2@apiVersion: apps/v1@' `find . -iregex ".*yaml\|.*yml" -exec awk '/kind:\s+(Deployment|StatefulSet|ReplicaSet|DaemonSet)/ {print FILENAME}' {} +`
```

Manually modified after searching for rest of files containing extensions/v1beta1 except Ingress objects obtained from: "`egrep -rL 'kind:\s+Ingress' | xargs awk '/extensions\/v1beta1|apps\/v1beta2/ {print FILENAME}'`"
Manually modified files:
> modified:   stable/cluster-autoscaler/README.md
> modified:   stable/cluster-autoscaler/values.yaml
> 	modified:   stable/owncloud/README.md
> 	modified:   stable/owncloud/values.yaml
>      modified:   stable/neo4j/templates/core-statefulset.yaml

Changes based on https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
* NetworkPolicy resources will no longer be served from extensions/v1beta1 by default in v1.16. Migrate to the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1 API.
* PodSecurityPolicy resources will no longer be served from extensions/v1beta1 by default in v1.16. Migrate to the policy/v1beta1 API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.
* DaemonSet, Deployment, StatefulSet, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 by default in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

#### What this PR does / why we need it:
Compatibility k8s v1.16

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Updating everything in a single PR will not work because the CI needs to execute some test installing the chart in an individual way. Apart from that, the chart version present in the _Chart.yaml_ should be bumped in every chart.

For example, charts contributed by Bitnami were already updated, see [those already merged PRs](https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajuan131+is%3Aclosed+apiVersion+to). The approach should be similar, a single PR per chart with the changes and the version bumped  according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by uniuuu** [comment]
Hello @carrodher 

In case some of Charts will be long time aren't updated approach from PR can be used to move them forward. 
Now CI test is passed. 
Versions have been bumped. 

`while read -r a; do gawk -i inplace -F'.' '{sub(/version:\s+([0-9]{1,}\.)+[0-9]{1,}/,$1"."$2"."1+$3); print }' $a; done < list_of_paths_to_Chart.yaml_files`

Some of Charts were failing in CI due to other issues. I've excluded them from PR.
List of failed charts: 
```
 ✖︎ burrow => (version: "0.3.4", path: "incubator/burrow") > Error waiting for process: exit status 1
 ✖︎ istio => (version: "0.2.14-chart4", path: "incubator/istio") > Deprecated chart must not have maintainers
 ✖︎ puppet-forge => (version: "0.1.9", path: "incubator/puppet-forge") > Error validating maintainer 'Gerard Hickey': 404 Not Found
 ✖︎ aws-cluster-autoscaler => (version: "0.3.4", path: "stable/aws-cluster-autoscaler") > Error waiting for process: exit status 1
 ✖︎ dask-distributed => (version: "2.0.3", path: "stable/dask-distributed") > Error waiting for process: exit status 1
 ✖︎ linkerd => (version: "0.4.2", path: "stable/linkerd") > Error validating maintainer 'Vic Iglesias': 404 Not Found
 ✖︎ mission-control => (version: "0.4.4", path: "stable/mission-control") > Error waiting for process: exit status 1
 ✖︎ msoms => (version: "0.2.1", path: "stable/msoms") > Error validating maintainer 'Sambit Mishra': 404 Not Found
 ✖︎ namerd => (version: "0.2.1", path: "stable/namerd") > Error waiting for process: exit status 1
 ✖︎ nginx-lego => (version: "0.3.2", path: "stable/nginx-lego") > Error waiting for process: exit status 1
 ✖︎ sapho => (version: "0.2.3", path: "stable/sapho") > Error waiting for process: exit status 1
 ✖︎ sensu => (version: "0.2.4", path: "stable/sensu") > Error validating maintainer 'Shane Starcher': 404 Not Found
```



> Updating everything in a single PR will not work because the CI needs to execute some test installing the chart in an individual way. Apart from that, the chart version present in the _Chart.yaml_ should be bumped in every chart.
> 
> For example, charts contributed by Bitnami were already updated, see [those already merged PRs](https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajuan131+is%3Aclosed+apiVersion+to). The approach should be similar, a single PR per chart with the changes and the version bumped according to [semver](http://semver.org/):
> 
> > Given a version number `MAJOR.MINOR.PATCH`, increment the:
> > 
> > * MAJOR version when you make incompatible API changes,
> > * MINOR version when you add functionality in a backwards-compatible manner, and
> > * PATCH version when you make backwards-compatible bug fixes.
> >   Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.



> Updating everything in a single PR will not work because the CI needs to execute some test installing the chart in an individual way. Apart from that, the chart version present in the _Chart.yaml_ should be bumped in every chart.
> 
> For example, charts contributed by Bitnami were already updated, see [those already merged PRs](https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajuan131+is%3Aclosed+apiVersion+to). The approach should be similar, a single PR per chart with the changes and the version bumped according to [semver](http://semver.org/):
> 
> > Given a version number `MAJOR.MINOR.PATCH`, increment the:
> > 
> > * MAJOR version when you make incompatible API changes,
> > * MINOR version when you add functionality in a backwards-compatible manner, and
> > * PATCH version when you make backwards-compatible bug fixes.
> >   Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Review by Aisuko — COMMENTED** [review]
Thanks for your PR, but I believe we should not do this in this way. We can make PR and relate to this.

**Comment by scottrigby** [comment]
@uniuuu thank you for your contribution, but @carrodher and @Aisuko are correct. See the note at https://github.com/helm/charts/blob/master/CONTRIBUTING.md#how-to-contribute-to-an-existing-chart
> In order to make testing and merging of PRs easier, please submit changes to multiple charts in separate PRs

If you want to break this into separate PRs that would be helpful. But closing this as it can not be merged as-is.

**Pull request closed without merging**
