### PR TITLE
[incubator/druid] Bump Apache Druid to 0.19.0

### LINKED ISSUE #23314: [incubator/druid] bump up druid version to 0.19.0
**Describe the solution you'd like**
It would be good to have 0.19.0 as a default version. To bump up druid version, need to update image version, application 
 version and documentation.

### PR DESCRIPTION
**Pull request by asdf2014**
No

#### What this PR does / why we need it:

Bump Apache Druid to 0.19.0

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

@maver1ck @AWaterColorPen

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by maver1ck** [comment]
@asdf2014 
Please add sign-off

**Comment by asdf2014** [comment]
@maver1ck Thanks for your reminder. It's done.

**Pull request merged**
