### PR TITLE
[incubator/couchdb] Add configurable affinity to CouchDB StatefulSet

### PR DESCRIPTION
**Pull request by natarajaya**
**What this PR does / why we need it**:
Adds configurable affinity to CouchDB StatefulSet.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
N/A

**Special notes for your reviewer**:
None.

### CODE REVIEW

**Comment by natarajaya** [comment]
CLA signed.

**Comment by kocolosk** [comment]
Good idea, thanks for the PR.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
