### PR TITLE
[stable/prometheus-operator] Add configuration options

### LINKED ISSUE #11768: [stable/prometheus-operator] needs higher container cpu limits or need customization parameters
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
current

**Which chart**:
stable/prometheus

**What happened**:
Frequent CPUThrottlingHigh alerts on the following pod.containers:
alertmanager-prometheus-prometheus-oper-alertmanager-0.config-reloader  
prometheus-prometheus-prometheus-oper-prometheus-0.prometheus-config-reloader 
prometheus-prometheus-prometheus-oper-prometheus-0.rules-configmap-reloader 
There is no way to raise the current hardwired cpu limits (100m, 50m, and 100m) on them.

**What you expected to happen**:
Need a way to raise the cpu limits on them when need.  for instance, we estimate that we would need to raise the cpu limites to 200m, 150m, and 200m respectively to eliminate the frequent CPUThrottlingHigh alerts on them.  There are other hardwired resource limites generated by the operator that may need similar customization support.

**How to reproduce it** (as minimally and precisely as possible):
This seems a self-evident design issue.

**Anything else we need to know**:
This is similar to #9540 but different.
We observed this CPUThrottingHigh alert while using stable/prometheus 4..0.0 and 4.1.1.
The premetheus-operator itself must also make a change either to raise the hardwired cpu limits, or add support for the cpu limit customization.

### LINKED ISSUE #11836: [stable/prometheus-operator] Cannot add extraArgs to Prometheus
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request (mainly)
Can be considered bug because Prometheus is failing because of the lack of memory

**Version of Helm and Kubernetes**:
k8s: v1.13.3
helm: v2.12.3

**Which chart**:
`stable/prometheus-operator`

**What happened**:
When trying to use the `stable/prometheus-operator` chart, I couldn't find a way to pass in extra definitions. `query.max-samples` cannot be set and Prometheus runs out of memory.

Based on the documentation:
> Prometheus is configured via command-line flags and a configuration file. While the command-line flags configure immutable system parameters (such as storage locations, amount of data to keep on disk and in memory, etc.), the configuration file defines everything related to scraping jobs and their instances, as well as which rule files to load.

I think configuring the `query.max-samples` can only be done with flags at start up.

**What you expected to happen**:
Be able to configure the `query.max-samples` flag at start up.

### LINKED ISSUE #11891: [stable/prometheus-operator] Low resource requests on sidecars Alertmanager and Prometheus
**Version of Helm and Kubernetes**:
Helm: v2.13
Kubernetes: v1.13.3

**Which chart**:
[stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator)

**What happened**:
Prometheus and Alertmanager do not deploy properly, config-reloader and configmap-reloader go into error state.

output of kubectl describe on Alertmanager pod (only the sidecar part):
```
 config-reloader:
    Container ID:  docker://15b92a20305388ff7815cc9710ae5fd48b301ecee0c139f97877b70829169176
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      -webhook-url=http://127.0.0.1:9093/monitoring/alertmanager/-/reload
      -volume-dir=/etc/alertmanager/config
    State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
 State:          Running
      Started:      Fri, 01 Mar 2019 22:05:47 +0100
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/podc0b26c5c-3c3d-11e9-9063-005056a42579/6fb668d6128ec5ad33145c84b4c8816030f38985a41ec4ffc75c52c9b4b3ef9f/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```

After 61 restarts, the pod deploys succesfully and my service becomes available.

I found similar issues around low resource requests, to test it out I deployed some pods myself with the low resources request and I got the same error, uping the requests by a little made the pod deploy without a hitch.

I can't seem to change the resource requestof the prometheus and alertmanager daemonset, if I alter the daemonset and restart the pods, it still takes the old resource requests (probably this is defined in the custom resource def?)

**What you expected to happen**:
Both Prometheus and Alertmanager deploy without a hitch

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart on K8s v1.13.3

**Anything else we need to know**:
I looked into the issue and I think it has to do with the low resource requests that are set on the sidecars.

### PR DESCRIPTION
**Pull request by vsliouniaev**
#### What this PR does / why we need it:
- Add configuration options introduced in 0.29.0 to alter memory and CPU limits for re-loader sidecars in the prometheus pod.
- Add configuration options for prometheus [query args](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#queryspec)
- Add documentation for frequently-experienced issue with CRDs not being installed due to helm bug

#### Which issue this PR fixes
  - fixes #11768 
  - fixes #11836
  - fixes #11891 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by JessieAMorris** [comment]
I just tried this out and while the values file has the variable `configReloaderCpu`. This changes the resources for the `rules-configmap-reloader` container but there's still no option to change the resources for the `prometheus-config-reloader` container.

Due to this I'm still seeing `CPUThrottlingHigh` alerts for the prometheus pod.

**Comment by JessieAMorris** [comment]
Ah checking upstream it seems that prometheus-operator doesn't support changing the `prometheus-config-reloader` resources yet. Basically [this](https://github.com/coreos/prometheus-operator/pull/2403/files) PR needs to be done but for the `prometheus-config-reloader` container.

**Comment by JessieAMorris** [comment]
I've got a PR on the `prometheus-operator` repo open to add the additional options needed. https://github.com/coreos/prometheus-operator/pull/2466

**Pull request merged**
