### PR TITLE
[stable/docker-registry] LoadBalancer settings

### LINKED ISSUE #20462: [stable/docker-registry] Can't assign loadBalancerIP for LoadBalancer service type
**Describe the bug**
When specifying the loadBalancerIP in values.yaml, the service does not assign the specified static IP. It just gives the service the first available IP from the available address pool configured in metalLB.  All other helm charts are working fine when loadBalancerIP is specified.

**Version of Helm and Kubernetes**:
Kubernetes:
Client Version: v1.17.2
Server Version: v1.17.1
Helm:
v3.0.2+g19e47ee

**Which chart**:
stable/docker-registry

**What happened**:
service doesn't show the specified loadBalancerIP as External-IP docker-service-registry

**How to reproduce it** (as minimally and precisely as possible):
Specify the following in values.yaml

```
service:
  name: registry
  type: LoadBalancer
  port: 5000
  loadBalancerIP: 10.10.30.205

### PR DESCRIPTION
**Pull request by wilinger**
#### What this PR does / why we need it:
Allows setting loadBalancerIP and loadBalancerSourceRanges values.yaml
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #20462

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by survivant** [comment]
I'll like to add another point if it's not to late.  I'm using MetalLB as LoadBalancer and it's easier for us to have a fix IP for the docker-registry.  


here the command that I'll use

`helm install docker-registry stable/docker-registry --set persistence.enabled=true,persistence.existingClaim=docker-registry-claim,persistence.size=5Gi,service.type=LoadBalancer,spec.loadBalancerIP=10.1.7.105 --namespace docker-registry`

for now, I have to deploy the chart, go and edit the yaml deployed

```
I'm adding this line under spec.
loadBalancerIP: 10.1.7.105
```


, scale to 0 and scale back to 1.

could be good to have that line in the template

**Comment by wilinger** [comment]
> 
> 
> I'll like to add another point if it's not to late. I'm using MetalLB as LoadBalancer and it's easier for us to have a fix IP for the docker-registry.
> 
> here the command that I'll use
> 
> `helm install docker-registry stable/docker-registry --set persistence.enabled=true,persistence.existingClaim=docker-registry-claim,persistence.size=5Gi,service.type=LoadBalancer,spec.loadBalancerIP=10.1.7.105 --namespace docker-registry`
> 
> for now, I have to deploy the chart, go and edit the yaml deployed
> 
> ```
> I'm adding this line under spec.
> loadBalancerIP: 10.1.7.105
> ```
> 
> , scale to 0 and scale back to 1.
> 
> could be good to have that line in the template

To set fixed loadBalancerIP, this should work with the changes. I just tested it on helm 3.  

```--set service.type=LoadBalancer,service.loadBalancerIP=10.1.7.105```

**Comment by wilinger** [comment]
@jpds @rendhalver Appreciate a review here, thanks!

**Comment by survivant** [comment]
Just to do a little follow up with the reviewers.

**Comment by wilinger** [comment]
@rendhalver @jpds Can we get a review here please?

**Comment by survivant** [comment]
please a review.

**Comment by wilinger** [comment]
Need review

**Pull request merged**
