### PR TITLE
Add namespace to finish_cluster command.

### PR DESCRIPTION
**Pull request by mrtyler**
**What this PR does / why we need it**:

Fixes the suggested `finish_cluster` command so that it works with deploys to namespaces other than `default`.

This is a trivial fix. I tested it by hand.

@rjkernick since you are active on #5044 which I am following.

### CODE REVIEW

**Comment by kocolosk** [comment]
Nice fix @mrtyler, I think you've just bumped into a metadata update clash with the merge of #5440

**Comment by mrtyler** [comment]
Thanks @kocolosk. I rebased on current master and re-bumped the version.

**Pull request merged**
