### PR TITLE
[stable/elasticsearch] implement init container for installing plugins

### PR DESCRIPTION
**Pull request by pavdmyt**
#### What this PR does / why we need it:

Provides init container to install list of plugins specified by `Values.cluster.plugins`. 

`Values.extraInitContainers` is not suitable for installing plugins because `/usr/share/elasticsearch/plugins` directory is not mounted by `extraInitContainers` and plugins get installed only inside init container, but not inside actual **elasticsearch** container.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by pavdmyt** [comment]
@simonswine @icereval any chance to review this PR?

**Comment by desaintmartin** [comment]
Thanks!
I like the idea. I've just tested it and it works well. Could you add a test in the CI directory for that? (and extra point if you manage to actually prove that a plugin is present, but that's not easy currently)
/ok-to-test

**Comment by pavdmyt** [comment]
@desaintmartin there is already a test in `ci` directory for this feature. 

I'm not sure that I'm fully understood regarding "plugin is present". Can you explain what it should do?

**Comment by desaintmartin** [comment]
Oh, sorry, missed it.

Actually testing that it correctly installed the plugin is currently complex in helm and probably out of scope for now.

/lgtm

**Comment by desaintmartin** [comment]
Oh, please rebase. :)

**Comment by pavdmyt** [comment]
@desaintmartin done, now everything should be good.

**Comment by roonie007** [comment]
when will this be merged ?

**Comment by desaintmartin** [comment]
About 3 months ago.

**Comment by roonie007** [comment]
@desaintmartin I saw the merge, but i just tested it with -- repository-s3 -- it's not working

```yaml
elasticsearch:
  image:
    tag: 6.6.1
  cluster:
    name: elasticsearch
    plugins: 
    - repository-s3
  master:
    persistence:
      size: 512M
  data:
    heapSize: 5g
    persistence:
      size: 10G
```

then in the container when i run this command to get the installed plugins :

```bash
bin/elasticsearch-plugin list 
```

I get this output

```
[root@elasticsearch-master-0 elasticsearch]# bin/elasticsearch-plugin list  
ingest-geoip
ingest-user-agent
```

repository-s3 is not listed as installed

**Comment by roonie007** [comment]
@desaintmartin my fault, the version of the chart is `version: 1.17.2` in my requirements.yaml, 
sorry for the inconvenience

**Pull request merged**
