### PR TITLE
[stable/spinnaker] remove ending slash of gate's url

### PR DESCRIPTION
**Pull request by eh-am**
Signed-off-by: Eduardo Aleixo <eduardoaleixomartins@gmail.com>

#### What this PR does / why we need it:
Removes ending slash in gate url

Was trying with appVersion: 1.11.0 and [this seems necessary](https://github.com/spinnaker/spinnaker.github.io/issues/1154). It should be compatible with current version (1.9.1)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
My first PR :)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cdelguercio** [comment]
I'm having the same issue. Any reason why this hasn't been approved yet?

**Comment by cirocosta** [comment]
I just tried it out here with the latest chart (`1.4.0`) and:

- without the patch: 500's  (`[...] The request was rejected because the URL was not normalized`); then
- with it: works fine 👍 

ps.: this is my first time spinning a spinnaker cluster.
pps.: the PR will need to go from the statefulset to the new configmap under `templates/configmap/halyard-init-script.yaml`

**Comment by viglesiasce** [comment]
/unassign

/assign @dwardu89 

@dwardu89 can you take a look at this one?

**Comment by dwardu89** [comment]
Looks good to me, it will mimic the #1155 you mentioned above. Has this been tested with another system apart from GKE? e.g. AWS EKS?  @eh-am 
You'll need to resolve the conflicts before i can approve it.

**Comment by eh-am** [comment]
argh sorry for the force pushes

@dwardu89  no, only tested on GKE, and minikube (if that counts)

**Review by dwardu89 — APPROVED** [review]

**Pull request merged**
