### PR TITLE
[kuberhealthy] Fix ServiceMonitor selector

### PR DESCRIPTION
**Pull request by mazzy89**
#### What this PR does / why we need it:

`ServiceMonitor` is not able to scrape correctly metrics because the `Service` is not found. The reason is due to the wrong label used in the selector.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by mazzy89** [comment]
@integrii @lolimjake @ihoegen

**Review by integrii — APPROVED** [review]
thanks!

**Pull request merged**
