### PR TITLE
[stable/memcached] fix the memcached chart's bug, when the AntiAffinity is soft

### PR DESCRIPTION
**Pull request by AlawnWong**
when the AntiAffinity is soft,
the preferredDuringSchedulingIgnoredDuringExecution.podAffinityTerm.topologyKey should be a map , not a array.

@linki

### CODE REVIEW

**Comment by sameersbn** [comment]
@AlawnWong please bump the chart version in Chart.yaml file

**Comment by AlawnWong** [comment]
@sameersbn    
I has bumped the chart version. 
Why the ci/circleci test failed ?

**Comment by sameersbn** [comment]
@AlawnWong https://circleci.com/gh/kubernetes/charts/2664?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link say's their linter issue. I've added a commit to resolve the issues

**Pull request merged**
