### PR TITLE
[stable/fluentd] add support to deployment with scale

### PR DESCRIPTION
**Pull request by sagile1**
#### What this PR does / why we need it:

We would like to deploy the Fluentd as a Deployment and not as Statefulset
Since flush_at_shutdown param is supported, there is no risk of losing data in scaling down in the stateless deployment

#### Which issue this PR fixes
in the current state, fluentd will be stateful if one of the following has been set
.Values.autoscaling.enabled  OR Values.useStatefulSet

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hectorj2f** [comment]
@sagile1 can you describe more in details your scenario?

**Comment by sagile1** [comment]
> @sagile1 can you describe more in details your scenario?

Hi @hectorj2f hectorj2f, 
We would like to deploy the fluentd to K8S as deployment and not statefullset
In the current state, there is a condition the deploy the chart as statefullset if autoscale is enable.
we don't see any risk to use deployment + autoscale since fluentd has the ability to flush the buffer to s3 once it scale down (flush_at_shutdown param). so there is no data loss in this case. you can find more details in https://docs.fluentd.org/configuration/buffer-section

**Pull request closed without merging**
