### PR TITLE
Added steps for how to add stable charts.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes/charts/issues/1536

### CODE REVIEW

**Comment by sameersbn** [comment]
The stable charts repo is added by default isn't it?

**Comment by gyliu513** [comment]
What do you mean by default? If I install a Kubernetes cluster manually by myself, how to add it by default? @sameersbn

**Comment by sameersbn** [comment]
I mean when you execute `helm init`, the `~/.helm` directory will be initialized with the stable repo by default.

To demonstrate:

```
# rm -rf ~/.helm
# helm repo list
Error: open /home/sameersbn/.helm/repository/repositories.yaml: no such file or directory
# helm init --client-only
Creating /home/sameersbn/.helm 
Creating /home/sameersbn/.helm/repository 
Creating /home/sameersbn/.helm/repository/cache 
Creating /home/sameersbn/.helm/repository/local 
Creating /home/sameersbn/.helm/plugins 
Creating /home/sameersbn/.helm/starters 
Creating /home/sameersbn/.helm/cache/archive 
Creating /home/sameersbn/.helm/repository/repositories.yaml
# helm repo list
NAME  	URL                                             
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts
```

**Comment by gyliu513** [comment]
Yes, thanks @sameersbn , updated the PR a bit, can you please help check if ok?

**Comment by unguiculus** [comment]
In my eyes this is unnecessary and misleading. I don't think we need a section on how to enable the stable repo when it is automatically enabled out of the box.

**Comment by gyliu513** [comment]
The reason that I want to list it here is because there maybe some 3rd party may update the logic of `helm init` by not adding `stable` charts, so it is better that we can mention what is the link of `stable` charts. @unguiculus

**Comment by gyliu513** [comment]
@unguiculus what about the update? Just want people get to know the default link of stable charts in the README.

**Pull request merged**
