### PR TITLE
[stable/instana-agent] Add PriorityClass to the instana agent's daemonset template

### PR DESCRIPTION
**Pull request by yottta**
### What this PR does / why we need it:
It's adding the possibility to specify a PriorityClass name in the daemonset's template.

#### Special notes for your reviewer:
Just mentioning them: @jbrisbin @wiggzz  @JeroenSoeters @fstab @mdonkers @dlbock @nfisher 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by nfisher** [comment]
Hi @yottta, Thanks for the PR we have an internal mechanism that tests and promotes changes. I’ll copy the replicate the essence of what you’ve contributed and add your e-mail as Co-author.

**Comment by yottta** [comment]
@nfisher any updates?

**Comment by dlbock** [comment]
@yottta Apologies for the slow response. I will get your changes in if not this week, next week.

**Comment by dlbock** [comment]
Putting this PR on hold as our internal mechanism will create a separate PR as part of the process.

**Comment by yottta** [comment]
Can be closed since another [PR](https://github.com/helm/charts/pull/23895) was merged Instana's flow.

**Comment by mdonkers** [comment]
/close
Requested changes already merged with https://github.com/helm/charts/pull/23895

**Comment by mdonkers** [comment]
@dlbock Could you please close this PR for completeness? Seems like I'm not able as the "Reviewers" contains only you and Will at this point.
Thx

**Comment by dlbock** [comment]
@mdonkers I can try, but I'm not sure if I can?

**Comment by mdonkers** [comment]
Guess nothing we can do about it then... We'll just let it run stale and should get auto-closed :-(

**Pull request closed without merging**
