### PR TITLE
Pachyderm: Fixed typo in the specific version command

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by jonandernovella** [comment]
@LaurentGoderre Please rebase to `HEAD` and make changes accordingly.

**Comment by LaurentGoderre** [comment]
@jonandernovella done!

**Comment by jonandernovella** [comment]
@LaurentGoderre The test won't pass until we bump the chart version.

**Comment by LaurentGoderre** [comment]
Done!

**Pull request merged**
