### PR TITLE
[stable/kafka-manager] Fix some minor typos in README.md

### PR DESCRIPTION
**Pull request by ParthKolekar**
Signed-off-by: Parth Kolekar <parthkolekar@indeed.com>

#### Is this a new chart
No.

#### What this PR does / why we need it:
Fixes some minor spelling and typos.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
I did not version bump this since this is just a README.md fix.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ParthKolekar** [comment]
Hello @giacomoguiulfo, could you confirm if I need a version bump for this?

**Comment by giacomoguiulfo** [comment]
Yes, do a patch version bump please

**Comment by ParthKolekar** [comment]
Patch version bumped!

**Pull request merged**
