### PR TITLE
[stable/apm-server] add @mumoshu to OWNERS

### PR DESCRIPTION
**Pull request by mumoshu**
As I am the original author of the chart. Currently I miss the privilege to put LGTM any pull rquest to chart due to the situation, as seen in https://github.com/helm/charts/pull/11661#issuecomment-471587560

### CODE REVIEW

**Comment by mumoshu** [comment]
@mattfarina Would you mind approving this? Without this, I can't put LGTM on the chart I created 😅

**Comment by cpanato** [comment]
@mumoshu please bump the chart version

**Comment by mumoshu** [comment]
@cpanato Thanks for reviewing! Just bumped the version num.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
