### PR TITLE
Add imagePullSecrets

### PR DESCRIPTION
**Pull request by vipulagarwal**
Signed-off-by: Vipul Agarwal <va@vagarwal.net>

#### What this PR does / why we need it:
`imagePullSecrets` is required when using a private docker registry. This will handle `imagePullSecrets` if specified in the values.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vipulagarwal** [comment]
@cpanato I have created a new PR. Please review and let me know if you need any changes.

**Comment by mattfarina** [comment]
cc @davidkarlsen as you're the maintainer of this chart

**Comment by cpanato** [comment]
will wait for @davidkarlsen 😄

**Comment by vipulagarwal** [comment]
@davidkarlsen can you look into this please?

**Comment by vipulagarwal** [comment]
Hi @davidkarlsen and @lachie83, please look at this and let me know if anything needs changing.
Cheers

**Comment by vipulagarwal** [comment]
Hi @davidkarlsen @achie83, please can you look at this PR and approve.

**Comment by vipulagarwal** [comment]
@cpanato: since @davidkarlsen is unavailable, would you able to approve this PR please?

**Comment by maorfr** [comment]
/assign

I suggest to push this forward unless we have any objections.
@vipulagarwal can you please rebase?

**Comment by davidkarlsen** [comment]
Sorry for the late response - my inbox is drowning in github stuff!

**Review by davidkarlsen — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
