### PR TITLE
[incubator/kubernetes-vault] adding new incubator project 

### PR DESCRIPTION
**Pull request by alejandroEsc**
Kubernetes-Vault to incubator repo.

Reviewers:
I was finishing creating this chart when it was pointed out that there already is a chart PR for this project here: https://github.com/kubernetes/charts/pull/1396. Since I already have moved ahead with this chart and nearing completion I decided to submit it and leave the community and the author @bbriggs how to reconcile these two, the more info and viewpoints the better is the philosophy here.

### CODE REVIEW

**Comment by bbriggs** [comment]
I'd be happy to help reconcile this with you! Many contributors and views makes for stronger systems.

**Comment by unguiculus** [comment]
Is it ok to close #1396 then?

**Comment by unguiculus** [comment]
Please apply best practices, especially regarding standard labels:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

See chart examples for reference:
https://github.com/kubernetes/helm/tree/master/docs/examples/nginx

Regarding RBAC, please follow this style:
https://github.com/kubernetes/charts/pull/1504/files

**Comment by bbriggs** [comment]
I'd like for someone from the charts team to review my PR first, please, given that it has been there for about a month now, so no, I would not prefer to have my PR closed.

**Comment by alejandroEsc** [comment]
@unguiculus done with your requests. @bbriggs I agree, any idea what the current state is and why?

**Comment by bbriggs** [comment]
@alejandroEsc I popped into the Helm core dev meeting a couple weeks ago to request review after it sat idle for 8 days and got a promise to review it. However, there has been no movement on it since. They did say they wanted to "evaluate the full stack" meaning kuernetes-vault + the kubernetes PR someone else submitted. 

However, I'm pretty disappointed by the handling and lack of attention to PRs so far. I've been trying to be patient and wait for things to resolve given that this is my first PR here and I don't know what's normal or processes that are expected, but this is more than frustrating that work gets ignored to the point that work is now being duplicated.

**Comment by alejandroEsc** [comment]
@bbriggs yeah it is frustrating, ill see if i can contact a few people there and get your PR moving.

**Comment by unguiculus** [comment]
@bbriggs Sorry, I probably misunderstood. I won't close your PR then. I'll check back with @lachie83 to see if we can get this through.

**Comment by unguiculus** [comment]
Can we close this PR, now that #1396 was merged?

**Comment by alejandroEsc** [comment]
@unguiculus I appreciate the politeness of you asking. Yes please do, any further work will be submitted against current vault chart :) Excellent job @bbriggs and i hope you continue to contribute!

**Comment by bbriggs** [comment]
Looking forward to it. If you want to make some improvements to the k8s-vault chart, feel free to ping me. I'd love to collaborate on it.

**Pull request closed without merging**
