### PR TITLE
OwnCloud: Update chart to 0.4.1

### PR DESCRIPTION
**Pull request by jotadrilo**
- update OwnCloud image version to 9.1.2-r0

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@jotadrilo this is currently failing to install because the requirements repository needs an extra slash at the end. There is a bug open against helm to get this fixed but until then will need you to update.

**Comment by viglesiasce** [comment]
Actually this is because the default helm stable repo url has changed to:


https://kubernetes-charts.storage.googleapis.com/

**Comment by jotadrilo** [comment]
@k8s-bot e2e test this

**Comment by jotadrilo** [comment]
@viglesiasce thanks for letting me know. It seems the checks passed this time.

**Comment by viglesiasce** [comment]
Thanks @jotadrilo!

**Pull request merged**
