### PR TITLE
[stable/treafik] Upgrade to Træfik v1.7.1

### PR DESCRIPTION
**Pull request by Starefossen**
#### What this PR does / why we need it

Upgrade Træfik to v1.7.1

#### Which issue this PR fixes

containous/traefik#3952

#### Special notes for your reviewer

Thanks for making Helm and Kubernetes awesome! ❤️ 

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- ~[ ] Variables are documented in the README.md~

### CODE REVIEW

**Comment by dtomcej** [comment]
@Starefossen Can you please update your commit with the Correct DCO? Hit the "Details" to see whats going on :)

Thanks!

**Comment by Starefossen** [comment]
@dtomcej ahh.. good catch! I amended to the commit and tried to sign-off one more time. Fixed!

**Comment by cpanato** [comment]
@Starefossen need to update the readme.md to to match the new tag

**Comment by Starefossen** [comment]
Thanks @cpanato – another good catch! Fixed 😄

**Comment by dtomcej** [comment]
@Starefossen Sorry to be a bother. Can you rebase and bump the chart version?

**Comment by Starefossen** [comment]
@dtomcej done and done 😄

**Pull request merged**
