### PR TITLE
[stable/pachyderm] Bump chart version to 0.1.6

### PR DESCRIPTION
**Pull request by jonandernovella**
Added RBAC support and updated Pachyderm version to 1.7.0

### CODE REVIEW

**Comment by unguiculus** [comment]
@jonandernovella Unfortunately, the chart hard-codes the service account. Would you mind creating another PR aligning it with our RBAC best practices?

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

An update with regard to resource names and labels would also be appreciated. See https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md. Thanks.

**Comment by jonandernovella** [comment]
@unguiculus I can see that you are not familiar with the project. By design, Pachyderm currently requires some resource names to be hardcoded. This has been discussed in previous PRs. Thanks!

**Pull request merged**
