### PR TITLE
[stable/selenium] Updating default version to latest tag

### PR DESCRIPTION
**Pull request by diemol**
Hi,

I just bumped into this repo and I noticed that the version was out of date. Thus, this PR.

Besides that, nice work!

### CODE REVIEW

**Comment by diemol** [comment]
Hi,
Any news on this? I am usually helping to release the docker-selenium images, and I can also update this repo from time to time, but it would be nice to get some feedback and see if this makes sense for you all.

**Comment by mattfarina** [comment]
cc: @flah00

**Comment by flah00** [comment]
LGTM

**Pull request merged**
