### PR TITLE
[stable/weave-cloud] Switch to using Docker Hub, bump version

### PR DESCRIPTION
**Pull request by cPu1**
#### What this PR does / why we need it:
This PR switches to using Docker Hub in order to avoid intermittent issues with pulling from the weaveworks namespace from quay.io.

#### Checklist
- [x] Chart Version bumped
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by errordeveloper** [comment]
@stefanprodan looks like I'm not a member any more, would you mind to help please?

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
