### PR TITLE
[stable/prometheus] add failure and success threshold to probes

### PR DESCRIPTION
**Pull request by mblaschke**
@mgoodness 
@gianrubio 

#### Which issue this PR fixes
- Add readinessProbeFailureThreshold
- Add readinessProbeSuccessThreshold
- Add livenessProbeFailureThreshold
- Add livenessProbeSuccessThreshold

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [-] Variables are documented in the README.md -> the others are also not documented?
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@mblaschke 
Would you mind to bump chart version to latest please? Thank you.

**Comment by mblaschke** [comment]
@zanhsieh  rebased and pushed.. minor version is ok?

**Comment by mblaschke** [comment]
@zanhsieh rebased and pushed, again :)

**Review by zanhsieh — APPROVED** [review]

**Comment by mblaschke** [comment]
@zanhsieh rebased and pushed, once again :)
Chart version was too old so test was failing

**Pull request merged**
