### PR TITLE
[incubator/sentry-kubernetes] Add optional PodDisruptionBudget

### PR DESCRIPTION
**Pull request by BenBlaisdell**
@gianrubio 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by BenBlaisdell** [comment]
@gianrubio It seems that test is failing because Chart.yaml doesn't list any maintainers. Is there anything else I need to do to get this merged in?

(Sorry for the ping/questions; this is my first contribution to this repo)

**Comment by BenBlaisdell** [comment]
@gianrubio @unguiculus Can someone address my previous question?

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request closed without merging**
