### PR TITLE
[incubator/kube-spot-termination-notice-handler] New chart

### PR DESCRIPTION
**Pull request by egeland**
Add a simple chart for the very useful [kube-spot-termination-notice-handler](https://github.com/mumoshu/kube-spot-termination-notice-handler)

### CODE REVIEW

**Comment by rimusz** [comment]
`README.md` is missing, it must be included so users can read what is chart about and how to use it. thanks

**Comment by egeland** [comment]
I'll add one! 👍

**Comment by rimusz** [comment]
and thanks for the useful chart 👍

**Comment by egeland** [comment]
@mgoodness I added the README - hope it's ok now?

**Review by mgoodness — APPROVED** [review]
I think this is of sufficient quality for the incubator. We'll want a NOTES.txt, a more complete README.md, and more polish in general before it goes to stable.

**Pull request merged**
