### PR TITLE
Addition of liveness probe template parameters in Kafka StatefulSet

### PR DESCRIPTION
**Pull request by dzmuda**
**What this PR does / why we need it**:

Exposes liveness probe parameters for configuration

**Which issue this PR fixes**

None

**Special notes for your reviewer**:

None

### CODE REVIEW

**Comment by javierholguera** [comment]
Looking forward to this getting merged, we need it too.

**Comment by benjigoldberg** [comment]
/lgtm

Thanks for the contribution @dzmuda 

cc: @javierholguera good to go now

**Pull request merged**
