### PR TITLE
[stable/prometheus-operator] Add volume mounts and volume

### PR DESCRIPTION
**Pull request by omerlh**
#### Which issue this PR fixes
Added volume mounts and volume to alert manager spec
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by vsliouniaev** [comment]
Could you please bump the chart version

**Comment by omerlh** [comment]
Fixed, thanks :)

**Pull request merged**
