### PR TITLE
Modify Ingress template to be easier to --set

### LINKED ISSUE #11070: [stable/chartmuseum] Make ingress host configuration more `--set` friendly
**Version of Helm and Kubernetes**:
Helm v2.10.0
Kubernetes 1.10.3

**Which chart**:
stable/chartmuseum

**Feature request**:
The ingress hosts configuration is not `--set` friendly since the hosts are keys in a map and the paths are arrays under that key.

See for instance Kubeapps (https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/values.yaml), where ingress hosts looks like:
```
    hosts:
      - name: hostname.host.com
        path: /
```

Another example is WordPress (https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml) which is structured in the same way.

The use-case here is that the ChartMuseum chart is being installed as part of an AWS k8s cluster bootstrap and the host(s) (which are internal ELBs) are not known at chart-creation time and have to be dynamically set at runtime.  As a workaround I am dynamically generating a YAML file that contains the properly structured map but it would be much simpler if we could simply `--set` the hosts like we're doing with our Kubeapps install.

### PR DESCRIPTION
**Pull request by out-of-band**
Signed-off-by: Scott Collier <collierthescott@gmail.com>

#### What this PR does / why we need it:
The current ingress template is difficult to use with `--set` if the hosts are not known until install-time (e.g., for automated deployments).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #11070 

#### Special notes for your reviewer:
This is a breaking change from the existing Ingress template so I bumped the SemVer to a new major version (v2.0.0).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by pytimer — APPROVED** [review]
It's ok for me.

**Comment by out-of-band** [comment]
Sure @jdolitsky I will do that ASAP tomorrow morning.

**Comment by out-of-band** [comment]
@jdolitsky @pytimer I updated the README.  I included the ingress setup in the parameters table at the top and added an Ingress section to the document (and updated the ToC with doctoc).

One question, though: ideally the Ingress TLS configuration would be per-host.  I don't think it was before, either, but the way it *should* technically work (I think) is something like this:

```
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}```

Should I make that change as part of this PR or make it a future improvement?  I should be able to get to it today or tomorrow either way.

**Comment by jdolitsky** [comment]
@out-of-band awesome work! Can you fix the DCO check?

The secret change sounds good to me. @pytimer? lets get this in pre-merge if possible

**Comment by out-of-band** [comment]
@jdolitsky I fixed the DCO check, sorry about that, for got to `-s` the README commit.  I had to rebase and force-push to get it fixed.

**Comment by jdolitsky** [comment]
@out-of-band any chance we can get the secret addition before merge? If busy we add this at a later date

**Comment by out-of-band** [comment]
@jdolitsky Absolutely.  I will make the change ASAP, should be in the next couple of hours.

**Comment by pytimer** [comment]
@out-of-band @jdolitsky Sorry, I have something during this time, it looks good to me about secret.

**Comment by out-of-band** [comment]
Just checking in on this.  Is everything good or is further review pending?

**Comment by jdolitsky** [comment]
@out-of-band no this looks good to me! apologies for delay. merging
/lgtm

**Comment by pytimer** [comment]
@out-of-band Can you fix the `stable/chartmuseum/Chart.yaml` conflict?

**Comment by out-of-band** [comment]
@pytimer  Merge conflict is resolved.

**Comment by jdolitsky** [comment]
🎉

**Pull request merged**
