### PR TITLE
[stable/airflow] added option to specify git-clone initContainer custom resources

### PR DESCRIPTION
**Pull request by yehlo**
Signed-off-by: Joshua Leuenberger <joshua.leuenberger@bedag.ch>

#### What this PR does / why we need it:
The default resource limitation of the resource container using the main container needed to much resources. #22274 
Added the option to specify the initContainer ressources

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yehlo** [comment]
Hi @thesuperzapper
I went ahead and updated the resource configuration in the values below initContainer. 
I think it is the cleaner way to not use git-sync resources for both. 
Thanks for your inputs. 

@gsemet Can you take a look at this?

**Comment by thesuperzapper** [comment]
@gsemet do not merge this yet

**Comment by thesuperzapper** [comment]
@yehlo this PR would introduce more issues, see the alternative here: #22298 

What you did in this PR is confusing, as it doesn't do what it implies, you have called the value `dags.initContainer.resources` when it isn't the resources for initContainer.

The best option is to use the already present `dags.git.gitSync.resources`, as to preform the initial git-clone will not require more resources than any following syncs.

**Comment by yehlo** [comment]
@thesuperzapper I see that I fd-up the indentation of the values.yaml. Fixed it in the most recent commit. Maybe you meant that with? 
> What you did in this PR is confusing, as it doesn't do what it implies, you have called the value dags.initContainer.resources when it isn't the resources for initContainer.

I do think that the git-sync and git-clone containers need to be treated separately since they are different mechanisms. 

Using the git-sync resources attribute on the git-clone container is in my opinion confusing. You would have to configure your initContainer resources on you sidecar container. And even if you don't use the git-sync mechanism you'd have to define atleast the resources part if need be.

**Comment by thesuperzapper** [comment]
I agree that we should seperate the requests between `git-sync` and `git-clone`, but do you realise that `initContainer` is not the same as the `git-clone` container?

**Comment by thesuperzapper** [comment]
Wait, I am mistaking `preinitdb` for `initContainer`.

**Comment by thesuperzapper** [comment]
This looks ok now, please squash your commits.

**Comment by thesuperzapper** [comment]
@gsemet this looks ok to test

**Comment by yehlo** [comment]
I guess the naming is kind off confusing. 
Thanks for your inputs. 

@gsemet It's up for merging now :)

**Review by thesuperzapper — APPROVED** [review]

**Review by gsemet — APPROVED** [review]
/lgtm

Good idea !

**Pull request merged**
