### PR TITLE
[stable/superset] fix init startup script for superset entrypoint. 

### PR DESCRIPTION
**Pull request by shashankkoppar**
Is this a new chart?
No

What this PR does / why we need it:
Adds the following functionality:

updates Superset init script which has been changed from superset version 0.36.0 and also standard suggested from superset documentation. 
https://superset.apache.org/installation.html#a-proper-wsgi-http-server

Which issue this PR fixes
None

### CODE REVIEW

**Comment by shashankkoppar** [comment]
@MarcusSorealheis  Can you please check ?
I have also added support in entrypoint if someone is upgrading superset version  too.

**Review by MarcusSorealheis — APPROVED** [review]
I think it looks good. Thanks for keep it updated.

**Comment by shashankkoppar** [comment]
@davidkarlsen Can you also please review?

**Comment by shashankkoppar** [comment]
@davidkarlsen  . Sorry for mentioning again. I would appreciate if you review it as well. Thanks!

**Pull request merged**
