### PR TITLE
[incubator/ory-oathkeeper] Propagate changes from upstream

### PR DESCRIPTION
**Pull request by aeneasr**
#### What this PR does / why we need it:

This PR adds a helm chart for [ORY Oathkeeper](https://github.com/ory/oathkeeper). I would also like to take ownership of this chart as I'm the primary author/maintainer of ORY Oathkeeper.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @aeneasr 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by aeneasr** [comment]
I didn't know that's a thing. What does the repository need to provide in order for this to work? I actually searched for docs on that before making this PR but was unable to find it.

**Comment by aeneasr** [comment]
Ah my bad, it's in the helm/hub repository: https://github.com/helm/hub/blob/master/docs/github.md

**Comment by aeneasr** [comment]
Yeah I think that makes most sense! Thank you for the pointer.

**Comment by aeneasr** [comment]
For anyone looking, the official helm charts are now published at: https://k8s.ory.sh/helm/

**Pull request closed without merging**
