### PR TITLE
[stable/postgresql] improving consistency between master and slave sts

### PR DESCRIPTION
**Pull request by joaocc**
#### What this PR does / why we need it:
Improves consistency of the definitions of master and slave

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution @joaocc, please, can you take a look at the failing tests?
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/helm_charts/9272/pull-charts-e2e/16485/

**Comment by joaocc** [comment]
@carrodher bumped and pushed. thx

**Pull request merged**
