### PR TITLE
[state/elasticsearch] add pullSecrets in README.md

### PR DESCRIPTION
**Pull request by imtnd**
#### What this PR does / why we need it:
I could not find 'pullSecreats' in README.md.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by imtnd** [comment]
I changed only a README.md
Should I need to up the version?

**Comment by zanhsieh** [comment]
Yes.

**Pull request merged**
