### PR TITLE
[stable/nginx-ingress] Add security context for default backend

### LINKED ISSUE #14971: [stable/nginx-ingress]  defaultbackend not started with PSP enabled
**Describe the bug**
Pods default backend in nginx-ingress chart doesn't start when `podSecurityPolicy.enabled`is set to `true`

The pod try to start with nginx-ingress psp which doesn't allow container to run as root
Deployment default backend doesn't specify a runAsUser in its security context which launches it as root
The pod doesn't start because the psp is not respected

**Version of Helm and Kubernetes**:
helm 2.14.1
Kubernetes 1.13.6

**Which chart**:
stable/nginx-ingress 1.6.17

**What happened**:
default backend pods doesn't start 
`Error: container has runAsNonRoot and image will run as root`

**What you expected to happen**:
Pod run

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/nginx-ingress --set podSecurityPolicy.enabled=true

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by LucasBoisserie**
#### What this PR does / why we need it:
Add Security Context for defaultBackend pod, to start pods with no root user
Remove nginx-ingress sa for defaultBackend, pod doesn't need nginx-ingress controller rights

#### Which issue this PR fixes
  - fixes #14971 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zhaofengli** [comment]
@LucasBoisserie This commit breaks PSP, as it deletes `serviceAccountName` in `default-backend-deployment.yaml`.

**Comment by LucasBoisserie** [comment]
@zhaofengli, default-backend-deployment doesn't need any specific privileged. If we respect the principle of least privileged, it had no reason to run with the ingress-controller PSP which have too much permission !
When you attach the nginx serviceaccount, default backend run with ingress-controller PSP!

Default backend need to run with a simple restrict PSP, already deploy in the most of cluster as the default policy !

If you need an example of restrict PSP, kubespray have one [here](
https://github.com/kubernetes-sigs/kubespray/blob/7a2cfb8578c4f0ef870ee6c806d08b0655f0d416/roles/kubernetes-apps/cluster_roles/templates/psp.yml.j2)

**Comment by zhaofengli** [comment]
@LucasBoisserie I'm well aware that I can supply my own restrictive PSP, but we should not assume that the cluster has one already that allows any authenticated user to access. For instance, RKE/Rancher does not provide one (`default-psp` is a PSP that allows *all* privileges, and is obviously not granted to everyone by default). I think we should provide a PSP for default-backend in the chart so it always works and provides a clear expectation of what privileges it requires.

**Comment by LucasBoisserie** [comment]
@zhaofengli
I find a rancher post about the subject but they didn't give a recommandation: https://rancher.com/blog/2019/2019-01-17-101-more-kubernetes-security-best-practices/

I look into other charts and some of them have PSPs for all deployment (like prometheus-operator) and other have juste a security-context (like grafana)
I'm agree with you that a PSP for default-backend is the good solution

I let you create the issue/PR and discuss with the maintainers
Please ref this PR that i can follow the subject ! :)

**Comment by svrc-pivotal** [comment]
Will work on a PR for this; similar to prometheus-operator the "right" solution is to provide an OOTB highly-restricted PSP, role binding, role, and SA for the default backend, which are optional and replaceable with a user-defined SA.   

Otherwise any cluster with PSPs enabled in the usual way (i.e. no default PSP, must be explicit) can't use the nginx-ingress helm chart

**Pull request merged**
