### PR TITLE
[incubator/sparkoperator] Adding securityContext parameter for sparkoperator

### PR DESCRIPTION
**Pull request by ghost**
#### What this PR does / why we need it:

Adds securityContext param for sparkoperator chart to allow for the operator to conform to any necessary security requirements.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by liyinan926** [comment]
@whitlekx can you give an example of how you configure the securirycontext in a `helm install` command?

**Comment by whitlekx** [comment]
You would have to know what part of the security context you would want, but you could do a `helm install . --set securityContext.runAsUser=1000`, etc.

**Comment by whitlekx** [comment]
Yep!

**Pull request merged**
