### PR TITLE
[stable/nextcloud] Bump to Nextcloud 17

### PR DESCRIPTION
**Pull request by pfuhrmann**
#### Special notes for your reviewer:
- Also fixed compatibility with Kubernetes 1.16 ([kubernetes.io](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/))

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by pfuhrmann** [comment]
link in robot comment is wrong / not working [1].

pull-charts-e2e  1186968697391026182

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/18170/pull-charts-e2e/1186968697391026182/

**Pull request merged**
