### PR TITLE
postgres: Fix link in README

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by foxish** [comment]
[CLA ping]

**Comment by lachie83** [comment]
looks like there's an issue with the LF CLA. Can you please sign?

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/charts/240)

**Comment by viglesiasce** [comment]
Closing as this CLA still has not been signed.

**Pull request closed without merging**
