### PR TITLE
[stable/neo4j] Neo4j fixes

### LINKED ISSUE #19934: [stable/neo4j] chart cannot work in k8s 1.16+
**Describe the bug**
Neo4j installation from Helm chart is failed under Kubernetes 1.16+.
```
$ helm install --name neo4j-helm stable/neo4j --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```
**Version of Helm and Kubernetes**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"archive", BuildDate:"2019-12-10T11:28:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"archive", BuildDate:"2019-12-11T14:00:15Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
**Which chart**:
stable/neo4j

**What happened**:
An error during Helm chart installation

**What you expected to happen**:
An installed Neo4j instance from chart

**How to reproduce it** (as minimally and precisely as possible):
Please try to install Neo4j with Helm

### PR DESCRIPTION
**Pull request by srilumpa**
#### Is this a new chart

No

#### What this PR does / why we need it:

* Enforce compatibility of the chart with K8S 1.16
* Enforce Helm best practices in labels

#### Which issue this PR fixes
  - fixes #19934

#### Special notes for your reviewer:

@mneedham I not quite sure on the upgrading procedure since I wasn't able to thoroughly test it, but I am able to deploy the chart on a Kubernetes v1.16.2 minikube box.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dfateyev** [comment]
Any news on that? are there any issues with this PR?

**Comment by ppoliani** [comment]
@srilumpa  have you managed to make it work with the neo4j v4?

**Comment by srilumpa** [comment]
@ppoliani I haven't tried it since I wanted only to be able to deploy the chart on a Kubernetes platform 1.16+.

Maybe the Neo4J v4 compatibility should be the subject of an other PR.

**Review by moxious — COMMENTED** [review]
Hi, Neo4j employee here.  LGTM and I think this is a really helpful PR.   Also, +1 for separating Neo4j 4.0 support into a separate PR.   There are some rather large changes between 3.5 and 4.0 that impact fine details of server configuration and should be dealt with separately.   I also happen to know that @mneedham is out of the office at the moment.

**Comment by styk-tv** [comment]
Screenshot 2020-03-25 at 17 15 09

Would be great if the time to adoption of new releases was by community was embedded into the pipelines of software releases. 1h into docker hub is definitely less than into a cloud-native chart which half of the world is using it seems. No pressure, just saying...

@moxious @tinwelint @nawroth @jimwebber

**Comment by madianas** [comment]
Any news on this?
I've managed to upgrade this chart to v4.0.2  . Main issue was, if using DNS discovery type, NEO4J_dbms_default__advertised__address must be an ip address, instead of a domain name. Right now working on K8S discovery type version.

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
