### PR TITLE
Fix typo in readme.md

### PR DESCRIPTION
**Pull request by frits-v**
Console -> consul typo

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by frits-v** [comment]
CLA signed.

**Comment by unguiculus** [comment]
Please bump the chart version

**Pull request merged**
