### PR TITLE
[stable/grafana] fix issue #15083

### LINKED ISSUE #15083: [stable/grafana] unable to import dashboard : download_dashboards.sh failed
**Describe the bug**
I want to upload grafana dashboard  by the id but I'm behind a proxy
even with the env http_proxy,https_proxy,no_proxy set the pod doesn't start
the 

**Version of Helm and Kubernetes**:
K8S 1.14.2

**Which chart**:
Stable/grafana
```
      rbac:
        pspEnabled: true
        create: true
      serviceAccount:
        name: tiller
        create: true

      deploymentStrategy: RollingUpdate
      image:
        repository: grafana/grafana
        tag: 5.2.2
        pullPolicy: IfNotPresent
      securityContext:
        runAsUser: 472
        fsGroup: 472

      downloadDashboardsImage:
        repository: appropriate/curl
        tag: latest
        pullPolicy: IfNotPresent

      plugins:
      persistence:
        enabled: false

      adminUser: admin
      adminPassword:XXXX
      grafana.ini:
        server:
          root_url: https://ingress-mydomain/grafana/
      dashboards:
        default:
          kubernetes-cluster:
            gnetId: 7249
            datasource: Prometheus
          nginx-ingress:
            gnetId: 9614
            datasource: Prometheus
          kubernetes-cluster-monitoring-prometheus:
            gnetId: 8588
            datasource: Prometheus
      extraEmptyDirMounts:
      - name: dashboards
        mountPath: /var/lib/grafana/dashboards/default
      sidecar:
        imagePullPolicy: IfNotPresent
        datasources:
          enabled: true
          label: grafana_datasource
        dashboards:
          enabled: true
          label: grafana_dashboard
      env:
        https_proxy: ((https_proxy))
        http_proxy: ((http_proxy))
        no_proxy: ((no_proxy))
        HTTPS_PROXY: ((https_proxy))
        HTTP_PROXY: ((http_proxy))
        NO_PROXY: ((no_proxy))


```
**What happened**:

The grafana deployment fail
image

the download-dashboard container is not able to download dashboard :

```
kubectl logs grafana-5fc4b5946f-thm2k -c download-dashboards -n monitoring
/etc/grafana/download_dashboards.sh: line 8: can't create /var/lib/grafana/dashboards/default/kubernetes-cluster.json: nonexistent directory
```

**What you expected to happen**:
I espect that dashboards can be uploaded even if my K8S is located behind a proxy

### PR DESCRIPTION
**Pull request by obeyler**
#### Which issue this PR fixes
  - fixes #15083 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by benmyb** [comment]
Hi, guys.
Why are there multiple commas in yaml file? I think this cause error below:
`Error: YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 51: did not find expected key`
Because in helm created deployment.yaml I find code like this:
```
          "command": ["/bin/sh"],
          "args": [ "-c", "mkdir -p /var/lib/grafana/dashboards/default", "/etc/grafana/download_dashboards.sh" ],
```
It should be:
```
          command: ["/bin/sh"]
          args: [ "-c", "mkdir -p /var/lib/grafana/dashboards/default", "/etc/grafana/download_dashboards.sh" ]
```

**Comment by zanhsieh** [comment]
@obeyler ??

**Comment by obeyler** [comment]
@zanhsieh I don't understand why some "" have been added
I'll fixe that quickly

**Comment by phillebaba** [comment]
I am getting the same error as @benmyb. The issue seems to be the trailing commas that is causing the error.

**Comment by obeyler** [comment]
@phillebaba  I fixed my error in this PR
https://github.com/helm/charts/pull/15149

**Comment by phillebaba** [comment]
I am sorry, I must have missed that PR. Thanks for being quick with the bug fix.

**Pull request merged**
