### PR TITLE
Windows PS command for root password retrieval

### PR DESCRIPTION
**Pull request by pablonautic**
#### What this PR does / why we need it:

Added Windows Powershell command  for root password retrieval.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by thomasliddledba** [comment]
@pablonautic - I like this PR is there anyway we can resolve the DCO issue?

**Comment by pablonautic** [comment]
@thomasliddledba DCO fixed (also learned something new about git ;) )

**Comment by pablonautic** [comment]
@thomasliddledba any chance this being merged?

**Comment by thomasliddledba** [comment]
@pablonautic - This looks to have failed the lint-charts.  You will need to resolve this first.

**Comment by pablonautic** [comment]
@thomasliddledba The message is `✖︎ stable/mssql-linux > Chart version not ok. Needs a version bump!` - how do I fix that? Doesn't seem to me like this micro change would deserve a version bump...

**Pull request closed without merging**
