### PR TITLE
Feature/run jenkins as non root user

### PR DESCRIPTION
**Pull request by ghost**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by ghost** [comment]
# Four test cases:

## test case 1: current state as-is - results into runAsUser: 0
```
helm install --debug --dry-run 
--name jenkins .
```

## test case 2: Only setting FsGroup does not make sense - results into runAsUser: 0
```
helm install --debug --dry-run \
--set Master.FsGroup=1000 \
--name jenkins .
```

## test case 3: Valid input - results into runAsUser: 1000
```
helm install --debug --dry-run \
--set Master.RunAsUser=1000 \
--name jenkins .
```

## test case 4: Valid input - results into runAsUser: 1000 and fsGroup: 1000
```
helm install --debug --dry-run \
--set Master.RunAsUser=1000 \
--set Master.FsGroup=1000 \
--name jenkins .
```

**Comment by ghost** [comment]
I have signed the CLA

**Review by timstoop — APPROVED** [review]
Just one question, is there a good reason to not make this the default? Can that be documented?

**Comment by ghost** [comment]
@timstoop Sure, I'd like to make it the default. 
The only reason to NOT make it the default, is not to change the current behavior.

**Comment by timstoop** [comment]
Agreed, but that wouldn't really break anything, would it?

**Comment by ghost** [comment]
@timstoop : Hello Tim, it wouldn't break anything when installing the helm chart from "scratch" (new Jenkins instance with new persistent volume).
For those that are having Jenkins already running with the current chart (as root user with uid=0) and who want to "upgrade" to new chart version it will be a breaking change: They have to explicitly set RunAsUser and FsGroup to 0 or change all file permissions on the persistent volume (/var/jenkins_home) from root to jenkins.

I'll prefer making RunAsUser=1000 and FsGroup=1000 the default from security perspective.
What do you think? If you agree, I'll change the PR.

**Comment by viglesiasce** [comment]
Apologies for the delay @gippimania! And thank you very much for the contrib.

**Pull request merged**
