### PR TITLE
[stable/prometheus-node-exporter] Add options to change volume mount propagation 

### PR DESCRIPTION
**Pull request by kaarolch**
Signed-off-by: Karol Chrapek <kaarol@it-flow.pl>

#### What this PR does / why we need it:
This PR allow to mount volume inside node exporter with `rslave` option - in kubernetes [mountPropagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation). This is useful when you would like to monitoring dynamic mounting volumes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kaarolch** [comment]
@cpanato or @gianrubio do you have any concern regaring `mountPropagation`?

**Comment by kaarolch** [comment]
@gianrubio any chance to merge this PR?

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
