### PR TITLE
[stable/grafana] Fix issue with literal (|) being added to deployment yaml when using extraContainers

### LINKED ISSUE #13986: stable/grafana extraContainer config is broken
**Describe the bug**
When the value extraContainer is used. the chart don't get deployed successfully.
```
YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 104: did not find expected '-' indicator
```
**Version of Helm and Kubernetes**:
k8s: 1.14.1
helm: v2.13.1

**Which chart**:
stable/grafana

**What happened**:

**What you expected to happen**:
The chart should be deployed successful with the extraContainer config

**How to reproduce it** (as minimally and precisely as possible):
enable the extraContainer config 

**Anything else we need to know**:
fixed by changing the templates/deployment.yaml
```diff
--- a/stable/grafana/templates/deployment.yaml
+++ b/stable/grafana/templates/deployment.yaml
@@ -290,8 +290,8 @@ spec:
 {{ toYaml .Values.readinessProbe | indent 12 }}
           resources:
 {{ toYaml .Values.resources | indent 12 }}
-{{- if .Values.extraContainers }}
-{{ toYaml .Values.extraContainers | indent 8}}
+{{- with .Values.extraContainers }}
+{{ tpl . $ | indent 8 }}
 {{- end }}
     {{- with .Values.nodeSelector }}
       nodeSelector:
```

### PR DESCRIPTION
**Pull request by mlamanuzzi**
Signed-off-by: Michael Lamanuzzi <mlamanuzzi@walmart.com>

No
#### What this PR does / why we need it:
When using extraContainers configuration, a literal pipe is added to the deployment yaml output when following the example provided in values.yaml.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #13986
Note: this fix was already proposed by @HaveFun83

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@mlamanuzzi 
Could you bump the chart again please? Thank you.

**Comment by ldealmei** [comment]
This fix broke my working configuration. I am not too sure what the reason might be. Is it intended to not work with such a configuration?

Here is my configuration:
```yaml
# ...
extraContainers:
- name: grafana-image-renderer
  image: grafana/grafana-image-renderer:1.0.7
  ports:
    - name: image-renderer
      containerPort: 8081
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
# ...
```

and the error I get:

```sh
Linting release=grafana, chart=/var/folders/x_/rxt_0rrj1tb08pp2cf7f2mp00000gn/T/140727471/grafana/latest/stable/grafana/grafana
==> Linting /var/folders/x_/rxt_0rrj1tb08pp2cf7f2mp00000gn/T/140727471/grafana/latest/stable/grafana/grafana
[ERROR] templates/: render error in "grafana/templates/deployment.yaml": template: grafana/templates/deployment.yaml:48:10: executing "grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: grafana/templates/_pod.tpl:279:7: executing "grafana.pod" at <.>: wrong type for value; expected string; got []interface {}
```

**Pull request merged**
