### PR TITLE
[stable/rabbitmq] fix Error: enoent with forceBoot on new install (see #13485)

### PR DESCRIPTION
**Pull request by denis111**
#### What this PR does / why we need it:
It fixes Error: enoent on new installs with forceBoot enabled, see https://github.com/helm/charts/issues/13485#issuecomment-498730132

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
completes #13485 

#### Special notes for your reviewer:
Also corrected type with ")" char in README,md 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks so much for the fix!

**Comment by juan131** [comment]
Hi @denis111 

Could you rebase from master and bump the version of the Chart.yaml again? It seems there was a patch release since you created the PR

**Comment by denis111** [comment]
@juan131 I updated the PR yesterday

**Pull request merged**
