### PR TITLE
[stable/jenkins] added changelog

### LINKED ISSUE #16324: stable/jenkins Changelog
**Describe *in detail* the feature/behavior/change you'd like to see.**
As I can't find the changelog it would be a good idea to add one. I'm using one of the old charts and as I want to update Jenkins I would like to know what changed.

The problem is when updating release there is no way of knowing what exactly changed.

**Describe the solution you'd like**
A simple changelog.md file would be enough.

**Describe alternatives you've considered**
An alternative would be to check https://github.com/helm/charts/commits/master/stable/jenkins or diff charts but it would take too long.

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

It adds a change log to the README

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #16324

#### Special notes for your reviewer:

I added the commit columns for the auto generated change log. We can't maintain it within PRs as the merge commit isn't known when creating the PR.

Therefor I am unsure if we should keep or remove that column. For the existing changes it might help to improve the change log as it's easier to find the commit.

I used this script to generate the initial change log and did some manual changes afterwards:
```
#!/usr/bin/env bash

git log --abbrev-commit --pretty=oneline stable/jenkins/ | while read line ;
do
  read -r commit message <<< "$line"
  version=$(git show $commit:stable/jenkins/Chart.yaml|grep "version:"|sed 's/version: //')
  printf "| %6s | %s | %s |\n" $version $commit "$message"
done
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
have you looked at existing changelogs in other charts?
stable/ambassador/CHANGELOG.md
stable/concourse/CHANGELOG.md
stable/falco/CHANGELOG.md
stable/gocd/CHANGELOG.md
stable/sysdig/CHANGELOG.md
stable/logdna-agent/CHANGELOG.md

**Comment by torstenwalter** [comment]
@maorfr Thanks for the pointer. I updated the change log and added a note that it's auto generated. So for sure it's not as good as a manually crafted change log, but better then nothing as a starting point.

**Comment by maorfr** [comment]
Very nice work!

**Pull request merged**
