### PR TITLE
[stable/prometheus-operator] add support for pod annotations

### PR DESCRIPTION
**Pull request by bpehling**
Signed-off-by: Ben Pehling <shinjipehling@gmail.com>

#### What this PR does / why we need it:
Adds support for pod annotations for the prometheus operator pod. This is important for annotations that are needed at the pod scope (ie. `sidecar.istio.io/inject: "false"`)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@bpehling Could you please document this in the README.md as well?

**Comment by bpehling** [comment]
> @bpehling Could you please document this in the README.md as well?

@vsliouniaev README.md updated

**Comment by vsliouniaev** [comment]
I cannot ok-to-test but if you force push it will reset the lgtm state, which may let me bypass by lgtm-ing again

**Comment by bpehling** [comment]
@vsliouniaev done

**Pull request merged**
