### PR TITLE
[stable/dex] Add imagePullSecrets

### PR DESCRIPTION
**Pull request by mujx**
#### What this PR does / why we need it:
Enables usage of private docker registry.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vi7 — CHANGES_REQUESTED** [review]
Hi @mujx ,
thank you for the PR. Please update documentation (README.md) and default values of the Chart (values.yaml) with the new parameter.

Also you need to bump minor ver of the chart and not the patch ver

**Comment by mujx** [comment]
@vi7 Updated the PR.

**Review by vi7 — APPROVED** [review]

**Pull request merged**
