### PR TITLE
Adding a CI check for the NOTES.txt file

### PR DESCRIPTION
**Pull request by mattfarina**
Points to docs when file missing to point user to a fix

Ref #2373

### CODE REVIEW

**Comment by prydonius** [comment]
We may also want to move this check to the `helm lint` command given that it's a best practice @mattfarina. Thoughts?

**Comment by mattfarina** [comment]
@prydonius is it a best practice? I don't see it in the [best practices guide](https://docs.helm.sh/chart_best_practices/). Is it a best practice for everyone or a requirement of this repo?

I think we should merge this in here. If this is a best practice we can make a change to helm. Once `helm lint` has that change we can remove the custom check here.

Is NOTES.txt as a best practice a good talk for the charts and helm calls?

**Comment by prydonius** [comment]
@mattfarina agree that it should be discussed in one of the calls, I personally feel it is a best practice, but there are also cases when NOTES.txt is not necessary (e.g. very small tools, internal things that have documentation elsewhere). Will merge this for now.

**Pull request merged**
