### PR TITLE
Add k8s-spot-termination-handler chart

### LINKED ISSUE #6: Helm chart
Contributing a Helm chart to https://github.com/kubernetes/charts

### PR DESCRIPTION
**Pull request by QuingKhaos**
#### What this PR does / why we need it:

Adds a chart for the [K8s Spot Termination handler](https://github.com/pusher/k8s-spot-termination-handler) which watches the AWS metadata service when running on Spot Instances.

#### Which issue this PR fixes

  - fixes pusher/k8s-spot-termination-handler#6
  - recreated cause #8902 was closed by the bot :sweat_smile: 

#### Special notes for your reviewer:

Could this go already straight to stable?

I hope the `OWNERS` file is ok/correct/allowed?

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
We already have this, no?

https://github.com/helm/charts/tree/master/stable/k8s-spot-termination-handler

It's missing a readme though. Maybe you could create a PR to update that chart? Would be faster anyway as it seems PRs to add new charts are taking 30-60 days to be reviewed and merged.

**Comment by EmiiKhaos** [comment]
Oooooooooooooh, didn't checked the repo between the last PR and simply recreated it :see_no_evil: 

Will create a proper new PR :)

**Comment by EmiiKhaos** [comment]
@max-rocket-internet see #10496

**Pull request closed without merging**
