### PR TITLE
[stable/k8s-spot-termination-handler] add security context definition

### PR DESCRIPTION
**Pull request by alemairebe**
#### Is this a new chart
NO

#### What this PR does / why we need it:
When using a PSP preventing use of root user we have to set a security policy as image set user in a non-decimal form: https://stackoverflow.com/questions/49720308/kubernetes-podsecuritypolicy-set-to-runasnonroot-container-has-runasnonroot-and

#### Which issue this PR fixes
Didn't checked

#### Special notes for your reviewer:
It fixes my issue, I hope it will fixes others as well.
@KierranM @egeland @mariusv 
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mariusv** [comment]
LGTM
/ok-to-test

**Comment by alemairebe** [comment]
/lgtm
is the command this bot is waiting for :-)

**Comment by mariusv** [comment]
heh, you are right...was doing multiple approvals in other projects :-))

/lgtm

**Pull request merged**
