### PR TITLE
[stable/prometheus-operator] Conditional cAdvisor metrics for kubelet's serviceMonitor

### PR DESCRIPTION
**Pull request by VLZZZ**
#### What this PR does / why we need it:
cAdvisor endpoint is [deprecated in kubelet since 1.15](https://github.com/kubernetes/kubernetes/issues/68522).
But we need an ability to conditionally control this section of serviceMonitor for clusters which a in transition phase - having separate cAdvisor daemonset with own serviceMonitor, in this case we're doubling the metrics.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by VLZZZ** [comment]
May someone take a look at the tests please?
@vsliouniaev @bismarck 
```
I0330 17:44:25.800] Deleting release 'prometheus-operator-n8nkn79bmn'...
I0330 17:44:36.775] release "prometheus-operator-n8nkn79bmn" deleted
I0330 17:44:36.799] Deleting namespace 'metheus-operator-presubmit-21653-1244680922532417543-n8nkn79bmn'...
I0330 17:44:37.363] namespace "metheus-operator-presubmit-21653-1244680922532417543-n8nkn79bmn" deleted
I0330 17:44:44.069] Namespace 'metheus-operator-presubmit-21653-1244680922532417543-n8nkn79bmn' terminated.
I0330 17:44:44.069] Error linting and installing charts: Error processing charts
I0330 17:44:44.069] ------------------------------------------------------------------------------------------------------------------------
I0330 17:44:44.070]  âœ–ï¸Ž prometheus-operator => (version: "8.12.4", path: "stable/prometheus-operator") > Error waiting for process: exit status 1
I0330 17:44:44.070] ------------------------------------------------------------------------------------------------------------------------
I0330 17:44:46.327] 1ad1ac57f712dbcbd7d5bcd18cf4930bdf10b66da197c2704b87accab32ce83f
W0330 17:44:46.375] Traceback (most recent call last):
W0330 17:44:46.375]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0330 17:44:46.376]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0330 17:44:46.376]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0330 17:44:46.376]     check(*cmd)
W0330 17:44:46.376]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0330 17:44:46.376]     subprocess.check_call(cmd)
W0330 17:44:46.377]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0330 17:44:46.377]     raise CalledProcessError(retcode, cmd)
W0330 17:44:46.377] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0330 17:44:46.377] Command failed
I0330 17:44:46.378] process 639 exited with code 1 after 3.2m
E0330 17:44:46.378] FAIL: pull-charts-e2e
```

**Comment by vsliouniaev** [comment]
Could you please bump the chart version? Looks like the test cluster has been fixed

**Comment by VLZZZ** [comment]
@vsliouniaev Sure, done, thank you!

**Pull request merged**
