### PR TITLE
[new feature] Also apply ACLS to topics

### PR DESCRIPTION
**Pull request by stevie-**
**What this PR does / why we need it**:
Also apply ACLs to topics, if set.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes issue with shell not support `(( count++ ))`

### CODE REVIEW

**Comment by cpanato** [comment]
@stevie- please bump the chart version

**Comment by stevie-** [comment]
@cpanato done. Thanks

**Comment by davidkarlsen** [comment]
New feature so increase mionor version

**Comment by stevie-** [comment]
@davidkarlsen I've increased to 0.9.3 when I created the pull request. but test failed with a chart version error (I assume form build.log). So I checked master, and master updated to 0.9.3 in the meantime. I bumped the version again to 0.9.4. Which version is the correct one to set?

Due to my changes labels got removed. So you may need to add /lgtm again.

**Pull request closed without merging**
