### PR TITLE
[stable/dex] Add initContainers support

### PR DESCRIPTION
**Pull request by mhrabovcin**
#### What this PR does / why we need it:

It adds an option to run `initContainers` (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) when deploying `dex` chart.

#### Special notes for your reviewer:

@desaintmartin could you please review this small change.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md (there is no readme file)
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks!
Could you rebase?
/ok-to-test

**Comment by mhrabovcin** [comment]
@desaintmartin I've rebased to master branch.

**Comment by vi7** [comment]
@mhrabovcin README has been finally added to this chart so could you please document the parameter you've introduced in this PR (initContainers). Also as far as your changes are user facing could you please update a minor version of the chart (rather than patch version)

**Comment by zanhsieh** [comment]
@mhrabovcin 
Could you resolve the conflict file again please? Thank you.
stable/dex/Chart.yaml

**Pull request merged**
