### PR TITLE
Update Zookeeper dependency

### PR DESCRIPTION
**Pull request by alexvicegrab**
Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

**What this PR does / why we need it**:

Updating Zookeeper dependency to latest stable Zookeeper. This means that resources are not automatically assigned (e.g. memory: 4Gi, cpu: 1) at startup.

**Special notes for your reviewer**:

N/A

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@alexvicegrab because this is a major version bump (0.5.0 -> 1.X.X) there are changes in values.

`heap` -> https://github.com/kubernetes/charts/blob/master/incubator/zookeeper/values.yaml#L241
`imagePullPolicy` -> https://github.com/kubernetes/charts/blob/master/incubator/zookeeper/values.yaml#L26
`port` -> https://github.com/kubernetes/charts/blob/master/incubator/zookeeper/values.yaml#L37
 - this will require changes in our templating for url  override for zookeeper as well

**Comment by alexvicegrab** [comment]
@benjigoldberg, OK, will update chart to address `heap`, `imagePullPolicy` and `port`.

For the URL override, I assume this will need updating the `zookeeper.port`

**Comment by alexvicegrab** [comment]
Regarding `port`, this is only used for the case where Zookeeper is not installed with the chart but specified separately, otherwise service discovery is used.

**Comment by alexvicegrab** [comment]
@benjigoldberg, updated pullPolicy and the JVM heap as an environmental variable override with same values as before. Also updated docs.

**Comment by benjigoldberg** [comment]
@alexvicegrab looks good 👍 

Waiting for tests to pass

**Comment by benjigoldberg** [comment]
\lgtm

**Pull request merged**
