### PR TITLE
[fluentd-elasticsearch] Review  fluentd sources position file

### PR DESCRIPTION
**Pull request by gianrubio**
**What this PR does / why we need it**:

Not all the fluentd sources had pos_file configured. The consequence is that when fluentd crash/restart it pushes all the logs again.

@monotek

### CODE REVIEW

**Comment by monotek** [comment]
👍

**Comment by NicolasT** [comment]
Confirmed to be an issue, https://github.com/scality/metal-k8s/issues/62#issuecomment-405040779

**Comment by monotek** [comment]
chart version needs to be bumped too.

**Comment by mattfarina** [comment]
/lgtm

I'm assuming @monotek is ok with this because the last feedback was to bump the version but no complaints.

**Comment by unguiculus** [comment]
The chart was moved to stable in #6925.

**Comment by mattfarina** [comment]
@unguiculus oops. Thanks for catching that. I removed the approved as well.

**Comment by monotek** [comment]
I've added the change to my pr already so should not be necessary to add it again...

**Comment by viglesiasce** [comment]
Fixed in #6925

**Pull request closed without merging**
