### PR TITLE
Opa/conf change

### PR DESCRIPTION
**Pull request by tlm**
#### What this PR does / why we need it:
When using helm to generate the webhook certificate's for kubernetes subsequent helm upgrades produce new certificates. OPA needs to be restarted in this case to use the CA that Kube APIServer is expecting.

#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by tlmiller** [comment]
Still hoping to get this included

**Comment by timothyhinrichs** [comment]
Version on this needs to be updated

**Comment by tlmiller** [comment]
Thanks @timothyhinrichs all done.

**Comment by kfox1111** [comment]
I've been a little concerned with the general tls cert approach of helm when it comes to validating/mutating web hooks. I think it will end up updating the ca key potentially before any of the backend pods are updated, leading to a cluster that could potentially not validate anymore. I think the cert-manager approach is much more stable to these sorts of issues as the ca doesn't change with the workload. This change does make that potential issue a bit less likely though, so probably a good change to do anyway, if helm managed tls is to be left in place.

**Comment by simonklb** [comment]
This should've been `{{- if or .Values.generateAdmissionControllerCerts .Values.opa }}` no? Not using the embedded opa config (by setting `opa: false`) should not impact the cert generation, or am I missing something?

**Comment by tsandall** [comment]
@simonklb that looks like it's the case. Could you submit a PR to update the conditional?

**Comment by tlmiller** [comment]
@tsandall @simonklb Started #15985 to fix this. Sorry for the bug

**Pull request merged**
