### PR TITLE
[stable/grafana] Fix statefulset grafana service

### PR DESCRIPTION
**Pull request by muwon**
Signed-off-by: Muwon Lum <muwonone@gmail.com>

#### Is this a new chart
No

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR is intended to fix:
- Duplicate service (service and headless-service) definitions when persistence is enabled and persistence type is set to 'statefulset'
- Allow to use 'NodePort' service type with statefulset

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by muwon** [comment]
Re-ran 'pull-charts-e2e' test and full test.  It kept failing at deleting the test namespace.  My local test and lint worked fine.  Can someone help take a look at the namespace deletion issue?

**Comment by zanhsieh** [comment]
@muwon 
Could you resolve the chart conflict please? I will work with helm member if the e2e test fails again. Sorry for waiting.
stable/grafana/Chart.yaml

**Pull request closed without merging**
