### PR TITLE
[stable/prometheus-operator] add resources field to admissionWebhooks jobs

### PR DESCRIPTION
**Pull request by sjentzsch**
#### What this PR does / why we need it:

Currently the admissionWebhooks jobs (both `job-createSecret.yaml` and `job-patchWebhook.yaml`) of prometheus-operator do not allow for configurable resource requests and limits. This PR adds the capability, and also updates the README accordingly.
With this, all pods should now have configurable resource sections.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@sjentzsch
I think you might need to resolve Chart.yaml conflict.

**Comment by sjentzsch** [comment]
@zanhsieh done.

**Comment by zanhsieh** [comment]
@vsliouniaev
@bismarck
Could you guys LGTM this PR please? Thank you.

**Comment by vsliouniaev** [comment]
/lgtm

Not _really_ certain that there's a use for this outside of some restricted environments where specifying resources is mandatory.

**Comment by sjentzsch** [comment]
> /lgtm
> 
> Not _really_ certain that there's a use for this outside of some restricted environments where specifying resources is mandatory.

Exactly that's our use case.

**Pull request merged**
