### PR TITLE
[stable/wordpress] Explicitly unset nodePort when service is ClusterIP

### PR DESCRIPTION
**Pull request by adtennant**
#### What this PR does / why we need it:
This allows the Helm release to be switched between LoadBalancer and ClusterIP without getting the following error:
```
Service "wordpress" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @adtennant 

I was unable to reproduce the issue you're trying to solve:

```bash
$ helm repo update
$ helm install stable/wordpress --set service.type=ClusterIP --name wordpress
$ kubectl get svc wordpress-wordpress -o json | jq .spec.ports
[
  {
    "name": "http",
    "port": 80,
    "protocol": "TCP",
    "targetPort": "http"
  },
  {
    "name": "https",
    "port": 443,
    "protocol": "TCP",
    "targetPort": "https"
  }
]
```


On the other hand, please note that you need to sign every commit to pass the DCO tests.

**Comment by adtennant** [comment]
@juan131 You should be able to reproduce with the following:

```
helm install stable/wordpress --name wordpress
helm upgrade --set service.type=ClusterIP wordpress stable/wordpress
```

**Comment by juan131** [comment]
Thanks for providing the detailed command! I'm able to reproduce the issue now!

**Review by juan131 — APPROVED** [review]
I'm approving the changes, but please rebase your branch from master and update it so we can proceed with the merging process!

**Pull request closed without merging**
