### PR TITLE
[stable/dex] OWNERS list updated

### PR DESCRIPTION
**Pull request by vi7**
#### What this PR does / why we need it:

Added myself to the list of owners as discussed with @desaintmartin 

#### Which issue this PR fixes

n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vi7** [comment]
/assign @desaintmartin 

please review

**Comment by vi7** [comment]
Hi @desaintmartin 

Please advise how could I fix that:

> The following users are mentioned in OWNERS file(s) but are not members of the helm org.
> 
> * vi7
>   
>   * stable/dex/OWNERS
>   * stable/dex/OWNERS

**Comment by kfox1111** [comment]
You don't need to bump the chart version to add yourself to owners.

**Comment by desaintmartin** [comment]
> You don't need to bump the chart version to add yourself to owners.

AFAIK, I think you do, otherwise test will fail (a chart is immutable, and OWNERS is part of the chart)

**Comment by desaintmartin** [comment]
> You don't need to bump the chart version to add yourself to owners.

AFAIK, I think you do, otherwise test will fail (a chart is immutable, and OWNERS is part of the chart)

/approve

@vi7, we need you to get added to the Helm org as a collaborator. I've just asked in the #charts channel of the k8s slack.

Please also add yourself in Chart.yaml. I'll add myself there in a subsequent PR.
@kfox1111 @sstarcher @rendhalver I don't see you in the OWNERS but I see you in the Chart.yaml, do you want to get added or get removed?

**Comment by prydonius** [comment]
just invited @vi7 to be a collaborator on the repo

**Comment by vi7** [comment]
> You don't need to bump the chart version to add yourself to owners.

CI is failing unless you do so

**Comment by vi7** [comment]
> Please also add yourself in Chart.yaml.

@desaintmartin done

**Pull request merged**
