### PR TITLE
Fix regression by pr #13000

### PR DESCRIPTION
**Pull request by kfox1111**
This reverts the incorrect patch merged as part of pr #13000 as
well as adds warnings so that hopefully this never happens again.

### CODE REVIEW

**Comment by maorfr** [comment]
Did you accept the invite?

**Comment by hectorj2f** [comment]
LGTM

**Comment by maorfr** [comment]
@kfox1111 you should be able to do ok-to-test

**Comment by kfox1111** [comment]
> Did you accept the invite?

Just did. thanks.

/ok-to-test

**Pull request merged**
