### PR TITLE
[stable/prometheus-operator] Use disableCompaction value

### LINKED ISSUE #21290: [stable/prometheus-operator] Prometheus CRD storage spec metadata ignored in upgrades, creates new PVC
**Describe the bug**
On upgrade from version 8.3.3 to 8.7.0, we discovered that a new PVC was created instead of using the PVC prior to upgrade. Looking at the Prometheus resource, we noticed that the `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata` field was set to empty, ignoring our configs (we set `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata` to have a `name` field).
e.g.
```
kubectl get prometheus -oyaml
...
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
...
```

It looks like maybe we can tie this bug back to https://github.com/helm/charts/pull/20419, which introduced a change in the CRD to use the standard object's metadata.

**Version of Helm and Kubernetes**:
Helm v2.16.1
Kubernetes v1.16.4

**Which chart**:
stable/prometheus-operator

**What happened**:
New PVC was created (different name) and used by Prometheus

**What you expected to happen**:
Expected previously-created PVC to be used. This resulted in Prometheus using a new PV which meant old data wasn't getting shown.

**How to reproduce it** (as minimally and precisely as possible):
Upgrade the chart from 8.3.3 to 8.7.0 passing in the following (example) values to set the metadata name field
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: test
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gracedo**
#### What this PR does / why we need it:
Bug fix. Currently the `prometheusSpec.prometheus.disableCompaction` option is not getting passed through to the operator.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/helm/charts/issues/21290

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
Could you please bump the chart version? Looks like the test cluster has been fixed
/lgtm

**Comment by vsliouniaev** [comment]
> I0403 09:20:25.939] Error: incompatible versions client[v2.16.5] server[v2.15.2]

😮

/retest

**Comment by gracedo** [comment]
woops, tagged the wrong "fixes" issue - this PR actually fixes this one https://github.com/helm/charts/issues/21135

**Pull request merged**
