### PR TITLE
[stable/jenkins] allow running sidecar containers for Jenkins master

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

It allows to run sidecar containers next to Jenkins master. One use case is [triggering builds with webhooks behind a secure firewall](https://jenkins.io/blog/2019/01/07/webhook-firewalls/#triggering-builds-with-webhooks-behind-a-secure-firewall).

[Smee client](https://smee.io/) could ne run as sidecar container next to Jenkins, which would allow it to forward Webhooks via localhost.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by torstenwalter** [comment]
@maorfr Could you have a look at this?

**Comment by maorfr** [comment]
Sure!

Do you think we can avoid having the entire manifest inside `values.yaml`?

**Comment by torstenwalter** [comment]
It's probably possible, but that would possibly limit it to a single sidecar and we need to be prescriptive to which options one could set.

For a simple sidecar this would be enough within `values.yaml`:
```
  SidecarContainers:
   - name: smee
     image: docker.io/twalter/smee-client:1.0.2
```

**Comment by maorfr** [comment]
At this moment, do you see any additional use cases?

If not, due to this chart's complexity, I would suggest to keep it simple...
If we find additional use cases in the future, this ability can be added.

What do you think?

**Comment by torstenwalter** [comment]
In the past I also had to run a prometheus exporter running as sidecar container reporting the number of files and other metrics. That would already makes two use cases.

Not sure if webhooks from GitHub and GitLab could be handled with the same sidecar conatainer.

**Comment by maorfr** [comment]
Add ability to trigger builds with webhooks behind a secure firewall would make an awesome feature!

I don't think that it needs to be anything else at all, it is good enough on its own ;)

**Comment by torstenwalter** [comment]
I could add another PR just for the webhook part. That way there would be an easy configuration option for webhook trigger and one this one for other sidecar use cases like metric exporter.

**Comment by maorfr** [comment]
I'll approve this PR :)
I do suggest that you add documentation about what this example does, as this is the use case that drove you to add this ability.

**Comment by maorfr** [comment]
One more comment:
The docker repo is not automated and not documented, which may deter users from using it. Can this be adressed?

**Comment by torstenwalter** [comment]
sure it was just meant as an example, but I'll add an automated build for it.

**Comment by torstenwalter** [comment]
Automated build on docker hub: https://hub.docker.com/r/twalter/smee-client/builds
GitHub repo for the docker image: https://github.com/torstenwalter/smee-client

**Pull request merged**
