### PR TITLE
Bump Drupal image version to 8.2.3-r0

### PR DESCRIPTION
**Pull request by juan131**
- Bump Drupal image version to 8.2.2-r2
- Fixed security issues (Ref DRUPAL-CORE-2016-005).

### CODE REVIEW

**Comment by juan131** [comment]
@k8s-bot ok to test

**Comment by juan131** [comment]
I signed it!

**Comment by juan131** [comment]
I signed it!

**Comment by prydonius** [comment]
Manually tested and this lgtm

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@k8s-bot e2e test this

**Pull request merged**
