### PR TITLE
[incubator/distribution] Deprecating incubator chart

### PR DESCRIPTION
**Pull request by jainishshah17**
**What this PR does / why we need it**:
Promoting chart to the stable repo https://github.com/helm/charts/pull/6337
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Strange - and probably unrelated to this deprecation - but still worth a look - it seems like the readinessprobe is failing, see: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/helm_charts/7155/pull-charts-e2e/12488/?log#log

**Comment by jainishshah17** [comment]
@davidkarlsen Maybe just timing issue.

**Comment by davidkarlsen** [comment]
maybe have a test values.yaml with increased values? (or increase the defaults?) See https://github.com/helm/charts/blob/master/test/README.md

**Comment by jainishshah17** [comment]
@davidkarlsen It's not configurable.

**Pull request merged**
