### PR TITLE
[stable/influx] Add support for pod affinities and tolerations

### PR DESCRIPTION
**Pull request by azhelev**
Signed-off-by: Atanas Zhelev <azhelev+github@mailbox.org>

#### What this PR does / why we need it:
Adds support for pod affinities and tolerations  

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by azhelev** [comment]
@jackzampolin  please take a look at this one

**Comment by azhelev** [comment]
Rebased on top of current master.
/assign @jackzampolin

**Review by paulczar — CHANGES_REQUESTED** [review]
these new values should also be documented in the README for the chart.

**Pull request merged**
