### PR TITLE
stable/prometheus: Add service session affinity

### PR DESCRIPTION
**Pull request by nicholascapo**
Add `sessionAffinity` to the Prometheus Server and Alertmanager services.
@mgoodness @gianrubio 

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@nicholascapo 
Could you bump the chart version to latest please? Thank you.

**Comment by nicholascapo** [comment]
@zanhsieh Done

**Pull request merged**
