### PR TITLE
[stable/gcloud-endpoints] #1785 namespace defined templates with char…

### PR DESCRIPTION
**Pull request by kevinschumacher**
…t name
#1785

### CODE REVIEW

**Comment by kevinschumacher** [comment]
@dhilipkumars the tests are failing because the `.Values.image` url is no longer valid. I have submitted a PR to fix that here: https://github.com/kubernetes/charts/pull/2321

**Comment by dhilipkumars** [comment]
cc: @ultimateboy could you suggest? The CI fails as the image seems to be invalid anymore.

**Comment by dhilipkumars** [comment]
@kubernetes/charts-maintainers Im going to merge this inspite of failing test, the chart is resonably un- maintained.

**Comment by unguiculus** [comment]
No idea why this still fails.

**Comment by unguiculus** [comment]
@ultimateboy Could you have a look at this?

**Comment by dhilipkumars** [comment]
Should we just ignore this chart and move on ?

**Comment by mattfarina** [comment]
Do we need to increase the build time?

/retest

**Comment by unguiculus** [comment]
Increasing the timeout won't help. The pods don't come up.

```
I0116 16:04:27.748] gcloud--4730-gcloud-endp-d46c784cf-wvz2w   0/1       CrashLoopBackOff   6         9m
```

If @ultimateboy does not react, I'd deprecate the chart. The chart was alread broken which was revealed in this PR.

**Comment by timstoop** [comment]
/retest
I'm going to assume nothing has really changed here, so if this test fails again, I'm going to start the process of deprecating the chart, as described in https://github.com/kubernetes/charts/blob/master/PROCESSES.md.

**Pull request closed without merging**
