### PR TITLE
[stable/gcloud-sqlproxy] Allow specifying more than one instance.

### PR DESCRIPTION
**Pull request by jgoclawski**
Useful when you want the proxy to serve multiple instances on different ports.

I'm bumping chart version to 0.3.0 as this is a breaking change.

### CODE REVIEW

**Comment by jgoclawski** [comment]
/assign @seanknox
cc: @rimusz

**Comment by jgoclawski** [comment]
I have rebased to master and the tests pass. Please let me know if there's anything blocking this PR from getting merged.

**Comment by unguiculus** [comment]
cc @rimusz

**Pull request merged**
