### PR TITLE
[stable/prometheus-operator] Bump prometheus-operator version to 0.41.0

### PR DESCRIPTION
**Pull request by sev3ryn**
#### Is this a new chart
No
#### What this PR does / why we need it:
Bump docker image tags for

* prometheus
* prometheus-config-reloader

Update prometheus-operator CRDs to 0.41.0

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mrueg** [comment]
@sev3ryn thanks for your PR!
A few comments:
* Can you also update configmap-reload image to v0.4.0 (changed in v0.41.0)?
* Can you include TLS support for prometheus-operator (added in v0.39.0)? This might allow us to deprecate the tlsProxy.

**Comment by sjentzsch** [comment]
Thanks for the PR! Looking forward to it. My concerns:

- need to add `probes` to prometheus-operator/clusterrole.yaml (why is there a duplicated entry of `podmonitors`? Could be a good opportunity to replace it)
- shouldn't we bump the version of the chart to a new major one? 10.x? From the release log of prometheus-operator, we now depend on "kubernetes v1.16 or newer", right?
- would be awesome to incorporate the `clusterAdvertiseAddress` now: https://github.com/coreos/prometheus-operator/pull/3160 (otherwise, I will file a MR)

**Comment by sev3ryn** [comment]
@mrueg I've bumped version of configmap-reload image. Regarding TLS support - maybe it worth doing it as separate PR, to not wait a long for probes support to be merged. What do you think?

Otherwise me how do you see adding TLS configs and values like tls-min-version, tls-cipher-suites - certs in a secret and other as helm values?

**Comment by mrueg** [comment]
Thanks! Sure, there can be a follow-up PR to support that as well. I think eventually cert/key should be in a secret similar to tlsProxy currently and the rest simply be values.

**Comment by sev3ryn** [comment]
@sjentzsch thanks for your findings, 

fixed prometheus-operator/clusterrole.yaml
> From the release log of prometheus-operator, we now depend on "kubernetes v1.16 or newer", right?

Yes, you are correct - you opened my eyes why this was not updated to v0.39.0 before :(
This will probably lead to lots of modifications, unfortunately - e.g. `templates/prometheus/rules` and `hack` will be no longer needed. What do you suggest to do? wouldn't it impact lots of chart users?

**Comment by sjentzsch** [comment]
@sev3ryn I would suggest to start the 10.x version, and add a note to the README. In my opinion, there is only one way to go (which is forward), and all proper chart users should pin the version anyway, so by opening a 10.x we should be fine. However, I am not one of the core maintainers, would be good to have another opinion too.
If we go that way, indeed, I would support removing `templates/prometheus/rules` and `hack`.

**Comment by sev3ryn** [comment]
@sjentzsch As I understand `clusterAdvertiseAddress` should be unique for each replica and this is not possible to do because `templates/alertmanager/alertmanager.yaml` you set values for all the replicas at once

**Comment by sjentzsch** [comment]
@sev3ryn Yes indeed, that would be an optional setting; by default it definitely has to be unset. It's just, I would require it for a use case I have (with alerting cluster spanned across two kubernetes clusters), thus I would need the option to set it. However, not necessarily within this MR.

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to prometheus-operator for a short time until https://github.com/prometheus-community/community/issues/28#issuecomment-672933972 is resolved. If you want to help with that effort, to test etc, that would be great!

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
