### PR TITLE
[stable/jenkins] make deploymentAnnotation configurable

### PR DESCRIPTION
**Pull request by LeoQuote**
#### What this PR does / why we need it:
add an additional deploymentAnnotation for jenkins master deployment.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@LeoQuote You need to increase the chart version. Could you also add an entry in CHANGELOG.md?

Change itself looks good.

**Comment by LeoQuote** [comment]
Thanks for your reply, I’ll do it later.

**Comment by LeoQuote** [comment]
/assign @mogaal

I've bumped version and changed changelist @torstenwalter

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Pull request merged**
