### PR TITLE
[stable/prometheus-adapter] Add myself to OWNERS

### PR DESCRIPTION
**Pull request by steven-sheehy**
#### What this PR does / why we need it:
There's a lot of open PRs for this chart that aren't being approved. After the call for maintainers, I thought I might offer up my help for this chart. Adds an OWNERS file, adds myself to it and existing chart maintainer from Chart.yaml

#### Which issue this PR fixes
See https://github.com/helm/charts/issues/13867

#### Special notes for your reviewer:
I didn't put my email in the Chart.yaml since I've been getting a lot of spam due to it being in other charts that I maintain. Hope that's OK.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
/cc @MattiasGees
would you like to be added as an OWNER to this chart?

**Comment by maorfr** [comment]
/lgtm

welcome @steven-sheehy !

**Comment by steven-sheehy** [comment]
@maorfr Mind lgtm it again?

**Pull request merged**
