### PR TITLE
[incubator/buzzfeed-sso] Fix wrong proxy container port

### PR DESCRIPTION
**Pull request by anas-aso**
#### What this PR does / why we need it:
Due to the wrong container port, the proxy ingress will always sees the backend as unhealthy since the health check endpoint will be `/` instead of `/ping`. This issue is only visible on GKE as described here : https://stackoverflow.com/questions/44584270/how-to-get-a-custom-healthcheck-path-in-a-gce-l7-balancer-serving-a-kubernetes-i

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by anas-aso** [comment]
@darioblanco can you please have a look at this change ? It's a blocker for us.

**Comment by darioblanco** [comment]
Wow, this was indeed a bug. I had to double and triple check it, as it works perfectly in my set up. I am surprised that the pod wasn't in a restarted loop and would like to investigate more.

I have updated it to the new port in my production cluster, and as expected, it works.

/approve

**Comment by anas-aso** [comment]
@darioblanco the pod won't be in a restart state since the `readinessProbe` and `livenessProbe` are configured correctly. The current chart work perfectly on AWS as well. This issue is only visible on GKE since they rely on named ports to figure out the health check endpoint.

**Comment by anas-aso** [comment]
@darioblanco btw, I guess we will face the issue of `/ok-to-test` on this PR as well, any idea if we can speed up fixing this issue ? I'm more interested in this PR than the other open one (since this is a bug).

**Comment by darioblanco** [comment]
I run this on GKE, that is the surprising fact. Which Kubernetes version do you use?
Regarding the /ok-to-test issue, I should have requested the trusted user role before to be honest, but better late than never :)

Once that one is resolved, I will prioritize merging this MR, I indeed think this one is more important.

And thanks for your contribution!

**Comment by anas-aso** [comment]
@darioblanco any updates ?

**Comment by darioblanco** [comment]
Still no news, awaiting feedback in https://github.com/helm/charts/issues/14682

**Comment by anas-aso** [comment]
@darioblanco is there a way to get a trusted collaborator review this PR ? usually permissions issue take time and I don't expect the issue you opened to be addressed fast enough.

**Comment by darioblanco** [comment]
It took a loooong time to get the `buzzfeed-sso` merged into the repo, even if it was in `incubator` state. They reacted with a twitter message from the community in the past. I think they are overloaded with MRs, and that's why I think the permission issue might be faster.

But who knows, maybe we are lucky and a collaborator with permissions can merge this. You can try pinging them in the slack channel.

**Comment by anas-aso** [comment]
@darioblanco now only the `/lgtm` is required. I hope you can do that 😅

**Comment by komljen** [comment]
Unfortunately no :(
Hm, I think you should be able to do it, did you try?

**Comment by anas-aso** [comment]
@komljen can you please have a look at this PR ?

**Comment by komljen** [comment]
I can, but it will require rebase as well since buzzfeed-sso is changed in master.

**Comment by komljen** [comment]
I think you can just bump the chart version to `0.0.3`.
Master chart is already at `0.0.2`.

**Comment by anas-aso** [comment]
@komljen all green now, we should be able to merge, right ?

**Pull request merged**
