### PR TITLE
[stable/dask] Dask ingress

### PR DESCRIPTION
**Pull request by darkyat**
Signed-off-by: Harald Haas <harald.haas@cloudpilots.com>

#### What this PR does / why we need it:
This PR adds the possibility to expose dask and jupyter ui through an ingress definition. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by darkyat** [comment]
Would be great if you could have a look @danielfrg @mrocklin and sorry for the required force-push at the end.

**Comment by mrocklin** [comment]
cc'ing @beberg , who might know more about what is going on here than I do

**Comment by darkyat** [comment]
@beberg let me know if I should merge those changes together or if there is anything missing/unclear. Thanks!

**Comment by darkyat** [comment]
@beberg @mrocklin wanted to ask if you had any chance to take a look. I have more PRs in the pipeline that would build upon this. Thanks!

**Comment by mrocklin** [comment]
While I know Dask well I do not know Kubernetes or Helm well, so I'm probably not qualified to review this.  

If you have confidence in what you're doing then I would say "go for it".  

cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
This looks reasonable to me.

**Comment by mrocklin** [comment]
@darkyat is there anythin in particular that you need from me in order to move forward here?

**Comment by jacobtomlinson** [comment]
@mrocklin I think you need to allow testing and mark that you are happy to the k8s ci robot using the slash commands. [See an example here](https://github.com/helm/charts/pull/17541#issuecomment-536453645).

**Comment by jacobtomlinson** [comment]
Ooh [looks like I'm also allowed to do things](https://github.com/helm/charts/blob/master/stable/dask/OWNERS) here.

/lgtm
/assign @danielfrg

@danielfrg how does someone go about getting "trusted reviewer" status?

**Comment by jacobtomlinson** [comment]
🤔 that isn't quite what I expected to happen.

**Pull request merged**
