### PR TITLE
bugfix(chart/stable/gitlab-ce): Dependent postgres version was missing ImagePullPolicy on init container

### PR DESCRIPTION
**Pull request by lachie83**
https://github.com/kubernetes/charts/issues/307

### CODE REVIEW

**Review by ravishivt — CHANGES_REQUESTED** [review]
Could you also bump the gitlab-ce version in Charts.yaml?

**Comment by lachie83** [comment]
@ravishivt Good catch. Will do!

**Review by ravishivt — APPROVED** [review]
Looks good!

**Comment by lachie83** [comment]
cc @gtaylor

**Comment by gtaylor** [comment]
LGTM!

**Review by gtaylor — APPROVED** [review]

**Comment by TKCen** [comment]
What is the state on this? Aside from deletion of the chart the tests seem to approve. I guess the issue is the specific behaviour of the chart regarding the host-url setting of gitlab?

**Comment by lachie83** [comment]
@TKCen Just waiting on the maintainers to merge

**Comment by viglesiasce** [comment]
Will merge when I get back to the keyboard. Sorry for the delay

**Pull request merged**
