### PR TITLE
[stable/kiam] Port stable/kiam xlock race bugfix to helm chart

### LINKED ISSUE #9261: [stable/kiam] port xlock race fix to helm chart
This pull request in kiam helps to address xlock race condition issue: https://github.com/uswitch/kiam/pull/180 . Righ now stable/kiam helm chart does not have this flag.

**Version of Helm and Kubernetes**:
k8s 1.12, stable/kiam 2.0.0-rc3

**Which chart**:
stable/kiam

**What happened**:
missing bugfix port

**What you expected to happen**:
bugfix ported

**How to reproduce it** (as minimally and precisely as possible):
more details in original bugfix  https://github.com/uswitch/kiam/pull/180

### PR DESCRIPTION
**Pull request by max-lobur**
Port https://github.com/uswitch/kiam/pull/180 to stable/kiam
Fixes #9261

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@max-lobur could you please add signoff to your commits to make the DCO pass?

**Comment by max-lobur** [comment]
@vsliouniaev thanks for taking a look, done.

**Comment by max-lobur** [comment]
@linki @scottrigby any of you guys have a minute to look please?

**Comment by max-lobur** [comment]
bump

**Comment by max-lobur** [comment]
bump

**Comment by max-lobur** [comment]
@ewbankkit can you take a look pls?

**Comment by max-lobur** [comment]
bump

**Comment by max-lobur** [comment]
rebased

**Comment by max-lobur** [comment]
😍

**Comment by pingles** [comment]
Hi! We've now released `v3.0` so I'd suggest updating the container image to support that. There's a few breaking changes when upgrading from 2.x that are highlighted in https://github.com/uswitch/kiam/blob/master/docs/UPGRADING.md but we'd definitely suggest adopting `v3.0` for new releases.

**Comment by max-lobur** [comment]
I know, I already passed v2->v3 transition with rc1 image.
@pingles you're saying it's an rc1 issue and should not happen in v3 stable?

**Comment by max-lobur** [comment]
oops, wrong thread

**Comment by max-lobur** [comment]
@pingles I believe container image wont solve wrong mount behavior here.

I will make a separate PR to bump image to stable tho

**Comment by ewbankkit** [comment]
@max-lobur , @pingles https://github.com/helm/charts/issues/9790 has been opened to make sure the Helm chart has full support for v3.0.

**Comment by max-lobur** [comment]
bump

**Comment by ewbankkit** [comment]
@max-lobur Could you please resolve the conflict?

**Comment by max-lobur** [comment]
@ewbankkit done

**Comment by max-lobur** [comment]
@paulczar can you please take a look if this can be merged?

**Comment by max-lobur** [comment]
rebased

**Comment by darend** [comment]
We are running into this same issue this PR addresses.

@max-lobur can you rebase 1 more time?
@paulczar can you give a lgtm again?

**Comment by max-lobur** [comment]
rebased

**Comment by max-lobur** [comment]
rebased, bump

**Comment by max-lobur** [comment]
getting a 1 line merged has never been harder :)

**Comment by darend** [comment]
@max-lobur We should move this to [helm-hub](https://helm.sh/blog/intro-helm-hub/). It  would allow the chart to be self-hosted by kiam

**Comment by danmx** [comment]
kiam maintainers are adding their own helm chart: https://github.com/uswitch/kiam/pull/232

**Comment by max-lobur** [comment]
oh a rebellion, cool :D
I'll make sure my change is there then

**Comment by danmx** [comment]
@max-lobur rebellion is going slow so reopening this PR makes sense 😄

**Comment by max-lobur** [comment]
@danmx done

**Comment by danmx** [comment]
@paulczar could you take a look at it again?

**Comment by max-lobur** [comment]
rebased

**Review by linki — APPROVED** [review]

**Comment by max-lobur** [comment]
rebased

**Comment by darend** [comment]
@paulczar / @unguiculus / @lachie83 could one of you give the final approval /lgtm for this PR? Its been open since November and is a very minor change

**Comment by max-lobur** [comment]
rebase

**Comment by darend** [comment]
@maorfr could you help us push this through?

**Comment by maorfr** [comment]
/lgtm

I would consider helm hub, as previously mentioned here.

**Comment by darend** [comment]
Thanks @maorfr !

**Comment by max-lobur** [comment]
🎉

**Pull request merged**
