### PR TITLE
[stable/metabase] Add yachtcaptain23 to as a reviewer and approver

### PR DESCRIPTION
**Pull request by yachtcaptain23**
Signed-off-by: Albert Wang <amwang217@gmail.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
Increase the number of maintainers and reviewers. I'm an employee at a tech startup that uses Metabase deployed on Kubernetes.

#### Special notes for your reviewer:
@pmint93 verbally approved me in https://github.com/helm/charts/pull/22320 as a maintainer.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pmint93** [comment]
Every changes to a chart need version bump. Please bump the chart version

**Comment by yachtcaptain23** [comment]
@maorfr would you be able to assist? Thank you

**Comment by yachtcaptain23** [comment]
@pmint93 would you re-review?

**Comment by pmint93** [comment]
This PR looks good to me and can be merged. But reviewer also need to be added to this repository as read-only user, only repository [maintainers](https://github.com/helm/charts/blob/master/OWNERS) can do so.

Maybe @davidkarlsen can help ?

**Comment by yachtcaptain23** [comment]
@davidkarlsen Would you be able to assist?

**Pull request closed without merging**
