### PR TITLE
[stable/traefik] add support for Forward Authentication

### PR DESCRIPTION
**Pull request by redondos**
#### What this PR does / why we need it:

Adds support for Traefik Forward Authentication.

Upstream documentation: https://docs.traefik.io/configuration/entrypoints/#forward-authentication

#### Which issue this PR fixes

No issues found.

#### Special notes for your reviewer:

None.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
@redondos will you update this from master, so we can try to get it merged?

**Comment by redondos** [comment]
@billimek, sure, sorry for the delay. We've actually been using a slightly different syntax that we've found more useful in our organization, so I've pushed those changes based off the updated master.

**Review by chickenriggies — APPROVED** [review]

**Review by colinhoglund — APPROVED** [review]

**Comment by redondos** [comment]
@billimek @dtomcej, can we please get this reviewed?

**Comment by mmatur** [comment]
Hi @redondos 

Could you please rebase your PR?

**Comment by redondos** [comment]
@mmatur sure, done.

**Review by mmatur — APPROVED** [review]
/lgtm

**Pull request merged**
