### PR TITLE
[stable/anchore-engine] Configure external_hostname / port for Anchore API

### LINKED ISSUE #17189: [stable/anchore-engine] enable configuration of external_hostname/external_port
**Is your feature request related to a problem? Please describe.**

When standing up Anchore through the chart e.g., behind a firewall, the API constructs URLs for what we consider the "internal" API server address.  These are not terribly useful to our users.

**Describe the solution you'd like**

Anchore has configuration options for this, `external_hostname` / `external_port`, that allowed the API server to create URLs that map to what we consider the "external" address.  The chart should configure them if requested.

### PR DESCRIPTION
**Pull request by 0xDEC0DE**
Fixes: https://github.com/helm/charts/issues/17189

### CODE REVIEW

**Comment by Btodhunter** [comment]
@0xDEC0DE Thanks for the contribution! Can you please add the values you're referencing in the template to the values.yaml file? You can comment them out so they're not set by default. A short description above the commented out values explaining the purpose of these values would also be very helpful for users.

**Comment by 0xDEC0DE** [comment]
> @0xDEC0DE Thanks for the contribution! Can you please add the values you're referencing in the template to the values.yaml file, under `anchoreGlobal`? 

Whoops!  I thought I did that.  Pushed.

**Pull request merged**
