### PR TITLE
[stable/nats] Fixes default value of auth.user documented in README.md

### PR DESCRIPTION
**Pull request by vpartington**
#### Which issue this PR fixes
* Fixes default value of auth.user documented in README.md

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@vpartington 
Please bump the chart version to latest. Thank you.

**Comment by vpartington** [comment]
It's a minor change in the `README.md`. Does that also require the chart version to be bumped?

**Comment by zanhsieh** [comment]
@vpartington 
yes please.

**Comment by juan131** [comment]
Hi @vpartington 

As @zanhsieh explained, every change (even if it's a minor correction in the README.md) requires bumping the version in the **Chart.yaml**

In your case, you need to bump the patch version.

**Comment by vpartington** [comment]
@zanhsieh @juan131 Thanks. I have bumped the patch version number.

I have amended my earlier commit and force pushed to the branch so that the change is in a single commit.

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
