### PR TITLE
Fix missing ghost.fullname in template call.

### PR DESCRIPTION
**Pull request by ejamesc**
**What this PR does / why we need it**: Given I am a user of this chart,
When I try to deploy this using serviceType NodePort,
Then helm will explode and tell me that 

```
Error: render error in "ghost/templates/NOTES.txt": template: ghost/templates/NOTES.txt:39:130: executing "ghost/templates/NOTES.txt" at <{{template "fullname...>: template "fullname" not defined
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
/ok-to-test
/lgtm
You'll need to rebase and bump the version in Chart.yaml again, though.

**Comment by timstoop** [comment]
/lgtm
Glad you didn't listen to me and merged from master instead of the rebase :smile:

**Comment by javsalgar** [comment]
LGTM as well

**Comment by ejamesc** [comment]
This PR seems to be blocking on @tompizmor and @prydonius. Would it be possible to get it merged within the next 24 hours? I don't really want to keep merging haha. 😆

**Comment by timstoop** [comment]
In general, you can wait with merging until the PR is approved. I'm pretty active and once the PR has been approved, you've done the merge, I can simply lgtm it again to merge it to master.

The maintainers are pretty busy people, I'm afraid :(

**Comment by ejamesc** [comment]
Thank you @timstoop and @prydonius! I know you guys must be really busy, so thank you for taking the time! =] <3

**Comment by prydonius** [comment]
Thank you @ejamesc for the fix, and sorry for the delay! Just FYI, the repo maintainers are also able to push to your branch and we often merge/rebase to resolve conflicts before LGTM'ing when we can to avoid the feedback loop :), so no worries about that. Of course, if we can get them merged before a conflict happens, that's always better!

**Comment by ejamesc** [comment]
Oh! Alright then, thanks for telling me, I’ve learnt something new. :)

**Comment by ejamesc** [comment]
Gah, I just realised that due to a bad merge to master, I changed the Ghost app version to 1.22.2 (the latest release is 1.22.1). Should I update?

**Pull request merged**
