### PR TITLE
[stable/grafana] test

### PR DESCRIPTION
**Pull request by s12chung**
#### What this PR does / why we need it:
Add basic test to stable/grafana.

#### Which issue this PR fixes
No issue, adds new test.

#### Special notes for your reviewer:
based on `stable/mysql`, as I've been writing a lot of helm test PRs lately

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@s12chung please update your branch

**Comment by s12chung** [comment]
@maorfr is there anything else i need to do?

**Comment by maorfr** [comment]
/lgtm

You just did it :)
Thanks for contributing!

**Comment by s12chung** [comment]
awesome. thanks :D

**Pull request merged**
