### PR TITLE
[stable/ignite] Ignite features

### PR DESCRIPTION
**Pull request by fsniper**
#### What this PR does / why we need it:
This adds extra environment, container, volume features to the ignite helm chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I didn't change the Values.env section for backwards compatibility. Key Value pair was not enough to add secret/configmap references for environment variables. Instead added values.envVars
 
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by bergerx — APPROVED** [review]

**Comment by bergerx** [comment]
@scottrigby @maorfr do you mind having a look here?

**Comment by bergerx** [comment]
Oh this has been waiting for a while, can anyone check this?

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
