### PR TITLE
postgresql: optional prometheus metrics exporter

### PR DESCRIPTION
**Pull request by databus23**
This PR adds the option to run a side-car Prometheus metrics exporter for postgres. It requires no additional configuration and can be enabled be setting `metrics.enabled=true`

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by databus23** [comment]
I change a minor detail: the metrics image is now specified as `metrics.image` and `metrics.imageTag`. I think this is more in line with the postgres image itself.

**Comment by lachie83** [comment]
cc @swordbeta - Chart maintainer

**Comment by databus23** [comment]
rebased on master and bumped chart to 0.3.0

**Comment by databus23** [comment]
Rebased on master. ping @swordbeta

**Comment by databus23** [comment]
Whats the hold up? Are we still waiting on @swordbeta? /cc @viglesiasce

**Comment by viglesiasce** [comment]
@databus23 going to test today for UX and will report back. Since we havent heard from @swordbeta in a while would you be willing to mark yourself as a maintainer of this chart? If so please add yourself to the Chart.yaml.

**Comment by databus23** [comment]
@viglesiasce Sure. I added myself. Is there a document about the review process? Not sure what's the difference between. What's expected of a code and of a UX review?

**Pull request merged**
