### PR TITLE
[stable/mongodb] Documents existing persistence.existingClaim var

### PR DESCRIPTION
**Pull request by pcm32**
#### What this PR does / why we need it:

Documents existing (and tested) variable persistence.existingClaim for the mongoDB chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
    - Didn't open one.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped: Not applicable, just documentation improvement.
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by juan131** [comment]
Hi @pcm32 

Thanks for the PR! 

Could you please increase the "fix" version on the **Chart.yaml** and sign your commits (that's mandatory in order to pass the DCO tests)? 

> You can find more information about how to sing your commits by clicking on "Details" under the error that DOC is displaying.

**Comment by pcm32** [comment]
Hi @juan131, I have done now!

**Comment by juan131** [comment]
Thanks for the fix @pcm32 !!

**Pull request merged**
