### PR TITLE
Increased probe timeout

### PR DESCRIPTION
**Pull request by rmaugusto**
When database is stoped brutally database can start with "FATAL: the database system is starting up".
Depending on the storage it may take more than 60 seconds to autofix and the POD will restart indefinitely.

120 seconds should be enough but in future works we could add the chart variables.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by mattfarina** [comment]
@rmaugusto You have an error reported by CI. You need to increase the version of the chart (see the Chart.yaml fil)

**Comment by rmaugusto** [comment]
Something missing to merge ?

**Pull request merged**
