### PR TITLE
[incubator/raw] New chart

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**:

The `incubator/raw` chart takes a list of raw Kubernetes resources and
merges each resource with a default `metadata.labels` map and installs
the result.
 Some use cases for this chart include Helm-based installation and
maintenance of resources of kinds:
- LimitRange
- PriorityClass

**Special notes for your reviewer**:

Tested the priority classes example using these:

```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-rc.1", GitCommit:"2106a5910f6de3c07b8f329c7adaca38a0d3f825", GitTreeState:"clean", BuildDate:"2018-03-19T23:38:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

### CODE REVIEW

**Comment by josdotso** [comment]
Trying this chart locally, it seems well-suited to manage these resources:

- LimitRange
- Namespace
- PriorityClass
- StorageClass

**Comment by mattfarina** [comment]
/ok-to-test

@prydonius curious to your thoughts on this style chart?

**Comment by unguiculus** [comment]
Interesting concept. I kinda like it.

**Comment by josdotso** [comment]
@prydonius Ping.

**Comment by prydonius** [comment]
Sorry for the delay, this is pretty interesting and I like the approach! I'm wondering if we could give this a more descriptive name though, `resource-labeler`?

**Comment by prydonius** [comment]
@josdotso okay, I don't have a strong opinion either way so I'm okay with this :+1:.

Thanks for the contribution!

/lgtm

**Comment by josdotso** [comment]
Thank you!

**Pull request merged**
