### PR TITLE
[stable/stolon] upgrade api version for kubernetes 1.16+

### PR DESCRIPTION
**Pull request by yujunz**
#### Is this a new chart

No

#### What this PR does / why we need it:

The v1.16 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

* DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the extensions/v1beta1 and apps/v1beta2 API groups)
  * Migrate to use the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

#### Which issue this PR fixes

None

#### Special notes for your reviewer:

None

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yujunz** [comment]
Resolved conflict with `master` branch

**Review by lwolf — APPROVED** [review]

**Pull request merged**
