### PR TITLE
[stable/metrics-server] Update rbac apiversion from v1beta1 to v1

### PR DESCRIPTION
**Pull request by mtougeron**
Signed-off-by: Mike Tougeron <tougeron@adobe.com>

#### What this PR does / why we need it:
This updates the rbac apiVersion from v1beta1 to v1. Other areas of the chart are already using v1

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mtougeron** [comment]
cc @olemarkus / @kennethaasan

**Comment by mtougeron** [comment]
Thanks!

**Comment by kppullin** [comment]
I _think_ this may have be a breaking change and adding a comment here in case someone else runs across the same trouble.

When updating from 2.10.0 to 2.10.1 using helm v3.1.0 we get the error:

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: kube-system, name: metrics-server-auth-reader, existing_kind: rbac.authorization.k8s.io/v1, Kind=RoleBinding, new_kind: rbac.authorization.k8s.io/v1, Kind=RoleBinding
```

which looks similar to the issues raised here: https://github.com/helm/helm/issues/7697#issuecomment-592069653 .  It's confusing that the `existing_kind` is listed as `rbac.authorization.k8s.io/v1` since the existing value is `rbac.authorization.k8s.io/v1beta1`, however this aligns with most of the comments in the linked helm issue.

I've worked around it be deleting and recreating the chart, as suggested by the above thread.

**Pull request merged**
