### PR TITLE
[stable/prometheus-adapter] Allow the prometheus-adapter to read deployments to enable Object metrics for deployments

### LINKED ISSUE #7700: [stable/prometheus-adapter] Allow the resource-reader-cluster-role to access Deployments
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
Helm Client: v2.9.1
Helm Server: v2.9.1
Kubernetes Version: v1.10.6-gke.2

**Which chart**:
Prometheus Adapter

**What happened**:
When implementing autoscaling for a queue based workload, I found it easiest to associate a `jobs_per_worker` metric with the deployment that works that queue. The metrics are exported by a single pod and associated via correctly labeling the metric.

When configuring my HPA, I used something similar to the following:

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "queue-one-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "queue-one-workers"
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Deployment
        name: queue-one-workers
      metricName: jobs_per_worker
      targetValue: 100
```

When attempting to scale in this fashion, I received errors in the logs of the adapter that indicated that it the cluster role did not have access to deployments and therefore could not fetch the metric.

**What you expected to happen**:
Since `Object` metrics can be associated with `Services`, `Deployments`, etc... I would expect this adapter to be able to scale correctly with object metrics for those resources.

**How to reproduce it** (as minimally and precisely as possible):
Try to scale on an `Object` metric using a Deployment object as the target.

**Anything else we need to know**:
I'd be happy to work on this change. In my fork I simply added `extensions` to the `apiGroups` and `deployments` to the `resources` configuration in https://github.com/helm/charts/blob/master/stable/prometheus-adapter/templates/custom-metrics-resource-reader-cluster-role.yaml

We could make the same change here as well but I wanted to solicit some feedback to see if this makes sense or has other ramifications.

### PR DESCRIPTION
**Pull request by jasonwc**
#### What this PR does / why we need it:
In order to implement `Object` metrics on a `Deployment` object, the adapter needs to be able to read them.

In our case, we wanted to associate a metric with the deployment (e.g. add a `jobs_in_the_queue` metric tied to the deployment that works that queue) and so we made this change on our fork. Figured it would be worth trying to get it back in upstream.

Check out the #7700 for more details!

#### Which issue this PR fixes

    - fixes #7700

#### Special notes for your reviewer:
- Wasn't sure if we wanted this to be more configurable, but since we were already allowing `Service` resources to be read, I figured this was ok.

#### Checklist

- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by steven-sheehy** [comment]
@jasonwc Are you sure this is necessary? I'm using a metric associated with a Deployment and it works fine. I'll respond to your issue with details.

**Comment by jasonwc** [comment]
Thanks @steven-sheehy! I'll take a look at the issue and respond there.

**Comment by jasonwc** [comment]
Closing after further discussion in https://github.com/helm/charts/issues/7700

**Pull request closed without merging**
