### PR TITLE
Switch to Helm rc.1 release

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
attempting to delete and re-create tiller too

**Comment by prydonius** [comment]
@viglesiasce I jumped the gun a bit an already updated tiller via some lines in this PR, and realised later that this breaks the CI until this gets merged in (sorry).

**Comment by lachie83** [comment]
Ran some tests alongside @prydonius. This is GTG

**Comment by lachie83** [comment]
LGTM

**Comment by prydonius** [comment]
thanks @lachie83!!

**Pull request merged**
