### PR TITLE
[stable/prometheus] to 2.16.0

### PR DESCRIPTION
**Pull request by naseemkullah**
/assign @zanhsieh 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@vsliouniaev 
Could you help me to look into the log file please? I cannot see what might cause the e2e failed.

**Comment by naseemkullah** [comment]
🎉

**Pull request merged**
