### PR TITLE
fix PR#3308

### LINKED ISSUE #1550: Prometheus chart does not allow (easy) scrape interval modification
**Version of Helm and Kubernetes**: v2.5.0
**Which chart**:Prometheus
**What happened**: When installing grafana dashboards (eg https://grafana.com/dashboards/162), the dashboard has a lot of gaps. 
After investigation, it seems the dashboard requires a relatively small scrape interval. As least smaller that the OOTB one of 1m. 
To my surprise it was not possible to change the scrape interval of the template in an easy way using values.yaml.  AFAIK, i have to duplicate the complete prometheus config template in my values.yaml file. 

**What you expected to happen**:
Just update scrape interval in values.yaml and update helm chart. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by nseyvet**
**What this PR does / why we need it**:
Externalize global timing-related parameters for prometheus scraping to allow their easier modification, i.e. without the need to pass the whole configuration file. See #1550 for details. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1550

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by nseyvet** [comment]
hi,
any luck merging this?

**Comment by gianrubio** [comment]
@nseyvet please rebase it

**Pull request merged**
