### PR TITLE
[incubator/vault] Fix liveness check when vault is sealed or uninitialized

### PR DESCRIPTION
**Pull request by jbialy**
#### What this PR does / why we need it:

Fixes issue related to the comment https://github.com/helm/charts/pull/9462#pullrequestreview-212561183.

PR  https://github.com/helm/charts/pull/9462 changed the liveness check from a simple TCP socket to using a httpGet request. However, when a Vault pod starts in either an `uninitialized` or `sealed` state the default return codes from the `/v1/sys/health` endpoint will cause the liveness check to fail resulting in a `CrashLoopBackOff `.

This PR addresses this issue by having the `/v1/sys/health` endpoint return a status code `204` when Vault is either `sealed` or `uninitialized` ensuring that the liveness check passes.

#### Special notes for your reviewer:

There is also an issue filed under https://github.com/helm/charts/issues/11067, however it does not appear to be directly related to the original [PR](https://github.com/helm/charts/pull/9462) that this fix addresses.

This PR extends the work done in https://github.com/helm/charts/pull/11616.
#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jbialy** [comment]
@unguiculus PTAL, it'd be great to get this merged!

**Comment by okgolove** [comment]
Someone please merge it.
This is really annoying thing.

**Pull request merged**
