### PR TITLE
[stable/fluentd-elasticsearch] better deprecation info

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by gajus** [comment]
Whats the reason this chart has been deprecated?

**Comment by axdotl** [comment]
@gajus It was moved to https://github.com/kiwigrid/helm-charts and will maintained there.

Check https://github.com/helm/hub for more details on distributed repos.

**Comment by gajus** [comment]
Doesn't answer the question why it was deprecated.

I feel (and I am sure the sentiment is prevalent) a lot more safe by consuming a chart hosted on helm/charts than another repository.

**Comment by axdotl** [comment]
There were several discussions about it (see https://github.com/helm/community/pull/24 which results in https://github.com/helm/community/blob/master/proposals/distributed-search.md).

AFAIK this whole repo (at least its content) will become deprecated and as the fluentd-elastisearch chart is no longer maintained here its set to deprecated.

**Pull request merged**
