### PR TITLE
[mongodb] Add separate affinity for arbiter pod

### PR DESCRIPTION
**Pull request by botzill**
Signed-off-by: Chirica Gheorghe <chiricagheorghe@gmail.com>

#### What this PR does / why we need it:

Add a separate affinity for the arbiter pod. Useful l when we want to deploy nodes from arbiter separately and have more control over it. 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Hi, thanks for your contribution.
A new version appeared in the last hours so you need to bump the version in the [_Chart.yaml_](https://github.com/helm/charts/blob/master/stable/mongodb/Chart.yaml#L3) again, that is the reason for the failing test.

**Comment by botzill** [comment]
@carrodher Done.

**Comment by botzill** [comment]
@carrodher Can you check it?

**Pull request merged**
