### PR TITLE
[stable/traefik] Add `acme.dnsProvider.ovh` example

### PR DESCRIPTION
**Pull request by emmanuelCarre**
#### What this PR does / why we need it:

Add values example for OVH provider  for acme.

#### Which issue this PR fixes
None.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by dtomcej** [comment]
Hello @emmanuelCarre Can you rebase so that we can get this merged?

**Comment by emmanuelCarre** [comment]
Hi,
I rebase my branch. It should be OK now.

**Pull request merged**
