### PR TITLE
[stable/openvpn] ipv4 forwarding init container

### PR DESCRIPTION
**Pull request by kamsz**
This PR adds an optional init container that will enable IPv4 forwarding.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jasongwartz** [comment]
@kamsz thanks for submitting! This one I’d like to test out a little bit and I may not have time for a little while to do so - thanks for being patient.

**Comment by kamsz** [comment]
@jasongwartz Sure thing!

**Comment by kamil-szczygiel-dragon** [comment]
Do not mark as stale. @jasongwartz any updates on this?

**Comment by jasongwartz** [comment]
Haven’t forgotten! @kamsz @kamil-szczygiel-dragon can you recommend how I should go about testing this?

**Comment by kamsz** [comment]
@jasongwartz I believe a simple cluster on GKE is sufficient (I've observed this issue with GKE cluster).

**Comment by jasongwartz** [comment]
@kamsz sorry if I’m not understanding fully. When you say you’ve noticed this issue on GKE, what issue are you referring to?

**Comment by jasongwartz** [comment]
@kamsz could you please clarify the question above, and also merge latest master?

**Comment by kamsz** [comment]
> @kamsz sorry if I’m not understanding fully. When you say you’ve noticed this issue on GKE, what issue are you referring to?

Issue I've encountered is lack of IPv4 forwarding enabled on nodes, which resulted in the change I'm proposing.

**Comment by jasongwartz** [comment]
sorry for the back-and-forth. I'd like to finally try and get this merged, as it's also useful for https://github.com/helm/charts/pull/16381. Can you update the chart version? then we'll be good to go :smile:

**Comment by zanhsieh** [comment]
@kamsz 
Could you resolve conflicting files please?
stable/openvpn/Chart.yaml
stable/openvpn/README.md
stable/openvpn/values.yaml

**Comment by jasongwartz** [comment]
Bump 😄 
Just need to fix the merge conflicts

**Comment by jasongwartz** [comment]
Usurped by https://github.com/helm/charts/pull/16381

**Pull request closed without merging**
