### PR TITLE
[stable/prometheus-blackbox-exporter] Allow custom module for blackbox service monitor

### PR DESCRIPTION
**Pull request by meyskens**
#### What this PR does / why we need it:
Add the ability for the ServiceMonitor to target a custom defined module from the configuration.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Aisuko** [comment]
ping @desaintmartin Any feedback could be good.

**Comment by desaintmartin** [comment]
Thanks!
/ok-to-test
/lgtm

**Pull request merged**
