### PR TITLE
[stable/minio] update minio and mc

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
update minio and mc

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by nitisht** [comment]
@cpanato we'll make another MinIO release today, can we please hold off the update till then

**Comment by cpanato** [comment]
@nitisht sure, can you ping me here?

/hold

**Comment by nitisht** [comment]
Thanks will do

**Comment by nitisht** [comment]
@cpanato this is the latest release `RELEASE.2019-08-01T22-18-54Z`

**Comment by cpanato** [comment]
@nitisht the new images are ready?

**Comment by nitisht** [comment]
> @cpanato this is the latest release `RELEASE.2019-08-01T22-18-54Z`

Yes @cpanato

**Comment by cpanato** [comment]
oh sorry, did not see the message before :/ did not refresh the issue my bad @nitisht do we have a new for mc as well?

**Comment by nitisht** [comment]
no worries :)

mc is at `RELEASE.2019-07-31T19-17-35Z` so nothing to change

**Comment by cpanato** [comment]
@nitisht PTAL
/hold cancel

**Pull request merged**
