### PR TITLE
Add initial Mastodon chart

### PR DESCRIPTION
**Pull request by blakebarnett**

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
Does anyone have a cluster where they can test this? I dont have any currently supporting the batch/v2alpha1 API?

cc @kubernetes/charts-maintainers

**Comment by blakebarnett** [comment]
Sorry, I haven't had any time to keep working on this.  Currently the storage for system / assets is broken and needs to be refactored (needs shared storage, I was going to just add NFS).  I'm not sure when I can get back to this, feel free to close.

**Comment by seanknox** [comment]
Thanks for the update @blakebarnett. Feel free to submit another PR whenever you're ready and we'll give it another go.

**Pull request closed without merging**
