### PR TITLE
[stable/node-problem-detector] Update the daemonset template volume mount to use hostpath.logdir variable

### PR DESCRIPTION
**Pull request by jamiebuxxx**
Signed-off-by: JaMile Jackson <jamile.jackson@nielsen.com>

#### What this PR does / why we need it:
This chart was missing the variable in the daemonset template to actually mount the log path on the host. In our case we need to update the log.path to `/run/log/`. This is how we discovered this bug. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by louisblin** [comment]
Hi @jamiebuxxx ,
Just a heads up that #21670 might solve your use case. Up to you whether you want to move forward with this PR.

**Comment by jamiebuxxx** [comment]
@louisblin Thanks for the heads up! That would handle it for sure, but I think the bug in the template should still be fixed. Maybe that fix could get added into your PR and we can close this one?

**Comment by louisblin** [comment]
Hey @jamiebuxxx ,
I'm seeing this just now and #21670 was already merged... Maybe the current hardcoded log mount could be a default value of `extraVolumes` / `extraVolumeMounts` in #21670 . Then, you could override that default with your own mounts and achieve the same effect . How does that sound?

**Comment by jamiebuxxx** [comment]
@louisblin Cool, thanks for the heads up on merge. As for the suggestion, that's could work and will definitely achieve the same effect. However, I do like having a "main" default and using the `extraVolumes` / `extraVolumeMounts` as exactly that. It's a common pattern that I have seen in Helm charts before.

I will merge in the last changes and get the version bumped for this PR. Thanks for your input!

**Comment by jamiebuxxx** [comment]
@max-rocket-internet @Random-Liu @andyxning Could someone take a look at this PR when y'all have a chance? Thanks!

**Review by max-rocket-internet — APPROVED** [review]
Nice

**Comment by max-rocket-internet** [comment]
Thanks @jamiebuxxx

**Pull request merged**
