### PR TITLE
[stable/minio] Indentation fix for pod label capability

### PR DESCRIPTION
**Pull request by sshahinco**
Signed-off-by: Sherief Shahin <smshahin1611@gmail.com>

#### What this PR does / why we need it:
Fixes the previous pod capability added, by removing extra indentation 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by sshahinco** [comment]
@nitisht Is it okay to merge now for use in our project? It has been an impediment for us as well as the next commit I am planned to push today after a successful trial of the pod label capability in our project

**Comment by sshahinco** [comment]
If possible, I checked the list of helm members and I found that @prydonius can approve my merge as well. We are truly blocked by not having pod label capabilities

**Comment by nitisht** [comment]
Looks good @sshahinco we can merge

**Pull request merged**
