### PR TITLE
[stable/minio] Allow chart upgrades to resume from failure

### PR DESCRIPTION
**Pull request by stephenc**
#### What this PR does / why we need it:

When using this chart as a sub chart I have repeatedly encountered situations where the chart fails to complete the hooks, but without reporting an error. The create bucket job hook should be idempotent, so if it was not deleted last time upgrading, we should be safe to delete it before the next upgrade

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by stephenc** [comment]
@wlan0 / @nitisht thoughts?

**Comment by nitisht** [comment]
PR looks fine @stephenc , but you need to fix the failures in CI (DCO , Lint etc)

**Comment by stephenc** [comment]
@nitisht the test failure seems unrelated

**Comment by nitisht** [comment]
> @nitisht the test failure seems unrelated

It is not unrelated. [Linting](https://circleci.com/gh/helm/charts/125721?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) fails with 

```
Checking chart 'minio => (version: "5.0.12", path: "stable/minio")' for a version bump...
Old chart version: 5.0.12
New chart version: 5.0.12
Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ minio => (version: "5.0.12", path: "stable/minio") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------

Exited with code exit status 1
```

While [DCO reports](https://github.com/helm/charts/pull/20934/checks?check_run_id=485797970) that commit is not signed properly

**Pull request closed without merging**
