### PR TITLE
[stable/oauth2-proxy] add undocumented ingress.{path,annotations,hosts,tls} to README

### PR DESCRIPTION
**Pull request by jhoblitt**
@miouge1

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jhoblitt** [comment]
Is it appropriate to bump the chart version for doc only fixes?

**Comment by jhoblitt** [comment]
eh, ok, it looks like CI fails without a chart version bump even on the README...

**Comment by jhoblitt** [comment]
ping

**Review by Miouge1 — APPROVED** [review]
/lgtm

**Comment by jhoblitt** [comment]
I've incremented the version dump to `0.12.3` and repushed.

**Comment by jhoblitt** [comment]
@Miouge1 Ugh, this PR needs the `lgtm` label again...

**Pull request merged**
