### PR TITLE
[stable/wordpress] Add option for skipping the installation wizard

### PR DESCRIPTION
**Pull request by javsalgar**
Signed-off-by: Javier J. Salmeron Garcia <jsalmeron@bitnami.com>

#### What this PR does / why we need it:
Enable the parameter for skipping the installation wizard. This is useful for using the chart with an already initialized WordPress database.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/bitnami/bitnami-docker-wordpress/issues/157

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
/ok-to-test

**Comment by 0GiS0** [comment]
Hi folks,

I'm trying to deploy this helm and I get an error because of this feature: 

Giselas-iMac:wordpress gis$ kubectl logs excited-seagull-wordpress-5994c54f6b-9slr4

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing wordpress
**'false' is not a valid value for 'skipInstall'. Allowed: yes, no**
Giselas-iMac:wordpress gis$ 

So I had to add this set to the command:

helm install stable/wordpress --set wordpressSkipInstall=no

Could you fix it? 

thanks a lot!

**Comment by javsalgar** [comment]
Thanks for reporting: https://github.com/helm/charts/pull/13005

**Pull request merged**
