### PR TITLE
[rabbitmq-ha] add schedulerName option

### PR DESCRIPTION
**Pull request by alice-sawatzky**
Signed-off-by: Alice Sawatzky <alice.sawatzky@farmersedge.ca>

#### What this PR does / why we need it:

This adds the ability to set the [`podSpec.schedulerName`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#podspec-v1-core) field in the `StatefulSet` template in the rabbitmq-ha chart.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by alice-sawatzky** [comment]
@steven-sheehy PR template told me to @ you, care to take a look?

**Comment by steven-sheehy** [comment]
/lgtm
Thanks @alice-sawatzky!

**Comment by alice-sawatzky** [comment]
thanks!

**Pull request merged**
