### PR TITLE
stable/jenkins: Switch from Deployment to StatefulSet

### PR DESCRIPTION
**Pull request by jfrabaute**
As jenkins uses a PV, it should be a StatefulSet so it keeps track of
the correct PV and PVC on restart/upgrades.

### CODE REVIEW

**Comment by jfrabaute** [comment]
The `updateStrategy` is not correct.
I'll send a fix soon.

**Comment by jfrabaute** [comment]
PR updated with the updateStrategy fix.

**Comment by wmcdona89** [comment]
@jfrabaute thanks for the PR. #23126 also proposes this change.

**Comment by jfrabaute** [comment]
Sounds good, no problem closing my PR and you can merge the other one (which has the changes for the doc which I missed).

**Comment by scottrigby** [comment]
📢 `stable/jenkins` has moved to https://github.com/jenkinsci/helm-charts. If still applicable, please reopen the PR there. Thanks!

**Pull request closed without merging**
