### PR TITLE
[RabbitMQ] Set Parallel podManagementPolicy for restarting of entire cluster

### PR DESCRIPTION
**Pull request by ssup2**
Signed-off-by: Jungsub Shin supsup5642@gmail.com

#### What this PR does / why we need it:

After shutdown of entire rabbitmq cluster, each rabbitmq
wait for the response of the existing cluster to start
except the last stopped rabbitmq.

If the last stopped rabbitmq is not first pod rabbitmq
of statefulset, rabbitmq wait the cluster Infinitely.
To solve this issue, podManagementPolicy is must Parallel.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by tompizmor** [comment]
@ssup2 Do you think it makes sense to expose a property to configure the podManagementPolicy from the values.yaml? I don't know if for some use cases someone would be interested in keep using `OrderedReady` as pod management policy.

**Comment by ssup2** [comment]
@tompizmor Oops. podManagementPolicy Parallel has also the problem. At the first boot with parallel, Each RabbitMQ dosen't  recognize each other and fail to clustering.  I think I need to find a way to sequence boot with Parallel option or provide podManagementPolicy as a option for recover the rabbitmq cluster.

I close this issue

**Comment by ssup2** [comment]
@tompizmor I think providing podManagementPolicy as option is best choice, I will recreate pull request.

**Pull request closed without merging**
