### PR TITLE
fix repository name and version up to 6.2.1

### PR DESCRIPTION
**Pull request by MasayaAoyama**
**What this PR does / why we need it**:
1. Fix datadog docker image repository name for agent6
2. Update DataDog Agent chart to the newest version.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by MasayaAoyama** [comment]
Hello, please check me :)
/assign @irabinovitch 
/assign @hkaj 
/assign @xvello

**Review by hkaj — APPROVED** [review]

**Comment by MasayaAoyama** [comment]
@hkaj 
Thank you.
CI is passed, but status cannot reported.
Can I recheck? How to do it?
https://circleci.com/gh/kubernetes/charts/10918

**Pull request merged**
