### PR TITLE
[incubator/sparkoperator] setting the default correctly in the values file

### PR DESCRIPTION
**Pull request by mjschmidt**
Tied to [this issue on the spark operator github page](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/454)

If you don't set this default values file the service account of spark-spark is created instead of the desired service account of just spark, you end up with a service account of spark-spark.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by mjschmidt** [comment]
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

**Comment by mjschmidt** [comment]
#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

**Comment by mjschmidt** [comment]
I don't have control of the chart version and the variables remain unchanged to previous version

**Review by yuchaoran2011 — COMMENTED** [review]
I don't think this change is necessary. The service account name is by default empty, following the Helm chart [best practices](https://helm.sh/docs/chart_best_practices/#yaml-configuration). You can always pass your desired service account name using `--set serviceAccounts.spark.name=spark` with `helm install`.

**Comment by mjschmidt** [comment]
@yuchaoran2011 but the sparkoperator doesn't work with its default value. If you spin up with just default values you run into problems because the service account it creates is named "spark-spark" when the intended name for the service account should be just "spark".

**Comment by yuchaoran2011** [comment]
@mjschmidt The default configuration will create a service account called `<helm-release-name>-spark`, which you put in `spec.driver.serviceAccount` in the YAML. The reason you have `spark-spark` is because you set the release name to `spark` (possibly using `--name` flag during `helm install`).

**Comment by mjschmidt** [comment]
Right, but what I am saying is if you follow the spin up instructions, the example jobs should be changed then to accept the default values and the service account for that python job should be changed from spark to spark-spark.

I honestly don't care if the chart changes or the example files all change. I just think it doesn't make much sense for the example files to not work.

**Comment by mjschmidt** [comment]
This file would need to be changed the match the quick start directions listed here
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md

**Comment by mjschmidt** [comment]
Oh... @youhonglian I get what you are saying.

**Comment by mjschmidt** [comment]
Still seems silly that the name would affect the service account name. But I can accept that answer I guess...

**Comment by tcz001** [comment]
Hi This issue still happened on my trial following the quick start here 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md

**Comment by mjschmidt** [comment]
Yeah, so I figured it out, I guess at a certain level I really just felt like the name of the deployment shouldn't be tied to the name of the service

**Pull request closed without merging**
