### PR TITLE
add volumeBindingMode to ignite

### PR DESCRIPTION
**Pull request by marinkobabic**
By adding volumeBindingMode a scheduling of volumes is possible

### CODE REVIEW

**Comment by marinkobabic** [comment]
You should in generally remove all the storage classes from the chart and let the user define the storage class name. This way the application is decoupled from the underlying infrastructure.

**Comment by marinkobabic** [comment]
Please can we make here any progress?

**Comment by marinkobabic** [comment]
/assign @bergerx 

Please can you merge this not breaking change

**Comment by bergerx** [comment]
Ah sorry, I'm mot one of the maintainers here, i'm just a contributor like you, I can't really merge stuff.

There is an ongoing process for migrating the hosting of the charts to their respective owners, and last time I checked ignite chart doesn't really have any strong owners willing to host it for others. Maybe apache foundation. But until then its likely that our PRs wont have attention as I understand the situation of this.

**Pull request closed without merging**
