### PR TITLE
[stable/jenkins] allow templating of volumes

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

Rendering the volumes using the tpl function allows templating within values.yaml

If one for example renders a secret or config-map within a chart which has this chart
declared as dependency in its `requirements.yaml` then one could inject the rendered
secret like this:

```
Persistence:
  volumes:
  - name: jenkins-secrets
    secret:
      secretName: '{{ template "jenkins.fullname" . }}-casc-secrets'
  mounts:
  - mountPath: /run/secrets/casc
    name: jenkins-secrets
    readOnly: true
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by torstenwalter** [comment]
@maorfr Thanks for looking into this that fast. :thumbsup:

**Comment by maorfr** [comment]
/lgtm

thank you for contributing!

**Pull request merged**
