### PR TITLE
[stable/graylog] deprecate graylog chart

### PR DESCRIPTION
**Pull request by KongZ**
Signed-off-by: KongZ <goonohc@gmail.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
This deprecates the Graylog chart and references the new home.

#### Special notes for your reviewer:
@scottrigby please link this PR to #21103 ?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by scottrigby** [comment]
Hi @KongZ, are you interested in preserving the commit history from here to there? Here is a good writeup on how to do that https://torstenwalter.de/helm-chart-hosting/

**Comment by KongZ** [comment]
@scottfrederick thanks for pointing out how to do it. I already preserve the history to my new repo :)

**Comment by scottrigby** [comment]
Great 👏 Added an issue I saw https://github.com/KongZ/charts/issues/3 but in general looks good!

**Review by scottrigby — APPROVED** [review]
/lgtm

**Pull request merged**
