### PR TITLE
[stable/spark-history-server] Add service annotations

### PR DESCRIPTION
**Pull request by vvbogdanov87**
Add service annotations

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vvbogdanov87** [comment]
All commits are signed. I don't know why DCO check failed.

**Comment by yuchaoran2011** [comment]
@vvbogdanov87 Have you run the commands mentioned [here](https://github.com/helm/charts/pull/17350/checks?check_run_id=232200591)? They should fix your DCO issue.

**Comment by vvbogdanov87** [comment]
@yuchaoran2011 Could you please review.

**Review by yuchaoran2011 — APPROVED** [review]
/lgtm

**Pull request merged**
