### PR TITLE
[stable/minio] create bucket after install through configuration parameter with tls enabled

### LINKED ISSUE #10683: [stable/minio] Bucket creation through configuration parameter not working with tls enabled
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:

**Which chart**: stable/minio 2.3.4

**What happened**: [stable/minio] Getting error while  installing minio with tls enabled and providing bucket name to create after install (through command line configuration parameter). 

Error -   `Connecting to Minio server: http://minio:9000
mc: <ERROR> Unable to initialize new config from the provided credentials. Access Denied. `

**What you expected to happen**: Minio should get installed with bucket localbucket already created in it.

**How to reproduce it** (as minimally and precisely as possible): Try to install minio in distributed mode with tls enabled and give List of buckets to create after minio install.

eg helm command - 
`
 helm upgrade --debug  --install 
  --set mode=distributed 
  --set replicas=4 
  --set persistence.size=32Gi 
  --set persistence.storageClass=managed-premium 
  --set accessKey=$STORAGE_ACCOUNT 
  --set tls.enabled=true 
  --set buckets[0].name=localbucket,buckets[0].policy=none,buckets[0].purge=false 
  --set tls.certSecret=tls-ssl-minio 
  --set secretKey=$STORAGE_KEY minio stable/minio
`

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by raru12**
#### What this PR does / why we need it: 

[stable/minio]  When creating buckets which were provided through configuration parameter, mc is connecting to minio on http even when tls is enabled.  Changes done to connect minio on https when tls is enabled

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10683

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by nitisht — COMMENTED** [review]
@raru12 can you add steps to test this functionality,

**Comment by raru12** [comment]
@nitisht  - I have tested the following changes in 2 scenarios - 

1) Installing minio and giving bucket name to create after install with tls enabled - 
cmd - 
  helm upgrade --debug  --install \
  --set persistence.enabled=false \
  --set accessKey=$STORAGE_ACCOUNT \
  --set tls.enabled=true \
  --set tls.certSecret=tls-ssl-minio \
  --set buckets[0].name=localbucket3,buckets[0].policy=none,buckets[0].purge=false \
  --set buckets[1].name=localbucket4,buckets[1].policy=none,buckets[1].purge=false \
  --set secretKey=$STORAGE_KEY minio stable/minio

Note - you have to have tls-ssl-minio secret as required to enable tls and set the STORAGE_ACCOUNT, STORAGE_KEY values 

2) Installing minio and giving bucket name to create after install without tls
cmd - 
  helm upgrade --debug  --install \
  --set persistence.enabled=false \
  --set accessKey=$STORAGE_ACCOUNT \
  --set buckets[0].name=localbucket3,buckets[0].policy=none,buckets[0].purge=false \
  --set buckets[1].name=localbucket4,buckets[1].policy=none,buckets[1].purge=false \
  --set secretKey=$STORAGE_KEY minio stable/minio

Note - set the STORAGE_ACCOUNT, STORAGE_KEY values

**Comment by raru12** [comment]
@nitisht When we give list of buckets to be created, the install starts a job `minio-make-bucket-job`.
This job uses mc (minio client) to create the bucket and when tls is enabled this job is failing since it is trying to connect to minio on http instead of https.

**Review by nitisht — COMMENTED** [review]
Tested locally, works fine @raru12 

I have one last ask, can you please add steps to use this feature in the Readme file. Similar to the way `defaultBucket` is documented.

**Comment by raru12** [comment]
@nitisht This is an existing feature which was not working, so I am not clear what to add. 
Do you want me to add a section in README.md to describe, how to create a bucket(many buckets ) after minio install (The way it is done for - configure TLS)?

**Comment by nitisht** [comment]
>This is an existing feature which was not working, so I am not clear what to add.

Agreed, I just tested and see that it doesn't work..

> Do you want me to add a section in README.md to describe, how to create a bucket(many buckets ) after minio install (The way it is done for - configure TLS)?

Yes, that will be very helpful. We're trying to improve the quality of docs here in the Helm chart. Once this is done, I will remove the old `defaultBucket` approach

**Comment by raru12** [comment]
@nitisht Added steps to use this feature. Please review it and let me know in case of any issue.

**Comment by nitisht** [comment]
Thanks @raru12

**Pull request merged**
