### PR TITLE
[stable/prometheus-operator] Istio compatibility fixes.

### PR DESCRIPTION
**Pull request by eperdeme**
#### What this PR does / why we need it:
Renames the ports from 'web' to 'http' to allow Istio to understand the protocol used.

#### Special notes for your reviewer:
Basic port name changes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by eperdeme** [comment]
Breaks hard coded health checks / ready checks. Coding fix.

**Comment by vsliouniaev** [comment]
Could you bump the chart version again please

**Pull request merged**
