### PR TITLE
stable/velero: adding namespace to resources

### PR DESCRIPTION
**Pull request by kkunkel**
#### What this PR does / why we need it:

This adds the namespace metadata to resources. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by prydonius** [comment]
Thanks @kkunkel, but I'm not sure I see why this is necessary? Helm will automatically create these resources in the specified release namespace.

**Comment by prydonius** [comment]
Hey! Thanks for the explanation, makes sense now. That said, I'm not sure it makes sense to make this change in the chart. Are you able to use the [namespace directive](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-namespace) for this instead?

**Comment by kkunkel** [comment]
We have been using the namespace directive which allows us to deploy one configuration of velero. When we added another environment, Kustomize is unable to, both, apply the namespace directive, and identify which resources to patch. The only way we have been able to deploy numerous velero deployments has been `helm template ...` -> manually add namespaces -> Flux/Kustomize -> Profit

I agree that this PR does not add any value to the most common use cases, but it does enable our additional use case and allows us to automate the deployment and updates of Velero

**Comment by prydonius** [comment]
> Kustomize is unable to, both, apply the namespace directive, and identify which resources to patch.

I'm not all that familiar with Kustomize, but wouldn't it just generate resources with the right namespace and then `kubectl apply` would patch the resources in the cluster? Or are you talking about kustomize patches?

My biggest concern with adding this to this chart, is that it sets a precedent for adding it to all charts in stable, as the usecase isn't specific to Velero. I'm curious what other maintainers think about this. cc @helm/charts-maintainers

**Comment by kkunkel** [comment]
Some Googling turned up these https://github.com/helm/helm/issues/3553 and https://github.com/helm/charts/pull/16382 which seem to indicate that the Helm community would prefer to not support chart installation using `helm template ...|kubectl apply -f`.

In my opinion, that's a shame. Others using GitOps workflows will encounter this issue and the changes required to work seem, to me at least, very minimal and possibly a better practice when generating yaml through `helm template ...`.

**Comment by stefanprodan** [comment]
@kkunkel what Kustomize version are you using? I can confirm that custom resources namespace patching works with Flux 1.15.0 (Kustomize 3.2.0).

This is how it should work:
* do `helm template > base/velero/velero.yaml`
* create `base/velero/kustomization.yaml`
```yaml
resources:
  - velero.yaml
```
* create  `overlays/test/namespace.yaml`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
```
* create `overlays/test/kustomization.yaml`
```
namespace: test
resources:
  - namespace.yaml
bases:
  - ../../base/velero/
```
* create `.flux.yaml`
```yaml
version: 1
commandUpdated:
  generators:
    - command: kustomize build .
```

**Comment by kkunkel** [comment]
Hey @stefanprodan! Thank you for investigating this issue! This issue only presents itself in repository containing multiple directories (environments in our case). Would you be willing to connect a flux daemon to https://github.com/kkunkel/helm-flux-kustomize-test ? I believe this will demonstrate the failure case.

**Comment by kkunkel** [comment]
to be clear, the `--git-path=` should be (DEV|QA|PROD)

**Comment by stefanprodan** [comment]
@kkunkel have you looked at my example? you need to remove the namespace from base and add it to each environment, like i did with test1 and test2.

**Comment by kkunkel** [comment]
@stefanprodan, yes, I've updated https://github.com/kkunkel/helm-flux-kustomize-test to reflect those changes, but it still fails. Kustomize is apparently more finicky than the documentation warns

**Comment by stefanprodan** [comment]
Well you didn't moved the namespace yaml out of the base nor did you add a namespace resource and yaml in your envs, can you please read my example?

**Comment by kkunkel** [comment]
I apologize! I have removed the ns.yaml from base and added it to the environment directories. I've updated all the kustomization.yaml files. I am still encountering the same failure

**Comment by stefanprodan** [comment]
@kkunkel your overlays are wrong, just use `kustomize build` to test your changes. Here:
```
helm-flux-kustomize-test $ kustomize build DEV/
2019/10/11 02:18:45 absolute path error in '/Users/aleph/go/src/github.com/stefanprodan/helm-flux-kustomize-test/base/velero/ns.yaml' : evalsymlink failure on '/Users/aleph/go/src/github.com/stefanprodan/helm-flux-kustomize-test/base/velero/ns.yaml' : lstat /Users/aleph/go/src/github.com/stefanprodan/helm-flux-kustomize-test/base/velero/ns.yaml: no such file or directory
Error: accumulating resources: recursed accumulation of path './velero/': accumulating resources: recursed accumulation of path '../../base/velero': accumulating resources: accumulating resources from 'ns.yaml': evalsymlink failure on '/Users/aleph/go/src/github.com/stefanprodan/helm-flux-kustomize-test/base/velero/ns.yaml' : lstat /Users/aleph/go/src/github.com/stefanprodan/helm-flux-kustomize-test/base/velero/ns.yaml: no such file or directory
```

**Comment by kkunkel** [comment]
@stefanprodan, I missed base/velero/kustomization in a commit and submitted another commit which I think you may have missed. This is the output I get: 
```kkunkel@IT-USA-17707:~/IdeaProjects/flux-test/DEV$ kustomize build .
Error: accumulating resources: recursed accumulation of path './velero/': accumulating resources: recursed accumulation of path '../../base/velero': no matches for OriginalId apps_v1_DaemonSet|velero|restic; no matches for CurrentId apps_v1_DaemonSet|velero|restic; failed to find unique target for patch apps_v1_DaemonSet|restic
kkunkel@IT-USA-17707:~/IdeaProjects/flux-test/DEV$ kustomize build .
Error: accumulating resources: recursed accumulation of path './velero/': accumulating resources: recursed accumulation of path '../../base/velero': no matches for OriginalId apps_v1_DaemonSet|velero|restic; no matches for CurrentId apps_v1_DaemonSet|velero|restic; failed to find unique target for patch apps_v1_DaemonSet|restic
kkunkel@IT-USA-17707:~/IdeaProjects/flux-test/DEV$ cd ..
kkunkel@IT-USA-17707:~/IdeaProjects/flux-test$ kustomize build DEV
Error: accumulating resources: recursed accumulation of path './velero/': accumulating resources: recursed accumulation of path '../../base/velero': no matches for OriginalId apps_v1_DaemonSet|velero|restic; no matches for CurrentId apps_v1_DaemonSet|velero|restic; failed to find unique target for patch apps_v1_DaemonSet|restic
kkunkel@IT-USA-17707:~/IdeaProjects/flux-test$ kustomize version
Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:linux GoArch:amd64}
```

**Comment by stefanprodan** [comment]
You haven't removed the namespace from base/restic-daemonset-patch.yaml :)

**Comment by kkunkel** [comment]
Well...

My ignorance is confirmed and here for posterity. Please correct my understanding if necessary:

When using Flux+Kustomize to perform last mile modification to the output of a Helm template that lacks the namespace element in muliple envrionments within the same repository, the namespace attribute must be declared within the environments' .flux.yaml

Is that the best solution?

**Comment by stefanprodan** [comment]
@kkunkel the namespace patching has nothing to do with Flux, this is how Kustomize works. I think this PR should be closed, adding the namespace to Helm template is not the solution that you're looking for, in fact the namespace should be eluded from base for your kustomization to work.

**Comment by prydonius** [comment]
Thanks for helping resolve this @stefanprodan, and glad you were able to get your usecase working @kkunkel!

**Pull request closed without merging**
