### PR TITLE
[stable/nginx-ingress] Upgraded to 0.19.0.

### PR DESCRIPTION
**Pull request by jpds**
**What this PR does / why we need it**: Upgrade to 0.19.0.

### CODE REVIEW

**Comment by jpds** [comment]
`/approve` ?

**Comment by cpanato** [comment]
@jpds the owners from chart have this power 😄

**Comment by jpds** [comment]
Hmm, that's not what happened in #7276, but OK.

**Comment by cpanato** [comment]
in that PR the owner approved -> https://github.com/helm/charts/pull/7276#issuecomment-416439147

**Comment by cpanato** [comment]
I can try :)

/approve

**Pull request merged**
