### PR TITLE
[stable/elasticsearch] Update elastic to 6.6.1

### PR DESCRIPTION
**Pull request by ialidzhikov**
Signed-off-by: ialidzhikov <i.alidjikov@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by BenTheElder** [comment]
[test-infra maintainer trying to ensure prow is not having issues for helm/charts again, apparently the trust settings for this repo are just collaborators, so I can't actually check 🤷‍♂️]

**Comment by desaintmartin** [comment]
Let me try, use me as a remote control. :)
/assign
/test pull-charts-e2e

**Comment by desaintmartin** [comment]
It reads "job triggered", I assume it is ok (even if I'm probably 2 days late).
/ok-to-test

**Comment by desaintmartin** [comment]
Back to @ialidzhikov: thanks!
/lgtm

**Pull request merged**
