### PR TITLE
[stable/bitcoin] Fix deployment resources mapping

### PR DESCRIPTION
**Pull request by ghostbuster91**
#### What this PR does / why we need it:

This PR fixes deployment resources mapping. Actual code does not map resources from values properly to deployment resources because the amount of indentation is incorrect.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by ghostbuster91** [comment]
As stated in guidelines I'm mentioning maintainers: @govale @daniel-yavorovich

**Comment by ghostbuster91** [comment]
Hi, can we merge it?

**Review by cpanato — APPROVED** [review]

**Comment by ghostbuster91** [comment]
Thanks!

**Pull request merged**
