### PR TITLE
[stable/verdaccio] add env value

### PR DESCRIPTION
**Pull request by rgaskill**
@etiennetremel

#### What this PR does / why we need it:
Adds the ability to specify environment variables on the deployment.  Hand for providing secret to the container.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by etiennetremel** [comment]
lgtm

**Comment by rgaskill** [comment]
Am I missing a step for approval?

**Comment by etiennetremel** [comment]
Unfortunately I'm not a maintainer but since it has been more than a month that this PR is open, maybe you should ask on Slack if someone can help merging it

**Pull request closed without merging**
