### PR TITLE
[stable/airflow] Add log persistence for workers

### PR DESCRIPTION
**Pull request by bnutt**
#### What this PR does / why we need it:
Currently there is not an option to mount logs persistence for worker pods, so unless you are using s3, gcs, etc, you cannot store logs via a  PVC store and use something like EFS to write logs. This results in loss of logs between deployments of worker pods and being unable to see logs in webui.

Signed-off-by: Brian Nutt <brian@slice.com>
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
@bnutt 
Could you show me sample usage ? Do you plan to create volume separately ?

**Comment by bnutt** [comment]
> @bnutt
> Could you show me sample usage ? Do you plan to create volume separately ?

I plan to use EFS for this, so my logsPersistence would look something like this:

##
## Storage configuration for logs
logsPersistence:
  ##
  ## enable persistance storage
  enabled: true
  ##
  ## Existing claim to use
  # existingClaim: nil
  ##
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## A configuration for shared log storage requires a `storageClass` that
  ## supports the `ReadWriteMany` accessMode, such as NFS or AWS EFS.
  storageClass: efs
  accessMode: ReadWriteMany
  ##
  ## Persistant storage size request
  size: 4Gi

Optionally, I could use an existing claim, but here I am using efs-provisioner to create the pvc for me, this should allow for the logs to be on all worker pods even if they have been replaced.

**Comment by maver1ck** [comment]
And why you can't do this with existing:
* extraConfigmapMounts 
* extraVolumes

**Comment by bnutt** [comment]
> And why you can't do this with existing:
> 
> * extraConfigmapMounts
> * extraVolumes

I could do this with extraVolumes as well, but it was an attempt to make it consistent since other airflow services have ability to use logs persistence. More than happy to just use extraVolumes/extraVolumeMounts to do the same

**Comment by cpanato** [comment]
i think we can go to `extraVolumes/extraVolumeMounts`

**Comment by bnutt** [comment]
SGTM, I will close this for now then.

**Comment by gsemet** [comment]
Maybe we can add a tips in the README on how to use extraVolumes to keep logs

**Pull request closed without merging**
