### PR TITLE
Jenkins LTS 2.46.1

### PR DESCRIPTION
**Pull request by jwhitcraft**
- Latest LTS
- Latest Git Plugin
- Migrated base image to the official jenkins docker repo instaed of the official library as they are automaticly updated when released and the official docker libraray is just a clone of the official jenkins once

### CODE REVIEW

**Comment by jwhitcraft** [comment]
Here is the reasoning i moved away from the docker official library to the jenkinsci official image

https://github.com/jenkinsci/docker/issues/461#issuecomment-290906258

**Comment by jwhitcraft** [comment]
Ping @mgoodness @viglesiasce @scottrigby

**Comment by scottrigby** [comment]
@jwhitcraft I'm on plane wifi now (slow!) but I'll check after we land. Likely in the morning. But based on @rtyler and @carlossg comments this sounds like the correct approach. 

As a side note, I've been wondering why so many of the charts I've worked with so far are not using the standard images for each app (in some cases I know there are no regulary updated / standard / security-reviewed images, hence Bitnami images etc).

**Comment by jwhitcraft** [comment]
@scottrigby, I would imagine it's because of the default plugins, and since the jenkins container has no way to install plugins on startup we are stuck with doing it this way.

Maybe we can work the the jenkins guys and adjust the docker image to allow passing a list of plugins as environment an environment variable or something.

**Comment by jwhitcraft** [comment]
Closing this in favor of #921 

/close

**Pull request closed without merging**
