### PR TITLE
stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml  change:  CoreDNSDown to monitor coredns job

### PR DESCRIPTION
**Pull request by ira-shumacher**
CoreDNSDown currently looks at kube-dns metric and not coredns

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bismarck** [comment]
Please see the [note](https://github.com/helm/charts/blob/bc492cd5ee88917e998013cfbf965dedae0e479e/stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml#L1-L3) at the top of the file you're modifying.  Also, you must [sign ](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work)your commits.

**Comment by ira-shumacher** [comment]
Signed-off-by: Ira Shumacher <shumacher.ira@kenshoo.com>

**Comment by vsliouniaev** [comment]
Rules are sourced from another repository as described here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/README.md#developing-prometheus-rules-and-grafana-dashboards

The intention behind `kube-dns` being the name of the service is that this is the kubernetes DNS service and the specific implementation is not relevant. Common Kubernetes deployment processes take this stance, so that is the reason why the above-mentioned rules repository does this as well. If your specific instance has another name it is likely because your installation process is different. If you would like to customize this option, or other rules configurations the best option you have is to deploy the rules separately to this chart.

/hold

**Pull request closed without merging**
