### PR TITLE
Kamus

### PR DESCRIPTION
**Pull request by omerlh**
#### What this PR does / why we need it:
Add [Kamus](https://github.com/Soluto/kamus) helm chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by lachie83** [comment]
@omerlh Can you please sign your commits? Take a look at the DCO bot about how to do that

**Comment by omerlh** [comment]
Thanks @lachie83, forget that on my last commit - should be fixed now. The e2e/tide are running for ever, is that expected?

**Comment by lachie83** [comment]
Thanks. It's probably not running. Let me try and bump it

**Comment by omerlh** [comment]
Aha! look like it is not running:
```
I0107 17:50:58.128] Will upload results to gs://kubernetes-jenkins/pr-logs using pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
I0107 17:50:58.129] Call:  kubectl get -oyaml pods/af54ee31-12a4-11e9-911b-0a580a6c0030
W0107 17:50:58.303] The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0107 17:50:58.308] Command failed
```

**Comment by omerlh** [comment]
That's me:
```
kubelet, gke-jenkins-default-pool-51cafeba-qkh4  Liveness probe failed: Get http://10.0.9.211:9999/api/v1/isAlive: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
How can I see the pods logs or connect to the environment?

**Comment by omerlh** [comment]
Ok, my mistake - look like the tests are passing now 🤷‍♂️ Tide is pending because it's waiting for approvals?

**Comment by lachie83** [comment]
It looks like the automatic trigger of the e2e tests isn't working. I just manually enabled it by adding the label

**Comment by omerlh** [comment]
What are the next steps? Can you please review the PR?

**Comment by omerlh** [comment]
Moved to our own hosted [chart repository](https://charts.soluto.io), per the new guidelines.

**Pull request closed without merging**
