### PR TITLE
Fix issue when upgrading sonarqube to the latest LTS (6.7.2)

### LINKED ISSUE #4787: [stable/sonarqube] changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh': Read-only file system
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.8.2 Kubernetes 1.9.6

**Which chart**: sonarqube-0.3.6

**What happened**: sonarqube pod fails with the message ``chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh': Read-only file system``

```
NAME                                  READY     STATUS             RESTARTS   AGE       IP              NODE
sonarqube-sonarqube-6c8c666d7-bhcq8   0/1       CrashLoopBackOff   3          1m        10.233.65.157   kub02

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE       SELECTOR
sonarqube-postgresql   ClusterIP   10.233.60.130   <none>        5432/TCP   1m        app=sonarqube-postgresql
sonarqube-sonarqube    ClusterIP   10.233.9.11     <none>        9000/TCP   1m        app=sonarqube,release=sonarqube

NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS             IMAGES            SELECTOR
sonarqube-postgresql   1         1         1            1           1m        sonarqube-postgresql   postgres:9.6.8    app=sonarqube-postgresql
sonarqube-sonarqube    1         1         1            0           1m        sonarqube              sonarqube:6.7.2   app=sonarqube,release=sonarqube

NAME                            DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES            SELECTOR
sonarqube-sonarqube-6c8c666d7   1         1         0         1m        sonarqube    sonarqube:6.7.2   app=sonarqube,pod-template-hash=274722283,release=sonarqube

NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS             IMAGES            SELECTOR
sonarqube-postgresql   1         1         1            1           1m        sonarqube-postgresql   postgres:9.6.8    app=sonarqube-postgresql
sonarqube-sonarqube    1         1         1            0           1m        sonarqube              sonarqube:6.7.2   app=sonarqube,release=sonarqube

NAME                            DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES            SELECTOR
sonarqube-sonarqube-6c8c666d7   1         1         0         1m        sonarqube    sonarqube:6.7.2   app=sonarqube,pod-template-hash=274722283,release=sonarqube
```

**What you expected to happen**: sonarqube pod has to up and running

**How to reproduce it** (as minimally and precisely as possible):

``helm install -n sonarqube --namespace sonarqube -f values.yaml stable/sonarqube``

values.yaml
```yaml
---
image:
  repository: sonarqube
  tag: 6.7.2

service:
  name: sonarqube
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000

ingress:
  enabled: false

persistence:
  enabled: false

postgresql:
  imageTag: "9.6.8"
  postgresUser: "sonarqube"
  postgresPassword: "sonarqube"
  postgresDatabase: "sonarqube"
  persistence:
    enabled: false
```

**Anything else we need to know**: Nope

### PR DESCRIPTION
**Pull request by shuraa**
**What this PR does / why we need it**: fix issue when upgrading sonarqube up to 6.7.2

**Which issue this PR fixes**: fixes #4787

**Special notes for your reviewer**: the change might be look a bit weird, but actually install_script.sh isn't required outside of the ``install-plugins`` init container :)

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @rjkernick

**Review by rjkernick — APPROVED** [review]

**Comment by shuraa** [comment]
Is any chance to merge this PR in the nearest future :) ?

**Pull request merged**
