### PR TITLE
[stable/parse] Fix security context disabling misspellings

### PR DESCRIPTION
**Pull request by tjg184**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@tjg184 
Please sign DCO and bump the chart version to latest. Thank you.

**Comment by juan131** [comment]
Hi @tjg184 

As @zanhsieh mentioned, it's mandatory to bump the version of the chart (even for trivial changes in the README.md like this one). Could you please bump the patch version in the Chart.yaml?

Please also note that you need to signoff your commit, otherwise the CI won't merge your contributions.

**Comment by tjg184** [comment]
Ok, I think everything should be completed now.

**Comment by juan131** [comment]
Hi @tjg184 

The DCO tests are still failing. There must be commits without signing.

You also need to rebase your PR from master since there are conflicting files with master.

**Pull request merged**
