### PR TITLE
stable/prometheus Updated README.md with instructions for configuring pod scraping

### PR DESCRIPTION
**Pull request by adamkpickering**
Signed-off-by: Adam Pickering <adamkpickering@gmail.com>

#### Is this a new chart

No.

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

The chart has a default prometheus configuration that enables annotations to be added to API resources, which causes prometheus to then scrape them. This is not documented and I lost a couple hours on this, so I figured I'd update the documentation.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by adamkpickering** [comment]
/assign @zanhsieh

I think I did everything right. How confusing that dco-labeler passes but DCO does not...

**Comment by zanhsieh** [comment]
@adamkpickering 
Based on "Details" next to DCO below:

```
Commit sha: 68367f9, Author: Adam Pickering, Committer: Adam Pickering; Expected "Adam Pickering adamkpickering@telus.com", but got "Adam Pickering adamkpickering@gmail.com".
```

**Comment by adamkpickering** [comment]
/assign @zanhsieh

Ok I think I fixed it.

**Comment by zanhsieh** [comment]
@adamkpickering 
Could you sign DCO as the 'Detail' shows on bottom of this page?

/ok-to-test

**Review by zanhsieh — APPROVED** [review]

**Comment by adamkpickering** [comment]
@zanhsieh my apologies. I had thought I had fixed the discrepancy between email addresses prior to my second comment but I seem to have fallen victim to Friday brain. Let me know if there is anything else I can do.

**Comment by zanhsieh** [comment]
@adamkpickering 
Chart version still need to bump. Click Details next to lint-charts in the bottom of this page to see the reason.

**Comment by adamkpickering** [comment]
@zanhsieh 
Ah I see. I was assuming the chart didn't need a version bump because it was a documentation change. Done, hopefully that's the last thing...

**Comment by adamkpickering** [comment]
@zanhsieh What is the status of this PR? As far as I can tell we're waiting for @gianrubio to review it. Or are we waiting for something else?

**Comment by zanhsieh** [comment]
@adamkpickering 
Please scroll down to the bottom of this PR, you should see two outstanding issues before merging.

**Comment by adamkpickering** [comment]
@zanhsieh @gianrubio Ok should be good. Sorry for taking so long to get this sorted out, I'm new to contributing to software like this.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
