### PR TITLE
[stable/fluent-bit] Fixes compatibility with 1.16

### PR DESCRIPTION
**Pull request by daixiang0**
To support 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by drakedevel** [comment]
@daixiang0 apologies for the drive-by feedback, but the chart with this PR doesn't install on Kubernetes 1.16 for me. The `selector` field on DaemonSetSpec became mandatory after extensions/v1beta1, and is absent in this chart. The result is an error like this when the chart is installed initially:

```
Error: release fluent-bit failed: DaemonSet.apps "fluent-bit" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"fluent-bit", "release":"fluent-bit"}: `selector` does not match template `labels`
```

Before I saw this PR, I hacked up this version of the fix:

```diff
--- a/stable/fluent-bit/templates/daemonset.yaml
+++ b/stable/fluent-bit/templates/daemonset.yaml
@@ -1,4 +1,4 @@
-apiVersion: extensions/v1beta1
+apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   name: {{ template "fluent-bit.fullname" . }}
@@ -8,6 +8,13 @@ metadata:
     heritage: {{ .Release.Service }}
     release: {{ .Release.Name }}
 spec:
+  selector:
+    matchLabels:
+      app: {{ template "fluent-bit.name" . }}
+      release: {{ .Release.Name }}
+{{- if .Values.podLabels }}
+{{ toYaml .Values.podLabels | indent 6 }}
+{{- end }}
   updateStrategy:
     type: RollingUpdate
   template:
```

That works for me on 1.16, feel free to use it in your PR if it's helpful.

**Comment by daixiang0** [comment]
@drakedevel it would be good, i use it.

**Comment by zanhsieh** [comment]
@daixiang0 
Need a version bump again.

**Comment by daixiang0** [comment]
@zanhsieh test pass!

**Comment by daixiang0** [comment]
@zanhsieh test pass!

**Comment by zanhsieh** [comment]
@kfox1111
@edsiper
@hectorj2f
@Towmeykaw
Could you approve this?
/cc @Towmeykaw

**Comment by drakedevel** [comment]
It looks like #17838 duplicates this but got merged first, so this PR is probably redundant now.

**Pull request closed without merging**
