### PR TITLE
Fix configuration name

### PR DESCRIPTION
**Pull request by pgbezerra**
Documentation is wrong.

### CODE REVIEW

**Comment by stijndehaes** [comment]
If you look at current master expose config is under webserver:

https://github.com/puckel/docker-airflow/blob/master/config/airflow.cfg

**Comment by paulobezerr** [comment]
sorry @stijndehaes, fixed.

**Comment by stijndehaes** [comment]
@gsemet Could you review this?

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
Ok for me, you just need to update the version (minor)

**Comment by paulobezerr** [comment]
finished.

**Comment by gsemet** [comment]
Perfect !
/lgtm

**Pull request merged**
