### PR TITLE
[stable/kafka-manager] add Release.Namespace

### PR DESCRIPTION
**Pull request by anragen**
add Release.Namespace when port-forward

#### Is this a new chart
NO

#### What this PR does / why we need it:
add Release.Namespace when port-forward
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by giacomoguiulfo** [comment]
@anragen Thanks for your PR. Can you make a `patch` version bump to the Chart.yaml

**Comment by scottrigby** [comment]
DCO sign-off is also not on the commit, which will need to be fixed before merge

**Comment by anragen** [comment]
> DCO sign-off is also not on the commit, which will need to be fixed before merge

fixed

**Comment by anragen** [comment]
> @anragen Thanks for your PR. Can you make a `patch` version bump to the `Chart.yaml`

fixed

**Pull request closed without merging**
