### PR TITLE
Update to latest Minio helm chart

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by nitisht** [comment]
fixes https://github.com/kubernetes/charts/issues/6351

**Comment by unicman** [comment]
Is there any specific reason tide and pull-charts-e2e are waiting for last few days? tide seems to be waiting for some manual review but other one seems to be a automated routine which should have finished by now I guess?

**Comment by nitisht** [comment]
Closing this as Spinnaker chart is already updated

**Pull request closed without merging**
