### PR TITLE
[incubator/gogs] Features added in gogs

### PR DESCRIPTION
**Pull request by ribeiromiranda**
#### What this PR does / why we need it:
* Gogs version 0.11.86
* Added mailer
* Added nodeSelector, affinity, tolerations
* Added existing persistence volume

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

Signed-off-by: André R. de Miranda <andre@miranda.work>

### CODE REVIEW

**Comment by obeyler** [comment]
@mirandawork Thanks for this PR.
Could you explain me why you add a persistence volume claim for Postgres ?
I think that the volume is already required by postgres helm chart dependency.

**Comment by mirandawork** [comment]
@obeyler The change was made in the persistence volume of gogs and not of the postgres. This change add the option to use a PVC was created manually.

I made other change https://github.com/helm/charts/pull/11652/commits/9de8a97a95891e6086208ba0bfea6e8d81b45383 because I had forgotten to add the key 'existingClaim' in the file values.yaml.

**Review by obeyler — APPROVED** [review]

**Pull request merged**
