### PR TITLE
[stable/reloader] Adds imagePullSecrets and securityContext

### PR DESCRIPTION
**Pull request by marcostvz**
#### What this PR does / why we need it:
Adds imagePullSecrets to ServiceAccount

Adds securityContext to Deployment

Updates stakater/reloader image to v0.0.41

Moves examples from README.md to values.yaml

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by marcostvz** [comment]
@faizanahmad055 who should I assign this to review/accept? Thanks!

**Comment by faizanahmad055** [comment]
@marcostvz We will review and merge this PR soon.

**Comment by marcostvz** [comment]
Ok, if you do not mind, I will bring all the changes you have in the other chart.

**Comment by faizanahmad055** [comment]
@marcostvz Yes sure, that would be great.

**Comment by marcostvz** [comment]
@faizanahmad055 please, take a look. I also submitted https://github.com/stakater/Reloader/pull/101 syncing back my changes from here, if you can take a look at that too, double thanks :).

**Comment by faizanahmad055** [comment]
@marcostvz Sure, someone from team will check and merge that soon.

**Review by faizanahmad055 — APPROVED** [review]

**Pull request merged**
