### PR TITLE
[stable/jenkins] Move kubernetes and job plugins to latest versions

### PR DESCRIPTION
**Pull request by davidcurrie**
Move kubernetes to 1.12.4 and workflow-job to 2.24

Signed-off-by: David Currie <dcurrie@cloudbees.com>

### CODE REVIEW

**Review by carlossg — APPROVED** [review]

**Comment by davidcurrie** [comment]
lol - in the time it took me to work out what the tests were doing and decide that I didn't know why it was failing they'd already re-run and passed!

**Pull request merged**
