### PR TITLE
[stable][airflow] Fix README typo

### PR DESCRIPTION
**Pull request by joegoldbeck**
The code uses `postgresHost` as expected https://github.com/helm/charts/blob/8476460c07f8bdcd61ce030f2724c77963dad0ed/stable/airflow/templates/_helpers.tpl#L40 so this is just a typo

### CODE REVIEW

**Comment by maver1ck** [comment]
@joegoldbeck 
Could you please fix PR ?

**Comment by joegoldbeck** [comment]
@maver1ck are you referring to

```
Checking chart 'stable/airflow' for a version bump...
Old chart version: 0.15.0
New chart version: 0.15.0
Error linting charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ stable/airflow > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
Exited with code 1
```
?

I can certainly bump the version, but I didn't change any code at all, just fixed a typo in the readme so perhaps a version bump is unnecessary?

**Comment by gsemet** [comment]
can you rebase please?

**Comment by gsemet** [comment]
@joegoldbeck can you rebase?

**Comment by joegoldbeck** [comment]
Closing in favor of #11678

**Pull request closed without merging**
