### PR TITLE
Bump Helm to v2.5.1 in CI

### PR DESCRIPTION
**Pull request by viglesiasce**
Needs to be coordinated with Tiller update. In the future I will find a way to automate the Tiller update so we can do these in lock step and without human intervention.

### CODE REVIEW

**Review by prydonius — CHANGES_REQUESTED** [review]
can you also bump the version in the repo-sync script so it's consistent?

**Comment by viglesiasce** [comment]
@prydonius all set. I can upgrade Tiller when ready. Or better yet do you know if tiller is backwards compatible?

**Comment by prydonius** [comment]
@viglesiasce I'm not sure if it is or not, probably best to just upgrade and merge around the same time. I'll leave it to you!

/lgtm

**Review by prydonius — APPROVED** [review]

**Pull request merged**
