### PR TITLE
[stable/gocd] Gocd agent privileged mode for dind

### PR DESCRIPTION
**Pull request by MPV**
**What this PR does / why we need it**:
This adds support for privileged mode, which is required for using the Docker-in-Docker (DinD) GoCD agents.

Without this fix, this is what you're getting in the DinD agents:

```
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
```

...as per my comment here: https://github.com/gocd/docker-gocd-agent/pull/55#issuecomment-410974901

😍 GoCD chart maintainers @arvindsv @GaneshSPatil @varshavaradarajan

### CODE REVIEW

**Comment by bdpiparva** [comment]
@MPV  -- LGTM. This is to support privileged mode on the static agent installed using helm chart. However, we encourage users to use elastic agent over the static agent. You can control the privileged mode for an elastic agent from the elastic profile.

**Comment by arvindsv** [comment]
@GaneshSPatil and @bdpiparva are taking a look at this.

**Comment by GaneshSPatil** [comment]
@MPV -- circle-ci lint is failing for the PR, would you mind taking a look at it?

**Comment by MPV** [comment]
Seems only a version bump of the chart is needed. Would you like me to do that? 

```
ERROR: Chart version not ok. Needs a version bump.
```

**Comment by GaneshSPatil** [comment]
Yes, you need to bump up the chart version and update the changelog file.

**Comment by MPV** [comment]
@GaneshSPatil:
- [X] Chart version bumped.
- [X] Changelog updated.

**Comment by GaneshSPatil** [comment]
@MPV -- Thanks a lot for the PR.

**Comment by MPV** [comment]
Thanks @GaneshSPatil. 

Looks like it might still need a `lgtm` label from someone? 
Possibly by @arvindsv or @bdpiparva ?

**Pull request merged**
