### PR TITLE
Review jenkins networkpolicy docs

### PR DESCRIPTION
**Pull request by gianrubio**

### CODE REVIEW

**Comment by gianrubio** [comment]
The test failed because I didn't increase the chart version, it's really required to increase the version if I'm just changing the readme?

```Error please increment the new chart version to be greater than the existing version of 0.9.0```

**Comment by unguiculus** [comment]
Yes. We decided to be strict about this. Releases should be immutable.

**Comment by gianrubio** [comment]
@unguiculus could you review again?

**Pull request merged**
