### PR TITLE
typo fixed

### PR DESCRIPTION
**Pull request by yaroslavya**
are going are going-> are going

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@yaroslavya please bump the chart version and sign the DCO

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign the DCO](https://github.com/helm/charts/pull/8068/checks?check_run_id=20536522), also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by yaroslavya** [comment]
@cpanato , @carrodher sorry it took a while, seem to be done, can you have a look?

**Comment by cpanato** [comment]
@yaroslavya you need to rebase your branch to get the latest changes and re-bump the chart version

**Comment by yaroslavya** [comment]
@cpanato done, can you have a look, please?

**Pull request merged**
