### PR TITLE
Add Event Store

### PR DESCRIPTION
**Pull request by andymeierdev**
#### What this PR does / why we need it:
- Adds Event Store helm chart to the incubator repo

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by paulczar** [comment]
Have you considered hosting this chart and repository yourself?   Helm's Chart Hub now supports external repositories.  See more here - https://github.com/helm/hub#how-to-add-your-helm-charts

**Review by grigorov — APPROVED** [review]

**Comment by ameier38** [comment]
> Have you considered hosting this chart and repository yourself? Helm's Chart Hub now supports external repositories. See more here - https://github.com/helm/hub#how-to-add-your-helm-charts

@paulczar thanks, it looks neat but I would rather have Event Store added to the stable repo as it makes it easier to install (no need to add a repo first) and it would get better review and support. @riccardone maybe Event Store would like to host the repo themselves?.

**Pull request closed without merging**
