### PR TITLE
[stable/seq] Feature add psp

### PR DESCRIPTION
**Pull request by msschl**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/seq]`)

### CODE REVIEW

**Comment by msschl** [comment]
@gertjvr @nblumhardt @KodrAus any news?

**Comment by msschl** [comment]
@gertjvr @nblumhardt @KodrAus any news?

**Comment by KodrAus** [comment]
Thanks for your patience @msschl! Let's get this one merged in.

**Pull request merged**
