### PR TITLE
[stable/mongodb] Add chart label to template

### PR DESCRIPTION
**Pull request by javsalgar**
Signed-off-by: Javier J. Salmeron Garcia <jsalmeron@bitnami.com>

#### What this PR does / why we need it:
This fixes an issue in the Bitnami automation pipeline of the charts. Without this tag, the charts are not being tested 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
    - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Did you check it doesn't break backwards compatibility or upgrading processes?

**Comment by javsalgar** [comment]
I tested the upgrade and found no issues

**Review by juan131 — APPROVED** [review]
Great thanks!!!

**Pull request merged**
