### PR TITLE
[stable/elasticsearch-exporter] Add imagePullSecret support

### PR DESCRIPTION
**Pull request by jnodorp**
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

This PR adds support for using an image pull secret.

### CODE REVIEW

**Comment by jschlichtholz** [comment]
Is there anything required from side to get this in?

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

@svenmueller, also added you as a trusted collaborator so you can be assigned.

**Pull request merged**
