### PR TITLE
[stable/sentry] Add loadBalancerIP to service

### PR DESCRIPTION
**Pull request by malvex**
**What this PR does / why we need it**: 
This PR allows setting specific loadBalancerIP to service for Sentry helm chart

### CODE REVIEW

**Comment by mattfarina** [comment]
@malvex Thanks for the PR. Before we can merge this you need to signoff on the commits. You can find details at https://github.com/helm/charts/pull/7827/checks?check_run_id=18335238. We usually don't review PRs until they have signoff.

**Comment by malvex** [comment]
@mattfarina Thanks for your reply. First commit wasn't signed, but right after that I ammended signed commit, but for some reason it didnt trigger tests

**Pull request closed without merging**
