### PR TITLE
[stable/mysql] Update mysql user password when it changes

### PR DESCRIPTION
**Pull request by viniciusgama**
#### What this PR does / why we need it:
The mysql user password is only set once. In case you need to change it after your first installation of the chat it will not work. This PR is based on this one https://github.com/helm/charts/pull/3591 and tries to address it by always updating the password and forcing a restart of mysql when it changes

#### Which issue this PR fixes
https://github.com/helm/charts/issues/5499

#### Special notes for your reviewer:
This PR is a revivel of a old one https://github.com/helm/charts/pull/3591. Credits to @komljen 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by olemarkus** [comment]
It is unclear if this is really wanted. See https://github.com/helm/charts/issues/5167 for the long version of this discussion

**Comment by benlangfeld** [comment]
@olemarkus It is not possible to reliably change passwords without this. I strongly encourage this to be accepted, even if hidden behind a feature flag, because it is absolutely essential to managing MySQL using this chart in the real world.

**Comment by benlangfeld** [comment]
@olemarkus Would you please re-consider this?

**Pull request closed without merging**
