### PR TITLE
added support to specify the custom kubernetes cluster domain.

### PR DESCRIPTION
**Pull request by guptaarvindk**
Signed-off-by: Arvind Gupta <guptaarvindk@gmail.com>

**What this PR does / why we need it**:
added support to specify the custom kubernetes cluster domain. cluster.local may not be always true.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by guptaarvindk** [comment]
Hi @prydonius @foxish can you please review this pull request.

**Comment by unguiculus** [comment]
cc @Acaleph @Minio

**Comment by unguiculus** [comment]
Please bump minor version and resolve conflicts.

**Pull request closed without merging**
