### PR TITLE
[stable/sonarqube] Upgrade postgresql chart version

### LINKED ISSUE #20414: [stable/sonarqube] Upgrade Postgresql/Mysql sub chart version
Postgresql and Mysql charts are very old (> 2 years)
postgresql : 0.8.3 
mysql : 0.6.0

We are missing extra feautre that are available in more recent version.

**Is your feature request related to a problem? Please describe.**
I need to add anotations to Postgresql PVC. This is not possible in current chart version.

**Describe the solution you'd like**
Upgrade chart version to latest versions

### PR DESCRIPTION
**Pull request by sparqueur**
#### What this PR does / why we need it:
Sonarqube uses a very old version of Postgresql Chart. We miss some features provided by new versions such as being able to add annotations.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #20414 (partial fix)

#### Special notes for your reviewer:

Postgresql chart values attribute name have change. I had to update them.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rjkernick** [comment]
Thanks for the PR. All commits must be signed off in order to be merged into this repository. Report of issues can be found: https://github.com/helm/charts/pull/20420/checks?check_run_id=414852616

**Comment by sparqueur** [comment]
Hi @rjkernick ,
I've done the updates. Sorry, I am not used with signing my commits ;-)

**Pull request merged**
