### PR TITLE
[incubator/raw] Resource templates

### PR DESCRIPTION
**Pull request by mumoshu**
This is handy when you basically want an adhoc helm chart that securely generates Kubernetes secrets with a tool like [helm-secrets](https://github.com/futuresimple/helm-secrets).

Signed-off-by: Yusuke Kuoka <ykuoka@gmail.com>

### CODE REVIEW

**Comment by mumoshu** [comment]
@josdotso Hey! Would you mind reviewing this?

Also, I've added myself as a another Chart reviewer/approver to helm maintain this chart. If you don't mind, please let me help 😄

**Comment by josdotso** [comment]
Ah well.. this looks awesome! haha. And thanks for the help on reviewing.

/approve
/lgtm
/okay-to-test

**Comment by mumoshu** [comment]
@josdotso Thanks for reviewing! I had to add a harmless raw resource in the default values.yaml https://github.com/helm/charts/blob/56d5b63d2998bcd519b52639b586d896b9016633/incubator/raw/values.yaml#L68-L73 to pass the chart ci.

Perhaps there was't chart ci when you first authored this chart, that's why we didn't have one before.

**Comment by mumoshu** [comment]
@josdotso Maybe /lgtm once again flows everything again

**Comment by josdotso** [comment]
Thanks. Yes, I don't think CI was instituted at the time I authored this. 

/lgtm

**Comment by mumoshu** [comment]
@josdotso Thanks for the confirmation and reviewing ☺️

**Pull request merged**
