### PR TITLE
add pod selector on cassandra statefulsets

### PR DESCRIPTION
**Pull request by code0x9**
**What this PR does / why we need it**: Use updated K8S StatefulSet spec, so that cassandra can be installed on K8S > 1.9. See https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-selector

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by evanstucker-hates-2fa** [comment]
I built a cluster on AWS using kops recently, and this PR fixes the issue for me.
```
cd /home/evans/github.com/helm/charts
git fetch origin pull/7285/head:7285
git checkout 7285
helm install /home/evans/github.com/helm/charts/incubator/cassandra
```

**Comment by batazor** [comment]
@viglesiasce @seanknox please review this PR

**Comment by maeb** [comment]
The duplicate PR https://github.com/helm/charts/pull/7348 (exactly the same fix + cassandra version upgrade) seems to be closer to getting merged so I suggest no more resources be spent on this one.

**Comment by code0x9** [comment]
@maeb Do you really think someone can 'contribute' to this repo by watching PRs and add version tag to original PR, because that one seems to be closer to getting merged? If so, who's gonna spend their time and effort on here? At least, I won't.

**Comment by maeb** [comment]
@code0x9 I'm just interested in getting the fix for this issue merged ASAP cause I rely on it in production. I already commented in the other issue that it was a duplicate of this one - intending that one to be abandoned. When members of the Helm Project then proceeds with reviewing the other PR what am I supposed to do. Just trying to minimize double effort.

**Comment by maeb** [comment]
@code0x9 I prefer this PR because it fixes the issue and NOTHING else. That was the problem with the commit causing the issue in the first place; "small refactoring, oh well I'll just bump the API version while I'm at it".

**Comment by MPV** [comment]
@code0x9 There seems to be a conflict in `incubator/cassandra/Chart.yaml`? 😊

**Comment by robermorales** [comment]
Some news??

**Comment by rwkarg** [comment]
Bump.
This issue has been outstanding for almost a month now... 😞 It just needs the chart version bumped since it's been waiting.

**Comment by hairmare** [comment]
I just checked that it also works with `helm install --set podLabels.foo=bar`.

@code0x9 Could you assign an OWNER to get the ball rolling? Posting `/assign @foxish` as per the bots recommendation will probably help surface this.

/lgtm

**Comment by Tabrizian** [comment]
This is a very nice job and Cassandra chart doesn't work now, when is it going to be merged?

**Comment by thedodd** [comment]
Yea, I tested these changes out on a k8s cluster running the latest k8s release. Seems to be working well. 

Just need to get this PR merged.

**Pull request closed without merging**
