### PR TITLE
Add service label values for Nexus

### PR DESCRIPTION
**Pull request by kyle-williams-1**
Enable use of custom service labels for the Nexus chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
    - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rjkernick** [comment]
Had a PR get merged ahead of yours. Please resolve/update the Chart.yaml.

**Comment by kyle-williams-1** [comment]
Merge conflict resolved

**Comment by rjkernick** [comment]
thanks for the quick turnaround on the feedback

**Pull request merged**
