### PR TITLE
[stable/kong]: added updateStrategy property

### PR DESCRIPTION
**Pull request by landorg**
Signed-off-by: Roland Gritzer <gritzer.roland@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by rolandg** [comment]
removed the other PR and recreated. 
Not 100% sure about the default values.
Please check.

**Comment by hbagdi** [comment]
Let's open up the entire strategy part of the deployment manifest to end users and keep rolling update as a default.
This is a whole can of worms, and other users will want to experiment with other types of strategy or tweak some other configuration.

Please see: https://github.com/helm/charts/blob/master/stable/openvpn/values.yaml#L6

**Comment by hbagdi** [comment]
Please add a test-case (re-use an existing one) in ci directory which specifies the a strategy.
This will ensure that the manifest is rendered correctly when strategy is specified.

**Comment by rolandg** [comment]
I have tried to add a test. Please check.
Not sure how to resolve the merge conflict witout write access.

**Comment by hbagdi** [comment]
@rolandg You can do:
```
# update local master branch
git checkout master
git pull origin master
# and then rebase it
git checkout pr
git rebase master
# there might be conflicts that git reports that you will have to resolve
git push --force
```


I can't see any test case that you have added in the CI directory.
Please specify an updateStrategy section in the following YAML:
https://github.com/helm/charts/blob/master/stable/kong/ci/loadbalancer-values.yaml#L3

**Comment by rolandg** [comment]
@hbagdi thanks for the pointers. seems to work now

**Pull request merged**
