### PR TITLE
wordpress: Small fixes in values.yaml

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Typo and other small fixes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
LGTM!

**Comment by sameersbn** [comment]
thanks @juan131 
/lgtm

**Pull request merged**
