### PR TITLE
[stable/postgresql] Fix `initdbScripts`; add `postgresqlExtendedConf` to pass appended configuration via values

### LINKED ISSUE #8916: [stable/postgresql] Read postgresql.conf / pg_hba.conf overrides from values
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

[stable/postgresql](https://github.com/helm/charts/tree/master/stable/postgresql) chart reads complete `postgresql.conf` and `pg_hba.conf` from files. This is inflexible. I propose to change this chart to:

1. Read configuration overrides from values instead of files (see [stable/rabbitmq](https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L99) for example);
2. Allow extending `postgresql.conf` instead of overriding it (cf. bitnami/bitnami-docker-postgresql#90).

### LINKED ISSUE #10284: [stable/postgresql] `init-scripts` configmap is skipped with non-null `.Values.initdbScripts`
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

[stable/postgresql](https://github.com/helm/charts/tree/master/stable/postgresql)

**What happened**:

`.Values.initdbScripts` is not honored

**What you expected to happen**:

`.Values.initdbScripts` should be honored

**How to reproduce it** (as minimally and precisely as possible):

1. Edit `values.yaml` to include:
    ```
    initdbScripts:
      test.sh: |
        #!/bin/sh
    ```

2. Deploy stable/postgresql chart

3. Run `kubectl get configmaps -l release=<release>`

4. Observe no `<release>-init-scripts` configmap created

**Anything else we need to know**:

Missing condition at https://github.com/helm/charts/blob/master/stable/postgresql/templates/initialization-configmap.yaml#L1

### PR DESCRIPTION
**Pull request by intelfx**
#### What this PR does / why we need it:

Fixes issues, because less issues is better.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - _actually_ fixes #8916
  - fixes #10284

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
What about the existing `.Values.postgresqlConfiguration` ?

**Comment by intelfx** [comment]
@desaintmartin Just like with `.Values.configurationConfigMap` vs. `.Values. extendedConfConfigMap`, it has different semantics: if specified, it overrides default configuration completely.

Or do you want me to change semantics of the existing option? I can do that, but it’ll be a breaking change.

**Comment by tompizmor** [comment]
I didn't realize there was already a PR for fixing this and sent this one that is already merged. 
In any case this PR is more complete than mine so I think you should rebase my changes from master anb then merge this one too. What do you think @intelfx?

**Comment by intelfx** [comment]
Fine. Stand by for rebase.

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by tompizmor** [comment]
@intelfx It seems you need to re-bump the chart version

**Comment by intelfx** [comment]
@tompizmor I thought I bumped it to 3.8.0 with last commit?

**Comment by intelfx** [comment]
@tompizmor Roger. Force-pushed, please recheck.

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by tompizmor** [comment]
Thanks, @intelfx!! Finally merged!

**Pull request merged**
