### PR TITLE
stable/mysql add resources to init container

### LINKED ISSUE #12438: [stable/mysql]
We should be able to specify the resource/limits of the init container

https://github.com/helm/charts/blob/798226aac49d8f28bca9b6afb03a89df8ce1d467/stable/mysql/templates/deployment.yaml#L25

### PR DESCRIPTION
**Pull request by skang0601**
Signed-off-by: Sung Kang <skang0601@gmail.com>

#### What this PR does / why we need it:
The current MySQL chart will fail to deploy to clusters that set [ResourceQuotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) due to the being unable to set resources on the init-container.

#### Which issue this PR fixes
  - fixes #12438

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by olemarkus** [comment]
/assign

Thanks for the PR. Can you fix the test failures and the DCO?

**Comment by skang0601** [comment]
@olemarkus Let me know if things look fine, sorry for the delayed response I've in the middle of traveling.

**Comment by skang0601** [comment]
Looks like the test failed due to another change going in to the chart before the PR got merged. I bumped up the version and pushed some new changes.

**Pull request merged**
