### PR TITLE
[stable/metrics-server]

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### What this PR does / why we need it:
Fix cluster roles for metrics-server. In this way metrics-server is able to list all namespaces. 
Metrics-server version bump

#### Special notes for your reviewer:
Ref: https://github.com/kubernetes-incubator/metrics-server/issues/293
Ref: https://github.com/kubernetes-incubator/metrics-server/pull/296

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mariomarin** [comment]
Please merge this pull request

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus and now?

**Comment by olemarkus** [comment]
Looks like metrics-server is not stopping properly. Not sure if that is related to the version bump. You could try splitting this PR in two

**Comment by PierluigiLenociAkelius** [comment]
We have a concurrent PR here: https://github.com/helm/charts/pull/15919/files

**Comment by olemarkus** [comment]
> We have a concurrent PR here: #15919

This one has some unresolved comments

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus I did it https://github.com/helm/charts/pull/16606

**Comment by PierluigiLenociAkelius** [comment]
I will close this because is useless. Ref: https://github.com/helm/charts/pull/16618 or https://github.com/helm/charts/pull/16606

**Comment by PierluigiLenociAkelius** [comment]
https://github.com/helm/charts/pull/16654

**Pull request closed without merging**
