### PR TITLE
[stable/sentry] Add post-upgrade hook to db-init job

### PR DESCRIPTION
**Pull request by gordcorp**
#### What this PR does / why we need it:

The db-init job invokes `sentry upgrade`, which runs the db migrations.
When a chart upgrade is applied which includes a new version of Sentry, it seems desirable to run this job, so this PR adds a hook to do so. The command seems to be safe to run even when the sentry version has not changed as part of the upgrade.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

pinging @rothgar

### CODE REVIEW

**Comment by mattfarina** [comment]
/ok-to-test
cc @rothgar

**Comment by gordcorp** [comment]
Tests look ok now.

I did some digging to confirm `sentry upgrade` is safe to run each time - and yes it is according to  https://forum.sentry.io/t/is-it-safe-to-run-sentry-upgrade-noinput-every-time-sentry-is-restarted/2808/3

/assign @okgolove - sorry just noticed you are the chart owner now.

**Pull request merged**
