### PR TITLE
No placeholder in command

### PR DESCRIPTION
**Pull request by AdamDang**
Line 38:  *Replace the `x.x.x` placeholder with the chart release version.*
But there is no placeholder in command in line 35.

### CODE REVIEW

**Comment by timstoop** [comment]
Your change would actually break the command. Did you actually try the command as given? Because it works fine, no placeholder is needed, as it's referring to the Chart itself, not an image.

**Comment by timstoop** [comment]
Ah, I see it now, I'd recommend to use the line about the placeholder instead. I do not see any value in that.

**Comment by AdamDang** [comment]
@timstoop I prefer to delete the "...replace ..." content too. It's done, Thanks!

**Pull request merged**
