### PR TITLE
Added helm chart for federation v2.

### LINKED ISSUE #8559: Adding federation v2 helm chart
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Kubernetes: 1.11+
Helm: 2.10+

**Which chart**:
A new federation v2 chart https://github.com/kubernetes-sigs/federation-v2/tree/master/charts/federation-v2

We want to host the federation helm chart at here.

### PR DESCRIPTION
**Pull request by gyliu513**
Signed-off-by: Guang Ya Liu <gyliu513@gmail.com>

#### What this PR does / why we need it:
This is a chart copied from https://github.com/kubernetes-sigs/federation-v2/tree/master/charts/federation-v2

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/helm/charts/issues/8559

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by pmorie** [comment]
Thanks a lot for opening this @gyliu513! Really looking forward to having federation-v2 in the charts repo.

**Comment by desaintmartin** [comment]
I am not sure the licence is needed, as it is the same as /LICENCE.

**Comment by gyliu513** [comment]
@desaintmartin I think it is still needed, as each chart can be used standalone by the end user.

**Comment by pmorie** [comment]
I'm in agreement with @gyliu513 re: license file

**Pull request closed without merging**
