### PR TITLE
[stable/kiam] update service port name

### LINKED ISSUE #8002: [stable/kiam] Update serer.service.name from grpc to grpclb
**Is this a request for help?**:

---

**BUG REPORT**:

**Version of Helm and Kubernetes**:
Helm 2.10.0
Kubernetes 1.10.7

**Which chart**:
stable/kiam

**What happened**:
One of the templates (server-service.yaml) hasn't been updated with the original template https://github.com/uswitch/kiam/blob/master/deploy/server.yaml. The value:

```
  ports:
    - name: grpc
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
```
should be

```
  ports:
    - name: grpclb
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
```
So it causes issues with the DNS discovery:
https://github.com/uswitch/kiam/issues/144

**What you expected to happen**:
server-service port name is equal to grpclb

**How to reproduce it** (as minimally and precisely as possible):
Install latest chart and see the logs of any of the agents, error like:
_"INFO: grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.kiam-server on 100.64.0.10:53: no such host"_
appears

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
update service port name 

#### Which issue this PR fixes
  - fixes https://github.com/helm/charts/issues/8002

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by cpanato** [comment]
@goruha @mattfarina I saw we are using rc1 in the chart version and app version. for this PR what should be the chart version?

thanks

**Comment by goruha** [comment]
@cpanato I guess if this fix is not blocker and critical - let's use `2.0.0-rc-2`

**Comment by cpanato** [comment]
done @goruha

**Comment by cpanato** [comment]
@davidkarlsen can you take a look at this one? thanks

**Pull request merged**
