### PR TITLE
[stable/jenkins] Add existing PVC

### PR DESCRIPTION
**Pull request by flah00**
Add the `Persistence.ExistingVolume` value, for jenkins

### CODE REVIEW

**Comment by flah00** [comment]
@lachie83 @viglesiasce bump

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@flah00 Thanks for the contrib. Just want to do some further testing but this looks good.

**Comment by prydonius** [comment]
thanks @flah00 this lgtm, I improved the templating a little bit -- can you update your other PRs?

**Comment by flah00** [comment]
@prydonius Thanks for the feedback, much cleaner (I'd been struggling to understand when `include` would be used over `template`). I've updated the other PRs.

**Comment by prydonius** [comment]
Rebased to fix conflicts

**Pull request merged**
