### PR TITLE
[stable/sentry] bump dependency postgresql 0.8.1

### PR DESCRIPTION
**Pull request by scottrigby**

### CODE REVIEW

**Review by mgoodness — CHANGES_REQUESTED** [review]
Not sure what happened with this one, but apparently neither the postgresql nor redis dependency version got bumped.

**Comment by scottrigby** [comment]
Re dependency bumping, same discussion as https://github.com/kubernetes/charts/pull/1963#issuecomment-327506712.

**Comment by scottrigby** [comment]
@k8s-bot test this

**Comment by scottrigby** [comment]
Hm, reading [this doc](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#the-testing-and-merge-workflow) I see a `member` would need to add a `@k8s-bot [e2e|unit] test this issue: #<flake issue>` comment. @mgoodness can you do this? This failed test doesn't look related to this PR.

**Review by mgoodness — APPROVED** [review]

**Comment by scottrigby** [comment]
@mgoodness What could be going on here I wonder? Is it just test and retest till it passes? 😂 🤖

**Comment by scottrigby** [comment]
Out of date, stable/sentry postgresql dep version is up to date.

**Pull request closed without merging**
