### PR TITLE
[stable/oauth2-proxy] Support for TLS

### LINKED ISSUE #12820: [stable/oauth2-proxy] No support for TLS (volumes, mounts, port changes, etc)
**Is this a request for help?**:

No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature

**Version of Helm and Kubernetes**:

2.11.0
1.11.5

**Which chart**:

oauth2-proxy

**What happened**:

No support for TLS. The container supports it, but there is no way to mount a TLS secret or change the ports to SSL ports.

**What you expected to happen**:

That the chart supports these things.

**How to reproduce it** (as minimally and precisely as possible):

Try and add a TLS Secret or change the container port.

**Anything else we need to know**:

@Miouge1 
PR is on the way.

### PR DESCRIPTION
**Pull request by michaelajr**
#### What this PR does / why we need it:

@Miouge1 Adds support for TLS.

#### Which issue this PR fixes

fixes #12820 

#### Special notes for your reviewer:

No.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Miouge1** [comment]
Rather than `extraVolume` did you consider another option like `secretName`?

**Comment by michaelajr** [comment]
@Miouge1 Might be cleaner. The user can then just specify the `secretName` and the volume and mount would be implicitly set up. The `README` would then specify that a TLS Secret is expected containing `tls.key` and `tls.crt` files. Let me know if this is what you'd prefer and I can make the change.

**Comment by Miouge1** [comment]
It's a pattern I've seen used for things like `ingress.tls.secretName`, so if you think it could work, I think it would be best to use a similar approach.

**Comment by michaelajr** [comment]
Sounds good. Will get on it shortly. Thanks.

**Comment by Miouge1** [comment]
@michaelajr you will also need to rebase this on latest master to resolve the merge conflicts

**Pull request closed without merging**
