### PR TITLE
Fixed table layout in minio readme

### PR DESCRIPTION
**Pull request by leonkunert**
@Minio
@Acaleph

**What this PR does / why we need it**: Fixes table layout for minio readme which is broken in the last line

### CODE REVIEW

**Comment by rjkernick** [comment]
Please sign the CLA and bump the version in Chart.yaml

**Comment by leonkunert** [comment]
CLA signed and version bumped.

**Comment by rjkernick** [comment]
CircleCI is still failing on the version check. Message: 
Error please increment the new chart version to be greater than the existing version of 1.1.1

**Comment by rjkernick** [comment]
Please rebase master and resolve merge conflicts

**Comment by unguiculus** [comment]
Closing this. Comparing against master, it doesn't really fix anything.

**Pull request closed without merging**
