### PR TITLE
[stable/artifactory] Service annotations

### PR DESCRIPTION
**Pull request by stanislavb**
Allow full customization of service annotations for all three services
in artifactory chart: artifactory, postgres and nginx. Purpose of the
change is to allow end user to provide configuration for other
kubernetes components to act on.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @jainishshah17 @eldada

**Review by eldada — APPROVED** [review]
Looks good.

**Review by jainishshah17 — APPROVED** [review]
/approve

**Comment by stanislavb** [comment]
Perhaps it was not my place to assign the pull request to a specific person, as suggested by the bot? It was not my intention to delay the approval. It looks to me that this change now meets the requirement specified in CONTRIBUTING.md: "Any change requires at least one LGTM. No pull requests can be merged until at least one maintainer signs off with an LGTM."

**Comment by prydonius** [comment]
> Perhaps it was not my place to assign the pull request to a specific person, as suggested by the bot? It was not my intention to delay the approval. It looks to me that this change now meets the requirement specified in CONTRIBUTING.md: "Any change requires at least one LGTM. No pull requests can be merged until at least one maintainer signs off with an LGTM."

No worries @stanislavb, sorry for the delayed review.

/lgtm

**Pull request merged**
