### PR TITLE
[stable/prometheus-pushgateway]: Fix release namespace

### PR DESCRIPTION
**Pull request by maxbrunet**
#### Is this a new chart

No

#### What this PR does / why we need it:

Add release namespace to resources

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

cc @gianrubio @cstaud

### CODE REVIEW

**Comment by davidkarlsen** [comment]
There is no need for this - helm will add the namespace by itself.

**Comment by maxbrunet** [comment]
@davidkarlsen it does not when you deploy with `helm template`

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to `stable` prometheus charts for a short time until prometheus-community/community#28 (comment) is resolved. If you want to help with that effort, to test etc, that would be great!

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts).

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
