### PR TITLE
[stable/metallb] Add support for prometheus-operator

### PR DESCRIPTION
**Pull request by mkhpalm**
Signed-off-by: Mike Palmer <mpalmer@terascope.io>

#### What this PR does / why we need it:

This PR adds support for Prometheus Operator

* https://github.com/coreos/prometheus-operator
* https://github.com/helm/charts/tree/master/stable/prometheus-operator

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by sebastien-prudhomme** [comment]
My comments:
- i would not mix different kind of resource in the same file (service and servicemonitor)
- i would add a way to enable or disable the prometheus rules. Maybe some users just want the metrics and not the alerts
- not sure about that but i would use separate servicemonitors for controller and speaker components

**Comment by mkhpalm** [comment]
Thanks for the feedback!

 > i would not mix different kind of resource in the same file (service and servicemonitor)

I split service from servicemonitor

> i would add a way to enable or disable the prometheus rules. Maybe some users just want the metrics and not the alerts

I added an option to enable or disable (default) the rules

> not sure about that but i would use separate servicemonitors for controller and speaker components

I split the servicemonitor into separate controller and speaker components

**Comment by zzzuzik** [comment]
please review/merge it. thx

**Comment by zzzuzik** [comment]
bump

**Pull request merged**
