### PR TITLE
[incubator/jaeger] Adding agent sidecar for query and OWNERS file, update jaeger to 1.12

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
* Adding OWNERS file as this is needed
* Adding an optional agent sidecar for query as per https://github.com/jaegertracing/jaeger-kubernetes/issues/112#issuecomment-458042080
* Update to Jaeger 1.12

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by naseemkullah** [comment]
bump

**Comment by maorfr** [comment]
/assign
/ok-to-test

please add yourselves to the Chart.yaml file as well :)

**Comment by maorfr** [comment]
/lgtm

thanks and good luck!

**Comment by naseemkullah** [comment]
Thanks @maorfr !

**Pull request merged**
