### PR TITLE
stable/nextcloud: create db-secrets also for external DB

### PR DESCRIPTION
**Pull request by lentzi90**
Signed-off-by: Lennart Jern <lennart.jern@gmail.com>

#### What this PR does / why we need it:
The db-secret was only created for mariadb, not for external databases even though the deployment expects this. This PR allows the deployment to work also with external databases.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by billimek** [comment]
The test failed with `https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/14384/pull-charts-e2e/1135394406707236864/`.  I think because of the `{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled }}` line in `templates/db-secret.yaml`.

It appears that the else condition is going to trigger every time and expects that value to be populated.

Perhaps change it t:

```yaml
{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  db-password: {{ default "" .Values.mariadb.db.password | b64enc | quote }}
  db-username: {{ default "" .Values.mariadb.db.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalDatabase.enabled }}
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  db-username: {{ default "" .Values.externalDatabase.user | b64enc | quote }}
  {{- end }}
{{- end }}
```

**Comment by billimek** [comment]
@lentzi90, there is another nearly identical PR for the same solve, #14407 - do you have a preference which one we go with?

FYI @imran1008 ^^^

**Comment by lentzi90** [comment]
It doesn't matter to me which one is merged. :)

**Comment by billimek** [comment]
@lentzi90 can you please rebase with master to pick up the new changes and properly bump the Chart.yml version again?  We should be good-to-go with merging this once we can do those things.

**Comment by lentzi90** [comment]
@billimek done! :)

**Pull request merged**
