### PR TITLE
[stable/dex] Add liveness and readiness probes.

### PR DESCRIPTION
**Pull request by lhotrifork**
### What this PR does / why we need it:
Liveness and readiness were missing.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vi7** [comment]
Hi @lhotrifork , thank you for those changes! Please consider the following comments:
- as it's mentioned [here](https://github.com/dexidp/dex/blob/master/Documentation/kubernetes.md#deploy-the-dex-server) when Dex is doing TLS termination on its own using self-signed certs health checks won't work properly, this should be mentioned in the chart README alongside with liveness and readiness params
- new chart params are marked as documented in the README in the PR description but they are not, please document them assuming the comment above

**Comment by lhotrifork** [comment]
Hi @vi7,

I've updated with your comments - liveness and readiness probes are disabled if `Values.https: true`.
Also updated default values to match kubenetes defaults.

**Pull request merged**
