### PR TITLE
de-capitalize all the variables of tensorflow-inception

### PR DESCRIPTION
**Pull request by cheyang**
**What this PR does / why we need it**:

de-capitalize all the variables, as variables in Charts should not be capitalized.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cheyang** [comment]
@timstoop , as your suggestions. PTAL.

**Comment by timstoop** [comment]
Thanks for this!
/ok-to-test
/lgtm

**Comment by unguiculus** [comment]
Please bump the minor version for this.

**Comment by cheyang** [comment]
> Please bump the minor version for this.

@unguiculus , 
I don't quite understand your meaning.  Can you explain by providing example. Thanks very much.

**Comment by timstoop** [comment]
In Chart.yaml, you bumped the version from 0.2.3 to 0.2.4. That's a bump in patch level. The second number is the minor version. So @unguiculus is requesting you to change the version to 0.3.0 instead.

You may want to look into https://semver.org/ for more info.

**Comment by cheyang** [comment]
@timstoop , thanks. You make my day.

**Comment by cheyang** [comment]
@unguiculus, updated as your suggestions. PTAL.

**Pull request merged**
