### PR TITLE
[stable/prometheus-operator] update dependencies

### PR DESCRIPTION
**Pull request by kvonbredow**
Signed-off-by: Kyle von Bredow <kylevonbredow@gmail.com>

#### What this PR does / why we need it:

Updating the dependencies to incorporate the change to prometheus-node-exporter which allows the user to specify `affinity` and `nodeSelector` objects.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by paskal** [comment]
@kvonbredow, have you tested these changes? Disregarding only minor version change in grafana they introduced some breaking changes. From what I see they should not break this chart, however it should be tested before going live for everyone.

**Comment by kvonbredow** [comment]
I tested the changes in my own cluster, and the changes themselves should only be additive (it added optional objects to the helm values).  After taking a look, it seems someone simply got in before me and the chart version was hitting a merge conflict.  I've caught my branch up with a merge and the tests are passing.

**Comment by kvonbredow** [comment]
@jessesuen done!

**Review by paskal — APPROVED** [review]

**Comment by paskal** [comment]
@davidkarlsen, could you please merge this one?

**Pull request merged**
