### PR TITLE
[incubator/zookeeper] Remove redundant }

### PR DESCRIPTION
**Pull request by vflong**
#### What this PR does / why we need it:
helm install with service.annotations parameter failed

```bash
$ helm install --namespace xxx --name xxx \
--set persistence.storageClass="udisk-ssd" \
--set persistence.size="50Gi" \
--set service.type="LoadBalancer" \
--set service.annotations."service\.beta\.kubernetes\.io\/ucloud-load-balancer-type"="inner" \
--set service.annotations."service\.beta\.kubernetes\.io\/ucloud-load-balancer-vserver-protocol"="tcp" \
incubator/zookeeper

Error: release xxx failed: Service "xxx" is invalid: metadata.labels: Invalid value: "Tiller}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Deepak-Routray** [comment]
Can this PR be merged? Latest chart is broken still.

**Comment by davidkarlsen** [comment]
Obsolete - fixed in 6ba43ecda1095e88cde890c46f919a8e34a707bc

**Pull request closed without merging**
