### PR TITLE
[stable/spinnaker] use spinnaker service settings to set service type

### PR DESCRIPTION
**Pull request by paulczar**
Instead of using a helm hook to patch the services, we can use service
settings to tell spinnaker to set the service type.

This sets up a service-settings configmap and puts the existing
service-settings bits into that and has a switch for setting two things
needed for ingress, type to NodePort and also the `useExecHealthcheck`
to false to ensure GCP ingress works.

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@paulczar can you, please,  rebase?

**Comment by paulczar** [comment]
@cpanato

**Review by cpanato — APPROVED** [review]

**Pull request merged**
