### PR TITLE
[stable/selenium] Fix Jetty max thread templating

### PR DESCRIPTION
**Pull request by bendemaree**
This fixes the value that is rendered when trying to specify `hub.gridJettyMaxThreads`.

As requested in the contributor guidelines: summoning @flah00 and @diemol. 😄

### CODE REVIEW

**Comment by flah00** [comment]
LGTM

**Comment by davidkarlsen** [comment]
@bendemaree Can you also please bump the Chart.yaml version?

**Comment by bendemaree** [comment]
@davidkarlsen done; sorry for the delay.

**Pull request merged**
