### PR TITLE
[stable/percona-xtradb-cluster] Adding pod annotations

### LINKED ISSUE #7936: [stable/percona-xtradb-cluster] Add annotation support for statefulset or annotate pods when metrics are enabled
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Which chart**:

stable/percona-xtradb-cluster

**What happened**:

There is no possibility to annotate percona stateful set

**What you expected to happen**:

I'd like to put annotation on it.
For example: 
```
prometheus.io/scrape=true
prometheus.io/port=9104
```

### PR DESCRIPTION
**Pull request by maver1ck**
What this PR does / why we need it:
Adding ability to specify pod annotations

Which issue this PR fixes
fixes #7936

Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

  DCO signed
  Chart Version bumped
  Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
@cpanato 
Thanks for review. How to make this merged ?

**Comment by cpanato** [comment]
ping @paulczar

**Pull request merged**
