### PR TITLE
[stable/prometheus-operator] Upgrade to 0.25.0

### LINKED ISSUE #8722: [stable/prometheus-operator] Update to 0.25.0
**Which chart**: stable/prometheus-operator
**What happened**: using release 0.24.0
**What you expected to happen**: using release 0.25.0

This release (https://github.com/coreos/prometheus-operator/releases/tag/v0.25.0) introduces two new features
* [FEATURE] Allow passing additional alert relabel configs in Prometheus custom resource ( coreos/prometheus-operator#2022)
* [FEATURE] Add ability to mount custom ConfigMaps into Alertmanager and Prometheus ( coreos/prometheus-operator#2028)

_I plan on addressing this, opening issue to track_

### PR DESCRIPTION
**Pull request by vsliouniaev**
#### What this PR does / why we need it:
@gianrubio, this release (https://github.com/coreos/prometheus-operator/releases/tag/v0.25.0) introduces two new features
* [FEATURE] Allow passing additional alert relabel configs in Prometheus custom resource (coreos/prometheus-operator#2022)
* [FEATURE] Add ability to mount custom ConfigMaps into Alertmanager and Prometheus (coreos/prometheus-operator#2028)

#### Which issue this PR fixes
  - fixes #8722

#### Special notes for your reviewer:
- Skip deploying CRDs on upgrade - the resources already exist and helm is not able to modify them using the CRD hook. The operator manages the upgrade by itself and it's possible to use the extra features and perform the upgrade all in one step. In the future it may be necessary to use a job to perform the CRD upgrade at the `crd-install` point.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Installing on a clean cluster works
- [x] Upgrading an existing release works and the fact that the operator upgrades the CRDs after release does not prevent me from specifying `configMaps` or `alertRelabelConfigs` as part of the release

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@maver1ck There are a _lot_ of issues with `crd-install` right now in helm. This is the safest option as it actually allows someone to upgrade the chart from operator <0.25 to 0.25. Without this change the CRD installation process would simply fail as they are deployed as unmanaged resources.

I know about the issue with helm-diff, but this is the less bad than having a chart that simply does not work.

Please see these issues:
https://github.com/helm/charts/issues/9941
https://github.com/helm/charts/issues/9241
https://github.com/helm/helm/issues/4925

**Comment by maver1ck** [comment]
I'm thinking if previous solution based on separated chart for CRD wasn't better.

**Pull request merged**
