### PR TITLE
Update GitLab-CE image to release 9.0.0

### PR DESCRIPTION
**Pull request by kwent**
Related to https://about.gitlab.com/2017/03/22/gitlab-9-0-released/

### CODE REVIEW

**Comment by kwent** [comment]
I signed it!

**Comment by kwent** [comment]
I'm not sure what happened here. How do i debug this ?

**Comment by kwent** [comment]
@k8s-bot e2e test this

**Comment by kwent** [comment]
@seanknox @mgoodness Could you relaunch tests please ?

**Comment by mgoodness** [comment]
@k8s-bot e2e test this

**Comment by kwent** [comment]
Perfect. I also deployed in my local minikube with no issues 👍 🎉

**Comment by seanknox** [comment]
Thanks @kwent!

**Comment by andrioid** [comment]
A quick warning to those who plan to "helm upgrade". It inits a new database, so be sure to backup first.

**Comment by kwent** [comment]
I think an off cluster Postgres is always recommended for production anyway.

**Pull request merged**
