### PR TITLE
[incubator/azuremonitor-containers] Fix typos in readme & notes

### PR DESCRIPTION
**Pull request by vishiy**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rendhalver** [comment]
Please put [ incubator/azuremonitor-containers] in the title so it's easy to tell at a glance what the PR is for.

**Comment by vishiy** [comment]
@rendhalver - sure, will do that way for the future PRs.

**Pull request merged**
