### PR TITLE
Upgrade Traefik to the v1.1.2 bug fix release

### PR DESCRIPTION
**Pull request by krancour**

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
Looks like @itamarst submitted a change for this in #333 too. @krancour I'll leave it up to you to decide whether you want to close this or #333, although in the interest of updating it quickly it might be better to go with this since @itamarst needs to sign the CLA.

**Comment by krancour** [comment]
@prydonius damn... didn't notice #333. Sorry for the dup.

It might be faster to get this one through, as it seems you requested a change in #333 that you haven't gotten yet.

It's up to you how to proceed. I'm not offended if mine is the one that gets closed.

**Comment by prydonius** [comment]
@krancour no worries at all! Tried this out and it LGTM, so makes sense to go with this PR.

**Comment by krancour** [comment]
Any reason this can't be merged yet?

**Pull request merged**
