### PR TITLE
[stable/metabase] interpolate liveness and readiness probes

### PR DESCRIPTION
**Pull request by kl4w**
Signed-off-by: Kash Law <ka.shing.law@gmail.com>

#### What this PR does / why we need it:
Allows modification of the values of the liveness and readiness probe. In our case, we'd like to modify the liveness probe.

#### Special notes for your reviewer:
Change is a no-op compared to the original template. I've also got another PR for this chart that has bumped up the same patch version (https://github.com/helm/charts/pull/20456). Let me know how you'd like me to handle this and I'll make the necessary change.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pmint93** [comment]
@kl4w Can you please bump the chart version again, due to current conflict

**Comment by kl4w** [comment]
@pmint93 updated chart version and rebased

**Review by pmint93 — APPROVED** [review]

**Comment by pmint93** [comment]
/approve
/lgtm

Thanks for your contribution ;)

**Pull request merged**
