### PR TITLE
[stable/prometheus-operator] Made service port configurable

### PR DESCRIPTION
**Pull request by anandsinghkunwar**
* Prometheus/Alertmanager service port configurable
* Indentation fixes of comments in the `values.yaml` file

No

#### What this PR does / why we need it:
This makes prometheus and alertmanager service port configurable in the chart. These were previously hardcoded in the chart. 

#### Special notes for your reviewer:
The change has been made in a backward compatible and hence only the minor version has been bumped. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
/ok-to-test
The tests will keep failing until one of these can be done:

- #18271
- #18310

**Comment by anandsinghkunwar** [comment]
@vslivsliouniaev when can those be merged?

**Comment by anandsinghkunwar** [comment]
@vsliouniaev Can you review/merge?

**Comment by vsliouniaev** [comment]
There are several other places in the chart with 9090 and 9093 hardcoded, which this PR would break

**Comment by anandsinghkunwar** [comment]
Gotcha. Will send out the update in a day.

**Comment by vsliouniaev** [comment]
I see there are a few places where this can already be specified in the chart. I would be a better experience to put this in one place, but this cannot be done without bumping the chart version to another major release because it would break compatibility. So I suggest just making the hardcoded ports be set by the new property you are introducing

**Comment by zanhsieh** [comment]
@anandsinghkunwar 
Would you mind to resolve conflicting file please?
stable/prometheus-operator/Chart.yaml

**Comment by anandsinghkunwar** [comment]
This is a WIP for now, I messed up my commit history. Will cleanup and try again.

**Comment by anandsinghkunwar** [comment]
@zanhsieh @vsliouniaev Done, can you approve?

**Comment by vsliouniaev** [comment]
Still more hardcoded values exist
```bash
$ egrep -re '909(0|3)' stable/prometheus-operator | grep -v values.yaml | grep -v README.md | grep -v cmd.sh
stable/prometheus-operator/templates/alertmanager/ingress.yaml:{{- $servicePort := 9093 -}}
stable/prometheus-operator/templates/alertmanager/service.yaml:      targetPort: 9093
stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml:      url: http://prometheus-{{ template "prometheus-operator.fullname" $ }}-prometheus-{{ . }}.prometheus-operated:9090/{{ trimPrefix "/" $.Values.prometheus.prometheusSpec.routePrefix }}
stable/prometheus-operator/templates/prometheus/ingress.yaml:{{- $servicePort := 9090 -}}
stable/prometheus-operator/templates/prometheus/ingressperreplica.yaml:{{- $servicePort := 9090 -}}
```

**Comment by anandsinghkunwar** [comment]
Hi @vsliouniaev, I looked at that, the `prometheus-operated` service is internal to prom operator and its port is probably hardcoded in the operator itself. 
The other 909(0|3) ports are from either the `ingress` resource(which is not part of this change) or are `targetPorts`

**Comment by vsliouniaev** [comment]
Agree with you about the operated prometheus replicas.

When it comes to ingress, and the service resources, merging your change would mean the target prometheus and alertmanager will not be reachable in the cluster when someone uses ingress resources

**Comment by anandsinghkunwar** [comment]
@vsliouniaev I believe you're right. I forgot about the backend service in the ingress resource. Will look at what it points to right now and modify accordingly.

**Comment by vsliouniaev** [comment]
thanks!

**Comment by anandsinghkunwar** [comment]
@vsliouniaev Done.

**Comment by zanhsieh** [comment]
@anandsinghkunwar 
Would you consider to be one of this chart owners? @gianrubio has no interest in maintaining this chart. If you would like to volunteer, see:

https://github.com/helm/charts/issues/13867

If you keen, please submit another PR for OWNERS file change, wait for invitation, and let @vsliouniaev LGTM it.

**Comment by vsliouniaev** [comment]
@zanhsieh I believe the requirement to become an owner is now limited to trusted collaborators of the repository

**Comment by vsliouniaev** [comment]
This isn't possible:
https://github.com/helm/charts/pull/18450#issuecomment-547930367

**Pull request merged**
