### PR TITLE
[Sentry] Disable ingress by default

### PR DESCRIPTION
**Pull request by dlackty**
According to Sentry's parameter table in documentation, it says that ingress is disabled by default but actually it's not.

Let's update `values.yaml` to make it coherent.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @rothgar

**Comment by rothgar** [comment]
I had probably saved it with ingress enabled for my own usage.

I guess the alternative would be to enable ingress by default. It looks like Kubernetes may want to ship an ingress controller by default in the future but for now we can leave ingress disabled by default and just make sure it's documented.

**Comment by unguiculus** [comment]
The readme already specifies `false` as default.

**Pull request merged**
