### PR TITLE
[stable/mysqldump] added option to store backups in directory named like the database

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it:
* added option to store backups in directory named like the database
* added --database option to mysqldump command to have the "CREATE DATABASE IF NOT EXIST" statement in the sql dump

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by axdotl** [comment]
@paulczar Would you agree if we move the mysqldump chart to our repo (https://github.com/kiwigrid/helm-charts)? So that we get changes released faster.

**Comment by monotek** [comment]
@paulczar 
currently we can't provide write access to the repo, but our plan is to have prow bot or some github actions running in the future which enables us to use "/lgtm" there too.

**Comment by monotek** [comment]
@paulczar 
done in: https://github.com/helm/charts/pull/10933

**Pull request merged**
