### PR TITLE
[incubator/buzzfeed-sso] Allow an initial setup without upstreams

### PR DESCRIPTION
**Pull request by anas-aso**
#### What this PR does / why we need it:
For new setup you might need to deploy the chart without defining any upstreams to give other team the auth infrastructure and the freedom to add their services when needed.

#### Special notes for your reviewer:
If you try to deploy the chart without upstreams, the proxy application will fail with the following error : 
```
{"error":"Invalid configuration:\n  error reading upstream configs file: open /sso/upstream_configs.yml: no such file or directory","level":"error","msg":"error validing options","service":"sso-proxy","time":"2019-06-07 13:36:52.671"}
```
this is expected since the configuration file wasn't created by the config map in that case.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by anas-aso** [comment]
@komljen 🙏

**Review by komljen — APPROVED** [review]

**Review by darioblanco — APPROVED** [review]

**Comment by anas-aso** [comment]
@darioblanco one last `/lgtm` and I promise you won't see me for a while 😄

**Comment by anas-aso** [comment]
@komljen could you please have a look ?

**Pull request merged**
