### PR TITLE
gocd: wrong agent resource value ref

### PR DESCRIPTION
**Pull request by balboah**
#### What this PR does / why we need it:

Ability to have separate resource specs on the GoCD server and agent (as originally intended).

#### Special notes for your reviewer:

.Values.agent.resources exist in values and README but is not used in deployment.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

@arvindsv @GaneshSPatil @varshavaradarajan

### CODE REVIEW

**Review by GaneshSPatil — APPROVED** [review]

**Comment by balboah** [comment]
@GaneshSPatil whops, fixed!

**Pull request merged**
