### PR TITLE
[stable/drone]Add drone rpc host

### LINKED ISSUE #12862: [stable/drone]: path selection is wonky
BUG? Arguably so. This ingress logic either needs to be extended with the config to provide a path ourselves, as it now failes for istio:

`if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb"`

**Which chart**
stable/drone

**What happened**:
istio's path mapping does not like `/` and thus blocks `/*`

**What you expected to happen**:
`/hello` to pass

**How to reproduce it** (as minimally and precisely as possible):
follow the [ingress-certmanager example from istio](https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/) and replace the path `/hello` for `/`. Then try with `/*`

**Anything else we need to know**:
I think we can't assume what the engine prefers, and would like to have the option to provide a path for the ingress:

```
ingress:
  hosts:
    - bla.bla.bla
  path: /*
```

### PR DESCRIPTION
**Pull request by zakkg3**
What this PR does / why we need it:

- [x] added envvar DRONE_RPC_HOST pointing to the internal service
- [x] added istio to defaults for /* path, added path fallback for ingress

this changes was review by @christian-roggia  with /lgtm but the pr was not finished. (https://github.com/helm/charts/pull/12864#issuecomment-491539747)
this changes its also being tested by me on EKS cluster OK.

Which issue this PR fixes
fixes https://github.com/helm/charts/issues/12862

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zakkg3** [comment]
@maofr @christian-roggia @cpanato Plase review or /lgtm as this changes was already reviewed here https://github.com/helm/charts/pull/12864#issuecomment-491539747

**Comment by zakkg3** [comment]
Christian, Könntest du bitte :D
/assign @christian-roggia

**Comment by Morriz** [comment]
yay!

**Pull request merged**
