### PR TITLE
Add node selector to dask helm chart

### PR DESCRIPTION
**Pull request by stevededalus**
@danielfrg 

Addresses #1899 for the dask-distributed charts, adding a nodeSelector option to the configs.

Not sure if this is the right place to be sending a PR, would love some input or pointers.

### CODE REVIEW

**Comment by stevededalus** [comment]
@lachie83 , is this the right repo to send PRs to or is there a dask repo I should be using?

**Comment by mrocklin** [comment]
@stevededalus see also https://github.com/kubernetes/charts/pull/2914

**Comment by mrocklin** [comment]
Note that #2914 proposes to deprecate this chart

**Comment by stevededalus** [comment]
Ah @mrocklin , should I abandon this PR in favor of the `/dask` chart or will there be period before it's deprecated?

**Comment by mrocklin** [comment]
I would like to see the `/dask` chart be merged quickly, but that PR has been live for a few months now, so expecting it to merge quickly might be unwise.  

That being said, the current stable/dask-distributed chart seems somewhat broken to me.  I'm not sure I would recommend using it.

**Comment by unguiculus** [comment]
I'd expect #2914 to be merged soon. I'd suggest we close this and you create another PR against the new chart once it's merged.

**Comment by mrocklin** [comment]
@stevededalus #2914 was merged.  Do you have any interest in redirecting the changes in this PR against that chart?

**Comment by stevededalus** [comment]
Yup, I'll abandon this PR and reopen one against that chart later this weekend, thanks for the reminder

**Pull request closed without merging**
