### PR TITLE
[stable/prometheus-operator] Sync prometheus operator dashboard and rules

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Signed-off-by: Matteo Gazzetta <matteo_gazzetta@hotmail.it>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by tiagom62** [comment]
@vsliouniaev @bismarck @gianrubio can one of you take a 👀?

**Comment by ElfoLiNk** [comment]
@vsliouniaev ?

**Comment by vsliouniaev** [comment]
`PrometheusRemoteWriteDesiredShards` has a different annotation to what you have here. Looks like there's another pull request open with the same issue here: #21248

**Pull request closed without merging**
