### PR TITLE
[incubator/solr] Bug/fix solr requirements

### LINKED ISSUE #19823: [incubator/solr] Support for Kubernetes 1.16.2
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
Kubernetes:  1.16.2

### PR DESCRIPTION
**Pull request by eyenx**
#### What this PR does / why we need it:
Deployment of solr doesn't work anymore because of an old dependency of `incubator/zookeeper`
#### Which issue this PR fixes

  - fixes #19823 

#### Special notes for your reviewer:

Updates the dependency of `incubator/zookeeper` to chart version `2.1.3`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lwj5** [comment]
@eyenx Hey could you bump solr version up to 8.4 in both chart.yaml and values.yaml as 7.7.2 doesn't fully support zookeeper 3.5.5.  If above is okay bump chart version to 1.4.0.

**Comment by eyenx** [comment]
Word. Was just testing around and see the status of zk isn't really being fetched correctly.

**Comment by sete391** [comment]
> Word. Was just testing around and see the status of zk isn't really being fetched correctly.

Remember bump chart version to 1.4.0 because @lwj5 request!

**Comment by eyenx** [comment]
I'll do asap

**Comment by eyenx** [comment]
Sorry guys, I'm relatively new doing PRs for helm/charts 

How long does it usually take for an issue to be approved/LGTM?

**Comment by lwj5** [comment]
@eyenx erm could you bump version to 1.4.0 instead of 1.3.5 currently. need a major increment as the dependencies are different

I tried to contact @unguiculus on slack he's unresponsive.
Can you assign davidkarlsen or maorfr or both. They have approved the last few solr PRs.

**Comment by eyenx** [comment]
Will do.

**Pull request merged**
