### PR TITLE
[stable/logstash] Add elasticsearch and rabbitmq credentials

### PR DESCRIPTION
**Pull request by endrec**
#### What this PR does / why we need it:
Previously there was no way to support credentials to connect an input/output plugin. This change provides an easy way to push Elasticsearch and RabbitMQ credentials to the container environment.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

Signed-off-by: Endre Czirbesz <endre@czirbesz.hu>

### CODE REVIEW

**Comment by rendhalver** [comment]
What does adding the rabbitmq credentials do for us?

**Comment by endrec** [comment]
Adding rabbitmq credentials gives us the opportunity to easily connect to a secure rabbitmq queue, and read events from there. Rabbitmq is one of the built-in input/output plugins, just like elasticsearch.

**Comment by rendhalver** [comment]
Input/output plugins for what? Elasticsearch or Kube?

**Comment by endrec** [comment]
None of the above. 
I have to point out that we are talking about changes in the `logstash` chart, that might give you some clue...


They are `logstash` input/output plugins.

**Comment by rendhalver** [comment]
Sorry it's been a busy week.
Ok that makes sense.

**Pull request closed without merging**
