### PR TITLE
fix(stable/rabbitmq-ha): Enabling TLS for ingress resulted in YAML parse error (#4835)

### LINKED ISSUE #4835: [stable/rabbitmq-ha] YAML parse error with .Values.ingress.tls = true
**Is this a request for help?**: **NO**

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.10", GitCommit:"044cd262c40234014f01b40ed7b9d09adbafe9b1", GitTreeState:"clean", BuildDate:"2018-03-19T17:44:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: **rabbitmq-ha**

**What happened**:

 .Values.ingress.tls = true and got reported the following error:
```
Error: UPGRADE FAILED: YAML parse error on rabbitmq-ha/charts/rabbitmq-ha/templates/ingress.yaml: error converting YAML to JSON: yaml: line 27: did not find expected '-' indicator
```

**What you expected to happen**:

Enables TLS without a parse error.

**How to reproduce it** (as minimally and precisely as possible):

Set `.Values.ingress.tls = true`

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by estahn**
**What this PR does / why we need it**: So TLS doesn't break the chart.

**Which issue this PR fixes**: fixes #4835

**Special notes for your reviewer**:
The ingress still states `Most likely this will be just one host, but in the event more hosts are needed, this is an array` which is untrue and will break the ingress.

### CODE REVIEW

**Comment by estahn** [comment]
/assign @viglesiasce 

This was tested on our Kubernetes cluster and is working.

**Comment by viglesiasce** [comment]
ping @etiennetremel 

What do you think of this change?

/ok-to-test

**Review by etiennetremel — APPROVED** [review]

**Comment by etiennetremel** [comment]
Sorry for the delay @estahn, looks good thanks!

**Comment by estahn** [comment]
Any updates on this? @etiennetremel @viglesiasce

**Comment by etiennetremel** [comment]
@estahn, only Kubernetes Charts members can merge to master, will need to wait a bit

**Pull request merged**
