### PR TITLE
[stable/metrics-server] Update chart accordly to metrics server repo

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus I don't want to bother but I want to close this topic.

**Comment by olemarkus** [comment]
Not sure what is up with this one, but it adds almost 2k commits. My guess is that some merge went wrong somewhere. Perhaps rebase this on top of master and push again?

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus I tried to rebase but I messed up. Create a new one. This is cleaned.
https://github.com/helm/charts/pull/16654

**Pull request closed without merging**
