### PR TITLE
[stable/kibana] Added option to add Sidecar containers

### PR DESCRIPTION
**Pull request by Towmeykaw**
**What this PR does / why we need it**:
It adds the option to specify sidecar containers to the kibana pod. This enables adding a openid-connect  proxy.

### CODE REVIEW

**Comment by compleatang** [comment]
Hi @Towmeykaw two points. 

1. WRT to the code itself. Can you add an example for folks getting started as to how they would use the sidecar pattern? This could live either in comments in the values.yaml (where I generally prefer it when dealing with new charts) or in the README itself. Folks that are new to charts will have a much easier time understanding how to implement because there are some nuances when running strings through `tpl`.

2. I'm trying to understand the benefit of implementing proxies as sidecars vis a vis gating ingress with a proxy from another chart/deployment. My assumption is that because Kibana does not have an embedded authentication system that you need / want to be able to gate at the pod level to ensure that anyone accessing the pod itself is properly authenticated (maybe this is an incorrect assumption). If that assumption is correct then a bit more work would need to be done to change the service and ingress to use the proxy / authentication port rather than to connect to the Kibana port directly. In general I'm not totally convinced by this pattern, but perhaps I'm missing something. Do you have examples of similar patterns leveraged by other charts?

**Comment by Towmeykaw** [comment]
Hi @compleatang !
As for the code I could add an example in values.yaml no problem.  

The problem i would like to solve is I have a Keycloak chart handling authentication and I want Kibana to have authentication. I looked into the keycloak-proxy chart but it felt excessive to have a chart for something as small as a proxy. But I might be missing something. I took the idea from this blogpost, its for prometheus but same idea. https://medium.com/@lukas.eichler/protecting-prometheus-with-oauth2-oidc-86d1c3f132b2

**Comment by Towmeykaw** [comment]
You are right, I totally missed that. If you feel that it doesn't make
sense for this chart I might just fork it and make my own?

Den tors 23 aug. 2018 17:22Casey Kuhlman <notifications@github.com> skrev:

**Comment by compleatang** [comment]
OK. AFAICT it looks good.

/ok-to-test

**Comment by Towmeykaw** [comment]
@compleatang I fixed the documentation and added an example in values.yaml

**Comment by compleatang** [comment]
great. 

/assign @unguiculus 

(BTW, am I doing this wrongly, shouldn't my approve signal to the bot trigger the merge process?)

**Comment by Towmeykaw** [comment]
@compleatang  I think its /lgtm that starts the merge

**Pull request merged**
