### PR TITLE
[incubator/mysqlha]Add aisuko to OWNERS

### PR DESCRIPTION
**Pull request by Aisuko**
#### What this PR does / why we need it:

I'd like to become mysqlha helm chart maintainer, I have been added `mysql-exporter` to the chart like #13028, and I'm going to add multiple services on mysql #13632
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - related #13869

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
can we get @jpoon and @jonhoare to take a look at this?

**Comment by Aisuko** [comment]
> can we get @jpoon and @jonhoare to take a look at this?

That's should be better. But, I do not know how to send a request to these peoples. Is there have any other idea?

**Comment by jpoon** [comment]
LGTM

**Comment by maorfr** [comment]
@jpoon would you like to be added to the OWNERS file as well?

**Comment by jpoon** [comment]
Oh snap, brain fart -- I don't work at Microsoft anymore. If you could also update my email on this change that would be most appreciated @Aisuko:

~jason.poon@microsoft.com~ helmchart@jasonpoon.ca

**Comment by Aisuko** [comment]
> Oh snap, brain fart -- I don't work at Microsoft anymore. If you could also update my email on this change that would be most appreciated @Aisuko:
> 
> ~[jason.poon@microsoft.com](mailto:jason.poon@microsoft.com)~ [helmchart-mysql@jasonpoon.ca](mailto:helmchart-mysql@jasonpoon.ca)

Why not?  I have been updated your email  😄

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

welcome and good luck!

**Comment by Aisuko** [comment]
Thanks a lot, I will do my best.

**Pull request merged**
