### PR TITLE
[stable/chaoskube] Refactor Chaoskube

### PR DESCRIPTION
**Pull request by alexvicegrab**
Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

**What this PR does / why we need it**:
Refactor Chaoskube to enable _helpers.tpl, affinities, tolerations, and flexible resource selection.

**Special notes for your reviewer**:
N/A

### CODE REVIEW

**Comment by alexvicegrab** [comment]
@linki would you be able to review?

**Comment by linki** [comment]
@alexvicegrab I'm sorry for the delay! I'll have a look.

**Review by linki — APPROVED** [review]
lgtm, thanks @alexvicegrab

**Comment by alexvicegrab** [comment]
Thank you @linki, delighted to contribute to the very useful chaoskube :)

**Pull request merged**
