### PR TITLE
[stable/traefik] Allow configuration of defaultEntryPoints

### LINKED ISSUE #4099: [stable/traefik] Allow configuration of defaultEntryPoints
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

**Which chart**:
`stable/traefik`

**What happened**:

**What you expected to happen**:

When using Traefik as the ingress to route traffic we need to be able to manage WebSockets as well to backend services, my understanding (and this could be off) is that for this to be the case the `defaultEntryPoint` needs to include `ws, wss` in the `traefik.toml` file (Reference: https://github.com/containous/traefik/issues/1327).

This could either be done as an extension of the current `if...else` block, simply adding `ws` or `wss` where required, but it would be more extensible if this was configurable by the end-user, with defaults matching the current provided template.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by amnk**
The idea is simple: instead of having several ifs, we maintain a list of
needed entry points. So I've replaced all calls of `.Values.ssl.enabled`
to checking if `https` is in the list.

Closes: #4099

**What this PR does / why we need it**: to have more flexible way of defining `defaultEntryPoints` for Traefik.

**Which issue this PR fixes**: fixes #4099

**Special notes for your reviewer**:

### CODE REVIEW

**Review by krancour — CHANGES_REQUESTED** [review]
This is a breaking change since it eliminates `ssl.enabled`, which existing users are very likely dependent on.

Corresponding documentation updates are also absent from this PR.

**Comment by amnk** [comment]
@kragniz I've updated chart version to `2.0.0`, and made changes in README.md. Would appreciate feedback on this :)

**Comment by kragniz** [comment]
I think you mean @krancour

**Comment by amnk** [comment]
@kragniz Yeah, sorry for disturbing :(

**Comment by amnk** [comment]
@krancour, what do you think? Can we get this merged, or this is too much of a change?

**Comment by krancour** [comment]
> Can we get this merged, or this is too much of a change?

@amnk, I apologize for not being clear. It is "too much" in that it is a "breaking change." i.e. Someone who upgrades would need to know about this change and account for it or else they're going to be surprised that things don't work the way they used to. The convention is that breaking changes are only undertaken in conjunction with major releases, i.e. incrementing the x in x.y.z and that's not generally undertaken lightly. If an when a major release happens, there needs to be a coordinated effort to pay down all technical debt and lump as many necessary breaking changes together as possible.

If you have a way of doing this _without_ affecting backwards compatibility, it can be more readily considered.

**Pull request closed without merging**
