### PR TITLE
[stable/prometheus-operator] sync prometheus rules from coreos and etcd upstream

### LINKED ISSUE #8749: [stable/prometheus-operator] Alert rules are created for components even if scrapes are disabled
*Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
*Helm*: 2.10.0
*Kubernetes*: 1.10.6

**Which chart**:
stable/prometheus

**What happened**:
If scraping of a particular Kubernetes components (e.g. API server) is disabled via Helm values, corresponding alert rules are still configured in Prometheus leading to alerts that are constantly firing.

**What you expected to happen**:
If scraping configurations are disabled then alert rules that would rely on those metrics should also be disabled.

**How to reproduce it** (as minimally and precisely as possible):
- Deploy the prometheus operator chart with the below values set:
  ```
  kubeControllerManager:
    enabled: false
  ```
- The below alert rule is still configured in the  `PrometheusRule` resource and will immediately enter an alerting state:
  ```
    - alert: KubeControllerManagerDown
      annotations:
        message: KubeControllerManager has disappeared from Prometheus target discovery.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
      expr: |
        absent(up{job="kube-controller-manager"} == 1)
      for: 15m
      labels:
        severity: critical
  ```

### PR DESCRIPTION
**Pull request by paskal**
#### What this PR does / why we need it:
This PR:
- sync existing rules and dashboards from etcd and coreos repos using script from #10488

#### Which issue this PR fixes
  - fixes #8749
  - close #10008

#### Special notes for your reviewer:
I'm using this configuration in production for two months, expected behavior after upgrade: a few new alerts appear (because of the sync) and a few false positive are removed (due to enabled conditional enable like `{{- if and .Values.defaultRules.create .Values.nodeExporter.enabled }}`).
Reviewer might run `stable/prometheus-operator/hacks/*.py` himself, expected result: either nothing changes, or new changes from coreos repo will be introduced to files.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by paskal** [comment]
@gianrubio could you please merge this before we got into another race condition on versions?

**Comment by faheem-cliqz** [comment]
Any luck getting this merged soonish? @paskal

**Comment by paskal** [comment]
Sadly it's not up to me, I can't do anything but keeping it in "ready-to-merge" state.

**Pull request merged**
