### PR TITLE
[stable/grafana]  Fix README.md layout of table broken.

### LINKED ISSUE #16826: [stable/grafana] Layout of table in README.md is broken.
**Describe the bug**

Layout of table in README.md is broken like the screen capture below.
helm_charts_stable_grafana

**Version of Helm and Kubernetes**:

**Which chart**:

stable/grafana

**What happened**:

Like the screen capture above.

**What you expected to happen**:

Correctly format the table.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by zanhsieh**
#### Which issue this PR fixes

  - fixes #16826 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Eeemil** [comment]
Shouldn't this PR be named `[stable/grafana]`? :)

**Comment by zanhsieh** [comment]
@Eeemil @maorfr 
Could you approve this?

**Comment by zanhsieh** [comment]
@Eeemil 
Could you lgtm this?

**Comment by Eeemil** [comment]
Sorry, I tried :(

**Pull request merged**
