### PR TITLE
[stable/redis] Fix for compatibility issues in apiVersions for statefulset

### PR DESCRIPTION
**Pull request by msschl**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Hi, thanks for the PR, I am not sure about this change. Did you find any issue installing the chart?

I am asking because according to the [deprecation note](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), the "new" API format `apps/v1` is available since v1.9, so users should be able to use the new format without issues using k8s >=1.9; in the same way, the [prerequisites present in the README](https://github.com/helm/charts/tree/master/stable/redis#prerequisites) are setting the 
k8s 1.12 as the minimum guaranteed version.

Also, the logic in the `_helpers.tpl` is not rendered when installing the chart via `helm template` + `kubectl ...`, so it is not a valid solution for all users.

**Comment by msschl** [comment]
No, I didn‘t had any issues. This PR can be closed.

**Comment by carrodher** [comment]
Ok, let's wait until the "stale bot" closes the issue. Thanks anyway for your contribution! 👏

**Pull request closed without merging**
