### PR TITLE
[stable/node-problem-detector] remove flag--name which not working

### PR DESCRIPTION
**Pull request by blackwith**
#### Is this a new chart
No

#### What this PR does / why we need it:
Fix installation chart instruction because if we do 
```
helm install --name node-problem-detector stable/node-problem-detector
```

we will get the error :
```
Error: unknown flag: --name
```
#### maintainers :
@max-rocket-internet 
@Random-Liu
@andyxning 
@wangzhen127

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [X]  Chart Version bumped

### CODE REVIEW

**Review by max-rocket-internet — APPROVED** [review]

**Comment by max-rocket-internet** [comment]
@blackwith you need to bump the chart version

**Comment by blackwith** [comment]
> @blackwith you need to bump the chart version

What do you mean ? How can I do that ?

**Comment by max-rocket-internet** [comment]
In your branch, you need to increase the minor `version` in `Chart.yaml` otherwise the checks won't pass 🙂

**Comment by blackwith** [comment]
@max-rocket-internet ok thanks for the explanation, the version has been bumped. 
Need an `/ok-to-test` now :smiley:

**Comment by max-rocket-internet** [comment]
I can't see the bump. There should be 2 files changed now 😅

**Comment by blackwith** [comment]
> I can't see the bump. There should be 2 files changed now sweat_smile

So sorry for this waste of time :sweat_smile: , it should be fixed now.

**Comment by max-rocket-internet** [comment]
Now you have a conflict...

**Comment by blackwith** [comment]
> Now you have a conflict...

solved

**Comment by max-rocket-internet** [comment]
Thanks @blackwith 🙂

**Pull request merged**
