### PR TITLE
[stable/pachyderm] Bumped chart to 0.1.5

### PR DESCRIPTION
**Pull request by jonandernovella**
This PR includes a fix in order for jobs to be scheduled despite data is pushed beforehand.

### CODE REVIEW

**Comment by mattfarina** [comment]
@jonandernovella Can you help me understand how switching from a generated service account name to a hard coded one makes jobs possible. Could there have been a permissions issue with the generated service account name?

**Comment by jonandernovella** [comment]
@mattfarina Logs from the jobs show the following: `pipeline-rc: Error creating: pods "pipeline-x-v1-" is forbidden: service account default/pachyderm was not found, retry after the service account is created`

This service account seems to be hardcoded in jobs' `rc`.

**Comment by mattfarina** [comment]
@jonandernovella Thanks for pointing me at the project. The docs note the name requirement. I would file this as an issue upstream because 1) name predictability (with my security hat on) and 2) possible problems if more than one instance of this chart is installed (or deleted).

**Comment by jonandernovella** [comment]
@mattfarina https://github.com/pachyderm/pachyderm/issues/2647. I opened an issue here.

**Pull request merged**
