### PR TITLE
[stable/kube-state-metrics] use the correct rbac values parameter

### PR DESCRIPTION
**Pull request by tariq1890**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by krichter722** [comment]
@tariq1890 I tested that this PR together with https://github.com/helm/charts/pull/21563 allows to allow volumes of type `projected` (in an upcoming PR) which is very helpful for running kube-state-metrics on GKE 1.16.x.

**Comment by tariq1890** [comment]
@krichter722 Thanks for your response. Just to confirm then; it is working as expected, correct?

**Comment by krichter722** [comment]
@tariq1890 I wanted to confirm that your change works well together with my changes in #21563 where you referenced this PR. Afaiu you're correcting the use of a template key in `values.yml` which seems to good idea to me. In case your intention is to fix `pull-charts-e2e` for the PR as well, I couldn't test that yet, but I propose to go ahead and merge this PR, then I'll rebase #21563 as you suggested. I couldn't test the changes of this PR alone, but they look good to me.

Thanks for your work.

**Comment by tariq1890** [comment]
@mrueg would you be able to review?

**Pull request merged**
