### PR TITLE
[stable/verdaccio] Added namespace support to port-forward command

### PR DESCRIPTION
**Pull request by MichielDeMey**
**What this PR does / why we need it**:
Adds support for a non-default namespace for the `port-forward` command.

### CODE REVIEW

**Comment by MichielDeMey** [comment]
@k8s-ci-robot recheck CLA

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by MichielDeMey** [comment]
@unguiculus Bumped to `0.3.2`

**Pull request merged**
