### PR TITLE
[stable/hl-composer] Update owners

### PR DESCRIPTION
**Pull request by nicolapaoli**
#### What this PR does / why we need it:

Update owners for HL-Composer Chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by alexvicegrab — APPROVED** [review]
/lgtm

**Comment by alexvicegrab** [comment]
@nicolapaoli, pre-approving, but @dbandin and @inzamam-iqbal need to be member of the Helm organisation to be added as Owners

**Comment by nicolapaoli** [comment]
Hi @mattfarina please advise here. 
OWNERS file is updated but it looks @dbandin and @inzamam-iqbal need to be part of the Helm organisation.

**Comment by prydonius** [comment]
Just invited @dbandin and @inzamam-iqbal to be collaborators on this repo

**Comment by alexvicegrab** [comment]
Aha, great, @inzamam-iqbal worked, but still waiting for @dbandin. @dbandin, please let me know as soon as you join and I'll re-verify all PRs.

**Comment by alexvicegrab** [comment]
@prydonius, thanks so much for your swift help.

**Comment by dbandin** [comment]
Hi @alexvicegrab, thanks for looking at this. Got the invite accepted.

**Pull request merged**
