### PR TITLE
[stable/airflow] Remove dependency on initContainer for creating conn…

### PR DESCRIPTION
**Pull request by somcsel**
…ections

#### What this PR does / why we need it:

Allows airflow connections to be created irrespective of whether an initContainer is being used.

Moved/copied the blocks that mount the "connections" volume and runs the add-connections.sh script outside of the conditional block that is only included when an init-container is being used.

#### Which issue this PR fixes

Not applicable: refer to discussion on original PR https://github.com/helm/charts/pull/10317#pullrequestreview-204840913

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by somcsel** [comment]
@gsemet @antweiss please take a look

**Comment by antweiss** [comment]
Looks fine to me. This is the way it should've been implemented in the first place. Can't recall why I made it dependent on init-container definition, but there's clearly no reason for that. I'm assuming you've tested this. :)

**Pull request merged**
