### PR TITLE
adds standard labels to magento chart pvc's

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by avra911** [comment]
@sameersbn are you sure you can add labels to `PersistentVolumeClaim`?

I tried the new code and the results is having labels such as `failure-domain.beta.kubernetes.io/region: europe-west1`.

Maybe I am doing something wrong.

**Comment by sameersbn** [comment]
@avra911 addition of the labels should not create any problems. according to https://kubernetes.io/docs/admin/multiple-zones/ those labels do not indicate failure. Are you seeing any issues deploying the chart? If yes, it would be great if you could create an issue and if possible provide instructions to reproduce the issue.

**Comment by avra911** [comment]
@sameersbn, I have no issue deploying the chart, everything works.
The name was ambiguous, but as you said, is normal.

Thank you for feedback!

**Pull request merged**
