### PR TITLE
kube2iam: Support configuring which namespace kube2iam should run under

### PR DESCRIPTION
**Pull request by oyvindio**

### CODE REVIEW

**Comment by mgoodness** [comment]
Configuring the namespace this way is discouraged unless there's a specific use case. Otherwise, it's best to use `helm install --namespace <namespace> stable/kube2iam`.

**Comment by prydonius** [comment]
@oyvindio does the above method work for your usecase?

**Comment by oyvindio** [comment]
Sorry, I totally forgot about responding on this PR. 
Yes it can work. I understand why setting namespace based on a value is discouraged since there is a separate flag for that.

**Comment by viglesiasce** [comment]
Closing.

**Pull request closed without merging**
