### PR TITLE
WIP: [stable/traefik] Fixes helm upgrades for kv providers

### LINKED ISSUE #7172: [stable/traefik] Update KV Configs by running helm upgrade
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

Helm:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
K8s:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/traefik

**What happened**:

When you change values in the values file and run:
`helm upgrade traefik` the values in etcd were not changed.

**What you expected to happen**:

If I run `helm upgrade` and afterwards:
`kubectl run  --rm -it traefik-etcd-test --image=quay.io/coreos/etcd:v3.1.8 --restart=Never --env="ETCDCTL_API=3" -l app=traefik -- etcdctl --endpoints=http://traefik-etcd-cluster-client:2379 get <traefik/dir/key> --prefix
`
I should see the new value.

**How to reproduce it** (as minimally and precisely as possible):

Install Traefik with HA enabled and ETCD as Key/Value Provider

**Anything else we need to know**:

I create a PR for this running the storeconfig job also after upgrades.

### PR DESCRIPTION
**Pull request by alwinmarkcf**
**What this PR does / why we need it**:

This PR enables updating configs with a helm upgrade.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes: #7172

**Special notes for your reviewer**:

I've to do further testing. This may conflict with ACME certs, while overriding or deleting them, which would be very bad

### CODE REVIEW

**Comment by alwinmarkcf** [comment]
Actually I'm not sure if this worked as I just now ruined my Certs for about an hour until I ran in every possible rate limitation because of:
https://github.com/containous/traefik/issues/3754#issuecomment-412627242

And I had to generate certs on a different host, manually adding sections to my legacy acme.json

Therefore also: https://github.com/containous/traefik/issues/3754#issuecomment-412627242 would be very important as it's a must have for running on production as I had to find out on the hard way two times. At least until I know whats the type of the cert object value.

**Comment by paulczar** [comment]
This looks like a change in behavior, so should be more than just a patch bump on the version?

/ok-to-test

**Comment by alwinmarkcf** [comment]
@paulczar don't know. Actually while adding the HA feature broke the helm upgrade process. Thats why I thought it's a bug

**Comment by alwinmarkcf** [comment]
Ok so for 1.6 there must be also fixed some things on traefik side as otherwise certs will be overwritten every time. 1.7 Introduced a new config variable: `traefikConfiguration.GlobalConfiguration.ACME.OverrideCertificates` which I could use here. So I will use this variable together with the importAcme value and the Revision number to check if OverrideCertificates has to be true or false.

I implement that now or at the beginning of the next week and test it locally but it should work.

**Comment by alwinmarkcf** [comment]
@paulczar so I'tried and tested a lot and the most practical way for me is to upgrade the chart to traefik 1.7 as it introduced a new config parameter which I need for this usecase. Now I guess even though its for me still  a bugfix a minor release makes sense.

Problem here is 1.7 is just a RC so don't know if we should hold this PR unless 1.7 is stable.

Guess both is your decision

**Comment by alwinmarkcf** [comment]
Still waiting for 1.7 to became stable. Currently RC 5 is released

**Comment by alwinmarkcf** [comment]
Actually 1.7 is stable now, so this can be merged

**Comment by alwinmarkcf** [comment]
Created a new MR

**Pull request closed without merging**
