### PR TITLE
[stable/prometheus] allow multiple alert files

### PR DESCRIPTION
**Pull request by premkumar-gg**
Signed-off-by: Premkumar Anand <premkumar@giffgaff.co.uk>

#### Is this a new chart
No

#### What this PR does / why we need it:
Allows multiple alert files for Prometheus charts. It is particularly handy when deploying Prometheus in a cluster with a number of different services having a number of alerts. Instead of bloating the values.yaml file, this PR allows adding one or more alert files per service.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by premkumar-gg** [comment]
cc @mgoodness @gianrubio

**Comment by zanhsieh** [comment]
@maorfr @lachie83 
Would you guys help this? @gianrubio has disappeared and lost interest for a long time. Have chat with @mgoodness and he also does not have interest on maintaining this chart either:

--- Kubernetes slack private message ---
Friday, October 18th
zanhsieh 10:08 PM
Hi Michael. Sorry for bothering you again. Would you mind to LGTM this PR please? https://github.com/helm/charts/pull/17979

goodness 10:09 PM
Hi Ming. afraid I haven’t been an active maintainer of the repo for a couple of years now. don’t have merge access

zanhsieh 10:10 PM
But you are still on the list of the owners. https://github.com/helm/charts/blob/master/stable/prometheus/OWNERS
I feel really really sorry for bothering you, but @gianrubio has lost interest in the prometheus helm chart.

**Comment by premkumar-gg** [comment]
Good effort there!

As a side note, I'm happy to be a maintainer for this chart, if that helps.

**Comment by zanhsieh** [comment]
@davidkarlsen 
Would you mind to LGTM this please? Reasons as described above 👆

**Comment by premkumar-gg** [comment]
Any attention to this.. Or have people actively moved on to prometheus-operator chart?

**Comment by maorfr** [comment]
/lgtm

we are indeed looking for new maintainers for this chart!

**Comment by janssk1** [comment]
Isn't a sidecar approach as used by eg grafana dashboards more appropriate ? That allow the service1 alerts to live in the service1 chart, and the alert definitions will come and go whenever service1 gets installed/removed. 

Right now, prometheus scaping is dyanmic (scrape targets are discovered as long as they have the correct annotations), dashboard can be added dynamic (as longs as the configmaps have the correct labels)  but alerts are still pretty static..

**Comment by max-rocket-internet** [comment]
@premkumar-gg

We get this error when upgrading to this version of the chart:

```
  Error: render error in "prometheus/templates/server-configmap.yaml": template: prometheus/templates/server-configmap.yaml:17:43: executing "prometheus/templates/server-configmap.yaml" at <$value.groups>: can't evaluate field groups in type interface {}
  Error: plugin "diff" exited with error
```

Our values worked before:

```
serverFiles:
  alerts:
    groups:
    - name: aws_health
      rules:
      - alert: 'AWS Health Issue'
        expr: 'aws_health_events{xxxxxx} > 0'
        labels:
          severity: 'warning'
```

Are people supposed to change the structure of `serverFiles.alerts` now?

**Comment by max-rocket-internet** [comment]
@premkumar-gg

I think you can solve it by doing this instead of what you have [here](https://github.com/helm/charts/blob/0a1d70d5d4350d2a88a64f1f6638ea612f44c4e9/stable/prometheus/templates/server-configmap.yaml#L17-L24):

```yaml
{{ if eq $key "alerts" }}
{{ if empty $value.groups }}
    groups:
{{- range $ruleKey, $ruleValue := $value }}
    - name: {{ $ruleKey -}}.rules
      rules:
{{ $ruleValue | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{- end }}
{{ else }}
```

Suggestion came from here: https://github.com/roboll/helmfile/issues/643#issuecomment-498519464

But even with this change, all our alerts are removed when we have `serverFiles.alerts.groups` set. If we rename this key to `serverFiles.alerts.service1` like your example, I think it works but it's still showing a huge diff so I don't really want to apply it.

We really want to be able to split our alerts up into different files as currently we have around 2000 lines of YAML there. But it needs to be backwards compatible with current values structure 🙂

**Comment by premkumar-gg** [comment]
I lost track of this PR.. sorry @max-rocket-internet ..

> Are people supposed to change the structure of serverFiles.alerts now?

Simple answer I could think of. No, they don't need to.

Going by what we had in [server-configmap.yaml](https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml), I wasn't expecting any other keys than `alerts` or `prometheus.yml` . With that assumption, the change works fine compatible backwards.

In your case, you have:

```
serverFiles:
    anchore-pass: xxxxxx
    ^^$key              ^^$value
```

...where $value is not yaml, so the change seemed incompatible. Have you added any other template within your chart handle this?

But any ways, you raised a good point about the `and` not operating as intended. I'll raise another PR to fix that.

Meanwhile, if this blocks your case, please use this:

```
{{- if eq $key "alerts" }}
{{- if empty $value.groups }}
    groups:
{{- range $ruleKey, $ruleValue := $value }}
    - name: {{ $ruleKey -}}.rules
      rules:
{{ $ruleValue | toYaml | trimSuffix "\n" | indent 6 }}
{{- end }}
{{ else }}
{{ toYaml $value | indent 4 }}
{{- end }}
{{- end }}
```

**Comment by premkumar-gg** [comment]
> /lgtm
> 
> we are indeed looking for new maintainers for this chart!

Count me in @maorfr

**Comment by premkumar-gg** [comment]
> Isn't a sidecar approach as used by eg grafana dashboards more appropriate ? That allow the service1 alerts to live in the service1 chart, and the alert definitions will come and go whenever service1 gets installed/removed.
> 
> Right now, prometheus scaping is dyanmic (scrape targets are discovered as long as they have the correct annotations), dashboard can be added dynamic (as longs as the configmaps have the correct labels) but alerts are still pretty static..

That will be a nice one to have, yes.

Static alerts are still valid. For example, you may have an alert that alerts whenever **any** of your pods use 90% of the maximum memory. This is not service-specific.

**Comment by max-rocket-internet** [comment]
@premkumar-gg 

> ...where $value is not yaml, so the change seemed incompatible.
> Have you added any other template within your chart handle this?

No. There's no need. This just creates a file in the pod at `/etc/config/anchore-pass` that we use in `scrape_configs`. It can be at a different path but we still need to be able to create files like this using the chart.

**Pull request merged**
