### PR TITLE
[stable/selenium] Fixing typos in readme and templates

### PR DESCRIPTION
**Pull request by wind0r**
#### What this PR does / why we need it:
This PR fixes different Typos inside the selenium chart

#### Special notes for your reviewer:
A variable got renamed is that small version bump okay for that?

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@wind0r can you please rebase?

**Comment by wind0r** [comment]
@cpanato rebased :)

**Pull request merged**
