### PR TITLE
[incubator/zookeeper] Fix passing secrets (#9519)

### LINKED ISSUE #9519: [incubator/zookeeper] passing secrets in values.yaml breaks chart
**Is this a request for help?**:No

---

**Is this a BUG REPORT or FEATURE REQUEST?** BUG
In values.yaml, if you pass in a secret via `values.secrets` it will cause helm to return an error on install or upgrade.  

`
i.e. adding this to myvalues.yaml
secrets:
  - name: zookeeper
    keys:
    - mysecret
    mountPath: /opt/zookeeper/secret
`
^ I have tried everything to quote this :-(

> helm install --name=testit --namespace zktest incubator/zookeeper --values myvalues.yaml

> Error: YAML parse error on zookeeper/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 105: did not find expected key
[myvalues.yaml.txt](https://github.com/helm/charts/files/2612034/myvalues.yaml.txt)

**Version of Helm and Kubernetes**:
`helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
incubator/zookeeper

**What happened**:
When trying to add a secret(s) to values.yaml, I got an error running helm

**What you expected to happen**:
nominal install or upgrade

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:
I think I can fix it, expect a PR

### PR DESCRIPTION
**Pull request by bluebenno**
#### What this PR does / why we need it:
Fix for #9519, passing in secret(s) to values.yaml causes a yaml parse error.  Typo on indentation??

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #9519 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Chart Version bumped

### CODE REVIEW

**Comment by bluebenno** [comment]
@kow3ns @lachie83 ping.  I'm sure you guys are busy at Kubecon, if you have some spare time please could you review this. Thanks, I appreciate your time and chart!

**Comment by bluebenno** [comment]
🙏

**Comment by bluebenno** [comment]
@lachie83 version bumped in Chart.yaml

**Review by lachie83 — APPROVED** [review]

**Pull request merged**
