### PR TITLE
[stable/mongodb-replicaset] Various improvements

### PR DESCRIPTION
**Pull request by unguiculus**
* Add OWNERS file
* Better script formatting and quoting
* Change directory of config file to the location expected
  by the scripts in the Docker image
* Run MongoDB as non-root user
* Move all chart-related `mongod` option to cli args in order to make configuration easier
* Move `on-start.sh` out of install Docker image into configmap in order to not rely on new images to be pushed when changes are made
* Improve MongoDB initialization waiting for replicas to reach the desired state
* Fix issues with read-only configmaps with Kubernetes 1.9.4
* Improve pod disruption budget configuration

### CODE REVIEW

**Comment by unguiculus** [comment]
@foxish Could you push the new install image, please?

**Comment by qcho** [comment]
I'm not sure if it is the best place to point this out, probably out of the scope of the PR. But wouldn't be a good idea to use the `bitnami` image as the `stable/mongodb` chart does?

This would allow to join forces with the `stable/mongodb` owners, be at the last stable mongodb version (today replicaset is at `appversion: 3.4`) with ease.

It supports replication:
https://github.com/bitnami/bitnami-docker-mongodb#setting-up-a-replication

**Comment by unguiculus** [comment]
@qcho Switching to the Bitnami image is definitely out of scope for this PR. It would probably require quite some refactoring. And to be honest, I don't see why we should move away from the official Mongo image.

**Comment by foxish** [comment]
/lgtm
Pushing the image now.

**Comment by foxish** [comment]
```
docker build -t k8s.gcr.io/mongodb-install:0.6 .
Sending build context to Docker daemon 11.78 kB
Step 1 : FROM alpine:3.4
 ---> c7fc7faf8c28
Step 2 : MAINTAINER Anirudh Ramanathan <foxish@google.com>
 ---> Using cache
 ---> 12a8760ffe0d
Step 3 : RUN apk update && apk add bash openssl && wget -qO /peer-finder http://storage.googleapis.com/kubernetes-release/pets/peer-finder
 ---> Running in 84ca977cc024
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
2 errors; 11 distinct packages available
The command '/bin/sh -c apk update && apk add bash openssl && wget -qO /peer-finder http://storage.googleapis.com/kubernetes-release/pets/peer-finder' returned a non-zero code: 2
```

Will try again in a while. Unable to build the image atm.

**Comment by mattfarina** [comment]
@foxish @unguiculus seeing the error:

```
Error: error validating "": error validating data: found invalid field runAsGroup for v1.SecurityContext
```

**Comment by foxish** [comment]
Pushed the new image. This should be good to go.
Thanks @mattfarina for catching that.

/lgtm

**Review by foxish — APPROVED** [review]

**Pull request merged**
