### PR TITLE
Update Minio/mc to latest release and fix an issue with NAS Gateway

### PR DESCRIPTION
**Pull request by nitisht**
#### What this PR does / why we need it:
Update the Minio and mc Docker image

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by nitisht** [comment]
cc @jonandernovella

**Comment by jonandernovella** [comment]
@nitisht LGTM. Good job!

**Comment by davidkarlsen** [comment]
@nitisht can you fix the conflict? TIA

**Comment by nitisht** [comment]
done @davidkarlsen

**Comment by jonandernovella** [comment]
+1 @sameersbn @mgoodness

**Comment by harshavardhana** [comment]
@nitisht we should also bring support for other envs such as etcd etc as well.

**Comment by andrewnet** [comment]
Hi, it seems there is no activity on this issue. Can anyone take a look? The minio helm chart is behind the minio release too far.

**Comment by jonandernovella** [comment]
> Hi, it seems there is no activity on this issue. Can anyone take a look? The minio helm chart is behind the minio release too far.

+1

**Comment by nitisht** [comment]
closing this in favour of #9531

**Pull request closed without merging**
