### PR TITLE
Update docs for charts moved to stable

### PR DESCRIPTION
**Pull request by mikesplain**
A little docs cleanup!

### CODE REVIEW

**Comment by mikesplain** [comment]
CNCF CLA signed

**Comment by lachie83** [comment]
LGTM

**Comment by lachie83** [comment]
Just waiting on e2e tests to be fixed before merging

**Comment by mikesplain** [comment]
Cool thanks @lachie83.  Let me know if you need any other changes!

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Pull request merged**
