### PR TITLE
[stable/prometheus] Update kube-state-metrics to v1.7.2

### PR DESCRIPTION
**Pull request by lruslan**
Signed-off-by: Ruslan Lutsenko <ruslan.lutcenko@gmail.com>

#### What this PR does / why we need it:

Update kube-state-metrics to v1.7.2

Add missing permissions in kube-state-metrics-clusterrole 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

Missing permissions taken from original clusterrole file (revision under release 1.7.2) https://github.com/kubernetes/kube-state-metrics/blob/4c0e83b3407e489eda34c26f7794ec69856ccd76/kubernetes/kube-state-metrics-cluster-role.yaml

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by lruslan** [comment]
@mgoodness @gianrubio is there any chance you can take a look at this PR? Thank you
/assign @gianrubio

**Comment by zanhsieh** [comment]
@lruslan 
Could you signoff DCO again please? Thank you.

**Comment by lruslan** [comment]
@zanhsieh signed DSO, all seem to be clean now. Thanks

**Comment by zanhsieh** [comment]
@mgoodness @gianrubio 
Would you guys approve this PR please?

**Pull request closed without merging**
