### PR TITLE
Kong v0.12.3 support and probes value tweaks

### PR DESCRIPTION
**Pull request by shashiranjan84**

### CODE REVIEW

**Review by pbaezab — COMMENTED** [review]
livenessProbe timeout == readinessProbe timeout? why? Best practices say not equals times, and readiness timeout < liveness timeout. Ok?

**Comment by shashiranjan84** [comment]
@pbaezab thanks, keeping initial probe delay higher for livenessProbe than readinessProbe  makes sense but why timeout needs to be higher too?

**Review by pbaezab — COMMENTED** [review]
InitiaDelaySeconds is fine with 30 or 60; But timeout in liveness is small, I prefered 10 or 15, and timeout in readiness is minor, 5 or 10 respectively, always minor than liveness. When liveness and readyness are equals, k8s can had  bad performance. Read the best practices for liveness and readiness.

**Comment by shashiranjan84** [comment]
How one probe `timeoutSeconds` affects others, I checked the doc https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ and the example used in there not even set explicit `timeoutSeconds`, so basically same default value for both the probes. Mind providing me link to the best practices for liveness and readiness.

Regarding initialDelaySeconds, I am keeping it high(and now different) because I want probe to wait for migrations job to finish.

**Comment by shashiranjan84** [comment]
ping @unguiculus, waiting for your approval, thanks.

**Comment by sameersbn** [comment]
@shashiranjan84 generally you should have the readinessProbes fire more frequently because if the pod is not responding then you want kubernetes to know asap so that it stops routing the traffic to that pod. If your deployment has more than one replica this is improves the resilience to failures.

The liveness probes are generally triggered less frequently, and especially when you have the same test for both probes it does not make sense to have the same frequency for both probes.

edit: i mixed the liveness and readiness probe mentions which ended up making no sense. Now fixed. Sorry about that.

**Comment by shashiranjan84** [comment]
@sameersbn rebased, would you please review or should we wait for @unguiculus to review?

**Comment by sameersbn** [comment]
@shashiranjan84 Actually the readiness probe should be more frequent. I mixed up the probe names in my previous comment (now edited and corrected). I am sorry about this. Also I would bump the liveness probe `periodSeconds` way higher to say `30` but I leave that entirely up to you.

**Comment by shashiranjan84** [comment]
@sameersbn no worries, I did get confuse for a moment as redinessProbe usually controls the traffic, but somehow got convinced. 

I bumped liveness probe periodSeconds to 30. Please review and approve.

**Pull request merged**
