### PR TITLE
Add Jenkinsfile to repo which defines PR testing

### PR DESCRIPTION
**Pull request by viglesiasce**
This Jenkinsfile does the following:
- Checkout PR code
- Install latest helm
- Check for directories that have changed
- Install each of the applications that have changed
  - Run Helm lint
  - Install
  - Uninstall

In the future this needs to:
1) Use a latest link for helm rather than hardcoding a URL
2) Check for successful installation of the helm application
3) Use better logic for figuring out what to test

### CODE REVIEW

**Comment by sgoings** [comment]
How are you planning on hooking up a k8s cluster for the `helm install` to use?

**Comment by viglesiasce** [comment]
Jenkins agents are running inside of a Kubernetes cluster and helm uses the service account for authentication.

**Comment by sgoings** [comment]
Neat. Love the foundation you're laying here.

**Comment by viglesiasce** [comment]
Thanks! For more on the Jenkins+K8s methodology:
https://cloud.google.com/solutions/jenkins-on-container-engine

**Pull request merged**
