### PR TITLE
[stable/jenkins]: use wrong type for master.runAsUser comparison (#21358)

### LINKED ISSUE #21358: [stable/jenkins] Using master.fsGroup and master.runAsUser gives "at <eq .Values.master.runAsUser 0.0>: error calling eq: incompatible types for comparison"
**Describe the bug**
When using master.fsGroup and master.runAsUser with a value of 1000 for the helm release an error is returned.:

`Error: template: jenkins/templates/jenkins-master-deployment.yaml:69:12: executing "jenkins/templates/jenkins-master-deployment.yaml" at <eq .Values.master.runAsUser 0.0>: error calling eq: incompatible types for comparison`

**Version of Helm and Kubernetes**:
helm v3.1.1
Kubernetes = latest EKS version

**Which chart**:
stable/jenkins

**What happened**:
I tried to update an ingress hostname, but got presented with the error on runAsUser

**What you expected to happen**:
The run to succeed

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by chrisLeeTW**
#### Is this a new chart
No

#### What this PR does / why we need it:
fix issues, which make this variable can be used correctly in helm v3.

#### Which issue this PR fixes
`fixes #21358` (https://github.com/helm/charts/issues/21358)

#### Special notes for your reviewer:
No

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by chrisLeeTW** [comment]
@zanhsieh Is there still anything that I need to complete ? please let me know, thanks.

**Comment by torstenwalter** [comment]
@chrisLeeTW Can you merge it with master. Change looks good!

**Comment by zanhsieh** [comment]
@chrisLeeTW 
The chart version still need to bump to latest.

**Comment by chrisLeeTW** [comment]
@torstenwalter @zanhsieh sorry for delay reply. I've bump the chart version to the latest for 1.14.1.

**Comment by torstenwalter** [comment]
@chrisLeeTW Once more? Can you add an entry to CHANGELOG.md?

**Comment by chrisLeeTW** [comment]
@torstenwalter sorry for delay reply. entry added in CHANGELOG.md

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Comment by torstenwalter** [comment]
@chrisLeeTW Thank you!

**Pull request merged**
