### PR TITLE
[stable/presto] Uses official image from prestosql.io

### PR DESCRIPTION
**Pull request by shawnzhu**
Signed-off-by: Ke Zhu <kzhu@us.ibm.com>

No.

#### What this PR does / why we need it:

This is for pickup the official container image of prestosql community to avoid using out-of-date release and vulnerable container images.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - supports #19831 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by shawnzhu** [comment]
@maorfr @lachie83 May I have your review/comments?

**Comment by chickenPopcorn** [comment]
Hey @shawnzhu, thanks for the PR. It works great. But when I tried to bump it further to 330 but it fails. The coordinator complains that 
```
ERROR	Announcer-0	io.airlift.discovery.client.Announcer	Cannot connect to discovery server for announce: Announcement failed for http://presto:8080
```
The service didn't have an endpoint (`None`) and thus can't resolve the domain name `presto`. Not sure how an image update could cause this. Care to bump the version further to the latest?

**Comment by shawnzhu** [comment]
@chickenPopcorn I hope https://github.com/helm/charts/pull/20404/commits/19f97b80b7ea51b7b685889c9c43d7d7dd8fd926 (pushed under this PR) fixes your problem on the coordinator can not discover itself.

> The service didn't have an endpoint (None) and thus can't resolve the domain name presto.

This is not a problem for the k8s cluster I use that a pod can discover itself via a service endpoint. However, I can reproduce this problem by using Minikube. (`http://presto:8080` is a valid service endpoint (assuming you use `presto` as helm release name) after deployment that all worker pods can use).

After https://github.com/helm/charts/pull/20404/commits/19f97b80b7ea51b7b685889c9c43d7d7dd8fd926 a coordinator pod will use `localhost` (just like  pod liveness/readyness check) instead of a service endpoint to discover itself.

**Pull request merged**
