### PR TITLE
[stable/sentry] Don't set sentry pods resources by default

### PR DESCRIPTION
**Pull request by minhdanh**
#### Is this a new chart
No

#### What this PR does / why we need it:
I think sentry chart shouldn't set the resources values of the worker, web and cron pods by default.
This makes it very hard to override these values because of the way helm merge the values.
For example when I need to unset the values of cpu limit, I can't do that by simply using this:
```
resources:
    limits:
      # cpu: 500m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 300Mi
```
because the default value from the chart will be used.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by minhdanh** [comment]
@okgolove Done. Please check.

**Comment by okgolove** [comment]
@minhdanh I meant major version - 3.0.0.

**Comment by minhdanh** [comment]
@okgolove Ah, yeah I just did it. Please check.

**Comment by okgolove** [comment]
You should sign your new commits :)

**Comment by minhdanh** [comment]
Yeah, I committed on my mobile and I realized that the new commit not signed yet. Just did that seconds after your comment :D

**Comment by minhdanh** [comment]
Hi @okgolove 
Can this be merged now?

**Review by okgolove — APPROVED** [review]

**Pull request merged**
