### PR TITLE
[stable/kong] misc improvements

### PR DESCRIPTION
**Pull request by hbagdi**
- Unify controller and proxy deployment together to simplify the
- Deployment is available under apps/v1 apiVersion since Kubernetes 1.9
  (almost 2 years ago).
  Deployments under extensions/v1beta1 apiVersion are no longer served by
  default from kubernetes 1.16 onwards.
  deployment and debugging
- Fix bug in readiness probe of the controller
- Fix bug in configuring readiness/liveness/resources for controller
- reduce initialprobedelays to 10seconds; the init-container makes sure
  that the db connectivity is correctly established

Signed-off-by: Harry Bagdi <harrybagdi@gmail.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by rainest** [comment]
@hbagdi would you be able to add the (non-version bump change) from https://github.com/rainest/charts/commit/99604af663208ac6e60358666375e2074f4039a9 to this PR, or would it be easier to wait til after and create a 20.1?

**Comment by hbagdi** [comment]
@rainest Done

**Comment by hbagdi** [comment]
@shashiranjan84 @rainest Please review. Thanks!

**Review by shashiranjan84 — APPROVED** [review]
/lgtm

**Pull request merged**
