### PR TITLE
[stable/minio] Document azuregatway.replicas, fix template conditional logic that ot…

### PR DESCRIPTION
**Pull request by jgdef-tulip**
…herwise fails for 'azuregateway.enabled: true', bump chart version

Signed-off-by: John de Freitas <jgdef@tulip.co>

@nitisht 
@wlan0

#### What this PR does / why we need it:
The conditional logic to require a volume was broken in that on line 85 of `templates/deployment.yaml` the if statement considered whether any of the gateway options were enabled, but the very similar check on line 165 (for the spec volume section) was different, causing an error if `azuregateway.enabled=true` (or likely any other gateway type) was set as a variable.

While here, also document the missing `azuregateway.replicas` chart variable in `README.md`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I didn't open an issue for this, though I can.
To reproduce the issue, have a `myvalues.yaml` file such as:
```
azuregateway:
  enabled: true
```

Then from the `stable/minio` directory run `helm install -f myvalues.yaml .`.
This results in the error:
```
Error: release azure-minio-gateway failed: Deployment.apps "azure-minio-gateway" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "export"
```
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks for the PR @jgdef-tulip , please resolve the conflicts. We should take this in

**Comment by jgdef-tulip** [comment]
Resolved conflicts.

**Comment by jgdef-tulip** [comment]
Had to update chart version since original PR; needs sign-off again.

@nitisht
@wlan0

**Comment by wlan0** [comment]
Thanks for the PR @jgdef-tulip. LGTM

**Pull request merged**
