### PR TITLE
etcd-operator - Add owners

### PR DESCRIPTION
**Pull request by lachie83**

### CODE REVIEW

**Comment by mattfarina** [comment]
@chancez For owners files to work you need to be a member of the Kubernetes organization. The [processes is documented on the community repo](https://github.com/kubernetes/community/blob/master/community-membership.md). You already have a couple commits here, @lachie83 is proposing you for an owner so I assume he'd be a sponsor, and I would be a second one.

Would you apply for k8s membership?

**Comment by chancez** [comment]
Sure, I wouldn't mind. Let me go through that.

**Comment by chancez** [comment]
Okay, I accepted the organization invite. I should be a member now.

**Pull request merged**
