### PR TITLE
[incubator/nifi] Add incubator chart for Apache NiFi 1.8.0

### PR DESCRIPTION
**Pull request by joaocc**
#### What this PR does / why we need it:
Adds incubator chart for Apache NiFi 1.8.0.

#### Special notes for your reviewer:
This is a fork of an existing helm chart, updated to work with Apache NiFi 1.8.0, with external zookeeper, single storage disk, and some bug fixes

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by joaocc** [comment]
Test says lint failed but gives no indication of the error cause. 
```
Happy Helming!
"incubator" has been added to your repositories
Error: no repository definition for http://storage.googleapis.com/kubernetes-charts-incubator. Please add the missing repos via 'helm repo add'
Error linting charts
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
Exited with code 1
```

Local lint also doesn't point out any errors (just a warning due to lack of icon).
Any ideas?
Thx

**Comment by tlvince** [comment]
@joaocc thanks for this chart. I've been able to get this running with a single node NiFi cluster with the following values:

```yaml
  storageClass: null
  replicaCount: 1
  properties:
    clusterSecure: false
    needClientAuth: null
    httpPort: 8080
    httpsPort: null
    siteToSite:
      secure: false
  ca:
    enabled: false
  sts:
    hostPort: null
  loadBalancer:
    enabled: true
    httpPort: 8080
    httpsPort: null
  zookeeper:
    servers: 1
    antiAffinity: "soft"
```

I did have some trouble with volume claims, hence `storageClass: null`. I also had to tweak the readiness probe. Do these changes make sense? https://github.com/joaocc/charts/compare/nifi-1.8.0...tlvince:nifi-1.8.0

**Comment by joaocc** [comment]
It seems that incorporating the fixes from @tlvince created some problems with DCO.
As I don't have much experience with DCO, can anyone tell me what may  be  the best  way to proceed?
Right now, my solution would be to close this PR, create a branch with all my changes except those  from @tlvince and commit. Changes from @tlvince could then be added as a separate PR, with separate DCO.
Thx

**Comment by tlvince** [comment]
@joaocc happy for you to squash/rebase my tweaks

**Comment by joaocc** [comment]
/remove-lifecycle stale
Anyone can help clarify what lint is complaining about?
Thx

**Comment by maorfr** [comment]
hey @joaocc 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Pull request closed without merging**
