### PR TITLE
[stable/socat-tunneller] Document new chart location

### PR DESCRIPTION
**Pull request by plumdog**
#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by mattfarina — CHANGES_REQUESTED** [review]
Unfortunately, we cannot accept this PR. The automation to package this up and handle the chart itself has all been removed. This change to the source would never be seen in any package.

**Comment by plumdog** [comment]
@mattfarina ok, understood.

Is there a canonical way to announce the new location of a chart that was in stable?

**Comment by mattfarina** [comment]
You can list it on Artifact Hub. Deprecated packages aren't going to show there by default but the new location will. This is available via `helm search hub` and through the Artifact Hub website.

**Comment by plumdog** [comment]
To close the loop: now findable here https://artifacthub.io/packages/helm/isotoma/socat-tunneller

@mattfarina many thanks.

**Pull request closed without merging**
