### PR TITLE
[stable/sysdig] fix setting env

### LINKED ISSUE #21105: [stable/sysdig] cannot set env unless ebpf enabled
**Describe the bug**

env vars cannot be set unless ebpf.enabled = true

```
          {{- if .Values.ebpf.enabled }}
          env:
            - name: SYSDIG_BPF_PROBE
              value:
          {{- end }}
          {{- if .Values.proxy.httpProxy }}
            - name: http_proxy
              value: {{ .Values.proxy.httpProxy }}
          {{- end }}
```

**Which chart**:
stable/sysdig

**What happened**:

Values:

```
proxy:
  httpProxy: http://192.168.1.1:8080
```

`Error: YAML parse error on sysdig/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 40: did not find expected key`

**What you expected to happen**:
Proper install

**How to reproduce it** (as minimally and precisely as possible):
Set proxy.httpProxy or daemonset.env with ebpf.enabled false

### PR DESCRIPTION
**Pull request by bcg62**
#### Is this a new chart
no

#### What this PR does / why we need it:
allows setting env vars without having to use ebpf

#### Which issue this PR fixes
fixes #21105 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bencer** [comment]
@bcg62 lgtm, can you add a changelog entry line to get this merged pls?

**Review by nestorsalceda — CHANGES_REQUESTED** [review]
I miss the CHANGELOG.md entry

But the other things looks great.

Thank  you for the PR!

**Comment by bcg62** [comment]
@bencer @nestorsalceda CHANGELOG.md updated.

Thanks

**Comment by bencer** [comment]
thanks!
/lgtm
/approve

**Pull request merged**
