### PR TITLE
[stable/elasticsearch] Ingress for Elasticsearch client nodes

### PR DESCRIPTION
**Pull request by kamsz**
@simonswine @icereval @rendhalver @desaintmartin

#### What this PR does / why we need it:

Adds ability to expose Elasticsearch client as Ingress.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks for your PR!
Please bump a minor version since it is a new, non-breaking feature.
/assign
/ok-to-test

**Comment by kamsz** [comment]
RTM.

**Comment by desaintmartin** [comment]
Could you change the version to be 1.15.0 instead of .3?
Appart from that, tested and approved. :)

**Pull request merged**
