### PR TITLE
[stable/prometheus-operator] Bump node exporter version

### PR DESCRIPTION
**Pull request by kaarolch**
Signed-off-by: Karol Chrapek <kaarol@it-flow.pl>

#### What this PR does / why we need it:
Update prometheus operator to support newest node_exporter with `mountPropagation` option. 
( #11194 )

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by kaarolch** [comment]
@vsliouniaev need to bump version, because another change was added.

**Comment by vsliouniaev** [comment]
I'm afraid I cannot merge this PR because it needs an ok-to-test on it to be added so that tests can run

**Comment by kaarolch** [comment]
@gianrubio are you able to run test?

**Comment by cpanato** [comment]
@kaarolch can you please update your branch and fix the conflicts? thanks!

**Comment by kaarolch** [comment]
@cpanato Once again version bumped. I hope that now no new commit would been merged in the same time:)

**Comment by vsliouniaev** [comment]
My
/ok-to-test
does nothing, so I hope someone else is able to add this tag to the PR so I can merge it
(After probably another few version bumps along the way)

**Comment by kaarolch** [comment]
@gianrubio could you look on this PR?

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
