### PR TITLE
[stable/weave-cloud] Bump weave cloud

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
Bump weave cloud

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

**Comment by cpanato** [comment]
I need to fix a commit, another went thru by mistake.

Will rebase asap

**Comment by cpanato** [comment]
done

**Pull request merged**
