### PR TITLE
[incubator/elasticsearch] add pull secret option

### PR DESCRIPTION
**Pull request by rpahli**
allow to add pull secret over values

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @icereval 

I think the version comparision should be rework using `semvercompare`. Probably in a separate PR, though.

**Review by icereval — APPROVED** [review]
LGTM

**Comment by rpahli** [comment]
I think the test failing because a there is an error inside the kubernetes cluster:
https://github.com/kubernetes/kubernetes/issues/61178

which kubernetes version are you using inside the Jenkins?

**Comment by rpahli** [comment]
@unguiculus I think there is still a problem with this issue:
https://github.com/kubernetes/kubernetes/issues/61178

how can I find the current kubernetes version which will be used during the tests?

**Comment by unguiculus** [comment]
The current test cluster is 1.9.4.

**Comment by rpahli** [comment]
OK the minimal version is 1.9.5 to get the e2e tests running

**Comment by unguiculus** [comment]
What did 1.9.5 change that's causing the problem here?

**Comment by rpahli** [comment]
This was the issue thas causes the Problem: https://github.com/kubernetes/kubernetes/issues/61178

And the elasticsearch chart uses the subpath feature

**Comment by davidkarlsen** [comment]
@rpahli do you still want to have a go on this - maybe in a new PR or should we just let it go?

**Comment by rpahli** [comment]
@davidkarlsen I'm currently in vocation. I'll update the PR after my vocation.

**Pull request closed without merging**
