### PR TITLE
Fix typo on busybox tag for grafana chart values

### PR DESCRIPTION
**Pull request by sei-jmattson**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by jacobblock** [comment]
Not a designated reviewer but I just happened to start working with this chart in the last hour I can confirm this PR is correct. I've had to overwrite chownDataImage.tag to fix this typo locally; it should be merged. Looking forward to more cleanup of the chart.

**Comment by arthurk** [comment]
Please merge this PR, the current grafana chart is broken

**Pull request merged**
