### PR TITLE
[stable/mssql-linux] make statefulset, support agent, bump version

### PR DESCRIPTION
**Pull request by kim0**
#### What this PR does / why we need it:
* Convert from deployment to Statefulset. This enables an actual version upgrade without pods fighting on the disks!
* Expose SQL server Agent
* Use Microsoft docker registry
* Upgrade image version

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kim0** [comment]
I have tested this to install and upgrade correctly. This was done in 2 cases, with persistence enabled and no predefined claims. And with persistence.enabled=false.

**Comment by kim0** [comment]
/assign @thomasliddledba
Also @lachie83 your review is welcome

**Comment by kim0** [comment]
Hello @thomasliddledba and @lachie83 .. I was hoping to get this merged soonish if you can .. Thanks!

**Comment by thomasliddledba** [comment]
@kim0 - I will review.  Thanks

**Comment by kim0** [comment]
Howdy @thomasliddledba .. Just checking if you had a chance to review this. Thanks!

**Comment by kim0** [comment]
Hello @thomasliddledba .. Let me know if there's anything I can help with to get this done sooner. Thanks

**Comment by thomasliddledba** [comment]
@kim0 - There are many significant changes in this PR.  The changes you're proposing are good changes, however, significant in nature and are more then just a minor version bump.  Can you break this PR up? The SQL Agent change as a minor bump but the k8s object change as a major bump?

**Comment by kim0** [comment]
Hi @thomasliddledba .. unfortunately I was forced to move on to using Azure SQL managed instance and currently don't have time to improve this further. Feel free to cherrypick anything useful from it.

**Pull request closed without merging**
