### PR TITLE
[stable/prometheus] Update Pushgateway image tag

### LINKED ISSUE #5845: [stable/prometheus] Pushgateway ingress path breaks webpage - CSS and JS files not found (404)
**Is this a request for help?**:
Yes and no
If I could have solved my issue any other way please let me know
If not, let me know what you think of my solution

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.8.2
Kubernetes: v1.10.0

**Which chart**:
stable/prometheus

**What happened**:
I was trying to configure the three ingresses for `Server`, `Alertmanager` and `Pushgateway` to have the same `host` and different `path`, but the `Pushgateway` webpage was broken becuase of the `nginx.ingress.kubernetes.io/rewrite-target: /` annotation (the `static` folder containing CSS and JS files was not being found).
I'm using the `stable/nginx-ingress` Chart as ingress controller
My ingresses `hosts` are:
`Server`: prometheus.example.com
`Alertmanager`: prometheus.example.com/alertmanager
`Pushgateway`: prometheus.example.com/pushgateway

**What you expected to happen**:
Get the `pushgateway` ingress to work, or have the ability to specify the "application root" at the application level, which is possible in a newer `pushgateway` image with the parameter `--web.route-prefix`

**How to reproduce it** (as minimally and precisely as possible):
Enable the three ingresses with the above hosts and the following annotations on all three:
```
annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/rewrite-target: /
```

**Anything else we need to know**:
I managed to fix it myself and I'd be happy to open a PR.
I've updated the Values file to use the newer `pushgateway` image `prom/pushgateway:v0.5.1`
I've set `pushgateway` extraArgs:
```
extraArgs:
  web.route-prefix: "pushgateway"
```
I've set the ingress annotations to:
```
annotations:                                      
  kubernetes.io/ingress.class: nginx
```
(NOTE: no `rewrite-target` in this case)
I then had to modify the Chart as the `readinessProbe` in the `pushgateway-deployment.yaml` file was failing for the missing "prefix".
It was checking: `path: /#/status`
It should have been checking: `path: /pushgateway/#/status`
The change I made:
```
readinessProbe:
  httpGet:
  {{- if (index .Values "pushgateway" "extraArgs" "web.route-prefix") }}
    path: /{{ index .Values "pushgateway" "extraArgs" "web.route-prefix" }}/#/status
  {{- else }}
    path: /#/status
  {{- end }}
```

### PR DESCRIPTION
**Pull request by francesco-beccaria**
**What this PR does / why we need it**:
Update the `pushgateway` image tag to allow passing new parameters to the container (e.g. web.route-prefix - see changelog for v0.5.0 [here](https://github.com/prometheus/pushgateway/blob/a8923752ba64d98d98cafc072d508c833f5a4c4b/CHANGELOG.md)) and fix the `readinessProbe` in the `pushgateway-deployment.yaml` file when the above example parameter is used

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes #5845

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by francesco-beccaria** [comment]
/assign @mgoodness
cc: @gianrubio

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by francesco-beccaria** [comment]
Hi @gianrubio,
Thanks for your approval.
Is the failed test because I originally had the same Chart version and had to increase it with an additional commit?
Should I simply /retest it or do I need to change anything else?
Cheers,
F

**Pull request merged**
