### PR TITLE
[stable/redis] Add chart and release labels in pods

### PR DESCRIPTION
**Pull request by javsalgar**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by desaintmartin** [comment]
Hello guys,
Doesn't all of these PRs break k8s/helm upgrades (https://github.com/helm/helm/issues/2494)

**Comment by paultiplady** [comment]
Confirmed, these changes appear to have broken backwards-compatibility with existing deployments, and should therefore require a major version bump, rather than including in a point release.

**Comment by desaintmartin** [comment]
What I mean is that EVERY version (even patch version) upgrade will break, not only this one.

**Comment by paultiplady** [comment]
Is the problem you're raising that there is no satisfactory migration path (even if it requires modifying the deployment outside of helm)?

**Comment by desaintmartin** [comment]
Well, the (temporary) satisfactory path is to revert those changes so that there is no mutable labels and we can actually use those Charts in production.
There should be a consensus about this problem for all charts of this repository, clear understanding of the problem (helm vs k8s and its implications) and it should be written on the guidelines of this repo.

**Comment by paultiplady** [comment]
That seems correct to me. Helm requires its charts use SemVer, under which It's a bug to break upgrades on a patch release.

As long as there's a documented upgrade procedure for a back-incompatible change on major release that would comply with the requirements of SemVer, though depending on how painful that migration is you could also deem it unacceptable, or hide it behind a feature-flag so that existing users don't need to take the upgrade.

**Comment by paultiplady** [comment]
Thanks for the clarification, my understanding of the issue was incomplete. You're right, it sounds like this change simply isn't compatible with the way that k8s metadata is managed. 

Providing a concrete link from the API docs, https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector.

**Pull request merged**
