### PR TITLE
Atlantis ingress bug with port

### PR DESCRIPTION
**Pull request by anasinnyk**
#### What this PR does / why we need it:
Right now we can use ingress only in the case when we set Values.service.port to 4141. It's incorrect. We should not use hardcode here.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by sstarcher — APPROVED** [review]

**Comment by jkodroff** [comment]
I give up.

**Comment by anasinnyk** [comment]
@jkodroff I rebased master branch

**Comment by jkodroff** [comment]
@anasinnyk I have no idea why I can't run any of the bot commands.  I'm in the OWNERS file as a reviewer and maintainer.  I've followed up about it on the k8s Slack.

**Comment by anasinnyk** [comment]
it's really strange. I don't change a service port. Service should be available by 80 port. Maybe try re-run:
/retest

**Pull request merged**
