### PR TITLE
[stable/datadog] add orchestrator-explorer option

### PR DESCRIPTION
**Pull request by hkaj**
#### What this PR does / why we need it:

Add orchestrator-explorer option

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vboulineau** [comment]
@hkaj You miss signoff on commits for your PR to be merged.

**Comment by hkaj** [comment]
e2e tests passed, can i get an lgtm please? 🙏

**Comment by Sayrus** [comment]
Hello @hkaj ,

Where is DD_ORCHESTRATOR_EXPLORER_ENABLED coming from? I don't seem to find anything on [Github](https://github.com/search?q=DD_ORCHESTRATOR_EXPLORER_ENABLED&type=Code) or on the datadog/datadog-agent history.
Currently, it seems that the Orchestrator is always enabled and thus setting `datadog.orchestratorExplorer.enabled` to false only seem to generate an ERROR as the Cluster Agent is now lacking permission to create a datadog-cluster-id configmap.

**Comment by hkaj** [comment]
Hi @Sayrus, thanks for reaching out.

We'll be releasing this feature's documentation soon, apologies for the confusion in the meantime. What do you mean by "the Orchestrator is always enabled" ? The default values.yaml config doesn't enable it and I just checked, it doesn't get enabled.

I see what you mean about the error log though, I just checked and it's my bad! We should check if the feature is enabled before trying to create the config map. However as you can see [here](https://github.com/DataDog/datadog-agent/blob/134b3e2c6b5657a488617aff85476e6c60f5560d/cmd/cluster-agent/app/app.go#L269-L273) we just try and fail cleanly, it doesn't keep running in the background. I'll add a ticket to guard it with a config check in a following release (as we do for the [controller](https://github.com/DataDog/datadog-agent/blob/134b3e2c6b5657a488617aff85476e6c60f5560d/pkg/clusteragent/orchestrator/controller.go#L55-L58)) to avoid writing a confusing error log.

I hope that helps, let me know if you have any other question.

**Comment by Sayrus** [comment]
Indeed, I wrongly assumed that the code was executed because there was an error log and I only checked the main app.go file.
Thanks for the update!

**Pull request merged**
