### PR TITLE
Add ingress, pod annotations and resources to spark-history-server

### PR DESCRIPTION
**Pull request by stijndehaes**
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>

#### What this PR does / why we need it:

It adds pod annotation support to the spark history server.
It also adds an ingress.yaml to the spark history server chart.
Also resources are now supported on the pod.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by yuchaoran2011 — APPROVED** [review]
LGTM. Thanks for contributing.

**Comment by von1994** [comment]
In templates/ingress.yaml, "annotations" should indent 2, not 4. It will align with "labels".

**Comment by stijndehaes** [comment]
@von1994 You are right do you want to make a PR to fix it? Or you rather want me to do it?

**Comment by von1994** [comment]
I'll fire a new issue and send a PR to you.

**Pull request merged**
