### PR TITLE
[stable/prometheus-operator] Update prometheus-node-exporter version

### PR DESCRIPTION
**Pull request by noonedeadpunk**
###  What this PR does / why we need it:

In order to get support of 1.16 node-exporter we need to use
appropriate version of prometheus-node-exporter

Signed-off-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@noonedeadpunk 
Could you resolve the Chart.yaml version conflict please? Thank you.

**Comment by noonedeadpunk** [comment]
@zanhsieh It's impossible to keep track on it... Things move on so fast here

**Comment by zanhsieh** [comment]
@vsliouniaev 
Would you LGTM again this PR ASAP please? Thanks.

**Comment by mnaser** [comment]
just wondering why this hasn't merged when it seems ready

**Comment by noonedeadpunk** [comment]
So it had another versions conflict once PR has been verified, and as it was updated, it needs to be confirmed again I guess.

**Comment by zanhsieh** [comment]
@noonedeadpunk 
Would you mind to bump the chart version to latest please?

**Comment by noonedeadpunk** [comment]
Argh...... Will close this PR and open new one....

**Pull request closed without merging**
