### PR TITLE
incubator/elasticsearch: Add `PodDisruptionBudgets`

### PR DESCRIPTION
**Pull request by NicolasT**
See: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
See: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
See: https://github.com/scality/metal-k8s/issues/157

### CODE REVIEW

**Comment by NicolasT** [comment]
/assign @icereval
CC @simonswine @rendhalver

**Comment by rendhalver** [comment]
Sounds good @NicolasT! Have you tested this out locally to see how it goes?

**Comment by rendhalver** [comment]
We need some testing for that sort of thing.
It looks like you have some errors in the code.
Can you look into those please @NicolasT ?

**Comment by rendhalver** [comment]
Ahh that would explain it. Thanks.
I guess we need that fixed before we can proceed.

**Comment by NicolasT** [comment]
Jay! /CC @rendhalver

**Pull request merged**
