### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by jfelten**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by jasongwartz** [comment]
+1 from me, I asked @jfelten if I could help maintain this chart

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
@jasongwartz You have an invitation to join the repo as a collaborator you will need to accept.

**Comment by jasongwartz** [comment]
@mattfarina thanks!

**Pull request merged**
