### PR TITLE
[stable/chartmuseum] fix configurable parameters name about storage env

### LINKED ISSUE #10456: [stable/chartmuseum] Fix configurable parameters name about amazon storage
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

**Version of Helm and Kubernetes**:

```sh
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Which chart**:

`stable/chartmuseum`

**What happened**:

This charts some amazon storage configurable parameters name incorrect.For example, `env.open.AMAZON_BUCKET` should update `env.open.SOTRAGE_AMAZON_BUCKET`.

**What you expected to happen**:

Update amazon storage configurable parameters name in https://github.com/helm/charts/tree/master/stable/chartmuseum#configuration

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by pytimer**
Signed-off-by: pytimer <lixin20101023@gmail.com>

#### What this PR does / why we need it:

This PR fix configurable parameters name error about storage env in stable/chartmuseum README.md .

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10456

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jdolitsky** [comment]
@pytimer thanks for this, can you also bump the chart version to 1.8.3 ?

**Comment by pytimer** [comment]
@jdolitsky I send new commit that bump chart version to 1.8,3, hope you can review.

**Pull request merged**
