### PR TITLE
Fixing template variable.

### PR DESCRIPTION
**Pull request by jaredbischof**
Without this update I get the following error when deploying the chart:

Error: render error in "consul/templates/consul.yaml": template: consul/templates/consul.yaml:55:21: executing "consul/templates/consul.yaml" at <{{template "fullname...>: template "fullname" not defined

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for the PR. Please fix CircleCI and bump the chart version.

**Comment by mattfarina** [comment]
@jaredbischof any chance you could rebase this off of master? A change made there extended the test timeout period which may help this pass.

**Comment by unguiculus** [comment]
It seems this has become obsolete now.

**Pull request closed without merging**
