### PR TITLE
stable/kong: Add ability to add secrets as a volume in Kong. 

### PR DESCRIPTION
**Pull request by sukrit007**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Add ability to add secrets as a volume in Kong. This is useful to override default ADMIN and Proxy certs and keys. For e.g.

- We can create a tls secret consisting of keys and certificates:
```bash
kubectl create secret tls  kong-ssl-secrets \
  --key=tls-key.pem \
  --cert=tls-cert-bundle.pem
```

- Pass it as parameter to helm chart to override default kong ssl certs:

```yaml
secretVolume: 'kong-ssl-secrets'
env:
  ssl_cert: /etc/secrets/tls.crt
  ssl_cert_key: /etc/secrets/tls.key
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by hbagdi** [comment]
It is possible that users want to mount multiple secrets.
Imagine a case where one wants a different certificate on the proxy path and a different one for the Admin API.

Could you update the PR to mount an array of secrets?

**Comment by sukrit007** [comment]
> It is possible that users want to mount multiple secrets.
> Imagine a case where one wants a different certificate on the proxy path and a different one for the Admin API.
> 
> Could you update the PR to mount an array of secrets?

@hbagdi  Should we just have multiple files as part of 'generic' secret and the user who is installing the chart can give the path to the secret.   For instance,  to do a separate admin cert we can pass following values to the chart:
```
secretVolume: 'kong-ssl-secrets'
env:
  ssl_cert: /etc/secrets/proxy-ssl.crt
  ssl_cert_key: /etc/secrets/proxy-ssl.key
  admin_ssl_cert: /etc/secrets/admin-ssl.crt
  admin_ssl_cert_key: /etc/secrets/admin-ssl.key
```

where kong-ssl-secrets is the name of the generic secret containing proxy-ssl.crt, proxy-ssl.key, admin-ssl.crt and admin-ssl.key for above example.  Thoughts ?

**Comment by hbagdi** [comment]
> @hbagdi Should we just have multiple files as part of 'generic' secret and the user who is installing the chart can give the path to the secret. 

That is one way to go about doing it.
Other users might create a `tls` secret with a cert-key pair in two secrets and they will want to mount both of those.

And there are other cases as well where users will want to mount things other than certificate as a volume.
Doing this in a future PR will be a breaking change and hence I recommend that we do this in this PR itself.

**Comment by sukrit007** [comment]
> > @hbagdi Should we just have multiple files as part of 'generic' secret and the user who is installing the chart can give the path to the secret.
> 
> That is one way to go about doing it.
> Other users might create a `tls` secret with a cert-key pair in two secrets and they will want to mount both of those.
> 
> And there are other cases as well where users will want to mount things other than certificate as a volume.
> Doing this in a future PR will be a breaking change and hence I recommend that we do this in this PR itself.

@hbagdi   Added support for multiple secret volumes.  Let me know if we are all good with the change.

**Review by hbagdi — APPROVED** [review]
/lgtm

We should add these secrets to the Ingress Controller deployment as well, but that deployment will go away soon (to be combined with the Kong deployment itself).

**Comment by hbagdi** [comment]
This will need a rebase on the latest master.

**Comment by sukrit007** [comment]
@hbagdi rebased my changes and bumped the version.  Needs LGTM since I rebased it.

**Pull request merged**
