### PR TITLE
Fixed invalid empty annotations in redis chart template

### PR DESCRIPTION
**Pull request by Funk66**
Signed-off-by: Guillermo Guirao Aguilar <contact@guillermoguiraoaguilar.com>

#### What this PR does / why we need it:

The redis chart template renders an empty annotations field. This PR ensures that the annotations field is only included if it contains values.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by yurrriq** [comment]
It was my understanding that `with` is supposed to work how it was used before this PR. Which version of Helm were you using such that it produced empty `annotations`?

**Pull request merged**
