### PR TITLE
[stable/influxdb] Additional auth job variables

### PR DESCRIPTION
**Pull request by jrob**
#### What this PR does / why we need it:

This PR adds to variables for configuration of the post install auth job. This is to help in scenarios where the installation is taking longer but will eventually finish if given more time. 

#### Special notes for your reviewer:

Both of the variables default to either the previous value or the kubernetes default value.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jrob** [comment]
@jackzampolin @aisuko @naseemkullah
Please review. Thank you!

**Comment by naseemkullah** [comment]
Thanks for the PR @jrob ... We just created a shiny new repo for the influxdata helm charts here: https://github.com/influxdata/helm-charts would you mind making the PR there?

We will get around to putting a deprecation notice here soon enough, sorry about that!

**Comment by jrob** [comment]
PR moved to https://github.com/influxdata/helm-charts/pull/18

**Comment by Aisuko** [comment]
Thanks for your guys' patient. I believe we can merge this for this repo. Because we should keep this repo to May 2020 until it is de-listed from Helm Hub. And on the other hand, we should do the thing that @naseemkullah said. This is would be to make more sense for our contributors.

**Review by Aisuko — APPROVED** [review]
/approve

**Pull request merged**
