### PR TITLE
[stable/prometheus-operator] Re-sync prometheus rules and grafana dashboards

### PR DESCRIPTION
**Pull request by iuriaranda**
#### What this PR does / why we need it

Re-sync the prometheus rules and grafana dashboards.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by iuriaranda** [comment]
Yeah I still have to resolve that linting error somehow. The problem is that they've introduced a special notation in a prometheus rule upstream ([here](https://github.com/helm/charts/pull/21248/files#diff-365cff774eb3b04dae4571b2b53cbcb2R173)), and it's giving issues when translated to a Helm template.

I'm still figuring out how to fix it, we either change that notation upstream in the `kube-prometheus` repo or we figure out how to escape a backtick (`) in a helm command.

**Comment by iuriaranda** [comment]
@vsliouniaev Can you review again please? I've fixed the linting error and merged from master.

**Comment by vsliouniaev** [comment]
The sync scripts produce a different output than what is in your PR

**Comment by iuriaranda** [comment]
@vsliouniaev Have you seen my previous comment? How do you propose to proceed?

**Comment by vsliouniaev** [comment]
> I've seen that this has been manually fixed in previous syncs like this

Sounds like the scripts need to be updated to take care of this

**Comment by iuriaranda** [comment]
> Sounds like the scripts need to be updated to take care of this

@vsliouniaev that would be great. Do you have any ideas on how to do that? I can't think of any regex or method that can perform this kind of transformation.

**Comment by iuriaranda** [comment]
Ok, I think I've found a reasonable solution. See [this commit](https://github.com/helm/charts/pull/21248/commits/f44d2063bc8c9586e4122dd300d68709bcd8bb21).

cc @vsliouniaev

**Comment by iuriaranda** [comment]
I see no relation between my changes and the failed tests.

Are the tests spinning up a fresh new cluster on every run, or they reuse the same cluster between runs? If so, there might be some CRD or webhook configuration leftovers from previous runs.

**Comment by iuriaranda** [comment]
@unguiculus @vsliouniaev can any of you check the test cluster? It looks like a previous test messed up with the CRDs and mutation hooks, and tests are failing.

**Comment by iuriaranda** [comment]
great, thanks @unguiculus 
The tests are now green.

**Comment by iuriaranda** [comment]
@vsliouniaev tests are green now, can you review again please? Thanks.

**Comment by iuriaranda** [comment]
@vsliouniaev thanks for approving. You also need to remove the `hold` label

**Comment by vsliouniaev** [comment]
/unhold
Thanks!

**Comment by iuriaranda** [comment]
Apparently tests are failing again, same problem as the other day. @unguiculus could you check the test cluster again please?
Thanks!

**Comment by davidham** [comment]
There is a change in the current rules-1.14/k8s.rules.yaml from `coreos/kube-prometheus` that will fix a `PrometheusRuleFailures` issue in prometheus-operator, anything I can do to help get this merged?

**Comment by iuriaranda** [comment]
@davidham well, apparently the test environment is not fully cleaned up sometimes, and the tests fail systematically. We can't really proceed until somebody fixes the test cluster.

cc @vsliouniaev @unguiculus 

@davidham the change in the rules you mention, is it already included in this PR? Or should I re-sync the rules again?

**Comment by iuriaranda** [comment]
Finally all tests are green and PR is up to date with the latest changes from master 🎉 

Now it only needs the `lgtm` label again 😛 

@vsliouniaev can you review again please?

**Pull request merged**
