### PR TITLE
[stable/prometheus-operator] Configurable kubeDns ports

### PR DESCRIPTION
**Pull request by richerve**
#### What this PR does / why we need it:

Make the kubeDns exporter ports configurable

#### Special notes for your reviewer:

Apart from making the ports configurable, it fixes an issue with the last commit where if no service selector is configured for kubeDns then rendering the Chart fails as the evaluation of `{{- if .Values.kubeDns.service.selector }}` fails for not having the `service` key defined.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by richerve** [comment]
@vsliouniaev just noticed a bug after my PR was merged, I explained it in this PR description. Also used the opportunity to make the kubeDns ports configurable.

**Comment by richerve** [comment]
thx @bismarck

**Comment by richerve** [comment]
Ready @bismarck

**Comment by vsliouniaev** [comment]
Could you please bump the chart version and we'll re-apply the LGTM label

**Pull request merged**
