### PR TITLE
[stable/datadog] RBAC apiversion specified in values.yaml

### PR DESCRIPTION
**Pull request by cw-sakamoto**
https://github.com/kubernetes/charts/issues/3121

Since ```.Capabilities.KubeVersion``` method requires revision for each kube release, I changed it to specified apiversion in values.yaml.

### CODE REVIEW

**Comment by cw-sakamoto** [comment]
@hkaj Hi, thanks for this charts maintenance.
Would you mind reviewing this PR ?

**Comment by cw-sakamoto** [comment]
@hkaj @irabinovitch @xvello 
Would you mind reviewing this PR ?

**Comment by jewilmeer** [comment]
Would be nice if this could be merged. Whats the hold up? Anything I can do?

**Comment by xvello** [comment]
Hello,

We are concerned this PR breaks deployments for users using RBAC on 1.6 / 1.7 clusters (until they manually set an additional setting), while addressing a non-standard chart usage (deploying via  `kubecrt` instead of `helm`).

My personal feeling is that `kubecrt` should be patched to support substitution of these standard variables, instead of constraining every chart to only use a subset of the helm template variables. @unguiculus could you please provide insights on this?

**Comment by unguiculus** [comment]
@xvello How is this related to `kubecrt`? 

/hold

**Comment by xvello** [comment]
@unguiculus [The linked issue](https://github.com/kubernetes/charts/issues/3121) mentions the deployment does not work because they use `kubecrt` instead of `helm`+`tiller`. Is it a deployment scenario this repo aims to support?

This PR removes the use of the standard and documented [.Capabilities.KubeVersion.Minor object](https://docs.helm.sh/chart_template_guide/#built-in-objects), to replace it with a manually set value. I do not think that is a legit change, unless this repo officially supports this deployment method.

As I'm pretty new to helm charts, I'd love your input on this.

**Comment by JeanMertz** [comment]
I'm one of the authors of [kubecrt](https://github.com/blendle/kubecrt). To shed some light on this:

We created kubecrt because

**Comment by JeanMertz** [comment]
I'm one of the authors of [kubecrt](https://github.com/blendle/kubecrt). To shed some light on this:

We created kubecrt because we wanted a "tillerless experience" of Helm, and have more control over our deployment strategies. We wanted to use official Charts, without having to use the helm deployment strategy, or having to run Tiller on our cluster.

To read more about our reasoning, see: https://github.com/kubernetes/helm/issues/2722#issuecomment-331732811

However, since we wrote it, Helm has integrated a `helm template` command which does some of the things that kubecrt does. I think the way forward for us would be to change kubecrt to use the APIs being used by `helm template`, which (I suppose?) would also mean that it somehow handles these situations where it has no access to Tiller to process the relevant variables.

I am not sure how Helm gets the required values from Tiller, but I believe that Helm passes along the template to Tiller, and it processes the variables and applies the configuration to the cluster. For us, an ideal solution would be if we could _ask_ Tiller to process a template, but not have it do anything, aside from giving us back the processed template. Or, another solution would be for us to be able to ask Tiller what the value of a specific variable should be, so we can process the template locally, and fill in the blanks based on Tiller's response.

But, I don't think that's possible right now, although I haven't been keeping up with Helm's development in the past couple of months, so for now, we'll have to work around that by simply rejecting charts that depend on variables provided by Tiller (or do whatever `helm template` does, I don't know how it handles this situation either).

So as for what @xvello proposed:

> My personal feeling is that `kubecrt` should be patched to support substitution of these standard variables, instead of constraining every chart to only use a subset of the helm template variables.

I agree, if it is possible to handle these substitutions, we'll have to support that. If it's not possible without processing the template server-side, we'll just have to short-circuit parsing charts that depend on these variables.

I obviously don't think Helm (or any official charts) should concern itself with this deployment strategy that we use, but it would be nice if Tiller was (or maybe already is) more flexible to handle these "client-only mode" situations.

**Comment by xvello** [comment]
Thanks @JeanMertz ,

I think it's safe to close this PR then.

**Comment by cw-sakamoto** [comment]
@xvello Thanks for your comment.

>kubecrt should be patched to support substitution of these standard variables, instead of constraining every chart to only use a subset of the helm template variables. 

I agree. So, I will close this PR.

>this repo officially supports this deployment method.

I'm sorry for this point of view was missing.

@jewilmeer I'm sorry I couldn't help. You may resolve your trouble with ```helm template```.

**Pull request closed without merging**
