### PR TITLE
[stable/mariadb] Customizable service type

### PR DESCRIPTION
**Pull request by nouney**
Hi,

This PR allows users to expose the service via the Kubernetes service type (`ClusterIP` (default), `NodePort`, `LoadBalancer`).

### CODE REVIEW

**Comment by nouney** [comment]
I signed it

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by linki** [comment]
Works as expected. Thanks @nouney.

**Pull request merged**
