### PR TITLE
Add Telegraf DaemonSet Chart

### PR DESCRIPTION
**Pull request by jackzampolin**
This begins the process of breaking up the `stable/telegraf` chart into two separate charts, `stable/telegraf-ds` and `stable/telegraf-s`. Having both of these in one chart resulted in a over large `values.yaml` file and complex, easy to mess up configuration. 

https://github.com/kubernetes/charts/pull/708

@jchauncey @jagregory @jeroenvisser101

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@jackzampolin that's cool! I might try it next week on our cluster. Does this also support updating the configmap and restarting the deamons? Since I tried that with the current setup and wasn't able to, that might be good to add (comes in handy when using PVCs, since if you delete the chart, recreate it, the data is gone)

**Comment by jackzampolin** [comment]
@jeroenvisser101 Need to write a `post-upgrade` job that sends a `SIGHUP` to each of the running processes to enable that feature. Its def on my TODO list tho! 😜

**Comment by jeroenvisser101** [comment]
@jackzampolin great! btw, is this still WIP or is there a reason for the service not being there?

**Comment by jackzampolin** [comment]
@jeroenvisser101 No need for the service on the daemonset. I'll have the service on the `telegraf-s` chart I'm pushing up later.

**Comment by jeroenvisser101** [comment]
@jackzampolin Ah, that's cool! Looking forward to seeing it 👍

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
I think it might be a good idea to rename this to the more verbose `telegraf-daemonset`, just so it's more clear. Likewise, `telegraf-s` should be renamed to `telegraf-standalone`.

**Comment by jackzampolin** [comment]
@prydonius Renamed!

**Comment by jackzampolin** [comment]
Tests failing because default deployment creates no objects. This is intentional.

**Comment by jackzampolin** [comment]
Bump?

**Comment by viglesiasce** [comment]
Hey @jackzampolin sorry for the delay.

What are your plans for deprecating the old chart? Is there a plan to have a TICK chart that deploys the whole stack?

**Comment by jackzampolin** [comment]
@viglesiasce I can deprecate it in either this PR or #822. I still need to write the full stack chart that does the whole install, but I'm having enough trouble keeping these updated and haven't pulled the time to do it. Have some work coming down the pipe and some version updates. Lets sync on this.

**Comment by viglesiasce** [comment]
This chart fails to install when no values are provided:

```
$  helm install stable/telegraf-daemonset/
Error: release looping-seahorse failed: no objects visited
```

**Review by viglesiasce — CHANGES_REQUESTED** [review]
Fails to install with default values. Please make this fail gracefully by responding to users what they need to do in order to install successfully.

**Comment by unguiculus** [comment]
Marking this as stale. Please update PR within one week.

**Comment by jackzampolin** [comment]
@unguiculus You can close this PR

**Pull request closed without merging**
