### PR TITLE
[stable/postgresql] Add support for extra init containers

### PR DESCRIPTION
**Pull request by rsotnychenko**
Signed-off-by: Rostyslav Sotnychenko <me@sota.sh>

#### What this PR does / why we need it:
There are cases when one needs to execute some code that requires additional binaries before database initialization.
`extraInitContainers` is a (de-facto) standard for Helm charts and it was missing for the PostgreSQL chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rsotnychenko** [comment]
ping @prydonius @sameersbn @javsalgar @desaintmartin @miguelaeh

**Comment by carrodher** [comment]
Changes LGTM, please, can you resolve the conflicts?

**Comment by rsotnychenko** [comment]
@carrodher thanks, I've resolved the conflicts

**Comment by rsotnychenko** [comment]
/unhold

Got a false-negative on CI, everything is okay with the changes and the PR can be safely merged.

**Pull request merged**
