### PR TITLE
[stable/minio] fix accidental removal of a liveness probe

### LINKED ISSUE #10667: [stable/minio] lastest release fails in distributed mode cause the liveness probe was removed
**Is this a BUG REPORT** (choose one):

**Version of Helm and Kubernetes**:
whatever

**Which chart**:
stable/minio

**What happened**:
the liveness probe does not work anymore

**What you expected to happen**:
should work

**How to reproduce it** (as minimally and precisely as possible):
helm install  --name minio2  --set mode=distributed stable/minio

**Anything else we need to know**:
this commit removed the path of the liveness probe
https://github.com/helm/charts/commit/777ee084e6ddd75542d3c6236112d49874e79d19

I'll propose a PR.

### PR DESCRIPTION
**Pull request by sgandon**
#### What this PR does / why we need it:
add back the liveness proble http path

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10667  

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by nitisht** [comment]
@sgandon can you fix the DCO issue

**Comment by sgandon** [comment]
@nitisht is that ok now ?

**Comment by nitisht** [comment]
@sgandon yes, thanks

**Pull request merged**
