### PR TITLE
[stable/nats] Added service of metrics for nats able to target it from prometheus

### PR DESCRIPTION
**Pull request by Hakob**
Signed off by hakoaraqelyan@gmail.com

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Hakob 
Is it possible to break down this PR to each chart? It's hard to get all charts OWNERS agreement  on your change and nail down with specific version of each chart.

**Comment by Hakob** [comment]
> @Hakob
> Is it possible to break down this PR to each chart? It's hard to get all charts OWNERS agreement on your change and nail down with specific version of each chart.

@zanhsieh 
I have opened this PR only for contributing stable/nats chart. The other changes which have made by others, need to break down by them, not by me. Please inform them to separate their changes from my PR. TY

**Comment by carrodher** [comment]
HI, 
Thanks for your contribution. In order to review the PR and merge it, changes should be separated by chart, it is not only for owners reviewing the changes but also the CI/CD system needs the changes isolated by chart in order to be able to test those changes.

Can you maintain only your changes? If it is difficult to manage a branch in this status feel free to close this PR and send a new one with a new branch created from `master` with the latest changes.

**Comment by juan131** [comment]
Hi @benjamin-wright 

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart was deprecated and moved to [bitnami/charts](https://github.com/bitnami/charts/) some weeks ago. Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In this issue ([#20969](#20969)), we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

**Pull request closed without merging**
