### PR TITLE
[incubator/druid] upgrade dependencies to latest version

### LINKED ISSUE #22753: [incubator/druid] Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
**Describe the bug**

```bash
$ helm install incubator/druid --version 0.2.0 --generate-name

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**Version of Helm and Kubernetes**:

```bash
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

https://hub.helm.sh/charts/incubator/druid

**What happened**:

Unable to install incubator/druid

**What you expected to happen**:

No error appears when install incubator/druid 

**How to reproduce it** (as minimally and precisely as possible):

```bash
helm install incubator/druid --version 0.2.0 --generate-name
```

**Anything else we need to know**:

None

### PR DESCRIPTION
**Pull request by AWaterColorPen**
#### What this PR does / why we need it:

  - update `zookeeper` from `2.1.3` to `2.1.4`
https://github.com/helm/charts/commit/0e247de6cba3970a7a31463cb8ef83dabdf11955#diff-a98ea5ed3d7475f31d22d53b4e07e244 enable the new feature to fix zk pod crash issue.
  - update `mysql` from `0.10.2` to `1.6.4`
  - update `postgresql` from `3.11.7` to `8.6.4`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #22753 #21166

#### Special notes for your reviewer:
  
 - add myself to maintainers  😁
 - Volunteering from issue helm#13867
 - Past contributions to incubator/druid chart:
   - helm#22393
   - helm#22755
   - helm#22870
   - helm#23044
   - helm#23561

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by AWaterColorPen** [comment]
/assign @maver1ck 
please help for a review.

**Comment by AWaterColorPen** [comment]
I had tested the PR on my k8s cluster. it was ok. And I checked the e2e test log, it seems zookeeper headless service issue.

**Comment by maver1ck** [comment]
@AWaterColorPen 
Maybe let's try without upgrade of ZK ?

**Comment by AWaterColorPen** [comment]
@maver1ck let me add a new commit to revert ZK.

**Comment by AWaterColorPen** [comment]
I checked the last e2e test's log.
```
I0611 12:43:09.283]   Warning  Unhealthy  2m27s (x4 over 3m6s)  kubelet, gke-jenkins-default-pool-51cafeba-1lzf  Liveness probe errored: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0611 12:43:09.284]   Warning  Unhealthy  2m18s                 kubelet, gke-jenkins-default-pool-51cafeba-1lzf  Readiness probe errored: rpc error: code = Unknown desc = error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/containers/916aca5088a6ee2576ae7ef46721c09eebd6859166e6286c43e5c1728aa92848/json: read unix @->/var/run/docker.sock: read: connection reset by peer
I0611 12:43:09.284]   Warning  Unhealthy  2m18s                 kubelet, gke-jenkins-default-pool-51cafeba-1lzf  Readiness probe errored: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0611 12:43:09.298] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I0611 12:43:09.298] <== Description of pod druid-jkg1brtxoo-zookeeper-0
I0611 12:43:09.300] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I0611 12:43:10.414] ------------------------------------------------------------------------------------------------------------------------
I0611 12:43:10.414] ==> Logs of container druid-jkg1brtxoo-zookeeper-0
I0611 12:43:10.415] ------------------------------------------------------------------------------------------------------------------------
I0611 12:45:10.257] ------------------------------------------------------------------------------------------------------------------------
I0611 12:45:10.258] <== Logs of container druid-jkg1brtxoo-zookeeper-0
I0611 12:45:10.259] ------------------------------------------------------------------------------------------------------------------------
```

`Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running`. It seems zookeeper-0's node is unhealthy, then zookeeper-1 can't find zookeeper-0 any more. 😰 Maybe we can try retest again.

**Comment by AWaterColorPen** [comment]
I can't understand why it failed when just get `ContainerCreating` pod status. But it started to pull image at `I0611 14:18:06.284`😂
```
I0611 14:18:09.146] Error from server (BadRequest): container "druid" in pod "druid-mjkt0qldfq-coordinator-749bdc4bb4-7fbkq" is waiting to start: ContainerCreating
I0611 14:18:09.147] Error printing details: Error waiting for process: exit status 1
```

**Comment by maver1ck** [comment]
@AWaterColorPen 
Thank you for your PR.

**Comment by asdf2014** [comment]
@AWaterColorPen Thanks a lot.

**Comment by AWaterColorPen** [comment]
@scottrigby 
Added myself as OWNER. And this PR is to volunteer as collaborator per issue #13867
@maver1ck seems to be rarely online anymore

**Comment by AWaterColorPen** [comment]
> @scottrigby
> Added myself as OWNER. And this PR is to volunteer as collaborator per issue #13867
> @maver1ck seems to be rarely online anymore

@scottrigby could you help to add me as collaborator?

**Comment by asdf2014** [comment]
Hi, @scottrigby @AWaterColorPen .  Is there any threshold for becoming a Collaborator? Currently, I have also contributed some [PRs](https://github.com/helm/charts/pulls/asdf2014) to the incubator/druid chart. I am also the [Committer & PMC](https://druid.apache.org/community/) of Apache Druid. I wonder if I can also be added as a Collaborator for this chart? :smile:

**Comment by scottrigby** [comment]
@AWaterColorPen added you per https://github.com/helm/charts#owning-and-maintaining-a-chart

@asdf2014 In general we look for a history of past contributions. I see you have done that https://github.com/helm/charts/commits?author=asdf2014. You would want to make a PR to add you to the chart.yaml maintainers list and chart OWNERS file, and use the PR to discuss with the current maintainers for adding you.

One note, have you seen https://github.com/helm/charts/issues/23685#issuecomment-697432038?

**Comment by asdf2014** [comment]
@scottrigby Thanks for your reply, a [PR](https://github.com/helm/charts/pull/23805) has been created as required. In addition, regarding the migration you mentioned, given that we have maintained a [druid-operator](https://github.com/druid-io/druid-operator) project separately, I also think it is unlikely that this chart will be migrated to the current Apache Druid code.

**Comment by AWaterColorPen** [comment]
@asdf2014 For my understanding, [druid-operator](https://github.com/druid-io/druid-operator) is not a helm chart project. right?

**Comment by asdf2014** [comment]
@AWaterColorPen Yes, your understanding is correct.

**Pull request merged**
