### PR TITLE
[stable/hlf-ord] Update hlf-ord

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: v.login <v.login@s7.ru>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/approve

**Comment by batazor** [comment]
Ping @alexvicegrab @inzamam-iqbal @dbandin

**Review by alexvicegrab — APPROVED** [review]
/lgtm

**Pull request merged**
