### PR TITLE
[stable/k8s-spot-termination-handler] add annotations and updateStrategy

### PR DESCRIPTION
**Pull request by egeland**
#### What this PR does / why we need it:

Rolls up the changes in #13483 and fixes the issue that's blocking that PR. Also refactors them a little.

#### Special notes for your reviewer:

If this is merged, then #13483 is superseded and can be closed.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by egeland** [comment]
@mattfarina , any chance you could review?

**Comment by egeland** [comment]
@KierranM, could you review, please? :)

**Review by KierranM — APPROVED** [review]

**Comment by KierranM** [comment]
Clearly I'm not trustworthy, thanks robot 😂

**Comment by egeland** [comment]
That's odd - you are clearly in the OWNERS file... 😕

**Comment by egeland** [comment]
Ahh... check your email for an invite to collaborate, @KierranM 
Something like https://cdn-std.dprcdn.net/files/acc_700983/9gVvBh

**Comment by KierranM** [comment]
Ah there we go, it was lost in a pile

**Comment by axozoid** [comment]
@prydonius / @jlegrone , could you please review this PR? I'd like to contribute more, but that will cause a merge conflict now. Thanks!

**Comment by egeland** [comment]
oops - the bot is too smart! @axozoid or @KierranM , would you please do the honours?

**Pull request merged**
