### PR TITLE
[stable/ark] Fix prefix param, add restic podannotation and resource

### PR DESCRIPTION
**Pull request by faizshukri**
#### What this PR does / why we need it:

- Fix indentation and position of prefix (refer https://heptio.github.io/velero/v0.10.0/api-types/backupstoragelocation.html)
- Apply podannotations to restic pod so that kube2iam will works
- Apply resources to restic pod

#### Special notes for your reviewer:

I'm aware of PR #11068 which also enable bucket prefix. But since the scope of that PR quite large (and introduce breaking changes), I assume it might take a while.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizshukri** [comment]
@cpanato Any idea how to resolve the CRD error? I saw @agolomoodysaada already put `"helm.sh/hook-delete-policy": "before-hook-creation"` label to all CRD resources.

**Comment by agolomoodysaada** [comment]
I think my PR was also receiving CRD errors try /retest

**Comment by cpanato** [comment]
@faizshukri please update your branch

**Comment by faizshukri** [comment]
@cpanato It's updated, and the test passed now. Thanks :)

**Comment by faizshukri** [comment]
@cpanato The prefix has been added in this [PR](https://github.com/helm/charts/pull/11068). But the indentation is a bit off.

I've updated this PR to fix that. And also applying podannotation and resource to the restic pod. Currently its only applied to ark.

**Comment by PabloCastellano** [comment]
@faizshukri Please resolve the conflict!

**Comment by faizshukri** [comment]
@PabloCastellano Resolved, yet e2e test always fails on me.

**Comment by PabloCastellano** [comment]
Yes, this is a known issue. Check https://github.com/helm/charts/pull/11068#issuecomment-465404606

**Comment by faizshukri** [comment]
@cpanato Can I get approval on this, since the e2e failure was caused by another issue?

Thanks

**Comment by unguiculus** [comment]
The prefix stuff was already merged in #12832, but looking at it again, `values.yaml` was not updated there. Also, what's still missing is an entry in the config table in the readme. Cloud you please add that?

**Comment by faizshukri** [comment]
@unguiculus If you meant `configuration.backupStorageLocation.prefix`, it's already in the readme.

**Comment by unguiculus** [comment]
Right, I had overlooked it.

**Pull request merged**
