### PR TITLE
ommand-->command

### PR DESCRIPTION
**Pull request by yjl-lgx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by carrodher** [comment]
@yjl-lgx you should bump chart version in `Chart.yaml`

**Review by carrodher — CHANGES_REQUESTED** [review]
You should increment chart version (`version`) in `Chart.yaml`

**Comment by yjl-lgx** [comment]
@foxish OK

**Pull request merged**
