### PR TITLE
[stable/presto] Prestosql version bump to 337

### PR DESCRIPTION
**Pull request by ghost**
#### What this PR does / why we need it:
prestosql is now on version 337 that have interesting improvements. Unfortunately, bumping up the version in he chart is not enough since healthchecks and readiness/livenessprobe will fail due to some changes in the official image behaviors.
This issues are fixed in this PR.

#### Special notes for your reviewer:
@bivas nothing in particular, hopefully this PR will be good enough to be merged, ty.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mattfarina** [comment]
@valeriano-manassero The error from CI is pointing out that the resource type is no longer supported by Kubernetes for Deployments. It's an old and now deprecated API version. It's not part of your change but is affecting your PR. There are two options, either fix it here or it needs to be fixed in another PR and then this one be rebased from that change.

**Comment by valeriano-manassero** [comment]
> @valeriano-manassero The error from CI is pointing out that the resource type is no longer supported by Kubernetes for Deployments. It's an old and now deprecated API version. It's not part of your change but is affecting your PR. There are two options, either fix it here or it needs to be fixed in another PR and then this one be rebased from that change.

@mattfarina I updated this PR and now CI looks good so I think we should be ok, let me know. Ty!

**Comment by valeriano-manassero** [comment]
> > dain  1 hour ago
> > /v1/status should be used for liveness checks on coordinator and workers
> 
> Maybe you want to update the check endpoints as well. Since the 340 is released, Can you bump the version as well

`/v1/status` are used already for probes in this PR.
About version bump, I'm not sure it should be included in this PR.

Maybe a specific PR after merging this one (if not will be approved) is a better solution?

**Review by marceloavf — APPROVED** [review]

**Comment by valeriano-manassero** [comment]
Since this will not probably merged and I had other improvements to be made, I created a new chart and added it to ArtifactHub on https://artifacthub.io/packages/helm/valeriano-manassero/presto

Closing this one, ty for feedbacks.

**Pull request closed without merging**
