### PR TITLE
[grafana] update grafana sidecar to 0.1.75

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* updated sidecar container to version 0.1.75
  * uses non root user
  * uses alpine image
  * should fix frequent restarts of sidecar container

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
* see recent commits in https://github.com/kiwigrid/k8s-sidecar/commits/master for moreinfos

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by monotek** [comment]
Ah, damn. I messed up the versioning.
This was supposed to be 4.6.0 not 4.6.2. 
4.6.0 & 4.6.1 are missing now :(

**Pull request merged**
