### PR TITLE
[stable/prometheus-operator] add ingress for Thanos sidecar, update kubelet svc

### PR DESCRIPTION
**Pull request by darkstarmv**
Signed-off-by: Maxim Valiarovski <maxim.valiarovski@target.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
- add ingress configuration for Thanos sidecar, so it can be accessed via ingress by thanos querer running in another cluster
- update kubelet service monitor to have scrape timeout, so we don't get time outs on slow kubelets

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dholbach** [comment]
I'm not the best person to review this. Not sure why I was auto-assigned.

/uncc @dholbach

**Comment by darkstarmv** [comment]
/assign vsliouniaev
assign gianrubio

**Comment by vsliouniaev** [comment]
/ok-to-test

Seems like you'll need to add the thanos CRD and also reference it in the readme if you want to upgrade prometheus operator to v0.36.0

**Pull request closed without merging**
