### PR TITLE
[stable/grafana] add useExistingRole option

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
#### What this PR does / why we need it:
This add useExistingRole option, which enables chart to skip role creation and instead bind to existing role - which is needed in f.ex. some RHEL openshift+jenkins setups, where "normal users" are not allowed to create role's (but can do the rolebinding and sa creation to the existing role).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by KlavsKlavsen** [comment]
I see no reason for the pull-charts-e2e failure ?

**Comment by KlavsKlavsen** [comment]
/test pull-charts-e2e 
(trying to rerun test :)

**Comment by KlavsKlavsen** [comment]
Test says return code != 200.. But nothing what it actually got - and the grafana pod logs looks perfect - last entry says is listening as it should.. Seems more like perhaps a matter of timing - test pod starting too quickly or something?

**Comment by davidkarlsen** [comment]
This chart is deprecated: https://github.com/helm/charts/pull/23662
Please submit PRs against: https://github.com/grafana/helm2-grafana

**Pull request closed without merging**
