### PR TITLE
[stable/jenkins] Use StatefulSet instead of Deployment

### PR DESCRIPTION
**Pull request by dylanpiergies**
#### What this PR does / why we need it:

Switch out the Jenkins master Deployment for a StatefulSet.

#### Which issue this PR fixes

Fixes the Jenkins element of #1863

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by phisco** [comment]
Yes, please. Nobody would run Jenkins without persistence enabled, it is a stateful application and therefore should move to use a statefulset

**Comment by dylanpiergies** [comment]
I'm inclined to enhance it so that it can use `volumeClaimTemplates` as well, but one step at a time. ;)

**Comment by phisco** [comment]
I don't think it really make sense to have volumeclaimtemplates, as jenkins has no HA and there is no way to scale it to more than 1 replica. 🤷‍♂️

**Comment by dylanpiergies** [comment]
> I don't think it really make sense to have volumeclaimtemplates, as jenkins has no HA and there is no way to scale it to more than 1 replica.

My thinking was that the difference in the way the lifecycle of the PV/PVC works if you use a volumeClaimTemplate. It would mean you're free to uninstall the chart without the Jenkins home volume being deleted.

**Comment by dylanpiergies** [comment]
@phisco Anyway, such discussions are precisely the reason I've kept it separate.

**Review by wmcdona89 — COMMENTED** [review]
@dylanpiergies thanks for the PR! 

what would you think about making this an opt-in feature for now...perhaps via a `master.statefulSet.enabled` flag...and allow the chart to support using `Deployment` or `StatefulSet`. we could then consider making `StatefulSet` the default in a future major release.

**Comment by wmcdona89** [comment]
#23087 also proposes this change

**Comment by dylanpiergies** [comment]
@wmcdona89 Well, aside from the renamed values for the labels and annotations, this is a non-breaking change, at least theoretically. I was hoping to see what automation testing would occur prior to looking to fully assess the level of technical risk involved and whether any additional testing needs to be performed.

As for continuing to support `Deployment`, well on the one hand I kinda feel it's in bad taste to continue to support something that's plainly inappropriate (even arguably incorrect), as discussed on #1863. I definitely think of this change as more towards the bug fix end of the spectrum than a feature. On the other hand, yeah, it _is_ quite a fundamental change and will probably raise alarm among the more risk-averse.

Personally, I think if upgrade path from any sane configuration we can think of can be demonstrated to run smoothly, we should just cut over. Keeping support for `Deployment` will leave tech debt. Though if people want to take a softer approach, I'm willing to make the necessary changes to make the use of `StatefulSet` optional.

**Comment by mattfarina** [comment]
/ok-to-test

@wmcdona89 can you update from master to pull in the changes.

**Comment by torstenwalter** [comment]
/hold This chart will be moved to https://github.com/jenkinsci/helm-charts see for details #23562
Would be great if you could create the PR in the new location.

**Pull request closed without merging**
