### PR TITLE
Update readme to reflect move from incubator to stable for cockroachdb

### PR DESCRIPTION
**Pull request by hvaara**
CockroachDB is now in stable. Updated the install section, and one more place referring to the incubator.

/cc @a-robinson Does this look ok?

### CODE REVIEW

**Comment by hvaara** [comment]
The build failed because I didn't bump the chart version. I've only updated `README.md`. Should I still update the chart version? If I do, I'll wait for #3769 to be merged first.

**Comment by a-robinson** [comment]
Thanks @hvaara! This LGTM. Feel free to use the same version number as #3769, I can update that one if this gets in first.

/ok-to-test
/lgtm
/approve

**Comment by hvaara** [comment]
@a-robinson Thanks a lot for taking a look! I've updated the chart version.

**Pull request merged**
