### PR TITLE
[incubator/kafka] Tolerations for kafka exporter

### PR DESCRIPTION
**Pull request by ephur**
#### What this PR does / why we need it:
Updates PR that was previously unmerged to support adding tolerations to the Kafka Exporter

#### Special notes for your reviewer:
@faraazkhan 
@h0tbird 
@benjigoldberg 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@ephur please sign the DCO

**Comment by ephur** [comment]
> @ephur please sign the DCO

fixed, had the wrong name in the original dco signoff, thanks!

**Pull request merged**
