### PR TITLE
[stable/jenkins] FIX #20262

### LINKED ISSUE #20262: [stable/jenkins] helm3 unable to install chart without cluster-admin permission
**Describe the bug**
When trying to install stable/jenkins chart with a serviceaccount that is not **cluster-admin** the result is a **forbidden** creating RBAC resources

**Version of Helm and Kubernetes**:
- helm version `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`
- Kubernetes `version 1.11.x  - 1.17.x` 
- Openshift `v3.11`
- May impact other versions as well

**Which chart**:
stable/jenkins

**What happened**:
Issuing command `helm3 install jenkins stable/jenkins` using a service account with **admin** role on the specified namespace the result is the following:

```
Error: roles.rbac.authorization.k8s.io "jenkins-schedule-agents" is forbidden: user "system:serviceaccount:test:test" (groups=["system:serviceaccounts" "system:serviceaccounts:test" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["persistentvolumeclaims"], Verbs:["*"]}
{APIGroups:[""], Resources:["pods"], Verbs:["*"]}
{APIGroups:[""], Resources:["pods/exec"], Verbs:["*"]}
{APIGroups:[""], Resources:["pods/log"], Verbs:["*"]}
```

**What you expected to happen**:
The chart should be installed successfully

**How to reproduce it** (as minimally and precisely as possible):
Create a namespace and a serviceaccount in it. 
The new service account must have **admin** role in the namespace
Use that service account to install the chart

Example steps:
```
kubectl create ns test
kubectl -n test create serviceaccount test
kubectl -n test create rolebinding --clusterrole=admin --serviceaccount=test:test test-admin
kubectl -n test describe $(kubectl -n test get secret -o name| grep test-token) | grep token | cut -d " " -f 7 
```
Use the retrieved token into the `test` namespace, to issue the following command:
`helm3 install jenkins stable/jenkins`

**Anything else we need to know**:

The problem is in `rbac.yml` file at lines 16-19:
```yaml
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims"]
  verbs: ["*"]
```

The **admin** role lack the permission to grant `verbs: ["*"]` to the selected resources, only the cluster-admin can do that

### PR DESCRIPTION
**Pull request by mbovo**
#### Which issue this PR fixes
  - fixes #20262

#### Checklist
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@mbovo Thanks for this. Looks like a good improvement. Haven't tested it so far. Could you fix the DCO check?

**Comment by mbovo** [comment]
@torstenwalter done, sorry for the delay, I had to reinstall on this laptop my keys

**Comment by Cirrith** [comment]
Quick question, why is `deletecollection` needed? 

I'm still pretty new to Jenkins Kubernetes so apologizes if that is a stupid question.

**Comment by mbovo** [comment]
@Cirrith not sure if it's actually used. 
I've write the permission list in order to match the permission from the "admin" cluster role, that is the one given when you are admin only on a namespace.I
I think jenkins should be granted perms equal to an admin in the namespace in which it resides in order to spawn pods and the like and the manage them.

**Comment by Cirrith** [comment]
@mbovo I recently ran into a similar issue when upgrading from helm2 to helm3 for [Gitlab-runner](https://gitlab.com/gitlab-org/charts/gitlab-runner). It might be worth looking at their helm chart as their solution didn't hard-code resource lists.

Gitlab-Runner Templates:
[Values.yaml](https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/master/values.yaml). Search for rbac
[Role.yaml](https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/master/templates/role.yaml)

**Comment by mbovo** [comment]
IMHO maybe it's better to keep this as bugfix of #20262  and open another one as change request with the customization of RBAC fields as @Cirrith suggest, what do you think about @torstenwalter ?

**Comment by torstenwalter** [comment]
@mbovo Thank you for this PR. Nice job!

**Pull request merged**
