### PR TITLE
[stable/spring-cloud-data-flow] Add OWNERS file

### PR DESCRIPTION
**Pull request by chrisjs**
Signed-off-by: Chris Schaefer <cschaefer@pivotal.io>

#### What this PR does / why we need it:

Adds OWNERS file for SCDF chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
@chrisjs any chance you can get another OWNER? :)

**Comment by chrisjs** [comment]
> @chrisjs any chance you can get another OWNER? :)

@maorfr - sure, added!

**Comment by maorfr** [comment]
great! just add him to Chart.yaml as well :)

**Comment by chrisjs** [comment]
done!

**Comment by maorfr** [comment]
/assign
/ok-to-test

nicely done!

**Pull request merged**
