### PR TITLE
[stable/stolon] Upgrade Stolon image to v0.13.0-pg11

### PR DESCRIPTION
**Pull request by demisx**
#### What this PR does / why we need it:
Upgrades current Postgres version to PG11

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by lwolf** [comment]
lgtm

**Comment by demisx** [comment]
@lachie83 @davidkarlsen Hi guys. Can any of you please advise what needs to be done here to move this PR forward? This is my first PR in helm repo and I am not sure what the next steps are. Is anything else needed for me.

Please note, I've added the OWNERS file with the current 2 maintainers as per #13869. Thank you.

**Comment by demisx** [comment]
@viglesiasce @prydonius Can one of you guys please review this PR and let me know if anything is preventing it from being merged? Any other feedback that would help to maintain this helm chart fresh would be also appreciated. I am pretty new to this. Thank you.

**Comment by zanhsieh** [comment]
@demisx 
Could you bump the chart to latest please? Thank you.

**Comment by zanhsieh** [comment]
@lwolf 
I suggest splitting update OWNER file and image to different PR.

**Comment by lwolf** [comment]
@zanhsieh thank you, will do

**Comment by zanhsieh** [comment]
@lwolf 
Would you mind to post the link of separate PR for owners changes?

**Comment by lwolf** [comment]
@zanhsieh yes, sorry for the delay - https://github.com/helm/charts/pull/18175

**Comment by demisx** [comment]
@zanhsieh I've updated this PR to include the latest chart version. Please let me know if anything else is needed.

**Comment by zanhsieh** [comment]
@demisx 
I think it would be better if we take off OWNER modification as separate PR; otherwise this would always have "do-not-merge/invalid-owner-file" tag on.

**Comment by demisx** [comment]
@zanhsieh I've removed `OWNERS` file from this PR and will create a separate one as requested.

**Review by merqurio — APPROVED** [review]

**Comment by demisx** [comment]
Guys, is there anything else I can do to move this PR forward?

**Review by jlegrone — APPROVED** [review]
/lgtm

**Comment by jlegrone** [comment]
@demisx sorry about the delay, I tried updating your branch but got hit with the DCO bot. Please rebase from master and I'll approve again.

**Pull request closed without merging**
