### PR TITLE
[stable/traefik] Add option to specify /ping check entry point.

### LINKED ISSUE #16718: [stable/traefik] /ping entry point is set hardcoded to 'http'
**Is your feature request related to a problem? Please describe.**
In chart v1.69.1 readinessProbe and livenessProbe were introduced, using Traefik's /ping endpoint. Both use the http port (80), and are hardcoded. We'd like to be able to use https (443).

**Describe the solution you'd like**
Make the /ping entry point configureable.

**Describe alternatives you've considered**
I've tried setting `--ping --ping.entrypoint=https` but it seems this will not override settings in the configmap.

A PR is on it's way.

### PR DESCRIPTION
**Pull request by robinelfrink**
Signed-off-by: Robin Elfrink <robin.elfrink@eu.equinix.com>

#### Is this a new chart
No.

#### Which issue this PR fixes
  - fixes #16718

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by robinelfrink** [comment]
Rebased due to Chart version merge conflict.

**Comment by zanhsieh** [comment]
@emilevauge
@dtomcej
@timoreimann
@vdemeester
@nmengin
@mmatur
@ldez
@Juliens
@jbdoumenjou
@geraldcroes
@SantoDE
@errm
Could you guys merge it please?

**Comment by robinelfrink** [comment]
> Hello @robinelfrink Do you think you could bump this chart version so we could merge this today?

Done.

**Pull request merged**
