### PR TITLE
stable/prometheus-operator Fix typos in CRD

### PR DESCRIPTION
**Pull request by timja**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@timja thanks for spotting the issue!

The CRDs are generated from the code here: https://github.com/coreos/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go so they would have to be fixed there first and then imported here.

Could you open a pull request in coreos/prometheus-operator to fix the spelling mistake and then we can sync them up to here.

**Comment by timja** [comment]
It's already fixed there:
https://github.com/coreos/prometheus-operator/commit/7055b7f66ecd9994aa0f1a9628c69962e58cf4d5

Just needs syncing, close this I assume?

**Comment by vsliouniaev** [comment]
Looks like this hasn't had a release yet. In general I tend not to sync the CRDs unless there's some new feature in them. The default prometheus-operator configuration manages CRDs in the cluster too, so it will create them and overwrite the ones provisioned by Helm anyway.

Feel free to close this

**Pull request closed without merging**
