### PR TITLE
telegraf: allow overriding protocol

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Allows users to change the protocol for Telegraf's StatsD from TCP to
UDP.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
I signed it!

**Comment by lachie83** [comment]
cc @jackzampolin

**Comment by lachie83** [comment]
LGTM. @jackzampolin any comments?

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by jackzampolin** [comment]
I'm not a huge fan of the approach here. Seems like a quick fix that leaves the `protocol` undefined for the other service plugins. 

Working on splitting this chart up into a couple of different telegraf charts because of the rough way this implemented. I'm fine with merging if we add the `protocol` definition to the other service plugins too.

**Comment by lachie83** [comment]
@jeroenvisser101 @jackzampolin How would you like to proceed with this PR?

**Comment by jeroenvisser101** [comment]
I think it's best to close this and work this into the separate telegraf-service chart that @jackzampolin is making. I'll have a chat with him, probably next week, about this.

**Comment by lachie83** [comment]
@jeroenvisser101 Closing at your request.

**Pull request closed without merging**
