### PR TITLE
[incubator/elasticsearch] Add option to add additional ES_JAVA_OPTS parameters

### PR DESCRIPTION
**Pull request by desaintmartin**
**What this PR does / why we need it**:

Add option to add additional ES_JAVA_OPTS parameters to the whole cluster.

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @simonswine @icereval @rendhalver

**Comment by rendhalver** [comment]
Can you do this with the env var that already exists?
What does this allow us to do that can't be done with the env setup?

**Comment by desaintmartin** [comment]
Actually, it can't be done using the env var already existing (or if it can, one would have to completely override ES_JAVA_OPTS envvar).

Use case was to have some upgrade requiring temporary "non-secure" features only using a flag:
```yaml
elasticsearch:
  cluster:
    additionalJavaOpts: "-Des.allow_insecure_settings=true"
```

**Comment by rendhalver** [comment]
Ok cool.
Let's get this tested then.

/ok-to-test

**Comment by desaintmartin** [comment]
Rebased.

**Comment by desaintmartin** [comment]
Rebased again. Can we get this merged @rendhalver or do you need more informations ?

**Pull request merged**
