### PR TITLE
[stable/minio] update default values

### PR DESCRIPTION
**Pull request by harshavardhana**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by harshavardhana** [comment]
// cc @krisis

**Comment by Birdrock** [comment]
What is the reasoning for the increase in PVC and memory requests? This seems to be a rather significant change in footprint.

**Comment by harshavardhana** [comment]
> What is the reasoning for the increase in PVC and memory requests? This seems to be a rather significant change in footprint.

Reasoning - all serious deployments such as productiion ones have minimum of 1TiB any other values are too small and are generally just toy setups for testing.  Default values carry meaningful values for a production deployment.

You are allowed to change these default values if you want a test setup @Birdrock

**Comment by Birdrock** [comment]
@harshavardhana Thank you for the answer - this makes sense.

**Comment by patricklucas** [comment]
This change caught us off guard a bit, with the large resource increases.

A pattern other charts use is to have a separate `values-production.yaml` file with suggested defaults for production deployments, leaving the default `values.yaml` for a minimum-viable setup useful as a baseline for testing/"toy" setups, like you say, which usually comprise the majority of deployments of Helm charts for software like this.

**Comment by harshavardhana** [comment]
> This change caught us off guard a bit, with the large resource increases.
> 
> A pattern other charts use is to have a separate `values-production.yaml` file with suggested defaults for production deployments, leaving the default `values.yaml` for a minimum-viable setup useful as a baseline for testing/"toy" setups, like you say, which usually comprise the majority of deployments of Helm charts for software like this.

I disagree - Our default is production or close to production. If you have a preferred values.yaml you should  provide us that value rather than relying on defaults.

**Comment by patricklucas** [comment]
A prevailing philosophy for Helm charts in this repo is to [not specify default resources](https://github.com/helm/charts/search?q="not+to+specify+default+resources"), leaving it to users to choose and ensuring things can run out-of-the-box on a wide range of environments.

I think this applies to persistent volume size too, especially for something like Minio which can be used for deployments large and small, and PVs are much more easily grown than shrunk.

@krisis do you have an opinion on this? There was no justification for the change given in the issue title or description, but maybe you and @harshavardhana discussed this offline?

**Comment by harshavardhana** [comment]
> A prevailing philosophy for Helm charts in this repo is to [not specify default resources](https://github.com/helm/charts/search?q=%22not+to+specify+default+resources%22), leaving it to users to choose and ensuring things can run out-of-the-box on a wide range of environments.
> 
> I think this applies to persistent volume size too, especially for something like Minio which can be used for deployments large and small, and PVs are much more easily grown than shrunk.
> 
> @krisis do you have an opinion on this? There was no justification for the change given in the issue title or description, but maybe you and @harshavardhana discussed this offline?

I disagree, this is our helm chart we will choose whatever the sane defaults we think is necessary.  Not all products are same there cannot be generalized philosophy. You have the option to choose whatever values you want by customizing just like how you would customize for a production deployment. 

We want to make deployment experience from the get go a production like experience,  choosing toy setup defaults undermines our requirement. If you have no reason to go beyond certain small scale requirement then that is not the problem of this helm chart.. You are allowed to choose whatever you want in your limited deployment.

**Comment by patricklucas** [comment]
I'm not sure if you usually communicate like this or are just having a bad day, but comments like yours are what give open source communities and software engineers at large a bad reputation.

If you are not interested in civil collaboration in this community, I would suggest moving your chart to a separate repository and listing it on [Helm Hub](https://hub.helm.sh/) so that other users who expect the same level of openness of collaboration and courtesy as you can usually get from the maintainers of this Helm repository and of the other charts in it are not disappointed.

**Comment by harshavardhana** [comment]
> I'm not sure if you usually communicate like this or are just having a bad day, but comments like yours are what give open source communities and software engineers at large a bad reputation.
> 
> If you are not interested in civil collaboration in this community, I would suggest moving your chart to a separate repository and listing it on [Helm Hub](https://hub.helm.sh/) so that other users who expect the same level of openness of collaboration and courtesy as you can usually get from the maintainers of this Helm repository and of the other charts in it are not disappointed.

@patricklucas I am the maintainer of this helm repo, excuse me from being direct in what is the intention and there are no good reasons why "toy" defaults are correct.

You are simply disappointed with default values that is just your personal opinion which we don't agree with, we gave an explanation on why the default values were changed. You can configure whatever you want in this repo - no one is forcing you to use a particular set of configuration and not allow you to change, you know exactly what your resources are and what you wish to use this for. A minor change in your workflow is all that is needed i.e providing values.yaml

We will eventually move this chart, this repo is going to become obsolete end of this year - https://github.com/helm/charts#deprecation-timeline

**Pull request merged**
