### PR TITLE
Update graylog.replicas customization example

### PR DESCRIPTION
**Pull request by inthecloud247**
#### What this PR does / why we need it:
Fixes incorrect example command in graylog helm chart.

### CODE REVIEW

**Comment by KongZ** [comment]
@inthecloud247 please bump chart version

**Comment by inthecloud247** [comment]
@KongZ bump'd

**Comment by inthecloud247** [comment]
going to close this and open a clean PR

**Comment by inthecloud247** [comment]
looks like my change was already merged in a diff PR, so this is unnecessary.

**Pull request closed without merging**
