### PR TITLE
[incubator/druid] add enabled flag to all druid roles

### PR DESCRIPTION
**Pull request by AWaterColorPen**
not a new chart

#### What this PR does / why we need it:

The new features:

- add enabled flag to all druid roles
  - customer will want only one or two druid roles such as historical with no `_default_tier`. adding `enabled` flag to all druid roles support deploying a part of druid apps
- remove some dependencies chart default values from `values.yaml`
  - delete `zookeeper.persistence.enabled` setting. it is `true` by default at [zookeeper chart](https://github.com/helm/charts/blob/master/incubator/zookeeper/values.yaml#L120)
  - delete `postgresql.persistence.enabled` setting. it is `true` by default at [postgresql chart](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L290)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

It was tested on our own production k8s cluster. It is ready for production now.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by AWaterColorPen** [comment]
/assign maver1ck
please help for a review

**Comment by maver1ck** [comment]
@AWaterColorPen 
Please rebase after this:
https://github.com/helm/charts/pull/22912

**Comment by AWaterColorPen** [comment]
@maver1ck updated

**Review by asdf2014 — APPROVED** [review]
LGTM

**Pull request merged**
