### PR TITLE
[stable/kube-state-metrics]: Add support for host networking

### PR DESCRIPTION
**Pull request by nicholascapo**
Signed-off-by: Nicholas Capo <nicholas.capo@gmail.com>

@fiunchinho 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Review by davidkarlsen — APPROVED** [review]

**Comment by nicholascapo** [comment]
@davidkarlsen Thanks! That was fast!
How long will it take before I can use the updated version?
I still only see v1.1.0 after a `helm repo update`

**Comment by nicholascapo** [comment]
Ah there it is, just had to wait a bit longer :grinning:

**Pull request merged**
