### PR TITLE
concourse: Small fixes in README and templates

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Typo and other small fixes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Chr1st0ph — APPROVED** [review]

**Comment by cimomo** [comment]
Resolved merge conflict. @timstoop @Chr1st0ph @william-tran

**Comment by cimomo** [comment]
Updating the chart version since it got bumped since the last PR. @sameersbn @timstoop

**Review by Chr1st0ph — APPROVED** [review]

**Pull request merged**
