### PR TITLE
[stable/prometheus] additional control added to cluster role (#16907 #16690)

### LINKED ISSUE #16690: stable/prometheus - fails with empty clusterrole ruleset
**Describe the bug**
If your render prometheus charts without psp, the clusterroles for alertmanager and pushgateways end up without any rules like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
```
instead we need to add an empty array like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
  []
```

**Version of Helm and Kubernetes**:
helm v2.14.3
k8s 1.13.x

**Which chart**:
stable/prometheus

**What happened**:
```
error: error validating "STDIN": error validating data: ValidationError(ClusterRole): missing required field "rules" in io.k8s.api.rbac.v1beta1.ClusterRole; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
The ClusterRole should be applied successfully.

**How to reproduce it** (as minimally and precisely as possible):
deploy the chart without psp.

**Anything else we need to know**:

### LINKED ISSUE #16907: [stable/prometheus] Cluster Roles & Role bindings created for disabled componenets
**Describe the bug**
Chart will create ClusterRoles & ClusterRolerBindings for components which are not enabled.
The ClusterRoles do not have any rules associated but are still created. 

Is this the desired behaviour? 

**Version of Helm and Kubernetes**:
helm: v2.14.3
K8s: minikube v1.3.1

**Which chart**:
stable/prometheus

**What happened**:
Empty cluster roles and cluster role bindings created for disabled components

**What you expected to happen**:
ClusterRoles & ClusterRoleBindings should not be created for disabled components

**How to reproduce it** (as minimally and precisely as possible):
```
values.yml:
-----
pushgateway:
  enabled: false
alertmanager:
  enabled: false
```
`helm install --name dev-prom stable/prometheus -f values.yml --debug --dry-run`

Running after install:
`k get clusterroles | grep dev-prom`
Shows unnecessarily created cluster roles .

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by schoofsc**
Signed-off-by: schoofsc <Christian.Schoofs@t-online.de>

#### What this PR does / why we need it:
If .Values.rbac.create = true and .Values.alertmanager.enabled = false or .Values.pushgateway.enabled = false then still roles are created with rules that are empty so the helm chart doesn't work! This is also the case if the default values are used.
The changes made are based on the files server-clusterrole.yaml and server-clusterrolebinding.yaml.
Furthermore the templates kube-state-metrics-clusterrole and kube-state-metric-clusterrolebinding have been adapted so that all files have the same format.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #16907
  - fixes #16690

#### Special notes for your reviewer:
@zanhsieh I've put out a new "clean" PR. I did this because I had a DCO problem with #17746 because I did commits with two users.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by schoofsc** [comment]
@zanhsieh can you help me with the failed test? 
To me it looks like it's due to a problem with the test infrastructure. Locally I have tested the chart several times and it works fine. Maybe it's because the Node-Exporter can't start because there is already a Node-Exporter in the test infrastructure (independent of the test deployment of the chart).

**Comment by zanhsieh** [comment]
@vsliouniaev 
Could you look into this? BTW, how do I get similar PRs moving if the e2e test log asking me to use kubectl logs to investigate? I don't think I have access to e2e test stack.

**Comment by schoofsc** [comment]
@zanhsieh I updated the chart version. Can you give me the lgtm label?

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
