### PR TITLE
 [stable/external-dns] Add SecurityContext and bump to 0.5.9

### PR DESCRIPTION
**Pull request by so0k**
#### What this PR does / why we need it:

- external-dns `0.5.7` added support for read only filesystem via `securityContext` - adding chart parameter
- external-dns `0.5.9` no longer uses `root` user and breaks this chart usage of `/root/.aws/credentials` (which was undocumented, but added in Chart version `0.5.1`)

#### Special notes for your reviewer:

- **Breaking change**: Chart `1.1.0` requires users of appVersion < 0.5.9 who also use `aws.secretKey` and `aws.accessKey` to set `aws.credentialsPath: "/root/.aws/"` - although this use case should affect a minor set of user as on AWS IAM policies attached to the node role or `kube2iam` / `kiam` should be used instead

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by so0k** [comment]
refer also to https://github.com/zalando-incubator/kubernetes-on-aws/pull/1413/files

**Comment by so0k** [comment]
ping @mgoodness @mattfarina

**Comment by so0k** [comment]
@davidkarlsen - you're PR breaks external-DNS for some users

**Comment by so0k** [comment]
@linki what is the process to get these merged, you approved 7 days ago, yet it was never merged?

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
