### PR TITLE
[stable/grafana] fixed sidecar image version

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* fixed typo in image of pr https://github.com/helm/charts/pull/16309

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
can we split the `Recreate` to another PR?

**Comment by monotek** [comment]
> can we split the `Recreate` to another PR?

Sorry, was not intended. I just removed it...

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

thanks!

**Pull request merged**
