### PR TITLE
fix misspelling of Kubernetes

### PR DESCRIPTION
**Pull request by normanjoyner**
Fixes a few typos and cleans up some extraneous whitespace

### CODE REVIEW

**Comment by mattfarina** [comment]
@normanjoyner Thanks for the contribution. Charts are immutable so the version needs to be incremented. I did this for you and cleaned up the lint errors.

**Comment by mattfarina** [comment]
@normanjoyner I didn't notice this before but, we try to change on chart per pull request. Since you are changing two charts can you please pull these apart into two pull requests.

**Comment by linki** [comment]
@mattfarina don't mind me. just dropped a blank line that the linter complained about.

**Review by juan131 — CHANGES_REQUESTED** [review]
You're updating two charts (incubator/vault and stable/risk-advisor) on the same PR. Please create a separate PR for any of them.

**Review by Chr1st0ph — APPROVED** [review]

**Pull request closed without merging**
