### PR TITLE
[stable/airflow] Add checksum annotations to roll deployments

### PR DESCRIPTION
**Pull request by darkgerm**
#### What this PR does / why we need it:
- Add checksum annotations to roll deployments when configmaps or secrets change.
- Rename the filenames of configmap and secret to let them match the name in Kubernetes. (For the chart readability)
- Remove `configmap.fabric8.io` annotations because it is not used in this chart.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by stijndehaes** [comment]
I think the removed annotation is used by: https://github.com/fabric8io/configmapcontroller

But the way you introduced this now works for everyone. I wanted to make a PR like you just did :) 
Maybe you could also add the `extraConfigmapMounts` or I will make a second PR adding them later your choice.

**Comment by darkgerm** [comment]
Hi @stijndehaes, Thank you for your prompt reply!

I think it's impossible to add checksum annotations for `extraConfigmapMounts`. Since the extra configmap content is not in the chart, there is no way to calculate the checksum for it. If someone has extra configmap and wants to roll deployment when it changes, he should install `fabric8io/configmapcontroller` and set annotations by overriding`airflow.podAnnotations` in `values.yaml`. (or maybe another way if he prefers.)

**Comment by stijndehaes** [comment]
@darkgerm good point I will look into rolling out the fabric8io/configmapcontroller for my needs.

**Comment by darkgerm** [comment]
@gsemet @maver1ck  please review this when you have time. Thanks!

**Review by gsemet — APPROVED** [review]

**Pull request merged**
