### PR TITLE
[stable/jenkins] add numExecutors as a variable in values file

### PR DESCRIPTION
**Pull request by kevinm444**
#### What this PR does / why we need it:
This will allow users to set the numExecutors for Jenkins on startup after helm install without having to change the config.yaml file or using the Jenkins UI to configure the numExecutors.

#### Special notes for your reviewer:
Will allow users to easily use values.yaml file for everything instead of having to make specific changes to other template files.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by kevinm444** [comment]
Hi @maorfr,

Thank you for your comment.
I believe it is important to expose the numExecutors field in order for Jenkins to be run automatically without even having to configure the settings for the # of executors. 
Users that deploy Jenkins through helm charts with job templates will be able to automatically run their builds through either repository commits or going to the url build path.

**Comment by maorfr** [comment]
Very well :)
If you resolve conflicts we can get on with merging.
Thanks for contributing!

**Comment by kevinm444** [comment]
Done, thank you for the quick reply!

**Pull request merged**
