### PR TITLE
goldpinger: Added PriorityClassName to Chart

### PR DESCRIPTION
**Pull request by mpritter76**
Signed-off-by: Mike Ritter <mike.ritter@target.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

@okgolove @s-vkropotko

### CODE REVIEW

**Review by okgolove — APPROVED** [review]

**Comment by okgolove** [comment]
Hi @mpritter76! Thank you for the PR.

Everything is fine except chart's version. Could you bump it?

**Comment by mpritter76** [comment]
Is it both version and appVersion that needs to be incremented?

**Comment by vkropotko** [comment]
Hi @mpritter76! 
appVersion is a version of an application -> image.tag = 2.0.0
So only chartVersion in your case.

**Review by s-vkropotko — APPROVED** [review]

**Pull request merged**
