### PR TITLE
[stable/step-certificates] Add Chart for step-certificates

### PR DESCRIPTION
**Pull request by maraino**
#### What this PR does / why we need it:
This PR adds a chart to install [step-certificates](https://github.com/smallstep/certificates), an online certificate authority for internal infrastructure.

#### Which issue this PR fixes
First version

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @maraino,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by maraino** [comment]
> Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

Hi @maorfr, I haven't considered it yet, but sure, it's an option and I'll look into it.

**Comment by maraino** [comment]
@maorfr: I've followed your suggestion and added a new repo to helm hub. See https://github.com/helm/hub/pull/105
If this PR is merged, the stable repo will contain the most stable release, while the smallstep repo will have stable but newer versions.

**Comment by maorfr** [comment]
i am glad you followed my suggestion! :)
we will probably not merge both, so no worries there. i prefer that the smallstep repo be the only one with this chart ;)
wdyt?

**Comment by maraino** [comment]
@maorfr Because of the visibility, I would prefer to see the package in the stable repo, step-certificates is an online certificate authority for internal infrastructure and I think is a quite useful service. Not only that this helm package is used as a sub-chart for [autocert](https://github.com/smallstep/autocert). Autocert uses a mutating admission webhook, that looks to a specific annotation in your YAML and injects HTTPS/TLS certificates in pods, and it takes care of renewing them using a sidecar. I haven't created a PR for autocert yet because it depends on step-certificates.

The combination of both packages does a big part of the work that you need to get your infrastructure communications over (m)TLS.

**Pull request closed without merging**
