### PR TITLE
[stable/prometheus] Add options for config file path and disabling configmapReloader

### PR DESCRIPTION
**Pull request by techninja1008**
#### What this PR does / why we need it:

It adds the `server.configPath` option to change prometheus's `--config.file` argument. It also adds `configmapReloader.enabled` to allow disabling of the reloader.

This is specifically so that I can properly utilise a Thanos sidecar, which both templates the config file and provides the reloading functionality itself.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

N/A

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by techninja1008** [comment]
Ping @mgoodness @gianrubio

**Comment by techninja1008** [comment]
Ping @gianrubio

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by techninja1008** [comment]
Features have already been added since opening of this merge request.

**Pull request closed without merging**
