### PR TITLE
[stable/ipfs] upgrade image, misstype in pvc size example

### PR DESCRIPTION
**Pull request by danacr**
instead of persistence.size, the example was referencing storage.size which will not work

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by pieterlange** [comment]
You're also upgrading IPFS in this PR

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

thanks for contributing!

**Pull request merged**
