### PR TITLE
[stable/jenkins] Allow to enable OWASP Markup Formatter Plugin

### PR DESCRIPTION
**Pull request by 375gnu**
Signed-off-by: Hleb Valoshka <375gnu@gmail.com>

#### What this PR does / why we need it:

If one works with ghprb jenkins plugin then data sent but github contains html snippets which are not parsed by default (see https://github.com/janinko/ghprb/issues/140). To workaround this issue one needs to install OWASP Markup Formatter Plugin and to set markup formatter to `Safe HTML`.

Currently using the chart we can install the required plugins, but `Safe HTML` should be enabled manually. This PR fixes this inconvenience.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
Hey @375gnu,

Happy to see another contribution from you!
Can this PR be simplified? I would expect no changes to `_helpers.tpl` for example. In addition, can the existing mechanism to install plugins be used?

What do you think?

**Comment by 375gnu** [comment]
Hi @maorfr, I've simplified my pr a little. If you are ok with it, i'll squash commits.

My original idea was to make it fool proof that's why it was quite big.

**Comment by maorfr** [comment]
Thanks for your reply and changes, much appreciated. It is looking much better!

I see that in `config.yaml` there is a mention of the plugin version. Can this be avoided? If not, we should at least document it.

In addition, I would prefer to not add the plugin installation, but rather document it instead, to avoid changing the default chart installation.

Will that be ok by you?

**Comment by 375gnu** [comment]
Hi @maorfr , I've pushed a new commit addressing your requirements. If the pr looks good now for you I'll rebase it against the current master and squash into a single commit.

**Comment by maorfr** [comment]
/ok-to-test
Looks good! Thanks for your cooperation :)
Feel free to squash if you want.

**Comment by 375gnu** [comment]
Hi @maorfr , I've squashed and rebased, could you merge it?

**Comment by maorfr** [comment]
/lgtm

Thanks for contributing!

**Pull request merged**
