### PR TITLE
[stable/datadog] Add some missing syscalls to the `system-probe` seccomp profile

### PR DESCRIPTION
**Pull request by L3n41c**
#### What this PR does / why we need it:

Add some missing syscalls to the `system-probe` seccomp profile

#### Which issue this PR fixes

There’s some OS / kernel versions where `system-probe` ends in `CrashLoopBackOff` state with the current seccomp profile. And reverting to the default seccomp profile fixes the issue, which is the sign that the current seccomp profile is too restrictive of those platforms.

So, I ran `system-probe` under `strace` with the default seccomp profile to see all the syscalls that it does and I added in the custom seccomp profile the ones that were missing.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by leeavital — APPROVED** [review]

**Comment by clamoriniere** [comment]
/ok-to-test
Hi @L3n41c, could you please rebase this PR.

**Comment by L3n41c** [comment]
Hi @clamoriniere ,
This PR has just been rebased.

**Pull request merged**
