### PR TITLE
[incubator/oauth-proxy] Tweaked oauth-proxy deployment template to accept boolean extraArgs

### PR DESCRIPTION
**Pull request by dcwangmit01**
* Prior to this commit, values.yaml extraArgs only allowed setting of
  `key=value` pairs.  However, some oauth2_proxy flags are boolean
  flags with only `key` and no `value`.  In the example below,
  `ssl-insecure-skip-verify` is one such flag.

```
  extraArgs:
    provider: "oidc"
    ssl-insecure-skip-verify:
    cookie-secure: "true"
```

* This commit allows boolean flags to be added to extraArgs as shown
  above by `ssl-insecure-skip-verify`.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by compleatang** [comment]
LGTM

**Comment by compleatang** [comment]
One super minor point is that if #3255 is merged before this then you'd need to version bump again.

**Comment by dcwangmit01** [comment]
I'll watch for it and update the PR if it happens.  Thanks @compleatang

**Pull request merged**
