### PR TITLE
[stable/rabbitmq] Fix healthchecks

### PR DESCRIPTION
**Pull request by tompizmor**
#### What this PR does / why we need it:
Updates the rabbitmq healthchecks so they are trustworthy. It seems the previous version never fail.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by tompizmor** [comment]
@intelfx @thomas-riccardi can you check this one?

**Review by thomas-riccardi — COMMENTED** [review]
LGTM, I didn't test though

**Review by thomas-riccardi — APPROVED** [review]
Tests OK:
- pod stays alive more than 5 min
- when changing the test string to `ok2` instead of `ok` in the liveness probe: after 2min the pod is correctly marked unhealthy and killed

**Comment by tompizmor** [comment]
I did the same tests. Thanks!

**Pull request merged**
