### PR TITLE
[stable/influxdb]:Persistence should be enabled in default and Notes need to include the password and user name if default user had been enabled.

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

#### What this PR does / why we need it:

* Persistence should be enabled. I believe that can be tips for the user who were going to deploy it. If you did not have your persistence storage plain(like dynamic pv or other), your deployment would be failed.  You can turn off persistence manually and that means your data may be lost if the pod be destroyed.

* If the default user has been set. The Notes.txt should include the command of how to print the user name and password

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Aisuko** [comment]
/ retest

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

thanks!

**Pull request merged**
