### PR TITLE
[stable/jenkins] Added ability to configure multiple LoadBalancerSourceRanges

### PR DESCRIPTION
**Pull request by yukirii**
**What this PR does / why we need it**:

This change allows us to configure multiple loadBalancerSourceRanges. It could be useful if you want to allow more than one inbound IP address ranges.

In the current implementation, you received following error when you try to specify multiple IP address ranges:
```yaml
# values.yaml
Master:
  loadBalancerSourceRanges:
    - 192.0.2.0/24
    - 198.51.100.0/24
    - 203.0.113.0/24
```
`Error: release jenkins failed: Service "jenkins" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[192.0.2.0/24 198.51.100.0/24 203.0.113.0/24]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by lachie83 — APPROVED** [review]

**Comment by shiftky** [comment]
I didn't change charts logic but the test failed. 🤔 
Is there a problem with the loading of the Jenkins plugin?

**Pull request merged**
