### PR TITLE
[incubator/kafka] Added external.labels to external services

### PR DESCRIPTION
**Pull request by kortatu**
#### What this PR does / why we need it:

If a user needs to set the external service labels similar to add labels to pods, there was no way to do it. 

#### Special notes for your reviewer:
The solution implemented is the same as for adding annotations at install time.

#### Checklist

- [ x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by kortatu** [comment]
Do I need to do something about this `pull-charts-e2e Expected — Waiting for status to be reported`?
Can I do something to avoid this issue to be closed by the bot?

**Comment by benjigoldberg** [comment]
@kortatu this LGTM once you pull the `Chart.yaml` and rebump the version

**Pull request merged**
