### PR TITLE
[stable/sysdig] Fix value in example

### PR DESCRIPTION
**Pull request by meyskens**
The `AgentTags` value did not exist (anymore). Changed this to `sysdig.settings.tags`

#### What this PR does / why we need it:
Fixing a mistake in the documentatiom

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by bencer** [comment]
@meyskens I'd prefer not to bump the version for a doc change, otherwise thanks! good catch!

**Comment by meyskens** [comment]
@bencer no problem, was just following the instructions (and CI failure)

**Comment by sameersbn** [comment]
> @bencer no problem, was just following the instructions (and CI failure)

yea. the CI will not allow us to merge this change with a version update as we treat every chart version immutable. Please bump the version (sorry about this)

**Comment by meyskens** [comment]
@ameersbn done!

**Comment by thiagocaiubi** [comment]
Hello,

I wasn't able to set tags.

Based on the example:

```
helm install --name my-release \
    --set sysdig.accessKey=YOUR-KEY-HERE,sysdig.settings.tags="role:webserver,location:europe" \
    stable/sysdig
```

The error is:

```
Error: failed parsing --set data: key "location:europe" has no value
```

I've tried other formats but couldn't make it.

Any idea?

**Comment by cpanato** [comment]
I will take a look @thiagocaiubi

**Pull request merged**
