### PR TITLE
[incubator/cassandra] Allow change of readiness address

### PR DESCRIPTION
**Pull request by stephenh1991**
Signed-off-by: Steve Hill <stephenh1991@gmail.com>

@KongZ 
@maorfr 

#### What this PR does / why we need it:

This PR is to enable customisation of the readiness address to support clusters that run over public IP addresses.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by KongZ** [comment]
The readiness is used for testing node inside Pod. Why you want to probe another Cassandra node outside the cluster?

**Comment by stephenh1991** [comment]
@KongZ Thanks for taking a look at this!

The reason I added the PR is if you run Cassandra using a public IP for the broadcast address, we use `GossipingPropertyFileSnitch` between multiple DC's in different AWS regions and to connect to those clusters we use the public EIP of the instance. So when the node joins an existing cluster it will be identified by it's `CASSANDRA_BROADCAST_ADDRESS` as you can see below:

```
Datacenter: DC11
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
DN  54.210.84.57    71.96 MB   256          100.0%            8e5b26b1-8851-46bf-b8aa-a59c9b8cacf1  RA1
DN  54.173.142.176  80.1 MB    256          100.0%            afd02af2-a9d5-4567-8b0b-157c4e8d066b  RA4
Datacenter: DC12
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
DN  54.251.181.216  48.93 MB   256          41.6%             0f4e7feb-7985-478f-9a4f-f9f7a7c53d6d  RA2
DN  54.169.32.177   92.22 MB   256          61.1%             c6005057-92dd-48be-aae4-03d9857e6ba2  RA1
UN  34.254.176.213  3.38 MB    256          55.1%             29ab4fb4-aa6e-46b4-a9b1-deb42372f9a5  RAC2
DN  54.251.147.119  46.85 MB   256          42.2%             d4f2a6ef-a1dd-4066-b320-9b64bee4f238  RA2
```

**Comment by stephenh1991** [comment]
@KongZ is this ok to merge now?

**Comment by KongZ** [comment]
@stephenh1991 there is a conflict on Chart.yaml that need to resolve.

**Comment by stephenh1991** [comment]
@KongZ sorry didn't see that when I last looked, should be resolved now.

**Comment by stephenh1991** [comment]
@KongZ do I need to do anything else to get this merged?

**Comment by KongZ** [comment]
@stephenh1991 not sure why previous didn't work.

**Pull request merged**
