### PR TITLE
[stable/jenkins] add existingSecret for admin credentials

### PR DESCRIPTION
**Pull request by cgroschupp**
#### What this PR does / why we need it:
Allow to use an existing secret for the admin credentials

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by torstenwalter — COMMENTED** [review]
This looks good to me. Can you rebase it on master and bump the version number?

**Comment by cgroschupp** [comment]
@torstenwalter done

**Comment by torstenwalter** [comment]
@cgroschupp Thank you for this contribution!

**Pull request merged**
