### PR TITLE
[stable/prometheus-operator] add missing relabeling values to the README and remove a duplicate entry

### PR DESCRIPTION
**Pull request by crandles**
#### What this PR does / why we need it:
Adds more relabelings to the prometheus-operator and fixes a few items in the README.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by crandles** [comment]
Forgot how to resign the commit. All set now.

**Comment by legal90** [comment]
@crandles Oops. It seems you accidentally committed the artifact (`stable/coredns-1.1.0.tgz`) :)

**Comment by vsliouniaev** [comment]
/lgtm cancel
/hold
@crandles could you please remove the binary file you accidentally added?

**Comment by crandles** [comment]
will do

**Comment by crandles** [comment]
Updated to resolve a conflict.

**Pull request merged**
