### PR TITLE
[stable/minio] Bugfix #9515: fix _helpers.tpl to generate the correct…

### PR DESCRIPTION
**Pull request by wlan0**
… fullname

Fixes: https://github.com/helm/charts/issues/9515

### CODE REVIEW

**Comment by wlan0** [comment]
/assign @obedmr 
/assign @davidkarlsen 

Please review

**Comment by obedmr** [comment]
hi @wlan0, it's putting back the issue that was fixed on #8349. Below a full execution. The thing is that you're adding the `name` which is the chart name as far I remember. 

```
(.venv) box ➜  minio git:(pr9611)  helm install .
NAME:   tan-crab
LAST DEPLOYED: Thu Nov 29 14:55:11 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                            READY  STATUS   RESTARTS  AGE
tan-crab-minio-995fcf5fc-xd94j  0/1    Pending  0         0s

==> v1/Secret

NAME            AGE
tan-crab-minio  0s

==> v1/ConfigMap
tan-crab-minio  0s

==> v1/PersistentVolumeClaim
tan-crab-minio  0s

==> v1/Service
tan-crab-minio  0s

==> v1beta2/Deployment
tan-crab-minio  0s


NOTES:

Minio can be accessed via port 9000 on the following DNS name from within your cluster:
tan-crab-minio-svc.default.svc.cluster.local

To access Minio from localhost, run the below commands:

  1. export POD_NAME=$(kubectl get pods --namespace default -l "release=tan-crab-minio" -o jsonpath="{.items[0].metadata.name}")

  2. kubectl port-forward $POD_NAME 9000 --namespace default

Read more about port forwarding here: http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/

You can now access Minio server on http://localhost:9000. Follow the below steps to connect to Minio server with mc client:

  1. Download the Minio mc client - https://docs.minio.io/docs/minio-client-quickstart-guide

  2. mc config host add tan-crab-minio-local http://localhost:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY S3v4

  3. mc ls tan-crab-minio-local

Alternately, you can use your browser or the Minio SDK to access the server - https://docs.minio.io/categories/17



(.venv) box ➜  minio git:(pr9611)  export POD_NAME=$(kubectl get pods --namespace default -l "release=tan-crab-minio" -o jsonpath="{.items[0].metadata.name}")
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
(.venv) box ➜  minio git:(pr9611)
(.venv) box ➜  minio git:(pr9611)
(.venv) box ➜  minio git:(pr9611)  export POD_NAME=$(kubectl get pods --namespace default -l "release=tan-crab" -o jsonpath="{.items[0].metadata.name}")
(.venv) box ➜  minio git:(pr9611)
(.venv) box ➜  minio git:(pr9611)  echo $POD_NAME
tan-crab-minio-995fcf5fc-xd94j
(.venv) box ➜  minio git:(pr9611)
```

**Comment by wlan0** [comment]
Hello @obedmr 

The error is originating from the pod not being ready. 

```
RESOURCES:
==> v1/Pod(related)
NAME                            READY  STATUS   RESTARTS  AGE
tan-crab-minio-995fcf5fc-xd94j  0/1    Pending  0         0s
```

Have you tried running `export POD_NAME=$(kubectl get pods --namespace default -l "release=tan-crab-minio" -o jsonpath="{.items[0].metadata.name}")` command after the STATUS is `Ready`?

**Comment by obedmr** [comment]
mm, my pod appears as ready and running.

```
(.venv) box ➜  minio git:(pr9611)  kubectl get pods | grep moldy-ostrich
moldy-ostrich-minio-768c85f557-fq5hp   1/1       Running   0          50s
(.venv) box ➜  minio git:(pr9611)
(.venv) box ➜  minio git:(pr9611)
(.venv) box ➜  minio git:(pr9611)   export POD_NAME=$(kubectl get pods --namespace default -l "release=moldy-ostrich-minio" -o jsonpath="{.items[0].metadata.name}")
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
```

**Comment by wlan0** [comment]
@obedmr Thanks for taking the time to test this. Your original fix was correct. I mistook the Issue reported in here: https://github.com/helm/charts/issues/9515 and believed that naming convention was a standard, rather than just a practice. Closing this PR

**Pull request closed without merging**
