### PR TITLE
 Add logging-section to InfluxDB configmap and values 

### PR DESCRIPTION
**Pull request by giddel**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by jackzampolin** [comment]
Gets a 👍 from me!

**Comment by giddel** [comment]
@davidkarlsen  @jackzampolin  
What are the next steps here ... when the PR will get merged?

**Comment by giddel** [comment]
@mattfarina @davidkarlsen 
What are the next steps here ... when the PR will get merged?

**Comment by giddel** [comment]
@mattfarina @davidkarlsen @jackzampolin 
What are the next steps here ... when the PR will get merged?

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
