### PR TITLE
[stable/nginx-ingress] Reverting PR 10849

### PR DESCRIPTION
**Pull request by harshal-shah**
Signed-off-by: Harshal Shah <harshal2623@gmail.com>

#### What this PR does / why we need it:
This PR reverts #10849 
We had tested this 10849 with `--force` and it worked for us but this can be a production issue where loadbalancers can get recreated.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10849 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by Miouge1** [comment]
I can confirm what @monotek wrote here: https://github.com/helm/charts/pull/10849#issuecomment-458889534

#10849 broke existing releases:
> Error: UPGRADE FAILED: Service "nginx-ingress-controller-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Service "nginx-ingress-controller-stats" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Service "nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable

Let's revert it ASAP.

**Comment by oldskool** [comment]
This revert causes the original issue mentioned in #7933 to resurface when trying to upgrade the chart to version 1.2.3:

```
~ $ helm ls|grep nginx-ingress
project-nginx-ingress                   	8       	Thu Jan 31 10:51:14 2019	FAILED  	nginx-ingress-1.2.3	0.22.0     	project       
```

```
Failed to upgrade chart
rpc error: code = Unknown desc = Service \"project-nginx-ingress-controller\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable
```

**Comment by monotek** [comment]
use --force or uninstall & install again. 
I think there is now way for an update now when you already have installed the first broken version.

**Comment by Miouge1** [comment]
Since nginx-ingress is stateless a `helm del --purge <release name> && helm install` should unlock your situation as long as you pass it the same values.

**Comment by oldskool** [comment]
Thanks guys, doing a `helm upgrade --force` took some trial and error, but eventually did the trick. 👍

**Comment by harshal-shah** [comment]
Please just remember if this is done on Production instances, the loadbalancer will get recreated and so you can see some blips in connectivity until the DNS is updated with new LoadBalancer IP.

**Comment by dperetti** [comment]
@harshal-shah not everyone has DNS that auto-updates to the new loadbalancer. Even when they do, this causes serious downtime.
This should not happen in a "stable" branch. Anything that's related to external connectivity should be more carefully tested.

**Comment by ianks** [comment]
This whole situation is a nightmare. There is no clear non-breaking upgrade path and early adopters of helm are now stuck on a dated version of nginx-ingress. 👎🏼👎🏼

**Comment by Chili-Man** [comment]
This PR does more then just revert PR 10849; in [PR 10849](https://github.com/helm/charts/pull/10849) only the following 3 service resources are updated:

* stable/nginx-ingress/templates/controller-metrics-service.yaml
* stable/nginx-ingress/templates/controller-stats-service.yaml
* stable/nginx-ingress/templates/default-backend-service.yaml

However, this pull request (#10993) reverts the 3 above plus adds an extra update to another service:

* stable/nginx-ingress/templates/controller-metrics-service.yaml
* stable/nginx-ingress/templates/controller-stats-service.yaml
* stable/nginx-ingress/templates/default-backend-service.yaml

* stable/nginx-ingress/templates/controller-service.yaml   <---- This one should not have been changed, which is causing the upgrade problems 

I'll submit to undo that change

**Pull request merged**
