### PR TITLE
[stable/prometheus-node-exporter] removed errant space

### PR DESCRIPTION
**Pull request by branttaylor**
#### What this PR does / why we need it:
removed an errant space. uncommenting this line leaves a space that will cause the values.yaml to fail to apply correctly.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@branttaylor Please fix the DCO signing and bump the chart patch version.

**Comment by branttaylor** [comment]
@davidkarlsen done. sorry about that, i'm new to this.

**Pull request merged**
