### PR TITLE
[stable/consul] Use provided GossipKey if it exists.

### PR DESCRIPTION
**Pull request by jaredbischof**
**What this PR does / why we need it**: Currently, the provided GossipKey in values.yaml never gets used. This update uses the provided GossipKey if it exists.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by paulczar** [comment]
This is a feature change (albiet minor) so should probably be a minor bump to the version rather than a patch.    otherwise lgtm.

/ok-to-test

**Comment by jaredbischof** [comment]
I actually thought of this as a patch rather than a feature change simply because the current README.md file lists GossipKey as a parameter when in fact, setting that parameter currently does nothing without this commit.

**Comment by jaredbischof** [comment]
Can this move forward?

**Comment by svyotov** [comment]
@jaredbischof I am having the same issue. I would like to point out though that if you are doing this implementation, in my opinion it would be better to move `GossipKey` to `Gossip.Key` to be consistent with `Gossip.Encryption` and `Gossip.Enabled` and to update README.md to actually reflect those changes as those configurations are either missing or invalid there as far as I can see.

**Comment by svyotov** [comment]
This will also close : https://github.com/helm/charts/issues/7104

**Pull request closed without merging**
