### PR TITLE
[stable/stackdriver-exporter] Correct servicemonitor name

### PR DESCRIPTION
**Pull request by charlieegan3**
Fixes typo from https://github.com/helm/charts/pull/16372

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by charlieegan3** [comment]
@apenney might you be able to :heavy_check_mark: this? Hopefully a quick one :pray:

**Review by apenney — APPROVED** [review]

**Comment by charlieegan3** [comment]
Thanks, I'm guessing I also need some helm team blessings... @maorfr might you be able help here again?

**Pull request merged**
