### PR TITLE
[stable/nfs-server-provisioner] Upgrade nfs-provisioner to v2.3.0

### PR DESCRIPTION
**Pull request by lurraca**
No
#### What this PR does / why we need it:
 
It upgrades the version of nfs-provisioner from v2.2.2 to v2.3.0. **v2.3.0** contains valuable features including one that fixes the *'stale file handle'* issue on certain environment dealing with persistent disks. 

* https://github.com/kubernetes-incubator/external-storage/issues/1212
* https://github.com/kubernetes-incubator/external-storage/pull/1214

#### Which issue this PR fixes
There are no open issue in this repo related to this PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by xrow** [comment]
Hi,

I think this commit is missing the ports in https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/templates/service.yaml. Maybe.

I git this error:

E0131 22:38:04.407784       1 controller.go:908] error syncing claim "4f34df36-447a-11ea-9fd5-00259056a256": failed to provision volume with StorageClass "standard": error getting NFS server IP for volume: service SERVICE_NAME=nfs-nfs-server-provisioner is not valid; check that it has for ports map[{111 TCP}:true {111 UDP}:true {662 TCP}:true {662 UDP}:true {875 TCP}:true {875 UDP}:true {2049 TCP}:true {2049 UDP}:true {20048 TCP}:true {20048 UDP}:true {32803 TCP}:true {32803 UDP}:true] exactly one endpoint, this pod's IP POD_IP=10.128.0.91

**Comment by naseemkullah** [comment]
Thanks @xrow , this should help https://github.com/helm/charts/pull/19260

**Comment by naseemkullah** [comment]
Hi @lurraca could you please update the README values section with version 2.3.0?

**Pull request merged**
