### PR TITLE
[stable/redis-ha] feat: implement RBAC

### PR DESCRIPTION
**Pull request by SweetOps**
#### What this PR does / why we need it:
* necessary to have possibility to use RBAC
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ssalaues** [comment]
@SweetOps Thank you for making these additions! #11815 just merged so you will need to rebase however otherwise it lgtm

**Comment by SweetOps** [comment]
@ssalaues , waiting for your `lgtm` ^^

**Pull request merged**
