### PR TITLE
maintenance: chart release 0.5.4

### PR DESCRIPTION
**Pull request by sameersbn**
- update to `bitnami/mariadb:10.1.19-r2`
  + MariaDB package to version `10.1.19`

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
FYI saw this in the event logs when installing.

```
  1m		1m	1	{kubelet ip-10-0-11-226.us-west-2.compute.internal}	spec.containers{handy-clownfish-mariadb}	Warning	Unhealthy	Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!
```

**Comment by lachie83** [comment]
LGTM

**Comment by sameersbn** [comment]
> FYI saw this in the event logs when installing.

Thanks for pointing it out @lachie83. It's actually the readiness probe attempting a connection before the pod is in ready state. This is expected behavior. Pretty normal stuff.

**Pull request merged**
