### PR TITLE
[stable/selenium]upgrade to latest selenium version

### PR DESCRIPTION
**Pull request by manoj9788**
upgraded to the latest Selenium 3.4.0 version

### CODE REVIEW

**Comment by manoj9788** [comment]
CLA signed

**Comment by prydonius** [comment]
@manoj9788 looks like the CLA isn't matching, can you check the commit author email?

**Comment by flah00** [comment]
LGTM

**Comment by manoj9788** [comment]
I hope the CLA should be fine now..

**Comment by manoj9788** [comment]
ping @prydonius

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
thanks @manoj9788, sorry for the delay

**Comment by manoj9788** [comment]
Thanks @prydonius :)

**Pull request merged**
