### PR TITLE
[stable][airflow] Allow usage of existing secrets for postgres and redis

### PR DESCRIPTION
**Pull request by bnutt**
#### What this PR does / why we need it:

Adds the ability to specify your own predefined secret to configure the connection credentials to both postgresql and redis.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gsemet — CHANGES_REQUESTED** [review]
Look great. Can you add a description of this key in the readme (in the big table, and also in a dedicated section to give an example)?

**Comment by bnutt** [comment]
> Look great. Can you add a description of this key in the readme (in the big table, and also in a dedicated section to give an example)?

Added!

**Comment by gsemet** [comment]
/lgtm

Thanks !

**Pull request merged**
