### PR TITLE
[stable/unifi] Invalid link in chart sources

### PR DESCRIPTION
**Pull request by Jonher937**
#### What this PR does / why we need it:
There was a invalid link in sources, this commit fixes the link.

#### Checklist
- [x] DCO signed
- [x] Version bumped

#### Maintainers
@billimek 

Signed-off-by: Jonathan Herlin <jonte@jherlin.se>

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by billimek** [comment]
I think the bot that handles this is broken right now with the github outage - will need to wait to make any progress on this PR until GitHub is healthy again.

**Comment by billimek** [comment]
Yeah you need to bump the chart version with even a documentation change like this.  Just a bump to `0.1.11` should work.

**Comment by Jonher937** [comment]
I realised 😞 
It's in https://github.com/helm/charts/pull/8639/commits/f8474df84e934d4966d4ac0e16c3c9b3866706b9 so it should pass the tests now unless I missed something else.

**Pull request merged**
