### PR TITLE
[stable/prometheus-operator] fix bug in configmap-dashboards.yaml

### PR DESCRIPTION
**Pull request by arielb135**
fixing bug can't evaluate field Release in type []uint8 - reason is because we're in a loop - it was missed

#### What this PR does / why we need it:
It's not possible to deploy with grafana dashboards enabled, as the installation throws "can't evaluate field Release in type []uint8 - reason is because we're in a loop - it was missed"

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by arielb135** [comment]
Should i bump up the version for such a small change?

**Comment by vsliouniaev** [comment]
/ok-to-test
@arielb135 could you please fix the sign-off?

**Comment by arielb135** [comment]
> /ok-to-test
> @arielb135 could you please fix the sign-off?

Hi, i have major issues with my laptop, I thought i added the comment on the commit through the web interface, any other way of doing so?

**Comment by zanhsieh** [comment]
@arielb135 
Check this: https://github.com/helm/charts/pull/18188/checks?check_run_id=269776146

**Pull request closed without merging**
