### PR TITLE
[stable/verdaccio]: Document pull policy correctly

### PR DESCRIPTION
**Pull request by ercanucan**
**What this PR does / why we need it**:

This MRs fixes the README documentation regarding pull policy.
The default behavior of this chart's pull policy is IfNotPresent, regardless of what the image tag is.

### CODE REVIEW

**Comment by ercanucan** [comment]
Signed cnfc-cla

**Comment by ercanucan** [comment]
@seanknox @viglesiasce Would be great to get your feedback on this.

**Comment by etiennetremel** [comment]
If you use an image with tag latest (which is btw not recommended), you should set the pullPolicy to Always as follow:
```
$ helm install --name my-release \
    --set image.pullPolicy=Always \
    stable/verdaccio
```

**Comment by ercanucan** [comment]
@etiennetremel Thank you very much for the fast response! Yes, I understand overriding the `pullPolicy` via the command-line.

The use-case we had (using verdaccio-gitlab) was something like the following:
```
helm install --name my-release \
    --set image.repository=...../verdaccio-gitlab --set image.tag=latest \
    stable/verdaccio
```

In this case, the image tag is overwritten correctly. However, the `pullPolicy` is still enforced as `ifNotPresent`, which does not conform with expected behavior of kubernetes, right? In the current case, the user needs to remember to also override the `pullPolicy` whenever he wants to use the image `latest`.

That's why I thought it might make sense not to enforce it here in the chart and let the underlying kubernetes infrastructure take care of the rest.
What do you think?

**Comment by etiennetremel** [comment]
I'm a bit skeptics about this change since you should let the user choose what they want to do.
Let's see what the approvers suggest. FYI, the _imagePullPolicy_ parameter is created by default during chart bootstrap `helm create my-chart`.

Default Kubernetes behavior is described here: https://kubernetes.io/docs/concepts/containers/images/#updating-images

**Comment by ercanucan** [comment]
@etiennetremel thanks, yes, I am aware of the Kubernetes behavior :-) I had already included the link you provided in my commit message. :-)

I just raised this up because I found that the verdaccio helm chart does not conform to that expected behavior. The README also says it should behave this way but it does not. So if you decide not to take this in, an update to the README would be nice:
https://github.com/helm/charts/blob/master/stable/verdaccio/README.md#configuration

**Comment by etiennetremel** [comment]
Ha right, README is misleading, `IfNotPresent` should be default behavior. Thanks for pointing this out.

**Comment by ercanucan** [comment]
@etiennetremel you are welcome, thanks for your feedback :-)

**Comment by dlouzan** [comment]
@etiennetremel If you guys have corrected this in the README, I guess this can be closed.

**Comment by etiennetremel** [comment]
Maybe we can make the README.md adjustment in this PR since it is open?

**Comment by dlouzan** [comment]
Oh, ok, I thought that it had already been added. I would wait for Erçan then, he should be back in a couple of days and he's the owner of the PR & fork :-)

**Comment by ercanucan** [comment]
@etiennetremel @dlouzan @bufferoverflow: Updated the README accordingly and kept the existing pull policy behaviour as you suggested.

Please have a look and let me know what you think.

**Comment by ercanucan** [comment]
@mattfarina Fixed the merge conflict. Please take a look.

**Pull request merged**
