### PR TITLE
[stable/prometheus-cloudwatch-exporter] - Add annotations to serviceAccounts for EKS IAM

### PR DESCRIPTION
**Pull request by bouge**
Add service account annotation and add service account to deployment.

Signed-off-by: Louis Bougeard <lbougeard@and.digital>

#### What this PR does / why we need it:
This PR allows for annotations to serviceAccounts to allow for IAM roles for service accounts in EKS rather than having to pass in tokens, instead using a web identity token file.

This relates to: https://groups.google.com/forum/#!topic/prometheus-users/mhn1Z3yG-XA

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bouge** [comment]
@asherf the test seems to be failing (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/20162/pull-charts-e2e/1217470903982493697/), but I don't believe it's related to the changes that the PR makes, do you have any ideas?

**Comment by bouge** [comment]
@asherf  not ideal, is this because I've bumped the chart version? Happy to spend some time investigating but not really sure what the tests are doing...

**Comment by torstenwalter** [comment]
If you show the hidden lines then it reveals the error:

` Error creating: pods "prometheus-cloudwatch-exporter-gtjlvmcooy-5797678ccc-" is forbidden: error looking up service account udwatch-exporter-presubmit-20162-1217499848031342594-gtjlvmcooy/prometheus-cloudwatch-exporter: serviceaccount "prometheus-cloudwatch-exporter" not found   10m   
`

You added this condition[` {{- if .Values.serviceAccount.create }} `which might be the cause.

**Comment by bouge** [comment]
@torstenwalter I've moved the logic for that... still failing.

How can I see the logic for the test or run it locally to try and get it to pass?

**Comment by torstenwalter** [comment]
The logs show which commands are executed.

**Comment by bouge** [comment]
@torstenwalter all the tests are now passing, would you be able to review this PR please?

**Comment by bouge** [comment]
@gianrubio @torstenwalter - Any update on this, please?

**Pull request merged**
