### PR TITLE
[stable/nextcloud] Add php-fpm+nginx support

### PR DESCRIPTION
**Pull request by ishioni**
#### What this PR does / why we need it:
Running nextcloud on apache is slower than via nginx. This PR allows one to use nginx instead of apache2

#### Special notes for your reviewer:
I am not sure how to properly go about making sure the user knows/is informed that he should use a different image than the default if selecting nginx.enabled, short of taking control of the image.tag field. 

Also, this is my first PR, so forgive any mistakes, comments very much welcome

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ishioni** [comment]
I have bumped the chart version to 1.9.0

**Comment by ishioni** [comment]
@billimek I am unsure what to do about the conflict merge, which triggers the error in e2e tests

**Review by billimek — APPROVED** [review]

**Pull request merged**
