### PR TITLE
Fix broken table in README.md for PostgreSQL chart

### PR DESCRIPTION
**Pull request by GabrielNicolasAvellaneda**
Signed-off-by: Gabriel Nicolas Avellaneda <avellaneda.gabriel@gmail.com>

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, unfortunately, we need to do some formalisms also in minor changes like this. Before continuing, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by GabrielNicolasAvellaneda** [comment]
@carrodher Chart version updated. Thanks.-

**Pull request merged**
