### PR TITLE
add MongoDB chart

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
ICYMI we already have a chart in incubator for mongo with replicasets. We should rename that chart to mongo-replicaset and set the chart description properly before merging this.

**Comment by prydonius** [comment]
@viglesiasce agreed, we should rename it adding a -petset, -statefulset or -clustered postfix in this PR. Any particular preference to which it should be? `-clustered` is more general, could there be a usecase for someone wanting a clustered using multiple deployments vs. StatefulSet?

**Comment by viglesiasce** [comment]
The feature in mongo that it is using is literally called [replicaset](https://docs.mongodb.com/manual/core/replica-set-members/) so we should use that as the suffix.

**Comment by prydonius** [comment]
@viglesiasce Oh right, yeah. I'm a little hesitant that this will confuse others like it confused me though, but I guess an end-user will be thinking more about MongoDB than Kubernetes resource types.

**Comment by sameersbn** [comment]
PR has been updated to rename the existing `mongodb` chart to `mongodb-replicaset`

**Comment by viglesiasce** [comment]
@sameersbn can you fix the conflict?

**Comment by sameersbn** [comment]
have rebased the PR to resolve the conflicts and also updated the docker image version used in the chart.

**Comment by sameersbn** [comment]
ping!

**Comment by viglesiasce** [comment]
I tested this and found that the new mongodb chart works well but the old one is failing to install due to the following:

```
installing config scripts into /work-dir
installing mongod.conf into /config
chown: invalid user: 'mongodb:mongodb'
```

I'll get an issue open and assign to @foxish.

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@prydonius @lachie83 LGTM

**Pull request merged**
