### PR TITLE
[mongodb-replicaset] Restructure and apply best practices

### PR DESCRIPTION
**Pull request by unguiculus**
* Split up to one yaml file per resource
* Fix old petset references
* Improve persistence configuration
* Config entries start with a lower-case letter
* Enhance configuration
* Drop component annotation
* Improve test.sh
* No default resoure requests/limits
* Add _helpers.tpl

### CODE REVIEW

**Comment by lachie83** [comment]
@unguiculus can you confirm if this can be closed in favor of #428?

**Comment by lachie83** [comment]
@foxish do you have any comments to add here?

**Comment by unguiculus** [comment]
I was not aware of #428. I would not close this in favor of #428. My PR does a lot more. Plus, I thought it'd be good to fix things before moving it to stable. If #428 is to be merged, I'd be happy to rework this change to build upon it.

**Comment by lachie83** [comment]
@unguiculus Looks like #428 is ready to be merge. Can you chime in on that PR so we can make a decision on how to proceed.

**Comment by zonorti** [comment]
@unguiculus @lachie83 this is a good one, please merge it before #428 and I would update my pull request

**Comment by unguiculus** [comment]
@lachie83 @iMelnik Very cool. Thanks.

**Comment by InAnimaTe** [comment]
Any updates on this moving forward? btw, Thanks for the hard work on getting making replica sets easier for everyone!

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Pull request merged**
