### PR TITLE
[incubator/zookeeper] Makes persistence fully configurable

### PR DESCRIPTION
**Pull request by fedenusy**
### Motivation
We create Zookeeper StatefulSets during CI on AWS.

Due to the high frequency with which we were creating volumes, EBS wound up getting stuck very frequently.

This change allows us to sidestep the issue by relying on kubelet host volumes.

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for the PR. I'd like you to slightly adjust it following our best practices. See #1869.

**Comment by fedenusy** [comment]
@unguiculus does this look ok?

**Pull request merged**
