### PR TITLE
[incubator/sparkoperator] Support podAnnotations

### PR DESCRIPTION
**Pull request by SamClinckspoor**
Signed-off-by: Sam Clinckspoor <sam.clinckspoor@gmail.com>

#### What this PR does / why we need it: 
Support adding custom annotations to the operator pod

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
@SamClinckspoor Please fix the merge conflicts and bump the version number to 0.3.0.

**Comment by SamClinckspoor** [comment]
@yuchaoran2011 done

**Review by yuchaoran2011 — APPROVED** [review]

**Pull request merged**
