### PR TITLE
[stable/redis-ha] Fix missing redis ha announce services

### LINKED ISSUE #18190: [stable/redis-ha]: announce services not created
**Describe the bug**
After installing a redis-ha app with helm, the config-init container crashes and the redis-ha-server-0 pod never starts.

To my understanding, it is caused by the absence of the -announce services, which I believe should be created by Helm.

**Version of Helm and Kubernetes**:
Helm v2.15.0
Kubernetes 1.16.1
Cilium CNI v1.6.1

**Which chart**:
stable/redis-ha

**What happened**:
The test-redis-ha-server-0 pod is stuck in status Init:CrashLoopBackOff

The config-init container complains:
```
Initializing config..
Could not connect to Redis at test-redis-ha:26379: Name does not resolve
/readonly-config/init.sh: line 84: Could not resolve the announce ip for this pod: not found
```
The announce service does not exist, and therefore the code mentionned in https://github.com/helm/charts/issues/16911#issuecomment-529280098 for example cannot succeed.

**What you expected to happen**:
Helm to install announce services and the redis pods to start and run successfully.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --dry-run --debug --name redis stable/redis-ha > redis-debug
```
Open redis-debug, note that no "announce" service are present in the manifest.

### PR DESCRIPTION
**Pull request by PaulFarver**
#### What this PR does / why we need it:
This fixes an issue, where announce services and SENTINEL_ID's were not properly created, when .Values.replicas was a number, as the values.yaml suggests
This happened because the int function returned 0 when used on a value that was of the json.Number type

#### Which issue this PR fixes
  - fixes #18190 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by PaulFarver** [comment]
After fiddling with it a little, I have come to these conclusions:

- Casting a json.number to an integer with the "int" function in gotpl results in a 0
- Casting a string to an integer is possible with the "int" function in gotpl
- Using the "until" function requires an integer as an argument  

This is why the fix requires us to cast the replicas to a string before converting them to an integer, that can be used in the until funciton.
I must admit that this is not a pretty solution.

**Comment by zanhsieh** [comment]
@PaulFarver 
Would you bump the chart version to latest please? Thank you.

**Comment by PaulFarver** [comment]
@zanhsieh 
It should be fixed now.

**Pull request merged**
