### PR TITLE
[stable/kubernetes-dashboard] Add ingress service

### PR DESCRIPTION
**Pull request by mwinters0**
In order to have an AWS ELB target an Ingress, you must have a Service with an app selector of the ingress controller.  This work enabled my use case for adding basic-auth via the Ingress:

```yaml
httpPort: 443
ingress:
  enabled: true
  hosts:
  - dashboard.mydomain.com
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: myteam-user-basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    ingress.kubernetes.io/class: "nginx"
  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789:certificate/foo-123-bar-456
      dns.alpha.kubernetes.io/external: dashboard.mydomain.com
    loadBalancerSourceRanges:
    - 1.2.3.4/27 # My Office
```

Also, some Readme cleanup to match the style of other charts.

### CODE REVIEW

**Comment by mwinters0** [comment]
cc-ing the maintainer @kfox1111 .  Newer PR #2435 slightly overlaps.

**Comment by kfox1111** [comment]
I've got some other changes that may have overlap too:
https://github.com/kfox1111/charts/tree/oidc/stable/kubernetes-dashboard
Rough usage document here:
https://github.com/kfox1111/charts/blob/oidc/stable/kubernetes-dashboard/MiniKubeOIDC.md
I've been letting it simmer for a bit. Was going to post it this week.

It lets you setup authentication via oidc so it is no longer insecure.

Setting up a password on an ingress does not fix the main security issue with the dashboard which allows any user to be cluster-admin that has access to the internal k8s network by talking to the dashboard.

This change set blocks all unauthenticated access.

It does not have bits in it yet for dealing with how to securely get the dashboard out through an ingress though... I was hoping https://github.com/kubernetes/ingress-nginx/issues/1461 would get implemented quickly and you could use a self signed cert between the ingress and the kube-dashboard proxy.

Any thoughts?

**Comment by mwinters0** [comment]
I only have a few moments right now, but my primary thought is that you hit the nail on the head - the focus of this work is to enable access to the Ingress, via a LoadBalancer Service.  Authentication isn't really a concern in this work, and perhaps my including basic-auth in my example was a distraction.

That said, the OIDC/DEX work looks interesting and I'm happy to modify anything if it eases that merge.

**Comment by kfox1111** [comment]
Can the appSelector be added to the existing svc rather then adding a second one?

Also, I don't see anything breaking in this change, so could you use version number 0.4.1 instead of 0.5.0?

**Comment by mwinters0** [comment]
Version has been changed to 0.4.1.

This is the only way that I'm aware of to get an nginx Ingress controller in front of the application in AWS today.  The nginx Ingress controller currently does not create ELBs for you, so you must use a LoadBalancer Service targeting the Ingress controller, which then targets your app.

There are other Ingress controllers in the works to make things behave more as you expect, but those have not yet reached 1.0 release and probably won't have full feature parity with the nginx controller.

**Comment by mgoodness** [comment]
This chart already creates a Service. Why not add the necessary fields to that rather than creating a new one?

**Comment by mwinters0** [comment]
The Nginx Ingress docs [state](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/README.md#aws) that this is accomplished with a [separate service](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-l4.yaml).  If there is another way to have a traffic flow of ELB -> Nginx Ingress -> Dashboard Service, I'm not aware of it.  I'm also not aware of any other Ingress solution which supports the same authentication feature set as the Nginx Ingress controller (eg, client certs, or basic-auth).

**Comment by mgoodness** [comment]
I'm afraid you're misunderstanding those docs. Creating a Service for the nginx Ingress controller is only required once, when you install the controller itself. All traffic to controller Pods then routes through that Service. If you use the `nginx-ingress` chart in this repo, the necessary [Service](https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml) is created for you.

All this chart needs to provide is its own Service & Ingress resource, which it does.

**Comment by mwinters0** [comment]
@mgoodness I think you assume I only want to have one ELB for all Ingress to my cluster.  In fact, I want to have one ELB dedicated to the Dashboard, with certs and loadBalancerSourceRanges which are specific to Dashboard access.

**Comment by kfox1111** [comment]
OH, I think I see what your trying to do.

So, why use an ingress at all then? You could just make the existing service type LoadBalancer? It would skip the nginx-ingress entirely but still allowing the 1-1 loadbalancer/dashboard relationship.

**Comment by mwinters0** [comment]
@kfox1111 Because I want to use TLS with client certs (or at least TLS with basic-auth, as my example above shows.)  Neither of these modes is supported by ELBs, which is what a LoadBalancer Service creates.  The only way I've found to get these features is through an Nginx Ingress, which requires its own LoadBalancer Service.

**Comment by kfox1111** [comment]
The issue though with that, is its insecure inside the cluster. any compromised container could reach out to the dashboard and issue commands without any authentication as cluster-admin.

Thats why I've been working on the dex/kubernets-dashboard integration. basic auth/ldap/github/google/etc based auth works, and any container contacting the dashboard directly can't access anything as the new kubernetes-dashboard 1.7 default rbac rules are very restrictive.

Could you try out the dex/kubernetes-dashboard minikube instructions and see if that kind of arrangement would solve your use case?

**Comment by viglesiasce** [comment]
Marking stale.

**Pull request closed without merging**
