### PR TITLE
Add a default issuer when the email is provided

### PR DESCRIPTION
**Pull request by pierreozoux**
I believe we should simplify the user experience when it comes to managing certs in kubernetes.

With this PR, the user is only requested to give their email to get started to provision certs!

### CODE REVIEW

**Comment by unguiculus** [comment]
The cert-manager chart is managed upstream and then pushed over to the charts repo. Please open a PR there.

https://github.com/jetstack/cert-manager

cc @munnerz

**Comment by munnerz** [comment]
We've had some discussion on implementing this feature over in https://github.com/jetstack/cert-manager/issues/289

As far as I'm aware, unless something has changed in Helm, this chart won't work on initial install due to the way Helm validates whether resource api versions are valid (we can't define a CRD and an instance of that same CRD within the same chart and install all at once).

I would love to be wrong! Currently, the thinking is to provide a second chart to make it clear they need to be installed one after the other.

**Comment by unguiculus** [comment]
@munnerz Here's a nice trick that achieves this: https://github.com/kubernetes/charts/pull/3795

**Comment by pierreozoux** [comment]
Thanks @unguiculus for the hint, I'll see if I have and maybe PR upstream then.

BTW, I'm also working on a PR for rook CRDs (upstream) and hitting the same problem:
https://github.com/kubernetes/helm/issues/3610

If you have some ideas to add to this, I think it would be nice to solve it the helm way (which I have no idea yet what it could be).

**Pull request closed without merging**
