### PR TITLE
[stable/rabbitmq] Improvements

### PR DESCRIPTION
**Pull request by lohmag**
#### What this PR does / why we need it:
Adds ability to rebalance master for queues when number of replicas >1
ref: https://www.rabbitmq.com/rabbitmq-queues.8.html#rebalance

Add improvements to ServiceMonitor

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution. Can you apply the same changes in _stable/rabbitmq/values.yaml_ to the _stable/rabbitmq/values-production.yaml_?

**Comment by lohmag** [comment]
> Thanks for your contribution. Can you apply the same changes in _stable/rabbitmq/values.yaml_ to the _stable/rabbitmq/values-production.yaml_?

done

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
