### PR TITLE
[stable/graylog] Bump graylog image version, 3.1.2-1

### LINKED ISSUE #17318: [stable/graylog] Upgrade image 3.1.0
When to update graylog to 3.1.0 with chart ?

### LINKED ISSUE #17553: [stable/graylog] Image repository documentation out of sync with values.yaml
**Describe the bug**
README.md does not describe structure of values.yaml file properly.

https://github.com/helm/charts/blob/master/stable/graylog/values.yaml#L32-L34 shows that `repository` field is a child of `image` and README.md says that repository should be set using `graylog.image`.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/graylog

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by circa10a**
#### Is this a new chart

No

#### What this PR does / why we need it:

- Update chart to use most up to date graylog image.
- Fix incorrect documentation. Usage of existing documentation will result in unexpected behavior.

#### Which issue this PR fixes

 - fixes #17553
 - fixes #17318

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by KongZ** [comment]
@circa10a sorry, please bump the version again. There is another PR was merged before you.

**Comment by circa10a** [comment]
@KongZ Bumped

**Pull request merged**
