### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mgrachev**

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by billimek** [comment]
@mgrachev thanks for this PR.  Can you [address the DCO action](https://github.com/helm/charts/pull/8418/checks?check_run_id=23628609) to move this forward?

**Comment by davidkarlsen** [comment]
@mgrachev can you please sign off your commits and bump the chart version? TIA
/assign

**Comment by mgrachev** [comment]
Done.

**Comment by alexvicegrab** [comment]
Would be much better to have separate PRs for each of the charts, so we can resolve separate issues.

There seems to be an issue with the Redis and Keycloak charts as well.

**Review by juan131 — CHANGES_REQUESTED** [review]
You need to do a different PR for each chart. Check: https://github.com/helm/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart

**Comment by mgrachev** [comment]
https://github.com/helm/charts/pull/8632
https://github.com/helm/charts/pull/8679
https://github.com/helm/charts/pull/8680
https://github.com/helm/charts/pull/8695
https://github.com/helm/charts/pull/8696
https://github.com/helm/charts/pull/8699
https://github.com/helm/charts/pull/8700
https://github.com/helm/charts/pull/8701
https://github.com/helm/charts/pull/8702
https://github.com/helm/charts/pull/8703
https://github.com/helm/charts/pull/8704

**Pull request closed without merging**
