### PR TITLE
[stable/nextcloud] Upgrade to 18.0.3 (Nextcloud Hub), upgrade deps, cron fixes

### PR DESCRIPTION
**Pull request by pfuhrmann**
Signed-off-by: Patrik Fuhrmann <fuhrmann.patrik@gmail.com>

#### What this PR does / why we need it:
- upgrade app version to 18.0.3 (Nextcloud Hub)
- upgrading dependencies
- launch cron every 5 minutes
- document installation using Helm 3

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pfuhrmann** [comment]
Not sure why `lint-charts` failed because the dependencies are NOT out of date.

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading mariadb from repo https://charts.bitnami.com/bitnami
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

**Comment by pfuhrmann** [comment]
@chrisingenhaag @billimek 

I really do not know what to do here. Tests are failing due to requirements out of date, even though this seems to be not the case:

`requirements.yaml`
```
dependencies:
- name: mariadb
  version: ~7.3.19
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: redis
  version: ~10.5.7
  repository: https://kubernetes-charts.storage.googleapis.com/
```

`requirements.lock`
```
dependencies:
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 7.3.19
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 10.5.7
digest: sha256:3543c6d40124bd4803178516fcc7c3233d6cf73e174b3d13ca81cdaed37897c9
generated: "2020-04-18T21:42:01.397500726+02:00"
```

**Comment by khoutz182** [comment]
@pfuhrmann no idea if this helps or not, just getting into helm/k8s. anyway it may have something to do with the new bitnami repo not being added to the test environment, although i think i saw tests passing in another pr with a bitnami repo. anyway, running the following passed the linting locally

```shell
➜  charts git:(nextcloud-upgrades) ✗ git pull quay.io/helmpack/chart-testing      
➜  charts git:(nextcloud-upgrades) ✗ git remote -vvv
k8s	https://github.com/helm/charts (fetch)
k8s	https://github.com/helm/charts (push)
origin	https://github.com/pfuhrmann/charts.git (fetch)
origin	https://github.com/pfuhrmann/charts.git (push)
➜  charts git:(nextcloud-upgrades) ✗ docker run -it --rm --name ct --volume $(pwd):/data quay.io/helmpack/chart-testing sh -c "cd /data && helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo add kubernetes-charts https://kubernetes-charts.storage.googleapis.com/ && ct lint --config /data/test/ct.yaml --chart-dirs stable,incubator"

...
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 nextcloud => (version: "1.10.0", path: "stable/nextcloud")
------------------------------------------------------------------------------------------------------------------------

"incubator" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "kubernetes-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading mariadb from repo https://charts.bitnami.com/bitnami
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
Linting chart 'nextcloud => (version: "1.10.0", path: "stable/nextcloud")'
Checking chart 'nextcloud => (version: "1.10.0", path: "stable/nextcloud")' for a version bump...
Old chart version: 1.9.2
New chart version: 1.10.0
Chart version ok.
Validating /data/stable/nextcloud/Chart.yaml...
Validation success! 👍
Validating maintainers...
==> Linting stable/nextcloud

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ nextcloud => (version: "1.10.0", path: "stable/nextcloud")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

without the `helm repo add bitnami...` it would fail the same way as the ci output. hope this helps, delete this if i'm getting in the way.

**Comment by pfuhrmann** [comment]
@khoutz182 Thanks a lot!

It indeed seems like there is no intention supporting extra repositories anymore. Which kind of makes sense, given the deprecation status of `helm/charts`.

I think this would be a good time to set up a separate repository for this chart? @chrisingenhaag what do you think?

It would be great if we could get it into Nextcloud's own account (`nextcloud/helm` for example).

**Pull request closed without merging**
