### PR TITLE
Added authentication in collector and query for Cassandra storage

### PR DESCRIPTION
**Pull request by harpratap**
Signed-off-by: Harpratap Singh Layal <harry.harpratap@gmail.com>

#### What this PR does / why we need it:
When using an external cassandra storage with authentication the username and password weren't being added to collector and query deployments. Now it adds them as environment variables.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I know we should ideally put these in secrets but Elasticsearch was already using configmaps. So just used the same logic for Cassandra.
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by harpratap** [comment]
@cpanato Can you please take a look at this?

**Comment by harpratap** [comment]
bump

**Comment by mattfarina** [comment]
cc @dvonthenen @mikelorant @pavelnikolov

**Comment by pavelnikolov** [comment]
LGTM

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
