### PR TITLE
upgrade for security fixes - in_cluster was removed as it is smartly …

### PR DESCRIPTION
**Pull request by sstarcher**
…determined now

### CODE REVIEW

**Comment by sstarcher** [comment]
@rendhalver does this look good to you?

**Comment by zanhsieh** [comment]
@rendhalver
@sstarcher
Please take a look this PR. Thank you.

**Comment by sstarcher** [comment]
@zanhsieh I would prefer not to approve my own PR, but I can.

**Comment by sstarcher** [comment]
Yep, that's what I thought :)

**Review by czuares — APPROVED** [review]
Tested and verified locally.

**Comment by zanhsieh** [comment]
@sstarcher 
Pinged @rendhalver  in kubernetes slack.

**Comment by rendhalver** [comment]
@zansieh what will happen on early version of the image?
Say if someone uses this Chart and had the image tag set to 7.0.1?

**Comment by zanhsieh** [comment]
@rendhalver 
I think it should be ok since those users could always overwrite values.yaml themselves by `--set image.tag=7.0.1` during deploying helm chart.

**Comment by rendhalver** [comment]
@zanhsieh @sstarcher We can't assume it will be okay. We need to make sure so we don't break peoples deploys.

**Comment by sstarcher** [comment]
@rendhalver how about we bump the major version due to backwards incompatibility?   We have not in the past put in version-specific logic we have instead moved forward and bumped a major version.

**Comment by rendhalver** [comment]
@sstarcher If people don't know what has changed it will have the same effect as just removing the value. We also need to allow people to use a newer version of the Chart with an older image.
When did the auto-discovery change happen in the filebeat image?

**Comment by sstarcher** [comment]
We don't support filebeat 3.x.x.  This chart has never guaranteed support for any version except for the one that is specified in this chart.  The change was made in 7.4.0.  

https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-7.4.0.html

**Comment by rendhalver** [comment]
> We don't support filebeat 3.x.x. This chart has never guaranteed support for any version except for the one that is specified in this chart. The change was made in 7.4.0.

That isn't specified anywhere in the README.

So if someone has their image pinned to an older version this version of the Chart will break their deployment?

**Comment by sstarcher** [comment]
So you just want a update to the Readme?

**Comment by rendhalver** [comment]
> So you just want a update to the Readme?

Yes. Otherwise people will have no idea their systems may break if they use this.

**Comment by sstarcher** [comment]
Sounds, great I'll make that addition.

**Comment by sstarcher** [comment]
@rendhalver updated let me know what you think

**Comment by sstarcher** [comment]
@rendhalver ping

**Comment by sstarcher** [comment]
@rendhalver review please

**Review by cpanato — APPROVED** [review]
/lgtm

thanks for adding the readme

**Comment by cpanato** [comment]
@rendhalver PTAL

**Comment by sstarcher** [comment]
Just need the do-not-merge label dropped

**Comment by sstarcher** [comment]
Just need a review

**Comment by sstarcher** [comment]
@rendhalver any chance on a final review or should I close the ticket?

**Pull request merged**
