### PR TITLE
Prometheus: provide options to use existing PVCs

### PR DESCRIPTION
**Pull request by mgoodness**
* Added `persistentVolume.existingClaim` options for alertmanager & server
* If defined, use those named PVCs. Else create new ones using template
* Documentation

I've not been able to use the Prometheus chart in stage/prod yet, because I want to preserve metrics stored on existing PVs. This addition allows an operator to specify existing PVCs that should be used
instead of having the release create new ones.

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Review by viglesiasce — CHANGES_REQUESTED** [review]
Needs a chart version bump.

**Comment by mgoodness** [comment]
Bumped!

**Review by viglesiasce — APPROVED** [review]

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Pull request merged**
