### PR TITLE
fix url which not exist anymore

### PR DESCRIPTION
**Pull request by liwjGhostcloud**
fix url which can not use anymore

### CODE REVIEW

**Comment by timstoop** [comment]
Every change on a Chart requires the version in Chart.yaml to be bumped as well, even if it's a documentation change. Please bump the patch level of the version in Chart.yaml as well.

**Comment by liwjGhostcloud** [comment]
i have changed the version of Chart.yaml @timstoop

**Comment by unguiculus** [comment]
cc @gianrubio

**Comment by sameersbn** [comment]
https://prometheus.io/docs/instrumenting/exporters/ links to the same URL as this PR suggests

/approve

**Pull request merged**
