### PR TITLE
Add support for deployment tolerations and update helpers

### PR DESCRIPTION
**Pull request by shaunmansell**
Signed-off-by: Shaun Mansell <shaun.s.mansell@gmail.com>

**What this PR does / why we need it**:
1) Adds support for specifying tolerations in the deployment resource.
A common use-case for node affinity is to set node labels **and** tolerations to work together, so we want support for both in the deployment to cover the common variations of node affinity.

2) Updates the helper template functions to include the updated fullname and chart values.
If you used a release name that was the same as the chart name under the previous fullname template value, you'd end up with a fullname value that duplicate the same content. In this case, the fullname would end up as "elasticsearch-exporter-elasticsearch-exporter". The new helper function ensures this duplication doesn't happen any more.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by shaunmansell** [comment]
@svenmueller

**Review by svenmueller — APPROVED** [review]
Thx for the PR! The changes are straight forward and look good to me 👍

**Comment by svenmueller** [comment]
@shaunmansell can you merge changes from master branch to this branch (to resolve the conflicts)?

**Comment by shaunmansell** [comment]
@svenmueller conflicts have been sorted and the version bumped to account for previous increase from the pod annotation changes

**Comment by svenmueller** [comment]
Thx @shaunmansell !

**Pull request merged**
