### PR TITLE
[stable/prometheus] Prometheus server globals parameterization (rebased)

### PR DESCRIPTION
**Pull request by marksto**
Reincarnation of #3308. Sorry, had accidentally committed with the working email and didn't notice.

### CODE REVIEW

**Comment by jpds** [comment]
I actually find this change to a bit of a regression - it's nice to have toggles for these settings, but now, how do I set `external_labels:`[1] without hitting:

```
parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:\n  line 6: field global already set in type config.plain"
```

Or any other global config option that prometheus introduces in the future? This brought down one of my prometheus servers because I helm upgraded it without realizing that I had a different `scrape_internal` set.

[1]: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by amnk** [comment]
The same here..... Those changes should at least bump major version of the chart.

**Pull request merged**
