### PR TITLE
[incubator/drone] Bump version to last stable (0.8.5)

### PR DESCRIPTION
**Pull request by mavimo**
**What this PR does / why we need it**:

Update drone to last stable release ([v0.8.5](https://github.com/drone/drone/releases/tag/v0.8.5) released on 2018-03-29T17:40:54Z)

**Special notes for your reviewer**:

None

### CODE REVIEW

**Comment by mavimo** [comment]
/assign @mattfarina 

cc/ @christian-roggia

**Comment by christian-roggia** [comment]
I will check the new version within the next few days on my cluster, but normally there shouldn't be any problem in bumping the minor version since there are no breaking changes. Thank you for your PR!

**Comment by christian-roggia** [comment]
Everything is fine, this PR is ready to be merged.

**Pull request merged**
