### PR TITLE
Add Gluster Chart for helm deployment.

### PR DESCRIPTION
**Pull request by humblec**
GlusterFS ( www.gluster.org)  is a scalable network filesystem. Using common off-the-shelf hardware, you can create large, distributed storage solutions for media streaming, data analysis, and other data- and bandwidth-intensive tasks. GlusterFS is free and open source software and completely user space filesystem. This chart enable to run gluster containers in a kube setup.

Signed-off-by: hchiramm <hchiramm@redhat.com>

### CODE REVIEW

**Comment by hunter** [comment]
This chart doesn't seem to do much with cluster/brick configuration or integration with Kubernetes. Are there plans to add Heketi and a StorageClass?

**Comment by humblec** [comment]
@hunter Yes, thats the plan. However I dont want to bring it in the first version. We can work on it, please let me know if you would like to collaborate on this effort. Most welcome 👍

**Comment by obnoxxx** [comment]
There seems to be some connection to : https://github.com/gluster/gluster-kubernetes/issues/39

**Comment by rimusz** [comment]
@humblec for the start you should update the `readme` what can be accomplished with this chart, 
single GFS instance or cluster, does it have persistence or not.

**Comment by humblec** [comment]
@rimusz Sure. Thanks !

**Comment by viglesiasce** [comment]
I would prefer to have this as a stateful set rather than a single non PV backed Pod. A single node gluster does not make much sense and this appears to be the minimum possible to get a single node going.

**Comment by viglesiasce** [comment]
Marking as stale. @humblec please update within the next week if you are still interested in getting this in.

**Comment by humblec** [comment]
@viglesiasce I would like to sort this out asap. I am kind of exploring the possibilites of statefulset deployment.

**Comment by prydonius** [comment]
@humblec I'm closing this since it's been stale for 2 weeks, but please do resubmit when you're able to pick this up again :)

**Pull request closed without merging**
