### PR TITLE
[incubator/cassandra] Add maver1ck to OWNERS

### PR DESCRIPTION
**Pull request by maver1ck**
*Is this a request for help?:*

I'd like to be added as an Owner. This was confirmed by @KongZ by email.
There is a lot of work in Cassandra chart and 5 of my PR and many others are waiting for merge.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Review by KongZ — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@maver1ck please bump the chart version. TIA

**Comment by maver1ck** [comment]
@davidkarlsen 
Done.

**Pull request merged**
