### PR TITLE
[stable/airflow] Fix git-sync configmap #21970

### LINKED ISSUE #21970: [stable/airflow] git-sync.sh - error during 'rm';  suggested fix included.
**Describe the bug**
I installed this chart with persistence enabled, with NFS auto provisioner. I also enabled git-sync
But it failed with 'device busy'.

Issue comes from the way the dags directory is cleaned up before cloning.

in file ```templates/configmap-git-clone.yaml``` , the cleaning up in ```git-sync.sh``` should be done the same way as in git-clone.sh script, that is, instead of ```rm -rf $DIR```, with a ``` if [ -d $DIR ..] rm -rf $(find . -mindepth  ...) ; fi```

After doing that, I got no longer the error. I suspect the error comes from the fact that the dags directory is an actual mount point (and also reused by other pods) so that's why the removal failed.

**Version of Helm and Kubernetes**:
No helm, used something else. 
Kubernetes server v1.13.0

**Which chart**:
stable/airflow

**What happened**:
see above

**What you expected to happen**:
git-sync to work ok.

**How to reproduce it** (as minimally and precisely as possible):
enable persistence and dags ini tcontainer and dags gitSync.

**Anything else we need to know**:
Suggested fix is included above.

### PR DESCRIPTION
**Pull request by yehlo**
Fix #21970

Using only `rm -rf $DIR` would lead to an error with the resource being marked as busy. 
Using the same method used in git-clone.sh fixes the issue. 

Signed-off-by: Joshua Leuenberger joshua.leuenberger@bedag.ch

#### What this PR does / why we need it:
Fixes an issue with the git-clone configmap. 

#### Which issue this PR fixes
  - fixes #21970

#### Special notes for your reviewer:
@gsemet 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yehlo** [comment]
/assign @gsemet 

Sorry if I missed something, first time commiter :/.

**Comment by yehlo** [comment]
Hi @gsemet 
Had to rebump version after signing my commit.

**Review by gsemet — APPROVED** [review]
/lgtm

**Pull request merged**
