### PR TITLE
[stable/airflow] Allow extra ConfigMaps and Secrets to be added as Environment Variables

### PR DESCRIPTION
**Pull request by toneill818**
#### What this PR does / why we need it:
Currently if we want to include environment variables from config maps we must map each item in the `extraEnv`. This PR provides a way to import an entire configMap or secrets saving time.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

##### Maintainers: 
@gsemet 
@thesuperzapper

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@toneill818 the `stable/airflow` helm chart has moved

Can you please raise your PR in the new repo?
https://github.com/airflow-helm/charts/tree/main/charts/airflow

**Comment by gsemet** [comment]
@thesuperzapper I though we did not had to move out of helm/charts ?

**Comment by thesuperzapper** [comment]
@gsemet see the conversation here: https://github.com/helm/charts/issues/21103#issuecomment-717865262

It was just really confusing messaging, we do have to move.

**Pull request closed without merging**
