### PR TITLE
[stable/velero] add support for cross-subscription backups/restore

### PR DESCRIPTION
**Pull request by boxcee**
## What this PR does / why we need it:
Adds some fields to the VolumeSnapshotLocation and BackupStorageLocation to enable backups and snapshots cross subscription in Azure.

#### Which issue this PR fixes
vmware-tanzu/velero#1646

#### Special notes for your reviewer:
Depends on vmware-tanzu/velero#1895 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by prydonius — COMMENTED** [review]
Thanks @boxcee, I'm just a little concerned about setting the chart to use the beta by default. Could we hold this change back until 1.2.0 is released?

**Comment by prydonius** [comment]
cc @nrb

**Comment by boxcee** [comment]
@prydonius, yes, sure. I just wanted to keep my PR up-to-date.

**Comment by prydonius** [comment]
@boxcee #18492 updates the docs for v1.2.0, so we'll merge that first when 1.2.0 is released and this can be rebased on top of that.

**Comment by nrb** [comment]
I have moved this to our new repository with https://github.com/vmware-tanzu/helm-charts/pull/22

**Comment by davidkarlsen** [comment]
This chart has been deprecated and moved to a new repo: https://github.com/helm/charts/blob/master/stable/velero/README.md

**Pull request closed without merging**
