### PR TITLE
Check presence of values in README.md

### PR DESCRIPTION
**Pull request by Miouge1**
**What this PR does / why we need it**:

Many charts are missing variables in their README.md. It's easy to forget to document variables when creating them. An automatic process to detect those cases would be nice.

**Special notes for your reviewer**:

I tested this locally with the stable/mysql chart.

I submit this as a [WIP] PR to get early feedback and see if I should continue in that direction... or not :)

### CODE REVIEW

**Comment by timstoop** [comment]
This would be a very nice addition!

**Comment by Miouge1** [comment]
I remove the WIP tag. I would love to see better sync between charts and the README.md doc :)

/assign @linki

**Comment by unguiculus** [comment]
Thanks for this. While it would be nice to have, it doesn't cover everything, e. g. using `$` or in a different scope using `with` or `range`.

BTW, testing is currently being refactored and moved to a separate repo.

https://github.com/kubernetes-helm/chart-testing/pull/1

**Comment by Miouge1** [comment]
@unguiculus you are right it doesn't cover all cases, but it's still better than nothing.

If we can detect 75% automatically, it's already an improvement.

**Comment by unguiculus** [comment]
Closing this since chart testing has been moved to https://github.com/kubernetes-helm/chart-testing

**Pull request closed without merging**
