### PR TITLE
[stable/prometheus] updated all prometheus docker images to latest versions

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### What this PR does / why we need it:
* updates prometheus to v2.19.0
* updates alert amnager to v0.21.0
* updates node exporter to v1.0.1
* updates push gateway to v1.2.0
* uses kube-state-metrics 2.8.* chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by monotek** [comment]
/test pull-charts-e2e

test fails because node exporter can't be installed :/

```
I0617 21:17:22.005]   Normal   NotTriggerScaleUp  5m (x27 over 10m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match node selector
I0617 21:17:22.005]   Warning  FailedScheduling   5s (x12 over 10m)  default-scheduler   0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.
```

**Review by zanhsieh — APPROVED** [review]

**Comment by monotek** [comment]
@zanhsieh & @gianrubio 
do you have any idea whats the ci problem?
have you seen this before?

**Comment by zanhsieh** [comment]
@monotek 
I saw the similar problem on the PR merged before this. Some helm member just fixed it few days ago. It seems coming back.

**Comment by monotek** [comment]
/retest

Do your remember the name?
I'll ask in the helm slack channel tomorrow.

**Comment by zanhsieh** [comment]
@monotek 
See here:
https://github.com/helm/charts/pull/22801
https://github.com/helm/charts/pull/22725

**Comment by monotek** [comment]
/retest

@scottrigby could you have a look at the ci infra please?

**Comment by monotek** [comment]
@cpanato 

Thanks a lot :)

**Pull request merged**
