### PR TITLE
[stable/prometheus-operator] Incorporate upstream changes in clusterrole.yaml

### PR DESCRIPTION
**Pull request by anothertobi**
#### What this PR does / why we need it:
This change brings the change from https://github.com/coreos/prometheus-operator/pull/2319 to the Helm chart.
Also adding myself as a maintainer since we @vshn are using the operator and therefore I will keep maintaining this chart.

#### Which issue this PR fixes
This PR fixes the following issue:
`failed: synchronizing governing service failed: updating service object failed: services "alertmanager-operated" is forbidden: cannot set an ownerRef on a resource you can't delete: no RBAC policy matched, <nil>`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@anothertobi I'm happy with the changes to the chart.

As for adding you as a maintainer, are you interested in actively maintaining the chart, answering github issues and doing PR reviews? If you're looking for a way to more quickly merge changes into this repo, being a maintainer would still require someone else to approve the changes.

**Comment by anothertobi** [comment]
Thanks for the update @vsliouniaev 👍 

Yes, I'm interested in actively maintaining this chart (including GitHub issues / PR reviews) 😃

**Comment by anothertobi** [comment]
Bumped the chart version

**Pull request merged**
