### PR TITLE
[stable/consul] Make cluster name a variable

### PR DESCRIPTION
**Pull request by elafarge**
People don't necessarily use "local" as a cluster name. Since this
value was hardcoded in the cluster bootstraping script, the Chart
couldn't be installed on such cluster.

This commit introduces a "ClusterName" variable defaulting to "local"
for that parameter.

Note
----

Since the different consul node are living in the same namespace, just getting 
rid of the "cluster.xxx"part in the domain name might be even more relevant. 
What do you think ?

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
Thanks @elafarge. I think this is good to go. Can you please bump the chart version?

**Comment by lachie83** [comment]
Need to dig into why pods aren't making it to running state.

**Comment by elafarge** [comment]
Mmmmh I don't know. Pods appear as expected (and join together to form a consul cluster as well). However there is a 30-ish second delay between each pod creation.

Eventually, I went for the "don't specify any cluster name" solution, which doesn't add any "Value" and I don't think people would be willing to spread Consul clusters across Kubernetes clusters anyways. 
This commit removes code instead of adding a template variable, which feels better to me. Let me know if you have any objections :)

It also works on my cluster (I just tested), same spawning time (1m30-2m for the tree nodes) and... the CI still fails. I'll try to reproduce what the Jenkins script does on my machine and figure out what's going on. Could you provide me with the build script by any chance ?

**Comment by elafarge** [comment]
Mmmh, it really works like a charm on my end... After a dozen seconds (the time for the PVC to be bound) the first Pod's state transitions from "Pending" to "Running".

I'm running Kubernetes 1.6.1 on top of AWS. Maybe your tests are running on a 1.5 cluster ? From what I recall, I don't think there are any differences in the way DNS namespacing is handled (nor in the Pod's `/etc/resolv.conf`) between these versions.

Could the Tenkins failure be linked to the StatefulSet's PersistentVolumeClaims not being honored somehow ? I have no clue about the environment these tests are running in, I'm just trying to guess. 

PVCs are not removed on `helm delete` (which is a good thing :) ). Maybe you're not deleting them in your testing environment and reached a cloud provider specific limit ?

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@k8s-bot e2e test this

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
Thanks for the info @elafarge, just checked and the PVCs are not getting bound because the chart is requesting a beta storage class named 'default' by default. We need to either:

- conditionally switch between alpha and beta storage class annotation for 1.4 and 1.5 support (and default to alpha)
- leave out the beta annotation/storageClassName option by default, adding it in if a storage class is defined for 1.6+ support

The former will make it pass in the CI, the latter will require us to update the test cluster to 1.6 - however if we can verify that the chart works well in 1.6 I would prefer to go for the latter as we should upgrade to 1.6 soon anyway.

**Comment by elafarge** [comment]
Wouldn't it be possible to test both versions ? I think Jenkins now has a feature somewhat equivalent to Travis CI's build matrix (I never tried it though) that would allow us to run the same test suite against multiple Kubernetes versions.

This way, if we running on 1.5 we'll use a user-defined storage class as `StorageClass`'s value in our chart and just use the default one provided by Kubernetes for 1.6+ versions (and yeah, we'll also have to handle the `alpha/beta` status in the annotation)p

Also I don't think it's relevant to test the `1.4` version: `kind: StatefulSet` is hardcoded in the Chart. In 1.4 `StatefulSet`s were still called `PetSet`s :)

Would all that make sense ?

**Comment by prydonius** [comment]
We haven't really settled on what versions we want to officially support (though we're working towards deciding this and making it transparent), I would say that for now we can err on the side of supporting 1.5 and 1.6 by conditionally switching between alpha and beta storage class annotations. I think we should do this in a separate PR though. @lachie83 want to go ahead and merge this despite the test failure?

**Comment by lachie83** [comment]
Let's get this merged first -- #973

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
LGTM

**Pull request merged**
