### PR TITLE
[stable/redis] Fix: broken netpol

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### What this PR does / why we need it:

It seems like as of `7.0.0` the netpol is broken (noticed when `allowExternal: false` did not behave as expected after upgrade)

This PR is an attempt to remediate this regression, while accommodating `sentinel` port. 

Review and suggestions are encouraged, thanks.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @carrodher @desaintmartin @juan131 @prydonius @sameersbn @tompizmor @javsalgar

**Comment by naseemkullah** [comment]
https://github.com/helm/charts/blob/43abdbaacd94af8c0764d7ce3dd02b991fd976d4/stable/redis/templates/networkpolicy.yaml#L33
should probably be nested in a `- ports:` somewhere

**Comment by javsalgar** [comment]
Could you explain a bit in more detail the issue so we can understand what the PR fixes?

**Comment by naseemkullah** [comment]
My pleasure.

So the 3 things that I am trying to tackle:

1. As per [documentation](https://kubernetes.io/docs/concepts/services-networking/network-policies/), the `from` is not nested in `ports` but rather at the same level: e.g. `.spec.ingress.from` and `.spec.ingress.ports`

2. As such we need to ensure that both  ` - port: {{ .Values.sentinel.port }}` and   ` - port: 9121` are well nested within `.spec.ingress.ports`

3. Finally, we should add an if statement around ` - port: {{ .Values.sentinel.port }}` as it is not necessarily enabled.

I'm not 100% sure on my implementation of this though so would appreciate your review!

**Comment by javsalgar** [comment]
Thank you. It looks good to me. @juan131 can you trigger the testing phase?

**Pull request merged**
