### PR TITLE
Update minio chart to latest release and config format

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by so0k** [comment]
@NitishT can you update the NOTES to point to the correct service name?

**Comment by so0k** [comment]
note:
https://github.com/NitishT/charts/blob/master/stable/minio/templates/minio_svc.yaml#L4

vs

https://github.com/NitishT/charts/blob/master/stable/minio/templates/NOTES.txt#L3

they don't match

**Comment by nitisht** [comment]
Nice catch @so0k . Updated the NOTES file.

**Pull request merged**
