### PR TITLE
[stable/rabbitmq-ha] - Use the serviceAccount name from the template helper for consistency …

### PR DESCRIPTION
**Pull request by gdmello**
**What this PR does / why we need it**:
Fixes a broken cluster - the nodes fail on startup when attempting to connect to the kubernetes api server - `Failed to get nodes from k8s - (403)`.

Fixes https://github.com/kubernetes/charts/issues/6206

@etiennetremel @coreypobrien - Please review! thank you!

### CODE REVIEW

**Review by etiennetremel — APPROVED** [review]

**Comment by gdmello** [comment]
/assign @scottrigby
As suggested by @k8s-ci-robot

**Comment by gdmello** [comment]
thank you @unguiculus!

**Pull request merged**
