### PR TITLE
[stable/cluster-autoscaler] Update rolebinding.yaml

### PR DESCRIPTION
**Pull request by victoru**
This is a RoleBinding resource, not ClusterRoleBinding

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@victoru Bump the chart version

**Comment by dhilipkumars** [comment]
@victoru the pods aint comming up, could you please fix the CI error?
```
I0816 14:20:05.325] cluster-2620-aws-cluster-autoscaler-1091296286-fbpbj   0/1       CrashLoopBackOff   4         3m

```

**Comment by victoru** [comment]
hmm, how was #1587 able to pass this check? It's failing right now because `autoscalingGroups` is empty by default.

```
F0816 14:32:29.329918       1 cloud_provider_builder.go:91] Failed to create AWS cloud provider: Failed to build an aws cloud provider: Either node group specs or node group auto discovery spec must be specified
```

**Comment by dhilipkumars** [comment]
```
RoleBinding and ClusterRoleBinding
A role binding grants the permissions defined in a role to a user or set of users. 
It holds a list of subjects (users, groups, or service accounts), and a reference to 
the role being granted. Permissions can be granted within a namespace with a 
RoleBinding, or cluster-wide with a ClusterRoleBinding
```
My first question is why do we want a cluster-autoscalar to be confined within a namespace?

**Comment by mgoodness** [comment]
> My first question is why do you want a cluster-autoscalar to be confined within a namespace?

There is a separate ClusterRole/Binding for granting access to cluster-wide resources. This Role/Binding only grants permission to create & update the cluster-autoscaler's ConfigMap.

**Comment by mgoodness** [comment]
@victoru thanks for catching this so quickly. Sloppy on my part.

**Comment by mgoodness** [comment]
This chart will just be another one we have to excuse from tests. It's (currently) AWS-only, and requires user-provided values for successful deployment.

**Comment by dhilipkumars** [comment]
Thanks Okay now understood.  Did not check the other `yaml`
/unassign

**Pull request merged**
