### PR TITLE
[stable/prometheus] Use ksm chart for ksm

### PR DESCRIPTION
**Pull request by naseemkullah**
By leveraging the [ksm chart](https://github.com/helm/charts/tree/master/stable/kube-state-metrics) we are deduplicating community effort.

cc @zanhsieh 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by evalizhangli** [comment]
I use helm 2.14.3. when I run the command "helm upgrade --install prometheus ", It will return error "UPGRADE FAILED
Error: UPGRADE FAILED: Service "prometheus-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable". What should I do after you    commit this chang?

**Comment by naseemkullah** [comment]
Hi @evalizhangli , try deleting the ksm service and deployment then reinstalling the prometheus chart. Let me know if that works.

**Comment by naseemkullah** [comment]
@evalizhangli with helm 2 you can also try adding the `--force` flag upon upgrade of prometheus.

>       --force=false: Only used when grace-period=0. If true, immediately remove resources from API and bypass graceful deletion. Note that immediate deletion of some resources may result in inconsistency or data loss and requires confirmation.

**Comment by evalizhangli** [comment]
Hi @naseemkullah 
Yes, I deleted the ksm service/deplyment/clusterrole/clusterrolebing,   then  run the "helm upgrade --force install prometheus", It works. Thank you very much~
but I hava another question, I see the new prometheus-kube-state-metrics service appear clusterIP endpoint. but I didn't config it

**Comment by naseemkullah** [comment]
My pleasure @evalizhangli , happy it worked!

This has to do with ksm chart's config:


https://github.com/helm/charts/blob/deb403a4ec7da319da604baaf440929b550f8fe5/stable/kube-state-metrics/values.yaml#L20

https://github.com/helm/charts/blob/deb403a4ec7da319da604baaf440929b550f8fe5/stable/kube-state-metrics/templates/service.yaml#L22

Whereas previously, the prometheus' chart's ksm used a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).

**Pull request merged**
