### PR TITLE
[stable/chartmuseum] Update apiVersion for Kubernetes 1.16 support

### PR DESCRIPTION
**Pull request by alexvolsh**
Signed-off-by: Alex Voloshyn <alex@geeoz.com>

#### What this PR does / why we need it:
apiVersion in the Ingress doesn't support in the Kubernetes 1.16 and above.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jdolitsky** [comment]
@alexvolsh - will this break now on older versions of kubernetes?

We probably want to add something like
```
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

**Comment by alexvolsh** [comment]
@jdolitsky I've added and checked support for older versions.

**Pull request merged**
