### PR TITLE
stable/nginx-ingress fix: pdb selector by component

### PR DESCRIPTION
**Pull request by sermilrod**
#### What this PR does / why we need it:
Fixes PDB object selector

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sermilrod** [comment]
e2e is failing with this message:
```shell
I0327 14:54:30.923] Error linting and installing charts: Error processing charts
I0327 14:54:30.923] ------------------------------------------------------------------------------------------------------------------------
I0327 14:54:30.924]  âœ–ï¸Ž nginx-ingress => (version: "1.34.3", path: "stable/nginx-ingress") > Error waiting for process: exit status 1
I0327 14:54:30.924] ------------------------------------------------------------------------------------------------------------------------
I0327 14:54:31.609] 088f032167ad5d9466526191bc133c00b2ca6d61bd5f84687117683504e4103c
W0327 14:54:31.641] Traceback (most recent call last):
W0327 14:54:31.641]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0327 14:54:31.642]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0327 14:54:31.642]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0327 14:54:31.642]     check(*cmd)
W0327 14:54:31.642]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0327 14:54:31.642]     subprocess.check_call(cmd)
W0327 14:54:31.642]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0327 14:54:31.642]     raise CalledProcessError(retcode, cmd)
W0327 14:54:31.643] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0327 14:54:31.643] Command failed
```
And the test pod looks like it is timing out:
```bash
I0327 14:53:33.975] Events:
I0327 14:53:33.975]   Type     Reason     Age                     From                                             Message
I0327 14:53:33.975]   ----     ------     ----                    ----                                             -------
I0327 14:53:33.976]   Normal   Scheduled  10m                     default-scheduler                                Successfully assigned nginx-ingress-presubmit-21654-1243548539506659328-a1rsdcvbdp/nginx-ingress-a1rsdcvbdp-controller-6mj46 to gke-jenkins-default-pool-51cafeba-0nxp
I0327 14:53:33.976]   Normal   Pulled     8m13s (x2 over 9m53s)   kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Container image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0" already present on machine
I0327 14:53:33.976]   Normal   Created    8m11s (x2 over 9m53s)   kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Created container nginx-ingress-controller
I0327 14:53:33.976]   Normal   Started    8m5s (x2 over 9m24s)    kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Started container nginx-ingress-controller
I0327 14:53:33.976]   Warning  Unhealthy  7m29s (x6 over 8m39s)   kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Liveness probe failed: Get http://10.0.1.168:10254/healthz: dial tcp 10.0.1.168:10254: connect: connection refused
I0327 14:53:33.977]   Normal   Killing    7m12s (x2 over 8m16s)   kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Container nginx-ingress-controller failed liveness probe, will be restarted
I0327 14:53:33.977]   Warning  Unhealthy  6m52s (x2 over 7m2s)    kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Readiness probe failed: HTTP probe failed with statuscode: 500
I0327 14:53:33.977]   Warning  Unhealthy  6m41s (x2 over 7m11s)   kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Readiness probe failed: Get http://10.0.1.168:10254/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0327 14:53:33.977]   Warning  Unhealthy  4m52s (x10 over 8m42s)  kubelet, gke-jenkins-default-pool-51cafeba-0nxp  Readiness probe failed: Get http://10.0.1.168:10254/healthz: dial tcp 10.0.1.168:10254: connect: connection refused
```

```bash
I0327 14:53:34.802] I0327 14:53:24.386824       6 status.go:117] updating status of Ingress rules (remove)
I0327 14:53:34.802] E0327 14:53:24.391610       6 store.go:171] timed out waiting for caches to sync
I0327 14:53:34.803] I0327 14:53:24.459885       6 trace.go:116] Trace[879269065]: "Reflector ListAndWatch" name:k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156 (started: 2020-03-27 14:52:57.621798513 +0000 UTC m=+6.085417520) (total time: 26.769056026s):
I0327 14:53:34.803] Trace[879269065]: [26.769056026s] [26.769056026s] END
I0327 14:53:34.803] E0327 14:53:25.391809       6 store.go:185] timed out waiting for caches to sync
I0327 14:53:34.803] I0327 14:53:25.391943       6 nginx.go:307] Starting NGINX process
```

Is this a CI/CD failure? Can I get some help please?

**Comment by sermilrod** [comment]
@ChiefAlexander @taharah E2E passing and ready. Waiting for your 👍 to go.

**Comment by ChiefAlexander** [comment]
/lgtm

Thank you!

**Pull request merged**
