### PR TITLE
[stable/redis] minimal support for persistence.existingClaim

### PR DESCRIPTION
**Pull request by colthreepv**
**What this PR does / why we need it**:
stable/redis [advertises use of existing PersistentVolumeClaim](https://github.com/kubernetes/charts/tree/master/stable/redis#persistence) but it does not work, as there is no switch inside the templates that look up that value.

**Which issue this PR fixes**:  
I made directly a PR, instead of an Issue + PR.

**Special notes for your reviewer**:  
I am quite a newbie when it comes to Kubernetes/Charts, I tried to keep the changes to a minimum,  so they can be iterated over by more expert contributors.

I am not sure if a contribution requires a test, although I would expedite this PR as the advertised functionality on a **stable** Chart does not work

### CODE REVIEW

**Comment by mattfarina** [comment]
/ok-to-test

@colthreepv Thanks for the pull request. When changes come in they need to increment the chart version. I've done that for you this time.

**Comment by carrodher** [comment]
Hi @colthreepv, thanks for the contribution, it's a good catch.

I can see [CI tests](https://circleci.com/gh/kubernetes/charts/9208?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) failing due to
```
[ERROR] templates/: render error in "redis/templates/redis-master-statefulset.yaml": template: redis/templates/redis-master-statefulset.yaml:121:18: executing "redis/templates/redis-master-statefulset.yaml" at <.Values.persistence....>: can't evaluate field existingClaim in type interface {}
```

According to [`value.yaml`](https://github.com/kubernetes/charts/blob/master/stable/redis/values.yaml):
```
  persistence:
    enabled: true

    ## The path the volume will be mounted at, useful when using different
    ## Redis images.
    path: /bitnami/redis/data

    ## The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services.
    subPath: ""

    ## redis data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessModes:
    - ReadWriteOnce
    size: 8Gi
```
can you add it? Also, we should include it in the [README configuration table](https://github.com/kubernetes/charts/blob/master/stable/redis/README.md#configuration).

**Comment by colthreepv** [comment]
Ok, should be ok now, the e2e test does not break!

Hopefully I will find the time to PR some basic helm tests for this chart

**Pull request merged**
