### PR TITLE
[stable/unifi] bumping docker image to 5.11.47

### PR DESCRIPTION
**Pull request by billimek**
#### What this PR does / why we need it:

* Bumps the unifi docker image to version 5.11.47

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by billimek** [comment]
@mcronce can you take a look?

**Comment by mcronce** [comment]
Well, pending merge conflicts, anyway

**Comment by billimek** [comment]
Looks like the image version was already bumped as part of #18052 so this is no longer necessary.

**Pull request closed without merging**
