### PR TITLE
[stable/grafana] Add required field "apiVersion: v1"

### PR DESCRIPTION
**Pull request by dragon3**
#### What this PR does / why we need it:

The `apiVersion: v1` is required in Chart.yaml, but now Chart.yaml for Grafana doesn't have it.
https://github.com/helm/helm/blob/master/docs/charts.md#the-chartyaml-file

#### Special notes for your reviewer:

I found this while I investigating https://github.com/helm/helm/issues/4699 .
I couldn't install the Grafana helm chart with the error `failed: the server could not find the requested resource`.
I found it seems the error caused by missing `apiVersion`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- ~~Variables are documented in the README.md~~

### CODE REVIEW

**Comment by maorfr** [comment]
Hey @dragon3,

Thanks for contributing!
If you resolve conflicts we can get this merged.

**Comment by dragon3** [comment]
Hi @maorfr 
> If you resolve conflicts we can get this merged.

I just resolved the conflict. Please check it!
THank you!

**Comment by dragon3** [comment]
Ah, lint failed. 
I need to bump version again. I'll do that.

**Comment by dragon3** [comment]
Hi @maorfr 
> I need to bump version again. I'll do that.

It's done. Please check it 🙏

**Pull request merged**
