### PR TITLE
[stable/falco] use version 0.13.0 instead of latest

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
use version 0.13.0 instead of latest

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
looks like it is related with the Kernel in the CI

**Comment by cpanato** [comment]
@unguiculus can you help here? see the comments above

**Comment by davidkarlsen** [comment]
@bencer See https://github.com/helm/helm/blob/master/docs/chart_best_practices/pods.md

**Comment by bencer** [comment]
OK, then we just need a changelog entry for this and happy to merge it :)

**Comment by cpanato** [comment]
@bencer ok, i will do that tomorrow, thanks
we just need to figure out the issue in the CI, looks like it is not happy with the existing kernel version

**Comment by cpanato** [comment]
@bencer @davidkarlsen updated the changelog PTAL

**Pull request merged**
