### PR TITLE
[stable/metricbeat] bump metricbeat, add overrideConfig and overrideModules

### PR DESCRIPTION
**Pull request by kimxogus**
Signed-off-by: Taehyun Kim <kgyoo8232@gmail.com>

#### What this PR does / why we need it:
#12199 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes metricbeat's #12199 issue

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kimxogus** [comment]
Updated as suggested in https://github.com/helm/charts/pull/12202#issuecomment-476923203

**Comment by at-k** [comment]
I understand why this feature is needed, and it is also good idea to align  the behavior of charts to filebeat. 
This PR seems to be working properly on my local environment.

**Pull request merged**
