### PR TITLE
[stable/mariadb] add support for mysql exporter extra args

### PR DESCRIPTION
**Pull request by eddycharly**
Added support for mysql exporter extra arguments to be scraped by prometheus.
See https://github.com/prometheus/mysqld_exporter/

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
Hi @eddycharly ,
Thank you very much for the PR!!!!!
Good job!!

**Comment by eddycharly** [comment]
@miguelaeh thanks, is publishing of the chart automatic ?

**Pull request merged**
