### PR TITLE
[stable/hackmd] Support kubernetes >= 1.16

### PR DESCRIPTION
**Pull request by onokatio**
#### Is this a new chart
No.

#### What this PR does / why we need it:

stable/hackmd uses `extensions/v1beta2`and `extensions/v1beta1` but kubernetes 1.16 deprecates them.
So this PR migrates charts to use  `apps/v1`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by onokatio** [comment]
is it ok to merge?

**Comment by zanhsieh** [comment]
@onokatio 
You need to get a helm chart member to LGTM this PR in order to merge, since there's no owner for this chart. After helm chart member LGTM this chart, would you volunteer to be an owner of this chart? See:

https://github.com/helm/charts/issues/13869

**Comment by onokatio** [comment]
@zanhsieh 

I'm ok to be a volunteer.

**Pull request merged**
