### PR TITLE
[stable/datadog] bump dependency kube-state-metrics 0.2.2

### PR DESCRIPTION
**Pull request by scottrigby**

### CODE REVIEW

**Review by mgoodness — CHANGES_REQUESTED** [review]
No dependency version bump

**Comment by scottrigby** [comment]
@mgoodness Right, I left this PR because `helm dependency update` changed the lock file, so this appeared to be out of date. I was trying to think about what we want to do in these cases, and it seemed to me that we may want to ensure the lock file is updated. Thoughts?

**Comment by scottrigby** [comment]
@mgoodness @prydonius from [Slack](https://kubernetes.slack.com/messages/C6E3XH1ED/convo/C6E3XH1ED-1504564552.000017/?thread_ts=1504564552.000017) it sounds like because the SHA has changed from `helm dep update` then the lock file must have been out of sync before this.

The question now is, should we merge these 3 PRs to level-set the lock file, or just wait until the dependency version has it’s next update?

**Review by mgoodness — APPROVED** [review]

**Pull request merged**
