### PR TITLE
[stable/metricbeat] Add 'extraSecrets' for save private data like *.pem

### PR DESCRIPTION
**Pull request by imcheck**
#### What this PR does / why we need it:
This pr is to add `extraSecrets` attribute into `values.yaml` for save private data.
In my case, I tried to connect to ElasticSearch with ssl/tls communication using CA certificates, I want to save the files into secret instead of passing the certificates through `volumnMounts.hostPath`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by imcheck** [comment]
@mumoshu Hi, I'm waiting for merging this PR.
when could you finish to review this pr?

**Comment by mumoshu** [comment]
@imcheck Thanks for your contribution(and patience) ☺️

**Pull request merged**
