### PR TITLE
[stable/postgresql] Use tpl for extraEnvVarsCM

### PR DESCRIPTION
**Pull request by evili**
Signed-off-by: Evili del Rio <evili.del.rio@gmail.com>

#### What this PR does / why we need it:
Use `tpl` to expand the value of `extraEnvVarsCM` so that the name can vary from release to release when used as a subchart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by javsalgar** [comment]
Please fix the merge issues in the chart

**Comment by javsalgar** [comment]
And thanks for the PR! :)

**Comment by juan131** [comment]
This chart has been deprecated and moeved to https://github.com/bitnami/charts/tree/master/bitnami/postgresql. Every contribution must be moved to the new repository instead.

For more information, see https://github.com/helm/charts/tree/master/stable/postgresql#this-helm-chart-is-deprecated

**Comment by davidkarlsen** [comment]
Chart is deprecated

**Pull request closed without merging**
