### PR TITLE
[incubator/vault] Add priorityClassName for pods and minReadySeconds for deployment

### PR DESCRIPTION
**Pull request by lawliet89**
Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

#### What this PR does / why we need it:
Allows configuring of Pod Priority Classes and `minReadySeconds`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lawliet89** [comment]
Any thoughts on this? This isn't a huge change.

**Comment by lawliet89** [comment]
@mattfarina @davidkarlsen

Sorry for tagging you guys out of the blue. You guys approved PRs related to Vault recently. Can I get _someone_ who has any interest in the Vault chart to look through my PR? It has been weeks.

**Comment by mattfarina** [comment]
@jpds Can you take a look at this?

/ok-to-test

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
