### PR TITLE
[incubator/vault] Change vault api address to use http instead of https

### PR DESCRIPTION
**Pull request by Roman-Galeev**
#### What this PR does / why we need it:

Fixes vault api variable value

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@mckjhd 
Could you bump to latest version and sign DCO please? Thank you.

**Comment by jbialy** [comment]
@mckjhd, good catch! Please resolve conflicts as suggested by @zanhsieh

**Comment by mckjhd** [comment]
@zanhsieh @jbialy done.

**Pull request merged**
