### PR TITLE
[stable/concourse] update to 3.3.2

### PR DESCRIPTION
**Pull request by cmosetick**
- Concourse v3.2.1
- bump version number in chart.yml

### CODE REVIEW

**Comment by shanesveller** [comment]
Is anyone else using this chart? A week or so ago, I found that when upgrading my deployed release to this `3.2.1` image version that even the simplest [Hello World example from the docs](http://concourse.ci/hello-world.html) fails to run, similar to this issue:

https://github.com/concourse/concourse/issues/1230

**Comment by mumoshu** [comment]
Hi @shanesveller, I've tried it myself - seems to work for me on concourse 3.2.1 on k8s on minikube v0.19.
image

Perhaps something is going wrong with the file system of your choice?

**Comment by shanesveller** [comment]
I've made minimal customizations to the released version of the Concourse chart other than setting `imageTag`, username/password, Postgres password, and adding annotations for my ingress controller. However, the upstream issue I linked has some additional developments posted today that suggest it may be related to the kernel in use on my GKE cluster. I'm using Google's Container-Optimized OS with kernel `4.4.35+`.

**Comment by mumoshu** [comment]
Hi @cmosetick, thanks for the PR! 👍
Would you mind updating the version number to 3.3?
It has some nice features like [credentials management and caching](https://concourse.ci/downloads.html).

**Comment by viglesiasce** [comment]
I was unable to get a simple task running:
```
runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/
concourse-work-dir/3.3.2/assets/bin/init\\\" to rootfs \\\"/concourse-work-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd7ea29477f/volume/rootfs\\\" at \\\"/concourse-wo
rk-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd7ea29477f/volume/rootfs/tmp/garden-init\\\" caused \\\"open /concourse-work-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd
7ea29477f/volume/rootfs/tmp/garden-init: permission denied\\\"\""
```

**Comment by mumoshu** [comment]
@viglesiasce Which kind of hosts are you running your k8s cluster managing your concourse on?
I had no problem when running my cluster on minikube as explained in [my prev comment](https://github.com/kubernetes/charts/pull/1365#issuecomment-311860560).

**Comment by mumoshu** [comment]
@viglesiasce Do we have a shared workspace, like hosted Jenkins, to browse the complete configuration and logs of your failed build, or are you just running it locally?

**Comment by viglesiasce** [comment]
I am running on GKE 1.6.6, I ran the following task using `fly execute`:
```
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo blah
```

Full build output:

```
$  fly -t local execute -c /tmp/pipeline.yaml
executing build 1
initializing
Pulling ubuntu@sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4...
sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4: Pulling from library/ubuntu
75c416ea735c: Pulling fs layer
c6ff40b6d658: Pulling fs layer
a7050fc1f338: Pulling fs layer
f0ffb5cf6ba9: Pulling fs layer
be232718519c: Pulling fs layer
f0ffb5cf6ba9: Waiting
be232718519c: Waiting
c6ff40b6d658: Verifying Checksum
c6ff40b6d658: Download complete
a7050fc1f338: Verifying Checksum
a7050fc1f338: Download complete
f0ffb5cf6ba9: Verifying Checksum
f0ffb5cf6ba9: Download complete
be232718519c: Verifying Checksum
be232718519c: Download complete
75c416ea735c: Download complete
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
Digest: sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4
Status: Downloaded newer image for ubuntu@sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4

Successfully pulled ubuntu@sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4.

runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/
concourse-work-dir/3.3.2/assets/bin/init\\\" to rootfs \\\"/concourse-work-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd7ea29477f/volume/rootfs\\\" at \\\"/concourse-wo
rk-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd7ea29477f/volume/rootfs/tmp/garden-init\\\" caused \\\"open /concourse-work-dir/volumes/live/3fc2ca00-a9c1-4ddf-4599-3fd
7ea29477f/volume/rootfs/tmp/garden-init: permission denied\\\"\""

errored
```

Having this chart only work in minikube is not sufficient for getting it merged. 

It looks like the following flag may need to be configurable:
https://github.com/kubernetes/charts/issues/1479

**Comment by mumoshu** [comment]
@viglesiasce Thanks for the clarification. Yes, I agree with you.
Who's going to take initiative on this?
Perhaps should I take this PR over and add #1479 into a newly submitted PR?

**Comment by viglesiasce** [comment]
I'm testing that now will post back with results and the commit adding it if it works.

**Comment by viglesiasce** [comment]
Was not able to get it to work.

```
{"timestamp":"1500346371.038435936","source":"worker","message":"worker.setup.already-done","log_level":1,"data":{"session":"1"}}
{"timestamp":"1500346371.039204597","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"arch
ive","session":"2.1.1"}}
{"timestamp":"1500346371.039284468","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"bosh
-deployment","session":"2.1.2"}}
{"timestamp":"1500346371.039364338","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"bosh
-io-release","session":"2.1.3"}}
{"timestamp":"1500346371.039428949","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"bosh
-io-stemcell","session":"2.1.4"}}
{"timestamp":"1500346371.039475918","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"cf",
"session":"2.1.5"}}
{"timestamp":"1500346371.039535046","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"dock
er-image","session":"2.1.6"}}
{"timestamp":"1500346371.039580822","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"git"
,"session":"2.1.7"}}
{"timestamp":"1500346371.039632082","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"gith
ub-release","session":"2.1.8"}}
{"timestamp":"1500346371.039686441","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"hg",
"session":"2.1.9"}}
{"timestamp":"1500346371.039746523","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"pool
","session":"2.1.10"}}
{"timestamp":"1500346371.039819479","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"s3",
"session":"2.1.11"}}
{"timestamp":"1500346371.039865494","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"semv
er","session":"2.1.12"}}
{"timestamp":"1500346371.039931059","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"time
","session":"2.1.13"}}
{"timestamp":"1500346371.039979458","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"trac
ker","session":"2.1.14"}}
{"timestamp":"1500346371.040045261","source":"worker","message":"worker.garden.extract-resources.extract.already-extracted","log_level":1,"data":{"resource-type":"vagr
ant-cloud","session":"2.1.15"}}
failed to create btrfs filesystem: exit status 1
{"timestamp":"1500346371.051383018","source":"baggageclaim","message":"baggageclaim.fs.run-command.failed","log_level":2,"data":{"args":["bash","-e","-x","-c","\n\t\ti
f [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_P
ATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! fil
e $IMAGE_PATH | grep BTRFS; then\n\t\t\t/concourse-work-dir/3.3.2/assets/btrfs/mkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mount
point -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb
in:/bin","MOUNT_PATH=/concourse-work-dir/volumes","IMAGE_PATH=/concourse-work-dir/volumes.img","SIZE_IN_BYTES=18446744073473904640"],"error":"exit status 1","session":
"3.1","stderr":"+ '[' '!' -e /concourse-work-dir/volumes.img ']'\n++ stat --printf=%s /concourse-work-dir/volumes.img\n+ '[' 0 '!=' 18446744073473904640 ']'\n+ touch /
concourse-work-dir/volumes.img\n+ truncate -s 18446744073473904640 /concourse-work-dir/volumes.img\ntruncate: Invalid number: '18446744073473904640': Value too large f
or defined data type\n","stdout":""}}
{"timestamp":"1500346371.051576376","source":"baggageclaim","message":"baggageclaim.failed-to-set-up-driver","log_level":2,"data":{"error":"failed to create btrfs file
system: exit status 1"}}
```

**Comment by mumoshu** [comment]
@viglesiasce Thanks for taking your time 👍 

Regarding the error you've shared, AFAIK, you need to create loopback devices on the host to be provided to baggageclaim like described in https://github.com/concourse/concourse/issues/402#issuecomment-219434781, when your dockerd uses a graph driver other than btrfs(which might be true in your GKE node I suppose) as the default graph driver.

I haven't tested it myself(~~I use Container Linux, which uses btrfs by default for the graph driver for my prod workloads~~ Container Linux as of today doesn't use btrfs by default. I can't recall how I managed to run it on Container Linux last time/overlay as the graph driver and baggageclaim driver on extfs as host fs for my minikube env), but I guess you need to tweak your node provisioning script/process to inject creations of loopback devices, and also the helm template for concourse workers to mount those loopback devices from hosts to containers.

**Comment by mumoshu** [comment]
Or I'd suggest to write in docs about setting btrfs as the graphdriver for docker to avoid the problem in the first place. Would it be easier than hacking with lookback devices on hosts and mounts to containers, etc?

**Comment by cmosetick** [comment]
@mumoshu Would you still like to see this PR with Concourse v3.3?

**Comment by mumoshu** [comment]
@cmosetick Thanks for checking in 👍 
It seems like @viglesiasce has already and kindly added the commit cd3374f to update Concourse to v3.3.2

**Comment by viglesiasce** [comment]
This was merged in #1528

**Pull request closed without merging**
