### PR TITLE
[stable/karma] upgrade karma to v0.29

### PR DESCRIPTION
**Pull request by prymitive**
Signed-off-by: Łukasz Mierzwa <l.mierzwa@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by prymitive** [comment]
@davidkarlsen might `/lgtm` when you have a chance? Thanks

**Comment by prymitive** [comment]
@davidkarlsen  / @sameersbn any chance for a `/lgtm` here?

**Comment by davidkarlsen** [comment]
/lgtm
@prymitive sorry for the delay!

**Comment by prymitive** [comment]
Thanks!

**Pull request merged**
