### PR TITLE
[stable/datadog] Adding full datadog role permissions

### PR DESCRIPTION
**Pull request by awwithro**
Follow on to https://github.com/kubernetes/charts/pull/2769

Datadog requires permissions to integrate with kubernetes beyond what it needs for leader election.

### CODE REVIEW

**Comment by awwithro** [comment]
@dhilipkumars can you help with this PR? There were a few in-flight PRs around Datadog RBAC that were waiting to get merged. See also https://github.com/kubernetes/charts/pull/2474

**Comment by awwithro** [comment]
@dhilipkumars does anything else need to happen before this gets merged?

**Comment by dhilipkumars** [comment]
@awwithro Merged now , sorry for the delay.

**Pull request merged**
