### PR TITLE
Fix debug mode cannot be enabled when logLevel is specified

### PR DESCRIPTION
**Pull request by minhdanh**
**What this PR does / why we need it**:

This PR fixes an issue when `debug.enabled` is set to `true`, but debug mode will not be enabled because `logLevel` is already specified. According to Traefik's document:

```
# Enable debug mode.
# This will install HTTP handlers to expose Go expvars under /debug/vars and
# pprof profiling data under /debug/pprof.
# The log level will be set to DEBUG unless `logLevel` is specified.
#
# Optional
# Default: false
#
# debug = true
```
(https://docs.traefik.io/configuration/commons/)

### CODE REVIEW

**Comment by krancour** [comment]
@minhdanh, chart version needs to change to 1.32.1 since a minor change was just merged ahead of this bug fix. Will keep an eye out and merge as soon as that's set.

**Comment by minhdanh** [comment]
@krancour I updated the version. Please have a look.

**Pull request merged**
