### PR TITLE
Readme fix: default version is 0.12.0

### PR DESCRIPTION
**Pull request by Jokero**
**What this PR does / why we need it**:
Fixed readme

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
Hi @Jokero, thanks for your PR. All changes to a Chart, even documentation changes, require a version bump in Chart.yaml. Also, we cannot do anything with it unless you sign the CLA.

**Comment by Jokero** [comment]
@timstoop Then maybe it's better to close the PR and change the version of image in readme with new chart release with useful changes?) Make sense?

**Comment by timstoop** [comment]
Not really, you can just bump the version and push that, that'll be good enough :) We got lots of small fixes these days, no worries there. Do make sure you sign the CLA, though.

**Comment by Jokero** [comment]
Now it's good :+1:

**Pull request merged**
