### PR TITLE
Rocketchat

### PR DESCRIPTION
**Pull request by LuluGO**
- Fix auth problem for rocket.chat using mongodb chart, added default mongodbUsername, mongodbPassword and mongodbDatabase
- Change how to declare image in deployment
- Change liveness probe path
- Add README.md file

@geekgonecrazy

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Would be great if we could have someone from our team on the list to that could help review that Rocket.Chat PR's.

One of the previous PR's related to our chart actually caused it to stop working.

**Comment by geekgonecrazy** [comment]
@sebastien-prudhomme agreed.  Adjusted to be the same 👍

**Comment by geekgonecrazy** [comment]
/assign sebastien-prudhomme

We’d like to not see this just sit.  What else is needed to get this merged?

**Comment by verwilst** [comment]
2 things:
- Your commits are missing --signoff, as marked by the 'dco-labeler' check underneath
- Please use 
```
image:
  repository: rocket.chat
  tag: 0.73.1
  pullPolicy: IfNotPresent
```
instead of defaultImage and version in values.yaml

**Comment by verwilst** [comment]
Please also check the 'Files changed' section for Review comments. :-)

**Comment by geekgonecrazy** [comment]
Is the repository / tag a standard used elsewhere?  But makes sense.  We will of course have to preserve image value for backwards compatibility.

I’ll amend my commit to include signature.  Had no idea that’s what the contrib allowed meant.  Something like commits-signed or something would have been more intuitive there.

> Please also check the Review comments. :-)

I actually don’t see any in the files tab just your comment above. I’ll take another look on desktop.  Perhaps a glitch.


Thanks for taking a look we will fix asap.

**Comment by verwilst** [comment]
This has become quite out of date in the meantime.. :-) Would it be possible to split it up into several PR's? The /api/info is a nice find and the readme is sorely needed, so i'll merge those quickly. 

Would it be possible to explain what "auth issue" you're encountering? I'm also using the mongodb chart alongside it, and it authenticates just fine. Setting the user/pass combo to a hardcoded 'rocketchat' doesn't seem like a safe thing to do.

**Pull request closed without merging**
