### PR TITLE
NEXUS: bump the app version to 3.15.2

### PR DESCRIPTION
**Pull request by jeff-knurek**
also updated the README to have the correct values

Signed-off-by: Jeff Knurek <j.knurek@travelaudience.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rjkernick** [comment]
@jeff-knurek You forgot to put --signoff

**Comment by jeff-knurek** [comment]
🤦‍♂️ so, I guess reverting and committing again should be suitable in this case? _I highly doubt anyone else is working on this branch..._

**Pull request merged**
