### PR TITLE
[incubator/cassandra] Pod disruption budget

### LINKED ISSUE #8380: [incubator/cassandra] Pod disruption budget
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Version of Helm and Kubernetes**:
Helm: 2.10
K8s: 1.10

**Which chart**:
incubator/cassandra

**What happened**:
There is no pod disruption budget for cassandra

**What you expected to happen**:
Ability to configure one

### PR DESCRIPTION
**Pull request by maver1ck**
Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

#### Which issue this PR fixes
  - fixes #8380 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@maver1ck can you fix the conflict?

**Comment by maver1ck** [comment]
@davidkarlsen Done.

**Pull request merged**
