### PR TITLE
[incubator/hue] Initial version of the chart

### PR DESCRIPTION
**Pull request by romainr**
Signed-off-by: Romain <romain.rigaux@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by romainr** [comment]
Ping?

**Comment by romainr** [comment]
@jlegrone @jlegrone, is there anything else I should do to help for the review?

**Comment by romainr** [comment]
Ping

**Comment by maorfr** [comment]
hey @romainr 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by romainr** [comment]
Is it the new recommended way? It might sounds less official but more lightweight.

Created https://github.com/helm/hub/pull/124

**Comment by maorfr** [comment]
https://helm.sh/blog/intro-helm-hub/

it is ;)

**Comment by davidkarlsen** [comment]
I think this can be closed as we have https://hub.helm.sh/charts/hue/hue now

**Pull request closed without merging**
