### PR TITLE
[stable/superset] bump superset versions to newer pip version for more features.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

I'm just bumping the chart's app version.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by phildum** [comment]
Thanks for making this PR.

As per https://github.com/helm/charts/issues/18951 and https://github.com/helm/charts/issues/18390, the current initFile won't work with the latest version of Superset. Rather than me making another fork, @MarcusSorealheis are you able to edit values.yaml in this PR please as per https://github.com/helm/charts/issues/18951#issuecomment-555298599

**Comment by MarcusSorealheis** [comment]
> Thanks for making this PR.
> 
> As per #18951 and #18390, the current initFile won't work with the latest version of Superset. Rather than me making another fork, @MarcusSorealheis are you able to edit values.yaml in this PR please as per [#18951 (comment)](https://github.com/helm/charts/issues/18951#issuecomment-555298599)

I've made the changes and tested them for the init script thanks for the catch.

**Comment by MarcusSorealheis** [comment]
@phildum I am having trouble get the signoff to register. I amended the commit.

**Comment by MarcusSorealheis** [comment]
I created a clean clone of this one here: https://github.com/helm/charts/pull/19915

**Pull request closed without merging**
