### PR TITLE
[stable/airflow] Adding a secretMap instead of adding multiple secrets

### PR DESCRIPTION
**Pull request by dwardu89**
#### What this PR does / why we need it:
This will allow you to specify a kubernetes Secret kind which will load all it's values in the map instead of having to specify each secret individually. You can use the `secrets: []` and can switch to `secretsMap:` when ready.
#### Which issue this PR fixes
N/A
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dwardu89** [comment]
@gsemet @thesuperzapper @maver1ck Just the ok from you before it can merge.

**Comment by gsemet** [comment]
ok for me ! great thanks !

/gltm

**Comment by dwardu89** [comment]
@gsemet could you add the lgtm label again. You weren’t assigned to it now I assigned you

**Comment by alexbegg** [comment]
@dwardu89 did you accidentally commit a `values-test.yaml` file? Unfortunately we can't make a new PR without bumping up the version so I am going to make an issue to delete that file. If there was a reason for the file let me know.

**Comment by dwardu89** [comment]
@alexbegg  It was being used for testing locally. But i'll have it removed. I'll be pushing a PR in a few moments.

**Pull request merged**
