### PR TITLE
[stable/aws-iam-authenticator] Add myself as maintainer

### PR DESCRIPTION
**Pull request by nckturner**
#### What this PR does / why we need it:
Add myself as a maintainer of the aws-iam-authenticator chart.

#### Special notes for your reviewer:
I am a maintainer of kubernetes-sigs/aws-iam-authenticator.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
/ok-to-test
@maorfr Would you please take a look? Thank you.

**Comment by maorfr** [comment]
@nckturner need to bump the version chart.

**Review by scottrigby — CHANGES_REQUESTED** [review]
@nckturner This looks good 😄 But can you also add yourself to a new OWNERS file for this chart as well? See https://github.com/helm/charts#owning-and-maintaining-a-chart 

Ping me on k8s Slack if you don't get a reply soon, GitHub notifications are a shot in the dark sometimes

**Review by scottrigby — APPROVED** [review]
:100:

**Pull request merged**
