### PR TITLE
[stable/airflow] Adding airflow scheduler existing secret connections option

### PR DESCRIPTION
**Pull request by Coqueiro**
#### What this PR does / why we need it:

This adds the option of using an existing secrets resources for scheduler connections. This is desirable since some organizations prefer to use other secret kinds like ExternalSecrets.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Coqueiro** [comment]
Hi, @gsemet , @thesuperzapper and @maver1ck !
I'm new to PRing into helm/charts, so I'm unsure of how to ask for reviews/approvals. I tried running /assign but it didn't work.
Therefore, here's my request! 

Can you please review this PR? 
Thanks!

**Comment by thesuperzapper** [comment]
Im really not sure this is a necessary feature

**Comment by gsemet** [comment]
Are you doing this to integrate Airflow with Hashicorp Vault? That can be a pretty interesting feature, maybe not as a script like it is done in this PR. But I never dealt with ExternalSecrets directly, so I am curious on how we would do it in a clean way

**Comment by Coqueiro** [comment]
@thesuperzapper 
A feature like this is necessary because some companies work a lot with GitOps in Github, and it's not a very secure place for credentials. This allows companies (like mine) to keep those connections elsewhere, while using this chart. We're already using it, which detains us from using the official chart, so for us it's necessary, and it may be useful for others :)
@gsemet
We're integrating with AWS Secret Manager using Kubernetes' ExternalSecrets. This allow us to keep credentials secure from Git, while applying some governance layers in AWS.

**Comment by Coqueiro** [comment]
@thesuperzapper @gsemet 
Hi! Do you guys have any further feedbacks? Can you please review? Thanks!

**Comment by gsemet** [comment]
Do you think it would be possible to document a bit more how the integration with AWS Secret manager?

**Comment by Coqueiro** [comment]
Of course, @gsemet !
I'll link some references and document an example to clear things up. Just to be clear, this feature introduces a flexible way to secure credentials, and AWS Secret Manager is just one of ways to do so, so this documentation might benefit from other examples in the future.

**Comment by Coqueiro** [comment]
Sorry for the delay, @gsemet.
I've added more documentation on how to further use this feature, including some references and an example on how to integrate with AWS Secret Manager.
Is it clear enough?

**Comment by gsemet** [comment]
ok for me
/lgtm

**Comment by gsemet** [comment]
You need to bump the chart version. Can you bump the minor section please?

**Comment by Coqueiro** [comment]
@gsemet Just bumped it

**Pull request merged**
