### PR TITLE
[stable/keycloak] use realm url for probe instead of static welcome page

### PR DESCRIPTION
**Pull request by dojadop**
Signed-off-by: Michael Dop <michael.p.dop@gmail.com>

#### What this PR does / why we need it:
This will result in keycloak actually performing some action (e.g. hitting the database) versus just serving a static webpage for liveliness and readiness probes

#### Which issue this PR fixes
N/A

### CODE REVIEW

**Comment by unguiculus** [comment]
I think it would make sense to distinguish between liveness and readiness probe here and only make the change for readiness probe.

**Comment by dojadop** [comment]
I can do that but I have always done both when we maintained our own copy of the keycloak chart also the openshift example does it as well: https://github.com/jboss-dockerfiles/keycloak/blob/master/openshift-examples/keycloak-https.json#L193 

Let me know what you want me to do.

**Comment by unguiculus** [comment]
I would change it. Makes more sense.

**Comment by dojadop** [comment]
Well thinking about that some more what happens when keycloak looses connectivity to the database or something else goes wrong internally it would not fail the liveliness check and the pod would continue to run.

It would be nice if keycloak actually had a health endpoint.

**Comment by unguiculus** [comment]
@dojadop If the database can't be reached the readiness check will fail. The liveness check will still succeed, which makes sense. There's no need to restart Keycloak in this case. That's why it makes sense to distinguish between the two probe types.

**Pull request merged**
