### PR TITLE
[stable/rabbitmq-ha] Clustering fixes

### LINKED ISSUE #3914: RabbitMQ HA Chart Persistence Issue
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
rabbitmq-ha

**What happened**:
When I generate a cluster it works well, with the exception of persistence. RabbitMQ, if I'm not mistaken, requires the hostname to be equivalent in order for Mnesia to retrieve the appropriate data and restore it to the RabbitMQ server. Unfortunately, when the hostname is rabbit@[POD IP], and the IP is constantly changing, if a RabbitMQ pod belonging to the statefulset were to be restarted, it will start with 0 data. As a result, queue data is lost upon startup. Upon inspection of the pod's mnesia folder I found 3 different sets of folders (one for each restart).

**What you expected to happen**:
I expected that queue data in each pod is persisted to the same place for mnesia to read from, but it's not.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster, once up and running, restart one of the pods and you'll notice it will get a new IP and in the mnesia folder (/var/lib/rabbitmq/mnesia) will show multiple folders for each new rabbit@[POD IP] that is generated upon pod deletion/creation.

**Anything else we need to know**:
Is there a way that we can use actual hostnames without IPs? This will lead to each successive start being stored in the same mnesia folder for restoring purposes (if needed). I've tried to change it to using metadata.name but that breaks the clustering autodiscovery (even if I were to change the cluster_formation.k8s.address_type=hostname). Perhaps I'm missing something here?

Thank you!

Matt

### PR DESCRIPTION
**Pull request by coreypobrien**
* Use hostnames instead of IPs for node names since IPs are ephemeral
* Always use a headless clusterIP service for clustering
* Never use a cached erlang cookie since we are always providing it

Fixes #3914 

Primarily this switches from using the pod IP to using the hostname for the rabbit node name. The pod IP doesn't work with persistence because new pods get new IPs which then can't access the existing data because the node name has changed.

As a part of that change, I realized that we need to have a headless ClusterIP for StatefulSet DNS stuff to work correctly, but we allow changing the service type to `LoadBalancer` etc.  To ensure DNS stuff always works correctly, I created a new service that is always headless ClusterIP to use for clustering DNS requirements.

Finally, after rolling things a few times during testing, I got into the state where `/var/lib/rabbitmq/.erlang.cookie` was set to something other than the current `RABBITMQ_ERLANG_COOKIE`. Since we shouldn't ever need to keep this cached cookie around, I added a snippet to the init container to remove that file if it exists.

Here's what things look like after the changes:

```
bash-4.4# rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local ...
[{nodes,
     [{disc,
          ['rabbit@rabbitmq-ha-test-rabbitmq-ha-0.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
           'rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
           'rabbit@rabbitmq-ha-test-rabbitmq-ha-2.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local']}]},
 {running_nodes,
     ['rabbit@rabbitmq-ha-test-rabbitmq-ha-2.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
      'rabbit@rabbitmq-ha-test-rabbitmq-ha-0.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
      'rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local']},
 {cluster_name,
     <<"rabbit@rabbitmq-ha-test-rabbitmq-ha-0.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local">>},
 {partitions,[]},
 {alarms,
     [{'rabbit@rabbitmq-ha-test-rabbitmq-ha-2.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
          []},
      {'rabbit@rabbitmq-ha-test-rabbitmq-ha-0.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
          []},
      {'rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local',
          []}]}]
```

```
bash-4.4# ls -lah /var/lib/rabbitmq/mnesia/
total 32
drwxr-xr-x    6 rabbitmq rabbitmq    4.0K Apr  2 15:26 .
drwxr-xr-x    6 rabbitmq root        4.0K Apr  2 15:26 ..
drwxr-xr-x    3 rabbitmq rabbitmq    4.0K Apr  2 15:26 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local
drwxr-xr-x   18 rabbitmq rabbitmq    4.0K Apr  2 15:26 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local-plugins-expand
-rw-r--r--    1 rabbitmq rabbitmq       2 Apr  2 15:26 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha-discovery.testrabbit.svc.cluster.local.pid
drwxr-xr-x    3 rabbitmq rabbitmq    4.0K Apr  2 14:51 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha.testrabbit.svc.cluster.local
drwxr-xr-x   18 rabbitmq rabbitmq    4.0K Apr  2 14:51 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha.testrabbit.svc.cluster.local-plugins-expand
-rw-r--r--    1 rabbitmq rabbitmq       2 Apr  2 14:51 rabbit@rabbitmq-ha-test-rabbitmq-ha-1.rabbitmq-ha-test-rabbitmq-ha.testrabbit.svc.cluster.local.pid
```

### CODE REVIEW

**Comment by timstoop** [comment]
Although I think this looks fine, I wonder if we should prefer the solution from #4591, as that seems the cleaner solution. Or is there a good reason to do it like this instead?

**Comment by coreypobrien** [comment]
😮 So, philosophically speaking, if `rabbitmq` adds support for clustering, why do we need `rabbitmq-ha` as a separate chart?

Practically speaking, the solution being proposed there looks a lot like the way `rabbitmq-ha` is _currently_ doing things with IP-based node names which doesn't work with persistence.

**Comment by timstoop** [comment]
Totally agree with you there. If we can have a single rabbitmq Chart that support a single replica and can also scale up automagically, we should do that.

**Comment by unguiculus** [comment]
cc @etiennetremel

**Review by etiennetremel — APPROVED** [review]
Really nice work and thanks for the effort! That was the missing part to have it resilient to upgrade.

**Comment by estahn** [comment]
@coreypobrien We had a lot of issues with the `rabbitmq` chart and broken mnesia databases due to the use of names instead of IPs. It felt like due to the pod using IPs it was recovering a lot better because it would just fail over and rebuild the mirror.

Given we don't have a lot of operational experience with RabbitMQ, the issue may be somewhere else.

**Comment by martianoff** [comment]
@estahn main problem with IP names it doesn't work with persistent storage, but without persistent storage it is not reliable since you can lose all queued data, because it can't rejoin cluster on ip change (supposed)

**Comment by estahn** [comment]
@maksimru We're not using persistent storage. We have 5 pods across nodes with a policy `ha-mode: exactly, ha-params: 3`.

IMO we will need to lose >3 pods to lose data. Please correct me if I'm wrong.

Also, we favour availability and are fine with a possible message loss.

How are you dealing with broken mnesia databases? Is that not happening for you at all?

**Comment by martianoff** [comment]
@estahn, lose together 3 or even 5 pods is not so hard, for example, if all pods are on same node you can overload it and node will get down with all pods, other reasons are network failure, cloud provider issues etc.
I never had problems with broken mnesia database so far.

Btw i tested solution from @coreypobrien and it still not reliable, simple kubectl delete pod rabbitmq-0 make rabbit-0 hang on CrashLoopBackOff, it is unable to reconnect to the cluster (inconsistent_cluster), most likely because it is already removed from other nodes but still thinks it is clustered

**Comment by estahn** [comment]
@maksimru Yes, clearly but the pods have an anti-affinity rule so the pods are all on different nodes.

It's working fine for us without persistent volumes and just IP addresses. We can just delete pods and they rejoin the cluster.

**Comment by estahn** [comment]
@maksimru I just tried the latest 1.3.0 version and it recovered fine after running `kubectl delete pod saucy-penguin-rabbitmq-ha-0`

**Comment by ApsOps** [comment]
@estahn @coreypobrien I just tried this as well, but deleting a pod takes it in a crashloop forever due to `BOOT FAILED`, with this log:
```
2018-04-09 09:15:15.618 [debug] <0.97.0> Lager installed handler lager_forwarder_backend into error_logger_lager_event
2018-04-09 09:15:15.618 [debug] <0.100.0> Lager installed handler lager_forwarder_backend into rabbit_log_lager_event
2018-04-09 09:15:15.613 [debug] <0.94.0> Lager installed handler error_logger_lager_h into error_logger
2018-04-09 09:15:15.618 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,error_logger_lager_event}) at pid <0.96.0>
2018-04-09 09:15:15.618 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_lager_event}) at pid <0.99.0>
2018-04-09 09:15:15.618 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_channel_lager_event}) at pid <0.102.0>
2018-04-09 09:15:15.623 [debug] <0.103.0> Lager installed handler lager_forwarder_backend into rabbit_log_channel_lager_event
2018-04-09 09:15:15.623 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_connection_lager_event}) at pid <0.105.0>
2018-04-09 09:15:15.623 [debug] <0.106.0> Lager installed handler lager_forwarder_backend into rabbit_log_connection_lager_event
2018-04-09 09:15:15.623 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_mirroring_lager_event}) at pid <0.108.0>
2018-04-09 09:15:15.624 [debug] <0.109.0> Lager installed handler lager_forwarder_backend into rabbit_log_mirroring_lager_event
2018-04-09 09:15:15.624 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_queue_lager_event}) at pid <0.111.0>
2018-04-09 09:15:15.624 [debug] <0.112.0> Lager installed handler lager_forwarder_backend into rabbit_log_queue_lager_event
2018-04-09 09:15:15.624 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_federation_lager_event}) at pid <0.114.0>
2018-04-09 09:15:15.624 [debug] <0.115.0> Lager installed handler lager_forwarder_backend into rabbit_log_federation_lager_event
2018-04-09 09:15:15.625 [debug] <0.86.0> Supervisor lager_sup started gen_event:start_link({local,rabbit_log_upgrade_lager_event}) at pid <0.117.0>
2018-04-09 09:15:15.625 [debug] <0.118.0> Lager installed handler lager_forwarder_backend into rabbit_log_upgrade_lager_event
2018-04-09 09:15:15.638 [debug] <0.81.0> Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.120.0>
2018-04-09 09:15:15.642 [debug] <0.80.0> Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.121.0>
2018-04-09 09:15:15.647 [debug] <0.82.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.122.0>
2018-04-09 09:15:15.647 [debug] <0.82.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0},{job_input,0},{job_run,0},{job_time,0},{job_error,0}]) at pid <0.123.0>
2018-04-09 09:15:15.948 [info] <0.33.0> Application lager started on node 'rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local'
2018-04-09 09:15:16.084 [debug] <0.90.0> Lager installed handler lager_backend_throttle into lager_event
2018-04-09 09:15:17.969 [debug] <0.127.0> Supervisor inet_gethost_native_sup started undefined at pid <0.128.0>
2018-04-09 09:15:17.969 [debug] <0.60.0> Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.127.0>
2018-04-09 09:15:17.979 [debug] <0.136.0> Supervisor mnesia_sup started mnesia_sup:start_event() at pid <0.137.0>
2018-04-09 09:15:17.979 [debug] <0.136.0> Supervisor mnesia_sup started mnesia_ext_sup:start() at pid <0.138.0>
2018-04-09 09:15:17.979 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_monitor:start() at pid <0.140.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_subscr:start() at pid <0.141.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_locker:start() at pid <0.142.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_recover:start() at pid <0.143.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_tm:start() at pid <0.144.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_checkpoint_sup:start() at pid <0.145.0>
2018-04-09 09:15:17.980 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_controller:start() at pid <0.146.0>
2018-04-09 09:15:17.981 [debug] <0.139.0> Supervisor mnesia_kernel_sup started mnesia_late_loader:start() at pid <0.147.0>
2018-04-09 09:15:17.981 [debug] <0.136.0> Supervisor mnesia_sup started mnesia_kernel_sup:start() at pid <0.139.0>
2018-04-09 09:15:17.981 [info] <0.33.0> Application mnesia started on node 'rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local'
2018-04-09 09:15:17.983 [info] <0.33.0> Application mnesia exited with reason: stopped

BOOT FAILED
===========

Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 444
    rabbit:'-boot/0-fun-0-'/0 line 300
    rabbit_mnesia:check_cluster_consistency/0 line 663
throw:{error,{inconsistent_cluster,"Node 'rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local' thinks it's clustered with node 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local', but 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local' disagrees"}}
Log file(s) (may contain more information):
   <stdout>

2018-04-09 09:15:17.984 [error] <0.5.0>
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 444
    rabbit:'-boot/0-fun-0-'/0 line 300
    rabbit_mnesia:check_cluster_consistency/0 line 663
throw:{error,{inconsistent_cluster,"Node 'rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local' thinks it's clustered with node 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local', but 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local' disagrees"}}
Log file(s) (may contain more information):
   <stdout>
{"init terminating in do_boot",{error,{inconsistent_cluster,"Node 'rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local' thinks it's clustered with node 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local', but 'rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local' disagrees"}}}
```
Any ideas how to deal with this? (other than deleting the rabbitmq-1 data, of course)

**Comment by martianoff** [comment]
@estahn did you try with persistent storage?

**Comment by coreypobrien** [comment]
The ideal is to have persistent storage ("if all of my pods stop simultaneously, I don't lose any data") high availability ("I can lose N pods and still be online"), and failure recovery ("if I lose a pod, kubernetes heals my cluster automatically"). This PR strictly handles the persistent storage story. With IP-based names, you cannot lose all of your nodes and still have persistent data because new pods come up without access to the persisted data in mnesia. The high availability story is pretty solid I think (i.e losing 1 pod isn't a problem). The `inconsistent_cluster` errors is part of the failure recovery story and is well reported regardless of the persistent storage story in issues #4474, #4519, #4685. I'd suggest we focus on the `inconsistent_cluster` issue in (preferably one of) those issues.

**Comment by brianwawok** [comment]
@coreypobrien what part of autocluster is supposed to make this form as one cluster instead of three?

The OLD style chart before this merge had issues (crashed node could not rejoin).. but all 3 nodes correctly joined the same cluster.

After this change, starting 3 nodes forms 3 clusters of size 1.

My clusters are called
```

Cluster rabbit@rabbitmq-ha-0.rabbitmq-ha-discovery.default.svc.cluster.local
Cluster rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local
Cluster rabbit@rabbitmq-ha-2.rabbitmq-ha-discovery.default.svc.cluster.local

```

I have a slightly hacked configmap so its possible it was a hacking mistake.. but past that not sure how to dig deeper?

```

2018-05-04 21:23:56.765 [info] <0.33.0> Application rabbit started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.765 [info] <0.33.0> Application rabbitmq_amqp1_0 started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.765 [info] <0.5671.0> Peer discovery: enabling node cleanup (will remove nodes not known to the discovery backend). Check interval: 10 seconds.
2018-05-04 21:23:56.766 [info] <0.33.0> Application rabbitmq_peer_discovery_common started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.766 [info] <0.33.0> Application rabbitmq_shovel started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.767 [info] <0.33.0> Application rabbitmq_federation started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.767 [info] <0.33.0> Application rabbitmq_consistent_hash_exchange started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.767 [info] <0.33.0> Application rabbitmq_peer_discovery_k8s started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.770 [info] <0.33.0> Application rabbitmq_management_agent started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.770 [info] <0.33.0> Application cowboy started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.770 [info] <0.33.0> Application rabbitmq_web_dispatch started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.813 [info] <0.5738.0> Management plugin started. Port: 15672
2018-05-04 21:23:56.813 [info] <0.5844.0> Statistics database started.
2018-05-04 21:23:56.813 [info] <0.33.0> Application rabbitmq_management started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.813 [info] <0.33.0> Application rabbitmq_federation_management started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
2018-05-04 21:23:56.813 [info] <0.33.0> Application rabbitmq_shovel_management started on node 'rabbit@rabbitmq-ha-1.rabbitmq-ha-discovery.default.svc.cluster.local'
 completed with 11 plugins.
2018-05-04 21:23:57.099 [info] <0.5.0> Server startup complete; 11 plugins started.
 * rabbitmq_shovel_management
 * rabbitmq_federation_management
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * rabbitmq_peer_discovery_k8s
 * rabbitmq_consistent_hash_exchange
 * rabbitmq_federation
 * rabbitmq_shovel
 * rabbitmq_peer_discovery_common
 * rabbitmq_amqp1_0


```

**Comment by francesco-beccaria** [comment]
@coreypobrien
Can I ask about the "Never use a cached erlang cookie since we are always providing it" bit?
Why was it necessary?
and
Is the RabbitMQ app recreating that file upon start, taking the value from the environment variable?

I'm asking because even if I'm passing the Erlang Cookie in the `values.yaml` file I've had a problem where one of the three nodes of my Cluster had a different Erlang Cookie (in that file `/var/lib/rabbitmq/.erlang.cookie`) after I deleted the pod and it was recreated.

I deleted the pods one by one because I had changed the rabbitmqMemoryHighWatermark in the `values.yaml` file, then run a helm upgrade, and I wanted the nodes to start up with the new value.
All three nodes had, and still have, the `/var/lib/rabbitmq/.erlang.cookie` file present, but one was different and after deleting that pod I had lots of messages in the logs like the one below, and the node could not rejoin the cluster:

    2018-05-22 12:58:26.181 [error] <0.373.0> ** Connection attempt from disallowed node '...@...' **

I had to manually write the correct Cookie in the `/var/lib/rabbitmq/.erlang.cookie` file then the node came back up, only to get a message like:

    2018-05-22 14:55:01.563 [warning] <0.4551.0> Message store ".../msg_store_persistent": rebuilding indices from scratch

which because the queue was huge never manages to finish and the pod reboots itself.
This are only test queues and messages, so no big problem there, but with my luck, that pod was the one where the queue with the biggest number of messages was (47M out of the 53M).

I just don't understand why the Cookie was different for some reason, and where that one came from.

I'm using an efs-provisioner for the storage class. Not sure if that's relevant as I never had any problems with it before.

Maybe I was simply wrong to delete the pods one by one after updating the Chart Values?

Understanding better how the cached cookie file works would be very useful, and if you have any idea of what might have happened as well.
Sorry for the long message.
F

**Comment by coreypobrien** [comment]
> Why was it necessary?
> Is the RabbitMQ app recreating that file upon start, taking the value from the environment variable?

Since the chart is providing the cookie with `rabbitmqErlangCookie` which [gets mapped into the environment variable](https://github.com/kubernetes/charts/blob/8b31fed47cdc96d4f0fbbc33108405371274cb77/stable/rabbitmq-ha/templates/statefulset.yaml#L119-L123) that [the image puts into the cookie](https://github.com/docker-library/rabbitmq/blob/4b2b11c59ee65c2a09616b163d4572559a86bb7b/3.7/alpine/docker-entrypoint.sh#L164-L176) the chart is always the source of truth for the cookie. 

The specific case you're running into is probably due to what we should probably consider a bug in this chart due to upstream helm annoying behavior. This chart sets the cookie to a random value if you don't specify it. That random value gets updated every time helm is run so every upgrade will change the cookie. Since that leave old pods with the old cookie and new pods with the new cookie, you get the behavior you're seeing. The easy fix is to just specify the cookie in you helm values.

**Comment by francesco-beccaria** [comment]
Thanks for your reply.
I do set the Cookie in the values file for exactly that reason, that's why I was surprised to see a different one.
And up until I deleted the pod the three nodes were all happy and clustered.
We do have federation set up on the cluster, and I noticed the federation "definition" (for lack of the appropriate term) lives on a specific node, meaning that the command `rabbitmqctl federation_status` needs to be run on the correct pod to get a result. And once I had the federation "definition" (..again) split on two nodes.
This is pure ignorance on my part. I'm still quite new to RabbitMQ. I'm pretty sure though it has nothing to do with this particular issue I had

**Pull request merged**
