### PR TITLE
[stable/percona-xtradb-cluster] Custom command for metrics exporter

### LINKED ISSUE #9100: [stable/percona-xtradb-cluster] Custom command for metrics exporter
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm v2.10
K8S v1.10

**Which chart**:

stable/percona-xtradb-cluster

**What happened**:

Mysqld exporter has ability to configure what metrics to present. This can be done by command line args. Unfortunately there is no way to pass command line args to exporter in this chart.
https://github.com/prometheus/mysqld_exporter

**What you expected to happen**:

Ability to configure mysqld exporter

### PR DESCRIPTION
**Pull request by maver1ck**
Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

#### What this PR does / why we need it:
Adding ability to configure mysqld exporter

#### Which issue this PR fixes
  - fixes #9100 

#### Special notes for your reviewer:

Sample configuration
```
metricsExporter:
  enabled: true
  commandOverrides: ["/bin/mysqld_exporter"]
  argsOverrides:
  - "--collect.info_schema.innodb_metrics"
  - "--collect.info_schema.tablestats"
  - "--collect.info_schema.userstats"
  - "--collect.engine_innodb_status"
  - "--collect.auto_increment.columns"
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Review by paulczar — CHANGES_REQUESTED** [review]
I don't see a bump on the chart version!

**Review by paulczar — APPROVED** [review]

**Comment by maver1ck** [comment]
@paulczar lgtm ?

**Review by jgleonard — APPROVED** [review]
LGTM!

**Pull request merged**
