### PR TITLE
Add me as reviewer, default ServiceMonitor to false

### PR DESCRIPTION
**Pull request by ihoegen**
#### What this PR does / why we need it:
Not everyone uses Prometheus Operator

#### Special notes for your reviewer:
@integrii @lolimjake 
#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ihoegen** [comment]
I'm going to hold off on version bump for when there's more features

**Comment by integrii** [comment]
Thanks Ian!

**Pull request merged**
