### PR TITLE
[stable/prometheus] Add example alert config (#966)

### LINKED ISSUE #966: How to add alert rule to prometheus ?
Could you give me simple example how to add alert rule to chart stable/prometheus ?

I install it with default values.
I added graph.

I cannot figure out how to add the rules.

### PR DESCRIPTION
**Pull request by anthu**
#### What this PR does / why we need it:
This PR adds an example configuration for the `alerts` block in prometheus-server configuration.
It seems not to be that obvious as the issue #966 and the linked issues show.
 
#### Which issue this PR fixes
  - fixes #966

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

Signed-off-by: Anton Huck <anton.huck@netlight.com>

### CODE REVIEW

**Comment by nodox** [comment]
What is that status of this? Its extremely helpful as I've searched for a couple hours looking for how alert configuration works with this helm chart. Please merge soon!

**Review by gianrubio — CHANGES_REQUESTED** [review]
please fix conflicts and make sure CI is green

**Comment by anthu** [comment]
Sure - there you go!
Thanks for the review.

**Pull request merged**
