### PR TITLE
[stable/grafana] Set the user and fs group for grafana

### LINKED ISSUE #5635: [stable/grafana] Crash-looping with volume permission denied on fresh install
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

**Which chart**: stable/grafana

**What happened**:
I installed the chart for the first time using the following command:
```
helm install stable/grafana --name grafana --namespace monitoring --values grafana-dev.yaml
```
And the content of the grafana-dev.yaml:
```
ingress:
  enabled: true
  hosts:
  - grafana.example.com
persistence:
  enabled: true
  size: 1Gi
  accessModes:
  - ReadWriteOnce
env:
  GF_SERVER_DOMAIN: grafana.example.com
  GF_SERVER_ROOT_URL: https://grafana.example.com
envFromSecret: "grafana-secret"
rbac:
  create: false
```
The chart installs without problems, but the grafana pod crash-loops, here are the logs from the container:
```
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```

**What you expected to happen**:
I expected the grafana pod to not crash-loop, and launch correctly.

**How to reproduce it** (as minimally and precisely as possible):
Run the command mentioned in the "What happened?" section. Fetch the logs from the container.

### PR DESCRIPTION
**Pull request by andybug**
**What this PR does / why we need it**: Fixes persistent volume permission errors with the new grafana image. The init container that downloads remote dashboards will now run as the same user as grafana. Previously, grafana would error and not start.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5635 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by brian-schwegmann — APPROVED** [review]
:shipit:

**Comment by pv93** [comment]
What is the status with this PR? Need it to get stable/grafana working

**Comment by andybug** [comment]
lint is failing due to:

    Verifying maintainer 'Ming Hsieh'...
    ERROR: 'Ming Hsieh' is not a valid GitHub account. Please use a valid Github account to help us communicate with maintainers in PRs/issues.
    ERROR: Chart validation failed.

**Comment by azman0101** [comment]
It seems you need to bump the version in Chart.yaml.

**Pull request merged**
