### PR TITLE
[stable/rabbitmq-ha] Fix security context for init container

### LINKED ISSUE #21739: Invalid security context for initContainer
**Describe the bug**
The security context for the init container contains `fsGroup` which isn't valid.

**Version of Helm and Kubernetes**:
`v3.1.2`

**Which chart**:
rabbitmq-ha

**What happened**:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext`

**What you expected to happen**:
The chart to install successfully.

**How to reproduce it** (as minimally and precisely as possible):
Try installing it.

**Anything else we need to know**:
It was related to #21344, specifically: https://github.com/helm/charts/pull/21344/files#diff-e00e6fcd2c8b56c1bd9161e193b126fdR72

### PR DESCRIPTION
**Pull request by caiges**
No
#### What this PR does / why we need it:
It corrects the security context for the iniContainer.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #
- fixes #21739 
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Doqnach** [comment]
This PR would solve our problem of being unable to install a new instance of `stable/rabbitmq-ha`.

**Comment by rccrdpccl** [comment]
This PR would allow to install this chart with helm v3

**Review by steven-sheehy — APPROVED** [review]
/assign
/ok-to-test
/lgtm
Thanks!

**Comment by steven-sheehy** [comment]
Just need to merge from master and fix chart version

**Pull request merged**
