### PR TITLE
[stable/nginx-ingress] add support for controller specific tcp, udp p…

### PR DESCRIPTION
**Pull request by michaelgeorgeattard**
We need container ports open without adding configmaps/service entries.

I can improve README.md if necessary.

### CODE REVIEW

**Comment by michaelgeorgeattard** [comment]
@mgoodness @viglesiasce Can you kindly confirm if the PR is mergeable quality?

**Comment by michaelgeorgeattard** [comment]
@mattfarina Can you have a look please?

**Comment by mattfarina** [comment]
@michaelgeorgeattard The latest changes came in after the DCO was in place for Helm. You can learn more about it at https://www.helm.sh/blog/helm-dco/index.html and learn about signoff commands to fix this at https://github.com/helm/charts/pull/6691/checks?check_run_id=16945836

**Pull request closed without merging**
