### PR TITLE
Add NodeSelector to CockroachDB Pods

### PR DESCRIPTION
**Pull request by oliverisaac**
**What this PR does / why we need it**:
This is a feature I needed to make sure the pods were running on the nodes I needed. This is a non-breaking change to let others do the same.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by a-robinson** [comment]
Thanks!

/ok-to-test
/lgtm
/approve

**Comment by oliverisaac** [comment]
Sorry, this is my first PR and I'm learning I should have just shoved it into a new PR branch...

**Comment by a-robinson** [comment]
No worries, thanks for the contribution!

**Pull request merged**
