### PR TITLE
[stable/opa] Added a namespace selector config to admission controller

### PR DESCRIPTION
**Pull request by aleerizw-zz**
#### What this PR does / why we need it:
Making the namespace selector configurable allows for more flexibility.
e.g. we want to enable it for only 1 namespace.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by aleerizw** [comment]
@tsandall could you please review :pray:

**Review by tsandall — APPROVED** [review]
LGTM

**Pull request merged**
