### PR TITLE
avoid the secret changed performing upgrade

### LINKED ISSUE #11600: [stable/prestashop] secret change on upgrade
## BUG REPORT

**Version of Helm and Kubernetes**:
- Helm v2.12.3
- kubernetes v1.11.5-gke.5

**Which chart**:

stable/prestashop

**What happened**:

If the secret is generated with rrandAlphaNum, it is re-generated when upgrade

**What you expected to happen**:
The secret doesn't change

**How to reproduce it** (as minimally and precisely as possible):

1. run  ` helm install stable/prestashop --set prestashopHost="test.it --name  austere-meerkat`
2.   run ```  kubectl get secret --namespace test austere-meerkat-prestashop -o jsonpath="{.data.prestashop-password}" | base64 --decode ```
3. get `hXFkaSXZmN`
4. run  `helm upgrade austere-meerkat stable/prestashop`
5. run  ```kubectl get secret --namespace test austere-meerkat-prestashop -o jsonpath="{.data.prestashop-password}" | base64 --decode ```
6. get `I1jSLaS0Wf`

### PR DESCRIPTION
**Pull request by Nittarab**
#### What this PR does / why we need it:

avoid the secret changed performing upgrade

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes  #11600 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign your existing commits](https://github.com/apps/dco), you can find custom instructions in the “Details” link from the below DCO check. In the same way, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by Nittarab** [comment]
Hi @carrodher, i fix the DCO. 
Do you think? this is a minor release?

**Comment by carrodher** [comment]
It seems like a change/improvement in functionality, so it might be okay to use minor for it.
In the same way, in the meantime, a new PrestaShop version was released so you need to solve some conflicts to include those changes.

It sounds harder than it is: 
- Resolve conflicts in `stable/prestashop/Chart.yaml`
- Increase `minor` over the value after fix the conflict.

**Comment by Nittarab** [comment]
Thanks @carrodher for the explanation, now I think It's ok.

**Pull request merged**
