### PR TITLE
[stable/spinnaker] update dependencies

### PR DESCRIPTION
**Pull request by prydonius**
Fixes an issue where Redis resources are truncated to 24 characters instead of
63.

Fixes https://github.com/kubernetes/helm/issues/2116

### CODE REVIEW

**Comment by linki** [comment]
@k8s-bot e2e test this

**Comment by linki** [comment]
@prydonius do you have an idea why the e2e tests are timing out?

**Comment by lachie83** [comment]
> @prydonius do you have an idea why the e2e tests are timing out?

@linki this chart doesn't install in 180 seconds

**Comment by prydonius** [comment]
@linki @viglesiasce gentle ping

**Comment by viglesiasce** [comment]
Sorry for the delay. Will try to incorporate this in #961

**Comment by viglesiasce** [comment]
Closing in favor of #961

**Pull request closed without merging**
