### PR TITLE
Add "persistence.existingClaim" to documented options

### PR DESCRIPTION
**Pull request by spitimage**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign the CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement), also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by spitimage** [comment]
This is just a very minor doc edit. No need for a chart version bump.

**Comment by prydonius** [comment]
@spitimage it's required for the CI to pass, even for minor doc changes. We cannot get this merged if the version is not bumped! Please bump the patch version.

**Comment by prydonius** [comment]
/ok-to-test
/lgtm

Thanks a lot @spitimage, sorry about the CI issue!

**Pull request merged**
