### PR TITLE
Updated Pachyderm Helm chart for allowing multi-instance deployments

### PR DESCRIPTION
**Pull request by naztyroc**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jonandernovella** [comment]
@naztyroc Hi there! Did you test this on different scenarios? Also, why did you remove the `pfsCache`? Did you check if port-forwarding still works?

**Comment by jonandernovella** [comment]
I see that you reverted back the fully qualified SA name. I recently had to make an update on the SA name because it seemed to be hardcoded on pachd. Otherwise pipelines did not really start.

**Comment by naztyroc** [comment]
HI Jon,


In our environment we notice that the pipeline was looking for a specific service account in K8, I believe it's called pachyderm-storage-secret. Is that value hardcoded in the replication controller for the pipeline?

-Rashian

**Comment by jonandernovella** [comment]
@naztyroc Yes, it is hardcoded as far as I read here: https://github.com/pachyderm/pachyderm/blob/50ca64bc2397eac56712faf6914e91b63b91cfa6/src/server/pkg/deploy/assets/assets.go#L42

Same applies for the etcdName.

**Comment by naztyroc** [comment]
I see.. Can the value be changed to a variable? In the chart, we've inserted values like this {{ template "pachd.fullname" . }}-storage, so the names can be dynamic.


-Rashian

**Comment by jonandernovella** [comment]
@naztyroc We might need to ask @jdoliner. But in principle those values will not work unless you change them in `pachd`

**Comment by naztyroc** [comment]
We've set a variable in pachd which gets populated via the helm chart name. That gave us the ability to deploy the chart multiple times in any namespace. All the values where specific to the name of the chart.


-Rashian

**Comment by jonandernovella** [comment]
Nice work! Please test if port-forwarding works from outside the cluster:`pachctl port-forward &` and also whether all storage bakends work. You might need to revert back the SA name for now.

**Comment by naztyroc** [comment]
In our environment, bare metal on prem, we have the following:




3 Controller Nodes (api-server / scheduler / etcd / controller-manager / kubelet / kube-proxy)
9 Compute Nodes (kubelet / kube-proxy)

K8-Pod infrastructure (Calico Network / Flannel / KubeDNS / Heapster / InfluxDB)


Storage Backend (CEPH via RBD / NFS)


What worked for us was deploying the chart with RBD dynamic persistent volume creation. We had to manually create the SA pachyderm-storage-secret for the pipeline because there was not place in the chart to declare in the replication controller. Instead of using port-forwarding, we declared the ADDRESS variable to suite the proper instance service nodeport.     


-Rashian

**Comment by jonandernovella** [comment]
I suggest that we close this PR. In general, users should not manually create the `SA` and the pachyderm-storage-secret for the pipelines, nor using the `env: ADDRESS` to reach the cluster.

**Comment by naztyroc** [comment]
Understood.. If there was a way to create a variable in the pipeline replication controller that matched the variables we placed inside the mount point for pachd, it could work.


-Rashian

**Comment by jonandernovella** [comment]
@naztyroc Agree. Let us consult with @jdoliner

**Pull request closed without merging**
