### PR TITLE
[stable/nats] Fix hard-coded port definitions

### PR DESCRIPTION
**Pull request by guessi**
#### What this PR does / why we need it:

port definition should not be hard-coded

#### Which issue this PR fixes

  - N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by guessi** [comment]
@tompizmor please have a look at this PR while you are free, thanks

**Review by juan131 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
