### PR TITLE
[WIP] move to StatefulSets

### PR DESCRIPTION
**Pull request by vise890**
Solves #632

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@vise890 I cannot get the pods to pass readiness checks and the pods keep crashing. Is that what you're seeing?

**Comment by vise890** [comment]
Yes, that's what I'm seeing. I haven't had time to investigate this further unfortunately.

In #632 @mattbates was saying that he made some progress.

I think we can close this PR.

**Comment by ReSearchITEng** [comment]
I am interested to take a look into the failing code. Where is it available?

**Pull request closed without merging**
