### PR TITLE
Allow upgrade with empty clusterIP

### LINKED ISSUE #4704: [stable/external-dns] invalid value for spec.clusterIP on 0.5.3 upgrade
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.8.1 and k8s 1.9.6/1.7.3 (same error, different clusters)

**Which chart**:
external-dns

**What happened**:
Without changing any user defined values, upgrading from 0.5.2 to 0.5.3 fails with this when the `service.clusterIP` setting is not customised:
```
Error: UPGRADE FAILED: Service "external-dns" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**:
Upgrade from 0.5.2 to 0.5.3 to succeed when values set by the user have not changed.

**How to reproduce it** (as minimally and precisely as possible):

1. Install external-dns chart 0.5.2 without customising `service.clusterIP`
1. Try to upgrade to 0.5.3 with the same options, upgrade fails

**Anything else we need to know**:
v0.5.3 changed this in https://github.com/kubernetes/charts/pull/4377. I think that PR might resolve going from a set value back to default (empty string) but something might be validating a different situation of empty string to not set?

**Workaround**:
Pin version to 0.5.2 for now.

### PR DESCRIPTION
**Pull request by hobti01**
**What this PR does / why we need it**: Reverts #4377 to fix the same issue

**Which issue this PR fixes**: fixes #4704

**Special notes for your reviewer**: Attempted to align with other charts, but behaviour is inconsistent between charts.

### CODE REVIEW

**Comment by coreypobrien** [comment]
Meh, this breaks upgrades.

**Comment by hobti01** [comment]
@coreypobrien this PR reverts to the original approach which also displayed the error in some(?) cases.

**Comment by coreypobrien** [comment]
@hobti01 I outlined the problem in the PR to revert this ⬆️

**Comment by hobti01** [comment]
But you are reverting my change that broke upgrades, as reported in #4704 :-)

**Comment by coreypobrien** [comment]
Is there ever a valid use case for generating `custerIP: ""` from the helm chart? I think that will always cause problems so we should never do that.

**Comment by hobti01** [comment]
I agree with you and have already tried exactly this change, and it surprisingly fails.  There are at least 4 approaches that I saw in other charts.  I do not want to set any value for `clusterIP` either, but the approach in your PR has already failed.  Unfortunately I do not have a solution, which is why I reverted the change.  Good luck with your PR!

**Pull request merged**
