### PR TITLE
[stable/consul] Add readinessProbe for correct rolling update

### PR DESCRIPTION
**Pull request by mecseid**
#### What this PR does / why we need it:
Adds readiness probe for StatefulSet. The rolling update will wait the cluster to get a healthy state.
Based on: [consul-helm-chart](https://github.com/hashicorp/consul-helm/blob/v0.11.0/templates/server-statefulset.yaml)
#### Which issue this PR fixes
* N/A
#### Special notes for your reviewer:
@lachie83 Please review :)
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mecseid** [comment]
@zanhsieh Is it a Kubernetes DNS related problem, or I misunderstand something?
As I read the logs, I think it can't resolve the service name because of wrong resolv.conf file or DNS settings.

**Comment by zanhsieh** [comment]
/test pull-charts-e2e

@mecseid 
Let's give it another try.

**Comment by zanhsieh** [comment]
@vsliouniaev @cpanato 
What you guys think? Cannot find trace-able information in e2e log.

**Comment by cpanato** [comment]
@mecseid i saw this in the logs
```
ping: consul-jrv9nkey01-1.consul-jrv9nkey01.consul-presubmit-18171-1191190275863613440-jrv9nkey01.svc: Name does not resolve
```

are you able to deploy that locally or in a test cluster?

**Comment by lachie83** [comment]
I've also tested this and it doesn't work because of the login in the startup scripts that expect the pod to go ready before proceeding with the restart of the start.

**Pull request closed without merging**
