### PR TITLE
[stable/wordpress] Update ingress api version for k8s 1.16. Signed-of…

### LINKED ISSUE #17727: [stable/wordpress] Ingress wrong apiVersion
**Version of Helm and Kubernetes**:
2.14.3 & 1.15.3

**Which chart**:
[stable/wordpress]

**What happened**:
Ingress is wrong apiVersion for newer Kubernetes versions (>=1.14).  It fails to be created.  Changing `ingress.apiVersion` from `extensions/v1beta1` to `networking.k8s.io/v1beta1` allows ingress to be created.

**Anything else we need to know**:
Can either parameterise `apiVersion:` or [this helper ](https://github.com/helm/charts/blob/c2cdb7602266ed6fbb689193fa0ed109e0e03490/stable/minio/templates/_helpers.tpl#L68)can automate (I've not tested).

### PR DESCRIPTION
**Pull request by circa10a**
#### What this PR does / why we need it:

Make wordpress compatible with k8s 1.16

#### Which issue this PR fixes

  - fixes #17727

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Please, can you take a look at [this comment](https://github.com/helm/charts/issues/17727#issuecomment-538870185) in the attached issue?

**Comment by carrodher** [comment]
I think this PR #17758 encompasses the different cases

**Comment by holmesb** [comment]
Hi @circa10a, I believe this can be closed since #17731 was merged.

**Pull request closed without merging**
