### PR TITLE
[stable/redis] Redis global password support

### LINKED ISSUE #18177: [stable/redis] Read password from globals
It would be very useful to allow redis read password from globals in similar way it is done for stable/postgresql This would allow to easier setting of it in case redis is used as child.

This feature would be helpful in our situation when we are creating Redis as optional dependecy in case we want to use local Redis cache and not some external one.

**Describe the solution you'd like**
Simialar approach as it is in stable/postgresql:
- [password defined in helper](https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl#L81-L91)
- [include password from template](https://github.com/helm/charts/blob/master/stable/postgresql/templates/secrets.yaml#L13)

**Describe alternatives you've considered**
Alternatively I would consider approach used in some other charts where databases are optional dependencies and then there is separate set for internal and external database settings, however for consistency above approach would be prefered by us.

### PR DESCRIPTION
**Pull request by zbikmarc**
#### What this PR does / why we need it:
This PR adds support for password read from globals variables in stable/redis

#### Which issue this PR fixes
  - fixes #18177 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by javsalgar** [comment]
Please fix merge issues. LGTM

**Comment by zanhsieh** [comment]
@zbikmarc 
Would you resolve the file conflict please?
stable/redis/Chart.yaml

**Comment by zbikmarc** [comment]
> @zbikmarc
> Would you resolve the file conflict please?
> stable/redis/Chart.yaml

Done. I did not see notification with messages.

**Pull request merged**
