### PR TITLE
gypsydiver/cluster autoscaler trim down psp

### PR DESCRIPTION
**Pull request by gypsydiver**
#### What this PR does / why we need it:

Current PSP is rather broad, this PR trims it down.

#### Special notes for your reviewer:

Supersedes  #15016

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by gypsydiver** [comment]
@yurrriq

**Review by yurrriq — APPROVED** [review]
/lgtm

**Comment by yurrriq** [comment]
Thanks!

**Pull request merged**
