### PR TITLE
[stable/keycloak] Add option to specify extra init containers

### LINKED ISSUE #4633: Adding custom keycloak theme for chart
FEATURE REQUEST

I think we need the possibility to add a configurable PVC in order to be able to provide custom keyloack themes to the deployments. 

At least I don't know a better way for providing a custom theme. Don't want to build a custom keycloak image in order to do so. :/
 
**Which chart**:

Keycloak

**What happened**:

Theme not configurable as theres no optional mount point in the chart

### PR DESCRIPTION
**Pull request by unguiculus**
**What this PR does / why we need it**:

Adds the option to configure extra init containers which could be used as providers for installing additional components such as themes.

**Which issue this PR fixes**:

Fixes #4633

### CODE REVIEW

**Comment by unguiculus** [comment]
Please review: @nexeck @clkao @Flowkap

**Comment by scottrigby** [comment]
Just want to also relate to this issue #4283

**Pull request merged**
