### PR TITLE
[stable/prometheus-operator] Fix readme typos

### PR DESCRIPTION
**Pull request by OlegPS**
Signed-off-by: Oleg Selin <oleg.selin@gmail.com>

#### What this PR does / why we need it:
Just fix typos in kubeEtcd parameters

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by OlegPS** [comment]
Should we really bump version with readme change?

**Comment by paskal** [comment]
It's a requirement, so yes, version should be bumped even for this small change.

**Comment by OlegPS** [comment]
Nice, thanks for clarification! Yes, values.yaml is OK.

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
