### PR TITLE
[stable/prometheus-adapter] Allow prometheus-adapter to start in hostNetwork mode

### PR DESCRIPTION
**Pull request by mfamador**
#### What this PR does / why we need it:
Allow prometheus-adapter to start in hostNetwork mode, needed when we use an alternate overlay networking, like Weave CNI on EKS, for instance.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mfamador** [comment]
ping

**Review by hectorj2f — CHANGES_REQUESTED** [review]
it needs a rebase to solve conflicts

**Pull request merged**
