### PR TITLE
Adding myself to maintainers

### PR DESCRIPTION
**Pull request by lizrice**
#### What this PR does / why we need it:
Adding myself as suggested by @desaintmartin (since I'm a maintainer for kube-hunter itself)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Hello,
Can you signoff the commit and bump a patch version of the chart? See the README and CONTRIBUTING.md of this repo.

**Comment by lizrice** [comment]
@desaintmartin sorry, I misread the thing about signing (thought GPG signing was sufficient, but that was just me not paying enough attention!) Hope I got the version bump right?

**Comment by desaintmartin** [comment]
All good! don't hesitate to ping me in case of doubts in PRs for kube-hunter.
/lgtm
/approve

**Pull request merged**
