### PR TITLE
[stable/minio]: Add additional owners for MinIO Chart

### PR DESCRIPTION
**Pull request by nitisht**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by wlan0 — APPROVED** [review]

**Comment by nitisht** [comment]
@cpanato can you please help us add `krisis` and `harshavardhana` to the Helm org please

**Comment by maorfr** [comment]
added both as trusted collaborators

**Comment by nitisht** [comment]
Thanks @maorfr . Could you pls approve the PR

**Comment by maorfr** [comment]
why are you removing maintainers from Chart.yaml? i'd expect new maintainers to be added rather then existing ones deleted...

**Comment by nitisht** [comment]
@maorfr dev@minio.io is a group with all the MinIO devs, so i figured it’s redundant adding individual email ids

**Comment by nitisht** [comment]
ping @maorfr

**Pull request merged**
