### PR TITLE
stable/chart/mongodb-replicaset OpenSSL fix and infinit loop fix

### PR DESCRIPTION
**Pull request by ecbois**
#### What this PR does / why we need it:
What happened: When creating the client certificate for the replica set member Openssl throws: unable to write 'random state'

I solved this issue by setting the RANDFILE environment variable in the 'on-start.sh' script when using ssl like below.

Other issue when using SSL and trying to start mongodb, if the mogodb client is not able to connect to the server when testing if mongodb is up, it will wait for ever. Added a counter to avoid the loop

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [x ] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @steven-sheehy

**Review by unguiculus — CHANGES_REQUESTED** [review]
Thanks for the PR. Please fix DCO and correct the indentation in your changes.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
> Other issue when using SSL and trying to start mongodb, if the mogodb client is not able to connect to the server when testing if mongodb is up, it will wait for ever. Added a counter to avoid the loop

It is not an infinite loop. It uses a bash timer to wait for 15 minutes because MongoDB needs a long time to recover when shutdown suddenly. Having a counter and a timer is duplicative and makes the timer now inaccurate. I would say remove the counter you added.

**Comment by ecbois** [comment]
> > Other issue when using SSL and trying to start mongodb, if the mogodb client is not able to connect to the server when testing if mongodb is up, it will wait for ever. Added a counter to avoid the loop
> 
> It is not an infinite loop. It uses a bash timer to wait for 15 minutes because MongoDB needs a long time to recover when shutdown suddenly. Having a counter and a timer is duplicative and makes the timer now inaccurate. I would say remove the counter you added.

Noted. however, when deploying in Azure Kubernetes Services, if your deployment is faulty, 15 minutes is too long, aks stop your deployment and you can't retrieve any logs because of that. I will remove my counter, but maybe this should be an input parameter somehow

**Comment by ecbois** [comment]
> DCO

Sorry what is DCO? did you mean the doc?

**Comment by steven-sheehy** [comment]
> Noted. however, when deploying in Azure Kubernetes Services, if your deployment is faulty, 15 minutes is too long, aks stop your deployment and you can't retrieve any logs because of that. I will remove my counter, but maybe this should be an input parameter somehow

It is: `init.timeout`

> Sorry what is DCO? did you mean the doc?

Please ensure all GitHub [checks](https://github.com/helm/charts/pull/16655/checks?check_run_id=205712624) pass. DCO is one of them.

**Comment by PierreBrisorgueil** [comment]
error RANDFILE still present, too bad to let the PR closed

**Pull request closed without merging**
