### PR TITLE
Kiam update 3.2

### PR DESCRIPTION
**Pull request by mehstg**
#### What this PR does / why we need it:
Updates chart to latest KIAM version v3.2
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [x ] Variables are documented in the README.md

@ewbankkit

### CODE REVIEW

**Comment by cpanato** [comment]
@mehstg please sign the DCO

**Comment by mehstg** [comment]
@cpanato  DCO signed

**Comment by mehstg** [comment]
@mattfarina @foxish

**Comment by mehstg** [comment]
Is anyone maintaining this chart anymore?

**Comment by cpanato** [comment]
@mehstg sorry for the delay

**Review by cpanato — APPROVED** [review]

**Pull request merged**
