### PR TITLE
Simplify  for unifi

### PR DESCRIPTION
**Pull request by wernerb**
#### What this PR does / why we need it:
This merges the three services into one, letting you have one service (ClusterIP or LoadBalancer, NodePort) that has all ports necessary for proper communication with UAPs.

The problem now is that with each Service you get a different clusterIP (or expensive LoadBalancer) while actually Unifi requires the `8080:/inform`, `stun`, and `discovery` to be on the same interface. (Same as upstream docker). 
Unifi can't reach stun port right now because its on a different IP, or with NodePort on a different port.  NodePort can still work but its also easier through a single service.

Unifi also has no separate IP binding for these ports meaning they are all expected to run off the same IP.

In fact, if the maintainer allows it, we can also remove the controllerService and move everything in one service with multiple named ports.

Signed-off-by: Werner Buck <email@wernerbuck.nl>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
This is a very welcome simplification, thank you @wernerb!

As the nature of the change isn't backwards-compatible with the current chart, can we please bump the minor semver version? (e.g. to 0.3.0)

**Comment by billimek** [comment]
@wernerb Sorry I didn't address the original question earlier, but agree that a single service for all the things (gui, controller, discovery, stun) makes more sense.  Is this something you're willing to include in this PR?

**Comment by bootc** [comment]
This merge breaks my UniFi deployment, please see #11268.

**Pull request merged**
