### PR TITLE
[stable/prometheus-postgres-exporter] Add prometheusrule support

### PR DESCRIPTION
**Pull request by DaveOHenry**
#### What this PR does / why we need it:
This just adds support for creation of "prometheusRule" objects that can be used by Prometheus Operator. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DaveOHenry** [comment]
ping

**Comment by DaveOHenry** [comment]
ping
    


-------- Ursprüngliche Nachricht --------
Von: "stale[bot]" <notifications@github.com> 
Datum: 03.05.2020  16:18  (GMT+01:00) 
An: helm/charts <charts@noreply.github.com> 
Cc: David Heinrich <David.Heinrich@cortado.com>, Mention <mention@noreply.github.com> 
Betreff: Re: [helm/charts] [stable/prometheus-postgres-exporter] Add prometheusrule support (#21096) 



This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by zanhsieh** [comment]
@DaveOHenry 
Could you resolve the conflict list on bottom of this PR page?

**Comment by DaveOHenry** [comment]
ping
    


-------- Ursprüngliche Nachricht --------
Von: "stale[bot]" <notifications@github.com> 
Datum: 03.06.2020  17:01  (GMT+01:00) 
An: helm/charts <charts@noreply.github.com> 
Cc: David Heinrich <David.Heinrich@cortado.com>, Mention <mention@noreply.github.com> 
Betreff: Re: [helm/charts] [stable/prometheus-postgres-exporter] Add prometheusrule support (#21096) 



This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by DaveOHenry** [comment]
ping

________________________________
Von: stale[bot] <notifications@github.com>
Gesendet: Freitag, 3. Juli 2020, 17:32
An: helm/charts
Cc: DaveOHenry; Mention
Betreff: Re: [helm/charts] [stable/prometheus-postgres-exporter] Add prometheusrule support (#21096)


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.

**Comment by DaveOHenry** [comment]
ping

________________________________
Von: stale[bot] <notifications@github.com>
Gesendet: Sonntag, 2. August 2020, 22:00
An: helm/charts
Cc: DaveOHenry; Mention
Betreff: Re: [helm/charts] [stable/prometheus-postgres-exporter] Add prometheusrule support (#21096)


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to `stable` prometheus charts for a short time until prometheus-community/community#28 (comment) is resolved. If you want to help with that effort, to test etc, that would be great!

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
