### PR TITLE
Update kube state metrics

### PR DESCRIPTION
**Pull request by jurgenweber**
Here I have updated the prometheus chart to use the latest release of kube-state-metrics. This required some new rbac permissions, etc.

In upgradring and fixing this I ran into this issue in kube-state-metrics: https://github.com/kubernetes/kube-state-metrics/issues/260

### CODE REVIEW

**Comment by jurgenweber** [comment]
I signed the CLA, do I need to commit again to make it pass?

**Comment by woodsae** [comment]
👍

**Review by gyliu513 — COMMENTED** [review]
/lgtm

**Comment by mgoodness** [comment]
Will review ASAP; sorry about the delay.

**Comment by jurgenweber** [comment]
no problems, there is apparently a fix to kube-state-metrics and I will give that a test today/early next week and update this PR. I'll resolve the conflicts also.

**Comment by jurgenweber** [comment]
hhmmm, I rebased... I think that was a bad idea... How do I get rid of the irrelevant commits now? 

not sure why CircliCI is failing either.

**Comment by jurgenweber** [comment]
sorry, I started here: https://github.com/kubernetes/charts/pull/2477

**Pull request closed without merging**
