### PR TITLE
[stable/sentry] add missing user.password docs

### LINKED ISSUE #19344: [stable/sentry] Missing documentation for user.password
**Describe the bug**

The documentation is missing a callout and description for the `user.password` setting.

**Version of Helm and Kubernetes**:

N/A

**Which chart**:

stable/sentry v3.1.5

**What happened**:

N/A

**What you expected to happen**:

Document the use of setting your own Admin password via `user.password` value.

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Dean-Coakley**
* Fixes https://github.com/helm/charts/issues/19344

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Dean-Coakley** [comment]
Does this look good to ye @fl-max @OKNoah ?

**Comment by fl-max** [comment]
> Does this look good to ye @fl-max @OKNoah ?

LGTM

**Comment by okgolove** [comment]
Hi @Dean-Coakley! Thank you for catching and fixing this.

/lgtm

**Pull request merged**
