### PR TITLE
Add basePath option for Jaeger

### LINKED ISSUE #7489: [incubator/jaeger] Add option for specifying basePath
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Jaeger has added a new option to set the base path of the query UI, which makes it usable behind reverse proxies. This option should also be exposed in the chart as well.

PR which added this support: https://github.com/jaegertracing/jaeger/pull/748

### PR DESCRIPTION
**Pull request by lambertjosh**
**What this PR does / why we need it**:

Jaeger has added a new option to set the base path of the query UI, which makes it usable behind reverse proxies. This option should also be exposed in the chart as well.

PR which added this support: https://github.com/jaegertracing/jaeger/pull/748
Docs on set up: https://www.jaegertracing.io/docs/deployment/#ui-base-path

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #7489

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lambertjosh** [comment]
@cpanato thanks for reviewing, the errors in the deploy are unrelated to this PR as they also occur in the current published version. (Probably a change in the cassandra dependency.)

What is the best way to proceed here? Are we blocked from changes until someone fixes whatever issue is going on with cassandra?

**Comment by cpanato** [comment]
@lambertjosh I will try to check later this week what is happening 😄

**Comment by lambertjosh** [comment]
Actually it looks like there is an existing issue here working on the cassandra problem: https://github.com/helm/charts/issues/7407

**Pull request closed without merging**
