### PR TITLE
[stable/spinnaker] Provide a method to inject additional configuration into the gate.

### PR DESCRIPTION
**Pull request by CerealBoy**
#### What this PR does / why we need it:

There are times when injecting additional data into the configuration for the gate is a requirement, such as setting environment variables spinnaker/spinnaker#2695. This change will provide a value configuration to allow for this.

#### Which issue this PR fixes

N/A.

#### Special notes for your reviewer:

The new value name was selected at the top level, mainly as this affects the ``service-settings.yaml`` component and doesn't fit under another (though a new top-level could be selected instead if desired).

Pinging @viglesiasce + @lwander + @dwardu89 + @paulczar for review.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by legal90** [comment]
FYI: This is already solved in kinda generic way here: https://github.com/helm/charts/pull/13049

**Comment by CerealBoy** [comment]
@legal90 Whatever lets these settings (and even others beyond) be injected is good for me! When I opened this I hadn't thought to check if anyone else had required the same functionality sorry. I'd be quite happy for your change to supersede this one. Is there anything else that needs to happen for changes to be merged?

**Comment by legal90** [comment]
@CerealBoy Great! 
Unfortunately (as I mentioned in https://github.com/helm/charts/pull/13049#issuecomment-490046089) end-to-end tests for the `stable/spinnaker` chart are alway failing, so no PRs could be merged at this moment. 
I tried to reproduce it internally, but did not succeed - the chart works just fine 🤔

**Comment by CerealBoy** [comment]
Closing this PR in favour of #13049 

We can look at why and resolve the e2e-test execution there. At first glance, the booting of the Front50Service appears to be failing which is causing the test to fail (as the chart isn't being properly successfully and completely deployed). This is also the case for my local deployment (``pod/spin-front50-5bfcbff6b7-278wc           0/1     CrashLoopBackOff   1644       6d``).

**Pull request closed without merging**
