### PR TITLE
[stable/cockroachdb] labels for cockroachdb service

### PR DESCRIPTION
**Pull request by paepke**
Signed-off-by: Tobias Paepke <tobias.paepke@paepke.net>

#### What this PR does / why we need it:
It allows labels to be set for the service and internal service-discovery.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DuskEagle** [comment]
Is there a use case for having separate labels for service-discovery and service? It might be simpler to use the same set of labels on both.

**Comment by paepke** [comment]
> Is there a use case for having separate labels for service-discovery and service? It might be simpler to use the same set of labels on both.

Using a ServiceMonitor from "CoreOS Prometheus Operator" its good to have only the non-public service labeled to be selected via the labels.
I'm pretty sure there are other situations where you want to label only the public or the non-public service.

**Comment by DuskEagle** [comment]
> > Is there a use case for having separate labels for service-discovery and service? It might be simpler to use the same set of labels on both.
> 
> Using a ServiceMonitor from "CoreOS Prometheus Operator" its good to have only the non-public service labeled to be selected via the labels.
> I'm pretty sure there are other situations where you want to label only the public or the non-public service.

Good point. This change looks good to me.
/lgtm
/approve

**Pull request merged**
