### PR TITLE
stable/nginx-ingress: Allow specifying nodePort(s) and bump chart version to 0.3.1

### PR DESCRIPTION
**Pull request by chancez**

### CODE REVIEW

**Comment by chancez** [comment]
CC @mgoodness and @jackzampolin. Could y'all take a look at this?

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Comment by chancez** [comment]
@mgoodness Is this good? Anything preventing it form being merged?

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Comment by mgoodness** [comment]
@chancez LGTM.

**Comment by chancez** [comment]
@mgoodness who does merges for PRs?

**Comment by prydonius** [comment]
@chancez another maintainer needs to pass through LGTM'd to merge, see the process outlined in https://github.com/kubernetes/charts#review-process.

**Pull request merged**
