### PR TITLE
[stable/prometheus-operator] Added supports of ServiceAccount annotation in alertmanager

### PR DESCRIPTION
**Pull request by pburgisser**
Signed-off-by: Philippe Bürgisser (Camptocamp) <philippe.burgisser@camptocamp.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by pburgisser-c2c** [comment]
Hello @vsliouniaev,

Is the test broken ? It's producing a timeout. 
I'm not sure if it's the test iteself or my work.

Thanks

**Comment by vsliouniaev** [comment]
The test cluster is in a bad state and constantly breaks. There's nothing I can really do about it.

**Comment by scottrigby** [comment]
Resolved merge conflicts in order to retest fixed ci infra
/lgtm

**Pull request merged**
