### PR TITLE
fix some grammar mistakes

### PR DESCRIPTION
**Pull request by jonyhy96**
fix some grammar mistakes
```release-note
None
```

### CODE REVIEW

**Comment by lachie83** [comment]
Thanks @jonyhy96. Thanks for the contrib. You need to bump the chart version in each corresponding chart

**Comment by jonyhy96** [comment]
@lachie83 
Thanks for your reply and i already bump the chart version in each corresponding chart.
Please check this out.
Thank you

**Comment by jonyhy96** [comment]
Some mistakes already been fixed
close it.

**Pull request closed without merging**
