### PR TITLE
[stable/rabbitmq] Log to stdout and add metrics exporter

### PR DESCRIPTION
**Pull request by javsalgar**
#### What this PR does / why we need it:
This enables rabbitmq to be used with monitoring and logging tools (ELK, EFK, Prometheus)
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks for this great contribution!

**Comment by desaintmartin** [comment]
Is there any reason to use https://github.com/kbudde/rabbitmq_exporter instead of what is already used in rabbitmq-exporter (https://github.com/justwatchcom/elasticsearch_exporter) ? The first one seems really slow and often make probes to fail even with 5s timeout.

**Pull request merged**
