### PR TITLE
[stable/jenkins] Add support for custom ClusterIP

### PR DESCRIPTION
**Pull request by ghost**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by torstenwalter — COMMENTED** [review]
This looks good to me. Could you add an entry in `CHANGELOG.md`  and rebase on master?

**Comment by torstenwalter** [comment]
@fleeteo Can you fix the merge it with master? Please ping me once it's done.

**Comment by fleeteo** [comment]
@torstenwalter Done

**Pull request merged**
