### PR TITLE
[stable/grafana] Add Traefik's 2 IngressRoute support

### PR DESCRIPTION
**Pull request by zorgzerg**
#### What this PR does / why we need it:
This PR added to grafana chart Traefik's 2 IngressRoute support

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
/hold
@zorgzerg 
I don't think adding specific ingress vendor and occupied the **ingress** are a good idea. Think about if someone later would like to add nginx, nginxc, kong, ambassador, etc. as ingress vendor, what should that do with Grafana? How the ingress syntax get changed?

**Comment by zorgzerg** [comment]
@maorfr
Hi, PR is ready to approve

**Comment by zorgzerg** [comment]
> /hold
> @zorgzerg
> I don't think adding specific ingress vendor and occupied the **ingress** are a good idea. Think about if someone later would like to add nginx, nginxc, kong, ambassador, etc. as ingress vendor, what should that do with Grafana? How the ingress syntax get changed?

Just, everyone can activate the ingress that he needs. It seems to me convenient, no need to write additional YAML-files. All in one chart. 

In addition, this does not break the performance of chart components. I see no good reason for your refusal

**Comment by zanhsieh** [comment]
> > /hold
> > @zorgzerg
> > I don't think adding specific ingress vendor and occupied the **ingress** are a good idea. Think about if someone later would like to add nginx, nginxc, kong, ambassador, etc. as ingress vendor, what should that do with Grafana? How the ingress syntax get changed?
> 
> Just, everyone can activate the ingress that he needs. It seems to me convenient, no need to write additional YAML-files. All in one chart.
> 
> In addition, this does not break the performance of chart components. I see no good reason for your refusal

Then you need to change the code to let users choose which ingress vendor they want, not occupy it by default.

**Comment by zorgzerg** [comment]
> > > /hold
> > > @zorgzerg
> > > I don't think adding specific ingress vendor and occupied the **ingress** are a good idea. Think about if someone later would like to add nginx, nginxc, kong, ambassador, etc. as ingress vendor, what should that do with Grafana? How the ingress syntax get changed?
> > 
> > 
> > Just, everyone can activate the ingress that he needs. It seems to me convenient, no need to write additional YAML-files. All in one chart.
> > In addition, this does not break the performance of chart components. I see no good reason for your refusal
> 
> Then you need to change the code to let users choose which ingress vendor they want, not occupy it by default.

ingressRoute id disabled by default

See 144 string in values.yaml from commit

**Comment by zanhsieh** [comment]
@maorfr 
What do you think?

**Comment by sbuzonas** [comment]
I wrap my charts to provide IngressRoutes, it would be nice to see charts have traefik as an alternative to the standard ingress.

One problem with this PR is that entrypoints are TLS or not, never mixed.  It would need two IngressRoute resources one for TLS and one without, then two entrypoint arrays one for each.  Not to mention, a TLS route often has a non-TLS counterpart that is simply a redirect middleware to the TLS entrypoint, which is another potential condition case.

My opinion is that there are a number of ingress controllers that define their own CRDs for good reasons. If the reasoning is that `ingress.networking.k8s.io` isn't adequate, they should be engaging to improve the SIG; and/or providing an operator to transform ingress annotations into their custom resources.

**Pull request closed without merging**
