### PR TITLE
add optional serviceAccountName

### PR DESCRIPTION
**Pull request by anandkumarpatel**
Add serviceAccount variable for cases were RBAC is enabled and we need to allow mounting of docker socket.

reopening https://github.com/kubernetes/charts/pull/2445 after fixing cla issue

### CODE REVIEW

**Review by timstoop — CHANGES_REQUESTED** [review]
As charts are immutable, every change requires a bump of the version in Chart.yaml.

**Comment by sameersbn** [comment]
@anandkumarpatel could you please fix the issues with the `helm  lint` tests 

```
Running helm lint on the chart at stable/spotify-docker-gc
==> Linting stable/spotify-docker-gc
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: parse error in "spotify-docker-gc/templates/daemonset.yaml": template: spotify-docker-gc/templates/daemonset.yaml:40: unexpected EOF
```

**Comment by anandkumarpatel** [comment]
Fixed!

**Pull request merged**
