### PR TITLE
[stable/kubernetes-dashboard] Update deploy apiVersion to apps/v1

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What this PR does / why we need it:
From v1.14 chagelog:
> DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

This chart is using from example apiVersion `policy/v1beta1` which is available from v1.10. `apps/v1` is available since v1.9.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by kfox1111 — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@kfox1111 , fixed the test

**Pull request merged**
