### PR TITLE
Add Jenkins Kubernetes plugin service account and CRB for RBAC enabled clusters

### LINKED ISSUE #1092: Jenkins deployment with Kubernetes plugin does not have cluster access using RBAC
I've deployed the Jenkins chart that comes bundled with the Jenkins Kubernetes plugin but the plugin needs cluster access to create it's test pods.

Since the chart is deployed with the default serviceaccount, I need to grant full access to all serviceaccounts to the cluster with the command:

`kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts`

It would be better if Jenkins could be deployed with a specific account and grant the cluster-admin role just to it.

### PR DESCRIPTION
**Pull request by lachie83**
Closes #1092

### CODE REVIEW

**Comment by lachie83** [comment]
cc @viglesiasce

**Comment by viglesiasce** [comment]
@lachie83 can you automate the part of configuring the K8s plugin? Is it possible to just add this to the config.xml with an if block?

**Comment by lachie83** [comment]
@viglesiasce I thought about doing this but it's dependent on the creation of a service account which is stored in credentials.xml then the Kubernetes plugin references that name. Not sure how I feel about doing that. Thoughts?

**Comment by viglesiasce** [comment]
Merged in #1385

**Pull request closed without merging**
