### PR TITLE
[stable/mysql] The password values in values.yaml should be provided as base64

### PR DESCRIPTION
**Pull request by komljen**
If the user wants to provide its own passwords they should be base64 encoded in values.yaml file and not kept in clear text.

### CODE REVIEW

**Comment by komljen** [comment]
cc @viglesiasce

**Comment by prydonius** [comment]
IMO base64 is not much better than plain text and this will degrade the UX. The fact that tiller stores values in plain text is a separate issue and can be solved by configuring tiller to use a secret store.

**Comment by komljen** [comment]
I pretty much agree. Autogenerated passwords are better, but the issue is that on helm upgrade the new passwords are generated. Not sure how to work around this...

UPDATE: I created a new pull request to not recreate passwords on helm upgrade https://github.com/kubernetes/charts/pull/3494

That seems like a better idea and then we could close this one.

**Comment by komljen** [comment]
Closing this pull request in favor of https://github.com/kubernetes/charts/pull/3591

**Pull request closed without merging**
