### PR TITLE
[stable/prometheus] Use the new api for ingress

### PR DESCRIPTION
**Pull request by adberger**
This PR will use the new api for ingressnetworking.k8s.io/v1beta1 to avoid getting extensions/v1beta1/Ingress is deprecated by networking/v1beta1/Ingress and not supported by Kubernetes v1.20+ clusters. message after installing the chart

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@adberger 
Could you rebase this PR to 10.5.2 please? Thank you.

**Comment by adberger** [comment]
> @adberger
> Could you rebase this PR to 10.5.2 please? Thank you.

Set to 10.5.3 because 10.5.2 is already in master

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@adberger 
Could you resolve the conflicting of 'stable/prometheus/Chart.yaml' please? Thank you.

**Comment by adberger** [comment]
> @adberger
> Could you resolve the conflicting of 'stable/prometheus/Chart.yaml' please? Thank you.

Now it should be fine :)

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
