### PR TITLE
[incubator/sparkoperator] Move webhook hooks from post to pre

### PR DESCRIPTION
**Pull request by kiall**
#### What this PR does / why we need it:

The spark webhook init job was set to run post install/upgrade, however when
`--wait` is in use, Helm will wait for the Deployment to be ready before it
starts the post-install hook, which will never become ready as it's awaiting
the certificate generated by the hook.

#### Which issue this PR fixes

No issue filed

#### Checklist

- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by yuchaoran2011 — CHANGES_REQUESTED** [review]
This won't work because the init job uses the `sparkoperator.serviceAccountName`, which is created during installation. If run as a pre-install step, the job won't be able to find the service account.

**Comment by kiall** [comment]
> This won't work because the init job uses the `sparkoperator.serviceAccountName`, which is created during installation. If run as a pre-install step, the job won't be able to find the service account.

You're absolutely right - I had some leftover pieces from my earlier tests which made this work.

I see two possible ways forward:

1) Avoid generating the cert in a hook, instead use an init container on the operator deployment. This might require changes to the `gencerts.sh` to ensure it's idempotent, and to ensure that when scaling out, we don't end up with N different certs being generated in a race.

2) Create a dedicated SA/Role/RoleBinding as a pre-install hook, and switch to having the init job use that. I quickly mocked this up as it's seems preferable to be https://pastebin.com/bHQBBW8k (Note - that needs some cleanup... if the approach is OK, I'll cleanup and submit)

When using this approach the SA, Role, RoleBinding, Job are all created during the pre-install phase. Once the Job completes, all 4 resources are deleted and then the operator Deployment and usual SA, Role, etc are created.

Thoughts?

**Comment by yuchaoran2011** [comment]
I like your first suggestion better. It seems cleaner. The second approach is fine too. Feel free to submit your changes and then I'll review and test them later today.

**Pull request closed without merging**
