### PR TITLE
[stable/concourse] Allow the use of a specific image digest 

### PR DESCRIPTION
**Pull request by topherbullock**
This allows testing release against `concourse/dev` images without having to tag them.

The Concourse team is hoping to automate our [CI/CD pipelines](https://ci.concourse-ci.org/teams/main/pipelines/concourse) to use the digest of the image produced upstream to test against the Helm Chart.

Signed-off-by: Topher Bullock <cbullock@pivotal.io>

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
> ( not sure `imageDigest` is something anyone other than Concourse devs will want / use, so I left it undocumented )

### CODE REVIEW

**Comment by topherbullock** [comment]
@william-tran looks like I had to bump the chart version; rebased from helm master and bumped it.

**Comment by william-tran** [comment]
@topherbullock lets bump minor since this is a new feature

**Comment by topherbullock** [comment]
@william-tran Bumped the version to 2.1.0

**Review by william-tran — APPROVED** [review]

**Pull request merged**
