### PR TITLE
[stable/jenkins] enable xml config misspelling

### PR DESCRIPTION
**Pull request by danielllek**
Signed-off-by: Daniel Fenert <daniel.fenert@g2a.com>

#### What this PR does / why we need it:
Misspelling in template (enabledXmlConfig -> enableXmlConfig)

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by bergemalm** [comment]
I also see some issues where {{- end }}'s for `enableXmlConfig` are in wrong places. Should I create new pr for it?
Example:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L258-L274

**Comment by danielllek** [comment]
> I also see some issues where {{- end }}'s for `enableXmlConfig` are in wrong places. Should I create new pr for it?
> Example:
> https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L258-L274

@bergemalm I'm afraid I don't see it :-/

**Comment by bergemalm** [comment]
> > I also see some issues where {{- end }}'s for `enableXmlConfig` are in wrong places. Should I create new pr for it?
> > Example:
> > https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L258-L274
> 
> @bergemalm I'm afraid I don't see it :-/

In our use case we use jcasc only with `enableXmlConfig` set to false. With current merged changes it won't mount /var/jenkins_secrets and /var/jenkins_jobs causing secrets vars to fail (set to empty).

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Comment by torstenwalter** [comment]
> > > I also see some issues where {{- end }}'s for `enableXmlConfig` are in wrong places. Should I create new pr for it?
> > > Example:
> > > https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L258-L274
> > 
> > 
> > @bergemalm I'm afraid I don't see it :-/
> 
> In our use case we use jcasc only with `enableXmlConfig` set to false. With current merged changes it won't mount /var/jenkins_secrets and /var/jenkins_jobs causing secrets vars to fail (set to empty). @danielllek

I would not mount `credentialsXmlSecret` and `jobs` as both configure things via XML.
- `jobs` - job definitions done via XML:
   https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L190-L192
- `credentialsXmlSecret`
  https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L183-L184

I agree that `secretsFilesSecret` should be mounted. It also needs to be changed in https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L351-L367
Anyone volunteering for a PR?

And thanks for the feedback!

**Comment by bergemalm** [comment]
> I agree that `secretsFilesSecret` should be mounted. It also needs to be changed in https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L351-L367
> Anyone volunteering for a PR?
> 
> And thanks for the feedback!
Exactly what I meant!
I can do it.
@torstenwalter

**Pull request merged**
