### PR TITLE
[stable/datadog] Support DD_APM_ANALYZED_SPANS

### PR DESCRIPTION
**Pull request by laithalissa**
Update daemonset and deployment to support .Values.datadog.apmAnalyzedSpans,
setting DD_APM_ANALYZED_SPANS in the container environment.

Signed-off-by: Laith Alissa <laithalissa@gmail.com>

#### What this PR does / why we need it:
To get trace logging working for your application, you need to be able to set analyzed spans, the agent supports config through env vars, hence we support the .Value and pass it to the relevant env var.

#### Special notes for your reviewer:
I hope you're having a good day.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by laithalissa** [comment]
Anything holding up approval?

**Comment by laithalissa** [comment]
Reopening to see it it pulls in my rebase

**Comment by eric-cancil** [comment]
Also looking for this.

**Comment by wuservices** [comment]
@xvello or @hkaj would you be able to take a look? I'm trying to add analyzed spans to get app analytics on child spans as directed by support, but don't think I can set things up without this.

**Comment by wuservices** [comment]
@laithalissa @eric-cancil I think you can work around by setting the `DD_APM_ANALYZED_SPANS` [env variable](https://docs.datadoghq.com/tracing/guide/app_analytics_agent_configuration/?tab=docker#pagetitle)

**Pull request closed without merging**
