### PR TITLE
[stable/velero] Add priority classes

### PR DESCRIPTION
**Pull request by branttaylor**
Signed-off-by: Brant Taylor <brant.taylor@lifeway.com>

#### What this PR does / why we need it:

Adds pod priority classes to both Velero and Restic. This will help cluster admins ensure that pods for both Velero and Restic are available and can evict a lower-priority pod if needed.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@branttaylor 
Could you resolve the conflicting file please? 
stable/velero/Chart.yaml

**Comment by branttaylor** [comment]
@zanhsieh This is now resolved

**Comment by zanhsieh** [comment]
@branttaylor 
CRD cleanup failed:
```
I1030 08:39:40.928] Error: customresourcedefinitions.apiextensions.k8s.io "podvolumerestores.velero.io" already exists
```
You might consider to look at other charts (e.g. prometheus-*) to create some hook to clean up this  resource.

**Comment by nrb** [comment]
@zanhsieh We have a CRD clean up hook at https://github.com/helm/charts/blob/master/stable/velero/templates/cleanup-crds.yaml

**Comment by branttaylor** [comment]
Sorry, I'm a little new to this process. The CRD cleanup seems to have nothing to do with my PR. Is this a buggy test? I'd like to do what I can to move this forward, so just let me know how I can help!

**Comment by hectorj2f** [comment]
@branttaylor tests are still failing

**Comment by zanhsieh** [comment]
@branttaylor @nrb 
I saw the suspected CRD is 'podvolumerestores', whereas CRD cleanup covers:
- restore
- backup
- backupstoragelocation
- volumesnapshotlocation

The suspected CRD does not appear on the list, although it still has one (Does it cover anything created by this chart? If so, why not just one line and kill all?)
```
kubectl delete crd -l helm.sh/chart={{ include "velero.chart" . }}
```
I am not sure. That's why I silence myself.

**Comment by branttaylor** [comment]
@hectorj2f @nrb 
can someone help with getting the test to clean up CRDs properly?

**Comment by zanhsieh** [comment]
@branttaylor 
Actually you could do it yourself. Just change 

stable/velero/templates/cleanup-crds.yaml

Append this after line 35:

```
              kubectl delete podvolumerestores --all;
```

And commit then call '/test pull-charts-e2e'.

**Comment by branttaylor** [comment]
@zanhsieh 
That makes sense, thanks for the guidance! I just made that change and it looks like the tests ran successfully.

@hectorj2f 
Can you review now?

**Pull request merged**
