### PR TITLE
[stable/prometheus] Fix rollingUpdate: null indentation Recreate

### PR DESCRIPTION
**Pull request by swarkentin**
#### What this PR does / why we need it:
Fixes indentation from capability introduced in https://github.com/helm/charts/pull/21289

#### Special notes for your reviewer:
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by patricklucas** [comment]
@swarkentin I think this change broke the chart for Helm 3:

```
$ helm3 template prometheus stable/prometheus --version 11.1.0 --set server.strategy.type=Recreate
    <snip> (it works)
$ helm3 template prometheus stable/prometheus --version 11.1.1 --set server.strategy.type=Recreate
Error: YAML parse error on prometheus/templates/server-deployment.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context
```

Helm 2 appears to work:

```
$ helm fetch stable/prometheus --version 11.1.0
$ helm template prometheus-11.1.0.tgz --set server.strategy.type=Recreate
    <snip> (it works)
$ helm fetch stable/prometheus --version 11.1.1
$ helm template prometheus-11.1.1.tgz --set server.strategy.type=Recreate
    <snip> (it works)
```

**Comment by swarkentin** [comment]
@patricklucas yes you are right! Looks like the template is treated differently between helm 2 and helm 3. This may be due to https://github.com/helm/helm/issues/3470

I have added a PR to resolve this https://github.com/helm/charts/pull/21989

Thank you!

**Comment by patricklucas** [comment]
Great, thanks for the quick response!

**Pull request merged**
