### PR TITLE
[stable/nginx-ingress] Upgrade Image 0.9.0-beta.7

### PR DESCRIPTION
**Pull request by krisnova**
We need this image for TLS passthrough in the nginx ingress controller.

### CODE REVIEW

**Comment by linki** [comment]
@prydonius Can we somehow start supporting the new version of nginx-ingress controller?

I see three options
* Just update and use it as `stable/nginx-ingress`
* Create another chart called `stable/nginx-ingress-beta`
* (Mis)use the incubator track for beta releases as `incubator/nginx-ingress`

**Comment by rimusz** [comment]
@linki not sure the support/new chart is needed at all, just using:
 `--set controller.image.repository.tag="0.9.0-beta.7"` 
should work just fine

**Comment by so0k** [comment]
correct - here is an example of using the latest nginx-ingress image to set proxy-body-size - https://github.com/honestbee/public-charts/tree/portus/stable/portus#ingress-controller

**Comment by unguiculus** [comment]
@linki Support for 0.9 has already been added. There's no need for a separate chart. See https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L35-L39.

**Comment by unguiculus** [comment]
@kris-nova Please bump the chart version.

**Comment by linki** [comment]
@unguiculus I see, great. However, this should be a minor bump to the chart version then, right?

**Comment by unguiculus** [comment]
@linki You mean 0.5.0? I guess that would make sense.

**Review by prydonius — APPROVED** [review]
thanks @kris-nova!

**Comment by seanknox** [comment]
Just saw this—stoked TLS passthrough with nginx is possible now!

**Pull request merged**
