### PR TITLE
[stable/hackmd] - enable db port to be configurable

### PR DESCRIPTION
**Pull request by ajbosco**
#### What this PR does / why we need it:
The database port is hardcoded in this chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@ajbosco 
Could you sign DCO please? Thank you.

**Comment by ajbosco** [comment]
> @ajbosco
> Could you sign DCO please? Thank you.

All set now.

**Pull request closed without merging**
