### PR TITLE
[stable/stolon] Add optional pullSecrets

### LINKED ISSUE #8436: [stable/stolon] needs a way to specify pull secrets so the image can come from a private registry
If you try to make a custom image stored on a private repository, there is no way in the chart to specify the secret to pull the image with.

**Version of Helm and Kubernetes:** helm 2.9.1, and Kubernetes 1.11.3

**Which chart:** stable/stolon

**What happened:** Unable to pull an image from a private repository with a password.

**What you expected to happen:** I expected to be able to use a custom image pulled from a private repository, specifying the pullSecrets as a value

### PR DESCRIPTION
**Pull request by francois-travais**
#### What this PR does / why we need it:

Add optional pullSecrets to `values.yaml` in order to use images in private docker registries.

#### Which issue this PR fixes

  - fixes #8436 

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rimusz** [comment]
please remove conflict in `Chart.yaml` changing  to `appVersion: 0.12.0`

**Comment by francois-travais** [comment]
done.

**Pull request closed without merging**
