### PR TITLE
[stable/prometheus-operator] Operator RBAC: move some critical permission to Role

### LINKED ISSUE #19953: [stable/prometheus-operator] Too permissive ClusterRole secret access
**Is your feature request related to a problem? Please describe.**
In file `templates/prometheus-operator/clusterrole.yaml` we use very extensive access to secrets, basically we allow any ServiceAccount bound to this ClusterRole to manipulate all secrets.

```
 - apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*' 
```
Do You think it is possible to limit the acess scope? 

**Describe the solution you'd like**
Limit scope of secret access to requied minimum.

**Describe alternatives you've considered**
If this service needs to read all secrets in whole namespace, maybe we can move this part from ClusterRole to Role and add RoleBinding?  I know that k8s do not allow for cross namespace secret/configmap access but having such ClusterRole just do not feel right.

**Additional context**
I do not think that there is anything else.

Thanks!

### PR DESCRIPTION
**Pull request by miecio45**
#### Is this a new chart
No

#### What this PR does / why we need it:
This PR is an idea for moving part of critical permissions from ClusterRole to Role, as I think that it's not very secure to grant monitoring operator such extensive access.

#### Which issue this PR fixes
  - fixes #19953

#### Special notes for your reviewer:
I really needs Your opinion because maybe it's not the best way to fix those permissions, maybe I'm missing something and this access is really needed.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@miecio45 Please see https://github.com/coreos/prometheus-operator/issues/787. Most people deploy the prometheus-operator as a cluster-wide service, so that's why these permissions are needed.

**Comment by desaintmartin** [comment]
Although I agree with the observation that we should restrict prom-operator,
We probably need a way to restrict prom-operator permissions BUT in an optional and maintainable way.
1/ We should not prevent cluster-wide prometheus-operator for people needing it
2/ We should not overcomplexify the chart

Which makes this problem quite complex.

**Comment by miecio45** [comment]
As I'm still a little scared about giving any software access to all my statefullsets and configmaps, but I can absolutely understand that someone may want to use promethous-operator cluster wide. Maybe we can just parametrize it?

What do You think @bismarck maybe we can add just simple switch to disable those permissions in ClusterRole and add proper Role in the same time? Do you think it will require more changes than that?

**Comment by bismarck** [comment]
@miecio45 I'm okay with adding a switch, but the change isn't trivial.  You would have to take into account the `prometheusOperator.namespaces` and `prometheusOperator.denyNamespaces` configuration parameters.  You would have to create a `Role` and a `RoleBinding` for every namespace you have enabled.

**Comment by miecio45** [comment]
@bismarck In a moment of spare time please take a look, maybe my idea needs to be refined or changed.

**Comment by desaintmartin** [comment]
Should we try a follow-up?

**Comment by miecio45** [comment]
I would love to bring this topic back to life. Should I create issue so that we can discuss possible solution? @bismarck

**Comment by gmartinez-anchor** [comment]
I'm also interested in this. Doesn't feel right to allow access to all secrets in a cluster.

**Pull request closed without merging**
