### PR TITLE
[stable/prometheus-node-exporter] Upgrade to 0.18.0

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

#### What this PR does / why we need it:
Upgrades to latest release

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Review by tariq1890 — APPROVED** [review]
/lgtm

**Comment by davidkarlsen** [comment]
@cpanato ptal?

**Review by cpanato — APPROVED** [review]

**Pull request merged**
