### PR TITLE
Adds support for custom service annotations

### PR DESCRIPTION
**Pull request by strygin**
Signed-off-by: Dmitry Strygin <strygin@gmail.com>

#### What this PR does / why we need it:
This adds the ability to specify custom annotations to the service.
Example:
```
service:
  type: LoadBalancer
  ...
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
    external-dns.alpha.kubernetes.io/hostname: drone.domain.tld.
```

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by christian-roggia** [comment]
Maybe we can add this to the agent and to the server as well? Is there a use case for those two as well?

**Comment by strygin** [comment]
@christian-roggia If you mean deployment controllers, both the agent and the server have `annotations` already, as well as ingress.

**Pull request merged**
