### PR TITLE
[incubator/kafka] Update Zookeeper version to 2.1.0

### PR DESCRIPTION
**Pull request by krichter722**
#### What this PR does / why we need it:
Update Zookeeper version to 2.1.0 which supports Kubernetes 1.16

#### Which issue this PR fixes
./.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by krichter722** [comment]
Hi @zanhsieh, sorry to push another PR, but this one is rather small and just makes and already merged change in zookeeper available. I hope you find the resources to merge this soon.

**Comment by benjigoldberg** [comment]
@krichter722 this lgtm -- just need to fix the conflict

**Pull request closed without merging**
