### PR TITLE
[incubator/drone] Enable adjusting agent replicas

### PR DESCRIPTION
**Pull request by colinhoglund**
This PR enables adjusting the number of agent replicas. However, in order to support the default randomness of the drone shared secret, this also adds a checksum on `secrets.yaml` (as per [this article](https://docs.helm.sh/developing_charts/#automatically-roll-deployments-when-configmaps-or-secrets-change)) to ensure agent and server deployments are updated when the shared secret changes.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @christian-roggia

**Comment by christian-roggia** [comment]
LGTM

**Comment by colinhoglund** [comment]
@unguiculus I believe this PR is now okay to test. Let me know if you anything else from me.

**Pull request merged**
