### PR TITLE
[stable/drone] Fix rpc proto and port & Bump app version to 1.2 

### PR DESCRIPTION
**Pull request by zakkg3**
This pr fixes an issue with RPC connection (agent(s)/jobs to the server).
With no DRONE_RPC_PROTO environment variable the connection to the server was not possible.

It also bumps the app version to 1.2 wichs is extensively tested in an ELK cluster since the release of this version since this release fixes a few bugs.

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zakkg3** [comment]
/assign @christian-roggia
sorry buddy but this is not working without this changes. I did upgrade my deployment to the pr we merge today (2.0.4, the one I cherry pick from a pr we have opened) but this was still missing. Running ok since this morning. so problem fixed :)

**Comment by christian-roggia** [comment]
Is it normal that this PR has changes tracing back to 23 days ago? Is the branch not clean?

**Comment by sasso** [comment]
Anything blocking this PR from getting merged?

**Comment by zakkg3** [comment]
@christian-roggia  > Is it normal that this PR has changes tracing back to 23 days ago? Is the branch not clean?
Dont really know why this is tracing back. Let me know if i can do something else to improve that.
In the meantime, I am using this code, its working so far. and we laso have 4 votes waiting for this to be merged, so if you found it ok we may merge this

**Comment by zakkg3** [comment]
@maorfr can you take a look to this pr? we need to merge this. Thanks :)

**Pull request merged**
