### PR TITLE
[stable/oauth2-proxy] ADD http scheme to values, and template deployment and service

### LINKED ISSUE #17586: [stable/oauth2-proxy] templatify deployment ports for https
**Is your feature request related to a problem? Please describe.**
- `deployment.yaml`: can't add ports, to add an `https` port to the pod.
- `service.yaml` can't specify `targetPort` and `name`, to refer to the `https` port.
- liveness-/readinessProbe in deployment, can't change `port` or `scheme`, to use the added `https` port, and a `https`-scheme.

**Describe the solution you'd like**
- Ability for optional ports on deployment. 
- Updating port reference on service. 
- Change port-name and scheme on liveness-/readinessProbes in deployment

**Additional context**
Istio infers protocols from the actual "name" of the ports on services, so it's nice to be able to configure this to `https` as well when enabling TLS.

### PR DESCRIPTION
**Pull request by figaw**
#### What this PR does / why we need it:
Adds option for using https from the oauth2-proxy pod

#### Which issue this PR fixes
- fixes #17586 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by figaw** [comment]
ping @Miouge1 @desaintmartin

**Review by Miouge1 — APPROVED** [review]
/lgtm

**Comment by figaw** [comment]
We've just realized that `--http-address=0.0.0.0:4180` is specified on the deployment as "commandline arguments" https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/deployment.yaml#L41

So for tls/https you need to add a config that specifies `http-address: ""` and `https-address: "0.0.0.0:4180"` - note the `https`.

**Pull request merged**
