### PR TITLE
[stable/redis-ha] Update redis image + OWNERS file

### PR DESCRIPTION
**Pull request by naseemkullah**
For more info please see release notes for various fixes and improvements: https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES

### CODE REVIEW

**Comment by naseemkullah** [comment]
Hi @ssalaues I'd like to add you to the OWNERS file as you are a code maintainer of this chart, that way you can approve commits moving forward, is that OK?

**Comment by ssalaues** [comment]
@naseemkullah Both updates look good to me. Thank you!

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
thanks @sameersbn

**Pull request merged**
