### PR TITLE
[stable/traefik] Allow setting targetPort for https #885

### PR DESCRIPTION
**Pull request by blackstar257**

### CODE REVIEW

**Comment by blackstar257** [comment]
Retry CLA

**Comment by blackstar257** [comment]
This is also beneficial because AWS will generate certs for you as long as you use them on ELB. They don't let you export them, so getting a BASE64 is impossible.

**Comment by prydonius** [comment]
cc @krancour @c-knowles

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by cknowles** [comment]
`targetPort` is the internal port used by the pod so I can't see a need to customise this. Can you clarify your use case? Perhaps you meant `port` instead which is the external port and the one that would be used by an AWS ELB. In which case it should be done like the other charts, e.g. [gitlab-ce](https://github.com/kubernetes/charts/blob/29f740a719c51b75b7e8b8161d894495dd4e4d3d/stable/gitlab-ce/templates/svc.yaml#L14).

I haven't tried this commit but I believe it customising targertPort won't work since the [deployment](https://github.com/kubernetes/charts/blob/master/stable/traefik/templates/deployment.yaml#L63) still runs on 443 hence the `targetPort` can not be anything apart from 443. See [kube docs](https://kubernetes.io/docs/resources-reference/v1.6/#serviceport-v1-core) for details.

**Comment by krancour** [comment]
Agree with @c-knowles

**Comment by krancour** [comment]
I don't know how I forgot / missed this. It relates to #885.

I'm still not totally crazy about this.

**Comment by cknowles** [comment]
Ah I see. I need to double check our config but we're also terminating the SSL on ELBs and haven't needed to add this. Will come back tomorrow with what we have.

**Comment by krancour** [comment]
@c-knowles are you configuring the ELB manually or through annotations on Traefik's `Service` of `type: LoadBalancer`? I believe the issue in #885 is that the latter is the approach being employed and it doesn't offer sufficient flexibility to account for this.

**Comment by cknowles** [comment]
We are using `type: LoadBalancer`. Here is our relevant config from values.yml sent to Helm:
```
ssl:
  enabled: true
  enforced: true
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: SOME_AWS_CERT_ID
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
```

All the `service.beta.kubernetes.io/aws-load-balance-x` annotations are native to k8s they are not part of this chart.

Setting these values gives you:
1. SSL termination at ELB
1. AWS certificate manager used
1. HTTP->HTTPS redirection using Traefik (since afaik ELBs don't support that out of the box)

Side note, also using [area53](https://github.com/fairfaxmedia/area53) to add the DNS entries for the ELB:
```
service:
  annotations:
    # will end up as traefik.YOUR_AREA53_DOMAIN
    domainName: traefik
  labels:
    # enable area53 to add a route 53 DNS entry
    dns: route53
```

@blackstar257 does this cover your use cases or is there something I missed?

@krancour the only bit I can think of that is missing is if a user would like to disable port 80 on the Service/ELB and not have the http->https redirect.

**Comment by blackstar257** [comment]
@c-knowles 
Im looking to do ELB 443 SSL to Traefik via port 80 

443 HTTPS ELB -> 80 HTTP Traefik -> 80 HTTP Application Service

```
traefik:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: SOME_AWS_CERT_ID
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    https:
      targetPort: 80
```

**Comment by cknowles** [comment]
@blackstar257 ok understood, the use case is similar https://github.com/kubernetes/charts/issues/885 as @krancour said above then. Sorry for my misunderstanding. I suppose if we want to make it harder for users to break the config we could allow the `targetPort` override to only be 443 or 80 as those are the only values that will stand a chance of working given the deployment.yml.

In the future we could maybe flatten the annotations into more concrete options for the Chart but then that would probably take away some of the flexibility.

**Comment by krancour** [comment]
I think this PR really needs to amend the documentation with some insight into why someone might want to do this. I think this is going to be a very rarely used feature and I'd like for users to understand it's for handling an advanced or specialized use case. In the general case, I just would not want users preoccupied with possibly fine-tuning this.

**Comment by viglesiasce** [comment]
@blackstar257 can you update the README as @krancour suggests?

**Comment by blackstar257** [comment]
https://github.com/kubernetes/charts/pull/1017

Changing the way in which im achieving this. I think this will be accepted as a better solution.
@c-knowles 
@krancour

**Pull request closed without merging**
