### PR TITLE
[stable/grafana] Enabling extension of Role and ClusterRole rules.

### LINKED ISSUE #16640: [stable/grafana] Add ability to add additional rules to role and clusterrole
We're trying to add an extra init container to Grafana, and it runs well, except it doesn't have the permissions it needs. There doesn't appear to be any way in the current chart to extend the rules on role or clusterrole, except to create our own serviceprincipal, role, rolebinding, clusterrole, and clusterrolebinding, then use that serviceprincipal by name when deploying Grafana. It'd be ideal if the role and clusterrole just allowed additional rules added through values file additions.

**Is your feature request related to a problem? Please describe.**
Extra init containers that need additional permissions can't extend the deployed role/clusterrole to add those permissions.

**Describe the solution you'd like**
Define additional rules for clusterrole and role through values.

**Describe alternatives you've considered**
We could deploy our own serviceprincipal and all role/clusterrole/bindings needed, but it'd be less ideal, as we'd have an additional set of resources to manage. We'd also need to keep up with any required rules if Grafana ever changes (such as the recent change that added secret-based configuration).

### PR DESCRIPTION
**Pull request by kyschouv**
#### What this PR does / why we need it:
Enables extension of the ClusterRole and Role Rules through Values. This enables `extraInitContainers` to have additional access to Kubernetes APIs they may need without provisioning a completely separate service account for Grafana (which would require all of the RBAC Rules in the default chart Role/ClusterRole as well).

#### Which issue this PR fixes
  - fixes #16640 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by kyschouv** [comment]
Tagging for review: @zanhsieh @rtluckie @maorfr

**Comment by kyschouv** [comment]
How long should I expect for review on this? We'd like to avoid our workaround if we can get this in, but will have to pursue a workaround otherwise.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
