### PR TITLE
[stable/grafana] fix Service name in ingress template

### LINKED ISSUE #4130: [stable/grafana] Service name in ingress depends on old rules
BUG REPORT

**Version of Helm and Kubernetes**:
2.8.2

**Which chart**:
stable/grafana

**What happened**:
If you provide .Release.Name equals to "grafana" during helm install - new rules from _helpers.tpl calculate "grafana.server.fullname" as "grafana" and name field in svc.yaml has value "grafana", obviously. BUT in ingress.yml serviceName calculates with old rules, so we have to change serviceName declaration in ingress.yml from `{{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}` to grafana.server.fullname value.

**What you expected to happen**:
service.name == ingress.spec.rules[*].http.paths[*].backend.serviceName

**How to reproduce it** (as minimally and precisely as possible):
ingress.enabled = true,
uncomment annotations and hosts blocks in values.ingress
 
compare ingress.spec.rules[*].http.paths[*].backend.serviceName(ingress.yml) with service.name(svc.yml) by running helm install with these release names
helm install stable/grafana -n grafana -f values.yml --dry-run --debug
helm install stable/grafana -n graf -f values.yml --dry-run --debug

**Anything else we need to know**:
Nothing

### PR DESCRIPTION
**Pull request by oanogin**
@zanhsieh 

close #4130

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by unguiculus** [comment]
Already fixed in #4121. Thanks.

**Pull request closed without merging**
