### PR TITLE
[incubator/kafka] allow setting statefulset serviceaccount

### PR DESCRIPTION
**Pull request by smcavallo**
#### What this PR does / why we need it:
When hosting custom kafka images where docker auth is required this will allow a service account to be used, which can have a custom image pull secret

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
Many kafka users need to build their own kafka images to inject the cruise-control jars.
This allows them to do that, or just pull their own custom kafka images from a private repo.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X ] Chart Version bumped
- [X ] Variables are documented in the README.md
- [X ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@smcavallo thanks for another useful PR!

/ok-to-test

**Comment by smcavallo** [comment]
/assign @benjigoldberg
(I had to update the version in Chart.yaml - there was a conflict due to another merge to master of this chart)

**Pull request merged**
