### PR TITLE
Delete jobs using kubectl, not helm

### PR DESCRIPTION
**Pull request by valo**
The jobs should be deleted using `kubectl` not `helm`.

### CODE REVIEW

**Comment by valo** [comment]
Wow... All this after a one word change in the `README`?

**Comment by mattfarina** [comment]
@valo I can give you a little background...

1. To contribute anything there is the CNCF CLA that needs to be signed. It's just part of contributing to Kubernetes. Lots of projects have a CLA or a DCO.
1. Kubernetes has a lot of people working on it so there is a fair amount of automation. The automation tries to provide useful feedback. If you have ideas on how to improve that we're open to listening.
1. The testing that isn't in CircleCI uses Kubernetes clusters we operate. There's a gate in there for some security purposes so people don't do bad things like run a bitcoin miner in a pull request.
1. The version bump, which is why circleci is failing, is because we have immutable packages and we do continuous deployment.

I know it's a bit much for a small change and we thank you for the contribution.

**Comment by valo** [comment]
@mattfarina thanks for the clarification. I'll make sure to read more how to get all the things running when I try to contribute a helm chart. I signed the CNCF CLA.

**Pull request merged**
