### PR TITLE
[stable/zeppelin] New Chart for Zeppelin Notebook

### PR DESCRIPTION
**Pull request by danisla**
Chart for Zeppelin Notebook. Also compatible with [Hadoop Chart](https://github.com/kubernetes/charts/pull/1630) for running Spark on YARN.

### CODE REVIEW

**Comment by danisla** [comment]
Ping. Anything blocking this?

**Comment by viglesiasce** [comment]
I wasn't able to get this to work. The zeppelin pod stays in ContainerCreating waiting for the config map to be bound because for some reason the configMap name stays hardcoded to hadoop-hadoop. 

1. Installed stable/hadoop (release name: ideal-koala)
2. Tried to install with: 
```
$ helm install -n zep --namespace charts --set hadoop.useConfigMap=true,configMapName=ideal-koala-hadoop zeppelin
$ kubectl get configmap 
NAME                 DATA      AGE
ideal-koala-hadoop   8         4d
mc-mcrouter          1         4d
$ kubectl describe pod zep-zeppelin-3332132441-j11jn 
Name:		zep-zeppelin-3332132441-j11jn
Namespace:	charts
Node:		gke-junkyard-large-node-v1-4003773f-48p9/10.240.0.2
Start Time:	Fri, 29 Sep 2017 18:07:02 -0400
Labels:		app=zeppelin
		pod-template-hash=3332132441
		release=zep
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"charts","name":"zep-zeppelin-3332132441","uid":"85b23dbd-a562-11e7-8f7e-42010a8a0...
Status:		Pending
IP:		
Created By:	ReplicaSet/zep-zeppelin-3332132441
Controlled By:	ReplicaSet/zep-zeppelin-3332132441
Containers:
  zeppelin:
    Container ID:	
    Image:		dylanmei/zeppelin:0.7.2
    Image ID:		
    Port:		8080/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Limits:
      cpu:	2
      memory:	4Gi
    Requests:
      cpu:	2
      memory:	4Gi
    Readiness:	http-get http://:8080/ delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ZEPPELIN_PORT:		8080
      ZEPPELIN_JAVA_OPTS:	-Dspark.driver.memory=1g -Dspark.executor.memory=1g
      MASTER:			yarn
      SPARK_SUBMIT_OPTIONS:	--deploy-mode client --num-executors 2
    Mounts:
      /usr/hadoop-2.7.3/etc/hadoop from hadoop-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7gsdq (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  hadoop-config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	hadoop-hadoop
    Optional:	false
  default-token-7gsdq:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-7gsdq
    Optional:	false
QoS Class:	Guaranteed
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----							-------------	--------	------		-------
  12s		12s		1	default-scheduler							Normal		Scheduled	Successfully assigned zep-zeppelin-3332132441-j11jn to gke-junkyard-large-node-v1-4003773f-48p9
  12s		12s		1	kubelet, gke-junkyard-large-node-v1-4003773f-48p9			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-7gsdq" 
  12s		4s		5	kubelet, gke-junkyard-large-node-v1-4003773f-48p9			Warning		FailedMountMountVolume.SetUp failed for volume "hadoop-config" : configmaps "hadoop-hadoop" not found
viglesias@viglesias:~/git/charts/stable$ helm ls
NAME       	REVISION	UPDATED                 	STATUS  	CHART            	NAMESPACE
cd         	2       	Tue Jul 11 23:46:41 2017	DEPLOYED	spinnaker-0.3.0  	default  
ci         	3       	Fri Jan 20 15:07:23 2017	DEPLOYED	concourse-0.1.0  	default  
ideal-koala	1       	Mon Sep 25 18:00:26 2017	DEPLOYED	hadoop-1.0.0     	charts   
mc         	1       	Mon Sep 25 17:50:29 2017	DEPLOYED	mcrouter-0.1.0   	charts   
tb         	1       	Fri Sep  1 16:39:22 2017	DEPLOYED	gke-toolbox-0.1.0	default  
tb         	12      	Fri Sep  1 17:05:14 2017	DEPLOYED	gke-toolbox-0.1.0	default  
tb         	18      	Fri Sep  1 17:29:09 2017	DEPLOYED	gke-toolbox-0.1.0	default  
tb         	3       	Fri Sep  1 16:54:59 2017	DEPLOYED	gke-toolbox-0.1.0	default  
tb         	8       	Fri Sep  1 17:02:00 2017	DEPLOYED	gke-toolbox-0.1.0	default  
zep        	1       	Fri Sep 29 18:07:02 2017	DEPLOYED	zeppelin-1.0.0   	charts
```

**Comment by danisla** [comment]
@viglesiasce it looks like you are missing the `hadoop.` in the `configMapName` value on the command line.

Change this:

        --set hadoop.useConfigMap=true,configMapName=ideal-koala-hadoop` 

To this:

         --set hadoop.useConfigMap=true,hadoop.configMapName=ideal-koala-hadoop

**Comment by danisla** [comment]
@viglesiasce, I updated the hadoop NOTES.txt to output the correct value name. https://github.com/kubernetes/charts/pull/2385

**Comment by viglesiasce** [comment]
Worked like a charm now. Thanks @danisla!

**Pull request merged**
