### PR TITLE
[stable/jenkins] Add optional mapping for Ingress RouterName

### PR DESCRIPTION
**Pull request by fowlie**
Signed-off-by: Mats Faugli <mats.faugli@vegvesen.no>

#### Is this a new chart
No.

#### What this PR does / why we need it:
I got this error when running `helm install` to our Openshift cluster: `Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route`. This PR allows to fix this error by setting the attribute `.Values.master.route.ingressRouterName`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@fowlie Can you add an entry in `CHANGELOG.md`?

**Comment by fowlie** [comment]
Sorry for the delay. I noticed the upstream version was bumped in the meantime, so after a rebase I bumped the version number in this PR.

**Comment by fowlie** [comment]
Hm, probably shouldn't have done the rebase. I'm not very used to submitting PRs like this, any tips on how to fix this? :see_no_evil:

**Comment by erpel** [comment]
This seems related to #20624 although the diff looks cleaner there.

**Pull request closed without merging**
