### PR TITLE
docker-registry: added new ingress annotation for body size

### PR DESCRIPTION
**Pull request by velislav**
#### What this PR does / why we need it:
Fix the problem when I push docker image to the docker-registry and nginx throw exception "413 Request Entity Too Large"

#### Checklist

### CODE REVIEW

**Comment by rendhalver** [comment]
Why are you adding an annotation that is commented out?
annotations are something you can add easily so I see no reason for this to be added to the Chart.

**Comment by velislav** [comment]
If someone use ingress almost certain will hit the issue "413 Request Entity Too Large" 
For this reason this annotation should be prepared in advance. 
There is no reason something that will be use almost 100% of the times with ingress to not be prepared in the chart. It will save time of many users to search and apply it.

**Comment by gabrielcalderon** [comment]
I ran into this issue when running with default NGINX ingress. The default setup on this chart doesn't support pushing images. This PR would fix that. At least add it as a comment to the chart.

There's also the issue of docker-registry using root path of "/", it should be configurable.

**Comment by tjanson** [comment]
This is still an issue. Adding the annotation (actually adding it, not commented out of course) solves the problem.

Just in case, the correct syntax to add the annotation with Helm is: `--set ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="0"`.

I think this should be the default. At least I can’t imagine anyone being okay with whatever the default limit is (apparently `1M`). It would probably be ideal to provide a sane-ish default and expose it as a parameter.

**Comment by tjanson** [comment]
@rendhalver Any thoughts? Please reconsider this. I’d bet 99% of users run into this. Adding the annotation in its commented out state is not unusual. Would you prefer changes to this pull request, like an explanatory comment?

/remove-lifecycle stale

**Pull request closed without merging**
