### PR TITLE
[stable/sensu] Updating and supporting 63 character length

### PR DESCRIPTION
**Pull request by sstarcher**
Updating sensu and addressing #233

### CODE REVIEW

**Comment by sstarcher** [comment]
I will update Uchiwa as soon as this is merged.

**Review by bacongobbler — APPROVED** [review]

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by seanknox** [comment]
Thanks @sstarcher!

**Comment by sstarcher** [comment]
@seanknox thanks for the merge.  I have the same changes for Uchiwa #811

**Pull request merged**
