### PR TITLE
[stable/nginx-ingress] Revert #7933 which broke upgrading

### LINKED ISSUE #9227: [stable/nginx-ingress] ClusterIP set to ""
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/nginx-ingress

**What happened**:
Error: UPGRADE FAILED: Service "nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable

**What you expected to happen**:
It doesn't break compatibility 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
With default config:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L163

This will add clusterIP anyway:
https://github.com/helm/charts/commit/e17c2f95a43c1fb7d2307707df96568bba497527#diff-b2f5526b8650ff34ad6c9084e65609e8R21

### PR DESCRIPTION
**Pull request by mtparet**
#### What this PR does / why we need it:
Upgrading nginx-ingress is broken since https://github.com/helm/charts/pull/7933

#### Which issue this PR fixes
  - fixes https://github.com/helm/charts/issues/9227

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@mtparet please sign the DCO

**Comment by mtparet** [comment]
@cpanato done :)

**Comment by mtparet** [comment]
Could we go forward on this issue and decide what to do to fix current broken upgrades ? @cpanato @robermorales

**Comment by cpanato** [comment]
I'm fine with that.

@davidkarlsen can you please take a look in this PR? thanks!

**Comment by mtparet** [comment]
@robermorales what is your proposition to fix current broken upgrades ?

**Comment by robermorales** [comment]
@mtparet I do not know the best option, but I think that generating a new version that could also broke the upgrades is not the best idea. But it is only my opinion.

**Comment by mtparet** [comment]
@robermorales yes indeed the change will also break upgrades for people who installed it since the previous breaking change. 
Anyway we have to keep a way to have an empty ClusterIP as is immutable and it means that all charts installed (before the 9th november) with a ClusterIP `""` will not be able to use this chart anymore.

**Comment by robermorales** [comment]
"anymore"? Are you sure that no workaround possible?

Following your rationale, it this PR is merged, everyone with the chart in the version `v0.31.0` won't be able to use this chart anymore. Right?

It is only my opinion, you can do whatever you decide. I filled the original PR with the best intention, and got merged after 6 weeks of review. I still think it solved a problem. The broken upgrades are caused by an incorrect/invalid/innecesary clusterIP value, set by the old buggy versions.

I filled the PR since this value caused a problem to me, so I noticed the source and contributed a solution. I didn't think that I could not use the chart anymore. Specially, given that if I did that every time helm was refusing to do an upgrade, I wouldn't be able to use helm at all.

Please understand the rationale after the original PR.

If you need to get a solution to the manual upgrades, you can do it if you wish, but, if possible, try to do it without reintroducing the original offending value `clusterIP: ""`. Perhaps we need a pre-install hook to fix the originally broken values, and then, apply the templates. https://github.com/helm/helm/blob/master/docs/charts_hooks.md

**Comment by mtparet** [comment]
I understand and agree with the initial PR but we should do the best to avoid doing breaking changes.
If the breaking change is really unavoidable we should at least give a way to do manually the upgrade and advertise it.

**Comment by mtparet** [comment]
The workaround given here https://github.com/helm/charts/issues/9227#issuecomment-451058505  is working for me. So I'm closing this PR, the workaround should be writtent in the Readme for anyone upgrading from `< 0.31.0`

**Pull request closed without merging**
