### PR TITLE
[stable/sonarqube] Add talha as a maintainer for stable/sonarqube

### PR DESCRIPTION
**Pull request by rjkernick**
Signed-off-by: Rob Kernick <rjkernick@gmail.com>

#### What this PR does / why we need it:

Add a maintainer in the effort the help with #13867 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [x ] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
/assign
/lgtm

nicely done, thanks!

**Comment by rjkernick** [comment]
@maorfr thanks for the quick turn around. How can we get him added as a collaborator as well?

**Comment by maorfr** [comment]
its already done

**Pull request merged**
