### PR TITLE
[stable/rocketchat] Correct the indentation for node affinity

### PR DESCRIPTION
**Pull request by philtweir**
#### What this PR does / why we need it:

This character change fixes RocketChat deployment node affinity indentation. Node affinity is not otherwise respected.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by srueg** [comment]
@philtweir please sign off your commit (`git commit --signoff`) to comply with the DCO.
Also the chart needs a version bump.

**Comment by philtweir** [comment]
Thanks @srueg - will do asap.

**Comment by philtweir** [comment]
Apologies, took a couple goes to get the flow - have updated those with signed-off commits, and merged from master as a separate commit - is that sufficient ahead of squash & merge, or is there anything I can do to tidy up on my end?

**Comment by srueg** [comment]
Honestly, I don't know if it's possible to squash & merge with prow... Could you please rebase/squash in this branch?

**Comment by philtweir** [comment]
Sure - think that should be it? Many thanks :)

**Comment by srueg** [comment]
Thanks for your contribution! 👍

**Comment by philtweir** [comment]
Thanks @srueg!

**Pull request merged**
