### PR TITLE
[incubator/kafka] Makes readiness probe configurable

### PR DESCRIPTION
**Pull request by fedenusy**
### Motivation

When running Kafka with different configurations (different cpu/memory/storage, ci/staging/production, etc) it makes sense to alter the default readiness probe config.

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@fedenusy can you bump the version on this?

**Comment by fedenusy** [comment]
@benjigoldberg done!

**Comment by benjigoldberg** [comment]
Thanks for the PR @fedenusy!

**Pull request merged**
