### PR TITLE
[stable/weave-scope] bump version

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
Bump weave scope

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@stefanprodan can you check this one as well? thanks!

**Comment by stefanprodan** [comment]
I'm not in the owner list for this one, pinging @errordeveloper

**Pull request merged**
