### PR TITLE
Bump up GoCD app version to 18.11.0

### PR DESCRIPTION
**Pull request by bdpiprava**

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
@bdpiparva - the 400 Bad request is from the elastic profiles API for the PodConfiguration. I suspect its because of https://github.com/gocd/gocd/pull/5258.

**Comment by varshavaradarajan** [comment]
The error is 

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 11 column 88 path $.properties[1].value
```

**Comment by bdpiparva** [comment]
@varshavaradarajan - yes, https://github.com/gocd/gocd/blob/174bb81cc294480539cd886f83373bb1402c0039/api/api-base/src/main/java/com/thoughtworks/go/api/util/GsonTransformer.java#L45 is not able to parse pod configuration properly to `JsonElement`. I am working on it.

**Pull request merged**
