### PR TITLE
[stable/prometheus-operator] Update dependencies for RBAC, readme

### LINKED ISSUE #8877: prometheus-operator RBAC does not work
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/prometheus-operator

**What happened**:

After setup helm chart node exporters does not work, daemoset didn't start because RBAC give an error:

>  daemonset-controller  Error creating: pods "kube-prometheus-prometheus-node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used. Allowed ports: []]

**What you expected to happen**:

`helm upgrade -i kube-prometheus stable/prometheus-operator --namespace monitoring`

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### LINKED ISSUE #8967: Invalid retention description
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.11.0
Kubernetes: 1.10

**Which chart**:
prometheus-operator

**What happened**:
Using `alertmanager.alertmanagerSpec.retention` with a value of `7d` resulted in a crash looping pod with the following log `alertmanager: error: time: unknown unit d in duration 7d, try --help`

**What you expected to happen**:
I expected the pod to come up healthy

**How to reproduce it** (as minimally and precisely as possible):
configure  `alertmanager.alertmanagerSpec.retention` with a value of `7d` using prometheus-operator version 0.1.8

**Anything else we need to know**:
The documentation at https://github.com/helm/charts/tree/master/stable/prometheus-operator lists the following description for that key 
`Time duration Alertmanager shall retain data for. Value must match the regular expression [0-9]+(ms|s|m|h|d|w|y) (milliseconds seconds minutes hours days weeks years).`

### PR DESCRIPTION
**Pull request by vsliouniaev**
#### What this PR does / why we need it:
- Use latest node exporter chart to fix issue with PSP resources not being created per documentation
- Fix incorrect documentation for alertmanager retention

#### Which issue this PR fixes
fixes #8967
fixes #8877

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
Updated lock file, upgrade kube-state-metrics for fixed RBAC configuration too

**Review by paskal — APPROVED** [review]

**Pull request merged**
