### PR TITLE
Add 'carrodher' to OWNERS in Bitnami charts

### PR DESCRIPTION
**Pull request by carrodher**
**What this PR does / why we need it**: Add @carrodher to `stable|incubator/*/OWNERS` for Bitnami charts

### CODE REVIEW

**Comment by javsalgar** [comment]
I tried to reproduce the issue in the tests but I couldn't, I do not get that socket error

**Comment by carrodher** [comment]
@sameersbn @prydonius @tompizmor any ideas about the test issue?

**Comment by prydonius** [comment]
@carrodher can I suggest removing the failing ones from this PR and addressing them in a separate PR?

**Comment by carrodher** [comment]
Separating everything to avoid more issues

**Pull request closed without merging**
