### PR TITLE
[stable/node-problem-detector] User-specifed custom monitor definitions

### PR DESCRIPTION
**Pull request by jeevb**
#### What this PR does / why we need it:
Allow user-specified custom monitor definitions for Node Problem Detector

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jeevb** [comment]
https://github.com/helm/charts/pull/10548

@davidkarlsen: Could you review this PR when you get a chance? We had a need for configurable monitor definitions, and the above PR did not work for the reasons you stated.

**Comment by max-rocket-internet** [comment]
You need to rebase though.

**Comment by jeevb** [comment]
@max-rocket-internet: Done. Thank you for reviewing this PR.

**Pull request merged**
