### PR TITLE
[stable/grafana] Fix typo

### PR DESCRIPTION
**Pull request by the-smooth-operator**
#### What this PR does / why we need it:
Improve Documentation Fixing a typo.

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [-] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@The-smooth-operator 
Thanks for your contribution.

Could you bump the chart to latest version and sign DCO as on the bottom of this page suggested (click "Details" for instructions)? Thank you.

**Comment by The-smooth-operator** [comment]
Hi @zanhsieh,
I've made the changes as requested: signed off the commits and bumped chart version.
Sorry for missing on signing off. I did not bump the version before as I thought it wasn't needed for a change in the Readme.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
