### PR TITLE
[stable/traefik] Add extrnalIP to values

### PR DESCRIPTION
**Pull request by asabirov**
**What this PR does / why we need it**:
Allows set static external IP for the server. It's useful in case if there is no load balancer behind Traefik. For example, on Hetzner cloud.

### CODE REVIEW

**Comment by rjkernick** [comment]
Please sign the CLA and bump the version in Chart.yaml

**Comment by asabirov** [comment]
@rjkernick Thank you for reminding me.

**Comment by unguiculus** [comment]
cc @krancour

**Comment by krancour** [comment]
This looks good to me except for the conflict over chart version. There are a lot a in-flight Traefik chart PRs right now. If this were the next to be merged, the right version would be `1.32.0`.

**Pull request merged**
