### PR TITLE
[stable/jenkins] Enable Jenkins Configuration as Code auto-reload container environment variables configuration

### LINKED ISSUE #21134: REQ_TIMEOUT jenkins-sc-config side car
Hello,
Chart: Jenkins Helm Chart
Version: 1.9.19
Bug: we have jenkins as code returning timeouts in the jenkins-sc-config side-car container. Since we have many jobs, when jenkins is loading the configuration, it takes more than 10s (default value, and we need a couple of seconds more) and we got a timeout related to REQ_TIMEOUT. This forces jenkins to charge the config maps in a loop. This happens after a random time (10min, or 55min, etc.)

Proposed Solution:
Is possible to add one env var to allow the modification of the value REQ_TIMEOUT value of  jenkins-sc-config side-car?

Image of the side car: kiwigrid/k8s-sidecar:0.1.20

Thanks

### PR DESCRIPTION
**Pull request by sa-spag**
Hey there 👋 

#### What this PR does / why we need it
This PR adds a new `master.sidecars.configAutoReload.env` value that configures the Jenkins Configuration as Code auto-reload container environment variables. 

#### Which issue this PR fixes
  - fixes #21134

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name
- [x] Chart Version bumped

### CODE REVIEW

**Comment by torstenwalter** [comment]
@sa-spag: Your change looks ok. Can you merge it with Master branch or rebase on top of it?

Out of curiosity: Why do you want to set the timeout this high?

**Comment by sa-spag** [comment]
Thanks for your review @torstenwalter, I'll rebase.
Initially we had a bunch of Groovy scripts making use of the job DSL API, and Jenkins had to process them one by one. We merged them and now it's a lot better. In the end I don't need these changes myself but hopefully there are helpful to others.

**Comment by torstenwalter** [comment]
@sa-spag  Sorry I missed this one and something else got merged in the meantime. Would you mind to rebase once again?

**Comment by sa-spag** [comment]
> @sa-spag Sorry I missed this one and something else got merged in the meantime. Would you mind to rebase once again?

No problem. Done.

**Pull request merged**
