### PR TITLE
[stable/node-problem-detector] Add relabelings to include node label in metrics

### LINKED ISSUE #332: Missing node name from problem metrics
Would it be possible to add the node name as labels to the `problem_counter` metrics?
Currently the `instance` label refers to the IP address of the node-problem-detector pod, which makes it hard to match it up with the actually affected node.

```
problem_counter{endpoint="exporter",instance="172.12.34.56:20257",job="node-problem-detector",namespace="kube-system",pod="node-problem-detector-6k8pb",reason="AUFSUmountHung",service="node-problem-detector"}

problem_gauge{endpoint="exporter",instance="172.12.34.56:20257",job="node-problem-detector",namespace="kube-system",pod="node-problem-detector-6k8pb",reason="AUFSUmountHung",service="node-problem-detector",type="KernelDeadlock"}
```

### PR DESCRIPTION
**Pull request by Pharb**
Signed-off-by: Patrick Harböck <patrick.harboeck@tngtech.com>

#### What this PR does / why we need it:
Since #16125 node-problem-detector exposes metrics via a prometheus-operator ServiceMonitor.
These metrics did not include any labels to identify the relevant node.

This PR adds the necessary relabeling rules to include these labels (as suggested in https://github.com/kubernetes/node-problem-detector/issues/332).

#### Which issue this PR fixes
  - fixes https://github.com/kubernetes/node-problem-detector/issues/332

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Pharb** [comment]
@max-rocket-internet Is the behaviour of @k8s-ci-robot expected here? It does not seem to be able to assigned its suggested assignee.

**Review by max-rocket-internet — APPROVED** [review]

**Comment by max-rocket-internet** [comment]
> @max-rocket-internet Is the behaviour of @k8s-ci-robot expected here?

I never understand what the process is here. Users can be listed in `Chart.yaml` or in `OWNERS` but they can't be part of the process unless they are members of the Helm org I think?

**Pull request merged**
