### PR TITLE
[stable/kibana] Fix initContainers indentation

### PR DESCRIPTION
**Pull request by pavdmyt**
#### What this PR does / why we need it:

Fixes indentation for init containers created by `Values.initContainers`. If only `Values.initContainers`  are used, everything works fine. If `Values.initContainers` is combined with `Values.dashboardImport` or `Values.plugins` the following error will raise:

```
## override.yaml
initContainers:
  echo-container:
    image: "busybox"
    command: ['sh', '-c', 'echo Hello from init container! && sleep 3']

dashboardImport:
  dashboards:
    k8s: https://raw.githubusercontent.com/monotek/kibana-dashboards/master/k8s-fluentd-elasticsearch.json
```

```
$ helm install . -f override.yaml
Error: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 29: did not find expected key
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md (Not applicable)

### CODE REVIEW

**Comment by compleatang** [comment]
@pavdmyt thanks! Can you add a test that will use all three so that the CI helps catch this in the future?

something like an `initcontainers-full-values.yaml` in the ci directory. the file can just copy and paste the values from the files: 

* https://github.com/helm/charts/blob/master/stable/kibana/ci/dashboard-values.yaml
* https://github.com/helm/charts/blob/master/stable/kibana/ci/plugin-install.yaml
* https://github.com/helm/charts/blob/master/stable/kibana/ci/initcontainers-values.yaml

That will give us some future protection if any other init sequences are needed by the community.

**Comment by pavdmyt** [comment]
@compleatang great idea! Done.

**Comment by pavdmyt** [comment]
@compleatang the reason for recent CI fails is the following:

```
I0215 20:10:54.998] Plugin installation was unsuccessful due to error "Plugin logtrail [6.4.3] is incompatible with Kibana [6.6.0]"
```

Will update to something more up to date.

**Comment by compleatang** [comment]
@pavdmyt thanks for figuring that out. i quickly looked at the failure and it baffled me.

**Pull request merged**
