### PR TITLE
 [stable/owncloud] Allow use of external database

### PR DESCRIPTION
**Pull request by tompizmor**

### CODE REVIEW

**Comment by carrodher** [comment]
LGTM

**Comment by carrodher** [comment]
@tompizmor this is ready for merge. Merge it before #4222 because of the conflicts with the chart version (or fix the conflicts here, as you want)

**Comment by tompizmor** [comment]
@carrodher The merge is done automatically by the k8s-bot. I think we have to wait

**Comment by carrodher** [comment]
I just resolved conflicts in the other PR

**Pull request merged**
