### PR TITLE
Add optional service replica selector

### PR DESCRIPTION
**Pull request by rabadin**
When using a replicaset for the server (for redundancy purposes),
this allows to select which replica the service will talk to in
order to have a consistent view of the data.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@rabadin 
Could you sign DCO please? Thank you.

**Comment by rabadin** [comment]
@zanhsieh sure: done.

**Comment by zanhsieh** [comment]
/assign
@rabadin 
Could you bump the chart to latest again please? Thank you.

**Comment by rabadin** [comment]
@zanhsieh Sure thing. Done.

**Comment by rabadin** [comment]
@zanhsieh I've re-based onto master once again; please have another look when you get a chance.

**Comment by zanhsieh** [comment]
@rabadin 
This one needs a version bump to latest. Please check the e2e test log to see details.

**Comment by rabadin** [comment]
@zanhsieh I've rebased onto master and bumped the chart version... but pull-charts-e2e is still failing; it's unclear to me how the change I'm proposing can cause the error I'm seeing in the log... can you help?

**Comment by zanhsieh** [comment]
@rabadin 
Try to bump the chart to latest and tried again. Recently the chart version increased. I sort-of suspect some race condition happens in test-infra.

**Comment by rabadin** [comment]
@zanhsieh Done. Seems to have passed CI.

**Comment by zanhsieh** [comment]
@rabadin 
Could you bump the chart again please? e2e log seems complaining about it.

**Comment by rabadin** [comment]
@zanhsieh Done.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
