### PR TITLE
[stable/openvpn/ Exec OpenVPN Process

### PR DESCRIPTION
**Pull request by dippynark**
#### What this PR does / why we need it: 

Exec's OpenVPN process so that it runs as PID 1. In particular this means it receives the SIGTERM when it is terminated so that it stops gracefully.

This is particularly useful for version 2.4 of OpenVPN to make use of the `explicit-exit-notify` setting in server mode and trigger clients to reconnect when the server is terminated (instead of timing out).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jasongwartz** [comment]
@dippynark thanks for the contribution! Can you add a comment on the line above indicating why the exec is there?

The chart, as you know, is currently on openvpn 1.x, but hopefully 2.x will come soon (when I can get to it): https://github.com/helm/charts/pull/12269

**Comment by dippynark** [comment]
@jasongwartz will do, it's already 2.x though right?
```
docker run -it jfelten/openvpn-docker:1.1.0 openvpn --version
OpenVPN 2.3.14 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Dec 18 2016
...
```

**Comment by jasongwartz** [comment]
Huh - I thought it was on 1.1 as per https://github.com/helm/charts/issues/4569 but you’re right, the actual version in the container is 2.x (though an outdated version, but not *nearly* as bad as 1.x). Thanks for the prompt to check properly!

**Comment by jasongwartz** [comment]
/lgtm
/approve

Thanks for the contribution!

**Comment by dippynark** [comment]
@jasongwartz there is a PR for the update https://github.com/jfelten/openvpn-docker/pull/1 but not too sure how active that repo is

**Comment by jasongwartz** [comment]
AFAIK it’s mostly abandoned, hence the other work (which has stagnated, but I intend to come back to) to migrate to the more standard kylemanna image

**Pull request merged**
