### PR TITLE
[stable/kibana] fixed initcontainer name (capital letter)

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**:
* fixed initcontainer name (capital letter)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by monotek** [comment]
I think this was a search/replace mistake, when renaming of the variable as requested in: https://github.com/helm/charts/pull/6827

**Comment by compleatang** [comment]
IIRC before the variable was `DashboardImport` and @unguiculus and I asked for `dashboardImport`. 

In any event, AFAIK it's correct right now per adopted helm chart conventions so no need for this PR.

**Comment by compleatang** [comment]
Right. My fault.

**Comment by monotek** [comment]
I guess the tests worked because the init container is disabled by default...

**Pull request closed without merging**
