### PR TITLE
[stable/ghost] Bump Ghost version 

### PR DESCRIPTION
**Pull request by juan131**
- Update Ghost image version to "0.11.4-r0".
- Update chart to "0.4.2".

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@juan131 can you update the MariaDB requirement to 0.5.x here as well

**Comment by juan131** [comment]
@prydonius MariaDB version updated.

**Comment by prydonius** [comment]
lgtm, thanks @juan131!

**Review by prydonius — APPROVED** [review]

**Pull request merged**
