### PR TITLE
[incubator/konga] awaiting review to include new konga chart 

### PR DESCRIPTION
**Pull request by xfrarod**
#### What this PR does / why we need it:
Includes new incubator chart for Konga dashboard

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
New chart that spins up all infrastructure required to have konga dashboard working over a postgres DB storage backend.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vietwow** [comment]
I have tested and confirmed that the chart is good from my side.

Best Regards,
VietNC

**Comment by xfrarod** [comment]
Thanks @vietwow,  could we merge this PR so we can make this chart available to other users?

Thanks a lot for your help!

**Comment by wstrox** [comment]
Request to reopen?

**Comment by as3445** [comment]
what's the status on this?

**Pull request closed without merging**
