### PR TITLE
[stable/nextcloud] Remove broken attempt to mute logging of assets

### LINKED ISSUE #16860: [stable/nextcloud] Cannot upload images files when using ingress annotations
**Describe the bug**
In values.yaml, if you use enable ingress and uncomment the annotations, you will not be able to upload image files. (Tested png and jpeg). I suspect the issue is related to this setting:
`location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {`
Though I don't know why it's broken

**Version of Helm and Kubernetes**:`
Helm:
```$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Kubernetes:
```
$ kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
kmaster    Ready    master   21h   v1.14.6-k3s.1
kworker1   Ready    worker   21h   v1.14.6-k3s.1

```
**Which chart**:
stable/nextcloud

**What happened**:
"An unknown error has occurred"  message when trying to upload jpg file
Ingress log:
```
2019/09/04 20:17:16 [error] 617#617: *86972 rewrite or internal redirection cycle while internally redirecting to "/index.php/remote.php/webdav/wZAlVrObSUi88xl
```

**What you expected to happen**:
File uploads

**How to reproduce it** (as minimally and precisely as possible):
deploy stable/nextcloud with ingress enabled and the annotation uncommented
[values.yaml.txt](https://github.com/helm/charts/files/3576343/values.yaml.txt)

**Anything else we need to know**:
Example values.yaml attached

### LINKED ISSUE #22207: [stable/nextcloud] Error 500 accessing images
**Describe the bug**
Setting up nextcloud with nginx ingress proxy. Using default value for `ingress.annotations.nginx.ingress.kubernetes.io/server-snippet`. Getting server error `500` trying to access images stored in the nextcloud. All other functions work smoothly.

**Version of Helm and Kubernetes**:
Helm 2.16.3 / Kubernetes 1.18.2

**Which chart**:
stable/nextcloud

**What happened**:
Server error 500. Error message in proxy:
```
rewrite or internal redirection cycle while internally redirecting to "/index.php/remote.php/dav/files/jo/Photos/Coast.jpg",
```

**What you expected to happen**:
Server responds with 200 and the image

**How to reproduce it** (as minimally and precisely as possible):
Set up nextcloud 18.0.4 fpm/alpine flavour. Enable ingress with default server-snippet.

**Anything else we need to know**:
Removing the following part from the server-snippet resolves the issue:
```
      location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
      try_files $uri /index.php$request_uri;
      # Optional: Don't log access to other assets
      access_log off;
      }
```

### PR DESCRIPTION
**Pull request by bklang**
#### Is this a new chart

No

#### What this PR does / why we need it:

These (commented) lines in `values.yaml` are the recommended ingress settings. It appears to be an attempt to reduce logging noise. Unfortunately it has the side effect of breaking image uploads & downloads from Nextcloud. This was documented in issue #16860, and specifically [this comment](https://github.com/helm/charts/issues/16860#issuecomment-538244349). I had the same issue as reported, and removing these lines made it so image uploads/downloads work as expected.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #16860
  - fixes #22207 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by chrisingenhaag** [comment]
Hi, 
thx for the PR. Would like to approve the change. One missing thing is to add a version bump in Chart.yaml to fix breaking lint chart job.

**Comment by bklang** [comment]
@chrisingenhaag Chart version bumped. I also had to amend my second commit to sign it off, but it looks like the DCO did not pick up on the amended commit, even though I see it in Github.

**Comment by bklang** [comment]
Amended commit a second time, looks like we are good to go!

**Review by billimek — APPROVED** [review]

**Pull request merged**
