### PR TITLE
[stable/fluent-bit] Add logfmt support

### LINKED ISSUE #14173: [stable/fluent-bit] Add logfmt parser support
**Is your feature request related to a problem? Please describe.**
This chart configuration only supports json and regex parsers `parsers.regex` `parsers.json`

**Describe the solution you'd like**
Add support for logfmt parser.
Since this got merged: https://github.com/fluent/fluent-bit/pull/871
Should not be very hard

**Describe alternatives you've considered**
Add a totally custom configmap, but it's not very clear and will require lots of copypaste.

**Additional context**
Lots of people use this logging format since golang is growing in microservices architectures

### PR DESCRIPTION
**Pull request by ahoulgrave**
#### What this PR does / why we need it:
Enables adding logfmt parsers in the values file.

#### Which issue this PR fixes

  - fixes #14173

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by ahoulgrave** [comment]
@edsiper @kfox1111 any news on this?

**Comment by kfox1111** [comment]
Sorry. Having some email problems...

This templating every possible option is really making this thing unwieldy. We've got several different ways now to just specify your own configmap. whole configmap, rawConfig, various extraEntries without needing to add more template stuff.

How can we simplify this so you can do the things you want, without hardcoding a lot more options? Make the log type overridable instead of making new whole sections?

If not, maybe one option would be to consider making the whole parser block into a macro, called for each type. they look identical.

Are there going to be any other types then json,regex, and logfmt?

**Comment by kfox1111** [comment]
Why was this just slammed through 3 hours after a question was asked?

**Comment by maorfr** [comment]
Sorry about that, didn't notice. What can i do to ammend?

**Comment by kfox1111** [comment]
Tis what it is. We can continue to discuss the options and do a follow up patch if needed.

**Comment by maorfr** [comment]
Apologies again :facepalm:

**Comment by ahoulgrave** [comment]
IMO this diffs do not add a lot of complexity as it only adds one more formatter option, just like you can use `json` and `regex`.

I understand that there are many ways to manage the configmap and should be addressed, but for example, if i'd need to use `logfmt` without these diffs, then i'd have to create a custom configmap just for this, when i can just add one line to my values file.

Please let me know how can I help in any other way.

**Pull request merged**
