### PR TITLE
stable/cerebro: Add service labels support

### PR DESCRIPTION
**Pull request by NicolasT**
See: 0111ba487e2538c9561730a03714376b80189ca7
See: https://github.com/kubernetes/charts/commit/0111ba487e2538c9561730a03714376b80189ca7
See: #6595
See: https://github.com/kubernetes/charts/pull/6595

### CODE REVIEW

**Comment by timstoop** [comment]
/ok-to-test
But leaving the acceptance to @davidkarlsen, as that's the Chart owner :)

**Comment by davidkarlsen** [comment]
maybe @unguiculus can /approve ?

**Pull request merged**
