### PR TITLE
[stable/consul] Provide advanced configuration options for consul (resubmit)

### PR DESCRIPTION
**Pull request by timstoop**
**What this PR does / why we need it**:

This is a resubmit of #1269, which has already been approved there. I only merged master into it so it could be accepted without trouble.

**Special notes for your reviewer**:

Could you please approve this again, @unguiculus / @lachie83 ?

### CODE REVIEW

**Comment by timstoop** [comment]
It seems these Pods take a very long time to start... I'll retry locally to see if I can get some of the timings.

**Comment by pgdagenais** [comment]
@timstoop were you able to test it locally ? We tested it on our dev env and the PR seems okay. 

We also tested with `antiAffinity=hard` and it worked without any issue.

```
$ helm install ./consul --set antiAffinity=soft
NAME:   honorary-swan
LAST DEPLOYED: Tue Apr 17 15:59:08 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/StatefulSet
NAME                  DESIRED  CURRENT  AGE
honorary-swan-consul  3        1        0s

==> v1beta1/PodDisruptionBudget
NAME                      MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
honorary-swan-consul-pdb  N/A            1                0                    0s

==> v1/Pod(related)
NAME                    READY  STATUS             RESTARTS  AGE
honorary-swan-consul-0  0/1    ContainerCreating  0         0s

==> v1/Secret
NAME                             TYPE    DATA  AGE
honorary-swan-consul-gossip-key  Opaque  1     0s

==> v1/ConfigMap
NAME                        DATA  AGE
honorary-swan-consul-tests  1     0s

==> v1/Service
NAME                     TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)                                                                           AGE
honorary-swan-consul     ClusterIP  None            <none>       8500/TCP,8400/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP  0s
honorary-swan-consul-ui  NodePort   10.103.177.187  <none>       8500:30101/TCP                                                                    0s


NOTES:
1. Watch all cluster members come up.
  $ kubectl get pods --namespace=default -w
2. Test cluster health using Helm test.
  $ helm test honorary-swan
3. (Optional) Manually confirm consul cluster is healthy.
  $ kubectl exec honorary-swan-consul-0 consul members --namespace=default | grep server

$ k get pod -w
NAME                     READY     STATUS    RESTARTS   AGE
honorary-swan-consul-0   1/1       Running   0          11s
honorary-swan-consul-1   1/1       Running   0          6s
honorary-swan-consul-2   1/1       Running   0          3s
$ helm test honorary-swan
RUNNING: honorary-swan-ui-test-c2ses
PASSED: honorary-swan-ui-test-c2ses
$ kubectl exec honorary-swan-consul-0 consul members  | grep server
honorary-swan-consul-0  10.1.0.5:8301  alive   server  1.0.0  2         dc1  <all>
honorary-swan-consul-1  10.1.0.6:8301  alive   server  1.0.0  2         dc1  <all>
honorary-swan-consul-2  10.1.0.7:8301  alive   server  1.0.0  2         dc1  <all>
$ helm ls
NAME         	REVISION	UPDATED                 	STATUS  	CHART       	NAMESPACE
honorary-swan	1       	Tue Apr 17 15:59:08 2018	DEPLOYED	consul-1.3.6	default
```

**Comment by timstoop** [comment]
/retest
Starts fine here :/

**Comment by pgdagenais** [comment]
We have been running this version for 2 weeks in our staging cluster and it seems to be working perfectly. I'm just wondering why the test are still failing

**Pull request merged**
