### PR TITLE
annotations is pluralized in templates/deployment.yml

### PR DESCRIPTION
**Pull request by dangarthwaite**

### CODE REVIEW

**Comment by lachie83** [comment]
Please bump your chart version

**Comment by dangarthwaite** [comment]
@lachie83   Version bumped.  Also - what happened to my cncf-cla?

**Comment by lachie83** [comment]
looks like the commit is missing your github user?

**Comment by dangarthwaite** [comment]
@lachie83  .... one of my commits has a typo in the email address.

**Comment by dangarthwaite** [comment]
Can someone kick this cla bot?  One of my commits had a typo in my email address.  A later commit corrected this.

**Comment by dangarthwaite** [comment]
@lachie83  This is a lot of hassle for some missing 's' characters.  I've accepted the cncf-cla and I fixed my email address and re-pushed.

**Comment by lachie83** [comment]
Hi @dangarthwaite. It looks like one of the commits in this PR are from another user. You might have to revert and commit with the authorized user

**Pull request closed without merging**
