### PR TITLE
[stable/grafana] Fix typo in grafana chart README

### PR DESCRIPTION
**Pull request by johnjeffers**
#### Is this a new chart
No

#### What this PR does / why we need it:
Fixes a typo in the README for the Grafana chart.

The recent change to add the `ldap.enabled` param caused us a bit of downtime today as we tried to figure out why our LDAP config was not being applied after running the latest chart. The README has the incorrect parameter name of `ldap_enabled`. We had to dig in to the templates to discover that what we actually needed was `ldap.enabled: true`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@johnjeffers 
Could you sign DCO and bump chart to latest version as the bottom of this page instruction (click into 'Details) please? Thank you.
/assign

**Comment by johnjeffers** [comment]
@zanhsieh Hopefully I got everything you needed done. Let me know if you need anything else.

**Comment by zanhsieh** [comment]
@johnjeffers 
Well, this chart flies fast. Another chart version bump please. Sorry about that.

**Comment by johnjeffers** [comment]
It's unclear whether you are asking me to match the chart version or increase the version. I see the current merge conflict shows 4.1.2 vs 4.1.1. Which should it be?

**Comment by zanhsieh** [comment]
> It's unclear whether you are asking me to match the chart version or increase the version. I see the current merge conflict shows 4.1.2 vs 4.1.1. Which should it be?

Pick a highest one, e.g. 4.1.3 or 4.1.2.

**Pull request merged**
