### PR TITLE
[stable/rabbitmq-ha] RabbitMQ upgrade to 3.8.0 and proper support of the new rabbitmq_prom…

### PR DESCRIPTION
**Pull request by lebenitza**
## What this PR does / why we need it:

The `rabbitmqPrometheusPlugin` flag was added but with no proper support for ServiceMonitor. This plugin is available from RabbitMQ 3.8.0 and makes the old prometheus_rabbitmq_exporter obsolete for versions > 3.8.0.

More details here: https://www.rabbitmq.com/prometheus.html

They have nice dashboards maintained by them :)

#### Special notes for your reviewer:

Don't know what to do with the Rules. Should they be enabled only for old exporter? (which makes sense they don't work on 3.8.0 plugin). Should I try and migrate them to 3.8.0? Please advise.

@steven-sheehy 

All in all, these changes should be backwards compatible!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md (I did not add any new ones)
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@MihaiAnei 
Would you mind to resolve conflicting files please?
stable/rabbitmq-ha/Chart.yaml

**Comment by MihaiAnei** [comment]
> @MihaiAnei
> Would you mind to resolve conflicting files please?
> stable/rabbitmq-ha/Chart.yaml

Yup, fixed.

**Comment by Gsantomaggio** [comment]
@MihaiAnei Yes, When I added the new plugin I forgot this part,
but I already prepared this PR: https://github.com/helm/charts/pull/18106 .

I don't care which one will be used, just to know there is a duplication

**Comment by MihaiAnei** [comment]
@Gsantomaggio oh sorry mate, did not see that one. If you add the required changes for a ServiceMonitor object I think yours is more complete because it takes into account NodePorts as well. I will close this one afterwards and we can merge yours.

**Comment by Gsantomaggio** [comment]
@ MihaiAnei 
I sent you an invite. Feel free to add the missing part, so we will commit together :)!

**Pull request closed without merging**
