### PR TITLE
[stable/wordpress] Fixes template reference in tls-secrets.yaml

### PR DESCRIPTION
**Pull request by MikeEvansLarah**
#### Is this a new chart

No

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

Fixes template reference in tls-secrets.yaml. Template reference was missing `wordpress.` prefix, which was causing chart to fail when TLS secrets were specified.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by alemorcuq — APPROVED** [review]

**Comment by alemorcuq** [comment]
Thanks for this, @MikeLarah. LGTM.

Please, merge this @carrodher.

**Comment by carrodher** [comment]
A new chart version appeared in the meantime, please, can you bump again the version? CI/CD is failing because of that:
```
I1108 08:22:02.472] Error linting and installing charts: Error processing charts
I1108 08:22:02.472] ------------------------------------------------------------------------------------------------------------------------
I1108 08:22:02.473]  ✖︎ wordpress => (version: "7.6.6", path: "stable/wordpress") > Chart version not ok. Needs a version bump!
I1108 08:22:02.473] ------------------------------------------------------------------------------------------------------------------------
```

**Comment by MikeLarah** [comment]
Chart version bumped to 7.6.7

**Pull request merged**
