### PR TITLE
[incubator/solr] add me as maintainer

### PR DESCRIPTION
**Pull request by eyenx**
Based on this list, solr needs some maintainers.

related to: #13869

### CODE REVIEW

**Comment by mattfarina** [comment]
cc @ian-thebridge-lucidworks

**Comment by maorfr** [comment]
may you reference us to some previous work you did on this chart? or any others...

in addition, there is no OWNERS file, so this PR will have no effect.

**Comment by eyenx** [comment]
Just closing this as nobody seems to be interested in merging it.

**Comment by maorfr** [comment]
did you see my last comment?

**Pull request closed without merging**
