### PR TITLE
[stable/prometheus-operator] Custom API Group support (#10091)

### LINKED ISSUE #10091: [stable/prometheus-operator] Support for API Group for CRD
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Which chart**: stable/prometheus-operator

**What happened**: Needed to configure CRD API group flag present in the prometheus-operator deployment. 

**Anything else we need to know**: Will be pushing a change for the support of this

### PR DESCRIPTION
**Pull request by anandsinghkunwar**
Signed-off-by: Anand Singh Kunwar <anandkunwar95@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10091 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by anandsinghkunwar** [comment]
The operator has a support for custom API group, need to add that support.

**Comment by anandsinghkunwar** [comment]
@gianrubio Did you get a chance to review this?

**Comment by anandsinghkunwar** [comment]
@gianrubio Did you get a chance to review?

**Comment by anandsinghkunwar** [comment]
@sameersbn Can you take a look?

**Comment by vsliouniaev** [comment]
@anandsinghkunwar
cc: @gianrubio 

CRD API group was removed in prometheus-operator 0.26. 
https://github.com/coreos/prometheus-operator/issues/2238

This pull request was merged into a helm chart that had the values set to 0.26.

How did this feature work?

**Pull request merged**
