### PR TITLE
fix #16690 - stable/prometheus - fails with empty clusterrole ruleset

### LINKED ISSUE #16690: stable/prometheus - fails with empty clusterrole ruleset
**Describe the bug**
If your render prometheus charts without psp, the clusterroles for alertmanager and pushgateways end up without any rules like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
```
instead we need to add an empty array like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
  []
```

**Version of Helm and Kubernetes**:
helm v2.14.3
k8s 1.13.x

**Which chart**:
stable/prometheus

**What happened**:
```
error: error validating "STDIN": error validating data: ValidationError(ClusterRole): missing required field "rules" in io.k8s.api.rbac.v1beta1.ClusterRole; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
The ClusterRole should be applied successfully.

**How to reproduce it** (as minimally and precisely as possible):
deploy the chart without psp.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by TheKangaroo**
Signed-off-by: Till Adam <lxmail@web.de>

#### Which issue this PR fixes

fixes #16690

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by TheKangaroo** [comment]
I'm a bit confused about the failing circleci. Do I have to bump a new Chart version for this fix? @mgoodness @gianrubio

**Comment by eladitzhakian** [comment]
@TheKangaroo looks to me like that's exactly what's required

**Comment by zanhsieh** [comment]
@TheKangaroo 
Could you bump the chart version to latest please? Thank you.

**Comment by TheKangaroo** [comment]
@zanhsieh you mean like
```
version: 9.2.1
appVersion: 2.13.1
```
or literally `latest`?

**Comment by zanhsieh** [comment]
> @zanhsieh you mean like
> 
> ```
> version: 9.2.1
> appVersion: 2.13.1
> ```
> 
> or literally `latest`?

It needs to be digit (e.g. 9.2.1). Thank you.

**Comment by TheKangaroo** [comment]
@zanhsieh should be good now :)

**Comment by baboune** [comment]
lgtm

**Comment by somanythings** [comment]
@TheKangaroo I'm striking this very issue, but I don't know any of the process here, yet. Are you likely to merge shortly, or should I be forking and applying locally in the meantime? Thanks!

**Comment by TheKangaroo** [comment]
Hi @somanythings, I don't know how exactly the process here works also.
I think one of the reviewers (@mgoodness or @gianrubio) has to add the lgtm label and then they can merge the fix. I, as a contributor, am not allowed to merge PRs.

**Comment by zanhsieh** [comment]
@TheKangaroo 
The e2e test need a version bump to latest. Would you mind to do that? Thank you.

**Comment by TheKangaroo** [comment]
@zanhsieh Chart version is updated ✅

**Pull request merged**
