### PR TITLE
[stable/prometheus] Added initContainer option for prometheus-server

### LINKED ISSUE #17653: stable/prometheus: Allow for adding initContainer to server-deployment.yaml
Hello,

this is a feature request.
Is it possible to add the possibility for an initContainer to the server-deployment.yaml of stable/prometheus?

I would really appreciate this for e.g. restoring a backup or general maintenance tasks before starting prometheus.

Please also allow the initContainer access to the extraVolumeMounts and the persistence volume mount of the server.

Thank you!

### PR DESCRIPTION
**Pull request by Jabb0**
#### What this PR does / why we need it:
This PR implements an optional initContainer for the prometheus server in stable/prometheus. This is used for restoring a backup of prometheus or performing other maintenance tasks. Per default the initContainer is not enabled.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #17653

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Jabb0** [comment]
Alternative is to specify a wildcard initContainers array that is populated in values.yaml

**Comment by zanhsieh** [comment]
@Jabb0 
Would you resolve the conflicting files please? Thank you.
stable/prometheus/Chart.yaml
stable/prometheus/templates/server-deployment.yaml

**Comment by Jabb0** [comment]
@zanhsieh looks like the merge conflict is because someone else solved my issue. I will close this request now.

**Pull request closed without merging**
