### PR TITLE
[stable/metabase] Allow MB_SITE_URL to be set from values.yaml

### PR DESCRIPTION
**Pull request by OliverEvans96**
No

#### What this PR does / why we need it:

Allow `MB_SITE_URL` to be set from values.yaml in stable/metabase

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pmint93** [comment]
@OliverEvans96 Is this necessary while you can config Site URL in Admin > Settings > General > Site URL

**Comment by OliverEvans96** [comment]
@pmint93 - It's perhaps not strictly necessary since I could have:
- deployed the helm chart
- set up a k8s proxy
- created an account
- logged in to the GUI
- change the setting in the admin page
- create my ingress

But I think it's a much smoother experience to just set the correct base URL via an env var so that it's possible to directly expose the service at the correct subpath when the chart is deployed.

I'm certainly going to keep the option in my fork.

**Review by pmint93 — APPROVED** [review]

**Comment by pmint93** [comment]
/lgtm
Thanks for your contributions

**Comment by OliverEvans96** [comment]
Thank you!

**Pull request merged**
