### PR TITLE
[stable/minio] Add subpath for /export volume

### PR DESCRIPTION
**Pull request by rio**
Conditionally adds the subPath for the /export volume mount.
Works only if `persistence.enabled` is true and `persistence.subPath`
is not empty string.

This is handy in cases where the volume plugin doesn't
support sub folder mounting. GlusterFS plugin, for example doesn't support
it whereas NFS actually does.

### CODE REVIEW

**Comment by rio** [comment]
Could it be just me that's running in to this? I've seen other charts implement it.

**Comment by rio** [comment]
Any way for me to get this moving forward? @viglesiasce

**Comment by viglesiasce** [comment]
Thanks @Rio!

**Comment by rio** [comment]
merci beaucoup ^_^

**Pull request merged**
