### PR TITLE
[stable/rabbitmq] Option to create force_load file (#13485)

### LINKED ISSUE #13485: [stable/rabbitmq] Recover from "Waiting for Mnesia tables" after all nodes forced shutdown
**Is your feature request related to a problem? Please describe.**
Yes, in our dev/staging environment in AWS we turn-off at night time (set scaling group to 0) the nodes of EKS cluster to save costs and we enabled persistence for rabbitmq, so it was like unexpected shutdown for all rabbitmq nodes and it can't recover with "Waiting for Mnesia tables", i tried setting podManagementPolicy and service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" but it had no effect, still keeps looping with "Waiting for Mnesia tables"

**Describe the solution you'd like**
Can this solution be applied https://github.com/helm/charts/pull/9645#issuecomment-478638566 as an option? We'd really prefer availability over integrity.

**Describe alternatives you've considered**
Don't use persistence.

### PR DESCRIPTION
**Pull request by denis111**
Signed-off-by: Denis Kalgushkin <keygenmusic@gmail.com>

#### What this PR does / why we need it:
See #13485 . Adds an option to force rabbitmq start on unexpectedly shut down cluster.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #13485

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @denis111 

It looks a very complex solution just for creating a "force_load" file. 

To keep the chart as simple as possible, I'd suggest to implement a way to create that file during the container initialization when a certain env. variable is set (sth like `RABBITMQ_FORCELOAD`). What do you think about this approach?

**Comment by denis111** [comment]
Well yes, maybe it's too complex. I just saw how it's made for volume-permissions and also didn't want to touch volume-permisions init container.
Do you suggest to create the file in the main (not init) containter during the startup just before "exec rabbitmq-server"?

**Comment by juan131** [comment]
> Do you suggest to create the file in the main (not init) containter during the startup just before "exec rabbitmq-server"?

Yes, I think that cant be a solution

**Comment by denis111** [comment]
@juan131 
Ok, in that case I guess i can just use 'rabbitmqctl force_boot' command before exec. I hope to prepare a new PR next monday,

**Comment by denis111** [comment]
Created another PR https://github.com/helm/charts/pull/14149 so you can choose one and close another.

**Comment by juan131** [comment]
I'd rather follow the approach you used at #14149 
Please close this PR since I don't have privileges to do so.

**Pull request closed without merging**
