### PR TITLE
[stable/traefik] Update app version to 1.5.3

### PR DESCRIPTION
**Pull request by siwyd**
* Update Traefik version to 1.5.3
* Bump Chart version

### CODE REVIEW

**Comment by kachkaev** [comment]
I'd say chart version can be `1.21.2` instead of `1.22.0`. We're just updating traefik to a new patch release, which resolves to a bump in a patch release of the chart. https://github.com/kubernetes/charts/pull/3872 is `1.22.0` though, because it adds a new parameter and this is considered a chart feature.

Thanks for preparing this PR!

**Comment by siwyd** [comment]
@kachkaev Yeah that makes sense. Changed.

**Comment by krancour** [comment]
@siwyd, looks like there's a merge conflict here. It will LGTM after that is resolved.

**Comment by siwyd** [comment]
@krancour Rebased and version bumped to resolve conflict.

**Comment by krancour** [comment]
Thanks @siwyd 

/ok-to-test

**Comment by krancour** [comment]
Thanks @siwyd !

**Pull request merged**
