### PR TITLE
[stable/phpmyadmin] Add custom podLabels to deployment.yaml

### PR DESCRIPTION
**Pull request by verymahler**
In our company cluster, we can't use pods without an added custom label.
This change makes it possible to add a label simply by adding a value

```yaml
phpmyadmin:
  podLabels:
    custom/label: department1
```

#### Checklist 
* [x]  [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
* [x]  Chart Version bumped
 * [x]  Variables are documented in the README.md
 * [x]  Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by verymahler** [comment]
I seem to have to sign-off stuff. Just take this code and make your own PR if needed.
It's previously signed off code copied from the stable/mysql chart anyway.
https://github.com/helm/charts/blob/master/stable/mysql/templates/deployment.yaml#L26

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

In this case, as it's a new feature/functionality, I think a minor bump is more correct, can you change it? Apart from that, the PR is ready to be merged.

**Comment by verymahler** [comment]
> In this case, as it's a new feature/functionality, I think a minor bump is more correct, can you change it? 

I could, but wouldn't that set back this patch again? My rationale was that it isn't new functionality, just an extra parameter that was missed the first time and a small enough change to constitute as a patch. It's similar to `podAnnotations`, but it just seemed that it was missed during initial release. 

If you insist, I'll add another commit for a higher version number.

**Pull request merged**
