### PR TITLE
[mssql-linux] Added feature for Collation and README.md cleanup

### PR DESCRIPTION
**Pull request by thomasliddledba**
- Added new feature to change the collation and lcid of the MSSQL Server instance
- README.md and NOTES.txt cleanup (incorrect version specified in examples)

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @thomasliddledba

**Comment by thomasliddledba** [comment]
LGTM.

**Comment by thomasliddledba** [comment]
Fixed Conflicts in PR

**Comment by thomasliddledba** [comment]
@timstoop or @unguiculus - could you review and LTGM.  Corrected conflicts from a PR.

**Pull request merged**
