### PR TITLE
[incubator/cassandra] Adding restore pod configurations in cassandra chart

### PR DESCRIPTION
**Pull request by prem0132**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
/unassign @maver1ck 
/assign

Hey @prem0132, thanks for getting involved!
I would like to discuss this PR a bit.

Do you feel that a restore feature should be a part of the chart?
Can you describe what does the workflow has to look like to support this?
For example, how do you prevent a restore on every upgrade of the chart? cain will clean all existing data on restore, so i suppose that users will not want that happening...

Thanks!

**Comment by prem0132** [comment]
Hi @maorfr,

Thanks for taking the time.
Yes, I think there should be a restore feature as an option. It is not enabled by default but the user can enable it during install or upgrade.
User will enable restore while releasing the chart, and the restore pod will fetch the backed up data and restore it. A few use cases can be, switching from one cloud provider to another, or moving your cluster to a different location, or loading the initial application schema on the db.
If you set restore to false before upgrading, there will be no restore for that upgrade. So i don't think there's any downside. What do you think?
 
`
restore:
  enabled: false
`

Thanks!!

**Comment by maorfr** [comment]
I suppose that makes sense. It may be a risk if someone leaves the restore flag enabled, so we should address that to prevent this case. I thing a post install hook can help us here. Will you look into it?

Now lets talk implementation.
I feel that this should be a Job rather then a pod. And also, shouldn't we re-use the `backup` section rather then duplicating it?

What do you think?

**Comment by prem0132** [comment]
Even if somebody leaves the restore flag on, the pod won't be recreated as there will already be a pod with completed state.
If we add a hook, and the not keep it in `values.yaml`, then we are making it really hard to launch it again.
While i was trying this, sometimes the restore stops midway, but if you delete the pod and then do an upgrade then it restores successfully. So i'd rather not limit options.

**Comment by prem0132** [comment]
I believe this is fine as a pod. Unless you have any strong reasons

**Comment by prem0132** [comment]
We can leverage the `backup` section but this is fine too, people may have different backup and restore needs

**Comment by maorfr** [comment]
Take a look at this discussuon regarding backup and restore #9987.
I have a problem with a reatore that can happen over and over again. A restore on install may be a sensible choice, but otherwise it will require 2 changes in code, one to restore and one to disable restore, which does not make sense, and is very error prone.

Regarding Pod vs Job - if a pod runs once and exists, it should be a job. A pod is intended to stay up.

Regarding different restore needs - I can only think of the restore vars. Bucket, annotations, image, tag, environment variables, and maybe more - will almost always remain identical between backup and restore. I prefer chart simplicity over premature optimization and over flexibility.

Have I managed to persuade you on anything here? ;)

**Comment by prem0132** [comment]
okay, so how about this, let's make it one time post install job. 
with same params as backup.

**Comment by maorfr** [comment]
I'm +1 for that!
Thanks for getting involved!
Ping me when this is ready for review again :)

**Pull request closed without merging**
