### PR TITLE
[incubator/kafka] Add limitation to readme

### LINKED ISSUE #5089: [incubator/kafka] kafka service name must not be `kafka`
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v2.5.1
Kubernetes: v1.7.5

**Which chart**:
incubator/kafka

**What happened**:
When using `incubator/kafka` as a dependency and configure it so that the service name matches `kafka`, the Kafka container fails with `port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead.`

This is because Kubernetes provides an env variable `KAFKA_PORT` named after the service name.
Unfortunately the `confluentinc/cp-kafka` image does not start if an env variable `KAFKA_PORT` is set.

**What you expected to happen**:
The [README Known Limitations](https://github.com/kubernetes/charts/tree/master/incubator/kafka#known-limitations) should state, that there must not exist a service called `kafka` in the same namespace

**How to reproduce it** (as minimally and precisely as possible):
dependency on `incubator/kafka` in `/requirements.yaml`
```
dependencies:
- name: kafka
  version: 0.5.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
```
`nameOverride` to `kafka` in `/values.yaml`
```
kafka:
  nameOverride: kafka
```
override of template function `kafka.fullname` in `/templates/_helpers.tpl`
```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "kafka.fullname" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

**Anything else we need to know**:

Discussion whether this can/should be addressed in [confluentinc/cp-kafka](https://github.com/confluentinc/cp-docker-images/blob/4.0.x/debian/kafka/include/etc/confluent/docker/configure)

### PR DESCRIPTION
**Pull request by TobiasPfeifer**
**What this PR does / why we need it**:
container won't start if there exists a service called 'kafka' in the target namespace. See #5089

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5089

### CODE REVIEW

**Comment by TobiasPfeifer** [comment]
Test is failing because chart version has not been increased which seems unnecessary for me
```
Error please increment the new chart version to be greater than the existing version of 0.5.2
```

**Comment by benjigoldberg** [comment]
@TobiasPfeifer thank you for the contribution to improve our docs!

If you wouldnt mind bumping the patch version I will go ahead and merge. I know this is just a documentation change but we always bump the patch version.

**Pull request merged**
