### PR TITLE
[stable/kafka-topics-ui] Add chart for landoop/kafka-topics-ui ✨

### PR DESCRIPTION
**Pull request by DhiaTN**
#### What this PR does / why we need it:
This PR is for creating a Chart for the `landoop/kafka-topics-ui`

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
Hey @DhiaTN,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by DhiaTN** [comment]
> Hey @DhiaTN,
> 
> Have you considered hosting this chart and adding it to helm hub?
> https://github.com/helm/hub/blob/master/Repositories.md

**Comment by DhiaTN** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the helm org.
>     * @grebois       
>       * stable/kafka-topics-ui/OWNERS
>     * @DhiaTN
>       * stable/kafka-topics-ui/OWNERS

My bad, the file is deleted!

**Comment by DhiaTN** [comment]
@lachie83 Hey man could you check this, I'm really looking to deploy 😃
Thanks in advance, cheers 🍻

**Comment by maorfr** [comment]
Hey @DhiaTN,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by DhiaTN** [comment]
> Hey @DhiaTN,
> Have you considered hosting this chart and adding it to helm hub?
> https://github.com/helm/hub/blob/master/Repositories.md

Hey @maorfr, yeah I will adding it to the helm hub once the Chart PR is merged ✔️👌

**Comment by maorfr** [comment]
Read this:
https://github.com/helm/hub/blob/master/docs/github.md

You can host your own charts repo and add THAT to helm hub. What do you think?

**Comment by DhiaTN** [comment]
> Read this:
> https://github.com/helm/hub/blob/master/docs/github.md
> You can host your own charts repo and add THAT to helm hub. What do you think?
 @maorfr I submitted here the PR for the hosted chart: https://github.com/helm/hub/pull/72

**Comment by maorfr** [comment]
nicely done!
can we close this PR then?

**Comment by DhiaTN** [comment]
> nicely done!
> can we close this PR then?

Done 🔚

**Pull request closed without merging**
