### PR TITLE
[stable/gocd] Update ingress doc

### PR DESCRIPTION
**Pull request by varshavaradarajan**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
@GaneshSPatil  -  GoCD agents outside of the cluster connect to the GoCD server through Ingress on port 80?

**Comment by arvindsv** [comment]
Looks good to me. I'll let @GaneshSPatil approve it. I wonder if we should add a link to (or mention) the location within values.yaml that these annotations need to be added to. Maybe it will be clear that it is [this](https://github.com/helm/charts/blob/dc4e53a219fc079074be8a2e8c65afb6608ac1f7/stable/gocd/values.yaml#L154)?

**Comment by varshavaradarajan** [comment]
@arvindsv - thank you! Yeah, I'll make that change. Looks like there's https://github.com/helm/charts/blob/dc4e53a219fc079074be8a2e8c65afb6608ac1f7/stable/gocd/values.yaml#L157 to add too.

**Review by GaneshSPatil — APPROVED** [review]

**Comment by varshavaradarajan** [comment]
@GaneshSPatil , @arvindsv  - um, one of you need to add lgtm for this to get merged.

**Pull request merged**
