### PR TITLE
[stable/prometheus-to-sd] Adding acondrat to prometheus-to-sd owners

### PR DESCRIPTION
**Pull request by acondrat**
Signed-off-by: Arcadie Condrat <arcadie.condrat@gmail.com>

#### What this PR does / why we need it:
Adding an OWNERS file
#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped - N/A
- [x] Variables are documented in the README.md - N/A
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
@acondrat, i suggest we upgrade to the latest prometheus-to-sd image, which is `0.5.2`.
wdyt?

**Comment by acondrat** [comment]
@maorfr e2e tests keep failing and I am not sure why. Where is the test infrastructure hosted? prometheus-to-sd cannot run outside GCE and it might be the reason for failures.

**Comment by maorfr** [comment]
/retest

afaik it is.

**Comment by acondrat** [comment]
OK, so the `--source` is now a mandatory flag so I had to add a default value. I don't think anyone (except prow) used that without a `source`. Should be good to go now.

**Pull request merged**
