### PR TITLE
[stable/elasticsearch] Deprecate Elasticsearch chart in favor of official Elastic chart.

### LINKED ISSUE #10543: Migrating stable/elasticsearch charts out of helm/charts
**FEATURE REQUEST**:

We would like to migrate the Elastic charts out of helm/charts.

But first some back story.
At  KubeCon in Seattle last year I ran into @jethr0null at the Elastic stand who is in charge of the effort to build Helm Charts for the Elastic suite.
We had a chat where she let me know  Elastic had their own Chart for deploying an Elasticsearch cluster into Kube and she wanted my opinion on them.

Today @jethr0null, @Crazybus and I had the first chat on how we would go about migrating people over to the Elastic Charts.

The first task on our list was to open a discussion with the community on how to proceed.
The second task is to write up a migration plan for people wanting to switch over.
There will be other tasks along the way but lets start there.

Elastic has already added their Chart repo to Helm Hub if you want to check them out.

If anyone has any concerns or comments this is the place to make them so we can work out how best to do this as the awesome community that we are.

### PR DESCRIPTION
**Pull request by desaintmartin**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10543

#### Special notes for your reviewer:

Thanks to all contributors and maintainers who built this chart, and hopefully see you at https://github.com/elastic/helm-charts. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @rendhalver @jethr0null @Towmeykaw @Crazybus @HaveFun83 @simonswine @icereval @KongZ @hectorj2f

/hold
Until consensus is achieved.

**Comment by KongZ** [comment]
@desaintmartin I'm agree to deprecate Elasticsearch chart but why you have to remove `maintainers` name 🤔

**Comment by desaintmartin** [comment]
This is the procedure defined at the root of this ropo: PROCESSES.md.

**Comment by Towmeykaw** [comment]
Is it a problem that the official chart doesn't "support" Helm 3.? I'm guessing it works but the Readme states that it is not supported.

**Comment by desaintmartin** [comment]
This is a fair point of discussion. I use it to deploy a dozen Elasticsearch clusters in production using helm 3 and I have no problem, but I think the problem comes from the testing which is done using helm 2 only, so no guarantee that it works with Helm 3. Is that right @crazybus?

**Comment by Crazybus** [comment]
> This is a fair point of discussion. I use it to deploy a dozen Elasticsearch clusters in production using helm 3 and I have no problem, but I think the problem comes from the testing which is done using helm 2 only, so no guarantee that it works with Helm 3. Is that right @Crazybus?

This is correct.

Issue for Helm 3 support is https://github.com/elastic/helm-charts/issues/401 with a WIP PR for adding automated testing in https://github.com/elastic/helm-charts/pull/516.

The core maintainer for the Elastic Helm Charts is now @jmlrt :) (and has been for a long time now). I still work for Elastic, and in the same team is @jmlrt so you will still see me around in https://github.com/elastic/helm-charts.

**Comment by rendhalver** [comment]
I have no objections at all.
Nice work gang!

**Comment by jmlrt** [comment]
Hi all,

FYI Elastic chart has been released in GA with [7.7.0 release](https://github.com/elastic/helm-charts/releases/tag/7.7.0) yesterday.

We're now ready to for stable chart deprecation.

As for Helm 3 support, we have general good feedbacks of users with Elastic chart and Helm 3 but still have some work in progress to automate the tests.

**Comment by desaintmartin** [comment]
Not stale.
Anyone?

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by Towmeykaw** [comment]
So should we just merge this then? I have no objections.

**Comment by desaintmartin** [comment]
/hold cancel
Let's do it :)

**Pull request merged**
