### PR TITLE
Mr/spinnakerenvs

### PR DESCRIPTION
**Pull request by mruepp**
#### What this PR does / why we need it:

Enables the values.yaml to deliver additional Environment Variables to the halyard container

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Pls review
@viglesiasce 
@dwardu89 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by papanito — APPROVED** [review]
That actually solves my issue https://github.com/spinnaker/spinnaker/issues/3988

**Comment by mruepp** [comment]
/assign @dwardu89 
Pls review

**Comment by sramek5** [comment]
Does it work?

**Pull request closed without merging**
