### PR TITLE
Fixed configmap mount failure.

### PR DESCRIPTION
**Pull request by ellisio**
**What this PR does / why we need it**:

This fixes the following error when `.Values.config` is not set:

```
$: kubectl describe pods newrelic-newrelic-infrastructure-8m6wh
// ... Output
Warning  FailedMount            3s (x5 over 11s)  kubelet, gke-apps-prod-jenkins-pool-de8095df-300w  MountVolume.SetUp failed for volume "config" : configmaps "newrelic-newrelic-infrastructure" not found
```

**Special notes for your reviewer**:

I forked the chart into our own chart repository, made this change, and the `DaemonSet`s properly started.

### CODE REVIEW

**Comment by timstoop** [comment]
@rk295 Your thoughts about this? I'm not sure how well it work without any configuration. Or are there sane defaults in the image itself?

**Comment by ellisio** [comment]
@timstoop @rk295 This change wont have any effect as no `ConfigMap` entry is generated if this value is not defined.

See: https://github.com/kubernetes/charts/blob/master/stable/newrelic-infrastructure/templates/configmap.yaml#L1

**Comment by unguiculus** [comment]
Closing as already fixed.

**Pull request closed without merging**
