### PR TITLE
[stable/traefik] bump version to 1.6.5

### PR DESCRIPTION
**Pull request by mavimo**
**What this PR does / why we need it**:

Update traefik version to 1.6.3

**Special notes for your reviewer**:

~~Waiting for https://github.com/docker-library/official-images/pull/4429 to be merged~~

cc/ @krancour @emilevauge @dtomcej @ldez

### CODE REVIEW

**Review by ldez — APPROVED** [review]

**Comment by timstoop** [comment]
Please merge from master to fix the Chart.yaml conflict.

**Comment by mavimo** [comment]
@timstoop @ldez @dtomcej 
I make a mistake and rebased instead of merge master and lost all LGTM, sorry :(

**Comment by dtomcej** [comment]
@dtzar I will discuss with the team about the 1.6 vs 1.6.x on the chart, since minor releases can be released weekly.

As for the alpine image, I will also discuss it, but it is less likely, since the scratch image is the official image.

**Comment by mavimo** [comment]
@dtomcej @dtzar IMHO we should keep the version pinned to exactly the same version. Minor change should fix some bug but since user is not aware of the fix the resulting behavior can change breaking my env, eg.:

 - Let suppose vX.Y.0 have a bug (eg: I need to duplicate each slash in URL for the ingress config.. I know is to evident bug to be released, but let just use it as sample)
 - I use the chart and do some "change" on my configuration in order to make it work in my env also with "duplicate slash" bug
 - a new release (vX.Y.1) fix the bug, so changes on my config should be removed before I deploy a new version

Having the traefik image automatically update on my env should be a bad way to distribute the app, and version should be overwritten by config so, if you're safe to automatically upgrade it you should setup the config on your chart deployment, not the default behavior on traefik helm chart.

**Comment by dtomcej** [comment]
@dtzar As promised, we discussed this as a team, and came to the same unanimous conclusion that @mavimo and @krancour have mentioned.

Having mutable tags, where the version of the image referred to is not pinned to the chart version becomes a stability and diagnostic nightmare.

I understand your frustration with the delay in chart updates, but we are working on having more people be able to approve them, to allow them to be released faster.

Degrading the stability of the chart for convenience is not really something that we want to entertain. If you would like to use the latest image with your chart, you can feel free to edit the chart on your end, and that will allow you to apply it immediately without having to wait for official chart updates.

**Comment by dtzar** [comment]
No problem, I understand the reasoning - It was only a suggestion to make less work on the maintainers while having the default be more up-to-date for those who deploy.  There are other charts out there which do this, but it is a tradeoff and relates to how stable you believe/experience the product is for bug fix changes.

FWIW - the existing chart seems to deploy fine even with the `1.7` tag.

**Comment by mavimo** [comment]
@dtomcej @krancour I can try to maintain this chart up-to-date but I'm not able to approve and merge so let me know if there is something that I can to to make easier to approve PR related to traefik

**Comment by dtomcej** [comment]
@mavimo We just got granted the proper access. Did you want to bump this chart from v1.6.3 to 1.6.5?

**Comment by mavimo** [comment]
@dtomcej sure, I'll do in few minutes

**Pull request merged**
