### PR TITLE
Signed-off-by: rstuberg <rstuberg@infoblox.com>

### PR DESCRIPTION
**Pull request by rstuberg-ib**
Changes to be committed:
	modified:   ingress.yaml
This changes the ingress to externalPort not port which is internal to the container.

This fixes issue: https://github.com/helm/charts/issues/12838 

If I messed up the contribution process please correct me.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@rstuberg-ib Please bump the chart version and sign the commits. TIA
/assign

**Comment by rstuberg-ib** [comment]
Wasn't sure what version to bump to so I bumped the chart version based off the state of (master) incubator now and signed the commit. 

 /assign @davidkarlsen

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
