### PR TITLE
[stable/jenkins] Fix typo in document of stable jenkins

### PR DESCRIPTION
**Pull request by tottoto**
Signed-off-by: tottoto <tottotodev@gmail.com>

No.

#### What this PR does / why we need it:

Fix markdown syntax error.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - Nothing.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] DCO signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [stable/mychartname])

### CODE REVIEW

**Comment by torstenwalter** [comment]
@tottoto You need to increase the chart version to make CI pass. Patch version increase would be ok for this. Thank you.

**Comment by tottoto** [comment]
@torstenwalter Thanks for your review and advice !!

I increased the chart version.

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Pull request merged**
