### PR TITLE
[stable/ignite] add priorityClassName support

### PR DESCRIPTION
**Pull request by bergerx**
#### What this PR does / why we need it:
Add priorityClassName support for stable/ignite chart.

#### Special notes for your reviewer:
This one is really a straightforward change and nothing special about Ignite.

According to the maintainers in the Chart.yaml: @aasiutin @greyteardrop
But apparently @cpanato @scottrigby @maorfr @zanhsieh and @fsniper looked after the last PR.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by aasiutin — APPROVED** [review]

**Review by GreyTeardrop — APPROVED** [review]

**Comment by bergerx** [comment]
Is there anything i can do for this go forward?

**Comment by scottrigby** [comment]
@bergerx there is no OWNERS file for this chart, but the maintainers are listed here: https://github.com/helm/charts/blob/master/stable/ignite/Chart.yaml

Also, have you seen this issue? https://github.com/helm/charts/issues/23685

**Comment by bergerx** [comment]
Ah just before my last comment i briefly checked and failed find a migration issue for ignite, and hence put the comment above hoping someone to take ownership and this bit not to get lost in the meantime.

Thanks for chasing the ownership on the Apache side. I hope that'll go smooth.

@aasiutin @GreyTeardrop do you mind taking a look here until the chart migrates to its new place?

**Comment by aasiutin** [comment]
@bergerx  I've assigned helm maintainer to this PR to approve. It seems I can't assign labels for this PR.

I'll create a PR to add OWNERS file later on. If you don't mind I'll add you there too. What do you think?

**Comment by bergerx** [comment]
This won't last long with the mid November deadline, but anyway I can review the PRs in the meantime, feel free add me.

**Comment by scottrigby** [comment]
@aasiutin it's because there is no OWNERS file for this chart, so no delegation functionality. I'll send your approval through since you're one of the maintainers in Chart.yaml

**Pull request merged**
