### PR TITLE
[stable/dex] Add ingress for dex

### PR DESCRIPTION
**Pull request by rendhalver**
Signed-off-by: Pete Brown <pete.brown@powerhrg.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by scottrigby — CHANGES_REQUESTED** [review]
Looking good, except please also update `NOTES.txt` to get the app URL when ingress is enabled. See the new [Ingress](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#ingress) section of REVIEW_GUIDELINES

**Comment by rendhalver** [comment]
@scottrigby Are you happy with the changes I have made?

**Comment by rendhalver** [comment]
@scottrigby Are you happy with this one?

**Review by scottrigby — APPROVED** [review]
Thanks for pinging me on Slack - these look great 👍

**Pull request merged**
