### PR TITLE
[NEW] kube-lego

### PR DESCRIPTION
**Pull request by mgoodness**
This is a stand-alone chart for kube-lego, as mentioned and (briefly) discussed in #385. Should be generic enough to be used with nginx-ingress (PR coming soon) or the GCLB.

@jackzampolin

### CODE REVIEW

**Comment by viglesiasce** [comment]
Tested this over the weekend without any issues.

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by jackzampolin** [comment]
Tested this with #399. LGTM

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by mgoodness** [comment]
I suspect there's a problem with the post-delete hook I introduced in my last commit. Let me try something...

**Comment by mgoodness** [comment]
My fix for now is not to clean up. kube-lego creates its own secret, ingress, and service, but only when it finds an externally-created ingress to handle. The e2e runs in an isolated environment, so those resources are never created and the cleanup jobs are never able to delete them. The jobs just keep running until Jenkins times out. Best I can do is add a `activeDeadlineSeconds` to each job, but that also looks like a failure.

Cleanup in this case might best be done by the application itself.

Let's see if I can have...
@k8s-bot e2e test this

Edit: Ha! Guess not.

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
@mgoodness worked this time around

**Pull request merged**
