### PR TITLE
[stable/prometheus] gRPC port on prometheus service

### PR DESCRIPTION
**Pull request by ni-slamberti**
#### Is this a new chart
no, it's not
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
It adds the possibility to expose the gRPC port on the prometheus service, not enabled by default.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@ni-slamberti 
Could you bump the chart version to the latest please? Thank you.

**Comment by ni-slamberti** [comment]
@zanhsieh 
should be ok now, let me know if there's anything else I can improve and sorry for all the notifications.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
