### PR TITLE
Just typo in filename

### PR DESCRIPTION
**Pull request by karnauskas**
Just a filename change for telegraf chart:
conifgmap-ds.yaml -> configmap-ds.yaml

### CODE REVIEW

**Comment by mattfarina** [comment]
Hi @karnauskas. Charts are immutable. Could you please increment the chart version in the Chart.yaml file.

Also, to accept contributions we need a signed CLA. Cloud you please sign the CLA or have your organization sign one if appropriate.

**Comment by sameersbn** [comment]
ping @karnauskas

**Comment by karnauskas** [comment]
Signed CLA

**Pull request merged**
