### PR TITLE
concourse: remove public part of signing key

### PR DESCRIPTION
**Pull request by databus23**
This is not needed anywhere.
The atc inferes the public part from the private key automatically.

/cc @frodenas

### CODE REVIEW

**Comment by lachie83** [comment]
@frodenas Thoughts on this?

**Comment by frodenas** [comment]
@lachie83 @databus23 Apologies, missed this one. LGTM.

**Comment by lachie83** [comment]
Perfect thanks @frodenas. One more question. Should this be a minor or major version bump in the chart?

**Comment by databus23** [comment]
@lachie83: I think a minor bump is fine. This PR removes a value that was not used by the application. So even if people used it, its not going to break anything.

**Comment by frodenas** [comment]
Yes, a minor bump.

**Comment by lachie83** [comment]
lgtm

**Pull request merged**
