### PR TITLE
Incubator/zookeeper#17183

### LINKED ISSUE #17183: [incubator/zookeeper] Allow quorumListenOnAllIPs to be configurable
**Is your feature request related to a problem? Please describe.**

When quorumListenOnAllIPs is set to "false" (the default value), Zookeeper binds to only the pod IP address and not 0.0.0.0.  This causes problems when using Istio as the proxy sidecar wants to forward packets to the localhost address which is not listening on port 3888, resulting in "connection refused" errors.  The end result is that the Zookeeper nodes are unable to elect a leader and the ensemble never starts.

When quorumListenOnAllIPs is set to "true", Zookeeper binds to 0.0.0.0 and the Istio proxy sidecar is able to forward packets to Zookeeper.

**Describe the solution you'd like**
I would like a new environment value (env.ZK_QUORUM_LISTEN_ALL_IP) added to the values file that would allow quorumListenOnAllIPs to be enabled.  The config-script.yaml file would append the directive to the zoo.cfg file.  The default value would be "false" to maintain compatibility with previous behavior.

**Describe alternatives you've considered**

**Additional context**
I've already made and tested this change locally

### PR DESCRIPTION
**Pull request by jlforester**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Allows the Zookeeper quorumListenOnAllIPs option to be enabled at deployment time.  This is needed to enable Zookeeper to work with Istio.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #17183

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@jlforester 
Would you bump the chart version again to latest please? Thank you.

**Comment by jlforester** [comment]
> @jlforester
> Would you bump the chart version again to latest please? Thank you.

I seem to have royally messed up something.  I bumped the chart version as requested, but forgot to sign off on the commit.  Now I have a older commit that I can't amend to add the signoff and checks are failing.

Any advice?

**Comment by zanhsieh** [comment]
@jlforester 
I think it's file conflicting:
incubator/zookeeper/Chart.yaml

Even you don't sign every commit, e2e test could still run.

**Comment by jlforester** [comment]
> @jlforester
> I think it's file conflicting:
> incubator/zookeeper/Chart.yaml
> 
> Even you don't sign every commit, e2e test could still run.

@zanhsieh I've bumped the chart version again (it had changed again in the meantime) and resolved the conflict.

**Comment by esnible** [comment]
I could really use this feature.  I independently rediscovered this issue today, and came up with the same fix after two hours.  @lachie83 can you bump the version again and request a merge?

**Review by linsun — APPROVED** [review]

**Comment by linsun** [comment]
+1 - we ran into this in istio and we have to use this flag to get zookeeper running in the mesh.  I have tested this PR (a similar version)

**Comment by esnible** [comment]
I could really use this.  @lachie83 can you bump the version again and request a merge?  Or is there another PR that gives this function?

**Comment by Bengreen** [comment]
any updates or alternative proposals to this PR.

**Pull request closed without merging**
