### PR TITLE
[stable/grafana] Update to latest grafana (7.0.1->7.0.3) and latest sidecar (0.1.99->0.1.151)

### PR DESCRIPTION
**Pull request by asherf**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
/test pull-charts-e2e
--

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
