### PR TITLE
[stable/redis-ha] Updating Prometheus exporter support in for HAProxy

### LINKED ISSUE #17564: [stable/redis-ha] haproxy - disable exporter
**Describe the error:**
I do not want to use metrics so I have disabled exporter.
In the case of HAProxy, the conditions are missing and we always has prometheus annotations.

**Which table:**
redis-ha-3.7.13

**What happened:**
Prometheus is always looking for metrics.

**How to play it (as minimal and precise as possible):**
Deploy with HAProxy and disabled indicators. Then check the prometheus scrap status.

### PR DESCRIPTION
**Pull request by DandyDeveloper**
#### What this PR does / why we need it:
Disables exporter for HAProxy. Supports enabling and port changes now. 

#### Which issue this PR fixes
  - fixes #17564

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
@DandyDeveloper I see this error on last CI run. Is there a hard anti-affinity between the redis pods and the haproxy pod? It seems like it's not scheduling one of the pods as a result of the affinity rules but I can't tell which.

```
I1102 01:27:22.664]   Warning  FailedScheduling  2m (x6 over 2m35s)  default-scheduler                                0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules.
```

**Comment by ssalaues** [comment]
Hmm it's also possible that it's a scheduling issue with the test pod itself since the default affinity rules validates against the app and release labels which are templated on the test pod.
https://github.com/helm/charts/blob/master/stable/redis-ha/templates/tests/test-redis-ha-pod.yaml#L6

**Comment by DandyDeveloper** [comment]
@ssalaues Maybe? But I haven't touched any of those things haha, I've made some relatively minor adjustments. Super confusing.

**Comment by ssalaues** [comment]
@DandyDeveloper I don't think it's a direct result of anything we've changed/merged but likely some infra changes here that allows us to see this issue now. I was curious so I spun up and ran `helm test` on a 3 node cluster and I see a similar affinity issue preventing scheduling of the test pod. I typically use a 5+ nodes which is why I've been oblivious but I can make a PR for it can add it to this one.

**Comment by ssalaues** [comment]
@DandyDeveloper just needs a version bump and it's good to go

**Comment by DandyDeveloper** [comment]
@ssalaues

**Comment by ssalaues** [comment]
Sorry @DandyDeveloper this one slipped by me when I merged some PRs this morning.

**Comment by DandyDeveloper** [comment]
@ssalaues

**Pull request merged**
