### PR TITLE
Update charts to support imagePullSecrets as well as SELinux labeling

### PR DESCRIPTION
**Pull request by kurktchiev**
#### What this PR does / why we need it:
Datadog/MSSQL: Adding imagePullSecret support so images can be pulled from private registries
Datadog: add the ability to modify the SELinux labeling of the containers. Specifically needed for the diamanti.com platform

MSSQL: @thomasliddledba 
DataDog: @hkaj @irabinovitch @xvello @charlyf

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by thomasliddledba** [comment]
LGTM - Great contribution

**Comment by xvello** [comment]
/ok-to-test

hi @kurktchiev,
Thanks for the contribution. Our recommended selinux role is [`spc_t`](https://github.com/DataDog/datadog-agent/blob/4ab9dd712c0819640bc862f9c8a7275068668876/Dockerfiles/manifests/openshift/scc.yaml#L24-L32) as [described here](https://danwalsh.livejournal.com/74754.html). Could you please change the commended default?

**Comment by xvello** [comment]
Thanks! You'll need to signoff your commits though

/lgtm

**Comment by kurktchiev** [comment]
> Thanks! You'll need to signoff your commits though
> 
> /lgtm

Yeah I cant figure out why its failing on sign off even though i just ammend --signoff the whole branch... investigating

**Comment by xvello** [comment]
Looks like [this one](https://github.com/helm/charts/pull/9234/commits/441d82eccab5973b691b9a340315c4f166a7e254) is missing sign-off

**Comment by kurktchiev** [comment]
> Looks like [this one](https://github.com/helm/charts/pull/9234/commits/441d82eccab5973b691b9a340315c4f166a7e254) is missing sign-off

yeah i seem to be unable to get to my own commit to edit it... and i think its all coming from me doing it straight in here instead of on my local repo.

**Pull request closed without merging**
