### PR TITLE
[stable/metricbeat] Update metricbeat to 6.6.2

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by at-k** [comment]
Thank you for you contribution!
But this issue is solved on this [PR](https://github.com/helm/charts/pull/12593). Please confirm it.

**Comment by ialidzhikov** [comment]
Thank you, @at-k . I will close this one.

**Pull request closed without merging**
