### PR TITLE
[stable/bookstack] upgrade bookstack to 0.27.4-1

### PR DESCRIPTION
**Pull request by solidnerd**
#### What this PR does / why we need it:
Upgrade to the latest bookstack version

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by verwilst** [comment]
/ok-to-test

oops :-)

**Comment by solidnerd** [comment]
ping @verwilst  I need to update to the latest again.

**Pull request merged**
