### PR TITLE
Fix README.md persistence.enabled value

### PR DESCRIPTION
**Pull request by rilleralle**
The default value defined in the values.yaml file is set to true.

### CODE REVIEW

**Review by thomasliddledba — APPROVED** [review]
/lgtm

**Comment by thomasliddledba** [comment]
@rilleralle - Looks like you have a commit that is not signed off.  You will need to fix that to have this merged.  Review the following documentation in this repo for assistance.

https://github.com/helm/charts/blob/3fddb0cf9cdc94c845ccf053dfadda2b751ea9e7/CONTRIBUTING.md#how-to-contribute-to-an-existing-chart

**Comment by rilleralle** [comment]
Hi @thomasliddledba,
sorry I was not aware about the sign off. Thx for the hint.

**Review by thomasliddledba — APPROVED** [review]
/lgtm

**Pull request merged**
