### PR TITLE
Update incubator/etcd to statefulset (#631)

### PR DESCRIPTION
**Pull request by lwolf**

### CODE REVIEW

**Comment by lwolf** [comment]
I signed it!

**Comment by shashidharatd** [comment]
cc @kubernetes/charts-maintainers, can you PTAL

**Comment by lachie83** [comment]
@lwolf Can you please bump the chart version. then this will be gtg

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lwolf** [comment]
Can somebody resolve the conflict, since I don't have write access?

**Comment by lachie83** [comment]
@lwolf resolved. LGTM

**Pull request merged**
