### PR TITLE
[stable/phabricator] Add preamble and ingress support

### PR DESCRIPTION
**Pull request by Azuka**
This adds [preamble support](https://secure.phabricator.com/book/phabricator/article/configuring_preamble/) (useful when running behind a loadbalancer) as well as ingress support to the phabricator chart.

Confirmed working on GKE.

### CODE REVIEW

**Comment by sameersbn** [comment]
@Azuka the PR is being reviewed by @tompizmor. I think he has some issues getting the changes from the PR to work. Let's wait for him to get back with this findings.

**Comment by tompizmor** [comment]
@Azuka As Sameer said, I am unable to make this PR works on GKE. The phabricator image fails to initialize after mounting the preamble.php script with `$_SERVER['HTTPS'] = true;` content.
The issue I get in the phabricator pod is the following:

```
Error executing 'postInstallation': There was an issue while passing the registration of the admin user. The error was: Error: socket hang up
socket hang up
nami    TRACE Error: Error executing 'postInstallation': There was an issue while passing the registration of the admin user. The error was: Error: socket hang up
socket hang up
```

There is a similar PR and I think @sammerry documented how to work around this issue [here](https://github.com/kubernetes/charts/pull/3370/files#diff-557a859e24d9c95cd17f78f5c118b615)

However, I think this issue should be fixed in the Phabricator docker image.

**Comment by Azuka** [comment]
Thanks @sameersbn and @tompizmor. 

Sorry, I didn't realize you were working on it. I have this running in my GKE instance but it might be that I applied the preamble after the initialization of the phabricator db and volumes.

I'll try to retest locally with a fresh install.

**Comment by Azuka** [comment]
@tompizmor I'm going to close this is favor of #3370 as that appears to provide a more complete implementation.

**Comment by tompizmor** [comment]
@Azuka OK. Just for you to know, we have released a new version of the phabricator docker image (`2018.3.0-r1`) with a new apache configuration. With this configuration, the preamble script is not necessary.

**Pull request closed without merging**
