### PR TITLE
[stable/minio]: fix extraArgs values being ignored by minio binary inside pod

### LINKED ISSUE #20089: [stable/minio] fix handling of extraArgs
**Describe the bug**
Additional arguments passed in as values in `extraArgs` is ignored inside the pod even if they are listed in command field. e.g. when describing the pod or deployment.

**Version of Helm and Kubernetes**:
irrelevant for this issue

**Which chart**:
stable/minio v5.0.4

**What happened**:
Additional arguments are not passed to minio binary.

```
$ kubectl describe pod minio-6d5bd7789-7cbd2

...
Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
      --compat
...

```
```
$ kubectl exec -it minio-6d5bd7789-7cbd2 sh

/ # ps
PID   USER     TIME  COMMAND
    1 root      0:06 minio -S /etc/minio/certs/ server /export

```

**What you expected to happen**:
Additional arguments to be passed to Minio binary. Arguments should be in the same line as docker-entrypoint.sh, e.g:

```
$ kubectl describe pod <podname>
...
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export --compat
...
```
```
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:08 minio -S /etc/minio/certs/ server /export --compat
```

**How to reproduce it** (as minimally and precisely as possible):
`$ helm install --set extraArgs="{--compat}" stable/minio`

**Anything else we need to know**:
Refer to discussion in #17075

### PR DESCRIPTION
**Pull request by hutr**
#### What this PR does / why we need it:
Fix extraArgs to be on same line as docker-entrypoint.sh, else the arguments will be ignored inside the pod. 
Improvement for PR #19904 

#### Which issue this PR fixes
  - fixes #20089 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jaygridley** [comment]
Can we get any traction here?

**Comment by solomson** [comment]
Would like this fix as we currently have to fork our own chart just as a workaround..

**Comment by remiguittaut** [comment]
+1, really need this PR merged...

**Comment by hutr** [comment]
Trying again, only change since last time is the chart version which has been bumped to 5.0.15.
/assign @krisis

**Comment by hutr** [comment]
How can we merge this request?
I tried to fix the DCO signoff, but it removed the lgmt label.
Can someone point me to the right direction how to fix the dco signoff?

**Comment by bad** [comment]
How do we go on from here?  Apparently this fails because the Chart version got bumped on master in the meantime.  And @hutr has been inactive lately.

**Comment by harshavardhana** [comment]
Please bump the version in this PR @bad

**Comment by hutr** [comment]
I will bump the chart version to 5.0.20

**Comment by harshavardhana** [comment]
You have multiple things still missing in this PR @hutr - the DCO is not complete.

**Comment by bad** [comment]
> You have multiple things still missing in this PR @bad - the DCO is not complete.

@harshavardhana : @hutr is updating his pull request.  You need to mention him.

**Comment by harshavardhana** [comment]
@hutr you haven't completed DCO without that we can't merge this PR to helm repo.

**Comment by harshavardhana** [comment]
Check what do to do here https://github.com/helm/charts/pull/20091/checks @hutr

**Comment by hutr** [comment]
> > You have multiple things still missing in this PR @bad - the DCO is not complete.
> 
> @harshavardhana : @hutr is updating his pull request. You need to mention him.

Regarding DCO, i forgot to sign the first [commit ](https://github.com/helm/charts/pull/20091/commits/199295eb25fd3708eb6fe36bbae9f735c8cc4978)i did back in january. Not sure how to fix this. Any pointers?

**Comment by harshavardhana** [comment]
> Regarding DCO, i forgot to sign the first [commit ](https://github.com/helm/charts/pull/20091/commits/199295eb25fd3708eb6fe36bbae9f735c8cc4978)i did back in january. Not sure how to fix this. Any pointers?

Squash all commits locally sign them into one commit

**Comment by bad** [comment]
> > Regarding DCO, i forgot to sign the first [commit ](https://github.com/helm/charts/pull/20091/commits/199295eb25fd3708eb6fe36bbae9f735c8cc4978)i did back in january. Not sure how to fix this. Any pointers?
> 
> Squash all commits locally sign them into one commit

Or do an interactive rebase and reword the first commit

**Comment by hutr** [comment]
> > > Regarding DCO, i forgot to sign the first [commit ](https://github.com/helm/charts/pull/20091/commits/199295eb25fd3708eb6fe36bbae9f735c8cc4978)i did back in january. Not sure how to fix this. Any pointers?
> > 
> > 
> > Squash all commits locally sign them into one commit
> 
> Or do an interactive rebase and reword the first commit

Thanks guys, DCO is fixed now

**Comment by bad** [comment]
> > > > Regarding DCO, i forgot to sign the first [commit ](https://github.com/helm/charts/pull/20091/commits/199295eb25fd3708eb6fe36bbae9f735c8cc4978)i did back in january. Not sure how to fix this. Any pointers?
> > > 
> > > 
> > > Squash all commits locally sign them into one commit
> > 
> > 
> > Or do an interactive rebase and reword the first commit
> 
> Thanks guys, DCO is fixed now

Thank you guys for handling this so quickly.

**Pull request merged**
