### PR TITLE
[stable/minio] Add missing service account

### PR DESCRIPTION
**Pull request by tylercamp**
#### What this PR does / why we need it:
Adds minio service account definition that was missing in the original pull request https://github.com/helm/charts/pull/14917

#### Which issue this PR fixes
  - Not a formal issue but a comment on the previous pull request https://github.com/helm/charts/pull/14917#issuecomment-506803162

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

thanks for the quick fix!
i added a new line just to get this merged in faster.

**Comment by tylercamp** [comment]
@maorfr Any idea why that check would fail? Installs fine for me locally with default values and RBAC enabled.

**Pull request merged**
