### PR TITLE
[stable/prometheus-cloudwatch-exporter] Update cloudwatch-exporter version.

### PR DESCRIPTION
**Pull request by asherf**
Update version
https://github.com/prometheus/cloudwatch_exporter/releases/tag/cloudwatch_exporter-0.6.0

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@asherf 
If this PR passed, would you mind to volunteer to be one of the OWNER as replacement to @gianrubio ? It seems @gianrubio lost interest in maintaining helm chart. See:

https://github.com/helm/charts/issues/13867

**Comment by asherf** [comment]
@zanhsieh I am happy to do it.
https://github.com/helm/charts/issues/13867#issuecomment-543385179

**Comment by asherf** [comment]
@torstenwalter friendly ping :-)

**Pull request merged**
