### PR TITLE
[stable/prometheus-operator] Mark **An example template** explicitly as comment

### PR DESCRIPTION
**Pull request by deepaksood619**
It's a small change, but for a beginner it is not obvious and can take half a day to solve this.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by anothertobi** [comment]
Thank you for the PR, please bump the chart version in `Chart.yaml` so that tests can run successful.

**Comment by deepaksood619** [comment]
> Thank you for the PR, please bump the chart version in `Chart.yaml` so that tests can run successful.

Thanks for considering this PR, this is my first PR. I will start contributing more. Thanks

**Review by anothertobi — APPROVED** [review]

**Pull request merged**
