### PR TITLE
[stable/traefik] Add startupArguments to storeconfig job

### PR DESCRIPTION
**Pull request by jpiron**
Signed-off-by: Jonathan Piron <jonathanpiron@gmail.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

Provide startupArguments to the storeconfig job.

#### Which issue this PR fixes

None

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jpiron** [comment]
Hi, any update on this ?

**Comment by zanhsieh** [comment]
@emilevauge
@dtomcej
@timoreimann
@vdemeester
@nmengin
@mmatur
@ldez
@Juliens
@jbdoumenjou
@geraldcroes
@SantoDE
@errm
Please review this. Thank you.

**Comment by jpiron** [comment]
Conflicts solved

**Pull request merged**
