### PR TITLE
[stable/prometheus-operator] PrometheusRule Admission Webhooks

### LINKED ISSUE #1547: Add service annotations support (Enhancement proposal)
In non-operator helm prometheus there is a interesting defautl configuration that allows to scrape any service or endpoints with specific annotations:

```
annotations:
  prometheus.io/port: "80"
  prometheus.io/scrape: "true"
```

I think a default 'ServiceMonitor' with similar configuration can be very useful (in particular for migrations)

### PR DESCRIPTION
**Pull request by vsliouniaev**
#### What this PR does / why we need it:
With Prometheus Operator version 0.30+, the core Prometheus Operator pod exposes an endpoint that will integrate with the `validatingwebhookconfiguration` Kubernetes feature to prevent malformed rules from being added to the cluster.

##### How the Chart Configures the Hooks
A validating and mutating webhook configuration requires the endpoint to which the request is sent to use TLS. It is possible to set up custom certificates to do this, but in most cases, a self-signed certificate is enough. The setup of this component requires some more complex orchestration when using helm. The steps are created to be idempotent and to allow turning the feature on and off without running into helm quirks.
1. A pre-install hook provisions a certificate into the same namespace using a format compatible with provisioning using end-user certificates. If the certificate already exists, the hook exits.
2. The prometheus operator pod is configured to use a TLS proxy container, which will load that certificate.
3. Validating and Mutating webhook configurations are created in the cluster, with their failure mode set to Ignore. This allows rules to be created by the same chart at the same time, even though the webhook has not yet been fully set up - it does not have the correct CA field set.
4. A post-install hook reads the CA from the secret created by step 1 and patches the Validating and Mutating webhook configurations. This process will allow a custom CA provisioned by some other process to also be patched into the webhook configurations. The chosen failure policy is also patched into the webhook configurations

##### Alternatives
It should be possible to use [jetstack/cert-manager](https://github.com/jetstack/cert-manager) if a more complete solution is required, but it has not been tested.

##### Limitations
Because the operator can only run as a single pod, there is potential for this component failure to cause rule deployment failure. Because this risk is outweighed by the benefit of having validation, the feature is enabled by default.

- Fixes: https://github.com/coreos/prometheus-operator/issues/1547

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by Smirl** [comment]
I think this might have introduced a bug as I am getting 
```
missing required field "caBundle" in io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig
```

I also think that adding the new options in the README broke the markdown table:
image

**Comment by vsliouniaev** [comment]
@Smirl I think that validation comes from another webhook config you have set up in your cluster. I have seen this with the Open Policy Agent default config before. It's a valid configuration according to the kubernetes spec

Thanks for calling out the borked markdown

**Pull request merged**
