### PR TITLE
[stable/spinnaker] update spinnaker dependencies for kubernetes 1.16 and higher

### PR DESCRIPTION
**Pull request by ramonskie**
resolves issue #18460

bumped redis and minio depenencies as they set the correct api endpoints for k8
also needed to remove the `job` feature flag as it is removed in halyard.

### CODE REVIEW

**Comment by zanhsieh** [comment]
@ramonskie 
Could you sign DCO and bump the chart to latest version please? Thank you.

**Comment by ramonskie** [comment]
@zanhsieh am i responsible for a new release version?
i was under the impression that this would be handled by a ci.

**Comment by vsliouniaev** [comment]
/ok-to-test

Afraid so - specified in the PR template

```
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
```

**Comment by ramonskie** [comment]
is there anything else i need to do?

**Comment by zanhsieh** [comment]
@ramonskie 
As @vsliouniaev mentioned:
```
Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
```

**Comment by fjudith** [comment]
When this PR will be merged ?

It is actually impossible to deploy spinnaker on k8s 1.16+

**Comment by srinathkotu** [comment]
@fjudith not sure if you have found a work around this github issue has a few workarounds
https://github.com/helm/charts/issues/18460

**Comment by srinathkotu** [comment]
@dwardu89 @lwander any update for this merge request?

It would be amazing if this can be merge, cause i don't need to spend hours to make sure if the new version of spinnaker helm chart works properly with the latest release of spinnaker version

**Comment by ramonskie** [comment]
@zanhsieh any update or is there anything i can do?

**Comment by sadoMasupilami** [comment]
it would be great if this could be merged?

**Comment by zanhsieh** [comment]
@ramonskie 
Could you resolve two conflict files listed on the bottom of this page? Thank you.

**Comment by ramonskie** [comment]
@zanhsieh solved the conflicts
@viglesiasce @dwardu89 can you please merge?

**Pull request closed without merging**
