### PR TITLE
Typo fix in anchore-engine/README.md: and->an

### PR DESCRIPTION
**Pull request by AdamDang**
Line 44: Using and existing/external PostgreSQL service
              and->an

### CODE REVIEW

**Comment by viglesiasce** [comment]
cc @zhill

**Comment by zhill** [comment]
@AdamDang thanks for catching this

**Comment by AdamDang** [comment]
/assign @timstoop @viglesiasce
Hello, This typo is very obvious, Please can you help to aprove it? it's issued already one week.
Thanks a lot!

**Pull request merged**
