### PR TITLE
add to Grafana documentation some missing services parameters which appear in the service template

### PR DESCRIPTION
**Pull request by royeectu**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by royeectu** [comment]
@maorfr could you please go over the PR?

**Comment by royeectu** [comment]
@davidkarlsen why does the test fail?
What do I need to do?

**Comment by royeectu** [comment]
@maorfr , why does the test fail?

**Comment by maorfr** [comment]
You need to rebase. Current chart version in master is 4.1.0.

**Pull request merged**
