### PR TITLE
[stable/prometheus] Fix server.alertmanagers

### LINKED ISSUE #19801: [stable/prometheus] Cannot configure alertmanagers if alertmanager is not enabled
**Describe the bug**
I'm a little bit unsure if this should be considered a bug or not but I decided that it was a bug. It is not possible to set "server.alertmanagers" if "alertmanager.enabled" is not true. I don't see how a local Alertmanager cluster should be a prerequisite for configuring alertmanagers in Prometheus Server.

**Version of Helm and Kubernetes**:
3.0.0, 1.14

**Which chart**:
stable/prometheus

**What happened**:
I cannot set alertmanagers for Prometheus Server unless the chart is configured to install Alertmanager.

**What you expected to happen**:
I expect that server.alertmanagers will set static alertmanager config.

**How to reproduce it** (as minimally and precisely as possible):
Set server.alertmanagers to something while disabling the installation of alertmanager.

**Anything else we need to know**:
The way this is implemented makes zero sense as you'd never want to use static alertmanager configuration (server.alertmanagers) if you have a local installment (which you always have with alertmanager.enabled). Then you'd always want to find Alertmanagers with the SD config options.

### PR DESCRIPTION
**Pull request by mattiasnensen**
Signed-off-by: Mattias Nensén <mattias.nensen@sinch.com>

#### What this PR does / why we need it:
This makes it so that we can set Alertmanagers even if we don't install a local Alertmanager.

#### Which issue this PR fixes
  - fixes #19801

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [-] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by mattiasnensen** [comment]
Can someone help me figure out why the pull-charts-e2e job is failing?

**Comment by zanhsieh** [comment]
@vsliouniaev 
Would you mind to help me out please? Thanks.

**Comment by zanhsieh** [comment]
Thank you @mattiasnensen 
/lgtm

**Pull request merged**
