### PR TITLE
[stable/newrelic-infrastructure] Set the namespace in all the resources

### PR DESCRIPTION
**Pull request by alejandrodnm**
Signed-off-by: Alejandro Do Nascimento <alejandrodnm@gmail.com>

#### What this PR does / why we need it:
Sets the namespace for all the resources to the release namespace. This allows users to customize were the resources are going to be created.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by alejandrodnm** [comment]
cc @douglascamata

**Comment by davidkarlsen** [comment]
There is no need for this - helm does this automatically.

**Pull request closed without merging**
