### PR TITLE
[stable/chaoskube] Adding support for kube v1.17

### PR DESCRIPTION
**Pull request by li-adrienloiseau**
**Is this a new chart**
No.

**What this PR does / why we need it:**
Adds possibility to support Kubernetes v1.17.
On others charts the default value of apiVersion is:
`apiVersion: apps/v1`

### CODE REVIEW

**Comment by linki** [comment]
How about dropping the `if` entirely and just support `apps/v1`? Seems like a lot of charts do that, e.g. https://github.com/helm/charts/blob/master/stable/envoy/templates/deployment.yaml

**Comment by li-adrienloiseau** [comment]
> How about dropping the `if` entirely and just support `apps/v1`? Seems like a lot of charts do that, e.g. https://github.com/helm/charts/blob/master/stable/envoy/templates/deployment.yaml

indeed, it was a better solution.
/assign @linki

**Comment by linki** [comment]
@li-adrienloiseau You need to sign-off your commits in order for us to merge then. You can find out how to do that here: https://github.com/helm/charts/pull/23170/checks?check_run_id=897778129

**Comment by linki** [comment]
@li-adrienloiseau You also need to update the chart's version here: https://github.com/helm/charts/blob/c85fd771f3ab922253db745e3a428574266e0c1b/stable/chaoskube/Chart.yaml#L3

Let's make it `3.2.0`.

**Comment by mattfarina** [comment]
@li-adrienloiseau thanks for the contribution. Helm uses a [Developer Certificate of Origin (DCO)](https://developercertificate.org/) to show that you can contribute the content. This requires signoff in Git. The _checks_ tab at the top has commands you can run to fix this. Can you please signoff.

**Comment by li-adrienloiseau** [comment]
> @li-adrienloiseau You also need to update the chart's version here:
> 
> https://github.com/helm/charts/blob/c85fd771f3ab922253db745e3a428574266e0c1b/stable/chaoskube/Chart.yaml#L3
> 
> Let's make it `3.2.0`.

/assign @linki it's ok

**Comment by li-adrienloiseau** [comment]
> @li-adrienloiseau thanks for the contribution. Helm uses a [Developer Certificate of Origin (DCO)](https://developercertificate.org/) to show that you can contribute the content. This requires signoff in Git. The _checks_ tab at the top has commands you can run to fix this. Can you please signoff.

wtf ? with you're command:
`it rebase HEAD~5 --signoff`

Capture d’écran 2020-07-29 à 11 05 56

**Comment by li-adrienloiseau** [comment]
> > @li-adrienloiseau thanks for the contribution. Helm uses a [Developer Certificate of Origin (DCO)](https://developercertificate.org/) to show that you can contribute the content. This requires signoff in Git. The _checks_ tab at the top has commands you can run to fix this. Can you please signoff.
> 
> wtf ? with you're command:
> `it rebase HEAD~5 --signoff`
> 
> Capture d’écran 2020-07-29 à 11 05 56

/assign @mattfarina

**Comment by t1bb4r** [comment]
looks liked you signed 1290 commits by mistake

**Comment by linki** [comment]
Oh boy, I totally ignored that :disappointed:

@t1bb4r The merged YAML looks correct. It's just the huge commit comment that is wrong. Do you know if that has any negative consequences?

**Pull request merged**
