### PR TITLE
stable/prometheus-operator README.md markup fix

### PR DESCRIPTION
**Pull request by shubhamc183**
#### What this PR does / why we need it:
Just a simple typo in README.md markup

FROM: `alertmanager.alertmanagerSpec.`configSecret
TO: `alertmanager.alertmanagerSpec.configSecret`

### CODE REVIEW

**Comment by vsliouniaev** [comment]
You need to
- bump the chart version
- sign off the commit with `git commit --amend -s` `git push -f`

**Comment by shubhamc183** [comment]
@vsliouniaev do you still want to me do anything here because this is a very small change related to README.md?

**Comment by vsliouniaev** [comment]
> @vsliouniaev do you still want to me do anything here because this is a very small change related to README.md?

I don't control any aspects of the CI of this repo, so I cannot relax the requirements of the pull request process. The instructions on what to do are part of the readmes in this repo.

**Pull request merged**
