### PR TITLE
[stable/mariadb] Upgrade app version from 10.1 to 10.3

### PR DESCRIPTION
**Pull request by carrodher**
#### What this PR does / why we need it:

This PR upgrades the app version for this chart, from MariaDB 10.1 to MariaDB 10.3.
There are no changes in the chart itself, but as it is a major version in the application code I added a section about upgrades.

I checked other charts using this one as a dependency and all of them are using a hardcoded version (not `x.x.x`), so this change shouldn't affect other charts:  
```bash
$ ag 'name: mariadb' */*/requirements.yaml -A 1
stable/bookstack/requirements.yaml
2:- name: mariadb
3-  version: 4.4.x

stable/drupal/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/ghost/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/jasperreports/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/joomla/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/magento/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/mediawiki/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/moodle/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/nextcloud/requirements.yaml
2:- name: mariadb
3-  version: ~5.5.0

stable/opencart/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/orangehrm/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/osclass/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/owncloud/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/phabricator/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/phpbb/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/phpmyadmin/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/prestashop/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/redmine/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/suitecrm/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/testlink/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x

stable/wordpress/requirements.yaml
2:- name: mariadb
3-  version: 5.x.x
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by carrodher** [comment]
I would like to keep it open some days just in case there are some concerns regarding the upgrading

**Comment by tompizmor** [comment]
LGTM! I think we should have updated MariaDB  to 10.3 already

**Comment by juan131** [comment]
+1 to moving to 10.3

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
