### PR TITLE
[stable/jenkins] Please stop distributing the support plugin installs

### PR DESCRIPTION
**Pull request by jetersen**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by casz** [comment]
@torstenwalter or @mogaal perhaps we should remove support plugin entirely the 1.18 is basically a tombstone plugin there is no functionality in the plugin

**Comment by torstenwalter** [comment]
@casz Happy to remove it entirely. It's only there for downward compatibility. But I guess it does not make sense to keep support for it. There is an if condition which prevents installation anyhow if the casc plugin version is new enough.

Would you do the removal?

**Comment by casz** [comment]
I'll happy do the removal :)

**Comment by casz** [comment]
I'll try and get back to this

**Comment by casz** [comment]
I promise I haven't forgotten 😓

**Comment by torstenwalter** [comment]
@casz Did you had time to look into it?

**Comment by casz** [comment]
No 😅 I simply haven't and I properly won't get around to it 😓

**Pull request closed without merging**
