### PR TITLE
[stable/external-dns] Support for GKE

### PR DESCRIPTION
**Pull request by olofwalker**
This PR adds support for using the chart with GKE without giving your instances global read/write access rights to Google DNS (as discussed in this issue https://github.com/kubernetes-incubator/external-dns/issues/283). 

It accomplish this by setting an pod environment variable containing Google Cloud service account credentials.

It also shows in an example in the `README.md` how to do this using `--set` from the command line, to avoid mixing sensitive information into `values.yaml`

### CODE REVIEW

**Comment by fuhbar** [comment]
Thanks @olofwalker for contributing this PR to the community. :)

**Comment by fuhbar** [comment]
@olofwalker your PR only considers the case of providing a secret by value. But its very common to provide a secret by reference. 

Please have a look at:
* https://github.com/fuhbar/charts/tree/support-for-google-cloud
* https://github.com/fuhbar/charts/commit/b49a50bfb4bd4ff6e96ec0662f1dc598200fa6fe

I've rebased your branch to most current master and added the above mentioned feature. 

Do you want to incorporate those changes by yourself or do you want me to open another PR?

@linki Whats the recommend procedure to get these depending changes into mainline?

**Comment by olofwalker** [comment]
@fuhbar I rebased your changes into my PR, I did however try to do this with a new git client :) So there where a couple of gotchas in the process so to speak, please double check me :)

**Comment by fuhbar** [comment]
Hi @olofwalker. It seems that the only difference for now is the following: 

```
diff --git a/stable/external-dns/templates/deployment.yaml b/stable/external-dns/templates/deployment.yaml
index ddb865ed..325cdd8b 100755
--- a/stable/external-dns/templates/deployment.yaml
+++ b/stable/external-dns/templates/deployment.yaml
@@ -13,6 +13,12 @@ spec:
     {{- end }}
       labels: {{ include "external-dns.labels" . | indent 8 }}
     spec:
+      volumes:
+      {{- if .Values.google.applicationCredentials }}
+        - name: {{ template "external-dns.google.volumeMountName" .}}
+          secret:
+            secretName: {{ template "external-dns.fullname" . }}
+      {{- end }}
       containers:
         - name: {{ template "external-dns.name" . }}
           image: "{{.Values.image.name}}:{{ .Values.image.tag }}"
```

But from what I see this has been already covered in [Line 121 and following](https://github.com/kubernetes/charts/pull/3499/files#diff-365725c21974b9cd63a265b33fd5e4f6R121).

What do you think?

**Comment by fuhbar** [comment]
@olofwalker What are you thought about my last comment? Do you agree that this is `volumes` section is unneeded?

**Comment by olofwalker** [comment]
@fuhbar Hi, just got some time to look at it, removed the volume. Tested secret by value on a new GKE instance and it seems to work good with these changes.

**Comment by fuhbar** [comment]
@olofwalker One last thing, you need to increment the version number:

```
Checking the Chart version has increased for the chart at stable/external-dns
Error please increment the new chart version to be greater than the existing version of 0.4.9
Exited with code 1
```

Thanks :)

**Comment by linki** [comment]
I bumped it to the next patch version `0.4.10`.

**Comment by linki** [comment]
@olofwalker you changed the file permissions: `100644 → 100755`. Was that by mistake? I think these files shouldn't be executable.

**Comment by olofwalker** [comment]
@linki That is very interesting, not knowingly changed those, will remove the exec bit and push.

**Comment by pnovotnak** [comment]
What's left to do here?

**Comment by prydonius** [comment]
Looks like this now needs to be rebased, also looks like some pods aren't coming up from the last test so please see to that. Once those issues are fixed, it would be great to get this in :).

**Pull request closed without merging**
