### PR TITLE
[stable/prometheus-operator] Add ThanosRuler resources to ClusterRole

### LINKED ISSUE #21171: [stable/prometheus-operator] Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
**Describe the bug**
There is an unexpected flood of error message for Thanos Ruler CRDS

**Version of Helm and Kubernetes**:
Helm: 2.15.1
Kubernetes: v1.14.10-gke.17

**Which chart**:
prometheus-operator version 8.10.0

**What happened**:
```
E0301 17:04:11.624026       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:315: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0301 17:04:12.626151       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:315: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0301 17:04:13.653165       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:315: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0301 17:04:14.655977       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:315: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0301 17:04:15.658397       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:315: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:sandbox-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
```

**What you expected to happen**:
No error log message

**How to reproduce it** (as minimally and precisely as possible):
Install Helm prometheus-operator version 8.10.0

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by sbuzonas**
#### What this PR does / why we need it:

Add ThanosRuler resource to ClusterRole required by prometheus-operator

#### Which issue this PR fixes
  - fixes #21171 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
I can confirm, that it now works.

**Comment by Vad1mo** [comment]
```sh
Checking chart 'prometheus-operator => (version: "8.10.1", path: "stable/prometheus-operator")' for a version bump...
I0304 09:26:15.134] Old chart version: 8.10.1
I0304 09:26:15.135] New chart version: 8.10.1
I0304 09:26:15.135] Error linting and installing charts: Error processing charts
I0304 09:26:15.136] ------------------------------------------------------------------------------------------------------------------------
I0304 09:26:15.136]  âœ–ï¸Ž prometheus-operator => (version: "8.10.1", path: "stable/prometheus-operator") > Chart version not ok. Needs a version bump!
I0304 09:26:15.136] ------------------------------------------------------------------------------------------------------------------------
```

**Comment by vsliouniaev** [comment]
Thanks!
/lgtm

**Pull request merged**
