### PR TITLE
Remove helm.sh/created annotations

### PR DESCRIPTION
**Pull request by unguiculus**

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
Thanks a lot for this @unguiculus. Would you be able to split these into a single PR for each chart, and also bump the version for each chart? A single PR for each chart is much easier for us to test and merge, as well as to avoid conflicts.

**Comment by unguiculus** [comment]
@AmandaCameron Would you mind sharing your PR splitter script from PR #408? Could come in handy here. Thanks.

**Comment by AmandaCameron** [comment]
It was actually mostly just a couple of one-liners, not so much a proper 'script' -- and it's highly specific to the change I made.

The basic outline was: 
- for tmp in * in .../stable/
- set i to `basename $tmp`
- copy the files from an second checkout of my initial PR.
- `git checkout -b fix-pvcs-$i`
- `git commit -m "...<containing $i for the chart"`

**Comment by AmandaCameron** [comment]
Appologies if this is a second notification, wanted to clear it with the helm folks before sharing my madness:

The "script" was actually a couple of one-liners I ran in my shell, and was highly-based on the specific action of #408

However, the general method of madness was this:
- cd to .../stable
- for tmp in *
- `#` set i to `basename $tmp`
- `#` copy the specific files for chart $i from a second checkout, containing #408
- `git checkout master`
- `git checkout -b fix-pvcs-$i`
- `git commit -m "Commit Message for chart $i"
- sleep 5

Then a second script which did the following, using the [hub tool](https://hub.github.com/) for the heavy lifting:
- cd to .../stable
- for branch in `git branch -v | grep -v (git rev-parse master | head -c 7) | awk '{ print $1}'`
- `#` set i to `echo $branch | sed -i 's/fix-pvcs-//g'`
- `#` generate a .md file for the new PR message body in /tmp/$branch.md
- `hub pull-request -F /tmp/$branch -h <my-github-un>:$branch`
- sleep 30

**Comment by viglesiasce** [comment]
Closing in favor of the other PRs that were opened.

**Pull request closed without merging**
