### PR TITLE
[stable/elasticsearch] Add options for pre-stop and post-start hooks 

### PR DESCRIPTION
**Pull request by legal90**
#### What this PR does / why we need it:

This PR is the reworked version of https://github.com/helm/charts/pull/11494

It adds the following optional values:
- `data.hooks.preStop`, `data.hooks.postStart`
- `client.hooks.preStop`, `client.hooks.postStart`
- `master.hooks.preStop`, `master.hooks.postStart`

That allows to specify custom scripts which could be executed as post-start and pre-stop hooks on master, client or data ElasticSearch nodes (pods).

_Note:_ In order for `data.hooks.preStop` and `data.hooks.postStart` to take an effect, `data.hooks.drain.enabled` should be explicitly set to `false`. That's done this way for the backward compatibility with previous versions of the chart.

It also adds optional values `master.terminationGracePeriodSeconds` and `client.terminationGracePeriodSeconds`, so users can tweak termination grace periods according to pre-stop hooks they use.

#### Which issue this PR fixes

  - closes #11494 (the parent PR)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by pavdmyt** [comment]
@simonswine @rendhalver is there any chance to proceed with this PR? The implemented functionality is very desirable.

@legal90 I believe there also should be a test cases for the new options from `values.yaml` inside `ci` directory.

**Comment by legal90** [comment]
> I believe there also should be a test cases for the new options from values.yaml inside ci directory.

@pavdmyt Is there any examples or docs showing how this CI works? I see only some values there, but the verification part.

**Comment by pavdmyt** [comment]
@legal90 you have to put the file `<name>-values.yaml` in `ci` directory. The file is a common values file which is passed via `-f` during CI process. It should contain new values which were introduced by the PR.

Take a look here https://github.com/helm/charts/tree/master/test to have an idea on how CI is organized in this repo.

**Comment by legal90** [comment]
@pavdmyt Thank you! I've added `ci/hooks-values.yaml` with new values

**Comment by legal90** [comment]
@icereval Could you please review this PR?

**Comment by legal90** [comment]
@simonswine, @rendhalver, @icereval, @desaintmartin
Could you please review this PR?

**Comment by legal90** [comment]
@simonswine, @rendhalver, @icereval, @desaintmartin Could you please review this PR?

**Comment by anas-aso** [comment]
@simonswine @rendhalver it would be nice if you can check this PR.

**Comment by legal90** [comment]
I rebased the branch again.

@simonswine, @icereval, @rendhalver, @desaintmartin, @hectorj2f
Could you please take a look at this PR and tell if it has a chance to be merged?

**Comment by legal90** [comment]
Rebased. @KongZ, @Towmeykaw Could you please review this PR?

Or just tell me if you think it shouldn't be done this way, so we just close it and I won't spend time on it anymore.

**Comment by KongZ** [comment]
@legal90 thanks for contributing. This looks good to me

**Pull request merged**
