### PR TITLE
[stable/traefik] Bump Traefik version to 1.4.0

### PR DESCRIPTION
**Pull request by kachkaev**
See https://github.com/containous/traefik/releases

### CODE REVIEW

**Comment by krancour** [comment]
This PR has unrelated changes to comments and whitespace. This is easier to LGTM if unrelated changes are avoided. Consider opening a separate PR to correct formatting issues.

**Comment by kachkaev** [comment]
I added the second commit with whitespacing because [linting in CI failed](https://circleci.com/gh/kubernetes/charts/266) after the first commit. IMO this cosmetic change is acceptable when upgrading from chart v1.11 to v1.12. Making a separate PR and then releasing v1.12.1 makes less sense to me.

**Comment by krancour** [comment]
If it was necessary to pass linting, then that sgtm.

LGTM

**Pull request merged**
