### PR TITLE
[stable/metallb] Update MetalLB to 0.8.1.

### PR DESCRIPTION
**Pull request by danderson**
#### What this PR does / why we need it:

Updates MetalLB's chart to 0.8.1. The chart here mirrors the authoritative chart maintained in the upstream repo (https://github.com/danderson/metallb), this PR is a straight `rm -rf && cp -R` of that chart, with minor tweaks like bumping the chart version in conformance with guidelines.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by danderson** [comment]
Per robot orders:

/assign @scottrigby

**Comment by mohag** [comment]
@danderson This seems to have returned documentation for the removed `arpAddresses` setting, which were previously removed in #9023 and seems to not be used by the chart. (That problem seems to be present in your upstream version as well)

**Pull request merged**
