### PR TITLE
[stable/etcd-operator] Add Clusterwide option to values

### PR DESCRIPTION
**Pull request by podothecat**
Add clusterWide option to Values, to make able to run etcd operator as cluster wide

Signed-off-by: Wonbin Cho <podothecat@gmail.com>

#### Is this a new chart
No

#### Special notes for your reviewer:
This is my very first PR. :) 

#### What this PR does / why we need it:
There is no option to make operators work clusterwide.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by podothecat** [comment]
@lachie83
@alejandroEsc 

Can you guys review this PR please?

**Comment by robhunt3r** [comment]
bump? I think this is a must have

**Pull request closed without merging**
