### PR TITLE
[stable/redis-ha] Add serviceMonitor resource object

### PR DESCRIPTION
**Pull request by pgdagenais**
Signed-off-by: Philippe Dagenais <pgdagenais@gmail.com>

#### What this PR does / why we need it:
Following this PR (https://github.com/helm/charts/pull/14910).
I'm adding the serviceMonitor resource from the https://github.com/helm/charts/tree/master/stable/prometheus-redis-exporter chart.

A user might want to deploy everything that is needed to monitor the application within the same chart rather than deploying this chart (redis-ha) and the prometheus-redis-exporter chart.

These are the values that I added to the readme: https://github.com/helm/charts/pull/18518/files#diff-90d995e49ffa78848c1414023c10569bR89-R94

I also fixed the indentation of the values list

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@pgdagenais 
Would you fix the conflicting file please?
stable/redis-ha/Chart.yaml

**Comment by pgdagenais** [comment]
@zanhsieh Done! Thanks

**Pull request merged**
