### PR TITLE
[stable/atlantis] Fix typo in README.md for orgWhitelist

### PR DESCRIPTION
**Pull request by lnattrass**
orgWhitelist in README.md has a capital L, where it should be lowercase.

#### Is this a new chart
No

#### What this PR does / why we need it:
Fixes a typo in README.md documentation

#### Which issue this PR fixes
- fixes runatlantis/atlantis#637

#### Special notes for your reviewer:
Happened to be doing a helm PR and came across this.. Why not fixup while I'm here.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by jeff-knurek — APPROVED** [review]
/approve
/lgtm

sorry, didn't get a notification before to this change

**Comment by lnattrass** [comment]
Had to update this to pass version checks (from memory...)
Is this ok for now?

/assign @jeff-knurek

**Pull request merged**
