### PR TITLE
[stable/sonarqube] Add namespace tag to metadata to honor spinnaker deployments

### PR DESCRIPTION
**Pull request by mruepp**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by paulczar** [comment]
@mruepp can you try this using the `namespaceOverride` here ?  https://github.com/spinnaker/clouddriver/pull/3678

**Comment by rjkernick** [comment]
Please merge in the latest master increment the version in chart.yaml

**Pull request closed without merging**
