### PR TITLE
[stable/traefik] backoff storeconfig job

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:
Adds a backoff limit to storeconfig job.

If the job starts to fail for whatever reason, it will keep going... it happened here and it launched over 6k containers in a couple of days.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by caarlos0** [comment]
cc/ @ldez @dtomcej can someone take a look on this?

**Comment by superbarne** [comment]
The backofflimit should be in the Job spec, or am i wrong?
I get the following error:
```ValidationError(Job.spec.template.spec): unknown field "backoffLimit" in io.k8s.api.core.v1.PodSpec;```

**Comment by caarlos0** [comment]
you're right, my bad, fixing

**Comment by caarlos0** [comment]
@superbarne https://github.com/helm/charts/pull/17181

**Pull request merged**
