### PR TITLE
[stable/spinnaker] Add a support of halyard resource definitions

### PR DESCRIPTION
**Pull request by legal90**
#### What this PR does / why we need it:

This PR allows to specify `resources` block for halyard pod in `stable/spinnaker` chart.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by legal90** [comment]
/assign @dwardu89

@dwardu89 Could you please review this PR?
I guess we need to do the same for halyard hook jobs too...

**Review by dwardu89 — APPROVED** [review]

**Comment by legal90** [comment]
It seems that `pull-charts-e2e` tests are broken by some other error, which is not related to this PR.
The same error also happened in the other PR for Spinnaker: 
- https://github.com/helm/charts/pull/12719#issuecomment-480252564

@dwardu89 Could you please assist - is there anything I can do to push this PR forward? Thanks!

**Comment by legal90** [comment]
It seems that `pull-charts-e2e` tests were failing for a while with the same error. Even for those PS which were merged:
- https://github.com/helm/charts/pull/12097 (test details:)
- https://github.com/helm/charts/pull/12355 (test details: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/12355/pull-charts-e2e/21490/)

The only difference is that the exit code of test script for these jobs was successful despite on the actual error occurred (scroll down on the test details page). So, it seems that recently the test image/script was fixed and now it doesn't pass any PR for `stable/spinnaker` :(

@viglesiasce
@lwander
@dwardu89
@paulczar
Do you guys have any idea what's should be fixed in the chart templates / values.yml to make it working out-of-box, with default values?

**Pull request merged**
