### PR TITLE
traefik: bump 1.7.7 → 1.7.9

### PR DESCRIPTION
**Pull request by costela**
#### What this PR does / why we need it:

Updates traefik from 1.7.7 to 1.7.9, which includes a few fixes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by costela** [comment]
@dtomcej @cpanato I'm a bit stumped about the test failure. Can't replicate it myself (though I'm not running the chart on GKE). Any ideas?

**Comment by costela** [comment]
hey @cpanato: were there any changes to the testing infra that should make these errors go away? I'm not sure if your "retests" mean you think the problem is definitely *not* with the newer version of traefik.
Is there anything else I can do to help debug this?

**Comment by cpanato** [comment]
@costela I thought the issue is in the Test infra. I will reserve some time to check what is going on

**Comment by cpanato** [comment]
@costela checked the pod and it is being killed due `Terminated: OOMKilled`

maybe we need to bump the memory/cpu or remove the resource as similar other charts does

**Comment by cpanato** [comment]
i see this
image
maybe push to 50

**Comment by cpanato** [comment]
@costela however the best practice is not set the resource. can you make it `{}` ?

**Comment by costela** [comment]
> however the best practice is not set the resource. can you make it `{}` ?

sure! Should I make it a separate PR?
Thanks for the tip! Just wonder why I wasn't seeing this OOM myself :thinking:

**Comment by cpanato** [comment]
@costela however the best practice is not to set the resource. can you make it `{}`?

**Comment by cpanato** [comment]
@costela update this PR in another commit

**Comment by costela** [comment]
@cpanato I implemented it in a way that tries to keep backward compatibility. It will still break if someone relied on the default resource limits to keep a system from OOMing.
The old `{cpu,memory}{Request,Limit}` values could then be completely removed in a subsequent v2 of the chart.
PTAL.

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
thanks @costela

**Pull request merged**
