### PR TITLE
change the env variable  COUCHDB_USERNAME

### PR DESCRIPTION
**Pull request by ttalal**
the env variable is COUCHDB_USER
https://hyperledger-fabric.readthedocs.io/en/release-1.4/couchdb_as_state_database.html

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ttalal** [comment]
see https://hyperledger-fabric.readthedocs.io/en/release-1.4/couchdb_as_state_database.html

**Comment by ttalal** [comment]
NA

**Comment by alexvicegrab** [comment]
@ttalal, thanks for this fix. I'm happy to approve, but make sure that you pass DCO and the linting checks (e.g. you need to bump the version).

**Review by alexvicegrab — APPROVED** [review]
LGTM, just needs to pass the status checks. See comment above

**Pull request closed without merging**
