### PR TITLE
[stable/percona-xtradb-cluster] Fixing random pod names in tests

### LINKED ISSUE #7708: [stable/percona-xtradb-cluster] Random Pod name creates different deployment on every chart installation
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm: v2.10.0
Kubernetes: 1.10.6

**Which chart**:
percona-xtradb-cluster

**What happened**:
Everytime I generate deployment from this chart I'm getting different Pod for test.
This make helm diff showing difference on every update. 
The reason is this line:
https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/templates/tests/pxc-test.yaml#L4
Pod name is generated randomly on every run.

**What you expected to happen**:
Subsequent usage of percona chart without changing values show no differences.

**How to reproduce it** (as minimally and precisely as possible):

Install chart.
Run `helm diff` without changing anything in values.

### PR DESCRIPTION
**Pull request by maver1ck**
Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

#### What this PR does / why we need it:

Fixes random pod names in tests

#### Which issue this PR fixes
  - fixes #7708 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
ping @paulczar

**Comment by maver1ck** [comment]
@paulczar Any chance to merge this fix ?

**Comment by unguiculus** [comment]
Random pod names for tests are used on purpose. Otherwise running `helm test` in a row would fail. This pattern is common for many charts.

**Comment by maver1ck** [comment]
@unguiculus 
So maybe can we add flag to disable tests ?
Then we will have both random pod name and clean diffs when you're not using tests.

**Comment by unguiculus** [comment]
Have you tried `helm test --cleanup`?

**Comment by paulczar** [comment]
Looking over it ... I think it seems fine, but I want to ensure @unguiculus is okay with it since he had some concern.  ping me again in a few days if he hasn't responded and I'll be a bit more proactive and move it along.

**Pull request merged**
