### PR TITLE
Factorio version bump + configurable port.

### PR DESCRIPTION
**Pull request by gtaylor**
This PR includes two commits:

* A mundane bump of Factorio from 0.14.21 to 0.14.22. Chart bumps to 0.1.5.
* Incorporate the configurability work @linki did in https://github.com/games-on-k8s/docker-factorio/pull/2 to  add a value for the factorio game server port (plus Service). This bumps the chart to 0.2.0.

### CODE REVIEW

**Comment by linki** [comment]
@gtaylor, I think this isn't going to work. `FACTORIO_PORT` tells factorio to listen on that port inside the container. But the `targetPort` of your service is `factorio` which is still hard-coded to `34197` in the Deployment spec.

https://github.com/gtaylor/charts/blob/0be377d5f5dfe5e9e8c5edfded50b30807e43141/stable/factorio/templates/deployment.yaml#L75

My goal with the configurable port was to make the chart work better with factorio's server registry. Having a separate load balancer IP doesn't work as factorio registers itself with its node IP address. Similar behaviour for the port: whatever port factorio is told to listen on gets registered with the registry, so it must also listen on that port on the external address. Feel free to correct me if I'm wrong.

**Comment by linki** [comment]
Changing `containerPort` in the deployment spec to `{{ .Values.factorioServer.port }}` should work.

**Comment by linki** [comment]
Seems like I'm very wrong. Using arbitrary NodePorts works just fine with the server browser. I don't even have to open any ports in the firewall. Does this relate to their NAT punching? (https://www.factorio.com/blog/post/fff-143)

Anyways, I would leave out the configurable port commit for now. Your version `0.1.5` works fine.

**Comment by gtaylor** [comment]
Configurable port could be useful for those (such as myself) who don't publish their server in the directory but want an alternate port.

**Comment by lachie83** [comment]
@gtaylor @linki What's the consensus here? Can we proceed with the merge?

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
CI failing with the following `W0213 19:57:24.138] Error: release factori-965 failed: error validating "": error validating data: expected type int, for field spec.ports[0].port, got string`

**Comment by linki** [comment]
@lachie83 @gtaylor https://github.com/gtaylor/charts/pull/4 should fix the CI build.

**Comment by linki** [comment]
@gtaylor can you have peek at https://github.com/gtaylor/charts/pull/4 so we can merge this?

It just fixes an issue with the port being a string where it should be an int :confused:

**Comment by linki** [comment]
I can take care of it once I've got access to push here.

**Comment by linki** [comment]
@gtaylor I fixed the issue with the port being a string and now the e2e tests pass.

**Comment by gtaylor** [comment]
Sorry for the delay. LGTM!

**Pull request merged**
