### PR TITLE
Added info on values.yaml, it is possible to use URL for FTB. 

### PR DESCRIPTION
**Pull request by dleurs**
#### What this PR does / why we need it:
This pull request adds one line of additional information into stable/minecraft stable.yaml, (only one \#\# comment line) that will hopefully save developper's time

#### Which issue this PR fixes
Only modifying one line of comments

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by itzg** [comment]
@dleurs thank you for the contribution so far, but please review the PR description, especially the checklist. The bots will prevent further processing of the PR without that.

**Comment by dleurs** [comment]
Thank you for your response,
I hope I completed PR well enought

**Comment by dleurs** [comment]
@itzg Sorry, but what does it mean to bump the chart version ? Increment it ?

**Comment by itzg** [comment]
Correct, I think it's looking for the 3rd position in the version to be incremented for tiny changes like this.

**Pull request closed without merging**
