### PR TITLE
[stable/minio] adding jobPodLabels and jobPodAnnotations

### PR DESCRIPTION
**Pull request by kkunkel**
This allows for additional labels and annotations to be added to the Job that creates MinIO buckets.

This is useful to disable Istio injection when deploying MinIO to a namespace with automatic Istio injection enabled. The Istio proxy continues to run after the Job has completed, causing the `helm install` to fail.

Signed-off-by: Kevin Kunkel <kunkel.kevin@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by nitisht — CHANGES_REQUESTED** [review]
@kkunkel could you specify the new fields `jobPodAnnotations` / `jobPodLabels` in `values.yaml` as well?

**Comment by kkunkel** [comment]
@nitisht , thank you for your consideration and review. I've added your suggestions. Thank you again.

**Comment by nitisht** [comment]
Thanks for the PR @kkunkel

**Comment by kkunkel** [comment]
Is there anything else needed before a `/lgtm`?

**Comment by kkunkel** [comment]
I bumped the version because the pipeline was failing, but I don't believe it's related to the version or my code changes. Does this pipeline need to be updated?

**Comment by nitisht** [comment]
@kkunkel could you pls resolve the conflicts..

**Pull request closed without merging**
