### PR TITLE
[incubator/vault] Add service.externalTrafficPolicy value

### PR DESCRIPTION
**Pull request by kvolkovich-sc**
Its needed for a proper IP address in Vault Audit Log's `remote_address` field.

Details: https://github.com/sethvargo/vault-on-gke/issues/29

### Example (Kibana screenshots):

`service.externalTrafficPolicy: Cluster` - cluster Node's IP address

Screen Shot 2019-05-17 at 3 55 11 PM

`service.externalTrafficPolicy: Local` - real user's IP address

Screen Shot 2019-05-17 at 3 54 42 PM

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by kvolkovich-sc** [comment]
@prydonius, @lachie83, can you take a look at this PR?

**Comment by jbialy** [comment]
Please bump the chart version!

**Comment by jbialy** [comment]
@kvolkovich-sc can you take a look at the outstanding checks?

**Comment by jbialy** [comment]
Hi, can you please resolve the conflict so that we can get his merged?

**Comment by jbialy** [comment]
@kvolkovich-sc, are you still interested in getting this PR merged?

**Pull request closed without merging**
