### PR TITLE
drupal bump dependency mariadb 0.6.2

### PR DESCRIPTION
**Pull request by scottrigby**

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@scottrigby looks like you've included some extra resources in this one

**Comment by scottrigby** [comment]
@prydonius Hey yes you're right! I'll fix that right in a moment…

One flaw I just realized in my bump script is [this line](https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092#file-k8s_charts_bump_dependency_version-sh-L123), which does a `git add` on the entire chart path after the version bump. Instead, I should change that to explicitly only `git add $CHART_PATH/requirements.yaml $CHART_PATH/requirements.lock`.

**Comment by scottrigby** [comment]
@prydonius OK, PR fixed. For anyone interested, I also fixed the bump script: [diff](https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092/revisions#diff-ef79a9cf59bf5b9c2e0cd7f3f7418d88L123).

**Pull request merged**
