### PR TITLE
[stable/jenkins] Add Values.master.prometheus.serviceMonitorName

### LINKED ISSUE #23494: [stable/jenkins] Prometheus Servicemonitor issue with several Helm releases
When trying to install 2 helm releases with same name (e.g. jenkins) in different namespaces (e.g. jenkins-dev & jenkins-prod) with values:
  prometheus.enabled: true

Helm fails with message:
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceMonitor "jenkins" in namespace "monitoring" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "jenkins-prod": current value is "jenkins-dev"

Seems that chart should have value like prometheus.serviceMonitorName

### PR DESCRIPTION
**Pull request by truealex81**
Signed-off-by: Aleksandr Malkov <truealex@mail.ru>

#### What this PR does / why we need it:
Add Values.master.prometheus.serviceMonitorName

#### Which issue this PR fixes
  - fixes #23494

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mattfarina** [comment]
@truealex81 Thanks for the contribution. There are a couple things that need to be cleaned up here.

First, Helm uses a DCO to show you have permission to make the contribution. This requires git signoff (which is different from crypto signing). See the _checks_ tab at the top for how to correct for this.

Second, any time a chart is changed the version needs to be incremented. This is the `version` field in the `Chart.yaml` file. Can you please increment this.

**Comment by torstenwalter** [comment]
In addition it would be great if you could add an entry to CHANGELOG

**Comment by torstenwalter** [comment]
/hold This chart will be moved to https://github.com/jenkinsci/helm-charts see for details #23562
Would be great if you could create the PR in the new location.

**Pull request closed without merging**
