### PR TITLE
[stable/concourse] Replaces worker StatefulSet by Deployment

### LINKED ISSUE #8765: [stable/concourse] Pods/workers bounce between running and retiring
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm: 2.11.0
Kubernetes: 1.10.7

**Which chart**:

stable/concourse, 2.0.1

**What happened**:

I have dedicated nodes for each worker pod. When I drain/roll the nodes, the worker goes into retiring mode then disappears. When the rolled node is restarted and the pod is rescheduled, the worker is reregistered and is in "running" state. After a couple of minutes, the worker will go into "retiring" state, and a minute or two later the pod will go into CrashLoopBackoff. The worker and pod will bounce back and forth between running and retiring/crashing just long enough for work to get scheduled on the worker, and then the worker is marked as "retiring" and the pod crashes.

To resolve this, I have to scale my statefulset to 0, wait for all pods to terminate, prune all workers, then scale back to my desired number of workers.

**What you expected to happen**:

Running pods/workers don't get into a loop of running and crashing.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else we need to know**:

This is running on AWS, btrfs, and `persistence.enabled: false`.

### PR DESCRIPTION
**Pull request by cirocosta**
#### What this PR does / why we need it:

Previously, StatefulSets were used in order to work around some
issues that users had with having pods registering & deregistering
from ATC ( see https://github.com/concourse/concourse/issues/1457).

From what I understand, we were not even making use of the idea of 
bringing state together across restarts / new pods being created:

https://github.com/helm/charts/blob/43a94e6fa9c06274a432d34681f26d3f39b59fc3/stable/concourse/templates/worker-statefulset.yaml#L46

After the introduction of `--ephemeral`, the logic of automatically pruning a worker
that has gone away is *suepr* simplified: after `retire`, it'll be automatically pruned.

That said, I guess we can go back to the best way of deploying concourse: assuming
that the workers are ephemeral in all ways (including state).

As a result of the changes, `--ephemeral` comes set to `true` by default.

#### Which issue this PR fixes

 - fixes #8765 

#### Special notes for your reviewer:

~~I think in a close future we can have `StatefulSet`s back in order to have persistence but I'd say that for now (especially with 4.2.1 that doesn't include [some GC improvements](https://github.com/concourse/concourse/issues/2588)) we are much better off going with a simple `Deployment` that is totally stateless.~~ 

~~Another argument for having the StatefulSet would be to increase the size of the disk where the worker state lives if needed. Maybe there's a way around this?~~ Maybe we should not completely ditch the StatefulSet and try hard to go straight to the scenario where we have either SS or Deployments? 

Update: Actually, now I think it's actually pretty important to have the support for StatefulSet so we can support scenarios where disk IO is the highest priority

Wdyt?

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by william-tran** [comment]
Yes this is so awesome and moves towards an ideal view of operating concourse on k8s; if a worker dies, a new one can come up without any expectation of state left behind by the previous incarnation. I would only be comfortable with removing the option of statefulset+pvc if we ensured that space on the node is reclaimed when the worker restarts. We need to test that out on recent versions of k8s using each baggage claim driver. Early on (late 2017) I noticed that space was never being reclaimed and I eventually ran out of disk on the node, causing trouble for any other pods running on the node and not reclaimable until restarted the host vm. Having a PVC made it possible to deal with that reality by tossing the disk when it became full.

**Comment by paulczar** [comment]
let's rebase this and get it ready to merge!

**Comment by cirocosta** [comment]
That's a pretty valid concern @william-tran , especially when it comes to the btrfs baggageclaim driver.

I'll rebase the PR for now but still consider it on hold until we have in our test suite a test that verifies such behavior and ensures that for either `btrfs`, `overlay` or `naive` we have that cleaned up (prioritizing this today) - I just went through them and there's not one that specifically verifies that in an end-to-end manner.

Please let me know if there are any further scenarios you think would be interesting to cover before we move forward!   

thx!

**Comment by au-hao** [comment]
We are facing the issue (https://github.com/concourse/concourse/issues/1780) in the latest version of concourse. Would it be possible after introducing this feature, the issue could be solved? If so, could @cirocosta you help on testing it as well?

**Comment by cirocosta** [comment]
Hey,

We created an issue under `concourse/concourse` to keep track of a possible "leak" that happens when you use `btrfs` on a containerized environment: https://github.com/concourse/concourse/issues/3091

Another *possible* issue that I can see it when making use of local disks instead of persistent dir (with btrfs) - without the clean up that `emptyDir` would have (managed by the kubelet), the local disk would soon be filled with btrfs images there are there's no place in the code where a clean up would happen on termination right now.

The idea is to include https://github.com/concourse/baggageclaim/blob/1bd5c2e7660df90ebef1c27ea8b7bdcb4840f85a/fs/btrfs.go#L67-L101 in the lifecycle (at termination) so that when [`retire`ing](https://concourse-ci.org/worker-internals.html#RETIRING-table), the worker could have its things cleaned up.

The only sad part of it is that these changes would arrive only in the 5.x series (which is close to being released but not there yet).

thx!

**Pull request closed without merging**
