### PR TITLE
[stable/metabase] Release 0.3.1

### PR DESCRIPTION
**Pull request by ghost**
This change set releases a new version of the `stable/metabase` chart which includes:

- A new `database.connectionURI` configuration parameter.
- An upgrade to Metabase `v0.27.2`
- Storing the `database.encryptionKey` as a Kubernetes secret.

### CODE REVIEW

**Comment by ghost** [comment]
Please check CLA again.

**Comment by ghost** [comment]
I signed a corporate CLA. How do we proceed? The bot isn't picking this up.

**Comment by timstoop** [comment]
Did you sign in here as well? https://identity.linuxfoundation.org/projects/cncf

Otherwise send a mail to helpdesk@rt.linuxfoundation.org

**Comment by ghost** [comment]
Yes, signed there. I'll send an email there then.

**Comment by ghost** [comment]
Oh, seems like it's fixed now! No e-mail needed.

**Comment by ghost** [comment]
Oops, I realise the Chart version should remain 0.3.0 even with the Docker image tag changing up. Let me know when I can rebase.

**Comment by viglesiasce** [comment]
@optiomas CI is failing as follows:

```shell
I0104 05:46:23.252] metabas-4451-metabase-3512273097-mz98m   0/1       secrets "metabas-4451-metabase-database" not found   0         9m
```

This is because the defaults use the h2 DB type which does not create that secret. Can you make these env vars conditional based on the DB type as done with the secret?

**Comment by ghost** [comment]
@viglesiasce: Addressed the issues and updated to the latests Metabase version. PTAL again. I'd like to clean the branch history before merge so let me know if I can proceed.

**Comment by viglesiasce** [comment]
No worries on cleaning the branch @optiomas, we do a squash and merge.

Testing this manually now.

**Comment by viglesiasce** [comment]
Thanks @optiomas!!

/lgtm

**Pull request merged**
