### PR TITLE
[stable/jenkins] Support custom labels in deployment (#9714)

### LINKED ISSUE #9714: Support custom labels for deployments in Jenkins chart
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Which chart**:
jenkins

Can the chart support custom labels for deployments, like it already does for pods and services?

### PR DESCRIPTION
**Pull request by erihanse**
Signed-off-by: Erik Aaron Hansen <erihanse@outlook.com>

#### Which issue this PR fixes
  - fixes #9714 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rimusz** [comment]
@erihanse you put custom labels under pods, it should be under deployment part

**Comment by maorfr** [comment]
/lgtm
Thanks for contributing!

**Pull request merged**
