### PR TITLE
Fix data.persistence.storageClass in example in incubator/elasticsearch/README.md

### PR DESCRIPTION
**Pull request by patsevanton**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rendhalver** [comment]
You also need to edit the file in stable/elasticsearch because incubator/elasticsearch has been deprecated.
Please sign off on your commits and increment the chart version.
Have  look at the contributing guidelines for details on how to sign off on your commits
https://github.com/helm/charts/blob/master/CONTRIBUTING.md

**Comment by cpanato** [comment]
@patsevanton please bump the patch version of the chart and sign the DCO

**Pull request merged**
