### PR TITLE
[stable/prometheus-operator] Add option to set log formatting

### PR DESCRIPTION
**Pull request by mrueg**
Signed-off-by: Manuel Rüger <manuel@rueg.eu>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by mrueg** [comment]
@gianrubio can you lgtm it? Looks like I lost the race for chart version again

**Comment by paskal** [comment]
@mrueg now all other PRs are merged, could you please rebase your change on upstream once more?

**Comment by mrueg** [comment]
@paskal done

**Comment by paskal** [comment]
@davidkarlsen @cpanato could you please re-approve this one?

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
