### PR TITLE
Add OWNERS file to stable/openebs

### PR DESCRIPTION
**Pull request by kmova**
Signed-off-by: kmova <kiran.mova@openebs.io>

#### What this PR does / why we need it:

This PR adds OWNERS file to include OpenEBS Project Maintainers. Includes a single name for now, will expand with additional contributors in the future. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@kmova I've added you as a trusted collaborator - you should be able to test and merge now.

**Comment by kmova** [comment]
Thank you @davidkarlsen

**Pull request merged**
