### PR TITLE
[stable/redis] re-sync values-production.yaml with values.yaml

### PR DESCRIPTION
**Pull request by thomas-riccardi**
Signed-off-by: Thomas Riccardi <thomas@deepomatic.com>

#### What this PR does / why we need it:
#4662 added a second values file: `values-production.yaml`.
Since then, `values.yaml` has diverged without re-syncing `values-production.yaml`.
This PR re-syncs this file.

#### Special notes for your reviewer:
I did *not* bump the chart version as it doesn't change anything when this chart is used from the repository: `values-production.yaml` has to be manually used.
Should I still bump the chart version?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Thanks for this PR! Could you please bump the patch version in the **Chart.yaml**? It's mandatory for every single change.

**Comment by thomas-riccardi** [comment]
@juan131 chart patch version bumped , to be merged *before* #8931

**Review by juan131 — APPROVED** [review]
Thanks @thomas-riccardi

**Pull request merged**
