### PR TITLE
[rabbitmq] add http protocol to stats service name (matters with istio)

### PR DESCRIPTION
**Pull request by sebdoido**
Add `http` protocol in stats service name

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by carrodher** [comment]
I think in this case we can't ensure the backward compatibility because of the port renaming so it should be a major change. What do you think @juan131 @sameersbn? In the same way, do you prefer to include in the same PR other major changes or accept this one including only the port renaming?

Finally, there are other ports that should be renamed following the same approach, @sebdoido can you add those ones?

**Comment by sebdoido** [comment]
Hi
only this port renaming for this PR but i think, yes, we can bump a major version?
Let me know and i will amend my commit

**Comment by carrodher** [comment]
As port renaming is a major change it's better to rename all the ports in the same PR to avoid bumping the major version several times

**Comment by javsalgar** [comment]
From https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

```
grpc
grpc-web
http
http2
https
mongo
mysql*
redis*
tcp
tls
udp
```

I presume that you could add `tcp` to the other ports and `http` to the metrics one

**Comment by sebdoido** [comment]
Hi there
yes, you're right but it falls back on tcp by default
```
If the protocol cannot automatically be determined, traffic will be treated as plain TCP traffic.
```

Most of the time, people don't specify `tcp` because it's the default value handled by istio.

**Comment by sebdoido** [comment]
Hi there
welll, regarding the previous discussion and automatic protocol selection through istio
 https://istio.io/docs/ops/configuration/traffic-management/protocol-selection

We had a performance issue.
With istio 1.3.?, time duration to connect to a rabbitmq cluster for a cluster increased from 25ms to 130ms (average) without specifying the protocol.

If we explicitly set `tcp-xxx` or `http-xx` it's ok... and we go back to a normal duration.
We upgraded our cluster to Istio 1.4.3 and it's back to normal (~25ms) without specificy protocol in service name but i think it could be great to have it as a default value for people who would not be aware of this side effect.. (or are not up-to-date with latest (1.4.x) istio version.

Let me know if you think this PR can be merged?

**Comment by davidkarlsen** [comment]
This chart has been deprecated and moved: https://github.com/helm/charts/pull/21310

**Pull request closed without merging**
