### PR TITLE
[stable/spark] add daixiang0 to maintainer

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@zanhsieh hi, mind have a look.

**Comment by daixiang0** [comment]
@zanhsieh test pass.

**Comment by zanhsieh** [comment]
@daixiang0 
You need to get helm members approval, e.g. @scottrigby @cpanato and accept their invitation. I am not a helm member so what I can do is limited.

**Comment by daixiang0** [comment]
@scottrigby @cpanato  mind have a look?

**Comment by daixiang0** [comment]
@lachie83 ping

**Comment by daixiang0** [comment]
@cpanato @scottrigby @lachie83 mind have a look? Now no collaborator can maintainer this chart.

**Comment by scottrigby** [comment]
Per https://github.com/helm/charts/commits?author=daixiang0 sgtm 👍 

@daixiang0 I have added you as a read-only collaborator per https://github.com/helm/charts#owning-and-maintaining-a-chart. You must accept the invite: https://github.com/helm/charts/invitations

**Review by scottrigby — APPROVED** [review]
/lgtm

**Comment by abdennour** [comment]
please add me as maintainer for jenkins and oauth2-proxy charts

**Pull request merged**
