### PR TITLE
[stable/stolon] add prometheus service monitor

### LINKED ISSUE #16980: [stable/stolon] maxConnections example provided in values.yaml is not working
**Describe the bug**
values.yaml uses maxConnections as example for setting a postgres parameter.
Running with this value has the effect that the stolon cluster does not come up.
This is caused by the post Install helm hook error-ing on this key.

**Version of Helm and Kubernetes**:

**Which chart**:

stable/stolon version 1.1.2

**What happened**:

Installing chart for the first time with this in the config (as suggested by the example in values.yam)

`
pgParameters: 
    maxConnections: 1000
`
Cluster did not come up. No error logs. container running the post install helm hook never started.

Changing to 
`
pgParameters: 
    maxConnections: "1000"
`
post install container started. But still error as maxConnections was not recognized as valid postgres argument.

Changing to 
`
pgParameters: 
    max_connections: "1000"
`
Success. Cluster starting and postgresql.conf contains 1000 as max connections.

**What you expected to happen**:

Cluster comes up. max_connections in postgresql is set to 1000

Official postgres helm chart uses snakecase https://github.com/helm/charts/blob/master/stable/postgresql/templates/extended-config-configmap.yaml#L18

With snakecase the maxConnections would work.
So I suggest to either add smae snakecase fix to stolon helm chart or just update the example in the values file.

Maybe also add a comment that always "" is needed as the default of 1000 did not work either. Had to be "1000"

**How to reproduce it** (as minimally and precisely as possible):

See above.

**Anything else we need to know**:

### LINKED ISSUE #18208: [stable/stolon] ability to add prometheus service monitor object
We prefer to scrape metrics using Prometheus service monitor objects.
Currently these cannot be created via the stolon helm chart.

Would be nice if a service monitor object could be created that would get the metrics from all the stolon pods. This should be optional.

I needed I can add a pr that creates servicemonitor objects (and the corresponding service objects) in the same way as done with other helm charts.

### PR DESCRIPTION
**Pull request by aligthart**
@lwolf 
@rtluckie 

#### What this PR does / why we need it:

Add Prometheus service monitor to stable/stolon for scraping via service monitor object

#### Which issue this PR fixes
  - fixes #18208
  - fixes #16980

#### Special notes for your reviewer:

Service monitor is added in a similar way as done in other helm charts.
Also a new metrics-service is created as the sentinel did not had a service before.
All endpoints are accessible via this metric service which is always a clusterIP and thus only exposed in the cluster. Adding metrics port to existing services and creating a specific service for sentinel seemed more complex and might also add nodeports etc in case of something else than clusterIp. 

Also fixes max_connection example. 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by aligthart** [comment]
@lwolf, @rtluckie, @unguiculus, @zanhsieh any indication if/when this could be merged/reviewed?

**Comment by zanhsieh** [comment]
@aligthart 
Pinged in kubernetes slack channel #charts.

**Comment by lwolf** [comment]
in general lgtm. Could you also replace hardcoded 8080 in the deployments, otherwise overwriting the port will not work as expected.
```
grep -R "8080" stable/stolon
stable/stolon/templates/sentinel-deployment.yaml:              value: "0.0.0.0:8080"
stable/stolon/templates/keeper-statefulset.yaml:              value: "0.0.0.0:8080"
stable/stolon/templates/proxy-deployment.yaml:              value: "0.0.0.0:8080"
```

**Comment by aligthart** [comment]
Thanks @lwolf. Hardcoded 8080s removed. Tested with default values and different value for metrics port.

**Comment by aligthart** [comment]
@unguiculus, @zanhsieh A review was done by @lwolf Can this be merged now?

**Comment by zanhsieh** [comment]
@aligthart 
Pinged them in kubernetes channel #charts.

**Review by joschi36 — APPROVED** [review]

**Comment by aligthart** [comment]
thanks @joschi36 for the approval. 

@unguiculus , @zanhsieh, @lachie83, @mattfarina could you please finalize this pr. A previous pr took a few days. This one almost a month.....

**Comment by aligthart** [comment]
@unguiculus , @zanhsieh, @lachie83, @mattfarina could you please finalize this pr?
Tx

**Comment by aligthart** [comment]
Hi @maorfr

Getting this pr approved is taking a very long time. You helped with merging a previous mr on this chart (see https://github.com/helm/charts/pull/17963). 

In an attempt to get this second pr reviewed as well I assigned this to you. In case this is not the correct way, I appologize. And let me now.

Thanks,

**Comment by aligthart** [comment]
@lwolf @maorfr thanks guys!!

**Pull request merged**
