### PR TITLE
[kuberhealthy] added nodes to cluster role

### LINKED ISSUE #103: nevalau on Reddit has RBAC issue
image

`2019-02-12T09:00:06.663145281Z time="2019-02-12T09:00:06Z" level=warning msg="DaemonSetCheckerError determining which node was unschedulable. Retrying.nodes is forbidden: User \"system:serviceaccount:kuberhealthy:kuberhealthy\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"`

**Steps To Reproduce**
Install the helm chart

**Expected behavior**
The helm chart installs and everything works

### PR DESCRIPTION
**Pull request by omerlh**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes Comcast/kuberhealthy#103

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by omerlh** [comment]
The build failure seem unrelated: 
> Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.

**Comment by integrii** [comment]
@davidkarlsen and @omerlh - Thanks to both of you!

**Comment by omerlh** [comment]
Can you please bump the version also?

**Comment by integrii** [comment]
Bump what version?  The helm chart?

**Comment by omerlh** [comment]
Yes, the version with my changes is still 1.0.1. I pushed another [commit](https://github.com/helm/charts/pull/11473/commits/de5db0bde16ef5594c9f618d79b58b8d0f43d7df) that bumps the version, I think it wasn't merged.

**Comment by integrii** [comment]
I can't actually edit this chart directly - I am only authorized to approve PRs for it.  If you open another PR with the version bump and link me, I can approve it.

**Comment by integrii** [comment]
Actually, the chart right now is at version version: 1.1.0.  I think you are good.

**Pull request merged**
