### PR TITLE
[stable/jenkins] Improve documentation - clarify that rbac is needed for autoreload

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

@ricardompcarvalho had problems to configure autoreload. I tried to provide him with a minimal example and figured out that the documentation could be improved.

- listed additional properties in the README
- added a minimal example where configAutoReload is enabled
- pointed out that rbac needs to be enabled when using configAutoReload

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by holmesb** [comment]
@torstenwalter RBAC is not needed for autoreload.  I've just created a new cluster without RBAC.  Autoreload works fine.

**Comment by holmesb** [comment]
Rather than adding complexity for the user, I think we should automatically enable RBAC when auto-reload is enabled.

**Comment by torstenwalter** [comment]
@holmesb Do you suggest changing `{{ if .Values.rbac.install }}` to `{{ if or (.Values.rbac.install) (.Values.Master.JCasC.enabled) }}` in `rbac.yaml`?

That's should work, but it feels odd to grant Jenkins `cluster-admin` permissions when `rbac.enabled` is set to false. Enabling it manually forces the user to think about permissions and possibly using a less permissive role.

**Comment by torstenwalter** [comment]
```
Master:
  HealthProbesReadinessTimeout: 10
  JCasC:
    enabled: true
  Sidecars:
    configAutoReload:
      enabled: true
rbac:
  install: true
  roleBindingKind: RoleBinding
  roleRef: view
```

For configAutoReload binding the `view` role is sufficient, but if you want to start agents it should be changed to `edit`.

**Comment by holmesb** [comment]
> "odd to grant Jenkins `cluster-admin` permissions when rbac.install = false". 

Agreed, it's odd to grant Jenkins cluster-admin at all.  Only needed when agents are in different namespace from master, which I expect isn't typical.  But currently, this chart can only use a pre-existing role (default: cluster-admin) because rbac.yaml doesn't create one.   

Defaults should be roleRef: namespace-admin, roleKind: Role and roleBindingKind: RoleBinding.  Then can add a role to rbac.yaml using something like: 
```
{{ if or (.Values.rbac.install) (.Values.Master.Sidecars.configAutoReload.enabled) }}`
<same role-binding resource as now>
---
kind: {{ .Values.rbac.roleKind }} 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.roleRef }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
    verbs: ["*"]
```

Then values.yaml would be:

```
rbac:
  install: true
  serviceAccountName: default
  # Role reference - the name of the role that will be created
  roleRef: namespace-admin
  # Role kind (Role or ClusterRole) 
  # Note: if your agents are in a separate namespace from master, this should be ClusterRole
  roleKind: Role
  # Role binding kind (RoleBinding or ClusterRoleBinding)
  # Note: if your agents are in a separate namespace from master, this should be ClusterRoleBinding
  roleBindingKind: RoleBinding
```

With this switch to from cluster-admin to namespace-admin (by default), as long as we document what is happening, I think it's reasonable to enable rbac when auto-reload is enabled, even when `rbac.install = false`.

A couple of your other points:

> Do you suggest changing `{{ if .Values.rbac.install }}` to `{{ if or (.Values.rbac.install) (.Values.Master.JCasC.enabled) }}` in `rbac.yaml`?

It's only needed for auto-reload, so should be: `{{ if or (.Values.rbac.install) (.Values.Master.Sidecars.configAutoReload.enabled) }}` as I've put above.

> For configAutoReload binding the `view` role is sufficient,

Role must also have "watch" verb according to my testing.  I went with ["*"] above because I haven't tested all the agent scenarios and I expect [most](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#review-your-request-attributes) will be needed to spin-up & spin-down agents.   I'm sure the resources and verbs can be tightened further, but reducing from cluster-admin to namespace-admin is good enough for the time-being.

The scope of this issue has crept.  Are you happy to do this?  Otherwise I'm happy to create a new one and push myself.

**Comment by maorfr** [comment]
/ok-to-test
@holmesb, what you are describing is a whole separate PR on its own, no doubt we should reduce jenkins rbac from cluster-admin.

@torstenwalter, this seems like a great addition to the docs. Are there any pending additions for this PR?

**Comment by torstenwalter** [comment]
No the PR is complete. Giving RBAC some thoughts, but it's probably cleaner
to separate that into it's own topic.

**Comment by maorfr** [comment]
/lgtm

thanks for your contribution! :)

**Comment by maorfr** [comment]
This will probably require a version bump.

**Comment by torstenwalter** [comment]
@maorfr Version is bumped and master merged so that conflicts are resolved.

**Pull request merged**
