### PR TITLE
[incubator/vault] Start consul agent container before vault

### PR DESCRIPTION
**Pull request by monester**
#### What this PR does / why we need it:

If vault container has lifecycle postStart script which is waiting for vault to startup
and vault is configured to use Consul Agent then this postStart would never finish successfully.

Specifying consulAgent container before vault will fix this deadlock.

#### Which issue this PR fixes

No issue

#### Special notes for your reviewer:

it is simple block rearrangement. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by monester** [comment]
@jbialy @lachie83 please review

**Comment by jbialy** [comment]
I think that in order to solve the problem which you describe it might be necessary to use an init container that waits for consul to come up before continuing to launch the vault container. Otherwise there is no order to how the containers are started as far as I understand.

**Comment by monester** [comment]
> I think that in order to solve the problem which you describe it might be necessary to use an init container that waits for consul to come up before continuing to launch the vault container. Otherwise there is no order to how the containers are started as far as I understand.

Thanks for checking it. Yes there is no guarantee in which order containers will start, however maybe there is a bug/feature when there is `postStart` defined, containers are started one by one in order in which they are defined in `containers` section. That's why I moved agent before vault, as it is required to start-up vault. With no postStart containers are started in any order and it is not a problem.

script I'm running in postStat section is following:
```yaml
lifecycle:
  postStart:
    exec:
      command:
      - /bin/sh
      - -c
      - |
        while ! nc -z localhost 8200; do sleep 1; done;
        for key in /vault/unseal-keys/key*; do
          vault operator unseal -address=http://127.0.0.1:8200 `cat ${key}`
        done
```

I used a small test pod spec to verify this case:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: nginx
    image: nginx
  - name: ubuntu
    image: ubuntu:18.04
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt update; apt install -y netcat; while ! nc -z localhost 80; do sleep 1; done"]
    command: ['sh', '-c', 'sleep 6600']
```

Changing order or nginx/ubuntu containers would lead to deadlock.

**Comment by jbialy** [comment]
This is an interesting find!

/approve
/lgtm

**Pull request merged**
