### PR TITLE
[stable/openldap] Please add me as a mantainer

### PR DESCRIPTION
**Pull request by pennycoders**
According to #13869, this chart needs some mantainers

Signed-off-by: Alexandru Bogdan Pica <dtk077@gmail.com>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@pennycoders 
Please bump chart version to latest. Thank you.

**Comment by pennycoders** [comment]
Hi @zanhsieh 

Just bumped the chart version to 1.2.2.

Cheers,

Alex.

**Comment by zanhsieh** [comment]
@maorfr @lachie83 
Would you grant him as one of the OWNERS of this chart please?

**Comment by maorfr** [comment]
I'll leave this to @scottrigby

**Comment by scottrigby** [comment]
@pennycoders do you have any open PRs? I don't see any commits for you https://github.com/helm/charts/commits?author=pennycoders. We like to see at least some contribution history before adding people as chart OWNERS.

**Comment by pennycoders** [comment]
> @pennycoders do you have any open PRs? I don't see any commits for you https://github.com/helm/charts/commits?author=pennycoders. We like to see at least some contribution history before adding people as chart OWNERS.

Hi @scottrigby ,

I only have a PR. It did not get merged before another which fixed the same issue though.

You can check it out at the following URL:

https://github.com/helm/charts/pull/17512

Thanks,

Alex.

**Pull request closed without merging**
