### PR TITLE
[stable/hadoop] Optionally deploy Apache Knox for external access to HDFS via webhdfs

### PR DESCRIPTION
**Pull request by pfisterer**
This is an updated version of PR #5516 which includes authentication by default. 

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by paulczar** [comment]
I think it might make more sense to create a seperate chart for apache knox and add it as a requirements.yaml entry in this chart.

**Comment by pfisterer** [comment]
@paulczar: Thank you very much for your feedback. 

I agree that your approach would also makes a lot of sense. But accessing Hadoop services (e.g., HDFS) from outside Kubernetes requires using a service like Apache Knox. In my opinion, providing it as an option is also a viable alternative since the two are part of the same ecosystem.

However, if you prefer your approach, I can also try to migrate it to a new subproject here. But I would need some help in doing that.

**Comment by paulczar** [comment]
Given how many integrations apache knox has to ecosystem projects, I feel like it should get its own standalone chart and this (and other) charts can use it as a dependency in `requirements.yaml`.

**Comment by paulczar** [comment]
Haven't heard back on this for a while.  I'm going to close it.  If you want to discuss further feel free to re-open it and ping me on kubernetes slack.

**Pull request closed without merging**
