### PR TITLE
[stable/openvpn]: Adds Release.Namespace

### PR DESCRIPTION
**Pull request by jasongwartz**
#### What this PR does / why we need it:

Adds namespace configuration to the openvpn chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Why is this needed? Helm handles this automagically when you deploy into a `--namespace <some namespace>`

**Comment by jasongwartz** [comment]
I thought that was the case, and I found it to be true in my testing as well - but I noticed many other charts have this, so I was wondering if there was an edge case where this is useful that I wasn’t considering.

Eg: 
https://github.com/helm/charts/blob/10ddb0c607525b323d0b0ceb301ca82bbd31b6f9/stable/cert-manager/templates/deployment.yaml#L5
https://github.com/helm/charts/blob/83905b96bbc9648443f2ef7f168545a65a1eef49/stable/jaeger-operator/templates/role-binding.yaml#L6
https://github.com/helm/charts/blob/f8419597d52002644028f8f4246edea8639cc18d/stable/kured/templates/daemonset.yaml#L5
https://github.com/helm/charts/blob/2978da57109b37351f9d032fb0a73a976e56cf20/stable/cert-manager/webhook/templates/pki.yaml#L8

Are these examples redundant, or does the helm magic apply differently to different object types (eg. deployment vs rolebinding vs CRD)

**Comment by eh-am** [comment]
this is useful when deploying using Spinnaker

https://github.com/spinnaker/spinnaker/issues/2909#issuecomment-397577348

also related:
https://github.com/helm/helm/issues/3553

**Pull request closed without merging**
