### PR TITLE
[stable/fluent-bit] Add missing TLS settings to forward template block

### PR DESCRIPTION
**Pull request by rafaelmagu**
#### What this PR does / why we need it:

The chart documentation mentions TLS settings can be used for configuring forwarding in Fluent Bit but the ConfigMap template does not include them.

Tag @kfox1111 @edsiper

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by edsiper** [comment]
@rafaelmagu note that recent version only needs self_hostname when a shared_key exists, now shared_key is not TLS dependent (shared_key is used in Forward handshake protocol).

**Comment by rafaelmagu** [comment]
@edsiper I'll move the `Self_Hostname` block out of the TLS conditional and re-submit.

**Comment by rafaelmagu** [comment]
@edsiper pinging for a new review.

**Comment by kfox1111** [comment]
I'd very much like to get off the treadmill of having to add a value every time fluent-bit adds a new config option. Is there a better way?

**Comment by rafaelmagu** [comment]
@kfox1111 I suppose another option is to let users of this chart override the forward section completely with a YAML heredoc.

**Comment by rafaelmagu** [comment]
Closed due to lack of interest by the maintainers.

**Pull request closed without merging**
