### PR TITLE
[incubator/kafka] upgrade cp-kafka image to 5.1.2

### PR DESCRIPTION
**Pull request by fabriziofortino**
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by barryoneill** [comment]
Thank you @fabriziofortino  - I would love to see this go in :)

**Comment by MartinX3** [comment]
Nice! Can you update it to 5.1.3, @fabriziofortino ?

**Comment by MartinX3** [comment]
@fabriziofortino
Please update your PR :)

**Comment by maorfr** [comment]
/lgtm

be merged!

**Comment by zanhsieh** [comment]
@fabriziofortino 
Could you rebase and fix the conflicts please?

**Comment by davidkarlsen** [comment]
Obsoleted by https://github.com/helm/charts/pull/19645

**Pull request closed without merging**
