### PR TITLE
[stable/metabase] Bump version metabase to v0.34.0

### PR DESCRIPTION
**Pull request by halfdan**
Signed-off-by: Fabian Becker <halfdan@xnorfz.de>

#### Is this a new chart
No

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by pmint93 — CHANGES_REQUESTED** [review]
@halfdan Please also bump image version in values.yaml

**Comment by davidkarlsen** [comment]
@halfdan Please update readme and Chart.yaml accordingly.

**Comment by halfdan** [comment]
@pmint93 @davidkarlsen Done, and updated to the just release 0.34.0

**Review by pmint93 — APPROVED** [review]

**Pull request merged**
