### PR TITLE
[incubator/buzzfeed-sso] Add deprecation notice

### PR DESCRIPTION
**Pull request by darioblanco**
Signed-off-by: Darío Blanco <dblancoit@gmail.com>

#### What this PR does / why we need it:

This repository will be archived, therefore we need to move the chart to a new org to keep it available to our users

> Nov 13, 2020. At 1 year, support for this project will formally end, at which point the stable and incubator chart repos will be marked obsolete. At that time these chart repos will likely be garbage collected and no longer available. This git repository will remain as an archive.

#### Which issue this PR fixes

The chart has been copied to a new repo and is available through `artifacthub` in https://artifacthub.io/packages/helm/minddocdev/buzzfeed-sso . I would like to add anybody interested in contributing to this chart to the [minddocdev/buzzfeed-sso](https://github.com/minddocdev/buzzfeed-sso) repo. I still need to define the CI pipeline (will be with Github actions) and other tasks, while we need to set the contribution guidelines, but it will be ready before contributions happen (as I will spend some time now in improving the chart and would like to discuss the v2 of it).

In addition, I have identified that we do not give support to `pathType`, so setting a `path` with `/` will only work as an exact match for the new API. Therefore, it is now possible to define `pathType` in the ingress resource.

#### Special notes for your reviewer:

@komljen if you are interested in being an owner, I will gladly give you privileges in the new repository 👍 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by darioblanco** [comment]
I do not know if we can bypass the version bump for this one. We just need to add the deprecation notice in the README.

**Comment by komljen** [comment]
> @komljen if you are interested in being an owner, I will gladly give you privileges in the new repository 👍

Yes, please.

**Review by komljen — APPROVED** [review]

**Comment by komljen** [comment]
@darioblanco yes, we need to bump the chart version number, that is fine.

**Comment by darioblanco** [comment]
@komljen it is now ready to be merged, I have added support to the `pathType` attribute in the Ingress `path` resource (optional).

!lgtm

**Pull request merged**
