### PR TITLE
[stable/jenkins] Respect SlaveListenerPort value in config.xml

### PR DESCRIPTION
**Pull request by jlegrone**
**What this PR does / why we need it**:
Configuration of SlaveListenerPort appears to be supported in `values.yaml`, but is currently hardcoded in `config.yaml`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
@jlegrone please rebase your PR with master and bump the chart version. this version is already taken 
thanks

**Comment by jlegrone** [comment]
Jenkins update center is down.

/retest

**Comment by jlegrone** [comment]
@cpanato please take another look.

**Review by lachie83 — APPROVED** [review]

**Pull request merged**
