### PR TITLE
[stable/logdna-agent] Support the newest 2.1.9 image + improve chart

### PR DESCRIPTION
**Pull request by jakedipity**
This commit updates and adds yamls to support the latest image of the logdna-agent. This commit also includes some changes to make this helm chart more configurable and to better follow the standards set forth by the Helm community.

Could I get the existing maintainer, @leeliu, to take a look as well.

Signed-off-by: Jacob Hull <jacob@planethull.com>

#### What this PR does / why we need it:

Continued support of the latest agent image.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mattfarina** [comment]
@leeliu can you take a look at these changes?

@jakedipity have you considered having the logdna chart being hosted and developed out of a logdna GitHub repo? If you do that you can get it listed in the [Helm Hub](https://hub.helm.sh/) and the [Artifact Hub](https://artifacthub.io/) for discoverability. You can [host it all on GitHub](https://github.com/helm/hub/blob/master/docs/github.md) and we even have [GitHub actions to help](https://github.com/marketplace?query=helm).

If y'all host it you don't need to wait on us for approvals.

**Comment by jakedipity** [comment]
@mattfarina Thanks for the suggestion, we'll look into that. If we hosted our own repository would it make sense to also publish this chart in the stable repository here? We want to make sure we have maximum exposure.

Also, if we did go that route, would it be okay to use a git submodule to avoid duplication?

**Review by leeliu — APPROVED** [review]

**Comment by mattfarina** [comment]
@jakedipity The stable repository is going to be deprecated and turned off later this year. If you keep it in both places it would be a short term thing. Helm 3 does not ship with the stable repository configured in it but it does enable searching the Helm Hub.

We don't accept submodules but we are ok with bots that apply the changes from an upstream repo to the charts repo. Bitnami has long done that.

Once you do move to a new location you can follow the deprecation process and point people to the new location. The wordpress chart in the stable repository is an example of that.

**Pull request merged**
