### PR TITLE
[stable/prometheus-operator] Fix kubemismatchversion incorrect

### PR DESCRIPTION
**Pull request by minhdanh**
#### What this PR does / why we need it:

This is a follow-up PR for https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/231

#### Which issue this PR fixes
  - fixes https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/231

#### Special notes for your reviewer:

It looks like the rules haven't been synced for a while. I just need to get my minor change merged but ended up with many other changes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
I think it would be possible to support Kubernetes 1.13 and earlier, provided that the old rules and dashboards are kept in the chart and enabled through a switch - simply replacing the dashboards with ones that require kubernetes 1.14 would limit the user base pretty significantly

**Comment by minhdanh** [comment]
@brancz What should I do regarding these changes? According to @vsliouniaev these are for K8s 1.14 and support for K8s 1.13 and earlier versions is dropped.

**Comment by brancz** [comment]
I know little to nothing about this chart so I can’t really make a judgement call on this. He is right about the incompatible changes, these were changes that landed in kubernetes 1.14. Whatever @vsliouniaev says should be done, after all he maintains this chart (I neither use nor maintain it) :)

**Comment by minhdanh** [comment]
@vsliouniaev I think applying all the changes and make it backward compatible with K8s 1.13- is out of the scope of this PR. So I just commit the related change for now.
Please see if it looks good.

**Comment by vsliouniaev** [comment]
https://github.com/helm/charts/pull/16230 takes care of this requirement

**Comment by minhdanh** [comment]
Ah alright. So I'm closing this.

**Comment by minhdanh** [comment]
@vsliouniaev I tried to deploy the latest chart to see if the fix is included but it's not.
The fix that I need only applies to K8s 1.14.
I'm not sure if I open this PR and make my change merged, will it be overridden when people run `sync_prometheus_rules.py` script?

**Comment by vsliouniaev** [comment]
Kubernetes 1.14 rules are the ones that are being actively developed, so the place to fix them is in the upstream projects - https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by ElfoLiNk** [comment]
@minhdanh  Backport the fix to the  release-0.1 branch

**Comment by minhdanh** [comment]
@vsliouniaev Yes, already: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/231

@ElfoLiNk Not sure I understand here. The fix I made already merged to [master](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/231), but that is used to build the rules for K8s 1.14. So now when I backport the fix to [release-0.1 branch](https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/release-0.1), and run `sync_prometheus_rules.py` script, that will help to apply the fix to the old rules?

**Pull request closed without merging**
