### PR TITLE
[stable/oauth2-proxy] Add podSecurityContext

### PR DESCRIPTION
**Pull request by pwillie**
Signed-off-by: Peter Wilson <dearpete@gmail.com>

#### What this PR does / why we need it:

This adds the ability to provide a pod security context to the running pod.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pwillie** [comment]
Morning @Miouge1 and @desaintmartin, is this something you are happy to include?  Let me know if you need anything further.  Cheers,

**Comment by desaintmartin** [comment]
Thanks! Indeed this is a nice addition. Could you add a test file in the ci directory?
/ok-to-test
/assign

**Comment by pwillie** [comment]
Test added @desaintmartin

**Comment by pwillie** [comment]
@desaintmartin was the added test what you were after?

**Comment by pwillie** [comment]
@Miouge1 and @desaintmartin , any further changes required?

**Comment by desaintmartin** [comment]
Perfect, thanks!
/lgtm

**Pull request merged**
