### PR TITLE
Handle priorityClassName for incubator/fluentd-cloudwatch.

### PR DESCRIPTION
**Pull request by Yannig**
#### What this PR does / why we need it:

Handle priorityClassName when deploying fluentd daemonset.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by Yannig** [comment]
Any comments on this PR?

**Comment by maorfr** [comment]
need to make tests green

**Comment by Yannig** [comment]
@maorfr Thanks for your feedback. I think it's fine now.

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Pull request merged**
