### PR TITLE
[stable/sonarqube] Fix plugin range scope bug

### PR DESCRIPTION
**Pull request by stevehipwell**
Signed-off-by: Steve Hipwell <steve.hipwell@gmail.com>

#### What this PR does / why we need it:
This PR fixes a bug in the template to copy plugins to the lib folder.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by stevehipwell** [comment]
@zanhsieh could you take a look and add the `/ok-to-test` comment? This fixes an issue with PR https://github.com/helm/charts/pull/19545.

**Comment by stevehipwell** [comment]
@rjkernick @tsiddique could you take a look and add the `/lgtm` label?

**Comment by rjkernick** [comment]
One got merged ahead of this one. Please merge the latest master and I will get this approved this morning

**Pull request merged**
