### PR TITLE
Update minio NOTES.txt

### PR DESCRIPTION
**Pull request by diwakar-s-maurya**
**What this PR does / why we need it**:
It fixes the command to find pod name of current helm release. The current command does not work.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by mattfarina** [comment]
/cc @nitisht 

@nitisht Did you want to setup an OWNERS file on the minio chart so you can be asked to review PRs and merge changes yourself?

**Comment by nitisht** [comment]
> Did you want to setup an OWNERS file on the minio chart so you can be asked to review PRs and merge changes yourself?

Yes, that will be great @mattfarina . How do we do this?

**Pull request merged**
