### PR TITLE
[stable/datadog] Update README

### LINKED ISSUE #22661: [stable/datadog] Resources are not enabled as documented
**Describe the bug**
As per https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L467, Resources for each agent container are commented out instead of being enabled as eluded to in the docs (under [configuration options](https://github.com/helm/charts/blob/master/stable/datadog/README.md#all-configuration-options))

**Which chart**:
`2.3.8` of the datadog chart

@xlucas @clamoriniere Please halp! Thanks!

PS: Any insight/links on how these values were derived and how accurate they are would be in larger clusters would be much appreciated!

### PR DESCRIPTION
**Pull request by xlucas**
#### What this PR does / why we need it:

Update the README with the right default values for resource constraints.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #22661

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by xlucas** [comment]
Not sure it makes sense to bump the Chart version for this?

**Comment by L3n41c** [comment]
The GitLab CI enforces the Chart version bump… even for README ! 🤦

**Comment by mattfarina** [comment]
@xlucas The policy on this repository is that any time there is a change the chart version is bumped. Even for readme file changes. This is enforced with automation so it cannot be merged until the version is incremented.

**Pull request merged**
