### PR TITLE
[stable/kong] Quote smtp environment variables that are not strings

### PR DESCRIPTION
**Pull request by Bouwdie**
Signed-off-by: Peter Bouwdewijn <peter.bouwdewijn@gmail.com>

#### What this PR does / why we need it:
Fixes SMTP configuration for enterprise deployment

#### Which issue this PR fixes
  - fixes #17462

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by hbagdi** [comment]
ping @rainest

**Comment by rainest** [comment]
👍 good catch; these should indeed be quoted.

**Review by hbagdi — APPROVED** [review]
/ok-to-test
/lgtm

This will need rebasing on the latest master and another version bump.

**Comment by Bouwdie** [comment]
@hbagdi rebased and bumped the version :taco:

**Review by hbagdi — APPROVED** [review]

**Pull request merged**
