### PR TITLE
[stable/jenkins] Refactor environment variables, secret and open

### PR DESCRIPTION
**Pull request by RoelVanNyen**
This pr allows users of this chart to add a custom env variable into the values.yml 
- If it is in the Secret list, it will be referenced from the kubernetes secret store. 
- If it is in the Open list it will just be added to the env list as is.

### CODE REVIEW

**Comment by viglesiasce** [comment]
Hey @RoelVanNyen!

Is it possible to do this in a backwards compatible way? Can you introduce a new `CustomEnv` variable that doesnt refactor the way that the envs work today?

**Comment by RoelVanNyen** [comment]
Closing this for now, if I have some time for it in the future I will get back to it.

**Pull request closed without merging**
