### PR TITLE
Updated istio charts use image pull policy as IfNotPresent.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes/charts/issues/1368

### CODE REVIEW

**Comment by gyliu513** [comment]
/assign @lachie83 

Can you help review? Thanks.

**Comment by gyliu513** [comment]
@lachie83 ping for review

**Comment by unguiculus** [comment]
I guess the problem here is that the chart uses latest versions, i. e. you'll have to use `Always`. Generally, I'd be very much in favor of this change, but we should add versions as well.

**Comment by lachie83** [comment]
I'm okay with this. @unguiculus I do pin everything to a global release tag. See https://github.com/kubernetes/charts/blob/master/incubator/istio/templates/ingress-deployment.yaml#L26

**Comment by lachie83** [comment]
@gyliu513 Can you please bump the chart version in Chart.yaml?

**Comment by lachie83** [comment]
Waiting on Chart version bump to merge.

**Comment by gyliu513** [comment]
@lachie83 rebased, can you help check?

**Comment by rshriram** [comment]
@lachie83 and @gyliu513, once @gyliu513's fixes are merged, would you mind sending a PR to fix the yamls and docs in istio, and also send a PR to https://github.com/istio/istio.github.io/blob/master/_docs/tasks/installing-istio.md, to add a pointer to this helm chart as a quick start installation.

**Review by rshriram — APPROVED** [review]
Quick feedback (i dont know much about the helm chart workflow).

I hope the docker image version is tweakable somewhere as some global setting? Soon, we will start having biweekly releases and it would be useful to have configurable helmcharts. (the official version - i.e. the one here) should always point to the stable one. Thoughts?

**Comment by gyliu513** [comment]
@rshriram I can follow up to update doc in istio.

BTW: The file here https://github.com/kubernetes/charts/blob/master/incubator/istio/values.yaml is the parameters that can be configurable, you can see that all of the images can be updated.

**Comment by unguiculus** [comment]
@lachie83 You're right. I was only looking at the `values.yaml` and did not see version tags for each image.

**Comment by lachie83** [comment]
@gyliu513 please bump the chart version then we are GTG

**Comment by gyliu513** [comment]
Can you please show more detail for how to bump the char version?

I found that the current version is [0.1.6-chart1](https://github.com/kubernetes/charts/blob/master/incubator/istio/Chart.yaml#L4), which version do I need to bump it to?

Also what is the policy of bumping the versions here for istio chart? Thanks @lachie83

**Comment by lachie83** [comment]
@gyliu513 please bump the chart version

**Comment by gyliu513** [comment]
@lachie83 Done, thanks

**Pull request merged**
