### PR TITLE
[stable/anchore-engine] Small improvement about secret end env

### PR DESCRIPTION
**Pull request by kozmagabor**
#### What this PR does / why we need it:
1. We'd like to use full specified of ["EnvVar"](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#envvar-v1-core) like this:

```
env:
 - name: FOO_BAR
    valueFrom: 
      secretKeyRef:
        name: secret-name
        key: key-in-secret
```

2. Add small improvement about database password too.
3. We'd like to use existing secret for admin and database password

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Btodhunter** [comment]
Thanks for the contribution! I'll do some testing on this and hopefully get it approved asap. 

The one thing I noticed upon review was that the ANCHORE_DB_PASSWORD value change in the secret file for the enterprise feeds database will end up overwriting the ENV var for all other engine components, which will cause database connectivity issues if a different password was utilized for each DB. This is why I had to use the .feedsDbPassword value & add it to the pod definition directly.

**Comment by kozmagabor** [comment]
Hi @Btodhunter,

Yes, You're right!
I removed that commit.

**Comment by kozmagabor** [comment]
Hi @Btodhunter 

Any update about this PR?

Thanks,

**Comment by Btodhunter** [comment]
@kozmagabor Sorry, something came up. Testing it now and will approve asap.

**Comment by Btodhunter** [comment]
@kozmagabor This looks good and everything worked great in testing. One request before approval. Can you please update all the 'extraEnv' sections in the values.yaml file to have comments describing the syntax for specifying the vars.

Basically just replace all these sections:
```
extraEnv: {}
  # foo: bar
```
with:
```
extraEnv: []
  # - name: foo
  #    value: bar
```

Thanks!

**Comment by kozmagabor** [comment]
@Btodhunter I did it.

Thanks!

**Pull request merged**
