### PR TITLE
[stable/prometheus] added extra scrape config option

### LINKED ISSUE #5092: [stable/prometheus] adding custom scrape_configs seems convoluted
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes v1.9.6

**Which chart**:
stable/prometheus

**What happened**:
I couldn't find a simple way to add scrape configs. The only functional way I found to do that was to copy the whole contents of serverFiles.prometheus.yml.scrape_configs default over to my values.yaml and then append my scrape configs to that

**What you expected to happen**:
The contents of the prometheus.yml file could be broken in such a way to allow concise addition of content to each of its sections. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I implemented changes in my fork. I'll follow up with a PR

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* Adds an option to add additional scrape configs to prometheus.yml without the need to copy the whole prometheus.yml to your values file.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
    - fixes #5092 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — COMMENTED** [review]
/assign

**Comment by monotek** [comment]
I currently thinking about to make Blackbox exporter part of the chart like node exporter. 

Opinions?

**Comment by monotek** [comment]
Resolved merge conflicts.

**Comment by monotek** [comment]
@gianrubio what do you think about making Blackbox exporter part of the chart like node exporter?

If we would do this do we need the extra scrape config at all?

**Comment by gianrubio** [comment]
> @gianrubio what do you think about making Blackbox exporter part of the chart like node exporter?

I think it's a good idea to add it, I'd advice you to use [requirements](https://github.com/helm/charts/blob/master/stable/kong/requirements.yaml) from the official chart to make easier to manage dependencies.

**Comment by Phadated** [comment]
Can anyone please  explain this line "-  must be a string so you have to add a | after extraScrapeConfigs:"  with an example

**Comment by monotek** [comment]
https://adminswerk.de/multi-line-string-yaml-ansible-I/

**Pull request merged**
