### PR TITLE
[stable/magento] Bump Magento version 

### PR DESCRIPTION
**Pull request by juan131**
- Update Drupal image version to "2.1.3-r0".
- Update chart to "0.4.2".

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@juan131 can you update the MariaDB requirement to 0.5.x here as well

**Comment by juan131** [comment]
@prydonius MariaDB version updated.

**Review by prydonius — APPROVED** [review]
Thanks @juan131

**Pull request merged**
