### PR TITLE
Adds resource limits for containers in deploy

### PR DESCRIPTION
**Pull request by tlm**
#### What this PR does / why we need it:
Adds resource limits to containers in OPA deployment

#### Which issue this PR fixes:
No open issues for this fix

#### Special notes for your reviewer:
The current resources section defined in the deployment isn't doing anything

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by tsandall — APPROVED** [review]

**Comment by tlmiller** [comment]
Merged latest master and bumped chart version

**Pull request merged**
