### PR TITLE
[stable/concourse] fixed incorrect values for gitlab auth secrets

### PR DESCRIPTION
**Pull request by draeron**
Pretty straighforward : github secrets were created instead of gitlab's.

Feel free to accept the PR or correct it in another PR.

### CODE REVIEW

**Comment by william-tran** [comment]
Looks like a copy paste error on my part, thanks for the PR @draeron. If you want to go through the CLA steps I'll keep this one live, but if you need this urgently before you go through the CLA I can make another PR for this.

**Review by william-tran — APPROVED** [review]

**Comment by draeron** [comment]
the form was signed, i guess it might take some times before the bot updates it.

**Comment by william-tran** [comment]
@draeron not sure why its saying `commit missing GitHub user`

**Comment by william-tran** [comment]
heh that must've kicked it. Take a look at the linter result in the `ci/circleci` status:
```
Error please increment the new chart version to be greater than the existing version of 1.0.0
```

**Comment by william-tran** [comment]
@draeron  The current chart version is 1.0.1 as a PR was just merged, so you'll need to bump this to 1.0.2

**Comment by william-tran** [comment]
Thanks again @draeron!

**Pull request merged**
