### PR TITLE
[stable/metricbeat][1.6.0] adding support for pod priority

### PR DESCRIPTION
**Pull request by djsly**
#### What this PR does / why we need it:
Augments the metricbeat chart with pod priority logic using the priorityClassName field on both the daemonset and deployment object. 

#### Special notes for your reviewer:
I didn't set a default one even though I would normally see `system-node-priority` and `system-cluster-priority` for the daemonset and deployment object respectively. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by djsly** [comment]
@mumoshu and @at-k can you please review. who should we assign it to ?

**Review by cpanato — APPROVED** [review]

**Pull request merged**
