### PR TITLE
[stable/prometheus-operator] Update Prometheus version

### PR DESCRIPTION
**Pull request by spyros87**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by spyros87** [comment]
@vsliouniaev Could you please check?

**Comment by vsliouniaev** [comment]
@spyros87 Could you please bump the chart version?

**Comment by spyros87** [comment]
@vsliouniaev The version is bumped.

**Comment by vsliouniaev** [comment]
thanks!
/lgtm

**Comment by stijndehaes** [comment]
@vsliouniaev I am wondering if changing the default version from something different then the default version used by prometheus operator was a good idea. Could you quickly tell me what the risks are of diverging? Or maybe I am overthinking this and the risk is minimal?

**Pull request merged**
