### PR TITLE
(feat) Update Spark Chart

### PR DESCRIPTION
**Pull request by lachie83**
Add NOTES.txt
Use template helper
Move to stable

### CODE REVIEW

**Comment by lachie83** [comment]
Existing PR for reference -- https://github.com/kubernetes/charts/pull/163

**Comment by prydonius** [comment]
lgtm, was able to successfully deploy and access the portals

**Comment by viglesiasce** [comment]
Also tested manually by running the getting started tutorial. Worked a treat. Thanks @lachie83!

**Pull request merged**
