### PR TITLE
[stable/kiam] Added the image pull secret

### PR DESCRIPTION
**Pull request by junaid18183**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@junaid18183 please fix the lint issue
```
4:3       error    missing starting space in comment  (comments)
```

**Comment by junaid18183** [comment]
@cpanato I have fixed those linting issues

**Comment by ewbankkit** [comment]
@junaid18183 The kiam chart is now hosted by uSwitch.
Please open the PR in [their repo](https://github.com/uswitch/kiam) and close here.
Thanks.

**Comment by junaid18183** [comment]
> @junaid18183 The kiam chart is now hosted by uSwitch.
> Please open the PR in [their repo](https://github.com/uswitch/kiam) and close here.
> Thanks.

Thanks @ewbankkit I have opened https://github.com/uswitch/kiam/pull/303 closing this one

**Pull request closed without merging**
