### PR TITLE
[stable/cluster-autoscaler] add path to servicemonitor to allow prometheus scraping

### PR DESCRIPTION
**Pull request by pm990320**
Signed-off-by: Patrick Menlove <patmenlove@gmail.com>

#### What this PR does / why we need it:

Using kube-prometheus, the current configuration did not show the cluster autoscaler in the prometheus targets. This was fixed by adding `path: /metrics` to the servicemonitor.

#### Special notes for your reviewer:

Unsure of the versioning scheme - should this be a minor or patch version bump?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks! Please bump the minor version in `Chart.yaml`.

**Review by yurrriq — CHANGES_REQUESTED** [review]
Needs version bump

**Comment by pm990320** [comment]
Ok - I have bumped the minor version and added another change I later made to get it to work - selecting the namespace where cluster-autoscaler is deployed.

**Comment by yurrriq** [comment]
Thanks!
/ok-to-test

**Pull request merged**
