### PR TITLE
[stable/influxdb] Move bind_address under rpc header and update image to 1.7

### PR DESCRIPTION
**Pull request by naseemkullah**
Please see title

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @jackzampolin

**Comment by naseemkullah** [comment]
cc @jackzampolin

**Comment by jackzampolin** [comment]
Good for me! LGTM 👍

**Comment by naseemkullah** [comment]
bump

**Comment by scottrigby** [comment]
@naseemkullah Just a quick note about version. Since this chart is in stable, it should be at least 1.0.0. And since this is a breaking change, would you also please add an "Upgrading" section to the README letting users know when upgrading from `< 1.0.0` they'll need to change their charts values? See https://github.com/helm/charts/issues/5657.

Also @jackzampolin if you're added to an OWNERS file for this chart, you will be able to merge changes yourself. The best way is to create a PR adding yourself. See https://github.com/helm/charts#owning-and-maintaining-a-chart and https://github.com/helm/charts/issues/7446. Would you want to do this? And are there others who should be added to that?

**Review by scottrigby — CHANGES_REQUESTED** [review]
See https://github.com/helm/charts/pull/9384#issuecomment-443467617

**Review by scottrigby — APPROVED** [review]
👍

**Pull request merged**
