### PR TITLE
Typo fix in fluentd-cloudwatch/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
a small typo fix in fluentd-cloudwatch/README.md line 45

### CODE REVIEW

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
/retest

Going to retest again now that #4278 has landed to try and get more details.

**Comment by AdamDang** [comment]
@mattfarina 
Thanks a lot for your attention. I'd better close this PR before the problem solved.

**Pull request closed without merging**
