### PR TITLE
[incubator/docker-auth]add docker-auth helm chart

### PR DESCRIPTION
**Pull request by duyanghao**
Signed-off-by: duyanghao <1294057873@qq.com>

#### What this PR does / why we need it:
add helm chart of [docker auth](https://github.com/cesanta/docker_auth), which is a popular Docker Registry 2 authentication server.

### CODE REVIEW

**Comment by duyanghao** [comment]
> /assign @lachie83

/assign @lachie83

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

**Comment by scottrigby** [comment]
Would love to see this on Helm hub. Ping us on Slack if you need any help

**Pull request closed without merging**
