### PR TITLE
[incubator/zookeeper] Add Prometheus operator handling - define metri…

### PR DESCRIPTION
**Pull request by pierwszywolny**
#### What this PR does / why we need it:
Add Prometheus operator handling - [define metric endpoint autoconfiguration using the ServiceMonitor entities](https://sysdig.com/blog/kubernetes-monitoring-prometheus-operator-part3)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by pierwszywolny** [comment]
Hi @lachie83, any chance to have it reviewed?

**Comment by kaarolch** [comment]
@lachie83  any chance to merge this PR?

**Comment by kaarolch** [comment]
@kow3ns can you check this PR?

**Comment by lachie83** [comment]
I've just LGTMd https://github.com/helm/charts/pull/12672. Once that merges is this one still relevant and are there changes that need to be taken into consideration?

**Comment by pierwszywolny** [comment]
@lachie83 - no more work needed with this PR - seems it is duplicate of #12672

**Pull request closed without merging**
