### PR TITLE
[stable/prometheus] Update Prometheus Deployments and DS's for 1.16

### PR DESCRIPTION
**Pull request by VariableDeclared**
* Changed extensions/v1beta2 for apps/v1.

More info: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

No.

#### What this PR does / why we need it:

Bump YAML for Kubernetes 1.16.

#### Which issue this PR fixes
No issue found.

#### Special notes for your reviewer:
Bumped DaemonSet & Deployment appVersions.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by aayushdgkd — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@VariableDeclared can you fix the conflicts?

**Pull request closed without merging**
