### PR TITLE
[stable/nginx-ingress] disable Cluster roles if is a scope ingress

### PR DESCRIPTION
**Pull request by danigrmartinez**
**What this PR does / why we need it**:
This PR avoid creation of ClusterRole and ClusterRoleBinding when ingress is deployed as scope enabled. 

This is useful when you are deploying in a restrictive kubernetes cluster without permissions to create ClusterRoles or bind ClusterRoles. Since the ingress is Scope to a namespace, the Role is already good option.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: -

**Special notes for your reviewer**: 
I just tested within the default namespace. I am not sure will work if you specify a different namespace than where it is deployed.

### CODE REVIEW

**Comment by unguiculus** [comment]
Shouldn't we create `Role` and `RoleBinding` instead?

**Comment by danigrmartinez** [comment]
@unguiculus There is already a `Role` and `RoleBinding`. We may want to unify both (`Role` and `ClusterRole`) with the same permissions and change the type depending on if it is scoped or not.

**Pull request merged**
