### PR TITLE
[stable/grafana] apply comment on last PR

### PR DESCRIPTION
**Pull request by obeyler**
#### What this PR does / why we need it:
apply good remark done on my last PR https://github.com/helm/charts/pull/15149 by @qrilka and @Kieran-Brown

see also previous discussion on PR #15544  (closed because git trouble on DCO) 
#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by qrilka** [comment]
I still think that  #15149 should be reverted and the connection between dashboardProviders/dashboards and datasources should be just better covered in documentation.

**Comment by previ** [comment]
I am getting `Init:Error` at container `download-dashboards` starting.
Error message in init container log: `/bin/sh: /etc/grafana/download_dashboards.sh: Permission denied`.

**Pull request merged**
