### PR TITLE
[stable/sonatype-nexus] Fix conditional for tls to line up with docs

### PR DESCRIPTION
**Pull request by bbriggs**
**What this PR does / why we need it**: Current TLS conditional checks for `ingress.tls` instead of `ingress.tls.enabled`, as the docs indicate it should. This patch makes the code line up with the docs. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rjkernick** [comment]
Please bump the version in Chart.yaml

**Comment by bbriggs** [comment]
Hey @rjkernick, I bumped the version in Chart.yaml and rebased into the original commit. Are we okay to move forward?

**Pull request merged**
