### PR TITLE
[incubator/kafka] Makes updateStrategy fully configurable

### PR DESCRIPTION
**Pull request by fedenusy**
The kafka chart with `updateStrategy: RollingUpdate` _always_ ran partitioned updates, which broke `kubectl rollout status`.

This PR makes `updateStrategy` fully configurable, allowing `RollingUpdate`s without partitions.

This PR also updates nested zookeeper chart, to make zookeeper `rollingUpdate` configurable also.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @benjigoldberg @faraazkhan @h0tbird

**Comment by faraazkhan** [comment]
LGTM

**Pull request merged**
