### PR TITLE
[gitlab] Update api versions to support k8s 1.16

### PR DESCRIPTION
**Pull request by antongorkovenko**
Signed-off-by: Anton Gorkovenko <gostom@gmail.com>

#### Is this a new chart
no
#### What this PR does / why we need it:
Update api versions (deprecated -> actual) to support k8s 1.16
ref: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
#### Which issue this PR fixes
-
#### Special notes for your reviewer:
-
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by antongorkovenko** [comment]
@zanhsieh please approve

**Comment by zanhsieh** [comment]
@antongorkovenko 
This chart has no owner. BTW, you might consider to contribute to the chart maintained by gitlab themselves since on README.md stated this chart is deprecated.

**Pull request closed without merging**
