### PR TITLE
[stable/k8s-spot-termination-handler] Add missing 'namespace'

### PR DESCRIPTION
**Pull request by kforsthoevel**
The 'namespace' wasn't set for daemonset and serviceaccount.

Signed-off-by: Kai Forsthövel <kai.forsthoevel@invision.de>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@kforsthoevel 
Would you mind to bump the chart version to latest please? Thank you.

**Comment by kforsthoevel** [comment]
@zanhsieh - I have bumped the version from 1.4.6 to 1.4.7 already. Or am I missing something here? Sorry, it's my first PR for this repo.

**Comment by zanhsieh** [comment]
@kforsthoevel 
Yes, this PR need another bump to 1.4.8 due to fast iteration (unfortunately).

**Comment by kforsthoevel** [comment]
@zanhsieh 
Is there anything else I need to do? Thanks.

**Comment by zanhsieh** [comment]
@axozoid
@egeland
@kierranm
@mariusv
Would you guys LGTM this PR please?

**Pull request merged**
