### PR TITLE
[stable/Locust] adding a new maintainer

### PR DESCRIPTION
**Pull request by sekka1**
Applying to be an owner of the Locust chart.

Pass contribution to this chart:
* https://github.com/helm/charts/commit/a8279d3ce8aeb941237da319990d8de4a0eb977e#diff-a767ca50c32a0139601cbc9a43d17b78

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
have the old maintainers requested to be removed?

ping @so0k @haugene

would you like to be added as owners?

**Comment by sekka1** [comment]
@maorfr The OWNERS file and the maintainers file was not in sync.  In this issue it says to add your name into the maintainers so I figured something was not correct.  I have added them back into the maintainers list.  However, I am the only OWNER.

**Comment by so0k** [comment]
Hi, sorry, I no longer use Locust and you can remove me 

How to request to be removed?

**Comment by haugene** [comment]
Hey guys. I still want to help out with this chart. Admittedly I haven't done much here since my first contribution - but being in the owners would probably make it easier as well. I haven't been able to approve pull requests etc.

Referring to your post(#13869) @maorfr, I would like to be added as a maintainer. You say that "we aim to have 2 maintainers per chart", so that might be a good fit @sekka1? If on the other hand @sekka1 wants to go solo then that's ok as well.

Link to past contribution: https://github.com/helm/charts/commit/0ab53c795720882f3f9630c12f8ecf96ba881638#diff-a767ca50c32a0139601cbc9a43d17b78

PS: I've noted that we need an update in the base image again. I'll get a continuous build going :)

**Comment by sekka1** [comment]
@haugene I would like a co-maintainer and I think they (Helm charts repo) want 2 people on a project.

This sounds like a plan.  Let me change this PR with @haugene and @sekka1 . 

I will also remove @so0k .

**Comment by sekka1** [comment]
@maorfr I have updated per the comments in this thread.  Can you review?

**Comment by sekka1** [comment]
@maorfr ping ping ^

=)

**Comment by maorfr** [comment]
Added you both to the org, verify owners once you have accepted.

Also, Chart.yaml and OWNERS should contain the same people (I'm confused by garland/sekka1).

**Comment by sekka1** [comment]
@maorfr I have updated the owners/maintainers names to match.  That was my github handle and my real email address.  I have now made them the same.

**Comment by haugene** [comment]
@sekka1 I think it's only the names that were supposed to match. Your email could probably just stay the same. Have you accepted the invitation to the org?

**Comment by sekka1** [comment]
@haugene I just accepted the invite to the org.

**Comment by zanhsieh** [comment]
@sekka1 
You could test LGTM now.

**Comment by maorfr** [comment]
/lgtm

good luck!

**Comment by mbeacom** [comment]
@sekka1 @haugene

Would it be possible to adding some maintainers or the owner from the official locust org/repo to the maintainers list, so we can update it as we push out new releases?

This chart is using `0.9.0` which was September 1, 2018.  We are now on `0.12.2` available at: https://hub.docker.com/r/locustio/locust

**Comment by mbeacom** [comment]
I suppose it's worth adding, this publicly available helm chart *is not* using the official locust.io docker image.

**Comment by haugene** [comment]
Hey @mbeacom. In general I think that the more people can help out, the better. Having someone from the official org is a pure bonus. As for your comments, I have it on my todo list to create a CI/CD pipeline to build new versions of the image for each release of Locust and then maybe set up a PR here.

The reason why the official docker image isn't used is probably because we need the entrypoint.sh script to make the workers wait for the master to be ready. I've just branched this from the original GoogleCloudPlatform. Ironically I did it because it was out of date then. So I fixed the symptoms but not the issue I guess.

Anyways. If we could incorporate this into the official image then we don't have to maintain this side-version. Open to suggestions 👍

**Comment by haugene** [comment]
@mbeacom Just as an update here. I created a CircleCI workflow for the project and built all the version up until 0.13.1. In the last one I had to look at the official image to see that there were new dependencies needed.

Overall I want to re-use more of the official image. I'll try to find some time for experimentation, but I think that the Helm Chart version still needs its own entrypoint etc. This can either be checked into the official image and overridden in the chart, but it might be cleaner to base the Helm Chart version off the official image and only do the necessary tweaks in that Dockerfile.

As I said, I'm open for suggestions. For now I'll try to get the new version tested and bump the version here in the chart. Then we can discuss the best approach going forward. I guess this issue is not the place for it though. So I suggest one of us opens a new issue, either here or in the official repo, when we have a suggestion on how to proceed.

Links to build and new tags:
https://circleci.com/gh/greenbird/locust
https://hub.docker.com/r/greenbirdit/locust/tags

**Pull request merged**
