### PR TITLE
[stable/consul] Fix random test pod names

### LINKED ISSUE #8879: [stable/consul] random resource name causing issues
We are using https://github.com/roboll/helmfile to define our cluster setup through GitOps.

Helmfile runs diff and only does a `helm upgrade` when there are changes.

Consul has `consul-test.yaml` template with a random name, causing Helmsfile to always detect changes and try to upgrade.

```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"
  annotations:
    "helm.sh/hook": test-success
```

Would it be possible to remove the random part from the resource name, or atleast make the test optional?

### PR DESCRIPTION
**Pull request by lachlancooper**
#### What this PR does / why we need it:

Fixes random test pod names which cause `helm diff` to always detect changes.

A number of other charts are affected by this issue with seemingly no consensus on a solution as yet. However, I believe this is a reasonable way forward. See issue for further discussion.

#### Which issue this PR fixes
  - fixes #8879

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by michaelgeorgeattard** [comment]
What is the status of this PR please?

**Comment by lachlancooper** [comment]
As with other contributions I've made to this repository that were automatically closed without review, this issue isn't "stale". While minor, the issue still affects us daily, and as far as I'm aware this change fixes that without any major side effects.

**Comment by michaelgeorgeattard** [comment]
I honestly don't see why this PR is not merged.

Can you at least get a reason, so we can fix/improve on the PR?

**Comment by lachlancooper** [comment]
This trivial PR has been open for 3 months without any interaction from a maintainer. Without an indication of why it has been ignored I see little point in continuing to keep it up to date with master.

At this stage the process of contributing to this repo is too slow and inconsistent for our business to rely on, so we have chosen instead to maintain private forks of all the charts we use. It seems a shame that the community will be unable to benefit from any fixes we make.

Sorry, @michaelgeorgeattard. Feel free to propose this change in your own PR, perhaps you'll have better luck.

**Pull request closed without merging**
