### PR TITLE
Changed persistence.size to reflect actual values

### PR DESCRIPTION
**Pull request by MohamadGamal**
**What this PR does / why we need it**:
As the persistence.size description does not match that in the Values.yaml

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by rjkernick** [comment]
Thanks for the pull request. Please sign the CLA and increment the version in Chart.yaml

**Comment by MohamadGamal** [comment]
Hello @rjkernick , thanks for your reply  , I have signed the  CLA , but do I need to increment the version ? as it's just a change in the values description table

**Comment by rjkernick** [comment]
Hello,

Yes, even a small change needs to increase the version.

Rob Kernick

**Comment by MohamadGamal** [comment]
Done

**Pull request merged**
