### PR TITLE
[stable/jenkins] Add `master.jenkinsHome` and `master.jenkinsRef` options

### PR DESCRIPTION
**Pull request by vjda**
#### What this PR does / why we need it:

This PR enables those want to use their custom docker images from Jenkins or even to use Cloudbees Jenkins Distribution docker image. Now you can set the jenkins home path and the jenkins reference path where plugins and secrets are installed

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

/assign @torstenwalter

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vjda** [comment]
Hi @torstenwalter! I've just updated `README.md` to include both options. I forgot including them in my previous commit.

**Review by torstenwalter — COMMENTED** [review]
/lgtm

**Comment by torstenwalter** [comment]
Thank you for your contribution. Thats a nice addition.

**Comment by vjda** [comment]
Happy to help! :) Thanks @torstenwalter!

**Pull request merged**
