### PR TITLE
[stable/k8s-spot-termination-handler] AWS Spot termination handler

### PR DESCRIPTION
**Pull request by KierranM**
#### What this PR does / why we need it:
This is a chart for pushers handy [k8s-spot-termination-handler](https://github.com/pusher/k8s-spot-termination-handler) (the same folks who made [k8s-spot-rescheduler](https://github.com/helm/charts/tree/master/stable/k8s-spot-rescheduler)) for handling AWS Spot Instance termination requests to drain nodes.

#### Special notes for your reviewer:
I'm keen to get this into stable, so anything that needs to be done to make it so let me know. I've tested this chart myself and confirm it functions as expected.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by KierranM** [comment]
Hey @paulczar or @lachie83, anything I can do to get this reviewed/merged? :)

**Review by paulczar — APPROVED** [review]

**Comment by KierranM** [comment]
@paulczar do you have permission to merge this PR? I don't 😭

**Comment by legal90** [comment]
@KierranM @paulczar 
Should it be synced with the same chart form `incubator`? https://github.com/helm/charts/tree/master/incubator/kube-spot-termination-notice-handler

It has a README.md and uses the "official" image `kubeaws/kube-spot-termination-notice-handler`.

**Pull request merged**
