### PR TITLE
[stable/nextcloud] Ingress hosts configurable in values

### PR DESCRIPTION
**Pull request by almahmoud**
#### Is this a new chart
No

#### What this PR does / why we need it:
Adds the ability to specify ingress hosts, especially useful to change paths which is currently not possible.

We are currently using this modified chart and can successfully run the chart on a custom path by just changing the ingress path and adding an nginx annotation to rewrite the path. There doesn't seem to be an easy way to run at a custom path otherwise.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by almahmoud** [comment]
Squashed commits and signed-off, this should be ready for review now.

**Comment by chrisingenhaag** [comment]
Hi @almahmoud , thx for the PR. 

Sounds reasonable. I´m currently thinking of a possible addition to the ingress with a path rewrite.
Something like `nginx.ingress.kubernetes.io/rewrite-target: /` for nginx-ingress-contoller. But this would be ingress controller specific.

But anyway, anybode can add annotations to the ingress-object

/lgtm

**Comment by almahmoud** [comment]
@chrisingenhaag That is what we're doing. This is a working way to run the chart at path `/nextcloud/example/path`:

```
ingress:
  enabled: true
  hosts:
    - host: 'example.com'
      paths:
        - /nextcloud/example/path(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
```
(The proxy annotations to allow larger uploads)

**Comment by almahmoud** [comment]
Updated to latest master, fixed conflicts, and signed off on the last commit. Lmk if you want me to squash again or do something else

**Comment by almahmoud** [comment]
P.S. I edited the sign off manually to use my Full Name rather than the automated one that uses username, so DCO check seems to fail because it expects the username.

**Comment by almahmoud** [comment]
@chrisingenhaag Anything wrong with this? Can we get this merged?

**Pull request closed without merging**
