### PR TITLE
Rookout

### PR DESCRIPTION
**Pull request by Zohar2506**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
This is PR number 4 you open for Rookout. Why? Please reopen #6167 and fix issues there. Otherwise we lose all review history and can start all over again. Thanks.

**Comment by unguiculus** [comment]
Let me know if you need assistance.

**Comment by Zohar2506** [comment]
Reopened @unguiculus #6167

**Pull request closed without merging**
