### PR TITLE
[stable/traefik] Fix Prometheus Bucket precision truncation

### PR DESCRIPTION
**Pull request by lawliet89**
Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

#### What this PR does / why we need it:

Prevents Prometheus buckets smaller than 100ms from being truncated during templating.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by lawliet89** [comment]
@dtomcej 

Not sure if you are the right person. Please, could you take a look at this please.

**Comment by lawliet89** [comment]
Unstaling this. Any word from maintainers?

**Comment by dtomcej** [comment]
@lawliet89, sorry I must have missed this in my email,

Can you rebase this? I don't have any problem with removing the truncation.

**Comment by lawliet89** [comment]
@dtomcej I have rebased and bumped the minor version.

**Comment by Aisuko** [comment]
Hi @dtomcej, I have a consider with the chart's MINOR version. Why has a `74`?  And it can grow up to 100?

**Comment by lawliet89** [comment]
Fixed the failing test.

**Pull request merged**
