### PR TITLE
Wordpress chart for bare metal installation of k8s

### PR DESCRIPTION
**Pull request by nordri**
I see all charts are designed to run under a cloud provider. 
This chart is for bare metal, so to expose the service it uses NodePort instead of LoadBalancer.
Also it uses traefik (not included) to expose services to outside world.
It uses NFS and MySQL servers to store the files and database respectively.
I think I've explained all the details in the README file.

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by migmartri** [comment]
Hi @nordri,

First of all, thanks for the raising the bare-metal use case with this PR, there is good stuff in here :)

I believe (@prydonius or other official maintainer please correct me if I am wrong) that the charts in the official repository must include all the pieces required (i.e MySQL tier) to work out of the box or with minimal configuration (i.e hostname for Ghost).
 
That statement does not seem to be true in the proposed PR since it requires a running NFS and MySQL servers which might make it not suitable for merging.

That said, I would like to know what are your thoughts on extending the official stable WordPress chart to support the singularities or running apps in baremetal via configuration options.

### NodePort instead of LoadBalancer.

This can be changed using the properties `Values.serviceType` either in the yml file or at runtime executing `helm install stable/wordpress --set serviceType=NodePort`

### Ingress controller

Instantiated depending on a/some flags in the Values.yml file.

### Persistent Volume

I believe that in we rely on Cloud specific PV auto-provisioning, I am wondering what would be the best way to fit a configuration option in the Values.yml file. @prydonius have you guys thought about this?

Conditionally attaching a PV resource could be a feature extended across all the charts. 

Thanks!

**Comment by nordri** [comment]
Hello @migmartri 
Thanks for your words. I really appreciate your time.

>  the charts in the official repository must include all the pieces required

I've follow the CONTRIBUTING guidelines and it is true. If your chart depends on others they must be included. Nevertheless, I assume that if you are using Kubernetes on bare metal you have access to a MySQL and NFS servers on premise. 

> NodePort instead of LoadBalancer.

Indeed, but I do an extra step setting up the URL that will be use in the ingress controller. If you use the stable/wordpress with `serviceType: NodePort` the access to the wordpress web is through http://node:port while my proposal it is through http://hostname

> Ingress controller

Not sure what do you mean. I couldn't find any reference to ingress.yaml in the stable/wordpress directory tree. This was one of my motivation to do the PR. Doing something different from all the charts.

> Persistent Volume

I'm sorry but I'm little lost in this point as I've never seen PV auto-provisioning before (not in bare metal). I've always use PV and PVC. I configure the volume (NFS, Ceph, Gluster) and then write the appropriate yaml to use them on Kubernetes.

I'll keep working and try to do more platform independent. I want to include the MySQL chart in a future release.

Definitely, I don't want to replace stable/wordpress chart at all. The Bitnami team does a fantastic job. It's only that I need a different configuration to make it work and I choose the official Wordpress image because of the Kubernetes example [here](https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd)

Thanks!

**Comment by viglesiasce** [comment]
@nordri I agree with @migmartri that this work should be done in the stable/wordpress chart to make it more configurable.

**Comment by nordri** [comment]
OK. Let's do it. 
I'm now struggling with stable/wordpress configuration. I set the persistent as false and the service type as NodePort and I received this error:

 ` 19s        5s        3    {kubelet minion1}
  Warning        FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "exasperated-quokka-wordp" with RunContainerError: "GenerateRunContainerOptions: secrets \"exasperated-quokka-maria\" not found"`

There is no MariaDB available for wordpress chart and I thought all the dependencies should be included in the chart.

I'm missing something for sure.

**Comment by viglesiasce** [comment]
Hey @nordri! When developing on a chart, make sure to run `helm dep update` to pull in its dependencies. When charts are released by our CI process we automatically handle that.

**Comment by nordri** [comment]
Brilliant!
I can now deploy stable/wordpress on my infrastructure. Also I can use my ingress controller to address the service from the outer world.

So, what I want to do is if ServiceType is NodePort then write the ingress resource.

@prydonius suggested yesterday on Slack to use:

> @nordri or possibly a .Values.ingress.enabled and the ingress namespace could be used to provide other ingress settings

So I'll work in that direction. I don't know if I should close the PR and open it again when I've something to work with...

**Comment by prydonius** [comment]
@nordri great to hear. I think closing this and opening a separate PR makes more sense. Looking forward to the ingress support, this is definitely something we should add support for in most charts!

**Comment by nordri** [comment]
I will be back ;)

**Pull request closed without merging**
