### PR TITLE
[stable/grafana] Dashboards per providers and external ConfigMaps for dashboards

### PR DESCRIPTION
**Pull request by richerve**
**What this PR does / why we need it**:

It brings the possibility of specifying dashboards per provider. Right now is possible to configure multiple providers but is not possible to have a list of dashboards per each one.

It also includes the feature to reference external ConfigMaps containing dashboard configurations per provider 

**Special notes for your reviewer**:

This Change `values.yaml` slightly, specifically `dashboards: {}` to allow the definition per provider, so is a breaking change.

### CODE REVIEW

**Comment by richerve** [comment]
ping @mgoodness, any comment on this?

**Comment by unguiculus** [comment]
cc @zanhsieh @rtluckie

**Review by zanhsieh — APPROVED** [review]

**Comment by richerve** [comment]
ping @unguiculus @rtluckie @mgoodness 

Any movement on this?

**Comment by rtluckie** [comment]
@richerve changes look really good!  I will try and test later today.

**Comment by rtluckie** [comment]
lgtm

**Comment by richerve** [comment]
thx @rtluckie, Anything else needed at this point?

**Comment by richerve** [comment]
Rebased on master, any way to move this forward?

**Comment by richerve** [comment]
Rebased on master again.

Is there any interest to move this forward?

**Comment by richerve** [comment]
@unguiculus @rtluckie @zanhsieh @mgoodness, friendly ping

**Comment by richerve** [comment]
@zanhsieh is @mgoodness still the assignee of this Chart?

**Comment by zanhsieh** [comment]
@richerve I think @unguiculus could merge.

**Comment by richerve** [comment]
ping @unguiculus

**Comment by richerve** [comment]
Again, friendly ping @unguiculus @zanhsieh

**Pull request merged**
