### PR TITLE
Standalone dogstatsd fix

### PR DESCRIPTION
**Pull request by sdickhoven**
#### What this PR does / why we need it:
When running a standalone dogstatsd Deployment using the `datadog/dogstatsd` image, the pod gets killed by the liveness check.

This happens because the `datadog/dogstatsd` image does not include a `./probe.sh` command.

Since dogstatsd is a very simple single-process listener, the liveness check can be omitted IMHO.

A more permanent fix might be to update the `datadog/dogstatsd` image with a `./probe.sh` command but I'm not sure if this script could do much more than check if the process is running (in which case it is superfluous).

#### Which issue this PR fixes
No issue was opened for this.

#### Special notes for your reviewer:
This fix is specifically for a standalone dogstatsd Deployment. It does not attempt to fix any other use cases (e.g. DaemonSet).

The helm config is as follows:

```yaml
image:
  repository: datadog/dogstatsd
daemonset:
  enabled: false
deployment:
  enabled: true
datadog:
  name: datadog
  apiKeyExistingSecret: datadog
  env:
  - name: DD_ENABLE_GOHAI
    value: "false"
```

In my commit message I mention why gohai must be disabled when using the `datadog/dogstatsd` image.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by xvello** [comment]
Hi @sdickhoven ,

6.8.0, due in ~10 days, will ship a probe script, see https://github.com/DataDog/datadog-agent/pull/2709 and the dev build it links to.

As this version will also support directly using a http livenessprobe on port 5555 (for container runtimes that have bugs with exec probes), What would you think about having a "livenessProbe" configuration option for that? It would support the following values:

- "exec" (default): use exec probe.sh
- "http": use http probe on port 5555 as described in https://github.com/DataDog/datadog-agent/pull/2359 (I'll implement it when 6.8.0 is out)
- "disabled": remove the probe completely



/hold

**Comment by sdickhoven** [comment]
Hi @xvello 

Sure. That's a much better fix.

My PR was really just a hacky, minimal work-around since I just needed something that works.

By the way, you may also want to disable gohai by default in the dogstatsd image.

When gohai is enabled, it tries to run `df -l` which fails because BusyBox `df` doesn't recognize the `-l` (local volumes only) option. See

https://github.com/DataDog/gohai/blob/master/filesystem/filesystem_linux.go#L3

Of course, you could also include a stock Linux `df` binary in the image or patch gohai to detect BusyBox `df` and not use `df -l` (maybe do something like `| grep -E "^/dev/"` instead).

Thanks for your help.

- Simon

**Comment by sdickhoven** [comment]
Hi @xvello 
We're now running with 6.8.0-rc.1 and everything looks good. I'm going to close this PR.
Thanks.
- Simon

**Comment by xvello** [comment]
Thanks a lot for your feedback @sdickhoven !

**Comment by sdickhoven** [comment]
Very nice. Thanks for the update.
Were you able to look into gohai's use of `df -l` in the dogstatsd image?
Also, any idea when the 6.8.0 image will be officially released? So far there are only release candidates.
Regards

- Simon

**Comment by xvello** [comment]
Hi Simon,

I forwarded the gohai issue to the team maintaining it. In the meantime, it is safe to ignore this error.

6.8 will be available on the docker hub early next week, as we hit a last-minute bug in 6.8.0 that is delaying the release.

**Comment by xvello** [comment]
Hi @sdickhoven ,

6.8.1 is out!
About the gohai error, we did not catch it before, as most of our users run the dogstatsd image alongside an existing agent. In this case, `DD_ENABLE_METADATA_COLLECTION` has to be set to `false` to avoid agent and dogstatsd sending contradictory host metadata.

Is it your use case, or do you run dogstatsd by itself on some hosts?

**Comment by sdickhoven** [comment]
Hi @xvello 

Excellent. I'll try out the new image today. Thanks for the update.

Re our use case: We're just using dogstatsd as a forwarder of metrics that are sent by our HashiCorp Vault installation. So it doesn't need to report anything about the local host. Its sole purpose is to receive dogstatsd metrics from Vault and forward them on to DataDog.

- Simon

**Comment by xvello** [comment]
Okay, if you have no agent running on these hosts, you need to keep the host metadata collection enabled.

I just opened a PR to [disable gohai by default](https://github.com/DataDog/datadog-agent/pull/2815) on this image until we solve the alpine compatibility issue.

**Pull request closed without merging**
