### PR TITLE
[stable/coredns] update icon

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

In fact, the older one does not work, see https://hub.helm.sh/charts/stable/coredns.

### CODE REVIEW

**Comment by daixiang0** [comment]
same issue as #20304

**Comment by zanhsieh** [comment]
@daixiang0 
Would you mind next time when you submit PR, adding a title following the convention like:

[<stable|incubator>/<chart name>] <your title here>

For example in this PR,

[stable/coredns] update icon

This would make reviewers process it easier. Thank you for your cooperation.

**Comment by daixiang0** [comment]
@zanhsieh i forget it, done.

**Pull request merged**
