### PR TITLE
[stable/airflow] Fix typo in airflow/templates/configmap-env.yaml

### PR DESCRIPTION
**Pull request by noseka1**
Signed-off-by: Ales Nosek <ales.nosek@gmail.com>

No

#### What this PR does / why we need it:

This PR fixes a typo

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@noseka1 Please bump `Chart.yaml` to the next minor version: `7.1.6`, make sure you amend/force-push this change into your commit.

Also, you must prefix the PR/Commit name like: `[stable/airflow] XXXX`

**Comment by noseka1** [comment]
@thesuperzapper Thanks for the guidance. I made the respective changes and force-pushed the branch. Let me know if there is anything else for me to do. Thanks.

**Review by thesuperzapper — APPROVED** [review]
/ok-to-test

**Pull request merged**
