### PR TITLE
[stable/prometheus-operator] doc: README Update instructions to 5 CRDs from 4.

### PR DESCRIPTION
**Pull request by denniswebb**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by anothertobi — APPROVED** [review]

**Comment by anothertobi** [comment]
@denniswebb Unfortunately I couldn't get back to you earlier. Could you please update the version in `Chart.yaml`? Then I'll get this merged right away. Thank you 😃

**Comment by denniswebb** [comment]
@anothertobi I missed your message earlier. Just bumped it.

**Pull request merged**
