### PR TITLE
Added glusterFS support for history server

### PR DESCRIPTION
**Pull request by yuchaoran2011**

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
Please keep it open @k8s-ci-robot

**Comment by Miouge1** [comment]
This is a non-backwards compatible change, therefore incrementing the version number to a bugfix is not appropriate AFAIK.

**Comment by yuchaoran2011** [comment]
Please keep it open @k8s-ci-robot

**Comment by Miouge1** [comment]
@yuchaoran2011 AFAIK you just need a `/ lgtm`  to get this merged.

**Comment by yuchaoran2011** [comment]
@Miouge1 I just confirmed that I cannot lgtm my own PR. I need another Helm committer to help me get this in.

**Comment by okgolove** [comment]
Try to assign your PR to someone else from root [OWNERS](https://github.com/helm/charts/blob/master/OWNERS) file.

**Comment by yuchaoran2011** [comment]
@okgolove I am currently the sole owner of this chart as shown in OWNERS. This PR adds a colleague of mine to OWNERS.

**Comment by Miouge1** [comment]
OWNERS file works with the folder hierarchy, AFAIK only people in the OWNERS file at the root can get this approved and merged.

**Comment by yuchaoran2011** [comment]
@Miouge1 I know. Nobody in the root OWNERS cares to do that.

**Comment by yuchaoran2011** [comment]
Hey

**Comment by Miouge1** [comment]
You have a conflict in this PR. Maybe try to reach out to the people of approved the PR creating the conflict?

**Comment by yuchaoran2011** [comment]
Fine.

**Pull request closed without merging**
