### PR TITLE
[stable/spinnaker] clouddriver pod annotations

### LINKED ISSUE #12717: [stable/spinnaker] Enable user to add iam annotation on clouddriver pod
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Version of Helm and Kubernetes**:
helm v2.12.3
k8s v1.10.11

**Which chart**:
stable/spinnaker

**What happened**:
The clouddriver pod needs to be able to talk to aws to get an ecr authorization-token when adding ecr repos with the password-command flag. (see here for more info: https://www.spinnaker.io/setup/install/providers/docker-registry/#amazon-elastic-container-registry-ecr )
The best way to do this is to add an annotation to the clouddriver pod for kube2iam much like what has already been done with the halyard pod.

### PR DESCRIPTION
**Pull request by MarkFreebairn**
Signed-off-by: Mark Freebairn <mark_freebairn@rapid7.com>

#### What this PR does / why we need it:
Adds the option to annotate the clouddriver pod with an iam role. This is required when using ecr docker repositories as clouddriver will use the aws cli to try to get an authorization-token. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #12717

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by costimuraru** [comment]
In case we use S3 for the spinnaker backend, we also need the annotations on the front50 pod, right?
Similarly with what you did for clouddriver, could we make it work also for front50?

**Comment by MarkFreebairn** [comment]
> In case we use S3 for the spinnaker backend, we also need the annotations on the front50 pod, right?
> Similarly with what you did for clouddriver, could we make it work also for front50?

That is a good point, I am currently only using minio instead of s3 but I imagine the pod would need an annotation to talk to s3. I could add that here or it could be another PR?

Also, the pull-charts-e2e test is failing, I am not sure what the issue is, it looks like it times out installing spinnaker. I have ran this updated chart locally both with and without the annotation with no issue. Would anyone be able to help me with diagnosing this if they don't mind?

**Comment by costimuraru** [comment]
No idea why the test is failing. 
Perhaps a long shot, but maybe you could try to update the commit name and the PR name to be something like `[stable/spinnaker] ...`?

> I could add that here or it could be another PR?
Fine with me if you add the front50 change here, as the two changes are very much related.

**Comment by MarkFreebairn** [comment]
@costimuraru updated with front50 annotations - I have tested with and without the annotation and can confirm if using kube2iam, front50 cannot write to the s3 bucket without adding the iam role annotation.

**Comment by legal90** [comment]
Hi @MarkFreebairn . Thank you for what you've done in this PR!
Please have a look at latest state of #13049 - it allows to add custom settings for any Spinnaker service in a pretty generic way (not only for annotations). What do you think about it?

**Comment by mfreebairn-r7** [comment]
Hey @legal90 LGTM! I will close this PR in favour of #13049 thanks

**Pull request closed without merging**
