### PR TITLE
[incubator/logstash] Add LoadBalancerIP to values

### PR DESCRIPTION
**Pull request by budde377**
**What this PR does / why we need it**:

Allow configuration of the LoadBalancerIP on the service.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by budde377** [comment]
It seems the pods aren't being scheduled, I suspect because of the PVC not being created. I'm experiencing the same her #5287. Any pointers on what to do is highly appreciated.

**Comment by unguiculus** [comment]
Issues with the CI cluster have been fixed.

**Pull request merged**
