### PR TITLE
[Stable/chartmuseum] Allow external secrets

### PR DESCRIPTION
**Pull request by gezb**
Signed-off-by: Gerald Barker <gerald.barker@gmail.com>
#### What this PR does / why we need it:

Allows the use of a pre-existing secret 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jdolitsky** [comment]
@gezb this looks good to me. Since we are adding new features, can we bump the version of the chart to `1.9.0` instead?

**Comment by gezb** [comment]
@jdolitsky  done

**Comment by jdolitsky** [comment]
@gezb thank you!

**Pull request merged**
