### PR TITLE
Automatically mount config files

### PR DESCRIPTION
**Pull request by snomann**
**What this PR does / why we need it**:

Awesome job so far on the oauth2-proxy chart !!

This pull request provides ability to easily add configuration files to the oauth2-proxy binary. This was something that was needed because out of the box the oauth2-proxy chart only can do standard authentication against the email domain. However, if one wants to do more advanced group based authentication. This requires a service account. (hence the service account json file option in oauth2-proxy binary) This information can only be provided as a path to the json file. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

This was so that its easy to provide configuration files into the pods.

**Special notes for your reviewer**:

I can't think of anything.

### CODE REVIEW

**Comment by snomann** [comment]
Reviewing the contributors license agreement.

**Review by carrodher — CHANGES_REQUESTED** [review]
You should increment chart version (`version`) in `Chart.yaml`

**Comment by snomann** [comment]
Thanks @carrodher will get this in.

**Comment by unguiculus** [comment]
cc @compleatang

**Comment by snomann** [comment]
Closing, will reopen shortly.

**Pull request closed without merging**
