### PR TITLE
[stable/metabase] Version bump; added initContainers, extraVolumes, extraVolumeMounts.

### PR DESCRIPTION
**Pull request by dene14**
#### What this PR does / why we need it:
This PR adds support of  initContainers, extraVolumes, extraVolumeMounts passed from values.yaml.
This in particular handy to install DB drivers into metabase. Examples provided in chart's values.yaml

#### Which issue this PR fixes
I haven't opened issue for that, but basically there is no way to install plugins at all.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

/assign @pmint93

### CODE REVIEW

**Comment by dene14** [comment]
@pmint93 Could you please review/merge?

**Comment by pmint93** [comment]
Sorry but this repo is deprecating in few days, will no longer be updated.
The community is still looking forward to another repository metabase/metabase#13581

For more information, see the Helm Charts [Deprecation and Archive Notice](https://github.com/helm/charts#%EF%B8%8F-deprecation-and-archive-notice), and [Update](https://helm.sh/blog/charts-repo-deprecation/).

**Comment by dene14** [comment]
@pmint93 there are few more days before this repo moved to archive.
Could you please merge PRs in order #23956 #24024 

I really trying to avoid forking your chart and maintain it separately.

**Comment by dene14** [comment]
@pmint93 please...

**Comment by pmint93** [comment]
@dene14 currently charts in this repo should accept bug fixes only, it's not a good idea to add new feature when it very close to be archived.
However, as I see there is no other locations that the chart available except this deprecating one. So I made a quick repo to host metabase chart for community to continue working with it https://pmint93.github.io/helm-charts/

> Note: this is not official repository

You may move your contribution here https://github.com/pmint93/helm-charts

And about your changes: May we just adding option to mount existing volume to the pod plugins directory, so we manually put the drivers here instead of using empty volume and initContainer to download driver every time a pod created ?  Cause I really don't want this chart to be more complicated as it already is.

**Pull request closed without merging**
