### PR TITLE
avoid helm lint errors when adding annotations in a composable chart …

### PR DESCRIPTION
**Pull request by rawlingsj**
…values.yaml

without this we get a helm lint warning of:
`warning: destination for annotations is a table. Ignoring non-table value <nil>`

This is also consistent with other charts for example to name a few:
- jenkins https://github.com/kubernetes/charts/blob/2e26226/stable/jenkins/values.yaml#L27
- sumologic-fluentd https://github.com/kubernetes/charts/blob/master/stable/sumologic-fluentd/values.yaml#L8 
- sentry https://github.com/kubernetes/charts/blob/master/stable/sentry/values.yaml#L96

 I'm not too sure why the helm lint warning above occurs but this change seems to address it.

### CODE REVIEW

**Comment by mattfarina** [comment]
@rawlingsj What version of helm are you using where you get helm lint messages for this chart? A PR was merged recently that didn't have those issues with the chart. See https://circleci.com/gh/kubernetes/charts/1810. Trying to understand why you're having an issue.

**Comment by rawlingsj** [comment]
@mattfarina I'm using helm v2.7.2.  

I've just created a quick example project that you can clone and run:
```
helm dependency build
helm lint
```
to see the helm lint warnings I'm referring to:
```
2017/12/13 20:36:06 warning: destination for annotations is a table. Ignoring non-table value <nil>
2017/12/13 20:36:06 warning: destination for annotations is a table. Ignoring non-table value <nil>
```

**Comment by rawlingsj** [comment]
Link to the example project mentioned above https://github.com/rawlingsj/composible-chart-example

**Comment by mattfarina** [comment]
@rawlingsj Thanks for providing the example. I understand your problem because of it.

**Comment by rawlingsj** [comment]
great thanks @mattfarina!

**Pull request merged**
