### PR TITLE
Update tiller-deployment to use Octal

### PR DESCRIPTION
**Pull request by jpreese**
Noticed this when doing some investigation on another secret mounting issue. The Kubernetes API docs specify that the defaultMode value should be in Octal

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#secretvolumesource-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#secretvolumesource-v1-core

#### What this PR does / why we need it:
Updates the chart to use the numeric format as described in the API docs for secrets

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by jpreese** [comment]
Silly bot, still waiting for a review

**Comment by krancour** [comment]
I thought I approved this. Sorry.

**Comment by krancour** [comment]
@jpreese Just looked at why the tests are failing. This needs a rebase, and after you do, you'll find that v0.5.1 already exists. This needs to be v0.5.2.

**Comment by jpreese** [comment]
Updated to 0.5.2

**Comment by krancour** [comment]
@jpreese looks like commits need to be signed off on now. For some reason, I don't remember being a thing before, but I guess it is now.

**Pull request merged**
