### PR TITLE
[stable/fluent-bit] Added `input.tail.exclude_path` parameter

### PR DESCRIPTION
**Pull request by zerkms**
Signed-off-by: Ivan Kurnosov <zerkms@zerkms.com>

#### What this PR does / why we need it:

At the moment it's impossible to ignore some paths from being fed to the `tail` input, this PR simply adds another parameter

One of the real-life use cases: is to mute kibana logs (which cause problems): https://github.com/fluent/fluent-bit/issues/628#issuecomment-625644881

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by Vfialkin — APPROVED** [review]

**Comment by zerkms** [comment]
@edsiper @kfox1111 can we please merge this

**Comment by zerkms** [comment]
@kfox1111
@edsiper
@hectorj2f
@Towmeykaw

Any reason why this particular change is not reviewed/accepted? Thanks.

**Comment by zerkms** [comment]
Team, can we please accept it or somebody please give me any feedback on why it's postponed?

This is a really annoying bug.

**Pull request merged**
