### PR TITLE
[stable/sonarqube] bump version to 7.6

### PR DESCRIPTION
**Pull request by jcoeltjen**
Bump version from 7.4 to 7.6.

#### What this PR does / why we need it:

Updates the default image version and appVersion to 7.6.

#### Special notes for your reviewer:
Test was done on AKS.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by cpanato — DISMISSED** [review]
please update the readme.md as well

**Comment by jcoeltjen** [comment]
> please update the readme.md as well

Default value in readme is now the same as the real default value.

**Pull request merged**
