### PR TITLE
[stable/hackmd] Support 1.16 by upgrading postgresql

### LINKED ISSUE #20231: [stable/hackmd] 1.16 compatibility
**Describe the bug**

hackmd chart is not compatible with k8s 1.16

**Version of Helm and Kubernetes**:

```
$ k version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Which chart**:

`stable/hackmd`

**What happened**:
```
$ helm install hackmd stable/hackmd
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**What you expected to happen**:
Chart installs properly

**How to reproduce it** (as minimally and precisely as possible):

(see above)

**Anything else we need to know**:

I believe this is due to the dependency on the PostgreSQL chart, which is very out of date (`8.1.4` is latest, currently using `0.8.4`)

With ingress enabled, I also see the message
```
error validating data: ValidationError(Ingress.spec): unknown field "selector" in io.k8s.api.networking.v1beta1.IngressSpec
```

### PR DESCRIPTION
**Pull request by rbren**
#### What this PR does / why we need it:
This upgrades the postgres dependency for HackMD in order to support 1.16

#### Which issue this PR fixes
  - fixes #20231 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rbren** [comment]
This is still valid - anything else I need to do?

**Comment by ekeih** [comment]
This is still valid.
@mattfarina you are currently assigned to this PR, is there anything we can do to get this merged?

**Comment by mattfarina** [comment]
@rbren @ekeih can you rebase this off of master? It's trying to use an old version of the Helm client from config in your current branch.

We do need the tests passing before the automation will let us merge.

**Comment by rbren** [comment]
Rebased - hopefully it passes now

**Comment by mattfarina** [comment]
@yuanying  can you please review this PR?

**Review by yuanying — APPROVED** [review]
LGTM

**Pull request merged**
