### PR TITLE
[stable/ prometheus-operator/kube-state-metrics/prometheus-node-expor…

### PR DESCRIPTION
**Pull request by pmontanari**
…ter] Misc changes around imagePullSecrets

kube-state-metrics: added ability to specify imagepullsecrets to serviceacccount @fiunchinho
prometheus-node-exporter: fixed imagepullsecrets not being applied because of wrong variable used - 
prometheus-operator: bumped to new sub-charts - @gianrubio 
@
Signed-off-by: Patrick Montanari <patrick.montanari@gmail.com>

### CODE REVIEW

**Comment by pmontanari** [comment]
Hi @gianrubio, @fiunchinho,

I closed my previous PR because I did too many wrong operations with GitHub. Could you please review this PR  ?

Thanks
Patrick

**Comment by vsliouniaev** [comment]
@pmontanari Do you think it's a good idea to put imagePullSecrets under global? The stable/prometheus-operator chart does this, but not sure it's a completely good idea, so deferring to you.

I'm also pretty sure the build will fail because the lock file in stable/prometheus-operator 
will be incorrect

**Comment by pmontanari** [comment]
> @pmontanari Do you think it's a good idea to put imagePullSecrets under global? The stable/prometheus-operator chart does this, but not sure it's a completely good idea, so deferring to you.
> 
> I'm also pretty sure the build will fail because the lock file in stable/prometheus-operator
> will be incorrect

Actually, I chose this option  because of prometheus-operator... But in general, if a helm chart has several Service Accounts, having it in global is easier to apply to all other Service accounts.

**Comment by vsliouniaev** [comment]
What I mean is, with the current setup I would have to set image pull secrets in 2 locations in the prometheus-operator chart:

global.imagePullSecrets=...
kube-state-metrics.imagePullSecrets...


https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#global-chart-values

**Comment by pmontanari** [comment]
Correct, So can I create the global section ?

**Comment by gianrubio** [comment]
@pmontanari please fix CI

**Comment by pmontanari** [comment]
Ok, I cannot update 3 linked charts simultaneously...
I'll do it in 3 steps then

**Pull request closed without merging**
