### PR TITLE
[incubator/gogs] Update OWNERS

### PR DESCRIPTION
**Pull request by obeyler**
https://github.com/helm/charts/issues/13867#issuecomment-492670492

### CODE REVIEW

**Comment by maorfr** [comment]
hey @obeyler,

thanks for signing up for this!
i would be happy to see a reference to some work you did around this chart if that is ok with you :)

**Comment by obeyler** [comment]
@maorfr in fact to my part I'm already the owner of this chart :-)
currently I'm working hard on this helm chart to add serviceAccount/Podsecurity/role/etc..
(see https://github.com/orange-cloudfoundry/charts/tree/feature-gogs/incubator/gogs)
I just add my collegue pierre to help me to maintain it

**Comment by maorfr** [comment]
/lgtm

Sorry, was not attentive. Thanks!!

**Pull request merged**
