### PR TITLE
[stable/jenkins] Update to match actual defaults in value.yaml

### PR DESCRIPTION
**Pull request by admoriarty**
Signed-off-by: Aidan Moriarty <aidan.moriarty@gmail.com>

#### What this PR does / why we need it:
Just a small typo fix for the README

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by admoriarty** [comment]
Does the release pipeline not handle patch version bumps by itself? I assumed it did so didn't version bump such a trivial change manually.

**Comment by maorfr** [comment]
it doesn't :)
would you mind submitting the same PR to incubator/jenkins when #12890 is complete?

**Comment by admoriarty** [comment]
If I remember to, sure :D

**Comment by maorfr** [comment]
/assign
/ok-to-test

I will remind you :)

**Comment by maorfr** [comment]
Thanks for your contribution!

**Pull request merged**
