### PR TITLE
[stable/redis-ha] - Fix authentication with customConfig

### PR DESCRIPTION
**Pull request by Lord-Y**
Signed-off-by: Lord-Y <Lord-Y@users.noreply.github.com>

Fix authentication with customConfig

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Lord-Y** [comment]
@ssalaues @DandyDeveloper Can you guys review my PR? :-)

**Comment by DandyDeveloper** [comment]
@Lord-Y Yoi should check the new official chart @ https://github.com/dandydeveloper/charts

This may already have this fix present.

**Comment by Lord-Y** [comment]
> @Lord-Y Yoi should check the new official chart @ https://github.com/dandydeveloper/charts
> 
> This may already have this fix present.

In fact the issue is the same in the other chart.

**Comment by Lord-Y** [comment]
@DandyDeveloper any news for the merge?

**Comment by DandyDeveloper** [comment]
@Lord-Y Make a new PR in the latest please, this chart has be superseeded by that

**Comment by Lord-Y** [comment]
> @Lord-Y Make a new PR in the latest please, this chart has be superseeded by that

Thx for the reply @DandyDeveloper . I made the new one on the new repo.

**Pull request closed without merging**
