### PR TITLE
[stable/prometheus-blackbox-exporter] add "allowIcmp" setting

### PR DESCRIPTION
**Pull request by alice-sawatzky**
Signed-off-by: Alice Sawatzky <alice.sawatzky@farmersedge.ca>
@desaintmartin @gianrubio @rsotnychenko

#### What this PR does / why we need it:

Adds an option `allowIcmp` to `prometheus-blcakbox-exporter`, which if enabled adds the `CAP_NET_RAW` capability to the blackbox container, which is needed for ICMP probes to work.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by alice-sawatzky** [comment]
I just managed to run some ICMP probes without this capability. Not sure if this is unique to my cluster config or not. https://github.com/prometheus/blackbox_exporter#permissions says this is needed so, probably still worth adding?

**Comment by desaintmartin** [comment]
/assign
Thanks!
I may review it only tomorrow.

**Comment by alice-sawatzky** [comment]
I had to make the container run as root for ICMP to work. I've updated the README to mention this

**Comment by desaintmartin** [comment]
I am not sure if it is indeed needed on all clusters, but if documentation states it, it might be better to add it so that it does not break when upgrading cluster or prometheus-blackbox-exporter.

Could you add a ci/icmp-values.yaml testing this configuration?

**Comment by alice-sawatzky** [comment]
added the test!

I don't know why ICMP initially worked for me without this patch, but shortly after it spontaneously stopped working and needed these changes to work. so, i agree that this seems like a good idea to have

**Comment by desaintmartin** [comment]
Thanks!
/lgtm

**Pull request merged**
