### PR TITLE
[stable/postgresql]Set resource policy only when value is set

### PR DESCRIPTION
**Pull request by Miouge1**
**What this PR does / why we need it**:
Do not set `"helm.sh/resource-policy"` annotation if `.Values.persistence.resourcePolicy` is unset.

**Special notes for your reviewer**:
Related to #7283

### CODE REVIEW

**Comment by cpanato** [comment]
@Miouge1 what is the side effects or implications if this is set as "" ?

**Comment by Miouge1** [comment]
I've run into problems with chart version `0.18.0` and helm v2.8.2: 

```
helm install --name myrelease mychart ...
helm delete --purge myrelease ...
helm install myrelease ...
Error: release myrelease failed: persistentvolumeclaims "myrelease-postgresql" already exists
```

`mychart` includes `stable/postgresql` as a requirement.

This was not a problem before the resource policy annotation.

It may be a Helm bug, but I figured it doesn't cost to put the annotation only when necessary. It is also better for backwards compatibility.

**Comment by xaralis** [comment]
@cpanato Problem is that currently, there is no way to make postgres chart delete it's PVC automatically. It always acts as `keep` resource policy. It might be Helm issue, but since the fix is simple, we should go with it.

**Pull request closed without merging**
