### PR TITLE
suport wildcard certificates

### PR DESCRIPTION
**Pull request by attiasr**
quote is required to support wildcard certificates

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
@attiasr thanks for this PR
you need to bump the chart version and sign the [DCO](https://github.com/helm/charts/pull/7429/checks?check_run_id=14684787) - https://www.helm.sh/blog/helm-dco/index.html

**Comment by attiasr** [comment]
@cpanato bumped and signed off, thanks!

**Pull request merged**
