### PR TITLE
[stable/metrics-server] bump metrics-server version

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### What this PR does / why we need it:

Bump image version to latest at 0.3.3

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by PierluigiLenociAkelius** [comment]
I'm ready also to create a PR for whitespace formatting and to remove trailing blank lines as suggested by @bryantbiggs 
https://github.com/PierluigiLenociAkelius/charts/commit/a8bbdcbf2d9b29ba049dd11a369453669429dd66

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus as expected the build failed.

**Comment by olemarkus** [comment]
At least it seems given that it is the image version that is the problem. It is unclear to me why though. when I install/delete the chart from this PR it works just fine. So does linting the chart.

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus Seems that this is not working. I create this one to fix a bit the chart https://github.com/helm/charts/pull/16685

**Comment by PierluigiLenociAkelius** [comment]
@bryantbiggs the metrics-server bump version don't work sadly.

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus probably this is the reason: https://github.com/kubernetes-incubator/metrics-server/issues/278#issuecomment-515370587

If I use this options on k8s > v1.13 with kubelet (working without webhook authentication) works.

**Comment by olemarkus** [comment]
So the reason this is failing is that we have a test that looks like this:
`wget -qO- https://doltish-dachshund-metrics-server:443/version | grep -F 0.3.3`
And the version endpoint actually returns this:
```
{
  "major": "",
  "minor": "",
  "gitVersion": "v0.3.2-17+822102a6ca25b0-dirty",
  "gitCommit": "822102a6ca25b03318db397f1ceeec7b46f546a5",
  "gitTreeState": "dirty",
  "buildDate": "2019-05-02T18:40:38Z",
  "goVersion": "go1.10.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
This test in its current state is therefor completely useless and can be removed (or replaced by something more clever)

**Comment by PierluigiLenociAkelius** [comment]
The test could be improved but the answer is anyway wrong. So a fix is needed in both sides.

**Comment by PierluigiLenociAkelius** [comment]
There is a issue on metrics-server repo opened since june.
https://github.com/kubernetes-incubator/metrics-server/issues/272

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus the issue with the version is fixed, could you please approve again?

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus sorry... I forgot to sign the commit :( my bad.

**Comment by PierluigiLenociAkelius** [comment]
@olemarkus thank you! We finally did it! 🍾

**Pull request merged**
