### PR TITLE
[stable/postgresql] README.md - fix minor typos

### PR DESCRIPTION
**Pull request by cabiad**
#### What this PR does / why we need it:

Fix a couple of minor typos in README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign your existing commits](https://github.com/apps/dco), you can find custom instructions in the “Details” link from the below DCO check, also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by cabiad** [comment]
DCO signed.

Incremented chart semver as well, though I'm a bit confused about this, given that my changes only affect the README and not the chart itself.

**Comment by carrodher** [comment]
Yes, we should bump the version for every single change. Now LGTM, but it seems the merging test is failing because of some conflicts, can you review it?

**Comment by carrodher** [comment]
Tests failed because the chart version not ok it needs a version bump.

**Pull request merged**
