### PR TITLE
[stable/atlantis] Use newer ingress API to be compatible with Kubernetes 1.16

### PR DESCRIPTION
**Pull request by estahn**
#### What this PR does / why we need it:

Kubernetes 1.16 deprecates various APIs and therefore manifests require updates.
This PR updates the ingress API version and is backwards compatible so it can still be used with older Kubernetes versions.

#### Which issue this PR fixes

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by joeruello — APPROVED** [review]

**Review by arihantsurana — APPROVED** [review]

**Comment by lkysow** [comment]
@estahn thanks for the PR! I think the checks aren't passing though.

**Comment by estahn** [comment]
> @estahn thanks for the PR! I think the checks aren't passing though.

@lkysow The commits are signed-off yet the `dco-labeler` is not showing it. Any idea what is wrong?

**Comment by lkysow** [comment]
Maybe it's broken. If you squash your commits into one and force-push it should trigger another build.

**Comment by estahn** [comment]
> Maybe it's broken. If you squash your commits into one and force-push it should trigger another build.

Yeah, that seems to have done it 👍

**Pull request merged**
