### PR TITLE
Enabled NodePort for zipkin, grafana and prometheus.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes/charts/issues/1369

/cc @lachie83

### CODE REVIEW

**Comment by gyliu513** [comment]
@lachie83 ping for review

**Comment by gyliu513** [comment]
@lachie83 rebased, can you help check?

**Review by rshriram — APPROVED** [review]
Thanks @gyliu513 . This is very helpful. A lot of folks are actually using the helm charts.
Would you also mind sending the same fixes to github.com/istio/istio repo for zipkin/grafana/prometheus and an accompanying PR to github.com/istio/istio.github.io (https://github.com/istio/istio.github.io/blob/master/_docs/tasks/installing-istio.md#enabling-metrics-collection) where we tell users to query the NodePort instead of using kube proxy?

**Comment by gyliu513** [comment]
@rshriram sure, will open a PR for istio later.

**Comment by lachie83** [comment]
Please bump the chart version then we're GTG

**Comment by gyliu513** [comment]
Can you please show more detail for how to bump the char version?

I found that the current version is [0.1.6-chart1](https://github.com/kubernetes/charts/blob/master/incubator/istio/Chart.yaml#L4), which version do I need to bump it to?

Also what is the policy of bumping the versions here for istio chart? Thanks @lachie83

**Comment by lachie83** [comment]
please bump chart1 to the next chartx increment. Any structural changes to the chart constitute a chart version bump

**Comment by gyliu513** [comment]
@lachie83 done

**Comment by gyliu513** [comment]
ping @lachie83 , can we get this merged?

**Comment by gyliu513** [comment]
ping @lachie83 , any update?

**Comment by lachie83** [comment]
LGTM

**Pull request merged**
