### PR TITLE
[stable/opa] Fixing the liveliness and readiness probe by moving it from container mgmt to container opa

### PR DESCRIPTION
**Pull request by CarloColumna**
… mgmt to container opa.

Signed-off-by: Carlo Columna <carlocolumna@gmail.com>

#### What this PR does / why we need it:
This PR moves the liveliness and readiness probe checks from the container mgmt to container opa in the deployment.yaml. The probes located in the mgmt container check the endpoint Liveness/Readiness: http-get https://:443/ but this endpoint actually points to the OPA --addr=0.0.0.0:443. There might be a special reason for this but not sure so raising a PR.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by timothyhinrichs** [comment]
Let's squash those commits into 1.  The change and the version should be atomic

**Comment by timothyhinrichs** [comment]
Also, there's another in-flight PR bumping to 1.5.1.  Whichever one goes in first, the other will need to change

**Comment by CarloColumna** [comment]
Hi Tim! Thanks for looking into it. I squashed the commits into 1 now. I will update the chart version if the other PR gets through first.

**Comment by timothyhinrichs** [comment]
Another 1.5.1 just merged.  Presumably that'll cause conflicts here.  But once you get those resolved, we'll merge it.

**Comment by CarloColumna** [comment]
Merged the updates and bumped the chart version. Thanks!

**Comment by CarloColumna** [comment]
Thanks Tim!

**Pull request merged**
