### PR TITLE
rabbitmq-ha restart after total node failure

### PR DESCRIPTION
**Pull request by bartlett-ops**
I came across a bug in the rabbitmq-ha chart where it fails to restart after total node failure.
A similar issue is described by someone else [here](https://groups.google.com/forum/#!topic/rabbitmq-users/1KHZBXHoMQk)

The tl;dr is that the rabbitmq statefulset pods will fail their liveness probe if they cannot communicate with each other. However the default statefulset behaviour is to start one pod at a time. Therefore kubernetes get stuck waiting indefinitely for the first pod to start.

The fix is to utilise parallel statefulset scaling as described [here](https://github.com/kubernetes/kubernetes/pull/44899)

@etiennetremel 

Signed-off-by: Tom Bartlett <thomas.bartlett.1992@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by steven-sheehy** [comment]
Setting podManagementPolicy=Parallel would break upgrades as this is not an editable field in the spec. Also, Parallel will cause downtime for clients of RabbitMQ during upgrades, which is not acceptable for most users. Having all RabbitMQ pods down simultaneously is a rare occurrence and can be minimized by setting affinity rules to enforce scheduling on different nodes. I do wish RabbitMQ had a force_boot configuration option that would allow the user to choose availability over data integrity.

As such, I do not recommend this PR be merged. I added the ability to modify podManagementPolicy it just for this case in PR #8767. If you need this functionality, you can safely set it Parallel in your custom values yaml during helm install.

**Comment by sstarcher** [comment]
@steven-sheehy We have a usecase where over the weekend we shutdown the rabbitmq cluster.  With the new changes to the chart for the health probe how do you suggest we recover from this situation?  We agree that setting the podManagementPolicy to Parallel is not a good idea.

**Comment by sstarcher** [comment]
@steven-sheehy so ya as you mention the issue is data integrity.  Prior to the changes in the probe we would have not to be concerned with data integrity as the nodes would come backup without a force boot?

**Comment by steven-sheehy** [comment]
Please open an issue so we don't keep commenting on a closed PR. Even with the previous probe of `rabbitmqctl status` you would still see the 'waiting for mnesia tables' error indefinitely. That's just how rabbitmq works; it doesn't like all nodes to be down. The probe was changed to be more accurate and actually detect if rabbitmq is truly up and processing and restart if it isn't.

**Comment by sstarcher** [comment]
@steven-sheehy yes, but the probe would go healthy and the second and third nodes would come up and the cluster would recover.  I'll open a new issue.

**Pull request closed without merging**
