### PR TITLE
fix reference in readme

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fix docs so they match what is in use in values etc

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/charts/6300)

### CODE REVIEW

**Comment by timstoop** [comment]
This is fine, however, a lot of work is being done on the elasticsearch charts. You may want to check #elk-charts on the Kubernetes Slack if you'd like to join in on it. Your work might be completely overwritten in the next few weeks.

**Comment by davidkarlsen** [comment]
There was a larger change a week ago - but how it is now the README is not in sync with the actual implementation - if it changes in future - no problem - all I want is the docs to be coherent with the values. I've already joined the slack for the elk-chart.

**Comment by timstoop** [comment]
@simonswine @icereval for your consideration, seems a good thing to keep the docs up-to-date

**Pull request merged**
