### PR TITLE
stable/traefik: Add the acme http challenge entrypoint to the values

### PR DESCRIPTION
**Pull request by szeber**
In the helm config the acme http challenge endpoint is hardcoded to be `http`. This may not work if you are behind Cloudflare for example, as Cloudflare handles the http->https redirection itself, so the http endpoint will never receive any traffic.

This change allows overriding that endpoint to be the https endpoint (or any other endpoint for that matter).

### CODE REVIEW

**Comment by zanhsieh** [comment]
@szeber 
Would you bump chart version to latest please?

**Comment by szeber** [comment]
@zanhsieh updated

**Comment by szeber** [comment]
@zanhsieh @emilevauge will this get looked at at any point or should i just close the PR?

**Comment by zanhsieh** [comment]
@emilevauge
@dtomcej
@timoreimann
@vdemeester
@nmengin
@mmatur
@ldez
@Juliens
@jbdoumenjou
@geraldcroes
@SantoDE
@errm
Would you guys LGTM this PR please?

@szeber 
Another version bump please. Thank you and sorry for waiting.

**Pull request merged**
