### PR TITLE
[stable/prometheus-operator] - Fix err msg "found duplicate series for the match group"

### PR DESCRIPTION
**Pull request by Lord-Y**
Signed-off-by: Lord-Y <Lord-Y@users.noreply.github.com>

#### What this PR does / why we need it:

Fix err msg found duplicate series for the match group for KubePodNotReady alert. Here is my stack trace:
`
Error executing query: found duplicate series for the match group {namespace="default", pod="nginx-dbddb74b8-vks5q"} on the right hand-side of the operation: [{__name__="kube_pod_owner", endpoint="http", instance="X.X.X.X:8080", job="kube-state-metrics", namespace="default", owner_is_controller="true", owner_kind="ReplicaSet", owner_name="nginx-dbddb74b8", pod="nginx-dbddb74b8-vks5q", service="prometheus-operator-kube-state-metrics"}, {__name__="kube_pod_owner", app_kubernetes_io_instance="prometheus-operator", app_kubernetes_io_managed_by="Tiller", app_kubernetes_io_name="kube-state-metrics", helm_sh_chart="kube-state-metrics-2.4.1", instance="X.X.X.X:8080", job="kubernetes-service-endpoints", kubernetes_name="prometheus-operator-kube-state-metrics", kubernetes_namespace="prometheus-operator", kubernetes_node="XXXXXX-b6b5a477-zq60", namespace="default", owner_is_controller="true", owner_kind="ReplicaSet", owner_name="nginx-dbddb74b8", pod="nginx-dbddb74b8-vks5q"}];many-to-many matching not allowed: matching labels must be unique on one side
`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Lord-Y** [comment]
@bismarck @gianrubio Hello guys, can you have a look on my PR :)

**Comment by zanhsieh** [comment]
@Lord-Y 
Would you mind to resolve chart conflict please? Thank you.
stable/prometheus-operator/Chart.yaml

**Comment by Lord-Y** [comment]
@zanhsieh I fixed it

**Comment by Lord-Y** [comment]
@bismarck @gianrubio Can you guys approve the merge?

**Comment by vsliouniaev** [comment]
@Lord-Y It is not the goal of this chart to maintain alerts and dashboards - these are sourced from upstream repositories and synced using python scripts. Please submit your changes there.

/hold

**Comment by bismarck** [comment]
@Lord-Y Here's the upstream repository for alerts and dashboards: https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by eperdeme** [comment]
@Lord-Y DId you find a way to pull this update through to the helm chart? Hitting the same issue here.

**Comment by Lord-Y** [comment]
@eperdeme I updated the source repository. I must be merged later for next release of prometheus-operator. Maybe @vsliouniaev can tell us more about when.

**Comment by Mattes83** [comment]
@Lord-Y @eperdeme  There seems to be some additional work which needs to be done as documented here: https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack

I already tried to follow the instructions, but I am not able to perform the import

**Pull request closed without merging**
