### PR TITLE
[stable/ambassador]

### PR DESCRIPTION
**Pull request by iNoahNothing**
#### What this PR does / why we need it:
Revive this chart so people do not see a deprecated chart any longer

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Flydiverny** [comment]
🤔 bringing the chart back here?

**Comment by nbkrause** [comment]
@Flydiverny We are cloning it here. hub.helm.sh is still linking to this repository so we would like to make sure to keep this chart alive so anyone coming from there can still find value in this chart instead of seeing a big deprecated warning.

The long term solution is to figure out how to get hub.helm.sh to point to https://github.com/datawire/ambassador-chart but, for the time being, reviving the chart here until the repo is deprecated will be an acceptable solution

**Comment by Flydiverny** [comment]
@nbkrause Just make a PR to the hub repo adding the getambassador.io registry like this pr: https://github.com/helm/hub/pull/337/ also check the comment suggestion about artifacthub :)

**Comment by nbkrause** [comment]
@Flydiverny Thanks for the suggestion. I submitted a PR there since that is probably going to be easier than wrangling CI here will be

**Pull request closed without merging**
