### PR TITLE
[stable/docker-registry] Allow extra volume mounts in registry container

### PR DESCRIPTION
**Pull request by bvis**
Signed-off-by: Basilio Vera <basilio.vera@softonic.com>

#### What this PR does / why we need it:
Currently there's no way to configure Cloudfront as middleware in Docker Registry. The problem is the configuration needs [a file that contains the private key](https://docs.docker.com/registry/configuration/#example-middleware-configuration) and there's no option to mount it in the current chart.

I've added extra values to the deployment to do it.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by bvis** [comment]
Hi, is it anything we should do to ensure this is merged?

**Comment by zanhsieh** [comment]
/assign @rendhalver
@rendhalver @jpds 
Please lgtm this.

**Comment by bvis** [comment]
Hi again, could you review this, please?

**Comment by bvis** [comment]
Hi again, I'd like to know if there's something I could do to ensure this is properly reviewed and merged or discarded.

**Comment by bvis** [comment]
Ok, I’ll abandone this, it seems there’s no way to get this reviewed. I feel completely ignored and that’s not good.

Have a nice day

**Pull request merged**
