### PR TITLE
nginx-ingress controller: make runAsUser tunable

### PR DESCRIPTION
**Pull request by flavio**
#### What this PR does / why we need it:

Allow user to specify a different UID for the nginx-ingress-controller.
This is required when using images that are not based on debian, hence the nginx user has a different value.

By default the debian UID is going to be used. Regular users are not going to be affected by this change.

#### Which issue this PR fixes

No issue open about that.

#### Special notes for your reviewer:

~Should I version bump the helm chart?~ DONE

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@flavio please bump the chart version

**Comment by flavio** [comment]
Done, I'll squash the two commits together once everything looks good to you

**Pull request merged**
