### PR TITLE
[stable/fluentd] Remove duplicate pvc resource (#19131)

### LINKED ISSUE #19131: [stable/fluentd] Duplicate PVC resource
**Describe the bug**
When autoscaling is disabled and persistence is enable, the chart fails to install because there is a duplicate PVC template in the chart (pvc.yaml and pvc.yml)

**Version of Helm and Kubernetes**:
Kubernetes: 1.14.8
Helm: v2.13.0

**Which chart**:
stable/fluentd

**What happened**:
I tried to install the fluentd chart with autoscaling disabled and persistence enabled

**What you expected to happen**:
The chart to be installed successfully

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/fluentd --set persistence.enabled=true

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Uvedale**
#### What this PR does / why we need it:
This fixes a bug that prevents the installation of the chart with persistence enabled and autoscaling disabled.

#### Which issue this PR fixes
- fixes #19131 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Miouge1** [comment]
Looks good, @Uvedale can you rebase on latest master?

**Comment by Uvedale** [comment]
@Miouge1 done

**Pull request merged**
