### PR TITLE
Check the health endpoint to see if Vault has been unsealed

### PR DESCRIPTION
**Pull request by dmyerscough**
Perform a HTTP get of the `/v1/sys/health` endpoint to determine if Vault is available. Vault's health status codes:-

* 200 if initialized, unsealed, and active
* 429 if unsealed and standby
* 472 if data recovery mode replication secondary and active
* 501 if not initialized
* 503 if sealed

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @jpds

**Comment by nazarewk** [comment]
@dmyerscough Could you resolve the Chart conflict?

@unguiculus what is the status of this PR? I am very interested in merging this ASAP.

**Comment by unguiculus** [comment]
ping @jpds

**Comment by dmyerscough** [comment]
@nazarewk conflict resolved.

**Comment by dmyerscough** [comment]
Just curious, how come this PR has taken almost 1 months for a simple change?

**Comment by timstoop** [comment]
Lots of people working on lots of things. I've recently joined and I'm now working through the backlog to at least make it easier on the rest of the team to decide on accepting the simple patches. But yeah, few volunteers on Open Source projects in general. And I guess Charts are not really thát sexy, so a lot of people prefer to join other projects ;-) We're working on improving it, though!

**Comment by unguiculus** [comment]
@dmyerscough We usually give the chart's maintainer a chance to jump in and review, which he unfortunately not did. I'm merging this now.

**Pull request merged**
