### PR TITLE
deprecating sugarcrm

### PR DESCRIPTION
**Pull request by vtuson**
**What this PR does / why we need it**:
deprecating sugarcrm chart as it is no longer maintained

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by tompizmor — COMMENTED** [review]
/lgtm

**Comment by unguiculus** [comment]
Deprecating would also have required notes in readme and NOTES.txt.

**Comment by vtuson** [comment]
@unguiculus thanks for pointing that out, I have created a new PR to include this notifications: #5325

**Pull request merged**
