### PR TITLE
[stable/prometheus-operator] Upgrade grafana chart to version 3.5.13

### PR DESCRIPTION
**Pull request by minhdanh**
#### What this PR does / why we need it:

The current grafana chart is rather old. This PR upgrades grafana chart to latest version 3.5.13, that includes various fixes.
It also updates other dependencies like kube-state-metrics and prometheus-node-exporter to newer minor versions.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by minhdanh** [comment]
@gianrubio Please tell if anything else need to be done for this.

**Comment by mforutan-flexera** [comment]
when can we expect this to be merged?

**Comment by davidkarlsen** [comment]
@minhdanh Can you fix the merge-conflict?

**Comment by minhdanh** [comment]
@davidkarlsen Done

**Comment by minhdanh** [comment]
I mixed up the commits a bit but I've just fixed that. Things should be clean now.

**Comment by vsliouniaev** [comment]
Hey @minhdanh, I can get this merged if you update the PR with the new chart version

**Comment by minhdanh** [comment]
@vsliouniaev Done

**Pull request merged**
