### PR TITLE
[stable/mongodb-replica-set]securityContext bug

### PR DESCRIPTION
**Pull request by cyucelen**
Signed-off-by: Cagatay Yucelen cagatayyucelen@gmail.com

#### What this PR does / why we need it:
This PR fixes some template bug. securityContext toYaml converts Uint64 to string, this bug occurs when we use `--set` flag with helm install for example:
```
helm upgrade overhauler-mongodb-replicaset stable/mongodb-replicaset -i --tiller-namespace qa --namespace qa --set persistenceVolume.enabled=true,securityContext.fsGroup=0,securityContext.runAsUser=0,persistenceVolume.storageClass="generic" --wait --timeout 3600 --force
Error: release overhauler-mongodb-replicaset failed: StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.SecurityContext: v1.PodSecurityContext.FSGroup: readUint64: unexpected character: �, error found in #10 byte of ...|fsGroup":"0","runAsN|..., bigger context ...|name":"datadir"}]}],"securityContext":{"fsGroup":"0","runAsNonRoot":true,"runAsUser":"0"},"terminati|...
```
This bug also leads to unable to use this chart with istio sidecar.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by steven-sheehy** [comment]
/assign
It looks like the main purpose of this PR is to disable securityContext by setting securityContext.enabled because it breaks for you when using --set due to a Helm bug. You can already do this via --set "securityContext=null", so not sure the value of this.

**Comment by unguiculus** [comment]
`toYaml` is used in many places. We would have to change the whole chart to keep it consistent. So, I'm against this change. I'd suggest you file an issue with Helm. Can't you use a values file instead?

**Comment by cyucelen** [comment]
@steven-sheehy thanks for the advice it works as charm, but everybody is suffering from this issue with different charts, somehow this securityContext thing has issues with istio proxy. The common solution that works with other charts is setting the fsGroup and runAsUser to 0 value, but in this chart there is a bug about this.

@unguiculus it works when i use --set with other charts, so there is an inconsistency in here and it is affecting the dev experience.

thanks.

**Comment by unguiculus** [comment]
The latest commit refers to Cassandra and should not be in this PR.

**Comment by cyucelen** [comment]
@unguiculus i just reverted that commit

**Pull request merged**
