### PR TITLE
Remove chancez as owner/maintainer to etcd-operator/nginx-ingress

### PR DESCRIPTION
**Pull request by chancez**
I don't use either of these charts anymore and don't keep up with the
upstream projects since I don't use them any longer. Removing myself as
there are other maintainers.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@chancez you need to sign the DCO and bump the chart version of the nginx

**Comment by chancez** [comment]
Huh, I guess that's true with CI. I guess I need to update the DCO with my redhat email.

**Comment by cpanato** [comment]
@chancez you need to sign the DCO and bump the chart version of both. sad that are you leaving :(

**Comment by chancez** [comment]
@cpanato should be ready

**Review by cpanato — APPROVED** [review]

**Pull request merged**
