### PR TITLE
[stable/traefik] Add extraVolumes and extraVolumeMounts values

### PR DESCRIPTION
**Pull request by serbrech**
Signed-off-by: Stéphane Erbrech <stephane.erbrech@gmail.com>

Please review : @krancour @emilevauge @dtomcej @ldez

#### What this PR does / why we need it:
To make files available to traefik (like certificates, but avoiding secrets for security reasons), I want to be able to define arbitrary volumes and volume mounts for the `traefik` pod and container

**Use Case** : 
in Azure, I store all my secrets and certificates in Azure Keyvault. Today, the most secure and recommended way to use Keyvault data is to fetch them from Keyvault using [kubernetes-keyvault-flexvol](https://github.com/Azure/kubernetes-keyvault-flexvol). 
This allows me to mount the certificates and secrets in a tpmfs flexvolume into a pod.
nginx-ingress provides `extraVolumes` and `extraVolumeMounts` to support this : 

https://github.com/helm/charts/blob/f0880a7be03d720512b19182ace545a6c5878b5d/stable/nginx-ingress/values.yaml#L221-L229

The content is an arbitrary yaml that describes a volume and volume mount and is copied as is into the deployment : 

https://github.com/helm/charts/blob/f0880a7be03d720512b19182ace545a6c5878b5d/stable/nginx-ingress/templates/controller-deployment.yaml#L159-L161

This seems to be a low-risk/high-benefit addition to the chart

#### Which issue this PR fixes
  - implements #9440 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by serbrech** [comment]
@mmatur Is anything missing to merge this?
Or is it a feature that is not interesting?

**Comment by serbrech** [comment]
review/merge please? @dtomcej @mmatur @stealthybox :)

**Comment by serbrech** [comment]
Ready for merge after bumping the version

**Comment by Josh-West-Bose** [comment]
It's a shame this PR was never merged, as it's quite simple and incredibly valuable for the reasons mentioned in the description.

**Comment by maorfr** [comment]
/assign

if we get this PR back in shape, we can merge it :)

**Comment by EdanBrooke** [comment]
Did this ever get merged? I see it's been closed.
I'm trying to get LetsEncrypt working correctly with our Traefik installation and believe a volume mount is the way to go, but I can't find any documentation on how to mount a volume via the Helm chart values.

**Comment by serbrech** [comment]
@EdanBrooke Sorry, I closed it because I'm not going to spend more time trying to keep it up to date. I've had to rebase or bump version multiple times without anyone looking into merging it for weeks, only to be asked to bump the version again.
Feel free to open your own PR with the same changes.

**Comment by maorfr** [comment]
@serbrech i am sorry for this experience. i promise that if you bump one last time i will merge it! :)
feel free to tag me on any future PRs you may create.

thanks for contributing!

**Comment by EdanBrooke** [comment]
It'd be good to see this merged in :)

**Pull request closed without merging**
