### PR TITLE
[stable/prometheus-rabbitmq-exporter] ServiceMonitor Port Bugfix

### PR DESCRIPTION
**Pull request by jonnydford**
The service monitor currently tries to scrape the publish port, which isn't available on the Service. 
I've changed the endpoint port for the service monitor to scrape from the services' 'rabbitmq-exporter' port.

I've also changed the name to servicemonitor.yaml to match other Helm charts.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by RaymondArias** [comment]
I wonder if all the ports should just be called `rabbitmq-exporter` to avoid confusion?

**Comment by amartorelli** [comment]
Is it possible to get this merged? It's pretty useful.

**Review by RaymondArias — APPROVED** [review]

**Comment by geobos23** [comment]
This PR actually broke the exporter scraping, because it incorrectly changes the portname in servicemonitor from `publish` to `rabbitmq-exporter` while leaving the port name in service definition to `publish`.

Correct fix was applied by PR #16134 (merged before this one on Aug 13 -> version bump to 0.5.2) which changes the servicemonitor portname from `rabbitmq-exporter` to `publish` correctly alligning the 2 names defined in service and servicemonitor to `publish` value.
---------------
### Working - 0.5.2  (PR #16134)
- service definition
```
$ kubectl describe svc kube-stack-prometheus-rabbitmq-exporter
Name:              kube-stack-prometheus-rabbitmq-exporter
Namespace:         default
Labels:            app=prometheus-rabbitmq-exporter
                   chart=prometheus-rabbitmq-exporter-0.5.2
                   heritage=Tiller
                   release=kube-stack
Annotations:       <none>
Selector:          app=prometheus-rabbitmq-exporter,release=kube-stack
Type:              ClusterIP
IP:                10.160.1.8
Port:              publish  9419/TCP
TargetPort:        publish/TCP
Endpoints:         10.144.3.40:9419
Session Affinity:  None
Events:            <none>
```
- servicemonitor definition
```
$ kubectl describe servicemonitors.monitoring.coreos.com kube-stack-prometheus-rabbitmq-exporter
Name:         kube-stack-prometheus-rabbitmq-exporter
Namespace:    default
Labels:       app=prometheus-rabbitmq-exporter
              chart=prometheus-rabbitmq-exporter-0.5.2
              heritage=Tiller
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2019-09-20T09:14:59Z
  Generation:          2
  Resource Version:    35327210
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/kube-stack-prometheus-rabbitmq-exporter
  UID:                 1ebfe46c-db87-11e9-9877-42010aa401cd
Spec:
  Endpoints:
    Interval:  10s
    Port:      publish
  Selector:
    Match Labels:
      App:      prometheus-rabbitmq-exporter
      Release:  kube-stack
Events:         <none>
```

### Borken - 0.5.3 (This PR's version)
- service definition
```
$ kubectl describe svc kube-stack-prometheus-rabbitmq-exporter 
Name:              kube-stack-prometheus-rabbitmq-exporter
Namespace:         default
Labels:            app=prometheus-rabbitmq-exporter
                   chart=prometheus-rabbitmq-exporter-0.5.3
                   heritage=Tiller
                   release=kube-stack
Annotations:       <none>
Selector:          app=prometheus-rabbitmq-exporter,release=kube-stack
Type:              ClusterIP
IP:                10.160.1.8
Port:              publish  9419/TCP
TargetPort:        publish/TCP
Endpoints:         10.144.1.13:9419
Session Affinity:  None
Events:            <none>
```
- servicemonitor definition
```
$ kubectl describe servicemonitors.monitoring.coreos.com kube-stack-prometheus-rabbitmq-exporter 
Name:         kube-stack-prometheus-rabbitmq-exporter
Namespace:    default
Labels:       app=prometheus-rabbitmq-exporter
              chart=prometheus-rabbitmq-exporter-0.5.3
              heritage=Tiller
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2019-09-20T09:14:59Z
  Generation:          1
  Resource Version:    26578148
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/kube-stack-prometheus-rabbitmq-exporter
  UID:                 1ebfe46c-db87-11e9-9877-42010aa401cd
Spec:
  Endpoints:
    Interval:  10s
    Port:      rabbitmq-exporter
  Selector:
    Match Labels:
      App:      prometheus-rabbitmq-exporter
      Release:  kube-stack
```

**Comment by yoshz** [comment]
I can confirm as well the exporter is broken in 0.5.3.
The port name in the ServiceMonitor must match the port name in the Service.

**Pull request merged**
