### PR TITLE
[stable/filebeat] introduce dnsConfig values for the containers

### PR DESCRIPTION
**Pull request by orong-pp**
Signed-off-by: Oron Gola <oron.gola@perception-point.io>

#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by orong-pp** [comment]
looks like I'm hitting the same issue like here #16070 
cc @helm/charts-maintainers

**Comment by orong-pp** [comment]
retest

**Comment by orong-pp** [comment]
looks like I'm hitting the same issue like here #16070
@sstarcher

**Comment by sstarcher** [comment]
@orong-pp I don't have any control over that.

@rendhalver Do you have any plans to move this out of the helm/charts repo as this will go away Nov 2020.

I have a setup and projects outside of this org if you don't have any intentions to I would be more than happy to manage it.

**Comment by shanestarcher-okta** [comment]
It looks like elastic has their own chart now.  https://hub.helm.sh/charts/elastic/filebeat  It's likely best that people move to that chart.

**Comment by orong-pp** [comment]
thanks for the info @sstarcher and @shanestarcher-okta 
I wasn't aware of the fact this chart is about to go away soon

its relevant only to the filebeat chart right?

I will look at the elastic chart and try to migrate to it

**Pull request closed without merging**
