### PR TITLE
[stable/artifactory]Promote initContainers to pod spec

### PR DESCRIPTION
**Pull request by dhilipkumars**
Move initcontainers to podspec

### CODE REVIEW

**Comment by dhilipkumars** [comment]
cc: @jainishshah17 and @eldada

**Review by eldada — CHANGES_REQUESTED** [review]
Hi @dhilipkumars .
Good PR.
Please update all versions to *5.4.6*.
They are also missing from `values.yaml`:
*artifactory.image.version*
*nginx.image.version*

**Comment by prydonius** [comment]
Hmm it looks like Artifactory is using the Artifactory version for the chart version, this is confusing and `appVersion` should now be used for the Artifactory version. The reason for this is that the chart version should be independent from the application version as there are often "package-level" changes like this one that need to be made. I'm not sure of the best way to resolve this, perhaps the chart `version` could be bumped to 6.0.0 to disassociate it from the Artifactory version?

**Comment by eldada** [comment]
@prydonius - I'm aware of this, but I actually like the association of versions.
If we really need a new chart version for the same Artifactory version (for example 5.4.6), we can set the `Chart.yaml` **version** key to **5.4.6-a** or **5.4.6-1**. Does that make sense?

**Comment by prydonius** [comment]
@eldada although that would work, we would have to be very careful with future versioning as that indicates the version is a pre-release in semver. I'm fine with switching to that for now though.

I'm generally not a big fan of the current versioning scheme (across all charts in this repo), the appVersion was introduced to make this a bit easier, but given that version means more (shows up in helm search, etc.) it hasn't had the desired effect. Anyway, this is a longer discussion and I hope we'll come to a solution soon that makes the most sense to end users.

**Comment by dhilipkumars** [comment]
@prydonius and @eldada PTAL now.

**Review by eldada — APPROVED** [review]
Looks good on my end.

**Comment by prydonius** [comment]
thanks @dhilipkumars and @eldada!
/lgtm

**Pull request merged**
