### PR TITLE
[incubator/drone] GCE Ingress Path Fix

### PR DESCRIPTION
**Pull request by depado**
It looks like when using the GCE Ingress, we need to add a `*` in the ingress, otherwise it doesn't work.

This fix determines if the annotation `kubernetes.io/ingress.class` is set to `gce` and modifies the path in the rules from `/` to `/*`

### CODE REVIEW

**Comment by depado** [comment]
Signed the CLA.

**Comment by christian-roggia** [comment]
I can't test this, can you provide a link to the GCE documentation?

**Comment by unguiculus** [comment]
We just recently had a PR for another chart that did this because it seemed to be required for AWS. The solution was to simply configure both paths. I don't remember which chart it was.

**Comment by christian-roggia** [comment]
lgtm then, it can be merged.

**Comment by christian-roggia** [comment]
This PR needs a `/retest`.

**Pull request merged**
