### PR TITLE
[stable/anchore-engine] Update to anchore-engine:v0.7.0

### PR DESCRIPTION
**Pull request by Btodhunter**
enabled github feeds configuration
Use anchore-engine:v0.6.1 image when enterprise is enabled
add imagePullSecret configuration for private anchore-engine images
bump chart minor version
update feeds read timeout to 180
update README

Signed-off-by: Brady Todhunter <bradyt@anchore.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sc250024** [comment]
Yes please!

**Comment by sc250024** [comment]
@Btodhunter Since this `stable` Helm repository is slowly being deprecated, does Anchore have plans to serve its own Helm repository for its charts?

**Review by zhill — APPROVED** [review]

**Comment by zhill** [comment]
> @Btodhunter Since this `stable` Helm repository is slowly being deprecated, does Anchore have plans to serve its own Helm repository for its charts?

I can answer since I'm here. Yes we will be migrating to our own repo: https://github.com/anchore/anchore-charts/issues/15

**Comment by Btodhunter** [comment]
@sc250024 We are planning on migrating to our own chart repo! Just waiting for enough cycles to get it done. You can check the progress [here](https://github.com/anchore/anchore-charts/issues/15)

**Pull request merged**
