### PR TITLE
[stable/grafana] New existingClaim configuration parameter

### PR DESCRIPTION
**Pull request by h0tbird**
- Added `server.persistentVolume.existingClaim` to README.
- Honour the value in `deployment.yaml`.
- Don't define PersistentVolumeClaim if `existingClaim` is set.
- Default value in `values.yaml` is set to `""`.

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
Needs chart version bump then LGTM

**Comment by h0tbird** [comment]
Version bumped. @lachie83 can you squash? I can't.

**Comment by lachie83** [comment]
Sure. We'll squash on merge

**Pull request merged**
