### PR TITLE
[stable/pomerium] Chart updates for pomerium v0.1.0 

### PR DESCRIPTION
**Pull request by travisgroth**
#### What this PR does / why we need it:
This bumps the app version to support the latest release of Pomerium, and expose new metrics functionality.  Examples and documentation included.

/cc @desimone 

#### Related Issues:

pomerium/pomerium#214

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by victornoel** [comment]
@travisgroth I see you haven't included all the latest changes that were merged in pomerium/pomerium-helm, is that on purpose? In particular there are some that are important I think about config checksums.

**Comment by travisgroth** [comment]
@victornoel Not intentional, no.  I'll look at updating both of them to be consistent.

**Pull request merged**
