### PR TITLE
[stable/airflow] Typo fix in values.yaml of airflow chart

### PR DESCRIPTION
**Pull request by ypraveen**
Signed-off-by: Praveen Yalagandula <ypraveen@gmail.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@ypraveen what issue are you facing with including `ssh://` as this URI structure works fine for me?

**Comment by ypraveen** [comment]
@thesuperzapper I run into the following error with ssh:// in the front:
Cloning into '/'...
ssh: Could not resolve hostname github.com:merqurian: Name does not resolve
fatal: Could not read from remote repository.

Our previous config didn't have the "ssh://" prefix and was working fine. I switched back to that and it started working.

It seems git clone doesn't like the ":". Another option is that we could change it ssh://git@github.com/torvalds/linux.git --- that seems to work.

**Comment by thesuperzapper** [comment]
Yeah, with the `ssh://` its a URI, which means that `:` represents a TCP Port, not a repository.

**Comment by alexbegg** [comment]
I can also confirm that with `:` replaced with `/` the git url works for git-sync. This is just how git works, as defined in the documentation of git clone: https://git-scm.com/docs/git-clone#_git_urls. The `git@github.com:user/repo.git` is scp-like syntax specific to git and not a true url, but with `ssh://git@bitbucket.org/user/repo.git` you are using a real ssh uri therefore you only will put a `:` if you are specifying a port.

As for what the example should show I think what this PR shows is the best way, it should show the most common type which is the one without `ssh://` and with a `:` because that is how github shows it when they show a clone command for ssh. Either that or show both ways.

**Pull request closed without merging**
