### PR TITLE
[stable/distributed-tensorflow] Add Dysproz to OWNERS, update owner in Chart.yml

### PR DESCRIPTION
**Pull request by Dysproz**
As discussed with @zanhsieh in PR #16436, I add myself to OWNERS of this chart and update Chart.yml. I've mentioned previous owner in OWNERS file in emeritus section.

This PR is based on issue #13869 

Signed-off-by: Szymon <krasuski.szymon.piotr@gmail.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped (Should it be bumped in this situation?)
- [x] Variables are documented in the README.md (Owner is not mentioned in README)
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Dysproz** [comment]
@maorfr @lachie83 
Would you mind granting me as one of the owners of this chart?

**Comment by maorfr** [comment]
@cheyang ptal

**Comment by zanhsieh** [comment]
@Dysproz 
Check your email if invitation received.

**Comment by Dysproz** [comment]
@zanhsieh
I didn't receive any invitation

**Comment by zanhsieh** [comment]
@maorfr 
Would you mind to take a look please? Thank you.
/ok-to-test

**Comment by maorfr** [comment]
i would like to wait for @cheyang  to respond

**Comment by Dysproz** [comment]
@maorfr After a month of waiting, can we proceed further or are we still waiting?

**Pull request merged**
