### PR TITLE
minor README clarification

### PR DESCRIPTION
**Pull request by gmarik**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Review by paulczar — APPROVED** [review]
LGTM

**Comment by unguiculus** [comment]
@gmarik Please fix your CLI so we can get this in.

**Comment by jdumars** [comment]
Hi, please get your CLA signed, and we will ok this for testing. Thanks!

**Comment by prydonius** [comment]
@gmarek any luck on the CLA?

**Comment by gmarek** [comment]
No, it's still red. @kubernetes/test-infra-maintainers - who owns the bot now?

**Comment by prydonius** [comment]
@gmarek you can find all the CLA info here https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement, there's a mailing address at the bottom for someone to contact if you're still having issues

**Comment by gmarek** [comment]
@gmarik - as I guess putting my ldap was a mistake:)

**Comment by prydonius** [comment]
oops - sorry @gmarek!! feel free to unsubscribe :)

**Comment by stevekuznetsov** [comment]
The status right now is ` cla/linuxfoundation — unguiculus authorized, but 1 other problem ` -- SIG Testing does not maintain this integration, so I would suggest contacting the e-mail in the original post to ask what went wrong here.

**Comment by BenTheElder** [comment]
> No, it's still red. @kubernetes/test-infra-maintainers - who owns the bot now?

The `cla/linuxfoundation` status  is owned by the Linux Foundation. The matching `cncf-cla: no` / `cncd-cla: yes` labels come from Prow / test-infra maintainers.
Edit: ninjaed by @stevekuznetsov :upside_down_face:

**Comment by prydonius** [comment]
The issue is that @gmarik likely hasn't signed CLA, I just got mixed up and accidentally pinged @gmarek (who probably had no idea what I was talking about).

**Pull request closed without merging**
