### PR TITLE
correct miss spelling in chartmuseum

### PR DESCRIPTION
**Pull request by cheyang**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cheyang** [comment]
Thanks, @timstoop.

**Comment by jdolitsky** [comment]
/lgtm
thanks @cheyang!

**Pull request merged**
