### PR TITLE
[stable/prometheus] custom alertmanager config

### PR DESCRIPTION
**Pull request by pbalogh-sa**
#### What this PR does / why we need it:
If you want to use custom alermanager with setting `alertmanager.enabled=false`, you can use the defined custom alerting config without defining whole `serverFiles.prometheus.yml`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by lostick** [comment]
Is this `custom` element  necessary ?
There is already plenty of options to override a prometheus config IMO.

Sounds to me like it could create some confusion, especially with the existing `alertmanager.configFromSecret` and `alertmanager.configFileName` params.

**Comment by pbalogh-sa** [comment]
The alertmanager.configFromSecret and alertmanager.configFileName params contain alertmanager configuration but they aren't effect to prometheus configuration. This PR focus on prometheus-server configuration. I want to use custom alertmanager, not only custom alermanager config.
If you want to define custom alertmanager, the only is using server.configMapOverrideName option, because in server-configmap.yaml the alertmanager definition can't be modified: https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml#L22-L44

**Comment by pbalogh-sa** [comment]
Any update or comment on this?

**Pull request closed without merging**
