### PR TITLE
[stable/telegraf]

### LINKED ISSUE #9376: [stable/telegraf] telegraf deprecated version
**Is this a request for help?**:

No, PR is coming as well.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
It's a feature request

**Version of Helm and Kubernetes**:
```zsh
➜  stable git:(telegraf-refresh) ✗ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
➜  stable git:(telegraf-refresh) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/telegraf`

**What happened**:
`telegraf` chart use version `1.5` which is no longer developed [see 1.5 documentation](https://docs.influxdata.com/telegraf/v1.5/)
`1.5` had to have an `influxdb` as an output which is not the case anymore.

**What you expected to happen**:
`telegraf` should be up to date & not force the usage of `influxdb` anymore

**How to reproduce it** (as minimally and precisely as possible):
Installing `telegraf` use this example values:
```yaml
image:
  repo: "telegraf"
  tag: "1.5-alpine"
  pullPolicy: IfNotPresent
daemonset:
  enabled: false
single:
  enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
    limits:
      memory: 2Gi
      cpu: 1
  service:
    enabled: true
    type: ClusterIP
  config:
    agent:
      interval: "10s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    outputs:
      prometheus_client:
        listen: "0.0.0.0:9126"
    inputs:
      statsd:
        protocol: "udp"
        max_tcp_connections: 250
        tcp_keep_alive: false
        service_address: ":8125"
        delete_gauges: true
        delete_counters: true
        delete_sets: true
        delete_timings: true
        percentiles: [90]
        metric_separator: "_"
        parse_data_dog_tags: false
        allowed_pending_messages: 10000
        percentile_limit: 1000
```

### PR DESCRIPTION
**Pull request by kinok**
#### What this PR does / why we need it:
Basically it updates the version of `telegraf`

#### Which issue this PR fixes
  - fixes #9376

#### Special notes for your reviewer:
Bumped as minor as per the default `telegraf` image has been to change to the `latest` minor.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
Hi @kinok , for maintainers:
You can add this and it should work, if you want to keep the original maintainer

```
maintainers:	
- name: jackzampolin	
  email: jack@influxdb.com
```

**Comment by naseemkullah** [comment]
Oh sorry @kinok, my mistake.

**Comment by kinok** [comment]
No worries @naseemkullah it was a 1 minute thing to test :+1:

**Comment by maver1ck** [comment]
@kinok 
Probably you want also to remove deprecation notice ?

**Comment by kinok** [comment]
@maver1ck good point, thanks for the feedback.
Just rebased & push forced the fix branch, `lint-charts` scripts now pass.

**Pull request closed without merging**
