### PR TITLE
[incubator/kafka] Wait for all Kafka brokers to be connected to Zookeeper

### PR DESCRIPTION
**Pull request by marvelm**
#### What this PR does / why we need it:
This PR modifies the topic creation script to wait for all expected Kafka brokers to be available before continuing execution. The script will wait for Zookeeper to become available (unchanged behaviour), then query Zookeeper at a 20 second interval until all Kafka brokers have connected.

#### Which issue this PR fixes
We've noticed that topic creation will succeed as soon as the number of available Kafka brokers is equal to the replication factor.

Here's an example configuration. In this case, once the minimum number of brokers to satisfy the replication factor (`0, 1`) are available, partitions will be distributed these first two brokers. For our use-case, this results in an unbalanced workload where the broker `3` won't be written to. We are currently solving this problem by manually re-creating and running this job.
```yaml
replicas: 3
topics:
  - name: myTopic
    partitions: 6
    replicationFactor: 2
```

I realize that the easiest way to fix this issue to set `replicationFactor=replicas`. But, it may be worthwhile to fix the deeper issue.

#### Special notes for your reviewer:
Tests should pass with default values because no topics are specified. I've tested these changes in production with a configuration similar to what is described above.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by marvelm** [comment]
We've installed this chart several times in the past month on production clusters without issue.
@benjigoldberg Could you please review this when you get a chance?

**Comment by marvelm** [comment]
Pinging on this thread once again. I would really appreciate a review.

**Comment by benjigoldberg** [comment]
@marvelm I apologize for the delay in reviewing this. This is a great bug fix and solution. LGTM.

/lgtm

**Pull request merged**
