### PR TITLE
[incubator/schema-registry] update image to 5.0.1

### PR DESCRIPTION
**Pull request by fabriziofortino**
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
/test pull-charts-e2e
--

**Comment by fabriziofortino** [comment]
@benjigoldberg I think this should be OK now

**Comment by benjigoldberg** [comment]
/lgtm

@fabriziofortino thanks for the contribution!

**Pull request merged**
