### PR TITLE
Add stable/prometheus-es-explorer

### PR DESCRIPTION
**Pull request by alexppg**
Signed-off-by: Àlex Pérez-Pujol <alexperezpujol@disroot.org>

#### What this PR does / why we need it:
It adds the [prometheus-es-exporter](https://github.com/braedon/prometheus-es-exporter) to the stable chart repository.

#### Special notes for your reviewer:
None.

#### Checklist
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by alexppg** [comment]
I'm not sure why it says that I fail the DCO. I've signed with my main e-mail, but it wants me to set the corporate mail.

**Comment by vsliouniaev** [comment]
@alexppg the DCO checks that the signing email corresponds to the email in the commit itself.
```
git config user.email
```

**Comment by alexppg** [comment]
Thanks @vsliouniaev, I've change it. I believe there's nothing to be done on my side until somebody reviews it, the lint that fails won't pass until some maintainer is asigned.

**Comment by vsliouniaev** [comment]
Since you are submitting this chart to the repository, wouldn't it make sense that you should add yourself as the maintainer?

**Comment by alexppg** [comment]
No problem @mvasilenko, but I believe I can't add myself like that and make the tests pass. In a prior commit I added myself to the maintainers section but [this check](https://circleci.com/gh/helm/charts/59453?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) says I'm not validated as a maintainer, and I don't know how it validates it.

**Comment by alexppg** [comment]
ping @viglesiasce @foxish

**Comment by ntavares** [comment]
Just to keep this open as the bot is trying to close this. Is there anything still to be done here?

**Comment by alexppg** [comment]
@ntavares Somebody needs to revise it, as far as I know I don't have to do anything.

**Comment by maorfr** [comment]
hey @alexppg 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by alexppg** [comment]
I'd like to that, but right now I'm not able. I'll try to convince my company to do it, but for now is no possible. It's a problem @maorfr ?

**Comment by maorfr** [comment]
hey @alexppg, thanks for your reply!

it is an effort problem. chart maintainers are over loaded, so reviewing a new chart usually takes a long time. with that said, the way forward is not this repository, but rather helm hub! :)

Here are some things to consider if you are exploring hosting your own charts repository (copied from a similar PR):

I think that you totally should host your own charts!
This will give you more freedom around management, and you will not be blocked by us (maintainers).

This means that when users want to install your chart, instead of installing them from stable, they will install it from (for example) mycompany-charts:

$ helm install --name my-release mycompany-charts/mychart
Here are some instructions about how to host your own charts repo:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

In order for people to find out about your charts repo, you should add it to helm hub:
https://hub.helm.sh/

Here are some instructions about how to add your charts repo to helm hub:
https://github.com/helm/hub#how-to-add-your-helm-charts

Hope that answered all your questions! :)

**Comment by alexppg** [comment]
Thanks @maorfr ! I'll sure like to do that, because of all the reasons you mentioned. But as I said, I don't think this will be possible in a short time, so I'd like to maintain this chart here. Sorry and thanks for your kind explanation!

**Pull request closed without merging**
