### PR TITLE
[stable/external-dns]: Specify Google Cloud DNS credentials.json via kubernetes secret

### PR DESCRIPTION
**Pull request by dereulenspiegel**
This Pull Request adds the ability to specify a secret which contains the credentials.json used to authenticate against the Google Cloud DNS service for external-dns.

### CODE REVIEW

**Comment by paulczar** [comment]
Please bump the version number in `Charts.yaml`.

**Comment by dereulenspiegel** [comment]
Done :)

**Review by paulczar — APPROVED** [review]
LGTM

**Pull request merged**
