### PR TITLE
File system 'fs-12345678' does not exist

### PR DESCRIPTION
**Pull request by dawidmalina**
#### What this PR does / why we need it:

Fix issue related to default file system id:
```
W0109 08:06:08.407526 1 efs-provisioner.go:91] couldn't confirm that the EFS file system exists: FileSystemNotFound: File system 'fs-12345678' does not exist.
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by hacktron95** [comment]
Hello,
I don't truly know why this version triggers this error `1 efs-provisioner.go:60] environment variable FILE_SYSTEM_ID is not set! Please set it.`
when I install the helm chart with this
`helm install aws-efs stable/efs-provisioner --version 0.10.1 \
                                         --set efsProvisioner.provisionerName=efs-provisioner \
                                         --set efsProvisioner.awsRegion=${} \
                                         --set efsProvisioner.storageClass.name=efs \
                                         --set efsProvisioner.storageClass.isDefault=true \
                                         --set efsProvisioner.dnsName=${}`

while executing `helm install aws-efs stable/efs-provisioner --version 0.10.0 \
                                         --set efsProvisioner.provisionerName=efs-provisioner \
                                         --set efsProvisioner.awsRegion=${} \
                                         --set efsProvisioner.storageClass.name=efs \
                                         --set efsProvisioner.storageClass.isDefault=true \
                                         --set efsProvisioner.dnsName=${}`
triggers no issue at all,
what I understand is "it's either I pass the dnsName or the efsFileSystemId", correct?
thanks a lot

**Comment by dawidmalina** [comment]
@hacktron95 thanks for pointing this out. It looks like it's required even if this is invalid value. For me it's should be fixed in https://github.com/kubernetes-incubator/external-storage but for now I propose to revert it back.

@srueg, @mariusv what do you propose? I can drop a PR to roll this back.

**Comment by srueg** [comment]
Agree, let's roll back until it's fixed upstream. Thanks :+1:

**Comment by dawidmalina** [comment]
Please review: https://github.com/helm/charts/pull/19984

**Pull request merged**
