### PR TITLE
[stable/prometheus-redis-exporter] Support image pullSecrets

### PR DESCRIPTION
**Pull request by jmistx**
@acondrat 

#### What this PR does / why we need it:
Without this, you couldn't pull redis exporter image from private repos.

#### Special notes for your reviewer:
<3

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by acondrat** [comment]
lgtm but I don't think I am able to aprrove. To be honest I don't know if the maintainers field is of any use since you have to be a org member to aprrove PRs.

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

@acondrat, i have added you as a collaborator :)
please create a PR adding an OWNERS file with you in it. if you can think of anyone else that can maintain this chart with you - feel free to add them to the OWNERS file as well!

**Comment by jmistx** [comment]
You are the best, guys %)

**Comment by maorfr** [comment]
and thanks for contributing @jmistx!

**Pull request merged**
