### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eggie5**
postgres typo fix

### CODE REVIEW

**Comment by eggie5** [comment]
@k8s-bot ok to test

**Comment by eggie5** [comment]
I signed it!

**Comment by eggie5** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
Hi @eggie5 Can you also sign the LF cla please

**Comment by lachie83** [comment]
LGTM. Just waiting on LF CLA to be signed

**Comment by eggie5** [comment]
I signed it!

**Comment by lachie83** [comment]
Your google CLA is okay but your LF CLA is still broken.

**Comment by eggie5** [comment]
I see a green check for LF

**Comment by lachie83** [comment]
Thanks! Seeing the same thing on my end too.

**Comment by lachie83** [comment]
Will merge once e2e is fixed and we can rerun the tests.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@k8s-bot e2e test this

**Pull request merged**
