### PR TITLE
[stable/prometheus-blackbox-exporter] removes configmap-reload in favor of a configmap checksum

### PR DESCRIPTION
**Pull request by marshallford**
Signed-off-by: Marshall Ford <inbox@marshallford.me>

#### Is this a new chart

No.

#### What this PR does / why we need it:

Removes sidecar container watching for configmap changes in favor of checksum annotation in the deployment resource. The sha256 checksum is calculated by Helm during install and upgrades.

https://sanderknape.com/2019/03/kubernetes-helm-configmaps-changes-deployments/

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

N/A

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
Ping two owners in the kubernetes slack channel #charts

**Comment by desaintmartin** [comment]
Thanks!
What are the benefits/disadvantages of this approach? What does not work with the current approach?
(I'm not against the change, I just want to understand the implications)
/assign

**Comment by vsliouniaev** [comment]
IMO this is a good thing, since the blackbox exporter is really just a proxy, there isn't really a need to have another container running alongside it. This decreases the overall memory and CPU footprint of the pod.

**Comment by desaintmartin** [comment]
... And it further simplifies the chart. And because we don't need HA (AFAIK), it's a ...
/lgtm
;)

**Comment by vsliouniaev** [comment]
@marshallford Are you able to bump the chart version again? Sorry about the wait on this one

**Comment by marshallford** [comment]
@vsliouniaev done

**Pull request merged**
