### PR TITLE
stable/redis-ha - enable stats sock in ha-proxy config

### PR DESCRIPTION
**Pull request by squ1d123**
#### Is this a new chart
No

#### What this PR does / why we need it:
Enable stats sock in ha-proxy config if enabled

You do not get full monitoring of ha-proxy without it.

#### Special notes for your reviewer:
@ssalaues @dandydeveloper

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
@DandyDeveloper could you review this one?

**Comment by DandyDeveloper** [comment]
@squ1d123 How does this differ to using the HTTP for stats?

**Pull request closed without merging**
