### PR TITLE
[metricbeat] Enable use of PSPs

### PR DESCRIPTION
**Pull request by razaj92**
Signed-off-by: razaj92 <razajhaveri@googlemail.com>

#### What this PR does / why we need it:
Enables PSPs for metricbeat

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by at-k** [comment]
Sorry to keep you waiting!

It's good proposal to set psp configuration on metricbeat. 
I checked this PR on my local environment and it seems to work correctly,.

**Comment by at-k** [comment]
@ razaj92 please solve conflicts 
chart version has been updated.

**Comment by razaj92** [comment]
Hey @at-k

No worries, conflicts are now resolved

Thanks

**Pull request merged**
