### PR TITLE
[incubator/gogs] Add tls evaluation of ingress to template

### PR DESCRIPTION
**Pull request by fuhbar**
TLS related parameters in values files are existent, but the relevant entries in the corresponding `templates/ingress.yaml` were missing. Added a conditional and appropriate section.

### CODE REVIEW

**Comment by fuhbar** [comment]
@tvon would you mind glimpsing over this PR?

**Comment by tvon** [comment]
Seems reasonable to me

👍

**Comment by tvon** [comment]
Though, should have an example of usage.

**Pull request merged**
