### PR TITLE
[stable/prometheus-operator] Updated the kube-state-metrics svc matchlabels

### PR DESCRIPTION
**Pull request by ribeiromiranda**
##### What this PR does / why we need it:
The labels from kube-state-metrics service have been changed in commit: https://github.com/helm/charts/commit/ece06ce7535925760b901d630320b429524e6dea#diff-5683c47f1fce3f75f10401ba9b88815b

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@mirandawork without updating the kube-state-metrics dependency in this chart the selector will not work. Could you please also do this update and validate the changes?

**Comment by mirandawork** [comment]
@vsliouniaev changed the kube-state-metrics dependency.

**Comment by vsliouniaev** [comment]
This looks good, but I ran into an issue upgrading from a previous version of the chart because the deployment's `spec.selector` field is immutable. This requires anyone that has the chart already installed to perform an upgrade using the `--force` option so that the resources are recreated by helm.

In my opinion this is a breaking change 
- we should bump the major version of the helm chart
- we should add a line to the main body of this PR to indicate that someone doing the upgrade should add the `--force` option

**Comment by mirandawork** [comment]
I bumped the version to 6.0.0.

I propose to add some instruction in the section "Work-Arounds for Known Issues" from the readme.

Example:
### Upgrade
When executing the `helm upgrade` to avoid the error below is need add the argument `--force`

> invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by vsliouniaev** [comment]
Yes, please do

**Comment by vsliouniaev** [comment]
/lgtm
Thank you!

**Comment by tariq1890** [comment]
Hi `kube-state-metrics` maintainer here. Importing chart version `2.0.0` introduces breaking changes.  Labels and label selectors have been changed.

**Comment by tariq1890** [comment]
Ideally, the labels should have been changed in prometheus operator as well so that it matches the conventions in kube-state-metrics 2.0.*

Thoughts @vsliouniaev

**Comment by vsliouniaev** [comment]
@tariq1890 agree, but we have 3 dependencies that need to all be changed too

**Pull request merged**
