### PR TITLE
[incubator/drone] Support secret environment variables in drone server

### PR DESCRIPTION
**Pull request by colinhoglund**
This change creates a `server.envSecret` parameter to allow users to reference Kubernetes Secrets for environment variables.

### CODE REVIEW

**Comment by christian-roggia** [comment]
The secrets management in Helm has always bothered me, I couldn't find a good solution to this problem that was elegant and simple.

I'd like to put this PR on hold and discuss about possible alternatives if it is okay for you.

**Comment by colinhoglund** [comment]
@christian-roggia I agree that managing secrets in helm could use some improvement/best practices, and I would appreciate any recommendations you can provide.

I developed this strategy based on how other charts are handling secrets, as well as https://github.com/kubernetes/helm/issues/2780.
There are a number of open issues regarding helm secrets, such as https://github.com/kubernetes/helm/issues/2196.

However, I should point out that the current implementation of this chart encourages storing plain text secrets in `values.yaml`. This simply isn't an option for those of us checking `values.yaml` files into version control, therefore I am working off of a fork. I'm wondering if it makes sense to implement this backwards compatible change as a stop gap until there is an acceptable standard for handling secrets in helm.

**Comment by christian-roggia** [comment]
@colinhoglund please let me apologize for not giving you an answer, I am moving in a new house and I have been really busy these weeks. In around a week I should be ready to review this issue and we can discuss possible solutions.

**Comment by colinhoglund** [comment]
@christian-roggia No worries. We're currently working out of a private chart repo so there's no rush for me.

**Comment by koalalorenzo** [comment]
Is this discussion still going on? This feature could help us secure our variables (ex: the OAuth keys)

**Comment by christian-roggia** [comment]
As a temporary solution I guess that there is no better option. This PR can be merged, maybe in the future there will be a better support for secrets, but for now that's the best we got.

**Comment by christian-roggia** [comment]
lgtm

**Comment by colinhoglund** [comment]
@seanknox @christian-roggia I've actually started using a slightly different syntax on some other charts in order to make things a bit more succinct.

```
envSecrets:
  drone-server-secrets:
    - DRONE_GITHUB_CLIENT
    - DRONE_GITHUB_SECRET
    - DRONE_DATABASE_DATASOURCE
```

Since these values are intended to be used as environment variables anyway, it removes the env var -> secret key mapping and just assumes the secret key names are the same value as the env var names. The loop changes to:

```
            {{- range $secret, $keys := .Values.envSecrets }}
            {{- range $keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ . | quote }}
            {{- end }}
            {{- end }}
```

Let me know if you think this is a better approach and i'll be happy to update the PR, otherwise the current syntax also works fine.

**Comment by christian-roggia** [comment]
I think this might be a better approach and it also looks cleaner. Feel free to update the PR. Thanks!

**Comment by colinhoglund** [comment]
@christian-roggia Updated, thanks for the review.

**Comment by christian-roggia** [comment]
Please bump the major version instead of the minor version as this is a breaking change in the chart. (i.e. set chart version to 1.0.0).

**Comment by colinhoglund** [comment]
Unless I'm missing something there shouldn't be any breaking changes here. This just gives people the option of retrieving environment variables from secrets. Existing installations that pass variables to `env:` should continue to work.

**Comment by christian-roggia** [comment]
It's true that existing installation will continue to work, but the env management has fundamentally changed and everyone should think twice before keeping the old, unsecure installation.

**Comment by christian-roggia** [comment]
I am also thinking about finally moving this chart to stable as soon as the few open issues are solved.

**Comment by colinhoglund** [comment]
@christian-roggia sounds good, bumped version.

**Comment by christian-roggia** [comment]
This looks good to me. @unguiculus

**Pull request merged**
