### PR TITLE
grafana will now tpl dashboardConfigMap values

### PR DESCRIPTION
**Pull request by valdisrigdon**
#### What this PR does / why we need it:
Similar to https://github.com/helm/charts/pull/10603, this will tpl the values of the `dashboardsConfigMaps`.
We are using the Grafana chart as a subchart, along with Prometheus, to create a shared monitoring chart. In two places we are configuring the Grafana chart with static values from a `values.yaml` but we want them to be templatized to support deploying multiple versions in a single `Namespace`.

The `tpl` call in `deployment.yaml` allows us to specify the following in `values.yaml`. This way the name of the passed `ConfigMap` can match the `ConfigMap` defining the dashboards our wrapping chart generates.

```
dashboardsConfigMaps:
    infrastructure-config-map: '{{ include "prometheus-stack.fullname" . }}-dashboards'
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Based on a number of notes from https://github.com/helm/helm/issues/2492, this is a suggested way to make this work.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by valdisrigdon** [comment]
@zanhsieh @rtluckie @maorfr ready for a review

**Comment by zanhsieh** [comment]
This is a tough call....

**Comment by maorfr** [comment]
Possible.duplicate of #10603

**Comment by maorfr** [comment]
@valdisrigdon, everything has to be green to be merged ;)
Note that some.of your changes were already handled by a previous PR.

**Comment by valdisrigdon** [comment]
@maorfr Updated to resolve conflicts. https://github.com/helm/charts/pull/10603 solved half of this PR.

**Pull request merged**
