### PR TITLE
Feature/add subpath to grafana custom volumes

### PR DESCRIPTION
**Pull request by gandazgul**
#### What this PR does / why we need it:

It adds the ability to specify a subpath with each entry in extraVolumeMounts

This will allow configs and plugins to live in the same volume for example.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by gandazgul** [comment]
@maorfr is a one line change, let me know what you think.

**Comment by gandazgul** [comment]
Woohoo! Thank you @maorfr

**Comment by maorfr** [comment]
Thank you for your first contribution :)

**Comment by gandazgul** [comment]
How long does the pull-charts-e2e job usually take? is it stuck perhaps?

**Comment by maorfr** [comment]
most probably stuck. would you like to try and get someone involved? a good place would be the #charts channel in k8s slack. let me know if you prefer that I do it ;)

**Comment by gandazgul** [comment]
@maorfr yeah I dont have access to k8s slack and the registration site is down atm. Could you get it going for me? thank you

**Comment by maorfr** [comment]
I would suggest to close and open a new PR. assign me to it ;)

**Comment by gandazgul** [comment]
sounds good

**Pull request closed without merging**
