### PR TITLE
Provide our own secrets for kiam

### PR DESCRIPTION
**Pull request by jeckhart**
#### What this PR does / why we need it:
Add ability to provide TLS keys via predefined secrets instead of generating the secrets in the chart.

This is helpful so we don't have to keep those secrets around to run updates to the chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by ewbankkit** [comment]
@jeckhart It looks like this has been duplicated in https://github.com/helm/charts/pull/9755. Could you please double-check my assessment? Thanks

**Comment by jeckhart** [comment]
@ewbankkit You are correct, I think #9755 does the same thing this PR does.

**Comment by hakamadare** [comment]
#10353 has been merged, and does some of the work necessary to support this functionality

**Comment by jeckhart** [comment]
It looks like this has been implemented independently by 3 separate people. I'm happy the change made it in, but why did it take 3 attempts?

**Pull request closed without merging**
