### PR TITLE
[stable/metricbeat] updated metricbeat to 6.5.1

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### What this PR does / why we need it:
* updated metricbeat to 6.5.1

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mumoshu** [comment]
```
I1130 19:07:04.341] process 228 exited with code 0 after 0.0m
I1130 19:07:04.342] Call:  gcloud config get-value account
I1130 19:07:04.576] process 241 exited with code 0 after 0.0m
I1130 19:07:04.576] Will upload results to gs://kubernetes-jenkins/pr-logs using pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
I1130 19:07:04.576] Call:  kubectl get -oyaml pods/070c1df0-f4d3-11e8-b547-0a580a6c034d
W1130 19:07:04.665] The connection to the server localhost:8080 was refused - did you specify the right host or port?
E1130 19:07:04.668] Command failed
I1130 19:07:04.668] process 254 exited with code 1 after 0.0m
E1130 19:07:04.668] unable to upload podspecs: Command '['kubectl', 'get', '-oyaml', 'pods/070c1df0-f4d3-11e8-b547-0a580a6c034d']' returned non-zero exit status 1
I1130 19:07:04.669] Root: /go/src
I1130 19:07:04.669] cd to /go/src
I1130 19:07:04.669] Checkout: /go/src/github.com/helm/charts master:41d3f1e9c8f15a2488e31d7e953ca9db268f7829,9355:d94cf4f72a1004a3b74c47e0d205ff949ff4c0c8 to /go/src/github.com/helm/charts
I1130 19:07:04.669] Call:  git init github.com/helm/charts
```

How can I rerun the test?

**Comment by mumoshu** [comment]
O, it worked.

@monotek Thanks for your patience and support ☺️

**Comment by mumoshu** [comment]
🎉

**Comment by monotek** [comment]
Thanks for the review :-)

**Pull request merged**
