### PR TITLE
mssql-linux fullNameOverride value

### PR DESCRIPTION
**Pull request by matthewdevenny**
#### What this PR does / why we need it:
Adds the option of setting fullNameOverride to change the fully qualified app name. Resolves [9300](https://github.com/helm/charts/issues/9300)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by thomasliddledba** [comment]
LGTM - Nice contribution

**Comment by davidkarlsen** [comment]
@boxboatmatt Please fix the merge conflict.

**Comment by boxboatmatt** [comment]
@davidkarlsen merge conflicts resolved

**Comment by boxboatmatt** [comment]
@thomasliddledba @davidkarlsen can I get another approval and `ok to test` so we can merge this thing

**Comment by thomasliddledba** [comment]
I can't assign an `ok-to-test`.  I'm not a member just a chart owner/contributer.

**Pull request merged**
