### PR TITLE
[stable/airflow] Fix template directive value of nodePort for web service

### PR DESCRIPTION
**Pull request by pfxuan**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@pfxuan 
Would you mind to bump the chart version to latest please? Thank you.

**Comment by pfxuan** [comment]
Done. Thank you for checking this.

**Comment by pfxuan** [comment]
@maver1ck do you know when would we be able to merge this patch? Thanks!

**Comment by pfxuan** [comment]
@zanhsieh do you know when would we be able to merge this patch? Thanks!

**Comment by zanhsieh** [comment]
@pfxuan 
The owners (either one) need to LGTM it. I am not one of the owners.

@gsemet
@maver1ck
Would you guys to LGTM this PR please? Thank you.

**Comment by gsemet** [comment]
Hi ! No problem for this patch.
Next time simply @ me so I get a message on my mailbox, I am not notified on PR on airflow.

/lgtm

**Pull request merged**
