### PR TITLE
[stable/home-assistant] home-assistant chart enhancements

### PR DESCRIPTION
**Pull request by billimek**
#### What this PR does / why we need it:

* based on the persistent nature of this chart, using a default strategy Type of 'Recreate' instead of 'RollingUpdate' - with an optional override
* bumping home-assistant docker image to the latest stable version (0.89.1)
* updating label syntax to current helm standards (e.g.`app.kubernetes.io/name`)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
Going to make some additional changes and re-submit

**Comment by unguiculus** [comment]
/hold
See #12047

**Pull request merged**
