### PR TITLE
[Documentation] update labels in the documentation

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
Update the documentation in the label section to match the helm docs: https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed

### CODE REVIEW

**Comment by unguiculus** [comment]
We should also update to use `include` instead of `template`.

**Comment by unguiculus** [comment]
cc @helm/charts-maintainers

**Comment by cpanato** [comment]
@unguiculus update per your comment

**Pull request merged**
