### PR TITLE
[stable/kube-lego] #1785 namespace defined templates with chart name

### PR DESCRIPTION
**Pull request by kevinschumacher**
#1785

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@kevinschumacher Could you please check on this error?

**Comment by kevinschumacher** [comment]
@dhilipkumars the error is occurring because kube-lego cannot be deployed without the user providing the .Values.config.KUBE_LEGO

The chart decides NOT to specify a default and it is commented out in the default values.yaml

This is likely because you need to specify your own email address in order to sign up with letsencrypt. 

edit: this issue occurs in the current stable/kube-lego chart.

**Comment by kevinschumacher** [comment]
```
$  cd charts/stable/kube-lego
$  helm template .
Error: render error in "kube-lego/templates/deployment.yaml": template: kube-lego/templates/deployment.yaml:36:15: executing "kube-lego/templates/deployment.yaml" at <required "config.LEG...>: error calling required: config.LEGO_EMAIL is a required field
```


```
$  helm template . --set config.LEGO_EMAIL=kevinschumacher@noreply.users.github.com

---
# Source: kube-lego/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-lego
    chart: kube-lego-0.2.0
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
        release: RELEASE-NAME
    spec:
      serviceAccountName: "default"
      containers:
        - name: kube-lego
          image: "jetstack/kube-lego:0.1.4"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: LEGO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # kevinschumacher@noreply.users.github.com
            - name: "LEGO_EMAIL"
              value: "kevinschumacher@noreply.users.github.com"
    ...
```

**Comment by kevinschumacher** [comment]
https://github.com/kubernetes/charts/tree/master/stable/kube-lego#configuration

Note that there is purposely no default value for LEGO_EMAIL as mentioned in the readme.

**Comment by dhilipkumars** [comment]
Hi @jackzampolin and @mgoodness,  
Is it possible to provide a default dummy email address so that this Chart passes in the CI henceforth?

**Comment by jackzampolin** [comment]
`foo@example.com`?

**Comment by dhilipkumars** [comment]
@jackzampolin could you please fix that with a differnt PR please?

**Pull request merged**
