### PR TITLE
[stable/redis] use latest for oliver006/redis_exporter

### PR DESCRIPTION
**Pull request by ghost**
This changes `redis_exporter` tag to `latest`, as `v0.20.2` is not available on mirror.gcr.io.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Images should use fixed tags.

**Comment by carrodher** [comment]
Thanks for the contribution! 
Yes, to avoid breaking changes it's better to use a specific tag instead of `latest`, in the same way, before continue, you need to [sign your existing commits](https://github.com/apps/dco), you can find custom instructions in the “Details” link from the below DCO check, also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by jramos** [comment]
Dumb question: why does `bitnami/minideb` use `latest`?

**Comment by carrodher** [comment]
Well, I just checked other examples and it seems that sometimes we are using `latest` for some exporters and other images used as init containers like busybox (minideb in this case). I agree we should be consistent with that.

In my opinion, as a general rule for "containerized deployments" we should use immutable tags in production; this ensures that your deployment is not affected if a new revision inadvertently breaks existing functionality. Only if you are using containers for development, we can use rolling tags. This ensures that you are always using the latest version. Rolling tags also make it easier to use a specific version of a development tool (such as `node:8` for Node.js 8).

Taking a look at the [Chart best practices about pods](https://github.com/helm/helm/blob/master/docs/chart_best_practices/pods.md#images) it seems that we should use fixed tags.

Should we move to fixed tag all the images present in this repo? I mean, is this a change that should we apply to everything? In the same way, we should take into account in future revisions as @davidkarlsen did this time.
cc @prydonius @unguiculus @desaintmartin

**Comment by desaintmartin** [comment]
I would suggest pinning every version even in values.yaml as 90% of people don't follow values-production.yaml and just "extend" values.yaml.

**Comment by jramos** [comment]
👍 closing in favor of using explicit tags.

**Pull request closed without merging**
