### PR TITLE
[incubator/jaeger] deprecate jaeger

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
Deprecate Jaeger chart.
The chart has moved to https://github.com/jaegertracing/helm-charts/tree/master/charts/jaeger

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

/assign @scottrigby

### CODE REVIEW

**Comment by naseemkullah** [comment]
Also failing in this PR https://github.com/helm/charts/pull/19525

**Comment by cpanato** [comment]
@naseemkullah yep, i will check when i have some time.

**Comment by cpanato** [comment]
@naseemkullah fixed the cluster and the testing are passing now

**Pull request merged**
