### PR TITLE
[stable/opa] - making optional enable or disabled SideEffect-Webhook effect

### PR DESCRIPTION
**Pull request by nullck**
Signed-off-by: Thiago Dias <nullck@gmail.com>

### What this PR does / why we need it:
Make the admissionControllerSideEffect optional to the users, since the Kubernetes version  older than 1.12 doesn't provide support to SideEffect - https://github.com/linkerd/linkerd2/issues/2850

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@nullck 
Would you resolve conflicting files please?

stable/opa/Chart.yaml
stable/opa/templates/webhookconfiguration.yaml

**Comment by yurrriq** [comment]
Rather than suggesting to "set a comment" should we suggest setting the value to `null`?

**Comment by zanhsieh** [comment]
@nullck 
Would you mind to resolve conflicting files first?
stable/opa/Chart.yaml
stable/opa/templates/webhookconfiguration.yaml

**Comment by nullck** [comment]
> @nullck
> Would you mind to resolve conflicting files first?
> stable/opa/Chart.yaml
> stable/opa/templates/webhookconfiguration.yaml

sure sorry for my delay @yurrriq

**Comment by nullck** [comment]
I was considering here to close this PR since this is something that support an older Kubernetes version 1.10.X and we're not suppose to provide support for this version anymore.

**Pull request closed without merging**
