### PR TITLE
[stable/redis-ha] fix: sentinel depl should use resources.sentinel

### PR DESCRIPTION
**Pull request by tuananh**
sentinel deployment should use resources.sentinel instead of resources.master

### CODE REVIEW

**Comment by tuananh** [comment]
can someone take a look at this? this is quite essential in production because in production, resource request for master and replica are quite high while current chart setting for sentinel use master resource, which make it very wasteful.

**Comment by smileisak** [comment]
@tuananh thank you for your PR. @viglesiasce can you review this one. Or how can i request kubernetes org membership ?

**Pull request merged**
