### PR TITLE
[stable/prometheus] Prometheus 2.13.0

### PR DESCRIPTION
**Pull request by Gottox**
Signed-off-by: Enno Boland <mail@eboland.de>

#### Is this a new chart
No

#### What this PR does / why we need it:
This PR updates the prometheus chart to the latest releases
#### Which issue this PR fixes
No

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
looks like alertmanager is not starting
```
NAME                                                       READY   STATUS             RESTARTS   AGE
prometheus-o7c1wygmrh-alertmanager-5764884567-p7dwp        1/2     CrashLoopBackOff   5          3m59s
prometheus-o7c1wygmrh-kube-state-metrics-797d5f59c-rlrf7   1/1     Running            0          7m16s
prometheus-o7c1wygmrh-node-exporter-429q5                  1/1     Running            0          7m16s
prometheus-o7c1wygmrh-node-exporter-4jnt8                  1/1     Running            0          7m16s
prometheus-o7c1wygmrh-node-exporter-q62qj                  1/1     Running            0          7m16s
prometheus-o7c1wygmrh-pushgateway-868bd4bdd-zr6zz          1/1     Running            0          7m16s
prometheus-o7c1wygmrh-server-694bc944fc-fvw7r              2/2     Running            0          7m16s
```

**Comment by Gottox** [comment]
Thanks for the hint, I'm looking into it.

**Pull request closed without merging**
