### PR TITLE
[stable/redis] s/PostgreSQL/Redis

### PR DESCRIPTION
**Pull request by cihangir**

### CODE REVIEW

**Comment by cihangir** [comment]
Bump to verify CLA

**Comment by mattfarina** [comment]
Note, this is a doc only change and could be merged without bumping the version. Bumping versions with docs is on the agenda for charts chat. After that meeting I'll come back with more (unless someone else comes and merges first)

**Comment by cihangir** [comment]
Hey @mattfarina Do you guys need anything more for this PR?

**Comment by mattfarina** [comment]
Due to merge issues (from bumping the version) I manually merged (preserving the author). See 599b41c1031863635d0ec8fa4deb8cb8cc4b28fb

**Pull request closed without merging**
