### PR TITLE
[stable/stolon] support secrets for initdb pod

### PR DESCRIPTION
**Pull request by paprickar**
#### What this PR does / why we need it:
It allow the usage of the superuser username and password inside the initdb pod.
It provide a optional secret for the initdb pod to add an initial db user.

#### Special notes for your reviewer:
The additionalUserSecret for the initdb pod is optional and by default not used

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lwolf** [comment]
Hi @paprickar, could you provide more details about this change?
I understand half of it - where you making possible to provide superuser using the secret, but "additional" is not clear to me.

**Comment by paprickar** [comment]
Hey @lwolf 

sure the Idea is that with such [additional secret ](https://github.com/helm/charts/blob/bf897a550975c1c65e8579024bfaaa71ff67a61d/stable/stolon/values.yaml#L189 ) you can pass for example an application username and password to the [initdb pod](https://github.com/helm/charts/blob/bf897a550975c1c65e8579024bfaaa71ff67a61d/stable/stolon/values.yaml#L198)

With that you can execute the helm chart and have a ready to use database with an extra (none-superuser) secret for the application.

**Comment by lwolf** [comment]
I can see the usecase for this, but I don't think current implementation will scale. I can imaging multiple follow-up PRs from people who want to add 2,3,4,5,6 users.
I'd like to have a more generic solution here, something like providing list of k8s secret to the initdb, mounting all of them to the filesystem and then using standard initdb scripts to export or read those.

**Comment by paprickar** [comment]
valid point - would you be fine If I remove the additional secret part and for this PR we only include the usage of superuser secret inside the initdb?

**Comment by lwolf** [comment]
yes, sure

**Comment by paprickar** [comment]
Ok let me know if we can merge it

**Pull request merged**
