### PR TITLE
[stable/prometheus] Forcing a new line to be created in the configmap yaml generation

### PR DESCRIPTION
**Pull request by dwardu89**
**What this PR does / why we need it**:
This PR fixes the yaml generation for the "prometheus.yml" file. Without this, prometheus-server will not start due to the malformed configuration YAML.
Without this bug, the yaml generated will contain the following:
```
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_namealerting:
```
This will force a new line to solve the problem and make the generated YAML valid:
```
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      alerting:
```
**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by flemzord** [comment]
Please merge this pull request for fix prometheus deployement.

**Comment by dwardu89** [comment]
@flemzord This is failing becuase the pull-charts-e2e fails to successfully deploy the prometheus deployment. I believe this is another problem that's not related to this pull request.

**Comment by timstoop** [comment]
/lgtm
@mgoodness Seems good, right?

**Comment by mblaschke** [comment]
Please merge as we can confirm this issue for multiple environments.

**Comment by gianrubio** [comment]
@dwardu89 CI is failing, could you bump the chart to v6.3.2?

` echo 'Error please increment the new chart version to be greater than the existing version of 6.3.1' `

**Pull request merged**
