### PR TITLE
[stable/cockroachdb] bump to 19.1.3

### PR DESCRIPTION
**Pull request by rytaft**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by joshimhoff** [comment]
Reviewing now.

**Comment by joshimhoff** [comment]
Commit needs to be formatted like this (signoff is needed):

https://github.com/helm/charts/pull/14864/commits/9d8882a23b093501def9bb603cf26ecd60ae3cf0

See here:

https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by rytaft** [comment]
Fixed - thanks!

**Pull request merged**
