### PR TITLE
[incubator/elasticsearch] Configurable override names

### PR DESCRIPTION
**Pull request by siwyd**
As per current recommendations, add fullnameOverride options to the helpers file.

### CODE REVIEW

**Comment by siwyd** [comment]
@simonswine Would you be able to review this if possible?

**Comment by unguiculus** [comment]
I wonder if we really want separate fullnameOverrides for the individual components or just do something like this:

```
{{/*
Create a fully qualified client name.
*/}}
{{- define "elasticsearch.client.fullname" -}}
{{ template "elasticsearch.fullname" . }}-client
{{- end -}}
```

**Comment by unguiculus** [comment]
cc @icereval @simonswine

**Comment by yurrriq** [comment]
I am strongly in favor of a unified `fullnameOverride` approach.

**Comment by siwyd** [comment]
@unguiculus I pushed an update, let me know what you think.

**Comment by siwyd** [comment]
By the way, I wanted to pipe the output in order to truncate it to 63 chars, but couldn't get the following working:
```
{{- printf "%s-%s" (template "elasticsearch.fullname" .) .Values.client.name | trunc 63 | trimSuffix "-" -}}
```
Was getting this error:
```
Error: parse error in "elasticsearch/templates/_helpers.tpl": template: elasticsearch/templates/_helpers.tpl:2: unexpected <template> in parenthesized pipeline
```
Couldn't quite figure out how to fix it.

**Comment by sfrique** [comment]
This PR changes the pv/pvc names, so if user tries to upgrade, it should lose all data. 
Shouldn't this change the major version? of the chart?
It's already merged but...
@unguiculus 
@yurrriq 
@icereval

**Comment by yurrriq** [comment]
A major version bump makes sense. This wasn't an issue for me, since we weren't expecting the data to persist anyway.

**Pull request merged**
