### PR TITLE
[incubator/kafka] Add Prometheus Operator PrometheusRules

### PR DESCRIPTION
**Pull request by cablespaghetti**
#### What this PR does / why we need it:
Adds Prometheus Operator PrometheusRule support for deploying of rules/alerts alongside Kafka itself.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@cablespaghetti thanks for submitting this!
/ok-to-test

**Comment by cablespaghetti** [comment]
Amazing thanks @benjigoldberg!

**Pull request merged**
