### PR TITLE
Fix reference to etcdOperator replica count

### PR DESCRIPTION
**Pull request by dmyerscough**
Fix reference to `replicaCount` for the etcd-operator.

### CODE REVIEW

**Comment by mattfarina** [comment]
@dmyerscough Thanks for the contribution. Charts are meant to be immutable so any changes increment the version (in the Chart.yaml file). I incremented it for you this time.

**Comment by dmyerscough** [comment]
@mattfarina Thank you for incrementing the number, I overlooked that.

**Pull request merged**
