### PR TITLE
WIP: incubator/kafka 1.0.0

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**: Seeking style/pattern alignment with incubator/zookeeper. 1.0.0.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

I've been sitting on this code too long waiting on my zookeeper PR to merge and circle back (sorry about that) and Prometheus exporting has since landed here upstream.  Please help me get an idea of how to direct my efforts. There are many things here worth merging, but please tell me what you want dropped or changed. I've tried to move things around to simplify the PR diff. 

Disclaimer: I haven't shrink-wrapped the sweeping changes in this PR to the README yet. I'll do that once we can agree on the general approach I'm taking with the PR.

### CODE REVIEW

**Comment by ghost** [comment]
/assign @benjigoldberg

Please note the present WIP nature of this PR.  Wanted to get the convo started. After we agree on general direction, I'll write readme changes and do n=1 n=3 smoke testing.

**Comment by ghost** [comment]
Hi @benjigoldberg.  Could you help me pick a direction for this PR?  If the approach looks wrong, I will either fix it or I will start migrating my users to the pre-1.x pattern.  Thanks!

**Comment by benjigoldberg** [comment]
@josdotso sorry for the delay - last week was a busy one for me at the office. I put time on my calendar to give this an in-depth look tomorrow morning. Expect something tomorrow.

**Comment by benjigoldberg** [comment]
@josdotso I've read through this a few times and honestly I like this PR from top to bottom -- its an excellent cleanup that's been needed for awhile. I also like that it brings us in line w/ the ZK changes.

That being said, this is how I might suggest we can do this. Why don't we create a tracking PR, say `kafka/1.0.0` or something like that, and we can then merge pieces of this into that PR, by functionality. Once its all been merged in and reviewed, we can make the 1.0.0 push into master.

Does that sound reasonable to you?

**Comment by ghost** [comment]
SGTM @benjigoldberg .  Will try to get to work on this asap, but it may be a minute before I can do it.  Thanks!

**Comment by josdotso** [comment]
@benjigoldberg  Can you point me to an example of a tracking PR? Would this be a branch on `helm/charts` for `kafka/1.0.0` where I could PR parts of this PR?  

Definitely want to get this ball rolling. Being on a fork is no fun lol

**Comment by benjigoldberg** [comment]
@josdotso I actually dont see any tracking branches as I described on this repo. I was rereviewing this again just now and I think we can just work through this PR as-is -- its been a quiet time in the kafka chart anyway so I dont think there will be a lot of conflict and merge-noise if it takes us a few days to work through this. If you rebase I will have a look and hopefully the two of us can iterate through the PR and get 1.0 merged in here shortly. Sound ok to you?

**Pull request closed without merging**
