### PR TITLE
[stable/prometheus-operator] Prevent creating empty PrometheusRules.

### PR DESCRIPTION
**Pull request by tiagomeireles**
No

#### What this PR does / why we need it:
Prevent empty PrometheusRules that will fail a release.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by den-is** [comment]
I like that solution,
I have almost pushed different solution https://github.com/den-is/charts/commit/53c4bab604624761a09bce0c20dd3524286398ca
But that PR looks like more programmatic...

That issue has discovered one more possible bug.
What if user has apiserver and kubelet disabled too?
```
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
```
currently it disables only "Down" rules in each group, but creates other rules which won't be healthy

**Comment by vsliouniaev** [comment]
/ok-to-test

@tiagomeireles  thanks for your contribution!
Looks like Chart.yaml needs an update

**Review by vsliouniaev — APPROVED** [review]

**Comment by vsliouniaev** [comment]
@tiagomeireles looks like you just missed another PR merge. Could you please do another bump?

**Comment by tiagomeireles** [comment]
@vsliouniaev I rebased on master. Waiting for CI to pass 🤞.

**Comment by vsliouniaev** [comment]
/lgtm

Thanks!

**Pull request merged**
