### PR TITLE
[stable/elasticsearch-exporter] Fix wrong default value

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What this PR does / why we need it:
`helm install stable/elasticsearch-exporter` with default values and the exporter pod fails with:
```
err="failed to get index stats from localhost://:/_all/_stats: Get localhost:9200: unsupported protocol scheme \"localhost\""
```

Prefixing the url with `http://` is the fix.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Sorry for delay, I thought it had been merged.
/ok-to-test
/assign
Could you rebase?

**Review by desaintmartin — APPROVED** [review]

**Comment by ialidzhikov** [comment]
Rebased.

**Comment by desaintmartin** [comment]
Thanks!
/lgtm

**Pull request merged**
