### PR TITLE
[stable/prometheus-blackbox-exporter] updated docker image to 0.15.1

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* updated docker image to 0.15.1

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Hello,
Have you forgot to actually update the tag in values.yaml? ;)

**Comment by desaintmartin** [comment]
Hello,
Have you forgot to actually update the tag in values.yaml? ;)

**Comment by monotek** [comment]
You're right. Not my brightest day. Sorry :-/

**Comment by desaintmartin** [comment]
Hehe, no problem!
/lgtm

**Pull request merged**
