### PR TITLE
[stable/postgresql] Add desaintmartin as maintainer.

### PR DESCRIPTION
**Pull request by desaintmartin**
**What this PR does / why we need it**:

Since there is no longer any official maintainer of stable/postgresql, I propose myself. Hopefully I am not the only one. :)

List of contributions to this repo: https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Adesaintmartin+

cc @unguiculus for approval
cc @cpanato for reference

### CODE REVIEW

**Comment by cpanato** [comment]
@desaintmartin 
 - need to bump the chart version
 - need to sign the [DCO](https://github.com/helm/charts/pull/7447/checks?check_run_id=14866184)  (https://www.helm.sh/blog/helm-dco/index.html)

and i will defer to the helm charts mantainers to check this

**Comment by desaintmartin** [comment]
Done!

**Comment by cpanato** [comment]
still need to bump the chart version

**Comment by desaintmartin** [comment]
cc @mattfarina @scottrigby 
cc @carrodher as future owner

**Pull request merged**
