### PR TITLE
[stable/consul] allow to add extra annotations to consul

### PR DESCRIPTION
**Pull request by christianhuening**
#### What this PR does / why we need it:
This allows addition of extra annotations to the Consul Statefulset for the consul chart. This is for instance useful to avoid service meshin with linkerd etc.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by brunowego** [comment]
Thanks @christianhuening 👍

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by christianhuening** [comment]
ping

**Pull request closed without merging**
