### PR TITLE
[stable/datadog] Add options to collect events from k8s API

### PR DESCRIPTION
**Pull request by fiunchinho**

### CODE REVIEW

**Comment by seanknox** [comment]
Hi @fiunchinho, this PR appears to change the datadog chart from a DaemonSet to a Deployment. Can you explain your reasoning behind that?

**Comment by fiunchinho** [comment]
Actually, I'm not changing code: I'm adding a new deployment to be able to fetch events from the kubernetes api https://github.com/DataDog/docker-dd-agent#environment-variables

**Comment by seanknox** [comment]
@fiunchinho Could the original DS be modified to collect these additional events? Why is a new resource needed?

**Comment by vreon** [comment]
@seanknox It's a [Datadog limitation](https://github.com/DataDog/docker-dd-agent#environment-variables-1):

> Note: only one agent should have `KUBERNETES_COLLECT_EVENTS` set per cluster.

**Review by seanknox — CHANGES_REQUESTED** [review]
Hi @fiunchinho, can you:

- rebase your branch 
- bump the chart "minor" version (major.minor.patch)

**Comment by fiunchinho** [comment]
Done @seanknox . If there is anything else that needs to be changed before mergin, please let me know! Thanks

**Comment by seanknox** [comment]
@k8s-bot ok to test

**Comment by seanknox** [comment]
Thanks @fiunchinho! will merge after CI is green.

**Review by seanknox — APPROVED** [review]

**Comment by olalonde** [comment]
Would be nice to add a note about collectEvents in the README.md

**Pull request merged**
