### PR TITLE
[stable/cockroachdb] Upgrade CockroachDB version to v2.1.1

### PR DESCRIPTION
**Pull request by BramGruneir**
Signed-off-by: Bram Gruneir <bram@cockroachlabs.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by BramGruneir** [comment]
ah, the title is wrong, fixing it.

**Review by a-robinson — COMMENTED** [review]
Thanks! But you also need to update the `ImageTag` value in values.yaml

**Review by a-robinson — APPROVED** [review]
LGTM

**Pull request merged**
