### PR TITLE
[stable/prometheus-operator] Fix ordering

### PR DESCRIPTION
**Pull request by codinaut**
#### Is this a new chart
No.

#### What this PR does / why we need it:
Fix ordering in the documentation, just to make it consistent.

#### Which issue this PR fixes
_Nothing._

#### Special notes for your reviewer:
_Nothing._

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by codinaut** [comment]
I just changed `README.md`. Nothing changes at all in the chart. Does still it require a version bump?

**Comment by bismarck** [comment]
@codinaut Linter won't pass if you don't bump the version.

**Comment by codinaut** [comment]
@bismarck Please check again. Thank you. I've bumped it. 🚀

**Pull request merged**
