### PR TITLE
[stable/jenkins] Support custom master pod labels in deployment (#9714)

### LINKED ISSUE #11508: [stable/jenkins] Support jenkins pod labels
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I want to be able to put labels on the pods created by the deployment, within the podspec for the deployment. Like what originally was done here: https://github.com/helm/charts/pull/10533#issuecomment-453583975
**Version of Helm and Kubernetes**:

**Which chart**:
Jenkins

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by erihanse**
(#11508)

Signed-off-by: Erik Aaron Hansen <erikaron.hansen@drift.oslo.kommune.no>

#### What this PR does / why we need it:
We need to set custom labels on the master pod, for network policy reasons. 

#### Which issue this PR fixes
  - fixes #11508

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by erihanse** [comment]
@maorfr

**Comment by maorfr** [comment]
/lgtm

Thanks for contributing!

**Pull request merged**
