### PR TITLE
Adding the option to pass in parameters to Traefik chart

### PR DESCRIPTION
**Pull request by boxrick**
#### What this PR does / why we need it:

This is a simple change to allow a list of parameters to be defined which
can be used to add extra options to the start of Traefik.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

Signed-off-by: Rick Box <boxrick@gmail.com>

### CODE REVIEW

**Review by mathieuherbert — APPROVED** [review]

**Comment by boxrick** [comment]
Any more updates with this?

**Review by mmatur — APPROVED** [review]
/lgtm

**Pull request merged**
