### PR TITLE
[stable/influxdb] add member

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Victor Login <batazor111@gmail.com>

#### Which issue this PR fixes
solve #13867

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by mattfarina** [comment]
cc @jackzampolin

**Comment by maorfr** [comment]
/unassign @mattfarina 
/assign @jackzampolin 

would appreciate if the existing owner approves of this :)

**Comment by maorfr** [comment]
@jackzampolin, i've sent you an invitation to collaborate on this repo :)
after you accept the invitation, you can `/assign` yourself (and many additional commands become available).

**Pull request closed without merging**
