### PR TITLE
Fix formatting of table with parameters in PosgreSQL README.md

### PR DESCRIPTION
**Pull request by kodeva**
#### What this PR does / why we need it:
This PR fixes formatting of the table with PostgreSQL parameters in the PostgreSQL chart README.md.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Can you sign the commit (commit --amend -s)?
/ok-to-test

**Comment by carrodher** [comment]
Hi, thanks for the contribution, it seems there are some duplicated PR fixing the same issue:
https://github.com/helm/charts/pull/9772
https://github.com/helm/charts/pull/9747
https://github.com/helm/charts/pull/9775

I prefer to go ahead with the latest one (https://github.com/helm/charts/pull/9775) because it fixes another grammar typo, in the same way, it has the commit signed, only it is pending to bump the chart version.

**Comment by kodeva** [comment]
Sure, I gonna close this one.

**Pull request closed without merging**
