### PR TITLE
[stable/percona-xtradb-cluster] Update Stateful Set APIVersion to `apps/v1` - Mandatory for k8s 1.16

### PR DESCRIPTION
**Pull request by dabde**
Signed-off-by: Denis Dabischa <denis.dabischa@kloeckner.com>

#### What this PR does / why we need it:
Update APIVersion endpoint for Stateful set to work with k8s 1.16+

#### Special notes for your reviewer:
API Endpoint is already usable since k8s 1.9. 

## Reviewer:
@username.taken@gmail.com 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by kandy** [comment]
Duplicate of https://github.com/helm/charts/pull/22236

**Comment by dabde** [comment]
Not needed anymore.

**Pull request closed without merging**
