### PR TITLE
[stable/dex] Update dex to 2.16.0, rollout deployment when configuration change

### PR DESCRIPTION
**Pull request by desaintmartin**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by dcardozoo** [comment]
Hi, Could you please add a README for the chart?

**Comment by desaintmartin** [comment]
Although it is a good idea, I think this is out of scope of this PR and I don't have currently any time to do it.

I realize there is no OWNERS file here, so I've just added one with myself (hopefully I won't be alone in maintaining this) and I summon @davidkarlsen.

**Pull request merged**
