### PR TITLE
[stable/sonarqube] remove redundant test pod from sonarqube chart

### LINKED ISSUE #15486: [stable/sonarqube] test pod re-created on every run
**Describe the bug**

The ui test pod is recreated on every apply as it uses a random id to name the pod. 
This causes helm diff to always diff, and also the pod to run every time we do an apply. 
I am curious to know why this even runs when we have liveliness and readiness probes?
Do you think i can just make a PR to delete this @rjkernick ?

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
Sonarqube

**What happened**:
The chart always diffs.

**What you expected to happen**:
The chart should not diff.

**How to reproduce it** (as minimally and precisely as possible):
Try and apply the chart with no changes.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by willejs**
#### What this PR does / why we need it:

This removes redundent bats tests that are covered by the liveliness and readiness probes. 

#### Which issue this PR fixes
  - fixes #15486

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by rjkernick** [comment]
The purpose of those files is to be able to run the command "helm test" on the chart. They are not redundant.

**Comment by willejs** [comment]
🤦‍♂ Sorry, I obviously was not paying attention here. I didn't see the hook to indicate they were actually tests and was confused as they were not in the tests directory. I have updated the pr to put them in the right directory, and removed the randAlphaNum suffix in favour of using the appropriate `--cleanup` flag on helm test so they don't diff anymore.

**Pull request merged**
