### PR TITLE
[incubator/fluentd-elasticsearch] added annotations to values for prometheus scraping

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: adds possibility to add annotations via values.yaml of https://github.com/kubernetes/charts/tree/master/incubator/fluentd-elasticsearch, so you can enable prometheus scraping of the daemon set pods

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by timstoop — CHANGES_REQUESTED** [review]
Looks good and is a useful change. However, I'd prefer to see the option added to the README as well.

**Comment by monotek** [comment]
@timstoop 
added missing values to readme table.

**Pull request merged**
