### PR TITLE
[stable/nats] Add support for extraArgs to NATS

### PR DESCRIPTION
**Pull request by Will2817**
Signed-off-by: William Clifford <Will.Clifford@qlik.com>

#### What this PR does / why we need it:
This PR adds the ability to template in additional flags to the gnatsd process.

I have a use case, when using a custom NATS image, where additional custom flags need to be set.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by seriousben — APPROVED** [review]
LGTM

**Comment by carrodher** [comment]
Thanks for the PR, before continue, it seems you need to resolve some conflicts

**Comment by Will2817** [comment]
@carrodher All fixed up 😄

**Pull request merged**
