### PR TITLE
[stable/falco] Add affinity to falco chart

### PR DESCRIPTION
**Pull request by cw-sakamoto**
Signed-off-by: cw-sakamoto <sakamoto@chatwork.com>

#### What this PR does / why we need it:
- We need to use `affinity`(not `nodeSelector`) in falco

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by cw-sakamoto** [comment]
Thanks for good the product maintenance.
/assign @nestorsalceda

**Review by aixeshunter — APPROVED** [review]

**Comment by cw-sakamoto** [comment]
@aixeshunter Thanks approve!
If you have permission, please also send `/lgtm`..

https://github.com/helm/charts/pull/17841

**Comment by cw-sakamoto** [comment]
@aixeshunter 
@nestorsalceda 
@bencer 
Can anyone please do `/lgtm` ... ?

**Pull request merged**
