### PR TITLE
[stable/kibana] Define successful threshold for kibana pod readiness (#9649)

### LINKED ISSUE #9649: Kibana upgrades cause downtime while loading plugins
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: 2.11.0 & 1.10

**Which chart**: stable/kibana

**What happened**: On upgrade, if plugins are also to be installed, the old pod gets terminated before the new pod is completely ready. This is because kibana responds healthy to the health check once before stopping again to load all the plugins.

**What you expected to happen**: The old pod should be set to terminate only after the new pod is completely ready.

**How to reproduce it** (as minimally and precisely as possible): Install the stable/kibana helm chart along with plugins(I used logtrail). Run an upgrade with some change in the values.

**Anything else we need to know**: It works without a problem if `successThreshold` is added to the readiness probe.

### PR DESCRIPTION
**Pull request by mikhailadvani**
Signed-off-by: Mikhail Advani<mikhail.advani@gmail.com>

#### Which issue this PR fixes
  - fixes #9649 

#### Special notes for your reviewer:

* Added the newly introduced variables along with readinessProbe & livenessProbe blocks to the README.

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by compleatang** [comment]
@mikhailadvani this will need a rebase and chart version bump as we have merged a PR in between when you submitted this. PR looks GTG other than that.

**Comment by mikhailadvani** [comment]
@compleatang done

**Comment by compleatang** [comment]
Thanks!

/approve
/lgtm

**Pull request merged**
