### PR TITLE
[stable/presto] Be able to configure connectors

### LINKED ISSUE #19831: Presto for interactive SQL
Our requirement to use presto to access COS data. We have installed presto helm chart on our k8s cluster but not able to configure COS connection with it. Could you please help me to understand what are the steps need to be followed for using presto for interactive SQL connecting to COS data. 

```
kubectl get pod 

my-release-presto-coordinator-6f64697bbc-llb7p      2/2     Running     0          9d
my-release-presto-worker-6857797df8-9qw6b           2/2     Running     6          9d
my-release-presto-worker-6857797df8-bbhp4           2/2     Running     6          9d
my-release-presto-worker-6857797df8-nwv9p           2/2     Running     6          9d
my-release-presto-worker-6857797df8-qgf9x           2/2     Running     0          9d

kubectl exec -it my-release-presto-worker-6857797df8-9qw6b -- /bin/bash               

presto@my-release-presto-worker-6857797df8-9qw6b:/$ presto
presto> show catalog
     -> ;
Error running command: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=404, statusMessage=Not Found, headers={cache-control=[must-revalidate,no-cache,no-store], content-length=[244], content-type=[text/html;charset=iso-8859-1], date=[Thu, 02 Jan 2020 12:59:49 GMT]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
]

```

### PR DESCRIPTION
**Pull request by shawnzhu**
#### Is this a new chart
No.

#### What this PR does / why we need it:

It can not configure presto connectors at all in current presto chart v0.1.1. Which makes this chart less useful when deploying presto (which depends connectors to function).
This PR enables configuration options to specify connectors as inline values or a k8s secret.

#### Which issue this PR fixes
fixes #19831

#### Special notes for your reviewer:
This is a follow up of #20646

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ckdarby** [comment]
@shawnzhu This looks good :). Something we find out selves having to modify in the chart itself sadly is things related to other memory options in `config.properties` because this is unable to be passed into `the values.yaml`

Not sure if we'd want to add into this PR the ability to configure the configurations?

**Comment by shawnzhu** [comment]
@ckdarby may I ask which memory option you want to add/update in `config.properties`? 

I would prefer a separate issue/PR to update `config.properties` since this PR is about configuring catalogs only.

**Comment by ckdarby** [comment]
@shawnzhu Was hoping just to pass anything because there are other options I'd like to pass in there that are unrelated to memory.

Separate PR makes logical sense but might be a couple months for another PR to get merged :(

**Comment by shawnzhu** [comment]
> Separate PR makes logical sense but might be a couple months for another PR to get merged :(

I understand, you assume this PR can be merged sooner :)

**Comment by marceloavf** [comment]
Why to only connect workers to catalog but not coordinator? @shawnzhu

**Comment by shawnzhu** [comment]
@marceloavf see https://prestosql.io/docs/current/overview/concepts.html#worker

> Worker nodes fetch data from connectors and exchange intermediate data with each other. The coordinator is responsible for fetching results from the workers and returning the final results to the client.

So I assume it it worker nodes require catalog configuration files to fetch data from connectors.

**Comment by marceloavf** [comment]
I did add catalog configuration using your PR @shawnzhu but the coordinator still doesn't recognize it, I saw in the presto dashboard that the workers were connected but when I access coordinator CLI it doesn't show up.

**Comment by shawnzhu** [comment]
@marceloavf You're right. I can not list catalogs after removing catalogs folder from presto coordinator. adding it back

**Comment by marceloavf** [comment]
Getting an error after this update @shawnzhu 

```
Error: release presto-release failed: Deployment.apps "presto-release-coordinator" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "catalog-config-volume"
```

**Comment by shawnzhu** [comment]
@marceloavf sorry, fixed in https://github.com/helm/charts/pull/23539/commits/3cfc7e0cd4017b233c989cc318a4ff8eafade17d

**Pull request closed without merging**
