### PR TITLE
[stable/fluent-bit] Configure inputs, outputs, filters and parsers as a collection instead of a map.

### PR DESCRIPTION
**Pull request by marckamerbeek**
#### What this PR does / why we need it:
The configuration of input
Configure inputs, outputs, filters and parsers as a collection instead of a map. No hard-coded if statements in the template. All the components will be generated automatically. 

#### Which issue this PR fixes
This give the ability to add as many inputs, filters, parsers and outputs if you want without using extraEntries.input, extraEntries.outputs....etc

#### Special notes for your reviewer:
It took me quite a lot of work. Please review carefully. This is my first PR, so please be patience...:-)

### CODE REVIEW

**Comment by marckamerbeek** [comment]
@kfox1111 Am I missing something to get approval? This is my first contribution. Please advise...

**Comment by marckamerbeek** [comment]
@edsiper Hi Eduardo, my pull request is still pending and nobody is even answering. Could you please take a look if its worth continue with? I put a lot of effort in it. Thanks in advance

**Comment by marckamerbeek** [comment]
@kfox1111,  @Towmeykaw

This pull request is open for almost two months now, but nobody is responding. I'm willing to merge it again with the master, but I would like to know if its worth it.

**Comment by kfox1111** [comment]
While this looks really good and looks to clean things up, we've struggled a lot with the fact that fluent-bit's using toml and some of the ways they are using the config do not map easily back and forth to yaml. For example, the ordering of inputs, filters, and outputs matter. [input] [filter] [output] [input] [filter] [output] is not the same as [input] [input] [filter] [filter] [output] [output]. :( This patch set runs back into this same problem.

We've gotten pr after pr trying to "fix" the way values work only to trip over and over against this kind of thing. As you can see from the chart too, its getting unweildy in the number of config options that are being added to handle things too.

We spent a significant amount of time trying to come up with the options we have now, and several breaking patches go in only to have to revert.

I'm in general pretty discouraged by this chart at this point.

Frankly, I think it should be used to pull the raw logs from containers and ship them to fluent running in cluster to handle the parsing/modification/filtering/shipping to the real backend. This keeps processing on all the nodes light, and decopules the heavy processing where you can scale it. So having a million config options really distracts from how I think it really should be used. I'm kind of tempted to fork the chart to my own repo, and fix it up to do just the things I think it should do well, and resign as maintainer of this chart so other people can struggle with twisting it in knots.

So. What should we do with this chart? @edsiper any opinions?

Not trying to discourage you. This pr looks to be a good bit of work. But unfortunately this chart has some really tricky corners I think that are non obvious and its only getting worse.

**Comment by Towmeykaw** [comment]
@kfox1111 I was talking about the same thing yesterday. This looks like a promising change but will really need to be looked over so we don't end up in the same place again.

**Comment by marckamerbeek** [comment]
Thanks guys (@kfox1111 @Towmeykaw ) for commenting. Ok...I'll understand the issue you mentioned (I think). Just some wild idea: 

In my opinion the order of the filters should be determined by a field like Tag_Group_Order and not by the position in the config. Or am I talking bull*hit now? If filters (or inputs, outputs) have the same matcher, the Tag_Group_Order should determine the order. 

Filters should always be in between. So the Tag_Group_Order determines the order in the same tagged Inputs, Filters or Outputs. 

My idea should ask some work for @edsiper. 

I can work out an example config if necessary.

**Comment by kfox1111** [comment]
So you would add a field that is sorted by to get all the inputs/filters/outputs to line up within the group? That could work. If there are multiple inputs/filters/outputs within the group, they would need a way to order those as well.

I don't know if helm has a sort function. That may be an issue.

Using arrays in places instead of dictionaries would help possibly, but they also can not easily be merged in helm, just replaced.

I'm also a bit worried about how to map the datatypes. I think toml has some different quoting rules as yaml. So not sure how to get that to generically map.

**Comment by marckamerbeek** [comment]
@kfox1111 My plan was to solve this in fluent-bit itself and not in the configuration files. And as far as I know it will only be applicable on filters. 

`
filters:
  - Name: "parser"
    Match: "kube-services*"
    Tag_Group_Order: 0
  - Name: "kubernetes"
    Match: "kube-services*"
    Tag_Group_Order: 1
`
Will end up in:

`
[FILTER]
    Name parser
    Match kube-services*
    Tag_Group_Order: 0

[FILTER]
    Name kubernetes
    Match kube-services*
    Tag_Group_Order: 1
`

I'm not sure to call it Tag_Group_Order or Match_Order.

@edsiper What do you think?

**Pull request closed without merging**
