### PR TITLE
[stable/ghost] Update values.schema.json to reflect latest format

### PR DESCRIPTION
**Pull request by andresmgot**
#### What this PR does / why we need it:

The annotations for Kubeapps have changed a bit. This PR uses the latest annotations. It also adds support for specifying the size of the MariaDB volume.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by alemorcuq — APPROVED** [review]

**Comment by alemorcuq** [comment]
Thanks!

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by juan131** [comment]
Hi @andresmgot 

Could you please rebase from master and update your branch bumping the version in the **Chart.yaml**?

**Pull request merged**
