### PR TITLE
[stable/mongo] Use stable mongodb version in the chart

### PR DESCRIPTION
**Pull request by tompizmor**
We should be using mongodb 3.6.x as it is the stable version and not 3.7.x that is the development one.

### CODE REVIEW

**Comment by prydonius** [comment]
Is this a potentially breaking change @tompizmor? It should at least be a minor bump since it's switching minor versions.

**Comment by tompizmor** [comment]
in theory, it should not break anything. When we updated to mongo 3.7 there weren't special changes in the chart.

**Pull request merged**
