### PR TITLE
adding logging configs for influx

### PR DESCRIPTION
**Pull request by cpoole**
#### What this PR does / why we need it:
This exposes logging configuration for influx 

#### Special notes for your reviewer:
This PR is needed so that we can enable json structured logs

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpoole** [comment]
@jackzampolin k8s bot says to assign you and then wont let me assign you :thinking:

**Comment by cpoole** [comment]
@jackzampolin bump

**Comment by jackzampolin** [comment]
I'm not super involved in this project anymore. Let me see what I can do here.

**Review by jackzampolin — APPROVED** [review]

**Comment by cpoole** [comment]
@jackzampolin the k8s bot seems to hate you. Thanks for giving it a shot!

@sameersbn maybe you can help out?

**Comment by cpoole** [comment]
@prydonius sorry to ping you, but you've been super helpful in the past and you're a helm org member. Any chance I can get an ok-to-test on this?

**Comment by mamafun** [comment]
Just pass by.
@cpoole seems changes of this PR are already in the master branch?

**Pull request closed without merging**
