### PR TITLE
[stable/jenkins] Changed default value of Kubernetes Cloud name to match one in kubernetes plugin

### PR DESCRIPTION
**Pull request by electroma**
Changed: default value for Kubernetes Cloud name (kubernetes-plugin has hardcoded value "kubernetes"). Without this change each pod template needs to specify "cloud" parameter unless you manually set it to "kubernetes".

See https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/pipeline/PodTemplateStep.java#L23

### CODE REVIEW

**Comment by bacongobbler** [comment]
Considering helm is k8s-specific I think it's fine to hardcode this value. LGTM!

**Comment by electroma** [comment]
@bacongobbler, please let me know how long does it take to merge PR after LGTM?

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
lgtm

**Pull request merged**
