### PR TITLE
[stable/datadog] add ability to use a configmap to provide the

### PR DESCRIPTION
**Pull request by grumpymatt**
datadog-cluster.yaml config file

Signed-off-by: Matthew Gifford <matthew.gifford@railinc.com>

#### What this PR does / why we need it:
Provides ability to configure a configmap to provide the cluster-agent.yaml file for the cluster-agent

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by grumpymatt** [comment]
This is a refactor/fix for PR #17702

**Comment by CharlyF** [comment]
Thanks @grumpymatt 🥇 
/ok-to-test

**Pull request merged**
