### PR TITLE
Always pull latest docker image

### PR DESCRIPTION
**Pull request by kim0**

### CODE REVIEW

**Comment by unguiculus** [comment]
Any reason why you want to do this? We should really stay with stable versions.

**Comment by kim0** [comment]
I had deployed the default 2.0.0, and the autoscaler was breaking with some error relating to the size of my Azure VM. I spent a couple of hours tracking it down, to new code that was merged (that should have solved my problem), but since this was pointing to old docker image, I was still pointing at old code!

Looking at https://hub.docker.com/r/wbuchwalter/kubernetes-acs-engine-autoscaler/tags/ "latest" is really the only tag containing the code that knows about all Azure VM sizes. I am not sure if "latest" by definition is unstable, I am thinking it means latest stable tagged image. In which case, it makes sense to me. If that is not the case, then maybe @wbuchwalter should tag a new docker image and that should be made the default!

**Comment by wbuchwalter** [comment]
Hello,
`latest` is unstable indeed. When something is verified and working I tag using SemVer.
The reason this has not been done yet is mainly because I was in vacation for a few weeks with very limited internet access (and still am for a few days). 
I will push a new tag when I get back.
Note that PR on this repository also usually take a while to be merged (discussed here https://github.com/kubernetes/charts/issues/1471), so the new chart will be first available here: [wbuchwalter/Kubernetes-acs-engine-autoscaler/tree/master/helm-chart](https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/tree/master/helm-chart)

**Comment by mgoodness** [comment]
We do not want to default to using `latest` images. If a user needs to do so, he/she can set it in a values file or on the command line.

**Pull request closed without merging**
