### PR TITLE
feat(chart): Add baseline NiFi chart

### PR DESCRIPTION
**Pull request by sylus**
**What this PR does / why we need it**: Adds NiFi chart (https://nifi.apache.org/)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: N/A

**Special notes for your reviewer**: Went through a variety of NiFi charts and tried to pick the best elements of each. Right now am using my extended docker NiFi image which adds toolkit, but if better can just simply call the official apache/nifi:1.6.0 image.

I realize this might be a bit of back and forth but wanted to get this started!

P.S. A corresponding Kylo charts also has a P.R. https://github.com/kubernetes/charts/pull/5773

## Tasks

- [ ] Leverage apache/nifi:1.6.0 directly and documented how to extend
- [ ] Add more documentation to values.yaml
- [ ] Anything missing?

## Platform Experts

Just including some platform experts to get their take also:

@markap14

### CODE REVIEW

**Comment by sylus** [comment]
@tlvince

**Comment by sylus** [comment]
Currently you need to run with the govcloud/docker-nifi image as we have a few fixes need to bring upstream.

**Comment by juvlarN** [comment]
@sylus what are the changes you made? I've adjusted your template to use the current nifi version straight from the official docker and it seems to be working fine

**Comment by tlvince** [comment]
@sylus I had to make a few slight tweaks to get this to work out of the box (with the official Apache image):

```shell
❯ helm install --name nifi --namespace nifi .
Error: release nifi failed: StatefulSet.apps "nifi" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"nifi", "chart":"nifi-0.0.1", "heritage":"Tiller", "release":"nifi"}: `selector` does not match template `labels`]
```

Downgrading to `apps/v1beta1` was enough.

The `copy-nifi-templates` init container would not start:

```shell
  copy-nifi-templates:
  ...
  Args:
      cp /templates/hello-world.xml /opt/nifi/data/templates/
    State:          Terminated
      Reason:       Error
❯ kubectl logs --namespace nifi nifi-0 copy-nifi-templates
cp: can't create '/opt/nifi/data/templates/': Is a directory
```

I'm using Terraform to create flows rather than via templates, so I simply removed this.

Thereafter, NiFi came up fine.

**Comment by whs-dot-hk** [comment]
@sylus There are too may person preferences in your chart

**Comment by maorfr** [comment]
@sylus we meet again :)

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Pull request closed without merging**
