### PR TITLE
[stable/nginx-ingress] Nginx ingress no empty quotes clusterIp

### LINKED ISSUE #19041: [stable/nginx-ingress] Cannot upgrade release with Helm 3
**Describe the bug**
The dreaded "spec.clusterIP: Invalid value" error (fixed in #13646) is back because of Helm 3.
Once the chart has been installed, it is no longer possible to upgrade it regardless of whether `omitClusterIP` has been set.

**Version of Helm and Kubernetes**:
- `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`
- `Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
stable/nginx-ingress

**What happened**:
```
Error: UPGRADE FAILED: cannot patch "nginx-nginx-ingress-controller-metrics" with kind Service: Service "nginx-nginx-ingress-controller-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "nginx-nginx-ingress-controller" with kind Service: Service "nginx-nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "nginx-nginx-ingress-default-backend" with kind Service: Service "nginx-nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**:
I would expect the release to be upgradable after the first deploy.

**How to reproduce it** (as minimally and precisely as possible):
Our values.yml:
```yaml
controller:
  config:
    hsts-include-subdomains: 'false'
    http-redirect-code: '301'
    proxy-body-size: 512m
    server-name-hash-bucket-size: '256'
  controller:
    minAvailable: 1
    replicaCount: 3
  publishService:
    enabled: true
    pathOverride: 'nginx/nginx-nginx-ingress-controller'
  extraArgs:
    annotations-prefix: ingress.kubernetes.io
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: XXX.XXX.XXX.XXX
    healthCheckNodePort: 32619
    omitClusterIP: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: 10254
tcp:
  2222: 'storage/sftp-app:2222'
```

```console
# helm -n nginx install nginx stable/nginx-ingress --values values.yml --wait
NAME: nginx
LAST DEPLOYED: Thu Nov 21 13:04:31 2019
NAMESPACE: nginx
STATUS: deployed
REVISION: 1
TEST SUITE: None
# helm -n nginx upgrade nginx stable/nginx-ingress --values values.yml --wait
Error: UPGRADE FAILED: cannot patch "nginx-nginx-ingress-controller-metrics" with kind Service: Service "nginx-nginx-ingress-controller-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "nginx-nginx-ingress-controller" with kind Service: Service "nginx-nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "nginx-nginx-ingress-default-backend" with kind Service: Service "nginx-nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Anything else we need to know**:
There have already been a few reports in the previous pull request: #13646

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
Please see https://github.com/helm/charts/pull/19146

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #19041

#### Special notes for your reviewer:
#19146 was missing this, because if we keep `quote` we still get empty quotes as values for clusterIp.

As it stands we will still wind up with clusterIP: "" if no value is provided ... just {{ . }} is better since it will not add clusterIP to rendered files if no value is provided, but the user needs to quote any provided values themselves

Also forgot to do it for metrics service in previous PR

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @ChiefAlexander @taharah

**Comment by naseemkullah** [comment]
As it stands we will still wind up with clusterIP: "" if no value is provided ... just {{ . }} is better since it will not add clusterIP to rendered files if no value is provided, but the user needs to quote any provided values themselves

**Comment by ChiefAlexander** [comment]
Please add to the readme what is expected for this to work for users who may need to include that. I think this should also be a minor change as we are changing how someone would set their values files.

**Comment by naseemkullah** [comment]
@ChiefAlexander README updated, I also added a deprecation notice to the commendable `omitClusterIP` workaround as this would make it redundant.

**Comment by naseemkullah** [comment]
@ChiefAlexander had a few hiccups sorry. Chart is ready now! Thanks.

**Comment by ChiefAlexander** [comment]
Thanks for working on this
/lgtm

**Comment by naseemkullah** [comment]
My pleasure and thanks for the quick lgtm @ChiefAlexander

**Comment by naseemkullah** [comment]
Any idea why no artifact was produced??

image

**Comment by naseemkullah** [comment]
It's there now, charts sync every half hour.

**Comment by josefschabasser** [comment]
Hi! I'm on chart version 1.25.0 and tried to upgrade to 1.26.1. I removed the previously supplied clusterIP fields as auggested and sill get the same error.
```
$ helm history nginx-ingress
33              Fri Nov 15 13:48:28 2019        deployed        nginx-ingress-1.25.0    0.26.1          Upgrade complete
34              Thu Nov 28 12:09:04 2019        failed          nginx-ingress-1.26.1    0.26.1          Upgrade "nginx-ingress" failed: cannot patch "nginx-ingress-controller" with kind Service: Service "nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable && cannot patch "nginx-ingress-default-backend" with kind Service: Service "nginx-ingress-default-backend" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
Is there a special upgrade procedure? I was doing this previously and was hoping to remove the kubectl calls:
```
__clusterIP=$(kubectl get services nginx-ingress-controller -o jsonpath="{.spec.clusterIP}")
__clusterIPdefault=$(kubectl get services nginx-ingress-default-backend -o jsonpath="{.spec.clusterIP}")
helm upgrade nginx-ingress stable/nginx-ingress \
    --wait \
    --reuse-values \
    --set controller.service.clusterIP=${__clusterIP} \
    --set defaultBackend.service.clusterIP=${__clusterIPdefault}
```

**Comment by naseemkullah** [comment]
Hi @josefschabasser , I'm afraid my efforts were in vain. I have the same issue and I've given in and am hard quoting the clusterIPs in the values file until I can afford a downtime to re deploy without those values... Sorry :(

**Comment by heidemn** [comment]
@naseemkullah thanks for your efforts to fix this annoying issue.

Is there a remaining chance to fix this properly, or is there no way around hard-coding IP addresses when this issue occurs?
Just for me to understand: Why doesn't your fix work? Is this a limitation of how k8s handles Service resources, or is it a limitation of the Helm template language?

If I understood correctly, this issue at least should't appear for fresh deployments of 1.26.1 or later, right?

**Comment by naseemkullah** [comment]
> @naseemkullah thanks for your efforts to fix this annoying issue.
> 
> Is there a remaining chance to fix this properly, or is there no way around hard-coding IP addresses when this issue occurs?

I've tried just about everything after upgrading to helm3. I think if you are still on helm2 there is more of a chance, try commenting out all the clusterIP values in your values file and see if that works.

> Just for me to understand: Why doesn't your fix work? Is this a limitation of how k8s handles Service resources, or is it a limitation of the Helm template language?
> 
I'm pretty confused and not sure anymore sorry.

> If I understood correctly, this issue at least should't appear for fresh deployments of 1.26.1 or later, right?
That's my understanding and hope

**Comment by heidemn** [comment]
Thanks, will try that when back at work.
I'll also try to assign `null` to the `.clusterIP` values, maybe it has a different effect.

Maybe a stupid question - but is there a difference in Helm between commenting out a value and removing it?

**Comment by naseemkullah** [comment]
> Thanks, will try that when back at work.
> I'll also try to assign `null` to the `.clusterIP` values, maybe it has a different effect.
> 

Please share how it goes!

> Maybe a stupid question - but is there a difference in Helm between commenting out a value and removing it?

Not stupid to me! There is no difference in the resulting rendered template.

**Comment by heidemn** [comment]
I mixed up the PRs, and commented to the other one sorry....
https://github.com/helm/charts/pull/13646#issuecomment-561560417

**Pull request merged**
