### PR TITLE
[stable/datadog] Update datadog cluster agent rbac to create events in k8s

### PR DESCRIPTION
**Pull request by edify42**
### What this PR does / why we need it:
I've seen log outputs from the cluster-agent pod indicating the agent can't create an event in the namespace which external metrics are read by a HPA:
```
'events is forbidden: User "system:serviceaccount:monitoring-development:datadog-development-cluster-agent" cannot create resource "events" in API group "" in the namespace "test-hpa-1"' (will not retry!)
```

#### Special notes for your reviewer:

I didn't open an issue for this. The change was simple enough and seems to not break anything without (vanity update). An extra rbac permission to create and event seems fairly safe in the k8s world.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

Tagging: @clamoriniere  as you were the last maintainer that touched the file 😇

### CODE REVIEW

**Comment by clamoriniere** [comment]
Hi @edify42
Thank you for this fix.
Could you please update the version in the Chart.yaml file

**Comment by edify42** [comment]
> Hi @edify42
> Thank you for this fix.
> Could you please update the version in the Chart.yaml file

Done @clamoriniere

**Review by clamoriniere — APPROVED** [review]

**Comment by clamoriniere** [comment]
thank you @edify42
/lgtm

**Comment by madsonic** [comment]
Missing changelog updates
Shouldnt changelog updates be part of the checklist?

**Comment by clamoriniere** [comment]
@madsonic 
unfortunately we don't control this checklist

**Pull request merged**
