### PR TITLE
[stable/traefik] Added configuration for client certificate authentication

### PR DESCRIPTION
**Pull request by strmj**
Signed-off-by: justurm <1641544+justurm@users.noreply.github.com>

#### What this PR does / why we need it:
This PR adds support for configuring client certificate authentication (2-way-ssl / mutual auth).

The official documentation can be found at https://docs.traefik.io/configuration/entrypoints/#tls-mutual-authentication

#### Which issue this PR fixes
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by justurm** [comment]
Same as #9829

**Comment by somcsel** [comment]
Apologies @justurm, I didn't come across this PR during my search before creating #9829.

**Pull request closed without merging**
