### PR TITLE
Add a new stable chart for Weave Scope.

### PR DESCRIPTION
**Pull request by omkensey**
This PR adds a `weave-scope` chart with two subcharts (`weave-scope-frontend` and `weave-scope-agent`).

### CODE REVIEW

**Comment by omkensey** [comment]
I have signed the CLA, but it was under another e-mail address, and the LF account I created with that address already has this GitHub account associated.  The e-mail I used for this commit is on this GitHub account though, so GitHub properly tagged the commit with my GH account.  I'll contact helpdesk@rt.linuxfoundation.org in the meantime to sort this out.

**Comment by omkensey** [comment]
Bump to see if changing my primary e-mail on GitHub fixes things.

**Comment by omkensey** [comment]
Changed my LF login e-mail to match too.

**Review by unguiculus — CHANGES_REQUESTED** [review]
Thanks for the PR. I hope you'll get the CLA sorted.

Please have a look at our best practices, especially regarding standard labels.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

Also, see chart examples for reference:

https://github.com/kubernetes/helm/tree/master/docs/examples

BTW, creating a new chart with `helm create` Helm 2.5+ will give you an initial experience with best practices applied.

**Comment by omkensey** [comment]
* I see where some labels can probably become annotations (they were labels in the original source manifest from WeaveWorks but don't serve a query purpose any more).
* It looks like also I should consolidate service configuration under a "service" key instead of having those be at the top level of chart valuespace.
* I can probably change the truncation of the fullname from 24 to 63 characters.

Anything else I should specifically look at changing?

**Comment by unguiculus** [comment]
You should also create one file per resource. That would be it for a first round.

**Comment by omkensey** [comment]
I think I figured out my CLA signature issues but I have to rewrite the commit history to fix that (I misfingered doing `git config --global`) -- I'm going to close this PR, fix my repo, make the suggested changes, and do a new PR and reference this one in the commit message, if that's OK.

**Comment by omkensey** [comment]
I tried the Github official fix for a bad committer e-mail, but it did... ^ that.  So I'm going to close and resubmit.

**Pull request closed without merging**
