### PR TITLE
[stable/velero] add priority class helper

### PR DESCRIPTION
**Pull request by branttaylor**
#### Which issue this PR fixes
I believe that this fixes my previous PR's attempt at adding priority classes to Restic and Velero.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by branttaylor** [comment]
@prydonius @nrb 
Anything else I need to do here?

**Review by nrb — APPROVED** [review]

**Comment by branttaylor** [comment]
@nrb @prydonius anything further I can do here?

**Comment by branttaylor** [comment]
@nrb @prydonius @zanhsieh do i need to do something to merge this?

**Comment by nrb** [comment]
@branttaylor Looks like the chart version needs a bump per CI

> ✖︎ velero => (version: "2.3.2", path: "stable/velero") > Chart version not ok. Needs a version bump!

**Comment by branttaylor** [comment]
@nrb fixed

**Pull request merged**
