### PR TITLE
[stable/prometheus-operator]: update rules

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:

updates rules using `hack/sync_prometheus_rules.py`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
Whoa, these look like they're starting to include changes for kubernetes 1.14, and aren't compatible with previous versions of kubernetes, i.e. 1.13 and lower!

This realistically means that we'll need to have two sets of rules and dashboards, one that's compatible with earlier versions and one that works with later versions.

/hold

**Comment by vsliouniaev** [comment]
I think the best way forward here is to lock down the current rules for kubernetes 1.13 and create a new integration to sync rules for kube 1.14 and up. They could be controlled via chart variables, indicating that we should deploy 1.13 vs 1.14 rules

**Comment by vsliouniaev** [comment]
https://github.com/helm/charts/pull/16230 takes care of this requirement

**Comment by vsliouniaev** [comment]
https://github.com/helm/charts/pull/16230 takes care of the requirement to have multiple versions of rules

**Comment by caarlos0** [comment]
this was handled on other PRs AFAIK. Closing. 🙏

**Pull request closed without merging**
