### PR TITLE
Explicitly match the whole string in ingress paths of AM and Prom.

### PR DESCRIPTION
**Pull request by mplzik**
AlertManager's and Prometheus's ingresses are defined with a path
attribute in a form '/whatever/url/'. When using this at a current
version of GCP, this results in a backend configured to:

 * route requests to '/' (literally) to the application,
 * route everythig else to default backend.

The documentation at

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#httpingresspath-v1beta1-extensions

doesn't specify an exact match mode and this was not validated
in other than GCP environment; feel free to do so.

Signed-off-by: Milan Plzik <milan.plzik@ceai.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lachie83** [comment]
@emempi please bump the chart version

**Comment by lachie83** [comment]
please bump the chart version

**Comment by mplzik** [comment]
Okay, I just used a similar template with the path like "/.*" on GCP and got failure due to an invalid path expression. Now I'm not sure who's here to blame -- spec says the path is regex; GCP seems to interpret it as a globbing expression. Any ideas/suggestions?

**Review by gianrubio — CHANGES_REQUESTED** [review]
Is this change required only for GCP? 
I'd rather add the ability to customise the path and adding a note on Readme.md explaining how to use than changing the path to all other users.

**Comment by emempi** [comment]
This is what I'm not sure about; I tried to get more information about what is the authoritative behavior of path, but got no response in IRC. Will retry today and update the PR once I have sufficient amount of information.

**Pull request closed without merging**
