### PR TITLE
[stable/datadog] Add affinity to cluster agent deployment

### PR DESCRIPTION
**Pull request by h3poteto**
#### What this PR does / why we need it:
Affinity parameter is already used in the cluster agent deployment:
https://github.com/helm/charts/blob/0da34dafa56833770430bb7a135cf5f428914196/stable/datadog/templates/cluster-agent-deployment.yaml#L197-L200

But its definition does not exist in `values.yaml`. So I add affinity for the cluster agent in values, and I add it in README.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by clamoriniere** [comment]
Hi @h3poteto 
Thank you for finding this oversight. 
Your PR looks perfect, could you update the `CHANGELOG.md` file too.

**Comment by h3poteto** [comment]
I see, I will update the `CHANGELOG.md`.

**Pull request merged**
