### PR TITLE
[stable/ambassador] Flag ambassador chart as deprecated

### PR DESCRIPTION
**Pull request by Flydiverny**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Flydiverny** [comment]
@nbkrause a pr like this should hide the stable chart on helm hub :) did this on mobile so dco fails :smile: feel free to duplicate pr or I'll see if I remember next time on the laptop

**Comment by nbkrause** [comment]
@Flydiverny Thank you so much for helping out with this!

For my info, where did you find the information that this is how you do this?

**Comment by Flydiverny** [comment]
@nbkrause I looked at a chart I knew was deprecated, and figured that wasn't showing so checked in Monocular (what helm hub is running). But I should have just looked here: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart 😅

**Comment by nbkrause** [comment]
>  But I should have just looked here: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart 😅

🤦

**Comment by Flydiverny** [comment]
@nbkrause ready for merge :)

**Comment by nbkrause** [comment]
Thank you! I really appreciate all of the effort you have put in to maintain this chart!

/lgtm

**Pull request merged**
