### PR TITLE
[stable/sealed-secrets] Do not set port names.

### PR DESCRIPTION
**Pull request by bmcustodio**
#### What this PR does / why we need it:

See https://github.com/bitnami-labs/sealed-secrets/issues/397#issuecomment-618865476.

#### Which issue this PR fixes

https://github.com/bitnami-labs/sealed-secrets/issues/397

#### Special notes for your reviewer:

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mkmik** [comment]
Friendly ping

**Comment by denysvitali** [comment]
@srueg can yo please assign this to @olib963 ?

**Review by denysvitali — APPROVED** [review]
This indeed fixes the problem :+1:

**Comment by denysvitali** [comment]
@stefanprodan , can you please check this PR too?

**Review by srueg — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]
/lgtm

**Pull request merged**
