### PR TITLE
Fix stable/Jenkins correct default values in README

### PR DESCRIPTION
**Pull request by PacoVK**
**What this PR does / why we need it**:  Adjust Jenkins/ Jenkins Slave default Dockerimage and Jenkins slave default tag to the correct version

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by PacoVK** [comment]
Signed

**Comment by lachie83** [comment]
@PacoVK please bump the chart version in Chart.yaml

**Comment by viglesiasce** [comment]
Already fixed in another PR.

**Pull request closed without merging**
