### PR TITLE
[stable/redis-ha] Hotfix for #18166 conditions for haproxy metrics

### PR DESCRIPTION
**Pull request by VLZZZ**
#### What this PR does / why we need it:
- This PR fixes my mistype introduced in #18166.
    I didn't changed conditional statements during migration from exporter to embedded metrics
- Adds explicitly quotation instead of just `toString` for `port because of:
```
Exit code: 1, Message: Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 9, error found in #10 byte of ...|io/port":9101,"prome|..., bigger context ...|metheus.io/path":"/metrics","prometheus.io/port":9101,"prometheus.io/scrape":"true"}
```
helm version:
`client: 2.14.3`
`server: 2.14.3`
#### Special notes for your reviewer:
@DandyDeveloper @ssalaues sorry, completely my fault

```
[ERROR] templates/: render error in "redis-ha/charts/redis-ha/templates/redis-haproxy-service.yaml": template: redis-ha/charts/redis-ha/templates/redis-haproxy-service.yaml:32:20: executing "redis-ha/charts/redis-ha/templates/redis-haproxy-service.yaml" at <.Values.metrics.portName>: nil pointer evaluating interface {}.portName
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
@VLZZZ Another PR is merging now so you will need to re-bump the version. Could you enable the metrics in the ci values so we can catch more of these templating issues in the future?

**Comment by VLZZZ** [comment]
@ssalaues Sure.
I've only enabled metrics by default (not the haproxy itself), and updated Readme.

**Comment by ssalaues** [comment]
We should leave metrics disabled by default as this is the common practice among the charts. Really we only need to enable it here https://github.com/helm/charts/blob/master/stable/redis-ha/ci/haproxy-enabled-values.yaml#L10 for testing in CI

**Comment by VLZZZ** [comment]
@ssalaues thank you, done

**Pull request merged**
