### PR TITLE
[incubator/patroni]add missing permission

### PR DESCRIPTION
**Pull request by ggwpp**
Signed-off-by: ggwpp <p.ponyanan@gmail.com>

#### What this PR does / why we need it:
This PR add missing permission for use `Kubernets`  as DCS. It need permission to create custom service.
```
2019-03-28 04:52:56,017 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 289, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 50, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6820, in create_namespaced_service
    (data) = self.create_namespaced_service_with_http_info(namespace, body, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6905, in create_namespaced_service_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 364, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '4beced09-80d3-4a34-91b5-ae4e33fa1b8f', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 28 Mar 2019 04:52:56 GMT', 'Content-Length': '326'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \"system:serviceaccount:patroni\" cannot create resource \"services\" in API group \"\" in the namespace \"patroni\"","reason":"Forbidden","details":{"kind":"services"},"code":403}
```

#### Special notes for your reviewer:
No change for users who don't want to use this option.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@ggwpp please bump the chart version

**Comment by maorfr** [comment]
/lgtm

thanks for contributing and congrats on your first contribution!

**Pull request merged**
