### PR TITLE
[stable/prometheus-mongodb-exporter] v0.7.0 & other improvements

### PR DESCRIPTION
**Pull request by steven-sheehy**
#### What this PR does / why we need it:
- Bumps version to v0.7.0
- Breaking change in [v0.7.0](https://github.com/percona/mongodb_exporter/releases/tag/v0.7.0) changed args from `-` to `--`
- Switched image to one I maintain since the previous image seems to be unmaintained. Built directly from source Dockerfile. I'm the chart owner so can keep it up to date.
- Removed useless service. There's no clients invoking the exporter except Prometheus and it should not go through a service so that it can scrape all pods.
- Added `podAnnotations` to scrape pods directly
- Added `runAsGroup`
- Made the container port configurable
- Had to remove test pod since I don't know of a way to get another pod's IP without a service.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Stelminator** [comment]
> Removed useless service. There's no clients invoking the exporter except Prometheus and it should not go through a service so that it can scrape all pods.
Using Service annotations really is the canonical way to do this.  Prometheus doesn't actually scrape through the service.  The service is used for "service discovery", in this case, to enumerate the endpoints (Pods) that should be scraped, the annotations telling where and how.  Those endpoints are then scraped directly.  One can also update the service without having to update each pod (imagine if you just wanted to turn things off/on by hand for an emergency or experiment).  Additionally, the service is just convenient when wanting to check if things are working (especially when experimenting).

**Comment by steven-sheehy** [comment]
https://groups.google.com/d/msg/prometheus-users/jDEzVHUUFzw/pdNgbVGsBQAJ

I disagree. Pod scraping is preferred over service scraping by Prometheus maintainers. Besides the overhead maintaining a service that no real clients use, it also causes scrape issues when the pod is terminating.

**Review by cpanato — APPROVED** [review]

**Pull request merged**
