### PR TITLE
[stable/grafana] update grafana & all other docker images - updated labels

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it:
* updated all labels to kubernetes standard (see: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ & https://helm.sh/docs/topics/chart_best_practices/labels/)
* updated grafana to 6.6.1
* updated sidecar image to latest version
* used official curl image with real tag not latest
* updated busybox image to latest version
* updated bats image to latest version & use official repo
* used wget for bats test as curl is not available anymore
* removed useless bats init container
* some readme fixes & additions

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
* chart version raised to 5.0.0 as its a breaking change and --force has to be used to upgrade 
* upgrade info is in the readme

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Comment by wu0407** [comment]
so bad, upgrate from 4,* to 5.0, the deployment spec.selector is immutable , so you need delete deployment to upgrade.

**Comment by monotek** [comment]
Thats the reason its a major version update.

**Comment by wu0407** [comment]
That should add notice in README for upgrate from 4.* to 5.0.

**Comment by monotek** [comment]
https://github.com/helm/charts/blob/master/stable/grafana/README.md#to-500

**Comment by wu0407** [comment]
> https://github.com/helm/charts/blob/master/stable/grafana/README.md#to-500

I known that, but  the `--force`  which mean  force resource updates through a replacement strategy.  it is not mean ` delete the resource `.
addition this `helm upgrade  grafana   --cleanup-on-fail` is useless.

**Comment by monotek** [comment]
workaround:
```
#!/bin/sh
release=<release>
namespace=<release_namespace>
kubectl delete statefulset -n "$namespace" -l app=grafana -l release="$release" --cascade=false
kubectl label pod -n "$namespace" -l app=grafana -l release="$release" app.kubernetes.io/instance="$release"
helm upgrade --install grafana stable/grafana --namesapce=$namespace
```

**Pull request merged**
