### PR TITLE
[stable/elasticsearch] Rolling update statefulset  on configmap change

### PR DESCRIPTION
**Pull request by melifaro**
#### What this PR does / why we need it:
Currently StatefulSets ignore updates of the ConfigMap.
This PR suggest performing the rolling update if updateStrategy.type is set to RollingUpdate.
I'm not sure that it worth to introduce a separate value for it, so the feedback is highly appreciated.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by melifaro** [comment]
Sorry for the typos in the initial PR, I'm done fixing them. Also checksum for the client deployment is added. 
Is there any chance to review it?

**Review by anas-aso — APPROVED** [review]

**Comment by melifaro** [comment]
One more fix: I've moved checksum/config to spec.template.metadata.annotations, where it belongs. You can test that rolling updates work with this version.

**Comment by melifaro** [comment]
@desaintmartin can you please have a look?

**Comment by svenmueller** [comment]
@simonswine maybe you have some spare time for reviewing this PR?

**Comment by desaintmartin** [comment]
I'm sorry, I was slow at answering.
If you re-create it and assign me, I'll review it, this is an interesting feature.

**Pull request closed without merging**
