### PR TITLE
[newrelic-infra] Update to 1.7.0 and add OWNERS

### PR DESCRIPTION
**Pull request by jfjoly**
Signed-off-by: JF Joly <joly.pro@gmail.com>

#### What this PR does / why we need it:
This PR 
- updates the New Relic infrastructure daemon set to version 1.7.0.
- adds a OWNERS file to this chart

#### Note to reviewers
We, New Relic, are willing to keep the helm chart up to date with the latest version of our daemon set; to do so more efficiently, I'm adding a OWNERS file with New Relic people + @rk295 who has been active in maintaining this chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jfjoly** [comment]
@rk295 @areina @douglascamata Could you please review this PR?

**Comment by rk295** [comment]
Gah, I thought I had out an OWNERS file in this chart 🙁. Approved from my point of view.

**Comment by jfjoly** [comment]
I'm adding a OWNER file now

**Comment by jfjoly** [comment]
I added a OWNERS file and update both the PR description and the head comment.
I hope that clarifies the intent which is to keep this chart updated.

**Comment by jfjoly** [comment]
@scottrigby Would you please take a look at this PR? Thanks for your help!

**Comment by verwilst** [comment]
Please rebase your changes to latest master.

**Comment by jfjoly** [comment]
@verwilst done, rebased and ready for merge!

**Review by unguiculus — CHANGES_REQUESTED** [review]
Owners should also be added as maintainers in `Chart.yaml`.

**Comment by unguiculus** [comment]
I invited everyone as collaborator. That's necessary for OWNERS files to work.

**Comment by jfjoly** [comment]
Thanks @unguiculus I added the Owners in Chart.yaml.

**Review by unguiculus — APPROVED** [review]

**Pull request merged**
