### PR TITLE
mongodb-0.4.6: bump `bitnami/mongodb` image to version `3.4.2-r0`

### PR DESCRIPTION
**Pull request by dgomezleon**

### CODE REVIEW

**Comment by sameersbn** [comment]
deploying the chart prints the message `*** New version available: run docker pull bitnami/mongodb:3.4.2-r0 to update. ***` when this is the version already being used.

**Comment by sameersbn** [comment]
the issue has need resolved. lgtm

**Comment by lachie83** [comment]
looks like there's a bunch of commits here that aren't part of this PR. Can you clean this up?

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Pull request merged**
