### PR TITLE
[stable/aerospike] Add fullnameOverride for aerospike

### PR DESCRIPTION
**Pull request by okgolove**
Signed-off-by: Mikhail Naletov <okgolove@markeloff.net>

#### What this PR does / why we need it:
To be able to override resources' names is an important thing. Aerospike chart hasn't had this feature and I've added it.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
only adding the template? not using it anywhere?

**Comment by okgolove** [comment]
Do you mean I should add `fullnameOverride: ""` and `nameOverride:""` within values.yaml?
Because `aerospike.fullname` is already used for naming, for example.

**Comment by maorfr** [comment]
/lgtm

got it!

**Pull request merged**
