### PR TITLE
allows externally defined default-cert

### PR DESCRIPTION
**Pull request by whereismyjetpack**
Signed-off-by: Dann Bohn <dannbohn@gmail.com>

#### What this PR does / why we need it:
Allows for operators to maintain the default-cert outside of helm. this is useful when using tools such as sealed-secrets, or flux -- allowing operators to keep sensitive data out of git

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md

Thanks!
@krancour @emilevauge @dtomcej @ldez

### CODE REVIEW

**Comment by Art3mK** [comment]
I'm also interested in this, looks like you need to bump version again, as master is already `1.52.6`

**Comment by Art3mK** [comment]
@whereismyjetpack, could you, please, update chart version and assign approver?

**Comment by whereismyjetpack** [comment]
Hi friends! I bumped the version. I'm not sure who to assign this to, i assigned @nmengin  i'm super sorry if i assigned the wrong person

**Comment by Art3mK** [comment]
@whereismyjetpack would you mind to update this?

**Comment by whereismyjetpack** [comment]
I screwed something up royally. just going to close and start over.

**Comment by whereismyjetpack** [comment]
sorry for the french-up. submitted https://github.com/helm/charts/pull/10274

**Pull request closed without merging**
