### PR TITLE
[stable/gocd] Add support for tolerations on both the GoCD server and agent pods

### LINKED ISSUE #18628: [stable/gocd] Add support for specifying tolerations on the GoCD server and agent pods
Add support for specifying tolerations on both the GoCD server and agent pods in order to schedule them on nodes with matching taints.

**Is your feature request related to a problem? Please describe.**
I want to restrict the scheduling of the GoCD server/agent pods to nodes with matching taints in order to have full control of where they end up being scheduled

**Describe the solution you'd like**
Add support for specifying tolerations on the PodSpec's

**Additional context**
ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

### PR DESCRIPTION
**Pull request by pnordh**
Signed-off-by: Pontus Nordh <pontus.nordh@pagero.com>

#### Is this a new chart
No
#### What this PR does / why we need it:
Adds support in the stable/gocd chart for specifying tolerations on the GoCD server/agent PodSpec's

#### Which issue this PR fixes
  - fixes #18628

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by arvindsv** [comment]
It's implemented similar to `affinity` and the defaults are fine (empty). So, this looks fine.

/ok-to-test

**Comment by arvindsv** [comment]
cc: @varshavaradarajan @GaneshSPatil

**Comment by varshavaradarajan** [comment]
Looks good. Thanks for the PR, @pnordh! Do you mind updating the changelog too?

**Comment by pnordh** [comment]
@varshavaradarajan I've now updated the changelog with an entry for 1.19.1

**Comment by pnordh** [comment]
Thanks! :)

**Pull request merged**
