### PR TITLE
[stable/redis] Add password auth to sentinel (#18515)

### LINKED ISSUE #18515: [stable/redis] password not applied to sentinel
**Describe the bug**
The redis-sentinel container is configured with no password required, even when `usePassword` = `true`.
https://redis.io/topics/sentinel describes under "Configuring Sentinel instances with authentication" that the configuration file should contain `requirepass "your password"`

This report is the same as #14446 though that was retracted by the author.

Thus a configuration variable may be needed to allow an unauthenticated sentinel to be used with an authenticated cluster.

**Version of Helm and Kubernetes**:

Helm 2.15.2
Kubernetes 1.14

**Which chart**:

stable/redis

**What happened**:

The password is applied to redis port 6379, but sentinel port 26379 is unauthenticated

**What you expected to happen**:

Both ports require the same password

**How to reproduce it** (as minimally and precisely as possible):

Starting from `values-production.yaml`, set `sentinel.enabled` = `true` and `usePassword` = `true`.
Connect to the sentinel port, sending an AUTH command.

e.g. using py-redis, this will throw an exception, whereas commenting out the password will succeed:
```
import os;
import redis;
connection = redis.Redis(
    host='redis',
    port=26379,
    socket_connect_timeout=500,
    password=os.environ["REDISCLI_AUTH"],
)
```

**Anything else we need to know**:

As mentioned on #14446, adding `printf "\nrequirepass $REDIS_PASSWORD" >> /opt/bitnami/redis-sentinel/etc/sentinel.conf` to the password enabled section of the sentinel config generation looks likely to fix it.

### PR DESCRIPTION
**Pull request by shane-kearns**
Signed-off-by: Shane Kearns <dbgshane@gmail.com>

#### Is this a new chart
No
#### What this PR does / why we need it:
Fixes password authentication not being required for the redis-sentinel when enabled for the cluster.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #18515 

#### Special notes for your reviewer:

I believe this is a breaking change and bumped the chart to 10.0.0 because the python client library throws an exception if a password is provided but not required by the server. However redis-cli silently ignores such errors.
The end user instructions in NOTES.txt already specify to use a password when connecting to sentinel in the example redis-cli command given.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by javsalgar** [comment]
Thanks for the PR! Do you think that this will break other installations? I'm not sure if we should simply update the minor version.

**Comment by shane-kearns** [comment]
I don't think it will break the installation itself. The question is the effect on redis clients deployed by users of the service.

When using the python redis library, and specifying a password with chart 9.4.3:
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set

Because of this, the same client configuration can't trivially talk to both 9.4.3 and new clusters.
This is the reason I am being cautious about labeling it a breaking change in semantic versioning.

On the other hand, the user documentation already said you should specify a password when connecting to sentinel. So it's just a bug that should be fixed.

**Comment by zanhsieh** [comment]
@shane-kearns 
Could you resolve the conflict file please? Thank you.
stable/redis/Chart.yaml

**Comment by shane-kearns** [comment]
@javsalgar Your lgtm got auto removed by the conflict resolution. Could you please review again?
/assign javsalgar

**Comment by zanhsieh** [comment]
@shane-kearns 
Another file conflict needs to resolve. 
stable/redis/Chart.yaml

After that click circle to see if he responds.
image

**Comment by shane-kearns** [comment]
> 
> 
> @shane-kearns
> Another file conflict needs to resolve.
> stable/redis/Chart.yaml
> 

Thanks @zanhsieh - unfortunately the chart.yaml will conflict every time another PR is merged, because of the chart version bump.

> After that click circle to see if he responds.
> image

I do not have those UI elements available, possibly they are only visible to people with certain roles in the project.

**Pull request merged**
