### PR TITLE
[stable/jenkins] add k8s plugin config parameters

### PR DESCRIPTION
**Pull request by BryanHunt**
Signed-off-by: Bryan Hunt <bhunt@nvidia.com>

#### Is this a new chart

No

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

It adds additional configuration parameters to the Kubernetes plugin

#### Which issue this PR fixes

  - fixes # 22212

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by wmcdona89** [comment]
@BryanHunt did you see my [last review](https://github.com/helm/charts/pull/22276#pullrequestreview-412237838) on your previous PR? I posted it before I noticed that you'd closed that PR.

**Comment by BryanHunt** [comment]
@wmcdona89 I missed that.  I'm fine making those changes.  I should be able to get that done today.

**Comment by wmcdona89** [comment]
Thanks but it looks like you missed the period at the end. `tpl` takes 2 arguments with the 2nd being the scope.

**Comment by wmcdona89** [comment]
@BryanHunt thanks for the great PR! these additional options will be very useful.

**Pull request merged**
