### PR TITLE
[stable/prometheus-operator] Add label selector for kube-controller-manager service monitor

### PR DESCRIPTION
**Pull request by maberny**
#### What this PR does / why we need it:

This PR provides a service label selector for the kube-controller-manager service monitor.

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maberny** [comment]
@vsliouniaev Not quite, after upgrading the chart I saw that the kube-controller-manager was no longer getting scraped as it was before with the same configuration. Changing the label selector in the service monitor by hand fixed that.

**Comment by vsliouniaev** [comment]
What are the labels on the kube-controller-manager pods?

**Comment by maberny** [comment]
`k8s-app: kube-controller-manager`

**Comment by vsliouniaev** [comment]
You should set the labels here:
https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L543-L544

To select the pods via the service:
```
kube-controller-manager:
  service:
    selector:
      k8s-app: kube-controller-manager
      component: null
```

**Comment by maberny** [comment]
Oh I somehow missed that.  I'll test it and get back to you ASAP. Thank you for the pointers and quick reply.

**Comment by maberny** [comment]
@vsliouniaev Got around to test it this morning and using what you gave me works.
My mistake was by using the values below i was getting an unwanted ` component: kube-controller-manager` label in the selector
Values:
```
  service:
    port: 10252
    targetPort: 10252
    selector:
      k8s-app: kube-controller-manager
``` 
Service: 
```
  selector:
    component: kube-controller-manager
    k8s-app: kube-controller-manager
```
Using `component: null` fixed it therefore I will close this PR.
Thank you for the help!

**Comment by vsliouniaev** [comment]
np. 

Do you think there are more docs that we should add around this to make it clearer?

**Comment by maberny** [comment]
Yeah it would be a good idea. Just so I understand properly, does the behavior I encountered stem from a helm bug or is it intended?

**Comment by maberny** [comment]
Also rendering the templates locally doesn't reproduce the issue.

**Comment by vsliouniaev** [comment]
The selector is always additive, and that's the default one in the chart, so it was looking for pods that are labelled with both labels. There is actually a helm bug around this, but the chart has some explicit code in it to address the issue and allow you to clear the default selector.

I'm not sure why you wouldn't see this behavior locally, are you just running `helm template` ?

**Comment by maberny** [comment]
Alright. I ran `helm install --dry-run --debug`.

**Pull request closed without merging**
