### PR TITLE
[stable/prometheus] Add support for kube-state-metrics container arguments

### PR DESCRIPTION
**Pull request by terjesannum**
This will e.g. allow for specifying collectors

### CODE REVIEW

**Comment by unguiculus** [comment]
I think we can close this after merging #2124.

**Comment by brancz** [comment]
To me charts, are an abstraction, so if we can do any better with this abstraction we should do that, which is why I added support for individual collectors here: https://github.com/kubernetes/charts/pull/2124

The great thing is that collectors correspond to respective RBAC roles which can automatically be handled here.

I generally try to avoid doing things like "extraArgs", but I can see how it can still be useful. I'm just saying that if there is a need for a specific case let's try and make the best out of the abstraction possibilities :slightly_smiling_face: .

**Comment by viglesiasce** [comment]
I'm not against adding a trap door for extra configurability in cases like this.

**Pull request merged**
