### PR TITLE
owncloud-0.4.4: bump `bitnami/owncloud` image to version `9.1.4-r0`

### PR DESCRIPTION
**Pull request by dgomezleon**

### CODE REVIEW

**Comment by sameersbn** [comment]
lgtm!

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@davidbhlm-github @prydonius version needs to be bumped please

**Comment by sameersbn** [comment]
I think this PR should be closed in favour of #703

**Pull request closed without merging**
