### PR TITLE
Allow overriding of parser for tail input

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
It seems like the `docker` parser has `Time_Keep On` by default.
Some users may want to use a similar parser with `Time_Keep Off` however. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
True! Version number fixed.

**Comment by kfox1111** [comment]
Sorry. A different patch was slipped in that i didn't think would cause a merge conflict. Please rebase and try again.

**Comment by naseemkullah** [comment]
Np @kfox1111, just the chart version, fixed now, but should I bump  to 1.5.0?

**Comment by naseemkullah** [comment]
Seems like there was another conflict. fixed!

**Comment by naseemkullah** [comment]
bump

**Pull request merged**
