### PR TITLE
[stable/prometheus] Add Telemetry port to Kube-state-metrics

### PR DESCRIPTION
**Pull request by lawliet89**
Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

#### What this PR does / why we need it:

Add container port for Kube-state-metrics self telemetry. 

This is automatically enabled in the official Dockerfile: https://github.com/kubernetes/kube-state-metrics/blob/07719e2dce16118f16250ce8a6db91a0e9f6d8c1/Dockerfile#L7

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@lawliet89 
Could you bump the chart to latest version again? Thank you.

**Comment by lawliet89** [comment]
Done

**Pull request merged**
