### PR TITLE
add selector matchLabels

### PR DESCRIPTION
**Pull request by mostafahussein**
**What this PR does / why we need it**:
This PR fixes the following issue that appeared when I tried to deploy the latest release of mongodb chart 4.2.1

```
spec.template.metadata.labels: Invalid value: map[string]string{"app":"mongodb", "chart":"mongodb-4.2.1", "release":"testprojectv1"}: `selector` does not match template `labels` : exit status 1
```

### CODE REVIEW

**Comment by cpanato** [comment]
@mostafahussein you need to bump the version in the Chart.yaml and also sign off your commit

thanks!

**Comment by juan131** [comment]
Is `spec.selector.matchLabels` supported on every K8s API version?

**Comment by mostafahussein** [comment]
@juan131 I have not tested it on different versions of APIs but the same syntax is already written in other templates in mongodb chart - the replicaSet setup -  e.g. [mongodb/templates/poddisruptionbudget-primary-rs.yaml](https://github.com/helm/charts/blob/master/stable/mongodb/templates/poddisruptionbudget-primary-rs.yaml#L13), So I think it's already supported but was missed in the standalone deployment.

**Comment by juan131** [comment]
Hi @mostafahussein 

The main difference on those other templates is that they're using replicasets instead of deployments. I barely remember that there were some issues with that field on some APIs versions with deployments. However, I can't tell you what version was.

**Comment by juan131** [comment]
Anyway, I don't want to block you. I tested and it's working on version **1.11** and **1.10** so it's fine to me.

**Comment by desaintmartin** [comment]
Did that appear on an upgrade of an existing Release? If so, I would suggest NOT adding matchLabels as it will not fix your issue.
See https://github.com/helm/helm/issues/2494, probably caused by https://github.com/helm/charts/pull/6895

For the record, matchLabels is automatically generated from `spec.template.metadata.labels` if not explicitely set.

**Comment by mostafahussein** [comment]
I have not updated an existing mongo installation. I was using an old version of the chart for testing purposes then I have deleted mongodb then tried to use a higher version of the chart. I got this issue after adding `matchLabel` and reinstall it i was able to use the chart however i got a different issue that exists on the current releases of this chart but i wont discuss it in here as this will be out of scope of the current PR

**Comment by desaintmartin** [comment]
To be honest, I just deployed a new mongodb (helm install stable/mongodb) and can't reproduce. Can you describe how to reproduce?
I've been hit many times by this problem (but in my case only while trying to upgrade a Chart where the Deployment labels have been updated).

**Comment by xasor** [comment]
Hello,

Same problem here. Thanks for the PR @mostafahussein 

@desaintmartin try to install an older chart version and then do "helm upgrade" to the latest one. Like this:

```
helm install --name to-delete --version 4.2.1 stable/mongodb
helm upgrade --install to-delete stable/mongodb
```
and check the error

Error: UPGRADE FAILED: Deployment.apps "to-delete-mongodb" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"release":"to-delete", "app":"mongodb", "chart":"mongodb-4.2.2"}: `selector` does not match template `labels`

**Comment by desaintmartin** [comment]
the upgrade problem is (unfortunately) well known (see my previous comments), but is anyone able to reproduce without upgrade?

For the upgrade problem, I would suggest reverting the commit I pointed in an earlier comment. @javsalgar, can you elaborate on this commit or point me to a reference?

**Comment by mostafahussein** [comment]
In fact I am using rancher which i can only repeat the same steps as i mentioned before, i am not sure if this considered fresh installation for the chart or not but i am sure that i am not deploying it as an upgrade for an existing installation.

I will try to deploy `minikube` locally or any other possible way in order to try the chart as a fresh install. Also if someone else was able to deploy the chart and confirm if the issue does not occur that would be helpful.

**Comment by prydonius** [comment]
As far as I can tell, this is a fairly recent regression because we accidentally added a mutable label to the Pod Template labels: https://github.com/helm/charts/pull/6895/files. Thanks for the fix @mostafahussein, I made some changes to remove the mutable label.

**Comment by prydonius** [comment]
@desaintmartin didn't see you also pointed to the introduction of the issue in #6895, thanks!

**Pull request merged**
