### PR TITLE
[stable/datadog] Configure DD_APM_NON_LOCAL_TRAFFIC

### PR DESCRIPTION
**Pull request by stefansedich**
#### What this PR does / why we need it:
Currently when setting `nonLocalTraffic=true` only `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` is configured we possibly also want to set `DD_APM_NON_LOCAL_TRAFFIC=true` so that APM can also receive non-local traffic.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mfpierre** [comment]
Hey @stefansedich thanks for the contribution,

Did you consider using the `env` parameter to set `DD_APM_NON_LOCAL_TRAFFIC` when needed?

https://github.com/helm/charts/blob/0bca75c86881754223ae3eaa6df2a2fe59480526/stable/datadog/values.yaml#L198-L204

**Comment by stefansedich** [comment]
Hi Pierre,

That is exactly what I do right now, however I felt this would be a
valuable addition.

There is an APM tutorial which mentions only setting nonLocalTraffic and
not setting the env var too which is misleading not to mention I would
expect given the name nonLocalTraffic it would accept both non-local apm
and statsd traffic.

Is there any reason why this is not desired?



- Stefan

**Comment by stefansedich** [comment]
@mfpierre the docs in question: https://docs.datadoghq.com/agent/kubernetes/helm/?tab=macoshomebrew#enable-apm-and-distributed-tracing mention nothing about also setting DD_APM_NON_LOCAL_TRAFFIC when using helm, will this even work?

**Comment by stefansedich** [comment]
@mfpierre any more comment here or should I just close this one off?

**Comment by zanhsieh** [comment]
@stefansedich 
Please resolve stable/datadog/Chart.yaml version conflict. Thank you.

**Comment by mfpierre** [comment]
@stefansedich I think we can consider the change especially because the chart setting is really generic `nonLocalTraffic`, so it would make sense to change both dogstatsd & APM.

**Comment by stefansedich** [comment]
@mfpierre great! have rebased and looks like it should be good to go.

**Comment by gespinoza1-chwy** [comment]
> It seems this option doesn't exist anymore.

looking for it as well and its gone

**Comment by clamoriniere** [comment]
Hello @davenewza and @gespinoza1-chwy 

The `Datadog` chart moved since a wild on a dedicated repository: https://github.com/DataDog/helm-charts/tree/main/charts/datadog 

Also `DD_APM_NON_LOCAL_TRAFFIC` is not set to true by default for the Datadog agent containerised version.

Please use the chart present in https://github.com/DataDog/helm-charts/tree/main/charts/datadog and open an issue on https://github.com/DataDog/helm-charts if you still have difficulty to configure APM.

Thanks

**Pull request merged**
