### PR TITLE
[stable/datadog] Expose open_files_limit configuration to chart

### PR DESCRIPTION
**Pull request by dtilsner**
Signed-off-by: Derrick Tilsner <derrick@wearethorn.org>

#### What this PR does / why we need it:
This PR exposes the `open_files_limit` Datadog agent configuration within the helm chart. More details on what this logs config does can be found [here](https://docs.datadoghq.com/logs/faq/how-to-increase-the-number-of-log-files-tailed-by-the-agent/). When a kubernetes cluster contains a large number of pods running on a single node, the Datadog agent can end up tailing log files for performance reasons. By default this limit is set to 100, but there are situations where it is appropriate to override this limit to a higher value.

#### Which issue this PR fixes
See above

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by nicolasbelanger** [comment]
Hey @dtilsner .  Also got caught by the 100 open files limit, so thanks for the PR.  I'm just curious about the usage of the `DD_LOGS_CONFIG_OPEN_FILES_LIMIT` env.  Where did you find this?  I can't find it anywhere in the agent code...

**Comment by srikiz** [comment]
Is this closed because we can configure this using custom agent config as mentioned here - https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L1012

**Pull request closed without merging**
