### PR TITLE
[stable/minio] Add support for s3 compatible service endpoint

### PR DESCRIPTION
**Pull request by Rajik**
#### What this PR does / why we need it:
This PR will let users use a s3 compatible service endpoint while deploying using helm charts - it is possible when using docker image of minio.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Rajik** [comment]
@nitisht @wlan0 Can I get a code review pls?

**Comment by Rajik** [comment]
@nitisht @wlan0 Reminder!

**Comment by nitisht** [comment]
Thanks for the PR @Rajik

**Comment by nitisht** [comment]
Could you also change the line https://github.com/helm/charts/blob/master/stable/minio/templates/deployment.yaml#L85 to 

```
 {{- if and .Values.persistence.enabled (not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) }}
```

Looks like Gateway is not running due to double braces.

**Comment by Rajik** [comment]
@nitisht Made the change!

**Comment by Rajik** [comment]
Thank you @nitisht ,when can I expect it to be merged?

**Comment by Rajik** [comment]
Looks like the tests are not getting triggered :(

**Comment by nitisht** [comment]
> Looks like the tests are not getting triggered :(

Yeah.

Could we pls get a `/ok-to-test` @cpanato

**Comment by Rajik** [comment]
@cpanato Can you please give `ok-to-test` soon?

**Comment by Rajik** [comment]
@cpanato Waiting for your cmd ^^

**Comment by nitisht** [comment]
@Rajik can you close this and send a fresh PR with these changes? I suspect some issue with current PR, `/lgtm` does trigger tests for other PRs in this repo

**Comment by Rajik** [comment]
Ok.

**Comment by Rajik** [comment]
Please refer #11732

**Pull request closed without merging**
