### PR TITLE
 Make nginx controller container ports configurable

### PR DESCRIPTION
**Pull request by ChiefAlexander**
Signed-off-by: ChiefAlexander <alex.harder@fishtech.group>

#### What this PR does / why we need it:

This makes the ports for the nginx-controller container configurable. This was needed to implement https://github.com/kubernetes/ingress-nginx/issues/2724#issuecomment-444835897

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
@mgoodness can you take a look at this please?

**Comment by ChiefAlexander** [comment]
@jackzampolin or @mgoodness Could one of you take a look at this.

**Comment by dene14** [comment]
@jackzampolin
@mgoodness
What else required to have it merged? It's not truly a fix, but a working workaround that we cannot use with current helm chart.

**Comment by ChiefAlexander** [comment]
Can I get any 👀 on this? It has almost been a month with no feedback here. @jackzampolin @mgoodness

cc: @maorfr you approved the last pr into this chart, any feedback that you can give would be helpful.

**Comment by maorfr** [comment]
/assign
/ok-to-test

Very nice and clean. Thanks!

**Pull request merged**
