### PR TITLE
[stable/cluster-overprovisioner] multi deployment option - cleanup old deployment style

### PR DESCRIPTION
**Pull request by dabde**
Signed-off-by: Denis Dabischa <denis.dabischa@kloeckner.com>

#### What this PR does / why we need it:
Cleanup of unneeded backward compatibility of the chart.

#### Which issue this PR fixes
- remove default single deployment to deployments list

#### Special notes for your reviewer:
@max-rocket-internet 
@mmingorance-dh 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by mmingorance-dh — COMMENTED** [review]
Looks fine to me
@max-rocket-internet wdyt?

**Review by max-rocket-internet — APPROVED** [review]
Nice!

**Comment by Ghazgkull** [comment]
@max-rocket-internet Just stumbling upon this change now. It looks like this was a breaking change to the chart. Should it have come with a major version bump? In lieu of that, is it possible to update the README with a short little upgrade guide informing consumers of the breaking change and maybe giving an example showing how to deploy with N replicas now?

**Comment by max-rocket-internet** [comment]
@Ghazgkull ah yes, should have definitely been a major release version bump.

I think the comment in the default values.yaml is enough though? https://github.com/helm/charts/blob/master/stable/cluster-overprovisioner/values.yaml#L19-L27

**Pull request merged**
