### PR TITLE
adding endpoints resource permissions

### PR DESCRIPTION
**Pull request by julian3xl**
as described in kubernetes-sigs/external-dns#1005 now external-dns uses endpoints resource so it needs permissions to do it

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by julian3xl** [comment]
I don't know why it stays failing on lint because it succeeded https://circleci.com/gh/helm/charts/126790

**Comment by julian3xl** [comment]
I don't know what I have to do to fix version bumping lint error, please help

**Comment by julian3xl** [comment]
any news here? this chart is broken right now using headless, could you please merge this if you're happy with it?

**Comment by miguelaeh** [comment]
Hi @julian3xl ,
Thank you very much for the PR, as you can see here: https://github.com/helm/charts/tree/master/stable/external-dns#this-helm-chart-is-deprecated, this helm chart has been deprecated, could you open the PR at https://github.com/bitnami/charts instead, please?

**Comment by julian3xl** [comment]
Hi miguel, I also did it there https://github.com/bitnami/charts/pull/2035 but it seems nobody is handling requests there, and this is an urgent patch I guess :(

**Comment by julian3xl** [comment]
I'm closing this PR because @miguelaeh merged it on the new repository. Thanks so much!!!

**Pull request closed without merging**
