### PR TITLE
[stable/cerebro] Adding wvidana as collaborator

### PR DESCRIPTION
**Pull request by wvidana**
Volunteering as collaborator, per issue https://github.com/helm/charts/issues/13867

Past contributions to cerebro chart:
  - https://github.com/helm/charts/pull/14506

Past contributions to other helm charts:
  - https://github.com/helm/charts/pull/14196
  - https://github.com/helm/charts/pull/14189
  - https://github.com/helm/charts/pull/13667
  - https://github.com/helm/charts/pull/13666
  - https://github.com/helm/charts/pull/13665

### CODE REVIEW

**Comment by wvidana** [comment]
@davidkarlsen This PR is to volunteer as collaborator per issue https://github.com/helm/charts/issues/13867

**Comment by wvidana** [comment]
@davidkarlsen ping

**Comment by davidkarlsen** [comment]
See "Owning and maintaining a chart" at https://github.com/helm/charts - step 3) add OWNERS to .helmignore file (and then I don't think the chart-version needs to be bumped).

Did you receive an invite from github?

**Pull request merged**
