### PR TITLE
Fixing restic env issue #15998

### LINKED ISSUE #15998: [stable/velero] Restic daemonset AWS_SHARED_CREDENTIALS_FILE variable
**Describe the bug**
`AWS_SHARED_CREDENTIALS_FILE` environment variable should be skipped/removed if we disable `useSecret` in values file. 

**Version of Helm and Kubernetes**:
Helm version - v2.14.3. 
Kubernetes Version - v1.15.1

**Which chart**:
Velero 

**What happened**:
`AWS_SHARED_CREDENTIALS_FILE` environment variable is getting added into restic daemonset even though I disable useSecret `useSecret: false`. 

**What you expected to happen**:
`AWS_SHARED_CREDENTIALS_FILE` environment variable should be skipped/removed if we disable `useSecret` in values file. 

**How to reproduce it** (as minimally and precisely as possible):
1. Disable useSecret - `useSecret: false`.
2. Change directory to Velero charts.
3. Run - `helm template . --output-dir velero_yaml

**Anything else we need to know**:
N/A

### PR DESCRIPTION
**Pull request by paralika**
#### What this PR does / why we need it:
This PR will gate `AWS_SHARED_CREDENTIALS_FILE` and `GOOGLE_APPLICATION_CREDENTIALS` env  initialization base on `useSecret` value. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #15998

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by hectorj2f** [comment]
please, rebase against master there are some conflicts

**Comment by paralika** [comment]
@hectorj2f conflict has been resolved and changes are ready to review. Thanks!

**Review by hectorj2f — COMMENTED** [review]
/ok-to-test

**Pull request merged**
