### PR TITLE
[stable/grafana] Bump version

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Login Victor <batazor111@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
It seems you included some undesired changes

**Comment by batazor** [comment]
@carrodher @maorfr Made changes

**Comment by maorfr** [comment]
/lgtm

Thanks for contributing!

**Pull request merged**
