### PR TITLE
[stable/airflow] add LoadBalancer IP/SourceRanges config

### PR DESCRIPTION
**Pull request by thesuperzapper**
Adds the following Service configs:
* `airflow.service.loadBalancerIP`
* `airflow.service.loadBalancerSourceRanges`
* `flower.service.loadBalancerIP`
* `flower.service.loadBalancerSourceRanges`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
Could you review this @gsemet?

**Review by gsemet — APPROVED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@gsemet I think my rebase broke it, will fix

**Comment by thesuperzapper** [comment]
@gsemet I have fixed the issue

**Pull request merged**
