### PR TITLE
Submit stable searchlight chart

### PR DESCRIPTION
**Pull request by saumanbiswas**
cc: @sadlil @TamalSaha

### CODE REVIEW

**Comment by seanknox** [comment]
Hi @saumanbiswas, thanks for your contribution! Can you provide some background on what Searchlight is and why it might be relevant in the charts repo?

**Comment by viglesiasce** [comment]
Marking as stale. @saumanbiswas please update within the next week.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by tamalsaha** [comment]
[Searchlight](https://github.com/appscode/searchlight) is an Icinga2 operator that we , AppsCode, have developed. I think this can benefit anyone who wants to monitor their Kubernetes cluster using Icinga2.

**Comment by viglesiasce** [comment]
Closing as stale

**Comment by viglesiasce** [comment]
Didn't notice the new commits fixing issues. Looking at changes now.

**Comment by viglesiasce** [comment]
This still does not install due to the chart being nested in searchlight/searchlight

**Review by viglesiasce — CHANGES_REQUESTED** [review]
Please move this to the stable/searchlight folder otherwise it wont install

**Comment by tamalsaha** [comment]
@viglesiasce , I have update the chart

**Comment by viglesiasce** [comment]
@tamalsaha looks like pods are crash looping:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/953/pull-charts-e2e/2070/

**Comment by tamalsaha** [comment]
Hmm. We are going to change something so that the default chart setup works for searchlight. I am going to update it once ready.

**Comment by viglesiasce** [comment]
Closing as stale.

**Pull request closed without merging**
