### PR TITLE
[incubator/vault] tolerations and nodeSelector

### PR DESCRIPTION
**Pull request by dennybaa**
* Fixed affinity placement bug
* Added missing tolerations and nodeSelector
* liveness and readiness improvments

### CODE REVIEW

**Comment by jbialy** [comment]
@dennybaa , this is great and helps resolve my oversight after originally changing the liveness check. I'm thinking of also adding a `aliveIfSealed` option configurable in the Values. Since technically Vault should be considered "alive" even if it's in a sealed state.

**Comment by jbialy** [comment]
Related to https://github.com/helm/charts/pull/12043.

**Comment by dennybaa** [comment]
@jbialy thanks. I totally agree `aliveIfSealed` is absolutely feasible too, since some installation might use manual unseal and then it's a must. In my case I stick to auto-unseal with the cloud provider KMS help.

**Pull request merged**
