### PR TITLE
[stable/cockroachdb] Refactoring To Use Variables for Naming

### PR DESCRIPTION
**Pull request by devnulled**
#### What this PR does / why we need it:

No changes in functionality; I did some refactoring so that names can be referenced as variables instead of the copy and paste string formatting everywhere. This makes it much easier to make changes to the chart and debug them.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  N/A

#### Special notes for your reviewer:

I linted and tested by making sure the output of the previous version of the chart matched the fork I did the refactoring in. 

The link to the DCO is dead; no idea if I've signed it previously or not.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kannanlakshmi** [comment]
@bobvawter do you have any cycles to take a look at this? Alex is likely not going to get to it till later next week. Thanks!

**Comment by cpanato** [comment]
@devnulled please update your branch

**Comment by devnulled** [comment]
Well bummer, this was a time-consuming patch to make cleanly and having to rebase yet again is going to take me a bit.  Will someone be around to check it again before it goes stale if I rebase and submit again?

**Comment by a-robinson** [comment]
I'm really sorry, @devnulled. If you rebase it this week I'll review it within 48 hours.

**Comment by devnulled** [comment]
@a-robinson No worries, just part of it!  I just wanted to be sure it would get checked out in a reasonable amount of time.  I'll try to get it rebased this week and submit again.  Thanks for being available!

**Comment by a-robinson** [comment]
Any update, @devnulled? I'm still available if you're able to rebase.

**Comment by devnulled** [comment]
Hi @a-robinson, sorry for the delay, have been working on some other Helm charts at work that have taken longer than expected.  Anyway, I will finally pull down the latest changes today and work on reapplying them to the chart.

Somewhat related, and something I would open another ticket for; any appetite for adding an optional (and fully configurable) [Telegraf](https://github.com/influxdata/telegraf) sidecar to this chart so that each cockroachdb pod would have the ability to push out its Prometheus stats?

**Comment by a-robinson** [comment]
> Somewhat related, and something I would open another ticket for; any appetite for adding an optional (and fully configurable) [Telegraf](https://github.com/influxdata/telegraf) sidecar to this chart so that each cockroachdb pod would have the ability to push out its Prometheus stats?

I'm not personally very familiar with Telegraf, but I don't think we want to add it here at this point in time.

**Comment by devnulled** [comment]
I will resubmit this pull request when I get the git history straightened out rather than spam this one with commits.

**Pull request closed without merging**
