### PR TITLE
[stable/nextcloud] Add pod label for Redis network policy

### PR DESCRIPTION
**Pull request by w1ndy**
@chrisingenhaag @billimek

#### What this PR does / why we need it:

To enable the network policy for Redis, pods must be labeled with ``{{ .Release.Name }}-redis-client: "true"`` (see https://github.com/helm/charts/blob/master/stable/redis/templates/networkpolicy.yaml). Since this required pod label is hardcoded into the Redis chart's template, there is no way to change this label to match those defined in the NextCloud chart with chart configurations. Therefore, I propose adding a new label to the NextCloud chart to enable network policies for Redis.

These network policies can be enabled by setting following keys:
```yaml
redis:
  networkPolicy:
    enabled: true
    allowExternal: false
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by billimek** [comment]
@w1ndy thanks for submitting this.

If redis is not enabled, do you know what will happen?  I wonder if we will have a label called simply `-client: "true"` ?

**Comment by chrisingenhaag** [comment]
I‘d also Consider combining labeling only if redis is enabled.

**Comment by w1ndy** [comment]
@billimek @chrisingenhaag 
Thanks for the suggestion! I've added the assertion before applying the redis-client label.

**Pull request merged**
