### PR TITLE
[stable/prometheus-adapter] Fix auth-reader rolebinding

### PR DESCRIPTION
**Pull request by rhockenbury**
#### What this PR does / why we need it:
Fixes an issue with the auth reader role binding to allow the prometheus adapter to read the extension-apiserver-authentication configmap in kube-system. 

The extension-apiserver-authentication-reader role resides in the kube-system namespace so the rolebinding will also need to reside in the kube-system namespace. 

In the metrics-server chart, we can see this rolebinding is correctly set up - https://github.com/helm/charts/blob/c5989490cac32d4ca350c5d2f8928dfebff111b3/stable/metrics-server/templates/role-binding.yaml#L6. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rhockenbury** [comment]
@hectorj2f @MattiasGees Would either of you have time to review this in the near future?

**Comment by scottrigby** [comment]
/hold

Let’s hold PRs to `stable` prometheus charts for a short time until prometheus-community/community#28 (comment) is resolved. If you want to help with that effort, to test etc, that would be great!

**Comment by scottrigby** [comment]
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts).

If applicable, please re-open this PR there. Thanks!

**Pull request closed without merging**
