### PR TITLE
[stable/nextcloud] Create option to specify extra deployment volumes

### PR DESCRIPTION
**Pull request by bklang**
#### Is this a new chart
No

#### What this PR does / why we need it:

This is useful when converting from a legacy NextCloud environment to Kubernetes. Our deployment has data stored in an NFS volume. Using these new options, we can now directly import that volume into our Kubernetes NextCloud pods and migrate the data more easily (or even run the new pods with the old storage).

#### Which issue this PR fixes
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by billimek** [comment]
@bklang one minor request: can you please bump the minor version instead of the patch version?

e.g. change `Chart.yaml` version to `1.10.0` instead of `1.9.7`?

**Comment by bklang** [comment]
@billimek No problem, done! Thanks for the quick review.

**Pull request merged**
