### PR TITLE
Remove ezimanyi as owner of spinnaker chart

### PR DESCRIPTION
**Pull request by ezimanyi**
Lars added me to replace him when he stopped working on Spinnaker, but I've mostly been focused on other aspects of the Spinnaker project and haven't had the time to devote to looking at PRs in this chart repo. Removing myself as I'm not close enough to this chart to be an owner/approver.

### CODE REVIEW

**Comment by mattfarina** [comment]
@ezimanyi In the `Chart.yaml` file you need to increment the `version` field. Just increment the patch part by one. Every change to every chart needs to have the version incremented.

**Comment by ezimanyi** [comment]
@mattfarina: Thanks for catching that, updated now!

**Comment by dwardu89** [comment]
@ezimanyi There is a PR to move off this repository and onto another repository because helm/charts is going to be deprecated. Can you submit your PR changes to https://github.com/dwardu89/helm-charts/ instead please.

#24007

This PR is related to some internal discussions that were sent around to the devs in the OWNERS file.

**Comment by ezimanyi** [comment]
Obsolete as the chart is now deprecated.

**Pull request closed without merging**
