### PR TITLE
fix indentation of 'extraContainers'

### PR DESCRIPTION
**Pull request by agnewp**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zakkg3** [comment]
can you please sign your commits [see this](https://github.com/helm/charts/pull/14284/checks?check_run_id=138034731)
also needs a version bump.
please read the Checklist!
thanks.

**Comment by zakkg3** [comment]
because #14306
/close

**Comment by kozejonaz** [comment]
I know this is already merged in, but I had to revert this to `6` to ensure `extraContainers` was working.

When using 6 as indentation, and something like this as the override
```yaml
extraContainers: |
  - name: some_container
    image: some_image
    etc.
```
it works fine.

I might have missed something, but it looks like it was a mistake changing it to `10`. Please correct me if I'm not using this the correct way.

**Comment by zakkg3** [comment]
Can you open a pr for this please?

**Comment by kozejonaz** [comment]
> Can you open a pr for this please?

Sure thing!

**Comment by kozejonaz** [comment]
> Can you open a pr for this please?

I created https://github.com/helm/charts/pull/14899 :)

**Comment by zakkg3** [comment]
@cpanato Carlos, can you close this one plz. its fixed on https://github.com/helm/charts/pull/14899
thanks
/assign
/close

**Pull request closed without merging**
