### PR TITLE
[stable/kibana]updated kibana to 6.6.1

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### What this PR does / why we need it:
* updated kibana to 6.6.1
* added myself also to maintainers in the Chart.yaml as i'm already in the OWNERS file
* added option to disable dashboard import
* changed readme table indent

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by compleatang** [comment]
👍 

/ok-to-test
/lgtm

**Comment by monotek** [comment]
@compleatang 
I've changed the way how dashboard import is enabled which is a braking change.
Should we update the chart version to 2.0?
Or just use 1.7.0 and add an upgrading section to the readme?

**Comment by compleatang** [comment]
@monotek my view would be we should likely move the chart to 2.0.

**Comment by monotek** [comment]
@compleatang raised chart version to 2.0.0

**Comment by compleatang** [comment]
:+1:

/lgtm

**Comment by compleatang** [comment]
@monotek or @scottrigby does anyone know why this isn't merged? The check here says it's in the mergepool but on the prow status page it says this PR was merged. So I'm deeply confused what to do to get things unstuck.

**Comment by monotek** [comment]
hmm... strange... should i recreate the pr?

**Comment by compleatang** [comment]
@monotek ... still nothing. Very strange indeed. https://prow.k8s.io/pr?query=is%3Apr+repo%3Ahelm%2Fcharts+author%3Amonotek+head%3Akibana shows it's all ready and "in merge pool".

**Comment by compleatang** [comment]
FWIW, the latest merge to master was a day ago, seemingly about the same time (although hard to tell exactly on GH's interface), that this PR was put into the queue.

**Comment by monotek** [comment]
Ha, it worked in the end :-)

**Comment by compleatang** [comment]
whew

**Pull request merged**
