### PR TITLE
[stable/redis] Enable Kubernetes Cluster DNS domain to be overridden

### PR DESCRIPTION
**Pull request by miff2000**
#### What this PR does / why we need it:
Enables the Kubernetes Cluster DNS domain to be overridden. The current chart has this statically configured, meaning it cannot be used on clusters which have had their DNS domain updated from the default.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR. Could you change the name to clusterDomain? In other charts we have that name so it would be more consistent.

https://github.com/helm/charts/pull/13278

**Comment by miff2000** [comment]
No problem, that's done now. I've also bumped the version to 7.0.2 as I noticed that 7.0.1 exists on https://kubernetes-charts.storage.googleapis.com/redis-7.0.1.tgz

**Comment by carrodher** [comment]
Hi, it seems there are some conflicts in the _Chart.yaml_, can you take a look?

**Comment by miff2000** [comment]
> Hi, it seems there are some conflicts in the _Chart.yaml_, can you take a look?

Ah yeah, apologies, I didn't spot that yesterday. It was that bumped version number. That should be resolved now

**Comment by javsalgar** [comment]
LGTM

**Comment by GZijian** [comment]
The config in templates/configmap.yaml(line 36) for sentinel monitor should be configurable.

**Pull request merged**
