### PR TITLE
Update cockroachdb image tag

### PR DESCRIPTION
**Pull request by Miouge1**
**What this PR does / why we need it**:
Get the latest version of cockroachDB

**Special notes for your reviewer**:
Tested in my lab cluster.

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
Thanks for the update, @Miouge1. Would you mind also updating the tag in README.md? It's annoying that we have to update this in so many places, but that appears to be the convention across all the charts I've looked at.

**Comment by Miouge1** [comment]
Sure, here you go

**Review by a-robinson — COMMENTED** [review]
Sorry for the delay on this @Miouge1. I need to check into the test failures and haven't had a good chance to get a k8s cluster up and running the last couple days. I'll look into it soon!

**Comment by a-robinson** [comment]
Hm, I'm not sure what's going on. The chart works fine and passes tests when I run it myself (using Helm 2.9.1). It looks like in the above failure the cluster-init.yaml post-install hook never ran. Let's try it again.

**Comment by a-robinson** [comment]
@carrodher @unguiculus do you have suggestions on how to debug this? I don't know much about the test infrastructure being used. What I know:

1. The chart runs fine if I use these changes locally (checking out these changes then running `helm install ./stable/cockroachdb --name arob`) on a Kubernetes 1.8.10 cluster with Helm 2.9.1.
2. The resulting release passes tests (running `helm test arob`)
3. If the tests are failing on this PR, they're probably failing on master too since the bump from cockroach 2.0.0 to 2.0.2 shouldn't have any effect on whether the cluster can start.
4. Judging by the test failure's logs, the problem is that the post-install hook defined in https://github.com/kubernetes/charts/blob/master/stable/cockroachdb/templates/cluster-init.yaml isn't being run. Does that ring any bells?

**Review by a-robinson — COMMENTED** [review]
@Miouge1 as of https://github.com/helm/charts/pull/6964 the CI works again. If you don't mind updating this to use `2.0.4` instead of `2.0.2` and to have `version: 1.2.1` in Chart.yaml, I'd love to get this in. Otherwise I'll do it myself in a few days.

**Comment by a-robinson** [comment]
And also rebasing on top of master, of course.

**Pull request closed without merging**
