### PR TITLE
Bump plugins and Jenkins to latest and stable

### PR DESCRIPTION
**Pull request by jhelbling**
Bumb version of master-images to latest and stable plugins as well jenkins self

### CODE REVIEW

**Comment by jhelbling** [comment]
I signed it!

**Comment by jhelbling** [comment]
I signed it!

**Comment by jwhitcraft** [comment]
This is a dupe of #733

**Comment by seanknox** [comment]
Thanks for the PR @jhelblingHH. We do have a [PR](#733) in flight that will provide an updated Jenkins image, so I'm closing this one.

**Pull request closed without merging**
