### PR TITLE
[stable/redis-cache] Update api versions to support k8s 1.16

### PR DESCRIPTION
**Pull request by antongorkovenko**
Signed-off-by: Anton Gorkovenko <gostom@gmail.com>

#### Is this a new chart
no
#### What this PR does / why we need it:
Update api versions to support k8s 1.16
#### Which issue this PR fixes
no
#### Special notes for your reviewer:
no
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@antongorkovenko 

StatefulSet cause test failed?

```
I1016 22:08:15.146] Installing chart 'redis-cache => (version: "0.5.0", path: "incubator/redis-cache")'...
I1016 22:08:16.408] Error: release redis-cache-3lun8hjkjh failed: StatefulSet.apps "redis-cache-3lun8hjkjh-redis-cache" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"release":"redis-cache-3lun8hjkjh", "app":"redis-cache", "chart":"redis-cache-0.5.0", "heritage":"Tiller"}: `selector` does not match template `labels`]
```

**Comment by antongorkovenko** [comment]
> @antongorkovenko
> 
> StatefulSet cause test failed?
> 
> ```
> I1016 22:08:15.146] Installing chart 'redis-cache => (version: "0.5.0", path: "incubator/redis-cache")'...
> I1016 22:08:16.408] Error: release redis-cache-3lun8hjkjh failed: StatefulSet.apps "redis-cache-3lun8hjkjh-redis-cache" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"release":"redis-cache-3lun8hjkjh", "app":"redis-cache", "chart":"redis-cache-0.5.0", "heritage":"Tiller"}: `selector` does not match template `labels`]
> ```

missing selector
fixed

**Review by cpanato — APPROVED** [review]
/lgtm
/ok-to-test

**Pull request merged**
