### PR TITLE
Add myself to OWNERS for incubator/elasticsearch

### PR DESCRIPTION
**Pull request by rendhalver**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by paulczar — CHANGES_REQUESTED** [review]
LGTM just needs merge conflict resolved.

**Review by paulczar — APPROVED** [review]

**Comment by cpanato** [comment]
@paulczar need to sign the DCO for both authors or somehow add the label

**Comment by rendhalver** [comment]
It likely because the merge of master didn't have the signoff in it's commit.

**Comment by paulczar** [comment]
ugh yeah it looks like me using the github ui to rebase and fix the merge conflicts really messed things up.  both commits have DCOs, so I don't know what our best course of action here is.    It may be best to just make a new PR and close this one out ?

**Comment by cpanato** [comment]
agree

**Comment by rendhalver** [comment]
I can redo the PR. I will get that done now.

**Comment by rendhalver** [comment]
Closing in favour of #7601

**Pull request closed without merging**
