### PR TITLE
[stable/telegraf] Add processor config to telegraf

### PR DESCRIPTION
**Pull request by chirauki**
Signed-off-by: Marc Cirauqui <mcirauqui@gmail.com>

#### Is this a new chart

No.

#### What this PR does / why we need it:

Shamelessly copy template helper for `inputs` so one can also add `processors` into telegraf config.

#### Which issue this PR fixes

None, as far as I can find.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by eks5115** [comment]
@chirauki 
There was an error when my processor looked like this
```yaml
config:
  processors:
    - converter:
        fields: 
          integer: "total_mem"
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
```

output

```yaml
data:
  telegraf.conf: |+
    [[processors.converter]]
      [[processors.converter.fields]]
        integer = "total_mem"
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2

```

log
```
2020-06-30T06:44:53Z I! Starting Telegraf 1.14.4
2020-06-30T06:44:53Z I! Using config file: /etc/telegraf/telegraf.conf
2020-06-30T06:44:53Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 17: (converter.Converter.Fields) cannot unmarshal TOML array table into converter.Conversion (need slice)
```

I want the output to be [processors.converter.fields] no [[processors.converter.fields]]
```yaml
data:
  telegraf.conf: |+
    [[processors.converter]]
      [processors.converter.fields]
        integer = "total_mem"
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2
```

**Comment by chirauki** [comment]
Hey @eks5115 ,

It's been a while since I looked into this honestly... I think the logic for rendering maps or list of maps is not completely right... I uploaded this [commit](https://github.com/chirauki/charts/commit/65a8f29853e3c9802d3aa268fde3a5131a126070) to try to address this, can you try with the `_helpers.tpl` file from that commit?

With this in values:

```
config:
  processors:
    - converter:
        fields:
          integer: "total_mem"
    - enum:
        - mapping:
            field: "status"
            dest: "status_code"
            value_mappings:
              healthy: 1
              problem: 2
              critical: 3
```

I get the following rendered:

```
data:
  telegraf.conf: |+
...
    [[processors.converter]]
      [processors.converter.fields]
        integer = "total_mem"
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2
...
```

This will probably fix this case, although not every possible one... The rendering logic there needs some love from someone whose template-foo is stronger than mine...

**Comment by eks5115** [comment]
Thanks @chirauki. I get it.

**Pull request merged**
