### PR TITLE
[stable/jenkins] serviceAccountName not work when install=true

### PR DESCRIPTION
**Pull request by htkuan**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I find that if set .Values.rbac.install = true, 
then .Values.rbac.serviceAccountName will not working,
because all serviceAccountName will be replaced by {{ template "jenkins.fullname" . }}.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
this will probably be fixed by #13136

**Comment by htkuan** [comment]
#13136 looks good！and I think it should be fixed

**Comment by torstenwalter** [comment]
Thanks for the feedback. Please close the PR if it is fixed.

**Comment by htkuan** [comment]
got it

**Pull request closed without merging**
