### PR TITLE
Remove mistaken tag for selector

### PR DESCRIPTION
**Pull request by govale**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
Might be related to configmap mounts being read-only as of Kubernetes 1.9.4.

**Comment by govale** [comment]
@unguiculus yep. There is related [PR-4411](https://github.com/kubernetes/charts/pull/4411/) already. Should I make edits here or wait for a review of existed PR? Thanks!

**Comment by unguiculus** [comment]
#4411 was merged.

**Comment by timstoop** [comment]
Ah, you need to increment the Chart version and then we can retest.

**Pull request merged**
