### PR TITLE
[stable/ambassador] adding annotation support on the admin service

### PR DESCRIPTION
**Pull request by djsly**
#### What this PR does / why we need it:
Enables the user to set Annotations on the adminService

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Flydiverny** [comment]
/assign
/hold

Holding this for after #15538

**Comment by Flydiverny** [comment]
@djsly can you rebase this and set version as 3.1.0? :)

**Comment by djsly** [comment]
@Flydiverny  done :)

**Comment by Flydiverny** [comment]
@djsly make sure you fulfill the DCO, https://github.com/helm/charts/pull/15562/checks?check_run_id=180772924
Can read more here https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work

Or we can't merge :)

/ok-to-test

**Comment by djsly** [comment]
@Flydiverny fixed

**Pull request merged**
