### PR TITLE
Remove duplicate configuration items

### PR DESCRIPTION
**Pull request by cloudlena**
These config items seem to be duplicated in the `README.md`.

### CODE REVIEW

**Comment by mmatur** [comment]
@mastertinner Could you please bump chart version and fix the CI

**Comment by mastertinner** [comment]
Absolutely. Sorry, I wasn't aware that the version needed to be bumped for a documentation change. It's done now.

**Comment by zanhsieh** [comment]
@mastertinner 
Could you sign DCO please? Instruction:
https://github.com/helm/charts/pull/18720/checks?check_run_id=294261265

**Comment by mastertinner** [comment]
> @mastertinner
> Could you sign DCO please? Instruction:
> https://github.com/helm/charts/pull/18720/checks?check_run_id=294261265

Done

**Comment by mastertinner** [comment]
@mmatur, is this good to merge?

**Pull request closed without merging**
