### PR TITLE
[stable/traefik] Support configuration of mutual TLS

### LINKED ISSUE #9828: [stable/traefik] Support mutual TLS authentication
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:51:55Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**: stable/traefik

**What happened**: Unable to configure traefik to enable [mutual TLS authentication](https://docs.traefik.io/configuration/entrypoints/#tls-mutual-authentication)

**What you expected to happen**: The chart should provide the ability to enable and configure mTLS

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy traefik
2. Deploy a HTTPS web server that echoes received headers back to the client, such as [echoheaders](https://github.com/kubernetes/contrib/tree/master/ingress/echoheaders)
3. Access the web server, providing a client certificate: `curl --cert tls.crt --key tls.key https://myserver.example.com`
4. Notice there is no "x-forwarded-tls-client-cert" header in the returned response body
5. Notice that it is possible to access the web server without using mTLS: `curl https://myserver.example.com`

**Anything else we need to know**:
No

### PR DESCRIPTION
**Pull request by somcsel**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #9828

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by somcsel** [comment]
@dtomcej I am not sure who should review this PR: could you suggest somebody?

**Comment by gmorse81** [comment]
Can this be reopened and reviewed? Looking for this feature.

**Comment by somcsel** [comment]
@gmorse81 see PR #11347

**Pull request closed without merging**
