### PR TITLE
[stable/prometheus-node-exporter] update NOTES.txt to show correct port

### LINKED ISSUE #17882: [stable/prometheus-node-exporter] NOTES displays a wrong port for port-forward
**Describe the bug**
Connection is refused.
NOTES displays a wrong port for port-forward.

**Version of Helm and Kubernetes**:
```
$ helm3 version
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/prometheus-node-exporter

**What happened**:
Access to http://localhost:8080/ returned ERR_EMPTY_RESPONSE.
The logs are below.
```
Handling connection for 8080
E1011 14:47:15.177009    6337 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod 1fe6cc0145d731780fab3355b853fb1f0a8269ce7040ba92426c17601e1e0970, uid : exit status 1: 2019/10/11 05:47:15 socat[11310] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
```

**What you expected to happen**:
Accesible to prometheus-node-exporter.
Port 9100 may be correct.
Update NOTES.
```
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=prometheus-node-exporter,release=prometheus-node-exporter" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:9100 to use your application"
  kubectl port-forward $POD_NAME 9100
```

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm3 install --name-template prometheus-node-exporter stable/prometheus-node-exporter
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=prometheus-node-exporter,release=prometheus-node-exporter" -o jsonpath="{.items[0].metadata.name}")
$ kubectl port-forward $POD_NAME 8080:80
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by oke-py**
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>

No.
#### What this PR does / why we need it:
I updated NOTES.txt to show correct port.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #17882

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Comment by oke-py** [comment]
flakey test? `/retest` will resolve the test failure?

**Comment by zanhsieh** [comment]
@oke-py 
pull-charts-e2e test probably affected by prometheus chart due to it does not restrict which namespace it should fetch (in other words, each PR = 1 namespace and fetch all). I saw it ran 28h7m55s last night:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/17935/pull-charts-e2e/1183727888063533058/

Currently have no idea which sig channel to report and / or force stop this test.

**Comment by oke-py** [comment]
@zanhsieh Oh... thanks for investigation.

**Pull request merged**
