### PR TITLE
Updated airflow chart to use apps/v1 api group

### PR DESCRIPTION
**Pull request by Vicky7424**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@Vicky7424 There are a lot of unrelated changes in the chart - maybe a merge went bad?

**Comment by Vicky7424** [comment]
@davidkarlsen  i think its because of code editor i am using vs code and the changes i did are only the api name and chart release no.

**Comment by davidkarlsen** [comment]
Please come back with a clean PR with only relevant changes.

**Pull request closed without merging**
