### PR TITLE
Removes path specification from ingress service

### PR DESCRIPTION
**Pull request by wfernandes**
Fixes kubernetes/charts#6719

**What this PR does / why we need it**:

We used the chart on GKE. When we enabled the ingress it would return default backend - 404 on any request other than /. Apparently, the gcp ingress class handles the path: value differently

### CODE REVIEW

**Comment by wfernandes** [comment]
I fixed the email address on my linux foundation account and signed the CLA. Is there a way to kick off the check again...other than closing/reopening the PR?

**Comment by wfernandes** [comment]
@prydonius Please let me know if you need anything from me to better understand this PR. Thanks.

**Comment by jasonkeene** [comment]
:shipit:

**Comment by wfernandes** [comment]
Is there something we can do to merge this?

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by wfernandes** [comment]
@unguiculus Are you referring to this version? 

https://github.com/helm/charts/blob/61cf167f0ef0d192c1058038f02bc47352b1ae95/incubator/vault/Chart.yaml#L4

If so then I'll update it to 0.14.3

**Comment by wfernandes** [comment]
@unguiculus I've bumped the version. Feel free to squash and merge when y'all get the chance. Thanks.

**Comment by wfernandes** [comment]
@prydonius If you get a quick moment could you please take a look at this super small PR. Thanks :)

**Comment by wfernandes** [comment]
Let me know if there is anything else I need to do for this PR. Thanks!

**Comment by wfernandes** [comment]
@prydonius @unguiculus I fixed the commits to have the sign off on it. I also squashed the commits to make it easier to comprehend. I think it should be good to be approved.
Let me know if there is anything else y'all need me to do.

**Comment by unguiculus** [comment]
Sorry for the delay.

**Comment by jasonkeene** [comment]
@wfernandes
dreams

**Review by kvolkovich-sc — COMMENTED** [review]
Why not to make it configurable?

**Comment by jasonkeene** [comment]
@kvolkovich-sc Considering it took five months to get this single character change made, I don't think we'll be submitting a new PR to make it configurable. Have at it though!

**Pull request merged**
