### PR TITLE
[incubator/vault] Fix serviceAccount reference and resource limits

### PR DESCRIPTION
**Pull request by jbialy**
#### What this PR does / why we need it:

-  Add a reference to `serviceAccountName` in the deployment for when `serviceAccount.create` is set to `true`, otherwise the deployment will use the default service account.

- Move the `resources` block above the `extraContainers` block so that it applies to the Vault deployment even when an extraContainer is defined. Currently, if an extraContainer is defined the resource block gets applied to that container and not the Vault container.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jbialy** [comment]
bump? Could someone please give this an `/ok-to-test` if the changes look alright?

**Comment by maorfr** [comment]
Seems that serviceAccount.name is missing from README. Maybe its a good time to add it. wdyt?

**Comment by jbialy** [comment]
> Seems that serviceAccount.name is missing from README. Maybe its a good time to add it. wdyt?

Good idea! Updated!

**Pull request merged**
