### PR TITLE
[stable/velero] Make Restic resource requests and limits configurable

### PR DESCRIPTION
**Pull request by madddi**
#### What this PR does / why we need it:

It's currently only possible to configure the same resource requests and limits for Velero and Restic. It should be possible to configure specific resources for every component.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by hectorj2f — COMMENTED** [review]
/ok-to-test

**Comment by madddi** [comment]
Hi @hectorj2f, is there anything blocking this PR?

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Comment by madddi** [comment]
@hectorj2f Thanks! :)

The chart version was updated in between, so I updated it again and resolved the merge conflicts.

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Pull request merged**
