### PR TITLE
[stable/redmine] add support for existing PVCs in redmine and mariadb

### PR DESCRIPTION
**Pull request by flah00**
* add `persistence.existingClaim` for PVC
* add `mariadb.persistence.existingClaim` for mariadb PVC
    * requires #715

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@k8s-bot e2e test this

**Comment by prydonius** [comment]
Not sure what's up with the CI there

**Comment by flah00** [comment]
It's dependent on the new version of maria, iirc @prydonius

**Comment by flah00** [comment]
@prydonius I updated the `requirements.lock`, I think we good to go

**Comment by flah00** [comment]
@prydonius bump

**Comment by flah00** [comment]
I am able to install this locally, without issue, using default values and specifying existing PVCs. I assume this is due to some unknown error, in the test environment. @prydonius can we run the suite again? 

```console
$ helm install --name rmnopvc redmine
...
$ kubectl get po | grep -E '(maria|redm)'
rmnopvc-mariadb-3744605031-b15ww            1/1       Running   0          23m
rmnopvc-redmine-545406014-xbsfr             1/1       Running   0          23m
```

**Comment by flah00** [comment]
@prydonius bump

**Review by prydonius — APPROVED** [review]

**Comment by prydonius** [comment]
Thanks @flah00!

**Pull request merged**
