### PR TITLE
[stable/prometheus][stable/grafana] Use fullname for resources (i.e. services)

### PR DESCRIPTION
**Pull request by mstrzele**
Currently, Prometheus and Grafana can't be installed together in one
release, because the name of `server` services overlap themselves.

```yaml
dependencies:
  - name: prometheus
    version: 2.0.2
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: 0.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
```

```
$ helm install .
Created tunnel using local port: '53637'
SERVER: "localhost:53637"
CHART PATH: /var/folders/4q/nz4ytb693fzf70m5wcqk5ldc0000gn/T/tmp.4Rhs39DEiQ
Error: release insipid-zorse failed: services "insipid-zorse-server" already exists
```

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

cc @mgoodness for review. Not sure how this will affect upgrade.

**Comment by mgoodness** [comment]
This change would cause the destruction of existing resources and creation of new ones. Generally not a problem, *except* that deleting the PVCs would (in most cases) result in the deletion of dynamically-provisioned PVs. We should, IMHO, try to avoid that whenever possible.

I'm actually not sure why there would be a conflict. The Grafana service name should be `RELEASE-NAME-grafana`. Prometheus's are `RELEASE-NAME-alerts`, `RELEASE-NAME-kube-state-metrics`, and `RELEASE-NAME-server`. Is it possible that the Grafana chart is trying to call Prometheus's `server.fullname` template instead of its own?

Full disclosure: I haven't tried packaging Grafana & Prometheus together to see if it happens to me. @mstrzele, would you be willing to share your work?

**Comment by mstrzele** [comment]
Hi @mgoodness,

Thanks for a quick response. You can use [my sample chart](https://github.com/mstrzele/GH-543) for testing.

Below you can see both services generated with the same name:

```yaml
---
# Source: GH-543/charts/prometheus/templates/server-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: full-dragonfly-prometheus
    chart: "prometheus-2.0.3"
    component: "server"
    heritage: "Tiller"
    release: "full-dragonfly"
  name: full-dragonfly-server
spec:
  ports:
    - port: 80
      name: "http"
      protocol: TCP
      targetPort: 9090
  selector:
    app: full-dragonfly-prometheus
    component: "server"
  type: "ClusterIP"
```
```yaml
---
# Source: GH-543/charts/grafana/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: full-dragonfly-grafana
    chart: "grafana-0.2.1"
    component: "grafana"
    heritage: "Tiller"
    release: "full-dragonfly"
  name: full-dragonfly-server
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: full-dragonfly-grafana
    component: "grafana"
  type: "ClusterIP"
```

**Comment by mgoodness** [comment]
@mstrzele something's definitely buggy. Ran `helm template .` against your chart and got inconsistent output. Most of the time I got what you did. But a few other times I got:
```
---
# GH-543/charts/prometheus/templates/server-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: RELEASE-NAME-grafana
    chart: "prometheus-2.0.3"
    component: "server"
    heritage: "Tiller"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-grafana
spec:
  ports:
    - port: 80
      name: "http"
      protocol: TCP
      targetPort: 9090
  selector:
    app: RELEASE-NAME-grafana
    component: "server"
  type: "ClusterIP"
```
```
---
# GH-543/charts/grafana/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: RELEASE-NAME-grafana
    chart: "grafana-0.2.1"
    component: "grafana"
    heritage: "Tiller"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-grafana
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: RELEASE-NAME-grafana
    component: "grafana"
  type: "ClusterIP"
```
Would seem to confirm my suspicion that the `_helpers.tpl` from each chart are somehow "cross-pollinating". Pulling in @prydonius for an expert opinion.

**Comment by prydonius** [comment]
@mgoodness @mstrzele yeah, unfortunately template names are global and I believe the last one rendered is the one that gets used (and the order is non-deterministic too). The context might be helpful here, for example, the reason why charts depending on MariaDB don't run into this is because the fullname template uses `.Chart.Name` which get sets to the right context depending on which chart it's called from.

**Comment by mikesplain** [comment]
I'm doing something similar to @mstrzele and seeing the same issue, even with @mgoodness's v3.0.0 branch. I suspect many others will soon start doing the same, combining open source charts into combined charts for internal use (I'm making a monitoring one at the moment).  As @prydonius and the [docs said](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md), template names are global. Maybe both charts should be namespaced: e.g. `grafana.server.fullname` & `prometheus.server.fullname`? I'm happy to open some PRs as well if the right people point us in the right direction!

**Comment by mstrzele** [comment]
Problem still occurs when using latest versions (`stable/prometheus` v3.0.1 and `stable/grafana` v0.2.5):

```
---                                                                             
# foo/charts/prometheus/templates/server-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: prometheus
    chart: prometheus-3.0.1
    component: "server"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-grafana
```

```
---                                                                             
# foo/charts/grafana/templates/pvc.yaml                           
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: RELEASE-NAME-grafana
    chart: "grafana-0.2.5"
    component: "grafana"
    heritage: "Tiller"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-grafana
```

**Comment by mstrzele** [comment]
I've rebased the PR and prefixed defined templates in both Prometheus and Grafana (as said in [docs](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/named_templates.md#declaring-and-using-templates-with-define-and-template)).

I know that this will break the compatibility and will cause issues during upgrades, but IMHO without this change both these charts are unusable together (and how many people try to use only Prometheus and only Grafana?) and using them is not reliable (you can only guess with template will be used to generate i.e. the name of PVCs).

**Comment by mikesplain** [comment]
This is essentially what I had to do on our fork to get things working right. You may want to bump the version more than a patch release, since this is a breaking change. But I agree, even if Prometheus and Grafana are independent, they should certainly be able to work together or with other charts without fear of something as simple as `server.fullname` getting in the way.

**Comment by jrnt30** [comment]
@mstrzele Since you just changed the function name for the helpers, does it cause an issue with an upgrade of existing infrastructure?  It seems like the rendered template would remain consistent for both of these wouldn't it?

**Comment by mstrzele** [comment]
@jrnt30 👍 You're right. It will break the upgrade only when the wrong template was used for the first time.

@mgoodness Have you had a chance to look at it?

**Comment by mgoodness** [comment]
Sorry I let this sit for so long. LGTM!

**Pull request merged**
