### PR TITLE
[incubator/druid] update chart repo dependency references

### PR DESCRIPTION
**Pull request by scottrigby**
See #23971

### CODE REVIEW

**Comment by AWaterColorPen** [comment]
@scottrigby  It seems CI add `https://kubernetes-charts.storage.googleapis.com` as  `stable` not the `https://charts.helm.sh/stable`
```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
"incubator" has been added to your repositories
```

**Comment by scottrigby** [comment]
@AWaterColorPen you're right. Updating in a separate PR

**Comment by scottrigby** [comment]
Actually updated in this PR to test it. New repo URLs are being added correctly. However:
> Error: requirements.lock is out of sync with requirements.yaml

I'm unclear right now why that would be, since `helm dependency update` was run 🤔

**Comment by AWaterColorPen** [comment]
@scottrigby the CI uses `Helm v2`. Could you use the `Helm v3` to do `helm dependency update`?

**Comment by scottrigby** [comment]
OK not sure why the `helm dependency update` with helm 2 commit worked, but not helm 3 🤔 Will have to look into this.

**Pull request merged**
