### PR TITLE
[stable/elasticsearch-exporter]: shards, snapshots, update to 1.1.0

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:

- added the options for `shards`, `snapshots` and `cluster_settings`
- updated to latest elasticsearch-exporter

#### Special notes for your reviewer:

I'll be glad to add myself as a contributor to this. I've being using it for more than one year now and have a few PRs merged into elasticsearch-exporter itself as well... glad to open another PR adding me if you folks need help :) 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by caarlos0** [comment]
cc/ @desaintmartin @svenmueller

**Comment by svenmueller** [comment]
> > I'll be glad to add myself as a contributor to this. I've being using it for more than one year now and have a few PRs merged into elasticsearch-exporter itself as well... glad to open another PR adding me if you folks need help :)

@caarlos0 sounds good to me. would be nice to have you as contributor 👍

**Comment by caarlos0** [comment]
> /approve

@svenmueller I think you need to comment `/lgtm` to merge? 🤔

**Comment by caarlos0** [comment]
> @caarlos0 sounds good to me. would be nice to have you as contributor 👍

awesome, will do that on the next PR :D

**Pull request merged**
