### PR TITLE
Sentry chart not using mail.use_tls and mail.from_address (#2569)

### PR DESCRIPTION
**Pull request by llonchj**
Fix for #2569

### CODE REVIEW

**Comment by BenTheElder** [comment]
ping CLABot

**Comment by llonchj** [comment]
@BenTheElder cncf-cla was signed before submitting PR and i can see the agreement on my linuxfoundation.org account

**Comment by BenTheElder** [comment]
@llonchj please follow up with the issue and helpdesk I posted in your issue, unfortunately test-infra cannot do anything else about the CLABot, the failing github status comes from the [CNCF](https://www.cncf.io/).

**Comment by dgellow** [comment]
@llonchj Shouldn't we also update the config in the directory `templates/hooks`?

I see the following email config:
https://github.com/kubernetes/charts/blob/c1655fd4fbae069526e16f38b5f0d116ede599d5/stable/sentry/templates/hooks/db-init.job.yaml#L57-L67

https://github.com/kubernetes/charts/blob/c1655fd4fbae069526e16f38b5f0d116ede599d5/stable/sentry/templates/hooks/user-create.job.yaml#L56-L66

**Comment by llonchj** [comment]
Thanks @dgellow! it is updated. I saw those references but are not used.

**Comment by llonchj** [comment]
resigned cla

**Comment by pokoli** [comment]
@llonchj could you please fix the test? Not sure but probably it fails because the values are not set on the CI. I think the ENVIRONMENT variables should be set only if they have values set.

**Comment by BenTheElder** [comment]
*please* consider migrating this to prow. https://github.com/kubernetes/test-infra/issues/3778

**Comment by llonchj** [comment]
@pokoli kindly elaborate the issue by pointing me in the right direction to address it?

**Comment by pokoli** [comment]
@llonchj I just fixed it on #3038, which includes your work. So I think we can close this pr in favour of the new.

**Comment by unguiculus** [comment]
Closing in favor of #3038.

**Pull request closed without merging**
