### PR TITLE
[stable/heapster] Default service name to Heapster

### PR DESCRIPTION
**Pull request by jose5918**
- Allows for better compatibility with other tools
- Allows for custom labels

Fixes https://github.com/kubernetes/charts/issues/1132

### CODE REVIEW

**Comment by gtaylor** [comment]
Most definite yes!

Though, I'd break the custom label part out into its own commit.

**Comment by jose5918** [comment]
@gtaylor good idea. Should be better now

**Review by gtaylor — APPROVED** [review]

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Pull request merged**
