### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Opalo**
Fixed value for default: `persistence.type`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Opalo 
Could you sign the DCO and bump the chart version to latest please? The instruction below is on the bottom of this PR. Thank you.

**Comment by Opalo** [comment]
@zanhsieh, done.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
