### PR TITLE
[JENKINS] Secure Defaults

### PR DESCRIPTION
**Pull request by pnovotnak**
This PR makes a more secure out-of-the-box configuration for Jenkins installs by allowing the user to disable insecure agent protocols, enable CSRF, and disable CLI over remoting, while still allowing a user to run with their pants down if they so wish.

- [x]  Add toggles to config template
- [x]  Secure defaults
- [x]  Add documentation
- [ ]  Make linter happy

### CODE REVIEW

**Comment by carrodher** [comment]
You should increment chart version (`version`) in `Chart.yaml`

**Comment by timstoop** [comment]
And you should also sign the CLA ;-)

**Comment by jlegrone** [comment]
@pnovotnak any progress on this?  I'd love to see this change make it in soon so I may open a duplicate PR if you don't have time.

**Comment by jlegrone** [comment]
@viglesiasce this can be closed now that https://github.com/kubernetes/charts/pull/5026 is merged.  Thanks!

**Comment by viglesiasce** [comment]
Closing in favor of #5026

**Pull request closed without merging**
