### PR TITLE
[stable/elasticsearch-exporter]: adding myself as a maintainer

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:

Added myself as a maintainer so I can help :) 

#### Which issue this PR fixes

- refs https://github.com/helm/charts/pull/16409#issuecomment-522984727

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by caarlos0** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the helm org.
> 
> Once all users have been added as members of the org, you can trigger verification by writing `/verify-owners` in a comment.

🤔

**Comment by svenmueller** [comment]
@caarlos0 not sure why the label `do-not-merge/invalid-owners-file` was added

**Comment by desaintmartin** [comment]
You need to get yourself added as a Helm collaborator: https://github.com/helm/charts/#owning-and-maintaining-a-chart.
you can ask on Slack, `#charts`

**Comment by caarlos0** [comment]
or I can just leave myself as owner instead of both owner and maintainer?

**Comment by svenmueller** [comment]
@caarlos0 how about asking in the mentioned slack channel?

**Comment by caarlos0** [comment]
Asked :)

**Comment by maorfr** [comment]
@svenmueller you need to accept the invitation to join as a trusted collaborator to helm/charts.
i just resent the invitation.

if it doesn't show up in your mail, you will probably see it in one of:
https://github.com/helm
https://github.com/helm/charts

once you have accepted, comment `/verify-owners`

**Comment by caarlos0** [comment]
`/lgtm` again maybe?

**Comment by caarlos0** [comment]
ty :)

**Pull request merged**
