### PR TITLE
[stable/redis-ha] Install procps in sysctlImage command example

### PR DESCRIPTION
**Pull request by hendrikmaus**
**No**

#### What this PR does / why we need it:

Install `procps` in the sysctlImage example command; it fails without it with:

```
sysctl: command not found
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
@ssalaues @dandydeveloper

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@hendrikmaus Can you provide a little more context on this problem? It's not something I've experienced and I'm worried we're solving the wrong thing here with this PR.

What's the error you get?

What are the steps to reproduce? 

Is there an issue for this?

**Comment by ssalaues** [comment]
I will try to reproduce your issue @hendrikmaus I have used that specific functionality of the chart in the past with little to no issues but perhaps something has changed.

**Comment by zanhsieh** [comment]
@hendrikmaus 
Please bump chart to the latest version. Thank you.

**Comment by hendrikmaus** [comment]
_Sorry I was out of order for a little while._

The error message was included when I opened the PR, see above. Without installing `procps`, the container will fail as `sysctl` is not available.

The only step to reproduce the issue, is to use the "sysctlImage" example snippet from the Chart's readme file.

I will bump the version, review changes made and re-test my issue.

**Comment by DandyDeveloper** [comment]
@ssalaues Did you get a chance to try reproducing this?

**Comment by hendrikmaus** [comment]
Here is a quick way to reproduce it.

_Tested on Ubuntu 18.04 LTS (Docker 18.09.5) and Mac OS 10.14 (Docker 19.03.2)_

```sh
$ docker run --rm bitnami/minideb /bin/sh -c "install_packages systemd; sysctl --version"
(...)
/bin/sh: 1: sysctl: not found
```

Where this produces the expected:

```sh
$ docker run --rm bitnami/minideb /bin/sh -c "install_packages systemd procps; sysctl --version"
(...)
sysctl from procps-ng 3.3.15
```

**Comment by ssalaues** [comment]
I'm not sure why it keeps failing the tests. It keeps saying ` error: timed out waiting for the condition` especially since this is simply a README.md change. @davidkarlsen Any ideas on why this might be happening?

**Comment by DandyDeveloper** [comment]
@ssalaues This is probably because some of the pods aren't deploying and are looping/erroring. 

@hendrikmaus Can you make sure that this doesn't cause the initContainer to bootloop with the latest merged changes? 

Maybe we let something slip through in another PR?

**Comment by hendrikmaus** [comment]
@DandyDeveloper I double checked with a **fresh** deployment of the current state: no issues - it was ready after 57s with 2 haproxy pods and 3 redis pods using the `sysctlImage`. By the way, the `sysctlImage` is not active by default and this PR still is just a README change.

I suspect another reason, as a **non-fresh** deployment took about 6 minutes to be ready due to timeouts in finding the current master and failover. But this would only happen if the test environment would already have the redis-ha statefulset running.

I observed that the redis followers will restart quickly as the leader is still untouched. When the leader pod is restarted, however, the `config-init` container needs to run into a timeout before a failover is triggered and a new leader elected.

_config-init container log in the leader pod_
```log
Initializing config..
Attempting to find master
```

It waits a couple of minutes until it runs into a timeout and triggers a failover in order to re-elect a master; the log is then concluded by:

```log
Could not connect to Redis at 10.105.136.64:6379: Operation timed out
Can't ping master, attempting to force failover
Updating sentinel config with master 10.102.231.33
Updating redis config
Ready...
```

Where `10.105.136.64:6379` was the announce service IP of itself, the leader. And `10.102.231.33` is the announce service of another redis pod which was elected to be the new leader after the failover.

Indeed a nasty thing in production, since this would mean redis would not accept any `WRITE` operations until a new master had been re-elected.

**Pull request merged**
