### PR TITLE
[stable/prometheus] Add splunkbot

### PR DESCRIPTION
**Pull request by sylr**
This PR Adds a container to the alertmanager pod which will be able to forward alerts sent to it via webhook to splunk.

### CODE REVIEW

**Comment by timstoop** [comment]
I'm not against it per se, but I wonder if it wouldn't be better to make this a separate chart with a dependency on the prom chart. But I'd prefer to see that change for most other components within this chart as well.

**Comment by sylr** [comment]
@timstoop It's a new optional container within the prometheus-server pod, I don't know if I could make it as you suggested.

**Comment by unguiculus** [comment]
@timstoop I agree. Let's not continue bloating the Prometheus chart.

**Comment by prydonius** [comment]
@sylr would you be open to closing this PR doing this as a separate chart?

EDIT: that will be difficult given this is a sidecar. @timstoop @unguiculus @sylr any ideas on what we could do without bloating prometheus?

**Comment by paulczar** [comment]
I'm not seeing where alertmanager is configured to talk to the splunkbot (or vise versa).  It feels to me like this should be solvable in a separate chart talking back to the main prometheus endpoint ?

**Comment by paulczar** [comment]
Actually using a new YAML field `sidecars` that can be filled when running helm from a seperate values file we can solve this in an interesting pattern.   see https://github.com/kubernetes/charts/pull/3983/files for an example.

**Pull request closed without merging**
