### PR TITLE
[Incubator/kafka] Add kafka rest proxy

### PR DESCRIPTION
**Pull request by nhamlh**

### CODE REVIEW

**Comment by eicnix** [comment]
IMO third party resources like the rest proxy or the schema registry should be extracted into their own repository to reduce the complexity of each chart. Then they can be optionally be included as a dependency.

**Comment by unguiculus** [comment]
@eicnix I agree.

**Comment by unguiculus** [comment]
cc @benjigoldberg @faraazkhan @h0tbird

**Comment by benjigoldberg** [comment]
Super excited to see rest proxy being added! That being said I agree with @eicnix and @unguiculus, lets extract this into its own chart like we did with the [Schema Registry](https://github.com/kubernetes/charts/tree/master/incubator/schema-registry)

**Comment by nhamlh** [comment]
So I guess this PR should be considered as closed now. I will make another PR adding rest-proxy chart.

**Pull request closed without merging**
