### PR TITLE
[stable/suitecrm] fix(ingress): fix chart label

### PR DESCRIPTION
**Pull request by trollr**
#### Which issue this PR fixes
  - fixes ingress chart label

#### Special notes for your reviewer:
template suitecrm.chart is undefined
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, I would use the template approach as it is a common practice in other charts and also in other labels:
- Create a function in __helpers.tpl_:
```
{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "suitecrm.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
- Replace
```yaml
chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
```
by
```yaml
chart: "{{ template "suitecrm.chart" . }}"
```
in the following places:
```
templates/deployment.yaml
8:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
21:        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

templates/externaldb-secrets.yaml
8:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

templates/ingress.yaml
8:    chart: "{{ template "suitecrm.chart" . }}"

templates/suitecrm-pvc.yaml
8:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

templates/secrets.yaml
7:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

templates/svc.yaml
7:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
34:    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
```

**Comment by trollr** [comment]
Modified last commit with @carrodher comments

**Pull request merged**
