### PR TITLE
airflow custom init

### PR DESCRIPTION
**Pull request by javefang**
#### What this PR does / why we need it:
- Fix incorrect values in airflow/README.md.
- Allow airflow initContainer's image to be customised, as we can't access public image registry behind the company firewall.
- Fix various incorrect postgres related values

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kppullin** [comment]
In `values.yaml`, the changes to the keys `postgresUser` to `postgresqlUsername`, etc broke our airflow installation (we override the username, password, etc).  What's the need to change these keys?

Can this PR be reverted or updated to only include changes for the init container customizations?  Until then I need to figure out why our version pinning didn't work 😭

**Comment by javefang** [comment]
Hi @kppullin , I'm sorry this happened. Are you using your own postgres? In which case yes this PR will break your deployment if you are not pinning airflow chart version.

In my case I'm using helm to deploy both airflow and postgres.  Variables "postgresUser", "postgresPassword" and "postgresDatabase" are both used in airflow for postgres configuration, and the postgres sub-chart to configure postgres. In which case the postgres sub-chart will only pick up "postgresqlUsername" not "postgresUser". The airflow chart won't work before this PR if you have `postgresql.enabled=true`.

**Comment by javefang** [comment]
Also in principal yes I should've split this into two PR and I'm still happy to do so. This is what I think might work for us:

1. Revert this PR.
2. Make a new PR to include only the init container customisation.
3. Make another PR for the postgres variables fix. (Given you still agree with the postgres fix in this PR?)

**Comment by kppullin** [comment]
Thanks for the insight @javefang. Yes, we're using our own postgres and not the one from the chart, so this all makes sense.

I've got my pinning issue fixed... but not sure how to best proceed with this. I can update my config now that I know it's an issue, however I don't have any sense on how many other users are similarly affected.  I also appreciate your needs to address the issues with having values picked up from the subchart.

Any thoughts @gsemet and/or @maver1ck?

**Comment by gsemet** [comment]
Hi. I have no time to work on this actively (got a baby :) ), but here what I think:
- posgres stuff should match the postgresql requirements (chart)[https://github.com/helm/charts/tree/master/stable/postgresql]. So the right setting seems to be the ones on this commie (`postgresqlUsername` instead of `postgresqlUser`). 
- if you set your own database, set `postgresql.enabled: False` and hardcode the URL in `postgresql.postgresqlDatabase`. We might want to modify this part to use a secret (because username and password will be hardcoded). Can someone see how other charts does?

**Comment by kppullin** [comment]
Thanks for the feedback @gsemet and have fun with the baby!

I'll switch over to using the corrected postgres keys and then update to 0.10.0.

@javefang - It doesn't seem necessary to go through the hassle of reverting the change and splitting it into two parts, since it'll net out the same.  Thanks for improving this chart and fixing the postgres troubles; a little bit of pain feels worthwhile while this chart is relatively new.

**Comment by javefang** [comment]
Hi @kppullin , I noticed a mistake in this PR which might related to the issue you are experiencing at first. Although the values still needs fixing (prefix should be "postgresql" not "postgres"), the actual value key for user should be "postgresUser" not "postgresqlUsername". I was referencing the wrong postgresql chart version when making this PR. It should be 0.13.1 not the latest.

I have made another PR https://github.com/helm/charts/pull/10333 to fix the issue.

**Comment by gsemet** [comment]
/lgtm

But i do not have the authority to merge :(

**Comment by kppullin** [comment]
Thanks for the heads up @javefang - much appreciated!

**Comment by javefang** [comment]
> /lgtm
> 
> But i do not have the authority to merge :(

This one is merged already but has issues. A fix is implemented in #10333. An lgtm on that one too would be great!

**Pull request merged**
