### PR TITLE
[stable/home-assistant] add support for additionalPorts and vseditor

### PR DESCRIPTION
**Pull request by angelnu**
#### Is this a new chart
No

#### What this PR does / why we need it:
- support additionalPorts
- fix: vseditor changed logic for no passwords. This fix re-enable the no-password option.
- support to enable access to editor when home assistant does not start

#### Which issue this PR fixes
No issue opened before PR

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by runningman84** [comment]
/lgtm
@angelnu dies this change allow the Homematic integration without using host networking?

**Comment by angelnu** [comment]
@runningman84 - yes, I am able to run with this change without host network. I use a load balancer (metallb chart) so it looks like:

  ```
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.2.232
      publishNotReadyAddresses: true
      additionalPorts:
      - name: homematicproxy
        port: 2001
        targetPort: 2001
```

**Comment by runningman84** [comment]
can you also post the corresponding home assistant config for homematic?

**Comment by angelnu** [comment]
Here it is:

secret homematic_callback_ip -> 192.168.2.232 (my loadbalancer IP)
secret homematic_callback_port -> 2001

```
homematic:
  local_port: 2001
  interfaces:
    rf:
      host:          !secret homematic_host
      resolvenames:  json
      callback_ip:   !secret homematic_callback_ip
      callback_port: !secret homematic_callback_port
      username:      !secret homematic_username
      password:      !secret homematic_password
    #wired:
      #host:          !secret homematic_host
      #port:          2000
      #resolvenames:  json
      #callback_ip:   !secret homematic_callback_ip
      #callback_port: !secret homematic_callback_port
      #username:      !secret homematic_username
      #password:      !secret homematic_password
    ip:
      host:          !secret homematic_host
      port:          2010
      resolvenames:  json
      callback_ip:   !secret homematic_callback_ip
      callback_port: !secret homematic_callback_port
      username:      !secret homematic_username
      password:      !secret homematic_password
    groups:
      host:          !secret homematic_host
      port:          9292
      resolvenames:  json
      callback_ip:   !secret homematic_callback_ip
      callback_port: !secret homematic_callback_port
      username:      !secret homematic_username
      password:      !secret homematic_password
      path:          /groups
  hosts:
    ccu:
      host:          !secret homematic_host
      username:      !secret homematic_username
      password:      !secret homematic_password

binary_sensor:
  - platform: template
    sensors:
      homematic_up:
        friendly_name: "Homematic is sending updates"
        entity_id:
          - light.dimmer_kitchen
          - sensor.time
        value_template: >-
          {{as_timestamp(now()) - as_timestamp(states.light.dimmer_kitchen.last_changed) < 600}}

automation:
  - alias: Homematic Reconnect
    trigger:
      platform: state
      entity_id: binary_sensor.homematic_up
      to: "off"
    action:
      # Reconnect, if sensor has not been updated for over 1 hour
      service: homematic.reconnect
```

**Pull request merged**
