### PR TITLE
[stable/prometheus-adapter] Enhancements

### PR DESCRIPTION
**Pull request by steven-sheehy**
**What this PR does / why we need it**:
Ports my changes from closed [PR](https://github.com/helm/charts/pull/7159) to stable/prometheus-adapter.

- Add readiness and liveness probes
- Adds ability to disable default rules and add custom rules
- Adds affinity, nodeSelector, tolerations
- Adds a NOTES.txt and .helmignore per standard
- Adds securityContext to reduce pod permissions
- Adds ability to customize service values
- Fixes fullnameOverride
- Reduces logLevel as it was way too verbose.
- Minor cleanup to sort values in README and in values.yaml and fix typos

**Which issue this PR fixes** : N/A

**Special notes for your reviewer**:

@mattiasgees

### CODE REVIEW

**Comment by steven-sheehy** [comment]
@kevtaylor Yes, it works for me. You're right that it should be labels and not label. I'm guessing it depends on Helm and Kubernetes version whether it ignores that or errors. I did not write the original chart that added that though. You're welcome to submit a PR to address it.

**Comment by kevtaylor** [comment]
@steven-sheehy Will do. Thanks

**Pull request merged**
