### PR TITLE
git-clone crashes with git permissions issue

### PR DESCRIPTION
**Pull request by aramkarapetian**
When pulling private dags repo with ssh key it cannot attach tty and/or just crashes on keyscan.
see https://github.com/helm/charts/issues/19509

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by gsemet** [comment]
ok for me. You need to sign the DCO and bump the chart version

**Comment by ryan-a-baker** [comment]
@aramkarapetian - Do you want to sign the DCO and get this committed?  We are running in to this issue as well and would like to get this merged.

If you can't, we don't mind submitted the PR with the signed DCO.

**Comment by gsemet** [comment]
You can resubmit the same PR and I’ll approve it ASAP :)

**Pull request closed without merging**
