### PR TITLE
[stable/drone] Reorder server deployment environment

### PR DESCRIPTION
**Pull request by vaxinate**
ATTN: @christian-roggia @zakkg3

#### Is this a new chart

No

#### What this PR does / why we need it:

In order to configure Drone to use PostgreSQL, users must provide a database connection string via the `DRONE_DATABASE_DATASOURCE` environment variable. In the chart defaults, this value is defined in the `server.env.DRONE_DATABASE_DATASOURCE` key to use SQLite. Postgres users will need to override this, but the postgres connection string must include a password, so we prefer to provide it via `server.envSecrets`. However, because a default value is already present at `server.env.DRONE_DATABASE_DATASOURCE`, and the server deployment template puts the values in `server.env` _after_ the values in `server.envSecrets` we are unable to effectively override the default value in `server.env.DRONE_DATABASE_DATASOURCE`. Rearranging the ordering in which the template prints the contents of those values fixes the problem for w/o requiring any changes to the `values.yaml`.

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
 this PR doesn't add, remove, or modify any variables so i've left that checkbox unchecked in the checklist below.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vaxinate** [comment]
Sorry folks I just noticed my bad pull request name. I've updated it for clarity.

**Comment by zakkg3** [comment]
please bump version: 2.3.1
/ok-to-test

**Comment by vaxinate** [comment]
merge conflicts have been resolved (sorry for the goofy resolution commits) and the chart version bumped to 2.3.1.

**Pull request merged**
