### PR TITLE
[stable/oauth2-proxy] allow to set extraEnvs without proxyVarsAsSecrets

### PR DESCRIPTION
**Pull request by mstrzele**
#### Is this a new chart
No.
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
It moves the `env` block outside of the condition for proxying variables as secrets. If the condition is `false`, then the `extraEnvs` value cannot be passed as a table, because there is no `env` block defined.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mstrzele** [comment]
C'mon! It's a simple fix...

**Comment by desaintmartin** [comment]
Sorry for the delay!
/assign
/ok-to-test

**Comment by desaintmartin** [comment]
Could you rebase?

**Pull request merged**
