### PR TITLE
[stable/cerebro] added initialDelaySeconds

### PR DESCRIPTION
**Pull request by leva0887**
Added initialDelaySeconds: 120

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by paulczar** [comment]
/ok-to-test

you'll need to resolve the conficts.

**Comment by leva0887** [comment]
@paulczar while you review my commit versions of helm chart goes upper than my

**Pull request merged**
