### PR TITLE
Update Jenkins version to current LTS (2.19.4) and Kubernetes Plugin to 0.10

### PR DESCRIPTION
**Pull request by dserodio**
The current LTS release of Jenkins is 2.19.4, released 2016-11-23.

Also updating the Jenkins plugins, and config.xml for Kubernetes Plugin 0.10

 - Kubernetes 0.10
 - Credentials Binding 1.10
 - Git 3.0.1

### CODE REVIEW

**Comment by dserodio** [comment]
I read #194 and assumed an ImageTag version of 0.6.0

**Comment by unguiculus** [comment]
FYI: 2.32.1 LTS is now available.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Review by viglesiasce — APPROVED** [review]
Thanks @dserodio!! Sorry for the delay in reviewing.

I pushed the image with tag v0.6.0. In the future I will be separating out the Dockerfile so we can make the updates independent of each other.

Thanks again!

**Pull request merged**
