### PR TITLE
nginx-ingress: Adds autoscaling on memory

### PR DESCRIPTION
**Pull request by kennethaasan**
**What this PR does / why we need it**:
This adds `controller.autoscaling.targetMemoryUtilizationPercentage` and upgrades `controller-hpa.yaml` apiVersion to `autoscaling/v2beta1` to support memory auto-scaling.

### CODE REVIEW

**Comment by timstoop** [comment]
You'll need to merge from master and fix the version in Chart.yaml again. But the change looks good to me.
@mgoodness @jackzampolin @chancez What do you think?

**Comment by kennethaasan** [comment]
Thanks @timstoop. Merged from master now.

**Comment by kennethaasan** [comment]
Deployed, and seems to work perfect!

screenshot from 2018-05-24 14-24-53

**Pull request merged**
