### PR TITLE
[stable/mongodb] fix failing liveness probe during long running mongodb recovery

### LINKED ISSUE #17501: [stable/mongodb] liveness probe doesn't allow long running recovery
**Describe the bug**
The liveness probe fails if there is a long running recovery (mongodb catching up on the oplog). As a result kubernetes kills the pod, it gets restarted and begins recovery again and gets stuck in an endless cycle. Of course we could just increase `livenessProbe.initialDelaySeconds` but in our case (and I assume others as well) we have rather large production data bases for which we can't predict the recovery duration. We would like the liveness Probe to report liveness even during recovery.

[This issue](https://github.com/bitnami/bitnami-docker-mongodb/issues/87) in the bitnami-docker-mongodb repository is the exact same problem, but there they didn't find a solution, they just closed it because it didn't happen anymore for the issuer.

We found a solution and I'll open up a PR.

**Version of Helm and Kubernetes**:
helm: v2.14.3
kubernetes: v1.14.6

**Which chart**:
stable/mongodb

**What happened**:
endless reboot loop of pod in case of long running recovery

**What you expected to happen**:
liveness probe report liveness even during recovery but readiness only reports readiness after recovery

**How to reproduce it** (as minimally and precisely as possible):
Have a rather large database and a replicaset of mongo instances deployed. Then delete the primary pod, let it respawn and watch it recover. If during that time the liveness probe fails often enough, the pod gets deleted by kubernetes and restarts even though it was healthy

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by jonnylangefeld**
#### What this PR does / why we need it:
fix failing liveness probe during long running mongodb recovery to prevent reboot cycle

#### Which issue this PR fixes
  - fixes #17501 

#### Special notes for your reviewer:
Let me know if there is a better way to check liveness. This has worked for us on a rather large database.
Will present this PR to my legal team in order to sign the DCO. I will add my signature then.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks, @jonnylangefeld, what I don't fully understand is the difference in the behavior of both commands. I mean, `pgrep mongod` will work when the process appears in the system, and the existing [`ping`](https://docs.mongodb.com/manual/reference/command/ping/#ping) command work when the server is responding to the command, even even if the server is write-locked.

What I mean is that I don't understand why one method makes a difference from the other. But I am not a MongoDB expert so I am sure that there is an explanation. In the same way, we need the DCO signed before continuing.

**Comment by jonnylangefeld** [comment]
hi @carrodher, the issue only appears if one of the mongodb replicas is trying to catch up on a huge database and if this recovery is taking longer than the `livenessProbe.initialDelaySeconds` + retries. [This issue](https://github.com/bitnami/bitnami-docker-mongodb/issues/87) in the bitnami-docker-mongodb repository describes it perfectly. The issue over there just got closed because the issue creator didn't need it anymore.

The difference between the commands is that `mongo --eval "db.adminCommand('ping')"` will only succeed once the database is recovered (that's why this command is perfect for the readiness probe) and `pgrep mongod` succeeds as soon as mongodb starts its work (including during recovery). So `pgrep mongod` as liveness probe prevents kubernetes from killing the pod during mongodb's recovery, because the liveness probe is already successful.

I'm aware of the DCO, I hope I will receive response from my legal team today.

**Comment by carrodher** [comment]
Understood, thanks for your explanation, please ping me once the DCO issue is solved and we will merge the changes. Thanks!

**Comment by jonnylangefeld** [comment]
@carrodher, got positive feedback from our legal team and signed the commit.

**Comment by jonnylangefeld** [comment]
I don't know exactly why it shows "jonnylangefeld authored and Jonny Langefeld committed 6 days ago" (once github user name and once real name) now. I made sure that both author and Signed-off-by is both the same `Jonny Langefeld <jonny.langefeld@gmail.com>`, but still it shows as two. Hope that is not a problem.

Screen Shot 2019-10-03 at 8 12 51 AM

**Comment by jonnylangefeld** [comment]
ping @carrodher this PR is ready to be merged

**Comment by carrodher** [comment]
Sorry for the delay, now bots are handling it 😄

**Pull request merged**
