### PR TITLE
Allow adding custom ldif files to the openldap chart

### PR DESCRIPTION
**Pull request by ehardon**
Updated deployment.yaml file in order to provide the desired argument `--copy-service` to start the ldap docker image so that a user of the chart can override the basis ldif file with another one provided as an argument when installing the chart.
@enis 

Signed-off-by: <elena.hardon@ness.com>

### CODE REVIEW

**Comment by enis** [comment]
Should we protect the argument with 
```
{{- if .Values.customLdifFiles }}
```
or there is no need for that?

**Comment by ehardon** [comment]
Good point, it should be there. Thanks for spotting it!

**Comment by cpanato** [comment]
Hello @ehardon thanks for this PR

- you need to bump the chart version
- and sign the [DCO](https://github.com/helm/charts/pull/7396/checks?check_run_id=14768927) 
https://www.helm.sh/blog/helm-dco/index.html

**Comment by cpanato** [comment]
@ehardon still missing the DCO you can follow this steps https://github.com/helm/charts/pull/7396/checks?check_run_id=15027962

**Comment by ehardon** [comment]
Thanks @cpanato !

**Comment by svidrascu** [comment]
Can this be merged?

**Comment by cpanato** [comment]
@ehardon can you please rebase and fix the conflict?

**Comment by ehardon** [comment]
@cpanato fixed the conflict

**Comment by cpanato** [comment]
@ehardon thanks!

**Comment by THPubs** [comment]
@ehardon Can you please give us an example on how to include `customLdifFiles`?

**Comment by ehardon** [comment]
@THPubs When installing the helm chart you need to provide a config yaml file which should include your customLdifFiles
_helm install stable/openldap -f ldap_config.yaml_
where the `ladp_config.yaml`  file should look like the example below:
```yaml
customLdifFiles:
  file1.ldif: |-
    dn: ou=users,dc=example,dc=org
    objectclass: organizationalUnit
    objectclass: top
    ou: users

    dn: cn=uname,ou=users,dc=example,dc=org
    cn: uname
    gidnumber:
    givenname: 
    homedirectory: 
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: 
    uid: 
    uidnumber: 
    mail:
    userpassword: 
```

**Comment by THPubs** [comment]
@ehardon Great thanks a lot! It worked! It would be really nice if we can add it to the Readme so others can also find it easily.

**Comment by gmcbrien** [comment]
Hi - good that we can dd customt LDIF files! But, for my understanding, will this only copy the custom .ldif's to /container/service/slapd/assets/config/bootstrap/ldif/custom or will it actually 'execute' (import) them too?

**Comment by THPubs** [comment]
@gmcbrien Actually it does execute and seed the database. Worked for me. Can you please share a sample of your code?

**Comment by gmcbrien** [comment]
@THPubs Thanks for your interest. Attached is my values.yaml (with some fake user info) - renamed to .txt.

[values.txt](https://github.com/helm/charts/files/3120847/values.txt)

**Comment by THPubs** [comment]
@gmcbrien Sorry Im unable to find any issue with the file you sent. Try with one single ldif file and see?

**Comment by gmcbrien** [comment]
@THPubs No problem and thanks for offering support. 

According to this site https://github.com/osixia/docker-openldap#seed-ldap-database-with-ldif (where the original OpenLDAP image comes from):

<snip>
**Seed ldap database with ldif**
This image can load ldif files at startup with either ldapadd or ldapmodify. Mount .ldif in /container/service/slapd/assets/config/bootstrap/ldif directory if you want to overwrite image default boostrap ldif files or in /container/service/slapd/assets/config/bootstrap/ldif/custom (recommended) to extend image config.

Files containing changeType: attributes will be loaded with ldapmodify.

</snip>

My LDIFs are getting copied successfully to the 'custom' folder. But not being executed (at least, I see no users in the database).

I tested editing the volumeMounts in the deployment.yaml to point to 

mountPath: /container/service/slapd/assets/config/bootstrap/ldif/ (and not the custom subfolder). Again, my LDIFs get copied there... but no users in the database.

I also don't understand the comment about 'changeType'....

**Comment by gmcbrien** [comment]
Just an update - my problem is resolved.

I removed the part of my LDIF that defines the organisation ('o') and domain ('dc') and basically just left in there the definition of the roles and users. This worked fine. I am guessing my LDIF was being rejected as I was trying to overwrite 'top-level' data in my database, and this wasn't permitted.

**Pull request merged**
