### PR TITLE
[stable/hackmd] Remove erroneous selector from ingress resource

### PR DESCRIPTION
**Pull request by joachimmathes**
#### What this PR does / why we need it:

This PR fixes a `Ingress` resource in `stable/hackmd`. It removes a `selector` key from the `Ingress` since it is not part of the definition.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@joachimmathes thanks for your PR, you are removing the selector from the ingress and not from the deployment.

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Comment by joachimmathes** [comment]
> @joachimmathes thanks for your PR, you are removing the selector from the ingress and not from the deployment.

@cpanato Of course, you are right. Got it right in the title, but wrong in the description. :upside_down_face:

Thanks for merging.

**Pull request merged**
