### PR TITLE
[ci] Upgrade to chart-testing v2.2.0

### PR DESCRIPTION
**Pull request by unguiculus**
#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by unguiculus** [comment]
To be merged once chart-testing v2.2.0 is released.

**Review by cpanato — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]

**Comment by unguiculus** [comment]
Merged manually now due to bot issues.

**Pull request merged**
