### PR TITLE
[stable/grafana] fix dashboards-json-configmap, add registry+pullSecrets

### PR DESCRIPTION
**Pull request by DaytonG**
- Fixes bug found in PR #4713 with json dashboards needing to be one-liners
- adds image registry settings, cribbed from various other charts (like rabbitmq)
- add optional pullSecrets

### CODE REVIEW

**Comment by unguiculus** [comment]
I don't know where you found that but please stay with the standard for images. See review guidelines.

**Comment by DaytonG** [comment]
It's in ~25 stable charts. I can revert this change, of course. Just seems like a useful little separation (in my use case, anyway)

**Comment by unguiculus** [comment]
Please revert it.

**Comment by DaytonG** [comment]
Reverted.

**Comment by richerve** [comment]
@unguiculus any blockers to merge this?

**Comment by timstoop** [comment]
cc: @rtluckie 
Can you take a look at this, please?

**Comment by rtluckie** [comment]
changes LGTM.

**Comment by rtluckie** [comment]
changes LGTM.  @DaytonG Nice job fixing json dashboards

**Pull request merged**
