### PR TITLE
[stable/metallb] Add PSP utilization in speaker's ClusterRole

### PR DESCRIPTION
**Pull request by sandromodarelli**
#### What this PR does / why we need it:
Fix PodSecurityPolicy utilization adding use in speaker ClusterRole

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by sandromodarelli** [comment]
@Miouge1 Can you give your feedback on this fix? I saw that you have introduced PSP utilization in metallb chart 😄 ty

**Comment by Miouge1** [comment]
@sandromodarelli I suggest to use `"` rather than `'` for consistency.

I copy/pasted the PSP from here https://github.com/danderson/metallb/blob/master/helm-chart/templates/psp.yaml, and I suppose that your patch comes from here https://github.com/danderson/metallb/blob/master/helm-chart/templates/rbac.yaml#L37-L42 ?

**Comment by sandromodarelli** [comment]
@Miouge1 ty for your suggestion. I haven't seen before the helm chart in metallb repo (my fault) and I patched by my self this chart.

The one from https://github.com/danderson/metallb/blob/master/helm-chart/templates/rbac.yaml#L37-L42 is surely better written 😄 

Can I integrate it here?

**Comment by Miouge1** [comment]
You'll need to fix the DCO check: `git commit --amend --signoff`

**Comment by sandromodarelli** [comment]
Sent two commits and I can DCO label only the last one 😞 shame on me. How can I solve this?

**Comment by sandromodarelli** [comment]
The incorrect commit is this https://github.com/helm/charts/pull/12461/commits/200426729a463bccc86ac5d5fd596c2604aa5b50, right?

**Comment by Miouge1** [comment]
You can `git rebase master -i` and squash your commits into 1.

**Comment by sandromodarelli** [comment]
rebased to one correct commit. thank you so much @Miouge1 . Now I'll wait for @scottrigby 🙏

**Comment by sandromodarelli** [comment]
@scottrigby any news about this MR? it's a small fix and without it metallb's chart is useless in a podsecuritypolicy enabled cluster

**Comment by sandromodarelli** [comment]
@Miouge1 do you have any tip to unblock this MR? If you add this fix, i'll close the MR. What do you think about?

**Comment by Miouge1** [comment]
@cpanato can you help with the review here?

**Comment by AntonioMeireles** [comment]
hi all ... 

any progress on this ? as stated before without this  currently metallb's chart **_is useless in a podsecuritypolicy enabled cluster_**

Thanks in advance!

**Pull request merged**
