### PR TITLE
[stable/kube2iam] add priorityClassName, upgrade kube2iam

### PR DESCRIPTION
**Pull request by kimxogus**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by SharpEdgeMarshall** [comment]
any news?

**Comment by kimxogus** [comment]
hope someone review this...

**Comment by SharpEdgeMarshall** [comment]
Could someone please review this?

**Comment by linki** [comment]
lgtm

**Comment by linki** [comment]
/unassign @linki

(I'm not a maintainer anymore)

**Pull request merged**
