### PR TITLE
[stable/grafana] Update the app version to 7.0.5

### PR DESCRIPTION
**Pull request by gowrisankar22**
Signed-off-by: gowrisankar <gowrisankar.m01@sap.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - updating the app version https://github.com/helm/charts/pull/23111

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by gowrisankar22** [comment]
@zanhsieh Can you help to approve and merging?

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
