### PR TITLE
[datadog] Fixing failed lint when deployment is enabled.

### PR DESCRIPTION
**Pull request by sudermanjr**
Fixing regression where the service values are not set when the deplo…yment is enabled.

This can be tested by `setting deployment.enabled`: true and running `helm lint`

### CODE REVIEW

**Review by hkaj — COMMENTED** [review]
I think this worked as intended. `service` is not under `deployment`, it's supposed to be at the same level.
Deployment and service are also not intended to be enabled by default, the default use case is the daemonSet only.
What issue did you face and are looking to solve?

**Comment by sudermanjr** [comment]
Ah, didn't mean to leave it on by default.  I can change that. 

Not sure why service wouldn't be under deployment since it is only enabled when deployment is enabled due to the if statement at the top of the service.yaml file.

The chart fails to lint when deployment is enabled due to the service values not having any defaults in values.yaml.  Is the intended behavior to force the user to enable the deployment and also set values for the service?  Would it not be more user-friendly to have the service automatically created as a clusterIP service when enabling the deployment?  

Our use-case is to enable statsd collection inside the cluster for services to send stats to Datadog.  With this use case, it never makes sense to not have a service.

**Review by hkaj — CHANGES_REQUESTED** [review]
Right, that makes sense. Then let's put service back under deployment, I think that's fair given the `if` in the service template.
And `.Values.deployment.annotations` can go back to `.Values.deployment.serivce.annotations` as you first suggested. And `.Values.service.type` --> `.Values.deployment.service.type`

**Comment by sudermanjr** [comment]
Awesome.  Thanks for the feedback.  I put the service under deployment.  Verified that linting works with the deployment as well without.

**Review by hkaj — APPROVED** [review]

**Pull request merged**
