### PR TITLE
[stable/grafana] Render secret for envFromSecret automatically

### PR DESCRIPTION
**Pull request by pavdmyt**
#### Is this a new chart
No.

#### What this PR does / why we need it:
Renders secret for extra env vars automatically instead of creating it manually as it is done now. This allows to pass env vars that should be stored in secret easily as follows:

```yaml
envFromSecret:
  GF_AUTH_GOOGLE_CLIENT_ID: foo
  GF_AUTH_GOOGLE_CLIENT_SECRET: bar
```

This also simplifies integration with tools like [helmfile](https://github.com/roboll/helmfile), as sensible data can be easily passed to chart from env variables instead of figuring out how to render additional custom secret object.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@pavdmyt 
Could you bump the chart version again to latest? Thank you.

**Comment by pavdmyt** [comment]
@zanhsieh chart version bumped.

**Review by zanhsieh — APPROVED** [review]

**Comment by pavdmyt** [comment]
@zanhsieh resolved chart version conflict once again (probably yet another PR was merged).

**Review by zanhsieh — APPROVED** [review]

**Comment by ebabani** [comment]
This PR doesn't look right. With this approach we are storing secret data in the helm release, which is not something that is desirable.

We are also breaking backwards compatibility with releases that relied on `envFromSecret`. In our deployment we verified that this results in a broken upgrade.

@zanhsieh  What was the rationale for merging this? If this functionality is desired can it be done under a different key, and keep the old `envFromSecret` behaviour?

**Comment by pavdmyt** [comment]
@ebabani Actually I thought about probable backward compatibility issues creating this PR (possibly had to bump major version of the chart). I agree that moving functionality introduced by this PR under different key may be a good solution. I'm ready to open PR with fix.

Also, could you please provide the rationale why storing secret data in helm release is not considered as something desirable, this is not obvious to me.

**Comment by ebabani** [comment]
@pavdmyt As I see it(and feel free to correct me), the helm release information goes into a configmap in the tiller namespace, so your secret data is stored in a configmap vs a k8s secret.

Another use case we have is for our helm releases to be checked into source control. With the new approach this is no longer possible since there's confidential data in the `values.yaml` file.

Thanks for being open to make a PR for this. Let me know if you're still able to. I do like this new approach, as it makes configuring some environment values way easier, but using a different key would be best.

**Comment by pavdmyt** [comment]
@zanhsieh what do you think about moving functionality introduced by this PR into new key (e.g. `envRenderSecret`) and restore the old behavior for `envFromSecret`?

**Comment by zanhsieh** [comment]
@pavdmyt @ebabani 
I suggest new PR since it might overwrite another PR introduced after this chart merged.

**Comment by growse** [comment]
> Also, could you please provide the rationale why storing secret data in helm release is not considered as something desirable, this is not obvious to me.

Just to add to @ebabani 's comment: like many, I version control my k8s resources and helm chart values. I like to encrypt my secrets with sops, and the pattern of managing my k8s secrets as separate k8s resources while then supplying the right secret name to the chart is a useful one. Mingling secret data in with the rest of the config data would definitely be a step backwards in terms of usability. 

I imagine there are others out there that manage their secret lifecycle using something more complex. Point is, it's not unreasonable to have users managing their secrets separate from their charts and other resources.

**Comment by pavdmyt** [comment]
@growse Thanks for explanation!

We're using [Vault](https://www.vaultproject.io/) for managing secrets and [helmfile](https://github.com/roboll/helmfile) to deploy helm charts. During release deployment CI authenticates to Vault and fetches all required secret data, then helmfile passes secret data to the release by filling required keys from values file. So, the need for managing secrets separately from releases was not clear enough to me.

**Pull request merged**
