### PR TITLE
[stable/minio] Support imagePullSecrets for StatefulSet.

### LINKED ISSUE #23041: [stable/minio] StatefulSet does not support imagePullSecrets
**Describe the bug**
Currently the minIO chart does not apply imagePullSecrets to the StatefulSet template.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/minio

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by KinsheX**
Signed-off-by: Jonas Rabouli <jonas.h@rabouli.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
Adds imagePullSecret support for StatefulSet.
This is required if anyone wishes to run MinIO in distributed mode, and are pulling images from a private repository.

#### Which issue this PR fixes
  - fixes #23041

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sparqueur** [comment]
Please add the image pull secrets in all helm hooks (post-install-create-bucket-job.yaml ...)
You should define a clean _helper template (as postgresql one for instance) and use it everywhere.
Moreover, we should handle global.imagePullSecrets as a best practice

**Comment by KinsheX** [comment]
@sparqueur I have fixed the points you mentioned.
I have however left the format of the imagePullSecrets in the MinIO chart as-is, as to not make this PR change too much for other users of it.

**Comment by sparqueur** [comment]
> @sparqueur I have fixed the points you mentioned.
> I have however left the format of the imagePullSecrets in the MinIO chart as-is, as to not make this PR change too much for other users of it.

Thanks a lot @KinsheX. I was going to create a PR to add all this stuff as I needed it when I saw you were already working on one. :+1:

**Comment by KinsheX** [comment]
@krisis @wlan0 Anything we can do to see this PR through?

**Pull request merged**
