### PR TITLE
[stable/mysql] service endpoints shouldn't depend on /metrics

### PR DESCRIPTION
**Pull request by f84anton**
**What this PR does / why we need it**:
Problem: mysqld_metrics doesn't respond on "/metrics" when mysqld is dropping a big database for example. As a result the service doesn't have endpoint because all readiness checks for pod must be successful.
Solution: use "/" for httpGet probes on metrics container which will return only landing page with http code 200 so when metrics cannot be queried from mysql it will not affect service endpoint.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

@viglesiasce

### CODE REVIEW

**Comment by whereisaaron** [comment]
Hi @f84anton others see this issue too, and in part what causes it is the default/hard-coded health probe timeout of 1s for the metrics container. There is a separate PR #6477 to make the timeout of the metrics configurable. Then you could configure the timeout long enough for situations like your big database drop.

Changing the metrics health probe to '/' is a reasonable move too. I wonder if metrics endpoints should be able to take services offline at all?

**Comment by whereisaaron** [comment]
@f84anton I don't disagree. I just raised a PR to add optional metrics to the `memcached` chart, and there I check just the root of the metrics exporter. It would be nice if metrics exporters had a `/healthz` as standard, as well as `/metrics`.

I personal can't decide whether a Pod with broken metrics should be considered healthy enough to keep using. I haven't seen a definitive argument about how to handle this situation.

One take on it I am mulling over is perhaps we don't care to have the health of the metrics service determine readiness, but we do want the Pod replaced if the metrics are not live. That is, if we care about metrics at all, we want to fix them, not leave the Pod running but offline. So we would only configure a liveness probe for metrics (whether testing `/healthz`, `/`, or `/metrics`).

**Comment by olemarkus** [comment]
I have had issues with timeouts on this as well. So this one makes sense to me.

/assign
/ok-to-test

**Pull request merged**
