### PR TITLE
[incubator/kube-spot-termination-notice-handler] add support for ASG detach

### PR DESCRIPTION
**Pull request by egeland**
add support for an option to detach from autoscaling group

Signed-off-by: Frode Egeland <egeland@gmail.com>

#### What this PR does / why we need it:
This adds support for taking the affected instance out of the AWS AutoScaling Group (basic ASG only), which will allow a replacement to be requested sooner.

#### Checklist

- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by unguiculus** [comment]
We seem to have an issue with the chart-testing tool here. I'll try and get that fixed.

**Comment by egeland** [comment]
Any luck with the testing tool, @unguiculus ?

**Comment by egeland** [comment]
Any updates, @unguiculus ?

**Comment by egeland** [comment]
This has been merged via #10286

**Pull request closed without merging**
