### PR TITLE
Don't create serviceaccount and clusterrolebinding if module is not e…

### PR DESCRIPTION
**Pull request by jamie-liu**
…nabled in prometheus

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
Hi, thanks for your contribution. Please accept the CLA and we can take a look at it!

**Comment by jamie-liu** [comment]
@timstoop， 
Hello， I have signed the CLA. Thanks.

**Comment by unguiculus** [comment]
This has to wait for #4516.

**Comment by jamie-liu** [comment]
/assign @unguiculus
Is it OK to merge this request now?

**Pull request closed without merging**
