### PR TITLE
fix typo in mediawiki/README.md

### PR DESCRIPTION
**Pull request by scf0920**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by javsalgar** [comment]
LGTM

**Comment by javsalgar** [comment]
According to the test, the chart version was not updated. Could you please bump the version?

**Comment by scf0920** [comment]
@javsalgar  Thanks. Now it already update. :)

**Pull request merged**
