### PR TITLE
[stable/consul] update to latest

### PR DESCRIPTION
**Pull request by caarlos0**
#### What this PR does / why we need it:

Updates to latest consul (1.5.2).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by caarlos0** [comment]
btw @lachie83 do you need help with this chart? I can add myself as a maintainer too :)

**Review by lachie83 — APPROVED** [review]

**Comment by caarlos0** [comment]
```
I0628 20:03:08.780] Events:
I0628 20:03:08.780]   Type     Reason             Age                     From                Message
I0628 20:03:08.780]   ----     ------             ----                    ----                -------
I0628 20:03:08.780]   Normal   NotTriggerScaleUp  4m54s (x30 over 9m59s)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added):
I0628 20:03:08.781]   Warning  FailedScheduling   44s (x12 over 10m)      default-scheduler   pod has unbound immediate PersistentVolumeClaims (repea
```

test cluster is full? 🤔

**Comment by lachie83** [comment]
@caarlos0 I’m investigating

**Comment by caarlos0** [comment]
@lachie83 any news on this?

**Pull request merged**
