### PR TITLE
[stable/jira-software] Add jira-software chart

### PR DESCRIPTION
**Pull request by stevehipwell**
#### Is this a new chart?
Yes this is a new chart

#### What this PR does / why we need it:
This PR adds a _Jira Software_ chart

#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by stevehipwell** [comment]
@unguiculus @prydonius could you please take a look at this to review?

**Comment by stevehipwell** [comment]
Could someone please suggest who I should put in the OWNERS file?

**Comment by stevehipwell** [comment]
@zanhsieh do you have a suggestion as to who should be in the owners file?

**Comment by zanhsieh** [comment]
@stevehipwell 
One of helm members who recently LGTM PRs.

**Comment by stevehipwell** [comment]
Thanks @zanhsieh!

**Comment by zanhsieh** [comment]
@rjkernick
@tsiddique
Would you guys take a look this PR please?

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

**Comment by scottrigby** [comment]
Ping on Slack if you need any help getting a Helm repo running, automate chart testing, or listed on the Hub.

**Comment by stevehipwell** [comment]
@scottrigby is this only applicable to the new Helm 3 chart version or will it work for Helm 2 as well?

**Pull request closed without merging**
