### PR TITLE
[incubator/kafka] Add init container so kafka will wait for zookeeper to be ready.

### PR DESCRIPTION
**Pull request by mcdan**
#### Is this a new chart
Nope.

#### What this PR does / why we need it:
This can make kafka wait for zookeeper to be fully ready. The behavior is controlled by a flag and is set to the current behavior by default. When set to true an init container is added to the broker pod that will wait till zookeeper is fully ready, when this is not done you can observe kafka restarts on deployment.

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

@faraazkhan
@h0tbird 
@benjigoldberg

### CODE REVIEW

**Comment by mcdan** [comment]
Can anyone take a look at this?

**Review by Kratemis — APPROVED** [review]

**Pull request closed without merging**
