### PR TITLE
[stable/cluster-autoscaler] Deprecating chart

### PR DESCRIPTION
**Pull request by sc250024**
This Helm chart has been moved to the repository at https://github.com/kubernetes/autoscaler.

Signed-off-by: Scott Crooks <scott.crooks@gmail.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

This PR deprecates the `cluster-autoscaler` chart in favor of the new location at https://github.com/kubernetes/autoscaler.

#### Special notes for your reviewer:

**IMPORTANT**

This cannot be merged until https://github.com/kubernetes/autoscaler/pull/3341 has been merged!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sc250024** [comment]
@yurrriq Thanks for the approval. I think it will take some time until https://github.com/kubernetes/autoscaler/pull/3341 is reviewed and approved. Maybe we can kickstart the discussion over there.

**Comment by jfrancisco0** [comment]
PR https://github.com/kubernetes/autoscaler/pull/3341 seems to have been merged, satisfying the dependency.

**Comment by sc250024** [comment]
@jfrancisco0 Almost. Let's still wait for https://github.com/kubernetes/autoscaler/pull/3393 to be merged. The instructions I left for the repository maintainers for the PR https://github.com/kubernetes/autoscaler/pull/3341 weren't totally followed (notably, the creation of the `gh-pages` branch). So they need to do that first to actually create the Helm chart repository.

**Comment by yurrriq** [comment]
Looks like there are some outstanding issues with the GitHub Actions over there. Let's keep the hold tag here till that's all resolved.

**Comment by davidkarlsen** [comment]
@yurric all seems ok now?

**Comment by sc250024** [comment]
> @yurric all seems ok now?

More drama here: https://github.com/kubernetes/autoscaler/pull/3403

**Comment by gjtempleton** [comment]
Hey, 

we now have a working (manual for now) release process and have the chart published and installable as of the merging of https://github.com/kubernetes/autoscaler/pull/3413, so I think the hold on this can now be removed, thanks again for all your hard work on this!

**Comment by yurrriq** [comment]
Sounds great, thank you!
/hold cancel

**Pull request merged**
