### PR TITLE
[stable/influxdb] Add deprecation notice.

### PR DESCRIPTION
**Pull request by naseemkullah**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [n/a] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @Aisuko

**Comment by naseemkullah** [comment]
cc @scottrigby

**Review by Aisuko — COMMENTED** [review]
Thanks, I believe we should keep the chart with bug fi or enhanced feature(make sure the new chart must include the new feature) until MAY 2020 the new chart is listed on the Helm Hub.

**Comment by davidkarlsen** [comment]
@naseemkullah / @Aisuko Please follow https://github.com/helm/charts/blob/master/PROCESSES.md to deprecate charts.

**Pull request merged**
