### PR TITLE
[stable/prometheus-operator] Kubelet relabelings.

### PR DESCRIPTION
**Pull request by moskitone**
Added metrics relabeling config to kubelet service monitor.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
/lgtm
Thank you! :-)

**Comment by desaintmartin** [comment]
FYI this was a new feature and not a patch, it should have increased minor version.

**Pull request merged**
