### PR TITLE
[stable/datadog] Adding full RBAC scope to datadog cluster role

### PR DESCRIPTION
**Pull request by awwithro**
I followed the conventions from the other charts using RBAC wrt to how the values are used to setup the various roles/bindings. I also branched off of my branch in the following PR here: https://github.com/kubernetes/charts/pull/2690 let me know if i should rebase to make things more clear.

I'm also not 100% sure if all the permissions needed are covered by the role. From what I can tell looking at the code as well as the lack RBAC errors it my setup's api-server logs it seems good.

### CODE REVIEW

**Comment by awwithro** [comment]
@hkaj if you've got time to review this, I'd greatly appreciate it.

**Comment by hkaj** [comment]
Hey @awwithro
This seems to overlaps with https://github.com/kubernetes/charts/pull/2474 from @CharlyF but there may be distinct value in both. For example we could use your RBAC and Charly's leader election. Can you guys sync? There's a slack that can help for this btw: kubernetes.slack.com - feel free to CC me there if I can help.

**Comment by CharlyF** [comment]
@awwithro, more than happy to sync up. I'm @charly on the kubernetes slack.
I agree with @hkaj, I believe there is room for both of our contributions.
:)

**Comment by awwithro** [comment]
Sounds good, I'll reach out to you on slack

**Comment by awwithro** [comment]
@hkaj I spoke to @CharlyF about this. We figured this PR can be merged first and he'll rebase off of this

**Review by hkaj — APPROVED** [review]
Great, thanks for the contrib @awwithro, this is pretty useful!
LGTM ✅ 
Could a k8s member trigger tests? 🙏

**Comment by awwithro** [comment]
hey @prydonius, would you be able to give us a hand with this one?

**Pull request closed without merging**
