### PR TITLE
[stable/jenkins] Update Readme to work with Helm 3

### PR DESCRIPTION
**Pull request by bharathkkb**
Helm 3 requires release name and is of the format
helm install [NAME] [CHART] [flags]

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@bharathkkb can you add an entry in Changelog.md?

**Comment by bharathkkb** [comment]
@torstenwalter done :)

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Comment by torstenwalter** [comment]
@bharathkkb Thank you for the contribution.

**Pull request merged**
