### PR TITLE
[stable/elasticsearch-exporter] Allow PrometheusRules to be templated.

### PR DESCRIPTION
**Pull request by desaintmartin**
Also fix README to add missing desaintmartin OWNER.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Note: should it be a breaking change since this would potentially break existing rules stating `{{ $values }}` in them?

**Review by svenmueller — COMMENTED** [review]
i think we should treat it as breaking change since it potentially requires changes to existing alert configurations.

**Comment by desaintmartin** [comment]
Updated to reflect the breaking change.

**Comment by desaintmartin** [comment]
Rebased.

**Review by svenmueller — APPROVED** [review]
/lgtm

**Pull request merged**
