### PR TITLE
[stable/grafana] Fix custom dashboard folders breakage

### LINKED ISSUE #10183: [stable/grafana] Adding dashboards to specific folders w/ the sidecar?
**Is this a request for help?**:
yes

**Version of Helm and Kubernetes**:
helm: 2.12
k8s: 1.10.11

**Which chart**:
stable/grafana

**What happened**:
I would like to add dashboards from configmaps to specific folders in grafana (the grafana UI, I don't really care about the file location inside the pod). Is this possible using the sidecars deployed with grafana? looking through the provided values.yaml, I don't see an obvious solution.

### PR DESCRIPTION
**Pull request by minhdanh**
#### Which issue this PR fixes
  - fixes https://github.com/helm/charts/issues/10183#issuecomment-511589822

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mariogeorgievft** [comment]
Any ETA on this PR?

**Review by zanhsieh — APPROVED** [review]

**Comment by infa-ddeore** [comment]
you changes aren't present into https://github.com/helm/charts/blob/master/stable/grafana/templates/deployment.yaml unless I am mistaken

**Pull request merged**
