### PR TITLE
[stable/traefik] fine control over accesslog fields

### PR DESCRIPTION
**Pull request by jsleeio**
Submitting a new PR for this as I inadvertently pushed a bunch of irrelevant crap to my old one and I don't have the `git`-fu to clean it up. Sorry about that. I closed the previous PR.

Version bumped to 1.38.0.

**What this PR does / why we need it**:

Traefik 1.6 added finer control over what data is included in JSON access logs. Support this in the Helm chart.

* logging behaviour for pre-existing configs (ie. without these new options specified) should remain unchanged for both `common` and `json` access log formats

* logging behaviour for new deployments with default options should remain unchanged (access logs disabled)

* uncommenting the example options in `values.yaml` will result in `Authorization` headers being redacted in access logs; I personally think that should be the "sensible default" when using JSON logs, but that could cause "surprising changes" with existing deployments and thus probably belongs in a separate PR

### CODE REVIEW

**Comment by jsleeio** [comment]
had already been discussing this change with @dtomcej so...

/assign dtomcej

**Comment by dtomcej** [comment]
@jsleeio Can you bump this to 1.36.1?

**Pull request merged**
