### PR TITLE
update deployment.yaml add subPath

### PR DESCRIPTION
**Pull request by joshle**
**What this PR does / why we need it**:  some pvc rootPath don't have permission to write，so need subPath

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # add subPath config

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign the CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement), also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by carrodher** [comment]
@joshle this PR will be closed automatically in a few days. Are you interested in applying the changes and be able to merge it? If not, I can apply the same changes in another PR

**Comment by joshle** [comment]
You can apply the same changes in another PR, because I donot know how to  sign the CLA.

**Pull request closed without merging**
