### PR TITLE
Improve notes shown when installing ark

### PR DESCRIPTION
**Pull request by spingel**
* Display kubectl command for showing logs and listing secrets
* Change tar command to extract ark client binary only

Signed-off-by: Steffen Pingel <steffen.pingel@tasktop.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@spingel please bump the chart version

**Comment by spingel** [comment]
Looks like the test failures are unrelated to the change. The ark install leaves crds behind which cause subsequent installs to fail.

**Comment by cpanato** [comment]
we need to add something like this
```
{{- if semverCompare ">=2.10-0" .Capabilities.TillerVersion.SemVer }}
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
```

I can open a PR to fix that, and then you rebase, what do you think?

**Comment by spingel** [comment]
I didn't know about that delete policy. Looks like a good way to do it!

Chary.yml defines `tillerVersion: ">=2.10.0"` so not sure we need the if condition.

I'm happy to rebase once the pull request is up.

**Comment by spingel** [comment]
Rebased against master.

**Pull request closed without merging**
