### PR TITLE
[stable/redis] Fixed typo in README

### PR DESCRIPTION
**Pull request by harryleesan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rendhalver** [comment]
Please add the chart name [stable/redis] to the PR title so it's easy to tell what the Pr is for.
You also need to sign the CNCF CLA before we can accept your PR.

**Comment by harryleesan** [comment]
@rendhalver thanks for the heads up! I have signed the CLA and amended the title.

**Comment by carrodher** [comment]
Hi @harryleesan, because we merged this PR #6783 some minutes ago, you need to bump again the chart version.
The other PR as usual, bump the version to `3.7.1` so at this moment we've some failures in the test, you need to increase the version to `3.7.2`.

**Pull request merged**
