### PR TITLE
Wordpress YAML indentation cleanup

### PR DESCRIPTION
**Pull request by scottrigby**
When adding #813 it became clear that the stable/wordpress chart had yaml indentation issues. This PR cleans those up.

CC @prydonius 😄

### CODE REVIEW

**Comment by seanknox** [comment]
Looks like the deployment YAML is malformed:

```
seanknox at naga in ~/src/kubernetes/charts on pr-920 [!$]
$ helm install stable/wordpress/
Error: error validating "": error validating data: found invalid field requests for v1.Container
```

**Comment by scottrigby** [comment]
@seanknox Hm, interesting, OK. I'll automate the YAML conversion later Today and see what my manual error was - thanks!

**Comment by scottrigby** [comment]
The indentation appears OK to me, but TBH I only did this because I saw the related issue above needed indentation changes that stemmed originally from the stable/wordpress plugin (specifically, which were fixed in 2e2f55e). There doesn't appear to be a problem with the indentation in this PR, but if it's failing I can't explain why. I can say I initially attempted to use a tool to automate indentation consistency, until I realized (of course) this is impossible to do unless it's validated via some helm command – because helm's chart variable expansion is not valid YAML until it's actually expanded. I just referenced this PR in this other issue about creating best practices for charts: https://github.com/kubernetes/charts/issues/44#issuecomment-299991751.

@seanknox I can either leave this open for someone else to address, or just close it until we handle the above as a best practice and/or tooling. I don't have a preference… thoughts?

**Comment by scottrigby** [comment]
I'm choosing door number two for now 😄 
> close it until we handle the above as a best practice and/or tooling

**Pull request closed without merging**
