### PR TITLE
[stable/traefik] upgrade to 1.7.2

### PR DESCRIPTION
**Pull request by solidnerd**
#### Which issue this PR fixes
none

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@solidnerd Can you fix the merge conflict (and probably have to bump version after that)

**Comment by solidnerd** [comment]
@davidkarlsen done ;)

**Pull request merged**
