### PR TITLE
[stable/datadog] Add validity checks on clusterName

### PR DESCRIPTION
**Pull request by L3n41c**
#### What this PR does / why we need it:

The cluster name parameter has been introduced to disambiguate nodes
having the same name in different clusters.

Cluster names are, for ex., used to build hostnames and must therefore
comply with some rules.

We enforce here the same rules as the ones enforced by GKE:
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.FIELDS.name

The DataDog agent itself is already checking the validity of cluster names since
DataDog/datadog-agent#4492.

The goal of this change in the helm chart is to catch issues as early as possible because
having a clear error message from helm is smarter than having to dig in the logs of
a failing agent.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rifelpet** [comment]
@L3n41c This is going to cause issues for us because we have periods in our cluster name. We use Kops to manage our K8s clusters in AWS, and Kops' concept of the cluster name is a FQDN which would include periods as well. In order to work around this new limitation in the datadog chart we'd have to deviate our Datadog cluster name from our Kops cluster name which will be very confusing to users. Would it be possible to add periods to the allowed regex?

I realize this would also need to be changed in the agent upstream, but I thought I would ask here first.

**Comment by L3n41c** [comment]
@rifelpet 
Hello,
I’ll make some additional tests to validate that allowing periods doesn’t cause the issue I was trying to avoid by putting in place this restriction. But I think it should be OK.
Note that this will allow [cluster-name to have values that are not allowed on GKE](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.FIELDS.name). But if it’s standard with kops to have domain name as cluster name, it definitively makes sense to support it.

**Pull request merged**
