### PR TITLE
docs(README.md): add link to docs for nginx configMap :relaxed:

### PR DESCRIPTION
**Pull request by 0verc1ocker**
I need this for my future self. It is better than searching the web everytime to find all the configMap values that can be set for the nginx-ingress controller configMap. :)

#### What this PR does / why we need it:

Just adding a link to configMap for nginx-ingress so it is easier to find the values for the nginx-ingress controller configMap.

#### Which issue this PR fixes

This is just README docs improvement.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Comment by 0verc1ocker** [comment]
Why does nginx-ingress chart need a version bump? I only updated the README. :cry:

**Comment by 0verc1ocker** [comment]
@mgoodness Can we look into merging this link update?

**Comment by 0verc1ocker** [comment]
@mgoodness Can we look into merging this link update?

**Comment by ChiefAlexander** [comment]
/assign
/ok-to-test

You are going to have to bump the version before we can merge 😆

**Comment by 0verc1ocker** [comment]
@ChiefAlexander Hi, can you try now? I bumped up the nignx-ingress chart version and rebased from master. :+1:

**Comment by ChiefAlexander** [comment]
/lgtm

Thanks for the PR!

**Pull request merged**
