### PR TITLE
[stable/influxdb] Add Pod Annotations to Deployment

### PR DESCRIPTION
**Pull request by jorgevillaverde-sitewhere**
#### Is this a new chart

no

#### What this PR does / why we need it:

Add Pod Annotations to InfluxDB Deployment

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by Aisuko — CHANGES_REQUESTED** [review]
Thanks for your PR, please make a signoff first.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @Aisuko, the commit without the signoff has been amended.

**Review by Aisuko — APPROVED** [review]
/lgtm

**Comment by Aisuko** [comment]
Thanks.

**Pull request merged**
