### PR TITLE
[incubator/rundeck] added image.pullSecret to use private repository

### PR DESCRIPTION
**Pull request by TheRealElHugo**
#### What this PR does / why we need it:
It gives the ability to use a private repository to pull a customised image of rundeck.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dwardu89** [comment]
@langseb the title is incorrect, it should be incubator not stable

**Comment by mattfarina** [comment]
@langseb Helm uses a [Developers Certificate of Origin](https://developercertificate.org/) to signify that you have permission to contribute the content. Each commit needs signoff. The _checks_ tab on the pull request has commands you can use update the commits.

**Comment by kangshung** [comment]
@dwardu89 is this PR going to get merged?

**Comment by dwardu89** [comment]
@kangshung  i cannot put a lgtm tag until i get all green ticks. You need to satisfy those then i can merge it.

**Pull request closed without merging**
