### PR TITLE
[stable/sonarqube] Deployment strategies

### PR DESCRIPTION
**Pull request by RDPzero**
Signed-off-by: Ricardo Deitoz Posser <ricardo_rdpzero@hotmail.com>

@rjkernick @tsiddique

#### What this PR does / why we need it:
Enable deployment strategy configuration

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by RDPzero** [comment]
@rjkernick  Why this pull request wasn't merged and the https://github.com/helm/charts/pull/16651 got merged?

**Comment by rjkernick** [comment]
Just got lost in the shuffle. Sorry about that.

**Comment by zanhsieh** [comment]
@RDPzero 
Could you resolve conflicting files please? Thank you.

**Comment by torstenwalter** [comment]
@RDPzero Could you solve the merge conflicts? Would be great to have this merged.

**Comment by torstenwalter** [comment]
ping @RDPzero

**Comment by RDPzero** [comment]
@torstenwalter sorry for the delay
the pull request mentioned above (#16651) included the same functionality, so this one is useless

**Pull request closed without merging**
