### PR TITLE
Prometheus: modify config to support k8s 1.6 by default

### LINKED ISSUE #955: Prometheus might not work correctly with 1.6 RBAC
See https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L468
Also, see https://github.com/prometheus/prometheus/pull/2641

### PR DESCRIPTION
**Pull request by kujenga**
This commit adds support for Kubernetes 1.6 RBAC within the prometheus configuration for scraping node metrics. This should fix https://github.com/kubernetes/charts/issues/955

I've tested this on Google Container Engine with a clusters of version 1.5.7 and 1.6.2, both worked as expected.

cc @mgoodness

### CODE REVIEW

**Comment by kujenga** [comment]
Just signed the CLA!

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Comment by mgoodness** [comment]
Matches upstream config & verified working on minikube.

/lgtm

**Comment by mgoodness** [comment]
Oops! Let's bump the chart version to `v3.1.0`. Also, please allow maintainers to push to your branches in the future.

**Comment by kujenga** [comment]
@mgoodness done! will do in the future, I've enabled it here as well 👍

**Comment by cortesi** [comment]
Any news on getting this merged? It's pretty critical.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Review by viglesiasce — APPROVED** [review]

**Pull request merged**
