### PR TITLE
[stable/odoo checking if service type is loadBalancer before assigning…

### PR DESCRIPTION
**Pull request by fawaz-moh**
… loadBalancerIP in the service template

Signed-off-by: fawaz-moh <fawaz.moh.ibraheem@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by rafariossaa** [comment]
LGTM.
Could you merge this @juan131 ?

**Review by juan131 — APPROVED** [review]
Thanks for the PR!! Approving your changes

**Pull request merged**
