### PR TITLE
[stable/prometheus] Add Missing ClusterRole Permissions for Kube-state-metrics

### PR DESCRIPTION
**Pull request by lawliet89**
#### What this PR does / why we need it:

Kube-state-metrics was spewing lots of permission errors.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by lawliet89** [comment]
@zanhsieh requires a `/lgtm` command. PR approvals don't work for the bot.

**Comment by zanhsieh** [comment]
@lawliet89 
I mostly do ok-to-test first. Please don't rush.

/lgtm

**Comment by lawliet89** [comment]
Apologies. Didn't mean to rush.

**Pull request merged**
