### PR TITLE
[stable/sonarqube] add support for Oracle DB

### PR DESCRIPTION
**Pull request by jphayes**
Signed-off-by: Jeremy Hayes <jeremyh@liatrio.com>

#### Is this a new chart
Existing chart maintained by @rjkernick @tsiddique

#### What this PR does / why we need it:
- Adds support for connecting to an external Oracle database

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jphayes** [comment]
@torstenwalter based on your feedback (https://github.com/helm/charts/pull/18050#issuecomment-552632870), I have submitted a new PR for Oracle support

**Comment by jphayes** [comment]
@rjkernick @tsiddique can I get a review on this?

**Comment by rjkernick** [comment]
I am not looking to add new features to the chart at this time. I am working on moving it over into my company's repo.

**Comment by jphayes** [comment]
@rjkernick is it time to find additional maintainers then?

**Comment by rjkernick** [comment]
No, this chart repository is being deprecated in the coming months: https://github.com/helm/charts#deprecation-timeline. I will continue to maintain the charts over on my company's repository and get that repo listed on hub.helm.sh.

**Comment by davidkarlsen** [comment]
This chart has been deprecated and moved: https://github.com/helm/charts/pull/21007

**Pull request closed without merging**
