### PR TITLE
[stable/ghost] Fix targetPort when using ClusterIP

### LINKED ISSUE #11470: Ghost chart doesn't work correctly when ClusterIP used
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

v1.13.2, v2.12.3

**Which chart**:

stable/ghost

**What happened**:

This is the relevant part of my configuration:
```
ghostProtocol: http
ghostHost: www.mysite.net
ghostPath: /
service:
  type: ClusterIP
  port: 80
service:
  type: ClusterIP
  port: 80
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: true
  certManager: true
  annotations:
   kubernetes.io/ingress.class: nginx
  hosts:
  - name: www.mysite.net
    path: /
    tls: true
    tlsSecret: mysite-net-tls
```
Then URL's generated by Ghost are like http:/www.mysite.net/:80 instead of https://www.mysite.net

In the Deployment object I can find this:

```
        - name: GHOST_HOST
          value: www.mysite.net/
        - name: GHOST_PROTOCOL
          value: http
        - name: GHOST_PORT_NUMBER
          value: "80" 
```

**What you expected to happen**:

And I think it should be:
```
          value: "www.mysite.net"
        - name: GHOST_PROTOCOL
          value: "https"
        - name: GHOST_PORT_NUMBER
          value: 443
```
Maybe even without the GHOST_PORT_NUMBER

**How to reproduce it** (as minimally and precisely as possible):

Install chart using the above values.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Duologic**
Related issue: https://github.com/helm/charts/issues/11470

#### What this PR does / why we need it:

The ghost chart currently does not work when using ClusterIP. This seems to happen because the targetPort is set to http while the containerPort is set to 2368. Matching these ports made it work on my machine... :)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #11470

#### Special notes for your reviewer:
This could probably be handled with a variable in values.yaml, however I like to keep the changes small. Feel free to implement this better.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi, thanks for the PR :) 

There's something I do not fully understand. According to the deployment definition.

```
        ports:
        - name: http
          containerPort: 2368
```

Therefore, there shouldn't be a conflict when using one option or the other. Could you elaborate more in the error you found?

**Comment by Duologic** [comment]
When set to ClusterIP, the Service ends up with `targetPort: http`, I changed this to match the containerPort on the Deployment and that seems to work.

Example output:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-app
    chart: chart-1.1.1
    heritage: Tiller
    release: default-app
  name: default-app
  namespace: default
spec:
  type: ClusterIP
  clusterIP: 10.0.0.1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: default-app
```

I'm new to k8s, maybe somehow it should match `targetPort: http` and something has to change on the Deployment? I don't know how it should work in k8s, I just know how it works for me this way. 😄

**Comment by javsalgar** [comment]
Hi,

Please let us know the platform and the helm install command that you used. We will try to reproduce the issue

**Comment by Duologic** [comment]
I've been using `flux-helm-operator` for this, please have a look at my code: https://github.com/Duologic/ghost-dromomania

**Comment by javsalgar** [comment]
Are you able to reproduce by simply doing helm install in the chart?

**Pull request closed without merging**
