### PR TITLE
[stable/nextcloud] Inject certificates into image

### PR DESCRIPTION
**Pull request by ballj**
#### What this PR does / why we need it:
Adds CA certificate support to nextcloud. Allowing it to authenticate against ldap with an internal CA.

#### Which issue this PR fixes
N/A

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by chrisingenhaag** [comment]
Hi @ballj ,
thx for the PR. I think it is really specific what you want to realize. Isn´t something that can be handled via the extraVolumeMounts already existing within the chart? Sure you have to prepare a volume or configmap for this usecase. But from here I think it would work and would prevent us to bring this complexity into this chart.

regards

**Comment by ballj** [comment]
Basic functionality can be achieved with extra volumes. However I was thinking this maybe useful for others using ldap (for example) as it will work out of the box. I wouldn't say its very complex as the _certificates.tpl isn't used unless a certificate if specified.

**Comment by billimek** [comment]
The nextcloud chart has migrated to a new repo.  Can you please raise the pull request over there?  https://github.com/nextcloud/helm

**Pull request closed without merging**
