### PR TITLE
[stable/prometheus] Support ingress.extraPaths

### PR DESCRIPTION
**Pull request by Vlaaaaaaad**
### What this PR does / why we need it:
Adding ingress.extraPaths configuration to allow users to prepend additional paths to every host. This is required when working with aws-alb-ingress-controller and configuring ssl redirection (see https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/).

#### Special notes for your reviewer:

Heavily inspired by https://github.com/helm/charts/pull/16628

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Huh? Failed due to unbound PVCs which I did not touch.

/retest

**Comment by Vlaaaaaaad** [comment]
I was wrong. The tests are failing because `node-exporter` pods are stuck in `Pending` with `0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports` or similar errors.

The same check is failing in https://github.com/helm/charts/pull/17969. I am confused. Any advice on how to proceed?

**Comment by Vlaaaaaaad** [comment]
/retest

I am feeling lucky!

**Comment by Vlaaaaaaad** [comment]
@gianrubio any chance this can be merged without the tests passing? The test failures are unrelated.

**Comment by zanhsieh** [comment]
@Vlaaaaaaad 
I think ask @mgoodness would be faster. I saw @gianrubio [somewhere](https://github.com/kubernetes/k8s.io/issues/401#issuecomment-542799434) recently, but apparently he lost interest in this repo.

**Comment by Vlaaaaaaad** [comment]
AHAHAA! The tests were finally successful! 

CC @zanhsieh : any chance you can lgtm/ merge this? 

> If this PR passed, consider volunteering yourself as one of this chart OWNER.

I really would for charts I am more familiar with. I wouldn't say I am familiar enough with Prometheus.

**Comment by zanhsieh** [comment]
@Vlaaaaaaad @mgoodness 
Pinged @mgoodness already. I really hope @gianrubio would show up.

**Comment by Vlaaaaaaad** [comment]
@davidkarlsen I saw that you approved and got https://github.com/helm/charts/pull/17218 merged. Any chance you can do the same here? ;;)

**Comment by zanhsieh** [comment]
@Vlaaaaaaad 
Please bump the chart to latest version (again). Sorry for long waiting. Now I could get this chart moving again.

**Comment by Vlaaaaaaad** [comment]
@zanhsieh done! Updated from my phone but I think it looks good. 

Thank you for taking over the chart!

**Comment by zanhsieh** [comment]
@Vlaaaaaaad 
Sorry again. Another version bump please.

**Comment by Vlaaaaaaad** [comment]
@zanhsieh: no worries. Done!

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
