### PR TITLE
[incubator/kwatchman] Initial creation

### PR DESCRIPTION
**Pull request by snebel29**
Hi,
I'm creating this new chart from scratch, in order to allow deployments of the new tool [kwatchman](https://github.com/snebel29/kwatchman) which I'm the creator of.

It's pretty much a simple 1 replica deployment tool that is not even exposed, I hope everything is ok and I'm not missing anything since it's late here, so I can move the chart over stable soon.

Thanks in advance!

### CODE REVIEW

**Comment by maorfr** [comment]
hey @snebel29 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by snebel29** [comment]
Hi @maorfr ,
I will definitively take a look, thanks

**Comment by snebel29** [comment]
Any chance to get this PR reviewed? is it missing anything? should I target stable directly instead?

Thanks

**Comment by maorfr** [comment]
Have you considered hosting it? You can do it easily with github pages.
https://github.com/helm/hub/blob/master/docs/github.md

**Comment by snebel29** [comment]
Hi @maorfr 
I was already thinking on using GCS or similar as alternative helm repository, given that this repository would be a potential bottleneck for initial publication and future evolutions.

I didn't know you can use github pages to do so, that's cool I will certainly look to it.

Thanks!

**Comment by snebel29** [comment]
Hi @maorfr 
Once more thanks for the tip, I've finally hosted it within github pages and pushed onto helm hub.

It's a pity not being able to publish into helm charts but at least I will be autonomous and not depend on anyone for approve any future changes..

Cheers

**Pull request closed without merging**
