### PR TITLE
[stable/prometheus-mysql-importer] Add optional labels to each pod 

### LINKED ISSUE #11377: [stable/prometheus-mysql-exporter] Support pod labels
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm v2.12.1
GKE 1.11.6-gke.2

**Which chart**:

prometheus-mysql-exporter
version: 0.2.1

**What happened**:
I have few K8s clusters and deploy Prometheus exporters with specific name e.g. prometheus-mysql-exporter-matomo-dbmain.
Every particular release of MySQL exporter queries single CloudSQL database but doesn't have any labels specific to environment or database, so I can't separate metrics by environment and DB instance name.

**What you expected to happen**:

I'd like to add to each exporter pod specific custom labels, that will be grabbed by Prometheus during the scrape. Similar to [prometheus-postgres-exporter](https://github.com/helm/charts/blob/master/stable/prometheus-postgres-exporter/values.yaml#L188) podLabels variable.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Tarick**
#### What this PR does / why we need it:

Adds user-supplied labels to the pod for better metrics separation with multiple installations.

#### Which issue this PR fixes
  - fixes #11377

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mattfarina** [comment]
@Tarick This chart has not been updated in some time. In the `Chary.yaml` file the `maintainers` key is misspelled as `mantainers`. I know this is not your fault but it is what is stopping CI from passing. Could you please fix it?

**Comment by Tarick** [comment]
@mattfarina 
Synced from master, should be fine now.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
