### PR TITLE
stable/airflow: add initcontainer initdb option

### PR DESCRIPTION
**Pull request by memory**
Add option to run `airflow initdb` as an initcontainer before git-clone.

Signed-off-by: Nathan J. Mehl <n@oden.io>

#### Is this a new chart
No

#### What this PR does / why we need it:

- Add an `airflow.preinitdb` option: if true, the initdb step
  will be run as an initcontainer rather than inline in the
  scheduler startup; this can work around dependencies in custom
  db hooks that prevent initdb from running.

- fix a bug wherein if the git-clone initcontainer was not activated,
  but the git-sync sidecar container was, the web and scheduler
  deployments would fail due to not correctly creating the
  git-clone-secret volume, which is needed by both the initcontainer
  and the sidecar.

- Fix a similar bug for dag path mounting.

- Fix another cosmetic data type mismatch bug in values.yaml:
  `airflow.pools` should be a string containing a JSON
  object, not a yaml map.

#### Which issue this PR fixes
n/a

#### Special notes for your reviewer:
@gsemet hi! :)

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by memory** [comment]
@gsemet poke? :)

**Comment by memory** [comment]
@gsemet hope you're surviving the pandemic well.  I'm hoping to resume forward progress on our airflow work; did you have an opinion about this change?

**Comment by gsemet** [comment]
I am fine thanks ! I think this PR looks ok, let's try to merge it ! I am not sure when preinitdb script might be needed but if you need it, others might want it as well :)

**Comment by WarpRat** [comment]
Just curious, is there a reason this chart uses initdb everywhere instead of upgradedb? AFAICT the only difference is the recreation of all the default connections. I'll be happy to submit a pull request to allow users of this chart to have a choice between the two, I was just curious if there was something I was missing re upgradedb?

**Comment by gsemet** [comment]
Hi. Actually I never used it, I don’t remember seeing this.
It should just work for new db and also for existing one, so if you have a PR I’ll welcome it !

**Pull request merged**
