### PR TITLE
[stable/prometheus] Add env variables to stateful set

### LINKED ISSUE #17544: [stable/prometheus] prometheus-server statefulset doesn't set environment variables
When deploying `prometheus-server` as a _statefulset_ it doesn't set environment variables from the `server.env` values, like the _deployment_ does.

Deployment:

https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-deployment.yaml#L70-L73

Statefulset:

https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-statefulset.yaml

Making container configuration equal both a deployment and statefulset would be very useful.

### PR DESCRIPTION
**Pull request by iainbowman**
Signed-off-by: IainBowman <iain.bowman@gmail.com>

#### What this PR does / why we need it:
Adds ability to use defined server environment variables in the stateful set 
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #17544

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@iainbowman 
Could you resolve the conflict chart please?
stable/prometheus/Chart.yaml

**Comment by iainbowman** [comment]
Chart version updated

**Comment by zanhsieh** [comment]
/assign

@iainbowman 
Could you bump the chart version to latest please? Thank you.

**Pull request closed without merging**
