### PR TITLE
[stable/influxdb] Adds missing headless service configuration.

### LINKED ISSUE #20204: [stable/influxdb] Missing headless service configuration.
**Describe the bug**

> https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
>> StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/influxdb

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by hydra-bu**
Other modifications:
1. add release label to statefulset.yaml.
2. modify annotations syntax in values.yaml.

Signed-off-by: spring-bu <bushengquan@gmail.com>

>>StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #20204 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lelithium** [comment]
Hi ! Thanks for all your work on this chart,

Does this PR mean that the chart is unusable in its current form ? If so, is there a fallback version that would be more suited ?

**Comment by Aisuko** [comment]
@lelithium You are welcome. This PR includes the `headless` service for `Statefulset` of Influxdb, according to the k8s documents we know that `Statefulset` must be work with `headless` service and you can get more information in issue #20204.  This PR just fixed that issue.  I'm sorry for there is not have a fallback version.

**Comment by lelithium** [comment]
@Aisuko thank you for your quick response. I'll delay upgrading our custom InfluxDB chart to this community-maintained one for now then ! Thanks again for your work

**Comment by Aisuko** [comment]
Yes, you are right. These days has some broken change in this chart. Please just keep your stable version as a backup. And do not upgrade in the production environment.

**Comment by spring-bu** [comment]
> Hi ! Thanks for all your work on this chart,
> 
> Does this PR mean that the chart is unusable in its current form ? If so, is there a fallback version that would be more suited ?
hello, sir.
The current version works for a single replica, but they cannot communicate without headless service when starting multiple replicas.

**Comment by Aisuko** [comment]
@spring-bu Hello, sir. Thanks for your cleanly work. The CI-auto test there may got something wrong.

**Pull request closed without merging**
