### PR TITLE
[stable/rocketchat/ Add a member of Rocket.Chat Team to reviewers

### PR DESCRIPTION
**Pull request by geekgonecrazy**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
We'd like to prevent the chart from getting broke again I'm not sure what the policy is here.  But having a member of the Rocket.Chat team able to be notified of changes will help us ensure it keeps working.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by verwilst** [comment]
Please signoff your commits.

**Comment by geekgonecrazy** [comment]
Thanks @maorfr !

**Pull request merged**
