### PR TITLE
[stable/redis] Update exporter img

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
https://github.com/oliver006/redis_exporter/releases

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by pipko** [comment]
Isn't it better to create sidecar container for the exporter? As it usually does in mysq, mongodb, rabbitmq and lots of other charts?

**Comment by naseemkullah** [comment]
I think both approaches work? But maybe there is a clear advantage to the sidecar approach and if so we could make another PR to refactor accordingly. 

Question is what’s the major advantage to the sidecar approach?

**Comment by pipko** [comment]
The main approach is the fewer number of pods, I think. Exporters itself have no sense without main application, so the way how to sidecar containers share their lifecycle with parent application is almost the main goal of sidecar containers. There are some additional preferences, like minimal distance to the parent application (good for monitoring issues).

**Comment by naseemkullah** [comment]
Cool, we should do that then.

QQ: What about fewer number of containers vs fewer number of pods. Suppose we had 10 instances of redis each with its own sidecar VS have a deployment of the exporter scraping all 10 instances. ?

**Pull request merged**
