### PR TITLE
stable/metallb: remove maintainer.

### PR DESCRIPTION
**Pull request by danderson**
#### What this PR does / why we need it:

Empirically I'm not the maintainer of this chart, it's getting significant changes merged without me being involved. As such, I can't really vouch for what's in it, nor can I provide support for MetalLB when it's installed via Helm. This PR reflects that in Chart.yaml.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by danderson** [comment]
Please advise on how to override lint, which is complaining that this chart has no maintainers. I do want my name removed from Chart.yaml, so... How do we do this?

**Comment by scottrigby** [comment]
It sounds like this chart should be deprecated for now. See https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by maorfr** [comment]
hey @danderson,

we have been working hard lately to add new maintainers to charts and to fix existing ones (adding existing maintainers to be trusted collaborators. ask @zanhsieh :1st_place_medal:).

i'm getting a feeling that you are leaving us with mixed feelings, and i'd like to suggest an alternative:
we fix this situation by adding you as a trusted collaborator and you remain the chart's owner! in addition, i volunteer to be added as a maintainer as well to help.

if that is something you are willing to consider, i think it will be awesome. i've taken the liberty and sent you an invitation to join as a trusted collaborator on the repo. feel free to ignore that if you choose to leave. no hard feelings!

thanks for your on going contributions!

**Pull request closed without merging**
