### PR TITLE
[stable/mariadb] Fix configurable parameters

### PR DESCRIPTION
**Pull request by tomislater**
**What this PR does / why we need it**:
There is a typo in README.md file.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by tomislater** [comment]
Ohh, I see `ERROR: Chart version not ok. Needs a version bump.`. I will fix it.

**Pull request merged**
