### PR TITLE
[stable/external-dns] Add the ability for external-dns to manage records with Istio Virtual…

### PR DESCRIPTION
**Pull request by thomasv314**
Add the ability for external-dns to manage records with Istio Virtual Service resources

Required when either of these PR's is merged:

 https://github.com/kubernetes-sigs/external-dns/pull/1358
 https://github.com/kubernetes-sigs/external-dns/pull/1607

#### What this PR does / why we need it:
This PR gives external-dns the ability to inspect VirtualService resources and delegate domain records to them.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by thomasv314** [comment]
This should be good to go now that istio virtualservices are supported in external-dns 

https://github.com/kubernetes-sigs/external-dns/pull/1607

/assign @juan131

**Comment by Karthik-13** [comment]
@thomasv314 @juan131 will this feature be merged soon? We are running istio and knative workloads in our cluster with external-dns configured and this would solve a lot of our problems

**Comment by juan131** [comment]
Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), this Bitnami maintained Helm chart is now located at [bitnami/charts](https://github.com/bitnami/charts/). Please visit the [bitnami/charts](https://github.com/bitnami/charts/) GitHub repository to create Issues or PRs.

In [this issue](https://github.com/helm/charts/issues/20969) we tried to explain more carefully the reasons and motivations behind this transition, please don't hesitate to add a comment in this issue if you have any question related to the migration itself.

**Comment by thomasv314** [comment]
@juan131 I appreciate you taking the time to clarify, thanks!

@Karthik-13 this is merged into bitnami/charts: https://github.com/bitnami/charts/pull/3216

**Comment by Karthik-13** [comment]
@thomasv314 @juan131 The helm chart has the support for virtualservice added. But the image mentioned in values.yaml doesn't have the feature and is causing the pod to fail.
I've created an issue under bitnami chart repos here: https://github.com/bitnami/charts/issues/3275

Could you please specify which version of bitnami/external-dns image to use?

**Comment by thomasv314** [comment]
@Karthik-13 Yep, IMO that's not this charts responsibility. I built off master and pushed to our private registry, the functionality should be available in the next tagged release of external-dns.

**Pull request closed without merging**
