### PR TITLE
[stable/airflow] Update the default value of dags.path in the README

### PR DESCRIPTION
**Pull request by valouille**
Update the default value of dags.path in the README to match the actual default value in values.yaml file

### CODE REVIEW

**Comment by thesuperzapper** [comment]
While I agree that we should change this, the way this repo works is a bit stupid, and this would result in a new release being cut, we should try and work this change into another larger fix.

**Comment by cpanato** [comment]
@valouille please bump the chart version

**Comment by valouille** [comment]
@cpanato @thesuperzapper I'm not sure what to do. Should I bump the chart version or let you include this change into another larger fix ?

**Comment by thesuperzapper** [comment]
@valouille, I think rename the PR/Commit `[stable/airflow] documentation fixes`, and add the secondary change you mentioned in #22601 which is to change the README.md title to `Airflow Helm Chart`.

Don't forget to rebase and squash.

**Comment by thesuperzapper** [comment]
Additionally, we might want to include add docs about the issue you experienced in #22515 

Specifically:
* add a WARNING docstring in the `values.yaml` for `dags.installRequirements` which says: 
  * "if set to `true`, and you are using `dags.git.gitSync`, you must also enable `dags.initContainer` to ensure the requirements.txt is available at Pod start"
* add a NOTE docstring under `values.yaml` for `dags.initContainer.enabled` which says:
  * "this is mostly used for when `dags.installRequirements` is `true` to ensure that requirements.txt is available at Pod start"
  * (also remove the "in most environments, you can leave this as false" NOTE)

**Comment by alexbegg** [comment]
> Additionally, we might want to include add docs about the issue you experienced in #22552
> 
> Specifically:
> 
> * add a WARNING docstring in the `values.yaml` for `dags.installRequirements` which says:
>   
>   * "if set to `true`, and you are using `dags.git.gitSync`, you must also enable `dags.initContainer` to ensure the requirements.txt is available at Pod start"
> * add a NOTE docstring under `values.yaml` for `dags.initContainer.enabled` which says:
>   
>   * "this is mostly used for when `dags.installRequirements` is `true` to ensure that requirements.txt is available at Pod start"
>   * (also remove the "in most environments, you can leave this as false" NOTE)

Yes please, I just got super confused about this exact thing today and if that was there it would have made more sense to me

**Comment by thesuperzapper** [comment]
@alexbegg, so feel free to make those changes and force push this PR

**Comment by alexbegg** [comment]
Another mistake on the readme, in the "Airflow-Configs/Connections" and "Airflow-Configs/Variables" sections, the first sentence correctly states the values are `scheduler.connections` and `scheduler.variables` but for both of the code blocks they need to be updated to show connections and variables under "scheduler" instead of "airflow"

**Comment by alexbegg** [comment]
Also @valouille or @thesuperzapper if you want I can make a new PR with all the documentation fixes and then this can be closed

**Comment by valouille** [comment]
Sounds good to me !

**Comment by alexbegg** [comment]
Ok new PR is made, I also caught a couple more fixes for the readme: https://github.com/helm/charts/pull/22675

**Comment by valouille** [comment]
Thank you, let me close this PR then.

**Pull request closed without merging**
