### PR TITLE
[stable/prometheus-operator] Upgrade dependencies

### PR DESCRIPTION
**Pull request by krichter722**
#### Is this a new chart
No.

#### What this PR does / why we need it:
Profit from better logging in Grafana.

#### Which issue this PR fixes
./.

#### Special notes for your reviewer:
./.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by krichter722** [comment]
/assign @vsliouniaev

Do you have any idea why the linter complains about `Error: requirements.lock is out of sync with requirements.yaml`. That means that `helm dependency update` can't be used, right?!

**Comment by vsliouniaev** [comment]
It means that your lock file doesn't correspond to the dependencies file. I believe you would get the same error from `helm lint`

**Comment by krichter722** [comment]
@vsliouniaev I error occurs after running `helm dependency update` in `stable/prometheus-operator`. The result are the changes of this PR. I assume that the result should be correct and thus I don't understand the complaint by the `lint-charts` check. `helm lint` doesn't complain about anything.

**Comment by krichter722** [comment]
As soon as #21619 is merged, I'll try to reproduce with the helm version used in the linter job.

**Comment by vsliouniaev** [comment]
Could you please bump the chart version? Looks like the test cluster has been fixed

**Comment by krichter722** [comment]
@vsliouniaev I rebased the PR on master. The linter error is still raised. If I run `helm lint` with the same `helm` version that is used in the CI job, i.e. 

```
docker run -it -v $(pwd)/charts:/mnt --entrypoint sh alpine/helm:2.15.2
```

and then

```
cd stable/prometheus-operator && helm lint
```

I get 

```
# helm lint
==> Linting .
Lint OK

1 chart(s) linted, no failures
```

I have no idea why the CI job is failing. Do have any advise?

**Comment by krichter722** [comment]
The versions have been updated meanwhile.

**Pull request closed without merging**
