### PR TITLE
cert-manager: fast-forward to upstream 9e8c3ad8

### PR DESCRIPTION
**Pull request by munnerz**
* Bump manifests for v0.5.2 (jetstack/cert-manager#1087)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by kragniz — APPROVED** [review]
/lgtm
/approve

**Comment by munnerz** [comment]
Looks like the issues with the crd-install CRD are causing problems in CI too.

When the chart is being removed, CRDs are hanging around causing subsequent failures 😢

**Comment by munnerz** [comment]
cc @mattfarina would you mind taking a look at the `helm/charts` e2e cluster and cleaning up the Certificate, Issuer and ClusterIssuer CRDs?

This is a bit of an ongoing issue too 😬 would be brilliant if we can come up with a solution (perhaps we leave those there, and in CI somehow set `createCustomResources=false`?

**Comment by munnerz** [comment]
:pray: maybe someone has recycled the e2e cluster recently

/retest

**Pull request merged**
