### PR TITLE
[stable/mongodb-replicaset] Update MongoDB Exporter

### PR DESCRIPTION
**Pull request by ricoberger**
#### What this PR does / why we need it:

Update the MongoDB exporter to version [0.11.0](https://github.com/percona/mongodb_exporter/releases/tag/v0.11.0). Remove the the values for the `--mongodb.socket-timeout` and `--mongodb.sync-timeout` flag.

Another option would be to add the socket and connection timeout to the [connection string](https://docs.mongodb.com/manual/reference/connection-string/#timeout-options) and change the value names to sth. like `metrics.connectTimeoutMS` and `metrics.socketTimeoutMS`.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ricoberger** [comment]
Hi, is there any chance to get this merged?

**Review by steven-sheehy — APPROVED** [review]
/lgtm

**Pull request merged**
