### PR TITLE
add predator chart

### PR DESCRIPTION
**Pull request by enudler**
Signed-off-by: Eli Nudler <enudler@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md

### CODE REVIEW

**Comment by enudler** [comment]
@juan131 can you please take a look?

**Comment by juan131** [comment]
Hi @enudler 

I'm not one of the approvers of the repo (I'm just reviewer/approver on the charts maintained by Bitnami). Please find out the list of approvers in the link below:

https://github.com/helm/charts/blob/master/OWNERS

I'd also recommend you to include this PR in the Charts Office Hours agenda so the contribution of a new chart can be properly discussed.

**Comment by enudler** [comment]
/assign @maorfr 
Will be really glad if you can take a look

**Comment by maorfr** [comment]
Hey @enudler 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by enudler** [comment]
hey @maorfr 
Actually i did that but i thought it will be more official if's get to the 'main' helms repo

**Comment by maorfr** [comment]
We are trying to move away from 'main', and helm hub brings the solution. Looking forward, the hub is where users will search for charts, so great that you are already hosting! I took a look, very nice work!

**Comment by enudler** [comment]
ok thank you @maorfr

**Pull request closed without merging**
