### PR TITLE
[stable/sealed-secrets]feat: Update to 0.12.2

### PR DESCRIPTION
**Pull request by LucasBoisserie**
## What this PR does / why we need it:
Update to 0.12.2

#### Special notes for your reviewer:
make diff with https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.1/controller.yaml

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by srueg** [comment]
Please update the `image.tag` in the `README` accordingly.

**Comment by olib963** [comment]
LGTM /approve

**Pull request merged**
