### PR TITLE
[stable/kube-ops-view] Add tolerations

### PR DESCRIPTION
**Pull request by victorsalaun**
#### What this PR does / why we need it:

Add tolerations 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
This should also be added to the readme.
And should it be {} or []?

**Comment by victorsalaun** [comment]
Thanks @maorfr for looking at my PR.
There is no configuration table on the readme, that's why I didn't add the reference on the readme.
Looking at other helm charts, I've chosen the right type `[]`

**Pull request merged**
