### PR TITLE
allow ssl verificaion to be turned off

### PR DESCRIPTION
**Pull request by daniel-garcia**
This MR allows backends to use untrusted SSL certs. 

replaces #3044

### CODE REVIEW

**Comment by kachkaev** [comment]
@krancour could you please review this PR? It's really useful for running k8s dashboard behind traefik.

**Comment by kachkaev** [comment]
ping @krancour 😃  It'd be great if you could have a look at this and [other pending PRs](https://github.com/kubernetes/charts/pulls/assigned/krancour) or share some info on your availability.

@jdumars @unguiculus @mattfarina @prydonius is it possible to get an approval for some of traefik PRs by another community member? This one has been on hold for two weeks now 🤔

**Comment by krancour** [comment]
@kachkaev sorry. Re: my availability, it's certainly limited, but I do try and make a point of checking Traefik-related issues/PRs that need my attention every few days. Admittedly, I don't do that by looking at what's assigned to me (because some issues may not have been / aren't yet). Instead, I search my notifications for the string "traefik." Issues / PRs that don't have that string in their title slip through the cracks. (fwiw, since there are so many charts in this repo, all issues/PRs really should lead with `[incubator|stable]/chart-name`.)

I will look at this.

Re: other PRs, the most recent ones where where the ball's in my court were opened three days ago. Respectfully, some patience might be in order.

**Pull request merged**
