### PR TITLE
Typo fix in drupal/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
line 46: tables lists->table lists 
There are many such errors in stable directory.

### CODE REVIEW

**Comment by javsalgar** [comment]
LGTM

**Review by javsalgar — APPROVED** [review]

**Comment by sameersbn** [comment]
@AdamDang thanks for the contribution. #4231 includes the same fix and some additions fixes too.

**Comment by AdamDang** [comment]
OK, Sorry for this mistake.
Thanks a lot.

**Pull request closed without merging**
