### PR TITLE
[incubator/haproxy-ingress] Labels are not compatible with Istio requirements

### LINKED ISSUE #22068: [incubator/haproxy-ingress] Labels are incompatible with Istio requirements
**Describe the bug**
Deployment and DaemonSet `app` labels are incompatible with [Istio requirements](https://istio.io/docs/ops/deployment/requirements/)
> Deployments with app and version labels: We recommend adding an explicit app label and version label to deployments. Add the labels to the deployment specification of pods deployed using the Kubernetes Deployment. The app and version labels add contextual information to the metrics and telemetry Istio collects.
    The app label: Each deployment specification should have a distinct app label with a meaningful value. The app label is used to add contextual information in distributed tracing.
    The version label: This label indicates the version of the application corresponding to the particular deployment.

For what I can see [here](https://github.com/helm/charts/blob/958ca1d894c00001be0218227e3dd7d5bb7d2831/incubator/haproxy-ingress/templates/controller-deployment.yaml#L6) and [here](https://github.com/helm/charts/blob/958ca1d894c00001be0218227e3dd7d5bb7d2831/incubator/haproxy-ingress/templates/default-backend-deployment.yaml#L6) the default to the chart name.

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[incubator/haproxy-ingress]

**What happened**:
`app` label for Deployment and DaemonSet is incompatible with Istio requirements

**What you expected to happen**:
`app` label for Deployment and DaemonSet should be incompatible with Istio requirements, their `app` label should be unique

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by irizzant**
#### Is this a new chart
NO

#### What this PR does / why we need it:
PR changes `app` label to restore Istio requirements compatibility
#### Which issue this PR fixes
  - fixes #22068

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X ] Chart Version bumped
- [X ] Variables are documented in the README.md
- [X ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by xianlubird** [comment]
Pls add default values

**Comment by irizzant** [comment]
@xianlubird what is the default value you suggest? Is it ok now?

**Pull request merged**
