### PR TITLE
[stable/metabase] Fixes compatibility with 1.16

### PR DESCRIPTION
**Pull request by daixiang0**
To support 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

Signed-off-by: Xiang Dai 764524258@qq.com

### CODE REVIEW

**Comment by daixiang0** [comment]
@zanhsieh test pass!

**Comment by zanhsieh** [comment]
@daixiang0 
This chart does not have owner. 
@juan131 
Could you help to merge please? Thank you.

**Comment by juan131** [comment]
Hi @daixiang0 @zanhsieh 

I'm not in the OWNERS list of this chart nor in the OWNERS of the whole repository (check https://github.com/helm/charts/blob/master/OWNERS)

I'm just maintainer of the charts maintained by Bitnami.

/unassign @juan131 
/assign @unguiculus @scottrigby

**Comment by daixiang0** [comment]
@unguiculus @scottrigby any input?

**Comment by brunowego** [comment]
ping

**Comment by brunowego** [comment]
Do not forget add `selector` to `./templates/deployment.yaml`:

```yaml
spec:
  selector:
    matchLabels:
      app: {{ template "metabase.name" . }}
```

**Comment by daixiang0** [comment]
@brunowego thanks, done.

**Comment by daixiang0** [comment]
ping @pmint93 @unguiculus @scottrigby

**Comment by daixiang0** [comment]
ping @pmint93 @unguiculus @scottrigby

**Comment by pmint93** [comment]
I'm in process of being maintainer for this chart
Currently I have no permission to merge this PR until #19291 was merged, please wait ;)

**Comment by pmint93** [comment]
@daixiang0 Can you please bump to the latest version ? then I can lgtm this

**Comment by daixiang0** [comment]
@pmint93 sure, done.

**Pull request merged**
