### PR TITLE
[stable/rabbitmq-ha] Upgrade RabbitMQ to 3.8.8 version

### PR DESCRIPTION
**Pull request by tyranron**
#### What this PR does / why we need it:

Upgrades `stable/rabbitmq-ha` Helm chart to use the [latest 3.8.8 RabbitMQ](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.8) by default.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by tyranron** [comment]
[`3.8.8-alpine` Docker image](https://hub.docker.com/_/rabbitmq) is not yet published, but it usually arrives in 24 hours.

**Comment by tyranron** [comment]
@lachie83 @steven-sheehy `3.8.8` Docker image is published now.

**Review by steven-sheehy — APPROVED** [review]
/assign
/ok-to-test

**Comment by steven-sheehy** [comment]
This chart has been deprecated and is no longer maintained. It is recommended to use the Bitnami maintained [RabbitMQ chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) which has a similar feature set, including high availability. Thanks!

**Pull request closed without merging**
