### PR TITLE
[stable/kube-lego] update maintainers to use github ids

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
@mattfarina perhaps we could add this check for GitHub IDs as maintainers as part of the CircleCI static tests?

**Comment by prydonius** [comment]
This is failing because we don't deal with Helm's `required` values. We should bring this up again during the next charts chat.

**Comment by mattfarina** [comment]
@prydonius I added it to the agenda so we don't forget

**Comment by mattfarina** [comment]
@prydonius in the charts chat today we discussed this issue. From what we understand, the pattern used in other charts is to wrap the deployment in an if checking for the required value. If it's not there the deployment doesn't work so a user would need to check the notes.

For example, the ghost chart...
https://github.com/kubernetes/charts/blob/16630ee80a8ec6ad17f08c373a57bf98f0ffb1de/stable/ghost/templates/deployment.yaml#L1-L3

@viglesiasce how would this work with e2e testing though?

**Comment by prydonius** [comment]
Yes that approach has a better UX around it as the NOTES.txt can be used to provide instructions to correct the issue. The CI will simply pass in this case because it detects that there was no Deployment created (i.e. it only fails if there are pods and they don't enter a running state).

**Comment by unguiculus** [comment]
Merging this since the discussion is not really related to this PR and otherwise it is fine.

**Pull request merged**
