### PR TITLE
[NEW] AWS cluster autoscaler

### PR DESCRIPTION
**Pull request by mgoodness**
Installs the [cluster autoscaler on AWS](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws) for any number of autoscaling groups.

`autoscalingGroups` is a list. Not sure how that should be notated in the README.

### CODE REVIEW

**Comment by mgoodness** [comment]
May have submitted prematurely. Let me make sure it works as expected.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
Anybody with an AWS cluster willing to help test this?

**Comment by mgoodness** [comment]
@viglesiasce I'm running this chart on two different AWS clusters, each spanning three AZs. Works like a dream. If nobody else steps up to test, it's probably a low-risk merge.

**Comment by prydonius** [comment]
I was able to deploy it, but did not verify the autoscaling ability - @mgoodness I'll take your word on that :P.

**Pull request merged**
