### PR TITLE
Improve etcd statefulset template

### PR DESCRIPTION
**Pull request by mpeters**
+ Fix bash'ism in sh command for stderr redirection. The old line
results in process forking and a loop that doesn't finish
+ etcdctl defaults to simple output now which is comma separated
+ There are some scenarios when recovering from a crash where
/var/run/etcd/default.etcd exists but /var/run/etcd/member_id does not,
so make sure both exist before trying to use it to recover

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mpeters** [comment]
ping (to keep issue alive)

**Comment by mpeters** [comment]
ping (to keep issue alive)

**Comment by mpeters** [comment]
ping (to keep issue alive)

**Comment by mpeters** [comment]
ping (to keep issue alive)

**Comment by zanhsieh** [comment]
@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr
Could you guys LGTM this PR please? Thank you.

**Pull request merged**
