### PR TITLE
[stable/postgresql] Fix *.extraVolumes typo in README.md

### PR DESCRIPTION
**Pull request by deifyed**
#### What this PR does / why we need it:
Quick fix of two typos in README.md

#### Special notes for your reviewer:
Very quick (2 character change)

#### Checklist
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@deifyed 
Could you sign DCO as well as bump the chart version to the latest please? Thank you.

**Comment by deifyed** [comment]
Done. Sorry. Was hoping such a small change wouldn't require me having to dig into contributions.md, but alas. My bad.

**Review by miguelaeh — APPROVED** [review]
Thank you very much for the PR!!

**Pull request merged**
