### PR TITLE
Update testlink image to version 1.9.15-r4

### PR DESCRIPTION
**Pull request by joseajp**
Bump testlink image version to 1.9.15-r4

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@joseajp Looks like the dependency on the mariadb chart is failing on the 1.5 in that version of the chart. Can you update the dependency to 0.5.6 of the mariadb chart and run a helm dependency update. This should fix the broken CI

**Review by lachie83 — CHANGES_REQUESTED** [review]
Please update the mariadb dependency to chart version 0.5.6 and regenerate the requirements.lock using helm dependency update

**Comment by joseajp** [comment]
Updated MariaDB chart version to 0.5.6

**Comment by viglesiasce** [comment]
Ready for your next pass @lachie83

**Comment by prydonius** [comment]
Going to close this one out for #493. Thanks @joseajp.

**Pull request closed without merging**
