### PR TITLE
[incubator/elasticsearch] Support custom URI for discovery service

### PR DESCRIPTION
**Pull request by pietdaniel**
**What this PR does / why we need it**:

This PR add supports for a shortened `DISCOVERY_SERVICE` envvar entry.

Previously, this was hard coded to:

`{{ elasticsearch.fullname }}-discovery.{{ .Relase.Namespace }}.svc.{{ cluster.kubernetesDomain }}`

By doing so, alternative DNS mechanism could not be used for cluster discovery. 

This PR resolves this by conditionally using a shortened value when `cluster.shortenedDiscoveryURI` is given.

The new values is:

```
`{{ elasticsearch.fullname }}-discovery.{{ .Relase.Namespace }}`
```

### CODE REVIEW

**Comment by rendhalver** [comment]
This is hard coded because that's the name of the service that this chart creates.
Can you explain why you would need to override that?

**Comment by pietdaniel** [comment]
Our deployment requires cross cluster communication, to do so we have a different routing scheme which drops the `.cluster.local` section of the URI. Setting the k8s domain to empty string would be a valid approach but the trailing `.` prevents this.

**Comment by Rigdon** [comment]
@rendhalver As @pietdaniel said we need to be able to refer to service by _only_ `name.namespace` or `name.namespace.scv`. The trailing `.` if we set the clusterDomain to an empty string prevents this.

**Comment by rendhalver** [comment]
Ahh. That makes sense.
That sounds like a useful feature.
Could you add the option to just use that shorter name instead of the full name rather than overriding the while name?
Maybe wrap it in a variable that uses the short name if it's set and the long name if it isn't?

It looks like you need a rebase anyway.
Can you sort that out?

**Pull request closed without merging**
