### PR TITLE
Align names between grafana service and job URL

### PR DESCRIPTION
**Pull request by nseyvet**
**What this PR does / why we need it**:
Align service name and job url to inject datasources in Grafana.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes issue #4485

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by timstoop** [comment]
You also need to increase the `version` in Chart.yaml. That's required for all changes to a Chart.

**Comment by nseyvet** [comment]
@timestoop yes, saw that from build failure.

But the build still seems to fail.  Can not reproduce problem.

**Comment by nseyvet** [comment]
What does this 
```
Error validating data /home/circleci/project/stable/grafana/Chart.yaml with schema test/circle/yaml-schemas/Chart.yaml
	appVersion: Required field missing
```
mean?  There are no appVersion in grafana anywhere.

**Comment by nseyvet** [comment]
Also added an "appVersion" field in Chart.yaml that points to version 4.6.3 of Grafana.  But that should not have been required.

**Comment by timstoop** [comment]
It is required, there have been some changes in the build system recently that made some additional requirements to Charts. Not saying you caused the error, though, it's just that you're the first person working on this Chart to hit the problem with it :)

**Comment by nseyvet** [comment]
The pull-charts-e2e tests failure is related to the configmap handling changes in later kubernetes version (1.9.4+) not the  changes in this PR. 
See https://github.com/grafana/grafana-docker/issues/140

**Comment by nseyvet** [comment]
Tried with 5.0.4 image which is not supposed to use chown anymore as per https://github.com/grafana/grafana-docker/issues/140 .  Still see the following errors in the logs: ```I0328 10:43:34.082] ---Logs from container grafana in pod grafana-7182-1-859c94c46d-x8sj2:---
I0328 10:43:34.445] chown: changing ownership of '/var/lib/grafana/dashboards/..data': Read-only file system
I0328 10:43:34.445] chown: changing ownership of '/var/lib/grafana/dashboards/..2018_03_28_10_34_19.354854507': Read-only file system
I0328 10:43:34.446] chown: changing ownership of '/var/lib/grafana/dashboards': Read-only file system ```
Will revert the change to 4.6.3.

**Comment by unguiculus** [comment]
Closing this in favor of #4437.

**Pull request closed without merging**
