### PR TITLE
[stable/prometheus-operator] Update grafana dependency

### PR DESCRIPTION
**Pull request by bashofmann**
Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>

#### What this PR does / why we need it:
Update grafana dependency. This updates Grafana to 6.4.2

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@bashofmann 
Could you resolve conflicting files please?
stable/prometheus-operator/Chart.yaml
stable/prometheus-operator/requirements.lock
stable/prometheus-operator/requirements.yaml

**Comment by bashofmann** [comment]
Grafana has already been updated to a newer version in another pull request, so this one can be closed :).

**Pull request closed without merging**
