### PR TITLE
[stable/cluster-autoscaler] Support fullnameOverride

### PR DESCRIPTION
**Pull request by yurrriq**
#### What this PR does / why we need it:
Support `fullnameOverride`.

#### Special notes for your reviewer:
Thoughts, @olemarkus?

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
should we add the new field to values.yaml and README.md?

**Comment by yurrriq** [comment]
Sure, good idea. I'll do that now.

**Comment by yurrriq** [comment]
rebased. /ping @maorfr

**Comment by yurrriq** [comment]
I'll have to rebase again after #17569 is merged.

**Comment by yurrriq** [comment]
rebased again. can you `/lgtm` again, @maorfr? Thanks!

**Comment by yurrriq** [comment]
Thanks!

**Pull request merged**
