### PR TITLE
[stable/mercure] Add support for new options

### PR DESCRIPTION
**Pull request by dunglas**
#### What this PR does / why we need it:

Add supports for new Mercure options. Includes #12349 and #12457.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
hey @dunglas,

think you can 'recruit' someone to maintain this chart with you? :)

**Comment by dunglas** [comment]
Definitely. How does it work? I add her/his GitHub handle to the OWNER file?

**Comment by maorfr** [comment]
yes, add to OWNERS and ping me. if you do that on a separate PR, they will be able to review this one :)

**Comment by dunglas** [comment]
@maorfr here we are: https://github.com/helm/charts/pull/13607

**Pull request merged**
