### PR TITLE
[stable/prometheus-operator] do not fail if CRDs exist

### PR DESCRIPTION
**Pull request by joejulian**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Deleting CRDs can cause accidental data loss and should be avoided. If
this best practice is adhered to, reinstallation will fail because the
CRDs already exist. This change allows the installation to succeed even
if the CRDs do already exist.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by VLZZZ** [comment]
@joejulian 
I'm also experiencing the same issue, but my opinion is that this implementation is not full, because if I delete only 1 CRD manually, then this situation will not be handled during next installation and may be misleading.
But it is a great workaround anyway, and should also be implemented IMHO

**Comment by vsliouniaev** [comment]
How does this behave when CRDs are updated or new CRDs are added to the chart?

**Comment by joejulian** [comment]
It's not perfect, but helm doesn't have a good solution for crds and webhooks.

We do have a complete solution, but it's a bit of a hack and doesn't work with helm v3; we do this to avoid breaking installs and upgrades and also add a Job to `kubectl apply` the crd to handle the upgrade.

Since the crds are included as files, this is the best we can do without restoring to hacks.

I'm hoping we'll have some time to create a helm contribution to actually manage crds and webhooks, but for now this is the best we can do.

**Comment by joejulian** [comment]
If you do like the Job idea, I'd be happy to add that to the PR.

**Comment by VLZZZ** [comment]
@vsliouniaev @joejulian 
What about adding something like this to `crds.yaml`

```
{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.createCustomResource -}}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}}
---
{{.Files.Get "crds/crd-podmonitor.yaml"}}
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Prometheus") }}
---
{{.Files.Get "crds/crd-prometheus.yaml"}}
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
---
{{.Files.Get "crds/crd-prometheusrules.yaml"}}
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
---
{{.Files.Get "crds/crd-servicemonitor.yaml"}}
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ThanosRuler") }}
---
{{.Files.Get "crds/crd-thanosrulers.yaml"}}
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Alertmanager") }}
---
{{.Files.Get "crds/crd-alertmanager.yaml"}}
{{- end }}
{{- end }}
```

image

**Comment by vsliouniaev** [comment]
This does not solve for the case where CRDs get new features, which are then used by templates in the chart. This case has been needed in the past already.

**Pull request closed without merging**
