### PR TITLE
[stable/airflow] remove maver1ck from OWNERS

### PR DESCRIPTION
**Pull request by thesuperzapper**
as far as I can see @maver1ck is inactive, and its quite inconvenient because the bot always assigns him, so we never see the incoming PR's

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@gsemet, thoughts?

**Comment by gsemet** [comment]
We can leave some time to @maver1ck to respond. And since we will be moving out of this repository in a few weeks, do not feel it is a urgent operation :)

**Comment by maver1ck** [comment]
OK from my point of view. I have only time to maintain Druid and Cassandra.

**Comment by thesuperzapper** [comment]
@gsemet can you lgtm this?

**Comment by gsemet** [comment]
rebase + update version

**Pull request merged**
