### PR TITLE
[stable/selenium] add extraEnvs to deployments

### PR DESCRIPTION
**Pull request by sburtontx**
Signed-off-by: Sean Burton <sean.burton@civitaslearning.com>

#### What this PR does / why we need it:

The extraEnvs value is useful for setting deployment specific configuration.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by linki** [comment]
/unassign @linki

(I'm not a maintainer anymore)

**Comment by sburtontx** [comment]
@lachie83 @paulczar Should I assign this to someone else to approve?

**Review by cpanato — APPROVED** [review]

**Pull request merged**
