### PR TITLE
[stable/traefik] Add Datadog tracing support

### PR DESCRIPTION
**Pull request by andysnowden**
Signed-off-by: Andy Snowden <andy.snowden@equityzen.com>

#### What this PR does / why we need it:
Add tracing support for Datadog to template that was added in traefik 1.7

Traefik Doc: https://docs.traefik.io/configuration/tracing/#datadog

#### Which issue this PR fixes
No issues

#### Special notes for your reviewer:
None.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by dtomcej** [comment]
@andysnowden  Needs a version bump :)

**Comment by andysnowden** [comment]
@dtomcej someone just beat me, version bumped ;)

**Pull request merged**
