### PR TITLE
[stable/sonarqube] Fix failing deployment and tests

### PR DESCRIPTION
**Pull request by rjkernick**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jcscottiii** [comment]
@rjkernick Which version of k8s are you using?
When I was on 1.8.x, this PR worked fine for me.
Last night, I decided to update our cluster to 1.9.6 and this deployment broke. I kept getting `Read-Only` errors. Did some digging and found out that it was related to this security patch https://github.com/kubernetes/kubernetes/issues/60814

Tried this PR https://github.com/kubernetes/charts/issues/4787 out but it didn't work. But if i revert this patch and make the following change, it works.

```
@@ -115,6 +114,7 @@ spec:
           name: {{ template "sonarqube.fullname" . }}-config
       - name: install-plugins
         configMap:
+          defaultMode: 0755
           name: {{ template "sonarqube.fullname" . }}-install-plugins
```
But yeah, just wanted to gauge how's everything working on your side.

Examples of other charts having this problem:
https://github.com/kubernetes/charts/issues/4272
https://github.com/kubernetes/charts/issues/4166

**Comment by rjkernick** [comment]
I am on 1.8.x, but have also tested it on minikube with 1.9.4. I believe the helm tests run against 1.9.x as well

**Pull request merged**
