### PR TITLE
[stable/jenkins] Issue 22633, remove the wrong value 'master.overwritePluginsFromImage'

### PR DESCRIPTION
**Pull request by UkonnRa**
### What this PR does / why we need it:

Fix the issue #22633, change the wrong value `master.overwritePluginsFromImage`

#### Which issue this PR fixes

Fix the issue #22633 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by UkonnRa** [comment]
In fact, this is a very simple but important bug, just have no idea why you guys have not found and fixed this

**Comment by torstenwalter** [comment]
@UkonnRa Thanks for the PR. Can you fix the DCO check? CI system also requires that you bump the version of the chart. Also an entry in CHANGELOG.md would be great.

Thanks you.

**Comment by Andrei-Stepanov** [comment]
Hi. Please merge.

**Comment by torstenwalter** [comment]
@UkonnRa I included you fix in #23175 so that we can merge it soon.

**Pull request closed without merging**
