### PR TITLE
[stable/traefik] add ssl.upstream to support upstream L4 SSL/TCP

### PR DESCRIPTION
**Pull request by colinhoglund**
**What this PR does / why we need it**:
This change supports using L4 AWS ELBs with an `SSL/TCP` listener and ACM by allowing the user to disable SSL certificates in the traefik configuration while maintaining a separate "HTTPS" entrypoint.

All questions/comments/suggestions regarding the PR, or this architecture, are welcome.

## Example
I can use the following configuration to enforce SSL within traefik, but also use ACM certificates and a L4 ELB w/ PROXY protocol:

```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:*:certificate/*
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
ssl:
  enabled: true
  enforced: true
  upstream: true
externalTrafficPolicy: Local
proxyProtocol:
  enabled: true
  trustedIPs:
    - 10.1.0.0/16
rbac:
  enabled: true
```

This results in the following ELB listener configuration:

screen shot 2018-07-12 at 10 30 14 am

### CODE REVIEW

**Comment by dtomcej** [comment]
@colinhoglund Just to confirm, this setting is used when you want to have 2 separate entrypoints for http and https requests, but all TLS termination is done at your upstream LB?

The result is that you have 2 http entrypoints, with different names....But other than that, nothing is different.

Could you share your use case for why you couldn't just have all http traffic going through one entrypoint?

**Comment by colinhoglund** [comment]
@dtomcej The main reason for maintaining two entrypoints is that I would like traefik to continue to redirect all `http` traffic to `https` by setting ` ssl.enforced: true`.  It is not possible to do this redirect in a layer 4 ELB, and AFAIK it is also not possible if there is only one traefik entrypoint.

**Comment by colinhoglund** [comment]
@dtomcej 
After taking a second look, I think another approach that would work is to add proxyProtocol to the default `httpn` entrypoint when `ssl.enabled: false`.
```
...
      {{- if .Values.proxyProtocol.enabled }}
        [entryPoints.httpn.proxyProtocol]
        {{ template "traefik.trustedips" . }}
      {{- end }}
...
```

I'm wondering if this was just an oversight in the orginal implementation of proxyProtocol, or perhaps I don't fully understand the purpose of the `httpn` entrypoint. I'm not sure what effect this will have on existing deployments, but i'm happy to take this approach if you think it sounds cleaner.

**Comment by dtomcej** [comment]
@colinhoglund If I am not mistaken, when you have `ssl.enabled: false`, it creates a 2nd http entrypoint named `httpn` on `:8880`, and the service forwards traffic on the service from 443 -> 8880.

This was implemented in this PR: (https://github.com/helm/charts/pull/2651)

Can you confirm that is what you are attempting to accomplish?

**Comment by dtomcej** [comment]
@colinhoglund Just read your second comment. Hmmmm. I'm going to have to think about that one.

It is possible that the implementation in this PR is the simplest, since many other changes would possibly be breaking.

**Comment by mattfarina** [comment]
@dtomcej please let us know if this one is ok to merge

/ok-to-test

**Comment by dtomcej** [comment]
@colinhoglund Thought about it, and you should be able to accomplish what you want with:
`ssl.enabled: false` and `ssl.enforced: true`. The changes in this commit:
https://github.com/helm/charts/commit/ba0e74ae383f7fe8780cb7df4800fbd54dddad71

Should enforce that.

Can you confirm?

**Comment by colinhoglund** [comment]
@dtomcej That solution does not work when `proxyProtocol.enabled: true`. As discussed earlier, the following would need to be added to the `httpn` endpoint:

```
...
      {{- if .Values.proxyProtocol.enabled }}
        [entryPoints.httpn.proxyProtocol]
        {{ template "traefik.trustedips" . }}
      {{- end }}
...
```

I'm happy to change the PR to just add proxyProtocol support for httpn. However, I believe there was a possibility this could be considered a breaking change.

**Comment by dtomcej** [comment]
@colinhoglund Reviewed again, and I agree with this PR.

Can you bump the chart version and fix the conflicts?

Want to get this merged!

**Review by mattfarina — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@colinhoglund Still needs a bump of version

**Comment by colinhoglund** [comment]
@davidkarlsen merge conflict resolved.

**Pull request merged**
