### PR TITLE
[stable/jenkins] Fix jobs parsing for configmap by adding toYaml to jobs.yaml template

### PR DESCRIPTION
**Pull request by blaw2422**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by blaw2422** [comment]
verify cla/linuxfoundation

**Comment by viglesiasce** [comment]
@blaw2422 any luck with the CLA? I think you may need to comment `I signed it`

**Comment by jdumars** [comment]
Hi, please get your CLA signed, and we will ok this for testing. Thanks!

**Comment by blaw2422** [comment]
@jdumars, I have tried but am not receiving the email for approve from Linux foundation.

Any idea how to get that resent?

**Comment by blaw2422** [comment]
I signed it

**Comment by blaw2422** [comment]
@jdumars - got the CLA signed, any chance to test this?

**Comment by viglesiasce** [comment]
@blaw2422 is this a breaking change?

**Comment by blaw2422** [comment]
This is either a change to fix, or I misunderstood how to use the jobs
yaml.  I added to readme.  If someone could validate that's the way to use
it.  I'm using this method currently for my stack.

**Comment by viglesiasce** [comment]
i was able to add the job XMLs without the change to the configmap. That said your doc change is awesome. Can you remove the configmap change?

**Pull request merged**
