### PR TITLE
gitlab-ce: Make external ports configurable.

### PR DESCRIPTION
**Pull request by grugnog**
The specific use case for us is running ssh on a non-standard port to reduce scanner/bot noise - it seemed to make sense to include http/https ports configurable at the same time.

### CODE REVIEW

**Comment by grugnog** [comment]
I signed the CLA

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
cc @gtaylor

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Review by viglesiasce — CHANGES_REQUESTED** [review]
Please bump the postgres version to 0.3.0 so that it picks up the fix for Kubernetes 1.5.1 clusters

**Comment by gtaylor** [comment]
Good idea. LGTM!

**Review by gtaylor — APPROVED** [review]

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
You bumped the gitlab chart version to 0.3.0 instead of the postgresql requirement. Gitlab chart version needs to still be bumped albeit to 0.1.2

**Comment by grugnog** [comment]
Not sure what I was thinking there! This version should be the ticket.

**Review by viglesiasce — APPROVED** [review]

**Comment by grugnog** [comment]
@k8s-bot e2e test this

**Pull request merged**
