### PR TITLE
[stable/jaeger-operator] Bump version jaeger-operator to 14.0

### PR DESCRIPTION
**Pull request by alexsn**
#### What this PR does / why we need it:
Bumping to latest released version.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@alexsn @davidkarlsen 
I think it's CRD cleanup problem:
```
I1021 22:32:40.283] Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "jaegers.jaegertracing.io" already exists
```

**Comment by alexsn** [comment]
This PR simply bumps image tag, can this cause the above error?

**Comment by zanhsieh** [comment]
@alexsn

I think you might look at other stable charts with hook implemented to clear CRD.

**Pull request closed without merging**
