### PR TITLE
[stable/prometheus] Add option to configure subpath on server volume mounts

### PR DESCRIPTION
**Pull request by FlavioF**
#### What this PR does / why we need it:
Provide support to Volume Mount Sub Path for all volumes of Prometheus Server Deployment as documented in [Kubernetes Documentation](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath)

In our specific use case we would like to mount multiple alert/rule files in the same directory first to avoid over configuration and second because we want to split rules over different files on prometheus depending on context. Also, we want to be able to mount different ConfigMaps with rules and alerts from different context in the same directory to allow manage rules and alerts in different contexts. 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by cpanato** [comment]
@please sign the DCO in all commits

**Comment by FlavioF** [comment]
@cpanato done

**Comment by FlavioF** [comment]
@cpanato any update? :)

**Comment by cpanato** [comment]
@FlavioF you need to rebase and fix the conflict

**Comment by FlavioF** [comment]
@cpanato done :)

**Comment by cpanato** [comment]
ping @gianrubio @mgoodness

**Comment by gianrubio** [comment]
@FlavioF please update the README.md and the values.yaml

**Comment by FlavioF** [comment]
Thank you for feedback @gianrubio, what do you mean regarding documentation?

Looking into [README](https://github.com/helm/charts/tree/master/stable/prometheus) file it looks that stuff inside extraVolumes are not documented, probably because it is a list with exactly same sintaxe as k8s. 

I have updated values file.

**Comment by FlavioF** [comment]
@gianrubio any update? :)

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Pull request merged**
