### PR TITLE
Adding static IP documentation

### PR DESCRIPTION
**Pull request by Ngob**
Signed-off-by: Benoît Ngô <ngobenoit@gmail.com>

#### What this PR does / why we need it:
@shashiranjan84 
@hbagdi 
This PR add documentation about how to use a static IP for KONG-INGRESS

#### Special notes for your reviewer:
Related to [Kong Ingress #278](https://github.com/Kong/kubernetes-ingress-controller/pull/278)
#### Checklist
- [X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Comment by hbagdi** [comment]
@Ngob Could you please bump the chart version?

**Comment by Ngob** [comment]
@hbagdi I updated the pull request

**Comment by hbagdi** [comment]
@Ngob Could you rebase on master please?
The timing was a little bad, CI just merged in  #13475 .

**Comment by Ngob** [comment]
@hbagdi It has been updated using a rebase.

**Pull request merged**
