### PR TITLE
[incubator/sentry-kubernetes] Make EVENT_LEVELS env configurable

### PR DESCRIPTION
**Pull request by mislavcimpersak**
#### Is this a new chart
No.

#### What this PR does / why we need it:

Make the `EVENT_LEVELS` environment configurable through the `sentry.eventLevels` value.

#### Special notes for your reviewer:

The [underlying code](https://github.com/getsentry/sentry-kubernetes/blob/master/sentry-kubernetes.py#L42) already uses `EVENT_LEVELS`.
This env var can be easily set if sentry-kubernetes is deployed using kube configs, but not if deployed using this helm chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mislavcimpersak** [comment]
Issue is not stale, just never reviewed by the owners 😞

**Comment by mislavcimpersak** [comment]
once again, issue is not stale, just never reviewed by the owners 😞

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Comment by mislavcimpersak** [comment]
@cpanato thank you for reviewing and merging 💯 🌟

**Pull request merged**
