### PR TITLE
[stable/artifactory-ha] Bumping up version to 6.2.0

### PR DESCRIPTION
**Pull request by jainishshah17**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rimusz** [comment]
@jainishshah17 why are you using merged PR #6310 as a base?

**Comment by jainishshah17** [comment]
@rimusz Got confused between too many branches.

**Comment by rimusz** [comment]
I would suggest to close this one and open a new PR :)

**Review by rimusz — CHANGES_REQUESTED** [review]
I would suggest to close this one and open a new PR :)

**Comment by jainishshah17** [comment]
Created new PR https://github.com/helm/charts/pull/7303

**Pull request closed without merging**
