### PR TITLE
[stable/grafana] Now using correct variable in job and deployment template

### PR DESCRIPTION
**Pull request by nkobber**

### CODE REVIEW

**Comment by afritzler** [comment]
Any update on this PR?

**Comment by seanknox** [comment]
@k8s-bot ok to test

**Comment by fetmar** [comment]
@seanknox Thanks so much for this. Is this ready to be merged? It's a very small PR. 😄

**Comment by viglesiasce** [comment]
Closing in favor of #806 which includes this change as well

**Comment by viglesiasce** [comment]
oops i meant #941

**Pull request closed without merging**
