### PR TITLE
[stable/grafana] Added ability to specify a different repository for dashboard download

### LINKED ISSUE #4906: [stable/grafana]Add custom path Grafana dashboard import
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

It would be nice to be able to add a custom path to the dashboard import for internal charts.
So if a url was provided then that would be used instead of the default grafana url.

**Which chart**:
stable/grafana

### PR DESCRIPTION
**Pull request by Towmeykaw**
**What this PR does / why we need it**:
It adds the ability to specify a url for dashboard downloads.

**Which issue this PR fixes** : fixes #4906

### CODE REVIEW

**Comment by ghost** [comment]
cc: @rtluckie

**Comment by Flowkap** [comment]
@towmeykaw you should add [stable/grafana] to the title. I think grafana is not explicitly mentioned.

**Review by prydonius — APPROVED** [review]
/ok-to-test

**Pull request merged**
