### PR TITLE
nginx-ingress: fix metrics/stats service target ports

### PR DESCRIPTION
**Pull request by sylr**

### CODE REVIEW

**Comment by unguiculus** [comment]
/assign
/hold

Will review later.

**Comment by unguiculus** [comment]
What's the reason for this change? It doesn't make sense to have the target port configurable. Changing it would break things. In fact, it would be better to reference the named port in the stats service as well.

**Comment by sylr** [comment]
Using the chart as it is currently I had no endpoints for the metrics service.

I had to do this in order to get it work.

**Comment by monotek** [comment]
If you use this the metrics are exported and scraped by prometheus:

```
    stats:
      enabled: true
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
```

**Comment by unguiculus** [comment]
I have it up and running on our cluster. Works as expected. I don't think this PR makes sense.

**Comment by unguiculus** [comment]
Can we close this?

**Comment by monotek** [comment]
I think so...

**Pull request closed without merging**
