### PR TITLE
[stable/elasticsearch] master-eligible data node

### PR DESCRIPTION
**Pull request by pavdmyt**
#### What this PR does / why we need it:

Allows to configure master-eligible data nodes (`node.master: true`) by setting the following values:

```
Values.master.replicas: 0
Values.data.masterEligible: true
```

Such configuration helps in running Elasticsearch cluster without dedicated master nodes. This simplifies configuration for small/development clusters, where dedicated master nodes are unnecessary.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rendhalver** [comment]
What do you want to achieve with this?
A cluster deployed with this has three master nodes by default so I am not sure what your change with achieve.

**Comment by pavdmyt** [comment]
> What do you want to achieve with this?
> A cluster deployed with this has three master nodes by default so I am not sure what your change with achieve.

@rendhalver the main difference is that there is no dedicated master nodes (`Values.master.replicas` is set to 0). Instead, data nodes become responsible for handling master workloads as well.

**Comment by rendhalver** [comment]
If people are going to change the number of each node type then we have to assume they know what they are doing.
For example I believe you need three master nodes to maintain quorum.
The default number of data nodes is 2. How are you going to maintain cluster state when you only have two data nodes and zero data nodes?

**Comment by pavdmyt** [comment]
> If people are going to change the number of each node type then we have to assume they know what they are doing.

The default values are not changing default chart behavior. `values.yaml` provide user API to configure the elasticsearch cluster and any change assumes knowledgeable decision. 

> For example I believe you need three master nodes to maintain quorum.
> The default number of data nodes is 2. How are you going to maintain cluster state when you only have two data nodes and zero data nodes?

Probably the question was:

> How are you going to maintain cluster state when you only have two data nodes and zero **master** nodes?

If data nodes are set to be master-eligible (`Values.data.masterEligible: true`), than user have to adjust the number of data nodes to maintain a quorum based on this [formula](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain):

```
minimum_master_nodes = (master_eligible_nodes / 2) + 1
```

**Comment by pavdmyt** [comment]
@rendhalver @simonswine @icereval is there any chance to merge this PR?

**Comment by pavdmyt** [comment]
@rendhalver @simonswine @icereval any comments on this PR?

**Comment by pavdmyt** [comment]
@rendhalver @simonswine @icereval any chance to review this PR?

**Pull request closed without merging**
