### PR TITLE
[incubator/common] more logical port

### PR DESCRIPTION
**Pull request by davidkarlsen**
Have a more sensible port in the docs as smtp is 25, and ssh is 22.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/charts/6292)

### CODE REVIEW

**Comment by timstoop** [comment]
Can you add an `appVersion` field to the Chart.yaml, please?

**Comment by davidkarlsen** [comment]
@timstoop fixed. since this is a helper-chart it is a bit unnatural - so the closest was to set it to the chartVersion.

**Comment by timstoop** [comment]
/ok-to-test
That's fine I guess.

**Pull request merged**
