### PR TITLE
[incubator/druid] Update to druid official docker

### PR DESCRIPTION
**Pull request by veRYANgry**
### What this PR does / why we need it:
Updates this chart to use the official docker image of druid. Also makes Google cloud usage more obvious. Cleans of common parts of charts.

#### Special notes for your reviewer:
This was tested on gcp and tested ingesting large files (>1gig). Changes are adapted from a pull request that was removed for some unknown reason.
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by veRYANgry** [comment]
/assign @maver1ck
Please take a look. Thanks for your time

**Comment by veRYANgry** [comment]
Could someone with more experience help me out? Why would the pull-charts-e2e fail when trying to shutdown? Maybe I am completely reading these logs wrong. Thanks to anyone reading this.

**Comment by AWaterColorPen** [comment]
@veRYANgry

**Comment by AWaterColorPen** [comment]
@veRYANgry I am also interesting with this druid chart PR. It seems that zookeeper service don't work well.
```
I0118 04:13:15.667] 2020-01-18 04:04:18,322 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@588] - Cannot open channel to 3 at election address druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local:3888
I0118 04:13:15.667] java.net.UnknownHostException: druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local
```
But I have no idea to figure out the issue.

**Comment by veRYANgry** [comment]
> @veRYANgry I am also interesting with this druid chart PR. It seems that zookeeper service don't work well.
> 
> ```
> I0118 04:13:15.667] 2020-01-18 04:04:18,322 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@588] - Cannot open channel to 3 at election address druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local:3888
> I0118 04:13:15.667] java.net.UnknownHostException: druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local
> ```
> 
> But I have no idea to figure out the issue.

I think I found the issue causing that: 
```
I0118 04:13:14.291]   Warning  FailedScheduling        10m (x3 over 10m)  default-scheduler                                pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```
I don't understand why it would have this issue though

**Comment by AWaterColorPen** [comment]
> > @veRYANgry I am also interesting with this druid chart PR. It seems that zookeeper service don't work well.
> > ```
> > I0118 04:13:15.667] 2020-01-18 04:04:18,322 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@588] - Cannot open channel to 3 at election address druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local:3888
> > I0118 04:13:15.667] java.net.UnknownHostException: druid-ehg19amajx-zookeeper-2.druid-ehg19amajx-zookeeper-headless.druid-presubmit-19513-1218382853474095104-ehg19amajx.svc.cluster.local
> > ```
> > 
> > 
> > But I have no idea to figure out the issue.
> 
> I think I found the issue causing that:
> 
> ```
> I0118 04:13:14.291]   Warning  FailedScheduling        10m (x3 over 10m)  default-scheduler                                pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
> ```
> 
> I don't understand why it would have this issue though
> or this one above it:
> 
> ```
> I0118 04:13:14.291]   Warning  FailedScheduling        10m (x3 over 10m)  default-scheduler                                pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
> ```
> 
> I'm not sure how to figure out what the test node looks like. I'm guessing it's taking too many resources?

I found than 3 statefulset apps, middle-manager, postgresql on same node, and historical has no node. assign,

**Comment by AWaterColorPen** [comment]
middle-manager, postgresql on same node.  does it help to change persistence.accessMode from RMO to RWM?

**Comment by AWaterColorPen** [comment]
@veRYANgry hello guys, I think I found the issue. there is the PR https://github.com/veRYANgry/charts/pull/1 for your branch.

**Comment by veRYANgry** [comment]
@AWaterColorPen Thanks for the pull, that line of code should not have been left in.

**Comment by veRYANgry** [comment]
I'll need to fix the commit signoff later.

**Comment by veRYANgry** [comment]
@maver1ck
Please take a look, sorry for the issue before. I would really like to see this added so others can work off of it.

**Comment by maver1ck** [comment]
Sorry I didn't have time to look at it earlier.
But I think @AWaterColorPen PR is better to merge now:
https://github.com/helm/charts/pull/22393

**Comment by veRYANgry** [comment]
> Sorry I didn't have time to look at it earlier.
> But I think @AWaterColorPen PR is better to merge now:
> #22393

Yes! Thanks for getting time to look at @AWaterColorPen PR. I left this closed for that reason

**Pull request closed without merging**
