### PR TITLE
Added configuration for provider rfc2136 (see #11779)

### LINKED ISSUE #11779: [stable/external-dns] add configuration for provider rfc2136
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
-

**Which chart**:
stable/external-dns

**What do you want**:
To be able to configure a rfc2136 provider and its options

Following what you've done for other providers and taking into account flags that external-dns supports, I suggest something like this:

```
provider: rfc2136

rfc2136:
  host: ""
  port: 53
  zone: ""
  tsigSecret: ""
  tsigSecretAlg: hmac-sha256
  tsigKeyname: externaldns-key
  tsigAxfr: true
```

Fancy stuff:

- rfc2136.host is required if provider is rfc2136
- rfc2136.zone is required if provider is rfc2136
- if no rfc2136.tsigSecret is defined, use `--rfc2136-insecure`

### PR DESCRIPTION
**Pull request by elpadrinoIV**
Signed-off-by: Nicolas Dascanio <nicolas.dascanio@intraway.com>

#### What this PR does / why we need it:
It adds configuration parameters for provider rfc2136 in stable/external-dns chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #11779 

#### Special notes for your reviewer:
The default is to use a tsig secret. It may be changed to use an insecure connection as default .
I didn't change the chart version (I don't know if this should be part of the PR). The change is a new feature and backward compatible, so I guess the chart version should move to 1.7.0.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@elpadrinoIV please bump the chart version

**Comment by elpadrinoIV** [comment]
Bumped to version 1.7.0

**Review by cpanato — APPROVED** [review]

**Pull request merged**
