### PR TITLE
[incubator/kafka] Simplifies kafka chart by removing configmap

### PR DESCRIPTION
**Pull request by fedenusy**
### Motivation

The kafka configmap is unnecessary, and often creates issues during helm updates (see https://github.com/kubernetes/helm/issues/3275). This PR removes the configmap in order to make helm updates more reliable.

### CODE REVIEW

**Comment by ebabani** [comment]
Any updates on this PR? Would be useful to avoid helm upgrade errors.

**Comment by unguiculus** [comment]
cc @faraazkhan @h0tbird @benjigoldberg

**Comment by fedenusy** [comment]
cc @faraazkhan @h0tbird @benjigoldberg

Had to bump version number, going to need approval again.

**Comment by benjigoldberg** [comment]
\lgtm

Thanks for the PR @fedenusy

**Comment by fedenusy** [comment]
@benjigoldberg thanks for the quick reply! Looks like k8s-ci-robot ignored your "\lgtm" though, backslash instead of forward slash XD

**Comment by benjigoldberg** [comment]
@fedenusy haha sorry man 🤦‍♂️ 

/lgtm

**Pull request merged**
