### PR TITLE
[stable/traefik] Allow debug flag to be specified

### PR DESCRIPTION
**Pull request by kevinjqiu**

### CODE REVIEW

**Comment by krancour** [comment]
Traefik exposes `logLevel` setting, which this chart already surfaces. I'm trying to understand why there's a separate setting in Traefik for enabling debug logging, because it's reasonable to think one enables debug simply by setting `logLevel` to debug... right? I looked at the Traefik documentation for some insight into this and there is no specific explanation of this. (Maybe worth opening an issue with them to seek clarification on this?)

@kevinjqiu, what I would ask, for right now, is whether you can actually achieve the same result you're looking for using the logLevel setting that this chart already surfaces.

**Comment by kevinjqiu** [comment]
@krancour The `debug` flag and the debug loglevel achieve different things. The `debug` flag adds another endpoint handler `/debug/vars` so we can inspect the internal variables.

See:
- https://github.com/containous/traefik/blob/master/server/web.go#L133-L135
- https://github.com/containous/traefik/blob/master/server/web.go#L321-L333
- https://golang.org/pkg/expvar/

**Comment by krancour** [comment]
@kevinjqiu wow... that is not covered at all in Traefik's own documentation. 😞 

So... I can see the usefulness of this, but would suggest, in light of what you've told me, that the documentation for this chart, at least, be more clear about what "debug mode" entails.

Currently, your description of the option is:

> Whether to enable Traefik's debug logging

Like Traefik's own documentation, that description doesn't tell me that this enables an additional endpoint that lets me peak into Traefik's internals.

If you make that clear and also adjust the minor version number in `chart.yaml`, then this will LGTM.

**Comment by unguiculus** [comment]
This also requires a chart version bump.

**Comment by kevinjqiu** [comment]
@krancour Updated.

Also, this is how a request to `/debug/vars` look like:

```
$ curl traefik.example.com/debug/vars                                                                                           
{                                                   
"Goroutines": 32,                                   
"cmdline": ["/traefik","--configfile=/config/traefik.toml"],                                             
"memstats": {"Alloc":8623600,"TotalAlloc":58323776,"Sys":17643768,"Lookups":399,"Mallocs":591709,"Frees":520055,"HeapAlloc":8623600,"HeapSys":13959168,"HeapIdle":3637248,"HeapInuse":10321920,"HeapReleased":0,"HeapObjects":71654,"StackInuse":720896,"StackSys":720896,"MSpanInuse":158232,"MSpanSys":229376,"MCacheInuse":2400,"MCacheSys":16384,"BuckHashSys":1466335,"GCSys":708608,"OtherSys":543001,"NextGC":10012080,"LastGC":1501866796325487373,"PauseTotalNs":71869757,"PauseNs":[444046,144431,2556801,165237,5236406,126797,72086,4375415,1309325,2241253,125579,1004296,680835,52926100,461150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1501866301728967057,1501866302123354453,1501866302228125836,1501866302422421806,1501866302622594729,1501866302822882855,1501866303048775699,1501866303624018679,1501866304023452800,1501866304225276321,1501866319759793832,1501866440123782649,1501866561021782645,1501866675922666443,1501866796325487373,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":15,"NumForcedGC":0,"GCCPUFraction":0.0008549637749075306,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":4050,"Frees":3722},{"Size":16,"Mallocs":179102,"Frees":156743},{"Size":32,"Mallocs":131958,"Frees":105780},{"Size":48,"Mallocs":39749,"Frees":33162},{"Size":64,"Mallocs":12108,"Frees":10245},{"Size":80,"Mallocs":14478,"Frees":13044},{"Size":96,"Mallocs":22724,"Frees":21358},{"Size":112,"Mallocs":12540,"Frees":11787},{"Size":128,"Mallocs":15385,"Frees":14523},{"Size":144,"Mallocs":14914,"Frees":14066},{"Size":160,"Mallocs":1687,"Frees":1146},{"Size":176,"Mallocs":2960,"Frees":2734},{"Size":192,"Mallocs":10935,"Frees":10691},{"Size":208,"Mallocs":1793,"Frees":1295},{"Size":224,"Mallocs":5599,"Frees":4867},{"Size":240,"Mallocs":6611,"Frees":6605},{"Size":256,"Mallocs":3714,"Frees":3240},{"Size":288,"Mallocs":20897,"Frees":19557},{"Size":320,"Mallocs":436,"Frees":237},{"Size":352,"Mallocs":2573,"Frees":2160},{"Size":384,"Mallocs":105,"Frees":95},{"Size":416,"Mallocs":241,"Frees":120},{"Size":448,"Mallocs":81,"Frees":42},{"Size":480,"Mallocs":93,"Frees":80},{"Size":512,"Mallocs":1126,"Frees":1080},{"Size":576,"Mallocs":4077,"Frees":2961},{"Size":640,"Mallocs":6054,"Frees":5010},{"Size":704,"Mallocs":4792,"Frees":3969},{"Size":768,"Mallocs":1408,"Frees":1191},{"Size":896,"Mallocs":352,"Frees":207},{"Size":1024,"Mallocs":1151,"Frees":1090},{"Size":1152,"Mallocs":981,"Frees":681},{"Size":1280,"Mallocs":150,"Frees":120},{"Size":1408,"Mallocs":90,"Frees":60},{"Size":1536,"Mallocs":68,"Frees":44},{"Size":1792,"Mallocs":89,"Frees":56},{"Size":2048,"Mallocs":808,"Frees":664},{"Size":2304,"Mallocs":106,"Frees":64},{"Size":2688,"Mallocs":97,"Frees":74},{"Size":3072,"Mallocs":7,"Frees":7},{"Size":3200,"Mallocs":16,"Frees":7},{"Size":3456,"Mallocs":28,"Frees":18},{"Size":4096,"Mallocs":138,"Frees":114},{"Size":4864,"Mallocs":36,"Frees":31},{"Size":5376,"Mallocs":70,"Frees":60},{"Size":6144,"Mallocs":17,"Frees":4},{"Size":6528,"Mallocs":6,"Frees":2},{"Size":6784,"Mallocs":42,"Frees":40},{"Size":6912,"Mallocs":0,"Frees":0},{"Size":8192,"Mallocs":31,"Frees":25},{"Size":9472,"Mallocs":47,"Frees":44},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":2,"Frees":2},{"Size":10880,"Mallocs":22,"Frees":17},{"Size":12288,"Mallocs":32,"Frees":2},{"Size":13568,"Mallocs":4,"Frees":3},{"Size":14336,"Mallocs":4,"Frees":3},{"Size":16384,"Mallocs":17,"Frees":15},{"Size":18432,"Mallocs":6,"Frees":3},{"Size":19072,"Mallocs":0,"Frees":0}]}                                                   
}
```

**Comment by krancour** [comment]
This LGTM

cc @prydonius @viglesiasce @lachie83 

Could someone merge, please?

**Pull request merged**
