### PR TITLE
[stable/dashboard] Update to version 2.0.0

### LINKED ISSUE #20803: [stable/kubernetes-dashboard] Chart not yet compatible with version 2.0.x of dashboard
**Describe the bug**

When deploying the `kubernetes-dashboard` to a dedicated namespace, the container does not start and fails with

```
2020/02/17 07:40:15 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:dashboard:dashboard-kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kube-system"
```

**Version of Helm and Kubernetes**:

`helm`: `3.0.1`
`kubernetes`: `1.17.2`

**Which chart**:

`stable/kubernetes-dashboard`

**What happened**:

Container does not start and fails with

```
2020/02/17 07:40:15 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:dashboard:dashboard-kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0003833a0)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00053ae00)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00053ae00)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212
```

**What you expected to happen**:

Pod starts without errors

**How to reproduce it** (as minimally and precisely as possible):

1. Create `values.dashboard.yml`
    ```
    image:
    repository: kubernetesui/dashboard
    tag: v2.0.0-rc5
    pullPolicy: IfNotPresent
    pullSecrets: []

    rbac:
    create: true
    clusterAdminRole: false
    clusterReadOnlyRole: true

    serviceAccount:
    create: true
    name:
    ```
1. Install helm chart

    ```
    helm install dashboard stable/kubernetes-dashboard --namespace dashboard -f values.dashboard.yml
    ```

**Anything else we need to know**:

It seems it does not matter what is the value for `clusterReadOnlyRole` as I tried both `true` and `false`.
Also deploying it into `kube-system` does not help.

May be related to #15118 and #9776

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### What this PR does / why we need it:

Update the chart to be compatible with version v2.0.0 [1] of Kubernetes Dashboard.
This PR is based on funkypenguin chart [2]

[1] https://github.com/kubernetes/dashboard/releases/tag/v2.0.0
[2] https://github.com/funkypenguin/helm-kubernetes-dashboard

#### Which issue this PR fixes
  - fixes #20803 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@funkypenguin thank you!

**Comment by desaintmartin** [comment]
I think we should merge https://github.com/kubernetes/dashboard/pull/4502 ASAP and not update kubernetes-dashboard here...
/hold

**Comment by pierluigilenoci** [comment]
@desaintmartin so please speed up the merge because I need a working chart for v2.0.0 ASAP (like yesterday) and your PR is open since November. I don't care with PR you merge... but merge one, please. 😘

**Comment by funkypenguin** [comment]
@pierluigilenoci this temporary version of https://github.com/kubernetes/dashboard/pull/4502
should work in emergency: https://github.com/funkypenguin/helm-kubernetes-dashboard

**Comment by ReSearchITEng** [comment]
> I think we should merge [kubernetes/dashboard#4502](https://github.com/kubernetes/dashboard/pull/4502) ASAP and not update kubernetes-dashboard here...
> /hold

As the dashboard project does not focus on the helm chart, maybe it would still be better to keep it here.
We can see that there the PR is not accepted since Nov 2019.
I suggest at least for now we do it here (at least till that will be merged).

**Comment by desaintmartin** [comment]
It should be merged soon in kubernetes/dashboard.git, but thanks to the decentralization of charts.git and the hub, anyone is encouraged to fork and push to helm hub.

I'm afraid having a pseudo-official charts.git kubernetes-dashboard 2.0.0 chart AND a kubernetes/dashboard.git 2.0.0 chart that are not the same could be really confusing.

What I can do is: if it is not merged in kubernetes/charts.git within a few days, I'll create a PR with those changes here and get it merged.

**Comment by davidkarlsen** [comment]
@desaintmartin any update here?

**Pull request closed without merging**
