### PR TITLE
[stable/traefik] Update ACME staging CA

### PR DESCRIPTION
**Pull request by dtomcej**
**What this PR does / why we need it**:
This PR updates the ACME staging CA in the chart

**Which issue this PR fixes**
Currently users wanting to use Traefik v1.6 cannot use the older version of the chart and simply updating the image, due to changes in the LE endpoint.

**Special notes for your reviewer**:
This PR does not completely enable all 1.6 features, but will allow the chart to work properly with the Traefik 1.6 release. Further PRs will enable more functionality.

### CODE REVIEW

**Comment by jacobsvante** [comment]
LGTM?

**Comment by ldez** [comment]
> tide Pending — Not mergeable. Should not have needs-ok-to-test label.

**Pull request merged**
