### PR TITLE
[stable/nfs-server-provisioner]: Add nfs-server-provisioner chart

### PR DESCRIPTION
**Pull request by kiall**
Adds a new chart to deploy the kubernetes-incubator nfs-provisioner
using a StatefulSet. Additionally, it requested, will define the
necessary StorageClass resource needed to make use of the provisioner.

See https://github.com/kubernetes-incubator/external-storage/tree/master/nfs

### CODE REVIEW

**Comment by kiall** [comment]
Looks like CI wants a `NOTES.txt` - I'll write one up.

**Comment by unguiculus** [comment]
There's another similar PR: #2559 

Just wanted to let you know. I didn't really compare them. Does it make sense to have both?

**Comment by kiall** [comment]
> There's another similar PR: #2559
> Just wanted to let you know. I didn't really compare them. Does it make sense to have both?

Ah - @unguiculus - I didn't see that one :( There are some differences between the two e.g.:

* This PR uses a `StatefulSet` instead of a `Deployment`. For this particular workload, a `StatefulSet` is technically more correct.
* This PR is based on https://github.com/kubernetes-incubator/external-storage/tree/master/nfs - the kubernetes-incubator project.
* #2559 seems to be based on https://github.com/kingdonb/nfs-data instead

**Comment by kiall** [comment]
Looking at #2559 a little more - it seems the intent is actually quite different. #2559 has this in it's readme:

> If you are used to creating PVCs that automatically generate PVs, note that you
> must create both PV and PVC as the consumer of the NFS PV Provisioner service.

That's different to this service. https://github.com/kubernetes-incubator/external-storage/tree/master/nfs is designed to act as a dynamic volume provisioner, creating NFS volumes automatically based on the requests of a `PVC`.

**Comment by kiall** [comment]
@unguiculus I think this should be OK to review again - see #4142 for some discussion re the differences between the 3x different NFS charts...

**Comment by prydonius** [comment]
This lgtm to me, based on feedback from https://github.com/kubernetes/charts/issues/4142#issuecomment-381931756 I think we can go ahead and merge this!

/lgtm
/hold

**Comment by kiall** [comment]
Thanks @prydonius - are we looking for a second approval before un-holding? :)

**Comment by prydonius** [comment]
@kiall sounds like there was no objection on the other thread so I think we can go ahead and merge this! Thanks for the great work on this!

/hold cancel

**Pull request merged**
