### PR TITLE
[stable/nginx-ingress] Add debug snippet for ingress controller to readme

### PR DESCRIPTION
**Pull request by caulagi**
**What this PR does / why we need it**:

I added a snippet to the README which makes it possible/easier to debug issues with the nginx-ingress setup when installing the chart. IMO, this would be useful for first time users, who have not looked at the `values.yaml` carefully.

### CODE REVIEW

**Comment by caulagi** [comment]
Forgot to mention @jackzampolin, @mgoodness, @chancez

**Comment by jackzampolin** [comment]
I'm 👍 on this change

**Comment by carrodher** [comment]
You should increment chart version (`version`) in `Chart.yaml`

**Comment by caulagi** [comment]
@carrodher fixed!

**Pull request merged**
