### PR TITLE
[stable/dask] Tolerations for worker deployment

### PR DESCRIPTION
**Pull request by consideRatio**
#### Summary
Added tolerations as documented [here](http://kubernetes.dask.org/en/latest/#deployment-details) to the worker nodes for the Helm chart as well.

#### Related:
- https://github.com/dask/dask-kubernetes/pull/110

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by mrocklin** [comment]
Should probably cc @dsludwig or @jacobtomlinson instead

**Comment by mrocklin** [comment]
Both know more than I do

**Comment by jacobtomlinson** [comment]
LGTM

**Comment by consideRatio** [comment]
I updated the chart version again, merge?

**Pull request merged**
