### PR TITLE
[stable/kube-state-metrics] add support for running without cluster-admin privileges

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
Which issue this PR fixes

adds support for running on kubernetes setups (such as openshift) where you only have access to your own namespaces.

Signed-off-by: Klavs Klavsen klavs@EnableIT.dk
Special notes for your reviewer:
Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

    [ x] DCO signed
    [ x] Chart Version bumped
    [x ] Variables are documented in the README.md
    [x ] Title of the PR starts with chart name (e.g. [stable/mychartname])

### CODE REVIEW

**Comment by KlavsKlavsen** [comment]
merged latest updates to chart and resolved conflicts.. Who can review this for merging?

**Comment by KlavsKlavsen** [comment]
My corresponding PR for Prometheus (which uses this chart as a subchart) - has already been merged :)

**Comment by KlavsKlavsen** [comment]
If someone could show me whats failing in CI lint - as I can't view it :(

**Comment by tariq1890** [comment]
@KlavsKlavsen You need to bump the version again `2.8.14`. If you see the diff right now, `Chart.yaml` isn't included

**Comment by KlavsKlavsen** [comment]
Yay.. only in need of approval now ;)

**Comment by KlavsKlavsen** [comment]
I extended chart to also support useExistingRole (which will make it use the given role as ClusterRole name or Role name - depending on useClusterRole is true or false) - which means chart will not generate Role's - just SA and Rolebinding (which is something we also need in our OpenShift setup - it turns out :)

**Comment by KlavsKlavsen** [comment]
I'll fix monday

**Comment by KlavsKlavsen** [comment]
Fantastic - now I only need LGTM labels.. ;)

**Comment by KlavsKlavsen** [comment]
Now I've gotten this support merged in both Prometheus and Grafana
I'd really like to get it in the last chart I use for our Prometheus setup.. ?

**Comment by KlavsKlavsen** [comment]
I've rebased to latest master now.. How do i reopen this issue?

**Pull request closed without merging**
