### PR TITLE
[stable/rocketchat] Upgrade to RocketChat 1.0.3

### PR DESCRIPTION
**Pull request by srueg**
#### What this PR does / why we need it:
Update to new version of RocketChat and enable MongoDB replica set
since it's required for version 1.x.

#### Special notes for your reviewer:
As discussed with @verwilst 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@srueg we were actually working on this.  Trying to find a better path to upgrade.

From what we can tell changing the replicaset to enabled switches from using a deployment to a stateful set.  In doing so.. the persistent volume is actually dropped causing for total data loss.

We were investigating using pre-update hook to potentially mark a deployment resource and keep it from being deleted and then in the post-update migrating the data to the stateful set.

Can you confirm that data is not lost here?  🤞 if so we need to add a very big warning here some how since this has already been merged.

CC @verwilst

**Comment by verwilst** [comment]
Adding a upgrade warning front and center in the README would be a good start i think? I only tested a couple of new installs i'm afraid. :-(

**Comment by srueg** [comment]
You're right, enabling replicaset will drop the PVC :see_no_evil: 
I opened a PR to add a warning to the README: #14068

**Pull request merged**
