### PR TITLE
[stable/prometheus-operator] fix README.md

### PR DESCRIPTION
**Pull request by eduardobaitello**
Fix configuration parameter documentation for controller-manager Exporter
Signed-off-by: Eduardo Baitello <eduardobaitello@gmail.com>

### CODE REVIEW

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by vsliouniaev** [comment]
@eduardobaitello Sorry, but this needs another version bump - such is life in helm

**Comment by eduardobaitello** [comment]
@vsliouniaev @gianrubio The chart version was bumped

**Pull request merged**
