### PR TITLE
[stable/concourse] Moves prometheus annotation to deployment

### PR DESCRIPTION
**Pull request by cirocosta**
#### What this PR does / why we need it:

Previously, Prometheus annotations were added to the web service,
which is meant to represent the whole replica set of pods, leaving
no pod-specific labels to the metrics gathered, defeating the
purpose of some of them (that are meant to be container-specific).

By moving them to `deployment`, we're able to collect them per-pod,
instead of per-service.

#### Special notes for your reviewer:

Although it was possible to still have the effects of this change working without making the annotation per-deployment (by not setting the `concourse.web.prometheus.enabled` flag and manually including the annotations + env variables), I'm confident that going this route makes more sense. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

cc @frodenas / @william-tran

### CODE REVIEW

**Comment by william-tran** [comment]
From https://groups.google.com/forum/#!topic/prometheus-users/jDEzVHUUFzw it looks like prometheus scrapes each pod behind the service, and from #6338 and #6442 it looks like it is desirable to have it on the service to support prometheus-operator. Not having used that myself, can you add anything to that @2color @richardalberto?

**Comment by william-tran** [comment]
But, @cirocosta if you've observed differences in pod scraping vs service scraping that obfuscate some metrics, please add that to the discussion

**Comment by william-tran** [comment]
@paulczar I do not appreciate you lgtm-ing while this PR is being discussed. Why did you do that?

**Comment by paulczar** [comment]
sorry about that, as you know there was a backlog of PRs for the concourse chart, I was trying to clear through a bunch that were approved but had version conflicts as i could fix the conflicts through the web ui.  Clearly I either missed the ongoing discussion here,  Will figure out on slack with you if we want to revert or leave as is.

**Pull request merged**
