### PR TITLE
[stable/schema-registry-ui] Added support for the proxy switch.

### PR DESCRIPTION
**Pull request by Jack12816**
#### What this PR does / why we need it:

This PR updates the Schema Registry UI image version to the lastest 0.9.5 and adds support for the `PROXY` environment variable on the pod. This allows users to proxy Schema Registry API requests through the UI. Thats on the other hand really helpful when ingress is enabled and the Schema Registry API is not public available.

See: https://github.com/Landoop/schema-registry-ui/tree/v.0.9.5/docker#docker-options

#### Special notes for your reviewer:

A picture of a cute animal (not mandatory but encouraged).
Download

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Jack12816** [comment]
@cristian04 Hey, what's next with this PR? :)

**Comment by cristian04** [comment]
@sameersbn could you please assign this to me?

**Comment by cristian04** [comment]
Hi @Jack12816, I've just asked for approval on Slack as I dont have permissions to do it.

**Pull request merged**
