### PR TITLE
[stable/traefik] dashboard serviceType

### LINKED ISSUE #7912: [stable/traefik] dashboard does not run on gke
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.10
Kubernetes Server: v1.10.6-gke.2
Kubernetes Client: v1.11.2

**Which chart**:
stable/traefik

**What happened**:
Dashboard cannot run on GKE: `Error during sync: error while evaluating the ingress spec: service "example-ingress/traefik-controller-dashboard" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

**What you expected to happen**:
Dashboard to be deployed without issues

**How to reproduce it** (as minimally and precisely as possible):
Run on GKE
Use option: `dashboard.enabled: true`

**Anything else we need to know**:
Found on clean GKE cluster, where traefik is the only cluster controller installed

Manual intervention that provided results
- Updated the dashboard service to be of `kind: NodePort`
- Remove the dashboard ingress
- Redeployed using helm

### PR DESCRIPTION
**Pull request by smatyas**
#### What this PR does / why we need it:
This PR adds the ability to set the serviceType of the dashboard service. This is useful for when deploying to a managed k8s environment, e.g GKE.

#### Which issue this PR fixes
* fixes #7912, fixes #9291

#### Special notes for your reviewer:
This is the continuation of #9291 

Although I'm not entirely sure this is the right solution for the original problem. 
I'd rather say, one should just annontate the dashboard ingress something like here, then it will be accessible:

```
kubernetes:
  ingressClass: traefik
dashboard:
  enabled: true
  domain: traefik-dashboard.example.com
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
```

And another thing for future consideration: I believe that *enabling* and *exposing* the dashboard should be two different things driven by two separate parameters.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by dtomcej** [comment]
@smatyas Thank you for picking up this one! Also thank you for keeping the commits from @Basster. I was afraid you were not going to.

All good for me!

**Comment by Basster** [comment]
@smatyas thank you for taking over! :+1: Really appreciating.

**Pull request merged**
