### PR TITLE
[helm/charts] Add forecastle

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
- [Forecastle](https://github.com/stakater/forecastle) an opensource tool maintained by [Stakater](https://github.com/stakater)
- Forecastle is a control panel which dynamically discovers and provides a launchpad to access applications deployed on Kubernetes

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @scottrigby and @foxish 
Ping

**Comment by faizanahmad055** [comment]
Hi @scottrigby and @foxish
Ping

**Comment by faizanahmad055** [comment]
Hi @scottrigby and @foxish
Can you guys take a look please

**Comment by faizanahmad055** [comment]
Hi @scottrigby and @foxish
Can you guys take a look please

**Comment by faizanahmad055** [comment]
Hello @scottrigby and @foxish
Any update on this, please?

**Comment by scottrigby** [comment]
Hi @faizanahmad055 I wish I were able to respond to all GitHub notifications quicker than this. However, not only are we already as a volunteer group a bit behind on PRs, there was also post-KubeCon, holidays, and for my part starting a new job. In any case, thanks for reaching out on Slack, that does help a bit.

That said, I can't fully review this right now but it's in my queue. I can at least mark OK to test until then. Thanks, this looks interesting!

**Comment by scottrigby** [comment]
@faizanahmad055 as we're transitioning from this monolith charts repo to the new [hub.helm.sh](https://hub.helm.sh/), would you be interested in adding this Helm chart directly there? We are still completing documentation and tooling to help people host their own Helm charts repo, but if you're interested in getting there sooner than later, I'd be happy to help before that other work is complete. LMK what you think 😄

**Comment by faizanahmad055** [comment]
Hi @scottrigby,
I think the new approach is good. We are preparing our public repository so it can be searchable at [hub.helm.sh](https://hub.helm.sh/).

**Pull request closed without merging**
