### PR TITLE
[stable/dex] ADD annotations to grpc and web pods FIX #15451

### LINKED ISSUE #15451: [stable/dex] Missing: custom annotations on job-grpc-certs PodTemplateSpec
In the Job `..-grpc-certs` `templates/job-grpc-certs.yaml` the `spec.template.metadata.annotations` haven't been templated, so it's not possible to add custom annotations to the pod created by the Job.

We're using Istio, with automatic sidecar injection in all namespaces. Referring to: https://github.com/istio/istio/issues/11045 we're not able to add the `sidecar.istio.io/inject: "false"` to the Pod created by the Job, thus it never completes, and the status of the Helm install becomes Failed, because the job times out.

We were able to install the chart successfully with `--set certs.grpc.create=false` but was (of course..) missing certificates, so Dex wasn't starting.

The certificate-secrets were created by generating the templates with `helm install .. --set certs.grpc.create=true --debug --dry-run`, and manually installing the "openssl" ConfigMap, the Role and RoleBinding allowing for secret/configmap delete/create in the namespace, and the Job with the annotation added to the PodTemplateSpec.

### PR DESCRIPTION
**Pull request by figaw**
Signed-off-by: Nicolaj Græsholt <figaw@hotmail.com>

#### What this PR does / why we need it:

Adds custom annotations to the pods created by the grpc- or web-jobs. See #15451.

#### Which issue this PR fixes

  - fixes #15451

#### Special notes for your reviewer:

#15451 is about the grpc-job. I added custom annotations to the web-job as well for consistency.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks!
Could you rebase? A lot have changed (hopefully in the right direction) since you created the PR.
/ok-to-test

**Comment by figaw** [comment]
Rebased on master in beb5f5372 @desaintmartin 

I'd like to document the `certs.[grpc/web].pod.annotations` in the `README.md` but I don't want to confuse it with the current **Configuration** list, that specifically lists "values introduced in `2.0.0`".

- The current **Configuration** should probably be **Values introduced in 2.0.0**, and there should be a **Configuration** header listing all of the parameters in the values file.. but I didn't want to bloat this PR with unrelated changes.

**Comment by vi7** [comment]
> Rebased on master in [beb5f53](https://github.com/helm/charts/commit/beb5f5372a44d2fcbae63100341a7eb77c14e17a) @desaintmartin
> 
> I'd like to document the `certs.[grpc/web].pod.annotations` in the `README.md` but I don't want to confuse it with the current **Configuration** list, that specifically lists "values introduced in `2.0.0`".
> 
> * The current **Configuration** should probably be **Values introduced in 2.0.0**, and there should be a **Configuration** header listing all of the parameters in the values file.. but I didn't want to bloat this PR with unrelated changes.

Hi @figaw . Could you please change values table header from that:
```
The following table lists parameters introduced in v2.0.0
```

to that one:
```
Parameters introduced starting from v2
```

and add the values introduced in your PR to the same table?

It doesn't make much sense to have a different Configuration section in the readme. The table header mentioned above will be simply removed If somebody will be so kind to document **all** the chart values somewhere in future.

**Comment by figaw** [comment]
@vi7 of course! ... 
- I rebased again onto the master of helm/charts,
- added descriptions of the values to the readme and bumped minor,
- sorted the parameters in the list alphabetically. 

Back to you!

**Comment by vi7** [comment]
@figaw thank you! I'm not sure I have proper permissions for this PR so.

/approve

**Comment by vi7** [comment]
Hi @desaintmartin ! Are you ok with the changes?

**Comment by desaintmartin** [comment]
You have permissions. ;)
/lgtm
Thanks!

**Pull request merged**
