### PR TITLE
add MARIADB_ROOT_USER to wordpress chart

### PR DESCRIPTION
**Pull request by gauravarora**
added MARIADB_ROOT_USER to config as external db providers may not always name their user `root` (eg. AWS RDS)

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
LGTM!

cc/ @tompizmor @sameersbn

**Review by juan131 — CHANGES_REQUESTED** [review]
I just noticed you did not bumped the version of the chart:

https://github.com/kubernetes/charts/blob/master/stable/wordpress/Chart.yaml

**Comment by sameersbn** [comment]
@gauravarora I've bumped the chart version. Please do remember to bump the chart version for future contributions. Thanks!

**Review by sameersbn — APPROVED** [review]

**Comment by sameersbn** [comment]
@gauravarora after an internal review we realized that the `MARIADB_ROOT_USER` and `MARIADB_ROOT_PASSWORD` env variables will not have any effect on the container instance. As such the `externalDatabase.rootUser` and `externalDatabase.rootPassword` chart params bear no significance on the chart in the current state. 

If you take a look at https://github.com/bitnami/bitnami-docker-wordpress#create-a-database-for-wordpress-using-mysql-client we need to add support for additional environment variables for these params to have any effect on the container execution.

**Comment by sameersbn** [comment]
not applicable.. closing

**Pull request closed without merging**
