### PR TITLE
[stable/spinnaker] specify which namespaces to omit

### PR DESCRIPTION
**Pull request by dodizzle**
Signed-off-by: David O'Dell <dave@helix.re>

#### What this PR does / why we need it:
Currently the list of kubernetes namespaces to omit is hardcoded to kube-system and kube-public.
This change omits those by default but also allows omitting other namespaces.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ X] Variables are documented in the README.md

### CODE REVIEW

**Comment by viglesiasce** [comment]
Thanks for the PR! You'll need to bump the chart version.

**Comment by dodizzle** [comment]
Chart version bumped.

**Comment by dodizzle** [comment]
So this is my first PR and it took about 1 hour to create the fix but that was more than one week ago.
Am I missing a step?

**Comment by dodizzle** [comment]
@viglesiasce What is this PR missing that it is not merged yet?
This is my first time so if I'm missing some step please let me know.

**Pull request merged**
