### PR TITLE
Updating image of prometheus-redis-exporter to latest version

### PR DESCRIPTION
**Pull request by naseemkullah**
Please see https://github.com/oliver006/redis_exporter/releases/tag/v0.21.2 for more details

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
/lgtm cancel
@naseemkullah can you bump the chart version please? TIA

**Comment by naseemkullah** [comment]
@davidkarlsen Oops thanks! Chart bumped!

**Pull request merged**
