### PR TITLE
[stable/prometheus-cloudwatch-exporter] Add myself to owners/maintainers.

### PR DESCRIPTION
**Pull request by asherf**
https://github.com/helm/charts/pull/18003#issuecomment-543383721

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by zanhsieh** [comment]
@maorfr 
Would you mind to grant him as extra owner of this chart please?

**Comment by maorfr** [comment]
can we get lgtm from @torstenwalter ?

**Comment by maorfr** [comment]
@asherf  gotta make everything green.

**Comment by asherf** [comment]
@maorfr  sorry my bad... somehow forgot to sign the commit. fixed now.
I still think I need an invite to the github org.

**Comment by asherf** [comment]
errors seems to be timeouts.
Screenshot 2019-10-21 09 47 17

**Comment by asherf** [comment]
looks like there are a lot of failures for multiple PRs, due to timeouts.
will try to run tests again later.

**Comment by asherf** [comment]
@maorfr I need an invite to the helm org so this can be merged. thanks!

**Comment by asherf** [comment]
> @maorfr I need an invite to the helm org so this can be merged. thanks!

@maorfr friendly ping... can I get an invite? thanks!

**Comment by maorfr** [comment]
@asherf invitation sent.
once you accept, comment `/verify-owners` and this should be good to go.
welcome aboard!

**Pull request merged**
