### PR TITLE
[stable/postgresql] Merge metrics into master statefulset as sidecar.

### PR DESCRIPTION
**Pull request by desaintmartin**
#### What this PR does / why we need it:

While working with postgresql role privileges, I realized that the defined postgresql user has to have access from the metrics pod to the postgresql pod with potentially more permissions than it should have. Using it from localhost allows to potentially solve this (in a future PR?).

Moreover, having metrics as a sidecar reduces complexity as they now have the same lifecycle.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @prydonius @tompizmor @sameersbn @carrodher @juan131 for review

**Comment by carrodher** [comment]
Thanks, @desaintmartin. Changes LGTM, if nobody has any other concerns, in my opinion, we can merge it

**Pull request merged**
