### PR TITLE
[stable/sonatype-nexus] Update image to 3.12.1

### PR DESCRIPTION
**Pull request by bbriggs**
**What this PR does / why we need it**: Updates to latest Sonatype Nexus version, which is an urgent patch release according to release notes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bbriggs** [comment]
Pleasure doing business with you :) Do you I should probably apply for membership at this point to speed this up, @rjkernick?

**Comment by rjkernick** [comment]
It would definitely speed it up as it will run the tests automatically. Just have to find a couple sponsors and follow the directions here: https://github.com/kubernetes/community/blob/master/community-membership.md

**Pull request merged**
