### PR TITLE
raised elk stack to same version 6.2.4

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: Raises ELK Stack (Elasticsearch, Logstash & Kibana) to the same Docker image version 6.2.4, so the can be deployed together easily.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@monotek Maybe this should be 6.3.0 instead?

**Comment by monotek** [comment]
I'd like to do this as a next step.
I also thinking about to align chart versions. But would be hard to keep up with fixes to single charts.

**Comment by rendhalver** [comment]
Sounds good to me.

**Comment by rendhalver** [comment]
Looks like the versions were out of wack so aligning them sounds like a good plan.

**Comment by monotek** [comment]
So lets merge this on first. After this i'll add a new one for 6.3.0.

**Comment by monotek** [comment]
Fixed merge conflicts...

**Comment by unguiculus** [comment]
Please create separate PRs per chart and don't forget to update the readme files as well. Thanks.

**Comment by monotek** [comment]
created 3 new pull requests:

elasticsearch: https://github.com/kubernetes/charts/pull/6425
logstash: https://github.com/kubernetes/charts/pull/6423
kibana: https://github.com/kubernetes/charts/pull/6424

**Pull request closed without merging**
