### PR TITLE
[stable/nginx-ingress] No empty string clusterip

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseemkullah@gmail.com>

#### What this PR does / why we need it:
Please see #19041 and https://github.com/helm/helm/issues/6378#issuecomment-557746499
helm3 introduces 3 way merge, i am stuck with a release where omitClusterIP was not set and is now managed by helm3. This would probably help

#### Special notes for your reviewer:
We may be able to remove the omitclusterIP workaround if we wish, provided nobody has hardcoded `clusterIP: ""` in their values files

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @taharah @ChiefAlexander

**Review by asyncmind0 — APPROVED** [review]

**Pull request merged**
