### PR TITLE
[stable/kube-lego] kube-lego is in maintenance mode, in favor of cert-manager

### PR DESCRIPTION
**Pull request by jeff-knurek**
[adding note to documentation to reflect note in parent repo: https://github.com/jetstack/kube-lego]

### CODE REVIEW

**Comment by munnerz** [comment]
I've opened #3416 that adds the chart for cert-manager to this repo. Perhaps we can update this PR to include a link to the chart once it has merged?

**Comment by jeff-knurek** [comment]
I saw that in the slack channel, thanks for creating #3416

I expect your PR will get more attention and probably merge sooner, but I'll wait till then, and that way it's easier to just add a direct link to the preferred cert-manager chart

**Review by mattfarina — CHANGES_REQUESTED** [review]
There are a few changes I'd like to ask...

1. We're in the process of adding documentation on how to deprecate a chart. Can you do that here, in addition to the warning. Details are on https://github.com/kubernetes/charts/pull/3420
1. While I realize the lint issues are not the result of this PR can you please fix them. We want to leave the chart in a working state without issue.

**Comment by mattfarina** [comment]
/hold

I would like to hold in merging the deprecation of this chart until #3416 is merged.

**Comment by jeff-knurek** [comment]
@mattfarina regarding:
> While I realize the lint issues are not the result of this PR can you please fix them. We want to leave the chart in a working state without issue.

Should I just remove the `{{ required "config.LEGO_EMAIL ...` option, as this project is deprecated and it won't be so important to inform the user? 
But, I think this is a bug in the linter. How can you leave an empty value in a required field??

**Comment by jeff-knurek** [comment]
@mattfarina there's still a hold on this, but it's not clear why

**Comment by mattfarina** [comment]
/ok-to-test
/hold cancel

@jeff-knurek It's on hold because I'd not gotten back around to this after cert manager was merged.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
