### PR TITLE
[stable/jenkins] Fix backups when deployment has custom name

### PR DESCRIPTION
**Pull request by mogaal**
#### What this PR does / why we need it:

This PR fixes backups when Chart name is different than "jenkins" (default one).

By default, when you deploy stable/jenkins it gets _jenkins_ as a name. Backup runs fantastic for this setting (default one) because deployment name match Jenkins container name: https://github.com/helm/charts/blob/d228efa280d91c930578bb91eb704abf2cef51ef/stable/jenkins/templates/jenkins-master-deployment.yaml#L152-L153 (Container is always called Jenkins and it matches with the deployment name for the default settings)

If we assign a custom name for the chart (for this example `jenkins-inf`) we find the following issue:

```
$ kubectl create job --from=cronjob/jenkins-inf-backup alejandro-test
job.batch/alejandro-test created
$
$ kubectl logs -f alejandro-test-22bq5
2019/08/13 13:21:03 Backup started!
2019/08/13 13:21:03 Getting clients
2019/08/13 13:21:03 Getting pods
2019/08/13 13:21:03 Calculating paths. This may take a while...
2019/08/13 13:21:06 error in Stream: container jenkins-inf is not valid for pod jenkins-inf-7c5d7f4df7-l2jtl
```

As you see in the last line it's trying to look for a container `jenkins-inf` which doesn't exist. Remember from above container is always called `jenkins` it doesn't your release name. To match the right pod the cronjob already use labels ( https://github.com/helm/charts/blob/d228efa280d91c930578bb91eb704abf2cef51ef/stable/jenkins/templates/jenkins-backup-cronjob.yaml#L34-L35 ) but it is assuming the container name change and it is wrong.

#### Special notes for your reviewer:

Support yourself for the checking creating a job from a cronjob using the command: `kubectl create job --from=cronjob/jenkins-inf-backup alejandro-test`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
/ok-to-test
/approve

this looks good to me. are you also looking to be added as a maintainer to this chart? since you have added yourself to the OWNERS file...

**Comment by mogaal** [comment]
@maorfr yes, it's my second contribution and I am heavily using this chart at my work. Hopefully, future improvements are coming :-)

**Comment by maorfr** [comment]
@torstenwalter waiting for your lgtm :)

**Comment by torstenwalter** [comment]
@mogaal Thank you for fixing this. Good to have an additional maintainer on board.

**Comment by mogaal** [comment]
@torstenwalter no worries, happy to help out. 

Any idea how to remove the "do-not-merge/invalid-owners-file" tag? I guess is not gonna be merged until it disappears? 

Have a nice day

**Comment by torstenwalter** [comment]
I think this is the problem:

>The following users are mentioned in OWNERS file(s) but are not members of the helm org.
>
> Once all users have been added as members of the org, you can trigger verification by writing /verify-owners in a comment.

I don't have permissions to add you to the repo. @maorfr will do it.

I noticed that you haven't added yourself to the maintainers in Chart.yaml. That's worth one more commit ;-)

**Comment by mogaal** [comment]
Thanks @maorfr

**Pull request merged**
