### PR TITLE
[stable/influxdb] Use include function instead of template.

### PR DESCRIPTION
**Pull request by naseemkullah**
As `include` is preferred.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by Aisuko — APPROVED** [review]
/LGTM

**Comment by Aisuko** [comment]
@naseemkullah Thank you very much.👍

**Comment by naseemkullah** [comment]
My pleasure @Aisuko.

**Pull request merged**
