### PR TITLE
Do not create a serviceaccount for prometheus-operator if configured

### PR DESCRIPTION
**Pull request by ts4z**
#### What this PR does / why we need it:

Do not create a serviceaccount for prometheus-operator if configured.

This makes the prometheus-operator/serviceaccount.yaml file consistent with other local serviceaccount.yaml files, and allows us to use the default service account. (Without this change, we proceed to try to create the "default" service account.)

Signed-off-by: Tim Showalter <tjs@psaux.com>

#### Special notes for your reviewer:

@gianrubio 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
👍

**Comment by paskal** [comment]
You need to bump chart version to get merged.

**Comment by paskal** [comment]
Wrong case Lgtm, didn't work.

**Comment by ts4z** [comment]
@gianrubio Could you give me a /lgtm on this? Apparently a /Lgtm doesn't work

**Comment by vsliouniaev** [comment]
The race condition here is getting pretty crazy

**Comment by paskal** [comment]
@ts4z, Please merge and bump version once more.

**Pull request merged**
