### PR TITLE
[stable/jenkins] Add deploymentStrategy

### PR DESCRIPTION
**Pull request by kimxogus**
#### Is this a new chart
No

#### What this PR does / why we need it:
- When nfs like aws efs is used for pv, You don't have to set deployment's `.spec.strategy` to `Recreate`. This pr makes you can explicitly set `master.deploymentStrategy` to set it.
- Fix typo `master.priorityClass` to `master.priorityClassName` in values.yaml

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@kimxogus Jenkins does not support that you have two instances accessing the same disk. That's why it's not possible to have replicas > 1. 
That's also the reason why DeploymentStrategy is set to `Recreate` to avoid the same scenario during updates.

**Comment by kimxogus** [comment]
@torstenwalter I didn't know that, Thank you for the info. I closed this

**Pull request closed without merging**
