### PR TITLE
[prometheus-operator] Fixing scope issue (#23014)

### LINKED ISSUE #23014: [prometheus-operator] grafana configmap for dashboards needs global scope in range function
**Describe the bug**
Within the template grafana/configmap-dashboards.yaml there is a range function.  The call to the template function 

> namespace: {{ template "prometheus-operator.namespace" . }}

needs to be passed the global scope like this:

> namespace: {{ template "prometheus-operator.namespace" $ }}

Otherwise, helm cannot evaluate the scope and will not be able to render the chart.

**Version of Helm and Kubernetes**:
 helm 2.16.8
kubernetes 1.18.4

**Which chart**:
prometheus-operator

**What happened**:
Scope does not have the namespaceOverride value, so an error is thrown:

Error: UPGRADE FAILED: render error in "prometheus-operator/templates/grafana/configmap-dashboards.yaml": template: prometheus-operator/templates/_helpers.tpl:88:16: executing "prometheus-operator.namespace" at <.Values.namespaceOverride>: can't evaluate field Values in type []uint8

**What you expected to happen**:

No errors

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by mmerrill3**
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>

#### What this PR does / why we need it:
This fixes the scope issue with #23014 
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #23014 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mmerrill3** [comment]
@vsliouniaev had to rebase due to Chart.yaml conflict.

**Comment by bismarck** [comment]
@mmerrill3 Going to have to rebase one more time.

**Comment by mmerrill3** [comment]
@bismarck rebased.

**Pull request merged**
