### PR TITLE
[stable/fluent-bit] Upgrade to 1.2.1

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What this PR does / why we need it:
Upgrade to 1.2.1.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by edsiper** [comment]
@ialidzhikov imagepullpolicy must not be changed

**Review by edsiper — CHANGES_REQUESTED** [review]
imagepullpolicy is always

**Comment by ialidzhikov** [comment]
> imagepullpolicy is always

Done.

**Pull request merged**
