### PR TITLE
[stable/prometheus-operator] allow logLevel config for operator

### PR DESCRIPTION
**Pull request by estahn**
#### What this PR does / why we need it:

The operator of prometheus-operator is very noisy with its default
logLevel. This allows to configure the logLevel but keeps the default of
"info".

#### Which issue this PR fixes

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by estahn** [comment]
@gianrubio Is there anything else you need to review this? Would be good to lower these log messages.

**Comment by estahn** [comment]
@gianrubio ping

**Comment by paskal** [comment]
@estahn, could you please rebase this one once more?
@vsliouniaev, could please review it then?

**Comment by estahn** [comment]
@vsliouniaev @paskal done

**Comment by paskal** [comment]
@estahn sadly it seems you lost your changes now, only change currently is version bump.

**Comment by paskal** [comment]
It's no good now, wait for author for re-introduce changes please.

**Comment by estahn** [comment]
#11326 seems to be a duplicate of mine but was already merged 🤦‍♂️

**Pull request closed without merging**
