### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by Eslamanwar**
Typo in the default password postgresql
should be existingSecretKey: postgres-password
it makes the chart to fail when deploying with the default values.yaml

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by gsemet — CHANGES_REQUESTED** [review]
Ok for me, you just need to update the version

**Comment by rcjsuen** [comment]
@gsemet It seems to me that the problem stems from the [`README.md`](https://github.com/helm/charts/blob/19dbe963b152f7d0d60b7ad9e2f16dd22a0bc074/stable/airflow/README.md) file.

> ```
> kubectl create secret generic airflow-postgres --from-literal=postgres-password=$(openssl rand -base64 13)
> kubectl create secret generic airflow-redis --from-literal=redis-password=$(openssl rand -base64 13)
> ```

Should the `README.md` file be updated instead to say `--from-literal=postgresql-password`?

**Comment by gsemet** [comment]
Yes sure can you do it ?

**Comment by rcjsuen** [comment]
> Yes sure can you do it ?

@gsemet I have created #21886.

**Pull request closed without merging**
