### PR TITLE
[stable/mongodb] adding Release name as selector

### PR DESCRIPTION
**Pull request by jainishshah17**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jainishshah17** [comment]
https://github.com/kubernetes/charts/issues/5507

**Comment by jainishshah17** [comment]
@caarlos0 Can you take a look. Its minor and very useful change.

**Comment by unguiculus** [comment]
Thanks. Could you also fix this in the deployment?

**Pull request merged**
