### PR TITLE
[stable/prometheus-pushgateway] Fix podDisruptionBudget template

### LINKED ISSUE #15366: [stable/prometheus-pushgateway] pdb labels broken
https://github.com/helm/charts/blob/2f0cfa3bc222651811955cbc9f43d0fd4d130038/stable/prometheus-pushgateway/templates/pdb.yaml#L6 should be:
```
  labels:
{{ template "prometheus-pushgateway.defaultLabels" merge (dict "extraLabels" .Values.podLabels) .  }}
```

### PR DESCRIPTION
**Pull request by cstaud**
#### What this PR does / why we need it:
Hi @gianrubio, this PR contains a fix for the pdb.yaml template, which produces rendering errors when `prometheus-pushgateway.defaultLabels` is awailable.

#### Which issue this PR fixes
  - fixes #15366

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by cstaud** [comment]
@zanhsieh @gianrubio can you give me advice how i could speed up the delivery of this bugfix? we need this asap.

**Comment by zanhsieh** [comment]
@cstaud 
So this chart passed. Would you volunteer to be one of this chart owner? If so, please let me know which PR for owner file change. Thank you.

**Comment by cstaud** [comment]
@zanhsieh thx for the approval! At this point in time the future use of the prometheus-pushgateway at my team is unclear. When there is a reliable decision and I got the admission to maintain this during my work hours, I would like to take maintainer ship for this chart. Until then, thanks in advance, and have a nice weekend.

**Pull request merged**
