### PR TITLE
[stable/verdaccio] Fix deployment

### PR DESCRIPTION
**Pull request by manhluong**
#### Is this a new chart
No.

#### What this PR does / why we need it:
It fixes two problem installing the stable chart of Verdaccio.

With k8 stable, version 1.16, I have these 2 errors:

```
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"
```

and

```
Error: release snug-hound failed: Deployment.apps "snug-hound-verdaccio" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"verdaccio", "release":"snug-hound"}: `selector` does not match template `labels`]
```

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by manhluong** [comment]
@zanhsieh @mattfarina @scottrigby @sameersbn can I have some review please? :)

**Comment by zanhsieh** [comment]
@manhluong 
Sorry. Even I review this chart, I don't have permission to LGTM this chart. I am not a helm member. Others might have it.

**Comment by manhluong** [comment]
@zanhsieh yep no worries!

I was just wondering if I have to do something else to move forward the PR process or I have just have to wait. :)

Thanks for replying anyway!

**Comment by damlys** [comment]
Btw. it looks like I duplicated this PR :man_shrugging: https://github.com/helm/charts/pull/19003

**Review by mavimo — APPROVED** [review]

**Comment by manhluong** [comment]
Thanks @mavimo! But it seems that I also need a `lgtm` label? :thinking:

**Pull request merged**
