### PR TITLE
[stable/datadog] Bump KSM dependency

### LINKED ISSUE #15679: [stable/datadog]  kube-state-metrics generates RBAC errors due to old Chart dependency
The dependency chart for kube-state-metrics is ~0.16.0 whereas the latest version of the chart is 2.0.0

If we want to use the latest version of kube-state-metrics v1.6.0, we have a lot of errors due to RBAC such as:

E0718 10:02:29.504756       1 reflector.go:126] k8s.io/kube-state-metrics/internal/collector/builder.go:482: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:kube-system:datadog-agent-kube-state-metrics" cannot list resource "deployments" in API group "apps" at the cluster scope

Can you please update the requirements.txt to have ~2.0.0 ?

### PR DESCRIPTION
**Pull request by coreypobrien**
#### What this PR does / why we need it:
Updates to latest KSM chart to include new features from that chart like affinity, latest api groups and labelling practices, etc.

#### Which issue this PR fixes
- fixes #15679 

#### Special notes for your reviewer:
Used new major version since this will break anyone specifying KSM values that have been renamed.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by coreypobrien** [comment]
Realized the `serviceAccount.name` stuff in the values.yaml was indented incorrectly, but that didn't matter because we don't actually need to set that anyway so it was working as it was.

**Comment by coreypobrien** [comment]
Bumped to 2.2.1 since that was just released and picks up support for service annotations we need for https://github.com/DataDog/datadog-agent/issues/3923

**Comment by coreypobrien** [comment]
/retest
Weird caching issue? Couldn't find the new release of KSM.

**Comment by clamoriniere** [comment]
Hi @coreypobrien, 
Thank you for opening this pull-request. 
Before merging your PR, we are currently validating KSM 1.7.1 (that is corresponding to the version imbedded in `stable/kube-state-metrics` `2.2.1`) with our KSM integration in `datadog-agent`.

We also opened a PR (#15908) to:
- use the last KSM chart version that we validated 
- fix `/stable/kube-state-metrics/values.yaml` integration in our /stable/datadog/values.yaml.

**Comment by coreypobrien** [comment]
@clamoriniere How is the validation going?

**Comment by clamoriniere** [comment]
Hi @coreypobrien,
For the moment we didn't see any regression with KSM 1.7.1, so we can consider bumping the version next week.

For the futur release, we plan to synchronize the Ksm version update with that of Datadog-Agent.

**Comment by kcmartin** [comment]
I noticed a security issue was announced for `kube-state-metrics` versions 1.7.0 and 1.7.1:

https://github.com/kubernetes/kube-state-metrics/releases

`kube-state-metrics` 1.7.2 addresses it, and both ksm and the stable Helm chart are updated to 1.7.2.

Will this delay the PR? @clamoriniere

**Comment by coreypobrien** [comment]
@kcmartin Good call 👍 Bumped the chart again to pick up that security fix too.

**Comment by coreypobrien** [comment]
@clamoriniere How are we doing here? Any other blockers to merging this?

**Comment by clamoriniere** [comment]
Hi @coreypobrien 
I'm working on it with this PR #16267 that fix other issues

I'm deeply sorry for the delay...

**Comment by coreypobrien** [comment]
Is there a problem with merging this here and then bumping the version of datadog later?

**Pull request closed without merging**
