### PR TITLE
Upgrade Traefik to v1.1.0

### PR DESCRIPTION
**Pull request by krancour**
This upgrades the Traefik chart from v1.1.0-rc3 to the stable v1.1.0 that was released a few days ago.

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
@krancour can you bump the chart version in Chart.yaml?

**Comment by krancour** [comment]
@prydonius, I did, actually.

**Comment by lachie83** [comment]
Confirmed. Sorry about that @krancour

**Comment by prydonius** [comment]
woops, sorry @krancour, missed that!

**Comment by krancour** [comment]
np, gents.

**Comment by lachie83** [comment]
LGTM

**Pull request merged**
