### PR TITLE
[stable/prometheus-snmp-exporter] add namespace metadata

### PR DESCRIPTION
**Pull request by lwolf**
#### What this PR does / why we need it:

this is needed for when helm is used purely as a templating tool,
since helm template does not add the namespace
helm/helm#3553

Signed-off-by: Sergey Nuzhdin <ipaq.lw@gmail.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Miouge1** [comment]
I don't see this in any of the other Prometheus charts I have looked ([blackbox](https://github.com/helm/charts/blob/master/stable/prometheus-blackbox-exporter/templates/deployment.yaml) example). 

Is this a common pattern?

**Comment by lwolf** [comment]
I created PRs to add it to [prometheus](https://github.com/helm/charts/pull/14327) and [snmp exporter](https://github.com/helm/charts/pull/14328)
I answered similar question here - https://github.com/helm/charts/pull/14325#issuecomment-497647377

but tbh feel free to close it if you think it's not relevant.

**Comment by Miouge1** [comment]
@lwolf OK thanks for the info. This could be good to add to the default chart created by `helm create` (if not already).

/lgtm

**Pull request merged**
