### PR TITLE
[incubator/kube-downscaler] - Fix deployment

### PR DESCRIPTION
**Pull request by Lord-Y**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fix deployment
  - fix discover of resources
  - Add extraArgs

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Lord-Y 
Would you mind to sign DCO please? Thank you.

**Comment by Lord-Y** [comment]
@zanhsieh I did the sign off which change the commit id after force push. All my commits are now signed but Github is still complaining. Don't know what to do ... Any help?

**Pull request closed without merging**
