### PR TITLE
[incubator/kafka] Allows override for KAFKA_ADVERTISED_LISTENERS

### PR DESCRIPTION
**Pull request by fedenusy**
Useful when port forwarding from outside the cluster.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @benjigoldberg @faraazkhan @h0tbird

**Comment by benjigoldberg** [comment]
LGTM - should the patch version be 11 not 12 though?

**Comment by unguiculus** [comment]
@benjigoldberg 12 would be the next increment.

**Pull request merged**
