### PR TITLE
[stable/prometheus] update prometheus to 2.20.1 and cm reloader to 0.4.0

### PR DESCRIPTION
**Pull request by monotek**
#### What this PR does / why we need it:
* update prometheus to 2.20.1 and cm reloader to 0.4.0

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by monotek** [comment]
@Xtigyro

Thanks :)
Could you please also /lgtm ?

**Comment by Xtigyro** [comment]
> 
> 
> @Xtigyro
> 
> Thanks :)
> Could you please also /lgtm ?
> 
> Bot sys: "Pending — Not mergeable. Needs lgtm label."

Yeah - I usually do that at a later stage.

Thanks for the contribution - it's appreciated!

**Pull request merged**
