### PR TITLE
Gitea: Creation

### PR DESCRIPTION
**Pull request by ekozan**
This is still a WIP for comment

Todo 

- Automatic setup of Postgress
- Complete Readme 

I need to make an PR on the main repo for add a configuration script with env variable

### CODE REVIEW

**Comment by ekozan** [comment]
I signed it!

**Comment by viglesiasce** [comment]
Thanks for the submission @ekozan! Let us know when you are done adding the DB configuration. Look at the Wordpress and Gitlab charts for examples.

Also can you make sure to make the default service a ClusterIP if the credentials do not get set out of the box.

**Comment by ekozan** [comment]
Okay i'll do it tomorrow ;)

**Comment by jmn** [comment]
I am trying this (on GKE). Noting that the Gitea container is using a very large amount of memory compared to other containers. I am trying to see why that is. I *am* using sqlite so that might be thing.

image

**Comment by ekozan** [comment]
How many repo do you have ?

**Comment by jmn** [comment]
Just 3, one of which is a migration/mirror. Hardly any usage.

**Comment by jmn** [comment]
Perhaps set in` app.ini`:
`SESSION_LIFE_TIME = 86400`
I believe not setting session_life_time stores session data indefinitely which fills up disk.

**Comment by mgoodness** [comment]
@ekozan is this still an active/WIP PR? Do you have an ETA for completion?

**Comment by mgoodness** [comment]
Closing due to inactivity. Feel free to re-open if/when ready.

**Comment by robdefeo** [comment]
Did this ever get completed? Hoping to try this out

**Pull request closed without merging**
