### PR TITLE
[stable/coredns] Document variables, add maintainer

### PR DESCRIPTION
**Pull request by mrueg**
#### What this PR does / why we need it:
Documents Variables in Readme.md
Adds myself as a maintainer (as discussed with @maorfr a while ago on slack; I have provided most of the recent commits keeping the chart up to date and adding more features to it)
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
@andor44 @shashidharatd @Acaleph let me know if you have concerns.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
i've added @acaleph and @mreug to the trusted collaboratos list, need to both accept. in addition, need to make the tests green.

**Comment by mrueg** [comment]
> i've added @acaleph and @mreug to the trusted collaboratos list, need to both accept. in addition, need to make the tests green.
Thanks, I've accepted the invite. :)

**Comment by maorfr** [comment]
ping @acaleph @shashidharatd @andor44

**Comment by andor44** [comment]
/lgtm

sorry, misinterpreted @maorfr's message, thought no action was needed on our parts 😄

**Pull request merged**
