### PR TITLE
[stable/chaoskube] Updated OWNERS to add alexvicegrab

### PR DESCRIPTION
**Pull request by alexvicegrab**
#### What this PR does / why we need it:

Add myself as a maintainer to help review PRs.

#### Special notes for your reviewer:

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)
- [x] Version bumped

### CODE REVIEW

**Comment by alexvicegrab** [comment]
Aha, I will need to sign the DCO. Will do and update.

**Comment by alexvicegrab** [comment]
assign @maorfr

**Comment by maorfr** [comment]
/assign @linki 

please also add yourself to Chart.yaml

thanks!

**Comment by maorfr** [comment]
/lgtm

good luck!

**Pull request merged**
