### PR TITLE
[stable/mongodb] Support Prometheus monitoring using Prometheus Operator

### PR DESCRIPTION
**Pull request by startnow65**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by startnow65** [comment]
Hi @javsalgar, for the "fix metrics" part, set `values.usePassword` to `false` both containers in the pods should fully enter `running` state.

For the support for Service Monitors part
1. Prometheus Operator needs to be installed on the Kubernetes cluster. Please see guide [here](https://coreos.com/blog/the-prometheus-operator.html)
2. Set `values.metrics.enabled` and `values.metrics.serviceMonitor.enabled` to `true`
3. Pass the labels specified in the `matchLabels` section of the installed (from step 1 above) `Prometheus` CRD using the `values.metrics.serviceMonitor.additionalLabels`

`ServiceMonitor` objects should be created and Targets for mongodb should show up on Prometheus

You can also find more information in the values.yaml file
Please let me know if you need more information.
Thanks

**Comment by javsalgar** [comment]
Thanks! Could you explain a bit more about the "fix metrics" part? Do I need to set an empty password to make the Prometheus Operator integration work?

**Comment by javsalgar** [comment]
Thanks! LGTM

@juan131 @carrodher can you check?

**Comment by sebastien-prudhomme** [comment]
@startnow65 Hi, it seems that you forgot the standalone case. Can you confirm?

**Comment by startnow65** [comment]
Thank @sebastien-prudhomme, sadly, yes, I forgot the standalone case. I've created #9560 to fix that.

**Pull request merged**
