### PR TITLE
Updated linkerd chart

### PR DESCRIPTION
**Pull request by eicnix**
* Updated image version
* Add optional ingress configuration for the admin ui
* Allows to modify the linkerd configuration through a value

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
Crashing on startup with the following error
```
I 0315 23:17:49.267 THREAD1: Finagle version 6.41.0 (rev=95eedf5f41f78414fae25d93cc8fae02eeb5a75d) built at 20161220-164342
com.fasterxml.jackson.databind.JsonMappingException: label char expected but '{' found at '/http/1.1/* => /#/io.l5d.k8s/[{]{ .Release.Namespace }}/{{ .Values.linkerd.discoveryPortName }}
```

**Comment by lachie83** [comment]
templated variables cannot be in values.yaml

**Comment by seanknox** [comment]
Latest commit looks good. Thanks!

**Comment by seanknox** [comment]
@eicnix Can you bump the minor version in `Chart.yaml`? Thanks!

**Comment by eicnix** [comment]
@seanknox done.

**Comment by seanknox** [comment]
Thanks @eicnix—I bumped the minor version since this PR adds new functionality.

**Pull request merged**
