### PR TITLE
[stable/airflow] Remove values-test.yaml

### LINKED ISSUE #22600: [stable/airflow] delete values-test.yaml
**Describe the bug**
A file `values-test.yaml` was accidentally included in 7.1.2 (https://github.com/helm/charts/pull/22587) please delete the file and roll it into a future version 

**Version of Helm and Kubernetes**:
Helm: 3.2.1
Kubernetes: 1.15.7

**Which chart**:
stable/airflow: 7.1.2

**What happened**:
When the PR https://github.com/helm/charts/pull/22587 was made the contributor anciently included a file `values-test.yaml` that appears to not be intended to be part of the repo. Appears to be a test values file for dev/testing. Also it is not even up to date with values.yaml because it is missing some sections.

**What you expected to happen**:
There not be a `values-test.yaml`

**How to reproduce it** (as minimally and precisely as possible):
Pull down the latest commit https://github.com/helm/charts/commit/6c52106bc690a3ffc0f439574646379dbb0ca1bb that includes the 7.1.2 fix and you will see a `values-test.yaml`

**Anything else we need to know**:
There is no need to bump up the version of the chart just for a minor "hotfix" like this, so that is why I am making this as an issue so helpfully it is picked up for inclusion in a next version. If this was a standalone repo for the Airflow chart I would say we should create version Milestones to easily track and roll up all the minor hotfixes into the next version, similar to the apache/airflow repo.

### PR DESCRIPTION
**Pull request by dwardu89**
#### What this PR does / why we need it:
Keeping the chart clean in refernce to #22600 

#### Which issue this PR fixes
  - fixes #22600

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@gsemet, I don't mean this in a bad way, but can we please both review stuff before merging, to try and reduce the risk of introducing errors?

For example, like the random `values-test.yaml`, and confusing docs of PR #22587.

**Comment by gsemet** [comment]
Yes, sure I try my best :)

**Comment by alexbegg** [comment]
Also @gsemet and @thesuperzapper is it possible to include the [stable/airflow] prefix to the commit message when merging? Even though it is in the PR title for some reason some the last two stable/airflow commits in this repo have no prefix

**Comment by gsemet** [comment]
hI. I do not see the point in enforcing the commit message, it is not useful and neither enforced by the CI (if we want this, we need to make it automatically check).

**Pull request merged**
