### PR TITLE
[stable/grafana] Add rbac.pspUseAppArmor value to allow disabling AppArmor

### LINKED ISSUE #9090: [stable/grafana] PodSecurityPolicy breaks install on hosts without AppArmor
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**:
Helm 2.10.0, Kubernetes 1.10.7

**Which chart**:
stable/grafana

**What happened**:
I attempted to install the grafana/stable chart on our Kubernetes cluster running on Amazon Linux 2 with PodSecurityPolicy enforcement enabled. The resulting Grafana pod failed to start and entered state `Blocked` with the following message:

>Cannot enforce AppArmor: AppArmor is not enabled on the host

**What you expected to happen**:
I expected the Grafana pod to start up successfully.

**How to reproduce it** (as minimally and precisely as possible):
Install the Grafana chart with default values on a cluster with PodSecurityPolicy enabled, with nodes running any distribution without AppArmor (e.g. Amazon Linux 2, CentOS, Debian by default).

**Anything else we need to know**:
The best workaround at this point is to set `rbac.pspEnabled` to false and create the PSP and associated roles externally, which can be pretty painful.

I will try to send a PR later this week to add a setting to allow the AppArmor annotations to be turned off with a value change.

### PR DESCRIPTION
**Pull request by drakedevel**
#### What this PR does / why we need it:
This PR adds a flag `rbac.pspUseAppArmor` which makes the `apparmor.security.beta.kubernetes.io/*` annotations in the generated PodSecurityPolicy optional. These annotations prevent the chart from being directly installable on clusters with PSP enforcement running on distributions without AppArmor support (such as Amazon Linux 2). With the flag, the chart becomes substantially more usable.

Additionally updates the README.md to mention the new value, as well as the other `rbac.*` values which were undocumented.

#### Which issue this PR fixes
  - fixes #9090 

#### Special notes for your reviewer:
I tested this on our development cluster (Kubernetes 1.10.7 with PSP enforcement running on Amazon Linux 2):

```helm install --name grafana-test ./grafana```

Installs successfully, but results in a `Blocked` pod per #9090. 

```helm install --name grafana-test --set rbac.pspUseAppArmor=false ./grafana```

Installs successfully and the pod starts up just fine.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by drakedevel** [comment]
Rebased to fix merge conflicts, no changes besides whitespace and a higher chart version.

**Review by davidkarlsen — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@drakedevel can you fix the mergeconflict and I think this is good to go

**Comment by drakedevel** [comment]
@davidkarlsen done!

**Comment by drakedevel** [comment]
@davidkarlsen is there anything else I need to do in order for this PR to be merged?

**Pull request merged**
