### PR TITLE
[stable/prometheus-node-exporter] Add nodeSelector to DaemonSet

### PR DESCRIPTION
**Pull request by kvonbredow**
Signed-off-by: Kyle von Bredow <kylevonbredow@gmail.com>

#### What this PR does / why we need it:

It allows the node-exporter daemonset to be deployed in a hybrid cluster, such as a mixed-os environment with Linux and Windows nodes.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gianrubio — CHANGES_REQUESTED** [review]
I'd suggest you to replace `nodeSelector` by `nodeAffinity` because it gives more control, please see examples [here](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#scheduled-by-default-scheduler-enabled-by-default-since-1-12)

**Comment by kvonbredow** [comment]
Would it make sense to have the user specify an entire [Affinity object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#affinity-v1-core)? or just go ahead and drill down into `nodeAffinity`?

**Comment by davidkarlsen** [comment]
@kvonbredow See example here: https://github.com/helm/charts/blob/master/stable/node-problem-detector/templates/daemonset.yaml#L56

**Comment by kvonbredow** [comment]
Alright, I've pushed my changes to allow for that.  If you'd like me to use the `with` statement instead I can do that, but I figured I'd match the style of rest of the manifest.

**Pull request merged**
