### PR TITLE
[incubator/kafka] liveness and readiness probes as parameters

### PR DESCRIPTION
**Pull request by zaytsevpavel**
Guys, I have problems with starting kafka pods on my kubernetes cluster (running on bare metal).
```
Liveness probe failed: dial tcp 10.244.1.10:9092: getsockopt: connection refused
```
I decided to make liveness and readiness probes parameters configurable.

### CODE REVIEW

**Comment by unguiculus** [comment]
Please fix your CLA.

**Comment by fedenusy** [comment]
Please consider #3454 instead, which gives even more flexibility.

**Comment by benjigoldberg** [comment]
partially duplicated by https://github.com/kubernetes/charts/pull/3948

**Comment by unguiculus** [comment]
I think we can close this, since #3948 was merged.

**Pull request closed without merging**
