### PR TITLE
[stable/cert-manager] switch to semver version number

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: Changes version number of chart to SemVer as suggested in:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/conventions.md#version-numbers

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by munnerz** [comment]
Thanks for this PR - I've just dug into this repo with grep to see if any other projects are using a `v` prefix, and cannot see any other examples.

I did ask around the time of changing this if there was any objection, and the consensus was that there was nothing formal.

I'd be happy to switch this back though given other charts do the same.

The docs you linked to however, do not explicitly clarify about prefixes (and I know it is a messy issue in the world of semver). It'd be awesome if it can be clearly clarified there what should be done, to prevent something like this happening again.

Finally, we don't actually accept changes to the Helm chart in this repo, in favour of changes being made upstream so they can be properly versioned. They are then periodically synced across to here as appropriate. This allows us to properly version the chart with the application 😄: https://github.com/jetstack/cert-manager/tree/master/contrib/charts/cert-manager

Also, a last comment on the PR itself.. can you revert the rename of `00-namespace.yaml` please. That file is named as such, so that users that install cert-manager using our 'static manifests' will create the Namespace resource before any other 😄 

I'll close this for now to keep the k/charts issue board clean - please re-open upstream! 😄 

/close

**Comment by monotek** [comment]
Thanks for your reply. I'll create the issue at upstream later.

About the namespace file.... I don't get why you need it at all because helm has "--namespace" option, which creates the namespace, if not available. So normally you would not need that file.

**Comment by munnerz** [comment]
> About the namespace file.... I don't get why you need it at all because helm has "--namespace" option, which creates the namespace, if not available. So normally you would not need that file.

Yep, correct - it is only ever used when we generate static manifests using the `helm template` command here: https://github.com/jetstack/cert-manager/blob/master/contrib/manifests/cert-manager/without-rbac.yaml#L1-L8

(see https://github.com/jetstack/cert-manager/blob/master/hack/update-deploy-gen.sh#L24 for where we set the value to 'true').

Without this, a user would have to manually create this namespace before installing cert-manager **without** Helm (meaning they cannot simply `kubectl apply -f https://...`). When installing with Helm, this value is always false and so Helm/Tiller itself will create the namespace as you describe 😄

**Comment by Jokero** [comment]
@munnerz I am also wondered why cert-manager has `v` prefix. Actually I could not find any other chart with that prefix. Would like to have consistency between all charts here

**Pull request closed without merging**
