### PR TITLE
[stable/traefik] Feature/daemonset

### PR DESCRIPTION
**Pull request by dioguerra**
First and foremost. This is a Fix for THIS PR https://github.com/helm/charts/pull/11813
What this PR does / why we need it:
Which issue this PR fixes
Support for DaemonSet in Traefik (see #9797)

Special notes for your reviewer:
```yaml
hostNetwork:
  enabled: true
deployType: "DaemonSet"
securityContext:
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped (new feature)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by MrD2** [comment]
@zanhsieh can you review?

**Comment by zanhsieh** [comment]
/ok-to-test

@MrD2 
I could only push to e2e test but unable to merge it. Only the OWNERS could merge.

**Comment by hlascelles** [comment]
Happy new year stalebot!

**Comment by hlascelles** [comment]
We'd still like this.

**Comment by MrD2** [comment]
If there is enough interest i can supply this chart in a public repository from my institution

**Comment by hlascelles** [comment]
Yes please, it's something we would use! Thank you...

**Pull request closed without merging**
