### PR TITLE
Node-RED: Implemented the option to add a subPath when enabling persistence

### PR DESCRIPTION
**Pull request by gandazgul**
#### What this PR does / why we need it:

I implemented the option to specify a subPath when enabling persistence.

#### Special notes for your reviewer:

@billimek Could you take a look please?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by billimek — APPROVED** [review]

**Comment by billimek** [comment]
Great contribution @gandazgul, thank you!

**Comment by gandazgul** [comment]
Thank you!

**Pull request merged**
