### PR TITLE
[stable/prometheus-operator] Bump kube-state-metrics version

### PR DESCRIPTION
**Pull request by maruina**
#### What this PR does / why we need it:

Bump the Kube State Metric requirements to the latest version (as per https://github.com/helm/charts/pull/19726)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by maruina** [comment]
We should hold this PR until https://github.com/kubernetes/kube-state-metrics/issues/1012 is fixed.

**Comment by wilmardo** [comment]
@maruina They just released the fix:
https://github.com/kubernetes/kube-state-metrics/releases

The PR for the chart is already open:
https://github.com/helm/charts/pull/20028

**Comment by maruina** [comment]
Thanks @wilmardo, I updated the PR

**Comment by maruina** [comment]
@vsliouniaev do you think it's something related to the PR? I had a look at the link but I'm not sure why it's failing

**Comment by vsliouniaev** [comment]
Unfortunately this needs yet another version bump please!
/lgtm

**Comment by christopherfrazier** [comment]
FYI - kube-state-metrics is looping on SIGSEGV. Reverting to chart version 8.5.7 resolved it.

```
I0114 15:36:49.843638       1 main.go:89] Using collectors certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0114 15:36:49.843686       1 main.go:98] Using all namespace
I0114 15:36:49.843693       1 main.go:139] metric white-blacklisting: blacklisting the following items:
W0114 15:36:49.843709       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0114 15:36:49.844589       1 main.go:184] Testing communication with server
I0114 15:36:49.860236       1 main.go:189] Running with Kubernetes cluster version: v1.12. git version: v1.12.10. git tree state: clean. commit: e3c134023df5dea457638b614ee17ef234dc34a6. platform: linux/amd64
I0114 15:36:49.860266       1 main.go:191] Communication with server successful
I0114 15:36:49.860469       1 main.go:225] Starting metrics server: 0.0.0.0:8080
I0114 15:36:49.860554       1 main.go:200] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
I0114 15:36:49.860586       1 metrics_handler.go:96] Autosharding disabled
I0114 15:36:49.861998       1 builder.go:146] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
E0114 15:36:49.891515       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 44 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x13c4de0, 0x2178810)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191111054156-6eb29fdf75dc/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191111054156-6eb29fdf75dc/pkg/util/runtime/runtime.go:48 +0x82
panic(0x13c4de0, 0x2178810)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kube-state-metrics/internal/store.glob..func81(0xc000133100, 0xc000206ca0)
        /go/src/k8s.io/kube-state-metrics/internal/store/hpa.go:280 +0x1d4
k8s.io/kube-state-metrics/internal/store.wrapHPAFunc.func1(0x153f360, 0xc000133100, 0xc000579530)
        /go/src/k8s.io/kube-state-metrics/internal/store/hpa.go:296 +0x5c
k8s.io/kube-state-metrics/pkg/metric.(*FamilyGenerator).Generate(...)
        /go/src/k8s.io/kube-state-metrics/pkg/metric/generator.go:39
k8s.io/kube-state-metrics/pkg/metric.ComposeMetricGenFuncs.func1(0x153f360, 0xc000133100, 0x7f88baef93e0, 0xc000133100, 0x0)
        /go/src/k8s.io/kube-state-metrics/pkg/metric/generator.go:78 +0x122
k8s.io/kube-state-metrics/pkg/metrics_store.(*MetricsStore).Add(0xc000114680, 0x153f360, 0xc000133100, 0x0, 0x0)
        /go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:76 +0xf6
k8s.io/kube-state-metrics/pkg/metrics_store.(*MetricsStore).Replace(0xc000114680, 0xc000579350, 0x3, 0x3, 0xc0003ba400, 0x9, 0x3323f71, 0x219a560)
        /go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:138 +0xa4
k8s.io/client-go/tools/cache.(*Reflector).syncWith(0xc00045e480, 0xc000579320, 0x3, 0x3, 0xc0003ba400, 0x9, 0x0, 0xc000158ae0)
        /go/pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:354 +0xf8
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00045e480, 0xc000381e80, 0xc0003c0420, 0xc000403bb8, 0x0, 0x0)
        /go/pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:250 +0x8fa
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00045e480, 0xc0003c0420, 0x0, 0x0)
        /go/pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:257 +0x1a9
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:155 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003b0f78)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191111054156-6eb29fdf75dc/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000403f78, 0x3b9aca00, 0x0, 0x1, 0xc0003c0420)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191111054156-6eb29fdf75dc/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191111054156-6eb29fdf75dc/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00045e480, 0xc0003c0420)
        /go/pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:154 +0x16b
created by k8s.io/kube-state-metrics/internal/store.(*Builder).reflectorPerNamespace
        /go/src/k8s.io/kube-state-metrics/internal/store/builder.go:337 +0x265
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12601c4]
...
```

**Comment by foux** [comment]
This PR clearly broke `prometheus-operator` on my cluster, with the same issue as @christopherfrazier 
I'm now stuck with 8.5.7

**Comment by vsliouniaev** [comment]
Should have https://github.com/helm/charts/pull/20288 later today

**Pull request merged**
