### PR TITLE
[elastalert] Add flag to use_ssl when connecting to elasticsearch

### PR DESCRIPTION
**Pull request by gianrubio**
**What this PR does / why we need it**:

Use ssl connection when talking to a es server with tls enabled

### CODE REVIEW

**Comment by gianrubio** [comment]
@pickledrick @jertel

**Comment by jertel** [comment]
This is a duplicate of #4617 . Not sure what's holding that one up. @AlexRRR?

**Comment by AlexRRR** [comment]
@jertel that one is ready to go, there was a camelcase issue I was asked to fix so it lost the `lgtm` label.

**Comment by AlexRRR** [comment]
This PR takes into consideration redeploying in case the config changes, that's nice IMHO.

**Comment by jertel** [comment]
@AlexRRR your PR is failing CI (probably missing the newly required Charts.yaml "home" field), and it's falling behind which is causing merge conflicts with master, so the bot can't auto-merge. Since @gianrubio's  PR has the added benefit of detecting the config change I suggest closing your PR out in favor of this new one.

**Comment by timstoop** [comment]
Pet peeve of mine, but should the parameter not be called `use_tls` instead? As it hope it's not actually using SSL anymore...

**Comment by jertel** [comment]
I agree with you @timstoop. use_tls is preferred.

**Comment by gianrubio** [comment]
> Pet peeve of mine, but should the parameter not be called use_tls instead? As it hope it's not actually using SSL anymore...

I don't agree that `use_tls` it's the right parameter, the configuration parameter in ElastAlert is `use_ssl` so I'd prefer to follow their parameter

**Comment by unguiculus** [comment]
Camel case should be used.

`useSsl`

**Comment by gianrubio** [comment]
done

**Pull request merged**
