### PR TITLE
[stable/home-assistant] - Add extraVolumes/mounts

### PR DESCRIPTION
**Pull request by mikesplain**
#### Is this a new chart
No

#### What this PR does / why we need it:
* Add extraVoumes
* Add extraVoumeMounts
* Version bump

#### Which issue this PR fixes
n/a
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by billimek** [comment]
@mikesplain do you mind bumping the minor version?  (0.11.0)?

**Comment by mikesplain** [comment]
You bet, done! Thanks @billimek!

**Pull request merged**
