### PR TITLE
NFS setup to enable wordpress deployment to be scaled if you only have access to a ReadWriteOnce PVC

### PR DESCRIPTION
**Pull request by vtuson**
**What this PR does / why we need it**:
I have been looking to how you can scale the wordpress deployment in this chart beyond 1 replica. The problem is that Wordpress can be administer via the /admin console. This allows the user to install/update plugins, set themes, change css... this is persisted in a locally mounted volume. The current chart enables you to use a PVC that is correctly mounted to persist the above actions. 

However, if (as in many cloud providers) you only have access to PVCs that allow ReadWriteOnce, you can not scale your deployment outside a single node.

To have better high availability and allow for horizontal scaling, this PR enables (and can be disabled via values.yaml) a NFS server that maps to a ReadWriteOnce PVC. Then it defines a PV and PVC that is mounted in the Wordpress Replicas.  This means that all replicas can read the data, and changes done via /admin panel will be persisted and shared across them. As these are not performance sensitive write actions, an NFS should be good enough.

**Special notes for your reviewer**:
We can use this PR to discuss if this is a good approach or what other alternatives we can have to achieve similar solutions.

Please note that this only adds functionality, you can still turn it off and use the chart as you were before.

Also NFS PV requires to have provision the actual clusterip of the service, I have tried using the FDQN (svc.namespace.cluster.local) but this is not currently supported/working, so a clusterip has to statically be provision in the nfs-service, so it can be referred in the PV when installing a release.

### CODE REVIEW

**Review by prydonius — COMMENTED** [review]
This is really cool!! Couple of thoughts:

- What if we used the NFS dynamic provisioner (https://github.com/kubernetes-incubator/external-storage/tree/master/nfs), this will give us a real StorageClass and we can use it to dynamically provision future volumes. Since there should probably only be one provisioner, we'd probably need to have documentation to install the nfs provisioner chart before this one. Whilst the current method is valid, the dynamic provisioner is a more correct way of doing it IMO.
- If we choose to stick to this in the meantime, can we move the templates to a sub-chart so we can reuse this in other apps more easily?

**Comment by vtuson** [comment]
@prydonius re: NFS dynamic provisioner - so I guess the difference here would be that the Provisioner would monitor PVC for that storage class an auto-magically bound them. I guess that is not something you need to include in the chart and the current chart would allow you to do that as you can set the storageclass value.

The good thing about the NFS being build into the char is that it is specific to the chart and selfcontain imho - this is a nice feature to have since you dont need to give it super powers in the cluster, which I think raises the knowledge bar for the user of the chart.

"If we choose to stick to this in the meantime, can we move the templates to a sub-chart so we can reuse this in other apps more easily?" --> I like the suggestions. So would that be its own chart  that is pull from a separate repository or included in the same repo?

**Comment by prydonius** [comment]
> so I guess the difference here would be that the Provisioner would monitor PVC for that storage class an auto-magically bound them
correct, similarly to how a cloud provisioner might provision a GCE PD volume and bind that

> I guess that is not something you need to include in the chart and the current chart would allow you to do that as you can set the storageclass value.

Yep, but it might be useful to create an easy-to-install chart for the provisioner and host it in our repo. The nice thing about this approach is that you don't need to change this chart, but instead instruct the user to set the right storage class.

> The good thing about the NFS being build into the char is that it is specific to the chart and selfcontain imho - this is a nice feature to have since you dont need to give it super powers in the cluster, which I think raises the knowledge bar for the user of the chart.

true, I do think this is an easier approach. the downside is you deploy one nfs server per chart which is a little sub-optimal if you're deploying lots of these. 

>  So would that be its own chart that is pull from a separate repository or included in the same repo?

It can probably be included in the same repo, we don't really have a good place for these kinds of library charts right now.

**Comment by vtuson** [comment]
> Yep, but it might be useful to create an easy-to-install chart for the provisioner and host it in our repo. The nice thing about this approach is that you don't need to change this chart, but instead instruct the user to set the right storage class.
>

Might be, I guess we can do both. 
 
> The good thing about the NFS being build into the char is that it is specific to the chart and selfcontain imho - this is a nice feature to have since you dont need to give it super powers in the cluster, which I think raises the knowledge bar for the user of the chart.
> 
> true, I do think this is an easier approach. the downside is you deploy one nfs server per chart which is a little sub-optimal if you're deploying lots of these.

Yes but ultimately you are sharing one ReadWriteOnce PVC so  it is easier to manage who that maps to real storage. I think both solutions are valid for different use cases.

> 
> So would that be its own chart that is pull from a separate repository or included in the same repo?
> 
> It can probably be included in the same repo, we don't really have a good place for these kinds of library charts right now.

Ok, I can do that and maybe we can start a library to copy from in a repo of something.

**Comment by vtuson** [comment]
btw do you have a pointer to an example of a chart that includes a subchart already? @prydonius

**Comment by prydonius** [comment]
@vtuson you'd want to add the subchart to the requirements.yaml. Of course, the chart needs to be in the repo first, so you would need to get that merged prior to this change. (https://github.com/kubernetes/charts/blob/master/stable/wordpress/requirements.yaml)

**Comment by vtuson** [comment]
Right so the su b chat would be a new chart on it own?

**Comment by vtuson** [comment]
as suggested, I have created a PR for a generic chart - https://github.com/kubernetes/charts/pull/5049

**Comment by vtuson** [comment]
@adnan based on this https://github.com/kubernetes/charts/pull/5049#issuecomment-381640655 and the fact that this discussion has been open for months at an end, I would suggest to continue with this PR to merge the functionality into wp

**Comment by vtuson** [comment]
@adnan I have made a new commit removing the PV and PVC for nfs and mounting directly the volume

**Comment by vtuson** [comment]
I have tested and documented how to use the new nfs-server chart to do the same; https://github.com/kubernetes/charts/pull/5286

I will close the PR as soon as the other one is merged

**Pull request closed without merging**
