### PR TITLE
[stable/rabbitmq] Fix healthchecks for non-bitnami images

### PR DESCRIPTION
**Pull request by PaulFarver**
#### What this PR does / why we need it:
- The healthcheck scripts are no longer written to a file during startup. They are instead mounted from a configmap with appropriate permissions. This should make it easier to maintain the chart in the future.
- The healthcheck scripts are mounted to `/usr/local/sbin/` instead of `/opt/bitnami/rabbitmq/sbin/`. This is to accomodate images that don't have `/opt/bitnami/rabbitmq/sbin/` on their path.
- ~~Instead of creating and removing a .start file, when the healthcheck is first run, it is created after the healthcheck has been run. The if statement has been negated.~~

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by PaulFarver** [comment]
Just figured out why the startup check was the way it was. Did not notice that the .start file was located in the persisted path. Will revert that commit

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by tompizmor** [comment]
Hi @PaulFarver,

Thanks for the PR! It seems there are some conflicts in the `stable/rabbitmq/Chart.yaml` file.
Can you resolve them?

**Comment by PaulFarver** [comment]
> Hi @PaulFarver,
> 
> Thanks for the PR! It seems there are some conflicts in the `stable/rabbitmq/Chart.yaml` file.
> Can you resolve them?

Of course!
Corrected in e263561

**Comment by PaulFarver** [comment]
@tompizmor could you review this again? The conflict should be resolved

**Comment by PaulFarver** [comment]
It seems like this pull request is stuck in approved but not ok-to-merge. Is there anything I can do to help the process, so we can get this merged? @prydonius

**Comment by PaulFarver** [comment]
The lgtm label was removed after I resolved the conflict in Chart.yml. Could you take a look at it again @tompizmor ?

**Comment by juan131** [comment]
@tompizmor it seems we lost the track of this PR. Could you please re-review it when you have a chance?

**Comment by tompizmor** [comment]
HI @PaulFarver,

I am sorry for the late response. As juanariza says, we lost track of this PR in our internal system and we didn't realize until the stale bot added a new comment. Do you mind taking another look to the conflicts?

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by juan131** [comment]
Hi @PaulFarver 

The CI tests are failing:

```
I1007 08:35:55.899] Old chart version: 6.8.2
I1007 08:35:55.900] New chart version: 6.8.2
I1007 08:35:55.901] Error linting and installing charts: Error processing charts
I1007 08:35:55.901] ------------------------------------------------------------------------------------------------------------------------
I1007 08:35:55.902]  âœ–ï¸Ž rabbitmq => (version: "6.8.2", path: "stable/rabbitmq") > Chart version not ok. Needs a version bump!
```

It seems you need to bump the version in the **Chart.yaml**

**Comment by PaulFarver** [comment]
Hey @juan131 
I've bumped the version again. This chart is developing pretty fast ;)

**Comment by tompizmor** [comment]
Thanks @juan131 and @PaulFarver!

**Pull request merged**
