### PR TITLE
[stable/stellar-horizon] New helm chart

### PR DESCRIPTION
**Pull request by charyorde**
#### What this PR does / why we need it:
Helm chart for stellar-horizon. Details at https://hub.docker.com/r/satoshipay/stellar-horizon

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by charyorde** [comment]
@sameersbn Resolved. Thanks

**Comment by charyorde** [comment]
@todkap Oh. Didn't see this.

Please share.

**Comment by todkap** [comment]
We recently published an article with helm charts that demoed the entire setup of core and horizon.  The biggest issues we hit were related to storage classes and permissions for Postgres.  We ended up changing how we register default storage classes.

Take a look 
https://itnext.io/how-to-deploy-a-stellar-validator-on-kubernetes-with-helm-a111e5dfe437

We would welcome the thought of this being ported back to the community helm charts.

**Pull request closed without merging**
