### PR TITLE
stable/airflow Added support for airflow session affinity

### PR DESCRIPTION
**Pull request by stijndehaes**
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>

#### What this PR does / why we need it:

It adds support for session affinity. When doing a rolling upgrade with baked in dags. Dags appear and disappear because the image is changed. The session affinity can fix this if properly configured.

#### Which issue this PR fixes
-

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by stijndehaes** [comment]
@gsemet Can I ask your review for this PR.

**Comment by gsemet** [comment]
Not sure to understand why this does not work ?

**Comment by stijndehaes** [comment]
During a rolling upgrade we have 2 versions of the airflow image running: one with the old version of the dags and one with the new version. Maybe in the second version we have an extra dag. If you refresh the page you hit on of the two airflow web servers. One that has on dag less and this looks funky.

**Comment by gsemet** [comment]
Ah, wrong PR, this one is ok, I was questioning actually on the other one !

**Comment by stijndehaes** [comment]
> Ah, wrong PR, this one is ok, I was questioning actually on the other one !

That makes more sense :)

**Pull request merged**
