### PR TITLE
Update owncloud version

### PR DESCRIPTION
**Pull request by juan131**

### CODE REVIEW

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Review by viglesiasce — CHANGES_REQUESTED** [review]
This chart no longer installs on 1.5.1. Update its mariadb dep to 0.5.6 in order to pick up the fix.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by prydonius** [comment]
Closing as this is superseded by #380

**Pull request closed without merging**
