### PR TITLE
feat: uses helm-docs to automatically generate documentation for the …

### LINKED ISSUE #15717: [stable/grafana] Automatically generate chart documentation
**Is your feature request related to a problem? Please describe.**
I have noticed a number of charts where the README documentation is out of sync with the chart values. This is due to the related problem that updating values and having to also update the defaults and descriptions of those values in the README.md is tedious and error-prone. It would be nice to have a single source of truth for the descriptions and defaults of all values in a chart.

**Describe the solution you'd like**
I have implemented a project [helm-docs](https://github.com/norwoodj/helm-docs), which can automatically generate documentation for a chart. This includes parsing values defaults and descriptions from the `values.yaml` file. In this way, there will be only a single source of truth for this documentation, and the values file can have comments with exactly the same descriptions for values that ends up in the README

**Describe alternatives you've considered**
This project was inspired by the wonderful [terraform-docs](https://github.com/segmentio/terraform-docs) project, and though I did a lot of searching, I have been unable to find an equivalent project for helm charts, other than the one I have now implemented.

**Additional context**
We've been using this project where I work for about a year now, with great success. I think it will decrease effort required for writing documentation, as well as decrease the frequency with which the READMEs get out of sync.

I have integrated the tool with the grafana chart and will add a commit with those changes as an example of how the tool is used.

### PR DESCRIPTION
**Pull request by norwoodj**
…grafana helm chart

  Fixes https://github.com/helm/charts/issues/15717

#### What this PR does / why we need it:
Adds automatic documentation generation for the grafana helm chart using the [helm-docs](https://github.com/norwoodj/helm-docs) tool. This will enable contributors to update the values documentation in the README by running a script, rather than having to add/update that documentation manually after adding/changing the default of a value.

#### Which issue this PR fixes
  - fixes #15717

#### Special notes for your reviewer:
I am happy to make add new features to the helm-docs tool, which I am the owner of. I think this tool can substantially reduce the effort required to update documentation in this repository as well as increasing the accuracy of the documentation. The implementation of this for grafana is mainly intended as an example of the tool's usage. I would like that this tool is used to generate docs for _all_ of the charts here, though I will need help to do so. I hope that someone with control in this repository sees the value of auto-generating the documentation for these charts and helps me add this as a part of the contribution guidelines for the project as a whole.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
gotta get everything green ;)

**Comment by norwoodj** [comment]
@maorfr, apologies. Believe it's all fixed now. This merge request was mostly intended as an example, not something that should be merged in. Expecting contributors to author markdown templates and to run `helm-docs` before pushing changes for pull requests is a major shift from how this project has been operated up to this point. What I really would like to do is chat with the owners of this repository, (of which you seem to be one) about what it would take to get this documentation generation in as part of the ci pipeline for this project.

I'm happy to assist in making changes to contribution docs, circle-ci pipelines as well as to the tool itself, whatever is necessary. I just think that having automatic documentation generation will go a long way to reducing the toil of keeping values files and READMEs in sync as well as result in more correct documentation.

Let me know.

**Comment by maorfr** [comment]
I totally think this is a great idea. Implementation is somrething to discuss. You can join the fortnightly charts chat every other at Tuesday (on this week) at 9AM PT on https://zoom.us/j/653187273 and bring it up!

**Comment by norwoodj** [comment]
Apologies for dropping off the map, I was on vacation for the better part of two weeks and busy with a lot of other things. I would be happy to get on the next fortnightly chat and chat about what it would take to get this implemented.

I've changed a few things here, adding a `.helmdocsignore` file, allowing the tool to be run from the root of the repository and only generate grafana for now.

**Pull request closed without merging**
