### PR TITLE
[stable/fluentd] Minor typo in README.md

### PR DESCRIPTION
**Pull request by dotdc**
Signed-off-by: David Calvert <davidcalvertfr@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by imrtfm** [comment]
Hi, here's a PR for a minor typo in the README.md of stable/fluentd.
I'm not sure if the chart version should be bumped so I left the checkbox unchecked.
Let me know if this PR is valid.

/assign @miouge1

**Comment by hectorj2f** [comment]
You will need to bump the chart version

**Review by hectorj2f — CHANGES_REQUESTED** [review]
Please, bump the chart version

**Comment by imrtfm** [comment]
> Please, bump the chart version

Done!

**Comment by imrtfm** [comment]
Is there anything else needed for the merge?

**Pull request merged**
