### PR TITLE
[stable/wordpress] Fix link in README.md

### PR DESCRIPTION
**Pull request by limenet**
#### Is this a new chart

No

#### What this PR does / why we need it:

A link to an overview of possible annotations in the README was broken and I fixed it.

#### Which issue this PR fixes

*none*

#### Special notes for your reviewer:

Let me know if you want me to make any changes and thanks for all your work!

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @limenet 

Thanks so much for the fix! Could you please bump the patch version in the `Chart.yaml`? It's mandatory for the CI/CD to merge the PR

**Comment by limenet** [comment]
Hi @juan131 

You're very welcome, thanks for the quick reply! Of course, I was unsure whether that bump was necessary. See commit https://github.com/helm/charts/pull/17638/commits/f296ae5e0b416e739a8829862118b6be18eee53c for the change

**Comment by juan131** [comment]
Hi @limenet 

I just found out we also have this link at:

https://github.com/helm/charts/blob/master/stable/wordpress/values.yaml#L260

And:

https://github.com/helm/charts/blob/master/stable/wordpress/values-production.yaml#L260

Could you fix those links too?

**Comment by limenet** [comment]
Good catch, @juan131, thank you!

I just ran a ripgrep for that link on the whole repo and discovered another 28 uses of it:

```
stable\dokuwiki\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
incubator\webpagetest-server\README.md:For annotations, please see [this document](https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md).
stable\drupal\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\ghost\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\jasperreports\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\joomla\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\magento\values-production.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\magento\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\mediawiki\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\moodle\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\mongodb\values-production.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\mongodb\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\nats\values-production.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\nats\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\odoo\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\opencart\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\osclass\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\owncloud\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\orangehrm\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\parse\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\phpbb\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\prestashop\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\phabricator\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\rabbitmq\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\rabbitmq\values-production.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\redmine\values.yaml:    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\suitecrm\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
stable\testlink\values.yaml:  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
```

Are separate PRs necessary for each chart?

**Comment by juan131** [comment]
HI @limenet 

I already created the PRs for the rest of charts. See https://github.com/helm/charts/pulls/juan131

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by limenet** [comment]
@juan131 I didn't see your PRs, thanks for taking care of that and I'm happy seeing this already merged!

**Pull request merged**
