### PR TITLE
Adding new ScyllaDB Helm chart to incubator

### PR DESCRIPTION
**Pull request by yuval-yaari**
Signed-off-by: Yuval Yaari <yuval.yaari@gmail.com>

#### What this PR does / why we need it:
ScyllaDB is an open-source NoSQL data store compatible with Apache Cassandra.                                                                                 
This aims to make it easier for ScyllaDB users to deploy ScyllaDB on Kubernetes.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by samhain1138** [comment]
Still hoping to get this reviewed and merged...

**Comment by rawkode** [comment]
This chart didn't work, so I've submitted a patch to @samhain1138 which (if merged) should hopefully propagate to here.

Keen to see this enter the incubator :+1:

**Comment by samhain1138** [comment]
@rawkode I reviewed your PR and requested a small change.
Other than that, I'll make sure to merge it asap.
Thank you so much!

**Comment by rawkode** [comment]
@samhain1138 There are no comments on my PR

**Comment by samhain1138** [comment]
@rawkode there is now! ;-)

**Comment by samhain1138** [comment]
@rawkode merged!
Thanks, again!

**Pull request closed without merging**
