### PR TITLE
[cluster-autoscaler] Update apiversions to latest

### PR DESCRIPTION
**Pull request by velothump**
Allows deployment to 1.16 clusters

#### What this PR does / why we need it:

Updates api versions to allow deployment to 1.16 clusters

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
Will you please parameterize this to ensure compatibility with k8s <1.16? Here's an example: https://github.com/helm/charts/blob/67a6776ed150cb48259afcce99b4a5cda364703b/stable/minio/templates/_helpers.tpl#L34-L43

**Comment by velothump** [comment]
Makes sense @yurrriq, thanks. Updated now. I've also updated the deployment to use a helper function as well.

**Comment by yurrriq** [comment]
Looks great, thanks! Will you please remove `deployment.apiVersion` from `values.yaml` and `README.md`, and bump version to `6.0.0`?

**Comment by velothump** [comment]
Of course, completely forgot about the readme. All updated now :)

**Review by yurrriq — APPROVED** [review]
LGTM thanks!

**Pull request merged**
