### PR TITLE
[incubator/schema-registry] typo fix:  zookeper->zookeeper

### PR DESCRIPTION
**Pull request by AdamDang**
Line 77&78: zookeper->zookeeper

### CODE REVIEW

**Comment by benjigoldberg** [comment]
/lgtm

Thanks for the updates @AdamDang

**Comment by benjigoldberg** [comment]
@AdamDang we have a fix coming in another PR for the tests failing -- its not your fault. Once that merges we can bump the version of the chart in your PR and be ready to go. Thanks again for the contribution

**Comment by AdamDang** [comment]
@benjigoldberg OK, Thanks a lot!

**Comment by benjigoldberg** [comment]
@AdamDang ok -- if you bump the chart version and push that back up you should be good to go

**Comment by AdamDang** [comment]
@benjigoldberg 
It looks that bumping the chart version will cause conflicts.

**Comment by benjigoldberg** [comment]
@AdamDang can you pull the changes from master into this branch -- you'll need those changes for the tests to pass

**Comment by AdamDang** [comment]
Thank you! @benjigoldberg 
I think pulling the changes from master to my branch can not be done by my browser Chrome. 
Command line is needed, right? I am not install it yet. :(

**Pull request merged**
