### PR TITLE
[stable/prometheus] default retention time is 15 days if not specified

### PR DESCRIPTION
**Pull request by dodizzle**
If you do not specify a retention time ie. ( --storage.tsdb.retention.time ) then by default it is set to 15 days.
In this PR I make that the default so that it is clear to users.

Signed-off-by: David O'Dell <dave@helix.re>

### CODE REVIEW

**Review by gianrubio — CHANGES_REQUESTED** [review]
Please bump the chart version

**Comment by dodizzle** [comment]
@gianrubio chart version bumped

**Comment by dodizzle** [comment]
@gianrubio chart version bumped

**Pull request merged**
