### PR TITLE
Update all dependent charts to mariadb 0.5.8

### PR DESCRIPTION
**Pull request by scottrigby**
The MariaDB dependency for stable/drupal should be updated from 0.5.7 to 0.5.8. See #427

### CODE REVIEW

**Comment by scottrigby** [comment]
OK. I see now that - yesterday - #555 added another mariadb version bump to 0.5.9. I'll make another round of bump commits per chart. 

Two things come to mind here:
1. I'm tempted to write a utility to help bump all dependent charts when a dependency to a specific version (just because it's slightly tedious to do one at a time).
2. Do we need to do this at all? I noticed a few charts ([osclass](https://github.com/kubernetes/charts/blob/master/stable/osclass/requirements.yaml), [orangehrn](https://github.com/kubernetes/charts/blob/master/stable/orangehrm/requirements.yaml)) list the mariadb dependency as `version: 0.5.x`. Does this use the latest stable minor version? If so, can we just change all the other charts dependency versions to use this instead?

**Comment by scottrigby** [comment]
For item 1 just above, I wrote a quick [dependency version bump utility script](https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092) that works well enough for now, but I realize this is not ideal. Therefore, I just created an issue in the Helm repo (kubernetes/helm/issues/1947) to add a new *define* command to `helm dependency`. Anyone interested, let's discuss that idea there?

I'm still interested to hear feedback on item 2 above 😄

**Comment by scottrigby** [comment]
@lachie83 Do you generally prefer dependency version bumps like this to be incremental in separate PRs (so you can roll back one version at a time if needed), or should I go ahead and update these all to 0.5.9 (per #555) in this same PR?

**Comment by lachie83** [comment]
@scottrigby I think we should be able to pin to 0.5.x although you still need to generate the updated lock file and check that in. @prydonius Can you weigh in here?

**Comment by prydonius** [comment]
Thanks @scottrigby! Separate PRs would be preferred in these cases, as it's often easier to deal with conflicts. I know it's a pain, but you should be able to put a script together to automate submitting the PRs with the help of the [`hub`](https://github.com/github/hub) tool.

If there are PRs already open for bumping a version of one of these charts (e.g. #628), I would just leave a comment in the PR and the owner can take care of bumping the dependency. That way we have less conflicting PRs to worry about.

About pinning to 0.5.x, we discovered some issues with this in the current version of Helm, so for now pinning exact versions is more reliable. Hopefully these issues should be fixed in 2.2.0 so we can revisit this.

**Comment by scottrigby** [comment]
@lachie83 Thanks for helping with this.

@prydonius Just to be clear do you mean:
1. You prefer a separate PR for each chart dependent on the bumped chart (I made each a separate commit, with the idea that reverting would be easier that way)
2. Or you prefer one PRs like this for upgrading all dependent charts to `0.5.8` and a separate one to upgrade to `0.5.9`?

I'm just not sure which one you meant.

I did wire up a simple script for now (updated my gist https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092), which is pretty easy for the moment (though I would welcome thoughts on my proposal in https://github.com/kubernetes/helm/issues/1947 for adding this to the Helm CLI). 

If you mean 1 above, I can modify that script as you said with hub to make a separate branch for each dependent chart when it's dependency bumps.

Re pinning, understood. The script I wrote accepts a string as arg, so while I'm passing a defined version for now, the arg could be a pinned version later once that issue is fixed.

**Comment by scottrigby** [comment]
@prydonius OK I think the answer is 1 above. I updated [the script](https://gist.github.com/scottrigby/4cba8b7454c3ecb38a1136cd06261092) to make this super-easy. Closing this in favor of the separate PRs per dependent chart (bumping each to the current version 0.5.9):

- #643
- #644
- #645
- #646
- #647
- #648
- #649
- #650
- #651
- #652
- #653
- #654
- #655
- #656
- #657
- #658

Thanks again @lachie83 @prydonius

**Pull request closed without merging**
