### PR TITLE
[incubator/jaeger] bump image tag to 1.1.0

### PR DESCRIPTION
**Pull request by bpot**
Use the latest release of jaeger.

### CODE REVIEW

**Comment by mattfarina** [comment]
@bpot Thanks for the pull request. There are a couple things that need to happen before we can work on it:

1. You need to sign the CLA and then leave a comment for the automation to pick it up. The directions are in one of the previous comments by the bot.
1. Charts are immutable so the version in the Chart.yaml file needs to be incremented.
1. The readme has an image tag version that should also be updated.

**Comment by ledor473** [comment]
The latest is now 1.2.0 👍

**Comment by ledor473** [comment]
@jdumars please do not merge.
Actually I think you can close it considering this is merged: https://github.com/kubernetes/charts/pull/3798

**Comment by prydonius** [comment]
@ledor473 thanks!

/close

**Pull request closed without merging**
