### PR TITLE
[stable/prometheus-operator] Update grafana to 4.0.0.

### PR DESCRIPTION
**Pull request by desaintmartin**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by desaintmartin** [comment]
Hm. Is it another test failure?
`Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists`

**Comment by desaintmartin** [comment]
/hold 
I got reports of issues with this version of the grafana helm chart.

**Comment by zanhsieh** [comment]
> Hm. Is it another test failure?
> `Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists`
@desaintmartin 
I think this means CRD does not get deleted properly after the chart has been tested. You might consider to implement hook. See other stable charts having this implemented.

**Comment by desaintmartin** [comment]
@zanhsieh It is already implemented. Obviously something is wrong here but I don't know what.

https://github.com/helm/charts/blob/master/stable/prometheus-operator/ci/test-values.yaml#L1029
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml

**Comment by zanhsieh** [comment]
@desaintmartin
Let's see retest result.

**Comment by desaintmartin** [comment]
Seems to pass!
Note that this change requires helm >= 2.12.0 (https://github.com/helm/charts/pull/18176, not yet merged, maybe better to wait, hence the /hold). Should we advertise it as well in this chart?

**Comment by vsliouniaev** [comment]
It would be ok if we bump the major version of this chart to indicate the breaking change with Helm minimum version requirement

**Comment by desaintmartin** [comment]
Still waiting for https://github.com/helm/charts/pull/18176 to be merged in order to update this PR.

**Comment by zanhsieh** [comment]
CRD cleanup issue again:

```
...
I1024 07:52:11.349] Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
...
```

**Comment by vsliouniaev** [comment]
I have a more permanent fix for this here, waiting for it to get merged: https://github.com/helm/charts/pull/18271

**Comment by desaintmartin** [comment]
Rebased.

**Comment by zanhsieh** [comment]
@desaintmartin 
Would you volunteer to be another owner of this chart please? @gianrubio does not have interest in this chart anymore (this chart, in other words, literally only has single owner). See:

https://github.com/helm/charts/issues/13867

**Comment by desaintmartin** [comment]
I can help maintaining this chart but I won't have the time maintaining it on my own! I already maintain way too many charts for smooth PR merging. ;)

**Pull request merged**
