### PR TITLE
[stable/prometheus-operator] add missing Grafana Annotations to k8s-coredns dashboard

### PR DESCRIPTION
**Pull request by sjentzsch**
Signed-off-by: Sören Jentzsch <me@sjentzsch.de>

#### What this PR does / why we need it:

Annotations were missing for just the k8s-coredns dashboard, allowing to customize annotations for that dashboard, as is with all the other dashboards.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by maorfr — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by sjentzsch** [comment]
@maorfr Would you mind adding your LGTM? This Chart version conflict is quite annoying :-(

**Pull request merged**
