### PR TITLE
[stable/kube-ops-view] Upgraded to 0.11.

### PR DESCRIPTION
**Pull request by jpds**
#### What this PR does / why we need it:

New release.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped

### CODE REVIEW

**Comment by hjacobs** [comment]
@jpds thanks, LGTM

**Comment by hjacobs** [comment]
I'm not using Helm myself, but apparently RBAC is something to address: https://github.com/hjacobs/kube-ops-view/issues/225

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Pull request merged**
