### PR TITLE
[stable/kibana] add tests

### PR DESCRIPTION
**Pull request by s12chung**
#### What this PR does / why we need it:
Add basic tests to stable/kibana.

#### Which issue this PR fixes
No issue, adds new test.

#### Special notes for your reviewer:
- used `dwdraju/alpine-curl-jq` to test because I need curl, jq, and bash to accurately test, let me know if there's a better idea to test.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by s12chung** [comment]
fixed the test. missed this values file earlier: https://github.com/helm/charts/blob/7a10da0db524d0164e33998a671a4574e28d39d6/stable/kibana/ci/service-values.yaml#L2-L4

**Comment by compleatang** [comment]
@s12chung FYI you'll need to do a quick rebase after #12200 gets merged (I've marked it LGTM so it should merge shortly).

**Comment by s12chung** [comment]
something changed such that I can't connect to `"http://{{ template "kibana.fullname" . }}{{ if $port }}:{{ $port }}{{ end }}/api{{ .Values.livenessProbe.path }}"` now. investigating why. will get back after I sleep.

**Comment by compleatang** [comment]
@s12chung check out PR #12200 and the last commit there....

**Comment by s12chung** [comment]
see my latest commit, i don't completely understand this comment in #12200 : https://github.com/helm/charts/pull/12200/files/8679348e26e17528143ba7ff05bef8587432d764#diff-761d187d0b4be7a6e7099800525bcb80

**Comment by compleatang** [comment]
@s12chung i'm not 100% sure which comment you're referring to as the link doesn't resolve well. but in any event thanks for this! 

/lgtm

**Comment by pjanuario** [comment]
@s12chung and @compleatang This PR reverted the changes made at https://github.com/helm/charts/pull/12200 was this expected? Since previous PR was solving a problem when trying to override `kibana.yml` since `elasticsearch.url` is not valid anymore and `elasticsearch.hosts` needs to be used, and since there is a bug on helm, there was no way to bypass this.

**Comment by s12chung** [comment]
wasn't fully knowledge of the bug, as you can see my comment. do you know why ci might fail because of the changes?

**Comment by pjanuario** [comment]
@s12chung can help on that, I just noticed this because I am starting some new installation and using ELK 7 stack, so I stumbled on those problems.

**Pull request merged**
