### PR TITLE
[incubator/cassandra-k8s-operator] Add charts for the Orange's Cassandra Kubernetes operator

### PR DESCRIPTION
**Pull request by allamand**
Signed-off-by: sebastien allamand <sebastien.allamand@orange.com>

#### What this PR does / why we need it:

This PR adds a new chart for [cassandra-k8s-operator](https://github.com/Orange-OpenSource/cassandra-k8s-operator) a Cassandra Kubernetes operator (CassKop).

This will ease the management of Cassandra cluster in Kubernetes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
hey @allamand,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by allamand** [comment]
Hello @maorfr, actually I have nowhere to store the chart, so I thought it was better to add it in the helm/charts repository.

**Comment by allamand** [comment]
@maorfr, can we run e2e tests on this, is it ok for you ?

**Comment by allamand** [comment]
I can take a look at github page, but I already use github pages for documentation sharing in the project. It seems to be at this time that it would be more useful in the charts repository but I'm open mind :)

Regarding the tests, they are failing because the CRD is missing when testing the chart.

In fact, I don't create the CRD in the helm willingly to avoid garbage collector of the CRD when deleting the chart. Any suggestion on how I should be doing that?

thanks for help

**Comment by allamand** [comment]
@maorfr I think It's Ready to merge. I would like to merge it in incubator/charts, and I will work in future to have the charts on our own repo.

Is that ok for you ?

**Comment by prydonius** [comment]
> I would like to merge it in incubator/charts, and I will work in future to have the charts on our own repo.

I think that's fine for now. Just bear in mind that in the future we want to move towards a more distributed model, so folks will run their own chart repositories and add them to the Helm Hub (https://hub.helm.sh).

/lgtm

**Pull request merged**
