### PR TITLE
a typo in network

### PR DESCRIPTION
**Pull request by janitha09**
netwok to network

Signed-off-by: janitha09 <janitha_j@example.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by cpanato** [comment]
@janitha09 can you please bump the chart version and sign the DCO ? thanks for this PR!

**Comment by PierluigiLenociAkelius** [comment]
This change is also included in this PR: https://github.com/helm/charts/pull/16606

**Comment by PierluigiLenociAkelius** [comment]
@janitha09 could you please close your PR? Now is outdated by this https://github.com/helm/charts/pull/16654

**Pull request closed without merging**
