### PR TITLE
Update Cassandra chart name in example

### PR DESCRIPTION
**Pull request by yaron2**
Fix release name in chart install example

### CODE REVIEW

**Comment by zanhsieh** [comment]
@yaron2 
Would you mind to sign DCO and bump chart to latest version? Thank you.

**Comment by davidkarlsen** [comment]
@yaron2 please sign off your commits and bump the chart version

**Comment by cscetbon** [comment]
@yaron2, you tried to assign it to me ?

**Comment by yaron2** [comment]
> @yaron2
> Would you mind to sign DCO and bump chart to latest version? Thank you.

done

**Comment by yaron2** [comment]
dco-labeler still says 2 commits are missing signoff, but I've signed them off with:

```
git commit --amend -s -c 9effec42cc6c83350a6e07272c09b70f2d9f6caa
git commit --amend -s -c 10f524c214ee8c36bfd767d03439f81b65ff0b2c
git push
```

**Pull request closed without merging**
