### PR TITLE
[stable/sentry] Add note about Sentry ownership

### PR DESCRIPTION
**Pull request by BYK**
This PR adds a note to the readme stating that the chart is not maintained or backed by Sentry org itself.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by BYK** [comment]
Hi @okgolove! We at Sentry repo keep getting issues and questions regarding this Helm chart which we don't maintain. We may decide to join here some time in the future but our current focus is elsewhere so wanted to add a note regarding this.

I'm okay changing the wording however you prefer as long as it conveys this fact. I'm also okay having a dedicated forum topic at Sentry if people want to discuss about this chart.

**Comment by okgolove** [comment]
Hi @BYK! No problem. 
You should bump the chart version.

**Comment by BYK** [comment]
@okgolove - done! I'm also happy to chat around how we can stay in sync at least. We have a more basic setup we support for self-hosted at https://github.com/getsentry/onpremise and I'm okay chatting over IRC if you use that.

**Comment by okgolove** [comment]
@BYK I do. I will join the channel. You can find me using the same nickname.

**Review by okgolove — APPROVED** [review]

**Pull request merged**
