### PR TITLE
[stable/*] Proposal: Switch test image to "bats/bats"

### LINKED ISSUE #19155: End of Life for image "dduportal/bats:0.4.0" + Next Steps
**Is your feature request related to a problem? Please describe.**

Hi there! I discovered a few days ago that my personnal Docker image `dduportal/bats` is used in the Helm cart, while trying to delete the tag `0.4.0`.
2 days ago, someone opened an issue on my github repo about this image tagged as vulnerable: https://github.com/dduportal-dockerfiles/bats/issues/10, which is true as this is only a simple side project for me + there are more recent tags.

I would like to define with the project what would be the next steps as I could have had a negative impact on this project, without being aware of it. It is an operational risk for the Helm Charts on different level, and even if I'm happy to provide a useful tool, there should be an upgrade to make helm chart distribution/auhtoring safer and trustable.
What if someone steal my Docker Hub credentials or Github credentials and inject bad code in this image? 

**Describe the solution you'd like**

- Switch out from my image to a `helm/bats` image, built from a trustable github / DockerHub, or maybe https://hub.docker.com/r/bats/bats ?
  - Trustable Delivery Chain is a plus
  - No dependency on a single person :)
- Adapt the content of the image to have up-to-date dependencies, and maybe a smaller OS to limit the maintenance and attack vectore
  - Already done on my personal image with the tags `v1.1.0` (switched to Alpine), even though it introduces changes and other dependencies (`bats-asserts` libraries for instance)

**Describe alternatives you've considered**

I.D.K.

**Additional context**

Happy to help on the implementation, but such a discussion should happen publicly here as a community right?

If you feel anything I said is wrong, not well formulated, not understandable, not well said, I aplogie in advance, and please feel free to correct me or tell me!

By the way: thanks a lot for all this awesome work people!

### PR DESCRIPTION
**Pull request by dduportal**
Signed-off-by: dduportal <1522731+dduportal@users.noreply.github.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

This PR changes the image of the "test containers" to the official `bats/bats:v1.1.0`,
as `dduportal/bats:0.4.0` is a liability (see #19155 for explanations).

IMPORTANT: Please note that the base image changed from `debian:jessie` to `alpine:3.8`.

#### Which issue this PR fixes

  - Use a "schema2" docker image which allows to use digests for identifying the content (no more `Image docker.io/dduportal/bats:0.4.0 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/` message).
  - Image size improvement.
  - No more security alerts from outdated Debian packages.
  - fixes #19155 .

#### Special notes for your reviewer:

This PR is a proposal, as it does not completely fixes the root cause of the liability (e.g. depending on someone's else image), but it triggers the discussion.

Happy to help forging an image dedicated for this, owned by the CNCF or Helm project.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- ~[ ] Chart Version bumped~ (N.A.)
- ~[ ] Variables are documented in the README.md~(N.A.)
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by carrodher** [comment]
CI will fail because you need to split the changes individually per chart to be tested properly

**Comment by dduportal** [comment]
@carrodher ok, good to know. I would want to check if doing this change if ok, as the time required to open all the PRs should be worth it :)

My goal is to decommission this image as soon as possible as it is a liability, and I want to help as much to avoid breaking stuff. But I'm not really keen on spending hours, given the potential amount of "go / nogo" from the different chart authors here, so I really want to be sure I'm heading forward on the right direction.

Thanks for the feedback!

**Comment by carrodher** [comment]
I was reading the issue right now, thanks for this effort and for taking care of the security in all these charts.
I agree with the changes, but I will ping other core members.
cc @mattfarina @cpanato @unguiculus

**Comment by dduportal** [comment]
> I was reading the issue right now, thanks for this effort and for taking care of the security in all these charts.
> I agree with the changes, but I will ping other core members.
> cc @mattfarina @cpanato @unguiculus

Cool, thanks for the fast answers! I'll wait for a "global" confirmation, before working on subsequent PRs for each then :+1: .

**Comment by cpanato** [comment]
@dduportal agree as well, please open Pr for each one

**Comment by cpanato** [comment]
will close this one

**Pull request closed without merging**
