### PR TITLE
WIP [stable/etcd-operator] upgrade to v0.9.0

### PR DESCRIPTION
**Pull request by khrisrichardson**
Upgrade `etcd-operator` from `v0.7.0` to `v0.8.0`, which among other things allows one to specify etcd endpoints for the `etcd-backup-operator` instead of cluster name, enabling backup of clusters that were not spawned by the `etcd-operator`. It is also possible to specify etcd client TLS certs.

There were some accompanying spec changes in the transition to `v0.8.0`, and so the minor version of the chart was bumped accordingly.

This PR also fixes a couple typos and incorporates values that were mentioned in the `README.md` and `values.yaml` files but not actually used in any templates.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
thanks so much for contributing! will look at this asap and will try to get back this week.

**Comment by khrisrichardson** [comment]
I am considering working on this a little more to allow IAM roles instead of access keys. It doesn't seem possible with v0.8.0, so I'm open to postponing those changes until a PR is merged to coreos/etcd-operator that permits `awsSecret` to be null.

**Comment by alejandroEsc** [comment]
@khrisrichardson alright, sounds good to me.

**Pull request closed without merging**
