### PR TITLE
[incubator/fluentd-cloudwatch] Added busybox repo parameters

### PR DESCRIPTION
**Pull request by maartenszeker**
#### What this PR does / why we need it:
Added support for specifying the source repository and tag of the busybox image.
In our project we need to point to a different repo for busybox.

#### Special notes for your reviewer:
This pull request would fix our problems upstream for the use of this chart.
@jmcarp @icereval 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by brunocous** [comment]
This would also be helpful for me. This PR is similar to #15235, but add a tag parameter as well.

**Comment by joan-serra** [comment]
I think yours looks better. Will close mine and upvote that

**Comment by maartenszeker** [comment]
@mattfarina

**Pull request merged**
