### PR TITLE
[stable/prometheus] fix k8s version check for enableServiceLinks

### LINKED ISSUE #23674: [stable/prometheus] cannot set server.enableServiceLinks using helm@3
**Describe the bug**

Setting `server.enableServiceLinks` yields no result.

**Version of Helm and Kubernetes**:

```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Which chart**:

[stable/prometheus](https://github.com/helm/charts/tree/master/stable/prometheus)

**What happened**:

I am running into https://github.com/prometheus/prometheus/issues/7286 and need to set `server.enableServiceLinks=false`. It seems the field used to check k8s version [here](https://github.com/helm/charts/blob/3d91ea795fb452c7a0dcd6b1e2a9e4b2a13fd765/stable/prometheus/templates/statefulsets/server.yaml#L42-L48) (`.Capabilities.KubeVersion.GitVersion`) was removed in helm@3.

The equivalent field in helm@3 is `.Capabilities.KubeVersion.Version`.

**What you expected to happen**:

`enableServiceLinks` should be rendered in deployment / stateful set

**How to reproduce it** (as minimally and precisely as possible):

```
helm template stable/prometheus --set server.enableServiceLinks=false | grep enableServiceLinks
```

**Anything else we need to know**:

- https://github.com/helm/charts/pull/23299
- https://helm.sh/docs/chart_template_guide/builtin_objects/
- https://v2.helm.sh/docs/chart_template_guide/#built-in-objects

### PR DESCRIPTION
**Pull request by bfmiv**
#### Is this a new chart
No

#### What this PR does / why we need it:
Fixes a bug in `stable/prometheus`.

#### Which issue this PR fixes
  - fixes https://github.com/helm/charts/issues/23674

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bfmiv** [comment]
I have verified this locally

```
# Default (deployment)
helm template ./stable/prometheus | grep enableServiceLinks
      enableServiceLinks: true

# Set enableServiceLinks (deployment)
helm template ./stable/prometheus --set server.enableServiceLinks=false | grep enableServiceLinks
      enableServiceLinks: false

# Default (statefulSet)
helm template ./stable/prometheus --set server.statefulSet.enabled=true | grep enableServiceLinks
      enableServiceLinks: true

# Set enableServiceLinks (statefulSet)
helm template ./stable/prometheus --set server.statefulSet.enabled=true --set server.enableServiceLinks=false | grep enableServiceLinks
      enableServiceLinks: false
```

**Review by zanhsieh — APPROVED** [review]

**Comment by Xtigyro** [comment]
@bfmiv
`I0904 14:05:19.973] Error: render error in "prometheus/templates/deployments/server.yaml": template: prometheus/templates/deployments/server.yaml:42:7: executing "prometheus/templates/deployments/server.yaml" at <semverCompare ">=1.13-0" (include "prometheus.capabilities.kubeVersion" $)>: error calling semverCompare: Invalid Semantic Version`

**Comment by scottrigby** [comment]
This chart has been DEPRECATED and moved to https://github.com/prometheus-community/helm-charts. If still applicable, please re-open your PR there. Thanks!

**Pull request closed without merging**
