### PR TITLE
[stable/sentry] Update sentry's readme to talk about the new chart

### PR DESCRIPTION
**Pull request by Mokto**
#### Is this a new chart
No

#### What this PR does / why we need it:
Explain migration to the new Sentry, and supports Sentry 10

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by okgolove** [comment]
Hi @Mokto.
I wasn't able to find any information about _official repository_.

**Comment by Mokto** [comment]
You're right! To be honest I copied that part from another chart that I don't think is official too.

But I'll change it ;)

**Comment by Mokto** [comment]
@okgolove Done.

**Comment by okgolove** [comment]
Could you bump helm charts' version? CI job fails because it wasn't bumped.

**Pull request merged**
