### PR TITLE
[stable/spinnaker] Avoid IP infringement in default config

### PR DESCRIPTION
**Pull request by coderanger**
Even though the value isn't used, might as well not leave it in.

### CODE REVIEW

**Comment by paulczar** [comment]
Can you prefix the PR with [stable/spinnaker] and bump the chart version in Chart.yaml ?

also sign the CLA :)

**Comment by coderanger** [comment]
Heh, it seems like the bot only realized my CLA was signed after you commented? Other bits should be done.

**Review by paulczar — APPROVED** [review]
LGTM

**Pull request merged**
