### PR TITLE
 stable/memcached: Add support for metrics

### PR DESCRIPTION
**Pull request by olemarkus**
**What this PR does / why we need it**:
This pull request adds memcached_exporter as a sidecar container to the memcached pod.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by whereisaaron** [comment]
Hi @olemarkus @paulczar @mattfarina, I already previously proposed PR #6760 that adds the options for `memcached` Prometheus exporter as well as adding many more configurable `memcached` options. It also make the metrics exporter port and path configurable, and provides a headless Service for the metrics port Pod discovery.

@olemarkus would mind reviewing my PR #6760 to see if there is anything in your PR that I missed in my previous one? As I think the previous PR may be a strict superset of this one.

**Comment by mattfarina** [comment]
@olemarkus @gtaylor Can you take a look at this previous comment?

@olemarkus since you're in the owners file for this chart you can approve this yourself.

**Comment by olemarkus** [comment]
Yeah I already saw the comment/PR, but I haven't had tu3cPin copied text snippets to stop them expiring after haven't had the chance to comment yet.

**Pull request merged**
