### PR TITLE
fix deprecated setting in README.md

### PR DESCRIPTION
**Pull request by junkiebev**
`cidr` should read `addresses` on line 104

#### Which issue this PR fixes
  - Incorrect value in readme.md 

#### Special notes for your reviewer:
 
Non-breaking change to chart documentation.

### CODE REVIEW

**Comment by cpanato** [comment]
@junkiebev you need to bump the patch chart version

**Comment by junkiebev** [comment]
> @junkiebev you need to bump the patch chart version

Even though it is just a fix to an incorrect README.md line?

**Comment by junkiebev** [comment]
@cpanato - To clarify, following the readme in the current chart version doesn't result in a working config. Older versions of the image used a config setting key called `cidr` and the image used for the (non-incremented) version of the helm chart in question takes that value under a key called `addresses`.

**Comment by cpanato** [comment]
@junkiebev yes, you need to bump the chart version, otherwise will never pass on CI

**Pull request merged**
