### PR TITLE
[stable/prometheus] allow non-yaml objects for configmap values

### PR DESCRIPTION
**Pull request by premkumar-gg**
#### Is this a new chart
No

#### What this PR does / why we need it:
Fixes the bug quoted here: [https://github.com/helm/charts/pull/18112#issuecomment-550349123](https://github.com/helm/charts/pull/18112#issuecomment-550349123)

#### Special notes for your reviewer:
- Introduce feature allowing multiple alerts files
- Fix the bug introduced in #18112 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
This is still not backwards compatible. It removes these from our configmap:

```
    anchore-pass: |
-     xxxxxxx

    prometheus.yml: |
      global:
        evaluation_interval: 20s
        scrape_interval: 20s
        scrape_timeout: 20s
-     rule_files:
-     - /etc/config/rules
-     - /etc/config/alerts
-     scrape_configs:
-     - job_name: prometheus
-       static_configs:
-       - labels:
-           env: xxxx
-      ...
```

**Comment by premkumar-gg** [comment]
I've been always wrong @max-rocket-internet .. thanks for pointing it out. Now updated. Does it look okay now? I've tested with a similar set up as yours.. lgtm.. Let me know.

**Comment by max-rocket-internet** [comment]
Hey @premkumar-gg 

Now just one small problem is that the indentation is change for same data:

```
    anchore-pass: |
-     xxx
-
+       xxx
...
```

**Comment by premkumar-gg** [comment]
Please check now @max-rocket-internet ... Done some thorough testing with different values..

**Review by max-rocket-internet — APPROVED** [review]
Awesome! Thanks very much for the effort 💚

**Comment by max-rocket-internet** [comment]
Thanks again. Really looking forward to splitting our 2000 lines of alert YAML into separate files 😅

**Comment by premkumar-gg** [comment]
Thank you for the help!

**Comment by max-rocket-internet** [comment]
/assign @gianrubio

Any update on this?

**Comment by gboor** [comment]
I ran into this issue yesterday as described in #18942 - can we get this merged?

**Comment by premkumar-gg** [comment]
cc @maorfr .. can you take a look please..

**Comment by max-rocket-internet** [comment]
Or one of @mgoodness @gianrubio from chart owners file.

**Comment by premkumar-gg** [comment]
Any attention on this please..?

**Comment by max-rocket-internet** [comment]
@davidkarlsen @maorfr @paulczar please  😃

**Comment by schndr** [comment]
@davidkarlsen @maorfr @paulczar please 😃

**Comment by OliverKlette85** [comment]
@davidkarlsen @maorfr @paulczar please 😃

**Pull request merged**
