### PR TITLE
Fix typo in docker-registry/README.md

### PR DESCRIPTION
**Pull request by ko**
**What this PR does / why we need it**:

There appears to be a typo in the README.md.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rjkernick** [comment]
Please sign the CLA and update the version in chart.yaml

**Comment by ko** [comment]
CLA has been signed with the associated email address. Also rebased to update Chart.yaml.

**Pull request merged**
