### PR TITLE
Add a note about the default state of the API

### PR DESCRIPTION
**Pull request by apenney**
Tiny PR to add a note to the README.

### CODE REVIEW

**Comment by jdolitsky** [comment]
@apenney please bump the version in Chart.yaml from 0.3.6 to 0.3.7

**Comment by krancour** [comment]
@jdolitsky got it.

From the PR:

> This protects against unauthorized access to the API with default configuration values.

Knowing now that the default is based on a more-secure-by-default approach, the decision makes sense. Thanks.

Big +1 from me on putting this detail in bold!

/close

**Comment by jdolitsky** [comment]
@krancour think you put the comment on wrong github issue :)

**Comment by krancour** [comment]
@jdolitsky d'oh! I am so sorry about that!

**Comment by jdolitsky** [comment]
no worries!

@apenney we will need this to bump to 0.4.1 now

**Comment by tristanpemble** [comment]
It took me a while to figure out how to turn this on since the `env` configuration block is not documented here. It might be good to include an example of the `env: { open: { DISABLE_API: false } }`  configuration required (and also explain that this is how you can setup the Chartmuseum application's other configuration)

**Comment by jdolitsky** [comment]
yep lets add a quick not about that too.
@apenney this will need to be rebased and made chart version 0.4.2 now
thanks everyone!

**Comment by jdolitsky** [comment]
wow thanks for last commit :+1:

**Pull request merged**
