### PR TITLE
drupal-0.4.2: bump `bitnami/drupal` image to version `8.2.6-r0`

### PR DESCRIPTION
**Pull request by dgomezleon**

### CODE REVIEW

**Comment by sameersbn** [comment]
tested, lgtm.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Review by chrislovecnm — CHANGES_REQUESTED** [review]
Thanks!

**Review by chrislovecnm — CHANGES_REQUESTED** [review]
We need a rebase

**Comment by sameersbn** [comment]
I think this PR should be closed in favour of #751

**Pull request closed without merging**
