### PR TITLE
[stable/postgresql] Use immutable tags

### PR DESCRIPTION
**Pull request by carrodher**
- Bump patch version
- Use immutable tags
- Check rolling tags in the images (except minideb and exporter) and show a warning in NOTES.txt
- Add a section about rolling/immutable tags in README.md

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by pevers** [comment]
Hi @carrodher ,

This failed my build because I use this yaml config:
```
tag: 10.5
```

Doing:
```
helm install --name dev-db -f $DIR/charts/dev-db.yaml \
	stable/postgresql
```

With: 
```
Error: render error in "postgresql/templates/NOTES.txt": template: postgresql/templates/NOTES.txt:45:94: executing "postgresql/templates/NOTES.txt" at <"-r\\d+$">: wrong type for value; expected string; got float64
```

Because tag was parsed as a number and not a string. I changed my install script to:

```
helm install --name dev-db -f $DIR/charts/dev-db.yaml \
	--set image.tag=10.5 \
	stable/postgresql
```

And removed the image.tag from the yaml to resolve this issue.

**Comment by desaintmartin** [comment]
Is it related to this PR? I think just doing:
```yaml
tag: "10.5"
```

would work.

**Comment by carrodher** [comment]
Hi @pevers @desaintmartin,

Using the following tag works fine, please note that there are 3 digits and no quotes:
```yaml
tag: 11.3.0
```
it shows the following warning from the _NOTES.txt_
```
WARNING: Rolling tag detected (bitnami/postgresql:11.3.0), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/
```
so the regex worked fine.

But using only 2 digits (also without quoting)
```yaml
tag: 11.3
```
it fails to render _NOTES.txt_
```
Error: render error in "postgresql/templates/NOTES.txt": template: postgresql/templates/NOTES.txt:45:94: executing "postgresql/templates/NOTES.txt" at <"-r\\d+$">: wrong type for value; expected string; got float64
```

It seems that 2 digits are considered float and 3+ digits string.

In the other hand, quoting the value, it works with 2 or 3 digits:
```yaml
tag: "11.3"
```
```yaml
tag: "11.3.0"
```
The same when the parameter is passed with `--set image.tag`, it is interpreted as a string.

The final solution is quoting the value before applying the regex, in this way it works every time
```diff
-{{- if and (contains "bitnami/" .Values.image.repository) (not (.Values.image.tag | regexFind "-r\\d+$")) }}
+{{- if and (contains "bitnami/" .Values.image.repository) (not (.Values.image.tag | quote | regexFind "-r\\d+$")) }}
```
showing the warning even using `tag: 11.3`
```
WARNING: Rolling tag detected (bitnami/postgresql:11.3), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/
```

I will send a PR fixing it, thanks for letting us know.

**Pull request merged**
