### PR TITLE
[stable/kibana] add scheme option to livenessProbe and readinessProbe

### PR DESCRIPTION
**Pull request by dkoshkin**
#### What this PR does / why we need it:
When setting:
```
files:
  kibana.yml:
    server.ssl.enabled: "true"
``` 
The `Liveness` and `Readiness` probes fail and need to set the `scheme` option to `HTTPS`.

#### Special notes for your reviewer:
CC @compleatang @monotek

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by monotek — CHANGES_REQUESTED** [review]
Could you add an ci test for this please?

**Comment by compleatang** [comment]
Agree with @monotek WRT having a test. Gonna trigger testing just cause I'm tied up next few days. Mono I thought you were capable of doing this...?

/ok-to-test

**Comment by monotek** [comment]
@compleatang 
"lgtm" works. "ok-to-test" not ¯\_(ツ)_/¯

**Comment by dkoshkin** [comment]
This is my first PR with CI tests and I don't really understand how any of the others tests are not failing:
```
I0403 16:01:42.966] {"type":"log","@timestamp":"2019-04-03T16:00:02Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```
Do I need to do something to launch ES?

**Comment by monotek** [comment]
I've talked about such test cases with @compleatang recently. We don't have a proper solution for things which have elastic search as dependency. 

We could add an requirement which is only enabled in the ci config.

**Comment by monotek** [comment]
Sorry for the delay. We're still in the discussion about proper testing in: https://github.com/helm/charts/issues/12628

**Comment by compleatang** [comment]
@dkoshkin sorry for the extreme delay here. Thanks for the contribution. Unfortunately we're going to close this issue for the reasons below.

In combination with the elastic team, we've decided to deprecate stable/kibana going forward in favor of elastic/kibana. You can see the tracking issue for the work here -> https://github.com/helm/charts/issues/14935

We are encouraging all open issues to contribute their work to the "new" community chart led by the elastic team here -> https://github.com/elastic/helm-charts/tree/master/kibana

If you have any questions please feel free to comment on #14935 

/close
/hold

**Pull request closed without merging**
