### PR TITLE
[stable/stolon] Postgres needs a value when disable ssl

### PR DESCRIPTION
**Pull request by jmvizcainoio**
#### What this PR does / why we need it:

When you deploy the stolon chart  using `helm upgrade --install` the hook `update-cluster-spec-job` will be executed setting ssl to a null values. Stolon will create the postgres.conf file setting `ssl = ''` and postgres can't boot because is mandatory define the value into the config `ssl = 'on|off'`

This commit set to `ssl = 'off'` when execute the helm update.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by merqurio** [comment]
Hi @lwolf, now that the OWNERS is merged, 
Can you help us to get this merged ? 

Thanks !

**Comment by lwolf** [comment]
@merqurio it seems that this PR is a duplicate to https://github.com/helm/charts/pull/18915

**Comment by jmvizcainoio** [comment]
Duplicated https://github.com/helm/charts/pull/18915

**Pull request closed without merging**
