### PR TITLE
Added airflow variables support

### PR DESCRIPTION
**Pull request by stijndehaes**
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>

#### What this PR does / why we need it:

This pr adds adds support to load in airflow variables.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by stijndehaes** [comment]
@gsemet I see you in the owners file as well as @maver1ck. There are 4 PR's open for airflow right now. Could you help review and approve these? I would be interested to help out in the future

**Comment by gsemet** [comment]
/lgtm

Sorry for delay, I wasn’t notified

**Comment by stijndehaes** [comment]
> /lgtm
> 
> Sorry for delay, I wasn’t notified

No problem, only @maver1ck was automically added as a reviewer but I noticed you in the owners file

**Comment by stijndehaes** [comment]
@gsemet I think you still need to issue: /ok-to-test

**Comment by gsemet** [comment]
@maver1ck can you approve ?

**Pull request merged**
