### PR TITLE
trim trailing whitespace

### PR DESCRIPTION
**Pull request by moeryomenko**
#### What this PR does / why we need it:

Trim trailing whitespace

#### Special notes for your reviewer:

this is not an important change, but why not)

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Thank you for you contribution @moeryomenko . Could you please sign the DCO?

**Comment by moeryomenko** [comment]
@ialidzhikov, I signed the DCO

**Comment by moeryomenko** [comment]
if somebody work in VSCode, can add to setting.json

```json
{
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true
}
```

**Comment by moeryomenko** [comment]
@mattfarina pls approve

**Pull request closed without merging**
