### PR TITLE
[stable/nginx-ingress] Add support for standalone flags via extraArgs (#2072)

### PR DESCRIPTION
**Pull request by mluedke**

### CODE REVIEW

**Comment by mluedke** [comment]
CLA signed

**Comment by mluedke** [comment]
CLA signed

**Comment by mluedke** [comment]
CLA signed

**Comment by mgoodness** [comment]
@mluedke thanks for the contribution! Just need you to sign the CLA.

**Comment by mluedke** [comment]
It looks like I accidentally included a mismatched email address in the git commit. Not sure if there's any way to correct this. Should I close this and re-submit the PR?

**Comment by scottrigby** [comment]
@mluedke Since this is only one commit in this PR, locally you can do:
1. `git commit --amend --author="Your Name <youremail@address.com>"`
2. `git push YOUR_FORK YOUR_BRANCH --force`

**Review by scottrigby — APPROVED** [review]
Code LGTM re https://github.com/kubernetes/ingress/tree/master/controllers/nginx#command-line-arguments

**Comment by mluedke** [comment]
Thanks @scottrigby. All fixed.

**Comment by prydonius** [comment]
this needed a version bump, I bumped it to 0.8.5

/lgtm

**Pull request merged**
