### PR TITLE
[stable/mariadb] inject `mariadb-replication-password` from secret on…

### PR DESCRIPTION
**Pull request by bitfisher**
`mariadb-replication-password` in `master`-Statefulset should only be used if replication is enabled

### CODE REVIEW

**Comment by alemorcuq** [comment]
Hi, @bitfisher. Thanks for the PR!. Could you please increase the chart version?

**Comment by alemorcuq** [comment]
Thanks! Remember to sign the DCO so all checks are successful.

**Comment by alemorcuq** [comment]
Thanks! This is ready to be merged, @carrodher.

**Comment by alemorcuq** [comment]
As #19548 was merged, this needs another bump to the chart version, @bitfisher. Thanks!

**Comment by alemorcuq** [comment]
@bitfisher don't forget to sign the DCO!

**Comment by carrodher** [comment]
According to the [failing CI test](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/19500/pull-charts-e2e/1216379910654791680/) the chart version not ok, can you bump it?

**Comment by bitfisher** [comment]
@carrodher Bumped version and CI test is now ok!

**Pull request merged**
