### PR TITLE
New helm chart for h2non/imaginary

### PR DESCRIPTION
**Pull request by dragonsmith**
**What this PR does / why we need it**:

It brings a new Helm chart for [h2non/imaginary](https://github.com/h2non/imaginary/)

**Comments for a reviewer:**

The linting failure is because of the icon absence. I do not know how to address that as I have not found any official logo or an icon for "imaginary" app.

### CODE REVIEW

**Comment by dragonsmith** [comment]
The failure above is because of the icon absence. I do not know how to address that as I did not find any official logo or an icon for "imaginary" app.

**Comment by dragonsmith** [comment]
@scottrigby @prydonius

Sorry to bother you, please, can you look at this PR too? I'm pretty much sure it meets requirements now.

Thank you very much!

**Comment by dragonsmith** [comment]
@mattfarina 
Hello! Please, can you look into this PR? It was marked as "stale" already.

Thank you very much in advance!

**Comment by phroggyy** [comment]
Could we get this reopened and looked at?

**Pull request closed without merging**
