### PR TITLE
[stable/chart] prometheus-operator: Make namespace info explicit

### PR DESCRIPTION
**Pull request by surajssd**
For all the configs that have missing namespace information, this commit
adds following line to metadata of those namespaced objects.

```
namespace: {{ .Release.Namespace }}
```

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x]  title of the PR contains starts with chart name e.g. [stable/chart]

### CODE REVIEW

**Comment by vsliouniaev** [comment]
The namespace to install the chart into is specified by the helm `--namespace argument`. What's the benefit of adding these?

**Comment by surajssd** [comment]
> The namespace to install the chart into is specified by the helm --namespace argument. What's the benefit of adding these?

That's right. This value is placed by helm cli/tiller, somewhere. But this behavior is inconsistent with the helm rendering libraries. So if you go ahead and use libraries to parse certain charts which has no parameterizing like above they won't have namespace field in it.

Following is run in the prometheus dir that is downloaded from stable. In kubectl the default namespace is `default`.

```bash
$ helm fetch \
    --repo https://kubernetes-charts.storage.googleapis.com \
    --untar \
    --untardir ./ \
    prometheus-operator

$ helm template --namespace monitoring . | kubectl apply -f -
podsecuritypolicy.extensions/release-name-grafana created
podsecuritypolicy.extensions/release-name-kube-state-metrics created
podsecuritypolicy.extensions/release-name-prometheus-node-exporter created
...
servicemonitor.monitoring.coreos.com/release-name-prometheus-op-operator created
servicemonitor.monitoring.coreos.com/release-name-prometheus-op-prometheus created
Error from server (NotFound): namespaces "monitoring" not found
Error from server (NotFound): namespaces "monitoring" not found
```

Above in `template` sub-command I expect that the namespace I am giving is placed under the `namespace` field in `metadata` of each object. But it only replaces `{{ .Release.Namespace }}`.

The last two errors are because it is looking for namespace monitoring which does not exists. Even if it is present this means that half of the things will be created in `monitoring` namespace and other half in the default namespace.


```console
$ kubectl get pods
NAME                                                   READY   STATUS                  RESTARTS   AGE
release-name-grafana-5759d4d766-rwk88                  0/2     Init:CrashLoopBackOff   5          3m45s
release-name-grafana-test                              0/1     Error                   0          3m46s
release-name-kube-state-metrics-856fbc6f6-nq69k        1/1     Running                 0          3m45s
release-name-prometheus-op-operator-7fc4955ddd-zhqbv   0/1     CrashLoopBackOff        5          3m45s
```

Above does not deploy very well.


You might argue that this should be fixed in upstream helm tool. But prometheus operator uses this way of fixating namespace in some places.

e.g.: https://github.com/helm/charts/blob/3840c5edae9530a659007b2c38882b1b0355db68/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L4-L7

IMHO being explicit is no harm.

**Comment by surajssd** [comment]
@vsliouniaev updated this PR as well!

**Comment by vsliouniaev** [comment]
@surajssd, in order for this to work with all the resources provisioned by the chart, you would also have to do this for charts listed in the [requirements.yaml](https://github.com/helm/charts/blob/master/stable/prometheus-operator/requirements.yaml) kube-state-metrics and prometheus-node-exporter don't have the namespace made explicit. There's a pull request open for Grafana here, that hasn't gotten much traction: https://github.com/helm/charts/pull/14325. I think these charts would have to accept this change first before prometheus-operator can incorporate it.

If you want to install the chart into a specific namespace using rendered templates, you can accomplish this by setting the correct namespace on the kubectl context. If you want to create templates with the namespace already populated, I think you can achieve this with some creative use of the `yq` tool.

**Pull request closed without merging**
