### PR TITLE
[stable/redis-ha] Add resource limits to sysctlImage

### PR DESCRIPTION
**Pull request by bviolier**
#### Reviewers
@ssalaues & @dandydeveloper

#### Is this a new chart
No

#### What this PR does / why we need it:
Our Kubernetes clusters are restricted to not run anything without resource limits set. This adds the resource option to the sysctlImage.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@bviolier Can you bump the version please?

**Comment by ssalaues** [comment]
@bviolier There are many PRs getting merged currently. This PR will need to be rebased and the version will need to be bumped again.

**Comment by bviolier** [comment]
Branch is updated and bumped the version again!

**Pull request merged**
