### PR TITLE
[stable/grafana] Set plugins as a list

### PR DESCRIPTION
**Pull request by lostick**
The way we currently set plugins as a comma separated list makes it impracticable to extend.
Having them as a list is more convenient.

### CODE REVIEW

**Comment by lostick** [comment]
CLA signed

**Comment by cpanato** [comment]
@lostick please sign the DCO - https://www.helm.sh/blog/helm-dco/index.html

**Comment by lostick** [comment]
@cpanato sure thing

**Comment by lostick** [comment]
@unguiculus this is fine to be merged

**Pull request merged**
