### PR TITLE
[stable/jenkins] various

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:

- Update of the default jnlp slave image as the current default is quite old. 
- Update of default netpol api version as vast majority of users are using k8s version >= 1.7
- Update default jenkins plugins 
- ~~Chart version to 1.0.0 as it is in stable repo~~

#### Which issue this PR fixes
n/a
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
CC @lachie83 @viglesiasce

**Comment by maorfr** [comment]
Hey @naseemkullah,

I'd like to get this PR merged.
Can you resolve conflicts?
And please return the version to be in the `0.*`, i'll leave that to one of the core maintainers to bump.

thanks!

**Comment by naseemkullah** [comment]
All done @maorfr, please have a look. Thanks!

**Pull request merged**
