### PR TITLE
adding Cachet chart

### PR DESCRIPTION
**Pull request by lilithmooncohen**
Adding a chart for [Cachet](https://github.com/CachetHQ/Cachet), an opensource status page engine.

### CODE REVIEW

**Comment by unguiculus** [comment]
Please keep passwords auto-generated by default instead of  hard-coding concrete ones.

**Comment by jacobtomlinson** [comment]
This is exactly what I'm looking for. How can this PR be progressed?

**Comment by unguiculus** [comment]
@ryanckoch Are you still interrested in this? Otherwise, @jacobtomlinson feel free to pick it up.

**Comment by lilithmooncohen** [comment]
Oh yes... I totally forgot about this. My bad. I will try and get this resolved this evening.

**Comment by stevencarpenter** [comment]
@ryanckoch Just stumbled on this and would love to use it. Any chance you could take a quick look?

**Comment by ryanckoch** [comment]
@unguiculus Have any suggestion for how to accomplish it since the default values file is not templateable? I can allow for random values on the postgres password portion, but the cachet config wont end up with the same password and in turn not work.

**Comment by jacobtomlinson** [comment]
Is there anything I can do to get some more progress on this?

**Comment by ASCIIDuck** [comment]
I sounds like what needs to happen to progress this is to replace the hard coded passwords with something that is randomly generated. I'm not sure if the caveat here about "Be careful with generating random values" https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md would prevent this from being accepted. Looking at some helm charts that are present in stable, it seems like many just have credentials commented out.

**Comment by ryanckoch** [comment]
The only real way I see around it is to leave unset and require the user to set it. Would that be an issue as it breaks the model of being runable without end user changes?

**Comment by jacobtomlinson** [comment]
@unguiculus I agree that having hard coded database passwords are not ideal. However there are many charts in stable which do it out of necessity ([here](https://github.com/helm/charts/blob/master/stable/gitlab-ce/values.yaml#L101), [here](https://github.com/helm/charts/blob/master/stable/luigi/values.yaml#L82), [here](https://github.com/helm/charts/blob/master/stable/artifactory/values.yaml#L195)). It's a shame to block this for this reason.

@ryanckoch perhaps instead of defaulting it to a random password it should default to something like `cachet` to be in line with other charts. Or set it to no password at all like in the artifactory or sentry charts.

**Comment by unguiculus** [comment]
@jacobtomlinson I'm aware there are still some charts that set default password. This doesn't mean we should blindly follow this practice.

@ryanckoch You could auto-generate passwords or just leave them empty. You may conditionally install resources only if the password is set and add a warning to NOTES.txt. Provide passwords for CI only so the chart can be tested.
See https://github.com/helm/charts/blob/master/test/README.md#providing-custom-test-values

**Comment by ko5tas** [comment]
hey @lilithmooncohen did you end up creating the helm chart?

**Pull request closed without merging**
