### PR TITLE
[stable/nats] Fix ValidationError: unknown field "serviceName"

### PR DESCRIPTION
**Pull request by guessi**
#### Which issue this PR fixes
- Incorrect `deployment.spec`, introduced by #13537

#### Special notes for your reviewer:
- N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks for the fix @guessi

**Comment by juan131** [comment]
Hi @guessi 

Could you rebase from master and bump the version of the Chart.yaml again? It seems there was a patch release since you created the PR

**Comment by guessi** [comment]
@juan131 rebase & fixed

**Pull request merged**
