### PR TITLE
[stable/prometheus-node-exporter] Version bump to 1.0.1

### PR DESCRIPTION
**Pull request by mrueg**
#### What this PR does / why we need it:
https://github.com/prometheus/node_exporter/releases/tag/v1.0.1

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by vsliouniaev** [comment]
I can't affect CI but maybe we can bypass the problem. Try adding a ci override file like `stable/prometheus-node-exporter/ci/change-port.yaml`

```
service:
  targetPort: 9102
  port: 9102
```

**Comment by mrueg** [comment]
@vsliouniaev tried it unfortunately doesn't solve the issue :/

**Comment by vsliouniaev** [comment]
Looks like the ci files need to be named `*-values.yaml`. Take a look at this here: https://github.com/helm/charts/pull/23193

**Comment by mrueg** [comment]
Thanks @vsliouniaev , giving it a try!

**Pull request merged**
