### PR TITLE
Fix typo in prometheus readme

### PR DESCRIPTION
**Pull request by tmc**

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@tmc can you sign the linux foundation CLA by clicking the details link

**Comment by tmc** [comment]
yeah just went through that -- do I need to say something to re-trigger?

**Comment by tmc** [comment]
there it goes.

**Comment by viglesiasce** [comment]
We are working through the false positives of CI in another PR. This LGTM.

**Comment by prydonius** [comment]
LGTM. @viglesiasce I'm wondering if README changes require a bump in Chart.yaml (since the README is packaged in the chart?). Will the CI re-publish the current version?

**Comment by viglesiasce** [comment]
I am thinking that for README only fixes we dont bump the version of the chart. Its not a functional change to anything so its not worth burning version numbers and have people confused that they dont see a change. I could be convinced otherwise but just feel its a bit heavy handed. The chart will in fact be republished with the merge. I'm not sure what happens if/when we start signing charts from this repo. Same question could be posed for NOTES.txt changes which due to templating I would be more inclined to bumping the version.

**Comment by prydonius** [comment]
@viglesiasce yeah I agree with you, NOTES.txt should solicit a bump, but READMEs shouldn't. Good point, signing will be an issue, in which case we may need to bump for READMEs (perhaps we can start using a SemVer tag or something).

@tmc can you rebase on top of the latest changes so the CI can test these changes?

**Comment by viglesiasce** [comment]
@prydonius I think CI runs off the merged branch. 

@k8s-bot ok to test

**Comment by prydonius** [comment]
Just realised it's just a README fix anyway :P

**Pull request merged**
