### PR TITLE
Update zookeeper dependency to latest chart

### PR DESCRIPTION
**Pull request by ekampf**
Allows more configuration to persistence layer and nodeSelector

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by lachie83** [comment]
Please bump the chart version

**Comment by ekampf** [comment]
@lachie83 forgot about that.  Done.

**Comment by unguiculus** [comment]
Regenerate the requirements.lock: `helm dep up`

**Comment by ekampf** [comment]
@unguiculus done

**Pull request merged**
