### PR TITLE
Update to latest release RELEASE.2018-04-27T23-33-52Z

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by nitisht** [comment]
I see the error 

```
I0320 05:26:35.032] [2018-03-20T05:24:06.04885325Z] [FATAL] Unable to create configuration directories. (mkdir /root/.minio/certs: read-only file system)
```

This means Minio container is not able to write its config directory -- has anything changed on the testing platform to make FS as `readonly`?

**Comment by unguiculus** [comment]
@nitisht As of Kubernetes 1.9.4, configmaps are mounted read-only.

**Comment by nitisht** [comment]
> @nitisht As of Kubernetes 1.9.4, configmaps are mounted read-only.

Thanks for the info @unguiculus

**Comment by unguiculus** [comment]
@nitisht See #4281.

**Comment by unguiculus** [comment]
@nitisht Can you update? #4281 has been merged.

**Comment by nitisht** [comment]
Updated/rebased the PR @unguiculus . It still fails, I think it is related to https://github.com/kubernetes/kubernetes/issues/61076

**Comment by nitisht** [comment]
@unguiculus I have removed the `configMap` support for now, as there are multiple reports of users not being able to run Minio helm chart - [e.g. [here](https://github.com/minio/minio/issues/5725)]. 

Users can use environment variables inside pods for specific configuration values for the time being. I can bring back the configMap support at a later time. Your thoughts?

**Pull request merged**
