### PR TITLE
[stable/unifi] add mongodb dep requirement

### PR DESCRIPTION
**Pull request by cpwc**
Signed-off-by: Wei Cheng <calvinpohwc@gmail.com>

#### What this PR does / why we need it:
Adding mongodb as part of the requirement to allow this chart to run without setting up an external mongodb resource. While still keeping existing functionality to define external mongodb resource.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpwc** [comment]
@billimek would love to get some eyes on this.

**Comment by billimek** [comment]
Hi @cpwc, this change results in the default behavior to move away from the built-in mongoDB to either an external mongoDB or a sub-chart (external) mongoDB, is this correct?  Is this what we want to do?

I wonder what the issue is with the (current) default built-in mongoDB?  Does it make sense to retain this default behavior and optionally allow for a sub-chart mongoDB, if desired?

**Comment by cpwc** [comment]
@billimek looks like I've missed out the part where unifi already have built-in mongodb packaged together. Should close this PR.

**Pull request closed without merging**
