### PR TITLE
Dex

### PR DESCRIPTION
**Pull request by arunshetty33**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
Please rebase to latest master. Please base the chart on the latest `_helpers.tpl` you get with `helm create` using Helm 2.8+.

**Comment by sstarcher** [comment]
@arunshetty33 will you be able to make these changes soon?  If not I can pickup where you left off as I'm in need of a Dex chart.

**Comment by timstoop** [comment]
@sstarcher Feel free to create a new PR and reference this one, as it seems dead.

**Comment by unguiculus** [comment]
Closing this in favor of #4580.

**Pull request closed without merging**
