### PR TITLE
[stable/nginx-ingress] Add an ability to provide custom nginx template and dhparam

### PR DESCRIPTION
**Pull request by s4nch3z**

### CODE REVIEW

**Comment by erickt** [comment]
@mgoodness: have you had a chance to look at this? Due to the breaking change in 1.8 that I go into detail in https://github.com/kubernetes/ingress-nginx/issues/1622, it would be really handy to override the nginx template in order to allow ELBs to offload TLS, at least until there's a proper solution from the ingress-nginx folks.

**Comment by unguiculus** [comment]
For consistency, you may want to create helper templates for the resources names.

**Comment by unguiculus** [comment]
And sorry for the delay. I'm picking this up now.

**Comment by unguiculus** [comment]
I figured custom template have already made it in. I'm closing this now. Again sorry for the delay. Please open a new PR for dhparam if you like. Thanks.

**Pull request closed without merging**
