### PR TITLE
[stable/sonarqube] Resolve duplicate plugin files causing start up failure

### PR DESCRIPTION
**Pull request by ankitwal**
copy-plugins script checks and removes duplicate files of same plugins before copying downloaded plugins from tmp directory

Signed-off-by: Ankit Wal <ankit.wal@gmail.com>
@rjkernick 

#### What this PR does / why we need it: 
For stable/sonarqube
If a newer version of an already existing plugin is added to values file, it is downloaded and copied into /opt/sonarqube/extensions/plugins/ , where it will cause the server to fail at start up with the error: 

> Web server startup failed: Found two versions of the same plugin \<PluginName\> ...

This can be caused by either updating a default plugin, or updating an existing plugin with persistence set to true, eg 
```yaml 
plugins:
  # install: []
  install:
    - https://binaries.sonarsource.com/Distribution/sonar-scm-git-plugin/sonar-scm-git-plugin-1.8.0.1574.jar
```

This PR adds logic in copy-plugins script to check and removes duplicate files of same plugins before copying downloaded plugins from tmp directory, as recommended here [https://docs.sonarqube.org/latest/setup/install-plugin/](https://docs.sonarqube.org/latest/setup/install-plugin/). 

> Put the downloaded jar in $SONARQUBE_HOME/extensions/plugins, removing any previous versions of the same plugins.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@ankitwal please update your branch with latest upstream

**Comment by ankitwal** [comment]
@cpanato Updated with the latest upstream master.

**Pull request merged**
