### PR TITLE
[stable/cluster-autoscaler] Add support for ServiceMonitor (prometheus operator)

### PR DESCRIPTION
**Pull request by fabriziofortino**
#### What this PR does / why we need it:

Add support for prometheus operator ServiceMonitor.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
Hey, @fabriziofortino, thanks for this! The prometheus-operator helm charts have been migrated from coreos/prometheus-operator into this repository, so the links you've got in the documentation here point to deprecated charts, would you mind updating them? https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Comment by fabriziofortino** [comment]
not stale

**Pull request merged**
