### PR TITLE
Drone ingress.path addon and fallback config

### LINKED ISSUE #12862: [stable/drone]: path selection is wonky
BUG? Arguably so. This ingress logic either needs to be extended with the config to provide a path ourselves, as it now failes for istio:

`if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb"`

**Which chart**
stable/drone

**What happened**:
istio's path mapping does not like `/` and thus blocks `/*`

**What you expected to happen**:
`/hello` to pass

**How to reproduce it** (as minimally and precisely as possible):
follow the [ingress-certmanager example from istio](https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/) and replace the path `/hello` for `/`. Then try with `/*`

**Anything else we need to know**:
I think we can't assume what the engine prefers, and would like to have the option to provide a path for the ingress:

```
ingress:
  hosts:
    - bla.bla.bla
  path: /*
```

### PR DESCRIPTION
**Pull request by Morriz**
#### What this PR does / why we need it:
added istio to defaults for /* path, added path fallback for ingress

#### Which issue this PR fixes
fixes #12862 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Morriz** [comment]
@christian-roggia are you available to review this pr?

**Comment by christian-roggia** [comment]
please bump chart version

**Comment by zakkg3** [comment]
@Morriz

**Comment by Morriz** [comment]
This is the 3rd time that I have to bump the chart version because it conflicts with an earlier approved version...will it ever stop? Is there a safeguard against this?

**Comment by zakkg3** [comment]
We need to merge this as the rpc_host its pointing to the external url by default. 
In case of cognito this will not work. we need to use the internal service.
fixed in this pr, but the author its not bumping the chart version.
so i opened https://github.com/helm/charts/pull/14939

**Comment by zakkg3** [comment]
@cpanato @maorfr please close this (https://github.com/helm/charts/pull/12864#issuecomment-504030870)
/close 
thanks!

**Comment by Morriz** [comment]
awesome

**Pull request closed without merging**
