### PR TITLE
Add support for CPU and memory limit for deployment

### PR DESCRIPTION
**Pull request by yngvark**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by timstoop** [comment]
We're moving all Charts to use a `resources: {}` instead of specific named resources, to allow for easier setting of requested resources and limits, without cluttering the values.yaml and the README. Can you modify this commit to make that change instead?

**Comment by nick4fake** [comment]
@timstoop I really think this is out of scope. Could we merge this and proceed with refactoring later?

**Comment by timstoop** [comment]
I do not see why it is out of scope? As those variables are added by this patch, I'd rather see them added by following our best practises. What do you say, @scottrigby?

**Comment by muehlburger** [comment]
I run in this issue and the fix of @nick4fake would fix it. Is it possible to merge this PR and refactor later?

**Comment by yngvark** [comment]
I have delayed this now for ages, but I realize I haven't got time for it, so I'm closing this PR.

**Pull request closed without merging**
