### PR TITLE
[stable/elasticsearch-exporter]: improved healthchecks

### PR DESCRIPTION
**Pull request by caarlos0**
####  What this PR does / why we need it:

Improves healthcheck timeouts, uses the correct `healthz` endpoint and adds a `preStop` hook to avoid aborting ongoing requests ([here is why](https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes)).

This should help avoiding false positives while deploying or when a spot node is replaced.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by svenmueller — APPROVED** [review]

**Comment by svenmueller** [comment]
any idea why check `pull-charts-e2e` keeps failing?

**Comment by caarlos0** [comment]
> any idea why check `pull-charts-e2e` keeps failing?

no idea :/

**Comment by desaintmartin** [comment]
`I0923 12:22:49.625]  âœ–ï¸Ž elasticsearch-exporter => (version: "1.10.1", path: "stable/elasticsearch-exporter") > Chart version not ok. Needs a version bump!`

**Comment by svenmueller** [comment]
@caarlos0 can you please check regrading the Chart version?

**Pull request merged**
