### PR TITLE
[stable/grafana] Fix README.md typo and whitespace

### PR DESCRIPTION
**Pull request by vsliouniaev**
#### What this PR does / why we need it:
Fix typo in Readme
Replace tabs with spaces in example - when I copy-pasted this, even from the github page, it broke my helm template.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by vsliouniaev** [comment]
/assign @paulczar
Not certain that the helm chart version actually needs a bump, since only minor changes in README.md, not affecting functionality

**Comment by mattfarina** [comment]
@vsliouniaev Charts are immutable (or that's the goal). So, every change ends up in a release so we require all changes to bump the chart version.

**Comment by vsliouniaev** [comment]
Thanks! done

**Comment by vsliouniaev** [comment]
/assign @davidkarlsen
It's a really small change :)

**Pull request merged**
