### PR TITLE
[stable/dex] Remove `allowPrivilegeEscalation` from PodSecurityContext 

### PR DESCRIPTION
**Pull request by pipo02mix**
The [Kubernetes spec for PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podsecuritycontext-v1-core) does not allow to define `allowPrivilegeEscalation`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by pipo02mix** [comment]
Is just a fix in the comment, should I need to bump Chart version?

**Comment by vi7** [comment]
Hi @pipo02mix ,

yes, please update patch version of the Chart, I assume it should be bumped to `2.12.1`

**Review by vi7 — CHANGES_REQUESTED** [review]
please bump patch version of the Chart

**Comment by pipo02mix** [comment]
done

**Pull request closed without merging**
