### PR TITLE
update document of sumologic-fluentd

### PR DESCRIPTION
**Pull request by cheyang**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cheyang** [comment]
My changes won't cause the test fail. It's because the chart needs sumologic.collectorUrl

```
helm install --name my-release \
    --set sumologic.collectorUrl=YOUR-URL-HERE stable/sumologic-fluentd
```

**Comment by frankreno** [comment]
@cheyangI have merged a fix that will prevent the tests causing this failure.  If you rebase and update you will be good.

**Pull request merged**
