### PR TITLE
[incubator/samba] Samba4 Chart

### PR DESCRIPTION
**Pull request by iMartyn**
#### What this PR does / why we need it:
Adds Samba chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by iMartyn** [comment]
@maorfr pretty please can this be looked at?

**Comment by iMartyn** [comment]
@maorfr @scottrigby @sameersbn Please, pretty please?

**Comment by maorfr** [comment]
hey @iMartyn 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by iMartyn** [comment]
I have and I do not wish to do this, I do not feel that helm hub is close enough to feature complete to be used yet.  Please at least hit the retest button for me, even if you're just going to ignore the PR because you don't want contributions here.

**Comment by maorfr** [comment]
/ok-to-test

https://helm.sh/blog/intro-helm-hub/

**Pull request closed without merging**
