### PR TITLE
[stable/jasperreports] explicitly set imagePullPolicy

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM, but it looks like this needs a rebase.

**Comment by prydonius** [comment]
Rebased and updated to only include the imagePullPolicy update, as #447 included the other changes.

**Comment by lachie83** [comment]
@k8s-bot okay to test

**Comment by lachie83** [comment]
Manually tested. Works. This can be merged

**Comment by mgoodness** [comment]
@k8s-bot e2e test this

**Pull request merged**
