### PR TITLE
[stable/jenkins] Add Agent.Privileged option

### PR DESCRIPTION
**Pull request by twpayne**
This allows Jenkins slaves to execute as privileged containers. This is useful from some build systems that require such privileges, e.g. [Bazel](https://bazel.build/) needs privileges to create its sandboxed environments.

### CODE REVIEW

**Comment by rimusz** [comment]
you should rename PR title which starts as `[stable/jenkins] ..` so by that would be easier to distinguish which chart is for

**Comment by seanknox** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@twpayne Can you please bump the chart version?

**Comment by twpayne** [comment]
Done (and rebased on the latest `master`).

**Comment by viglesiasce** [comment]
@k8s-bot e2e test this

**Pull request merged**
