### PR TITLE
[stable/redis]Fix registryName

### PR DESCRIPTION
**Pull request by bhack**

### CODE REVIEW

**Comment by prydonius** [comment]
Thanks @bhack, but could you actually use the same approach @twistedvines used in https://github.com/kubernetes/charts/pull/5340? Default shouldn't really be used in the templates as the values.yaml file should contain all the defaults.

**Comment by bhack** [comment]
I think it is better to fix this bug before and merge as is cause actually it is ignored at helm install. Then in a subsequent PR remove all the default.

**Comment by prydonius** [comment]
@bhack that seems unnecessary (especially given the long PR cycle). The fix in #5340 is the correct way of fixing this.

If you would prefer not to do it, I can make the change on your branch for you.

**Comment by bhack** [comment]
I prefer to have this specific ignored value fixed soon. But if you have the bandwidth to test the remove of all the defaults in the template send me your changes on my branch.

**Comment by bhack** [comment]
@prydonius There are other defaults it was not so quick.

**Comment by bhack** [comment]
Still 18 defaults in the template.

**Comment by prydonius** [comment]
@bhack I really just meant the image templates for this PR. The other ones here aren't hardcoding defaults in the template, but are falling back on other values which may be okay.

**Comment by bhack** [comment]
@prydonius  Oh ok I supposed that you want to remove all in general from .tpl this is why I pushed for merge on that value.

**Pull request merged**
