### PR TITLE
[general] improve issue templates

### PR DESCRIPTION
**Pull request by torstenwalter**
#### What this PR does / why we need it:

As GitHub support [multiple issue templates](https://help.github.com/en/articles/about-issue-and-pull-request-templates) I suggest to make uses of that feature to distinguish between bug reports and feature request.

Many issue and PRs already follow a naming convention to include the name of the chart e.g. `[stable/jenkins]` or `[incubator/jaeger]` within the title. This makes it easier to search for and filter existing issues. 

To make it easier to follow this convention the issue templates contain examples within the title. I haven't seen such a functionality for pull requests. Therefor I added it to the checklist as reminder.

By intention I did not include a name of an existing chart within the examples as people sometimes forget to change it and that would be unfair to the chart maintainers mentioned within the example.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Comment by torstenwalter** [comment]
@mattfarina I saw that the status of foxish changed to emeritus.

**Comment by mattfarina** [comment]
@torstenwalter Thanks for the PR. I like the idea. Before merging I would like to discuss it with the other maintainers in the charts chat call tomorrow.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
