### PR TITLE
[stable/prometheus-operator] Update grafana dashboards

### PR DESCRIPTION
**Pull request by kpucynski**
Signed-off-by: Karol Pucynski <kpucynski@gmail.com>

#### Is this a new chart

No.

#### What this PR does / why we need it:

Grafana dashboards update.
Follow-up update after merge in kubernetes-mixin https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/a19b4c0a6ec563aa002c64e764ef652b42316472 and kube-prometheus https://github.com/coreos/kube-prometheus/pull/265

#### Special notes for your reviewer:

Prepared with `sync_grafana_dashboards.py` according to `prometheus-operator/hack/README.md`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by kpucynski** [comment]
It seems that there is no enough nodes to fit prometheus operator tests :|
I'll contact #sig-testing

**Comment by kpucynski** [comment]
Tests are failing on cleanup - it seems that something is messing with namespaces names :|
```I1015 10:01:31.544] Deleting release 'prometheus-operator-cc72wpmota'...
I1015 10:01:54.619] release "prometheus-operator-cc72wpmota" deleted
I1015 10:01:54.627] Deleting namespace 'metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota'...
I1015 10:01:55.029] namespace "metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota" deleted
I1015 10:04:55.163] error: timed out waiting for the condition on namespaces/metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota
I1015 10:04:55.164] Namespace 'metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota' did not terminate after 180s.```

**Comment by kpucynski** [comment]
@vsliouniaev tests are failing, but they are not related with this PR - some kind of problem with namespaces naming. Can you check it?

**Comment by kpucynski** [comment]
tests are working locally
```
------------------------------------------------------------------------------------------------------------------------
 ✔︎ prometheus-operator => (version: "6.18.1", path: "stable/prometheus-operator")
------------------------------------------------------------------------------------------------------------------------
```
I'll try to add separate PR with name override, so the test may pass.

**Comment by zanhsieh** [comment]
@kpucynski 
You probably need to limit namespaces what prometheus-operator tried to fetch. If you look closely into the pull-charts-e2e logs, there're a lot of lines look like below:

```
...
I1015 10:01:14.835] level=error ts=2019-10-15T09:51:22.824892471Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"jaeger-operatorpresubmit-10064-17576-jixsfgbwji\" does not exist" err=null
I1015 10:01:14.835] level=error ts=2019-10-15T09:51:22.824957837Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"prometheus-adapter-presubmit-10269-19049-zcec42qjqd\" does not exist" err=null
I1015 10:01:14.835] level=error ts=2019-10-15T09:51:22.82510638Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"nginx-ingress-presubmit-16139-1159522177662324736-fm1ef1gtbk\" does not exist" err=null
I1015 10:01:14.835] level=error ts=2019-10-15T09:51:22.825183325Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"redis-presubmit-11579-1141347282533224448-hmigbtrxda\" does not exist" err=null
I1015 10:01:14.836] level=error ts=2019-10-15T09:51:22.825225918Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"rnetes-dashboard-presubmit-13215-1123295741830238208-g8iy641qe9\" does not exist" err=null
I1015 10:01:14.836] level=error ts=2019-10-15T09:51:22.825267789Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"metheus-operator-presubmit-15150-1153587266484965376-vwi64znm8r\" does not exist" err=null
I1015 10:01:14.836] level=error ts=2019-10-15T09:51:22.825319893Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"a8ab533c93d624d209c16c1f8c0dbae3-1144370330500861952-t6oxjfh7s5\" does not exist" err=null
I1015 10:01:14.837] level=error ts=2019-10-15T09:51:22.825369521Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"prometheus-postgres-exporterpresubmit-10027-17613-fqra27bktt\" does not exist" err=null
I1015 10:01:14.837] level=error ts=2019-10-15T09:51:22.825404191Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"drupal-presubmit-13128-1118759550267166727-p7lr0a42p0\" does not exist" err=null
I1015 10:01:14.837] level=error ts=2019-10-15T09:51:22.825446806Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"5f6c539644a28f539ca1ff9bf5339e9a-1144337115476135936-95dgkd280t\" does not exist" err=null
I1015 10:01:14.838] level=error ts=2019-10-15T09:51:22.825498084Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"ambassador-presubmit-16904-1171579382859304964-1453licqc3\" does not exist" err=null
I1015 10:01:14.838] level=error ts=2019-10-15T09:51:22.827523188Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"batch-a0b94a46fef8ce09cc068046813efca7d141780e-20615-pgic3la1n6\" does not exist" err=null
I1015 10:01:14.838] level=error ts=2019-10-15T09:51:22.827641726Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"ometheus-adapter-presubmit-14570-1138405723533742080-8tr8jzdjgs\" does not exist" err=null
I1015 10:01:14.838] level=error ts=2019-10-15T09:51:22.827766162Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"concoursepresubmit-9204-18824-5duiul8q45\" does not exist" err=null
I1015 10:01:14.839] level=error ts=2019-10-15T09:51:22.827810372Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"mysql-presubmit-13864-1128728445027618819-0ubu8rq0ov\" does not exist" err=null
I1015 10:01:14.839] level=error ts=2019-10-15T09:51:22.827880942Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"atlantis-presubmit-11438-20669-gj3jf0b8th\" does not exist" err=null
I1015 10:01:14.839] level=error ts=2019-10-15T09:51:22.827919988Z caller=operator.go:878 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"dex-presubmit-14345-1134462677821689856-si5593djrl\" does not exist" err=null
...
```

In other words, prometheus-operator pull every pre-submit build, where each one is an isolated namespaces. Each build will only live very short amount of time before prometheus-operator realize  it's gone.  And this will cause the k8s-ci-bot timeout. I don't think it will succeed even you submit another PR, unless some restriction on fetching namespaces applied.

**Comment by kpucynski** [comment]
@zanhsieh the problem seems to be also with chart-testing - it cuts names and created additional errors, e.g.:
```
I1015 10:01:12.582] level=warn ts=2019-10-15T09:51:14.068Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-prometheus-operator-cc72wp-alertmanager-0.alertmanager-operated.metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota.svc:9094: lookup alertmanager-prometheus-operator-cc72wp-alertmanager-0.alertmanager-operated.metheus-operator-presubmit-17955-1184043671457107968-cc72wpmota.svc on 10.3.240.10:53: no such host\n\n"
```
I wonder how earlier tests worked...

**Comment by kpucynski** [comment]
/retest
let's see what will happen today

**Comment by zanhsieh** [comment]
@kpucynski 
Same bug as I mentioned before happens.

**Comment by kpucynski** [comment]
Let's see after merge with test fixes https://github.com/helm/charts/pull/18066/commits/d1637cfcdd52b7b3754e499bafb35d814967a031

**Pull request merged**
