### PR TITLE
[stable/hlf-ca] Support MySQL, Postgres and External Database

### PR DESCRIPTION
**Pull request by nhuray**
#### What this PR does / why we need it:

Fabric CA server needs a database to store users and certificates. 

It supports 3 database types:
  - `sqlite3`: In memory database (useful in dev)
  - `postgres`: as a cluster for production
  - `mysql`: as a cluster for production
    
The actual  `hlf-ca` chart version just support a `postgres` database. The database has to be installed before installing the `hlf-ca` chart and the name of the `postgres` chart has to be passed in the `hlf-ca` configuration.

#### Which issue this PR fixes

This PR allows to easily install and configure a `potsgres` or `mysql` database along the Fabric CA using the [Helm dependency](https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md).

With this change, the chart is configured to use an in-memory `sqlite3` database by default, but you can also configure the helm chart to install a `PostgreSQL` or a `MySQL` database along the Fabric CA server. 

### PostgreSQL

To install a `postgresql` running in Kubernetes you have to enable and configure the `postgresql` section in `values.yaml` or pass the following parameter:

```
 helm install stable/hlf-ca --name org1-ca --set postgresql.enabled=true
```

### MySQL

To install a `mysql` running in Kubernetes you have to enable and configure the `mysql` section in `values.yaml` or pass the following parameter:

```
 helm install stable/hlf-ca --name org1-ca --set mysql.enabled=true
```

### External Database

In case you already setup a database (`postgres` or `mysql`), you can enable and configure the `externalDatabase` section in `values.yaml` or pass the following parameters:

```
 helm install stable/hlf-ca --name org1-ca \
   --set externalDatabase.type=mysql \
   --set externalDatabase.host=myhost \
   --set externalDatabase.username=myuser \
   --set externalDatabase.password=mypassword \
   --set externalDatabase.password=mydatabase
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by alexvicegrab** [comment]
Thanks for your contribution @nhuray, we will review and check the chart is backwards compatible and get back to you.

**Comment by alexvicegrab** [comment]
Meanwhile, please fix the issues highlighted in the `ci/circleci`:

```
stable/hlf-ca/values.yaml
  57:3      error    trailing spaces  (trailing-spaces)
  62:15     error    trailing spaces  (trailing-spaces)
  70:89     error    trailing spaces  (trailing-spaces)
  74:20     error    trailing spaces  (trailing-spaces)
  85:86     error    trailing spaces  (trailing-spaces)
  86:128    error    trailing spaces  (trailing-spaces)
  93:15     error    trailing spaces  (trailing-spaces)
  97:121    error    trailing spaces  (trailing-spaces)
  104:8     error    trailing spaces  (trailing-spaces)
```

**Comment by alexvicegrab** [comment]
Hi @nhuray, thanks for this improvement, the code and additions look great to me. I just want to make sure that the chart is backward compatible in the sense that a previous version of the chart can be updated to this version.

Please check that you can:

1) Create a chart with the current stable version (with an external PostgreSQL database).
2) Check that you can obtain the cainfo, 'register' and 'enroll' a new user.
3) Update the chart to use your new additions by updating the `externalDatabase` field.
4) Check that you can obtain the cainfo, 'register' and 'enroll' a new user.

Thanks,
Sasha

**Comment by alexvicegrab** [comment]
Hi @nhuray, I think each requirement has some kind of hash associated with it. I remember seeing this error when submitting an improvement to a chart requiring a dependency. We need to run something along the lines of:

```
helm dep update
```

**Comment by nhuray** [comment]
@alexvicegrab I created a video to test the upgrade: https://drive.google.com/open?id=1GYlG6ufw0y_AVVw6gayzZGST40O7I1zU

**Comment by alexvicegrab** [comment]
Thanks for your excellent PR, @nhuray

**Pull request merged**
