### PR TITLE
[stable/neo4j] ingress for http and bolt, setting connector advertised addresses

### PR DESCRIPTION
**Pull request by dennybaa**
* added ingress for http and bolt
* configuration of connector advertised addresses
* custom neo4j-server.properties file

### CODE REVIEW

**Comment by maorfr** [comment]
This is pretty tough to review.
This would probably go through faster if it was broken down. Leaving that up to you @dennybaa

**Comment by dennybaa** [comment]
@maorfr yup, my catch is that integration test fails. I have no idea why( In our cluster works smooth. But I will try to downgrade neo4j image to the previous version or do smth to reduce the entropy)

**Comment by zanhsieh** [comment]
@dennybaa 
I am kind of suspecting these msgs appearing in the e2e test:
```
...
I1015 15:58:32.408] RUNNING: neo4j-iwhbme7nca-neo4j-service-test-5wvyl
I1015 15:59:19.992] FAILED: neo4j-iwhbme7nca-neo4j-service-test-5wvyl, run `kubectl logs neo4j-iwhbme7nca-neo4j-service-test-5wvyl --namespace neo4j-presubmit-17720-1184136030584836096-iwhbme7nca` for more info
I1015 15:59:20.008] Error: 1 test(s) failed
...
I1015 15:59:22.588] Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
...
```
@maorfr Is it possible to see the log file of container?

**Comment by pascalwhoop** [comment]
We have the `core` StatefulSet behind an ingress for the `bolt` websocket connection. Some of our analysts are complaining that they sometimes only get READ (because their socket is routed to a FOLLOWER instead of the LEADER. I know this is related to [this medium post](https://medium.com/neo4j/neo4j-considerations-in-orchestration-environments-584db747dca5). Before we build this "just for us" I'd like to understand if this MR already addresses this issue or, if not, what I would need to build on top of this to get a solid deployment including ingress.

I'm new to neo4j (about 2h of skimming the docs) but AFAIK, the read replicas should be used for all read connections and the leader (not core as a whole) should be used for RW so I imagine a set of ingresses in the like of 
- `neo4j.<domain>` --> ` "web service" --> core StatefulSet
- ` neo4j-bolt-ro.<domain>` --> "bolt read only service" --> read replicas
- `neo4j-bolt-rw.<domain>` --> "bolt write service" --> leader only

I guess the link to the leader would have to be done with a NodePort and port spreading so a service can be constructed that only points to the leader.

Am I misunderstanding something here? And are others feeling similar issues?

**Pull request closed without merging**
