### PR TITLE
[traefik] remove self as owner

### PR DESCRIPTION
**Pull request by krancour**
I regret that I must do this, but my bandwidth doesn't allow me to continue as a reviewer and approver for this chart.

I'm happy to have created a chart that has been used so much and received so much community attention, but I'm doing a disservice to everyone who continues to contribute if my time constraints don't allow me to review contributions in a timely manner. I have become a bottleneck and I don't want that.

Recently, many of the great folks at @containous, who are actually the developers behind Traefik, have come on board as reviewers and approvers for this chart. I can't imagine there could be any better stewards of this chart than they.

So... this PR is intended to be a graceful exit for me.

Everyone keep up the good work!

### CODE REVIEW

**Comment by dtomcej** [comment]
Thank you @krancour for all the work that you have contributed. Your expertise will be missed.

**Comment by davidkarlsen** [comment]
@krancour Can you bump the chart-version please?

**Comment by davidkarlsen** [comment]
@krancour It won't merge without a bump, see: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/helm_charts/6380/pull-charts-e2e/11779/

**Comment by krancour** [comment]
Sorry... I forgot about that.

**Comment by krancour** [comment]
Fixed.

**Comment by dtomcej** [comment]
```
Keep a weather eye on the horizon...
```

/lgtm

**Comment by dtomcej** [comment]
@mattfarina Did we need to give the bot a little love on this one?

**Comment by mattfarina** [comment]
@krancour Can you give this a version bump? It appears something else was merged. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/helm_charts/6380/pull-charts-e2e/12359/ for more details

@dtomcej There was (maybe still is) a problem over the past day or so where the GitHub API isn't returning all the issues/PRs to a query that should match. It's causing some delays and issues at time for the bots.

**Comment by krancour** [comment]
@mattfarina bumped

**Comment by dtomcej** [comment]
@krancour Can we get one more bump? I _promise_ this one will get in next.

**Pull request merged**
