### PR TITLE
[stable/prometheus-operator] fixes #15275 Default alertmanager logfmt for better experience when deploying

### LINKED ISSUE #15275: [stable/prometheus-operator] spec.logFormat in body must be of type string: "null"
On version Kubernetes 2.14, Helm 2.13. 
For the chart stable/prometheus-operator, when you want to install **several times** the chart you have to disable _prometheusOperator.createCustomResource_ because of this error that appears if you **already installed the chart once** :
`Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists`

Then, after setting _prometheusOperator.createCustomResource=false_ you have **another error** appearing :
```
Error: release torrid-panther failed: Alertmanager.monitoring.coreos.com "torrid-panther-prometheus-alertmanager" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"Alertmanager", "metadata":map[string]interface {}{"creationTimestamp":"2019-07-05T14:08:12Z", "generation":1, "labels":map[string]interface {}{"app":"prometheus-operator-alertmanager", "chart":"prometheus-operator-5.14.1", "heritage":"Tiller", "release":"torrid-panther"}, "name":"torrid-panther-prometheus-alertmanager", "namespace":"monitor3", "uid":"532ed11d-9f2e-11e9-bd84-525400f0e95b"}, "spec":map[string]interface {}{"baseImage":"quay.io/prometheus/alertmanager", "externalUrl":"http://torrid-panther-prometheus-alertmanager.monitor3:9093", "listenLocal":false, "logFormat":interface {}(nil), "logLevel":"info", "paused":false, "replicas":1, "retention":"120h", "routePrefix":"/", "securityContext":map[string]interface {}{"fsGroup":2000, "runAsNonRoot":true, "runAsUser":1000}, "serviceAccountName":"torrid-panther-prometheus-alertmanager", "version":"v0.17.0"}}: validation failure list:
spec.logFormat in body must be of type string: "null"
```
So it's due to the **spec.logFormat**.

### PR DESCRIPTION
**Pull request by alejandro-guzman**
Signed-off-by: Alejandro Guzman <aguzman@collab.net>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by agguzman** [comment]
@gianrubio I have an update to help with issue https://github.com/helm/charts/issues/15275

**Comment by irasnyd** [comment]
I hit the same problem reported in issue #15275 today, and found this PR. The suggested fix in this PR fixes the problem I encountered with stable/prometheus-operator. Can we get this merged?

**Comment by vsliouniaev** [comment]
Sorry I didn't see this PR, the feature got merged in https://github.com/helm/charts/pull/15582

**Comment by agguzman** [comment]
No problem, fix is in so closing.

**Pull request closed without merging**
