### PR TITLE
[stable/inbucket] bump inbucket

### PR DESCRIPTION
**Pull request by kimxogus**
**What this PR does / why we need it**: This PR includes
- Bump inbucket to [latest stable version](https://hub.docker.com/r/jhillyerd/inbucket/tags/) which targets `2.0.0`
- Add `cmdOptions`
- Expose pop3 port with service
- Rename `pop` to `pop3` with backward compatibility

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kimxogus** [comment]
I also added pvc support

**Comment by kimxogus** [comment]
can anyone review this?

**Comment by cpanato** [comment]
this is covered here: https://github.com/helm/charts/pull/7126

**Pull request closed without merging**
