### PR TITLE
[stable/etcd-operator] Default etcdOperator.tolerations in values.yaml

### PR DESCRIPTION
**Pull request by caruccio**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@caruccio 
Would you mind to sign DCO and bump the chart to latest please? Thank you.

**Comment by caruccio** [comment]
@zanhsieh done. hope this is fine now. thanks.

**Comment by caruccio** [comment]
Hey, any chance for an /lgtm?

**Comment by zanhsieh** [comment]
@lachie83
@alejandroEsc
Please LGTM this. Thank you guys.

**Review by alejandroEsc — APPROVED** [review]

**Comment by alejandroEsc** [comment]
lgtm

**Pull request merged**
