### PR TITLE
[stable/jenkins] workaround for busybox's cp (Closes: #10471)

### LINKED ISSUE #10471: [jenkins] cp --no-clober / -n isn't supported by busybox
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: any

**Which chart**: jenkins 0.27

**What happened**: init pod failed

**What you expected to happen**: init pod finished successfully

**How to reproduce it** (as minimally and precisely as possible): use AlpineLinux based image for Jenkins, provision an updated deployment 

**Anything else we need to know**:

in templates/config.yml we have:
```
  apply_config.sh: |-
    mkdir -p /usr/share/jenkins/ref/secrets/;
    echo "false" > /usr/share/jenkins/ref/secrets/slave-to-master-security-kill-switch;
{{- if .Values.Master.OverwriteConfig }}
    cp /var/jenkins_config/config.xml /var/jenkins_home;
    cp /var/jenkins_config/jenkins.CLI.xml /var/jenkins_home;
    cp /var/jenkins_config/jenkins.model.JenkinsLocationConfiguration.xml /var/jenkins_home;
{{- else }}
    cp --no-clobber /var/jenkins_config/config.xml /var/jenkins_home;
    cp --no-clobber /var/jenkins_config/jenkins.CLI.xml /var/jenkins_home;
    cp --no-clobber /var/jenkins_config/jenkins.model.JenkinsLocationConfiguration.xml /var/jenkins_home;
{{- if .Values.Master.AdditionalConfig }}
{{- range $key, $val := .Values.Master.AdditionalConfig }}
    cp /var/jenkins_config/{{- $key }} /var/jenkins_home;
{{- end }}
{{- end }}
```

`--no-clobber` option is supported by GNU coreutils but not busybox, so in AlpineLinux based containers cp fails.

I suggest changing it to:
```
...
    test -f /var/jenkins_home/config.xml || cp /var/jenkins_config/config.xml /var/jenkins_home;
...
```
and so on.

Cases like
```
    # Copy plugins to shared volume
    cp -n /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins;
```

can be changed to
```
    # Copy plugins to shared volume
    find /usr/share/jenkins/ref/plugins/ -maxdepth 1 -type f -exec /bin/sh -c 'test -f /var/jenkins_plugins/$(basename {}) || cp {} /var/jenkins_plugins' \;
```

This should work with any coreutils implementation.

Alternatively `cp` can be wrapped with shell script which implements `-n/--no-clobber`.

I can prepare a PR (but i don't want to sign any CLA or similar things).

### PR DESCRIPTION
**Pull request by 375gnu**
cp in busybox doesn't have -n/--no-clobber

Signed-off-by: Hleb Valoshka <375gnu@gmail.com>

#### Which issue this PR fixes
  - fixes #10471

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
@375gnu thanks for your PR!

I suggest we go for a simpler solution rather then testing each file.
The solution has to be generic enough.

From digging around a bit, I saw that `cp -i` may be an option we can use.
For example:
instead of using `cp -n src dst` we can use `false | cp -i src dst`

i think it will be much cleaner.
What do you think?

**Comment by 375gnu** [comment]
On 1/10/19, Maor Friedman <notifications@github.com> wrote:
> From digging around a bit, I saw that `cp -i` may be an option we can use.
> For example:
> instead of using `cp -n src dst` we can use `false | cp -i src dst`
>
> i think it will be much cleaner.
> What do you think?

False will just close stdin, so while we have an expected result, I'd
not rely on this cp's behaviour.

`yes n | cp -i src dst` looks much better.

I'll fix the PR.

**Comment by maorfr** [comment]
isn't yes a bit confusing?
will `echo n | cp -i src dst` do the same?

**Comment by 375gnu** [comment]
On 1/10/19, Maor Friedman <notifications@github.com> wrote:
> isn't yes a bit confusing?

Let's assume that our users know coreutils :)

> will `echo n | cp -i src dst` do the same?

In case `src` is a single file, but in case we have several sources
this will be like with `false`, so I'd have `yes n` as more reliable
solution.

**Comment by maorfr** [comment]
I'm with you :)

**Comment by maorfr** [comment]
/lgtm
Good job @375gnu!

**Pull request merged**
