### PR TITLE
[stable/kibana] Upgrade kibana

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Review by lachie83 — APPROVED** [review]
lgtm

**Comment by compleatang** [comment]
No problems here, but I want to wait and merge either #7387 or #7361 before merging this as that won't require anybody to rebase.

**Comment by compleatang** [comment]
Ugh. Apologies. This will need a rebase.

**Comment by davidkarlsen** [comment]
@compleatang fixed

**Pull request merged**
