### PR TITLE
[stable/falco] upgrade agent and rules to 0.21.0

### PR DESCRIPTION
**Pull request by cameronattard**
#### Is this a new chart

No.

#### What this PR does / why we need it:

Upgrades falco and rules to latest version.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

@bencer @nestorsalceda

### CODE REVIEW

**Comment by cameronattard** [comment]
Sorry @nestorsalceda, I think I've fixed the failing test.

**Comment by nestorsalceda** [comment]
/lgtm

Thanks for the PR @cameronattard

**Pull request merged**
