### PR TITLE
[stable/traefik] Added optional clusterIP value to specify the clusterIP for the main service

### PR DESCRIPTION
**Pull request by mcronce**
#### What this PR does / why we need it:
Adds an option to specify the ClusterIP on the main Traefik service.  I route to it by service IP and am not able to use a hostname for that particular purpose.

I also semi-fixed up the alignment in the values table in README.md :)

#### Which issue this PR fixes
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by mcronce** [comment]
Whoops....just noticed I did this from the wrong branch.

**Comment by mcronce** [comment]
Whoops - wrong PR

**Comment by paulgrahek** [comment]
Any update on this getting committed? Running into this problem as it breaks ```helm upgrade``` if the Traefik Dashboard service has a type "Cluster IP"

**Pull request closed without merging**
