### PR TITLE
[stable/instana-agent] Add Affinity block

### PR DESCRIPTION
**Pull request by DanOfir**
In order to be able to use anti-affinity to exclude certain nodes from this daemonset

Signed-off-by: Dan Ofir <dan.ofir@monday.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DanOfir** [comment]
@fstab @JeroenSoeters can you please review this PR?

**Comment by mmanciop** [comment]
@DanOfir would you please move this PR to https://github.com/instana/helm-charts/? Sounds like a great idea to merge, but merges on Helm Hub are no longer allowed.

**Comment by mmanciop** [comment]
@DanOfir we will merge this change with the upcoming version 1.1.4 of the helm chart. Meanwhile, due to the deprecation of Helm Hub, the new home of the Instana agent charts is https://github.com/instana/helm-charts.

**Comment by DanOfir** [comment]
merged by Instana team in official repo

**Pull request closed without merging**
