### PR TITLE
`[stable/prometheus-redis-exporter]`Adding Tolerations to Redis Exporter

### PR DESCRIPTION
**Pull request by nirlo**
#### What this PR does / why we need it:

Adds Tolerations to prometheus-redis-exporter. I want to ensure that the exporter is placed on the correctly tainted node within my cluster.

This keeps the chart in line with other exporters for prometheus such as postgres, mysql, and cloudwatch. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by acondrat** [comment]
Hi @nirlo 
Thanks for the PR. Please sign off the commits.

**Review by acondrat — APPROVED** [review]

**Comment by davidkarlsen** [comment]
@nirlo ping?

**Pull request closed without merging**
