### PR TITLE
[stable/datadog] adding init container resource requests to the system probe init container

### LINKED ISSUE #20035: [stable/datadog] not able to specify resources on init containers
**Describe the bug**
When I set daemonset.useDedicatedContainers to true, the helm chart deploys init containers. However there is no way for me to specify the resources for those containers. In my cluster the resources for these containers always defaults to an empty map, but the cluster also has a constraint that all containers must specify resource requests and limits for CPU and memory. This causes the daemonset to fail to deploy.

**Version of Helm and Kubernetes**:
Helm 3.0.2
OpenShift 3.11 (Kubernetes 1.11)

**Which chart**:
stable/datadog

**What happened**:
The daemonset failed to deploy

**What you expected to happen**:
I expect to be able to specify resources so that the daemonset can deploy successfully

**How to reproduce it** (as minimally and precisely as possible):
- Setup cluster to reject any containers that do not have resources specified
- Do not provide default resources for containers
- set daemonset.useDedicatedContainers to true

### PR DESCRIPTION
**Pull request by bkimbrough88**
#### What this PR does / why we need it:
Adds resources to the system probe init container. Without this, any Kubernetes cluster that enforces that all containers have resource requests on them will fail to initialize this container.

#### Which issue this PR fixes
  - fixes #20035

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by alemairebe** [comment]
@bkimbrough88 is there something blocking you to assign this to irabinovitch ?
I would like to see this approved so I could use it without adding another source for my helm charts.
Thanks !

**Comment by bkimbrough88** [comment]
> @bkimbrough88 is there something blocking you to assign this to irabinovitch ?
> I would like to see this approved so I could use it without adding another source for my helm charts.
> Thanks !

I tried, but @irabinovitch hasn't participated in the PR so it won't let me assign them. If no progress has been made, I'll bring this up during the next community office hours.

**Comment by alemairebe** [comment]
> I tried, but @irabinovitch hasn't participated in the PR so it won't let me assign them. If no progress has been made, I'll bring this up during the next community office hours.

Then maybe someone else from https://github.com/helm/charts/blob/master/stable/datadog/OWNERS ? I see @celenechang and @mfpierre are both marked as reviewers of this PR and have approval rigjhts.

**Comment by irabinovitch** [comment]
Apologies for missing the previous pings. We'll get back with a review ASAP

**Review by clamoriniere — COMMENTED** [review]
Hi @bkimbrough88 
Your change looks ok.
Could you please update the `CHANGELOG.md` file too with a small description of your change.

Thanks

**Comment by bkimbrough88** [comment]
> Hi @bkimbrough88
> Your change looks ok.
> Could you please update the `CHANGELOG.md` file too with a small description of your change.
> 
> Thanks

*Sigh* I've thoroughly messed up my branch now because I forgot to sign my commits. I'll fix this in a bit.

**Comment by clamoriniere** [comment]
/lgtm

thanks for your contribution and your patience with the review process. 👍

**Pull request merged**
