### PR TITLE
[stable/fluentd-elasticsearch] fix _helpers.tpl

### PR DESCRIPTION
**Pull request by kimxogus**
#### What this PR does / why we need it:
1. only `fluentd-elasticsearch.name` is used in app label
2. use `.Values.fullnameOverride`
3. set fullname `fluentd-elasticsearch` if release name is `fluentd-elasticsearch`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by monotek** [comment]
duplicate of: https://github.com/helm/charts/pull/9382/files

/close

**Comment by kimxogus** [comment]
@monotek #9382 doesn't fix wrong usage of `fluentd-elasticsearch.fullname` in labels.

`kubectl get po -l app=fluentd-elasticsearch` won't show `fluentd-elasticsearch` pods.

**Comment by monotek** [comment]
You're righ. It will in a couple of minutes :-)

**Comment by kimxogus** [comment]
Good 👍 
When you fix them in #9382 , I can close this PR.

**Comment by monotek** [comment]
Done.

**Pull request closed without merging**
