### PR TITLE
[stable/prometheus-operator]Update crd urls in readme

### PR DESCRIPTION
**Pull request by nigh8w0lf**
Signed-off-by: Ashwin Cheekati <ashwinchandrasekhar@gmail.com>

#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
fix crd urls in reademe, which are currently returning a 404 
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
These URLs refer to a version of prometheus-operator that hasn't been released yet.

**Comment by nigh8w0lf** [comment]
Oh okay, updated to the ones for release 0.34
https://github.com/coreos/prometheus-operator/tree/release-0.34/example/prometheus-operator-crd
These should be the correct versions right? @vsliouniaev

**Comment by davidkarlsen** [comment]
@nigh8w0lf please sign your commits

**Comment by vsliouniaev** [comment]
Yep looks good!
/ok-to-test
Please fix the sign-off

**Pull request closed without merging**
