### PR TITLE
[stable/logdna-agent]: v1.1.0

### LINKED ISSUE #13869: Call for maintainers for charts with no OWNERS
Hello,

As maintaining this repository is growing harder by the day, this is a call for maintainers!

This issue is about 'recruiting' maintainers for charts that have no OWNERS file. The list of charts can be found at the end of this message.

If you wish to be added as a maintainer to one of the charts in this issue, please open a PR to add an OWNERS file, and add yourself to that OWNERS file.
In addition, maintainers in Chart.yaml and OWNERS should match.

We would suggest to include in the PR references to past contributions to the chart you are applying for.

If you are a planning to apply for being a maintainer and know someone who also fits this (and is interested) - feel free to approach them and include them!
we aim to have 2 maintainers per chart.

Once a PR exists, please add a comment referencing this issue, and ping one of the [maintainers](https://github.com/helm/charts/blob/master/OWNERS#L1) to get added as a read-only user to the helm/charts repository.

Thanks in advance to everyone who applies! We need your help.

All new OWNERS should be familiar with the following documents:
https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md
https://github.com/helm/charts/blob/master/CONTRIBUTING.md
https://helm.sh/docs/chart_best_practices/

Here is the list of charts:

~~incubator/artifactory~~
~~incubator/burrow~~
incubator/check-mk
incubator/common
incubator/couchdb
incubator/distribution
~~incubator/drone~~
incubator/etcd
incubator/fluentd-cloudwatch
~~incubator/fluentd~~
incubator/goldfish
~~incubator/istio~~
~~incubator/jaeger~~
incubator/jenkins-operator
incubator/keycloak-proxy
~~incubator/keycloak~~
incubator/kube-janitor
incubator/kube-registry-proxy
incubator/kubernetes-vault
~~incubator/kubewatch~~
incubator/mysqlha
~~incubator/oauth-proxy~~
incubator/patroni
incubator/puppet-forge
incubator/riemann
incubator/spring-cloud-data-flow
incubator/tensorflow-inception
incubator/vault
incubator/vaultingkube
incubator/webpagetest-agent
incubator/webpagetest-server
incubator/xray
incubator/orientdb
incubator/solr
~~stable/acs-engine-autoscaler~~
~~stable/aerospike~~ (moved #13867)
stable/ark
~~stable/aws-cluster-autoscaler~~
stable/aws-iam-authenticator
stable/bitcoind
stable/buildkite
~~stable/cert-manager~~
stable/cluster-autoscaler
stable/consul
stable/cosbench
stable/coscale
stable/dask-distributed
stable/dask
stable/distributed-tensorflow
stable/ethereum
stable/express-gateway
stable/external-dns
stable/factorio
stable/gcloud-endpoints
stable/gcp-night-king
~~stable/gitlab-ce~~
~~stable/gitlab-ee~~
stable/hackmd
stable/hadoop
stable/heapster
stable/heartbeat
stable/hubot
stable/ignite
stable/ipfs
stable/janusgraph
stable/k8s-spot-termination-handler
stable/kanister-operator
~~stable/kanister-operator/charts/profile~~
stable/kapacitor
stable/katafygio
stable/keel
~~stable/kiam~~
~~stable/kube-lego~~
stable/kube-ops-view
stable/kube-slack
~~stable/kube-state-metrics~~ (moved #13867)
stable/kube2iam
stable/kuberos
stable/kured
stable/lamp
stable/linkerd
stable/locust
stable/luigi
~~stable/mailhog~~ (moved #13315)
stable/mcrouter
stable/metabase
stable/metallb
stable/minecraft
~~stable/mission-control/charts/elasticsearch~~
stable/msoms
stable/namerd
stable/neo4j
stable/nginx-ldapauth-proxy
stable/nginx-lego
stable/openldap
stable/percona
stable/presto
~~stable/prometheus-adapter~~
stable/prometheus-consul-exporter
stable/prometheus-couchdb-exporter
stable/prometheus-mysql-exporter
stable/prometheus-postgres-exporter
stable/prometheus-rabbitmq-exporter
stable/prometheus-redis-exporter
stable/prometheus-to-sd
stable/rethinkdb
stable/risk-advisor
stable/rookout
stable/sapho
stable/sensu
~~stable/sentry~~ (moved #13867)
~~stable/signalfx-agent~~
~~stable/spark-history-server/charts/nfs~~
stable/spark
stable/spartakus
stable/spotify-docker-gc
~~stable/spring-cloud-data-flow~~
stable/stackdriver-exporter
stable/stolon
stable/sumokube
stable/superset
stable/tomcat
stable/uchiwa
stable/unbound
stable/verdaccio
~~stable/weave-scope~~
stable/zeppelin
stable/zetcd
stable/logdna-agent
stable/socat-tunneller
~~stable/velero~~

### PR DESCRIPTION
**Pull request by smusali**
* v1.1.0

* Update README.md

#### What this PR does / why we need it:
* Fix `autoupdate` Type Mismatch
* Support for Custom `Secrets` Template
* Support for Custom `LogDNA API Hostname`
* Support for Custom `LogDNA Ingestion Hostname`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #13498, fixes #13496

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by smusali** [comment]
@scottrigby @unguiculus 

Can you quickly approve this `Pull Request`? It has passed almost all checks! This is just addition!

Thanks in advance!

**Comment by maorfr** [comment]
are you sure that it fixes #13869 ?

**Comment by smusali** [comment]
@maorfr, doesn't it? This PR contains `OWNERS` file too which is for specifying maintainers.

**Comment by maorfr** [comment]
right, but it will close the issue, which is not what we want.

**Comment by smusali** [comment]
@maorfr, I see - I'll remove that part from description

**Comment by maorfr** [comment]
i think you will have to close and reopen

**Comment by smusali** [comment]
@scottrigby @unguiculus

Can you quickly approve this Pull Request? It has passed all checks! This is just addition! And it is waiting for `/ok-to-test`

Thanks in advance!

**Comment by maorfr** [comment]
can we rebase and resolve conflicts? i'll approve it.
already added you as collaborators to the repo.

**Comment by jharlow1** [comment]
@smusali any chance of getting this rebased and approved? I was about to submit a similar PR for the apihost and loghost variables but didn't want to duplicate this one.

**Pull request closed without merging**
