### PR TITLE
[stable/traefik] Added ability to log itself logs in json format

### PR DESCRIPTION
**Pull request by alexandrst88**
**What this PR does / why we need it**:

This PR enabled, Traefik to log in JSON format(not related to access logs), this is useful if you want to proceed logs with Fluentd or some log processor.

### CODE REVIEW

**Comment by alexandrst88** [comment]
@SantoDE could you please review this PR? :)

**Review by geraldcroes — COMMENTED** [review]
LGTM

**Comment by c-knowles** [comment]
Anyone else getting consistent `backend not found` across all ingresses after updating to this chart version? Reverting to chart v1.48.0 appears to solve it.

**Comment by c-knowles** [comment]
@alexandrst88 cool thanks, wasn’t really sure what was wrong but will check it out the patched chart version.

**Pull request merged**
