### PR TITLE
Update Rocket.Chat version

### PR DESCRIPTION
**Pull request by kevinfaveri**
#### What this PR does / why we need it
It updates Rocket.Chat version from 2.1.1 to 2.3.1 (latest) 

#### Which issue this PR fixes
It updates Rocket.Chat version from 2.1.1 to 2.3.1 (latest) 

#### Checklist
- [x] Chart Version bumped

### CODE REVIEW

**Comment by verwilst** [comment]
Please adjust the Readme file accordingly (default image tag), and update version in Chart.yml as well (2.0.1 instead of 2.0.0)

**Comment by kevinfaguiar** [comment]
Done @verwilst

**Comment by davidkarlsen** [comment]
@kevinfaguiar please sign-off your commits

**Comment by kevinfaguiar** [comment]
Done @davidkarlsen

**Comment by verwilst** [comment]
2.4.9 is already in the tree, so this is obsolete by now :-)

**Comment by davidkarlsen** [comment]
Obsoleted

**Pull request closed without merging**
