### PR TITLE
[stable/calico-aws] Add new chart

### PR DESCRIPTION
**Pull request by gp42**
#### Is this a new chart
This is a new Helm chart for running Project Calico on AWS EKS.

#### What this PR does / why we need it:
Calico is a common/widely used solution for managing network on AWS EKS, and it is missing from charts.

#### Special notes for your reviewer:
Based on: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/calico.yaml
Can run on any Kubernetes cluster, but useful work will only be done on AWS EKS.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@gp42 
I would say a new chart should go thru incubator before going to stable branch.

**Comment by willejs** [comment]
@prydonius can you review this? It LGTM and id like to use it instead of making my own chart...

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

**Comment by scottrigby** [comment]
@gp42 looks pretty interesting. Hope to see it on the Hub. Ping us in Slack if you need any help

**Comment by gp42** [comment]
Okay, I guess I just host it on my GitHub and publish to  https://helm.hub.sh

**Pull request closed without merging**
