### PR TITLE
[stable/external-dns] Allow for the usage of existing secrets

### PR DESCRIPTION
**Pull request by marc-sensenich**
Signed-off-by: Marc Sensenich <sensenichm91@gmail.com>

#### What this PR does / why we need it:
Allows for the external secrets in the `extraEnv` field due to a template issue with the template providing a `map[string][string]` to the `secret.yaml` template.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by tompizmor** [comment]
Hi @marc-sensenich, this other PR https://github.com/helm/charts/pull/15900 should address this issue and it is being merged soon. 
Can you take a look at it and close this one if it is duplicated?

**Comment by marc-sensenich** [comment]
@tompizmor That PR covers it and this was an oversight on my part. Closing this PR

**Comment by tompizmor** [comment]
Thanks for checking so quickly!

**Pull request closed without merging**
