### PR TITLE
[stable/traefik] DaemonSet support

### PR DESCRIPTION
**Pull request by kartoch**
#### What this PR does / why we need it:

Support for DaemonSet in Traefik (see 

#### Which issue this PR fixes

 See issue #477, #3190, #3191,  #9787

#### Checklist

- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by nsteinmetz** [comment]
Shouldn't the traefik images be upated to 1.7.6+ (1.7.7. is just out : https://github.com/containous/traefik/releases) as there were some bugs and security issues ?

**Comment by rbq** [comment]
Are there any other charts with a similar variable? I'd suggest naming it something like `workloadKind` or `workloadController` instead of `deployType`, so that it's closer to the Kubernetes concept it represents.

**Comment by kurlzor** [comment]
It would be nice to finally have this without having to download and modify every new version of the chart...

**Comment by m-osmani** [comment]
i would really appreciate this feature.

my on-prem setup exists of 3 nodes (1 x master & 2 nodes).

i have deployed traefik based on the stable helm chart with externalIP + Letsencrypt.
Everything works execpt "traefik.ingress.kubernetes.io/whitelist-source-range", the reason is that the client ip is not forwarded to traefik.

if i change the option externalTrafficPolicy to "Local" then the client ip is available through X_FORWARDED_FOR but **only** over the NodePorts but not directly over the custom externalIP-80/443 (caused by kube-proxy - iptables - nat).

I know that the idea is to have a LB in front of traefik which will talk over proxy-protocol but in my case i dont want an external LB.

From my point of view its enough for small setups to have a reverse proxy (traefik ingress controller) to expose services to the outside world.

Based on this sentence [DaemonSets can be run with the NET_BIND_SERVICE capability, which will allow it to bind to port 80/443/etc on each host. This will allow bypassing the kube-proxy, and reduce traffic hops.](https://docs.traefik.io/user-guide/kubernetes/#deploy-traefik-using-a-deployment-or-daemonset) i think that it would work.

**Comment by tlvenn** [comment]
Yes ability to set `hostNetwork` & `hostPort` & `dnsPolicy` in the DaemonSet as pointed out by @Bessonov are super important.

**Comment by sylvainblot** [comment]
rebase ?

**Comment by metal3d** [comment]
If someone can rebase this PR, Daemonset is a needed feature for some users

**Comment by sylvainblot** [comment]
@metal3d https://github.com/sylvainblot/charts/tree/feature/daemonset

**Comment by metal3d** [comment]
OK :)
I didn't thought of incubator, thanks a lot

**Comment by tlvenn** [comment]
This PR has a little issue with the deployed service. The property `externalTrafficPolicy` is not valid when the service type is ClusterIp (the expected value in case of DaemonSet).

**Comment by sylvainblot** [comment]
@tlvenn Like this ? https://github.com/helm/charts/commit/2266a129e5b7761ab78af8d82dd60e95e779820b

**Comment by sylvainblot** [comment]
ok I wil add @Bessonov suggestions and create a new PR.

**Comment by sylvainblot** [comment]
can someone give a try to : https://github.com/sylvainblot/charts/tree/feature/daemonset
it adds hostNetwork.enable dnsPolicy and fix service ports.

**Comment by sylvainblot** [comment]
#11813

**Comment by tlvenn** [comment]
I can give it a try but I really need:
```

**Comment by sylvainblot** [comment]
sure

**Comment by sylvainblot** [comment]
can we do that with free field? and add the capacity for daemonset only ?

**Comment by sylvainblot** [comment]
is there an helm guideline to let the user manage the securityContext ?

**Comment by sylvainblot** [comment]
@tlvenn done

**Comment by m-osmani** [comment]
is it possible to know when this feature will be finished ?

**Comment by onedr0p** [comment]
LGTM

**Comment by kartoch** [comment]
Closing for more advanced PR #11813

**Pull request closed without merging**
