### PR TITLE
[stable/elasticsearch] Run as non-root

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:

Adds an option to configure the containers' security context `runAsUser` parameter.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @desaintmartin I've created a new PR as the other one got messed up. Here it is, disabled by default :)

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
bump

**Comment by NickLarsenNZ** [comment]
Can this be pushed along?

@naseemkullah looks like a winning solution. Just need to fix that conflict `stable/elasticsearch/Chart.yaml`

**Comment by naseemkullah** [comment]
conflict fixed @NickLarsenNZ! Thanks.

**Comment by AntonioMeireles** [comment]
hey all!

any progress on this ?

**Comment by NickLarsenNZ** [comment]
Is pull-charts-e2e broken or something?

Calling out to approvers:
@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr

**Comment by maorfr** [comment]
/ok-to-test
/lgtm

Thanks!

**Comment by NickLarsenNZ** [comment]
Thanks @maorfr, I'm not sure it's working properly though. [See the build output](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/13429/pull-charts-e2e/1131051660873830400/)

**Pull request merged**
