### PR TITLE
Added 'cadence' chart in incubator 

### PR DESCRIPTION
**Pull request by ahma**
#### What this PR does / why we need it:
This is a chart for cadence.  Cadence is a distributed, scalable, durable, and highly available orchestration engine to execute asynchronous long-running business logic in a scalable and resilient way.

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ahma** [comment]
Hi Lachlan,
Could you please check this chart? 
Thanks,
Feri
/assign @lachie83

**Comment by mattfarina** [comment]
@ahma This appears to be the same chart I can already get at https://hub.helm.sh/charts/banzaicloud-stable/cadence. Is there a reason to have it in both places? Note, our goal is to deprecate the stable charts repo and I am working on integrating the `helm search` commands into the Helm Hub for Helm v3.

**Comment by ahma** [comment]
Hi @mattfarina,
okay thanks, depending on that I'm closing this pr. 
Feri

**Pull request closed without merging**
