### PR TITLE
add namespace field

### PR DESCRIPTION
**Pull request by kanolato**
Signed-off-by: Miguel Angel Medina Mondragon <kanolato@gmail.com>

#### What this PR does / why we need it:
Added Namespace fields, useful when using `helm template` command
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @kanolato, can you please explain the need of namespace. If you want to deploy Reloader in specific namespace, you can achieve that by updating the flag `watchGlobally` to false.

**Comment by kanolato** [comment]
> Hi @kanolato, can you please explain the need of namespace. If you want to deploy Reloader in specific namespace, you can achieve that by updating the flag `watchGlobally` to false.

Hi @faizanahmad055, im using `helm template` as follows:
```
helm template --name example --namespace ex\
  --output-dir ./build \
    reloader
```
The output is the following:
```
---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: "reloader-1.0.1"
    heritage: "Tiller"
    app: reloader
    release: "example"
    group: com.stakater.platform
    provider: stakater
    
  name: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
      release: "example"
  template:
    metadata:
      labels:
        app: reloader
        release: "example"
        chart: "reloader-1.0.1"
        heritage: "Tiller"
        group: com.stakater.platform
        provider: stakater
        
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "stakater/reloader:v0.0.25"
        imagePullPolicy: IfNotPresent
        name: reloader
      serviceAccountName: reloader

```
Thats why i put the `namespace: {{ .Release.Namespace }}`. Most charts have that for the ones not using tiller. 

With `namespace: {{ .Release.Namespace }}` we get:
```
---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: "reloader-1.0.1"
    heritage: "Tiller"
    app: reloader
    release: "example"
    group: com.stakater.platform
    provider: stakater
    
  name: reloader
  namespace: example
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
      release: "example"
  template:
    metadata:
      labels:
        app: reloader
        release: "example"
        chart: "reloader-1.0.1"
        heritage: "Tiller"
        group: com.stakater.platform
        provider: stakater
        
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "stakater/reloader:v0.0.25"
        imagePullPolicy: IfNotPresent
        name: reloader
      serviceAccountName: reloader

```

**Pull request merged**
