### PR TITLE
[stable/rabbitmq-ha] Allow setting the publishNotReadyAddresses option

### PR DESCRIPTION
**Pull request by mprasil**
#### What this PR does / why we need it:

This allows setting the `publishNotReadyAddresses` option in the service
template. This is handy in cases where custom readiness check might
report pod as not ready, but we still want to publish the address in
DNS record.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
There's already a separate [service](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/service-discovery.yaml) that has `publishNotReadyAddresses ` set to true. Why not use that?

**Comment by mprasil** [comment]
We were contemplating that, we probably could. It just feels right to leave discovery service for cluster node discovery and use separate service for clients. There are other factors like missing labels and annotations that might be a reason to prefer the "client side" service. (though this is not something we really need)

**Comment by mprasil** [comment]
Hi @steven-sheehy, just wondering if you decided regarding this PR? I don't really care either way, but need to make certain decisions depending on whether this gets merged or not.

**Comment by steven-sheehy** [comment]
I'm inclined to not merge this.

**Comment by mprasil** [comment]
Fair enough, thanks for your input.

**Pull request closed without merging**
