### PR TITLE
[stable/kibana] updated kibana to 7.1.1

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

#### What this PR does / why we need it:
* updates kibana to 7.1.1
* adds elasticsearch dependency

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by compleatang** [comment]
ugh these flaky, flaky tests.... 

@monotek this demonstrates that we likely need to accept one of the following:

* super flaky tests
* very little test coverage
* that a standalone chart for kibana may not make sense.

In any event, I will comment on the test issue shortly.

**Comment by monotek** [comment]
@compleatang 
@jethr0null just asked if we would like to join forces with the elastic folks to have only 1 official Kibana chart. So maybe this would be a good idea to get everything working :-)

**Comment by compleatang** [comment]
@monotek absolutely! really think they should take over here....

**Comment by compleatang** [comment]
@monotek @jethr0null how can we get this collaboration started?

**Comment by jethr0null** [comment]
Hi @compleatang. I actually started a group chat in the k8s slack with you and @monotek so that we could chat about it. Does that work for you? Otherwise, we could start a new issue and use that to discuss if you prefer.

**Comment by compleatang** [comment]
sure that's fine. i haven't been on k8s slack routinely but happy to coordinate there :)

**Comment by monotek** [comment]
I'll close this one and create a new one tomorrow to deprecated the chart...

**Comment by compleatang** [comment]
Cool. I've added a tracker issue -> https://github.com/helm/charts/issues/14935

**Pull request closed without merging**
