### PR TITLE
[stable/airflow] Typo fix

### PR DESCRIPTION
**Pull request by zanhsieh**
Signed-off-by: Mingchin Hsieh <zanhsieh@gmail.com>

Based on https://github.com/helm/charts/pull/16447

#### Which issue this PR fixes
README.md typos

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@gsemet 
Would you mind to take a look this? @dylburger does not respond.

**Review by gsemet — APPROVED** [review]
/lgtm

**Comment by gsemet** [comment]
Thanks !

**Pull request merged**
