### PR TITLE
`helm add repo` --> `helm repo add`

### PR DESCRIPTION
**Pull request by ryanmjacobs**
#### What this PR does / why we need it:
I think this should be `helm repo add` instead of `helm add repo`; at least on my machine, that order worked.

```console
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Review by tao12345666333 — APPROVED** [review]
Thanks.

**Comment by maorfr** [comment]
this needs a version bump to pass.

**Comment by maorfr** [comment]
/close

so this chart is deprecated.
https://github.com/helm/charts/tree/master/stable/graphite

**Pull request closed without merging**
