### PR TITLE
[drone] Fixing go template "error calling index: index of untyped nil"

### PR DESCRIPTION
**Pull request by gullitmiranda**
this PR fix error when the value `ingress.annotations` has no value for `kubernetes.io/ingress.class` the generation of the template breaks with the following error:

```log
Error: render error in "charts/drone/templates/ingress.yaml": template: 
charts/drone/templates/ingress.yaml:23:27: executing 
"charts/drone/templates/ingress.yaml" at <index $.Values.ingre...>: 
error calling index: index of untyped nil
```

### CODE REVIEW

**Comment by jdumars** [comment]
Hi, please get your CLA taken care of and we'll approve this for testing.

**Comment by christian-roggia** [comment]
This PR can be merged.

**Pull request merged**
