### PR TITLE
[stable/rabbitmq] - Fix wrong PUBLISH_PORT(default 9090) if defined in values.yaml

### PR DESCRIPTION
**Pull request by huang-tianwen**
Fix wrong PUBLISH_PORT(defalut 9090) if defined in values.yaml

#### Is this a new chart
No.

#### What this PR does / why we need it:
If we define our metrics.port(in values-production.yaml use 9419), the prometheus container will still using 9090 as it's PUBLISH_PORT and cause the liveness and readiness probes fail and pod will keep restarting. This PR pass the metrics.port value to container PUBLISH_PORT EnvironmentVariable and fix the error.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by huang-tianwen** [comment]
@sameersbn I don't know how it didn't pass the test, but i think this is the correct one because i cannot use values-production.yaml when installing at AKS

**Comment by rafariossaa** [comment]
Hi @huang-tianwen ,
  Could you fix the errors that DCO reported ? You need to singoff your commits, and change the title of the PR.
  Also it would help if you mark the items in the checklist section of the PR.
thanks

**Comment by huang-tianwen** [comment]
> Hi @huang-tianwen ,
> Could you fix the errors that DCO reported ? You need to singoff your commits, and change the title of the PR.
> Also it would help if you mark the items in the checklist section of the PR.
> thanks

**Comment by huang-tianwen** [comment]
@rafariossaa I am sorry, just first time creating PR and I am not familiar with all those stuffs. Thanks for guiding me.
How run the test before i create a PR?

**Comment by rafariossaa** [comment]
/lgtm

@huang-tianwen  sorry for the delay.

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
