### PR TITLE
[stable/concourse] Add Prometheus scrape annotations

### PR DESCRIPTION
**Pull request by william-tran**
Follow-on to #3125

### CODE REVIEW

**Comment by matthope** [comment]
I've been using #3125 with service annotations (`web.service.annotations`) rather than deployment annotations. Is there anything to be gained this way?

(of course, a simple enabled turning on the annotation is a good idea)

**Comment by william-tran** [comment]
@matthope one less thing to have to figure out if you want to use prometheus

**Comment by matthope** [comment]
Sorry @william-tran - I wasn't clear. I was wondering if there is any benefit to using annotations on the deployment/pod rather than the service.

**Comment by william-tran** [comment]
@matthope Oh I see now, from https://groups.google.com/forum/#!topic/prometheus-users/jDEzVHUUFzw it looks like either technique works, with applying it to the pod helpful for scraping metrics when a pod is terminating. But looking at all the other charts, I see it being applied to the service rather than the pod in cases where a service exists, so applying it to the service would be a more consistent approach. I'll update my PR accordingly.

**Review by matthope — APPROVED** [review]

**Comment by mattfarina** [comment]
@viglesiasce tangentially related, should we get an owners file going for concourse?

**Comment by mattfarina** [comment]
@nexeck if you want to be able to merge changes to this chart you can do that now. Direction is up at https://codeengineered.com/blog/2017/kubernetes-chart-owners/. If you're interested we'd be happy to help.

**Pull request merged**
