### PR TITLE
incubator/elasticsearch - added gce-pd-ssd storageclass

### PR DESCRIPTION
**Pull request by marekaf**
**What this PR does / why we need it**:
it adds gce-pd ssd storageclass to incubator/elasticsearch so it is easier for this chart's users to deploy es to GKE 

There does not seem to be a guide on how to add a custom storageclass for a chart, so I took rethinkdb's https://github.com/helm/charts/tree/master/stable/rethinkdb implementation, improved it a bit and here it is

### CODE REVIEW

**Comment by cpanato** [comment]
still need to sign the DCO -https://github.com/helm/charts/pull/6875/checks?check_run_id=15455550

**Comment by bartimar** [comment]
Wtf, I'm confused. I need more information, I'll go check the contrib guide...

**Comment by bartimar** [comment]
the dco's status is so confusing...
I'm very happy when I can contribute to helm charts but I don't like spending more time dealing with this nonsense than actually working on the charts...

**Comment by bartimar** [comment]
ok, fck it...

**Pull request closed without merging**
