### PR TITLE
[stable/fluent-bit] Add Retry_Limit parameter support for es output

### PR DESCRIPTION
**Pull request by grimmxsleeper**
#### What this PR does / why we need it:
Expose backend.es.retry_limit for more configuration needs
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - Issue not created yet

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by grimmxsleeper** [comment]
/assign @towmeykaw 
this is my first PR let me know if i missed something

**Comment by zanhsieh** [comment]
@grimmxsleeper 
Would you mind to sign DCO first please? Thank you.

**Comment by grimmxsleeper** [comment]
@zanhsieh done

**Comment by Towmeykaw** [comment]
Looks good, just bump the chart version again.

**Comment by grimmxsleeper** [comment]
Bumped version

**Comment by zanhsieh** [comment]
@grimmxsleeper 
Could you resolve the file conflict please?
stable/fluent-bit/Chart.yaml

**Comment by grimmxsleeper** [comment]
@zanhsieh resolved conflict

**Comment by zanhsieh** [comment]
@kfox1111
@edsiper
@hectorj2f
@Towmeykaw
Would you guys LGTM this PR please? Thank you.

**Pull request merged**
