### PR TITLE
[stable/elasticsearch] post init job to configure cluster

### LINKED ISSUE #9066: [stable/elasticsearch] post init job to configure cluster
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm v2.10
K8S v1.10

**Which chart**:

stable/elasticsearch

**What happened**:

There is no possibility to configure number of shards and replicas per index (and many different options accessible by REST API)

**What you expected to happen**:

Post-init container with curl to use REST API

### PR DESCRIPTION
**Pull request by maver1ck**
#### What this PR does / why we need it:

Adding post-init job as a way to configure cluster

#### Which issue this PR fixes
  - fixes #9066 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by rendhalver** [comment]
What's the main use for this?

**Comment by maver1ck** [comment]
I can show you sample configuration :)
```
cluster:
  bootstrapShellCommand: >
    curl -XPUT 'http://elastic-elasticsearch-client.logging:9200/_template/all' -H 'Content-Type: application/json' -d'{"index_patterns": "logstash-*", "settings": {"number_of_shards": 3, "number_of_replicas": 1}}' 
```

**Comment by rendhalver** [comment]
Could we build that into the deployment instead?

**Comment by maver1ck** [comment]
Which deployment ? Client ?
I don't think so. As far as I know this is the reason helm post-install hooks was created.

**Comment by rendhalver** [comment]
Wow they don't make it easy do they.
It looks like you need to use the API or add an index template.

**Comment by maver1ck** [comment]
@rendhalver 
Nope. As far as I know this is the only way to configure number of shards and replicas.
Ref: https://discuss.elastic.co/t/how-to-change-the-default-amount-of-shards-and-replicas-of-indices/95989/4

**Comment by ayk33** [comment]
Do we have any ETA on when this PR will be available in master?

**Comment by rendhalver** [comment]
You can add an index tempate using the configmap if you want to do it that way.
It's a little bit more work but more portable.

**Comment by ayk33** [comment]
Is there a special environment variable that the container is looking for that can be mounted in the configmap to setup indices? How would the configmap work since we need to make an API call to elasticsearch to configure the indices.

**Comment by maver1ck** [comment]
@rendhalver 
Could you explain how ? Especially for Elastic 6 ?

**Comment by ayk33** [comment]
@maver1ck You will need to come up with some method of combining the configmap that is created from the helm chart with your own custom one. Then mount that configmap to the directory:
`/usr/share/elasticsearch/config/elasticsearch.yml` on the container. 
@rendhalver Did you have a better solution in mind? Or is that what you were thinking? 

A solution I still want to test is just running a post install curl to setup the indices settings. I am not sure if those settings will get preserved if a single master pod dies or not though. (Will be testing later) 

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html

**Comment by maver1ck** [comment]
@ayk33 
1) As far as I know there is no possibility to set up shards and replicas in `elasticsearch.yml`
2) My PR gives you exactly this - ability to run post-install curl :)

**Comment by ayk33** [comment]
@maver1ck Hopefully it gets approved soon :) I need that functionality.

**Comment by maver1ck** [comment]
@rendhalver I rebased PR. WDYT ?

**Comment by maver1ck** [comment]
ping @rendhalver

**Comment by maver1ck** [comment]
@rendhalver 
Yet another rebase. Can I get this merged ?

**Comment by maver1ck** [comment]
@rendhalver 
It's here third month. Could you please merge it ?

**Comment by rendhalver** [comment]
@maver1ck Can you put in a PR to add some docs to the README with command to configure the shards and replicas please?
I think that would be a handy addition so people have an ideas on how to achieve what you were using this for.

**Pull request merged**
