### PR TITLE
[stable/spinnaker] Update minio dependency

### LINKED ISSUE #23878: [stable/spinnaker] minio template contains superfluous parenthesis, causing installation errors
**Describe the bug**
Trying to install `spinnaker` with a recent version of `helm` produces errors.

**Version of Helm and Kubernetes**:

```shell
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"archive", BuildDate:"2020-09-18T18:46:38Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-gke.4801", GitCommit:"bd8e5ba9d65ac06f6abd076a44f195668631a536", GitTreeState:"clean", BuildDate:"2020-09-10T00:12:32Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/spinnaker

**What happened**:

```shell
$ helm template spinnaker helm-stable/spinnaker --version 2.2.3
Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled

Use --debug flag to render out invalid YAML
```

```shell
$ helm template spinnaker helm-stable/spinnaker --version 2.2.3 --debug
install.go:172: [debug] Original chart version: "2.2.3"
install.go:189: [debug] CHART PATH: /REDACTED/.cache/helm/repository/spinnaker-2.2.3.tgz

Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
helm.go:94: [debug] template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```

**What you expected to happen**:

I expected the chart to install cleanly.

**How to reproduce it** (as minimally and precisely as possible):

1. Download a recent version of helm3
1. Add helm-stable repo
   ```shell
   $ helm repo add helm-stable https://kubernetes-charts.storage.googleapis.com
   "helm-stable" has been added to your repositories
   $ helm repo update
   Hang tight while we grab the latest from your chart repositories...
   ...Successfully got an update from the "helm-stable" chart repository
   Update Complete. ⎈Happy Helming!⎈
   ```
1. Try to install the spinnaker chart
   ```shell
   $ helm template spinnaker helm-stable/spinnaker --version 2.2.3
   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled

   Use --debug flag to render out invalid YAML 

**Anything else we need to know**:

The root of the issue was a change in the Go standard library templating in Go 1.14 so any Helm release from the 8 months or so will be affected. It seems to have been fixed in the official minio chart, so perhaps we just need to update the version? See https://github.com/helm/charts/issues/21446 for more information.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
#### Is this a new chart

No

#### What this PR does / why we need it:

Fixes an issue with the spinnaker chart.

#### Which issue this PR fixes

Fixes #23878

#### Special notes for your reviewer:

This is my first Chart contribution, I hope I've done it right.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
CC @viglesiasce @ezimanyi @dwardu89 @paulczar

**Comment by johanbrandhorst** [comment]
Not sure why the linter failed, I ran
```
$ helm dependency update
```
to generate the `requirements.lock` changes.

Further, when I tried generating this locally using
```
$ helm template -f values.yaml --version 2.2.4 . > spinnaker.yaml
```
It contains references to `RELEASE-NAME` in a way that means the generated yaml isn't installable. What did I do wrong :grimacing:?

**Comment by mced** [comment]
@johanbrandhorst seems related to this https://github.com/ssl-hep/ServiceX/issues/215#issuecomment-719122324

**Comment by dwardu89** [comment]
@mced There is a PR to move off this repository and onto another repository because helm/charts is going to be deprecated. Can you submit your PR changes to https://github.com/dwardu89/helm-charts/   instead please.


https://github.com/helm/charts/pull/23924


This PR is related to some internal discussions that were sent around to the devs in the OWNERS file.

**Comment by mced** [comment]
@johanbrandhorst I cherrypicked your changes on the new repo managed by @dwardu89

**Comment by johanbrandhorst** [comment]
Sweet, thanks, I'll close this PR

**Pull request closed without merging**
