### PR TITLE
[stable/efs-provisioner] Add podLabels support

### LINKED ISSUE #22289: [stable/efs-provisioner] podLabels support
**Is your feature request related to a problem? Please describe.**
stable/efs-provisioner currently only allows setting podAnnotations but not podLabels.
While I'm trying to collect metrics for services grouped by labels with Prometheus. `kube-state-metrics` which I use to collect metrics does not allow to select metrics by annotations.

**Describe the solution you'd like**
I would like to have the ability to set additional pod labels, by specifying them on values.yaml `podLabels`.

**Describe alternatives you've considered**
To do custom kubectl label after helm is installed.

**Additional context**
e.g. https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L79

### PR DESCRIPTION
**Pull request by rvolykh**
Signed-off-by: Roman Volykh <rvolykh@gmail.com>

#### What this PR does / why we need it:
Useful for Prometheus metrics aggregation.

#### Which issue this PR fixes
  - fixes #22289 

#### Special notes for your reviewer:
I've bumped patch version, is it okey, or minor version should be bumped instead?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by mariusv — APPROVED** [review]

**Comment by rvolykh** [comment]
Hello @mariusv,

I have no ability to add the label `lgtm`. Or we are waiting for @hareku?

**Pull request merged**
