### PR TITLE
[incubator/ibm-blockchain-channel] Add IBM Blockchain Channel

### PR DESCRIPTION
**Pull request by some-ibmer**
Source code located in the following repository:

- https://github.com/IBM-Blockchain/ibm-container-service

### CODE REVIEW

**Comment by unguiculus** [comment]
See comments on #2071.

**Comment by some-ibmer** [comment]
@unguiculus, changes have been added.

**Comment by some-ibmer** [comment]
@unguiculus, the templates should be namespaced now.

**Comment by some-ibmer** [comment]
@unguiculus, this PR should be up-to-date with the requested changes from https://github.com/kubernetes/charts/pull/2071.

**Comment by some-ibmer** [comment]
@unguiculus, I'm not sure why the ci/circleci cannot find the tests [here](https://github.com/kubernetes/charts/pull/2070/files#diff-767610df29138faa1d3acb4d321cc432).

**Pull request closed without merging**
