### PR TITLE
[stable/prometheus-operator] Update CRDs from upstream

### PR DESCRIPTION
**Pull request by jbfavre**
#### What this PR does / why we need it:
Update provided CRDs from upstream to get them aligned with 0.37.0 release of prometheus-operator.

#### Which issue this PR fixes
  - might explain https://github.com/coreos/prometheus-operator/issues/3088

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mikesplain** [comment]
ping @jbfavre, mind rebasing and trying to get this in? We're running into this with new clusters.

**Comment by jbfavre** [comment]
@mikesplain thanks for the ping.
I'll take of it, but since prometheus-operator released 0.38.0, I think I'll decline this PR and open a new one for 0.38.0
We're running it on multiple clusters without issues for days now

**Comment by jbfavre** [comment]
Overrided by #21829

**Pull request closed without merging**
