### PR TITLE
Adding CraftCMS Chart

### PR DESCRIPTION
**Pull request by dn-ysa**
#### What this PR does / why we need it:

CraftCMS Helm Chart added to Incubator

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by pa-yourserveradmin-com** [comment]
Hi everyone. Do you have any updates? May be something can be changed / improved in order to bring closer this PR review?

**Comment by XedMada** [comment]
Would be lovely to see this advanced. Even better if the chart added an istio config option.

**Comment by dn-ysa** [comment]
Hi @XedMada ,

Thanks for the interest in this chart! I'll work on adding Istio there. Not sure if I can do it fast, but it will definitely be added

**Pull request closed without merging**
