### PR TITLE
[stable/coredns]: extra secret volumes support added

### PR DESCRIPTION
**Pull request by vi7**
#### What this PR does / why we need it:

Implemented support of the extra secrets.
Example usecase: connection to the TLS secured etcd backend through etcd client plugin (https://coredns.io/plugins/etcd/) which requires access to the certificate data.

#### Which issue this PR fixes

n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by vi7** [comment]
please review
/assign @shashidharatd
/assign @andor44

**Review by andor44 — APPROVED** [review]

**Comment by vi7** [comment]
Hi @andor44 @shashidharatd , any updates on this PR?

**Comment by andor44** [comment]
lgtm

**Comment by vi7** [comment]
> /lgtm

@andor44 seems that edited message hasn't been accepted by the CI properly, could you please send lgtm one more time?

**Comment by andor44** [comment]
here we go again
/lgtm

**Pull request merged**
