### PR TITLE
[stable/grafana] Add support to get charts from a git repository

### PR DESCRIPTION
**Pull request by cesaralbloz**
Signed-off-by: cesaralbloz <cesaralbloz@hotmail.com>

#### What this PR does / why we need it:
Add support for download dashboards from git repositories

#### Which issue this PR fixes
No fixes

#### Special notes for your reviewer:
Curl has been replaced by wget because the alpine/git image brings with wget instead of curl

### CODE REVIEW

**Comment by maorfr** [comment]
Hey @cesaralbloz,

Thanks for your contribution!
I think this is a great feature to have. But isn't this already possible using the `url` attribute?
https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L211

Consider the following:

If you want to install a dashboard located in:
https://github.com/repo/grafana-dashboards/blob/master/dashboards/dashboard.json
You can probably use the raw url:
https://raw.githubusercontent.com/repo/grafana-dashboards/master/dashboards/dashboard.json

Will that work?

If so, I admit that we can use some documentation to tell this story ;)

What do you think?

**Comment by cesaralbloz** [comment]
Your are OK about the github use case that allows HTTP GET without authentication. The idea of the change is allow to use private git repositories where there is not a public URL or getting files one by one.  In this cases, we need to clone the repository and copy the file after that. The clone repository is the more cost of operation so I added a simple mechanism for avoiding several clone repository operations

**Comment by maorfr** [comment]
Thanks for your reply.

Private repos will require authentication, won't they?

**Comment by cesaralbloz** [comment]
I do not have a github private repository so I do not know the behaviour but I suppose that it will be the same that I an working in my job. We have charts in a corporate git/gerrit repopitory that requires authentication and authorization for cloning files. Git clone with HTTPS works but it does not support/allow the checkout of individual files

**Comment by maorfr** [comment]
Have you tested that this addition works with private repos which require authentication?

**Comment by cesaralbloz** [comment]
Yes. I have tested it in my work. Authentication details would go included in the gitrepo value for example:

https://gituser:gitpass@private_git_server/owner/repo.git

**Comment by maorfr** [comment]
Will the same work using the `url` field?
I think it is crucial to avoid cloning a repo, it is a huge overhead.

**Comment by cesaralbloz** [comment]
I am agree that cloning the repository is an overhead so I added an check that avoids repeat the cloning operation if the repo has been cloned before. The problem that i have in my use case is thet I cannot get individual files from the git server as allows github so I have to add the clone operation before copy the file to the charts directory

**Comment by maorfr** [comment]
I have a feeling there is a solution that does not include cloning the entire repo. Even if we were to avoid cloning the same repo twice, this is still an overhead. I urge you to investigate further and try to find an alternative solution that works without cloning and also works with your repository. I would investigate a private token option for authentication, among other things.

Your contribution is appreciated!

**Pull request closed without merging**
