### PR TITLE
[stable/puppetserver] Add Puppet Server Helm Chart

### PR DESCRIPTION
**Pull request by Xtigyro**
#### Is this a new chart
Yes, it is a new chart.
#### What this PR does / why we need it:
This PR deploys everything required to run in a flexible manner a Puppet Server in Kubernetes and be discoverable by internal and external to the K8s cluster Puppet Agents.
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Xtigyro** [comment]
` ✖︎ puppetserver => (version: "0.2.0", path: "stable/puppetserver") > Error validating maintainer 'Miroslav Hadzhiev': 404 Not Found`

How can such error be fixed?

**Comment by Xtigyro** [comment]
A bug in the official latest Docker image of PuppetDB was introduced 8 hours ago. 
Tracking bug report: https://github.com/puppetlabs/pupperware/issues/157.

It can be worked around by using the previous version of the image: `6.5.0`. 

If the review of the chart is going to start before the bug is resolved - let me know so that we can include the bug-free version - `6.5.0`.

**Comment by Xtigyro** [comment]
The PR is in a fully functional state again - a fix has been provided for issue: https://github.com/puppetlabs/pupperware/issues/157.

**Comment by Xtigyro** [comment]
@zanhsieh @prydonius @lachie83 

Tests - passed.

**Comment by zanhsieh** [comment]
@Xtigyro 
Per @maorfr commented in kubernetes slack, we think it's better you host yourself. The value of helm chart or even a software is up-to-date, agile, and passion on it. Currently we are short of OWNERS to achieve that ideal state. See @maorfr previous comment below and learn how to self-hosting a helm chart:

https://github.com/helm/charts/pull/5071#issuecomment-520707994

**Comment by Xtigyro** [comment]
> 
> 
> @Xtigyro
> Per @maorfr commented in kubernetes slack, we think it's better you host yourself. The value of helm chart or even a software is up-to-date, agile, and passion on it. Currently we are short of OWNERS to achieve that ideal state. See @maorfr previous comment below and learn how to self-hosting a helm chart:
> 
> [#5071 (comment)](https://github.com/helm/charts/pull/5071#issuecomment-520707994)

@zanhsieh Me, Scott Cressi and Puppetlabs themselves agreed to help keep up-to-date the chart.

**Comment by Xtigyro** [comment]
Once the tests completed fine but even though just the `OWNERS` and `Chart.yaml` were changed afterwards - now they fail with a timeout while deleting the K8s namespace.

Is that really a problem of the chart?

**Comment by zanhsieh** [comment]
@Xtigyro 
If you would like to push this chart as stable, I suggest you slack (kubernetes.slack.com; search via their ids or names) to one of helm member to be a new chart as well as the OWNERS. Most of helm members are there, although they might immediately respond to you since we all have daily job(s).

**Comment by Xtigyro** [comment]
> @Xtigyro
> If you would like to push this chart as stable, I suggest you slack (kubernetes.slack.com; search via their ids or names) 

@zanhsieh 
Could you please send me an invitation to `miroslav.hadzhiev@gmail.com` for that `kubernetes.slack.com`?

**Comment by underscorgan** [comment]
👍

**Comment by maorfr** [comment]
Would it make sense for PuppetLabs to self host?

cc @underscorgan

**Comment by underscorgan** [comment]
@maorfr As far as I know we don't have an existing hosted helm registry but I can ask around and look into it.

**Comment by Xtigyro** [comment]
Finished some changes:
- Add Optional Static Data Volumes.
- Add Configurable PVC's Size.
- Add Optional PVC's Annotations.
- Add optional extra Pod Annotations.
- Add optional Pod Priority Scheduling.
- Add LICENSE.
- Add CHANGELOG.
- Update README.
- Add "nodeSelector", "affinity" and "tolerations" for Pod Deployments.
- Bump component versions. Bump chart version.
- Improve Values' comments.
- Fixes.

**Comment by Xtigyro** [comment]
- Add Ingress.
- Improve Tmpl Helpers.
- Improve `NOTES`.

@maorfr @underscorgan @zanhsieh 

Some more useful stuff has been finished.

**Comment by Xtigyro** [comment]
- Add PV/PVC Selector.

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

@underscorgan ping on Slack if you need any help setting up the Helm repo at Puppet Labs 😸

**Pull request closed without merging**
