### PR TITLE
[stable/kubernetes-dashboard] Set replica count

### LINKED ISSUE #4282: [stable/kubernetes-dashboard] support multiple replicas
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

The chart has no configurable value for the amount of replicas to create for the dashboard deployment. For better availability, I'ld like to be able to scale the dashboard.

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

Allow the user to configure the replica count of the Kubernetes
dashboard deployment.

Make the `deploymentStrategy` configurable as well.

Tested by creating a release with `replicaCount=3`, and verifying three
pods were created.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4282

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/assign @viglesiasce
@kfox1111 

thanks :)

**Comment by mxey** [comment]
FYI I had already opened https://github.com/kubernetes/charts/pull/5419, and there were reservations whether the Dashboard supports multiple replicas.

**Comment by mattjmcnaughton** [comment]
Ah thanks for letting me know @mxey - closing this in favor of your pr. Do you mind linking to #4282 from your pull request? Thanks!

**Pull request closed without merging**
