### PR TITLE
[WIP] Cassandra

### PR DESCRIPTION
**Pull request by chrislovecnm**
This is a WIP ... nuff said :)  Will be done before kubecon, cause it is in my demo ... SGTM

### CODE REVIEW

**Comment by lachie83** [comment]
Awesome! Excited to see this chart. I wrote one pre-petset about a year ago.

**Comment by krallistic** [comment]
Any Updates, or still working on it?

**Comment by chrislovecnm** [comment]
Still working on it, work is nuts. If u want to pick it up, I would not have any problem with that.

**Comment by chrislovecnm** [comment]
I am going to close for now.  Hope I have time soon to finish.  If someone wants to pick this up ... have at it!!

**Pull request closed without merging**
