### PR TITLE
[stable/coredns] fix servicetype and label change

### PR DESCRIPTION
**Pull request by radhus**
#### What this PR does / why we need it:

Bug fixes to the chart to avoid deployment failures.

Ping @minrk @andor44

### CODE REVIEW

**Comment by mrueg** [comment]
See also: https://github.com/helm/charts/pull/7736

**Comment by ccatlett2000** [comment]
I'd be in favor of just closing that PR and merging this one - as long as I can finally deploy the stable branch of coredns

**Comment by minrk** [comment]
I've no objection to closing my PR. Whatever gets this fixed sooner.

**Comment by andor44** [comment]
lgtm

**Comment by shashidharatd** [comment]
Thanks @radhus & @minrk for the fixes.
lgtm

**Comment by ChristopherJMiller** [comment]
Is there a workaround for this issue?

**Comment by radhus** [comment]
How do I find a trusted user who can review and test this?

**Comment by mrueg** [comment]
Not sure why https://github.com/helm/charts/pull/8404 did get merged while this did not @davidkarlsen ?

**Comment by ccatlett2000** [comment]
I don't know how anyone can deploy coredns via helm stable at all right now, as the label prevents creating the deployment.

I don't know why service type is a separate variable it seems non-intuitive and confusing, I like this solution much better.
Anyways cc @radhus #8404 will require changes to this PR (either adapting to it or reverting it).

**Pull request closed without merging**
