### PR TITLE
TLS support for ingress

### PR DESCRIPTION
**Pull request by devlounge**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
The chart has a changelog file which should be udated as well.

**Comment by unguiculus** [comment]
cc @varshavaradarajan

**Comment by varshavaradarajan** [comment]
@devlounge - can you please rebase? There was already version 1.0.7 released for tls support. https://github.com/kubernetes/charts/pull/5122/files

**Comment by GaneshSPatil** [comment]
@devlounge -- can you rebase the PR?

**Comment by GaneshSPatil** [comment]
@devlounge -- any updates on the PR?

**Pull request closed without merging**
