### PR TITLE
[stable/jaeger-operator] Introduce crds directory for compatibility with Helm v3

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

#### What this PR does / why we need it:

- add crds dir for helm 3
- add `template/crds.yaml` for helm 2

Which issue this PR fixes
Related to Issue #19008

Special notes for your reviewer:
This is not a complete migration to Helm v3. This PR make the Chart installable with Helm 3.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by scottrigby** [comment]
This does not look correct. You removed all the [Helm default labels](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#names-and-labels), and deleted the CRD entirely. Was this an accident?

**Comment by daixiang0** [comment]
sorry, i miss some files:(

**Comment by daixiang0** [comment]
@scottrigby mind have a look?

**Pull request closed without merging**
