### PR TITLE
[stable/postgresql] add docs for existingSecret structure

### LINKED ISSUE #19888: [stable/postgresql] doc: structure of existingSecret
**Describe the bug**

The chart documentation does not specify the structure of `existingSecret`. I need to specify a password for postgres and for user database. How can I do it with the secret?

**Version of Helm and Kubernetes**:

na

**Which chart**:

stable/postgresql

**What happened**:

n.a

**What you expected to happen**:

n.a.

**How to reproduce it** (as minimally and precisely as possible):

n.a.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by dani8art**
Signed-off-by: darteaga <darteaga@bitnami.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

Add documentation for clarifying the structure of the `existingSecret` so users can create it easily.

#### Which issue this PR fixes

  - fixes #19888

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rafariossaa** [comment]
/LGTM
Please @sameersbn , could you merge this ?

**Comment by carrodher** [comment]
The CI/CD failed because the chart version is not ok. Needs a version bump.

**Pull request merged**
