### PR TITLE
Fixed typo in sample values file

### PR DESCRIPTION
**Pull request by ghost**
#### What this PR does / why we need it:
Fixes a simple typo in the sample values file

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by carrodher** [comment]
Can you explain the advantage of using `my_init_script.sh: |+` instead of `my_init_script.sh: |`?

IMHO, `|` is the default behavior, using it, any further trailing newlines will be stripped, by using `|+` all the trailing newlines are conserved, but, what are the advantages of adding it in a bash script?

**Comment by k1-hedayati** [comment]
Hey @carrodher, my intention for this PR wasn't adding `|+` it was adding a space after the colon, `my_init_script.sh:|` to `my_init_script.sh: |` to fix the syntax error when running the chart and after that thought `|+` is safer than `|` so changed that as well.

**Comment by carrodher** [comment]
Hi, thanks for the fix related to the necessary space. About the `|+` I still have some concerns. Why do you think it is safer? I was looking at other charts in this repository including bash code using this method. There is no other chart using `|+` for bash scripts, all of them are using `|` or `|-`:
```bash
$ ag 'sh: \|\+$' -l | wc -l
       0
$ ag 'sh: \|\-$' -l | wc -l
      32
$ ag 'sh: \|$' -l | wc -l
      26
```
I just found valuable information in this [thread](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210).

**Comment by k1-hedayati** [comment]
I think it's safer because it keeps the line feed and trailing blank lines, so basically no change in the input that might introduce some issues in certain cases (for example somebody coding in [Whitespace language](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) :) ). But I've no insistence on it I can change it back to `|`.

**Comment by carrodher** [comment]
Again thanks for the contribution! Maybe in some context, it is better to use `|+` (as you rightly said in whitespace language), but in this specific case is a bash script where removing the trailing blank lines is not unsafe, in the same way `|`, also keeps the line feed.

Before proceeding with the merge, once applied the suggestions, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by k1-hedayati** [comment]
Done.

**Comment by cpanato** [comment]
@k1-hedayati please update your branch with the latest master and bump the chart version. thanks

**Comment by k1-hedayati** [comment]
@cpanato Chart version has already been updated

**Comment by cpanato** [comment]
@k1-hedayati I dont see the chart version in your commits. Please update to `3.18.3`

**Review by cpanato — APPROVED** [review]

**Pull request merged**
