### PR TITLE
stable/prometheus-operator - Support additional scrape configs if already de…

### LINKED ISSUE #23133: [stable/prometheus-operator] Allow custom additionalScrapeConfigs
For the moment I am using additional scrape configs to monitor custom resources outside of the Kubernetes cluster. The default implementation of prometheus will always look for these in the additional-scrape-confg Secret stored in kubernetes. 

I need prometheus to check a different ConfigMap for these as I don't want to have all the additional scrape configs in the values.yaml file as I'm building the configuration using a range over a few values, having them inside the values file will mean more work into maintaining them.

**Is your feature request related to a problem? Please describe.**
Not a problem, an improvement

**Describe the solution you'd like**
An additional if condition in the prometheus template, basically if additionalscrapeconfigCM is true to mount the ConfigMap I specify rather than the defaulted one. (templates/prometheus/prometheus.yml)

**Describe alternatives you've considered**
For the moment I'm setting a "dummy" additional scrape config, this works with helm2 but didn't test with helm3, basically if I do a fresh install of operator I will comment the AdditionalScrapeConfigs so the default one doesn't get deployed (it errors out) and my custom one gets deployed. I then uncomment and upgrade twice, one enables and changes the cm to the dummy scrapeconfig and the 2nd upgrade changes the dummy one to the one I'm deploying.

### PR DESCRIPTION
**Pull request by alexanderccc**
…ployed

#### What this PR does / why we need it:
Add support for existing prometheus scrape configurations

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #23133

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by alexanderccc** [comment]
@vsliouniaev @bismarck @gianrubio Please review and let me know if this can be implemented

**Comment by vsliouniaev** [comment]
/hold

This is already possible to do by using `.Values.prometheus.prometheusSpec.additionalScrapeConfigsExternal`. You will need to create a secret with the appropriate name and key.

**Comment by alexanderccc** [comment]
@vsliouniaev ok, but can we extend that option to allow custom naming and keys for prometheus or is it just not worth it?

**Comment by vsliouniaev** [comment]
I don't think it makes sense to support both. I think it would be fine to drop the current version in favour of yours, but you would need to bump the chart major version and update the doc here: https://github.com/helm/charts/tree/master/stable/prometheus-operator#upgrading-an-existing-release-to-a-new-major-version

You will also need to add sign off to your commits to make CI pass and clean up whatever the linter is complaining about.

**Comment by alexanderccc** [comment]
@vsliouniaev Sure, that's not a problem, but in regards to the current implementation, should I also remove the additionalScrapeConfigsExternal from the values and the if condition inside the prometheus template or should it be kept for backwards compatibility?

**Comment by vsliouniaev** [comment]
I think you should remove it, bump the major version and explain that for anyone using this feature in the old chart will need to switch to the new one you are introducing.

**Comment by alexanderccc** [comment]
@vsliouniaev I can't seem to amend my previous commits to add the sign-off, I'll close this pr and create another clean one.

**Pull request closed without merging**
