### PR TITLE
[stable/kubernetes-dashboard] Support pod annotations

### PR DESCRIPTION
**Pull request by QuingKhaos**
#### What this PR does / why we need it:

This adds annotations to the pod template, for example to add `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` annotation.

cc @kfox1111 

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by kfox1111** [comment]
lgtm

**Comment by kfox1111** [comment]
ping

**Review by kfox1111 — CHANGES_REQUESTED** [review]
Please update the version to 0.10.3

Looks like I have approval rights finally, so I should be able to help speed this along now. Sorry for the delays.

**Comment by EmiiKhaos** [comment]
Rebased onto master and bumped version to 1.1.0

**Pull request merged**
