### PR TITLE
[stable/drone] Add update to pipeline role

### PR DESCRIPTION
**Pull request by aviettran**
See:

https://github.com/helm/charts/issues/20944

@christian-roggia @paulczar @zakkg3

### CODE REVIEW

**Comment by LeankitJSmith** [comment]
This change worked for us.

**Comment by jltrippett** [comment]
Please merge this change. For a build using drone-runners, the pipelines fail with this error due to lacking the update verb:
image

**Comment by christian-roggia** [comment]
As the chart is deprecated this will be one of the last PR to be merged, please solve the conflicts and I will go ahead and merge it.

**Comment by aviettran** [comment]
@christian-roggia what are the conflicts? There are no merge conflicts.

**Comment by christian-roggia** [comment]
@aviettran you need to Sign-off the commit and bump the chart version

**Comment by aviettran** [comment]
@christian-roggia can this be merged?

**Comment by christian-roggia** [comment]
@aviettran the build is still failing, please bump the chart version.

**Pull request closed without merging**
