### PR TITLE
[stable/postgresql] Add back custom metrics.

### PR DESCRIPTION
**Pull request by desaintmartin**
Solves https://github.com/helm/charts/issues/15798

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks so much for adding this back @desaintmartin !!

**Comment by juan131** [comment]
Hi @desaintmartin 

Could you please rebase the PR from master and address the conflicts?

**Comment by desaintmartin** [comment]
Done!

**Pull request merged**
