### PR TITLE
[stable/sentry] delete hooks on success or before running again

### PR DESCRIPTION
**Pull request by mrbrownt**
#### What this PR does / why we need it:
This will cleanup the db init and user create job if they succeed. It will also delete them if the install fails and you run install again, that way new db init and user create jobs will run again.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by mattfarina** [comment]
cc @rothgar 
/ok-to-test

**Comment by rothgar** [comment]
Oh thanks for adding that! Is that a newer helm option? I don't remember seeing it when I originally made the chart and badly wanted it.

**Comment by mrbrownt** [comment]
@rothgar sure thing! I'm not sure, only been writing helm charts for about a month now.

**Review by mattfarina — APPROVED** [review]

**Comment by mrbrownt** [comment]
I resolved a merge conflict so the lgtm label got stripped @mattfarina

**Pull request merged**
