### PR TITLE
[stable/nginx-ingress] Added tolerations support for nginx-ingress

### PR DESCRIPTION
**Pull request by leoh0**
Support tolerations for nginx-ingress.

### CODE REVIEW

**Comment by snelis** [comment]
ah sweet - was about to make the same PR :)

**Review by mgoodness — CHANGES_REQUESTED** [review]
Great contribution, @leoh0; thanks! Unfortunately, I lost your author info during rebase. Go ahead and bump the chart version and I'll make sure you get full credit 😃

**Comment by leoh0** [comment]
@mgoodness No problem. 😃

**Review by mgoodness — APPROVED** [review]

**Pull request merged**
