### PR TITLE
[stable/concourse] Change Concourse links

### PR DESCRIPTION
**Pull request by arbourd**
Concourse.ci was hijacked and the team has made the decision to move to
https://concourse-ci.org:

https://medium.com/concourse-ci/were-switchin-domains-5597dcd0b48b

### CODE REVIEW

**Comment by arbourd** [comment]
Signed the CLA

**Review by william-tran — APPROVED** [review]

**Comment by william-tran** [comment]
@arbourd Thanks for the quick action on this one, and for fixing the version typo.

**Pull request merged**
