### PR TITLE
[stable/fluent-bit]add use_journal

### PR DESCRIPTION
**Pull request by texasbobs**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Adds the ability to specify the use_journal filter parameter.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by texasbobs** [comment]
Is this PR waiting on something from me?

**Comment by texasbobs** [comment]
Maybe @kfox1111  or @edsiper  can help?

**Comment by Towmeykaw** [comment]
Sorry for the wait. Shouldn't the default value be false since it's just a Boolean flag? Other then that it looks fine.

**Comment by texasbobs** [comment]
I can update that.  Thanks, @Towmeykaw.

**Pull request merged**
