### PR TITLE
[incubator/jaeger] Add missing implementation of cmdLineParams for co…

### PR DESCRIPTION
**Pull request by hypnoce**
Add missing implementation of cmdLineParams for collector and query deployments.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by hypnoce** [comment]
Is there any issue with this PR ?

**Comment by hypnoce** [comment]
Is there anything I have to change ?

**Comment by hypnoce** [comment]
@paulczar

**Comment by hypnoce** [comment]
Rebased. Can you please review ?

**Comment by hypnoce** [comment]
@viglesiasce @foxish Is anyone reviewing this PR ?

Thanks

**Comment by hypnoce** [comment]
Any chance this PR get merged ?

**Comment by hypnoce** [comment]
@mattfarina You were suggested as a reviewer.

**Comment by mattfarina** [comment]
cc @dvonthenen @mikelorant @pavelnikolov

**Review by mattfarina — APPROVED** [review]

**Comment by pavelnikolov** [comment]
LGTM

**Pull request merged**
