### PR TITLE
[stable/nginx-ingress] Remove checksum/config from DaemonSet template

### PR DESCRIPTION
**Pull request by robinkb**
#### What this PR does / why we need it:

The DaemonSet template still has a checksum/config annotation to trigger a rollout of the Ingress Controllers after a config change. Recreating the controllers after a configmap change is not necessary, and this annotation was already removed from the Deployment template in https://github.com/helm/charts/pull/5199.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by robinkb** [comment]
My local and GitHub e-mail settings were inconsistent. This was fixed on GitHub, but the DCO checks have not re-run.

**Comment by cpanato** [comment]
@robinkb maybe can you rebase?

**Pull request merged**
