### PR TITLE
[stable/postgresql] PostgreSQL metrics need the right username

### PR DESCRIPTION
**Pull request by mlaccetti**
**What this PR does / why we need it**:

If we use `POSTGERS_USER` = `sonar`, metrics go boom. So, let's use the same user for metrics as we created when we setup PostgreSQL!

**Which issue this PR fixes**:

N/A (PR as fix)

**Special notes for your reviewer**:

Easy, right?!

### CODE REVIEW

**Comment by mlaccetti** [comment]
@scottrigby any chance you can take a peek?

**Comment by mlaccetti** [comment]
@unguiculus Last time I issued a PR, I was told to do a merge, not a rebase, hence the giant swarm of commits.

Aside from that, should be ready to go; bumped the version, since it seems somebody else got there between submitting the PR and the review.

**Comment by unguiculus** [comment]
Merging is the correct thing to do but something went wrong. There shouldn't be a giant swarm of commits.

**Comment by unguiculus** [comment]
Let me know if you need help.

**Comment by mlaccetti** [comment]
Any help is appreciated - I never know when I get git right...

**Comment by mlaccetti** [comment]
@unguiculus I think I fixed it... PR is back to `XS`!

**Comment by unguiculus** [comment]
So, it looks like you got it right on your own. ;)

**Pull request merged**
