### PR TITLE
Adding helm exporter annotations

### PR DESCRIPTION
**Pull request by pvnrao**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sstarcher** [comment]
I believe podAnnotations is the normal wording people use.  Would it make sense to just add these as default annotations or to put them behind a flag vs having the user need to know what to add?

**Comment by pvnrao** [comment]
In the other charts, they followed a similar pattern (annotations). I think better if we leave it to the user.

**Comment by sstarcher** [comment]
Plenty of charts follow the pattern of including the annotations by default.  The user does not have control over what the annotations need to be they are determined by the software.

**Comment by sstarcher** [comment]
I would recommend putting these annotations on the service.

**Comment by davidkarlsen** [comment]
There are already annotations on the service for this: https://github.com/helm/charts/blob/master/stable/helm-exporter/templates/service.yaml#L11

**Comment by sstarcher** [comment]
The helm/charts repo is being deprecated.  I have redone the chart for helm v3 and moved it out of this repo. https://github.com/sstarcher/helm-exporter/tree/master/helm

**Comment by davidkarlsen** [comment]
Closing as chart is deprecated and moved.

**Pull request closed without merging**
