### PR TITLE
[WIP] Add fluentd-elasticsearch Chart

### PR DESCRIPTION
**Pull request by rendhalver**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by mattfarina** [comment]
When I try to run this I'm getting an error in my pod that reads:

```
config error file="/fluentd/etc/fluentd.conf" error="Unknown output plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Comment by rendhalver** [comment]
Thanks @mattfarina I will see what's going on there.

**Comment by rendhalver** [comment]
@mattfarina the docs I found for setting this up were written by the people at Tectonic.
I was overriding the image locally with the tectonic image (quay.io/coreos/fluentd-kubernetes).
It looks like fluent/fluentd-kubernetes-daemonset doesn't have the rewrite_tag_filter plugin.
Not sure of the best way to solve that. I will see what else is different with the Tectonic image and work out what to do from there.

**Comment by kenden** [comment]
Thanks @rendhalver .
It would be nice to get a generic chart for fluentd that works with all backend (cloudwatch, elasticsearch, logstash...).  Any chance to incorporate this PR into https://github.com/kubernetes/charts/tree/master/incubator/fluentd-cloudwatch ?

**Comment by rendhalver** [comment]
We could make a generic fluentd chart that amalgamates them.
They run on different images so we would need a way use the right one and let people customise them if needed.

**Comment by rendhalver** [comment]
We could use this chart as a start on the generic chart.
I am happy to rename it to fluentd and then we can pull in support for cloudwatch and logstash.
Sound like a plan?

**Comment by rendhalver** [comment]
I am thinking I will switch to the Tectonic image I have been using.
It is based on the official image and adds a few useful plugins.
I don't think any of those are specific to Tectonic.

**Comment by kenden** [comment]
As far as I can tell, the [tectonic image](https://github.com/coreos/tectonic-docs/blob/master/Documentation/files/logging/fluentd-aggregator-deployment.yaml#L25) is `quay.io/coreos/fluentd-kubernetes:v0.12-debian-elasticsearch`, which is created from 
https://github.com/coreos/fluentd-kubernetes-daemonset,
and is 14 commits / 7 months behind the official image from fluentd https://github.com/fluent/fluentd-kubernetes-daemonset at https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/  ?

**Comment by rendhalver** [comment]
This is true yes.
As I mentioned earlier I am using that Tectonic image because the example I found that worked for me was written by the people at Tectonic and it used that image.
It does include some extra plugins which I am also using in the config.
If people don't want to use those plugins I will just change the config to not use them by default and work out a way generate the configs so I can include those options locally.
If we are going to build a Chart that will work everywhere I will need to do that anyway.

**Comment by kenden** [comment]
@rendhalver Thanks for the details. Where do you see extra plugins? It seems everything in the coreos version is in the official version? https://github.com/fluent/fluentd-kubernetes-daemonset/compare/master...coreos:master

**Comment by rendhalver** [comment]
Hrm. Weird. The PR was originally using the fluent/fluentd-kubernetes-daemonset image and when it started the pod it complained that the rewrite_tag_filter plugin didn't exist.
I was running the coreos image locally and that wasn't happening for me.

**Comment by rendhalver** [comment]
Those repos are right as far as I can tell too.

**Comment by rendhalver** [comment]
My current thoughts on this are to rename this to something more explicit like fluentd-daemonset so it's obvious what it's used for and then setup the option to configure where to send the logs and make the config more easy to change in your deployment.

**Comment by rendhalver** [comment]
@kenden I have redone this one in #3560

**Pull request closed without merging**
