### PR TITLE
[stable/jenkins] Make SecurityRealm and AuthorizationStrategy configurable

### LINKED ISSUE #9402: [stable/jenkins] make securityRealm and authorizationStrategy configurable
FEATURE REQUEST

Currently, securityRealm and authorizationStrategy are hardcoded in Jenkins' config.xml. As far as I can tell, the only way to change them are:

- Changing after install manually, possibly through the web UI. This does not play well with `Master.OverwriteConfig`.
- Setting it up dynamically on an init script. I had an early version of this, quite convoluted. Not sure if it works seamlessly with `Master.OverwriteConfig` either.
- Using a fully custom config map.

I would be great to be able to set this up in an easier way. I am currently using a modified version of chart, adding additional values for hooking XML fragments in. This is how it looks:

<details><summary>Example patch</summary>
<p>

```diff
From 11e19a064adf21cab1120984f17324c565ff11d8 Mon Sep 17 00:00:00 2001
From: "Santiago M. Mola" <santi@mola.io>
Date: Wed, 29 Aug 2018 14:21:08 +0200
Subject: [PATCH 1/2] jenkins: configurable security

This is a very crude approach, just allowing injecting XML for security realm and authorization strategy.

Signed-off-by: Santiago M. Mola <santi@mola.io>
---
 jenkins/Chart.yaml            |  2 +-
 jenkins/templates/config.yaml | 16 ++++++++++++----
 jenkins/values.yaml           |  3 +++
 3 files changed, 16 insertions(+), 5 deletions(-)

diff --git a/jenkins/Chart.yaml b/jenkins/Chart.yaml
index ba2add7..f97e903 100755
--- a/jenkins/Chart.yaml
+++ b/jenkins/Chart.yaml
@@ -1,6 +1,6 @@
 name: jenkins
 home: https://jenkins.io/
-version: 0.18.0-srcd2
+version: 0.18.0-srcd3
 appVersion: 2.121.3
 description: Open source continuous integration server. It supports multiple SCM tools
   including CVS, Subversion and Git. It can execute Apache Ant and Apache Maven-based
diff --git a/jenkins/templates/config.yaml b/jenkins/templates/config.yaml
index 3003b1f..1255ded 100644
--- a/jenkins/templates/config.yaml
+++ b/jenkins/templates/config.yaml
@@ -13,10 +13,18 @@ data:
       <numExecutors>0</numExecutors>
       <mode>NORMAL</mode>
       <useSecurity>{{ .Values.Master.UseSecurity }}</useSecurity>
-      <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
-        <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
-      </authorizationStrategy>
-      <securityRealm class="hudson.security.LegacySecurityRealm"/>
+{{- if not (empty .Values.Master.ConfigXml.AuthorizationStrategy ) }}
+{{ .Values.Master.ConfigXml.AuthorizationStrategy | indent 4 }}
+{{- else }}
+        <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
+          <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
+        </authorizationStrategy>
+{{- end }}
+{{- if not (empty .Values.Master.ConfigXml.SecurityRealm ) }}
+{{ .Values.Master.ConfigXml.SecurityRealm | indent 4 }}
+{{- else }}
+        <securityRealm class="hudson.security.LegacySecurityRealm"/>
+{{- end }}
       <disableRememberMe>false</disableRememberMe>
       <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
       <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULLNAME}</workspaceDir>
diff --git a/jenkins/values.yaml b/jenkins/values.yaml
index b29313e..d6481fe 100644
--- a/jenkins/values.yaml
+++ b/jenkins/values.yaml
@@ -137,6 +137,9 @@ Master:
     # - secretName: jenkins.cluster.local
     #   hosts:
     #     - jenkins.cluster.local
+  ConfigXml:
+    SecurityRealm:
+    AuthorizationStrategy:
 
 Agent:
   Enabled: true
-- 
2.18.0
```
</p>
</details>

Would a PR for this be welcome? Or is there any other preferred method to do this?

### PR DESCRIPTION
**Pull request by meyskens**
#### What this PR does / why we need it:
makes securityRealm and authorizationStrategy configurable for use of other auth methods.

#### Which issue this PR fixes
  - fixes #9402

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

A big thank you to @smola for doing most of the work already in his issue!

### CODE REVIEW

**Comment by viglesiasce** [comment]
Thanks @meyskens! There was a [PR just merged](https://github.com/helm/charts/pull/9296) that implemented SecurityRealm but not the AuthorizationStrategy. Can you take a look at what needs to change here to accommodate?

**Comment by meyskens** [comment]
@viglesiasce I have rebased on master and changed my PR accordingly.

**Comment by viglesiasce** [comment]
Awesome! Thanks @meyskens!

/ok-to-test

**Pull request merged**
