### PR TITLE
[stable/prometheus] Add Blackbox exporter

### PR DESCRIPTION
**Pull request by sylr**
Manage an optional blackbox exporter for the prometheus server.

### CODE REVIEW

**Comment by thuandt** [comment]
@sylr I think blackbox exporter should be deploy as node-exporter.

Not `DaemonSets` but should be as other services/pods

**Comment by matthope** [comment]
Style/maintenance question - is it better to extend the existing `templates/server-deployment.yaml`, or add a new template?
In the long run, it'd be good to add in various other common exporters, so `templates/server-deployment.yaml` could get overly complex.

**Comment by amnk** [comment]
This would be great to have! Any chance we can merge this? @sylr do you maybe need any help?

**Comment by unguiculus** [comment]
Actually, we'd rather like to extract things to separate charts. There is a PR for a blackbox exporter (#3800). Once this is merged, it could be added as a dependency to Prometheus.

**Pull request closed without merging**
