### PR TITLE
[stable/spinnaker] replace lwander with ezimanyi in OWNERS

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Comment by lwander** [comment]
@ezimanyi

**Comment by ezimanyi** [comment]
@viglesiasce : It looks like this PR can't be merged until I'm a member of the org?  Are you able to send me an invite?  (It looks like you're an owner of the top-level `charts` repo.)  Thanks!

**Comment by viglesiasce** [comment]
Added, can you fix the DCO?

**Comment by viglesiasce** [comment]
Also the chart needs  a version bump:
https://circleci.com/gh/helm/charts/106580

**Pull request closed without merging**
