### PR TITLE
[stable/redis-ha] bump redis version

### PR DESCRIPTION
**Pull request by kimxogus**
Signed-off-by: Taehyun Kim <kgyoo8232@gmail.com>

no

#### What this PR does / why we need it:
1. ~~As haproxy metrics related service template is wrong, I had upgrade failure as below. This pr fixes haproxy-service template~~ Fixed in #18812 
```plain
UPGRADE FAILED
Error: render error in "redis-ha/templates/redis-haproxy-service.yaml": template: redis-ha/templates/redis-haproxy-service.yaml:32:20: executing "redis-ha/templates/redis-haproxy-service.yaml" at <.Values.metrics.portName>: nil pointer evaluating interface {}.portName
Error: UPGRADE FAILED: render error in "redis-ha/templates/redis-haproxy-service.yaml": template: redis-ha/templates/redis-haproxy-service.yaml:32:20: executing "redis-ha/templates/redis-haproxy-service.yaml" at <.Values.metrics.portName>: nil pointer evaluating interface {}.portName
```
2. Default redis version is now `5.0.6-alpine`

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
@kimxogus Thank you for the PR. The templating issue should be fixed now with  #18812 merged. If you want to fetch the latest changes, rebase, and bump the version again we can still get the new redis image merged.

**Comment by kimxogus** [comment]
@ssalaues Merged master and bumped chart patch version

**Comment by L3o-pold** [comment]
The app version was forgotten here https://github.com/helm/charts/blob/49b2a46e5e860c9f5b868b78963a052be4855bee/stable/redis-ha/Chart.yaml#L10

**Pull request merged**
