### PR TITLE
[stable/oauth2-proxy] fix PodDisruptionBudget.

### PR DESCRIPTION
**Pull request by desaintmartin**
Also change homepage.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
/lgtm

**Comment by scottrigby** [comment]
For reference, see https://github.com/helm/charts/pull/18073

**Comment by Miouge1** [comment]
Looks good, but it would have been nice to do `/ok-to-test` to see the CI values file in action (I didn't know that that was possible!)

**Comment by desaintmartin** [comment]
Bot can't merge until tests pass

And since we are collaborator, we do not need ok-to-test when we create a PR! Small privileges. ;)

**Comment by Miouge1** [comment]
OK got it, so it's just that the circleci output doesn't show up in the "checks" tab, but I tracked down the CI output to here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/19394/ :)

Cool stuff!

**Pull request merged**
