### PR TITLE
Update to ChartMuseum 0.4.1 and add non-root context path support

### PR DESCRIPTION
**Pull request by axdotl**
Added non-root context path support

### CODE REVIEW

**Comment by jdolitsky** [comment]
Thanks!
/ok-to-test

**Comment by jdolitsky** [comment]
@axdotl I almost forgot. Would you mind adding the other new var in v0.4.1, `INDEX_LIMIT` to values.yaml as well?
https://github.com/kubernetes-helm/chartmuseum/releases/tag/v0.4.1

**Comment by axdotl** [comment]
Sure, I added it.

**Comment by jdolitsky** [comment]
awesome, thanks so much
/lgtm

**Pull request merged**
