### PR TITLE
[stable/jenkins] Add Jenkins backendconfig values

### PR DESCRIPTION
**Pull request by milesmatthias**
#### What this PR does / why we need it:

When deploying Jenkins through this helm chart, many users need to add a backendconfig CRD to finish setting up ingresses. I realize this is GKE specific, but it is disabled by default and would greatly assist the many GKE users.

The alternative to not having this is `curl`ing the Kubernetes API server to create a backendconfig, which is the only remaining need after using this Helm chart. So having it all in the helm chart would prevent having to do this extra step.

#### Which issue this PR fixes

None

#### Special notes for your reviewer:

I know I need to finish adding DCO to every commit, but wanted to submit this PR to get feedback.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
For me it would be fine to include a change like this. Suggested improvements:

- Documentation for `BackendConfig` e.g. Linking to official documentation within `values.yaml` and adding a section which explains what this is for. Please mentions that it's GKE specific
- I would move the properties after ingress properties
- DCO => To make it easier you can squash your changes into a single commit.

**Comment by milesmatthias** [comment]
Thanks @torstenwalter. I've made those changes.

**Review by torstenwalter — CHANGES_REQUESTED** [review]
Please use a consistent naming within the documentation e.g. BackendConfig instead of
- backendconfig
- Backend Config
- Backendconfig

What is it that you are actually configuring within the spec? As it is now the user can set `master.backendconfig.enabled`, but without a spec it probably won't do much.
Even on GKE BackendConfig is not mandatory and ingress would be sufficient. 


> You can use a BackendConfig to configure an HTTP(S) load balancer to use features like Google Cloud Armor, Cloud CDN, and Cloud IAP.
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress

If it's part of the chart at least the service should be linked to the backed config. Otherwise I don't see much benefit of maintaining it here.

**Comment by milesmatthias** [comment]
Updated the README to be consistent.

I left the spec open ended since there are several things you can use: https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

In my mind, you would be required to provide your own spec in your values.

**Comment by torstenwalter** [comment]
@maorfr What's your view?

**Comment by maorfr** [comment]
/ok-to-test

i think we can start off like this and iterate. wdyt?

**Comment by torstenwalter** [comment]
@milesmatthias Can you increase the chart version? That should fix the build.

**Comment by milesmatthias** [comment]
@torstenwalter should be done now.

**Comment by torstenwalter** [comment]
@milesmatthias Thank you for the PR.

**Pull request merged**
