### PR TITLE
[stable/prometheus-blackbox-exporter] Improve blackbox exporter to handle custom relabelings

### PR DESCRIPTION
**Pull request by gillg**
#### What this PR does / why we need it:

Relabelings confings are completly missing in current helm chart.
Relabeling could be very useful to add custom labels for example.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by gillg** [comment]
Hum... in fact this repo just became deprecated :expressionless:

**Comment by desaintmartin** [comment]
Feel free to propose on new repo !

**Comment by scottrigby** [comment]
@gillg Correct! Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). Please reopen your PR there if still applicable. Thanks!

**Pull request closed without merging**
