### PR TITLE
[stable/airflow] bugfix gitsync and initContainer

### LINKED ISSUE #20606: [stable/airflow] volumeMounts[0].name: Not found: "git-clone"`
**Describe the bug**
I'm trying to install Airflow with custom dag repo but I encounter following exception:

```helm install airflow6 stable/airflow --version 6.0.0 --set dags.git.gitSync.enabled=true --set dags.git.url=https://github.com/x/airflow-dag --set dags.git.gitSync.refreshTime=60```

```Error: Deployment.apps "airflow6-web" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "git-clone"```

**Version of Helm and Kubernetes**:
Helm: ```version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}```

K8: `kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
`

```
> helm repo list
NAME    URL
stable  https://kubernetes-charts.storage.googleapis.com/
```

**Which chart**:

stable/airflow

### PR DESCRIPTION
**Pull request by pgbezerra**
When you do not activate iniContainer and want to activate git sync,
this error will be thrown `volumeMounts[0].name: Not found: "git-clone"`
It is not and expected behaviour.

  - fixes #20606

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by paulobezerr** [comment]
Hi there, please review my PR :)

**Comment by carlosescura** [comment]
Facing the same issue here. Any chance to get this approved?

**Comment by brunorafa** [comment]
OMG, I can't wait for it

**Comment by rcjsuen** [comment]
Also cause of #21008.

**Review by gsemet — APPROVED** [review]
/lgtm

**Comment by gsemet** [comment]
Sorry I am not noticed on PR unless someone @ me :(

**Comment by rcjsuen** [comment]
@paulobezerr @gsemet It seems to me that the current PR changes the volume so that it is only created if `.Values.dags.initContainer.enabled` resolves to `true`.

1. However, the `git-clone` volume is still a requirement of the `git-sync` sidecar so perhaps the conditional should be changed so that if either `.Values.dags.initContainer.enabled` or if `.Values.dags.git.gitSync.enabled` resolves to `true` the volume gets created? Otherwise, would you not simply continue to get the `volumeMounts[0].name: Not found: "git-clone"` errors given that the `git-clone` volume is still not being created?

https://github.com/helm/charts/blob/cd49db10bf62228f1639a67eb6798846dd2601cf/stable/airflow/templates/deployments-scheduler.yaml#L261-L266

2. The `charts/stable/airflow/templates/deployments-web.yaml` file also needs to be updated, correct?

**Comment by gsemet** [comment]
Yes I think you are right

**Comment by paulobezerr** [comment]
This commit c22bd37bc0b4fde003a5c5a46bff5935cf9bc0b2 fixed the problem and did more.
Thank you for you attention.
Regards!

**Pull request closed without merging**
