### PR TITLE
Add support for configuring pools in airflow

### PR DESCRIPTION
**Pull request by stijndehaes**
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>

#### What this PR does / why we need it:

This adds support for configuring pools through the airflow charts. This is done similar to airflow variables.

#### Which issue this PR fixes

- none

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by stijndehaes** [comment]
@gsemet If you have time to review this. It would be greatly appreciated.

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
Looks great ! Thanks !

**Comment by stijndehaes** [comment]
@gsemet I just pushed a small update to the docs that you can only use this feature from airflow 1.10.2

**Comment by gsemet** [comment]
/lgtm cancel

Ok and can you check to fix the small issue in the minikube example ?

**Comment by gsemet** [comment]
Link to the issue : https://github.com/helm/charts/issues/12042#issuecomment-486991038

**Comment by stijndehaes** [comment]
> /lgtm cancel
> 
> Ok and can you check to fix the small issue in the minikube example ?

Not sure what issue you mean. I have also removed the pools config from the minikube example. I could upgrade the minikube example to airflow 1.10.2. Then I can add the pool config again.

**Comment by stijndehaes** [comment]
@gsemet Should I also upgrade it to use airflow 1.10.2 by default?

**Comment by gsemet** [comment]
Sure you can do it !

**Comment by stijndehaes** [comment]
@gsemet Ok it's ready for another review :) 
I upgraded to 1.10.2
Fixed the default values for minikube by removing the ingress specification
And added support for configuring pools

I tested this locally on minikube

**Comment by gsemet** [comment]
Yes there has been another PR today (often they come in group, weirdly). Can you rebase and change the version please ?

**Comment by stijndehaes** [comment]
@gsemet I have rebased and resolved conflicts :)

**Review by gsemet — APPROVED** [review]

**Comment by gsemet** [comment]
Thanks for your PR. I am approving it but wonder how would you start several pools ? And say n workers for pool A and m for pool B?

**Comment by stijndehaes** [comment]
@gsemet An example of a config with 2 pools:

```
{
    "first pool": {
        "description": "This is an example of a first pool with 2 slots",
        "slots": 2
    },
    "second pool": {
        "description": "This is a second pool with 1 slot",
        "slots": 1
    }
}
```

I hope this makes it clear. The json syntax looks a bit weird I think, but this is how it works in airflow.

**Comment by gsemet** [comment]
I never actually used it. And how do you associate slot with tasks ? Per operator ?

**Comment by stijndehaes** [comment]
The documentation actually does a pretty good job of explaining it: https://airflow.apache.org/concepts.html#pools

In short you assign a task to a pool. And only as much tasks as the pool allows are run in parallel. You use this to be sure you don't overwhelm a system.

**Comment by gsemet** [comment]
Cool, that’s actually quite simple to use :)

**Comment by stijndehaes** [comment]
Yeah it is :) there used to be a nasty bug however. When you assigned a task to a non existing pool the scheduler used to crash. But this is fixed somewhere in the 1.10.x series. Can't remember the correct version. Now it just never schedules your task which can be confusing. But better then a crashing scheduler ;)

**Pull request merged**
