### PR TITLE
deprecation note

### PR DESCRIPTION
**Pull request by vtuson**
**What this PR does / why we need it**:
Adding deprecation notes to SugarCRM Readme and Notes

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by tompizmor — APPROVED** [review]
/ok-to-test
/lgtm

**Review by prydonius — APPROVED** [review]
/lgtm

**Pull request merged**
