### PR TITLE
[stable/prometheus-operator] Readme update of kube-proxy metrics bind address, pointing to multiple possible cm locations.

### PR DESCRIPTION
**Pull request by TBeijen**
#### What this PR does / why we need it:

Pointing out the possibility that kube-proxy config.yaml might be in a different configmap. Related to https://github.com/coreos/prometheus-operator/issues/2757

#### Which issue this PR fixes
  - fixes #

#### Special notes for your reviewer:

Just a minor docs update. Hopefully saves people some time (outweighing the review effort).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
The tests will keep failing until one of these can be done:
- https://github.com/helm/charts/pull/18271
- https://github.com/helm/charts/issues/18310

**Comment by vsliouniaev** [comment]
/lgtm
Could you please bump the chart version?

**Comment by TBeijen** [comment]
Done. Tagged from 8.1.2 to 8.1.3.

**Pull request merged**
