### PR TITLE
[stable/percona-xtradb-cluster] Minor version bump: Fix chart not being upgradable

### PR DESCRIPTION
**Pull request by mr-yaky**
**What this PR does / why we need it:**

Major version bump: Fix chart not being upgradable by removing 'chart' label from spec.selector or spec.VolumeClaimTemplate.

**Special notes for your reviewer:**

See #7680 and #7803 for explanations

### CODE REVIEW

**Comment by paulczar** [comment]
you'll need to sign your commit for DCO!

**Comment by mr-yaky** [comment]
sorry, for the delay

>you'll need to sign your commit for DCO!  

done

**Pull request merged**
