### PR TITLE
[newrelic-infra] Update image to 1.3.1

### PR DESCRIPTION
**Pull request by jfjoly**
Signed-off-by: JF Joly <joly.pro@gmail.com>

#### What this PR does / why we need it:
Updates Newrelic-infra image to version 1.3.1

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by rk295** [comment]
lgtm!

**Comment by jfjoly** [comment]
@linki Would you mind take a look at this PR?

**Comment by mattfarina** [comment]
@rk295 You should consider following the process at https://github.com/helm/charts#owning-and-maintaining-a-chart to have an OWNERS file where you can merge the things.

**Comment by rk295** [comment]
> @rk295 You should consider following the process at https://github.com/helm/charts#owning-and-maintaining-a-chart to have an OWNERS file where you can merge the things.

Thanks @mattfarina  I did not know about that. I'll create an OWNERS file and submit a PR.

**Pull request merged**
