### PR TITLE
Add nodeselector to values

### LINKED ISSUE #3789: Add NodeSelector to percona-xtradb-cluster
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature: Add a NodeSelector attribute to the percona-xtradb-cluster values.yaml so we can control which nodes the Db's run on.

**Version of Helm and Kubernetes**:
helm: 2.8.0
kubernetes: 1.9.2

**Which chart**:
percona-xtradb-cluster

**What happened**:
Cannot assign node affinity

**What you expected to happen**:
Be able to assign node affinity

### PR DESCRIPTION
**Pull request by stephenlawrence**
Fixes #3789 

Add NodeSelector to values.yaml for percona-xtradb-cluster chart.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by jdumars** [comment]
Hi, please get your CLA signed, and we will ok this for testing. Thanks!

**Comment by stephenlawrence** [comment]
@jdumars What is the CLA warning trying to tell me? I am not 100% sure how to resolve that issue.

**Comment by jdumars** [comment]
@stephenlawrence you need to follow the instructions here: https://git.k8s.io/community/CLA.md#the-contributor-license-agreement  Thanks!

**Comment by stephenlawrence** [comment]
@jdumars I have done this:
`git commit --amend --reset-author and then git push --force`

And I see a signed agreement at CLA already.

CLA still complaining though.

**Comment by prydonius** [comment]
@stephenlawrence you have several commits here with a different author (one that GitHub (and likely therefore the CLA) doesn't seem to recognise): https://github.com/kubernetes/charts/pull/3790/commits. Could you squash everything into a single commit with the correct author and force push again?

**Pull request closed without merging**
