### PR TITLE
Adding extra options for Master and Slave configuration

### PR DESCRIPTION
**Pull request by ecejjar**
**This PR adds multiple configuration options to Master and Slaves**:
- Extra ports to be opened in the master; some plug-ins require those ports
- RetentionTimeout and ConnectAndReadTimeout in agents: to better adapt to varying network conditions
- ImagePullSecrets in agents: allows to declare more than one secret, useful when pulling from multiple private repos
- ports in agents: allows to declare container-to-host port mappings
- liveness probe in agents: allows to declare a kubernetes liveness probe for agents
- UseCustomWorkspaceVolume in agents: allows to start an agent with fresh empty workspace

**This PR also fixes an issue when creating agents in namespaces other than the master namespace. Unless the master namespace is included in Jenkins URLs, slaves in other namespaces won't be able to connect to its master.**

**Special notes for your reviewer**:

This PR "resurrects" the stale https://github.com/kubernetes/charts/pull/1878, which I was unable to complete. I've tried to address all the reviewers' comments there, and added a few improvements.

### CODE REVIEW

**Comment by lachie83** [comment]
Please use the customConfig option to supply these changes in your config.yaml. Please refactor this PR to add only the extra ports.

**Comment by ecejjar** [comment]
Not sure I understand, do you mean that every config option in this PR but the extra ports should be set by ourselves in a custom ConfigMap of our own? And if so, is that because the PR is too large, or just because the other options don't seem interesting?

If the PR is too large, I can split it down into several PRs, and submit a bug for the issue with slaves in other namespaces. To be honest, I think ther're a few (in our own experience) useful config options in the PR.

**Comment by viglesiasce** [comment]
Hey @ecejjar!

Indeed this PR convolves too many things. Splitting it up will make it easier to review and merge.

**Comment by ecejjar** [comment]
I'm closing this PR to submit smaller PRs with every enhancement in this one.

**Pull request closed without merging**
