### PR TITLE
[stable/chronograf] Bump version && update readme

### PR DESCRIPTION
**Pull request by batazor**
Signed-off-by: Login Victor <batazor111@gmail.com>

#### What this PR does / why we need it:

- Bump version chronograf to 1.7.12
- Add a table to README
- Add nodeSelector, tolerations, affinity

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by batazor** [comment]
@scottrigby

**Comment by maorfr** [comment]
/ok-to-test

thanks for this PR!
why are we changing the image repository?

**Comment by batazor** [comment]
@maorfr This image repository indicated in the release https://github.com/influxdata/chronograf/releases/tag/1.7.12

it also uses `alpine` as base image

**Comment by maorfr** [comment]
/assign @jackzampolin 
/unassign

i'll let Jack take a look at this, i feel that i am missing some context here.

**Review by scottrigby — APPROVED** [review]
Regarding the image, here was the PR that changed the chart image from quay to docker.io: #3187 There's no explanation about why that was done, except the chart was outdated. The official project image repo is quay 👍 

I believe this PR is doing all the right things:
- Updating image (back) to the official project image, and bump version
- Adding `nodeSelector`, `tolerations`, `affinity` (thank you)
- Adding values table to README (thank you)

**Comment by scottrigby** [comment]
@maorfr did you want feedback from @jackzampolin specifically or just another set of eyes?

**Comment by maorfr** [comment]
/lgtm

wanted a set of eyes with context, which you just provided @scottrigby! thanks!
@batazor, thanks for contributing!

**Pull request merged**
