### PR TITLE
[newrelic-infrastructure] Deprecated newrelic-infrastructure chart in this repo

### PR DESCRIPTION
**Pull request by douglascamata**
#### Is this a new chart

No.

#### What this PR does / why we need it:

Deprecated the newrelic-infrastructure chart in this repository in favor of github.com/newrelic/helm-charts.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by areina — APPROVED** [review]

**Review by rk295 — APPROVED** [review]

**Comment by rk295** [comment]
I appreciate that dragging over the commit history would have been fairly complex, however it would have been nice to see New Relic at least acknowledge the 20+ community maintainers of this chart for the last two and a half years.

**Comment by douglascamata** [comment]
@rk295 you're totally right. I just added a mention here to the community contributors and maintainers. We're very thankful to all of them, including you. 👍

**Comment by douglascamata** [comment]
@rk295 actually, I was able to pull in all the contributors individually. Much better now!

**Comment by douglascamata** [comment]
Also I preferred the usernames to not easily expose people's email address.

**Pull request merged**
