### PR TITLE
fix typo in incubator gocd readme

### PR DESCRIPTION
**Pull request by scf0920**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by scf0920** [comment]
@foxish  Excuse me. Why  ci failed? I am very confused.

**Comment by timstoop** [comment]
There's a new requirement to the Chart, it now needs to have `maintainers` set.

**Comment by timstoop** [comment]
This is a deprecated chart. No need to file PRs against it.

Didn't notice it the first time around.

**Pull request closed without merging**
