### PR TITLE
Feature kafka pod annotations

### PR DESCRIPTION
**Pull request by sukrit007**
**What this PR does / why we need it**:
Adds support for adding pod annotations for kafka stateful sets.  This is useful for adding additional metadata to the pods that can be used for auto-discovery by other processes like datadog.

### CODE REVIEW

**Comment by benjigoldberg** [comment]
Thanks for the PR @sukrit007 -- can you remove the schema-registry changes from this PR?

**Comment by sukrit007** [comment]
@benjigoldberg  I have rebased my changes and it only includes commit for kafka.   Let me know if it looks good to you.

**Pull request merged**
