### PR TITLE
[incubator/zookeeper] Move container command and arguments into values.yaml

### PR DESCRIPTION
**Pull request by bluebenno**
#### What this PR does / why we need it:
Move container command and arguments into values.yaml.  This opens the door for adventurous 
 chart users to experiment with other, non-default container images.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by bluebenno** [comment]
@lachie83 @kow3ns ping.  Would you mind having a look at this PR?

**Comment by bluebenno** [comment]
@lachie83 @kow3ns ping. Would you mind having a look at this PR?

**Comment by maorfr** [comment]
/ok-to-test

@bluebenno, would you mind opening an issue to add a `Configuration` section to this chart? in the hope that someone picks that up :)
An example can be found here:
https://github.com/helm/charts/tree/master/stable/grafana#configuration

Thanks for contributing!

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Pull request merged**
