### PR TITLE
Update Storage Class from alpha to beta level:  issue #210

### PR DESCRIPTION
**Pull request by TerraTech**
Updates all instances of volume.alpha.kubernetes.io ==> volume.beta.kubernetes.io
issue #210

### CODE REVIEW

**Comment by lachie83** [comment]
We'll also need to take a pass to confirm if the prerequisites on the README need to be bumped to 1.4+

**Comment by TerraTech** [comment]
@lachie83 as per #210,
_then (moving target) annotations like this should be parameterized and set it in a global config with a reasonable default._

**Comment by prydonius** [comment]
See https://github.com/kubernetes/charts/issues/116#issuecomment-254975483 also. It seems that the annotation should be left off altogether (unless conditionally provided), but in my testing on GKE with 1.4, leaving off the annotation didn't automatically provision my PVC. Since GKE doesn't setup a default storage class object, you need to manually create one beforehand.

**Comment by prydonius** [comment]
Closing in light of discussions in #116 and #210 - a separate PR is required that will conditionally set the beta annotation if a storage class is provided. Thanks a lot @TerraTech!

**Pull request closed without merging**
