### PR TITLE
[stable/metrics-server] Add release.Namespace in meta

### PR DESCRIPTION
**Pull request by spiarh**
#### What this PR does / why we need it:

This PR adds release.Namespace in meta.

#### Which issue this PR fixes

This PR fixes issues when rendering template with 'helm template --namespace'. Without it, the rendered templates do not have the namespace defined which is problematic when using
a gitops approach. This is also a requirement for a tool like Spinnaker.

#### Special notes for your reviewer:

This is fully backward compatible and make it just more compatible with workflows using helm template.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by olemarkus** [comment]
Where the templates hard-code template to `kube-system` it should remain so. This is because these resources have to be in that namespace.
Adding for the rest is fine.

**Comment by lcavajani** [comment]
@olemarkus I just removed it from the `ClusterRoleBinding` since the resource is not namespaced otherwise I left `kube-system` in the `auth-reader` `RoleBinding`

**Pull request merged**
