### PR TITLE
[stable/prometheus-operator] Added anandsinghkunwar as OWNER

### PR DESCRIPTION
**Pull request by anandsinghkunwar**
Signed-off-by: Anand Singh Kunwar <anandkunwar95@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
I would be comfortable adding you as a reviewer here. Not sure if the process is less strict for that. Adding you as an owner appears to be forbidden by the repo process

**Comment by anandsinghkunwar** [comment]
@vsliouniaev Didn't really help.

**Comment by vsliouniaev** [comment]
You will need to follow the process for being added as a trusted collaborator here: https://github.com/helm/charts#trusted-collaborator

**Comment by scottrigby** [comment]
@vsliouniaev that's good enough for me 😄 

@anandsinghkunwar I have added you as a read-only collaborator per https://github.com/helm/charts#owning-and-maintaining-a-chart. You must accept the invite: https://github.com/helm/charts/invitations

**Comment by anandsinghkunwar** [comment]
@vsliouniaev Can you approve/merge?

**Pull request closed without merging**
