### PR TITLE
Update ownCloud image to version 9.1.3-r1

### PR DESCRIPTION
**Pull request by joseajp**
Bump ownCloud image version to 9.1.3-r1

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot ok to test

**Review by lachie83 — CHANGES_REQUESTED** [review]
Please update the mariadb dependency to chart version 0.5.6 and regenerate the requirements.lock using helm dependency update

**Comment by joseajp** [comment]
Updated MariaDB chart version to 0.5.6

**Review by lachie83 — APPROVED** [review]

**Comment by lachie83** [comment]
Getting Not Found when hitting / following NOTES.txt 

```
Not Found

The requested URL / was not found on this server.
```

**Comment by sameersbn** [comment]
#417 includes all the changes from this PR and some additional fixes for #406. If you will be merging this PR then I'll rebase #417 as required.

**Comment by prydonius** [comment]
Closing in favour of #417

**Pull request closed without merging**
