### PR TITLE
[stable/grafana] Much cleaner sed expression without backslashes.

### PR DESCRIPTION
**Pull request by Antiarchitect**
Seems previous one works not always. Just compare:
`curl -s https://raw.githubusercontent.com/Enapter/grafana-dashboards/master/cilium-agent-1.7.3.json | sed 's|\"datasource\": *\"\$[^,]*|\"datasource\": \"HELLO\"|g' | grep datasource`
And the new one:
`curl -s https://raw.githubusercontent.com/Enapter/grafana-dashboards/master/cilium-agent-1.7.3.json | sed 's/"datasource":[^,]*/"datasource": "HELLO"/g' | grep datasource`

Signed-off-by: Andrey Voronkov <voronkovaa@gmail.com>

#### What this PR does / why we need it:
It provides better, cleaner, and reliable sed expression when changing the source for downloaded dashboards.

#### Special notes for your reviewer:
The cilium-agent Grafana dashboard was extracted from here: https://github.com/cilium/cilium/blob/v1.7.3/examples/kubernetes/addons/prometheus/monitoring-example.yaml - just to have a convenient way to download it.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by Antiarchitect** [comment]
@zanhsieh pull-charts-e2e seems constantly failing by some technical reasons

**Comment by zanhsieh** [comment]
@Antiarchitect 
I think you need to bump the chart again.

**Comment by Antiarchitect** [comment]
@zanhsieh You mean 5.0.22 ?

**Comment by languitar** [comment]
I think this broke the intended behavior from my previous PR. I am now back at the situation that annotation data sources are replaced as well. For instance, for https://grafana.com/grafana/dashboards/617 I end up with the following JSON definition after replacement:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "CloudWatch",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
```

Before the replacement, the code is:
```
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },

**Comment by languitar** [comment]
The important part here is that `-- Grafana --` is a special case that must not be replaced.

**Comment by Antiarchitect** [comment]
@languitar Is it only `-- Grafana --` string or it is a whole `-- .* --` subclass?

**Comment by languitar** [comment]
I am only aware of this one special placeholder, which means that annotations should uses the internal Grafana DB. Might be that there are other special values, but we would have to ask a Grafana developer.

**Comment by Antiarchitect** [comment]
@languitar 

```
curl -s https://raw.githubusercontent.com/Enapter/grafana-dashboards/master/cilium-agent-1.7.3.json | sed 's/"datasource":[^-]{2}[^,]*/"datasource": "HELLO"/g' | grep datasource
```
What about this? If datasource value starts with `--` it will be protected.

**Comment by languitar** [comment]
As long as there are no datasource names with only one character ;-) but looks good to me.

**Comment by Antiarchitect** [comment]
@languitar I've used negation pattern. If the whole string contains `-- .* --` sequence it will not be replaced.

**Pull request merged**
