### PR TITLE
Add proxy support for grafana

### PR DESCRIPTION
**Pull request by salarmgh**
Currently grafana chart doesn't support proxy inside grafana container, so in some infrastructures which does not have access to internet without proxy, plugin download will be failed

Proxy configurations is inside values.yaml

### CODE REVIEW

**Comment by zanhsieh** [comment]
@salarmgh 
Could you sign DCO and bump chart to latest version please? See the bottom of this page (Click **Details** next to **DCO Action required after xx - DCO** for instructions) Thank you for contribution.

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@salarmgh 
Could you bump the chart version to latest please? I will merge it later on.

**Comment by salarmgh** [comment]
@zanhsieh version bumped, it seems there is a problem in ci test

**Pull request closed without merging**
