### PR TITLE
[stable/home-assistant] support for optional VS Code server sidecar

### PR DESCRIPTION
**Pull request by billimek**
#### What this PR does / why we need it:

Adds support for an optional sidecar container running VS Code Server for editing home-assistant configuration files

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by billimek** [comment]
This is what it looks like in practice, with the home-assistant VS Code extension installed:

image

**Comment by maorfr** [comment]
hey @billimek,

this you can 'recruit' someone to work on this chart with you? :)
that way you can pair and approve each other's changes without waiting for global maintainers...

**Comment by billimek** [comment]
> hey @billimek,
> 
> think you can 'recruit' someone to work on this chart with you? :)
> that way you can pair and approve each other's changes without waiting for global maintainers...

Hi @maorfr, yes I would love to!  It was my hope that I could recruit one or two people who have submitted their own PRs for this chart (this is what I did for stable/unifi), but none have really materialized as yet.  I've also reached-out to the Home Assistant development community to find a volunteer but no takers yet :(

**Comment by maorfr** [comment]
/assign
/lgtm

would you make another attempt to recruit? :)

**Pull request merged**
