### PR TITLE
[stable/gocd] Add information about adding plugins

### PR DESCRIPTION
**Pull request by mohamednajiullah**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR adds information to the README about adding plugins to a GoCD setup

#### Special notes for your reviewer:
This PR just updates the README.md.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
@mohamednajiullah - thanks for the PR. You need to bump the version of the helm chart since every change made to the helm chart (even the README) is a new version for users. Its how this repo is setup. 

In addition to bumping the chart version, make a new commit tp update the changelog too, please. You can notice this format if you look at any gocd related PRs in this repository.

**Comment by mohamednajiullah** [comment]
@varshavaradarajan, I have bumped up the chart version and added an entry to the changelog.

Could you please check now?

**Pull request merged**
