### PR TITLE
Redis Helm Chart. Add resources to init container in the slave-deployment template

### PR DESCRIPTION
**Pull request by vkropotko**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Thanks for this contribution @vkropotko !!!

Could you please add the parameter `sysctlImage.resources` to the table available at the **README.md** file too?

**Comment by vkropotko** [comment]
@juan131 Hi, Readme.md updated. 
Also, there are specified `default` resources for master and slave according to README.md but resources' lines were commented in values.yaml/values-production.yaml. Mb, change them in readme.md to `{}`.

**Review by juan131 — APPROVED** [review]
Thanks!!! I'm approving the changes.

**Pull request merged**
