### PR TITLE
[stable/metrics-server] Select amd64 nodes by default to match amd64 image

### LINKED ISSUE #17341: [stable/metrics-server] not starting properly on hybrid arm/amd64 clusters
**Describe the bug**
By default the chart uses an amd64 image:
```
gcr.io/google_containers/metrics-server-amd64
```
In a cluster than contains arm or arm64 nodes, the pod is not able to start.

**Version of Helm and Kubernetes**:
- helm `v2.14.3`
- kubernetes `v1.15.4`

**Which chart**: `stable/metrics-server`

**What happened**:
Since the amd64 image can't start on arm, it fails.
The idea would be to at least add an affinity as to prevent the pod from being scheduled on a node that is not compatible.
Otherwise arm and arm64 images are also available.

**What you expected to happen**:
Either being scheduled on a compatible node (amd64) or start on arm with a corresponding image (`gcr.io/google_containers/metrics-server-arm`).

**How to reproduce it** (as minimally and precisely as possible):
You would need an hybrid cluster with at least one node that is not arm64.
Then start the `stable/metrics-server` chart.

### PR DESCRIPTION
**Pull request by CoRfr**
The default image being gcr.io/google_containers/metrics-server-amd64,
it would make sense to restrict it to amd64 nodes to prevent scheduling
issues on hybrid clusters.

It is still possible to select arm or arm64 images & nodes as
parameters.

#### Which issue this PR fixes
  - fixes #17341

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by olemarkus** [comment]
The beta.kubernetes.io labels are deprecated and nodes should have kubernetes.io labels instead. This makes accepting this PR a bit hard as we need to support nodes having either of the above labels.

Secondly, I think this becomes a bit too specific for what should be handled by chart default values vs what you set as values on the release.

**Comment by CoRfr** [comment]
Right, I would remove the beta but that still wouldn't solve the 'either' `beta.kubernetes.io` or `kubernetes.io`, so I'm not sure how to do that.

Regarding the fact that the default value would be too specific, I understand and it's unfortunate that the image value is so specific too. If the metrics-server manifest on gcr.io was multi-arch I guess the problem would go away.

**Comment by olemarkus** [comment]
I don't really think you can solve this through this helm chart, unfortunately.

/close

**Pull request closed without merging**
