### PR TITLE
[stable/postgresql] Fix change ownership of NFS PV (#19921)

### LINKED ISSUE #19921: stable/postgresql Fails chown NFS mounted volume
**Describe the bug**
stable/postgresql uses an initContainer to chown the files in the postgres/data folder. However, the script does chown ALSO the postgresql/data folder. This leads to a failure in the initialisation process when the postgresql/data folder is a PV from a NFS server which uses [`no_root_squash` option](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s2-server-nfs-noroot.html) and the mounted folder belongs to a different user than postgresql, which is normally the case.
The actual script uses `find (...) -mindepth 0  (...) | xargs chown -R (...)` which exits with an error if it cannot chown the parent folder (due to `-mindepth 0`). It was introduced in [#17154](https://github.com/helm/charts/pull/17154)
A better approach would be to use `find (...) -mindepth 0  (...) -exec chown -R (...) {} \;` which completes successfully even if it is not able to change ownership of a folder / file (there is only a warning message).

**Version of Helm and Kubernetes**:
Helm: v3.0.0
Kubernetes: v1.17

**Which chart**:
stable/postgresql: v8.1.2

**What happened**:
The initContainer fails to if it cannot change ownership of the mounted folder

**What you expected to happen**:
The initContainer should either not try to change ownership of the parent folder (anyways postgresql doesn't require it) or continue in case of failure. The main container will fail anyways if there is any issue with file permissions / ownerships etc

**How to reproduce it** (as minimally and precisely as possible):
- Have both `.Values.volumePermissions.enabled .Values.persistence.enabled` enabled
- Set both `.Values.securityContext.runAsUser .Values.securityContext.fsGroup` to 999 (postgresql default user and group)
- Have a PV from a NFS with `no_root_squash` option enabled and folder owner i.e. nobody:nobody
- Install the chart and see initContainer fail

### PR DESCRIPTION
**Pull request by krufab**
#### What this PR does / why we need it:
This PR fixes issue #19921 as it allows container initialisation even when it cannot change ownership of the mount point itself. A persistent volume is generally mounted in `/bitnami/postgresql` and a the data folder is created inside. Postgresql does not need owership of the `/bitnami/postgresql` but only of its contents.

The old code attempted to change ownership of `/bitnami/postgresql` folder, which fails in certain configurations where a PV of type NFS is mounted. For example, when the folder does not belong to the postgres user but to i.e. nobody:nobody and change ownership is not permitted.

#### Which issue this PR fixes
  - fixes #19921 

#### Special notes for your reviewer:
The bug was introduced in https://github.com/helm/charts/pull/17154
This PR should solve the bug and keep compatibility with #17154 needs

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by alemorcuq** [comment]
Hi, @krufab.

Thanks for your PR! As I said in the related issue (#19921), I'm not really sure about this. The postgresql container does need the permissions in the parent directory (see https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L739), so with this change the init scripts may not work. But it is true that without this change then the chart isn't working at all.

What do you think about this @juan131 @sameersbn ?

**Comment by krufab** [comment]
Hi @alemorcuq,
thanks for your answer.
If I read correctly the link you posted in the related issue page (https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L739), postgres needs WRITE access to the parent folder, but not full ownership. This can be achieved having the shared folder use i.e.  777 mask, so that everyone can write in it. 
Probably, full ownership is required for the data folder, but this is different and achieved with the shell intiContainer part.

In general, with Kubernetes and mounted volumes, it's not always possible to change ownership of the parent folder itself, therefore the actual code will fail in many situations. 

I increased the minor version because the final effect is different (i.e. if you were relying of a full ownership of the mounted volume, now it't not the case). But I can change it to a patch.

**Comment by krufab** [comment]
Actually, reading better the actual code, applied with commit [16bea01a62](https://github.com/helm/charts/commit/16bea01a6257b2edc459709afef36d7df4daedaa) (the one which changed mindepth from 1 to 0), it does not make much sense. The actual code is:
```bash
find {{ .Values.persistence.mountPath }} -mindepth 0 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
  xargs chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}
```
That is, find all files and dirs in /bitnami/postgresql, except ".snapshot" and "lost+found", and change their ownership recursively (-R), but ALSO take /bitnami/postgresql itself (-mindepth 0) and change its ownership recursively...
So it does the job twice and even ignores the "-not -name".
The code previous that commit was:
```bash
find {{ .Values.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
  xargs chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}
```
and apparently it was not able to touch `.initialized*`files.
However, I think it was a matter of permissions, rather than ownership.
So we could either revert to the original -mindepth 1 version or use mine, but the actual code does not make much sense.

Another side note is that yes, my version completes successfully even if it cannot change ownership of some file, however, it `chown` still prints out an error message which is visible in the container's log

**Comment by krufab** [comment]
Any update on this?

**Comment by miguelaeh** [comment]
hi @krufab ,
Sorry for the late response, I agree with you in that using `-mindepth 0` it will ignore the `-not` options. 
I think we should revert it back to `-mindepth 1`, so the rules are properly applied. And, as this will not change the permissions of the `bitnami/postgresql` itself, we should change them but not recursively, so we maintain the ones given the `find` command.
Do you agree with those changes?

**Comment by krufab** [comment]
Hi @miguelaeh,
I reverted to -mindepth 1. However, I didn't get the 2nd part of your suggestion.
Should i use chown WITHOUT -R?

**Comment by miguelaeh** [comment]
Hi @krufab ,
I think so, as we want to give access to the folder but without modify the permissions of the content (those are changed with the `find` command)

**Comment by krufab** [comment]
Ok, someone already updated the code, so maybe my PR is obsolete now.
The only thing i might disagree on is that the initContainer fails if xargs chmod cannot change ownership of one item.
Using `find ... -exec chmod .. {};` rather than piping to xargs, would allow the script to continue.

**Comment by krufab** [comment]
Solved by #20479

**Pull request closed without merging**
