### PR TITLE
[stable/concourse] Fix Broken Tutorial Link

### PR DESCRIPTION
**Pull request by topherbullock**
The Concourse docs have a new section with a list of tutorials rather than a single hello-world

#### What this PR does / why we need it:
Fixes the a link in the message printed when a user starts 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by cpanato** [comment]
@topherbullock please bump the chart version and sign the DCO

**Comment by topherbullock** [comment]
@cpanato signing the DCO now... serves me right for being lazy and making the PR from GitHub.
Does a note change warrant a version bump? I'm fairly new to Helm charts :)

**Comment by cpanato** [comment]
yes, a patch bump @topherbullock

**Pull request merged**
