### PR TITLE
Update jenkins stable

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
- Adds support for additional labels in jenkins-master-svc
- Makes security realm optional
- Allows jenkins chart to specify additional config in values

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @viglesiasce and @lachie83 

Can you guys please take a look

**Comment by viglesiasce** [comment]
Thanks @faizanahmad055! Can you add docs in the README for the features you added?

**Comment by faizanahmad055** [comment]
> Thanks @faizanahmad055! Can you add docs in the README for the features you added?

Hi @viglesiasce, Thank you for looking into it. Can you please explain the docs you are talking about. I've already updated the readme with the new variables. Do you want me to update the readme with some further details of these changes?

**Comment by faizanahmad055** [comment]
> Yeah can you add some longer form examples in the README that describe how to use serviceLabels and additionalConfig and maybe why.

Hi @viglesiasce, I've updated the readme with some examples. Can you please take a look.

**Comment by faizanahmad055** [comment]
Hi @viglesiasce, I hope you are doing fine. Can you please take a look at the updated readme.

**Comment by faizanahmad055** [comment]
Hi @viglesiasce and @lachie83 
Ping

**Comment by viglesiasce** [comment]
thanks @faizanahmad055!! Looks great!

/lgtm

**Comment by viglesiasce** [comment]
@mattfarina any way to by pass the dco-labeler check for this PR. I made the chart bump from the UI but did not add the Signed-off-by and am not able to alter that commit message.

**Comment by faizanahmad055** [comment]
Hi @viglesiasce 
Closing this PR and opening a new one to avoid DCO issue. Please take a look at this #9296 PR with these changes so it can be merged.

**Pull request closed without merging**
