### PR TITLE
[stable/rabbitmq] Improve the readiness and liveness probes: now print healthcheck result

### LINKED ISSUE #12743: [stable/rabbitmq] better visibility on probes failure
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?**: feature request

**Which chart**: `stable/rabbitmq`

**What happened**:
When a `readinessProbe` or `livenessProbe` fails, we don't have any explanation of what the failure is:
```
kubectl describe ...
Warning  Unhealthy               2m45s (x3 over 5m15s)  kubelet, xxx  Readiness probe failed: 
```

**What you expected to happen**:
When a probe fails, kubectl displays stdout and stderr of the `exec` probe: the probe command should simply print the `GET /api/healthchecks/node` output.

**Anything else we need to know**:
I am preparing a PR to fix this issue.

### PR DESCRIPTION
**Pull request by thomas-riccardi**
Signed-off-by: Thomas Riccardi <thomas@deepomatic.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #12743 

#### Special notes for your reviewer:
- factorized probe code into `/opt/bitnami/rabbitmq/sbin/rabbitmq-api-check` (it's in `$PATH`, and is user writable, contrary to `/`)
- used explicit names for `curl` command
- kept full URL in the probes command: I believe it's more readable for kubernetes operators
- probes command as multi-line array in yaml: avoid unnecessary and unreadable escaping

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by cpanato** [comment]
why do you need to print out the health check result?

**Comment by thomas-riccardi** [comment]
> why do you need to print out the health check result?

I tried to explain that in the related issue: #12743 : the probe output shows up in `kubectl describe pod` when the probe failed: this helps debugging issues.

**Review by juan131 — APPROVED** [review]
I tested your changes and these are the main differences:

```diff
- Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed: 
+ Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed: curl: (7) Failed to connect to 127.0.0.1 port 15673: Connection refused
```

To me it's a much descriptive message so I'm approving your changes!

**Comment by juan131** [comment]
Could you please resolve the current conflicts with `stable/rabbitmq/Chart.yaml` ? After that we can continue with the merging process

**Comment by thomas-riccardi** [comment]
@juan131 
> I tested your changes and these are the main differences:
> 
> ```diff
> - Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed: 
> + Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed: curl: (7) Failed to connect to 127.0.0.1 port 15673: Connection refused
> ```
> 
> To me it's a much descriptive message so I'm approving your changes!

Thanks !
To be more precise I believe the `curl` errors were already reported; what was missing and what my PR adds is the rabbitmq management API response body (printed systematically, but only reported in `kubectl describe` in case of probe error).

Example:
```diff
- Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed: 
+ Warning  Unhealthy  3s                    kubelet, xxx  Readiness probe failed {"status":"failed","reason":"resource alarm(s) in effect:[memory]"}
```


I rebased and resolved the conflict on the chart version.

**Pull request merged**
