### PR TITLE
[stable/instana] Bump leadership-elector to 0.5.4

### PR DESCRIPTION
**Pull request by nfisher**
#### What this PR does / why we need it:

Updated leader-elector to 0.5.4 which uses a distroless image to reduce the number of ongoing vulnerabilities to 3 Debian stretch libraries:

- [glibc](https://security-tracker.debian.org/tracker/source-package/glibc)
- [openssl](https://security-tracker.debian.org/tracker/source-package/openssl)
- [busybox](https://security-tracker.debian.org/tracker/source-package/busybox)

#### Special notes for your reviewer:

- Chart installed and verified in minikube.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by dlbock — APPROVED** [review]
LGTM. @nfisher Just add your github handle to the `OWNERS` file as well? I think the `maintainers` list in the Chart.yaml is mostly informational, the lists in the `OWNERS` is the one that controls who can approve PRs.

**Comment by dlbock** [comment]
I'm also unsure if you have to be manually added as a collaborator of this repo to actually have approve/merge rights, or if the `OWNERS` file takes care of it... I guess we'll find out!

**Comment by nfisher** [comment]
Added to owners as both roles.

**Pull request merged**
