### PR TITLE
add support for newrelic private minions

### PR DESCRIPTION
**Pull request by sstarcher**
Chart for newrelic private minions - https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/private-locations/install-containerized-private-minions-cpms

### CODE REVIEW

**Comment by maorfr** [comment]
hey @sstarcher 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by sstarcher** [comment]
@maorfr I have no interest in hosting a chart repo.

**Comment by maorfr** [comment]
its really just a github repo...

I think that you totally should host your own charts!
This will give you more freedom around management, and you will not be blocked by us (maintainers).

This means that when users want to install your chart, instead of installing them from stable, they will install it from (for example) mycompany-charts:

$ helm install --name my-release mycompany-charts/mychart
Here are some instructions about how to host your own charts repo:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

In order for people to find out about your charts repo, you should add it to helm hub:
https://hub.helm.sh/

Here are some instructions about how to add your charts repo to helm hub:
https://github.com/helm/hub#how-to-add-your-helm-charts

wdyt?

**Comment by sstarcher** [comment]
@maorfr Ahh, I guess that approach can work I did not consider using github pages to host static content.  Will this approach continue to be the preferred approach in helm 3?  And is the overall goal to deprecate the `helm/charts` repo?

**Comment by sstarcher** [comment]
The primary concern about just hosting it in github pages is I lose all of  the testing support that is built into `helm/charts` so overall I don't think it's a preferred approach.

**Comment by maorfr** [comment]
this is the preferred approach moving forward :)
to make things easier, we are working hard on creating better docs and tools to help users achieve that.

this is still the way though :)

**Comment by sstarcher** [comment]
@maorfr if the preferred approach moving forward is to use personal distributed repos(which makes sense) please close this ticket out.  Your last message was not 100% clear me me.

**Comment by maorfr** [comment]
my last message is:
yes, this is the preferred approach :)

sorry for the confusion.

thanks for getting involved!
looking forward to see your helm hub PR!

**Pull request closed without merging**
