### PR TITLE
added resources for init container

### PR DESCRIPTION
**Pull request by michaelgaida**
**What this PR does / why we need it**:
Its introduces the option to set resources for the initContainer used. This enables to use this chart in resource quota restricted namespaces.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lachie83** [comment]
cc @etiennetremel PTAL

**Comment by lachie83** [comment]
@michaelgaida just an FYI for the next PR - we've moved to DCO. Here's what you have to do - https://www.helm.sh/blog/helm-dco/index.html

**Review by etiennetremel — APPROVED** [review]

**Comment by lachie83** [comment]
Manually merging given that this PR has been grandfathered in prior to the move to DCO and CLA has been met.

**Pull request merged**
