### PR TITLE
[stable/elastalert] Add ServiceAccount and PodSecurityPolicy to Elastalert

### PR DESCRIPTION
**Pull request by etiennetremel**
Add ServiceAccount and PodSecurityPolicy

### CODE REVIEW

**Comment by olemarkus** [comment]
This is a bit different from the typical
```
rbac:
  create: true
  pspEnabled: true
```
Any reason for not to do this similar to most other charts?

**Comment by etiennetremel** [comment]
> This is a bit different from the typical
> 
> ```
> rbac:
>   create: true
>   pspEnabled: true
> ```
> 
> Any reason for not to do this similar to most other charts?

There is a lot of inconsistency across all these charts. The serviceAccount I added is based on the default section bootstrapped by the `helm create my-chart` command. I'm using helm cli version 3.1.2 which include the following.

```yaml
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000
```

If you prefer the one you mentioned, let me know I will make the change.

**Comment by olemarkus** [comment]
You are certainly right things are inconsistent.
If you change `podSecurityPolicyEnabled` to `podSecurityPolicy.enabled`, I am happy.

/ok-to-test

**Comment by etiennetremel** [comment]
@olemarkus if you don't mind and to keep consistency with the `serviceAccount.create`, I changed to `podSecurityPolicy.create`.

**Pull request merged**
