### PR TITLE
Add OWNERS file

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
OWNERS file was missing in ingressmonitorcontroller. [IngressMonitorController](https://github.com/stakater/IngressMonitorController) an opensource tool maintained by [Stakater](https://github.com/stakater). We at stakater are adding this file so that we can effectively maintain this chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @davidkarlsen and @sameersbn,
Can you please review this. We have submitted this chart via helm/charts#8975. This chart has missing OWNERS file, that is needed to maintain this chart effectively. Can you please take a look and merge this PR.

**Comment by faizanahmad055** [comment]
Hi @davidkarlsen and @sameersbn,
The second point of **Owning and Maintaining A Chart** is
```text
Be invited (and accept your invite) as a read-only collaborator on this repo. This is required for @k8s-ci-robot PR comment interaction.
```
Can you guys also help me, how to get invited?

**Comment by davidkarlsen** [comment]
@faizanahmad055 You'll get an invite

**Review by davidkarlsen — APPROVED** [review]

**Comment by faizanahmad055** [comment]
Thank you @davidkarlsen

**Pull request merged**
