### PR TITLE
[stable/prometheus-operator] fix typo for prometheus Operator Service…

### PR DESCRIPTION
**Pull request by yujin-hong**
#### Is this a new chart
No

#### What this PR does / why we need it:
Service type NodePort was denoted as NodepPort. It can cause confusion for beginners.
fix typo in values.yaml for prometheus Operator Service type comment

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by bismarck** [comment]
@yujin-hong Thanks for the PR.  I believe you need to bump the version of the Chart, even though it's a small documentation change.

**Comment by yujin-hong** [comment]
> @yujin-hong Thanks for the PR. I believe you need to bump the version of the Chart, even though it's a small documentation change.

Now, I bumped the version

**Comment by bismarck** [comment]
@yujin-hong I believe you lost your change in the last commit.

**Comment by yujin-hong** [comment]
@bismarck sorry for my mistake

**Pull request merged**
