### PR TITLE
exporter fails if localhost cannot be resolved

### PR DESCRIPTION
**Pull request by kabakaev**
prometheus metrics postgresql exporter fails silently if "localhost" cannot be resolved

### CODE REVIEW

**Comment by kabakaev** [comment]
I signed it!

**Comment by viglesiasce** [comment]
cc @mgoodness for review.

**Comment by mgoodness** [comment]
Looks good functionally: `/metrics` is available on port 9187. I'm generally a fan of `127.0.0.1` over `localhost` anyway, so 👍 from me!

Patch version bumped

**Comment by prydonius** [comment]
@k8s-bot ok to test

**Pull request merged**
