### PR TITLE
[stable/redis-ha] narrower config checksums to only restart components if needed

### PR DESCRIPTION
**Pull request by multi-io**
#### Is this a new chart

No.

#### What this PR does / why we need it:

In the current master, if you have haproxy enabled, both haproxy and redis/sentinel will be restarted during Helm release upgrades if anything in either component's configuration changed. So e.g. haproxy is restarted even if you only modify Redis's memory limit settings, and Redis is restarted even if you only change haproxy's timeout settings. This is because the checksum annotations in both components are computed over the entire configuration configmap, so any configuration change anywhere will restart everything.

This PR moves the config files into separate template definitions and adapts the checksum computations in both haproxy and redis so the checksum only changes if something was changed in the config files that the respective service actually uses.

@ssalaues @DandyDeveloper

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
Everything looks okay, and I can easily see the value. Another PR just merged so you will have to bump the version once again and I'll approve.

**Comment by multi-io** [comment]
Rebased & version bumped.

**Pull request merged**
