### PR TITLE
[stable/elastic-stack] Bump kibana version

### PR DESCRIPTION
**Pull request by mikhailznak**
#### What this PR does / why we need it:

It's update Kibana version in whole elastic-stack chart
We need to update because in new Kibana version was realized possibility to customize path for importing dashboards

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Desh96** [comment]
This change  would be  very useful

**Comment by Ratiborec** [comment]
@christian-roggia Could you look at this commit too?

**Pull request merged**
