### PR TITLE
[stable/postgresql] Fix breaking chart when persistence.enabled=false

### LINKED ISSUE #9847: [stable/postgresql] Setting persistence.enabled=false breaks the chart
**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.12.2

**Which chart**:
stable/postgresql

**What happened**:
$ helm install --set "persistence.enabled=false" --name pg-demo stable/postgresql

Error: YAML parse error on postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 88: mapping values are not allowed in this context

**What you expected to happen**:
The chart to install successfully

**How to reproduce it** (as minimally and precisely as possible):
$ helm install --set "persistence.enabled=false" --name pg-demo stable/postgresql

**Anything else we need to know**:
Happens since commit c8330f2dbcf1075f1ed1d112f66c922a4a926083 

Maybe because we now have a duplicate `updateStrategy` in the stafulset.yaml.

I'll try to make a PR for this.

### PR DESCRIPTION
**Pull request by npiganeau**
#### What this PR does / why we need it:
Fix for #9847 

#### Which issue this PR fixes

  - fixes #9847 

#### Special notes for your reviewer:

@desaintmartin 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by npiganeau** [comment]
Ok. Added a new commit with modifications from #9834 to this PR

**Comment by stephenmoloney** [comment]
@npiganeau Can you change the title of this PR to something more meaningful 

Eg `[stable/postgresql] Fix breaking chart when persistence.enabled=false`

**Comment by stephenmoloney** [comment]
@desaintmartin @npiganeau  Which PR is the one to go forward? #9834 or #9853 ?

**Comment by desaintmartin** [comment]
https://github.com/helm/charts/pull/9834 has been merged.

**Pull request closed without merging**
