### PR TITLE
Fixed traefik empty values

### PR DESCRIPTION
**Pull request by anasinnyk**
**What this PR does / why we need it**:
Fixed helm issue for rewrite empty values.
example:
```
$ helm template --set "dashboard.auth.basic.user=pass" charts/stable/traefik > /dev/null
2018/05/16 16:50:42 warning: destination for auth is a table. Ignoring non-table value <nil>
```

**Special notes for your reviewer**:
It's just a warning, but it's so annoying when you run any helm command

### CODE REVIEW

**Comment by unguiculus** [comment]
I don't remember seeing this warning. What Helm version do you use? You may want to open an issue with Helm if you think this can be improved. Anyways, I'm against this change. It is good practice to have empty defaults in values.yaml. Otherwise, we'd probably have to change just about all chart in this repo.

**Comment by anasinnyk** [comment]
I checked it on v2.9.1 and v2.8.1.

**Comment by krancour** [comment]
I also have not encountered this issue and like @unguiculus feel opposed to this. I've seen things done this way before, but I feel like it's a lot of (manual) testing to verify that no template code that references these values is adversely affected by this. Unless I can be convinced that there really _is_ an issue here, I'd leave it be.

**Pull request closed without merging**
