### PR TITLE
[stable/nginx-lego] Convert registry to k8s.gcr.io

### PR DESCRIPTION
**Pull request by mattfarina**
See #3141 for more detail

### CODE REVIEW

**Review by prydonius — APPROVED** [review]
/lgtm

**Comment by prydonius** [comment]
/hold

@mattfarina since this chart is actually deprecated, I recommend we don't update it and just leave as-is. In fact, we should remove it from this repo at this point.

**Comment by mattfarina** [comment]
@prydonius I just added a topic for our next meeting on handling of deprecated charts. There are a few that are explicitly and implicitly.

**Comment by prydonius** [comment]
Sure, FWIW the procedure is documented here (https://github.com/kubernetes/helm/blob/master/docs/charts.md#deprecating-charts) but hasn't been implemented well.

**Comment by mattfarina** [comment]
@prydonius At what point after being marked deprecated does it get removed? Do we have any stats on its usage?

**Comment by prydonius** [comment]
@mattfarina it shouldn't be removed from the storage bucket and repo index, we should just remove it from this repo so that we don't accidentally update it again.

**Comment by mattfarina** [comment]
@prydonius Two questions:

1. What about cases like this where it's a vanity url change?
1. Should we add a CI check to fail if the chart has the deprecated property set to true?

**Comment by prydonius** [comment]
> 1. What about cases like this where it's a vanity url change?

I don't think there should be any changes to deprecated charts, but perhaps that's too strict a view?

> 2. Should we add a CI check to fail if the chart has the deprecated property set to true?

Possibly, though wouldn't it make more sense to just make sure they are removed from the repo? Is there any reason we'd want to keep them in the repo?

**Comment by mattfarina** [comment]
@prydonius 

> I don't think there should be any changes to deprecated charts, but perhaps that's too strict a view?

This might be worth hashing out with the other maintainers. I don't hold a strong view on this one.

> Possibly, though wouldn't it make more sense to just make sure they are removed from the repo? Is there any reason we'd want to keep them in the repo?

A few thoughts:

* If we remove it and someone comes along with another chart of the same name it could end up overwriting old chart. If versioning is similar some versions could be overridden while others are not creating a real problem for semver requirements.
* If someone wants to come along with a new chart and maintain it under the name we could use CI to make sure there's a major version bump (for compatibility) and that the deprecated is removed. We could enforce policy that way.
* If someone wants to know the history or status of the chart they would then have a record they could easily find and read.
* Above the deprecated property in the chart we could put a comment stating where they can find the procedure to un-deprecate it or even why it's deprecated.

**Comment by prydonius** [comment]
> This might be worth hashing out with the other maintainers. I don't hold a strong view on this one.

+1, let's discuss it next week or via mailing list

R.E. your other points, you've convinced me. In that case, a CI failure when updating a deprecated chart without un-deprecating would be ideal.

**Pull request merged**
