### PR TITLE
[stable/datadog] Fix https://github.com/kubernetes/charts/issues/6572

### PR DESCRIPTION
**Pull request by guizmaii**
**What this PR does / why we need it**:

Fix https://github.com/kubernetes/charts/issues/6572

### CODE REVIEW

**Comment by guizmaii** [comment]
Hi @xvello,

Google Cloud seems to have problems today. For now, I can't test. I'll try tomorrow morning.


Jules

**Comment by xvello** [comment]
@knqyf263 is that OK with you? This path should be safer for most OSes

**Comment by knqyf263** [comment]
@xvello OK! Thank you!

**Comment by JessicaGreben** [comment]
I tested these changes on GKE and it fixes the #6572 for me.  Hoping this will get merged soon 😄 @xvello @guizmaii

**Comment by ebalsumgo** [comment]
Is there a reason this only went into the DaemonSet and not the Deployment?

**Pull request merged**
