### PR TITLE
[stable/metricbeat] Add nonResourceURLs of "metrics" to RBAC

### PR DESCRIPTION
**Pull request by marc-sensenich**
Signed-off-by: Marc Sensenich <sensenichm91@gmail.com>

#### What this PR does / why we need it:
Adds the RBAC rule for allowing `metricbeat` to pull API Server metrics if using the apiserver metricset

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by at-k** [comment]
I tried this PR on my environment and confirmed it worked correctly to add rule. 

By the way, this rule is not included in the [Elastic Official configuration](https://raw.githubusercontent.com/elastic/beats/6.5/deploy/kubernetes/metricbeat-kubernetes.yaml). 

Can you show me an example, or how to test this PR ?

**Comment by marc-sensenich** [comment]
@at-k if you run the deployment in an RBAC enabled cluster with the following configuration for the Chart this will be a similar configuration to what we needed it for, based on https://www.elastic.co/guide/en/beats/metricbeat/6.5/metricbeat-module-kubernetes.html which should be updated in their guide for this case

```yaml
deployment:
  modules:
    kubernetes:
          enabled: true
          config:
           - module: kubernetes
              metricsets:
                - apiserver
             # Change this to http if your test cluster uses it
              hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              ssl.certificate_authorities:
                - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
```

**Comment by at-k** [comment]
@marc-sensenich Thank you, I understand. 

Actually, Metricbeat on my test cluster accesses `/metrics` when `apiserver` is used. (and it is failed because of rbac). 

It looks good to me except Chart version. 
Please check current version and bump it up.

**Comment by marc-sensenich** [comment]
@at-k update the Chart version

**Pull request merged**
