### PR TITLE
grafana will now tpl datasources

### PR DESCRIPTION
**Pull request by Place1**
#### What this PR does / why we need it:
This PR adds support for using values in grafana datasource configuration.

#### Which issue this PR fixes
fixes #10603

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
Correct. What about tpling the dashboard files? ;)

**Comment by Place1** [comment]
that sounds good too. Can dashboard files contain content that conflicts
with golang templates?

**Comment by Towmeykaw** [comment]
A dashboard is just json right? So should be fine.

**Comment by Place1** [comment]
From looking at some dashboard files they do contains snippets like this one (from a kubernetes dashboard):

```
"targets": [
            {
              "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", name=~\"^k8s_.*\", container_name!=\"POD\", namespace=~\"^$Namespace$\", pod_name=~\"^$deployment-.*\", pod_name=~\"^$Pod$\", kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
              "format": "time_series",
              "hide": false,
              "interval": "10s",
              "intervalFactor": 1,
              "legendFormat": "pod: {{ pod_name }} | {{ container_name }}",
              "metric": "container_cpu",
              "refId": "A",
              "step": 10
            }
          ],
```

if we run a dashboard file like this through `tpl` we'll get lots of errors like "function 'pod_name' not defined". i think it would be a large breaking change to tpl the dashboards by default. users would need to escape their dashboard files.

**Comment by maorfr** [comment]
I tend to agree. Although I am only talking about dahboards that are included in the `dashboards` directory.
Lets leave that for now and see if a need comes up.

@Place1, need to make all tests green to merge ;)

**Pull request merged**
