### PR TITLE
Sentry - Allow adding custom environment variables (for plugins support)

### PR DESCRIPTION
**Pull request by ekampf**
Added ability to specify custom environment variables in the values.yaml - this helps support Sentry plugins.

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @rothgar

**Comment by rothgar** [comment]
I'm just curious, when I'm cc'd on these PRs is there something I should be doing? I generally look at the PR but don't deploy or test them.
I just wanted to make sure nothing is waiting on me.

**Comment by unguiculus** [comment]
@rothgar You are pinged because you are the maintainer. You are expected to review the PR. In the end, you should give your LGTM if you are ok with the change or state otherwise if not.

**Pull request merged**
