### PR TITLE
Adds a newline between notes

### PR DESCRIPTION
**Pull request by itamarhaber**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign the CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement), also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by carrodher** [comment]
It seems that a new version of Redis has appeared, could you resolve the conflict?

**Comment by itamarhaber** [comment]
@caarlos0 resolved - ty.

EDIT: oops, prematurely said.
EDIT 2: now resolved

**Pull request merged**
