### PR TITLE
[stable/traefik]: Add securityContext to deployment

### PR DESCRIPTION
**Pull request by pho-enix**
Signed-off-by: Sebastian Poehn <sebastian.poehn@gmail.com>

#### Which issue this PR fixes
* Expose `securityContext` in values.yaml

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by pho-enix** [comment]
What's the point with the `Contribution Allowed` label? I thought you switched to DCO?!

**Comment by davidkarlsen** [comment]
@pho-enix can you bump the chart version again? Another change found way first.

**Comment by pho-enix** [comment]
Re-created as #11262

**Pull request closed without merging**
