### PR TITLE
[incubator/zookeeper] fix annotations possibly having null values instead of objects

### PR DESCRIPTION
**Pull request by cademarkegard**
#### What this PR does / why we need it:
When validating the Zookeeper chart with defaults against the JSON Schema for Kubernetes objects it is failing due to the `annotations` key having `null` values, for example:
```
metadata:
  labels:
     some:example
  annotations:
spec:
   ....
```

This PR fixes it so the chart can adhere to following the schema strictly.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Chili-Man** [comment]
hey @lachie83  or @kow3ns can we please get this reviewed ?

**Comment by zanhsieh** [comment]
@Chili-Man 
@cademarkegard 
I suggest you guys direct msg in Kubernetes Slack channel to the chart owner. Most of them come with exact the same id and same person.

**Pull request merged**
