### PR TITLE
[stable/etcd-operator] Fix table in readme

### PR DESCRIPTION
**Pull request by Dean-Coakley**
#### What this PR does / why we need it:
* Fix formatting error in table
* Made capitalisation consistent in table
* ~Update default values in README~ Landed in https://github.com/helm/charts/pull/9928

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Dean-Coakley** [comment]
@chancez Can I get a review on this please?

**Comment by chancez** [comment]
Sorry I'm not well up to date on the etcd-operator or chart, and am not using it anymore. I need to remove myself as a maintainer.

**Comment by Dean-Coakley** [comment]
No problem @chancez 

@davidkarlsen Can I get a quick review for this table formatting fix?

**Pull request merged**
