### PR TITLE
Calculate elasticsearch gateway parameters automatically from replicas

### PR DESCRIPTION
**Pull request by benjaminhuo**
Signed-off-by: Benjamin <benjamin@yunify.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
This gets in the way of having a single master for dev environments.
Maybe we can have an automatic value if not manually defined.

**Comment by benjaminhuo** [comment]
@desaintmartin , It's ok for the 1 master case.
In my code change below, "div .Values.master.replicas 2 | add1" =  (master replicas count)/2 + 1
minimum_master_nodes: {{ div .Values.master.replicas 2 | add1 }}

if the .Values.master.replicas is set to 1, then minimum_master_nodes will be set to (1/2) + 1 which is 1

if the .Values.master.replicas is set to 2, then minimum_master_nodes will be set to (2/2) + 1 which is 2

if the .Values.master.replicas is set to 3, then minimum_master_nodes will be set to (3/2) + 1 which is 2, the majority of master

**Comment by desaintmartin** [comment]
Oh, nice.
/ok-to-test
Maybe there are use cases that require to set MINIMUM_MASTER_NODE manually, let's see what other maintainers think about this.

**Comment by benjaminhuo** [comment]
@simonswine @rendhalver @icereval , are you ok with this PR?

Thanks
Ben

**Comment by desaintmartin** [comment]
Should we try to get this merged into https://github.com/elastic/helm-charts first? @rendhalver 

BTW I am still not sure that there is NO use case for manually setting this (i.e let this value be overridden)

**Comment by benjaminhuo** [comment]
Hi @desaintmartin and @rendhalver ,
I'm sure that this PR is better than current fix value 2 because it'll be changed based on data node replicas which is the correct behavior.

We have similar setting for our own cloud elastic service.

Ben

**Comment by rendhalver** [comment]
I am thinking we should be allowing people to set the value as well.

**Comment by benjaminhuo** [comment]
User has to setting these values manually whenever he need a new replica  number other than 2.
And maybe this is more troublesome

**Pull request closed without merging**
