### PR TITLE
feat(octopus): Add baseline Octopus chart

### PR DESCRIPTION
**Pull request by sylus**
**What this PR does / why we need it**: Adds baseline Octopus Helm chart

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Special notes for your reviewer**: There is still one tasks that needs to be done but I have been successfully running this with AzureAD integration and MSSQL Server on Linux.

- [x] Add optional MSSQL for Linux
- [x] Run through Linter
- [x] Figure out issue with Octopus container
- [x] Leverage official docker containers
- [x] Hard coded LB config under sqlDbConnectionString as Linux mssql svc not added to Win host
- [ ] Add tentacle container image (waiting on upstream 1709, 1803)

Pinging Octopus maintainer(s) @PaulStovell @Zentron

### CODE REVIEW

**Comment by sylus** [comment]
Hey @zentron @christianacca you know if anyone in Octopus has looked at this yet? Has been running solid for past 2-3 months and numerous upgrades.

**Comment by zentron** [comment]
What were you looking for from our side @sylus ?

**Comment by zentron** [comment]
We may end up needing to publish an officially supported helm chart in the future as the available environment variables may change in the future

**Comment by christianacca** [comment]
Hi @sylus, I'm only working with docker swarm (at the moment) so can't comment

**Comment by maorfr** [comment]
hey @sylus 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

(this is your 2nd chart i am seeing, may be best for you)

**Pull request closed without merging**
