### PR TITLE
[incubator/kube-downscaler] - Add priorityClassName and update image tag

### PR DESCRIPTION
**Pull request by Lord-Y**
Signed-off-by: Lord-Y <Lord-Y@users.noreply.github.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Pluies** [comment]
Hey @Lord-Y , thank you for this PR! 👍 

Could you please only add the `priorityClassName` in the podspec if it's defined? Something like:

```
    {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
    {{- end }}
```

It seems to be the preferred way to do it across other charts, and is explicit about only adding this line when needed!

**Comment by Lord-Y** [comment]
> Hey @Lord-Y , thank you for this PR! 👍
> 
> Could you please only add the `priorityClassName` in the podspec if it's defined? Something like:
> 
> ```
>     {{- if .Values.priorityClassName }}
>       priorityClassName: "{{ .Values.priorityClassName }}"
>     {{- end }}
> ```
> 
> It seems to be the preferred way to do it across other charts, and is explicit about only adding this line when needed!

@Pluies I updated the deployment accordingly.

**Review by Pluies — APPROVED** [review]
Looks good to me!

/ok-to-test
/approve

**Pull request merged**
