### PR TITLE
[stable/fluent-bit] Update fluent-bit to 0.13.0. Add section for parsers

### PR DESCRIPTION
**Pull request by gabe-sorensen**
@edsiper @kfox1111 
**What this PR does / why we need it**:
This makes the default image for the chart fluent-bit 0.13.0. It also adds a section for defining parsers, which is included with the 0.13.0 release of fluent-bit.

This is what I was using for my parsers section in values.yaml:
```yaml
parsers:
  regex:
    - name: apache
      regex: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
      timeKey: time
      timeFormat: '%d/%b/%Y:%H:%M:%S %z'
    - name: apache2
      regex: '^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
      timeKey: time
      timeFormat: '%d/%b/%Y:%H:%M:%S %z'
    - name: apache_error
      regex: '^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$'
    - name: nginx
      regex: '^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$'
      timeKey: time
      timeFormat: '%d/%b/%Y:%H:%M:%S %z'
  json:
    - name: json
      timeKey: time
      timeFormat: '%d/%b/%Y:%H:%M:%S %z'
    - name: docker
      timeKey: time
      timeFormat: '%Y-%m-%dT%H:%M:%S.%L'
      timeKeep: "On"
      decodeFieldAs: "escaped"
      decodeField: "log"
```

### CODE REVIEW

**Comment by kfox1111** [comment]
looks good to me, except I'd bump the minor version of the chart as there are breaking changes in the values.

**Comment by edsiper** [comment]
LGTM

**Pull request merged**
