### PR TITLE
[stable/prometheus-operator] k8s 1.16 Install dashboards and prometheus rules

### LINKED ISSUE #18347: [stable/prometheus-operator] dashboards/alerts not installed
Default dashboards and alerts are not installed

**Version of Helm and Kubernetes**:
Helm v2.13.1 / Kubernetes v1.16

**Which chart**:
prometheus-operator-6.21.0

This works as expected in Kubernetes v1.15.4

### PR DESCRIPTION
**Pull request by asosso**
Default dashboards and prometheus rules aren't installed in Kubernetes 1.16.

#### What this PR does / why we need it:
Default dashboards and prometheus rules aren't installed in Kubernetes 1.16.

#### Which issue this PR fixes

  - fixes #18347

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
/ok-to-test
@asosso 
If this PR passed, would you mind to volunteer to be one of this chart owners please? See:

https://github.com/helm/charts/issues/13867

@gianrubio no longer interested in maintaining this chart.

**Comment by den-is** [comment]
That's included in https://github.com/helm/charts/pull/18375
I'm waiting collaboration on opinions on that matter https://github.com/helm/charts/pull/18375#issuecomment-546674057

Also kubernetes v1.17.0 will be released very soon. v1.18.0 is not that far away either with such lightning fast release cycle of kubernetes. So I'm thinking of bumping MAX kubernetes to 9.9.9-9.

**Comment by vsliouniaev** [comment]
> So I'm thinking of bumping MAX kubernetes to 9.9.9-9

Yeah, it shouldn't have a max limit

**Comment by den-is** [comment]
I'm not sure why you keep pushing as you have duplicate of https://github.com/helm/charts/pull/18375 with very same issues :)

**Comment by den-is** [comment]
@asosso about what new functionalities you talk ? my PR has no new features.

And you have not just extended max kubernetes version to enable it in 1.16, but you run same python scripts and pulled same issues from the latest upstream. I mean if you have read your pushed changes at all. and did not read problems discovered and fixed by other people.

**Comment by asosso** [comment]
@den-is i think is faster to merge this pull request to fix 1.16 compatibility without update dashboards and rules (I rebased this PR).

Your PR seems good, could you bump to 7.0.x version?

**Comment by den-is** [comment]
@asosso 
I see that you have pushed fix, removing faulty changes.
Now your commit is good and of course is faster fix to present problems.

I will merge my PR later. Coz I'm still waiting upstream operator to release new version. Plus going to push fixes to upstream mixin repo too.

**Comment by vsliouniaev** [comment]
Hey, trying to figure out why the tests are flaking out on you here. Hopefully this should resolve it
https://github.com/helm/charts/pull/18430

**Comment by zanhsieh** [comment]
@asosso 
Could you fix conflicting file please?
stable/prometheus-operator/Chart.yaml

**Comment by asosso** [comment]
@zanhsieh done

**Pull request merged**
