### PR TITLE
[stable/sonarqube] Fix chart rendering when providing 'lib' values

### LINKED ISSUE #20269: [stable/sonarqube] Chart rendering fails when adding 'lib' values
**Describe the bug**
When adding 'lib' values in 'plugins', the chart rendering fails.

**Version of Helm and Kubernetes**:
`Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}`
`Kubernetes: 1.14.x`

**Which chart**:
stable/sonarqube 3.3.2

**What happened**:
Issuing command `helm upgrade stable/sonarqube` or `helm install stable/sonarqube` with `-f values.yaml` like this:

    plugins:
      install:
        - https://binaries.sonarsource.com/Distribution/sonar-php-plugin/sonar-php-plugin-3.3.0.5166.jar
        - https://binaries.sonarsource.com/Distribution/sonar-csharp-plugin/sonar-csharp-plugin-8.1.0.13383.jar
        - https://binaries.sonarsource.com/Distribution/sonar-python-plugin/sonar-python-plugin-2.3.0.5351.jar
        - https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.2.0/sonarqube-community-branch-plugin-1.2.0.jar
      lib:
        - sonarqube-community-branch-plugin-1.2.0.jar

Produces the following error:

    UPGRADE FAILED
    Error: render error in "sonarqube/templates/copy-plugins.yaml": template: sonarqube/templates/copy-plugins.yaml:30:24: executing "sonarqube/templates/copy-plugins.yaml" at <.Values.sonarqubeFolder>: can't evaluate field Values in type interface {}
    Error: UPGRADE FAILED: render error in "sonarqube/templates/copy-plugins.yaml": template: sonarqube/templates/copy-plugins.yaml:30:24: executing "sonarqube/templates/copy-plugins.yaml" at <.Values.sonarqubeFolder>: can't evaluate field Values in type interface {}

**What you expected to happen**:
The chart should be rendered and installed normally

**How to reproduce it** (as minimally and precisely as possible):
Insert any value in `lib` and try to install the chart

**Anything else we need to know**:
The problem is in file copy-plugins.yaml, inside the `range` statement we should add `$` before `.Values` to make it access global scope.

https://helm.sh/docs/chart_template_guide/variables/

    Variables are normally not “global”. They are scoped to the block in which they are declared. Earlier, we assigned $relname in the top level of the template. That variable will be in scope for the entire template. But in our last example, $key and $val will only be in scope inside of the {{ range... }}{{ end }} block.
    However, there is one variable that is always global - $ - this variable will always point to the root context. This can be very useful when you are looping in a range need to know the chart’s release name.

### PR DESCRIPTION
**Pull request by heruscode**
…20269)

Signed-off-by: Marcio Rodrigues <marcio.mrg1@gmail.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
Fix chart rendering problem

#### Which issue this PR fixes
  - fixes #20269

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rjkernick** [comment]
Duplicate of #20255

**Comment by davidkarlsen** [comment]
This chart has been deprecated and moved: https://github.com/helm/charts/pull/21007

**Pull request closed without merging**
