### PR TITLE
[stable/redis-ha] Adds imagePullSecrets

### PR DESCRIPTION
**Pull request by marcostvz**
Signed-off-by: Marcos Estevez <marcos.stvz@gmail.com>

#### What this PR does / why we need it:
Adds imagePullSecrets to serviceAccounts, needed to pull the images if they're in private registries.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@marcostvz
Thank you for the PR!

I think this would be better to apply imagePullSecrets for each component (haproxy/redis) separately. 

Seeing as the images have different repositories, I think its more appropriate.

**Comment by marcostvz** [comment]
Hello @DandyDeveloper,

In our use case, we only use 1 global imagePullSecret as we replicate all the public images into the same registry. But still I gave the option to have separated imagePullSecrets along with the global ones.

Kind regards :)

**Comment by DandyDeveloper** [comment]
> In our use case, we only use 1 global imagePullSecret as we replicate all the public images into the same private registry. But still I gave the option to have separated imagePullSecrets along with the global ones.

@marcostvz Thanks for the update, I still think we should completely remove the `.Values.global` section, it's confusing for people coming in. Although I completely understand that your environment uses a single global private source, not everyone will, and although I am in favour of DRY principles, here I think have 2 sections is justified without a global. 

I'm willing to have my mind changed on this though!

**Comment by marcostvz** [comment]
@DandyDeveloper, I was trying to make it flexible to all use cases, but no problem, we can be flexible too specifying the imagePullSecrets in redis section ;)

Thanks for your review!

**Comment by DandyDeveloper** [comment]
> @DandyDeveloper, I was trying to make it flexible to all use cases, but no problem, we can be flexible too specifying the imagePullSecrets in redis section ;)

I definitely agree with imagePullSecrets being defined anywhere we pull an image. 100%

I just think we should avoid global values because its unnecessary overhead that means we'll have to keep an additional eye on it, just better off without it in the long term, I think.

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
