### PR TITLE
[stable/jenkins] Update Jenkins images and plugins

### PR DESCRIPTION
**Pull request by jordanjennings**
The jenkins images have moved from the `jenkinsci` organization just to `jenkins` on Docker Hub, updated that here. Also bumped the versions to the latest available for the images and the plugins. Tested on my cluster, working as expected (and the in-place upgrade worked too).

### CODE REVIEW

**Comment by viglesiasce** [comment]
For some reason this did not work for me. I got the following error:

```
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Nov 09, 2017 5:37:05 AM WARNING org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Failed to count the # of live instances on Kubernetes
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:422)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:375)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:715)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:61)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viglesiasce** [comment]
Here is the error from the agent when trying to connect:

```
JNLP agent connected from 10.92.1.50/10.92.1.50
Waiting for slave to connect (1/100): default-r3smmWaiting for slave to connect (2/100): default-r3smmWaiting for slave to connect (3/100): default-r3smmWaiting for slave to connect (4/100): default-r3smmWaiting for slave to connect (5/100): default-r3smmRemoting version: 3.10
Waiting for slave to connect (6/100): default-r3smmWaiting for slave to connect (7/100): default-r3smmWaiting for slave to connect (8/100): default-r3smmWaiting for slave to connect (9/100): default-r3smmThis is a Unix agent
Waiting for slave to connect (10/100): default-r3smmWaiting for slave to connect (11/100): default-r3smmWaiting for slave to connect (12/100): default-r3smmWaiting for slave to connect (13/100): default-r3smmWaiting for slave to connect (14/100): default-r3smmWaiting for slave to connect (15/100): default-r3smmWaiting for slave to connect (16/100): default-r3smmWaiting for slave to connect (17/100): default-r3smmERROR: Failed to install restarter
ERROR: Connection terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
Caused: hudson.remoting.ChannelClosedException: Remote call on JNLP4-connect connection from 10.92.1.50/10.92.1.50:52438 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:897)
	at jenkins.slaves.restarter.JnlpSlaveRestarterInstaller.install(JnlpSlaveRestarterInstaller.java:53)
	at jenkins.slaves.restarter.JnlpSlaveRestarterInstaller.access$000(JnlpSlaveRestarterInstaller.java:34)
	at jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$1.call(JnlpSlaveRestarterInstaller.java:40)
	at jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$1.call(JnlpSlaveRestarterInstaller.java:37)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jordanjennings** [comment]
@viglesiasce Not seeing that myself, but I did notice that the chart upgrade did NOT change the image reference in the default pod template for the Kubernetes plugin. After changing it to 3.10-1 my builds are still working, and I confirmed that the agent pod is using the updated version. Will test further with a new installation.

**Comment by viglesiasce** [comment]
Thanks @jordanjennings mine was an install from scratch.

**Comment by jordanjennings** [comment]
@viglesiasce Fresh install working for me, hmmm... I also tried with the latest Jenkins (2.89) and that worked too, and tried with the alpine variants of both jenkins and jnlp just for kicks. Worked in all cases for me. Any chance the test cluster you were using is misconfigured in some way?

**Comment by audip** [comment]
@viglesiasce @jordanjennings Are we going to have a separate chart for Jenkins LTS? 
The question as this image is being bumped to 2.84 and LTS is 2.73

**Comment by jordanjennings** [comment]
@audip It makes sense to have the default be the LTS and let people override if they want. I'll test things on the current LTS and update the pull request if it's working.

**Comment by jordanjennings** [comment]
Updated to LTS image as default. Everything working for me on a fresh install with LTS and JNLP 3.10-1.

**Comment by viglesiasce** [comment]
Hey @jordanjennings!

I was able to get this working but only by setting the label for my test job explicitly. Is that new behavior in 2.73, where it no longer uses K8s agents if no label is set?

**Comment by jordanjennings** [comment]
@viglesiasce Not sure if that's new behavior, but it has never worked for me without the label being explicitly mentioned.

**Comment by viglesiasce** [comment]
Thanks @jordanjennings for the quick response.

**Pull request merged**
