### PR TITLE
[stable/openebs] Update charts to 1.6.0 release

### PR DESCRIPTION
**Pull request by ChandanSagar**
- Updated image tags as per 1.6.0 release
 - Updated values.yaml
 - Updated README
 - Updated clusterrole.yaml

Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by prateekpandey14 — APPROVED** [review]
Lgtm

**Review by kmova — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
