### PR TITLE
Fixed the broker id

### PR DESCRIPTION
**Pull request by IvanovOleg**
#### What this PR does / why we need it:
Fixed the wrong brocker id definition (HOSTNAME variable is not defined)
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by IvanovOleg** [comment]
Can anybody approve?

**Comment by IvanovOleg** [comment]
Is anybody here?

**Comment by benjigoldberg** [comment]
@IvanovOleg were you seeing hostname undefined in the basic installation of this chart with no modified values? Or did you change configuration/image?

**Comment by IvanovOleg** [comment]
@benjigoldberg, KAFKA_BROKER_ID variable depends on HOSTNAME variable which is not set. During the kafka loading process it checks KAFKA_BROKER_ID which has invalid value (empty) and fails to start. Kubernetes 1.13.1

**Comment by IvanovOleg** [comment]
`[2018-12-17 19:30:12,704] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration broker.id: Not a number of type INT` 
This error appears by default (zookeeper.enabled=false zookeeper.url=zookeeper), zookeeper is installed using the appropriate package.

**Comment by IvanovOleg** [comment]
Will anybody approve?

**Comment by IvanovOleg** [comment]
Friendly reminder

**Comment by cpanato** [comment]
running the CI first. very sorry for this delay. i will looks into, but I'm not familiar with kafka

**Comment by cpanato** [comment]
@IvanovOleg To run the tests this branch needs to be updated, can you rebase and bump the chart version?

**Comment by IvanovOleg** [comment]
@cpanato 
I recreated this PR as https://github.com/helm/charts/pull/10591 due to the merging conflict.

**Pull request closed without merging**
