### PR TITLE
[incubator/zookeeper]: fix a typo

### PR DESCRIPTION
**Pull request by daixiang0**
When i debug run script:
```
+ echo zookeeper.log.threshold=INFO
run: line 70: $LOGGER_PROPERS_FILE: ambiguous redirect
```
Then i find `LOG4J_PROPERTIES` val is not defined:
```
incubator/zookeeper$ git grep LOGGER_PROPERS_FILE
templates/config-script.yaml:91:      echo "zookeeper.log.threshold=$ZK_LOG_LEVEL" >> $LOGGER_PROPERS_FILE
```

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@tadas-subonis  @kow3ns mind have a look?

**Comment by daixiang0** [comment]
@tadas-subonis @kow3ns mind have a look?

**Comment by daixiang0** [comment]
@tadas-subonis @kow3ns mind have a look?

**Comment by daixiang0** [comment]
Hi, @lachie83 @kow3ns mind have a look?

**Comment by daixiang0** [comment]
@lachie83 hi, test pass!

**Comment by zanhsieh** [comment]
@kow3ns
Please take a look. Thanks.

**Comment by zanhsieh** [comment]
@daixiang0 
Another conflicting file need to resolve:
incubator/zookeeper/Chart.yaml

**Comment by daixiang0** [comment]
@zanhsieh  done.

**Comment by daixiang0** [comment]
@zanhsieh @lachie83 test pass.

**Comment by zanhsieh** [comment]
@daixiang0 
Hey, 'File changed 0' ? Does the master branch catch up what your change before?

**Pull request closed without merging**
