### PR TITLE
[stable/gocd] add host in template ingress.yaml instead of using default backend

### LINKED ISSUE #10750: [stable/gocd] GoCD Ingress default template
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST  

**Version of Helm and Kubernetes**:

helm v2.12.1
kubernetes v1.12.4

**Which chart**:

stable/gocd

**Anything else we need to know**:

In file "gocd/templates/ingress.yaml":
I would like to change `spec`
from

```
  backend:
    serviceName: {{ template "gocd.fullname" . }}-server
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}

```
to

```
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "gocd.fullname" . }}-server
            servicePort: {{ .Values.server.service.httpPort }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
```

Because when I use the default ingress config I can not access gocd by the hostname that I defined in `values.yaml`.   
I deploy  gocd behind traefik.
Here is the error log: `"level":"warning","msg":"Error in ingress: HTTP is nil"`

@varshavaradarajan Could you check this? Thanks.

### PR DESCRIPTION
**Pull request by colachg**
#### What this PR does / why we need it:
 if there is no host in template ingress.yaml, use default backend.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10750

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by sheroy** [comment]
@colachg Sure, I'll test it today.

**Comment by arvindsv** [comment]
@colachg Just for the record, this is different from my recommendation mentioned [here](https://github.com/helm/charts/pull/10795#issuecomment-457779917). The difference being that it's not backwards compatible with what exists today.

In case you have an ingress host name defined, you can't reach the server through the ingress IP any more. The [Default Backend](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend) mentioned in the k8s docs will not be used (since one won't be defined, after this change).

I'm not saying that's necessarily wrong. Maybe that is how it is used and you should be expected to only use ingress hosts. I just don't know what it is that people use.

What I like, though, is that with no change made to values.yaml (assuming you had no hosts defined), then the behavior is unchanged and the default backend is still defined and usable.

**Comment by arvindsv** [comment]
Maybe @MPV, @balboah and others who've contributed to this chart have thoughts / ideas?

**Comment by colachg** [comment]
@arvindsv Thanks for your time :)
> What I like, though, is that with no change made to values.yaml (assuming you had no hosts defined), then the behavior is unchanged and the default backend is still defined and usable.  

Yes, the hosts in values are commented out, So the default backend works.
Then if somebody uncomments the hosts (s)he should know what will happen, maybe we can add some explains in comments.

**Comment by colachg** [comment]
@arvindsv Thanks for your time :)
> What I like, though, is that with no change made to values.yaml (assuming you had no hosts defined), then the behavior is unchanged and the default backend is still defined and usable.  

Yes, the hosts in values are commented out, So the default backend works.
Then if somebody uncomments the hosts (s)he should know what will happen, maybe we can add some explains in comments.

**Comment by MPV** [comment]
Sorry @arvindsv, we have only spun up mainly agents with this chart yet. Soon looking to migrate our server into Kube too, but I'm not sure I have much input here yet. 

Also, I only see the exact change described in this PR, and not much context on why this is needed.

**Comment by varshavaradarajan** [comment]
@MPV - more context: https://github.com/helm/charts/issues/10750 and https://github.com/helm/charts/pull/10795 if you're interested.

**Comment by MPV** [comment]
To me, the change makes sense in a general sense (supporting Traefik). 

I can't speak to the regard how others use the ingress (by IP/hostname) though, sorry.

**Comment by arvindsv** [comment]
@MPV No worries. Thanks for taking a look and thinking about it.

**Pull request merged**
