### PR TITLE
[incubator/opsdroid] Add opsdroid chart

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Add incubator chart for the [opsdroid project](https://opsdroid.dev).

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
In testing it seems like the liveness probe is failing due to default settings which only run the web server on host `127.0.0.1`. This causes the opsdroid pod to continuously be restarted and eventually begin backing off.

**Comment by jacobtomlinson** [comment]
This is resolved now with opsdroid `v0.15.4`. The chart has been updated and I can confirm that the liveness probe is working.

```
INFO opsdroid.web: Started web server on http://0.0.0.0:8080
INFO aiohttp.access: 100.97.97.1 [16/May/2019:09:18:38 +0000] "GET /stats HTTP/1.1" 200 385 "-" "kube-probe/1.9"
INFO aiohttp.access: 100.97.97.1 [16/May/2019:09:18:48 +0000] "GET /stats HTTP/1.1" 200 385 "-" "kube-probe/1.9"
INFO aiohttp.access: 100.97.97.1 [16/May/2019:09:18:58 +0000] "GET /stats HTTP/1.1" 200 385 "-" "kube-probe/1.9"
INFO aiohttp.access: 100.97.97.1 [16/May/2019:09:19:08 +0000] "GET /stats HTTP/1.1" 200 385 "-" "kube-probe/1.9"
INFO aiohttp.access: 100.97.97.1 [16/May/2019:09:19:18 +0000] "GET /stats HTTP/1.1" 200 385 "-" "kube-probe/1.9"
```

**Comment by jacobtomlinson** [comment]
/assign @davidkarlsen

Please could someone review this

**Comment by maorfr** [comment]
hey @jacobtomlinson,

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

**Comment by jacobtomlinson** [comment]
@maorfr I hadn't! Is there a move away from this repository then?

**Comment by maorfr** [comment]
this is the intention, yes.
https://helm.sh/blog/intro-helm-hub/

**Comment by jacobtomlinson** [comment]
Done!
https://github.com/helm/hub/pull/99

**Comment by maorfr** [comment]
awesome!
feel free to close this one :)

**Pull request closed without merging**
