### PR TITLE
[stable/concourse]: Add a default prefix

### PR DESCRIPTION
**Pull request by limakzi**
This commit adds a default value for prefix, per reference:
https://docs.datadoghq.com/integrations/concourse_ci/.
It avoids emitting custom metrics.

Signed-off-by: Zabielski, Kamil <kamil.zabielski@lintops.tech>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by YoussB — CHANGES_REQUESTED** [review]
nice catch, thanks @limakzi 
- for context the prefix is mentioned already on the [datadog website](https://docs.datadoghq.com/integrations/concourse_ci/#configuration)
- @limakzi do you mind sorting the entries in the README.md, this is the convention that we have been following here.

**Comment by limakzi** [comment]
@YoussB I fix the order as it is in values. Enabled is the first. The rest is alphabetically, as far as I see.

**Comment by YoussB** [comment]
- we have the whole list sorted alphabetically, you can just run `:sort` on the whole table in `vim` and will fix it. 
- we don't have any login in place for how the entries are sorted.

**Comment by limakzi** [comment]
@YoussB Now it is sorted, It seems that it wasn't sorted before.
I cut one more duplicate in README.md as well. Peace!

**Review by YoussB — APPROVED** [review]
/lgtm

**Comment by YoussB** [comment]
Thanks a lot @limakzi

**Pull request merged**
