### PR TITLE
[stable/minecraft] upgrade to 1.13.1

### PR DESCRIPTION
**Pull request by JulienTant**
cc maintainer: @gtaylor 

#### What this PR does / why we need it:

This PR upgrade minecraft to the last version

#### Which issue this PR fixes

none

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gtaylor — CHANGES_REQUESTED** [review]
Do we need to also bump the chart version patch level?

**Comment by JulienTant** [comment]
The chart version was perfectly synced with the minecraft version, So I thought this was what we wanted. Tell me if you have a better idea

**Comment by JulienTant** [comment]
Oh wow i just totally missed that one, thanks :)

**Comment by gtaylor** [comment]
Thanks, @JulienTant and @davidkarlsen!

**Pull request merged**
