### PR TITLE
[stable/jenkins] Provision credentials.xml, secrets files and jobs

### PR DESCRIPTION
**Pull request by siwyd**
In order to allow for a more immutable deployment, this commit
adds support to allow provisioning of the following:
- credentials.xml
- secrets files
- jobs

### CODE REVIEW

**Comment by siwyd** [comment]
It's okay for me to assign like this? First pull request here...

/assign @viglesiasce 
/assign @lachie83

**Comment by timothyclarke** [comment]
@siwyd is this copying / deploying pre-created secrets / jobs etc or is it creating from scratch. 
In short if I was new to jenkins could I use this to create a fully working jenkins host with appropriate jobs / pipelines or is it primarily as a migration tool from an existing jenkins instance.

**Comment by siwyd** [comment]
@timothyclarke The intention is to allow for a reproducible Jenkins master. For me, at the moment, that means defining a job that polls GitHub, using credentials provided in credentials.xml (and decoded with defined keys).

So initially, I spin up Jenkins, and I manually provision the credentials and job. Because I don't want to do that again after doing it the first time, I get the credentials.xml, the secrets files needed to decode the credentials.xml and the GitHub job config XML. The job I put in values.yaml and everything else in Kubernetes secrets, as needed.

I suppose for a working Jenkins instance, there is a need for some pre-created secrets most of the time...

**Pull request merged**
