### PR TITLE
fixes example for importing grafana dashboards with the api

### PR DESCRIPTION
**Pull request by sstarcher**

### CODE REVIEW

**Comment by sstarcher** [comment]
These 2 pull requests are pretty much duplicates - https://github.com/kubernetes/charts/pull/4392

#4392 also changes it from wget to curl not sure why

**Comment by sstarcher** [comment]
Nothing I changed should effect the e2e test.  A `helm install .` works locally and no pods are failing.

**Comment by unguiculus** [comment]
Here' the reason: #4267

**Comment by unguiculus** [comment]
There's another PR that also fixes the URL in another place. See #4476.

I'd suggest you add this to your PR and we close the other one.

**Comment by unguiculus** [comment]
Two more related PR: #4129, #4096

Let's consolidate this here.

**Comment by sstarcher** [comment]
@unguiculus fixed the second location

**Comment by sstarcher** [comment]
rebased and fixed merge conflict

**Comment by sstarcher** [comment]
@unguiculus had to resolve conflicts can I get another lgtm

**Pull request merged**
