### PR TITLE
[stable/prometheus-node-exporter] - add podAnnotations value

### PR DESCRIPTION
**Pull request by Smirl**
Signed-off-by: Alex Williams <alex.williams@skyscanner.net>

#### Is this a new chart
NO

#### What this PR does / why we need it:
Add `podAnnotations` so node-exporter can have annotations added, for example `sidecar.istio.io/inject: false`

#### Which issue this PR fixes
No open issue when searching.

#### Special notes for your reviewer:
I have also added a default `podLabels` to the values.yaml. As that acts as a sort of documentation too.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Smirl** [comment]
FYI @gianrubio 

There are other PRs that might clash on chart version. I found: 

- https://github.com/helm/charts/pull/17359
- https://github.com/helm/charts/pull/17534
- https://github.com/helm/charts/pull/17712

**Review by prydonius — APPROVED** [review]
/lgtm

**Comment by Smirl** [comment]
Bump @gianrubio . Could you please take a look at this one?

**Comment by Smirl** [comment]
Hey @gianrubio 

I have rebased and fixed merge conflicts. However, the e2e tests are still failing and I'm a bit unsure why this is the case. Are these tests always failing or is it something that I have introduced?

Happy to fix if you can point me in the right direction.

Thanks

**Pull request merged**
