### PR TITLE
[stable/prometheus-operator] Update KubeNodeUnreachable alert to fix #21371

### LINKED ISSUE #21371: [stable/prometheus-operator] Cluster-autoscaler down-scaling events causes KubeNodeUnreachable alerts
**Describe the bug**
When a cluster autoscaling scale-down event occurs it causes a KubeNodeUnreachable alert to be fired. This is described in-depth in here: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/300 (and should be mimicked here as well)

**Version of Helm and Kubernetes**:
2.x, 1.14.x

**Which chart**:
stable/prometheus-operator 

**What happened**:
Alert is fired in the shutdown phase of the Node

**What you expected to happen**:
When a node is being scaled-down an alarm isn't fired.

**How to reproduce it** (as minimally and precisely as possible):
Scale down your k8s cluster

**Anything else we need to know**:
See discussion here: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/300

### PR DESCRIPTION
**Pull request by cablespaghetti**
Signed-off-by: Sam Weston <weston.sam@gmail.com>

#### What this PR does / why we need it:
Fixes #21371 by copying changes from https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/415. Stops the KubeNodeUnreachable alert going off every time cluster autoscaler marks a node for scale down.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@cablespaghetti could you please update the chart version here?

**Comment by cablespaghetti** [comment]
Sorry for the delay. Done.

**Comment by cablespaghetti** [comment]
I'm not sure why the test is failing. Works fine for me.
image

**Comment by vsliouniaev** [comment]
The test cluster is broken and is not allowing node-exporter to be installed. Unfortunately there isn't much I can do about this. @unguiculus , any chance you could help?

**Pull request merged**
