### PR TITLE
Remove 'Getting Started:' from various NOTES.txt.

### PR DESCRIPTION
**Pull request by gtaylor**
This was raised as being ambiguous during another review. I had copypasta'd this from the mysql chart. This PR removes it from everywhere else.

:eyeglasses: @prydonius @viglesiasce

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
LGTM

**Comment by prydonius** [comment]
Tests are failing due to a separate issue with some charts getting a deletion error.

I'm not 100% sure if we should bump chart versions here, my thinking is we don't want to. Thoughts @viglesiasce @lachie83?

**Comment by viglesiasce** [comment]
I'm torn on the NOTES.txt. For README i dont think we should but notes seems like we should since it is a user facing change.

**Comment by gtaylor** [comment]
I think any change to a template that causes meaningful differences in
behavior or instructions would definitely be a bump.

While this charts repo is so early, however, I think the version bump for
cosmetics would cause more potential trouble on the user side than it'd be
worth. Despite being the "right" thing to do.

T'is but one opinion, though!

**Comment by lachie83** [comment]
Is there any way to track the version changelog from within a chart?

**Comment by gtaylor** [comment]
Not currently, to my understanding.

**Comment by prydonius** [comment]
@viglesiasce @gtaylor @lachie83 does it make sense to judge it on a case-by-case basis for NOTES.txt changes, or apply a hard rule? There are certainly some changes to NOTES.txt that should require a bump in chart version, but some changes, such as this or spelling fixups, are just documentation changes that don't really affect the user and deployment that much.

**Comment by gtaylor** [comment]
For now I'd lean towards a case-by-case decision, pending the fleshing out of policies. We're likely to have little things like this to do across a number of charts as we make style decisions.

Would definitely make sense to get more rigid in the future as things solidify.

**Comment by lachie83** [comment]
I'm happy not bumping the version for this particular change as it's only cosmetic.

**Comment by prydonius** [comment]
Also agree that this change should not require bumping the version 👍 . @viglesiasce any strong objections to merging as-is?

**Comment by viglesiasce** [comment]
LGTM Whats the status on the fix for this CI issue?

**Pull request merged**
