### PR TITLE
[stable/redis] Fix psp for chart stable/redis

### PR DESCRIPTION
**Pull request by msschl**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/redis]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@msschl 
Could you bump the chart version to latest please? Thank you.

**Review by juan131 — APPROVED** [review]
Thanks so much for this great contribution!

**Comment by juan131** [comment]
Hi @msschl 

As @zanhsieh you need to rebase from master and bump the patch version in the **Chart.yaml**. Check the error below in the CI tests:

```
No requirements found in stable/redis/charts.
Linting chart 'redis => (version: "9.5.1", path: "stable/redis")'
Checking chart 'redis => (version: "9.5.1", path: "stable/redis")' for a version bump...
Old chart version: 9.5.1
New chart version: 9.5.1
```

**Comment by msschl** [comment]
@juan131 @zanhsieh rebased to master

**Comment by msschl** [comment]
@javsalgar @tompizmor @juan131 any news?

**Comment by juan131** [comment]
Hi @msschl

My apologies. I lost the track of this PR, please rebase the branch for master and bump the version again and I'll add the corresponding labels to merge the PR

**Review by juan131 — APPROVED** [review]

**Comment by msschl** [comment]
@juan131 done

**Review by juan131 — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
