### PR TITLE
[stable/consul] Fixes compatibility with 1.16

### PR DESCRIPTION
**Pull request by daixiang0**
To support 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@zanhsieh seems ci test env broken.

**Comment by daixiang0** [comment]
@zanhsieh is ci broken?

**Comment by zanhsieh** [comment]
@daixiang0 
I think yes. @unguiculus Could you take a look please?

**Comment by daixiang0** [comment]
@unguiculus any input?

**Comment by zanhsieh** [comment]
@maorfr Could you take a look this please? Thank you.

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Pull request merged**
