### PR TITLE
Fixed external postgres endpoint in worker_configmap.

### LINKED ISSUE #7402: [stable/anchore-engine] external db configuration not respected in worker_configmap.yaml
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**: 

**Which chart**: stable/anchore-engine

**What happened**: postgresql.externalEndpoint is ignored in templates/worker_configmap.yaml

**What you expected to happen**: it should be set just as in templates/core_configmap.yaml

**How to reproduce it** (as minimally and precisely as possible): Set postgresql.enabled=False and postgresql.externalEndpoint to a valid postgresql endpoint and start up the system. The worker pods will fail trying to get the postgesql endpoint that is not configured.

**Anything else we need to know**: Solution is to just re-use the logic from the core_configmap.yaml in the worker_configmap.yaml

### PR DESCRIPTION
**Pull request by Btodhunter**
Updated appVersion.

Updated chart version.

Signed-off-by: Brady Todhunter <bradyt@anchore.com>

**What this PR does / why we need it**: Fixes the configuration of external postgresql endpoints for worker nodes. Also upgrades the app version to the latest version of anchore-engine.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #7402

**Special notes for your reviewer**:

### CODE REVIEW

**Review by zhill — APPROVED** [review]

**Comment by mattfarina** [comment]
Manually added the contribution allowed label to unblock this as I troubleshoot the script.

**Comment by zhill** [comment]
thanks @mattfarina , much appreciated!

**Pull request merged**
