### PR TITLE
[incubator/jaeger] include namespace when logging into Jaeger Query UI

### PR DESCRIPTION
**Pull request by hardbyte**
**What this PR does / why we need it**: 

If someone happens to deploy Jaeger into a namespace (e.g.  `monitoring`) then it would be good if the commands that are printed out during deployment work. The `kubectl get pods` command includes the namespace, but for some reason not the `kubectl port-forward`

### CODE REVIEW

**Comment by hardbyte** [comment]
I've signed the Contributor License Agreement

**Comment by davidvonthenen** [comment]
@hardbyte  You need a bump the version in the Chart.yaml to pass tide, but looks good!

**Pull request merged**
