### PR TITLE
[stable/nginx-ingress] Update helper functions to follow new best practice

### PR DESCRIPTION
**Pull request by whereisaaron**
The recommended helper function created by `helm create` now avoid the double naming situation where `helm install --name nginx-ingress stable/nginx-ingress` lead to pod names like `nginx-ingress-nginx-ingress-controller-1234567890-abcde`. This patch updates the `nginx-ingress` to work the same way.

### CODE REVIEW

**Comment by mattfarina** [comment]
@whereisaaron Thanks for the contribution. Charts are immutable. Could you please increment the chart version in the Chart.yaml file.

**Comment by whereisaaron** [comment]
Thanks @mattfarina! I didn't know which order PRs would be merged, so wasn't sure of the eventual version number. I have bumped it now from 8.22 to 8.23.

**Pull request merged**
