### PR TITLE
[stable/stolon] Fix support for storageClassName

### PR DESCRIPTION
**Pull request by luxflux**
**What this PR does / why we need it**:
It fixes the support for specifying the `storageClassName` for the `stable/stolon` chart.

**Which issue this PR fixes**
The specified `persistence.storageClassName` for the `stable/stolon` is ignored.

### CODE REVIEW

**Comment by luxflux** [comment]
Dear @k8s-ci-robot, I signed the CLA now.

**Comment by luxflux** [comment]
/assign @sameersbn 

The bot suggest you to have a look at it... So I'm assigning this to you, sorry for any inconveniences.

**Comment by luxflux** [comment]
@rtluckie maybe you want to have a look at this as well?

**Comment by rtluckie** [comment]
@luxflux  good catch!  lgtm

**Pull request merged**
