### PR TITLE
[stable/etcd-operator] Support hostNetwork parameter on deployments

### PR DESCRIPTION
**Pull request by ni-slamberti**
#### Is this a new chart
No, it's not.
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Gives the opportunity to run the deployments with `hostNetwork: true` set via helm values.
This is not enabled by default, but can be useful when using the operator to backup/restore existing etcd clusters running directly on the node.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
It's used on our on-prem kubernetes cluster to backup and restore etcd using cloud storage.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by alejandroEsc** [comment]
@ni-slamberti I apologize for taking so long, will get in contact with you soon.

**Comment by ni-slamberti** [comment]
Hey @alejandroEsc, any feedback on this?

**Comment by ni-slamberti** [comment]
hey @alejandroEsc @lachie83 is there anything I can improve to have this merged?

**Comment by ni-slamberti** [comment]
@alejandroEsc @lachie83 let me know when you have time to have a look at this.

**Pull request closed without merging**
