### PR TITLE
[stable/grafana] grafana secret mount permissions

### PR DESCRIPTION
**Pull request by ghost**
add "defaultMode" variable for Grafana secret mounts

Signed-off-by: Daniel Han <danielhan@helloiamelliot.com>

The necessity of being able to configure `defaultMode` for secrets comes from using Postgres, with verification, as the backing store of Grafana.  The maximum permissions the client TLS key can have is 0600/384 (o+rw).  `defaultMode` defaults to 0644/420, preventing the client from being able to establish a connection with the database. 

@zanhsieh @rtluckie 

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by danielhan** [comment]
@davidkarlsen Thanks for the looksee!  I needed to rebase and increment the version once more, so the `lgtm` was been removed

**Review by davidkarlsen — APPROVED** [review]

**Pull request merged**
