### PR TITLE
[stable/cluster-overprovisioner] Adds imagePullSecrets to deployment

### PR DESCRIPTION
**Pull request by marcostvz**
#### What this PR does / why we need it:
Adds imagePullSecrets to deployment, allowing to pull the image from a private registry

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by max-rocket-internet — APPROVED** [review]

**Comment by max-rocket-internet** [comment]
@marcostvz I'm curious though, why is this required? It's a public image. Do you really have your own custom docker image to run `pause`?

**Comment by marcostvz** [comment]
Hi @max-rocket-internet, some of our customers work in closed environments, so we replicate all the used images :)

**Comment by marcostvz** [comment]
thanks a lot for the quick review!

**Pull request merged**
