### PR TITLE
[stable/gocd] add host in template ingress.yaml instead of using default backend

### LINKED ISSUE #10750: [stable/gocd] GoCD Ingress default template
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST  

**Version of Helm and Kubernetes**:

helm v2.12.1
kubernetes v1.12.4

**Which chart**:

stable/gocd

**Anything else we need to know**:

In file "gocd/templates/ingress.yaml":
I would like to change `spec`
from

```
  backend:
    serviceName: {{ template "gocd.fullname" . }}-server
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}

```
to

```
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "gocd.fullname" . }}-server
            servicePort: {{ .Values.server.service.httpPort }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
```

Because when I use the default ingress config I can not access gocd by the hostname that I defined in `values.yaml`.   
I deploy  gocd behind traefik.
Here is the error log: `"level":"warning","msg":"Error in ingress: HTTP is nil"`

@varshavaradarajan Could you check this? Thanks.

### PR DESCRIPTION
**Pull request by colachg**
Signed-off-by: Cola Chen <colachg@gmail.com>

#### What this PR does / why we need it:
add host in the ingress template.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #10750

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by colachg** [comment]
@GaneshSPatil Could you do me a favor to check it? :)

**Comment by arvindsv** [comment]
/cc @sheroy might be able to take a look too.

From what I can see from https://github.com/helm/charts/issues/10750, it looks like the idea is to setup some [ingress host names](https://github.com/helm/charts/blob/d990d2d1ad44361eb69381ef6ba24e694cdfeb58/stable/gocd/values.yaml#L118), change the hosts file to include those names and make sure that the server is accessible through the hostname, when deployed on GKE.

Does anything else need to be checked?

**Comment by varshavaradarajan** [comment]
@arvindsv, @sheroy  - yes, what you said checks for if the change made works on GKE. 

Another thing to check is: when traefik is used as an ingress controller for GoCD (by setting ingress.class to traefik in values.yaml), requests are handled by traefik and not the default ingress controller for gke.

**Comment by sheroy** [comment]
I tried this today. 

1. On installing the chart with no changes, I got the following error:
Error: release test failed: Ingress.extensions "test-gocd-server" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified

2. I then added a host in values.yaml and mapped it in my hosts file and the installation went through. 
I could get to the GoCD server using the hostname mapped in my hostfile. I couldn't get to it using the ingress IP. 

3. I then set the annotation "kubernetes.io/ingress.class: traefik". With just setting this annotation, the ingress didn't seem to come up. I'm not sure if I needed to do more.  

cc: @varshavaradarajan @colachg @arvindsv @GaneshSPatil

**Comment by varshavaradarajan** [comment]
@sheroy -

For 3, you need to install `traefik` as an ingress controller by doing `helm install stable/traefik -n kube-system`. Make sure that you also do - 

```
kubectl create clusterrolebinding kube-system-sa \
--clusterrole=cluster-admin \
--serviceaccount=kube-system:default
```

**Comment by colachg** [comment]
@sheroy  

Thanks for your time:)

For 1, I think I should add default host in values.yaml or add `if...else...` in ingress.yaml. 

For 2, Look at the kubernetes official explain:
>Ingress can provide load balancing, SSL termination and **name-based** virtual hosting. 

I don't know whether you can access it with ingress IP using the default nginx controller.Maybe the nginx controller does something.

**Comment by varshavaradarajan** [comment]
@colachg - I am not sure about providing `test.go.cd` as the default ingress host. It seems like trying to fix `ingress.yaml` with no specific reason for having hosts in `values.yaml`. Besides, if people use this ingress with test.go.cd and tried to obtain certificates for test.go.cd (traefik + let's encrypt), there will be problems. Can't both the default backend and your fix be provided? On traefik, the default global backend will be unhealthy and won't be able to route requests, but the host specific backend can take care of the request.  The default backend can be used with other ingress controllers? I haven't tried this out as your fix worked fine on minikube and did not throw any errors when I did `helm install`. So, not sure if it will work.

cc: @sheroy , @arvindsv , @GaneshSPatil

**Comment by arvindsv** [comment]
Let's set some acceptance criteria (oh, how I hate those words) for this:

1. A simple `helm install` should continue to work, as it does today. With IP, etc. Without needing to install or do anything. Implies good defaults in values.yaml.

2. It should be possible to configure the chart, using values.yaml, to change the ingress controller / config, to allow it to be accessible using host names.

@varshavaradarajan Is that reasonable?

If so, that needs to happen.

**Comment by varshavaradarajan** [comment]
@colachg - then either works:  

1. Have `if-else`. If hosts exist, create host specific backends, else create the default backend.
2. Have both default and host specific backend as suggested in https://github.com/helm/charts/pull/10795#issuecomment-457287763

**Comment by colachg** [comment]
@varshavaradarajan 
OK, please review again thanks:)

**Review by varshavaradarajan — COMMENTED** [review]
@colachg - please update the changelog. 
@sheroy - can you please check if the change now works with GCE?

**Comment by arvindsv** [comment]
@colachg Let's do this. If you think the change mentioned in https://github.com/helm/charts/pull/10795#issuecomment-457779917 is valid, please make that change and I'll merge it in, before any other conflicts happen. :)

Since you've tried it with Traefik, I think it's fine. If anything needs changing, we can do it later. Thank you!

**Pull request closed without merging**
