### PR TITLE
[stable/prometheus] does not support semver compatible chart versioning.

### PR DESCRIPTION
**Pull request by ekesken**
Signed-off-by: Erhan Kesken <erhankesken@gmail.com>

#### What this PR does / why we need it:
We want to use build versions to track our private changes over upstream charts, with a convention like that:

```
<ORIGINAL_VERSION>+<TEAM_NAME>.<TEAM_VERSION>
ex: v0.7.0+cre.01
```

Which is compatible with [semver](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) rules, but this kind of versioning ends up with following error for prometheus chart:

```
Error: release prometheus failed: ConfigMap "prometheus-cre-server" is invalid: metadata.labels: Invalid value: "chart:prometheus-9.1.0_cre.01heritage": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

We should respect semver, and allow usage of build numbers in chart version, for that it's enough to replace `+` with `_` before using in label fields, with a template function.

#### Special notes for your reviewer:

We considered just using `-` instead of `+`, because semver `+` means build number, `-` means prebuild. And prebuilds are ignored by `helm upgrade/install` commands
if you're using a Helm repo over HTTP and do not pass chart version explicitly.

See [github.com/Masterminds/semver/constraints.go#L212-L217](https://github.com/Masterminds/semver/blob/3c560837130448941620d7694991d3ec440aefc0/constraints.go#L212-L217)

```
Issue #21: Per the SemVer spec (section 9) a pre-release is unstable and might not satisfy the intended compatibility.
The change here ignores pre-releases on constraint checks (e.g., ~ or ^) when a pre-release is not part of the constraint.
For example, ^1.2.3 will ignore pre-releases while ^1.2.3-alpha will include them.
```

So semver library used by Helm is skipping pre releases on purpose. If you use `v0.7.0-cre.01` as, then you'll get an error
like this `Error: chart "cert-manager" not found in http://127.0.0.1:8879 repository`.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by ekesken** [comment]
@zanhsieh @gianrubio can we move the PR forward?

**Comment by zanhsieh** [comment]
@ekesken 
Would you rebase and bump the chart version to latest again please? Thank you.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
