### PR TITLE
[stable/fluentd-elasticsearch] Add PodSecurityPolicy support

### PR DESCRIPTION
**Pull request by spiarh**
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>

#### What this PR does / why we need it:
Allow one to enable pod security policy when deploying fluentd.

The PSP allows the privilege escalation and specify the hostPath allowed.

This is a redo of #8504 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Regarding extraVolumeMounts, I assume this is only for secret or configMap, am I right ?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lcavajani** [comment]
/assign @cpanato @monotek 

Can you have a look ?

**Comment by monotek** [comment]
@lcavajani 
Please resolve merge conflict.

**Pull request merged**
