### PR TITLE
[stable/datadog] Update README

### PR DESCRIPTION
**Pull request by tangentspace**
**What this PR does / why we need it**: Updates the README to fix some incorrect chart parameters and add a description of the datadog.tags parameter.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@tangentspace Chart version needs a bump.

**Comment by tangentspace** [comment]
Ok, I bumped the version

**Comment by tangentspace** [comment]
I signed off all my commits and bumped the version again.

**Pull request merged**
