### PR TITLE
modify helpers to apply popular rule to decide fullname

### PR DESCRIPTION
**Pull request by at-k**
**What this PR does / why we need it**:

This pr intends to improve rule to decide full name.  See following example (Watch "NAME" column)

* current
```
> helm upgrade --install kube-state-metrics stable/kube-state-metrics
> helm list
NAME                    REVISION        UPDATED                         STATUS          CHART                           NAMESPACE
kube-state-metrics      1               Fri Jun 15 15:52:19 2018        DEPLOYED        kube-state-metrics-0.7.1        default

> kubectl get po
NAME                                                    READY     STATUS    RESTARTS   AGE
kube-state-metrics-kube-state-metrics-cf895cc4d-hwsbt   0/1       Running   0          6s

❯ kubectl get svc
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kube-state-metrics-kube-state-metrics   ClusterIP   10.103.129.232   <none>        8080/TCP         9s
```
* after this PR
```
> helm upgrade --install kube-state-metrics ./stable/kube-state-metrics
> helm list
NAME                    REVISION        UPDATED                         STATUS          CHART                           NAMESPACE
kube-state-metrics      1               Fri Jun 15 15:35:05 2018        DEPLOYED        kube-state-metrics-0.7.1        default

❯ kubectl get po
NAME                                 READY     STATUS    RESTARTS   AGE
kube-state-metrics-cf895cc4d-f77vk   1/1       Running   0          14s

❯ kubectl get svc
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kube-state-metrics   ClusterIP   10.109.237.24   <none>        8080/TCP         25s
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

none

**Special notes for your reviewer**:

This style is quite popular. As long as we searched in this repository, over 80 charts adopt this style.

### CODE REVIEW

**Comment by mumoshu** [comment]
@at-k Good catch! LGTM overall. The chart lint is failing for two reasons:

> Checking chart 'stable/kube-state-metrics' for a version bump...
Chart version on k8s/master : 0.7.1
New chart version:  0.7.1
ERROR: Chart version not ok. Needs a version bump.

You need to bump the version number of Chart.yaml to perhaps `0.7.2`

> Verifying maintainer 'Jose Armesto'...
ERROR: 'Jose Armesto' is not a valid GitHub account. Please use a valid Github account to help us communicate with maintainers in PRs/issues.
ERROR: Chart validation failed.

Sounds like we have to use the github username [fiunchinho](https://github.com/kubernetes/charts/commits?author=fiunchinho) in Chart.yaml.

**Comment by at-k** [comment]
CLA done

**Pull request merged**
