### PR TITLE
[stable/wordpress] Use only one PVC to prevent zone conflicts

### PR DESCRIPTION
**Pull request by bcorijn**
In high-availability cloud environments such as AWS or GCE, it is a perfectly plausible scenario to have kubernetes create the apache and wordpress PV's in different zones. This makes the wordpress pod impossible to schedule as it will look for a machine that is in both zones, which cannot exist.
Migrating to only one PV which contains both folders solves this issue.

### CODE REVIEW

**Comment by mgoodness** [comment]
I created #546 to discuss our general approach to multiple PVCs. In this case both PVCs are mounted into a single pod, so combining them seems reasonable.

**Comment by mgoodness** [comment]
@k8s-bot ok to test

**Comment by mgoodness** [comment]
@bcorijn I inadvertently removed your authorship while resolving merge conflicts. Please feel free to rebase and amend so you get full credit for your work. Sorry!

**Comment by mgoodness** [comment]
Maintainers: LGTM applied, but let's give @bcorijn a chance to fix my screwup before we merge.

**Comment by prydonius** [comment]
Thanks @bcorijn and @mgoodness! I am wondering if it's better to use the subPath option to use the same PVC for different mount points? cc @sameersbn

**Comment by bcorijn** [comment]
Was on holidays for a few days, but I'll rebase and amend today.

@prydonius I considered that, but decided not to as I thought it was some unneccesary complexity in the end. Open to reconsider though. 
Another reason was the base image at https://github.com/bitnami/bitnami-docker-wordpress, actually uses 4 volumes to ensure persistence, so persisting the parent folder would provide a better coverage than what is currently in place (and doing this with subpaths would need 4 of them). Following volumes are suggested by Bitnami:
```
- mariadb_data:/bitnami/mariadb
- wordpress_data:/bitnami/wordpress
- apache_data:/bitnami/apache
- php_data:/bitnami/php
```

**Pull request merged**
