### PR TITLE
[stable/grafana] Fix a typo in the Grafana chart notes

### PR DESCRIPTION
**Pull request by emedvedev**
#### What this PR does / why we need it:

Fixes a small typo in the notes :) "grafanfa" -> "grafana"

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@emedvedev 
Could you bump the chart version to latest please? Thank you.
/assign

**Comment by emedvedev** [comment]
@zanhsieh done :)

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
