### PR TITLE
Kube 1.16 removed deprecated api

### PR DESCRIPTION
**Pull request by Anishmourya**
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Aisuko** [comment]
Please make the signoff first. And bump the chart version.

**Comment by Aisuko** [comment]
@Anishmourya  Thanks please make a signoff  first.

**Comment by Anishmourya** [comment]
@Aisuko  can you merge this pr please ?

**Comment by Aisuko** [comment]
> @Aisuko can you merge this pr please ?

Sure, I'm sorry for replying so late and  thanks for your patient work

**Review by Aisuko — APPROVED** [review]
/LGTM

**Pull request merged**
