### PR TITLE
[stable/rabbitmq-ha] Ease the addition/removal of plugins

### PR DESCRIPTION
**Pull request by francois-travais**
#### What this PR does / why we need it:

This PR adds a new variable, `extraPlugins` to easily add or remove plugins. The default value enables [shovel](https://www.rabbitmq.com/shovel.html) and [federation](https://www.rabbitmq.com/federation.html) plugins which are not essentials for RabbitMQ to work. But since these plugins are enabled by default, we keep the backward compatibility.

This method is much easier than creating a configMap from scratch.

#### Which issue this PR fixes
None

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by francois-travais** [comment]
@steven-sheehy Version bumped. You can assign it to someone now. I can bump the version again later if necessary.

**Comment by steven-sheehy** [comment]
Thanks @francois-travais, looks good to me
/assign @davidkarlsen

**Comment by francois-travais** [comment]
@steven-sheehy I rebase and bumped the version

**Pull request merged**
