### PR TITLE
[stable/grafana] Add service.nodePort to README

### PR DESCRIPTION
**Pull request by mfvitale**
#### Which issue this PR fixes
* Add missing configuration property to README

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by mfvitale** [comment]
@zanhsieh @maorfr I don't think that version bumping is required here.

**Comment by zanhsieh** [comment]
@mfvitale 
let's give it a try. If failed plz version bump.
/approve
/lgtm

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@mfvitale 
e2e test failed. Please do version bump. Thank you.

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@mfvitale 
Sorry again. Could you mind to resolve file is conflict please? 
stable/grafana/Chart.yaml

**Comment by mfvitale** [comment]
> @mfvitale
> Sorry again. Could you mind to resolve file is conflict please?
> stable/grafana/Chart.yaml

Done! Why bumping to 3.11.1 not worked? I now bumped to 3.12.0

**Pull request merged**
