### PR TITLE
Kafka release name check

### PR DESCRIPTION
**Pull request by timm088**
What this PR does / why we need it:

When releasing these charts, service name will be prefixed with the release name, resulting in name-name. This also impacts DNS resolutions.

Special notes for your reviewer:

From my research, looks like the default chart template was changed (i.e., when running helm create locally), this function was just not added here

### CODE REVIEW

**Comment by unguiculus** [comment]
Why not update to the latest `_helpers.tpl` you get with `helm create` using Helm 2.8+?

**Comment by timm088** [comment]
Valid feedback, was only trying to ensure did not change the behaviour too much of what users may be familiar with (as the older _helpers had much less functionality)

I'll update to latest

**Comment by timm088** [comment]
@unguiculus Have implemented the change as you suggest, thank for picking that up.

**Comment by timm088** [comment]
By upgrading the helm `_helpers.tpl` to the latest, this has introduced a failure in the tests

The reason the test failed is because kubernetes sets a deprecated envvar for the service by default, that Kafka makes use of at startup see https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/configure#L61

There are a few options to deal with this:

1. we change the default name to `kafka-cluster` in Chart.yml
2. the test needs to change to install this chart with a release name e.g., --name kafka-cluster (and we should probably note in NOTES.txt to never name your release `kafka`
3. we have to live with the fact this chart will always deploy append `-kafka` to any name you give the release

**Options 1** is the simplest fix, but introduces a breaking change for anyone using this chart (it is still in the incubator track however)

@benjigoldberg thoughts on the options?
Primarily i was looking to fix the "kafka-kafka" issue, but it would appear have entered a bit of a hole

**Comment by timm088** [comment]
Actually, the solution presented here in an open issue on the confluent repo is quite simple https://github.com/confluentinc/cp-docker-images/issues/388. 

Have added an additional commit for this

**Comment by timm088** [comment]
@benjigoldberg anything further or LGTM?

**Comment by benjigoldberg** [comment]
Thanks for the contribution @timm088!

/lgtm

**Comment by benjigoldberg** [comment]
@timm088 needs another version bump

**Comment by timm088** [comment]
👍 bumped the version 
Looks like some of the CI is failing due to the associated account? (ERROR: 'Faraaz Khan' is not a valid GitHub account.?)

**Comment by timm088** [comment]
@benjigoldberg Bumped the chart version, thanks.
(Looks like something in CI is broken`ERROR: 'Faraaz Khan' is not a valid GitHub account.`)

**Comment by benjigoldberg** [comment]
ok @timm088 it took me a bit to figure this out, but its referring to @faraazkhan's email address in this file: https://github.com/kubernetes/charts/blob/master/incubator/kafka/Chart.yaml#L18

I think we need to figure out what his email address is now? Maybe he changed jobs? I've never seen this error before, but its definitely not on you.

@unguiculus are you familiar with this one?

**Comment by timm088** [comment]
Thanks @benjigoldberg ! Happy to help out with maintaining if need be, use this chart a fair bit

**Comment by faraazkhan** [comment]
The email seems correct and is the primary email for this github account. I’ve never seen the error message before, but it seems that its expecting the github username rather than the person’s name? In which case mine would be ‘faraazkhan’

**Comment by timm088** [comment]
So @faraazkhan ... I would change the github username then in the Chart.yml file?

**Comment by faraazkhan** [comment]
Yes, I believe we need to do that for each of the maintainers listed in there.

**Comment by timm088** [comment]
@faraazkhan @benjigoldberg have changed the maintainers to use github usernames and the pipeline is now working again (quite odd)

**Pull request merged**
