### PR TITLE
[stable/redis] Allow templates in user-provided configmap values

### LINKED ISSUE #16335: [stable/redis] allow templates in the user supplied conf
**Describe the solution you'd like**

To be able to specify helm template strings in the user conf values. So have the configmap use the `tpl` function to render the conf settings that the users have passed in values.

**Additional context**

In the GitLab chart, we would like to set the values in our parent chart, to some sane defaults, but we would also like to be able to have users edit the `save` settings without overwriting our defaults. By rendering the settings using tpl, we can have our setting read in some additional user provided config.

### PR DESCRIPTION
**Pull request by twk3**
Render configmap, master.configmap, slave.configmap, and
sentinel.configmap using the tpl function.

#### What this PR does / why we need it:

This allows us to do things like set the dbfilename to the release name
And is useful for charts that use redis as a subchart and want to
provide additional redis settings for users to tune.

#### Which issue this PR fixes

  - fixes #16335

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Thanks so much for the PR!! 

Could you update the **README.md** adding to each of modified parameters' description the sentence below?

```
(this value is evaluated as a template) 
```

**Comment by twk3** [comment]
> Thanks so much for the PR!!
> 
> Could you update the **README.md** adding to each of modified parameters' description the sentence below?
> 
> ```
> (this value is evaluated as a template) 
> ```

@juan131 I've now updated the readme

**Review by juan131 — APPROVED** [review]
Thanks for addressing the suggestion!

**Pull request merged**
