### PR TITLE
[stable/nginx-ingress] Remove old version support and enable support for 0.10

### PR DESCRIPTION
**Pull request by sirrapa**
… 0.10

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by prydonius** [comment]
Thanks @sirrapa! Please fix the CI error (version bump needed):

```
Checking the Chart version has increased for the chart at stable/nginx-ingress
Error please increment the new chart version to be greater than the existing version of 0.8.26
```

/ok-to-test

**Comment by dtzar** [comment]
The existing PR https://github.com/kubernetes/charts/pull/3369 is a more robust solution to handle backwards compatibility to solve this problem.

**Comment by aparris30** [comment]
Ok, the semver solution ([#3369](https://github.com/kubernetes/charts/pull/3369)) is indeed more robust.
Closing this PR...

**Pull request closed without merging**
