### PR TITLE
[stable/graylog] provisioner job hook

### PR DESCRIPTION
**Pull request by vlinevych**
Signed-off-by: Volodymyr Linevych <linevych.v@gmail.com>

#### What this PR does / why we need it:
This PR optionally installs the annotation that triggers the graylog provisioner job on chart release upgrades.

Triggering the provisioner job after release upgrade might be useful, depending on a logic of your provisioner script.
In my case, I install content packs and propagate saved searches. 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by KongZ** [comment]
@vlinevych Should we change to `.Values.graylog.provisioner.annotations`? Then we can freely add more annotations without modifying chart in the future. And please update the `README.md` as well when you add another field on values file.

**Comment by vlinevych** [comment]
@KongZ Thank you for the suggestion. Implemented.

**Pull request merged**
