### PR TITLE
stable/chartmuseum fix: missing labels in secret object

### PR DESCRIPTION
**Pull request by sermilrod**
#### What this PR does / why we need it:
This PR adds missing extra labels to secret object

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jdolitsky** [comment]
@sermilrod sorry to have missed this- do you mind rebasing and fixing version?

**Comment by sermilrod** [comment]
> @sermilrod sorry to have missed this- do you mind rebasing and fixing version?

Yeah sure, no problem

**Comment by sermilrod** [comment]
@jdolitsky done 👍  Can you please check it again?

**Pull request merged**
