### PR TITLE
[stable/zetcd] add repo archive notice and deprecate chart

### PR DESCRIPTION
**Pull request by scottrigby**
See #24030

### CODE REVIEW

**Review by unguiculus — APPROVED** [review]
/lgtm

**Review by unguiculus — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by mattfarina** [comment]
Manually merging as this is a required action and the chart is outdated with resources no longer available in Kubernetes. That is why the tests fail.

**Pull request merged**
