### PR TITLE
[stable/velero] DEPRECATE - Velero

### LINKED ISSUE #6: Deprecate the helm/charts Velero chart
From @cpanato:
> Deprecate the stable/velero chart in helm/charts. See https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
moving Velero Chart to https://github.com/vmware-tanzu/helm-charts

#### Which issue this PR fixes
  - fixes https://github.com/vmware-tanzu/helm-charts/issues/6

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by cpanato** [comment]
cc @carlisia

**Review by carlisia — CHANGES_REQUESTED** [review]
Looks great, just missing adding the deprecation notice to the `NOTES.txt` file.

**Comment by cpanato** [comment]
@carlisia done

**Comment by carlisia** [comment]
@nrb PTAL.

**Pull request merged**
