### PR TITLE
[stable/prometheus-operator] Major sync of rules, alerts and dashboards from upstream (3rd try)

### LINKED ISSUE #18311: [stable/prometheus-operator] prometheus rules not properly synced with kube-prometheus
**Describe the bug**
The prometheus rules have not been synced properly with kube prometheus repository.

For exemple in current rules, the following record doesn't exists:
node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate

but this one is used in the grafana dashboards.

The more, after manually synced with the provided script, the metric appears in the dashboard.

**Version of Helm and Kubernetes**:
Kubernetes: 1.14
Helm: 2.14

**Which chart**:
Prometheus operator: 6.21.0

### PR DESCRIPTION
**Pull request by den-is**
#### What this PR does / why we need it:
- First of all this PR has synced all rules, alerts and dashboards definitions from the upstream
- Updated sync scripts in the hack directory

#### Which issue this PR fixes
- fixes https://github.com/helm/charts/issues/18311

#### Special notes for your reviewer:
- ~~Disabled alert https://github.com/helm/charts/commit/c45b27385cd621e12881fda21506253b4a85a76a~~ Fixed by https://github.com/helm/charts/pull/18375/commits/17340c217d30ebc47adbabe8c64bd674c905bb81
_Known Golang "issue" https://github.com/golang/go/issues/18221 https://github.com/golang/go/issues/24475_

-  By default, Upstream has "wrong" datasource selected in network-utilisations and resources dashboards;  "prometheus" instead of "Prometheus", and not using variable. I've pushed fix only for this chart, not upstream.
```
Kubernetes / Networking / Cluster
Kubernetes / Networking / Namespace (Pods) 
Kubernetes / Networking / Namespace (Workload) 
Kubernetes / Networking / Pod 
Kubernetes / Networking / Workload 
```
- Also now you have to install grafana plugin for this Networking dashboards to display correctly
```
  plugins:
  - grafana-piechart-panel
```

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by vsliouniaev — APPROVED** [review]

**Comment by den-is** [comment]
I signed it

**Comment by rverma-nikiai** [comment]
looks like helm-bot didn't add Contribution Allowed label. Can we merge this PR?

**Comment by asychev** [comment]
Please, move this forward!

**Comment by vsliouniaev** [comment]
Blocked due to this repo's CI issues https://github.com/helm/charts/issues/18584

**Comment by nmaupu** [comment]
> Please, move this forward!

Pretty please 🙏 
This has already been accepted and reviewed.
Maybe @gianrubio or @bismarck can do something about it ?

**Comment by den-is** [comment]
Guys there are problems with helm/chart CI/CD process, system is not setting proper label. It's not our fault, we eagerly wait for this merge too.
We are not only chart/PR experiencing that problem.

**Comment by wu0407** [comment]
The    "Kubernetes / Networking / Namespace (Pods) "  warnning  Panel plugin not found: grafana-piechart-panel

**Comment by den-is** [comment]
@wu0407 read PR notes carefully
it it noted in there that you require plugin for correct display

**Comment by vsliouniaev** [comment]
@den-is I think it would be a good idea to install the plugin by default if the relevant dashboards are enabled or at least add this information to the docs.

In situations where the Grafana install is done without access to the internet this is definitely going to cause issues

**Comment by den-is** [comment]
@vsliouniaev and even chiefs of the upstream project are concerned about exactly same issue, but no progress for now. https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/290#issuecomment-549034760

Everything can be done and contributed. I could try on weekends if I have had enough time, if someone won't be faster.
It is possible to install plugin by default.
Of course not most pleasant solution - coz breaks "purity", but this chart already has many other biased points.
I don't care much about offline setups coz probably they are very rare case - but of course it is an issue which exists.

So probably installation will require on/off flags for that dashboards too.

**Pull request merged**
