### PR TITLE
[stable/magic-ip-address] static IP addresses for node-local services

### PR DESCRIPTION
**Pull request by mumoshu**
This chart is manually verified to work with the steps described in the README.

### CODE REVIEW

**Comment by mumoshu** [comment]
@linki Hey. Thanks for maintaining the charts! Would you mind reviewing this?

**Comment by mumoshu** [comment]
Could anyone review this?

**Comment by viglesiasce** [comment]
/lgtm

Apologies that we let this one get stale @mumoshu.

**Comment by mumoshu** [comment]
@viglesiasce Thanks for reviewing!

I've added the sign-off line to the commit message to make dco-labeler happy.

**Comment by mumoshu** [comment]
@viglesiasce And the LGTM status seems to have been reset. Could you approve it once again?

**Pull request merged**
