### PR TITLE
[stable/chart] sentinel on master cannot start

### PR DESCRIPTION
**Pull request by anasinnyk**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes sentinel for master without password

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by anasinnyk** [comment]
I hope test no running third time

**Comment by anasinnyk** [comment]
@caarlos0 can you stop it ))) 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/15951/pull-charts-e2e/1156130580920799232/
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/15951/pull-charts-e2e/1156121644620582912/

**Comment by caarlos0** [comment]
don't know why I'm mentioned here.

btw pr title is not according to rules, should have been `[stable/redis]` it seems.

**Pull request merged**
