### PR TITLE
small note about kafkaVersion parameter. Change default version

### PR DESCRIPTION
**Pull request by adeptg**
Signed-off-by: Yury Vidineev <adeptg@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by Aisuko — CHANGES_REQUESTED** [review]
Thanks for your PR, please bump the version.

**Comment by ssalaues** [comment]
@adeptg Yeah this just needs a version bump before it can be merged.

**Comment by adeptg** [comment]
Hi guys! Sorry I didn't think that a version bump is necessary when only comments are changed. Sorry and thanks for your patience!

**Comment by Aisuko** [comment]
cc @giacomoguiulfo Hello Sir, please help us review this, thanks

**Comment by ssalaues** [comment]
@Aisuko I just tested out the changes on my cluster and works as expected.

**Pull request merged**
