### PR TITLE
[stable/prometheus] Organized Templates Directory. Add ".gitignore".

### PR DESCRIPTION
**Pull request by Xtigyro**
#### Is this a new chart

No.

#### What this PR does / why we need it:

- Organizes the `templates/` directory into a clearer structure.
- Adds `.gitignore`. Adds `requirements.lock` to `.gitignore`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Xtigyro 

Thank you for the contribution.

Couple things:
- How do you ensure the backward compatibility
- Naming rule is still wordy. For example, prometheus/templates/alertmanager-configmap.yaml → .prometheus/configmaps/alertmanager-configmap.yaml, why moving into its functional directory (configmaps) but still keep suffix (-configmap) ?

**Comment by Xtigyro** [comment]
@zanhsieh 
>     * Naming rule is still wordy. For example, prometheus/templates/alertmanager-configmap.yaml → .prometheus/configmaps/alertmanager-configmap.yaml, why moving into its functional directory (configmaps) but still keep suffix (-configmap) ?

My initial idea was only to create a clearer dir structure but this is even better - thanks! Done.

>     * How do you ensure the backward compatibility

Aren't just the source filenames changing (which are put as first-line comments in the rendered resources) - which does not result to any actual changes of the deployment?

**Comment by zanhsieh** [comment]
@Xtigyro 
Let's give it a try.

/ok-to-test

**Review by zanhsieh — APPROVED** [review]

**Comment by Xtigyro** [comment]
@zanhsieh It appears it times out without a good reason - probably that's an internal infra temp issue?

**Comment by Xtigyro** [comment]
@zanhsieh Yeah - it should have been a temp infra issue. Re-run it today - OK.

**Comment by Xtigyro** [comment]
@zanhsieh I'll merge `master` and bump again the chart version - it seems another PR has gone in, in the meantime.

**Comment by Xtigyro** [comment]
@zanhsieh @gianrubio Done.

**Pull request merged**
