### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by charneykaye**
Take changes from the most accepted answer in the linked stackoverflow question, https://askubuntu.com/questions/1032476/ubuntu-18-04-no-dns-resolution-when-connected-to-openvpn

### CODE REVIEW

**Comment by jasongwartz** [comment]
/ok-to-test
/lgtm
/approve

Thanks for the contribution!

**Comment by jasongwartz** [comment]
@charneykaye can you please modify the commit to add the DCO signature?

**Comment by charneykaye** [comment]
@jasongwartz thanks!

**Comment by charneykaye** [comment]
@jasongwartz I've added the DCO and attempted to retest, however CI is throwing an error:

```
Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ openvpn => (version: "4.2.1", path: "stable/openvpn") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
```

Please help me understand this error, I lack the context.

**Comment by jasongwartz** [comment]
Ah yep - sorry, I forgot. Every change (even readme changes) needs a version bump. Just go into the Chart.yaml for this directory and increase the version (so bump here to 4.2.2: https://github.com/helm/charts/blob/master/stable/openvpn/Chart.yaml#L6)

**Comment by charneykaye** [comment]
@jasongwartz gotcha, thanks again! I believe this is OK now.

**Comment by jasongwartz** [comment]
/lgtm

Thanks again for the contribution!

**Pull request merged**
