### PR TITLE
README: Add persistence.existingClaim

### PR DESCRIPTION
**Pull request by jesselang**
**What this PR does / why we need it**:

Add persistence.existingClaim to configuration table in README so users are aware of it without looking through the templates.

### CODE REVIEW

**Comment by rjkernick** [comment]
Thanks for the pull request. Please sign the CLA and bump the version in Chart.yaml

**Comment by jesselang** [comment]
Bumping to check if the CLA is verified. If it doesn't work, I may need to change the email on the commit.

**Comment by rjkernick** [comment]
Thanks for signing the CLA. Please increment the version in Chart.yaml.

**Pull request closed without merging**
