### PR TITLE
[Incubator/kafka] Fix init container fail when pod restart

### PR DESCRIPTION
**Pull request by nhamlh**
**What this PR does / why we need it**: Fix init container fail when pod restart
If a pod being restarted after sometime, init container will be triggered to run. Init container will try to apply a label to the running pod using command kubectl label, which will fail because the label is already existed. This PR add option --overwrite to kubectl label command to overcome this issue.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@nhamlh thanks for the PR! This looks good, I'm just waiting for the linter/tests to pass before I move this PR along.

**Comment by nhamlh** [comment]
@benjigoldberg just a kind reminder if this PR could be merged :)

**Comment by josdotso** [comment]
Cool PR!  Thanks @nhamlh

**Comment by benjigoldberg** [comment]
@nhamlh if you bump the patch version I would be happy to merge this!

**Comment by nhamlh** [comment]
@benjigoldberg I have updated the chart version :D

**Pull request merged**
