### PR TITLE
[WIP] Add Chart for creating TPR for cert manager certificates

### PR DESCRIPTION
**Pull request by rendhalver**
This is for creating Third Party Resources for Cert manager Certificates
I am not sure how we can get these tested to I am marking this as WIP for now.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Review by jar361 — APPROVED** [review]

**Comment by unguiculus** [comment]
I'm not sure it make sense to have a chart for cert-manager certificates here as long as we don't have a chart for cert-manager itself.

A chart for cert-manager is currently being developed in the cert-manager repo. I have a PR open to align it to our best practices. The intention is to move the chart over to the charts repo once it is ready.

See https://github.com/kubernetes/helm/pull/3337.

**Comment by rendhalver** [comment]
I noticed that PR in cert-manager last week.
I am happy for this to wait till that get's moved across.
I was just pushing it upstream so it's available if people want to use it.

**Comment by unguiculus** [comment]
To be honest, I'm not a fan of WIP PRs. I like things to be ready for review when they are pushed. Makes it easier for maintainers.

**Comment by rendhalver** [comment]
Yep I understand that.
We can close this and I can redo it when we have the cert-manager Chart in this repo if you like.

**Comment by unguiculus** [comment]
Thanks.

**Pull request closed without merging**
