### PR TITLE
Support initContainers in prometheus-operator

### PR DESCRIPTION
**Pull request by kuznero**
Add `initContainers` for , #9031.

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@kuznero have you tested these changes work? I don't see how this is possible since the API does not have support for it https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

**Comment by kuznero** [comment]
> @kuznero have you tested these changes work? I don't see how this is possible since the API does not have support for it https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

Working on it as we speak. But I don't see why it shouldn't work.

**Comment by vsliouniaev** [comment]
The `prometheus` resource that is created is used by prometheus-operator to create a `statefulset` resource. Since there's no support for using the initContainer as per the API doc this does not get passed into the statefulset.

**Comment by kuznero** [comment]
> The `prometheus` resource that is created is used by prometheus-operator to create a `statefulset` resource. Since there's no support for using the initContainer as per the API doc this does not get passed into the statefulset.

I see now. And I also see it does not work in my testing. Annoying. Do you know if that is a good idea to use `containers` in place of `initContainers` for `chown` host path stuff?

**Comment by vsliouniaev** [comment]
I'm not the best person to answer that kind of question. You could try kubernetes.slack.com or ask in coreos/prometheus-oeprator if this kind of feature is necessay and what the suggested workaround could be

**Comment by kuznero** [comment]
> I'm not the best person to answer that kind of question. You could try kubernetes.slack.com or ask in coreos/prometheus-oeprator if this kind of feature is necessay and what the suggested workaround could be

Thanks, closing for now.

**Comment by kuznero** [comment]
Linking the issue on coreos/prometheus-operator here: https://github.com/coreos/prometheus-operator/issues/1888.

**Pull request closed without merging**
