### PR TITLE
[stable/minio] Fix minio cannot create bucket

### LINKED ISSUE #5403: mino make bucket job crashloop
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
1.8.9

**Which chart**:
stable/minio

**What happened**:
Fails to install due to crashlooping make bucket job due to missing initialize script.

**What you expected to happen**:
Successful deployment with created bucket.

**How to reproduce it** (as minimally and precisely as possible):
Install chart with an autocreated bucket

**Anything else we need to know**:
This was broken in #4277 when the configmap holding the initialize script was removed.

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

Running `helm install --set "accessKey=$minioaccesskey,secretKey=$miniosecretaccesskey,defaultBucket.enabled=true,defaultBucket.name=$minio_bucket_name,defaultBucket.purge=true" ./minio`
was failing with a `can't open '/config/initialize'` error message.

The `/config/initialize` script is the entrypoint for the
`post-install-create-bucket-job`. The `initialize` script comes from the
`minio` configmap. This `configmap` was deleted in
https://github.com/kubernetes/charts/pull/4277, because it also included
the `config.json`. Mounting the `config.json` was causing issues with
`minio` because Kubernetes switched to having all `ConfigMap` mounts be
readonly.

However, there is no issue with the `/config/initialize` script being
read only, so I added back the `configmap` with just the `initialize`
data.

I verified that the above `helm install` command works does not result
in a crash loop.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5403 

**Special notes for your reviewer**: @nitisht just wanted to tag you to get your eyes on this as well, because I think you have the most context on the `ConfigMap` stuff. Please let me know if I'm missing anything :)

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks for the PR @mattjmcnaughton I was planning to get back to this, but I am glad you did. I tested it locally and works fine for me. LGTM.

**Review by nitisht — APPROVED** [review]

**Comment by mattjmcnaughton** [comment]
@sameersbn mind giving this a quick look and signing off if it looks good? thanks!

**Pull request merged**
