### PR TITLE
[stable/hlf-peer] Configure logging

### PR DESCRIPTION
**Pull request by ClementGautier**
#### What this PR does / why we need it:
This PR allows the operator to specify the log level of the Peer. HLF is kind of verbose in debug mode, filling the disk quite fast and making the reading of logs painful.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
I've changed the defaults to reflect the default values of Hyperledger 1.3: https://github.com/hyperledger/fabric/blob/release-1.3/sampleconfig/core.yaml#L37 
Regarding higher version of hyperledger tho the control of the logging is controlled by the variable `FABRIC_LOGGING_SPEC` (https://hyperledger-fabric.readthedocs.io/en/release-1.4/logging-control.html#logging-specification). I didn't added it there tho to keep the PR simple and don't bring >=1.4 specific configurations in the codebase for now.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by alexvicegrab** [comment]
@nicolapaoli, this PR should not cause any issue with previous, as it merely converts a set hardcoded values to variables, so I will approve. We can easily update the Nephos example `values.yaml` to use `debug` mode if needed.

/approve

**Comment by alexvicegrab** [comment]
@ClementGautier thanks for your contribution!

**Comment by alexvicegrab** [comment]
@ClementGautier aha, please check conflicts and resolve. Thanks!

**Comment by ClementGautier** [comment]
@alexvicegrab it should be good now ;) Thx !

**Pull request merged**
