### PR TITLE
[incubator/elasticsearch] added extraInitContainers option

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: 
* adds extraInitContainers option
* updated elasticsearch to 6.4.1

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
will be goos if you can add a test case that uses the initcontainers

**Comment by monotek** [comment]
@cpanato you're talking about an example?

**Comment by cpanato** [comment]
@monotek https://github.com/helm/charts/blob/master/test/README.md#providing-custom-test-values

**Comment by monotek** [comment]
Thanks for the hint. Its done. :-)

**Comment by cpanato** [comment]
/lgtm

thanks for adding the test case

**Comment by monotek** [comment]
Fixed merge conflict...

**Comment by monotek** [comment]
@icereval could you please review?
Thanks :-)

**Comment by cpanato** [comment]
@monotek can you rebase and fix the conflict? thanks!

**Comment by monotek** [comment]
@cpanato done :-)

**Comment by davidkarlsen** [comment]
@simonswine
@icereval
@rendhalver

can we merge this?

**Pull request merged**
