### PR TITLE
[incubator/fluentd] Promote fluentd to stable

### PR DESCRIPTION
**Pull request by rendhalver**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by paulczar — CHANGES_REQUESTED** [review]
this looks fine to me, just needs to be rebased to solve the merge conflict.

**Comment by rendhalver** [comment]
Thanks @paulczar I will get that sorted soon.

**Comment by paulczar** [comment]
Since we're promoting to stable we should version it to `1.0.0`

**Comment by rendhalver** [comment]
Closing in favour of #8477

**Pull request closed without merging**
