### PR TITLE
[stable/datadog] Remove deprecated deployment

### PR DESCRIPTION
**Pull request by coreypobrien**
The deployment was originally added to handle Kubernetes events, but with leader election and the cluster-agent as better options, there's no reason to deploy the node agent as a deployment.

This removes the deprecated option to use a Deployment for the node agent but continues using a Deployment for statsd instead of the DaemonSet to avoid aggregation bugs.

### CODE REVIEW

**Comment by coreypobrien** [comment]
@hkaj @xvello Any thoughts on this? It has languished for a while.

**Comment by coreypobrien** [comment]
This has been open for a while so I'm going to add a few other recent reviewers 🤞 

/assign @charlyf @cpanato

**Comment by xvello** [comment]
hi @coreypobrien 

The variety of deployment cases our users run made us decide to postpone removing the deployment from the chart. For example, you run dogstatsd as a deployment instead of the recommended daemonset way, while other users might find that useless. Could you please elaborate on the reason why you do it?

The upcoming cluster-checks feature might also bring a legitimate use case for the deployment, to run these cluster-checks in dedicated pods. Although we appreciate your contribution, I feel like this is a change we should not rush for now. I'd rather work on reducing the maintenance toil of the deployment spec for now.

/hold

**Comment by coreypobrien** [comment]
Hey @xvello thanks for taking a look.

As far as statsd, this doesn't change the underlying statsd behavior of the agent daemonset. If you want to use the node agent for a statsd endpoint that still works as before. One accidental use case for the deprecated `Deployment` was to use it to deploy a statsd endpoint where pods access it via a `Service`. The options for statsd are:
1. Use the node agent with `hostNetwork: true` and bind to 127.0.0.1. I don't like this option because it requires pods sending data to statsd to also use `hostNetwork: true` but this PR doesn't change that behavior and that is still possible.
2. Use the `Deployment` option in this chart which includes a `Service`. This works before this PR but you have to override a lot of stuff so you don't _also_ duplicate node agent work from a daemonset. After this PR, turning on `statsd.enabled` continues to support this use case but in a cleaner way using `datadog/dogstatsd` so you don't duplicate node agent work.

The current `Deployment` uses the node agent and was only included because back when it was added there was no leader election or cluster-agent to deduplicate collecting Kubernetes events. Here is the original PR (https://github.com/helm/charts/pull/722). It was meant to solve that specific problem (a problem that no longer exists) and it has just been maintained because it was there as far as I can tell.

As for the cluster checks, I'm excited for this feature, but I don't think it will use the `Deployment` as implemented currently (before this PR). I assume we will want to add some additional configuration options that spin up a deployment for cluster checks only if you're using them and we will need to explicitly block the agent from duplicating the effort of the daemonset as well.

Unless there is a use case for the `Deployment` that I'm missing, I'd still like to see this cruft of bygone days removed.

**Comment by coreypobrien** [comment]
@xvello Sure, but that's not really the point here is it? All that functionality is still left in here. This PR doesn't change any of that.

**Comment by xvello** [comment]
My point was to show you a third option for statsd, that is our recommended method, and does not need a separate dogstatsd deployment.

You PR breaks two pretty common deployment cases:

- dogstatsd usage on the daemonset, which is our recommended usage pattern, by removing the 8125 container port (and the host port option) from the daemonset
- APM usage on the deployment+service, which is pretty common too

Because of this, I cannot accept this contribution. We currently are working on spec-ing version 2.0 of the chart with a clear migration path. In the meantime, I think it's best to keep the status quo.

**Pull request closed without merging**
