### PR TITLE
[consul/stable] Added support for multi-cluster consul deployments.

### PR DESCRIPTION
**Pull request by oliverisaac**
**What this PR does / why we need it**: This does three things because you need both for this to work right.

1: Adds support to create the secret for a pre-defined gossip key. (gossip.create: true)
2: Adds support to add arbitrary hostnames to join as either peers or as WAN peers. This allows the deployment of multi-cluster consul deployments.
3: Adds support to define an arbitrary top-level domain to the cluster (instead of cluster.local).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by oliverisaac** [comment]
@linki @lachie83 @foxish : Is there something we're waiting on to get this merged?

**Comment by PlugIN73** [comment]
Hi! What about merging this pr?

**Comment by PlugIN73** [comment]
I've tested this pull request in my cluster - it works. Consul joined to another consul cluster.

**Comment by PlugIN73** [comment]
Hi! Any news here?

**Comment by PlugIN73** [comment]
Ping! It's still needed! :)

**Comment by NikitaNaumenko** [comment]
Me need this feature too, it's great! 👍

**Pull request closed without merging**
