### PR TITLE
[stable/traefik] Parameterize metrics port exposure

### LINKED ISSUE #4236: [stable/traefik] metrics port/endpoint should not be exposed in traefik service
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
2.7.2 & 1.8

**Which chart**:
traefik

**What happened**:
When `metrics.prometheus.enabled` this chart add access to metrics endpoint and port in main service, so it get exposed to internet.
The metrics endpoint should only be exposed in dashboard service, so it can be protected.

**What you expected to happen**:
Not to expose metrics to internet

**How to reproduce it** (as minimally and precisely as possible):
A vanilla install with prometheus metrics enbaled

**Anything else we need to know**:

### LINKED ISSUE #4473: [stable/traefik] Do not expose metrics on service type loadbalancer
**Is this a request for help?**:

NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes Client v1.9.5
Kubernetes Server v1.9.4-gke.1

**Which chart**:
stable/traefik:1.25.2

**What happened**:
Activating prometheus metrics (or other metrics) adds another `ports` section to the service of type LoadBalancer. See here: https://github.com/kubernetes/charts/blob/86e1f83ab1b0824d64cc52242422572a362facca/stable/traefik/templates/service.yaml#L50-L54
In a cloud environment this leads to the creation of another public port (8080) on the load balancer provided by e.g. GCP, so that the whole world can access the metrics publicly.

**What you expected to happen**:
Metrics should not be publicly accessible - I want to access them either directly from inside the cluster or via their own dashboard ingress so that the ingress can be authorized with basic auth or client certificate.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart with the following values file:

```
rbac:
  enabled: true

loadBalancerIP: 'so.me.ip.here'

dashboard:
  enabled: true
  domain: dummy.domain
  ingress:
    annotations:
      kubernetes.io/ingress.class: "traefik"

metrics:
  prometheus:
    enabled: true
```

Access `so.me.ip.here:8080/metrics` and see the metrics.

**Anything else we need to know**:
Please let me know if I can assist.

### LINKED ISSUE #8903: [stable/traefik] reopen #4473 please
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BOTH

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
This is an important security risk that should be addressed

### PR DESCRIPTION
**Pull request by rafaelmagu**
#### What this PR does / why we need it:

The metrics port/endpoint is exposed by default on Traefik's main service whenever `metrics.prometheus.enabled` is set to `true`. This is somewhat of a security concern. This PR adds a default-false variable to allow users to limit the port exposure to only the dashboard service.

#### Which issue this PR fixes
  - fixes #4236
  - fixes #4473
  - fixes #8903

#### Special notes for your reviewer:

Submitted after a chat in Slack with @dtomcej. I didn't know what to name the variable so I went with the obvious `restrictAccess`. Am open to suggestions to make that clearer.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by jgiles** [comment]
@dtomcej @SantoDE @emilevauge ping? We can't enable Prometheus metric collection for our external-facing Traefik because of this security issue.

For all our other applications, our in-cluster Prometheus just discovers and scrapes the pods directly. The service exposure isn't necessary, and probably should be disabled by default because most of the time it is unsafe. But, for backwards compatibility, this PR with an option is sufficient.

**Comment by jgiles** [comment]
@SantoDE @emilevauge @dtomcej ping? We can't enable Prometheus for our externally-facing Traefik because of this security issue.

For all our other applications, our in-cluster Prometheus discovers and scrapes the pods directly. The service exposure is unnecessary in this common usecase, and should probably be disabled by default because it is often unsafe. For backwards compatibility, though, an option to disable is sufficient for now.

**Comment by rafaelmagu** [comment]
Ping @SantoDE @emilevauge @dtomcej for an update. This is ready to go. Please let me know if you need anything else to merge this.

**Comment by rafaelmagu** [comment]
Pinging @SantoDE @emilevauge @dtomcej again for an update.

**Comment by dtomcej** [comment]
@rafaelmagu Sorry for the delay. Kubecon had us pretty busy. Can you rebump the chart version so we can merge this?

**Comment by rafaelmagu** [comment]
@dtomcej bumped.

**Pull request merged**
