### PR TITLE
[incubator/kafka] Fixes zookeeper URL when kafka is included as subchart

### PR DESCRIPTION
**Pull request by fedenusy**
When kafka is included as a subchart, its zookeeper URL is incorrect. This PR fixes the issue.

### CODE REVIEW

**Comment by sameersbn** [comment]
@fedenusy i guess the chart deployments are failing in the test cluster due to faliure to bring up the zookeeper pods. In my local tests I noticed the cluster was running out of resources and was not able to schedule the zookeeper pods on a 3 node GKE cluster.  By removing the hardcoded resource requests https://github.com/kubernetes/charts/blob/master/incubator/zookeeper/values.yaml#L7-L13 I could get the chart to deploy properly. I wonder if we should remove these default values /cc @unguiculus

**Comment by unguiculus** [comment]
Generally, we recommend not to specify defaults for resources for exactly these reasons. I would comment them out so the comment serves as a suggestion.

**Comment by fedenusy** [comment]
These tests were running no problem [a couple days ago](https://github.com/kubernetes/charts/pull/3146)... did test infra change somehow?

@unguiculus ok I'll open Zookeeper PR removing those defaults.

**Comment by fedenusy** [comment]
Actually I just took a closer look at [the logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/3276/pull-charts-e2e/4578/)...

@sameersbn from what I can tell, zookeeper pods are coming up just fine. The `kafka-0` pod enters a `CrashLoopBackoff`, so the tests never execute. Is there a way to get logs out of that pod to see what the issue might be?

**Comment by fedenusy** [comment]
Ok I think I understand the issue.

`include "zookeeper.fullname" .` yields "RELEASE-kafka" (since `.` refers to the current kafka context). So the kafka broker ends up trying to connect to itself instead of the child zookeeper.

Is there a way to pass the child context into the `include` function?

*EDIT:* I think I got it, pushing fix shortly.

**Comment by fedenusy** [comment]
Gahhhhhh... the test succeeded, and then `helm delete --purge` took too long, and the build timed out.... 😞

**Pull request merged**
