### PR TITLE
Volume bug fix

### PR DESCRIPTION
**Pull request by boluisa**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by boluisa** [comment]
.

**Comment by davidkarlsen** [comment]
Isn't https://github.com/helm/charts/pull/7139 a duplicate of this one?

**Comment by boluisa** [comment]
yes it is. but I closed it because I was having issues making the PR

**Comment by boluisa** [comment]
i just closed this one.

**Pull request closed without merging**
