### PR TITLE
[stable/telegraf] Revamping telegraf chart

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
Building on @jackzampolin and the influxdata team's work.

I am looking to use a telegraf helm chart, I would like to use this one hosted in the stable repo.
I have revamped it, I removed the daemonset (node agent) capabiity for simplicity sake, just want to get this chart going again. In my particular case I would need it as a deployment within a cluster for other apps to send metrics to.

Updated labels
Updated helpers file
Update image (I know @kinok tried to do this a few months ago but PR got stale due to no response)
Various other things, please see file changes for more info

#### Which issue this PR fixes
Bring back telegraf in stable repo.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md (They never were)

### CODE REVIEW

**Comment by jackzampolin** [comment]
Also see chart here: https://github.com/influxdata/tick-charts/

I don't really have time to fully test this today.

**Comment by naseemkullah** [comment]
No worries @jackzampolin, maybe another charts maintainer can pick this up?

Shall I add you back to maintainers and to the new OWNERS file as well? I presumed since it was deprecated you would not want to be.

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
bump

**Review by cpanato — APPROVED** [review]

**Pull request merged**
