### PR TITLE
[stable/gitlab-ee] Use storageClassName for gitlab-ee.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed gitlab-ee for #1869

/cc @prydonius

### CODE REVIEW

**Review by prydonius — CHANGES_REQUESTED** [review]
wait for postgresql update

**Comment by gyliu513** [comment]
@prydonius postgresql here https://github.com/kubernetes/charts/pull/2005

**Comment by unguiculus** [comment]
Closing this because the chart is deprecated an won't receive any further updates.

**Pull request closed without merging**
