### PR TITLE
Publish chart for Searchlight

### PR DESCRIPTION
**Pull request by tamalsaha**
Searchlight is a alert manager for Kubernetes based on Icinga2. https://github.com/appscode/searchlight

Resubmitting pr https://github.com/kubernetes/charts/pull/953

### CODE REVIEW

**Comment by unguiculus** [comment]
See comments on #2314.

**Comment by tamalsaha** [comment]
@unguiculus PTAL

**Comment by tamalsaha** [comment]
@unguiculus chart is namespaced

**Comment by tamalsaha** [comment]
@unguiculus, I wonder if you can review this one, too.

**Pull request merged**
