### PR TITLE
[incubator/solr]: add volumeClaimTemplates.enabled flag

### PR DESCRIPTION
**Pull request by mcritchlow**
#### Is this a new chart
No.
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Similar to the Zookeeper chart it depends on, this enables a flag
allowing downstream users to decide whether they want PVCs created for
the StatefulSet.

This is particularly useful in review applications in a CI/CD
environment, which are inherently ephemeral, and PVCs cannot be
trivially removed via `helm delete` in a cleanup function.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mcritchlow** [comment]
What is needed to get a review of this PR?

**Comment by mcritchlow** [comment]
I'm very sorry to do this, but it's been well over 2 months and I noticed the last proposed Solr PR author had to do the same..

Could someone please take a look and let me know if this would be an acceptable change for this chart? Thank you.

@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr

**Comment by scottrigby** [comment]
Seems reasonable.

/ok-to-test 

By the way, have you seen the stable and incubator repo deprecation timeline?

@ian-thebridge-lucidworks I wonder if you'd want to reclaim ownership of this chart?

For context see this issue https://github.com/helm/charts/issues/21103 though that's only tracking stable charts.

**Comment by scottrigby** [comment]
@mcritchlow nice 🙂 would you be willing to ask them and link to this issue?

**Pull request closed without merging**
