### PR TITLE
stable/ambassador: Update to Ambassador 0.80.0.

### PR DESCRIPTION
**Pull request by kflynn**
Signed-off-by: Flynn <flynn@datawire.io>

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by nbkrause** [comment]
/lgtm

Thanks!

**Comment by kflynn** [comment]
Looks like we're hitting #16070...

/retest

**Comment by kflynn** [comment]
🙁 

/retest

**Comment by Flydiverny** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/17315/pull-charts-e2e/1175565655429091328/#0:build-log.txt%3A799

Could be caused by crd already existing, could try editing ci/default-values.yaml to disable crd.. and see if that helps 
@kflynn

**Pull request merged**
