### PR TITLE
[stable/spinnaker] Add option to specify storageclass for halyard persistence data volume

### LINKED ISSUE #22827: [stable/spinnaker] Add storageclass option to halyard persistence data volume
**Is your feature request related to a problem? Please describe.**
The halyard [statefulset](https://github.com/helm/charts/blob/master/stable/spinnaker/templates/statefulsets/halyard.yaml#L197) in the spinnaker helm chart does not have an option to specify the storageclass to use for its pvc. Instead, it always uses the default storage class.

**Describe the solution you'd like**
Provide an option in the values.yaml to configure storage class for the halyard statefulset pvc.

### PR DESCRIPTION
**Pull request by Karthik-13**
Signed-off-by: Karthick Prabu <karthikprabu.cs@gmail.com>

No

#### What this PR does / why we need it:
This PR adds the option to configure storageclass for the halyard statefulset persistence data volume. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #22827

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Karthik-13** [comment]
@paulczar can we go ahead and merge this PR?

**Comment by paulczar** [comment]
/retest

weird error on chart version, trying the old turn it off and on again approach.

**Pull request merged**
