### PR TITLE
[stable/redis] fixed nodePort for master and slave

### PR DESCRIPTION
**Pull request by polarn**
**What this PR does / why we need it**:
Support for nodePort is not really implemented, it's in the values.yaml but not in the template itself

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

#7521

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
@polarn please sign the DCO - https://www.helm.sh/blog/helm-dco/index.html

**Comment by cpanato** [comment]
please add the new variable in the README.md as well

**Comment by polarn** [comment]
@cpanato signed DCO and updated PR with variables in README.md

**Review by juan131 — APPROVED** [review]
Thanks for this contribution!

**Pull request merged**
