### PR TITLE
[Neo4j] Make it possible to pass in extra environment variables

### PR DESCRIPTION
**Pull request by mneedham**
I've copied the pattern used in the Drupal chart - https://github.com/kubernetes/charts/blob/master/stable/drupal/values.yaml#L146 - hopefully that's the correct way to achieve this.

### CODE REVIEW

**Comment by mgoodness** [comment]
Please edit the title to indicate which chart is being updated

**Comment by mneedham** [comment]
@mgoodness have updated the title + rebased against current master. Let me know if there's anything else I need to change.

**Comment by mneedham** [comment]
@unguiculus would you have the time to look at this one and see if it looks ok?

**Comment by unguiculus** [comment]
I didn't even bother running the CI. It would time out anyways for this chart. I ran the tests successfully on my cluster.

**Pull request merged**
