### PR TITLE
19576 Improved Jenkins persistence parameters documentation

### LINKED ISSUE #19576: stable/jenkins Improve Storage Class description
**Describe the bug**
The actual Jenkins documentation doesn't mention the `persistence.storageClass` amongs the parameters that can be set to customise persistence.

**Version of Helm and Kubernetes**:
Helm 3

**Which chart**:
stable/jenkins, version 1.9.9

**What you expected to happen**:
I will create a PR to fix it

### PR DESCRIPTION
**Pull request by krufab**
Signed-off-by: Fabio Kruger <krufab@gmail.com>

#### What this PR does / why we need it:
Improves documentation regarding storage class

#### Which issue this PR fixes
  - fixes #19576

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by mogaal** [comment]
@krufab thanks for helping out, do you mind updating the CHANGELOG? Besides that, it looks good!

**Comment by krufab** [comment]
Ok, I will update the changelog

**Comment by krufab** [comment]
The changelog has been updated

**Pull request merged**
