### PR TITLE
[stable/jenkins] Update jenkins README.MD with right default values

### PR DESCRIPTION
**Pull request by mmiranda**
Changing the default value for master.enableXmlConfig on README.MD according to values.yaml

#### What this PR does / why we need it:
Default value for key master.enableXmlConfig is wrong on the documentation

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@mmiranda Chart.yaml needs version-bump

**Comment by mmiranda** [comment]
@davidkarlsen done! :)

**Pull request merged**
