### PR TITLE
[prometheus] deprecate chart

### PR DESCRIPTION
**Pull request by naseemkullah**
Signed-off-by: Naseem <naseem@transit.app>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by scottrigby** [comment]
Will wait for @Xtigyro to lgtm this one

**Comment by Xtigyro** [comment]
CC: @zanhsieh @gianrubio

**Comment by scottrigby** [comment]
See https://github.com/prometheus-community/community/issues/28 for reference 😄

**Comment by defaultcute12** [comment]
Where can I find the stable prometheus chart with Grafana?

**Comment by naseemkullah** [comment]
@defaultcute12 
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
https://github.com/grafana/helm-charts/tree/main/charts/grafana

**Pull request merged**
