### PR TITLE
Sync etc and general rules with coreos/prometheus-operator

### LINKED ISSUE #9034: [stable/prometheus-operator] incorrect rules labels
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Version of Helm and Kubernetes**:
```
➜  ~  helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
➜  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.6", GitCommit:"d1d4d355f9364d164ca6e485cea3e60e0fa913ca", GitTreeState:"clean", BuildDate:"2018-09-28T00:40:25Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
k8s cluster is GKE

**Which chart**:
stable/prometheus-operator v0.1.14

**What happened**:
Labels set for alert:
```
alertname="KubeJobCompletion"
endpoint="http"
instance="10.36.1.129:8080"
job="kube-state-metrics"
job_name="some_job-1537981200"
namespace="dev-env"
pod="prometheus-kube-state-metrics-69db7f65dc-t7nz9"
service="prometheus-kube-state-metrics"
severity="warning"
```
Alert annotation:
```
message
    Job /kube-state-metrics is taking more than one hour to complete.
```
**What you expected to happen**:
Alert annotation:
```
message
    Job dev-env/some_job-1537981200 is taking more than one hour to complete.
```
**How to reproduce it** (as minimally and precisely as possible):
Deploy chart in a quick way and fail a job, you'll see wrong alert annotation message as above.

**Anything else we need to know**:
[prometheus-rules.yaml](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml) coreos file, imported by name of [all-prometheus-rules.yaml](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/all-prometheus-rules.yaml) here have misconfigured labels.
Following should be redefined:
```
{{ $labels.job }} -> {{ $labels. job_name }}
{{ $labels.namespaces }} -> {{ $labels.namespace }}
```
Interesting thing is what `labels.namespace` is already used in part of alerts.
@gianrubio, can I fix it in coreos/prometheus-operator? Or it's intentional and should (or should not) be fixed only in this repo?

### PR DESCRIPTION
**Pull request by paskal**
As per discussion in https://github.com/helm/charts/issues/8749, we need a way to sync rules with [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator) (or [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)). After that we could have multiply rules files and will be able to disable them in case component scraping is disabled.

Discovering coreos repo I found out that [etcd rules](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml) file is altered version from [etcd repo](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/etcd3_alert.rules.yml), I've created https://github.com/etcd-io/etcd/pull/10244 to update bith yaml and [libsonnet file](https://github.com/etcd-io/etcd/blob/master/Documentation/etcd-mixin/mixin.libsonnet) with prometheus-operator version.

Etcd rules won't be changed in coreos/prometheus-operator and it's safe to manually update it now from etcd-io version, which I did in this PR along with moving it to separate file. Part of it's rules moved to `general.rules` section and I've updated it in this PR as well.

Also https://github.com/coreos/prometheus-operator/pull/2096 results merged to fix #9034.

In next PR I'll split all.rules.yaml into multiply files and will add python script to sync them with coreos/prometheus-operator or kubernetes-mixin. This is the first step I'd like to have done separately.

### CODE REVIEW

**Comment by paskal** [comment]
/assign @gianrubio
ping for review @vsliouniaev

**Comment by jaipradeesh** [comment]
Hello there, any ETA for this merge?

**Comment by vsliouniaev** [comment]
Thanks for doing this @paskal . I'm not sure it's a good idea to disable only the etcd rules when etcd is disabled because this creates an inconsistency in the behaviour until this change is applied with respect to all exporters.

**Comment by paskal** [comment]
I can disable etcd switch for consistency for now. @gianrubio, waiting for your verdict.

**Comment by paskal** [comment]
@vsliouniaev I've disabled the switch, updated rules from [etcd libsonnet]

**Comment by dojadop** [comment]
Since this update the following alert is triggered constantly on my cluster:  EtcdHighNumberOfFailedHTTPRequests.  

Additionally looking at the upstream etcd rules (https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/etcd3_alert.rules) I do not see references to FailedHTTPRequests anymore so  should shall I open a Issue to remove this from this chart?

**Comment by paskal** [comment]
I'll prepare PR with fix in the morning, my apologies.

**Comment by paskal** [comment]
Metrics which alert set up on described there: https://github.com/etcd-io/etcd/blob/master/Documentation/v2/metrics.md
Alerts are in progress of adding in https://github.com/etcd-io/etcd/pull/10244, particular this one is taken from [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml) originally.

@dojadop, actually, what make you think it's not the real problem?

**Comment by dojadop** [comment]
@paskal after looking at the metrics it looks like there is a constant 404 which causes the alert to trigger: 

image

It might be related to this https://github.com/coreos/prometheus-operator/issues/1631#issuecomment-408087031 but not too sure

**Comment by paskal** [comment]
@dojadop, I'll exclude 404 from original repo and then will sync it up there.

**Comment by paskal** [comment]
@dojadop, actually it's hard to debug for me without having etcd. Would you be so kind to prepare expression which will exclude 404 errors from counting, test it and give it to me to be included in https://github.com/etcd-io/etcd/pull/10244?

**Comment by dojadop** [comment]
@paskal you need to add `code!="404"` to the selector
```
sum by(method) (rate(etcd_http_failed_total{job=~".*etcd.*", code!="404"}[5m])) / sum by(method) (rate(etcd_http_received_total{job=~".*etcd.*"}[5m])) > 0.05

sum by(method) (rate(etcd_http_failed_total{job=~".*etcd.*", code!="404"}[5m])) / sum by(method) (rate(etcd_http_received_total{job=~".*etcd.*"}[5m])) > 0.01
```

**Comment by dojadop** [comment]
Or if you want to ignore all 4xx error codes then you would use this:  `code!~"4[0-9]{2}"`

**Comment by paskal** [comment]
@dojadop https://github.com/helm/charts/pull/9516 sync this change to this very repo.

**Comment by paskal** [comment]
@dojadop, rules with 404 error excluded are synced to this repo, please open issues if you'll see any errors with current set of rules.

**Pull request merged**
