### PR TITLE
[incubator/kafka] Add configuration of backoffLimit for kafka-config job

### PR DESCRIPTION
**Pull request by mateuszrapacz**
#### What this PR does / why we need it:
This PR add possibility to configure backoffLimit for kafka-config job.
In some situations (e.g. many replicas of Kafka's pods, when the deployment process may take too long) the default value of this parameter (6) is insufficient, which causes the kafka-config job to fail. Thanks to the possibility of changing this parameter, kafka-config job can wait until all Kafka's pods are ready.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md

### CODE REVIEW

**Comment by mattfarina** [comment]
/ok-to-test

@benjigoldberg does this change look ok to merge?

**Comment by benjigoldberg** [comment]
@mattfarina yep, thanks for bumping this again.

/lgtm

**Pull request merged**
