### PR TITLE
[stable/weave-scope] only use serviceAccountName if rbac.create is true

### PR DESCRIPTION
**Pull request by elemeht**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by paulczar** [comment]
change looks good to me, but can you prepend the PR title with `[stable/weave-scope]` so that its easier to identify ?

**Comment by prydonius** [comment]
I'm not sure about this, what if I want to provide a pre-created service account that already has the RBAC rules setup?
cc @mgoodness @unguiculus

**Comment by unguiculus** [comment]
We should not do this. Our RBAC best practices are currently being revised. I've been discussing this with @omkensey. The first chart to implements the updated best practices is https://github.com/kubernetes/charts/tree/master/stable/cert-manager. See discussion at https://github.com/jetstack/cert-manager/pull/229.

I'm working on a PR to update the documentation. An initial draft is here: https://github.com/unguiculus/helm/blob/feature/rbac/docs/chart_best_practices/rbac.md

I asked @omkensey for feedback and may have to make slight changes to it. I'm off sick this week so I just did get around to finishing this off. I hope to create the PR soon.

**Comment by unguiculus** [comment]
cc @omkensey

**Comment by unguiculus** [comment]
PR for revised RBAC best practices: https://github.com/kubernetes/helm/pull/3408

**Comment by elemeht** [comment]
Do I need to do anything else to this PR?

**Comment by omkensey** [comment]
This looks good to me in current form.

**Pull request merged**
