### PR TITLE
[stable/efs-provisioner] Upgrade EFS provisioner

### PR DESCRIPTION
**Pull request by srueg**
#### What this PR does / why we need it:

Upgrade the provisioner to the latest version (v2.2.0-k8s1.12).
Add myself to OWNERS.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by hareku** [comment]
@srueg Thank you for your PR.

I think this PR is not necessary. Users can specify efs-provisioner tag from `values.yaml`, and default tag should be `latest`.

If you want to be an owner, please make another PR.

**Comment by srueg** [comment]
But the currently configured tag is `v2.1.0-k8s1.11` and the Chart references an `appVersion`. I would much prefer to provide a sane default.

**Comment by hareku** [comment]
https://github.com/helm/charts/blob/14dcbf62bb04a9ae15be1f91c3f5db9067cd948b/stable/efs-provisioner/templates/deployment.yaml#L49

It seems like a tag references `.Values.image.tag`.
Is this understanding mistaken?

**Comment by srueg** [comment]
Yes, you're right. I just meant currently the `values.yaml` file references `v2.1.0-k8s1.11` and not the `latest` tag.
It's also my understanding to be considered best practice to specify an image tag instead of using `latest`.

**Pull request merged**
