### PR TITLE
[stable/prometheus-operator] namespace override

### LINKED ISSUE #18837: [stable/prometheus-operator] Ability to configure namespace
I would like to create a chart which will depend on `prometheus-operator` and I want to install prometheus in a separate namespace.
```yaml
dependencies:
  - name: prometheus-operator
    version: "7.2.0"
    repository: "@stable"
```
Currently it's not possible to specify different namespace for prometheus (`namespace: {{ $.Release.Namespace }}`).

Is it a better way than fork the chart and change it to something like `namespace: {{ .Values.global.prometheusNamespace }}`?

### PR DESCRIPTION
**Pull request by yoninl2**
No
#### What this PR does / why we need it:
It adds a namespaceOverride parameter, which allows this chart to be used in cases where templating is used across namespaces. By providing this parameter, the resulting templating will output to the specified namespace.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #18837 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by yoninl2** [comment]
What's the pull-charts-e2e check? Is it waiting for ok-to-test label?

**Comment by yoninl2** [comment]
hello, any progress?

**Comment by yoninl2** [comment]
Seems the e2e has some issues, but I personally validated the chart, it's fine in my cluster.

```
# kubectl apply -f crds/
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com created
# helm upgrade --install prometheus -f ./ci/02-test-without-crds-values.yaml .
Release "prometheus" does not exist. Installing it now.
NAME:   prometheus
LAST DEPLOYED: Tue Jun  9 08:47:02 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Alertmanager
NAME                                     VERSION  REPLICAS  AGE
prometheus-prometheus-oper-alertmanager  v0.20.0  1         33s

==> v1/ClusterRole
NAME                                       AGE
prometheus-grafana-clusterrole             34s
prometheus-prometheus-oper-operator        34s
prometheus-prometheus-oper-operator-psp    34s
prometheus-prometheus-oper-prometheus      34s
prometheus-prometheus-oper-prometheus-psp  34s
psp-prometheus-kube-state-metrics          34s
psp-prometheus-prometheus-node-exporter    34s

==> v1/ClusterRoleBinding
NAME                                       AGE
prometheus-grafana-clusterrolebinding      34s
prometheus-prometheus-oper-operator        34s
prometheus-prometheus-oper-operator-psp    34s
prometheus-prometheus-oper-prometheus      34s
prometheus-prometheus-oper-prometheus-psp  34s
psp-prometheus-kube-state-metrics          34s
psp-prometheus-prometheus-node-exporter    34s

==> v1/ConfigMap
NAME                                                          DATA  AGE
prometheus-grafana                                            1     33s
prometheus-grafana-config-dashboards                          1     33s
prometheus-grafana-test                                       1     33s
prometheus-prometheus-oper-apiserver                          1     33s
prometheus-prometheus-oper-cluster-total                      1     33s
prometheus-prometheus-oper-controller-manager                 1     33s
prometheus-prometheus-oper-etcd                               1     33s
prometheus-prometheus-oper-grafana-datasource                 1     33s
prometheus-prometheus-oper-k8s-coredns                        1     33s
prometheus-prometheus-oper-k8s-resources-cluster              1     33s
prometheus-prometheus-oper-k8s-resources-namespace            1     33s
prometheus-prometheus-oper-k8s-resources-node                 1     33s
prometheus-prometheus-oper-k8s-resources-pod                  1     33s
prometheus-prometheus-oper-k8s-resources-workload             1     33s
prometheus-prometheus-oper-k8s-resources-workloads-namespace  1     33s
prometheus-prometheus-oper-kubelet                            1     33s
prometheus-prometheus-oper-namespace-by-pod                   1     33s
prometheus-prometheus-oper-namespace-by-workload              1     33s
prometheus-prometheus-oper-node-cluster-rsrc-use              1     33s
prometheus-prometheus-oper-node-rsrc-use                      1     33s
prometheus-prometheus-oper-nodes                              1     33s
prometheus-prometheus-oper-persistentvolumesusage             1     33s
prometheus-prometheus-oper-pod-total                          1     33s
prometheus-prometheus-oper-prometheus                         1     33s
prometheus-prometheus-oper-proxy                              1     33s
prometheus-prometheus-oper-scheduler                          1     33s
prometheus-prometheus-oper-statefulset                        1     33s
prometheus-prometheus-oper-workload-total                     1     33s

==> v1/DaemonSet
NAME                                 DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR  AGE
prometheus-prometheus-node-exporter  3        3        3      3           3          <none>         33s

==> v1/Deployment
NAME                                 READY  UP-TO-DATE  AVAILABLE  AGE
prometheus-grafana                   1/1    1           1          33s
prometheus-kube-state-metrics        1/1    1           1          33s
prometheus-prometheus-oper-operator  1/1    1           1          33s

==> v1/Pod(related)
NAME                                            READY  STATUS   RESTARTS  AGE
prometheus-kube-state-metrics-66d969ff69-x2k9b  1/1    Running  0         34s
prometheus-kube-state-metrics-66d969ff69-x2k9b  1/1    Running  0         34s
prometheus-kube-state-metrics-66d969ff69-x2k9b  1/1    Running  0         34s
prometheus-kube-state-metrics-66d969ff69-x2k9b  1/1    Running  0         34s

==> v1/Prometheus
NAME                                   VERSION  REPLICAS  AGE
prometheus-prometheus-oper-prometheus  v2.18.1  1         33s

==> v1/PrometheusRule
NAME                                                             AGE
prometheus-prometheus-oper-alertmanager.rules                    33s
prometheus-prometheus-oper-etcd                                  33s
prometheus-prometheus-oper-general.rules                         33s
prometheus-prometheus-oper-k8s.rules                             33s
prometheus-prometheus-oper-kube-apiserver-slos                   33s
prometheus-prometheus-oper-kube-apiserver.rules                  33s
prometheus-prometheus-oper-kube-prometheus-general.rules         33s
prometheus-prometheus-oper-kube-prometheus-node-recording.rules  33s
prometheus-prometheus-oper-kube-scheduler.rules                  33s
prometheus-prometheus-oper-kube-state-metrics                    33s
prometheus-prometheus-oper-kubelet.rules                         33s
prometheus-prometheus-oper-kubernetes-apps                       33s
prometheus-prometheus-oper-kubernetes-resources                  33s
prometheus-prometheus-oper-kubernetes-storage                    33s
prometheus-prometheus-oper-kubernetes-system                     33s
prometheus-prometheus-oper-kubernetes-system-apiserver           33s
prometheus-prometheus-oper-kubernetes-system-controller-manager  33s
prometheus-prometheus-oper-kubernetes-system-kubelet             33s
prometheus-prometheus-oper-kubernetes-system-scheduler           33s
prometheus-prometheus-oper-node-exporter                         33s
prometheus-prometheus-oper-node-exporter.rules                   33s
prometheus-prometheus-oper-node-network                          33s
prometheus-prometheus-oper-node.rules                            33s
prometheus-prometheus-oper-prometheus                            33s
prometheus-prometheus-oper-prometheus-operator                   33s

==> v1/Role
NAME                                     AGE
prometheus-grafana-test                  34s
prometheus-prometheus-oper-alertmanager  34s

==> v1/RoleBinding
NAME                                     AGE
prometheus-grafana-test                  34s
prometheus-prometheus-oper-alertmanager  34s

==> v1/Secret
NAME                                                  TYPE    DATA  AGE
alertmanager-prometheus-prometheus-oper-alertmanager  Opaque  1     33s
prometheus-grafana                                    Opaque  3     33s

==> v1/Service
NAME                                                TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)           AGE
prometheus-grafana                                  ClusterIP  172.20.26.89    <none>       80/TCP            33s
prometheus-kube-state-metrics                       ClusterIP  172.20.68.159   <none>       8080/TCP          33s
prometheus-prometheus-node-exporter                 ClusterIP  172.20.72.6     <none>       9100/TCP          33s
prometheus-prometheus-oper-alertmanager             ClusterIP  172.20.57.37    <none>       9093/TCP          33s
prometheus-prometheus-oper-operator                 ClusterIP  172.20.114.254  <none>       8080/TCP,443/TCP  33s
prometheus-prometheus-oper-prometheus               ClusterIP  172.20.213.63   <none>       9090/TCP          33s
prometheus-prometheus-oper-coredns                  ClusterIP  None            <none>       9153/TCP          33s
prometheus-prometheus-oper-kube-controller-manager  ClusterIP  None            <none>       10252/TCP         33s
prometheus-prometheus-oper-kube-etcd                ClusterIP  None            <none>       2379/TCP          33s
prometheus-prometheus-oper-kube-proxy               ClusterIP  None            <none>       10249/TCP         33s
prometheus-prometheus-oper-kube-scheduler           ClusterIP  None            <none>       10251/TCP         33s

==> v1/ServiceAccount
NAME                                     SECRETS  AGE
prometheus-grafana                       1        33s
prometheus-grafana-test                  1        33s
prometheus-kube-state-metrics            1        33s
prometheus-prometheus-node-exporter      1        33s
prometheus-prometheus-oper-alertmanager  1        33s
prometheus-prometheus-oper-operator      1        33s
prometheus-prometheus-oper-prometheus    1        33s

==> v1/ServiceMonitor
NAME                                                AGE
prometheus-prometheus-oper-alertmanager             33s
prometheus-prometheus-oper-apiserver                33s
prometheus-prometheus-oper-coredns                  33s
prometheus-prometheus-oper-grafana                  33s
prometheus-prometheus-oper-kube-controller-manager  33s
prometheus-prometheus-oper-kube-etcd                33s
prometheus-prometheus-oper-kube-proxy               33s
prometheus-prometheus-oper-kube-scheduler           33s
prometheus-prometheus-oper-kube-state-metrics       33s
prometheus-prometheus-oper-kubelet                  33s
prometheus-prometheus-oper-node-exporter            33s
prometheus-prometheus-oper-operator                 33s
prometheus-prometheus-oper-prometheus               33s

==> v1beta1/ClusterRole
NAME                           AGE
prometheus-kube-state-metrics  34s

==> v1beta1/ClusterRoleBinding
NAME                           AGE
prometheus-kube-state-metrics  34s

==> v1beta1/MutatingWebhookConfiguration
NAME                                  CREATED AT
prometheus-prometheus-oper-admission  2020-06-09T08:47:37Z

==> v1beta1/PodSecurityPolicy
NAME                                     PRIV   CAPS      SELINUX           RUNASUSER  FSGROUP    SUPGROUP  READONLYROOTFS  VOLUMES
prometheus-grafana                       false  RunAsAny  RunAsAny          RunAsAny   RunAsAny   false     configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
prometheus-grafana-test                  false  RunAsAny  RunAsAny          RunAsAny   RunAsAny   false     configMap,downwardAPI,emptyDir,projected,secret
prometheus-kube-state-metrics            false  RunAsAny  MustRunAsNonRoot  MustRunAs  MustRunAs  false     secret
prometheus-prometheus-node-exporter      false  RunAsAny  RunAsAny          MustRunAs  MustRunAs  false     configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
prometheus-prometheus-oper-alertmanager  false  RunAsAny  RunAsAny          MustRunAs  MustRunAs  false     configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
prometheus-prometheus-oper-operator      false  RunAsAny  RunAsAny          MustRunAs  MustRunAs  false     configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
prometheus-prometheus-oper-prometheus    false  RunAsAny  RunAsAny          MustRunAs  MustRunAs  false     configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim

==> v1beta1/Role
NAME                AGE
prometheus-grafana  34s

==> v1beta1/RoleBinding
NAME                AGE
prometheus-grafana  34s

==> v1beta1/ValidatingWebhookConfiguration
NAME                                  CREATED AT
prometheus-prometheus-oper-admission  2020-06-09T08:47:37Z


NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=prometheus"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.
# kubectl get po
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-prometheus-oper-alertmanager-0   2/2     Running   0          2m13s
prometheus-grafana-6cc9f69bf6-5n8tq                      2/2     Running   0          2m26s
prometheus-kube-state-metrics-66d969ff69-x2k9b           1/1     Running   0          2m26s
prometheus-prometheus-node-exporter-9jqwd                1/1     Running   0          2m26s
prometheus-prometheus-node-exporter-msmr8                1/1     Running   0          2m26s
prometheus-prometheus-node-exporter-qbvvj                1/1     Running   0          2m26s
prometheus-prometheus-oper-operator-7bbd5f6f5f-h8kt4     2/2     Running   0          2m26s
prometheus-prometheus-prometheus-oper-prometheus-0       3/3     Running   1          2m3s
```

/retest

**Comment by yoninl2** [comment]
The last two auto-CI failed with different reasons, one is timed out waiting for pod to be running, another one is timed out waiting pods to be terminated, but I didn't change code, /retest again.

**Comment by tiagomeireles** [comment]
This broke `prometheus.additionalServiceMonitors`. Its throwing the following.

```
Error: template: test/charts/prometheus-operator/templates/_helpers.tpl:88:16: executing "prometheus-operator.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride

Use --debug flag to render out invalid YAML
```

**Comment by tiagomeireles** [comment]
The fix appears to be 

```
+++ b/stable/prometheus-operator/templates/prometheus/servicemonitors.yaml
@@ -7,7 +7,7 @@ items:
     kind: ServiceMonitor
     metadata:
       name: {{ .name }}
-      namespace: {{ template "prometheus-operator.namespace" . }}
+      namespace: {{ template "prometheus-operator.namespace" $ }}
       labels:
         app: {{ template "prometheus-operator.name" $ }}-prometheus
 {{ include "prometheus-operator.labels" $ | indent 8 }}
```

**Comment by supertetelman** [comment]
I'm seeing this error as well. Is there an easy workaround until this gets patched?

`Error: render error in "prometheus-operator/templates/prometheus/servicemonitors.yaml": template: prometheus-operator/templates/_helpers.tpl:88:16: executing "prometheus-operator.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride`

**Comment by timown** [comment]
same happens for additionalPrometheusRulesMap and additionalPrometheusRules
need to replace . with $

**Comment by yoninl2** [comment]
I see, these are inside range function, I will create a new pr to fix, sorry didn't tested with some switch enabled.

**Comment by den-is** [comment]
There is another bug with that PR.
Apparently you have generated rules and dashboards manually. And reviewers have missed that fact.
Your change for rules and dashboards should be applied in python scripts which actually generate these resources.

Here is the https://github.com/helm/charts/issues/22892

**Pull request merged**
