### PR TITLE
[stable/spring-cloud-data-flow] Update to new SCDF version 2.0.2

### PR DESCRIPTION
**Pull request by chrisjs**
#### What this PR does / why we need it:

- update app version to 2.0.2
- update skipper version to 2.0.1

Signed-off-by: Chris Schaefer <cschaefer@pivotal.io>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@unguiculus/@paulczar: A friendly follow-up; it'd be great if you could weigh-in and give us feedback if you have any. Thanks!

**Comment by unguiculus** [comment]
The chart-testing too seems to have an issue here creating an invalid namespace name. I'll have to look into this.

**Comment by unguiculus** [comment]
We still have issues with CI. I'm investigating.

**Pull request merged**
