### PR TITLE
[incubator/vault] vaultExporter metrics service entry

### PR DESCRIPTION
**Pull request by mogaal**
#### What this PR does / why we need it:

Currently, when you enable vaultExporter (a container inside the Vault pod) there is no way access to the metrics through the service resource and it needs to exist in order to Prometheus (an example) be able to pull the metrics

#### Which issue this PR fixes

This PR check when it is enabled vaultExporter and set the exporter port (9410) inside the Service resource. 

Exposing metrics endpoint as service makes easier to third-party services (like Prometheus) to access the metrics.

#### Special notes for your reviewer:

For testing just play with 

```
vaultExporter:
  enabled: true
``` 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jbialy** [comment]
Just a general observation about the vault-exporter sidecar...

I've noticed that the [github repo](https://github.com/grapeshot/vault_exporter) is no longer accessible? It's hard to find a reference to the actual implementation and requirements aside from the working docker image. 🤔 

Perhaps going forward, a better place for adding sidecars would be under `extraContainers` with the option to include `extraPorts` within the `service` resource. This would be much more generic and seems to be the convention that other charts have taken?

**Comment by mogaal** [comment]
Good point, I'll close this PR and create a new one with the advises and suggestions.

**Comment by jbialy** [comment]
> Good point, I'll close this PR and create a new one with the advises and suggestions.

That'd be great!

**Pull request closed without merging**
