### PR TITLE
[incubator/cassandra] Ability to override Cassandra configuration files and docker command

### LINKED ISSUE #8375: [incubator/cassandra] Ability to override Cassandra configuration files
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Version of Helm and Kubernetes**:
Helm: 2.10
K8s: 1.10

**Which chart**:
incubator/cassandra

**What happened**:
There is no possibility of change to Cassandra configuration files

**What you expected to happen**:
Ability to change those files

### PR DESCRIPTION
**Pull request by maver1ck**
#### Which issue this PR fixes
  - fixes #8375

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by maver1ck** [comment]
@davidkarlsen 
This PR need more thinking.
The idea is to provide custom configuration files into /etc/cassandra

The only problem was that entry point in official cassandra image is trying to change ownership of those files and then is failing. (because configmaps are read-only)
So we need also custom entry point with args.
WDYT ?

**Comment by maver1ck** [comment]
ping @davidkarlsen

**Comment by deyceg** [comment]
@maver1ck will this work? the Docker image tries to chown directories so as of  k8s 1.9 anything you mount to `/etc/cassandra` will be read only.

**Comment by maver1ck** [comment]
@deyceg 
That's the reason I give option to override entrypoint :)

Sample configuration:
```
configOverrides:
  cassandra.sh: |
      chown -R cassandra:cassandra /var/lib/cassandra
      chmod 777 /var/lib/cassandra
      find /var/lib/cassandra /var/log/cassandra -exec chown cassandra:cassandra '{}' \;
      gosu cassandra cassandra -f
commandOverrides:
  - "bash"
argsOverrides:
  - "/etc/cassandra/cassandra.sh"
```

**Comment by deyceg** [comment]
@maver1ck missed that!

I ended up publishing our own version which will source any custom config from `/opt/cassandra` (or a dir of your choosing) into `/etc/cassandra` before the `chown` so the only change I made was to mount a slightly modified (but backward compatible) `docker-entrypoint.sh`

**Comment by maver1ck** [comment]
@deyceg 
I prefer to use official charts if this is possible :)

**Comment by deyceg** [comment]
@maver1ck same unfortunately timings etc. means I needed password authentication and ability to override yesterday :)

I've kept my chart as close to this one with a view of swapping over when its available officially!

**Comment by maver1ck** [comment]
@deyceg You can use my branch :)

**Comment by Sebubu** [comment]
This sample doesn't work for me. Pods are in `CrashLoopBackOff` until I removed the sample configuration again. No clue why.

> @deyceg
> That's the reason I gave option to override entrypoint :)
> 
> Sample configuration:
> 
> ```
> configOverrides:
>   cassandra.sh: |
>       chown -R cassandra:cassandra /var/lib/cassandra
>       chmod 777 /var/lib/cassandra
>       find /var/lib/cassandra /var/log/cassandra -exec chown cassandra:cassandra '{}' \;
>       gosu cassandra cassandra -f
> commandOverrides:
>   - "bash"
> argsOverrides:
>   - "/etc/cassandra/cassandra.sh"
> ```

**Comment by maver1ck** [comment]
Do you have some logs ?

**Pull request merged**
