### PR TITLE
[stable/redis] Fix (again) extraFlags and test it.

### PR DESCRIPTION
**Pull request by desaintmartin**
Fixes https://github.com/helm/charts/pull/10826 that broke https://github.com/helm/charts/pull/10388 that fixed yet another commit that broke.

And make sure we are done forever with this regression.

### CODE REVIEW

**Comment by desaintmartin** [comment]
/hold

Do you have any idea how to fetch the password for the test?

**Comment by desaintmartin** [comment]
For now I disable the test-connection when password is enabled, but it works for others, maybe making it work for all test cases is out of scope of this PR.

/hold cancel

**Comment by desaintmartin** [comment]
cc @carrodher @juan131 @prydonius @sameersbn @tompizmor
Any advice for the test part is appreciated as it could lead the way to future testing of this chart.

**Review by juan131 — APPROVED** [review]
Hi @desaintmartin 

I have no idea about how to retrieve the password. Maybe @unguiculus has more info.

In any case, regarding the fix (*stable/redis/templates/redis-master-statefulset.yaml*), the changes LGTM. The rest of the changes in the CI tests should help to avoid breaking this feature again in the future, thanks so much for it.

**Comment by desaintmartin** [comment]
Not stale.

**Comment by juan131** [comment]
Any news on how to fetch the password??  @desaintmartin

**Comment by desaintmartin** [comment]
I haven't investigated much, maybe we can bring this up in a chart meeting to see if someone has a tip? This is somehow related to the more general "try to generate a password" problem we face in many charts.

**Comment by carrodher** [comment]
Yes, I agree we can look for some ideas in the meeting

**Comment by desaintmartin** [comment]
There does not seem any way to fetch it. Maybe we can merge and at least some parameters are tested?

**Comment by carrodher** [comment]
Mmmm, yes I can't find another solution, btw there are some conflicts in the version.

**Comment by tjespers** [comment]
@desaintmartin while i like the idea of the test to check if the connection is ok, the current hook can fail for some attributes e.g. `redis-server --maxmemory 100mb` will produce the following:

```
# redis-cli
127.0.0.1:6379> CONFIG GET maxmemory
1) "maxmemory"
2) "104857600"
```

this will cause a test failure while it shouldn't, it might be better to not merge the test with this MR and submit it as a seperate PR once we solve the password issue as well as the issue i stated above?

**Comment by tjespers** [comment]
@desaintmartin secondly this PR also only restores the extra functionality for the master but the `slave.extraFlags` would still be broken if we were to merge this PR as is.

**Comment by kim0** [comment]
I am stuck and need to get this working ASAP. Basically my "master" is not really a master, rather a slave of another remote true master. So I need to be able to pass those extra flags to config that behavior.

@tjespers .. If I add extraFlags for slave, and remove the test for now. Will you merge it ?
Also, what's the best way to do this, should I send a separate PR ?

@desaintmartin if you can fix it soon (this week?) let me know to not send a separate PR .. Thx!

**Comment by desaintmartin** [comment]
Rebased and fixed for slave as well.

**Comment by kim0** [comment]
Thanks a lot @desaintmartin for the very quick fix :)

@tjespers & @sameersbn .. is it possible to get this merged soon? Thanks!

**Comment by tompizmor** [comment]
@desaintmartin It seems there are some conflicts. Can you resolve them?

**Comment by kim0** [comment]
@tompizmor .. can we please merge this .. Thanks

**Comment by desaintmartin** [comment]
Rebased.

**Comment by kim0** [comment]
Hope I'm not nagging .. but I really hope this can get merged soon. I'm blocked on this fix. Thanks!
@juan131 @tompizmor @sameersbn

**Comment by kim0** [comment]
@desaintmartin .. can you please rebase .. Thank you! sigh

I really hope the maintainers can quickly merge, so we can escape this rebase .. delay .. rebase cycle. Thanks! @juan131 @tompizmor @sameersbn

**Comment by desaintmartin** [comment]
Rebased! ;)

**Comment by kim0** [comment]
Sigh, this is becoming frustrating .. Such a small fix taking all that time, why!

Helm is pushing me to think twice before depending on it again

**Comment by desaintmartin** [comment]
There is no problem in having your own fork. This is what I do.

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Pull request merged**
