### PR TITLE
Fluent bit json command

### PR DESCRIPTION
**Pull request by asm72**
#### What this PR does / why we need it:

Makes it possible to define multiple commands in the json parser configuration

#### Which issue this PR fixes
NA
#### Special notes for your reviewer:
@kfox1111 , @edsiper PTAL
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [] Variables are documented in the README.md

### CODE REVIEW

**Comment by kfox1111** [comment]
lgtm

**Comment by kfox1111** [comment]
For consistency, could you call it extraEntries instead of command? maybe also add it to the other parser block too?

**Comment by asm72** [comment]
@kfox1111 The idea is that defining the json parser config with the "commands" directly (filling the config table by rows) is more flexible than defining all the entries that the parses supports cell by cell as it is now. For backward compatibility the "decodeFieldAs" flag is kept.
I don't know if I got your request right but I see the two flags "decodeFieldAs" and "commands" as alternative ways for defining the json parser config.
I can change the names without any issue ... let me know your thoughts on this.

**Comment by kfox1111** [comment]
```
your example:
  ##    commands:
  ##      - command: Decode_Field_As  escaped log do_next
  ##      - command: Decode_Field_As  json log
```

could be:
```
  ##    extraEntries:
  ##      - command: Decode_Field_As  escaped log do_next
  ##      - command: Decode_Field_As  json log
```

and it would be more consistent with the rest of the things adding chunks of config to the config files.

Well, actually, I think the example is not quite right. it would try to make a key for command. it probably should be:
```
  ##    extraEntries: |
  ##       command: Decode_Field_As  escaped log do_next
  ##       command: Decode_Field_As  json log
```

**Comment by asm72** [comment]
@kfox1111 PTAL
Thanks

**Comment by asm72** [comment]
@kfox1111 sorry for bothering you... who should/could approve this ?

**Comment by kfox1111** [comment]
no bother. thanks for pinging me. I would have thought my lgtm would have been enough.... lets see...

**Comment by kfox1111** [comment]
@mattfarina or @seanknox, could you please allow the test? I can't seem to do that. Thanks.

**Pull request merged**
