### PR TITLE
[helm/charts] Add annotations support in deployment of cerebro

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
Adds support for annotations in deployment of cerebro

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @davidkarlsen and @foxish
Ping

**Comment by faizanahmad055** [comment]
Hi @davidkarlsen and @foxish
Can you guys please take a look at this.

**Review by davidkarlsen — APPROVED** [review]

**Comment by faizanahmad055** [comment]
Hi @davidkarlsen
Thank you for approving the PR. I had to bump the version again after including the latest changes. Can you please take a look at it again.

**Pull request merged**
