### PR TITLE
[stable/stolon] Use custome names for stolon keeper in different namespace

### PR DESCRIPTION
**Pull request by Negashev**
#### Which issue this PR fixes
  - It help to create different UIDs for stolon keepers when you create two stolon clusters on one backend storage

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Negashev** [comment]
@cpanato It's ready to approve

**Review by cpanato — APPROVED** [review]

**Pull request merged**
