### PR TITLE
stable/fluent-bit: Add labels to all objects

### PR DESCRIPTION
**Pull request by NicolasT**
Also: restrict the `Service` `selector` somewhat to include the release
name.

Fixes: #6672
See: https://github.com/kubernetes/charts/issues/6672

### CODE REVIEW

**Comment by NicolasT** [comment]
/assign @linki
CC @kfox1111 @edsiper

**Comment by kfox1111** [comment]
lgtm

**Comment by kfox1111** [comment]
another 0.7 was merged recently. please bump the version again.

**Pull request merged**
