### PR TITLE
[incubator/druid] Add missing ingress.yaml to druid router

### LINKED ISSUE #23396: [incubator/druid] router ingress not deployed
**Describe the bug**
It is not possible to deploy router's ingress on Druid chart. `values.yaml` is prepared to do it but has no effect.

**Which chart**:
Incubator/druid

**What happened**:
Druid router's ingress is not deployed when it is configured with the values. Is `ingress.yaml` at `/helm/charts/tree/master/incubator/druid/templates/router` missing?

**What you expected to happen**:

**How to reproduce it**:
Deploy chart with router ingress enabled. On config file:
```yaml
router:
  enabled: true
  ingress:
    enabled: true
    path: /
    hosts:
      - druid.mydomain.com
```

### PR DESCRIPTION
**Pull request by leinad87**
### What this PR does / why we need it:
Adds the missing `ingress.yaml` to Druid's router template.

#### Which issue this PR fixes
  - fixes #23396

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by leinad87** [comment]
I've updated the chart version to `0.2.14` and now it fails with `FAIL: pull-charts-e2e`. Is it my error? What have I done wrong?

**Comment by AWaterColorPen** [comment]
/retest
@leinad87 for my understanding, it should be zookeeper's issue. zookeeper cost much time to be ready.
you can try to delete  `zookeeper.headless.publishNotReadyAddresses: true` in values.yaml.

**Pull request merged**
