### PR TITLE
[stable/kube2iam] Rolling updates

### PR DESCRIPTION
**Pull request by cknowles**
Also bump to latest image version

### CODE REVIEW

**Comment by linki** [comment]
Would it make sense to rather do:

```yaml
updateStrategy:
  type: {{ .Values.updateStrategy }}
```

and then set always set it to a value in values.yaml?

**Comment by cknowles** [comment]
@linki yes make sense if k8s adds to the list of values in the future, I will change that now. I think a lot of these sorts of addition would be better in some generic base layer for Helm rather than putting them into every Chart but I think it's the only possibility right now.

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Pull request merged**
