### PR TITLE
add Kubeinvaders

### PR DESCRIPTION
**Pull request by lucky-sideburn**

### CODE REVIEW

**Comment by lucky-sideburn** [comment]
Fixed circleci checks and commit messages :)

**Comment by zanhsieh** [comment]
@lucky-sideburn 
I would say a new chart should go thru incubator before reaching stable. Also, you should consider host your own.

**Comment by lucky-sideburn** [comment]
Ops sorry! You're right, I should pass through incubator. Should I close this pr?

**Comment by cpanato** [comment]
@lucky-sideburn we are not accepting new charts in the incubator, only in the stable folder.
But we prefer you host yourself the charts

**Comment by lucky-sideburn** [comment]
Ah ok. I already host chart [there](https://github.com/lucky-sideburn/KubeInvaders/tree/master/helm-charts).

**Comment by lucky-sideburn** [comment]
hi! passed all automatic tests

**Comment by lucky-sideburn** [comment]
@cpanato is it ok for merge?

**Comment by scottrigby** [comment]
Hi 👋 new charts are no longer accepted to `stable` or `incubator`. See [Status of the Project](https://github.com/helm/charts#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts#deprecation-timeline) for more info about that.

Good news is you can host a Helm chart yourself on GitHub, use the same tools as this repo does for automatic Chart [testing](https://github.com/helm/chart-testing) and [releasing](https://github.com/helm/chart-releaser), and list your Helm repo on https://helm.hub.sh. Follow this issue for info about existing guidelines and upcoming improvements: https://github.com/helm/charts/issues/7800

**Comment by lucky-sideburn** [comment]
https://hub.helm.sh/ :)

Thanks!

**Pull request closed without merging**
