### PR TITLE
[stable/prometheus-operator] Update cert expiration message

### PR DESCRIPTION
**Pull request by madstacks**
Signed-off-by: Daniel Formel <dkfinmv@gmail.com>

#### What this PR does / why we need it:
Update the `KubeClientCertificateExpiration` alert description to more accurately reflect the meaning of the metric. This metric is used to observe the expiration of client certificates used for authentication to the apiserver. It does not mean that the apiserver's server certificate is expiring which can be implied by the existing description.

Note that this metric is also generated by non-apiserver components but this alert limits the scope to `job="apiserver"`.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lachie83** [comment]
cc @gianrubio

**Review by gianrubio — CHANGES_REQUESTED** [review]
Please make a PR here https://github.com/kubernetes-monitoring/kubernetes-mixin/search?q=KubeClientCertificateExpiration&unscoped_q=KubeClientCertificateExpiration and them [sync the rules](https://github.com/helm/charts/tree/dc945c49b44290ab551fe8323b5dc28b0f8a6ed8/stable/prometheus-operator#developing-prometheus-rules-and-grafana-dashboards)

**Comment by madstacks** [comment]
I already did a PR for kubernetes-mixin https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/141 but I will work on syncing the rules. Sorry I should have read the README more carefully as I see this is noted there.

**Comment by paskal** [comment]
@madstacks, I've synced rules in https://github.com/coreos/prometheus-operator/pull/2337 - please wait for it to be merged and then just run scripts from `hack` folder to sync everything.
I suspect that there might be no change at all after that, you seems to have everything right already.

**Comment by paskal** [comment]
Just FYI: for preparing the sync PR I've used instructions from [this comment](https://github.com/coreos/prometheus-operator/pull/2096#issuecomment-436561961).

**Comment by madstacks** [comment]
Thanks @paskal! I forgot to update the runbook so I opened https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/142 to address that.

**Comment by paskal** [comment]
@madstacks, merge in coreos is done - feel free to sync rules there (via hack folder scripts) and rebase this PR based on these changes.

**Pull request closed without merging**
