### PR TITLE
[stable/minio] corrected syntax error in statefulset

### PR DESCRIPTION
**Pull request by capnajax**
#### What this PR does / why we need it:

Syntax error in Statefulset prevented installation from working.

#### Which issue this PR fixes

Syntax error

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

Signed-off-by: Thomas Wilkinson <thomas@capnajax.com>

### CODE REVIEW

**Comment by briend** [comment]
This PR reverts the fix I had submitted previously, 
FYI:
https://stackoverflow.com/questions/17891226/difference-between-and-operators-in-go

The := operator is an assignment and declaration in one. Therefore:

```
{{ $scheme := "http" }}
 {{- if .Values.tls.enabled }}
 {{ $scheme := "https" }}
 {{ end }}
```

If tls is enabled, this will simply declare and assign a new variable "scheme" that only exists until the {{ end }}. ie, it will have zero effect on actually enabling https for minio.

Effectively, scheme is now always "http". If the previous fix broke anything, it is probably because you have enabled tls and there are issues with your certificates. Rather than revert the fix you could simply set tls to disabled or figure out the issues with the certs.

**Comment by macgyver603** [comment]
@krisis the PR @briend is referencing is #21373, which fixed the scoping issue that this PR reintroduced

**Comment by TreeKat71** [comment]
Why it was merged? It seems wrong, and I can't enable TLS successfully.

**Pull request merged**
