### PR TITLE
[stable/rabbit] Add secret to service account

### PR DESCRIPTION
**Pull request by sventschui**
#### What this PR does / why we need it:
This PR adds the secret created in the rabbitmq chart to the service account to allow the pods to be scheduled when the openshift cluster requires this.

ping @desaintmartin

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
Thanks for the PR!!!!
/ok-to-test
/lgtm

**Comment by miguelaeh** [comment]
It seems another change has been merged in master, could you rebase master and resolve the conflicts please?

**Comment by sventschui** [comment]
@miguelaeh done :)

**Comment by davidkarlsen** [comment]
This chart has been deprecated and moved: https://github.com/helm/charts/pull/21310

**Comment by carrodher** [comment]
As this PR was created before the deprecation PR and it seems it's ready to be merged I think we can go ahead and merge it right now, in this way this change will be applied and moved to the new place. BTW, I can't reopen it

**Pull request closed without merging**
