### PR TITLE
[stable/prometheus-operator]: Fix typo in Helm hook

### PR DESCRIPTION
**Pull request by hwoarang**
#### What this PR does / why we need it:
Fix a small typo in Helm crd hook.

Signed-off-by: Markos Chandras <markos@chandras.me>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by hwoarang** [comment]
cc @vsliouniaev @bismarck @gianrubio

**Review by vsliouniaev — APPROVED** [review]

**Comment by hwoarang** [comment]
I had to rebase and bump the chart version again because another commit for operator was merged in the meantime.

**Pull request merged**
