### PR TITLE
[stable/prometheus-operator] allow empty ruleSelector and ruleNamespa…

### PR DESCRIPTION
**Pull request by ghost**
…ceSelector

Currently an empty ruleSelector or ruleNamespaceSelector does not select
all PrometheusRules or Namespaces respectively. Fix the prometheus
template to allow empty ruleSelector and ruleNamespaceSelector.

#### What this PR does / why we need it:
Currently an empty ruleSelector or ruleNamespaceSelector does not select
all PrometheusRules or Namespaces respectively. Fix the prometheus
template to allow empty ruleSelector and ruleNamespaceSelector.

#### Special notes for your reviewer:
@gianrubio By default all ServiceMonitors and PrometheusRules in all namespaces will be selected.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@ntroast The guidelines specify that charts should select their own resources by default, and from what you are saying this chart breaks this requirement : https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#deployments-statefulsets-daemonsets-selectors

**Comment by ntroast** [comment]
@vsliouniaev Sorry, I should have been more clear. By default `ruleSelectorNilUsesHelmValues` and `serviceMonitorSelectorNilUsesHelmValues` are true. This will add a selector to select based on labels just like before. When these values are false then all will be selected in all namespaces. Therefore, this meets the selectors requirement.

**Review by paskal — APPROVED** [review]

**Comment by vsliouniaev** [comment]
Your changes to the description of the behaviour of the namespace selector don't correspond to what is described in the API for prometheus operator. https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#namespaceselector

Also, pretty certain that the behaviour of `nil` and `{}` is equivalent and cannot be distinguished by Helm templating

**Pull request merged**
