### PR TITLE
[stable/postgresql] Update PostgreSQL chart, from PostgreSQL 10 to 11

### PR DESCRIPTION
**Pull request by carrodher**
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>

#### What this PR does / why we need it:

This PR updates the PostgreSQL version used by the chart

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]

**Review by tompizmor — COMMENTED** [review]
/hold

**Comment by tompizmor** [comment]
@carrodher is going to do some more testing with this PR before merging. I am blocking the merge until he finishes.

**Comment by carrodher** [comment]
As explained in the new README section, upgrading PostgreSQL from 10 to 11 will require some manual migration of the data existing in previous deployments, AFAIK there is not an automated way to do it, so is it fine adding this info to the README and bumping a major chart version? cc @juan131 @desaintmartin @prydonius

**Review by juan131 — APPROVED** [review]
Approving these changes

**Pull request merged**
