### PR TITLE
cockroachdb: Update version to 2.1.5

### PR DESCRIPTION
**Pull request by RaduBerinde**
- [x] Chart Version bumped

### CODE REVIEW

**Review by a-robinson — CHANGES_REQUESTED** [review]
You'll have to sign off on your commit to make the automated checks happy - https://github.com/helm/charts/pull/11540/checks?check_run_id=65619662

**Comment by a-robinson** [comment]
Otherwise
/lgtm
/approve

**Comment by RaduBerinde** [comment]
Thanks, updated.

**Pull request merged**
