### PR TITLE
[stable/traefik] Give traefik access to secrets, as in its official repo

### PR DESCRIPTION
**Pull request by kachkaev**
See https://github.com/containous/traefik/commit/ca5bbab20a661b3b3810aeba84f2169322c88fd4

Traefik pod may end up in an error loop otherwise.

### CODE REVIEW

**Comment by kachkaev** [comment]
I'd also like to update traefik from 1.3.1 to 1.3.3 ([released a few days ago](https://github.com/containous/traefik/releases)). Which chart version should that become?

**Comment by kachkaev** [comment]
ping @viglesiasce :–)

**Comment by kachkaev** [comment]
ping @lachie83 @mgoodness @unguiculus :–)

**Comment by krancour** [comment]
LGTM cc @viglesiasce  @lachie83

**Comment by krancour** [comment]
Actually... let's close this in favor for #1485, which includes this fix among other things.

**Pull request closed without merging**
