### PR TITLE
[stable/postgresql] - Fix readme typo

### PR DESCRIPTION
**Pull request by semyont**
* bitnami/influxdb was stated in the upgrade section instead of stable/postgresql

Signed-off-by: Semyon Teplisky <semyon@nostromo.energy>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by dani8art — COMMENTED** [review]
Hi @semyont , thank you so much for your PR, please bump the patch version of the chart

**Comment by semyont** [comment]
Hi @dani8art , did the patch bump...had trouble with rebase..hope it's fixed

**Comment by dani8art** [comment]
Please, sign off the latest commit https://github.com/helm/charts/pull/21256/checks?check_run_id=494817318 DCO bot is complaining about this

**Pull request merged**
