### PR TITLE
Updated values file

### LINKED ISSUE #6669: standard_init_linux.go:178: exec user process caused "no such file or directory
$ kubectl --namespace=default get pods -l "app=fluentd-cloudwatch,release=fluentd-cw"
NAME                                  READY     STATUS             RESTARTS   AGE
fluentd-cw-fluentd-cloudwatch-cw5cm   0/1       CrashLoopBackOff   1          22s
fluentd-cw-fluentd-cloudwatch-zplcp   0/1       Error              2          22s
$ kubectl logs -f fluentd-cw-fluentd-cloudwatch-zplcp
**standard_init_linux.go:178: exec user process caused "no such file or directory**

please help

### PR DESCRIPTION
**Pull request by jicowan**
Updated image to .43 and uncommented extraVars

**What this PR does / why we need it**:
Fixes issues with the chart for fluentd-cloudwatch

**Which issue this PR fixes** : 
fixes #6669

### CODE REVIEW

**Comment by jicowan** [comment]
Contributor license agreement, https://identity.linuxfoundation.org/system/files/clas/signed/cla_individual-a13f7c70803b412228a944376f0ffdb35ce4972e.pdf

**Comment by unguiculus** [comment]
Something went wrong here. Please fix the history.

**Pull request closed without merging**
