### PR TITLE
[stable/prometheus] Add support for volumeBindingMode

### PR DESCRIPTION
**Pull request by jyaworski**
Signed-off-by: Joseph (Jy) Yaworski <jyaworski@carotid.us>

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jyaworski** [comment]
@zanhsieh is there anything else you need from me?

**Comment by zanhsieh** [comment]
@jyaworski 
Nay. I think @gianrubio could take care of LGTM. Thank you for asking.

**Pull request merged**
