### PR TITLE
[incubator/jenkins] introduce development version

### PR DESCRIPTION
**Pull request by maorfr**
#### What this PR does / why we need it:
As chart maintainers, we have been working towards making the stable/jenkins chart follow chart best practices, while attempting to simplify it.
Over time, some breaking changes have been introduced to the chart. As this chart is in major version `0`, the major version was not bumped, which is confusing as the chart is in the `stable` repository.
This has led to some discussions [[1](https://github.com/helm/charts/pull/11960)] around these changes, and we have decided to move active development to the `incubator` repository.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by unguiculus** [comment]
Since there is already a Jenkins chart here, we cannot accept a second one. You are free to host the chart elsewhere and add it to the Helm Hub, though. Thanks.

**Comment by unguiculus** [comment]
I just re-read the description again. The only option I see is deprecating the stable chart. This would allow you to continue in incubator. However, we're kind of hesitant to add new stuff to incubator because we don't really want to host half-baked stuff here. I understand there's lots of problems with the Jenkins chart. Maybe that's would be the way to go then? Anyways, I'd suggest you join the next charts call and we can discuss the issue there.

**Comment by maorfr** [comment]
Hey! Thanks for taking the time :)
See related PR #12891, which "deprecates" the stable chart.

The decision to go to incubator was made in coordination with @viglesiasce, but I will be glad to join the charts call and bring this up.

**Comment by unguiculus** [comment]
Ah, didn't see that one. It would be best to do that in one PR. And make sure the new version in incubator is higher.

**Comment by maorfr** [comment]
Ack

**Comment by maorfr** [comment]
replacement PR is #12935

**Pull request closed without merging**
