### PR TITLE
[stable/kiam] Add deprecation notice

### LINKED ISSUE #16664: [stable/kiam] Migrate chart to uSwitch Helm repository
Following the merge of https://github.com/helm/hub/pull/131 the canonical [kiam](https://github.com/uswitch/kiam) chart is hosted by uSwitch.

* Old chart: https://github.com/helm/charts/tree/master/stable/kiam
* New chart: https://github.com/uswitch/kiam/tree/master/helm/kiam

This issue tracks the migration tasks:

- [x] Add a pre-deprecation notice to the [README](https://github.com/helm/charts/blob/master/stable/kiam/README.md): https://github.com/helm/charts/pull/16668
- [x] Close off open PRs and issues
  - [x] https://github.com/helm/charts/issues/16519
  - [x] https://github.com/helm/charts/issues/15313
  - [x] https://github.com/helm/charts/issues/17276
  - [x] https://github.com/helm/charts/pull/16369
  - [x] https://github.com/helm/charts/pull/16235
  - [x] https://github.com/helm/charts/pull/16561
  - [x] https://github.com/helm/charts/pull/17296
  - [x] https://github.com/helm/charts/pull/17224
  - [x] https://github.com/helm/charts/pull/17786
- [x] Do [official deprecation steps](https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart)

### PR DESCRIPTION
**Pull request by ewbankkit**
#### What this PR does / why we need it:

Deprecation notice for the kiam chart.
This chart has been deprecated in favour of the [uSwitch-hosted Helm chart](https://github.com/uswitch/kiam/tree/master/helm/kiam).

#### Which issue this PR fixes

  - fixes #16664

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- ~[ ] Variables are documented in the README.md~
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by ewbankkit** [comment]
Related:
* https://github.com/helm/charts/pull/16668
* https://github.com/uswitch/kiam/issues/301

**Comment by ewbankkit** [comment]
@viglesiasce Any chance of getting this merged?
Thanks.

**Review by scottrigby — APPROVED** [review]
/lgtm

**Pull request merged**
