### PR TITLE
[stable/mysql] change behavior of ".configurationFiles"

### LINKED ISSUE #12543: [stable/mysql] custom configurationFiles overwrites all default mysql config from container image
**Is this a request for help?**: No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

**Version of Helm and Kubernetes**:

```SHELL
$ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/mysql`

**What happened**:

When using configuration option `configurationFiles` to provide custom mysql configuration, it will overwrite existing mysql configuration introduced by the container image `mysql`:

When NOT using option `configurationFiles`:

```SHELL
mysql@5fbf78194ca6:/etc/mysql/conf.d$ ls -lh
total 12K
-rw-r--r-- 1 root root 43 Dec 29 02:22 docker.cnf
-rw-r--r-- 1 root root  8 Jul  9  2016 mysql.cnf
-rw-r--r-- 1 root root 55 Jul  9  2016 mysqldump.cnf
mysql@5fbf78194ca6:/etc/mysql/conf.d$ cat *
[mysqld]
skip-host-cache
skip-name-resolve
[mysql]
[mysqldump]
quick
quote-names
max_allowed_packet	= 16M
```

When using option `configurationFiles` in configuration like:

```YAML
  configurationFiles:
    tweak_performance.cnf: |-
      [mysqld]
      max_allowed_packet=64M
```

Then only one file is presented within the pod:

```SHELL
# ls -lh /etc/mysql/conf.d/
total 0
lrwxrwxrwx 1 root root 24 Mar 26 15:16 tweak_performance.cnf -> ..data/tweak_performance.cnf
# cat /etc/mysql/conf.d/*
[mysqld]
max_allowed_packet=64M
```

**What you expected to happen**:

It should NOT overwrite existing configuration by using configmap specified from configuration `configurationFIles`. E.g., in my case, it should be like:

```SHELL
# ls -lh /etc/mysql/conf.d/
total 0
lrwxrwxrwx 1 root root 24 Mar 26 15:16 tweak_performanc.cnf -> ..data/tweak_performanc.cnf
-rw-r--r-- 1 root root 43 Dec 29 02:22 docker.cnf
-rw-r--r-- 1 root root  8 Jul  9  2016 mysql.cnf
-rw-r--r-- 1 root root 55 Jul  9  2016 mysqldump.cnf
```

**How to reproduce it** (as minimally and precisely as possible):

Provisioning a release by helm by using following configuration:

```SHELL
```YAML
  configurationFiles:
    tweak_performance.cnf: |-
      [mysqld]
      max_allowed_packet=64M
```

**Anything else we need to know**:

If this is a bug, the fix can be very simple, just need to use `subPath` when mounting custom configuration files within https://github.com/helm/charts/blob/1c7af3905325491c4f17d57989ffa342354f969a/stable/mysql/templates/deployment.yaml#L128-L131

If this works as designed, such behavior should be documented clearly that it will overwrite **ALL** default configuration when using option `configurationFiles`.

### PR DESCRIPTION
**Pull request by shawnzhu**
#### What this PR does / why we need it:

Avoid overwriting all default configuration files when using config option `configurationFiles`

#### Which issue this PR fixes
 - fixes #12543 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by olemarkus** [comment]
/assign
/ok-to-test
Wonder if this should bump the chart to 1.0.0 though

**Comment by olemarkus** [comment]
The one issue I can see with this is that either you don't care about the config, or you want to be very explicit about the config. So I wonder if there should be some option to never use the config provided by the image.

But I agree that it is confusing the way it is now.

**Comment by shawnzhu** [comment]
> The one issue I can see with this is that either you don't care about the config, or you want to be very explicit about the config.

As what I documented in #12543 if the design of `.configurationFiles` is overwriting all config provided by the image, the current implementation works as designed. Then it just needs better document in README.md to clarify that `.configurationFiles` is for overwriting all config provided by the image. (the current default value is `nil` which leaves the designed behavior unclear)

> So I wonder if there should be some option to never use the config provided by the image.

Just using value `""` replacing default value `nil` for `.configurationFiles` (if the designed behavior is overwriting all configuration from the image) :)

**Pull request merged**
