### PR TITLE
kubernetes-dashboard: increase limits/requests memory resources

### PR DESCRIPTION
**Pull request by desaintmartin**
From 50Mi to 100Mi.

Fixes https://github.com/kubernetes/charts/issues/6114

### CODE REVIEW

**Comment by Nodraak** [comment]
ping @kfox1111

**Comment by rjkernick** [comment]
Please increment the version in chart.yaml

**Comment by desaintmartin** [comment]
Done.

**Comment by desaintmartin** [comment]
Rebased and updated version again.

**Comment by kfox1111** [comment]
looks good to me.

**Comment by desaintmartin** [comment]
ping @viglesiasce and @foxish

**Review by Nodraak — APPROVED** [review]

**Comment by desaintmartin** [comment]
Updated documentation as well.

**Comment by desaintmartin** [comment]
Up.

**Pull request merged**
