### PR TITLE
Allow no storage for zookeeper

### PR DESCRIPTION
**Pull request by jamielennox**
In some development environments I don't have a Volume Provisioner and I
don't need to persist zookeeper state as new nodes will synchronize it
from existing nodes.

If .Values.Storage is unset then we should skip mounting an external
storage provider into zookeeper.

Signed-off-by: Jamie Lennox <jlennox@au1.ibm.com>

### CODE REVIEW

**Comment by sameersbn** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@kow3ns mind giving this a glance as well?

**Review by kow3ns — COMMENTED** [review]
This seems unsafe. Why would you want no external storage for a ZooKeeper ensemble?

**Comment by jamielennox** [comment]
I was testing in a hand rolled cluster that didn't have volume support. It was only a dev environment so it was fine to not persist it. I see the point though, not sure if a dev environment like that should be a target.

**Pull request closed without merging**
