### PR TITLE
[stable/locust] Add Ingress template and Update Application version to 0.13.2

### PR DESCRIPTION
**Pull request by dellwon**
#### What this PR does / why we need it:
Add Ingress template for TLS

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by dellwon** [comment]
/assign @sekka1
/assign @haugene

Please, My PR Review for Helm Locust

**Comment by dellwon** [comment]
@haugene
I don't know what problems. plz, can you give me some hints?

**Comment by haugene** [comment]
@dellwon I'm actually not sure. We get the same error on multiple PRs so I don't think it's a specific problem related to yours. Have you clicked the details link and viewed the raw log?
I've searched it for "error" and it's one error I'm seeing also here when installing with Helm2: `Error: transport is closing`.
It might be related but it's not the one that fails the build I think. Later when uninstalling we get:
```
I0428 05:02:27.874] Deleting release 'locust-ehi32lnala'...
I0428 05:02:29.128] release "locust-ehi32lnala" deleted
I0428 05:02:29.148] Deleting namespace 'locust-presubmit-21596-1254998684911800320-ehi32lnala'...
I0428 05:02:29.765] namespace "locust-presubmit-21596-1254998684911800320-ehi32lnala" deleted
I0428 05:03:12.652] Namespace 'locust-presubmit-21596-1254998684911800320-ehi32lnala' terminated.
I0428 05:03:12.652] Error linting and installing charts: Error processing charts
I0428 05:03:12.653] ------------------------------------------------------------------------------------------------------------------------
I0428 05:03:12.653]  âœ–ï¸Ž locust => (version: "1.1.4", path: "stable/locust") > Error waiting for process: exit status 1
I0428 05:03:12.653] ------------------------------------------------------------------------------------------------------------------------
I0428 05:03:21.797] 5ed5aaacbc87a463fd10fdc556deb22ad294c0af6fa1b9199f9f9db4be273fdb
W0428 05:03:21.884] Traceback (most recent call last):
W0428 05:03:21.885]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0428 05:03:21.886]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0428 05:03:21.886]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0428 05:03:21.888]     check(*cmd)
W0428 05:03:21.889]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0428 05:03:21.889]     subprocess.check_call(cmd)
W0428 05:03:21.889]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0428 05:03:21.889]     raise CalledProcessError(retcode, cmd)
W0428 05:03:21.889] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0428 05:03:21.890] Command failed
I0428 05:03:21.890] process 627 exited with code 1 after 2.5m
E0428 05:03:21.890] FAIL: pull-charts-e2e
```

**Comment by haugene** [comment]
Hi again @dellwon. #22186 was just merged and it has fixed the e2e errors.
Rebase your branch against the new version on master and I think the tests should work again. If you could squash your commits as well that would be great 👍

**Comment by dellwon** [comment]
Hi~! @haugene 
I was checked it and resolve conflict. 
Thank you for your kindness.

**Comment by haugene** [comment]
Great, I'll have a look at this and do some testing before merging. A bit hectic these days but I'll try to find time by next week. In the meantime, it's great that you bumped the appVersion as it was really old. I've recently built new images and it could now be [updated to 0.14.5 as well](https://hub.docker.com/r/greenbirdit/locust/tags?page=1&name=0.14). Can you bump that as well and I'll be back for merging this later 😄

**Comment by mfcrocker** [comment]
@haugene It's worth noting that between 0.13.2 and 0.14.6 (another point version since 6 hours ago 😄 ), the environment variables have been changed, so if you want to bump that far you'll need to change `LOCUST_MASTER` to `LOCUST_MASTER_NODE_HOST`

**Comment by dellwon** [comment]
@haugene
Thanks~!
I was test it for version 0.14.5. but It's not working. 
Master node can't find Slave nodes. (Error: " You are running in distributed mode but have no slave servers connected. Please connect slaves prior to swarming.")
I don't know other ENV and don't know where located dockerfile. so I can't test anymore. (@mfcrocker , thanks, your comment is very useful)

If you give some info. about 0.14.5, I will update and test it. 
And...
I will planning to update "git-sync" version. Because "configmap" not support recursive folder.
So we update test file from git to "locust_tasks" volume. (It was checked in 0.13.2)

**Pull request closed without merging**
