### PR TITLE
[stable][sentry] Allow usage of existing secrets for sensitive data 

### PR DESCRIPTION
**Pull request by sfrique**
#### What this PR does / why we need it:
This enable the user to provide an already created secret for sensitive data. This is useful when using gitops and everything is committed.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by stephenmoloney** [comment]
What is the benefit of using multiple secret files instead of just one `existingSecret`?

I have an open PR for just using one `existingSecret` - https://github.com/helm/charts/pull/10144

**Comment by sfrique** [comment]
> What is the benefit of using multiple secret files instead of just one `existingSecret`?
> 
> I have an open PR for just using one `existingSecret` - #10144

Just to be able to selective enable which service is already created. 

Depending on what tool you have to create secrets, it may be best to have is separated.

Currently we are using only `userSecret` for all envs and `emailSecret` for just a few. 

I just think it gives more flexibility and since I was doing one, I did for the rest as well.

Sorry, I didn't find your PR before. The Reduce boilerplate code seems cool, I didn't look much to see if it could cause other problems, but it seemed to simplify quite a lot the chart.

**Pull request closed without merging**
