### PR TITLE
[stable/sentry] bump sentry, dependency charts, add configmap

### PR DESCRIPTION
**Pull request by kimxogus**
**What this PR does / why we need it**:
1. Sentry 9.0
2. Latest dependency chart updates (postgres, redis) and supports existing secret for passwords
3. Add configmap for custom configurations
4. Add pod annotations (In my case, I need this for s3 filestore with kube2iam)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ekampf** [comment]
Any progress here?

**Comment by kimxogus** [comment]
@davidkarlsen rebased to master

**Pull request merged**
