### PR TITLE
fix typo in opencart readme

### PR DESCRIPTION
**Pull request by scf0920**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by carrodher** [comment]
LGTM
/assign @prydonius

**Comment by carrodher** [comment]
Hi @scf0920, can you take a look at the conflicts? If you resolve it, the PR is ready to be merged

**Comment by scf0920** [comment]
@carrodher This conflict has already resolved.Thanks :)

**Pull request merged**
