### PR TITLE
[stable/postgresql]: add pods replace strategy support

### LINKED ISSUE #6066: [stable/postgresql] Fundamental Problems with Volumes and Helm
**Version of Helm and Kubernetes**:

**Which chart**:

`stable/postgresql`

**What happened**:

1. `helm --wait` does not work. 
2. `helm upgrade` fails with persistent volumes (and `--recreate-pods`)

**What you expected to happen**:

1. `helm --wait` should wait until postgres has successfully started
2. `helm upgrade` should not fail when redeploying database with persistent volumes

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

The `--wait` problem appears to be related to the following:
- <https://github.com/kubernetes/charts/blob/master/stable/postgresql/templates/deployment.yaml#L1>
- <https://github.com/kubernetes/helm/issues/3173#issuecomment-390321075>

The `upgrade` problem is probably related to using `Deployment` (as opposed to a `StatefulSet`), because it doesn't explicitly define an update strategy of `.spec.strategy.type==Recreate`. The default strategy is `RollingUpdate` which will always fail with persistent volumes.

- <https://kubernetes.io/cn/docs/concepts/workloads/controllers/deployment/#strategy>

### PR DESCRIPTION
**Pull request by alebabai**
**What this PR does / why we need it**: add pods replace strategy support

**Which issue this PR fixes** : #6066 `.spec.strategy.type==Recreate` fixes issue with `--wait` flag

### CODE REVIEW

**Comment by osterman** [comment]
@sameersbn could you take a quick peek at this PR? It's very low risk, backwards compatible and addresses a problem we're experiencing with a number of clients.

Thanks!!

**Comment by alebabai** [comment]
@unguiculus i fixed the testx (bump chart version again). Could you look into this, please?

**Pull request merged**
