### PR TITLE
[stable/keycloak] Deprecate chart after moving to new repo

### PR DESCRIPTION
**Pull request by unguiculus**
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
👍 See https://github.com/helm/hub/pull/66

**Comment by melissapalmer** [comment]
Is it possible to share the reasoning behind moving this chart to a different repo.? Thanks in Advance

**Comment by unguiculus** [comment]
@melissapalmer Sorry for the late response. I hadn't noticed your comment.

The chart was moved because we as maintainers of the chart had decided we wanted to host it in our own repository listed on the Helm Hub.

Additionally—and this is me speaking as a Helm org and charts maintainer—we want to drive adoption of the Helm Hub and would like folks to host their charts on their own and list them there. So, naturally, we went ahead with this.

**Pull request merged**
