### PR TITLE
[stable/dex] Add support of affinity and PodDisruptionBudget

### PR DESCRIPTION
**Pull request by legal90**
#### What this PR does / why we need it:
This PR adds values to support pod affinity / anti-affinity and PodDisruptionBudget for dex pods.
That allows to make dex installation more robust and tolerant to possible disruptions.

Default values are empty, so changes introduced here are backward-compatible.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] ~Variables are documented in the README.md~ _The chart is missing the entire `README.md`. I guess, it should be added in the scope of a separate PR_.

### CODE REVIEW

**Comment by legal90** [comment]
@prydonius Could you please take a look at this PR? Thanks!

**Comment by mattfarina** [comment]
/ok-to-test

Because it adds features the the current chart version was 1.0.0 I incremented the chart to 1.1.0 to keep with semver

**Pull request merged**
