### PR TITLE
[incubator/gogs] #1785 namespace defined templates with chart name

### PR DESCRIPTION
**Pull request by kevinschumacher**
#1785

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@kevinschumacher please fix the ci error
```
I0824 04:28:00.532] [ERROR] templates/: parse error in "gogs/templates/_helpers.tpl": template: gogs/templates/_helpers.tpl:2: template: multiple definition of template "gogs.fullname"
```

**Comment by kevinschumacher** [comment]
/retest

Sorry about delay on this. Busy at work, then busy on vacation!

**Comment by kevinschumacher** [comment]
conflict resolved

**Comment by dhilipkumars** [comment]
@kevinschumacher Apologies for the delay in responding.

**Pull request merged**
