### PR TITLE
[stable/sentry] Update environment variables mapping in configmap

### PR DESCRIPTION
**Pull request by ahmagdy**
## Update environment variables mapping in configmap
* Update configmap yaml file to match the latest version from Sentry.
* Include Google Client ID and secret in mapping to let sentry reading it, because it was not mapped.
* Bump Sentry from 9.1.1 to 9.1.2, No Breaking changes.
* Bump chart version.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by okgolove** [comment]
Hi @Ahmad-Magdy. Thank you for the PR.
Please, sign your commits.

**Comment by Ahmad-Magdy** [comment]
Hi @okgolove 
It's signed now, can you check my changes?

**Pull request merged**
