### PR TITLE
[helm/charts] Add gitwebhookproxy

### PR DESCRIPTION
**Pull request by faizanahmad055**
Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
- [Gitwebhookproxy](https://github.com/stakater/GitWebhookProxy) an opensource tool maintained by [Stakater](https://github.com/stakater)
- Gitwebhookproxy is a proxy to let webhooks to reach a Jenkins instance running behind a firewall

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by faizanahmad055** [comment]
Hi @scottrigby, @prydonius
Can you guys take a look?

**Comment by faizanahmad055** [comment]
Hi @scottrigby, @prydonius
Ping

**Comment by faizanahmad055** [comment]
Hi @scottrigby, @prydonius
Ping

**Comment by faizanahmad055** [comment]
Hey @scottrigby, @prydonius
Can anyone of you guys take a look?

**Comment by faizanahmad055** [comment]
Hello @scottrigby, @prydonius
Any update on this, please

**Comment by scottrigby** [comment]
Hi @faizanahmad055 - see https://github.com/helm/charts/pull/10024#issuecomment-452743703 and https://github.com/helm/charts/pull/10024#issuecomment-452745339 (you can comment there, but it also applies to this PR).

**Comment by faizanahmad055** [comment]
Hi @scottrigby,
I think the new approach is good. We are preparing our public repository so it can be searchable at hub.helm.sh.

**Pull request closed without merging**
