### PR TITLE
[stable/openldap] Fix helm3 ClusterIP updates

### LINKED ISSUE #20904: [stable/openldap] Helm3 fails with "ClusterIP is immutable" error
**Describe the bug**
When updating the release with helm3 it throws an error about ClusterIP not being mutable.

**Version of Helm and Kubernetes**:
```
$  helm version  
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```
```
$  kubectl version           
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
`stable/openldap`

**What happened**:
When updating the release with helm3 it throws:
```
Error: UPGRADE FAILED: cannot patch "ldap-openldap" with kind Service: Service "ldap-openldap" is invalid: spec.clusterIP: Invalid value: "": field is immutable: cannot patch "ldap-openldap" with kind Service: Service "ldap-openldap" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**:
Upgrade goes without issues because the field was not actually mutated

**How to reproduce it** (as minimally and precisely as possible):
`helm install ldap stable/openldap`

`helm upgrade ldap stable/openldap --set replicaCount=2`

**Anything else we need to know**:
I will provide the PR with solution.

### PR DESCRIPTION
**Pull request by Morishiri**
#### Is this a new chart
No

#### What this PR does / why we need it:
#20904

#### Which issue this PR fixes
  - fixes #20904

#### Special notes for your reviewer:
N/A
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by rpocase** [comment]
Would supersede #19428 if this is merged.

**Comment by Morishiri** [comment]
remove stale

**Comment by Morishiri** [comment]
not stale

**Comment by zanhsieh** [comment]
@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr
Would you guys LGTM this PR please? Thank you.

**Pull request merged**
