### PR TITLE
fix URIs in comments

### PR DESCRIPTION
**Pull request by tamsky**
Signed-off-by: Marc Tamsky [tamsky@users.noreply.github.com](mailto:tamsky@users.noreply.github.com)
#### What this PR does / why we need it:

fixes broken links in #comments

### CODE REVIEW

**Comment by cpanato** [comment]
@tamsky please bump the chart version

**Review by jonninen50 — APPROVED** [review]

**Comment by tamsky** [comment]
> @tamsky please bump the chart version

Bumped.

**Comment by paulczar** [comment]
please rebase or otherwise resolve the merge conflicts.

/ok-to-test

**Comment by tamsky** [comment]
@paulczar - rebased, no merge conflicts at this time.

**Review by cpanato — APPROVED** [review]

**Pull request merged**
