### PR TITLE
Typo fix in couchdb/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
a small typo in line 72

### CODE REVIEW

**Review by timstoop — APPROVED** [review]
Looks fine.

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
@kocolosk Do you know why this would be failing to start? See the details on the failed test run for more info.

**Comment by mattfarina** [comment]
/retest

Going to retest again now that #4278 has landed to try and get more details.

**Comment by kocolosk** [comment]
One of the containers in the Pod expects to find the SRV records for the members of the StatefulSet so it can join up the cluster members. It does a bounded exponential backoff and retry if it gets an NXDOMAIN back, but gives up after 10 tries. Looking at the logs that seems to be what happened here.

**Comment by kocolosk** [comment]
These lines also seem worrisome:

> I0317 00:23:42.246] chown: changing ownership of '/opt/couchdb/etc/default.d': Read-only file system

**Comment by kocolosk** [comment]
Clearly still busted ... we did make some changes regarding configuration directories in apache/couchdb-docker#50 a few months back, perhaps that has something to do with the `chown` permissions error. Will dig into it.

**Comment by kocolosk** [comment]
As far as I can tell those changes should not have any effect here. The chart is using the official 2.1.1 image and that image tag [has not moved since November](https://github.com/docker-library/official-images/blob/master/library/couchdb).

**Comment by AdamDang** [comment]
@kocolosk @mattfarina 
Thanks a lot for your attention.  I'd better close this PR before this problem solved.

**Pull request closed without merging**
