### PR TITLE
Typo fix in cockroachdb/README.md

### PR DESCRIPTION
**Pull request by AdamDang**
line 32: tables lists->table lists 
There are many such errors in stable directory.

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
Thanks @AdamDang! Could you please squash your two commits together? The version bump is meant to happen in the same commit to avoid leaving broken commits in the history.

**Comment by AdamDang** [comment]
Hi @a-robinson Thanks a lot for your attention.
I used to put 6 charts commits together, but I was told it's better separate them one by one. 
@unguiculus said in PR#4147
"Thanks for the effort. In general, we want separate PRs per chart. Would you mind splitting this up?"
So please can you process it with current status?

**Comment by AdamDang** [comment]
I guess that it maybe make building or testing complex and difficult for errors debugging, does it?

**Comment by a-robinson** [comment]
> I used to put 6 charts commits together, but I was told it's better separate them one by one.
> @unguiculus said in PR#4147
> "Thanks for the effort. In general, we want separate PRs per chart. Would you mind splitting this up?"
> So please can you process it with current status?

That's referring to not modifying multiple charts in the same PR. I'm asking you to combine the two changes in this PR into a single commit, because the version change logically belongs grouped together with the typo fix (and they're both modifying the same chart).

**Comment by AdamDang** [comment]
Hi @a-robinson, Thanks for your patience.
I'm a little confused. I modified two files in this PR: 
 Chart.YAML  Version changed  from 6.6.6 to 6.6.7
 README.md  Typo fix
the two commits are in same PR.
So what should I do further?
I really can not find any difference between this PR and other similar PRs I created in Charts project.

**Comment by sameersbn** [comment]
the PR will be squashed and merged so it really does not matter.

/ok-to-test
/lgtm

**Pull request merged**
