### PR TITLE
Used  argument defined in tcp and udp for targetPorts

### PR DESCRIPTION
**Pull request by djs28**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by djs28** [comment]
@drnic @ChiefAlexander is there anything else needed to be done on this? It would be good to get this in :)

**Comment by zanhsieh** [comment]
@djs28 
You need to bump chart version to the latest; otherwise checks on the bottom of this pages won't run and the OWNER of chart won't approve your PR.

**Comment by ChiefAlexander** [comment]
I am not sure what we are trying to accomplish with this pr... These target ports match what is set in the deployment/daemonset. Thus this change would break the service.
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L177
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-daemonset.yaml#L173

**Pull request closed without merging**
