### PR TITLE
[stable/sealed-secrets] Have optional command args passed to controller

### LINKED ISSUE #17556: [stable/sealed-secrets] Have optional command args passed to controller
**Is your feature request related to a problem? Please describe.**
As the default value for "--key-renew-period" changed in recent Sealed Secrets releases, I need some way to pass this command line option to the controller process (actually to keep automatic key rotation disabled in my current environment).

**Describe the solution you'd like**
The referenced patch enables us to pass arbitrary command line arguments to the controller process.

**Describe alternatives you've considered**
Different people need different options here, so it doesn't make sense to hard-code another command line option, like we have with "--key-prefix".

**Additional context**

### PR DESCRIPTION
**Pull request by k0ffee**
This enables us to set command line arguments, like
  commandArgs:
    - "--key-renew-period"
    - "0"
or:
  $ helm ... --set commandArgs={--key-renew-period,0}

Signed-off-by: Tino Reinhardt <t@freeshell.org>

#### Is this a new chart
no

#### What this PR does / why we need it:
As the default value for "--key-renew-period" changed in recent Sealed Secrets releases, I need some way to pass this command line option to the controller process (actually to keep automatic key rotation disabled in my current environment).

#### Which issue this PR fixes
  - fixes #17556

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by k0ffee** [comment]
@stefanprodan done.

**Comment by stefanprodan** [comment]
@k0ffee can you also please update the app version and container image to https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.9.1

**Comment by k0ffee** [comment]
@stefanprodan Also done. Thanks.

**Review by stefanprodan — APPROVED** [review]
/lgtm

**Pull request merged**
