### PR TITLE
[stable/neo4j] Discover members of cluster in the release namespace

### PR DESCRIPTION
**Pull request by Sudmota**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by unguiculus** [comment]
@Sudmota There's a problem with the test. I guess @mneedham needs to look at this.

**Comment by mneedham** [comment]
The test uses the default namespace. I've updated that in https://github.com/kubernetes/charts/pull/3047

**Comment by mneedham** [comment]
@Sudmota #3047 is merged into master and should hopefully have the functionality that you implemented in this PR.

**Comment by mneedham** [comment]
@unguiculus I think we can close this one as well.

**Comment by Sudmota** [comment]
Confirmed that changes are merged into master. Closing this PR. Thank you for all the help

**Pull request closed without merging**
