### PR TITLE
Update NOTES.txt

### PR DESCRIPTION
**Pull request by sordina**
Chart is wrong instructions.

Should add `-master` to name instructions.

### CODE REVIEW

**Comment by zanhsieh** [comment]
@sordina 
Could you sign DCO and bump the chart version to latest? Thank you.

**Comment by juan131** [comment]
Hi @sordina 

As @zanhsieh mentioned it's mandatory to sign the DCO and bump the version. Otherwise the CI will fail.

**Comment by sordina** [comment]
@juan131  hi, how do I sign the DCO? I don't really want to invest a lot of time for a simple documentation change but I'll do it if it's simple enough

**Comment by zanhsieh** [comment]
@sordina 
https://github.com/helm/charts/pull/17691/checks?check_run_id=247525090

**Comment by sordina** [comment]
tada

**Comment by zanhsieh** [comment]
@sordina 
Great!!

Also what we mean by "bump to Chart version to the latest" is to change:
https://github.com/helm/charts/blob/master/stable/redis/Chart.yaml#L3
from `9.2.2` to `9.2.3` and amend to your commit. Please do so so we can continue.

Thanks a lot.

**Comment by sordina** [comment]
@zanhsieh is it okay to merge now? I've bumped the version and redone the DCO

**Review by juan131 — APPROVED** [review]
/lgtm

**Pull request merged**
