### PR TITLE
[stable/anchore-engine] Update apiVersion for ingress

### PR DESCRIPTION
**Pull request by cityofships**
Signed-off-by: Piotr Parczewski <piotr.parczewski@nokia.com>

#### Is this a new chart
No

#### What this PR does / why we need it:

Start using new K8s networking API (as per https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). This saves the effort later when K8s v1.22 is released (but also effectively breaks deployment with ingress on clusters older than v1.14).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by zhill** [comment]
thanks @cityofships ! We'll take a look

**Comment by Btodhunter** [comment]
@cityofships Sorry - I should've merged this before doing the latest update. Can you fix the Chart version so there are no merge conflicts? Then I can approve this PR.

**Comment by cityofships** [comment]
certainly

**Comment by cityofships** [comment]
ping @Btodhunter

**Comment by cityofships** [comment]
another version conflict

**Pull request merged**
