### PR TITLE
[stable/traefik] Use kvprovider prefix in storage path

### LINKED ISSUE #11265: [stable/traefik] Kvprovider Prefix Not Respected By ACME Storage Path
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes: `Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
helm: `Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}`

**Which chart**:
stable/traefik

**What happened**:
I switched to using Consul for storing the ACME certificates, in an effort to be able to run traefik in cluster mode.

Traefik started up correctly, got some certificates, and seemed to work fine. I decided to take a look in consul, and found that it had created both a `traefik-private` prefix (which I specified in the helm values) but also a `traefik` prefix. The `traefik-private` prefix contained most of the keys, but the ACME certificates seems to be stored under the `traefik` prefix.

Consul (`/`):
image

Consul (`/traefik-private/`, my configured prefix):
image

Consul (`/traefik-private/acme/`, notice missing `account`):
image

Consul (`/traefik/`):
image

Consul (`/traefik/acme/account/`):
image

**What you expected to happen**:
I expected ALL keys created in Consul to be under my configured consul prefix. I intend to run multiple traefik ingress controllers on the same consul backend, currently I will be forced to share the same certificate storage for multiple completely different deployments of traefik.

**How to reproduce it** (as minimally and precisely as possible):
1. Set up Consul Cluster
2. Set up Traefik with values:
```
acme:
  challengeType: <your challenge type>
  email: <your LetsEncrypt email>
  enabled: true
kvprovider:
  consul:
    endpoint: <your consul hostname>:8500
    prefix: traefik-private #or your own preferred prefix
    watch: true
  storeAcme: true
```
3. Issue some certificates
4. Look in consul and see that 2 different prefixes have been created.

**Anything else we need to know**:
It seems to be due to https://github.com/helm/charts/blob/ae4e119ce28a642cd33466c51ea43cd1fbec1a44/stable/traefik/templates/configmap.yaml#L234 not being affected by my consul prefix configuration.

### PR DESCRIPTION
**Pull request by FrederikNJS**
#### What this PR does / why we need it:
The acme `storage` configuration was previously hardcoded. When using
multiple traefik installations, sharing the same kvprovider backend, but different prefixes,
they would all write their certificates to the same location. This
change makes the `storage` configuration conform to the `prefix`
configured for the kvprovider.

#### Which issue this PR fixes
Fixes #11265

#### Special notes for your reviewer:
If a user had previously configured a kvprovider with acme, and a custom prefix, the location of the certificates in the kvprovider will change. The user can of course just copy the kv entry to the new location, but we run the risk of re-requesting all certificates.

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by ncsibra** [comment]
Hi, I would love to see this merged and released. :)

**Comment by phroggyy** [comment]
I would like to point out that this change can cause problems for some users – if users are running one traefik cluster per namespace (a setup we're about to move to for dev), and use a shared kv store, it might actually be _desired_ to have the certs shared. You'd naturally want the config per namespace/cluster (we're making this change to make it easier to test new traefik configuration in your own namespace), but might want to use an existing cert, e.g a wildcard cert.

I propose adding a separate `acmeStoragePath` value so people _can_ maintain the behaviour if desired.

**Comment by FrederikNS** [comment]
@phroggyy I went ahead and implemented the change you suggested, but decided on the name `acmePrefix`, to align with the normal `prefix` variable

I still don't really understand your use-case though. For it to make sense for two traefik installations to share their certificate storage, they would have to be serving the same (sub)domains. Do you serve a single (sub)domain out of multiple namespaces?

**Comment by phroggyy** [comment]
@FrederikNS not if you're using a wildcard cert. if you're serving `dev1.example.com` and `dev2.example.com` you might want to be using `*.example.com`

**Comment by FrederikNS** [comment]
That makes sense. I have never used wildcards with Traefik, so I didn't consider that option.

But this solution with `acmePrefix` would accomodate that, correct?

**Comment by phroggyy** [comment]
Indeed it would

**Comment by FrederikNS** [comment]
Still waiting for a review...

**Comment by dtomcej** [comment]
@FrederikNS, This looks good,

Can you add the `acmePrefix` into the values.yaml (commented out?)

Thanks!

**Pull request closed without merging**
