### PR TITLE
[stable/metabase] add namespace argument to all templates

### PR DESCRIPTION
**Pull request by jukecraft**
## What this PR does / why we need it:
Currently, the namespace is not automatically added to templates, even if Helm is called with the `--namespace` attribute. This seems to be intended by Helm: https://github.com/helm/helm/issues/3553

Other charts have also done this for their templates, for example: https://github.com/helm/charts/pull/17712

#### Special notes for your reviewer:
FYI the PR template includes this defunct link https://github.com/helm/helm/tree/master/docs/chart_best_practices

Haven't tested locally since I'm not sure how. I'm not the original author of the chart. @pmint93 thank you for the chart, could you take a look at this potential improvement?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jukecraft** [comment]
FYI the PR template includes this defunct link https://github.com/helm/helm/tree/master/docs/chart_best_practices

**Comment by pmint93** [comment]
@jukecraft Can you please resolve the current conflict, so that the test can run

**Comment by jukecraft** [comment]
thank you!

**Pull request merged**
