### PR TITLE
[stable/concourse] Update flags for 5.2

### PR DESCRIPTION
**Pull request by cirocosta**
#### What this PR does / why we need it:

There's a new version of Concourse being prepared! This PR is about continuously adding the necessary flags to make it happen with Helm as well.

Once the next version ships, we can then promote this PR to non-draft.

So far, new configurations:
- [ability to configure the Concourse cluster name](https://github.com/concourse/concourse/pull/3736)
- [cacheing of secret lookups](https://github.com/concourse/concourse/pull/3628)
- [auditing of user actions](https://github.com/concourse/concourse/pull/3577)
- [time-based retention for the build collector](https://github.com/concourse/concourse/pull/3560)

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mattfarina** [comment]
cc @cirocosta @william-tran

**Comment by cirocosta** [comment]
https://github.com/concourse/concourse/releases/tag/v5.2.0 🙌

**Comment by cirocosta** [comment]
cc @william-tran

**Comment by paroxp** [comment]
_ship it, ship it, ship it_ :D

Thanks @cirocosta !

**Comment by cirocosta** [comment]
cc @mattfarina @cpanato

**Review by cpanato — APPROVED** [review]

**Pull request merged**
