### PR TITLE
[stable/traefik] Add support for tls-alpn-01 ACME challenge

### PR DESCRIPTION
**Pull request by Starefossen**
#### What this PR does / why we need it:

Add support for the new and recommended [TLS-ALPN-01](https://github.com/containous/traefik/blob/master/docs/configuration/api.md#tlschallenge) ACME challenge type.

#### Which issue this PR fixes

containous/traefik#3553

#### Special notes for your reviewer:

I suggest we should consider setting this as the new default for `acme.challengeType` and thus bumping the chart version to `v2.0.0` since this would be considered as a breaking change. 

Some what related I suggest we set `acme.staging` to `false` as default as well.

/cc @Juliens, @dtomcej, @cpanato 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by dtomcej** [comment]
>I suggest we should consider setting this as the new default for acme.challengeType and thus bumping the chart version to v2.0.0 since this would be considered as a breaking change.

There are lots of little updates that we would want to aggregate in the v2 chart. This will most likely happen with the next major Traefik release.

>Some what related I suggest we set acme.staging to false as default as well.

I disagree. Having staging enabled by default can prevent people from getting rate limited while they test their infra setup after installing the chart.

**Comment by Starefossen** [comment]
> > I suggest we should consider setting this as the new default for acme.challengeType and thus bumping the chart version to v2.0.0 since this would be considered as a breaking change.

> There are lots of little updates that we would want to aggregate in the v2 chart. This will most likely happen with the next major Traefik release.

Do you mean Træfik v2.0.0? I don't see that coming any time soon, but then again I don't have any inside information about the release schedule of Træfik. But for each release of Træfik where this chart deviates from the recommended best practice it makes it harder for (new) people and requires a lot of extra config to get going. Just my two cents.  

>> Some what related I suggest we set acme.staging to false as default as well.

> I disagree. Having staging enabled by default can prevent people from getting rate limited while they test their infra setup after installing the chart.

I see your point. Maybe we could add something to the documentation about this then 🙂

**Pull request merged**
