### PR TITLE
[stable/traefik] Add more options for Prometheus Service

### PR DESCRIPTION
**Pull request by lawliet89**
Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

#### What this PR does / why we need it:

- Fix lack of options for the Prometheus service

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by lawliet89** [comment]
@ldez @mmatur could I get some eyes on this PR please.

**Comment by lawliet89** [comment]
Hey @cpanato could I get this merged in please?

**Comment by valerauko** [comment]
Would incorporating https://github.com/containous/traefik-helm-chart/issues/46 be too much for one PR?

**Comment by lawliet89** [comment]
@valerauko  do you mean adding `prometheus.io/scrape: "true"` annotation by default?

**Comment by lawliet89** [comment]
Not stale. And still awaiting for review.

**Comment by cpanato** [comment]
@lawliet89 please rebase your PR and fix the conflicts, thanks!

**Comment by lawliet89** [comment]
```
 I0403 08:12:25.500] Error: incompatible versions client[v2.16.5] server[v2.15.2]
I0403 08:12:25.500] ========================================================================================================================
I0403 08:12:25.500] ........................................................................................................................
I0403 08:12:25.501] ==> Events of namespace traefik-presubmit-19827-1245987251704303618-n3bsqaada5
I0403 08:12:25.501] ........................................................................................................................
I0403 08:12:25.782] No resources found in traefik-presubmit-19827-1245987251704303618-n3bsqaada5 namespace.
I0403 08:12:25.782] ........................................................................................................................
I0403 08:12:25.782] <== Events of namespace traefik-presubmit-19827-1245987251704303618-n3bsqaada5
I0403 08:12:25.782] ........................................................................................................................
I0403 08:12:26.065] ========================================================================================================================
I0403 08:12:26.065] Deleting release 'traefik-n3bsqaada5'...
I0403 08:12:26.651] Error: incompatible versions client[v2.16.5] server[v2.15.2]
I0403 08:12:26.651] Error deleting Helm release: Error waiting for process: exit status 1
I0403 08:12:26.651] Deleting namespace 'traefik-presubmit-19827-1245987251704303618-n3bsqaada5'...
I0403 08:12:26.929] Error from server (NotFound): namespaces "traefik-presubmit-19827-1245987251704303618-n3bsqaada5" not found
I0403 08:12:26.929] Namespace 'traefik-presubmit-19827-1245987251704303618-n3bsqaada5' did not terminate after 180s.
I0403 08:12:27.213] Namespace 'traefik-presubmit-19827-1245987251704303618-n3bsqaada5' terminated.
I0403 08:12:27.213] Error linting and installing charts: Error processing charts
I0403 08:12:27.213] ------------------------------------------------------------------------------------------------------------------------
I0403 08:12:27.214]  ✖︎ traefik => (version: "1.87.0", path: "stable/traefik") > Error waiting for process: exit status 1
I0403 08:12:27.214] ------------------------------------------------------------------------------------------------------------------------
I0403 08:12:27.787] 1cc2afe363db390d41a9a7837697a5bf8b798ec9e26fbf8b364caafc45f27286
W0403 08:12:27.806] Traceback (most recent call last):
W0403 08:12:27.806]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0403 08:12:27.806]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0403 08:12:27.807]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0403 08:12:27.807]     check(*cmd)
W0403 08:12:27.807]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0403 08:12:27.807]     subprocess.check_call(cmd)
W0403 08:12:27.807]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0403 08:12:27.807]     raise CalledProcessError(retcode, cmd)
W0403 08:12:27.807] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1 
```

Not sure what I can do about the tests failing.

**Comment by lawliet89** [comment]
Still alive.

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Comment by valerauko** [comment]
Awesome, thanks!

**Pull request merged**
