### PR TITLE
Updated Keycloak helm chart to keycloak v4.4.0.Final.

### PR DESCRIPTION
**Pull request by edclement**
Signed-off-by: Ed Clement <ed.clement@gmail.com>

**What this PR does / why we need it**:
Updates the helm chart for keycloak to use the latest keycloak version (v4.4.0.Final). This PR also updates the configmap to handle the new default entry point for the docker keycloak image.

**Which issue this PR fixes** 
N/A

**Special notes for your reviewer**:
N/A

### CODE REVIEW

**Comment by unguiculus** [comment]
The CI job erroneously reports success. There's an issue with the chart-testing lib which I'll provide a fix for soon.

The update to 4.4.0 seems to require further changes.

/hold

**Comment by edclement** [comment]
@unguiculus 
> The update to 4.4.0 seems to require further changes.

I looked through the CI output and didn't see any issues. Anything I need to do? I've tested/deployed the chart with versions 4.3.0 and 4.4.0.

**Comment by edclement** [comment]
@unguiculus
> Did you deploy a cluster?
I did not.... Testing now using multiple nodes. Keycloak really needs to start using semantic versioning. By the way, which of the links at the bottom provide the log output you posted?

**Comment by edclement** [comment]
Looks like how clustering is handled using JDBC_PING changed significantly. I removed line 134 from the `values.yaml` file:

`  /subsystem=jgroups/stack=tcp/protocol=JDBC_PING/property=clear_table_on_view_change:add(value=true)`

...just to see if that would correct the problem. It allows keycloak to start but the following deprecation warnings are output: 
```
12:09:58,496 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0395: Operation add against the resource at address /subsystem=jgroups/stack=tcp/protocol=org.jgroups.protocols.JDBC_PING/property=datasource_jndi_name is deprecated, and it might be removed in future version. See the the output of the read-operation-description operation to learn more about the deprecation.
12:09:58,627 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0395: Operation add against the resource at address /subsystem=jgroups/stack=tcp/protocol=org.jgroups.protocols.JDBC_PING/property=break_on_coord_rsp is deprecated, and it might be removed in future version. See the the output of the read-operation-description operation to learn more about the deprecation.
12:09:58,714 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0028: Attribute 'socket-binding' in the resource at address '/subsystem=jgroups/stack=tcp/protocol=FD_SOCK' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
12:09:58,999 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0395: Operation add against the resource at address /subsystem=jgroups/stack=tcp/protocol=pbcast.GMS/property=max_join_attempts is deprecated, and it might be removed in future version. See the the output of the read-operation-description operation to learn more about the deprecation.
12:09:59,502 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0395: Operation add against the resource at address /subsystem=jgroups/stack=tcp/protocol=org.jgroups.protocols.JDBC_PING/property=initialize_sql is deprecated, and it might be removed in future version. See the the output of the read-operation-description operation to learn more about the deprecation.
12:09:59,555 INFO  [org.jboss.as.controller.management-deprecated] (pool-3-thread-2) WFLYCTL0395: Operation add against the resource at address /subsystem=jgroups/stack=tcp/protocol=org.jgroups.protocols.JDBC_PING/property=insert_single_sql is deprecated, and it might be removed in future version. See the the output of the read-operation-description operation to learn more about the deprecation.
```
I don't think this is going to be a small change (especially if we want to keep backward compatibility with keycloak 4.3.0 or lower).

I'll troubleshoot more this weekend. I didn't see any updated docs anywhere on this issue.

**Comment by axdotl** [comment]
Is there any update or can one support?

**Comment by unguiculus** [comment]
I created a new PR to update to 4.5.0.Final. See #8192. Please test and review. Thanks.

**Pull request closed without merging**
