### PR TITLE
[stable/prometheus] add server.extraFlags values array

### LINKED ISSUE #17038: [stable/prometheus] unable to add storage.tsdb.wal-compression flag
Hello,
There is no way to add --storage.tsdb.wal-compression argument with server.extraArgs for stable/prometheus chart.
server.extraArgs expects key:value array but prometheus server expects --storage.tsdb.no-lockfile without any value.

Exactly as it was reported [here](https://github.com/helm/charts/issues/11269) just a different flag.

### PR DESCRIPTION
**Pull request by eMCeee89**
#### What this PR does / why we need it:
Hello community,
Perhaps I am missing something and you will enlighten me but I found it too explicit to define one new condition inside of a template to be able to set a new flag. Is there a reason why it is defined this way? I expect that there will be more and more flags when progressively adding new features which may result in a huge and difficult-to-review template files.
I do understand that proposed solution is a breaking change for those that have e.g. `enableAdminApi` set to True (they will have to un-comment currently commented extraFlags array item `web.enable-admin-api`), at the same time this way we can modify only a data definition inside of values.yaml when introducing a new flag in the future.

I have changed also a description for `web.enable-admin-api` and `storage.tsdb.no-lockfile` based on a recommendation in https://github.com/helm/helm/blob/master/docs/chart_best_practices/values.md#document-valuesyaml

Thank you

#### Which issue this PR fixes
  - fixes #17038

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by zanhsieh** [comment]
@eMCeee89 
Would you mind to resolve conflicting files please?
stable/prometheus/Chart.yaml
stable/prometheus/README.md

**Comment by eMCeee89** [comment]
Hello guys,
I will do so tomorrow evening (CET).

/MC

Dňa ne 27. 10. 2019 o 15:52 zanhsieh <notifications@github.com> napísala(a):

**Comment by eMCeee89** [comment]
@cpanato

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@eMCeee89 
e2e test failed. Please bump chart version to latest. Thank you.

**Comment by eMCeee89** [comment]
@zanhsieh done, e2e tests are now green

**Review by zanhsieh — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@eMCeee89 
Could you rebase to latest chart version again? I think I figure out how to fix e2e test.

**Comment by eMCeee89** [comment]
@zanhsieh - done, all tests seems to be okay now

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
