### PR TITLE
fix mount path of config map

### PR DESCRIPTION
**Pull request by bilalcaliskan**
ignite could not read from the /opt/ignite/apache-ignite-fabric/config cause there is no such mounted config map in that directory. ignite could not read the values from the config map, after i changed the mount path, it started reading with right configuration.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by bilalcaliskan** [comment]
@davidkarlsen @unguiculus can you please review? This is just a mount point fix it's not a big change actually. Thanks.

**Comment by Aisuko** [comment]
@bilalcaliskan Hi, thanks for your PR,  please sign in DCO first. That can help you pass the CI. And do not forget to assign to the chart owner `by writing /assign @viglesiasce in a comment when ready`

**Comment by bilalcaliskan** [comment]
@Aisuko hello! I am sorry but i don't know what does DCO means. I have just fix a simple problem and i don't want the other people to face with the same problem. It should not be so hard to make a PR. I just changed the mount path so i can't understand why that CI tests are failing. It is impossible.

Thanks.

**Comment by bilalcaliskan** [comment]
@davidkarlsen @unguiculus would you mind if it takes your 5 minutes top to make a simple code review?

Thanks.

**Comment by unguiculus** [comment]
@bilalcaliskan You need to sign off you commits. See https://github.com/helm/charts/pull/15559/checks?check_run_id=169983809

**Pull request closed without merging**
