### PR TITLE
Contribution of puppet-forge to incubator Charts

### PR DESCRIPTION
**Pull request by hickey**

### CODE REVIEW

**Comment by hickey** [comment]
For a couple days now the CircleCi results have not been displaying. All I get when I try to look at the report of what failed is just a spinning icon. It seems to indicate that it failed lint of the chart, but I get linting of the chart to pass. 

```console
$ helm lint puppet-forge   
==> Linting puppet-forge
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

**Comment by viglesiasce** [comment]
The following is the failure:

```
Linting the Chart.yaml and values.yaml files at incubator/puppet-forge
incubator/puppet-forge/values.yaml
  29:11     error    trailing spaces  (trailing-spaces)
  61:1      error    too many blank lines (1 > 0)  (empty-lines)
```

I can tidy this up now.

**Comment by hickey** [comment]
Ah. Thank you. Was not evident from helm lint. I was just about to push another commit to fix these when I notice you had done so. So another thank you very much :-)

**Pull request merged**
