### PR TITLE
[incubator/druid] Remove the incubating label and update related infos for Apache Druid

### PR DESCRIPTION
**Pull request by asdf2014**
No

#### What this PR does / why we need it:

Remove the incubating label and update related infos for Apache Druid

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

@maver1ck @AWaterColorPen 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by asdf2014** [comment]
@maver1ck @AWaterColorPen PTAL.

**Comment by AWaterColorPen** [comment]
@asdf2014 
It should update chart version in  your PR
```
Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
 ✖︎ druid => (version: "0.2.1", path: "incubator/druid") > Chart version not ok. Needs a version bump!
------------------------------------------------------------------------------------------------------------------------
```

**Comment by asdf2014** [comment]
@AWaterColorPen Thanks for taking a look. This version has been bumped to `0.2.2`. And all tests passed.

**Comment by asdf2014** [comment]
Hi, @maver1ck . Thanks for testing this PR. The test task failed due to timeout. I think it can't be caused by this PR.. What do you think? 

```java
I0615 08:44:03.487] error: timed out waiting for the condition on namespaces/druid-presubmit-22788-1272448570280120323-i2jt7tb3um
```

**Comment by scottrigby** [comment]
Test infra should be fixed now

**Comment by asdf2014** [comment]
@maver1ck All CI tests have passed, would you please add a LGTM label.

**Pull request merged**
