### PR TITLE
[stable/concourse] Remove duplicate line

### PR DESCRIPTION
**Pull request by bracki**
@cirocosta Remove a duplicate line.

### CODE REVIEW

**Comment by cirocosta** [comment]
oooh, thxx!!

**Review by cirocosta — CHANGES_REQUESTED** [review]
Despite being a minor patch, it'd be necessary to have the version at `Chart.yaml` bumped 👍

**Comment by bracki** [comment]
@cirocosta Bumped the chart version as requested.

**Comment by cirocosta** [comment]
Thanks!

Now the only thing missing is applying the `Signed-of-by` trailer to your commit (so that the DCO bot gets happy) - https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work.

Thanks!

**Comment by bracki** [comment]
@cirocosta Done!

**Comment by cirocosta** [comment]
Awesome! Thx!

**Pull request merged**
