### PR TITLE
[stable/jenkins] deployment port must be targetPort

### PR DESCRIPTION
**Pull request by jibijose**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by torstenwalter** [comment]
Thanks. Looks ok. Please increment the chart version so that the build can be run.

Could you prefix the issue title with `[stable/jenkins]`?

**Comment by jibijose** [comment]
chart version updated to 1.3.6

**Review by torstenwalter — APPROVED** [review]
/lgtm

**Comment by torstenwalter** [comment]
@jibijose https://github.com/helm/charts/pull/15416/checks 

> DCO
> You have 2 commits incorrectly signed off. To fix, head to your local branch and run:
> 
> git rebase HEAD~2 --signoff
> Now your commits will have your sign off. Next run
> 
> git push --force-with-lease origin correction-deployment-port

**Comment by jibijose** [comment]
I will open a new PR with same changes.

**Pull request closed without merging**
