### PR TITLE
[stable/concourse] provide configuration(s) for integrating Concourse with Vault

### PR DESCRIPTION
**Pull request by jipperinbham**
enabled configuring Concourse to use Vault for managing secrets, exposes 3 types of Auth Backends: tokens, approle, and TLS

### CODE REVIEW

**Comment by viglesiasce** [comment]
@jipperinbham this is failing on the concourse web pod. The pod stays in the ContainerCreating state:

```
W1127 17:42:40.254] ++ kubectl get pods --no-headers --namespace pr-2446-3776
I1127 17:42:40.354] concour-3776-web-2545648290-wnm9h         0/1       ContainerCreating   0         9m
```

**Comment by jipperinbham** [comment]
@viglesiasce thanks for the heads up! I've fixed the issue and tests look good now, is there anything else I need to take care of?

**Comment by viglesiasce** [comment]
Thanks @jipperinbham!

**Pull request merged**
