### PR TITLE
Update Jenkins version to current LTS (2.19.4) and Kubernetes Plugin to 0.10

### PR DESCRIPTION
**Pull request by dserodio**
The current LTS release of Jenkins is 2.19.4, released 2016-11-23.

Also updating the Jenkins plugins, and config.xml for Kubernates Plugin 0.10

 * Kubernetes 0.10
 * Credentials Binding 1.10
 * Git 3.0.1

### CODE REVIEW

**Comment by dserodio** [comment]
I'll run some more tests

**Comment by dserodio** [comment]
Done testing, working great (on Minikube at least). This is my first PR to this repo, so I don't know if I should include the chart version number increase in the same PR or not, but I increased it to 0.1.6.

Since this PR requires an updated Jenkins Master image, the `ImageTag` in values.yaml also needs to be updated, but since I have no idea about the process to update these I left the ImageTag untouched.

**Comment by kingdonb** [comment]
I built a jenkins-master based on your changes and tested it out on Minikube, looks good to me

**Comment by dserodio** [comment]
Oops! Sorry about that, a rebase gone bad :( I'll close this and reopen a new one

**Comment by dserodio** [comment]
Created #341 to replace this one, sorry again for the mess

**Pull request closed without merging**
