### PR TITLE
[incubator/elasticsearch] - support imagePullSecrets

### PR DESCRIPTION
**Pull request by mwinters0**
This PR adds imagePullSecrets support to incubator/elasticsearch

### CODE REVIEW

**Comment by MikeSchuette** [comment]
@davidkarlsen So, https://github.com/helm/charts/pull/7234 which you reviewed was opened almost an entire month after this PR, and is nearly identical to this PR, but that one got reviewed and merged while this one still hasn't received a human response.  What am I doing wrong that my PRs do not receive reviews?  I have others open in a similar state.

**Comment by davidkarlsen** [comment]
@MikeSchuette there are simply too many PRs to keep up with - and also I was not the one that actually got that one merged (it was probably before I got lgtm-powers). If you are aware of double up PRs covering the same it is good to link them, so we can choose the one which is most fit and get the figures down. There is nothing wrong with the PR - I was simply not aware of it. Feel free to ping me on slack if you have some long-hanging fruit to be merged! :)

**Pull request closed without merging**
