### PR TITLE
[stable/elasticsearch] Add myself as maintainer.

### PR DESCRIPTION
**Pull request by desaintmartin**
As an owner of several k8s production clusters heavily using elasticsearch chart, I'd like to help in maintaining / reviewing this chart.

A few PRs I've done: https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=elasticsearch+is%3Apr+author%3Adesaintmartin+

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @simonswine @icereval @rendhalver

**Comment by rendhalver** [comment]
Sounds good to me.
Any objections @simonswine and @icereval?

**Comment by rendhalver** [comment]
Please rebase or merge master into your branch.
The chart version has changed since you opened this.

**Pull request merged**
