### PR TITLE
[stable/gitlab-ce] Use storageClassName for gitlab-ce.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed gitlab-ce for #1869

/cc @prydonius

### CODE REVIEW

**Review by prydonius — CHANGES_REQUESTED** [review]
wait for postgresql update

**Comment by gyliu513** [comment]
@prydonius postgresql here https://github.com/kubernetes/charts/pull/2005

**Review by prydonius — APPROVED** [review]
/lgtm

**Comment by prydonius** [comment]
@gyliu513 this chart is deprecated, maybe we should leave it?

**Comment by gyliu513** [comment]
sounds good, thanks @prydonius

**Pull request closed without merging**
