### PR TITLE
[stable/jenkins] Add option to overwrite plugins

### LINKED ISSUE #11228: [stable/jenkins] Option to overwrite plugins on start
It would be nice to have an option to override the installed plugins of the jenkins instance with the plugins and versions provided via the `Master.InstallPlugins` parameter.
The current behavior does not allow for downgrades of plugins and when using an Infrastructure-as-Code workflow it would be nice to be able to ensure that the provided list of plugins with the corresponding version will match to the plugins installed in the Jenkins instance.

My proposal to do this would be to add an additional line to the `apply_config.sh` that deletes the contents of `/var/jenkins_home/plugins/` on startup. This way the existing behavior can be left unchanged.

### PR DESCRIPTION
**Pull request by jcoeltjen**
#### What this PR does / why we need it:

Add an option to  overwrite all installed plugins with their versions with the values provided via the Master.InstallPlugins parameter.

#### Which issue this PR fixes
  - fixes #11228

#### Special notes for your reviewer:
The default behaviour of the chart does not change with this PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
/assign

Hey @jcoeltjen,
Thanks for contributing!

I have a question:
What is the expected and the actual behaviors of plugins that this PR tries to solve?

Maybe if the expected behavior makes more sense, maybe this should be the default behavior rather then a flag to enforce it?

Awaiting your reply!

**Comment by jcoeltjen** [comment]
Hi @maorfr ,

**The expected behavior is:**
I can provide a list of plugins that should be installed to the jenkins instance.
Now I also want to enforce that specific list of plugins with their respective versions.

**The current actual behavior is:**
When using the following syntax:
```yaml
Master:
  InstallPlugins:
    - git:3.9.3
    - blueocean:1.10.2
```
The git plugin and the blueocean plugin will be installed on startup.
When I now change the version for git to e. g. 3.9.2 and use `helm upgrade` the version in the instance will still be 3.9.3.

Beside changing the version of an already installed plugin I would also like to be able to make sure that the list of installed plugins on the jenkins instance matches the list provided in the chart values.
The jenkins admins should not be able to install plugins manually. Or at least don't persist these changes.
So when I force an upgrade for an existing release I want to make sure the instance will match its code representation.

I am not sure about changing the default behavior to this, because not everybody uses the chart for a strict Infrastructure-as-code setup. With this option set users will loose any manually installed plugins.
Which is what I want, but maybe is uncomfortable for other users.

**Comment by maorfr** [comment]
I'll go with you.

If you resolve the conflicts we can get this merged :)

**Comment by jcoeltjen** [comment]
I rebased the branch onto the current master.
Should I use SemVer for the version? Then it should be `0.31.0 ` instead of `0.30.1`.

**Comment by maorfr** [comment]
Right.

**Comment by jcoeltjen** [comment]
Version should be OK now.

**Comment by maorfr** [comment]
/lgtm

Thanks for contributing!

**Pull request merged**
