### PR TITLE
Add ability to control prometheus TSDB locking

### LINKED ISSUE #11269: [stable/prometheus] unable to add storage.tsdb.no-lockfile argument
There is no way to add --storage.tsdb.no-lockfile argument with server.extraargs for stable/prometheus chart.
server.extraargs expect for key:value array, but prometheus server expect --storage.tsdb.no-lockfile without any value.
Here is the logs 
```
Error parsing commandline arguments: unexpected true
prometheus: error: unexpected true
```

### PR DESCRIPTION
**Pull request by pastukhov**
This patch add ability to control prometheus TSDB lockibg via values

  - fixes #11269

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by pastukhov** [comment]
@mgoodness 
@gianrubio

**Comment by pastukhov** [comment]
Here it is similar fix for prometheus operator 
https://github.com/coreos/prometheus-operator/issues/854

**Review by gianrubio — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
