### PR TITLE
add prometheus data retention config

### PR DESCRIPTION
**Pull request by yagonobre**

### CODE REVIEW

**Comment by johnmarcou** [comment]
Hello,

Little typo here: https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/server-deployment.yaml#L51

No spaces needed around the `=`. This make the command crash because it can't find the parameter value.

Thanks.

**Comment by yagonobre** [comment]
Updated, thanks
https://github.com/kubernetes/charts/pull/2434

**Pull request merged**
