### PR TITLE
[stable/sonarqube] Sonarqube ingress fix

### PR DESCRIPTION
**Pull request by jamatute**
Hi, 

I had some issues deploying this chart in GKE, `/` was assigned to the sonarqube backend while `/*` was assigned to the default backed which gives an 404 error.

So `/` was loaded but all the rest (css, js...) wasn't loaded.

Therefore I had to make this change to assign all to the sonarqube backend.

Thanks

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @rjkernick

**Comment by jamatute** [comment]
PTAL @lachie83

**Pull request merged**
