### PR TITLE
[stable/prometheus-operator]: Re-sync prometheus rules and grafana dashboards

### PR DESCRIPTION
**Pull request by smoke**
#### What this PR does / why we need it:

This PR re-syncs prometheus rules and grafana dashboards using the automated scripts from ./hack folder.
This includes a fix for sign error in `NodeClockSkewDetected` that was causing false alarms https://github.com/prometheus/node_exporter/pull/1649

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by vsliouniaev** [comment]
Looks like you're trying to change a generated file:
```
3:  Do not change in-place! In order to change this file first read following link: 
4:  https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack	
```

/hold

**Comment by smoke** [comment]
@vsliouniaev Thanks for pointing that out, I have re-synced the rules and dashboards using the scripts.
/retest

**Comment by mattrapa** [comment]
Is updating Prometheus rules and Grafana dashboards handled by replicating this PR? Is there documentation on how to replicate it?
Thanks.

**Pull request merged**
