### PR TITLE
[stable/fluent-bit] Use release name as full name if contains chart name

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
Please see title

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @kfox1111

**Review by kfox1111 — COMMENTED** [review]
/lgtm

**Comment by naseemkullah** [comment]
Can I get please get an /ok-to-test @kfox1111 ? TIA

**Comment by naseemkullah** [comment]
Hmm sorry that did not work my mistake, maybe an /approve rather @kfox1111  TIA

**Comment by naseemkullah** [comment]
bump

**Pull request merged**
