### PR TITLE
[stable/prometheus-operator] Add namespace to all PrometheusRule objects

### PR DESCRIPTION
**Pull request by Smirl**
#### Is this a new chart
No

#### What this PR does / why we need it:
When installing with CI/CD tools that use `helm template` the `PrometheusRule` objects are placed in the current namespace (often default). This PR ensures that these objects are placed in the same namespace as the operator (and prometheus instance).

#### Which issue this PR fixes
* ensure rules are in correct namespace (edit. by updating the `sync_prometheus_rules.py` script)

#### Special notes for your reviewer:
* ~Some rules set a variable at the top of the template so I use `$namespace` rather than `.Release.Namespace` in these files.~
* ~I have raised another PR https://github.com/helm/charts/pull/19703 which bumps the chart to `8.4.0`. However, there isn't a dependency on that PR in this one.~

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by Smirl** [comment]
Fixed Chart.yml conflict.

/assign @davidkarlsen

**Comment by bismarck** [comment]
These rule files are sync'd from a few upstream repositories.  You would have to update the [sync script](https://github.com/helm/charts/blob/master/stable/prometheus-operator/hack/sync_prometheus_rules.py).

On another note, there's been a lot of [debate](https://github.com/helm/helm/issues/5465) whether setting the namespace in templates is a bad practice.  From what I understand, certain CI/CD systems [require](https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/#configure-the-bake-manifest-stage) the namespace to be set.

**Comment by Smirl** [comment]
Thanks for the review @bismarck. I have updated the `hack/sync_prometheus_rules.py` script and run it. This has also had the benefit of updating and adding rules to the `rules-1.14` directory. Rules for older versions of k8s are unchanged apart for the namespace added.

As for the debate, I'm on the side of adding it as it doesn't change the default behaviour. `--namespace` is still respected, etc.

We indeed use spinnaker which is why we are seeing this issue with rules being placed into the `default` namespace. Spinnaker has an override namespace function, but this breaks ServiceMonitors/Services which should be outside of the "prometheus operator" namespace (i.e. kube-system).

**Comment by bismarck** [comment]
@Smirl Change looks good.  Just one small request, could you bump the version to 8.5.3?

**Pull request merged**
