### PR TITLE
Add possibility to add custom initcontainers

### PR DESCRIPTION
**Pull request by yhekma**
#### What this PR does / why we need it:

For nonstandard (datasource) plugins for grafana, we need to be able to download stuff prior to running grafana. This way we can optionally execute a container that downloads/clones/whatever as an init

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by maorfr** [comment]
/assign

hey @yhekma,

`custominitcontainers` is not something i am very fond of, as in my opinion, values.yaml should not be just another place you store configuration.

take a look at some existing init containers and how they are implemented. usually, they will be exposed in a very simple way in values.yaml, and the heavy lifting will be done in the templates.

i understand the need for this feature, but i am sure there is a simpler way to expose it.
thanks for getting involved!

**Comment by yhekma** [comment]
hi @maorfr , thanks for the feedback. The reason I implemented it this way and not just say set an url in the values.yaml and do the checkout etc in the template is to keep flexibility. I do see your point though. Would you say that only specifying an url in the values.yaml along with the type of plugin (datasource/"normal") would be satisfactory?

**Comment by maorfr** [comment]
I would say that the purpose behind this feature is to fetch additoonal data sourcrs.
I would ask the following questions before implementing:

What is required for that?
Is it always done using git?
Does it have to be git?
What are the things that may vary in addition?
And any other question that you have encountered while discovering this need.

The values.yaml representation should be as simple as possible, depending on the answers.

I will just point out that there is a section that handles data sources, so maybe this feature is just about expanding it?

I will leave the design to you :)

Good luck and thanks for contributing!

**Comment by maorfr** [comment]
@yhekma, note that `extraInitContainers` are about to be merged in another PR - #12343. feel free to follow up on the conversation there to find out more ;)
you can use it once it is merged, but i would still think about a specific implementation for your requirements.

thanks for getting involved!

**Pull request closed without merging**
