### PR TITLE
[stable/prometheus-operator] Removed duplicate nodePort in prometheus service

### PR DESCRIPTION
**Pull request by btleedev**
#### What this PR does / why we need it:
Removed the duplicate nodePort in service.yaml. Purely cosmetic since yaml allows for duplicate entries.

#### Which issue this PR fixes
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by paskal — APPROVED** [review]

**Comment by btleedev** [comment]
Had to merge upstream and bump version again, please feel free to merge after lgtm.

**Comment by paskal** [comment]
You need to bump it once more.

**Comment by paskal** [comment]
@btleedev all more important PRs are merged now, if you'll update this PR it will have a very good chance to be merged now.

**Comment by btleedev** [comment]
@paskal @gianrubio merged master and bumped version, should be good

**Pull request merged**
