### PR TITLE
[incubator/druid] an invalid default value at midddleManager.config.druid_indexer_runner_javaOptsArray (#23312)

### PR DESCRIPTION
**Pull request by youngwookim**
#### Which issue this PR fixes

(#23312)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by maver1ck** [comment]
@youngwookim 
Please bump chart version

**Comment by youngwookim** [comment]
@maver1ck Addressed your comment. Bumped up chart version to 0.2.9 from 0.2.8

**Comment by maver1ck** [comment]
@youngwookim 
please check test result

**Comment by youngwookim** [comment]
@maver1ck Fixed the test failure.

**Pull request merged**
