### PR TITLE
[stable/kiam] Ability to handle secrets outside the chart

### PR DESCRIPTION
**Pull request by mikhailadvani**
Signed-off-by: Mikhail Advani <mikhail.advani@gmail.com>

#### What this PR does / why we need it: 

Currently the certificates have to maintained in the values file and cannot use any security measures people have in place to manage secrets outside the charts and values files. This PR allows the optional use of secrets managed outside the scope of the chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by mikhailadvani** [comment]
@ewbankkit : please provide feedback

**Comment by mikhailadvani** [comment]
@davidkarlsen @scottrigby can you please help take this forward

**Comment by mikhailadvani** [comment]
@ewbankkit yes I missed the existing PR #9526 . I would prefer using the single variable `existingSecret` approach taken in this PR though since it is more widely used technique and variable name across helm charts

**Comment by ewbankkit** [comment]
@mikhailadvani Yes, agreed.

**Comment by mikhailadvani** [comment]
@ewbankkit if you are okay with moving this forward, can you please add the necessary comments to take this forward

**Comment by ewbankkit** [comment]
@davidkarlsen @scottrigby lgtm

**Comment by nisan270390** [comment]
@mikhailadvani please take a look at this pull request #10353 which has beed merged and support this functionality

**Comment by mikhailadvani** [comment]
as mentioned above, already handled as pra of another PR

**Pull request closed without merging**
