### PR TITLE
[stable/grafana] upgrade to 6.2.4

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

#### What this PR does / why we need it:
Upgrades to latest release 6.2.4 - which is important since 6.2.3 was retracted.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by EricLemieux** [comment]
Fixes #14878

**Comment by hairyhenderson** [comment]
The CI build seems like it timed out? This just tripped us up too 🤦‍♂

**Pull request merged**
