### PR TITLE
Fix Kafka document

### PR DESCRIPTION
**Pull request by kanga333**
**What this PR does / why we need it**:
I found a typo in the documentation of kafka's chats. So I will fix it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by benjigoldberg** [comment]
@kanga333 Thanks for the contribution! Please bump the patch version for the CI builds to work!

**Comment by kanga333** [comment]
@benjigoldberg Thank you for review. I rebased and raised the version of chart.

**Comment by benjigoldberg** [comment]
@kanga333 if you pull master changes and bump the version we should be good to go. Apologies for the delays

**Comment by kanga333** [comment]
@benjigoldberg I got late, but I bumped it again.

**Pull request merged**
