### PR TITLE
Updating image from 1.4 to 1.6

### LINKED ISSUE #7143: [stable/influxdb] Update to influxdb 1.6.1
They did it:
https://github.com/influxdata/tick-charts/tree/master/influxdb

### PR DESCRIPTION
**Pull request by naseemkullah**
**What this PR does / why we need it**:
Updating default image from 1.4 to 1.6 to stay current.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #7143

**Special notes for your reviewer**:
This is my first CNCF commit, please let me know how I did

### CODE REVIEW

**Comment by naseemkullah** [comment]
I've just sent in my signed CLA.

**Comment by chrisprobst** [comment]
Hi, whats the status on this one?

**Comment by naseemkullah** [comment]
Hi @chrisprobst , I send in my signed CLA to the CNCF 4 days ago and am still waiting for their response. Once approved, we will be 1 step closer to merging.

**Comment by naseemkullah** [comment]
I dont get it I've signed the CNCF CLA and should be good to go

**Comment by dankohn** [comment]
@naseemkullah @mattfarina Helm just turned off use of the CLAbot. Now, you just need to sign your commits (`git commit --sign`) and they will pass.

Please see https://github.com/helm/community/issues/30

**Comment by naseemkullah** [comment]
Thank you @dankohn

**Comment by davidkarlsen** [comment]
@naseemkullah did you get a chance to sign your commits?

**Comment by naseemkullah** [comment]
Sorry for the delay. I believe I just did now @davidkarlsen

**Comment by davidkarlsen** [comment]
lgtm

**Pull request merged**
