### PR TITLE
[stable/redis-ha] Add `hardAntiAffinity` and `additionalAffinities` options

### PR DESCRIPTION
**Pull request by arbourd**
#### What this PR does / why we need it:

Adds new ways to control anti-affinity.

By default, the `affinity` key in the `values.yaml` is a string that has a default that can be overrode. This PR adds new ways to manipulate affinity:

- `hardAntiAffinity` which is a boolean `true` or `false` (default is `true`)
   This sets a `required` (true) or `preferred` (false) anti-affinity for the hostname
- affinity for the zone is always set as `preferred`
- `additionalAffinities` which is a YAML object which can be used to add additional affinity to the already above defaults ☝️ 
- `affinity` overrides `hardAntiAffinity` and `additionalAffinities` and is a string. This is to maintain backwards compatibility.

Why? We use this chart as a subchart and really like the default affinity settings, but want an easy one `--set` command to switch between hard and soft affinity (so we can run tests). Otherwise, we need to manipulate a large string. These changes are influenced by the [Concourse](https://github.com/helm/charts/blob/master/stable/concourse) chart that implements the same concepts.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by ssalaues** [comment]
Yeah there was lots of flip flop on whether to have the simple values vs the more complex but configurable. I think this is a good middle ground for both sides.

**Comment by ssalaues** [comment]
@arbourd A few PRs just got merged. Could you rebase and force push your changes? Once the conflicts are resolved (should just be the version bumps) I'll approve.

**Comment by arbourd** [comment]
Done. Thanks @ssalaues 😬

**Pull request merged**
