### PR TITLE
Change replication.enabled to replicaSet.enabled

### PR DESCRIPTION
**Pull request by sabbour**
The current suggested command line is wrong.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@sabbour could you please bump the chart version and add signoff to make the linter pass?

**Comment by sabbour** [comment]
@vsliouniaev I actually only changed the README. Does it warrant a bump?

**Comment by vsliouniaev** [comment]
Yep, charts are completely atomic, so lint will fail if you don't update the readme

**Comment by juan131** [comment]
Hi @sabbour 

Thanks for the PR! As @vsliouniaev mentioned you need to signoff your commit and increase the patch version in the **Chart.yaml**

It's mandatory for the CI

**Comment by sabbour** [comment]
Sorry @juan131 bear with me as this was my first PR here. It seems I can't get this sign-off thing to work.

**Comment by juan131** [comment]
It seems you also included changes from other charts. My recommendation: start from scratch.

- Close this PR
- Create a new branch with the changes on MongoDB chart and when you commit the changes remember to add the flag `--signoff`.
- Create a new PR with those changes

**Comment by sabbour** [comment]
Yeah git wouldn’t let me commit again without merging upstream changes.
Ok will do.

/close

- Ahmed

**Pull request closed without merging**
