### PR TITLE
[incubator/kafka] Rework mechanism to expose Kafka brokers externally

### PR DESCRIPTION
**Pull request by szubster**
#### What this PR does / why we need it:
Statefulsets from kubernetes 1.9 set label statefulset.kubernetes.io/pod-name to pod name.
Thus setting label pod in initcontainer is not needed anymore.
Also rbac settings, previously needed by initContainer are not needed.

#### Special notes for your reviewer:
I wasn't sure, to what version should the chart be bumped.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

@faraazkhan @h0tbird @benjigoldberg

### CODE REVIEW

**Comment by szubster** [comment]
Is anything more needed from me?
/lgtm does not seem to have pushed it forward.

**Comment by szubster** [comment]
I want to bump this PR.
Is there an blocker?
@unguiculus @benjigoldberg

**Comment by kppullin** [comment]
Leaving this here in case someone else runs into similar issues: if you previously set `rbac.enabled: true`, upon upgrading you may see errors related to missing kafka service account tokens.  To work around this I had to manually remove the `serviceAccount` and `serviceAccountToken` values from the kafka statefulset.

More details here: https://github.com/kubernetes/kubernetes/issues/76367#issuecomment-481689160

**Pull request merged**
