### PR TITLE
add: spinnaker clouddriver podAnnotations

### PR DESCRIPTION
**Pull request by hareku**
Signed-off-by: Masato Kureha <hareku908@gmail.com>

#### What this PR does / why we need it:
Add podAnnotations for `clouddriver.yml`
ref: https://www.spinnaker.io/reference/halyard/custom/#podannotations

Example: kube2iam for ECR auth-N. (values.yml)
```values.yaml
clouddriver:
  podAnnotations:
    iam.amazonaws.com/role: my-ecr-readonly-role-arn
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by hareku** [comment]
```
  additionalProfileConfigMaps:
    create: true
    data:
      clouddriver-local.yml: |-
        kubernetes:
          podAnnotations:
            iam.amazonaws.com/role: "${aws_iam_role.spinnaker_clouddriver.arn}"
```

This was not working, so I need this PR patch.
ping @lwander @dwardu89

**Review by dwardu89 — APPROVED** [review]

**Comment by MarkFreebairn** [comment]
Hey! I am only seeing this pr now, I somehow missed it before, I had added a very similar PR for the same thing here: https://github.com/helm/charts/pull/12719

One of these PRs should be closed, I don't mind which one but if we are going to merge this one then it should also include the changes I made to add pod annotations to the front50 pod. This is required if you are wanting to write spinnaker config to an s3 bucket instead of minio.

Also, I noticed both my PR and this one are failing on pull-charts-e2e but haven't been able to figure out why yet.

**Comment by hareku** [comment]
@MarkFreebairn You got it. I close this PR for #12719

**Pull request closed without merging**
