### PR TITLE
[stable/docker-registry] fix values.yaml imagePullSecrets example

### PR DESCRIPTION
**Pull request by trollr**
**What this PR does / why we need it**:

values.yaml example fix

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

imagePullSecret example in values.yaml

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by trollr** [comment]
Should I do a version increment? Think it's not necessary

**Comment by rendhalver** [comment]
Can you please include [stable/docker-registry] in the PR title so someone can easily tell what it's for.

**Comment by rendhalver** [comment]
Version should always be incremented.
The tests will fail if you don't increment the version.

**Pull request merged**
