### PR TITLE
[stable/heapster] New version

### PR DESCRIPTION
**Pull request by pierluigilenoci**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by PierluigiLenociAkelius** [comment]
@mattfarina or @jlegrone 😘

**Comment by PierluigiLenociAkelius** [comment]
@maorfr could you please take a look again

**Comment by PierluigiLenociAkelius** [comment]
@mattfarina @jlegrone

**Comment by maorfr** [comment]
sorry for not noticing earlier, but can we also update README with the new version?

**Comment by PierluigiLenociAkelius** [comment]
@maorfr done

**Comment by maorfr** [comment]
/lgtm

Thanks a lot!

**Comment by PierluigiLenociAkelius** [comment]
@maorfr prow build is stucked since your approval. 😭

**Comment by PierluigiLenociAkelius** [comment]
`I0708 17:56:22.644]   export POD_NAME=$(kubectl get pods --namespace heapster-presubmit-14815-1148289523600330752-k38pscsjfl -l "app=heapster-k38pscsjfl" -o jsonpath="{.items[0].metadata.name}")
I0708 17:56:22.644]   kubectl --namespace heapster-presubmit-14815-1148289523600330752-k38pscsjfl port-forward $POD_NAME 8082
I0708 17:56:22.644] 
I0708 17:56:23.588] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 of 1 updated replicas are available...
I0708 17:56:24.376] Waiting for deployment spec update to be observed...
I0708 17:56:24.385] Waiting for deployment spec update to be observed...
I0708 17:56:24.449] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 out of 1 new replicas have been updated...
I0708 17:56:24.474] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 1 old replicas are pending termination...
I0708 17:56:24.493] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 of 1 updated replicas are available...
I0708 23:47:03.893] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 of 1 updated replicas are available...
I0709 09:22:58.747] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 of 1 updated replicas are available...
I0709 09:58:32.407] Waiting for deployment "heapster-k38pscsjfl" rollout to finish: 0 of 1 updated replicas are available...`

There is something wrong. :(
https://prow.k8s.io/log?id=1148289523600330752&job=pull-charts-e2e

@maorfr any suggestion?

**Comment by maorfr** [comment]
tried to close and reopen, lets see if that makes any difference

**Comment by PierluigiLenociAkelius** [comment]
This is unbelievable. :(

**Comment by PierluigiLenociAkelius** [comment]
How is it possible that just the version bump can break the automation in this way? 🤦‍♂

**Comment by PierluigiLenociAkelius** [comment]
@mattfarina @jlegrone could please help us to figure out?

**Comment by PierluigiLenociAkelius** [comment]
` I0724 20:33:34.512] NAME                                  READY  STATUS        RESTARTS  AGE
I0724 20:33:34.512] heapster-y45tu7ic6l-667694f5f8-m97w7  1/2    ErrImagePull  0         2s `

**Comment by PierluigiLenociAkelius** [comment]
@maorfr I fixed it.  How is it possible that the tests had worked for the previous release remains a mystery to me.

**Comment by maorfr** [comment]
/lgtm

maybe the image previously existed?

**Comment by PierluigiLenociAkelius** [comment]
> maybe the image previously existed?

I checked the previous versions of the chart and the image name was without -amd. But this is not really important. 😃

**Pull request merged**
