### PR TITLE
Change indent from 8 to 4

### LINKED ISSUE #12106: [stable/fluent-bit] indent 8 should be indent 4?
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:

Helm = 2.13
K8s = 1.11.7

**Which chart**:

stable/fluent-bit latest

**What happened**:

Attempted to add extra input section. For example:

```
extraEntries:
  input: |
    [INPUT]
        Name             tail-syslog
        Path             /var/log/syslog.log
        Parser           tail-syslog
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
```

**What you expected to happen**:

Configured to work, but it did not as it was indented incorrectly:

```
  fluent-bit-input.conf: |-
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        [INPUT]
            Name             tail-syslog
            Path             /var/log/syslog.log
            Parser           tail-syslog
            Refresh_Interval 5
            Mem_Buf_Limit    5MB
            Skip_Long_Lines  On
```

**How to reproduce it** (as minimally and precisely as possible):

See above -- to note the indent 8 can be seen in multiple places in the config template.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by flands**
#### What this PR does / why we need it:

Some fluent-bit configurations do not work today

#### Which issue this PR fixes

  - fixes #12106

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped

Signed-off-by: Steve Flanders <steve@sflanders.net>

### CODE REVIEW

**Comment by flands** [comment]
PTAL @kfox1111 @edsiper

**Comment by sirrapa** [comment]
@kfox1111 @edsiper Can you Review the PR please? We are waiting for this PR.

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

thanks!

**Comment by kfox1111** [comment]
Good grief, not again! Stop merging these things!

**Comment by maorfr** [comment]
@kfox1111 how come?

**Comment by kfox1111** [comment]
This was forced through once before. breaking the api. then we undid it. then its happening again. Another breaking change. :(

The result last time was we came up with rawConfig for those that wanted to add sections. extraEntries is for adding entries to the existing sections. :(

That this keeps happening seems like we really need some kind of howto use thing.

**Comment by maorfr** [comment]
i have added you as a collaborator, so from now on you and @edsiper can own this with less other maintainers getting in the way! :)

**Comment by kfox1111** [comment]
Thank you. :)

**Pull request merged**
