### PR TITLE
[stable/superset] Update Maintainers List

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
updating maintainers list due to significant improvement in how app is started and big jump in version. Ongoing improvements to follow.

Signed-off-by: marcussorealheis <marcuseagan@gmail.com>

#### What this PR does / why we need it:

This PR expands the maintainer list to include me as I have both the bandwidth to follow the latest developments in the project and knowledge on problems caused in this environment. WOuld be good for users to know they can ping me with issues. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #
My last PR eliminated a `CrashLoopBackoff` that had been plaguing the chart for a while.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
Tagging @maorfr

**Comment by MarcusSorealheis** [comment]
@maorfr a few contributions related to wrangling of data and starting the app in the ways you want. I have some more, like minor bugfixes for charts and things but less SRE related.
I bet you aren't using hive in Prod because it won't work: https://github.com/apache/incubator-superset/commit/01689c38ea9acfcede1b10576f5c52af52dc340b
Have lots of tables/data sources, list needs to be refreshable: https://github.com/apache/incubator-superset/commit/56eac687f8f1d360f68fc78213ade8d298409603
https://github.com/apache/incubator-superset/commit/f486f435b4e7587632ae4d04868ecc7eaf17f508: doc entry for starting an app with modified FAB
Keeping deps docs updated so that production devops teams have good info: https://github.com/apache/incubator-superset/commit/b1269c31f730a4ee6fe5c72ae5e7394d27db3873
Improving security for production users: https://github.com/apache/incubator-superset/commit/4c35de1d1f775017094b83348b26a823078d0e84
please on't blame devops that you cannot connect to the DB, read the sqlalchemy docs: https://github.com/apache/incubator-superset/commit/83b5dcc8c2788157d3670b289b913c623d7f1817
Superset CLI was broken briefly, but not forever: https://github.com/apache/incubator-superset/commit/9ec3e18ecb6c183237d859919af4daea7893b897

**Comment by maorfr** [comment]
/approve

i'm +1 to this, thank you for stepping up, @MarcusSorealheis!

ping @alitari, would you like to keep maintaining this chart? :pray:

**Comment by alitari** [comment]
> /approve
> 
> i'm +1 to this, thank you for stepping up, @MarcusSorealheis!
> invitation sent as per #20528.
> 
> ping @alitari, would you like to keep maintaining this chart? 🙏

No, please feel free to take it over! 👼

**Comment by MarcusSorealheis** [comment]
> > /approve
> > i'm +1 to this, thank you for stepping up, @MarcusSorealheis!
> > invitation sent as per #20528.
> > ping @alitari, would you like to keep maintaining this chart? 🙏
> 
> No, please feel free to take it over! 👼

awesome, thank you! 🙏

**Comment by maorfr** [comment]
/lgtm

welcome aboard!

**Comment by MarcusSorealheis** [comment]
> /lgtm
> 
> welcome aboard!

Thank you! Happy to be here.

**Pull request merged**
