### PR TITLE
[stable/kubernetes-dashboard] Harden Kubernetes Dashboard security setup to protect whole cluster

### PR DESCRIPTION
**Pull request by Eddman**
In reaction to the [Tesla incident](https://blog.redlock.io/cryptojacking-tesla)...

Based on [Access control](https://github.com/kubernetes/dashboard/wiki/Access-control) best practises for Kubernetes Dashboard and great [talk](https://blog.heptio.com/on-securing-the-kubernetes-dashboard-16b09b1b7aca) from @jbeda:
- Use HTTPS by default
- Added minimal role for Kubernetes Dashboard (as default)
- Use cluster-admin role only if `rbac.clusterAdminRole` is `true` (not recommended)

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for the PR. Pleae adapt this to our RBAC best practices. thanks.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

**Comment by Eddman** [comment]
@unguiculus Adapted.

**Comment by isaacbentley** [comment]
@Eddman I made a comment in the PR as there's a bug, the proxy command needs to be updated to use the new port 8443.

**Comment by Eddman** [comment]
Hi @isaacbentley, can you be more specific? What "proxy command" do you mean?

**Pull request merged**
