### PR TITLE
[stable/nginx-ingress] Fixes permissions when running in scoped mode …

### PR DESCRIPTION
**Pull request by norwoodj**
…(#9636)

Signed-off-by: John Norwood <norwood.john.m@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by floriantraber** [comment]
see also #8914

**Comment by dotLou** [comment]
This PR essentially makes it so it's not possible to ever install this chart in without a cluster-level set of permissions, in a specific namespace, with RBAC enabled.

1. If you set `rbac.create=true` as well as `controller.scope.enabled=true`, then you get the new set of cluster role and binding + the role and rolebinding
1. If you set `rbac.create=true` and `controller.scope.enabled=false`, you'll get the previous set of cluster permissions + the role and rolebinding
1. If you set `rbac.create=false` and `controller.scope.enabled=false` then you get no roles set at all, cluster or otherwise.

IMO this was a breaking change and it certainly broke one of my use cases.

**Pull request merged**
