### PR TITLE
Fixing readme feedbacks

### PR DESCRIPTION
**Pull request by vishiy**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@vishiy Chart version will need to be bumped too.

**Comment by vishiy** [comment]
@davidkarlsen - Looks circle ci is failing saying 'no maintainers'. I clearly see maintainer(s) in chart.yaml. Do you know what else could be wrong ? Can you please help ? Thank you!
"incubator/azuremonitor-containers > Chart doesn't have maintainers"

**Comment by vishiy** [comment]
@davidkarlsen - can i please get a approval ?

**Pull request merged**
