### PR TITLE
upgrade Neo4j to latest 3.5 series

### PR DESCRIPTION
**Pull request by moxious**
#### What this PR does / why we need it:

Since the last update, Neo4j updated to the 3.5 series.  The docker containers work the same way, and really this just needs a version bump to expose new features for users.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Comment by moxious** [comment]
@mneedham was the original maintainer and can verify these changes are OK

**Comment by mneedham** [comment]
LGTM

**Comment by moxious** [comment]
@prydonius or @mattfarina could you please have a quick look?  Maintainer / original author LGTM'd this PR and it seems all the other checks are green.

**Review by mattfarina — APPROVED** [review]

**Comment by moxious** [comment]
Not sure why after going stale the tests failed a second time.  While waiting for the PR to be approved we moved up another patch version so I've updated again and pushed changes after merging master to see if this help.

**Comment by mneedham** [comment]
LGTM

**Comment by mattfarina** [comment]
@moxious new commits need to have the DCO signature on it. Can you please follow the directions on the checks tab to correct this.

**Comment by moxious** [comment]
@mattfarina done

**Comment by mattfarina** [comment]
@moxious There is still a commit missing DCO signoff. Can you please signoff on it.

**Pull request closed without merging**
