### PR TITLE
[stable/spinnaker] Add ecr as docker registry with --password-command parameter

### PR DESCRIPTION
**Pull request by mced**
Signed-off-by: Cédric Menassa <cedric.menassa@gmail.com>

#### What this PR does / why we need it:
Add `--password-command` parameter in Halyard to add ECR as Docker registry

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by loispostula** [comment]
@viglesiasce @lwander any chance to have this reviewed at some point?

**Comment by mced** [comment]
@ezimanyi any chance to review and approve this pr ?

**Comment by ezimanyi** [comment]
@mced : Looks like the PR to add me to the owners file hasn't been merged yet; I just pinged that PR to try to get it merged, then will take a look at this.

**Comment by ezimanyi** [comment]
Still blocked on #15564.

**Comment by mced** [comment]
@ezimanyi how can I help ?

**Comment by ezimanyi** [comment]
My link was wrong above (and was a circular reference to this issue); actually blocked waiting for #18552, which will give me permission to approve this PR.  Reached out to @viglesiasce who will help get that merged, hopefully later this week.

**Comment by ezimanyi** [comment]
@mced: Sorry for the delay in reviewing this!  This looks good, but can you please rebase and bump the chart version again, as a few PRs have bumped the version in the meantime.  Thanks!

**Comment by mced** [comment]
@ezimanyi here you are, but I don't get why the pull-charts-e2e test still fails

**Comment by ezimanyi** [comment]
@mced: I took a quick look at the test output and am not sure either---have you tried locally deploying the test with your changes, and/or using the [chart-testing](https://github.com/helm/chart-testing) tool against it?  I'm not overly familiar with these end-to-end tests (as this is the first PR against this chart I'm reviewing) so I'm probably not in the best position to help debug it.

**Comment by mced** [comment]
@ezimanyi no, I didn't test locally... and as you are, I'm not familiar with this test suite.
Can we invoke someone who will figure out why ?

**Comment by ezimanyi** [comment]
Maybe @paulczar @dwardu89 can help?  Sorry that I can't be of much assistance understanding why the test is failing.

**Comment by gdurandvadas** [comment]
This fails because the image used to run the Spinnaker install, `gcr.io/spinnaker-marketplace/halyard` does not contain `aws` command
```
$ docker run --rm gcr.io/spinnaker-marketplace/halyard:1.23.2 aws
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"aws\": executable file not found in $PATH": unknown.
```

ref: https://github.com/spinnaker/spinnaker/issues/5165

**Comment by mced** [comment]
@gdurandvadas Thanks for the bug details

**Comment by mced** [comment]
@ezimanyi can you /approve this pr please ?

**Pull request merged**
