### PR TITLE
Fix/airflow helper

### LINKED ISSUE #5341: README for grafana/grafana:5.0.4 seems tricky
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Kubernetes:

```
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

grafana:5.0.4

**What happened**:

```
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,component=" -o jsonpath="{.items[0].metadata.name}")
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
```

**What you expected to happen**:

```
$ kubectl --namespace default port-forward $POD_NAME 3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

**How to reproduce it** (as minimally and precisely as possible):

Let's say I want to install grafana 5.0.4 on GKE through helm... I'd go like this:

```
helm install --name grafana stable/grafana --set server.image=grafana/grafana:5.0.4
```

So far so good...

```
NAME:   grafana
LAST DEPLOYED: Mon Apr 30 19:37:13 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME     TYPE    DATA  AGE
grafana  Opaque  2     1s

==> v1/ConfigMap
NAME                     DATA  AGE
grafana                  1     1s
grafana-dashboards-json  0     1s

==> v1/Service
NAME     TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)  AGE
grafana  ClusterIP  10.39.245.216  <none>       80/TCP   1s

==> v1beta2/Deployment
NAME     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
grafana  1        1        1           0          1s

==> v1/Pod(related)
NAME                     READY  STATUS             RESTARTS  AGE
grafana-d5f78bcb5-dwm46  0/1    ContainerCreating  0         1s


NOTES:
1. Get your 'admin' user password by running:

   kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo

2. The Grafana server can be accessed via port 80 on the following DNS name from within your cluster:

   grafana.default.svc.cluster.local

   Get the Grafana URL to visit by running these commands in the same shell:

     export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,component=" -o jsonpath="{.items[0].metadata.name}")
     kubectl --namespace default port-forward $POD_NAME 3000
```

However...

```
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,component=" -o jsonpath="{.items[0].metadata.name}")
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
```

What if I don't need component?

```
$ export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana" -o jsonpath="{.items[0].metadata.name}")

$ kubectl --namespace default port-forward $POD_NAME 3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

### LINKED ISSUE #11618: stable/airflow _helpers.tpl assignment operator incorrect
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

The `_helpers.tpl` file uses `=` for some variable assignments instead of `:=`. This causes the install to fail.

### PR DESCRIPTION
**Pull request by andymeierdev**
#### What this PR does / why we need it:
The `_helpers.tpl` file in stable/airflow contains incorrect assignment operator causing install to fail.

#### Which issue this PR fixes
  - fixes #11618 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by ameier38** [comment]
@gsemet sry, referenced wrong issue in commit if you could approve again

**Comment by gsemet** [comment]
@ameier38 can you rebase (and bump to 1.0.1)

**Pull request merged**
