### PR TITLE
[stable/gocd] Support tls for ingress

### PR DESCRIPTION
**Pull request by hemslo**
**What this PR does / why we need it**:

Add tls support for gocd ingress.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @varshavaradarajan

**Comment by hemslo** [comment]
Any plan to merge this PR?

**Comment by varshavaradarajan** [comment]
@hemslo - sorry for the late reply. Yes. I'm testing this out. I'll put up a comment once done.

**Comment by varshavaradarajan** [comment]
@hemslo - can you please update the README.md ?

**Comment by hemslo** [comment]
@varshavaradarajan sure, updated.

**Comment by varshavaradarajan** [comment]
@unguiculus - the changes lgtm. Can you go ahead and review this and merge it if you have no problems?

**Comment by unguiculus** [comment]
Can we make this a minor bump, since it's a new feature?

**Comment by hemslo** [comment]
@unguiculus The tls support is get by default when run `helm create` a new chart, so I think it's just a patch.

**Comment by hemslo** [comment]
Can this PR be merged? TLS is needed for gocd agent outside kubernetes cluster, using official chart is easier than maintaining my own fork.

**Comment by unguiculus** [comment]
Bumping versions is not related to what `helm create` does. It's about the specific chart itself. This adds a feature, not a bug fix. So, a minor bump would be appropriate. I /lgtm it anyways, since it wasn't clearly handled in the past.

@varshavaradarajan I'd suggest patch level bump for bugfixes only in the future.

**Pull request merged**
