### PR TITLE
[stable/envoy] support loadBalancerIP

### PR DESCRIPTION
**Pull request by IguteChung**
Support loadBalancerIP value if service type is LoadBalancer

### CODE REVIEW

**Comment by mumoshu** [comment]
@IguteChung Thanks for your contribution!

This LGTM overall. Would you mind bumping the chart version by one minor ver?

**Comment by mumoshu** [comment]
Also would you mind signing your commits as explained in https://github.com/helm/charts/pull/17150/checks?check_run_id=223396054 ?

**Comment by zanhsieh** [comment]
@IguteChung 
Would you mind to resolve conflicting file please? 
stable/envoy/templates/service.yaml

**Comment by mumoshu** [comment]
This has been superseded by #18219 and #18265. Thanks for your contribution!

**Pull request closed without merging**
