### PR TITLE
Create a secret for external PostgreSQL instances

### PR DESCRIPTION
**Pull request by mlaccetti**
**What this PR does / why we need it**:

SonarQube makes an assumption about the name of a PostgreSQL secret when using an external server, which doesn't necessarily align with what a user has done. Instead, the chart should create a secret to store the PostgreSQL password, and consume that.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

N/A (issue as PR)

**Special notes for your reviewer**:

Simple change, I think?

### CODE REVIEW

**Comment by mlaccetti** [comment]
@rjkernick Looks like the PostgreSQL chart isn't setting up the user properly; have you seen this behaviour before?

**Comment by rjkernick** [comment]
I have not. I'll take a look in the morning and see if there are any recent
changes to the postgres chart.

**Comment by rjkernick** [comment]
Not seeing any breaking changes in the postgres chart. I have a feeling it is an issue with the charts test environment

**Comment by rjkernick** [comment]
Created #5374 to address the test failures. Once that is merged, you can rebase and the tests should pass

**Comment by rjkernick** [comment]
Please rebase master and bump chart version

**Comment by rjkernick** [comment]
Looks like something went wrong on you rebase.

**Comment by unguiculus** [comment]
BTW, in general, please don't rebase. Merge in the latest master. Otherwise Github can't display changes, which makes it harder for reviewers. In the PRs are squashed anyways.

**Comment by mlaccetti** [comment]
@rjkernick Merged.

**Comment by rjkernick** [comment]
Thanks. Looks like you just need to bump the version in Chart.yaml to 0.5.5.

**Pull request merged**
