### PR TITLE
[stable/datadog] fix PodSecurityContext seLinux section

### LINKED ISSUE #23084: [stable/datadog] unknown field "rule" in io.k8s.api.core.v1.PodSecurityContext
**Describe the bug**

When upgrading the chart to the latest version i get this error :  
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.securityContext): unknown field "rule" in io.k8s.api.core.v1.PodSecurityContext

**Version of Helm and Kubernetes**:
`
 kubectl version                                                                                                                                                                       Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

` helm  version                                                                                                                                                                         francois.beauchemin@MacBook-Pro
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`
**Which chart**:

stable/datadog 

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Seems to have been introduced in 2.3.23 ?

### PR DESCRIPTION
**Pull request by clamoriniere**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #23084

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ESBA-salman** [comment]
Hi,

We are seeing the following error:

Error: template: datadog/templates/daemonset.yaml:44:56: executing "datadog/templates/daemonset.yaml" at <.Values.datadog.securityContext.seLinuxOptions>: nil pointer evaluating interface {}.seLinuxOptions

**Comment by ESBA-salman** [comment]
> Hi,
> 
> We are seeing the following error:
> 
> Error: template: datadog/templates/daemonset.yaml:44:56: executing "datadog/templates/daemonset.yaml" at <.Values.datadog.securityContext.seLinuxOptions>: nil pointer evaluating interface {}.seLinuxOptions

Never Mind, I had to pass in the selinux options. 
Thanks

**Comment by clamoriniere** [comment]
Hi @ESBA-salman 

Sorry about this regression

we have release a new version (2.3.28) of the chart that include #23146 which allow to have `datadog.securityContext == nil` too in the `values.yaml` file.

**Pull request merged**
