### PR TITLE
Set environment variables from Kubernetes secrets #12446

### LINKED ISSUE #12446: [stable/logstash] set environment variables from kubernetes secrets
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** Feature Request

**Version of Helm and Kubernetes**: 1.11

**Which chart**: stable/logstash

I have secrets for passwords and tokens stored as secrets in Kuberntets which I need to reference in my logstash pipeline. I would like to be able to set these as environment variables in my container as outlined here https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables.

Example of command to create secret
```
kubectl create secret generic elasticsearch-secrets --from-literal=ELASTICSEARCH_USER=admin --from-literal=ELASTICSEARCH_PASSWORD=p@ssw0rd
```

Example expected container spec for logstash stateful set
```
spec:
  containers:
  - name: logstash
    image: "docker.elastic.co/logstash/logstash-oss:6.6.1"
    ....
    env:
      - name: ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: ELASTICSEARCH_USER
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: ELASTICSEARCH_PASSWORD
```

Example logstash pipeline using created environment variables
```
output {
   elasticseardch {
     user: "${ELASTICSEARCH_USER}"
     password: "${ELASTICSEARCH_PASSWORD}"
```

### PR DESCRIPTION
**Pull request by ChrisSchreiber**
#### What this PR does / why we need it:
Makes it possible to configure environment variables to be set from secrets in kubernetes

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #12446 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by czerasz-flaconi** [comment]
How about using the same logic as in [`stable/kong/templates/deployment.yaml`](https://github.com/helm/charts/blob/8d2547bcec2505bf00d23acdeb6064b3fe398f63/stable/kong/templates/deployment.yaml#L63)?

```
diff --git a/stable/logstash/templates/_helpers.tpl b/stable/logstash/templates/_helpers.tpl
index d88fb24b..b58a2328 100644
--- a/stable/logstash/templates/_helpers.tpl
+++ b/stable/logstash/templates/_helpers.tpl
@@ -30,3 +30,18 @@ Create chart name and version as used by the chart label.
 {{- define "logstash.chart" -}}
 {{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
 {{- end -}}
+
+{{/*
+Create environment variables
+*/}}
+{{- define "logstash.env" -}}
+{{- range $key, $value := .Values.env }}
+- name: {{ $key | upper | replace "." "_" }}
+{{- $valueType := printf "%T" $value -}}
+{{ if eq $valueType "map[string]interface {}" }}
+{{ toYaml $value | indent 2 -}}
+{{- else }}
+  value: {{ $value | quote -}}
+{{- end -}}
+{{- end -}}
+{{- end -}}
diff --git a/stable/logstash/templates/statefulset.yaml b/stable/logstash/templates/statefulset.yaml
index 5f2c389b..d8073b05 100644
--- a/stable/logstash/templates/statefulset.yaml
+++ b/stable/logstash/templates/statefulset.yaml
@@ -76,6 +76,7 @@ spec:
             - name: {{ $key | upper | replace "." "_" }}
               value: {{ $value | quote }}
           {{- end }}
+          {{- include "logstash.env" . | indent 10 }}
           resources:
 {{ toYaml .Values.resources | indent 12 }}
           volumeMounts:
```

**Comment by czerasz-flaconi** [comment]
@ChrisSchreiber what do You think about my [previous comment](https://github.com/helm/charts/pull/12447#issuecomment-476302969)?

I think this feature is very useful and deserves to be focused on :slightly_smiling_face:

**Comment by ChrisSchreiber** [comment]
@czerasz-flaconi  I'm not sure I follow exactly what this is doing 

> +{{- $valueType := printf "%T" $value -}}
> +{{ if eq $valueType "map[string]interface {}" }}
> +{{ toYaml $value | indent 2 -}}

Can you give me an example of what the values.env would look like to generate the valuesFrom section so I can test it?

**Comment by czerasz-flaconi** [comment]
@ChrisSchreiber here is an example from [`stable/kong/README.md`](https://github.com/helm/charts/blob/8d2547bcec2505bf00d23acdeb6064b3fe398f63/stable/kong/README.md):

```yaml
kong:
  env:
     pg_user: kong
     pg_password:
       valueFrom:
         secretKeyRef:
            key: kong
            name: postgres
```

Pls also take a look at [this include](https://github.com/helm/charts/blob/8d2547bcec2505bf00d23acdeb6064b3fe398f63/stable/kong/templates/_helpers.tpl#L67-L77):

```yaml
{{- define "kong.env" -}}
{{- range $key, $val := .Values.env }}
- name: KONG_{{ $key | upper}}
{{- $valueType := printf "%T" $val -}}
{{ if eq $valueType "map[string]interface {}" }}
{{ toYaml $val | indent 2 -}}
{{- else }}
  value: {{ $val | quote -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by czerasz-flaconi** [comment]
@ChrisSchreiber does my previous comment bring any clarification?

**Comment by ArgTang** [comment]
@ChrisSchreiber Do you still plan to work on this?

**Comment by ChrisSchreiber** [comment]
@czerasz-flaconi Thanks for the clarification. I agree that more flexibility is better.
@ArgTang I'm working on an update now.

**Comment by ChrisSchreiber** [comment]
it looks like this is already be handled by extraEnv

**Pull request closed without merging**
