### PR TITLE
Fix fluentd-elasticsearch extraVolumeMounts

### PR DESCRIPTION
**Pull request by ishabalin**
`.Values.extraVolumeMounts` is rendered into `ports:` section resulting in broken daemon set declaration.

### CODE REVIEW

**Comment by monotek** [comment]
Please resolve merge conflicts.

**Review by monotek — COMMENTED** [review]
/approve

**Comment by ishabalin** [comment]
Doh! It's just made things worse.

**Comment by ishabalin** [comment]
Started from scratch #7512.

**Pull request closed without merging**
