### PR TITLE
[incubator/couchdb] Promote CouchDB chart to stable

### PR DESCRIPTION
**Pull request by kocolosk**
#### What this PR does / why we need it:

* Updates one container image default tag to clear out a few CVEs
* Adds some keywords
* Moves the chart to stable

#### Special notes for your reviewer:

I've run through the technical requirements and documentation requirements checklists and believe that the chart meets the large majority of the requirements. Some of the [labeling guidelines](https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md) seem inconsistent with current practice for most stable charts and so I've stuck with what seems to be the _de facto_ standard.

The CouchDB chart has been baking in the incubator for a little over a year now and has seen a [healthy progression of fixes and enhancements](https://github.com/helm/charts/commits/master/incubator/couchdb). There's always more we can do, but I'm wondering if we can work out of `stable` now.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
you deprecate the chart in incubator and create a new one in the stable, but the incubator should stay there and set as deprecated 
please follow: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by kocolosk** [comment]
Ooh thanks - I failed to find that documentation.

**Comment by kocolosk** [comment]
Thanks for the tip @cpanato, I think this updated version of the PR follows the documented promotion process now.

**Comment by kocolosk** [comment]
Hi @sameersbn, just following the bot's guidance to assign you here, hopefully that's correct.

**Comment by kocolosk** [comment]
Just wondering if there's anything else I needed to do to advance this PR, thanks. It looks `XL` but is largely just a promotion to stable.

**Comment by jdmintz** [comment]
Would really love to use this in production but need it to be in stable first :(

**Comment by cpanato** [comment]
@kocolosk all files should continue in the incubator, you just set the deprecate flag and the documentation

**Comment by kocolosk** [comment]
@cpanato I'm pretty sure that's what I did in 504e6ecb. Did I screw something up elsewhere?

**Comment by cpanato** [comment]
@kocolosk all good my bad

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
