### PR TITLE
[stable/prometheus-operator] Ensure all rules can be toggled

### PR DESCRIPTION
**Pull request by sczizzo**
#### Rationale

We're migrating from the [`coreos/prometheus-operator` chart](https://github.com/coreos/prometheus-operator/tree/v0.29.0/helm), using the Helm values to slowly enable features as we move along. In testing this migration we've noticed that some PrometheusRule resources are created that we wouldn't expect, and there is no way to disable them.

This PR allows users to toggle individual rules that previously lacked their own configuration option. By default, these options are enabled (`true`), so the behavior is backwards-compatible.

#### Notes

These rules were introduced in #21248.

I found that `hack/sync_prometheus_rules.py` generates lots of changes even on the `master` branch. I've updated the script to reflect this PR, and I ran it against my branch to ensure it would generate the same predicates, but I have not committed the other changes it would make. Much of this would seem to be the result of the namespace override introduced in #22288.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by sczizzo** [comment]
Rebased and re-bumped chart version.

**Comment by sczizzo** [comment]
Looks like maybe an intermittent issue? I'll try retesting

**Comment by sczizzo** [comment]
Maybe third time's the charm? Retesting...

**Comment by sczizzo** [comment]
Welp, @vsliouniaev any guidance here?

Reading through the [test results](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/22879/pull-charts-e2e/1275116863935746053/), I see some issues with scheduling, which I would wager are more an issue with the build system than my changes here.

**Comment by sczizzo** [comment]
I've reported issues with the test infrastructure in the Kubernetes Slack `#charts` channel.

**Comment by sczizzo** [comment]
Apologies for the at-mention, but @scottrigby I see you've helped with the test infrastructure in the past. Would you be able to assist? The repo has multiple Prometheus Operator PRs failing at the moment (e.g. #22918).

**Comment by scottrigby** [comment]
The connection issue should have been fixed a few weeks ago. Let's retry
/test pull-charts-e2e

**Comment by scottrigby** [comment]
Tests passed. Re-adding `lgtm` from @vsliouniaev in this comment https://github.com/helm/charts/pull/22879#issuecomment-647369764
/lgtm

**Pull request merged**
