### PR TITLE
Bump drupal, joomla, mediawiki, owncloud, phpbb, testlink and wordpre…

### PR DESCRIPTION
**Pull request by dgonzalezruiz**
…ss charts

### CODE REVIEW

**Comment by dgonzalezruiz** [comment]
I signed it!

**Comment by dgonzalezruiz** [comment]
I fixed that. Please recheck.

**Review by chrislovecnm — CHANGES_REQUESTED** [review]
So either we need different commits or different PRs :)  Because if we have to back out any change, we cannot cherry pick :(

@viglesiasce thoughts?

**Comment by viglesiasce** [comment]
@dgonzalezruiz yes please. Can you chop this up into different PRs so that its easier and more efficient to test and merge them.

cc @prydonius

**Comment by viglesiasce** [comment]
Closing this as it needs to be split up per https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart

**Pull request closed without merging**
