### PR TITLE
[stable/collabora-code] make liveness and readiness probe configurable

### LINKED ISSUE #13309: [stable/collabora-code] Configurable liveness and readiness probes
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

- Describe *in detail* the feature/behavior/change you'd like to see.

Configurable liveness and readiness probe, like, for example in the mariadb chart: 

https://github.com/helm/charts/blob/master/stable/mariadb/templates/master-statefulset.yaml

**Which chart**:

collabora-code

**What happened**:

Liveness probe fails on my cluster because `initialDelaySeconds` value is too low.

**What you expected to happen**:

Liveness probe doesn't fail

### PR DESCRIPTION
**Pull request by mrtndwrd**
#### What this PR does / why we need it:

See #13309 

#### Which issue this PR fixes

  - fixes #13309

#### Special notes for your reviewer:

@chrisingenhaag please review

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by chrisingenhaag** [comment]
Hi @mrtndwrd ,
thx for your patch. But as you see there are some issues with your commits. Can you please rebase to one commit and sign-off it?

**Comment by mrtndwrd** [comment]
Some weird stuff happened because I had to ammend my commits to use `--signoff`. Not sure how I can amend  8a78a39 to add the signoff option, though... Any advice?

**Comment by chrisingenhaag** [comment]
> Some weird stuff happened because I had to ammend my commits to use `--signoff`. Not sure how I can amend [8a78a39](https://github.com/helm/charts/commit/8a78a392b238dd67169c22ce89d663fcf86eed0e) to add the signoff option, though... Any advice?

You should be able to rebase your branch and squash all commits to a single one, and then commit with ammend and sign-off + git force push.

**Pull request merged**
