### PR TITLE
Fix #10921

### LINKED ISSUE #10921: [stable/nginx-ingress] Disable controller-service on controller kind is specified as DaemonSet and useHostPort is true
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT/FEATURE REQUEST ...depends

**Version of Helm and Kubernetes**: Helm: v2.12.1;  Kubernetes: v1.13.2

**Which chart**: [stable/nginx-ingress]

**What happened**: 
**What you expected to happen**: When the controller kind is specified as DaemonSet and useHostPort is set to true, there is no need to spin up a service of type NodePort or LoadBalancer, or at least you should be able to disable this option.

### PR DESCRIPTION
**Pull request by msschl**
Reopen #11911

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
/ok-to-test

You will need to handle the git conflicts before we will be able to merge this in.

**Comment by msschl** [comment]
@ChiefAlexander done

**Pull request merged**
