### PR TITLE
Add support for AWS Secrets Manager

### PR DESCRIPTION
**Pull request by kurtmc**
**What this PR does / why we need it**:
Adds support for AWS Secrets Manager: https://concourse-ci.org/creds.html#asm

### CODE REVIEW

**Comment by william-tran** [comment]
@kurtmc can we call it `credentialManager.awsSecretsManager`? I should have asked for the same with SSM :S

**Comment by kurtmc** [comment]
@william-tran Done. Is it ok for me to rebase this pull request so that there is no conflict?

**Comment by william-tran** [comment]
YEs, please rebase, also bump the minor version of the chart instead as this is a new feature

**Comment by kurtmc** [comment]
@william-tran Done.

**Comment by william-tran** [comment]
thanks @kurtmc!

**Pull request merged**
