### PR TITLE
stable/jenkins update kubernetes plugin to 1.25.1, add 'events' r…

### PR DESCRIPTION
**Pull request by quarkie**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
update kubernetes plugin to 1.25.1
add 'events' resource to rbac which is required by the k8s plugin 1.25.1

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by njtman** [comment]
Hi @quarkie thank you for submitting this PR.  I'm see lots of errors in Jenkins because the service account doesn't have access to the `events` resource.  Reviewers - please approve and merge this in so a new chart can be released.

**Review by torstenwalter — COMMENTED** [review]
/ok-to-test

**Comment by torstenwalter** [comment]
@quarkie could you resolve merge conflicts?

**Comment by quarkie** [comment]
Hi, will resolve them tomorrow morning.

**Comment by quarkie** [comment]
resolved merge commits and rebased. As this is my first PR since years  i hope everything i do is correct :P if not please be kind with me  :)

**Comment by torstenwalter** [comment]
@quarkie Looks pretty good! Could you add an entry to CHANGELOG.md?
https://github.com/jenkinsci/kubernetes-plugin/releases/tag/kubernetes-1.25.1 is the reference for the events watch verb.

**Comment by quarkie** [comment]
of course, i was not sure , if the changelog entry would be generated somehow.

**Comment by torstenwalter** [comment]
@quarkie Thanks you for the improvement.

**Comment by njtman** [comment]
Thanks everyone for push this out

**Pull request merged**
