### PR TITLE
[stable/datadog] Set kube-state-metrics to actual version

### PR DESCRIPTION
**Pull request by eigokor**
Set kube-state-metrics to actual version 0.2.4

### CODE REVIEW

**Review by mgoodness — DISMISSED** [review]
Need a rebase. Also, chart version must be bumped.

In the future, please grant maintainers push access to your forks.

**Comment by viglesiasce** [comment]
cc @hkaj @irabinovitch

**Comment by hkaj** [comment]
Thanks for the ping @viglesiasce 
@eigokor Thanks for the update. Could you bump to 0.3.0 while you're at it? It went out 2 weeks ago: https://github.com/kubernetes/charts/commit/7b1a63a1c14e5fb67375d5c8dfbedab0c0753fb9

**Comment by mgoodness** [comment]
Please address comments within seven days or we'll close as stale.

**Comment by hkaj** [comment]
0.3.1 is out btw: #2002

**Pull request merged**
