### PR TITLE
[stable/kibana] Fix indent level in initContainers

### PR DESCRIPTION
**Pull request by donbowman**
When .Values.initContainers are used in conjunction with
.Values.dashboardImport, they both create initContainers.
These need to nest at the same level in the resulting yaml.

Signed-off-by: Don Bowman <db@donbowman.ca>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ x] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by cpanato** [comment]
@donbowman can you add a test that set a init container?

**Comment by donbowman** [comment]
> @donbowman can you add a test that set a init container?

gladly, but can you point me in the right direction? the existing tests seem to just run lint afaict. Am i missing something?

**Comment by cpanato** [comment]
@donbowman here https://github.com/helm/charts/tree/master/test#providing-custom-test-values

**Comment by donbowman** [comment]
> @donbowman here https://github.com/helm/charts/tree/master/test#providing-custom-test-values

ok i believe this done.

**Comment by compleatang** [comment]
Note this is a duplicate of #11324

**Comment by compleatang** [comment]
#11324 has been merged so this can be safely closed.

/close

**Comment by donbowman** [comment]
closed by

**Comment by donbowman** [comment]
closed by https://github.com/helm/charts/pull/11324

**Pull request closed without merging**
