### PR TITLE
Fix a couple version numbers in the kong README

### PR DESCRIPTION
**Pull request by stackedsax**
#### What this PR does / why we need it:
Just some housekeeping on the kong README.  

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

Fixing a broken link and some version numbers not quite up to date.

#### Special notes for your reviewer:
I didn't think I needed to bump the version for these changes, but let me know if you'd like me to.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by hbagdi** [comment]
@stackedsax Could you please take care of CI?

**Comment by stackedsax** [comment]
@hbagdi should just need the appropriate labels now.

**Review by hbagdi — APPROVED** [review]

**Comment by hbagdi** [comment]
@stackedsax Thanks for the updates!

**Pull request merged**
