### PR TITLE
[stable/fluent-bit] Add ignore_older parameter support for tail input…

### PR DESCRIPTION
**Pull request by pmorillon**
… plugin

#### Is this a new chart
No

#### What this PR does / why we need it:

This MR add support for `ignore_older` parameter for tail input plugin introduced in fluent-bit 0.14.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by Towmeykaw** [comment]
Shouldn't the default value be empty? Seems strange to mix a boolean with a string.

**Comment by pmorillon** [comment]
@Towmeykaw, agree with that. It's now fixed.

**Comment by Towmeykaw** [comment]
Shouldn't the default value be null?

**Comment by pmorillon** [comment]
`null` seems never used in this chart, always empty string : 

```yaml
#...
filter:
  mergeLogKey: ""
#...
```

```
{{- if .Values.filter.mergeLogKey }}
        Merge_Log_Key       {{ .Values.filter.mergeLogKey }}
{{- end }}
```

so i applied the same rule. Is null usage the rule to follow ? (it's my first contribution to this repo).

**Comment by Towmeykaw** [comment]
That's true, might be good to stick to it then 👍

**Pull request merged**
