### PR TITLE
[stable/ignite] Added extra parameter for region settings in ConfigMap

### PR DESCRIPTION
**Pull request by natebwangsut**
#### Is this a new chart

No

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

- Address wrong ConfigMap directory on Ignite 2.7.0++ 
- Added option for DataRegion settings via value file

#### Special notes for your reviewer:

Feedbacks are welcome.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by natebwangsut** [comment]
Any update for this PR?...

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
