### PR TITLE
jenkins: add optional LoadBalancerIP option.

### PR DESCRIPTION
**Pull request by sundbp**
To support running the master on a pre-allocated external IP we need to expose
the `loadBalancerIP` part of the service template.

### CODE REVIEW

**Comment by lachie83** [comment]
Please bump the chart version

**Comment by sundbp** [comment]
Ok, will do.

**Comment by unguiculus** [comment]
Marking this as stale. Please update the PR within one week.

**Comment by sundbp** [comment]
Indeed. It slipped my mind. I'll try to get to it.

**Comment by viglesiasce** [comment]
Bumped it meself. Thanks @sundbp!

**Comment by sundbp** [comment]
Thank you - and sorry for being slow!

**Pull request merged**
