### PR TITLE
Fix markdown sintax table at Configuration section

### PR DESCRIPTION
**Pull request by alexsandro-xpt**
The Configuration table was dropped, now it's is fixed.

### CODE REVIEW

**Comment by juan131** [comment]
Hi @alexsandro-xpt 

Thanks for the fix!! Could you please bump the fix version of the chart? Even those changes that only affect the **README.md** should bump that version

**Comment by juan131** [comment]
I'm still missing bumping the patch version of the chart...

**Comment by alexsandro-xpt** [comment]
@juan131 how to do that?

**Comment by juan131** [comment]
You need to bump the `version` available at **Chart.yaml** file.

**Comment by juan131** [comment]
You need to bump the `version` available at **Chart.yaml** file.

**Comment by juan131** [comment]
You need to bump the `version` available at **Chart.yaml** file.

**Comment by juan131** [comment]
You need to bump the `version` available at **Chart.yaml** file.

**Comment by juan131** [comment]
Hi @alexsandro-xpt 

It seems you did not sign your last commits. Please note that you need to sign every commit to be able to contribute. 

On the other hand, could you rebase your branch with latest changes on master? It seems there's a conflict on your PR

**Pull request closed without merging**
