### PR TITLE
[stable/nfs-client-provisioner] Fix typo in README

### PR DESCRIPTION
**Pull request by zerda**
#### What this PR does / why we need it:
Parameter `storageClass` is misspelled in README, It got me confused for a moment.

#### Which issue this PR fixes
- None

#### Special notes for your reviewer:
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@zerda Please sign your commits and bump the chart version like it says in the check-list in the issue-template.

**Comment by zerda** [comment]
@davidkarlsen Done. :)

**Pull request merged**
