### PR TITLE
[stable/ingressmonitorcontroller] Image Bump and Config Map updates

### PR DESCRIPTION
**Pull request by jseiser**
No

#### Which issue this PR fixes
Updated image to the latest version, and updated configMap to handle the creationDelay and resyncPeriod options

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ X] Chart Version bumped
- [ X] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by jseiser** [comment]
I'm not sure how to read the output from that test failure?

**Comment by jseiser** [comment]
Anyone able to help me understand this?

> pull-charts-e2e — Job failed.

**Review by rasheedamir — APPROVED** [review]

**Pull request closed without merging**
