### PR TITLE
[stable/phabricator] Bump Phabricator version 

### PR DESCRIPTION
**Pull request by juan131**
- Update Phabricator image version to "2017.02-r0".
- Update chart to "0.4.2".

### CODE REVIEW

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Comment by viglesiasce** [comment]
@juan131 is this a major upgrade to the phabricator version or is the year irrelevant wrt major/minor version?

**Comment by prydonius** [comment]
@juan131 looks like MariaDB dependency needs to be updated, please update requirements.yaml version to 0.5.x

**Comment by juan131** [comment]
@viglesiasce the year is irrelevant. They release a new version every week and the version is built as year.week

**Comment by juan131** [comment]
@prydonius MariaDB version updated.

**Review by prydonius — COMMENTED** [review]
Thanks @juan131

**Pull request merged**
