### PR TITLE
[stable/atlantis] Add support for extraVolumes and extraVolumeMounts

### PR DESCRIPTION
**Pull request by eddieramirez**
Signed-off-by: Eddie Ramirez <eddieramirez@me.com>

#### What this PR does / why we need it:
Allows specifying `extraVolumes` and `extraVolumeMounts`.

Use Case: retrieving secrets from Azure KeyVault using [Azure/kubernetes-keyvault-flexvol](https://github.com/Azure/kubernetes-keyvault-flexvol#use-the-keyvault-flexvolume).

In tandem with overriding `command` , we can retrieve secrets from Azure KeyVault.

```
extraVolumes:
  - name: keyvault
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"
        keyvaultname: "testkv"
        keyvaultobjectnames: "ATLANTIS_GH_USER;ATLANTIS_GH_SECRET;ATLANTIS_GH_TOKEN;ARM_ACCESS_KEY"
        keyvaultobjecttypes: "secret;secret;secret;secret"
        resourcegroup: "test-resource-group"
        subscriptionid: "00000000-0000-0000-0000-000000000000"
        tenantid: "00000000-0000-0000-0000-000000000000"

extraVolumeMounts:
  - name: keyvault
    mountPath: "/kvmnt"
    readOnly: true

command:
  - "/bin/sh"
  - "-c"
  - "export ATLANTIS_GH_USER=/kvmnt/ATLANTIS_GH_USER; export ATLANTIS_GH_SECRET=$(cat /kvmnt/ATLANTIS_GH_SECRET); export ATLANTIS_GH_TOKEN=$(cat /kvmnt/ATLANTIS_GH_TOKEN); export ARM_ACCESS_KEY=$(cat /kvmnt/ARM_ACCESS_KEY); docker-entrypoint.sh server"
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by eddieramirez** [comment]
Any update on this? Thanks!

**Comment by zanhsieh** [comment]
@jkodroff
@callmeradical
@lkysow
@jeff-knurek
@sstarcher
@anubhavmishra
Would you mind to LGTM this please? Thank you.

**Pull request merged**
