### PR TITLE
[incubator/neo4j] Expose `storageClass` for neo4j.

### PR DESCRIPTION
**Pull request by gyliu513**
Expose `storageClass` for neo4j, this can enable some 3rd party API get this key from `values.yaml`.

/cc @prydonius @unguiculus @mgoodness comments?

### CODE REVIEW

**Comment by prydonius** [comment]
@gyliu513 this needs a version bump.

As discussed in Slack, I'm not 100% sure this is the route we want to go down. That said, I need to think more about how this affects charts if we start uncommenting all values and default to empty if a value used to be commented. I agree, though, that if we can have all values uncommented then that makes parsing easier.

We can merge this change, and we can follow up on it.

**Comment by gyliu513** [comment]
Fixed part of https://github.com/kubernetes/charts/issues/2116

**Pull request closed without merging**
