### PR TITLE
[stable/datadog] Add options to set pod and container securityContext

### LINKED ISSUE #16353: [stable/datadog] container security context
The new Network Performance feature requires setting some container `securityContext.capabilities` - they are shown here under the "kubernetes" tab https://docs.datadoghq.com/graphing/infrastructure/network_performance_monitor/?tab=kubernetes

Currently only pod securityContext is exposed through values, not container securityContext.

Could we expose container securityContext as an optional values?

Thanks!

### PR DESCRIPTION
**Pull request by coreypobrien**
#### Which issue this PR fixes
  - fixes #16353

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by coreypobrien** [comment]
@hkaj @irabinovitch @charlyf @mfpierre @clamoriniere @xlucas
Anyone available to take a look at this? Thanks

**Comment by CharlyF** [comment]
Hey @coreypobrien - Sorry for the delay, and thanks for the PR!
We are currently working on a major revamp of the chart but I will sync with the team asap to see how we can include your suggestion.

Best,
.C

**Comment by coreypobrien** [comment]
Thanks for the update @CharlyF . Does that mean this won't be merged?

**Comment by CharlyF** [comment]
This seems like a reasonable implementation, I have to double check with the team to confirm how to best integrate your change in this chart (or the new one).

**Comment by coreypobrien** [comment]
Sounds good. Is there a branch somewhere you're working on where I could take a look and help with anything?

**Comment by CharlyF** [comment]
Hey @coreypobrien - I wanted to circle back on this.
I think my colleague has not pushed his branch yet so we can still get changes in.
I was reviewing your PR and per the [original issue](https://github.com/helm/charts/issues/16353) it seems like the need was solely for the system-probe container (which indeed requires extra capabilities given that it runs bpf code).
Could you let me know why you want to add the security context option to all containers ?
I am afraid that this might be error prone in some cases as we can't easily run with other users than the one configured in the Dockerfile for the agent process (and the other agents').

Best,
.C

**Comment by coreypobrien** [comment]
The original use case was that, but when I started down the path I realized there were a lot of other security settings that users focused on that would want to use like `allowPrivilegeEscalation` that are going to be useful on more than just the daemonset nodes and on both the pod and container contexts. So instead of trying to solve all of them ideally, I went with allowing the possibility of someone solving their specific problems.

My specific desires to to reduce privileges for places that the agent needs _less_ permissions like when it is in cluster-agent or cluster-check or apm-only mode.

**Comment by CharlyF** [comment]
@coreypobrien I see, thank you for clarifying.
We are ok with merging your change - However could you please add a disclaimer in the README for these options ? We want to be extra transparent as to when and how to use them, to avoid users configuring them thinking the agent can run with a different UID or with a limited context.

**Comment by zanhsieh** [comment]
@coreypobrien 
Would you mind to rebase and resolve conflict files please? Thank you.
stable/datadog/Chart.yaml
stable/datadog/README.md
stable/datadog/templates/cluster-agent-deployment.yaml

**Comment by CharlyF** [comment]
Also @coreypobrien if you can please address my comment: https://github.com/helm/charts/pull/17274#issuecomment-539074950 
that would be great

**Comment by clamoriniere** [comment]
Hi @coreypobrien 
May I ask you to rebase your PR, and look at the @CharlyF  comment https://github.com/helm/charts/pull/17274#issuecomment-539074950 if you are still interested to have the feature you have implemented.

**Comment by icelynjennings** [comment]
Merged in https://github.com/DataDog/helm-charts/pull/83.

**Pull request closed without merging**
