### PR TITLE
servie--->service

### PR DESCRIPTION
**Pull request by yjl-lgx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yjl-lgx** [comment]
servie---->service

**Comment by carrodher** [comment]
Now burrow is stable (https://github.com/kubernetes/charts/tree/master/stable/burrow) should we apply these changes in the stable one and close this PR?

**Comment by unguiculus** [comment]
@carrodher I'm closing this. We don't update deprecated charts.

**Pull request closed without merging**
