### PR TITLE
[stable/grafana] Be able to override port names on service and pod

### PR DESCRIPTION
**Pull request by samwyma**
Signed-off-by: Sam Wyma <sam@landinsight.io>

#### Is this a new chart
No

#### What this PR does / why we need it:
Adds ability to override port names. Our use case for this is to be able to have the ports available in Istio (see [here](https://istio.io/docs/setup/additional-setup/requirements/))

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@samwyma 
Please complete DCO signoff. Thank you.

**Comment by samwyma** [comment]
@zanhsieh Done. Sorry about that

**Comment by zanhsieh** [comment]
@samwyma Please check again. Ty.

**Comment by samwyma** [comment]
@zanhsieh Issue fixed. Cheers

**Pull request merged**
