### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by alwqx**
recursivly --> recursively
differnt --> different

### CODE REVIEW

**Comment by mattfarina** [comment]
@adolphlwq Thanks for the contribution. Chart versions are immutable. Even documentation changes need to have the version incremented. Could you please increment the patch part of the version in the Chart.yaml file.

**Comment by alwqx** [comment]
> increment the patch part of the version in the Chart.yaml file.

@mattfarina Done.

**Comment by lachie83** [comment]
/cc @lead4good 

This chart no longer appears to install correctly. Can you please take a look

**Pull request closed without merging**
