### PR TITLE
[incubator/couchdb] Increase default passwd length

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

By default, `couchdb` will generate a secrets for a default
username/password. Previously, the default length for those was 10
chars. Bump the default password length to 20 as there's no real cost,
and it provides slightly more security.

I tested with `kubectl get secrets RELEASE_NAME -o json | jq
.data.adminPassword | sed 's/"//g' | base64 --decode` to verify the
password was previously 10 chars, and is now 20 charts.

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/assign @seanknox
/assign @kocolosk 
thanks :)

**Comment by mattjmcnaughton** [comment]
Necessary password length is def a bit up for debate so no worries if y'all feel differently and want to close this :) Mostly I just submitted it because 10 seemed a little short to me, and there's no harm to increasing it.

**Comment by kocolosk** [comment]
I have no problem with this.

**Pull request merged**
