### PR TITLE
[stable/airflow] NOTES.txt it should look for the "-web" service

### PR DESCRIPTION
**Pull request by jjmata**
#### What this PR does / why we need it:

Avoids confusion when installing.

#### Special notes for your reviewer:

None.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

### CODE REVIEW

**Comment by cpanato** [comment]
@jjmata please sign the DCO and bump the chart version, thanks!

**Comment by gsemet** [comment]
Hi. Can you rebase and update the version please ?

**Comment by MahaGamal** [comment]
> Signed-off-by: Juanjo Mata [jjmata@jjmata.com](mailto:jjmata@jjmata.com)

Signed-off using these commands  https://github.com/helm/charts/pull/12367/checks?check_run_id=80655582

**Comment by gsemet** [comment]
You need to update the version please

**Comment by cpanato** [comment]
@jjmata please sign the DCO and bump the chart version

**Pull request closed without merging**
