### PR TITLE
add missing newlines

### LINKED ISSUE #17738: [stable/chart/metallb] missing newline
When parsing metallb with `helm template` and then deploy them with
`cat * | kubectl apply -f -` , the following errors occur:

`error: error validating "STDIN": error validating data: [ValidationError(ServiceAccount): unknown field "roleRef" in io.k8s.api.core.v1.ServiceAccount, ValidationError(ServiceAccount): unknown field "subjects" in io.k8s.api.core.v1.ServiceAccount]; if you choose to ignore these errors, turn validation off with --validate=false`

`error: error validating "STDIN": error validating data: ValidationError(ClusterRole): unknown field "spec" in io.k8s.api.rbac.v1.ClusterRole; if you choose to ignore these errors, turn validation off with --validate=false
`

This is caused by missing newlines through `end -` in the helm template.

### PR DESCRIPTION
**Pull request by rdxmb**
fixes https://github.com/helm/charts/issues/17738

### CODE REVIEW

**Comment by rdxmb** [comment]
no stale, please. 

Can this be merged?

**Comment by zanhsieh** [comment]
@rdxmb 
Sorry for waiting. Could you resolve the conflict file again one last time please?
stable/metallb/Chart.yaml

**Comment by rdxmb** [comment]
done

https://github.com/helm/charts/pull/17739/checks?check_run_id=295073866 -> can this be done on Github?

**Comment by zanhsieh** [comment]
@rdxmb 
I don't think so. The contributor needs to present his/her willingness of contribution his/her work to public community, not like Facebook - if the user doesn't say so then they take it w/o warning.

**Comment by rdxmb** [comment]
@zanhsieh 
Thanks, but that was not the question. I just wanted to give the willingness by this GUI and not again have to clone the whole project, commit, .... just for one line.

**Comment by zanhsieh** [comment]
@rdxmb 
Could you sign DCO please? Instructions on the bottom of this PR page. Click Details next to DCO.

**Comment by rdxmb** [comment]
done

**Comment by zanhsieh** [comment]
not stale

**Comment by davidkarlsen** [comment]
@danderson PTAL?

**Review by danderson — APPROVED** [review]

**Pull request closed without merging**
