### PR TITLE
[incubator/vault] Update owners

### PR DESCRIPTION
**Pull request by jbialy**
#### What this PR does / why we need it:

Adding myself to the OWNERS file as a maintainer.

#### Special notes for your reviewer:

My past PRs to the Vault chart:

https://github.com/helm/charts/pull/13371
https://github.com/helm/charts/pull/9462
https://github.com/helm/charts/pull/9429
https://github.com/helm/charts/pull/5974
https://github.com/helm/charts/pull/5694

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jbialy** [comment]
Call for maintainers: https://github.com/helm/charts/issues/13869

**Comment by maorfr** [comment]
/assign
/ok-to-test
/lgtm

thanks for stepping up and good luck!

**Pull request merged**
