### PR TITLE
[stable/influxdb] Refactor configmap by using implicit default values

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:

Instead of having every default value explicitly described in the values file and put into the corresponding configmap(s), just use defaults and adjust these values as needed. This is beneficial because overtime defaults may change and it is duplicate work to match it in the values file. Furthermore documenting configurable values in the README will be much more feasible. This PR also removes the now defunct admin section of the config.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by naseemkullah** [comment]
/retest
🤞

**Comment by naseemkullah** [comment]
Don't know why e2e is failing, going to try to open a new PR...

**Comment by naseemkullah** [comment]
https://github.com/helm/charts/pull/20787 created

**Comment by Aisuko** [comment]
> Don't know why e2e is failing, going to try to open a new PR...

I hit this issue several times. I saw the log that maybe the reason is the script was run in prior to connecting to the cluster.

**Comment by naseemkullah** [comment]
Actually there was an issue in my PR 😬 ...fixed in #20787

**Pull request closed without merging**
