### PR TITLE
[stable/cluster-autoscaler] Adds support for affinity to the cluster autoscaler

### PR DESCRIPTION
**Pull request by philipbjorge**
Adds the ability to specify affinity instead of just nodeSelector

### CODE REVIEW

**Review by viglesiasce — CHANGES_REQUESTED** [review]
Can you add this value to the values.yaml as well but leave it commented out.

**Review by viglesiasce — DISMISSED** [review]
Also needs a version bump in the Chart.yaml

**Comment by philipbjorge** [comment]
@mgoodness @viglesiasce -- Took care of the feedback :)

**Pull request merged**
