### PR TITLE
[stable/openvpn] Make openvpn work in Headless Services and HostPort mode

### PR DESCRIPTION
**Pull request by zzh8829**
Signed-off-by: Zihao Zhang <zzh8829@gmail.com>

#### What this PR does / why we need it:
There are two additions in this PR
1. Headless Service
This is [documented here](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). Kubernetes creates headless service for `ClusterIP` type service when the `ClusterIP` field is set to `None`. 

2. HostPort
When running openvpn without cloud load balancer (baremetal or whatever reason), we can only expose the service via NodePort. But this is not very practical because firstly openvpn commonly uses port 1194. Also, under many firewall configurations, random ports are often blocked. This is why I suggest adding hostport functionality to openvpn.

With these two change, openvpn can also work with [external-dns](https://github.com/kubernetes-incubator/external-dns)'s [headless mode](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/hostport.md) which is a nice addition.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by jasongwartz** [comment]
@zzh8829 thanks for the contribution!

I want to make sure I understand the use-case correctly. If I understand you, the combination of hostPort and headless service means that something like external-dns can create a DNS A-record that points to the node the OpenVPN pod is on, and using hostPort means that the port is static. If hostPort wasn’t specified (eg. using a nodePort service) then the port can only be specified in the nodePort range.

I’m not sure perpetuating the use of hostPort is a good idea - I’d rather encourage usage of nodePort, and then bake the port into the ovpn config file. That way there’s still not much user friction (the config file already has the right port, so there’s no confusion) but we avoid using the hostPort pattern which is discouraged.

The nodePort functionality already exists in this chart. The client template currently sets the port in the client config file to the value of externalPort (here: https://github.com/helm/charts/blob/master/stable/openvpn/templates/config-openvpn.yaml#L62) but we could change this to use nodePort instead if this is set.

What do you think of that? Is there a strong reason I’m missing to use hostPort over nodePort?

**Comment by zzh8829** [comment]
The only reason I have with for using hostPort is to bypass firewall restriction. Many public or corporate network only allow tcp connection to known ports. But again this can already be done with LoadBalancer mode. 
Cloud load balancer is [very expensive](https://cloud.google.com/compute/all-pricing#lb) at over $200 per year on GCP. So hostPort is a convenient way to achieve this without load balancer.

Similar usage is also implemented in charts like [prometheus](https://github.com/helm/charts/tree/master/stable/prometheus), [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) and [traefik](https://github.com/helm/charts/tree/master/stable/traefik)

**Comment by jasongwartz** [comment]
Ok - it’s not really the deployment I would choose but I understand your rationale. And I see the equivalent config in other projects, so I think it’s ok to match here. I would be extra happy if there was an inline comment or something just explaining the use-case (briefly).

**Comment by jasongwartz** [comment]
@zzh8829 can you merge latest master and update the chart version?

**Pull request merged**
