### PR TITLE
[stable/traefik] quote timeout configs in configmap

### LINKED ISSUE #14093: [stable/traefik] Timeout Parameters are not quoted in configmap
**Describe the bug**
When defining Timouts (e.g. timeouts.forwarding.dialTimeout), the value is not quoted even though it needs to be:

```
Error reading TOML config file /config/traefik.toml : Near line 78 (last key parsed 'forwardingTimeouts'): expected a top-level item to end with a newline, comment, or EOF, but got 's' instead
```

So Traefik is complaining the config(map) looks like:

```
[forwardingTimeouts]
  dialTimeout = 300s

```

instead of:

```
[forwardingTimeouts]
  dialTimeout = "300s"

```

**Version of Helm and Kubernetes**:
v2.11.0

**Which chart**:
stable/traefik

**What happened**:
Upgrade went wrong, because configs couldn't be read

**What you expected to happen**:
Timeout changes from 30s to 300s

**How to reproduce it** (as minimally and precisely as possible):
Just set the timeout values via: `--set timeouts.forwarding.dialTimeout`

**Anything else we need to know**:
a simple `| quote` would do the job.  `https://github.com/helm/charts/blob/master/stable/traefik/templates/configmap.yaml#L402`

### PR DESCRIPTION
**Pull request by alwinmarkcf**
In order to prevent:
```
Error reading TOML config file /config/traefik.toml
: Near line 78 (last key parsed 'forwardingTimeouts'): expected a
top-level item to end with a newline, comment, or EOF, but got 's'
instead
```

fixes #14093

Signed-off-by: Alwin Mark <a.mark@crowdfox.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Comment by dtomcej** [comment]
Just needs a rebase to update the chart number, and this one is good to go!

**Comment by alwinmarkcf** [comment]
rebase so please /retest

**Pull request merged**
