### PR TITLE
[stable/spring-cloud-data-flow] Remove support for rabbitmq-ha

### PR DESCRIPTION
**Pull request by lwj5**
#### Is this a new chart
No
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
rabbitmq chart supports replication since version 0.7.1, there is no longer a need to maintain two dependency in this chart.

Removed rabbitmq-HA suuport.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by chrisjs** [comment]
before ripping things like this out, we should deprecate them first.

can you provide URL(s) to documentation indicating rabbitmq-ha is deprecated in favor of rabbitmq chart ver 6+? we would need to provide solid references in a deprecation notice and assure people its a 100% drop in replacement, along with references to any migration needs.

if this is to be deprecated, the actual removal would likely occur when we move away from helm 2 and fully helm 3

**Comment by lwj5** [comment]
Hi,

Yes, deprecation notes will be important and moving from helm 2 and fully helm 3 is a good time to remove this.

As of now, the owner of rabbitmq-ha chart has no intention of migrating the chart from helm-stable and will be letting it deprecated with this repo, which will be in the start of May. I'll update when there's more info.

**Pull request closed without merging**
