### PR TITLE
[incubator/vault] parse extraContainers using tpl, to match extraInitContainers, & miscellaneous value type fixes

### PR DESCRIPTION
**Pull request by rosteroster**
#### What this PR does / why we need it:

At the moment, the Vault deployment doesn't parse extraContainers the same way extraInitContainers is and as a result, extraContainers is far less flexible.
extraInitContainers is parsed via tpl which allows for helm templating in .Values while extraContainers is parsed by toYaml which doesn't.

One thing we can do with tpl is use toYaml with it to let us use maps in .Values instead of raw strings.
One thing I learned: need to put quotes around {{ }} blocks of in our values that get passed in to tpl (ie https://github.com/helm/helm/issues/1761). This affected the default for the affinity value.

Signed-off-by: Brian Surber <bsurber120@yahoo.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by maorfr** [comment]
/lgtm

thanks for contributing!

**Comment by infa-bsurber** [comment]
Great, thanks for the review & merge.

**Comment by rosteroster** [comment]
Great, thanks for the review & merge.

**Pull request merged**
