### PR TITLE
Update CockroachDB tag to v1.1.0

### PR DESCRIPTION
**Pull request by lgo**
cc: @a-robinson

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
/ok-to-test
/release-note-none

You also have to update the Chart.yaml file. See https://github.com/kubernetes/charts/pull/1852/files for an example.

**Comment by lgo** [comment]
Done. Thanks Alex!

**Review by a-robinson — APPROVED** [review]
/lgtm
/approve no-issue

**Pull request merged**
