### PR TITLE
[stable/prometheus-operator] add chart

### PR DESCRIPTION
**Pull request by poidag-zz**
*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

### CODE REVIEW

**Comment by poidag-zz** [comment]
@unguiculus is @mgoodness the right person for this?

**Comment by unguiculus** [comment]
Have you had a look at https://github.com/coreos/prometheus-operator/tree/master/helm?

These charts are under very active development. It probalby doesn't make much sense to have another chart here.

cc @gianrubio @brancz

**Comment by poidag-zz** [comment]
@unguiculus I was not aware they were there. I thought there'd be a reason why they were not in this repo already. Happy to decline if you see no value here.

**Comment by brancz** [comment]
Thanks a lot for tagging us @unguiculus !

The ultimate goal of the helm charts in the prometheus operator repo is to have them here as well, however, the project itself as well as everything around it, is so fast moving, that it's very hard to maintain in separate repositories. When they are in the prometheus operator repo, there is little syncronization necessary.

I do want to take apart the helm charts in the Prometheus Operator repo however. Maybe this can be the start? 

@gianrubio what do you think about this? My take would be that these three charts should be easily extracted and be in the official helm charts

* node-exporter
* prometheus-operator
* kube-state-metrics
* alertmanager (created through prometheus-operator)
* prometheus (created through prometheus-operator)

Then the parts that are hard to syncronize (mostly the [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) parts) can continue to live on in the prometheus-operator repo, but the common and reusable parts can be here. (I would also hold off on the grafana chart for now as there are a lot of changes coming for v5.0)

**Comment by gianrubio** [comment]
> @gianrubio what do you think about this? My take would be that these three charts should be easily extracted and be in the official helm charts

Fully agreed, I already [had pointed](https://github.com/coreos/prometheus-operator/issues/592#issuecomment-346468179) to move prometheus-operator chart to the oficial repo. 

Seeing the current [prometheus chart](https://github.com/kubernetes/charts/tree/master/stable/prometheus/templates) I'd like to split all this templates like node-exporter, kube-state, alertmanager in new charts and leave only kube-prometheus in the prometheus-operator repo. @unguiculus what are your thoughts?

**Comment by unguiculus** [comment]
@gianrubio I agree.

**Comment by brancz** [comment]
Sounds good to me!

**Comment by prydonius** [comment]
@brancz @gianrubio as members of the Kubernetes orgs, you can add yourselves to OWNERS files to any charts you move here. This will give folks in the OWNERS files to test and approve PRs for merge, which hopefully gives you the flexibility to move faster within this repo also. If you aren't yet in the org, you can see how you can apply for membership here https://github.com/kubernetes/community/blob/master/community-membership.md. We can certainly help and sponsor new people after one or two contributions to the prometheus charts.

**Comment by brancz** [comment]
@gianrubio I understand you would like to maintain the chart in both the prometheus-operator as the "upstream" and sync changes here as a "downstream" but as part of the official helm charts. Is that correct? In that case I think we should update this PR to reflect the latest state of the chart in the upstream repo and move forward with this.

**Comment by bhack** [comment]
Any update on this?

**Comment by brancz** [comment]
cc @gianrubio

**Comment by gianrubio** [comment]
thanks for pinging me @brancz, it's ok to close this issue since there's another PR #6765 to address prom operator.

**Pull request closed without merging**
