### PR TITLE
[incubator/etcd] tidy up

### PR DESCRIPTION
**Pull request by egeland**
Some non-breaking tidy-ups of the chart.

### CODE REVIEW

**Comment by dhilipkumars** [comment]
CI is failing as the stateful set is not up in 3 mins.

**Comment by egeland** [comment]
That's weird, since I didn't really change anything that would affect it...

**Comment by dhilipkumars** [comment]
the CI needs to be fixed for Statefulset, I don't think it's because of the changes. 


/test pull-charts-e2e

**Comment by unguiculus** [comment]
The pods don't come up because storage class "anything" won't work with the beta annotation. How about leaving the storage class update to a separate PR and then do it like so: https://github.com/kubernetes/charts/pull/1332

**Comment by dhilipkumars** [comment]
Marking this as stale PR, not activity from the author

**Comment by egeland** [comment]
I'm hoping to get time to make the changes soon. 😅

**Comment by egeland** [comment]
@dhilipkumars I've updated it, and looks like it's passing now 😀

**Pull request merged**
