### PR TITLE
[stable/prometheus] use prefixURL in alertmanagers config

### PR DESCRIPTION
**Pull request by DaytonG**
When setting an alertmanager.prefixURL, I noticed that the server fails to talk to the alertmanager (a 404 is returned). Setting the path_prefix seems to avoid this.

### CODE REVIEW

**Comment by unguiculus** [comment]
Please fix your CLA so we can get this in.

**Comment by DaytonG** [comment]
I signed the CLA last night. Is there... something I'm missing to get it validated?

Edit: figured it out. First commit was the wrong email. Fixed and rebased my changes.

**Pull request merged**
