### PR TITLE
Add extraPorts option (#8945)

### LINKED ISSUE #8945: allow additional ports on the daemonset
FEATURE REQUEST:
**Version of Helm and Kubernetes**:
helm "v2.10.0"
kubernetes: 1.10.3
**Which chart**: fluent-bit

While it is possible to add additional INPUT blocks to the fluent-bit config file, it is not possible to expose additional ports on the daemonset.  This makes it hard to set up a forward block like:

```
    [INPUT]
        Name forward
        Port 5170
```

where the pods will communicate with the node local port via node IP.

### PR DESCRIPTION
**Pull request by snstanton**
Signed-off-by: Scott Stanton <scott.stanton@veeva.com>

#### What this PR does / why we need it:

This PR adds an extraPorts option that allows additional ports to be exposed by the daemonset.  This is needed to support hostPort access to a forward type input.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #8945 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
@snstanton thanks for submitting the PR - I have the same need and grateful to see what someone put this change out there.

It looks like the Chart.yaml is now in conflict (due to another PR getting merged and conflicting the chart version no doubt).  Any chance you can resolve and bump the chart version?  Hopefully one of the chart owners will take a look soon!

**Comment by unguiculus** [comment]
Please fix conflicts and bump minor version.

**Comment by snstanton** [comment]
Done.  Hopefully we can get it merged before another conflict shows up.

**Comment by snstanton** [comment]
I pulled and merged from master.  There were no changes to the chart.  What is left to do to get approval?

**Comment by billimek** [comment]
@unguiculus any chance you can take a look at this one again?

**Pull request merged**
