### PR TITLE
Adding support for custom labels on grafana svc

### PR DESCRIPTION
**Pull request by migueleliasweb**
Hey guys,

I was deploying a grafana chart another day and found out that there's no way to add custom labels to the service. I need that because I have the route53 plugin and it looks for the `dns: route53` label.

I have added in a very similar fashion as annotations a way to add custom labels to Grafana svc.

Cheers !

### CODE REVIEW

**Comment by migueleliasweb** [comment]
I'm unable to fully understand why the job failed. Apparently the PVC took too long to respond making the script failed to check the pod. My local tests show that the container fails to start until the volume is configured properly but eventually it works. I have tested deploying the chart without any extra parameters.

Any thoughts ?

**Comment by mattfarina** [comment]
@migueleliasweb I'm not sure what happened with this. Going to retest again now that #4278 has landed to try and get more details.

/retest

**Comment by migueleliasweb** [comment]
Same thing happened =/. Is there anything I can do to help ?

**Comment by unguiculus** [comment]
This is probably related to configmap mounts being read-only in 1.9.4.
See #4267

**Comment by migueleliasweb** [comment]
Thanks @unguiculus , I will wait for #4267 to be fixed :+1:  !

**Comment by unguiculus** [comment]
@migueleliasweb Could you merge in master and fix conflicts?

**Comment by migueleliasweb** [comment]
@unguiculus I'm gonna have a look now ! :+1:

**Comment by migueleliasweb** [comment]
@unguiculus Done ! Can you have a quick look ? :wink:

**Pull request merged**
