### PR TITLE
Deployment annotations

### PR DESCRIPTION
**Pull request by sandeepmendiratta**
**What this PR does / why we need it**:
Added annotations in the kubestate and server deployments. This can be used for custom annotations.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gianrubio — CHANGES_REQUESTED** [review]
Please update the Readme.md

**Comment by sandeepmendiratta** [comment]
Updated Readme.md.
/assign @gianrubio

**Review by gianrubio — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by sandeepmendiratta** [comment]
/assign @mgoodness 
Can you take a look?

**Comment by gianrubio** [comment]
This PR should be merged

**Pull request merged**
