### PR TITLE
[stable/minio] helm lint fix 

### PR DESCRIPTION
**Pull request by ahma**
#### What this PR does / why we need it:
Fix the helm3 strict lint result. 

- `[ERROR] templates/: template: minio/templates/serviceaccount.yaml:5:11: executing "minio/templates/serviceaccount.yaml" at <include "minio.serviceAccountName" .>: error calling include: template: minio/templates/_helpers.tpl:83:13: executing "minio.serviceAccountName" at <include "minio.fullname" .>: error calling include: template: minio/templates/_helpers.tpl:15:14: executing "minio.fullname" at <.Values.fullnameOverride>: map has no entry for key "fullnameOverride"
`

- `[ERROR] templates/: template: minio/templates/service.yaml:35:14: executing "minio/templates/service.yaml" at <.Values.service.externalIPs>: map has no entry for key "externalIPs"`

- `[ERROR] templates/: template: minio/templates/pvc.yaml:2:51: executing "minio/templates/pvc.yaml" at <.Values.persistence.existingClaim>: map has no entry for key "existingClaim"
`

- `[ERROR] templates/: template: minio/templates/pvc.yaml:24:14: executing "minio/templates/pvc.yaml" at <.Values.persistence.storageClass>: map has no entry for key "storageClass"
`
- `[ERROR] templates/: template: minio/templates/pvc.yaml:31:14: executing "minio/templates/pvc.yaml" at <.Values.persistence.VolumeName>: map has no entry for key "VolumeName"
`
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by ahma** [comment]
@davidkarlsen could you plesa reapprove this

**Comment by ahma** [comment]
@nitisht @krisis Could you put the `lgtm` label into this ? Thanks

**Review by nitisht — APPROVED** [review]

**Comment by ahma** [comment]
@nitisht thanks for your support, could you please to the label again. I'll try it for last ...

**Pull request merged**
