### PR TITLE
Remove AppsCode charts from stable charts

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: tamal <tamal@appscode.com>

We have decided to host our charts in our own repository and remove from stable charts to avoid confusion. Our new location: https://github.com/appscode/charts . Removed charts:

- g2
- kubed
- kubedb
- searchlight
- stash
- swift
- voyager

### CODE REVIEW

**Comment by prydonius** [comment]
Can you please follow the deprecation process outlined in the [processes](https://github.com/kubernetes/charts/blob/master/PROCESSES.md#deprecating-a-chart) doc? Each chart should be deprecated in a separate PR.

**Comment by tamalsaha** [comment]
Thanks @prydonius ! I am going to open separate pr for each one and ping to this one. I am going to leave this one open until all those are merged.

**Comment by jjo** [comment]
Some refs re: recent discussions around these charts FTR:
* [issue#4697](https://github.com/kubernetes/charts/issues/4697)
* [cncf/toc/issue#107](https://github.com/cncf/toc/issues/107)

**Comment by tamalsaha** [comment]
Deprecation notice for all AppsCode charts has been merged. Closing this issue. Thanks @prydonius @unguiculus .

**Pull request closed without merging**
