### PR TITLE
[stable/airflow] Upgrade version of default docker-airflow

### LINKED ISSUE #16257: [stable/airflow] Airflow on Minikube
**Describe the bug**
I have issues with installing Airflow on minikube, after installing the helm chart with:

    helm install --namespace "airflow" --name "airflow" stable/airflow

When everything is initialized, `kubectl get po -n airflow` returns:

```sh
NAME                                 READY   STATUS    RESTARTS   AGE
airflow-flower-7b4cbb6ff5-j9wph      0/1     Error     1          45s
airflow-postgresql-bdcb64f8d-f4qgb   1/1     Running   0          45s
airflow-redis-master-0               1/1     Running   0          45s
airflow-scheduler-86d6d9f5d-6fdg5    0/1     Error     1          44s
airflow-web-67cf9cf59c-2x8t6         1/1     Running   0          45s
airflow-worker-0                     1/1     Running   0          45s
```

The logs of the broken scheduler and the flower give the same issue with werkzeug:

```sh
...
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/usr/local/lib/python3.6/site-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package
```
This led me to the following issue <https://github.com/puckel/docker-airflow/issues/395>, which is solved by rolling back the version of `puckel/docker-airflow` to version `1.10.2`

But now the web pod is broken:

```sh
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
    import psycopg2
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
```

This leads me to <https://github.com/puckel/docker-airflow/issues/342> where is the advice to update tversion of `puckel/docker-airflow` to version `1.10.3`.

minikube version: v1.3.0
Helm: v2.14.3
kubernetes client version: v1.15.2
kubernetes server version: v.15.2

### PR DESCRIPTION
**Pull request by JWDobken**
#### What this PR does / why we need it:

The version 1.10.3 of puckel/docker-airflow has some known issues, which I found out is solved by a simple update to version 1.10.4

#### Which issue this PR fixes
  - fixes #16257

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maver1ck** [comment]
Please fix all errors and bump version.

**Comment by JWDobken** [comment]
> Please fix all errors and bump version.

done

**Comment by JWDobken** [comment]
ok.. so I only need to wait for labels?

**Comment by maver1ck** [comment]
Another conflict ?

**Comment by JWDobken** [comment]
it seemed that all was well; now also the signoff no longer works. What should I do?

**Comment by JWDobken** [comment]
Sorry, I need a little help here. I checkout the specific branch:

     $git checkout 542c5abb8a31175f4fd1547a02bfab6475c11313

The I add the sign-off signuture:

     $git commit --amend --signoff
    [detached HEAD 2736b9a2f] version bump
    Date: Fri Aug 23 12:47:28 2019 +0200
    1 file changed, 1 insertion(+), 1 deletion(-)

Now I want to push the sign-off:

     $git push --force-with-lease origin update-docker-airflow
     Everything up-to-date

And... the sign-off is still missing

**Comment by maver1ck** [comment]
Please fix all the checks.

**Comment by JWDobken** [comment]
Sorry I was not able to resolve any of the git issues I have been dealing (I really did my best).
I reforked and resolved the version bump and made a new PR: https://github.com/helm/charts/pull/16646

**Pull request closed without merging**
