### PR TITLE
[stable/jenkins] Removing Master.ContainerPort configuration

### PR DESCRIPTION
**Pull request by michelzanini**
**What this PR does / why we need it**:

As I reported in a previous pull request https://github.com/kubernetes/charts/pull/5957, the ContainerPort setting is not working properly.
If you change it to another port, Jenkins still starts on 8080 and the health check will always fail.
I have previously changed to send the ContainerPort down to the container to start Jenkins in another port, but it was suggested that instead we remove this setting, instead of allow it to be changed.

This PR make it not possible to change the port and container always run on 8080. If we want to keep this still configurable, I can revert to the previous PR.

Thanks.

### CODE REVIEW

**Comment by michelzanini** [comment]
@Nodraak,

I am replacing the previous PR with this one following the suggestion of not having a configuration to change the internal container port.

https://github.com/kubernetes/charts/pull/5957

Thanks.

**Review by Nodraak — APPROVED** [review]

**Comment by Nodraak** [comment]
I like this PR. IMO, this setting is an internal and should only be handled by Kubernetes. We only expose a Service (via Ingress) or a NodePort.

For the same reason, the `ServicePort` should probably be hardcoded too.

**Review by jlegrone — APPROVED** [review]
I'm happy with this, especially since the configuration was already failing.

**Pull request merged**
