### PR TITLE
[stable/openebs] update openebs to latest 0.8.0 release

### PR DESCRIPTION
**Pull request by prateekpandey14**
- Updated README
- Updated chart version
- Updated values.yaml
- Added analytics env var in maya-apiserver deployment

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@prateekpandey14 PTAL - the tag seems to be missing

**Review by kmova — APPROVED** [review]
/lgtm

**Pull request merged**
