### PR TITLE
Fix quote

### PR DESCRIPTION
**Pull request by azman0101**
When adding extra config 
```
{{- if .Values.cluster.config }}
{{ toYaml .Values.cluster.config | indent 4 }}
{{- end }}
```
Will produce invalide configuration
```
    gateway.recover_after_master_nodes: ${RECOVER_AFTER_MASTER_NODES:2}
    gateway.recover_after_data_nodes: ${RECOVER_AFTER_DATA_NODES:1}
    'thread_pool.bulk.queue_size: 350'
  log4j2.properties: |-
    status = error
    appender.console.type = Console

```

### CODE REVIEW

**Comment by unguiculus** [comment]
Bump for CLA check.

**Comment by jmdots** [comment]
A good pattern that you may want to follow here is the `with` statement. 
```
{{- with .Values.cluster.config }}
{{ toYaml . | indent 4 }}
{{- end }}
```

**Comment by azman0101** [comment]
@jmdots 

> A good pattern that you may want to follow here is the with statement.

`helm upgrade --install eslog ./charts/elasticsearch --namespace kube-system --set cluster.config="thread_pool.bulk.queue_size: 350" --dry-run --debug`

With this code
```
 {{- with .Values.cluster.config }}
{{ toYaml . | indent 4 }}
{{- end }}
```    

Or even this 

```
{{- with .Values.cluster.config }}
{{ . | indent 4 }}
{{- end }}
```
Generate this invalid elasticsearch configuration file in configmap
```
    gateway.recover_after_master_nodes: ${RECOVER_AFTER_MASTER_NODES:2}                                                                                                        
    gateway.recover_after_data_nodes: ${RECOVER_AFTER_DATA_NODES:1}                                                                                                             
    'thread_pool.bulk.queue_size: 350'                                                                                                                                          
           
  log4j2.properties: |-
```

**Comment by unguiculus** [comment]
cc @icereval

**Comment by unguiculus** [comment]
ping @icereval

**Comment by azman0101** [comment]
Are the pull-charts-e2e Job test new since the last merge PR ? https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/4721/pull-charts-e2e/7987/

Because, I do not think these tests have ever worked.

Charts Default number of master seems incorrect.

```I0523 18:56:37.105] [2018-05-23T18:38:26,904][WARN ][o.e.d.z.ZenDiscovery     ] [elastic-10083-1-elasticsearch-client-6864d58669-r5zt5] not enough master nodes discovered during pinging (found [[]], but needed [2]), pinging again
I0523 18:56:37.105] [2018-05-23T18:38:29,959][WARN ][o.e.d.z.ZenDiscovery     ] [elastic-10083-1-elasticsearch-client-6864d58669-r5zt5] not enough master nodes discovered during pinging (found [[]], but needed [2]), pinging again
I0523 18:56:37.106] [2018-05-23T18:38:32,970][WARN ][o.e.d.z.ZenDiscovery     ] [elastic-10083-1-elasticsearch-client-6864d58669-r5zt5] not enough master nodes discovered during pinging (found [[]], but needed [2]), pinging again```

**Comment by unguiculus** [comment]
@azman0101 Please merge in the latest master.

**Comment by unguiculus** [comment]
The chart has changed a lot in the mean time. I'm closing this as more or less obsolete.

**Pull request closed without merging**
