### PR TITLE
[stable/rabbitmq] fix typo

### PR DESCRIPTION
**Pull request by mgrachev**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Previous PR bumped version to the same as your, could you rebase and bump again version?

**Comment by rimusz** [comment]
please bump chart version to 3.5.3

**Comment by mgrachev** [comment]
@rimusz Done.

**Pull request merged**
