### PR TITLE
[stable/nfs-server-provisioner] changed statefulset to apps/v1 apVersion

### PR DESCRIPTION
**Pull request by chrisz100**
Signed-off-by: Christian Jantz <chris@level25.de>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by denysvitali** [comment]
LGTM, I'm having troubles deploying 0.3.1 on Kubernetes 1.16, this should definitely solve my issue:
```
ts=2019-11-08T11:05:42.661129012Z caller=release.go:216 component=release error="Chart release failed: nfs-server-provider: &status.statusError{Code:2, Message:\"validation failed: unable to recognize \\\"\\\": no matches for kind \\\"StatefulSet\\\" in version \\\"apps/v1beta2\\\"\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```

**Comment by chrisz100** [comment]
Guys... any update? This still not fixed is starting to make things in courses and environments kind of tricky...

**Comment by denysvitali** [comment]
To solve the issue I've create a (private) helm charts repo and added the fixed package. It works indeed. I'll keep using this workaround until this PR is approved

**Review by jlegrone — APPROVED** [review]

**Pull request merged**
