### PR TITLE
[stable/openvpn] adding ability to keep certificates in chart values

### LINKED ISSUE #7915: [stable/openvpn] ability to keep certificates in chart values
**Is this a request for help?**:no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm Client: v2.9.1, Server: v2.9.1
Kubernetes Client: v1.11.1, Server: v1.11.2"

**Which chart**:

stable/openvpn

**What happened**:

We would prefer to keep certificates in chart values rather than use persistence, since persistence adds extra complexity and area of potential issues.

Issues that we noticed already, during the testing:

1. if we use 2 replicas, sometimes one of them crashes about 6 times, then starts successfully at last. And sometimes both replicas keep crashing, because they start synchronously, and write certificates to the same location. This issue can be resolved only by removing one of the pods, then it recreates correctly.
2. when we remove openvpn chart in AKS, then install it again, installation often fails because old disk is not detached yet.

**What you expected to happen**:

We would install temporary openvpn chart, collect certificates, place them in values, and then re-install chart with new values. So, certificates would be permanent and saved in chart values.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

I will create pull request for this.

### PR DESCRIPTION
**Pull request by irozet**
#### What this PR does / why we need it:
Adds chart values to set openvpn server certificates with
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
    - fixes #7915

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

### CODE REVIEW

**Review by paulczar — CHANGES_REQUESTED** [review]
I would rather see these values be created as key:value pairs in a secret with an option to specify a secret that already exists.   you can load secrets as files in a directory.

Doing it this way will also let you load them in as full keys etc without base64 encoding them ( use helm to do the base64 calc ).

**Comment by irozet** [comment]
changed to use the secret, as you suggested. Please review

**Review by paulczar — APPROVED** [review]

**Comment by irozet** [comment]
please add /lgtm

**Comment by irozet** [comment]
@paulczar could you /lgtm this PR please?

**Pull request merged**
