### PR TITLE
[#5118] update nexus version to 3.10.0-04

### PR DESCRIPTION
**Pull request by 030**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rjkernick** [comment]
Please sign the CLA and increment the Chart.yaml version

**Comment by rjkernick** [comment]
Please fix merge conflicts

**Comment by rjkernick** [comment]
Need to merge upstream master:
```bash
git remote add upstream https://github.com/kubernetes/charts.git
git fetch upstream
git merge upstream/master
```
and then resolve merge conflicts

**Comment by 030** [comment]
When I run a helm install nexus, 3.9.0 is still installed.

The docker image that is used in the helm chart seems to be an unofficial one. What about using https://hub.docker.com/r/sonatype/nexus3/?

**Comment by rjkernick** [comment]
Did you run 'helm repo update'? Also, we have some work going into using the official image. See the conversation here: https://github.com/kubernetes/charts/pull/3617

**Comment by rjkernick** [comment]
Looks like something went wrong in the pull request. The image value was not changed: https://github.com/kubernetes/charts/blob/master/stable/sonatype-nexus/values.yaml

If you submit a new pull request. I will review it quickly

**Pull request merged**
