### PR TITLE
Kiam credential fetching smoke test

### PR DESCRIPTION
**Pull request by faarshad**
#### What this PR does / why we need it:
After kiam helm chart is deployed, currently there are no tests to validate if the pods are able to requests STS credentials. This PR will help to run `helm test RELEASE` for a  quick smoke test.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
To run the smoke test, `tests.expectedAssumedRole` need to be set to a valid value. After that, `helm test` should work like this:
```
# helm  test --cleanup kiam
RUNNING: kiam-tests
PASSED: kiam-tests
```
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by farshad-hobsons** [comment]
cc: @linki @scottrigby

**Comment by unguiculus** [comment]
The flag for enabling the test is unnecessary. Please remove it.

**Comment by farshad-hobsons** [comment]
Thanks @unguiculus - Removed the unneeded `tests.enabled`

**Comment by farshad-hobsons** [comment]
@linki, @unguiculus, @scottrigby - Thank you for looking at this.  

Unless there are some more configurations added (`sts assumable iam roles` that kiam server can assume) to testing environment, I think the following test will always fail. Is there any way to workaround this? Is there any way to not run the kiam-tests Pod during e2e?
```
I1029 17:49:53.250] Testing chart 'stable/kiam' in namespace 'presubmit-8721-15581-qcgaoeph3l-0'...
I1029 17:49:53.955] RUNNING: kiam-qcgaoeph3l-0-tests
I1029 17:49:54.191] ERROR: error validating "": error validating data: unknown object type "nil" in Pod.metadata.annotations.iam.amazonaws.com/role
W1029 17:49:54.292] Error: 1 test(s) failed
```

Also, the liveness/readiness probe failures on ` kiam-qcgaoeph3l-0-agent-g7gpw` seem to be unrelated to the changes that this PR is making. This PR does not make any functionality changes to either `kiam-agent` or `kiam-server` runtime configs.

**Comment by farshad-hobsons** [comment]
@unguiculus - Given that e2e are failing, should I try to re-add the `tests.enabled: false` key back again so that `kiam-tests` pods are never launched (by default) as part of e2e tests.

**Pull request closed without merging**
