### PR TITLE
[stable/concourse] Expose prometheus port in web service

### PR DESCRIPTION
**Pull request by richardalberto**
**What this PR does / why we need it**:
This PR exposes the prometheus port (if enabled) on the concourse web service. This enables users of the prometheus operator to create **ServiceMonitor** definitions to monitor concourse deployments.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lachie83** [comment]
cc @frodenas @viglesiasce @william-tran @nexeck

**Comment by 2color** [comment]
+1 based on the discussion in https://github.com/kubernetes/charts/pull/6422#issuecomment-405218248

**Comment by william-tran** [comment]
@richardalberto you'll also need to bump the chart version, please bump the minor version.

**Comment by richardalberto** [comment]
@william-tran ready to merge.

**Comment by william-tran** [comment]
Thanks @richardalberto @2color !

**Pull request merged**
