### PR TITLE
[stable/sealed-secrets] Add podLabels support

### PR DESCRIPTION
**Pull request by jjaniec**
Signed-off-by: Joffrey Janiec <jjaniec@student.42.fr>

No

#### What this PR does / why we need it:

Added the ability to set own pod labels to sealed-secrets deployment template

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by srueg — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]
/lgtm

**Pull request merged**
