### PR TITLE
[stable/spinnaker] Fix kubeconfig s3 bucket configuration in spinnaker chart

### LINKED ISSUE #22765: [stable/spinnaker] Do not expect volume mount for kubeconfig when using encrypted s3 bucket
**Describe the bug**
When installing the spinnaker helm chart with kubeconfig configured to use encrypted s3 bucket, the halyard pod fails still expecting the kubeconfig as kubernetes secret

> MountVolume.SetUp failed for volume "kube-config" : secret "my-kubeconfig" not found

Helm Version: v3.0.2
Kubernetes version: v1.15.11

Chart: stable/spinnaker

**What happened**:
When choosing kubeconfig source as encrypted s3 bucket, the spinnaker installation fails expecting the kubernetes secret for kubeconfig

**What you expected to happen**:
The spinnaker installation should use the s3 bucket to fetch kubeconfig and not expect k8s secret to provide the configuration

**How to reproduce it** (as minimally and precisely as possible):
Add the following kubeconfig configuration to values yaml and install the spinnaker helm chart. 

```
kubeConfig:
  enabled: true
  encryptedKubeconfig: encrypted:s3!r:us-east-1!b:mybucket!f:kubeconfig
```

**Anything else we need to know**:
This is due to an issue in the helm template which only checks `.Values.kubeConfig.enabled` to identify the source for kubeconfig as k8s secret. It should also check `.Values.kubeConfig.secretName` and this value should not be provided by default.

### PR DESCRIPTION
**Pull request by Karthik-13**
No

#### What this PR does / why we need it:
This PR fixes bug in spinnaker helm chart which expects kubeconfig secret as a volume mount even when s3 bucket is chosen as the source.

#### Which issue this PR fixes
  - fixes #22765

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by paulczar** [comment]
It's not clear to me what the error here was.  let's retry in case it was transitive.

/retest

**Comment by Karthik-13** [comment]
@paulczar the halyard-config.yaml needs to be updated as well, I believe I missed it. Before updating it, I have a query though. 
When the kubeConfig.enabled is set to false, is spinnaker still intended to pickup the config of cluster it is deployed on? It's a little confusing to me

**Comment by shubhamc183** [comment]
@Karthik-13 looks like the issue is NOT resolved yet. Volume entry is getting created.

When `kubeConfig.secretName` and `kubeConfig.secretKey ` are commented
```
kubeConfig:
  enabled: true
  #secretName: kubeconfig
  #secretKey: masterkubeconfig
  encryptedKubeconfig: encrypted:s3!r:us-east-1!b:BUCKET_NAME!f:masterkubeconfig
```

YAML generated contains
```
      volumes:
      - name: kube-config
        secret:
          secretName: my-kubeconfig
```
Not sure where exactly "my-kubeconfig" is coming from.

When `kubeConfig.secretName` = false
kubeConfig:
  enabled: true
  secretName: false
  #secretKey: masterkubeconfig
  encryptedKubeconfig: encrypted:s3!r:us-east-1!b:BUCKET_NAME!f:masterkubeconfig
```
YAML generated contains
```
      volumes:
      - name: kube-config
        secret:
          secretName: false
```

**Comment by Karthik-13** [comment]
@shubhamc183 Could you please provide more information such as your environment, app version, chart version that you are using currently?

**Comment by shubhamc183** [comment]
env: K8s, EKS
version: 2.0.0-rc9
appVersion: 1.16.2

**Pull request merged**
