### PR TITLE
[stable/opa] Add ServiceMonitor

### PR DESCRIPTION
**Pull request by yurrriq**
#### What this PR does / why we need it:
Add a ServiceMonitor template.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by timothyhinrichs** [comment]
This looks good except it's the same version as the other 2 PRs.  I presume every PR should have a unique version.

**Comment by yurrriq** [comment]
I figured I'd rebase and bump as the others get merged.

**Comment by tsandall** [comment]
@yurrriq once you resolve the conflict we can merge this.

**Pull request merged**
