### PR TITLE
Add portus chart

### PR DESCRIPTION
**Pull request by so0k**
Add Chart for a docker registry with access control managed by [Portus](http://port.us.org)

### CODE REVIEW

**Comment by so0k** [comment]
any chance someone takes a look at this? @prydonius ?

**Comment by prydonius** [comment]
@so0k any reason you haven't added a conditional dependency on MariaDB and Minio? I think that would be really useful to get this running out of the box.

@k8s-bot ok to test

**Comment by so0k** [comment]
Good point, I'll try to add that - thanks

**Comment by viglesiasce** [comment]
Marking as stale

**Comment by so0k** [comment]
Didn't have time yet to add conditional requirements, although it could be done in a subsequent PR?

**Comment by viglesiasce** [comment]
@so0k we'd really prefer to have things that can work out of the box have sane defaults before merging. I may be able to add this sometime this week.

**Review by unguiculus — CHANGES_REQUESTED** [review]
Are you going to keep come up with an update? Also, please used best practices for standard labels. Especially, the `app` label should use `name` instead of `fullname`.

See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md.

**Comment by so0k** [comment]
Ok, I had some higher priorities as the chart works as it is for us, but I will be able to complete this over the next weekend

**Comment by so0k** [comment]
@prydonius / @viglesiasce - I've added conditional support for Minio and Mariadb

**Note**: a vanilla k8s cluster will need ingress controller with TLS... 

@unguiculus - I'm confused regarding app label as I try to refer to several other stable charts and I don't see that best practice applied anywhere?
i.e:
- https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/svc.yaml

most seem to use `fullname` template.

Also, using `name` template doesn't make sense to me. selector queries will overlap if pods are not labeled with release name in `app` label if we release the same chart multiple times in the same cluster & namespace

I'll look at changing this if you can clarify how multiple releases of same chart will no cause issues.

**Comment by so0k** [comment]
I guess for selectors we use `app` as well as `release` labels.. so we would be able to use `template "name"` for the `app` label... 🤔

**Comment by unguiculus** [comment]
@so0k Best practices have not been set in stone from day one. They evolve over time. Latest best practices are reflected in the chart examples (https://github.com/kubernetes/helm/tree/master/docs/examples) and in the experience you get when creating a new chart with `helm create`with Helm 2.5+. And yes, most notably, we've started recommending `{{ template "name" . }}` for `app` labels which will require the `release` label as additional selector.

**Comment by so0k** [comment]
I'll try to change the labels in the next weekend

**Comment by unguiculus** [comment]
Closing as stale. Feel free to reopen when/if you decide to work on it again.

**Comment by rendhalver** [comment]
@so0k Do you mind if I use this as inspiration for another PR to get this working?
Or optionally do need a hand to get this one working?
We are wanting to use Portus in our environment so we will have somewhere to test it out.

**Comment by so0k** [comment]
@rendhalver yes please - we are currently moving to vmware/harbor

**Comment by rendhalver** [comment]
Yes to submitting a new PR or reopening this one @so0k?

**Comment by so0k** [comment]
you can submit a new PR please

**Comment by rendhalver** [comment]
Ok cool I will get that setup soon.
I will link it to this one so people know where it comes from.

Thanks for giving me a good start to getting it working.

**Pull request closed without merging**
