### PR TITLE
Add missing vault-addr to values file

### PR DESCRIPTION
**Pull request by AndrewCsoka**
@tuannvm @mlaccetti It seemed the VAULT_ADDR env var wasn't being set

### CODE REVIEW

**Review by mlaccetti — APPROVED** [review]
lgtm (wee one liners!)

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by AndrewCsoka** [comment]
I think this is waiting for approval from @mgoodness

Is there anything else that need's to be done?

**Comment by cpanato** [comment]
@AndrewCsoka please rebase and then sign the DCO thanks!

**Pull request closed without merging**
