### PR TITLE
[stable/sysdig] Fix 1.16 compatibility errors introduced in v1.4.19

### PR DESCRIPTION
**Pull request by nestorsalceda**
#### What this PR does / why we need it:

This PR fixes the 1.16 compatiblity errors introduced in latest revision

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x} Variables are documented in the README.md
- [x} Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by paulczar** [comment]
I would probably consider this to be a breaking change based on the fact it will stop working on older clusters.

**Comment by nestorsalceda** [comment]
Hey @paulczar, thanks for your review :)

Yes, it may be a breaking change but it will stop working only on clusters older than 1.9:

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

I mean, as long as the apps/v1 API was introduced in 1.9 we can just use the v1 API because the agent is not supported for such old versions.

Thank you again!

**Comment by paulczar** [comment]
What I meant to say was that we should probably bump the chart by a major version `v2.0.0` which is the appropriate semver thing to do on a breaking change.

**Comment by bencer** [comment]
Since this fixes a previously introduced mistake I'm not sure about bumping it to 2.0.
/lgtm
/approve

**Pull request merged**
