### PR TITLE
[stable/ark] Add init container support

### PR DESCRIPTION
**Pull request by josephgorse**
Signed-off-by: Joe Gorse <joseph.gorseiii@emc.com>

#### What this PR does / why we need it: 
This adds support for Init Containers. The Velero `add plugin` command uses init containers with a commonly mounted volume to load plugins. This PR enables users of the chart to automatically load plugins by defining an init container. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by josephgorse** [comment]
@viglesiasce

**Comment by unguiculus** [comment]
cc @domcar

**Comment by josephgorse** [comment]
@unguiculus Updated to 4.1.0 based on recent PR merge. This should still be good to go with all recent changes.

**Comment by josephgorse** [comment]
@mattfarina Are these test failures the result of a dirty test environment? It doesn't look like anything I've changed would cause these failures. Looks like there are already CRDs created in the environment before the test starts.

**Comment by mattfarina** [comment]
@josephgorse You were right about the CRDs. I removed them from CI and it passed. Out of band of the charts repo we are working on this problem.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
