### PR TITLE
[stable/prometheus-postgres-exporter] Fixes #5059, #5472, version update

### LINKED ISSUE #5059: [stable/prometheus-postgres-exporter] CrashLoopBackOf on fresh install
**BUG REPORT**

**Version of Helm and Kubernetes**:

 - Kubernetes: `1.9.4`
 - Helm: `v2.8.2`

**Which chart**:

 - `stable/prometheus-postgres-exporter`

**What happened**:

 - Pod doesn't start.  Viewing the pod with `kubectl get pods` I see that the pod is getting into a `CrashLoopBackOff` state after several unsuccessful restarts.

**What you expected to happen**:

 - Would like to see the pod start up successfully without intvervention

**How to reproduce it** (as minimally and precisely as possible):

 - Spin up Kubernetes instance, I used Minikube
 - Install configure Helm
 - `helm install stable/prometheus-postgres-exporter --name test`

**Anything else we need to know**:

 - I don't see any logs for the pod itself but can see error using `kubectl get events`, which makes it seem like there is something wrong with the manifests getting deployed but haven't found what is causing the error yet.

```
44s         5m           25        test-prometheus-postgres-exporter-7b5f9c5b47-t4wmp.1525f89e4c392cdb   Pod          spec.containers{prometheus-postgres-exporter}   Warning   BackOff                        kubelet, minikube       Back-off restarting failed container
5m          5m           1         test-prometheus-postgres-exporter-7b5f9c5b47-t4wmp.1525f8a27713dc21   Pod          spec.containers{prometheus-postgres-exporter}   Warning   Failed                         kubelet, minikube       Error: failed to start container "prometheus-postgres-exporter": Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/containers/13edcd8ee6d90110ce6fab64e90ad616961799416765166f844027b27820f478/resolv.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/209f3b964d2c905a9c516db94c0391994634ee90ee3697b303c12d6606809028/merged\\\" at \\\"/var/lib/docker/overlay2/209f3b964d2c905a9c516db94c0391994634ee90ee3697b303c12d6606809028/merged/etc/resolv.conf\\\" caused \\\"open /var/lib/docker/overlay2/209f3b964d2c905a9c516db94c0391994634ee90ee3697b303c12d6606809028/merged/etc/resolv.conf: read-only file system\\\"\""
4m          4m           1         test-prometheus-postgres-exporter-7b5f9c5b47-t4wmp.1525f8a8bd69a717   Pod          spec.containers{prometheus-postgres-exporter}   Warning   Failed                         kubelet, minikube       Error: failed to start container "prometheus-postgres-exporter": Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/containers/13edcd8ee6d90110ce6fab64e90ad616961799416765166f844027b27820f478/resolv.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/70e85fa1255be13f73ca343607c5399d9abcf034151a1388c1c4711fdfa1591c/merged\\\" at \\\"/var/lib/docker/overlay2/70e85fa1255be13f73ca343607c5399d9abcf034151a1388c1c4711fdfa1591c/merged/etc/resolv.conf\\\" caused \\\"open /var/lib/docker/overlay2/70e85fa1255be13f73ca343607c5399d9abcf034151a1388c1c4711fdfa1591c/merged/etc/resolv.conf: read-only file system\\\"\""
5m          5m           1         test-prometheus-postgres-exporter-7b5f9c5b47.1525f89b8dd5ff71         ReplicaSet                                                   Normal    SuccessfulCreate               replicaset-controller   Created pod: test-prometheus-postgres-exporter-7b5f9c5b47-t4wmp
5m          5m           1         test-prometheus-postgres-exporter.1525f89b8caace61                    Deployment                                                   Normal    ScalingReplicaSet              deployment-controller   Scaled up replica set test-prometheus-postgres-exporter-7b5f9c5b47 to 1
```

### LINKED ISSUE #5472: [stable/prometheus-postgres-exporter] ConfigMap is not used
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm v2.9.0
Kubernetes 1.10.0

**Which chart**:
`stable/prometheus-postgres-exporter`

**What happened**:
The ConfigMap included in the chart is not used/respected by the application

**What you expected to happen**:
The ConfigMap is used by the application.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy the chart (you'll be blocked by #5059, but assuming it was doing what it attempts to do, and `config.yaml` was mounted to path `/etc/config.yaml`)
2. Go to the prometheus URL, `{service-url}/metrics`
3. Look for the metrics like `pg_replication_lag` or `pg_stat_user_tables.relname`. They are not exported, even though being in the ConfigMap.

**Anything else we need to know**:
Will submit a PR soon, creating the issue for it.

### PR DESCRIPTION
**Pull request by utkuozdemir**
**What this PR does / why we need it**:
* Fixes #5059 
* Fixes #5472 
* Updates default image version for exporter

### CODE REVIEW

**Comment by unguiculus** [comment]
Please bump the chart version.

**Comment by gianrubio** [comment]
Fix the CI and we are ready to merge @utkuozdemir

**Comment by utkuozdemir** [comment]
@gianrubio done.

**Pull request merged**
