### PR TITLE
[stable/minio] fix identation for make-bucket-job

### PR DESCRIPTION
**Pull request by xaniasd**
Signed-off-by: Dimitris Stafylarakis <xanias@gmail.com>

No

#### What this PR does / why we need it:

The annotations created for the make-bucket job are wrongly indented. This PR solves this issue.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by xaniasd** [comment]
@zanhsieh updated!

**Comment by zanhsieh** [comment]
@xaniasd 
Great. Let's push ppl on the OWNER file.
@krisis
@harshavardhana
@nitisht
@wlan0
@dvaldivia
Would you guys mind to approve this PR please? Thank you.

**Pull request merged**
