### PR TITLE
[stable/ipfs] add bclermont to OWNERS

### PR DESCRIPTION
**Pull request by bclermont**
- Create the `OWNERS` file with  original author of this chart @YuviPanda (even if he did not contributed to this chart for almost 2 years).
- Add myself, @bclermont to OWNERS

Signed-off-by: Bruno Clermont <bruno@robotinfra.com>

#### Which issue this PR fixes

I'd like to become IPFS helm chart maintainer (handle stable/ipfs in #13869).
I already did some refactor and fixes (#15709) and I'm going to fix few things (For example: #16721) and we're using IPFS in production.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by maorfr** [comment]
added both owners as trusted collaborators.

once you both accept, comment with `/verify-owners`. you also need to sign the DCO.

/ok-to-test

**Comment by yuvipanda** [comment]
Hello @bclermont! I very much appreciate the ping.

Unfortunately I don't have the time to be involved in the IPFS community anymore, so I'd love to be removed from the list of maintainers. I'm glad it is getting updates though!

**Comment by bclermont** [comment]
> Hello @bclermont! I very much appreciate the ping.
> 
> Unfortunately I don't have the time to be involved in the IPFS community anymore, so I'd love to be removed from the list of maintainers. I'm glad it is getting updates though!

I removed you from the list, thanks for your initial contribution.

**Comment by maorfr** [comment]
/lgtm

thanks for getting involved!

**Pull request merged**
