### PR TITLE
[stable/grafana] Update server.persistentVolume.annotations

### PR DESCRIPTION
**Pull request by h0tbird**
- Added `server.persistentVolume.annotations` to README.
- Update template to use sprig template functions.
- Set default value to `{}` in `values.yaml`.

### CODE REVIEW

**Comment by lachie83** [comment]
@k8s-bot okay to test

**Comment by seanknox** [comment]
hmm, trying again... @k8s-bot ok to test

**Comment by seanknox** [comment]
@k8s-bot ok to test

**Comment by lachie83** [comment]
@h0tbird needs a version bump

**Comment by lachie83** [comment]
Then LGTM

**Comment by h0tbird** [comment]
Done. Thank you @lachie83

**Pull request merged**
