### PR TITLE
Merge helm/charts

### PR DESCRIPTION
**Pull request by sebgoa**
This is a PR to kick the tire on the merge of helm/charts.

History seems preserved and it was a pretty clean merge.
I kept the README from DM.

If we accept this, then we can work on the change of format in one place, as well as move on with the repository renaming.

### CODE REVIEW

**Comment by sebgoa** [comment]
The minecraft and elasticsearch-1 charts are moved to ./third_party because I did not hear back from Ben Barclay and Nick Barrett about signing the CLA.

Last remaining issue would be the commit by Paul Tiplady in the cassandra chart. I can move this one to the third_party repo as well.

Aaron Schlesinger seems to work for engine yard and should be covered by their corporate CLA.

ping @jackgr @sparkprime @technosophos

**Comment by sebgoa** [comment]
This last commit renames the manifests directory to templates.

Last remaining issue is to reformat the Chart.yam files.

**Comment by jackgr** [comment]
Nice work, @runseb!

**Comment by sebgoa** [comment]
This last commit modifies all the Chart.yaml file. Couple things to note:

1- I removed the maintainers field
2- I auto-generated the keyword based on the old description (that was fun :) ).

What is left:

1- Do we want to add a license header to all templates ?
2- Change the old DM templates to the new chart format (e.g redis, nfs..)

**Comment by jackgr** [comment]
What do you mean by `add a license header to all templates`? The [chart format](docs/design/chart_format.md) already provides for all charts to have LICENSE files.

**Comment by jackgr** [comment]
Yes, porting the old DM templates to the new chart format would be very valuable. A lot of folks are familiar with them, and porting them would help to illustrate the mapping from old to new. Not to mention, they're useful in their own right.

When porting, note that template references must now become chart references. I'm sure you know that, but as I'm in that part of the code right now, it's top of mind. :0)

**Comment by sebgoa** [comment]
@jackgr I don't think each chart can have a different LICENSE than the top license of the repo. When people sign a CLA to get their Chart in, they will agree to make it ASF v2. then the files should have a header with the copyright statement. At least that how it works with code...

**Comment by jackgr** [comment]
Good point. We may need to reexamine our assumptions about licensing.

/cc @sparkprime

**Comment by sparkprime** [comment]
We should check with legal but I think it makes sense for there to be a top level license file that applies to all the stuff under the kubernetes CLA, and then those charts don't need individual licenses (although we could still add them there if we wanted).  The third_party ones would have to have their own license files, although I believe they are all going to be the same ASF v2 license as well.  But in those cases the copyright owners would be different, so the chart.yaml should say something about that (or maybe README.md)

**Comment by jackgr** [comment]
LGTM

@sparkprime Are we good to go on legal at this point?

**Comment by sebgoa** [comment]
Little more work on this one. move the replicated service to its own chart like on kubernetes/charts/examples and moved the DM template in storage to their own chart directory.
Did a basic conversion following the replicated service example.

Untested.

Also reworked the Chart.yaml files to make the source an yaml array, otherwise `helm chart package` could not unmarshal basic string.

**Comment by jackgr** [comment]
Closes #6.

**Comment by sparkprime** [comment]
There is more to do here, Seb is going to make the PR compliant with our third_party priority.  Then we have to manually check all authors outside of third_party have a CLA via go/signcla

**Comment by jackgr** [comment]
OK. In that case, might be a good idea to put a check list at the top of the page and/or rename it as WIP. BTW, thanks for tracking the legal issues. That's a huge value add.

**Comment by sparkprime** [comment]
Here is my analysis of contributors:

People covered under Deis / Engineyard: (emails only)

gmonroy@engineyard.com
jason@slack.io (signed personal CLA using an @deis.com email)
rmocius@gmail.com (github username: rimusz, @technosophos attests works for Deis).
mfisher@engineyard.com
mbutcher@engineyard.com
icoffey@engineyard.com
sgoings@engineyard.com
mboersma@deis.com
nelluri@engineyard.com

People not covered under Deis / Engineyard, where we require both CLA and explicit consent:

Listed is email and github username, and commit if there is no CLA.

[OK] elson.rodriguez@gmail.com elsonrodriguez
[NO CLA] https://github.com/kubernetes/charts/commit/e5b87523265616b051f5d9dcf9c078bbc8925b39 paultiplady@gmail.com symmetric
[NO CLA] https://github.com/kubernetes/charts/commit/b87cd63fc1d5bdf58df7c453cf4f34a3f2d37120 radamanthus@gmail.com radamanthus
[OK] mail@wombatsoftware.de w0mbat
[OK] runseb@gmail.com rubseb

third_party contributions, for which we require neither consent nor CLA:

[NO CLA] https://github.com/kubernetes/charts/commit/7d511134a8332fa8b9e9809b5a16935d0c586c06 nick@edited.com (github username unknown)
[OK] benbarclay@gmail.com benbarclay

**Comment by technosophos** [comment]
`rmocius@gmail.com rimusz` is from Deis

**Comment by elsonrodriguez** [comment]
Per @sparkprime, Consenting to have my contributions merged into the new repo.

**Comment by sparkprime** [comment]
Thanks, Elson.

**Comment by sparkprime** [comment]
I got explicit permission from Max Sills to merge symmetric & radamanthus's contributions, so that's good.  All we need now is a note of consent from w0mbat.

**Comment by jackgr** [comment]
Great work chasing this _all the way_ down, @sparkprime!!!

**Comment by wombat** [comment]
Consenting to have my contributions merged into the new repo.

**Comment by sparkprime** [comment]
Thanks @w0mbat, and thanks @runseb for doing all the heavy lifting here.  We are now good to merge!

**Pull request merged**
