### PR TITLE
Added svc type for prometheus.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes/charts/issues/1411

/cc @lachie83

### CODE REVIEW

**Comment by gyliu513** [comment]
@lachie83 ping for review

**Comment by lachie83** [comment]
LGTM. Just need a chart version bump.

**Comment by gyliu513** [comment]
@lachie83 rebased, can you check?

**Comment by gyliu513** [comment]
@lachie83 ping if we can have this merged, thanks!

**Pull request merged**
