### PR TITLE
[stable/anchore-engine] upgrade the postgresql subchart

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
Signed-off-by: Sébastien Prud'homme <sebastien.prudhomme@gmail.com>

#### What this PR does / why we need it:

Use the latest version of the postgresql chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by zhill** [comment]
@sebastien-prudhomme thanks for the PR, I'm a bit swamped now, but will get to this asap. This is something I was looking at doing anyway, so it's appreciated. The only complications I expect are upgrade implications from older versions of the chart due to the changes in the postgres credential key names. But, I'll do some testing and add my review.

**Comment by zhill** [comment]
@sebastien-prudhomme and update on my question for upgrade?

**Comment by sebastien-prudhomme** [comment]
@zhill no sorry, i close this PR as i have no more needs to use that chart

**Pull request closed without merging**
