### PR TITLE
[stable/prometheus] Added extraInitContainers to match server

### PR DESCRIPTION
**Pull request by cliedeman**
Signed-off-by: Ciaran Liedeman <ciaran@stackworx.io>

#### What this PR does / why we need it:

Allows users to add extra initContainers to alertmanager, pushGateway and nodeExporter. Written to match server

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by cliedeman** [comment]
@zanhsieh is anything else needed here?

**Comment by zanhsieh** [comment]
/lgtm
@cliedeman 
Sorry for late approval.

**Pull request merged**
