### PR TITLE
stable/fluent-bit: Add Merge_JSON_Log support

### LINKED ISSUE #2322: [stable/fluent-bit] Add support for Merge_JSON_Log option in Kubernetes filter
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Version of Helm and Kubernetes**:
Helm: 2.6
Kubernetes: 1.6

**Which chart**:
stable/fluent-bit

/cc @edsiper

### PR DESCRIPTION
**Pull request by nictuku**
Add the ability for fluent-bit to merge log entry content if it's also a JSON string map. 

The feature remains off by default.

Closes #2322

### CODE REVIEW

**Comment by unguiculus** [comment]
cc @kfox1111 @edsiper

**Comment by edsiper** [comment]
LGTM

**Pull request merged**
