### PR TITLE
[stable/lamp] fixed missing load mpm event module in apache conf

### PR DESCRIPTION
**Pull request by fnerdman**
due to [breaking changes in the httpd image](https://github.com/docker-library/httpd/commit/17166574dea6a8c574443fc3a06bdb5a8bc97743), the httpd.conf needs to be updated. 

Fixes #3548

### CODE REVIEW

**Comment by unguiculus** [comment]
Such things should not happen. The problem is that the chart uses latest versions. Please update it to use release versions.

**Comment by fnerdman** [comment]
@unguiculus The chart uses release versions for httpd. See [here](https://github.com/kubernetes/charts/blob/master/stable/lamp/templates/deployment.yaml#L365)

**Comment by unguiculus** [comment]
This image is not stable. Changes in this image probably caused the issue. You should switch to a concrete release, such as `httpd:2.4.29-alpine`.

**Comment by fnerdman** [comment]
@unguiculus I've changed the httpd version to your suggestion.

**Pull request merged**
