### PR TITLE
[stable/redis] namespace the template helpers with chart name ({{ define "fullname" }} --> {{ define "redis.fullname" }}

### PR DESCRIPTION
**Pull request by kevinschumacher**
Per https://docs.helm.sh/chart_best_practices/#names-of-defined-templates

### CODE REVIEW

**Comment by kevinschumacher** [comment]
FYI I would be happy to do this for other charts as well. Please let me know if that's something that I should take on.

**Comment by dhilipkumars** [comment]
@kevinschumacher  Thanks for the PR.

**Pull request merged**
