### PR TITLE
[stable/prometheus] extraSecretMounts support

### PR DESCRIPTION
**Pull request by adidenko**
In order to monitor services that require authentication (like TLS) we need a way to provide Prometheus server with credentials/secrets in a secure manner. Kubernetes Secrets seem like a suitable solution for this.

For example, monitoring of external Etcd cluster with TLS auth. In such case it would be handy to put all the TLS files into Kubernetes Secret and then mount them into Prometheus Server pod. Current alternative is distributing secrets on all the worker nodes and using hostPath mounts.

### CODE REVIEW

**Comment by adidenko** [comment]
I've signed individual CLA, this is what I see on the sign up page:
`View your signed Individual Contributor License Agreement for this project`

But when I click the link, the PDF is missing (404 File not Found).

**Comment by adidenko** [comment]
As for failed tests, `prometheus-server` Pod failed to initialize, PV/PVC seems to be in order. Without `kubectl describe pod` it's hard to understand what is the reason, but my patch should not affect pod initialization since with default values it does not change anything in the deployment chart. Checked again on my local env (rebased on master) - works fine with and without extraSecretMounts

**Comment by mattfarina** [comment]
@adidenko Adding a call to `kubectl describe pod` would be a good idea when we have a failure. I created #4278 to fetch this.

In the case of your PR, there were some issues the other day with CI that are now fixed. retesting was all that was needed.

**Pull request merged**
