### PR TITLE
[stable/anchore-engine] bump image versions to v0.7.3 & v2.3.2

### PR DESCRIPTION
**Pull request by Btodhunter**
Signed-off-by: Brady Todhunter <bradyt@anchore.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by zhill — APPROVED** [review]

**Comment by zhill** [comment]
@Btodhunter looks like an api version issue. See in the log:
```
6:51:29.667] 
I0708 06:51:29.667] 1 chart(s) linted, no failures
I0708 06:51:29.675] Installing chart 'anchore-engine => (version: "1.6.10", path: "stable/anchore-engine")'...
I0708 06:51:30.818] Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by davidkarlsen** [comment]
Could it be from the rather old postgresql dependency chart, as I find no references to Deployment extensions/v1beta1 directly in the anchore chart?

**Comment by zhill** [comment]
> @zhill @Btodhunter Could it be from the rather old postgresql dependency chart, as I find no references to Deployment extensions/v1beta1 directly in the anchore chart?

@davidkarlsen Yeah, that's almost certainly it. It looks like the testing cluster is now on 1.16 that is hitting this issue. We'd love to upgrade it's just been a very thorny issue for users trying to upgrade and I'd really prefer not to do that for a point-release update of the application.

**Comment by davidkarlsen** [comment]
> > @zhill @Btodhunter Could it be from the rather old postgresql dependency chart, as I find no references to Deployment extensions/v1beta1 directly in the anchore chart?
> 
> @davidkarlsen Yeah, that's almost certainly it. It looks like the testing cluster is now on 1.16 that is hitting this issue. We'd love to upgrade it's just been a very thorny issue for users trying to upgrade and I'd really prefer not to do that for a point-release update of the application.

Sure - I can understand that - on the other side the pg chart is very very old - (1.0.0) while the latest one is 8.6.4 (https://github.com/helm/charts/blob/master/stable/postgresql/Chart.yaml#L3) - actually now deprecated as it is moved to bitnami.

Maybe it's time for a 2.x chart and move it home to anchore as stable is about to shut down? I guess nothing much changed in the patch release of anchore and users can just bump their tag if needed?

**Comment by Btodhunter** [comment]
> Sure - I can understand that - on the other side the pg chart is very very old - (1.0.0) while the latest one is 8.6.4 (https://github.com/helm/charts/blob/master/stable/postgresql/Chart.yaml#L3) - actually now deprecated as it is moved to bitnami.
Maybe it's time for a 2.x chart and move it home to anchore as stable is about to shut down? I guess nothing much changed in the patch release of anchore and users can just bump their tag if needed?

@davidkarlsen we are actually working on a 2.x chart that we will host ourselves. That should be ready very soon. In the meantime we want customers to be able to easily upgrade their deployments using this stable chart. For an interim solution, we're going to vendor in the old postgresql chart and update the apiVersion to work with k8s v1.15+

**Comment by Btodhunter** [comment]
We're re-evaluating our strategy with the chart. Will submit a new PR when the time comes.

**Pull request closed without merging**
