### PR TITLE
[stable/gocd] Add agent.env.extraEnvVars

### PR DESCRIPTION
**Pull request by MPV**
**What this PR does / why we need it**:
Adding `agent.env.extraEnvVars` (we already have `server.env.extraEnvVars`).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by arvindsv — APPROVED** [review]

**Comment by arvindsv** [comment]
Need a minute to think about the `extraEnvVars` in values.yml. Other values there are namespaced (in a sense) as `goAgent...` or `agent...`.

**Comment by arvindsv** [comment]
@varshavaradarajan might know the reason for (not) namespacing that on the [server side](https://github.com/helm/charts/blob/34d9976f3088d74afe22acdf902eb7b56159e369/stable/gocd/templates/gocd-server-deployment.yaml#L58-L60) as well.

**Comment by varshavaradarajan** [comment]
@arvindsv - the extra env vars will be referenced in the chart as `agent.env.extraEnvVars`, So, this makes it pretty clear that these belong to the agent. Similar to `agent.replicaCount`. When you say other values are sort of namespaced, are you talking about the values in agent.env? If so, we used the same names provided in our docs (so as to not refer to the same thing differently in multiple places) - https://docs.gocd.org/current/advanced_usage/agent_auto_register.html. I think this PR is fine. Let me know what you think.

**Comment by arvindsv** [comment]
@varshavaradarajan Agreed.

**Comment by cpanato** [comment]
@MPV please rebase and fix the conflicts so we can merge it

**Comment by MPV** [comment]
@arvindsv @cpanato @varshavaradarajan It's now rebased, and version bumped again. Feel free to have another look. 👍

**Comment by MPV** [comment]
Thanks ❤️

**Pull request merged**
