### PR TITLE
RBAC support for heapster

### PR DESCRIPTION
**Pull request by outcoldman**
If `rbac.enabled` is set to `true` - bind default ClusterRole `system:heapster`.

### CODE REVIEW

**Comment by outcoldman** [comment]
signed

**Comment by outcoldman** [comment]
Actually this is probably not enough. Going to close it for now.

**Comment by jar349** [comment]
If you begin work on a follow-on, could you please post the issue id here so that others can follow progress?

**Comment by kachkaev** [comment]
I also could not run the chart on k8s v 1.7 due to some failure in RBAC rules. Current workaround (non-helm):

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
```

**Comment by kachkaev** [comment]
@outcoldman were you able to investigate what was wrong in your PR? It'd be amazing if you could submit a new one if all worked!

**Comment by outcoldman** [comment]
@kachkaev @jar349 sorry guys, I have decided to avoid using Helm and Charts. In a lot of cases I have found them not working with RBAC, and just a lot of them did not have some configurations I needed. 

But to be honest - I believe this PR should work. Don't remember why I have decided that it is probably no enough.

**Pull request closed without merging**
