### PR TITLE
[stable/odoo] Update Odoo dependencies

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 <juan@bitnami.com>

#### What this PR does / why we need it:

This PR updates Odoo so it uses the latest major version of PostgreSQL as dependency.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

### CODE REVIEW

**Comment by tompizmor** [comment]
@juan131 The lint is failing

**Comment by juan131** [comment]
@tompizmor I think it was an issue with the PostgreSQL 4.0.1 version not being public yet. It's passing the CI tests now

**Pull request merged**
