### PR TITLE
[stable/redis] Fix: Add metrics labels and annotations only when enabled

### PR DESCRIPTION
**Pull request by happiness9721**
No

#### What this PR does / why we need it:

Fix bugs when metrics is disabled but labels and annotations were still appended.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
Thank you very much for the PR!!!!

**Comment by happiness9721** [comment]
It looks like version conflict, I bumped to the properly one.

**Pull request merged**
