### PR TITLE
Typo error corrected for the metrics.image.registry parameter

### LINKED ISSUE #5825: Error when launching  a mariadb chart with metrics enabled
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.9.1 , kubernetes 1.10
**Which chart**: stable/mariadb
**What happened**: If you launch it with metrics enabled you get an parsing error
**What you expected to happen**: mariadb chart launched
**How to reproduce it** (as minimally and precisely as possible):
helm install stable/mariadb --set metrics.enabled=true

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rafariossaa**
**What this PR does / why we need it**: Fix a typo in mariadb chart

**Which issue this PR fixes**: fixes #5825

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tompizmor** [comment]
hi @rafariossaa, you also need to increase the chart version in the Chart.yaml file

**Comment by rafariossaa** [comment]
Hi @tompizmor , just from 4.2.0 to 4.2.1 or 4.2.0a or any other thing? 
I don't know if is there a document with instructions for changing the releases numbers, if you can point me to it that  would be great.

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you need to [sign the CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement), also you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

So in this case you should increase the PATCH version from `4.2.0` to `4.2.1`.

**Comment by carrodher** [comment]
Hi, can you follow these instructions in order to sign the CLA? https://github.com/kubernetes/charts/pull/5828#issuecomment-393125552

**Comment by rafariossaa** [comment]
@carrodher I signed the CLA, now it says that there is another problem but It is not specified.
How could I fix this ? or It is ok to merge the PR

**Comment by carrodher** [comment]
It seem that this commit fb24b0de50706f34bd01f1e37957ec22d1fd205f has not been made by the authorized user (rafariossaa).
screen shot 2018-06-04 at 10 41 56

Can you revert it and commit/push the changes using the proper user? It should fix the issue

**Pull request closed without merging**
