### PR TITLE
[stable/testlink] Add option to configure Apache ports

### PR DESCRIPTION
**Pull request by miguelaeh**
Signed-off-by: Miguel A. Cabrera Minagorri <macabrera@bitnami.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Comment by miguelaeh** [comment]
Waiting for the new image to be released before merging this PR.

**Comment by juan131** [comment]
@miguelaeh is this ready to be reviewed?

**Comment by miguelaeh** [comment]
No, forget about this PR, it doesn't add too much value and also we have reverted the latest commit in the image so this will not take effect.

**Pull request closed without merging**
