### PR TITLE
[stable/coredns] allow the server to specify a nodeport

### PR DESCRIPTION
**Pull request by rmb938**
#### What this PR does / why we need it:

allow the server to specify a nodeport

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by andor44** [comment]
Looks good, I like what you did with `toJson`! Any reason to do a `toString` on the node port? Why not keep it as a number? LGTM otherwise.

**Comment by rmb938** [comment]
I was just following the `port` variable above it, since it used `toString` I thought I would just follow that. I could get rid of the `toString` if you want.

**Comment by andor44** [comment]
Ah, consistency is a fair enough reason.

@shashidharatd could you /ok-to-test please?

**Comment by shashidharatd** [comment]
@andor44, probably you too can do /ok-to-test as you are also the maintainer of this chart :)

**Pull request closed without merging**
