### PR TITLE
[stable/kibana] replace elastcisearch.url with elasticsearch.hosts

### LINKED ISSUE #12378: [stable/kibana] elasticsearch.url is deprecated
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/helm/charts/blob/90bcd1a5ef30b87dafe543726f8fdaaf0fe6cf84/stable/kibana/values.yaml#L24
https://github.com/elastic/kibana-docker/commit/5c9c6d18146932c42a1203f5b42d4daf49a6616e
https://github.com/elastic/kibana/pull/21928

**Anything else we need to know**:
Renaming it to elasticsearch.hosts is sufficient, converting to an array is optional.  Maybe related to https://github.com/helm/charts/issues/12199 and https://github.com/helm/charts/pull/12200

### PR DESCRIPTION
**Pull request by naseemkullah**
#### What this PR does / why we need it:
More recent versions of kibana complay about using `elasticsearch.url`, it appears that `elasticsearch.hosts` is the new name of this setting.

https://www.elastic.co/guide/en/kibana/7.0/docker.html#docker-defaults

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #12378

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by naseemkullah** [comment]
cc @compleatang @monotek

**Comment by desaintmartin** [comment]
This is a breaking change and should have been advertised as such.

**Comment by naseemkullah** [comment]
> This is a breaking change and should have been advertised as such.

Thanks for pointing that out @desaintmartin , https://github.com/helm/charts/pull/13720 created

**Pull request merged**
