### PR TITLE
fix wrong labelselector syntax, fixes #12134

### LINKED ISSUE #12134: [stable/traefik] kubernetes labeselector syntax wrong
**BUG REPORT**:

**Version of Helm and Kubernetes**:
1.12, 2.13

**Which chart**:
stable/traefik

**What happened**:
This is writen in the config, if you set a labelselector
```
[kubernetes]
labelselector = "map[foo:bar]"
```

**What you expected to happen**:
Correct syntax is:
```
[kubernetes]
labelselector = "foo=bar"
```
**How to reproduce it** (as minimally and precisely as possible):
set a labelselector

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
#### What this PR does / why we need it:
See #12134 

#### Which issue this PR fixes
  - fixes #12134
Maintainers:

@krancour 
@emilevauge 
@dtomcej 
@ldez

### CODE REVIEW

**Comment by ldez** [comment]
https://github.com/helm/charts/pull/12138/checks?check_run_id=77953383

**Comment by dtomcej** [comment]
@SimonHoenscheid Reviewing this PR, it appears that you are wanting to use a map instead of a string for labelselector.

Can you elaborate why the string does not work?

**Comment by SimonHoenscheid** [comment]
@dtomcej it works with the string

**Pull request closed without merging**
