### PR TITLE
[stable/prometheus] Use volumeMount subPath to fix prometheus-server from crashing

### PR DESCRIPTION
**Pull request by ravishivt**
This is a similar fix to #416.  It uses the `subPath` feature on the server's `storage-volume`.  Without this fix and using glusterfs backed volumes, the `prometheus-server` pod will crash loop with the below errors.  This happens because glusterfs volumes have hidden `.glusterfs` and `.trashcan` directories that get automatically added to the volume root.

Note that `prometheus-operator` uses the [same subPath solution](https://github.com/coreos/prometheus-operator/pull/30).

```
$ kubectl logs rprometheus-server-2529951580-kj2cq prometheus-server
time="2017-01-18T01:11:21Z" level=info msg="Starting prometheus (version=1.4.1, branch=master, revision=2a89e8733f240d3cd57a6520b52c36ac4744ce12)" source="main.go:77"
time="2017-01-18T01:11:21Z" level=info msg="Build context (go=go1.7.3, user=root@e685d23d8809, date=20161128-09:59:22)" source="main.go:78"
time="2017-01-18T01:11:21Z" level=info msg="Loading configuration file /etc/config/prometheus.yml" source="main.go:250"
time="2017-01-18T01:11:21Z" level=error msg="Error opening memory series storage: could not detect storage version on disk, assuming version 0, need version 1 - please wipe storage or run a version of Prometheus compatible with storage version 0" source="main.go:184"
```

### CODE REVIEW

**Comment by viglesiasce** [comment]
cc @mgoodness 

@ravishivt i think we should do this the same was as the postgres chart. Namely, make the subpath configurable. Will leave further comment to @mgoodness

**Comment by mgoodness** [comment]
I agree with Vic; make this `.Values.server.storageSubPath` with a default of `""` for reverse-compatibility. Guessing the `--storage-path` arg also needs to account for the (possible) additional path depth.

Should the same changes be made for alertmanager?

**Comment by ravishivt** [comment]
OK, the latest changes are similar to what was done in postgresql chart but not the same.  The main difference is that `persistence.subPath` defaults to `""` for reverse-compatibility.  Therefore, only a patch version update is needed.

@mgoodness Although alertmanager runs OK without the subPath, I added it since `prometheus-operator` does as well.  Also, the `--storage-path` doesn't need to change because the path in the container remains the same.  Only the storage of that path on the volume changes.

**Comment by mgoodness** [comment]
LGTM!

**Comment by viglesiasce** [comment]
@k8s-bot ok to test

**Pull request merged**
