### PR TITLE
[stable/jenkins] Add role kind option

### PR DESCRIPTION
**Pull request by Uvedale**
#### What this PR does / why we need it:
Enables restricting Jenkins permissions to a namespace. The RoleBindingKind was previously configurable but not the RoleKind. This makes the RoleKind configurable.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by Uvedale** [comment]
I've fixed the merge conflict @cpanato

**Comment by Uvedale** [comment]
@lachie83 could we get this through?

**Comment by cpanato** [comment]
@Uvedale can you rebase and resolve the conflict? then we can merge it

**Comment by cpanato** [comment]
@davidkarlsen can you look this one as well? thanks!

**Comment by lachie83** [comment]
@cpanato can you please rebase and we can get this merged?

**Comment by maorfr** [comment]
since everyone seems to be on the same page here, I'll help!
@Uvedale, one last time, resolve conflicts and i'll lgtm this ;)

**Comment by Uvedale** [comment]
@maorfr I've resolved the conflict

**Pull request merged**
