### PR TITLE
added additional ports option for prometheus-operator prometheus service

### PR DESCRIPTION
**Pull request by nicholasgibson2**
Signed-off-by: GIBSON, NICHOLAS R <ng560p@us.att.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by vsliouniaev** [comment]
@nicholasgibson2 
- Charts are atomic - you must bump the chart version for every change, otherwise the linter will fail
- You need to add information about the additional configuration options to the readme file
- You should provide an example of the configuration in the values file
- Since this chart has a `ci/` folder that is used to run tests, you should add the changes to that file as well
- The indentation on your configuration does not look correct, I think it should be 4 instead of 2?
- I think your `additionalPorts` configuration may need to be an `[]` instead of `{}` since it is an array of data
- Can you please let me know if these changes have been fully tested - the CI tests in this repository are set up to be cursory at best

**Comment by nicholasgibson2** [comment]
@vsliouniaev Thanks for the feedback, updated with requested changes. It works with the example values I deployed but I still need to test the default value type (I think you're right that it needs to be an array). Our test environment is unavailable right now so I'll get back to you once I'm able to test this.

**Comment by vsliouniaev** [comment]
Thanks a lot, looks like this should work.
It may take some time to merge due to the requirements in this project and the chart version may need to get bumped a few times. I'll ping you if that's the case

**Comment by vsliouniaev** [comment]
@nicholasgibson2 could you bump the chart version please?
@gianrubio could you add an ok to test?

**Comment by nicholasgibson2** [comment]
@vsliouniaev I bumped the version to 3.0.1. I tested using the default [] value and with actual values and everything is working.

**Comment by vsliouniaev** [comment]
Pretty sure the entire CI is now broken due to a docker upgrade on the host.

**Comment by vsliouniaev** [comment]
@gianrubio could you add an ok-to-test on this one please?

**Pull request merged**
