### PR TITLE
[stable/cluster-autoscaler] Fix tags and make them overridable

### PR DESCRIPTION
**Pull request by yurrriq**
## What this PR does / why we need it:
Fix the typo I introduced in #15812, and make the tags overridable per discussion.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

### CODE REVIEW

**Comment by yurrriq** [comment]
What do you think, @wjrogers?

**Comment by wjrogers** [comment]
Looks good to me. Thanks!

**Comment by yurrriq** [comment]
@maorfr, am I correct in thinking someone other than me needs to `/lgtm` this for it to me mergeable? Thanks for being my mentor as I learn the ropes. :smile:

**Comment by maorfr** [comment]
/lgtm

You are correct and welcome! Thank you both for being involved!

**Pull request merged**
