### PR TITLE
[stable/unifi] Fix typos/formatting in README.

### PR DESCRIPTION
**Pull request by jessestuart**
### What does this PR do?
- Fixes typo: `Ubiqiti` => `Ubiquiti`
- Consistent terminal punctuation.
- 80 column line breaks.
- Converts links to "reference" MD links as generated by [Gruber's](https://gist.github.com/gruber/1207378) script.
- Cleans up table formatting.

### CODE REVIEW

**Review by billimek — COMMENTED** [review]
/lgtm

**Comment by jessestuart** [comment]
Thanks @billimek! 👍

**Pull request merged**
