### PR TITLE
[incubator/docker-registry] #1785 namespace defined templates with ch…

### PR DESCRIPTION
**Pull request by kevinschumacher**
…art name

 #1785

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@kevinschumacher Why are we incrementing minor version? should we not simply go with patch level increament? 
IIRC you were only doing patch increment for your previous set of PRs?

**Comment by kevinschumacher** [comment]
@dhilipkumars 

> @kevinschumacher Why are we incrementing minor version? should we not simply go with patch level increament?

IMO we are changing the chart's API by changing the names of defined template functions. 

I am now incrementing major version when major version > 0, else incrementing minor version.

**Pull request merged**
