### PR TITLE
[stable/mongodb-replicaset] log bootstrap container messages

### PR DESCRIPTION
**Pull request by andrenarchy**
**What this PR does / why we need it**:
The bootstrap container logged its messages to a file in a temporary directory. This makes debugging very hard in case something goes wrong. This PR lets the bootstrap container log to stdout (analogous to the actual non-init container).

ping @foxish @unguiculus

### CODE REVIEW

**Comment by steven-sheehy** [comment]
Why not keep the old behavior and just tee the output to stdout as well?

**Comment by andrenarchy** [comment]
@steven-sheehy does logging log output to a (temporary) disk give any benefits? I wonder why this was done in the first place, so maybe I overlooked something. It just seems like a non-docker way of logging to me.

**Comment by floriantraber** [comment]
see https://github.com/helm/charts/issues/6830

**Comment by andrenarchy** [comment]
@floriantraber Thank you for the link!

So the problem is that `peer-finder` swallows the output of the script, right? If so, does anyone know if this is on purpose?

**Comment by steven-sheehy** [comment]
Looks like this was addressed in peer-finder via a [PR](https://github.com/kubernetes/contrib/pull/2866)? Can you confirm this logs to stdout now with your changes?

**Comment by andrenarchy** [comment]
@steven-sheehy thanks for the link! The PR did not get merged though and it looks like there hasn't been a follow-up PR to solve the issue yet.

**Comment by andrenarchy** [comment]
I created https://github.com/kubernetes/contrib/issues/2944 and looped in the author of the PR, maybe she figured out how to solve it in the meantime. :)

**Pull request closed without merging**
