### PR TITLE
[stable/jenkins] Add networkPolicy podLabels

### PR DESCRIPTION
**Pull request by olblak**
#### Is this a new chart
/

#### What this PR does / why we need it:
This pull request allows to customized network policy pod labels on top of the default 
`"jenkins/{{ .Release.Name }}-{{ .Values.agent.componentName }}": "true"`

#### Which issue this PR fixes
/

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

### CODE REVIEW

**Review by wmcdona89 — CHANGES_REQUESTED** [review]
@olblak thanks for the PR! the changes lgtm. please also update the CHANGELOG.

**Comment by wmcdona89** [comment]
@olblak looks like the issue with the test runner is resolved. please sign your latest commit.

**Comment by scottrigby** [comment]
Merge master to fix conflicts and retest. CI infra should now be fixed

**Comment by olblak** [comment]
> Merge master to fix conflicts and retest. CI infra should now be fixed

Done, I updated the chart version 2.2.0

**Comment by olblak** [comment]
It seems that I am missing lgtm label

**Review by torstenwalter — COMMENTED** [review]
/ok-to-test

**Comment by torstenwalter** [comment]
@olblak Sorry I missed to say lgtm. Can you fix the conflict? I promise to check faster this time.

**Comment by olblak** [comment]
@torstenwalter done

**Comment by torstenwalter** [comment]
@olblak Thank you for the PR and the patience in getting it in.

**Pull request merged**
