### PR TITLE
[stable/jenkins] Fix indentation in config.yaml

### PR DESCRIPTION
**Pull request by cesaralbloz**
Signed-off-by: Cesar Alba Lozano <cesaralbloz@gmail.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

Jenkins chart installation is broken when a values file is passed to helm install operation. 

You see the following kind of errors:

Error: YAML parse error on jenkins/templates/config.yaml: error converting YAML to JSON: yaml: line 31

### CODE REVIEW

**Comment by wmcdona89** [comment]
@cesaralbloz thanks for fixing the bug!

please rebase...bumping the version and updating the CHANGELOG

**Comment by torstenwalter** [comment]
@cesaralbloz Of course @wmcdona89 was right, you need to increase the chart version.

**Comment by torstenwalter** [comment]
Can you add the following to `stable/jenkins/ci/other-values.yaml`?

```
master:
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
```

that ensures that we don not break it again ;-)

**Comment by torstenwalter** [comment]
@cesaralbloz I needed to create another PR and included you fix in there #23175.

thank you very much for your contribution. This really helps the community.

**Pull request closed without merging**
