### PR TITLE
docs(*): update READMEs to reference chart repos

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
Fixed the consul issue in #120.

**Comment by prydonius** [comment]
Heh, now it's etcd

**Comment by fejta** [comment]
@k8s-bot e2e test this

**Comment by prydonius** [comment]
Think I've caught the rest in #121. Looks like there's something wrong with the latest e2e test, it shouldn't have passed.

**Comment by prydonius** [comment]
@k8s-bot e2e test this

**Comment by fejta** [comment]
One sec

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/865 to fix the test issue

**Comment by fejta** [comment]
@k8s-bot e2e test this

**Comment by fejta** [comment]
@k8s-bot e2e test this

**Comment by viglesiasce** [comment]
Thanks so much @prydonius and @fejta!!!

**Pull request merged**
