### PR TITLE
liveness/readiness probe tweaks

### PR DESCRIPTION
**Pull request by rdkls**
- indent out to correct level
- make more tolerant (can take a while for HA to start ...)
@billimek 

#### What this PR does / why we need it:
fix to indenting
tweak probes to handle slower container startups

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
Nice contribution @rdkl!  I also noticed issues with the readiness & liveness; thank you.

**Comment by rdkls** [comment]
thanks for your own work Jeff @billimek !

**Pull request merged**
