### PR TITLE
[stable/prometheus] Adding rbac support for endpoints,persistentvolumes, and hpas for kube-state-metrcs v1.2.0

### PR DESCRIPTION
**Pull request by jhyelton**
kube-state-metrics v1.2.0 added support for some new objects, including HPA and Endpoints.  This PR adds the necessary permissions to the ClusterRole in order for it to expose metrics about those objects.

### CODE REVIEW

**Comment by foxish** [comment]
/ok-to-test

cc/ @thuandt can you review this change?

**Comment by jhyelton** [comment]
@foxish is there anyone else that can review and merge this?

**Comment by foxish** [comment]
@mgoodness, can you PTAL?
Question - it looks like values.yaml is [installing v1.1.0](https://github.com/kubernetes/charts/blob/master/stable/kube-state-metrics/values.yaml#L5). Shouldn't you be bumping that up also?

**Comment by foxish** [comment]
It doesn't seem like it's using v1.2.0 yet. 
See https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L194.

Shouldn't that be changed?

**Comment by jhyelton** [comment]
I wasn't sure about changing the default initially, I just wanted to add support for all the resources being watched in 1.2.0.  I've updated the default image to 1.2.0.

**Comment by jhyelton** [comment]
@foxish @mgoodness is there anything else you would like to see in this PR to get it merged?

**Comment by unguiculus** [comment]
Seems this has been superseded by #3572.

**Pull request closed without merging**
