### PR TITLE
[stable/kibana]bump kibana to 6.7.0

### PR DESCRIPTION
**Pull request by cpanato**
#### What this PR does / why we need it:
Bump kibana to 6.7.0

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by compleatang** [comment]
@cpanato my preference is to get #12200 in which does the version bump but also fixes a small deprecation (and is a new contributor to the chart :smile: ).

**Comment by cpanato** [comment]
@compleatang sounds good to me, will close this :)

**Pull request closed without merging**
